import fs from "node:fs";import os from "node:os";import path from "node:path";import net from "node:net";import{spawn,execFileSync}from"node:child_process";
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function commandPath(c){try{const t=process.platform==="win32"?"where":"which";return execFileSync(t,[c],{encoding:"utf8",stdio:["ignore","pipe","ignore"]}).split(/\r?\n/).map(x=>x.trim()).find(Boolean)||null}catch{return null}}
export function findBrowser(){const c=[process.env.CHROME_PATH,process.env.EDGE_PATH,process.env.LOCALAPPDATA&&path.join(process.env.LOCALAPPDATA,"Google/Chrome/Application/chrome.exe"),process.env.LOCALAPPDATA&&path.join(process.env.LOCALAPPDATA,"Microsoft/Edge/Application/msedge.exe"),process.env.PROGRAMFILES&&path.join(process.env.PROGRAMFILES,"Google/Chrome/Application/chrome.exe"),process.env["PROGRAMFILES(X86)"]&&path.join(process.env["PROGRAMFILES(X86)"],"Microsoft/Edge/Application/msedge.exe"),"/usr/bin/google-chrome","/usr/bin/chromium","/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",commandPath("chrome"),commandPath("google-chrome"),commandPath("chromium"),commandPath("msedge")].filter(Boolean);const f=c.find(x=>fs.existsSync(x));if(!f)throw new Error("No Chrome/Edge found; set CHROME_PATH or EDGE_PATH");return f}
async function freePort(){return new Promise((resolve,reject)=>{const s=net.createServer();s.once("error",reject);s.listen(0,"127.0.0.1",()=>{const{port}=s.address();s.close(()=>resolve(port))})})}
async function waitJson(url,timeout=15000){const start=Date.now();while(Date.now()-start<timeout){try{const r=await fetch(url);if(r.ok)return r.json()}catch{}await delay(100)}throw new Error(`Timed out: ${url}`)}
class Session{constructor(ws){this.i=1;this.p=new Map();this.l=new Map();this.ws=new WebSocket(ws)}async open(){await new Promise((r,j)=>{const t=setTimeout(()=>j(new Error("CDP open timeout")),10000);this.ws.addEventListener("open",()=>{clearTimeout(t);r()},{once:true});this.ws.addEventListener("error",e=>{clearTimeout(t);j(new Error(e.message||"CDP error"))},{once:true})});this.ws.addEventListener("message",e=>{const m=JSON.parse(String(e.data));if(m.id){const p=this.p.get(m.id);if(!p)return;this.p.delete(m.id);m.error?p.j(new Error(m.error.message)):p.r(m.result||{})}else if(m.method)for(const h of this.l.get(m.method)||[])h(m.params||{})});return this}send(method,params={}){const id=this.i++;return new Promise((r,j)=>{this.p.set(id,{r,j});this.ws.send(JSON.stringify({id,method,params}))})}on(m,h){const a=this.l.get(m)||[];a.push(h);this.l.set(m,a)}waitFor(m,t=15000){return new Promise((r,j)=>{const x=setTimeout(()=>j(new Error(`Timed out ${m}`)),t);const h=p=>{clearTimeout(x);this.l.set(m,(this.l.get(m)||[]).filter(v=>v!==h));r(p)};this.on(m,h)})}async evaluate(e){const x=await this.send("Runtime.evaluate",{expression:e,awaitPromise:true,returnByValue:true,userGesture:true});if(x.exceptionDetails)throw new Error(x.exceptionDetails.exception?.description||x.exceptionDetails.text);return x.result?.value}close(){try{this.ws.close()}catch{}}}
export async function launchBrowser(){const executable=findBrowser(),port=await freePort(),dir=fs.mkdtempSync(path.join(os.tmpdir(),"math-v2-prod-package-"));const child=spawn(executable,[`--remote-debugging-port=${port}`,`--user-data-dir=${dir}`,"--headless=new","--no-first-run","--disable-background-networking","--disable-extensions","--disable-gpu","--no-proxy-server","--proxy-bypass-list=*","--no-sandbox","about:blank"],{stdio:["ignore","ignore","pipe"]});const v=await waitJson(`http://127.0.0.1:${port}/json/version`);return{executable,browserVersion:v.Browser||"unknown",async newPage(url="about:blank"){const r=await fetch(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(url)}`,{method:"PUT"});const j=await r.json();return new Session(j.webSocketDebuggerUrl).open()},async close(){try{child.kill("SIGTERM")}catch{}await delay(250);try{fs.rmSync(dir,{recursive:true,force:true})}catch{}}}}
export async function waitUntil(s,e,t=90000){const start=Date.now();let last;while(Date.now()-start<t){last=await s.evaluate(e);if(last)return last;await delay(100)}throw new Error(`waitUntil failed: ${e}; last=${JSON.stringify(last)}`)}
