export const BIOLOGY_SKILL_PLAN = Object.freeze({
  schemaVersion: "cap8-r4-subject-skill-plan-v1",
  subject: "biology",
  expectedSkills: 220,
  expectedAuthorityNodes: 80,
  families: [
    {
      key: "SCIENTIFIC_OBSERVATION_EVIDENCE",
      title: "Scientific observation, variables and evidence",
      authorityCodes: ["ah-Ⅳ-1", "ah-Ⅳ-2", "ai-Ⅳ-1", "ai-Ⅳ-2", "ai-Ⅳ-3", "an-Ⅳ-1", "an-Ⅳ-2", "an-Ⅳ-3", "po-Ⅳ-1", "po-Ⅳ-2", "pe-Ⅳ-1", "pe-Ⅳ-2", "pa-Ⅳ-1", "pa-Ⅳ-2", "pc-Ⅳ-1", "pc-Ⅳ-2", "tc-Ⅳ-1", "ti-Ⅳ-1", "tm-Ⅳ-1", "tr-Ⅳ-1", "Mb-Ⅳ-2"],
      prerequisiteFamilyKeys: [],
      skills: [
        "區分客觀觀察與主觀推論",
        "把生物現象轉成可檢驗的問題",
        "辨認自變項應變項與控制變因",
        "設計對照組與重複測量",
        "依器材精度記錄質性與定量資料",
        "用表格與圖形整理觀察結果",
        "判斷數據是否支持原先假說",
        "檢查科學報導的證據來源與限制",
      ],
    },
    {
      key: "MICROSCOPES_SCALE_DRAWING",
      title: "Microscopes, scale and biological drawing",
      authorityCodes: ["Da-Ⅳ-1", "INc-Ⅳ-1", "INc-Ⅳ-2", "INc-Ⅳ-3", "INc-Ⅳ-4", "INc-Ⅳ-5", "pe-Ⅳ-2", "pc-Ⅳ-2"],
      prerequisiteFamilyKeys: ["SCIENTIFIC_OBSERVATION_EVIDENCE"],
      skills: [
        "辨識複式顯微鏡主要構造與功能",
        "依步驟安全取放與調整顯微鏡",
        "由低倍開始尋找並置中標本",
        "比較物鏡倍率與視野大小亮度",
        "由視野移動判斷玻片調整方向",
        "計算總放大倍率並理解其限制",
        "依比例尺估算細胞大小",
        "繪製具標題比例與標示的生物圖",
      ],
    },
    {
      key: "CELL_THEORY_STRUCTURES",
      title: "Cell theory and cell structures",
      authorityCodes: ["Da-Ⅳ-1", "Da-Ⅳ-2", "Fc-Ⅳ-2", "INc-Ⅳ-5", "tm-Ⅳ-1"],
      prerequisiteFamilyKeys: ["MICROSCOPES_SCALE_DRAWING"],
      skills: [
        "說明細胞是生物體基本構造與功能單位",
        "辨識細胞膜細胞質與細胞核",
        "辨識植物細胞的細胞壁與葉綠體",
        "比較典型動物細胞與植物細胞",
        "由構造位置判斷細胞模型方向",
        "連結細胞構造與基本功能",
        "區分顯微觀察結果與模式圖",
        "評估細胞模型簡化內容與限制",
      ],
    },
    {
      key: "MEMBRANE_TRANSPORT_HOMEOSTASIS",
      title: "Cell membrane transport and homeostasis",
      authorityCodes: ["Da-Ⅳ-1", "Dc-Ⅳ-4", "Dc-Ⅳ-5", "INc-Ⅳ-5", "pe-Ⅳ-1", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["CELL_THEORY_STRUCTURES"],
      skills: [
        "說明細胞膜控制物質進出的功能",
        "由濃度差判斷擴散的淨移動方向",
        "由水分移動判斷滲透現象",
        "比較植物細胞在不同溶液中的變化",
        "區分物質移動與細胞主動反應",
        "由實驗控制溶液濃度與時間",
        "用質量或長度資料判斷水分進出",
        "連結細胞物質交換與內部恆定",
      ],
    },
    {
      key: "LEVELS_ORGANIZATION",
      title: "Levels of organization",
      authorityCodes: ["Da-Ⅳ-2", "Da-Ⅳ-3", "Fc-Ⅳ-1", "Fc-Ⅳ-2", "INc-Ⅳ-4", "INc-Ⅳ-5", "INc-Ⅳ-6"],
      prerequisiteFamilyKeys: ["MEMBRANE_TRANSPORT_HOMEOSTASIS"],
      skills: [
        "依微觀到巨觀排列生命組成層次",
        "區分細胞組織器官與器官系統",
        "由細胞形態推論可能的專門功能",
        "由組織協作解釋器官功能",
        "區分個體族群群集與生態系",
        "連結分子細胞與個體尺度",
        "用比例表示不同生命尺度關係",
        "避免把組成層次與分類階層混淆",
      ],
    },
    {
      key: "NUTRITION_ENZYMES",
      title: "Nutrition and enzymes",
      authorityCodes: ["Bc-Ⅳ-1", "Bc-Ⅳ-2", "Db-Ⅳ-1", "Fc-Ⅳ-2", "pe-Ⅳ-1", "pa-Ⅳ-2"],
      prerequisiteFamilyKeys: ["LEVELS_ORGANIZATION"],
      skills: [
        "辨識醣類蛋白質脂質的主要功能",
        "說明維生素礦物質與水的基本角色",
        "區分養分與食物的概念",
        "說明酵素催化與專一性的基本概念",
        "由溫度變化資料判斷酵素作用",
        "由酸鹼與濃度資料判斷酵素速率",
        "設計單一變因的酵素探究",
        "區分酵素加快速率與提供能量",
      ],
    },
    {
      key: "HUMAN_DIGESTIVE_SYSTEM",
      title: "Human digestive system",
      authorityCodes: ["Db-Ⅳ-1", "Bc-Ⅳ-1", "Fc-Ⅳ-2", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["NUTRITION_ENZYMES"],
      skills: [
        "依序辨識人體消化道主要器官",
        "區分物理性消化與化學性消化",
        "連結消化液酵素與養分分解",
        "說明小腸構造適合吸收的特徵",
        "區分消化吸收與排遺",
        "追蹤養分由食物進入循環的路徑",
        "由器官功能判斷消化異常影響",
        "用均衡飲食概念分析生活情境",
      ],
    },
    {
      key: "RESPIRATION_GAS_EXCHANGE",
      title: "Respiration and gas exchange",
      authorityCodes: ["Bc-Ⅳ-2", "Db-Ⅳ-3", "Dc-Ⅳ-4", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["HUMAN_DIGESTIVE_SYSTEM"],
      skills: [
        "依序辨識人體呼吸道主要構造",
        "說明肺泡適合氣體交換的特徵",
        "由濃度差判斷氧與二氧化碳移動",
        "區分呼吸運動氣體交換與細胞呼吸",
        "說明細胞呼吸由養分釋放能量",
        "比較吸入氣與呼出氣成分差異",
        "由運動前後數據解釋呼吸變化",
        "連結呼吸循環與細胞能量需求",
      ],
    },
    {
      key: "CIRCULATION_IMMUNITY",
      title: "Circulation and immunity basics",
      authorityCodes: ["Db-Ⅳ-2", "Dc-Ⅳ-3", "Dc-Ⅳ-4", "Gc-Ⅳ-3", "pe-Ⅳ-2", "pa-Ⅳ-1"],
      prerequisiteFamilyKeys: ["RESPIRATION_GAS_EXCHANGE"],
      skills: [
        "辨識心臟血管與血液的基本功能",
        "依方向追蹤體循環與肺循環路徑",
        "比較動脈靜脈與微血管特徵",
        "由心跳脈搏資料理解循環運作",
        "說明皮膚與黏膜的第一道防禦",
        "說明淋巴系統參與免疫作用",
        "區分有益共生與可能致病微生物",
        "避免把所有微生物視為病原",
      ],
    },
    {
      key: "EXCRETION_INTERNAL_BALANCE",
      title: "Excretion and internal balance",
      authorityCodes: ["Dc-Ⅳ-2", "Dc-Ⅳ-4", "Dc-Ⅳ-5", "Db-Ⅳ-2", "Db-Ⅳ-3", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["CIRCULATION_IMMUNITY"],
      skills: [
        "區分排泄與排遺",
        "辨識腎臟皮膚與肺排出物質的角色",
        "說明循環系統運送代謝廢物",
        "由水分攝取與流失理解平衡",
        "由體溫調節情境分析出汗與血流變化",
        "連結神經內分泌與器官系統協調",
        "由數據判斷體內狀態維持一定範圍",
        "避免把恆定誤解為數值完全不變",
      ],
    },
    {
      key: "NERVOUS_SYSTEM_SENSES",
      title: "Nervous system and senses",
      authorityCodes: ["Dc-Ⅳ-1", "Dc-Ⅳ-4", "Dc-Ⅳ-5", "Db-Ⅳ-5", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["EXCRETION_INTERNAL_BALANCE"],
      skills: [
        "辨識中樞與周圍神經系統基本功能",
        "依序追蹤刺激感受傳導與反應",
        "區分反射作用與意識控制反應",
        "由眼耳等感覺構造理解刺激接收",
        "比較感覺訊息與大腦形成的知覺",
        "分析反應時間實驗的變因與誤差",
        "連結神經調節與維持內部恆定",
      ],
    },
    {
      key: "ENDOCRINE_REGULATION",
      title: "Endocrine regulation",
      authorityCodes: ["Dc-Ⅳ-2", "Dc-Ⅳ-4", "Db-Ⅳ-4", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["NERVOUS_SYSTEM_SENSES"],
      skills: [
        "說明內分泌腺分泌激素進入循環",
        "辨識激素作用於特定目標的概念",
        "比較神經調節與激素調節速度",
        "由血糖調節情境理解負回饋",
        "連結生長代謝與生殖的激素調節",
        "由過多或不足推論平衡受到的影響",
        "避免把激素視為只在單一器官作用",
      ],
    },
    {
      key: "MOVEMENT_COORDINATION",
      title: "Movement and musculoskeletal coordination",
      authorityCodes: ["Dc-Ⅳ-1", "Dc-Ⅳ-4", "Db-Ⅳ-5", "Mc-Ⅳ-2", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["ENDOCRINE_REGULATION"],
      skills: [
        "說明骨骼支撐保護與運動功能",
        "辨識關節提供活動的位置",
        "解釋肌肉收縮拉動骨骼產生動作",
        "比較成對肌肉交替作用",
        "連結神經訊號感覺與動作協調",
        "由姿勢負荷情境判斷運動系統需求",
        "由仿生例子分析構造功能的應用",
      ],
    },
    {
      key: "ASEXUAL_SEXUAL_REPRODUCTION",
      title: "Asexual and sexual reproduction",
      authorityCodes: ["Ga-Ⅳ-1", "Da-Ⅳ-4", "Db-Ⅳ-4", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["MOVEMENT_COORDINATION"],
      skills: [
        "區分無性生殖與有性生殖",
        "比較兩種生殖的親本配子與子代差異",
        "辨識分裂出芽斷裂與營養繁殖例子",
        "說明有性生殖需配子結合",
        "連結細胞分裂與生長修補生殖",
        "由環境變化比較兩種生殖利弊",
        "避免把個體數增加都視為生殖",
      ],
    },
    {
      key: "PLANT_REPRODUCTION_DEVELOPMENT",
      title: "Plant reproduction and development",
      authorityCodes: ["Db-Ⅳ-7", "Ga-Ⅳ-1", "Db-Ⅳ-6", "Bc-Ⅳ-3", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["ASEXUAL_SEXUAL_REPRODUCTION"],
      skills: [
        "辨識花萼花瓣雄蕊與雌蕊",
        "說明花藥花粉胚珠與配子的關係",
        "區分傳粉與受精",
        "追蹤受精後種子與果實形成",
        "由種子構造判斷萌發所需條件",
        "比較風媒與蟲媒花的適應特徵",
        "連結營養繁殖與作物繁殖方式",
      ],
    },
    {
      key: "HUMAN_REPRODUCTION_DEVELOPMENT",
      title: "Human reproduction and development",
      authorityCodes: ["Db-Ⅳ-4", "Ga-Ⅳ-1", "Ga-Ⅳ-2", "Dc-Ⅳ-2", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["PLANT_REPRODUCTION_DEVELOPMENT"],
      skills: [
        "辨識男性與女性生殖系統基本功能",
        "說明精子卵與受精的關係",
        "追蹤受精卵著床與胚胎發育概念",
        "連結青春期變化與激素調節",
        "理解性染色體主要影響人類性別",
        "說明性染色體來自親代配子的組合",
        "以科學資訊尊重個體發展差異",
      ],
    },
    {
      key: "GENES_CHROMOSOMES_DNA",
      title: "Genes, chromosomes and DNA concepts",
      authorityCodes: ["Da-Ⅳ-4", "Ga-Ⅳ-2", "Ga-Ⅳ-3", "Ga-Ⅳ-4", "Fc-Ⅳ-2", "INc-Ⅳ-5", "tm-Ⅳ-1"],
      prerequisiteFamilyKeys: ["HUMAN_REPRODUCTION_DEVELOPMENT"],
      skills: [
        "依細胞核染色體與遺傳物質建立層次",
        "說明基因影響可遺傳性狀的概念",
        "比較同種生物染色體與個體性狀",
        "由細胞分裂圖判斷染色體變化",
        "辨識性染色體與體染色體概念",
        "區分基因型表現型與環境影響",
        "評估遺傳模型的簡化與限制",
      ],
    },
    {
      key: "MENDELIAN_PEDIGREES",
      title: "Mendelian inheritance and pedigrees",
      authorityCodes: ["Ga-Ⅳ-3", "Ga-Ⅳ-6", "Ga-Ⅳ-2", "pa-Ⅳ-1", "pa-Ⅳ-2", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["GENES_CHROMOSOMES_DNA"],
      skills: [
        "由孟德爾實驗辨識控制變因與結果",
        "區分顯性與隱性性狀的表現",
        "用符號表示成對遺傳因子",
        "由親代組合推論子代可能性",
        "讀取家系圖中的親屬與性狀資訊",
        "由家系資料排除不可能的遺傳組合",
        "用ABO血型情境理解多種遺傳因子",
      ],
    },
    {
      key: "VARIATION_MUTATION_BIOTECH",
      title: "Variation, mutation and biotechnology",
      authorityCodes: ["Ga-Ⅳ-4", "Ga-Ⅳ-5", "Gc-Ⅳ-4", "Ma-Ⅳ-1", "Mb-Ⅳ-1", "Mc-Ⅳ-1", "Mc-Ⅳ-2", "Nc-Ⅳ-1", "ah-Ⅳ-2"],
      prerequisiteFamilyKeys: ["MENDELIAN_PEDIGREES"],
      skills: [
        "區分遺傳變異與環境造成的差異",
        "說明遺傳物質變異可能改變性狀",
        "判斷生殖細胞變異可能傳給後代",
        "辨識育種發酵與基因技術應用",
        "比較生物技術的農業醫藥與環境效益",
        "分析技術風險倫理與生態影響",
        "以證據評估生質能源與生物處理方案",
      ],
    },
    {
      key: "EVOLUTION_NATURAL_SELECTION",
      title: "Evolution and natural selection",
      authorityCodes: ["Ga-Ⅳ-1", "Ga-Ⅳ-4", "Gb-Ⅳ-1", "La-Ⅳ-1", "an-Ⅳ-2", "tm-Ⅳ-1"],
      prerequisiteFamilyKeys: ["VARIATION_MUTATION_BIOTECH"],
      skills: [
        "由化石證據理解過去生物與滅絕",
        "區分個體適應與族群長期變化",
        "連結可遺傳變異生存繁殖與天擇",
        "由環境改變推論性狀比例可能變化",
        "避免把演化解釋為個體主動需要",
        "比較不同證據支持的演化關係",
        "說明科學解釋會隨新證據修正",
      ],
    },
    {
      key: "CLASSIFICATION_BIODIVERSITY",
      title: "Classification and biodiversity",
      authorityCodes: ["Gc-Ⅳ-1", "Gc-Ⅳ-2", "Fc-Ⅳ-1", "Ma-Ⅳ-2", "Ma-Ⅳ-5", "tm-Ⅳ-1"],
      prerequisiteFamilyKeys: ["EVOLUTION_NATURAL_SELECTION"],
      skills: [
        "依可觀察特徵建立生物分類標準",
        "使用二分檢索表辨識生物",
        "比較分類階層與生命組成層次",
        "由構造共同點推論生物關係",
        "說明物種多樣基因多樣與生態系多樣",
        "理解不同生物在生態系的功能",
        "結合在地與原住民族知識觀察生物多樣性",
      ],
    },
    {
      key: "MICROORGANISMS_DISEASE",
      title: "Microorganisms and disease",
      authorityCodes: ["Gc-Ⅳ-3", "Gc-Ⅳ-4", "Dc-Ⅳ-3", "Ma-Ⅳ-1", "Mc-Ⅳ-1", "ah-Ⅳ-1"],
      prerequisiteFamilyKeys: ["CLASSIFICATION_BIODIVERSITY"],
      skills: [
        "辨識微生物可能有益有害或無明顯影響",
        "比較細菌真菌與病毒的基本差異",
        "由傳播途徑理解感染風險",
        "連結皮膚黏膜與免疫防禦",
        "分析發酵與環境處理中的微生物應用",
        "區分相關性與病因證據",
        "以可信公共衛生資訊評估防護說法",
      ],
    },
    {
      key: "PLANT_STRUCTURE_TRANSPORT",
      title: "Plant structure and transport",
      authorityCodes: ["Db-Ⅳ-6", "Db-Ⅳ-8", "Bc-Ⅳ-3", "Mc-Ⅳ-2", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["MICROORGANISMS_DISEASE"],
      skills: [
        "辨識根莖葉主要構造與功能",
        "說明維管束運輸水分養分的功能",
        "追蹤水分由根到葉的路徑",
        "連結氣孔蒸散與水分運輸",
        "比較木本與草本莖的維管束特徵",
        "由植物覆蓋解釋地表逕流與氣溫影響",
        "從仿生例子分析植物構造功能",
      ],
    },
    {
      key: "PHOTOSYNTHESIS_RESPONSES",
      title: "Photosynthesis and plant responses",
      authorityCodes: ["Bc-Ⅳ-3", "Bc-Ⅳ-4", "Db-Ⅳ-6", "Dc-Ⅳ-5", "pe-Ⅳ-1", "pa-Ⅳ-2"],
      prerequisiteFamilyKeys: ["PLANT_STRUCTURE_TRANSPORT"],
      skills: [
        "說明光合作用的原料產物與能量轉換",
        "連結葉綠體與光合作用位置",
        "區分光合作用與植物呼吸作用",
        "由日光二氧化碳與水分資料判斷限制因素",
        "設計檢驗光合作用條件的對照實驗",
        "由向光與向地反應判斷刺激方向",
        "連結植物反應與生存環境",
      ],
    },
    {
      key: "POPULATION_COMMUNITY_ECOSYSTEM",
      title: "Population, community and ecosystem",
      authorityCodes: ["Fc-Ⅳ-1", "INc-Ⅳ-6", "La-Ⅳ-1", "Lb-Ⅳ-1", "Lb-Ⅳ-2", "Gc-Ⅳ-2", "pa-Ⅳ-1"],
      prerequisiteFamilyKeys: ["PHOTOSYNTHESIS_RESPONSES"],
      skills: [
        "區分個體族群群集生態系與生物圈",
        "辨識生物因子與非生物因子",
        "由樣區資料估計族群分布與數量",
        "分析溫度水光等因子對分布的影響",
        "比較競爭捕食互利與寄生關係",
        "由時間資料判斷生態演替",
        "分析人類活動如何改變群集結構",
      ],
    },
    {
      key: "FOOD_CHAINS_ENERGY_FLOW",
      title: "Food chains, webs and energy flow",
      authorityCodes: ["Bd-Ⅳ-1", "Bd-Ⅳ-3", "Gc-Ⅳ-2", "INc-Ⅳ-6", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["POPULATION_COMMUNITY_ECOSYSTEM"],
      skills: [
        "區分生產者消費者與分解者",
        "依攝食關係畫出食物鏈箭頭",
        "把多條食物鏈整合為食物網",
        "追蹤能量由太陽進入生態系的路徑",
        "說明能量沿營養階層逐級減少",
        "由物種增減推論食物網連鎖影響",
        "避免把食物鏈箭頭誤作生物移動方向",
      ],
    },
    {
      key: "MATTER_CYCLES_BALANCE",
      title: "Matter cycles and ecological balance",
      authorityCodes: ["Bd-Ⅳ-2", "Bd-Ⅳ-3", "Bc-Ⅳ-2", "Bc-Ⅳ-3", "Lb-Ⅳ-1", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["FOOD_CHAINS_ENERGY_FLOW"],
      skills: [
        "區分能量單向流動與物質循環",
        "追蹤碳在空氣生物與環境間移動",
        "連結光合作用呼吸與碳循環",
        "說明分解者使物質回到環境",
        "由生物量與環境資料判斷系統變化",
        "理解生態平衡是動態範圍而非完全不變",
        "分析干擾後生態系恢復或轉變",
      ],
    },
    {
      key: "BIODIVERSITY_CONSERVATION",
      title: "Biodiversity conservation",
      authorityCodes: ["Gc-Ⅳ-2", "Lb-Ⅳ-2", "Lb-Ⅳ-3", "Ma-Ⅳ-2", "Ma-Ⅳ-5", "Md-Ⅳ-1", "Na-Ⅳ-1", "ah-Ⅳ-2"],
      prerequisiteFamilyKeys: ["MATTER_CYCLES_BALANCE"],
      skills: [
        "辨識棲地破壞污染過度利用與外來種威脅",
        "比較物種棲地與生態系層級保育",
        "由族群資料判斷保育優先需求",
        "分析保護區復育與永續利用的條件",
        "比較科學監測與在地知識的貢獻",
        "評估保育措施對不同利害關係人的影響",
        "設計可記錄成效的公民保育行動",
      ],
    },
    {
      key: "HEALTH_ENVIRONMENTAL_IMPACT",
      title: "Human health and environmental impact",
      authorityCodes: ["Gc-Ⅳ-3", "Lb-Ⅳ-2", "Me-Ⅳ-1", "Me-Ⅳ-6", "Mc-Ⅳ-1", "Nb-Ⅳ-1", "ah-Ⅳ-2"],
      prerequisiteFamilyKeys: ["BIODIVERSITY_CONSERVATION"],
      skills: [
        "由暴露途徑分析環境汙染對生物影響",
        "說明難分解汙染物的生物放大",
        "比較污染濃度暴露時間與影響程度",
        "連結環境改變與健康風險但不替代診斷",
        "分析全球暖化對物種與生態系的影響",
        "評估生物處理與新興科技的效益風險",
        "以來源可靠的數據比較防治方案",
      ],
    },
    {
      key: "INTEGRATED_EXPERIMENT_INFERENCE",
      title: "Integrated experiment, graph, diagram and inference",
      authorityCodes: ["ah-Ⅳ-1", "ah-Ⅳ-2", "ai-Ⅳ-1", "ai-Ⅳ-2", "ai-Ⅳ-3", "an-Ⅳ-1", "an-Ⅳ-2", "an-Ⅳ-3", "pa-Ⅳ-1", "pa-Ⅳ-2", "pc-Ⅳ-1", "pc-Ⅳ-2", "pe-Ⅳ-1", "pe-Ⅳ-2", "po-Ⅳ-1", "po-Ⅳ-2", "tc-Ⅳ-1", "ti-Ⅳ-1", "tm-Ⅳ-1", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["HEALTH_ENVIRONMENTAL_IMPACT"],
      skills: [
        "對齊實驗問題變因步驟數據與結論",
        "由表格選擇適合的圖形並標示單位",
        "整合模式圖顯微圖與文字資訊",
        "辨認相關趨勢與因果證據的差別",
        "找出實驗限制並提出可行改進",
        "比較重複實驗與不同來源結果",
        "以科學證據提出解釋並標明不確定性",
      ],
    },
  ],
});
