export const CHINESE_SKILL_PLAN = Object.freeze({
  schemaVersion: "cap8-r4-subject-skill-plan-v1",
  subject: "chinese",
  expectedSkills: 320,
  expectedAuthorityNodes: 61,
  families: [
    {
      key: "PHONETIC_PRONUNCIATION",
      title: "Phonetic notation and pronunciation distinctions",
      authorityCodes: ["Ab-Ⅳ-1", "Ab-Ⅳ-2", "4-Ⅳ-1", "4-Ⅳ-3", "5-Ⅳ-1"],
      prerequisiteFamilyKeys: [],
      skills: [
        "依標準注音辨讀常用國字字音",
        "區分聲母相近字的正確讀音",
        "區分韻母相近字的正確讀音",
        "辨別四聲不同造成的詞義差異",
        "依詞語語境判斷一字多音",
        "辨認輕聲與變調在語句中的讀法",
        "以字典音讀資料核對存疑字音",
      ],
    },
    {
      key: "CHARACTER_STANDARD_VARIANTS",
      title: "Character form, standard form and variants",
      authorityCodes: ["Ab-Ⅳ-1", "Ab-Ⅳ-2", "4-Ⅳ-1", "4-Ⅳ-2"],
      prerequisiteFamilyKeys: ["PHONETIC_PRONUNCIATION"],
      skills: [
        "辨識常用國字的標準字形",
        "比較形近字部件位置的差異",
        "區分正字與常見誤寫字形",
        "辨認筆畫增減造成的不同字",
        "依上下文選出字形正確的詞語",
        "辨識異體字與現行標準字的關係",
        "以教育部字典核對標準字形",
      ],
    },
    {
      key: "RADICALS_DICTIONARY",
      title: "Radicals, components and dictionary skills",
      authorityCodes: ["Ab-Ⅳ-1", "Ab-Ⅳ-4", "4-Ⅳ-2", "4-Ⅳ-3"],
      prerequisiteFamilyKeys: ["CHARACTER_STANDARD_VARIANTS"],
      skills: [
        "判斷國字所屬部首",
        "拆分國字的主要部件",
        "依部首與筆畫查找字典",
        "依注音索引查找未知字詞",
        "讀懂字典中的音義與詞性標示",
        "從多個義項選擇符合語境的解釋",
        "交叉使用字典與辭典查證字詞",
      ],
    },
    {
      key: "CHARACTER_FORMATION",
      title: "Character formation principles",
      authorityCodes: ["Ab-Ⅳ-3", "4-Ⅳ-2"],
      prerequisiteFamilyKeys: ["RADICALS_DICTIONARY"],
      skills: [
        "由字形與本義辨識象形字",
        "由抽象符號辨識指事字",
        "由部件組合辨識會意字",
        "區分形聲字的形符與聲符",
        "由形符推測字義範圍",
        "由聲符推測可能讀音並核對例外",
        "運用造字原則辨析形近字",
      ],
    },
    {
      key: "ERRONEOUS_FORMS_HOMOPHONES",
      title: "Common erroneous forms and homophones",
      authorityCodes: ["Ab-Ⅳ-1", "Ab-Ⅳ-2", "Ab-Ⅳ-4", "Ab-Ⅳ-5", "4-Ⅳ-1", "4-Ⅳ-3"],
      prerequisiteFamilyKeys: ["CHARACTER_FORMATION"],
      skills: [
        "辨別同音異形字的語意差別",
        "依搭配關係選用正確同音字",
        "找出句中因形近而誤寫的字",
        "找出句中因音近而誤用的字",
        "依詞源與構詞判斷正確用字",
        "修正常見成語中的錯別字",
        "綜合字音字形字義訂正語句",
      ],
    },
    {
      key: "CONTEXTUAL_POLYSEMY",
      title: "Word meaning and contextual polysemy",
      authorityCodes: ["Ab-Ⅳ-1", "Ab-Ⅳ-4", "Ab-Ⅳ-5", "4-Ⅳ-3", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["ERRONEOUS_FORMS_HOMOPHONES"],
      skills: [
        "由前後文判斷詞語的語境義",
        "區分字詞的本義與引申義",
        "辨別同一字詞在不同句中的義項",
        "依搭配對象縮小多義詞的解釋範圍",
        "判斷詞語在句中的褒貶色彩",
        "辨認具體詞語轉為抽象用法",
        "以替換法檢驗所選詞義是否通順",
      ],
    },
    {
      key: "SYNONYMS_ANTONYMS_FIELDS",
      title: "Synonyms, antonyms and semantic fields",
      authorityCodes: ["Ab-Ⅳ-4", "Ab-Ⅳ-5", "5-Ⅳ-2", "5-Ⅳ-3"],
      prerequisiteFamilyKeys: ["CONTEXTUAL_POLYSEMY"],
      skills: [
        "辨認語境中意義相近的詞語",
        "比較近義詞在程度上的差別",
        "比較近義詞在使用對象上的差別",
        "辨認能形成對比的反義詞",
        "依上下位關係整理語義類別",
        "從同一語義場選出合宜用詞",
        "排除字面相近但語用不同的詞語",
      ],
    },
    {
      key: "IDIOMS_ALLUSIONS_USAGE",
      title: "Idioms, allusions and usage conditions",
      authorityCodes: ["Ab-Ⅳ-4", "Ab-Ⅳ-5", "Ca-Ⅳ-1", "Cb-Ⅳ-1", "Cc-Ⅳ-1", "5-Ⅳ-2", "5-Ⅳ-5"],
      prerequisiteFamilyKeys: ["SYNONYMS_ANTONYMS_FIELDS"],
      skills: [
        "理解常用成語的整體意義",
        "辨認成語適用的人事與情境",
        "區分字面義與成語慣用義",
        "由典故背景理解成語寓意",
        "判斷成語的褒貶與語氣",
        "修正搭配對象不合的成語用法",
        "依上下文選擇最精確的成語",
      ],
    },
    {
      key: "CLASSICAL_WORDS_MEANING",
      title: "Classical common words and ancient-modern meaning",
      authorityCodes: ["Ab-Ⅳ-6", "Ab-Ⅳ-7", "Ad-Ⅳ-4", "4-Ⅳ-3", "5-Ⅳ-2", "5-Ⅳ-3"],
      prerequisiteFamilyKeys: ["IDIOMS_ALLUSIONS_USAGE"],
      skills: [
        "依文句判斷常見文言實詞詞義",
        "辨識常見文言虛字的基本功能",
        "比較同一字的古義與今義",
        "辨認文言通假與語境線索",
        "由前後句推斷省略成分",
        "將文言語詞換成不失原意的白話",
        "避免以現代常用義誤解古文",
      ],
    },
    {
      key: "PARTS_OF_SPEECH_FUNCTION",
      title: "Parts of speech and word function",
      authorityCodes: ["Ab-Ⅳ-5", "Ab-Ⅳ-6", "Ac-Ⅳ-3", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["CLASSICAL_WORDS_MEANING"],
      skills: [
        "依句中功能辨認名詞與代名詞",
        "依句中功能辨認動詞與形容詞",
        "辨認副詞對動作或性質的修飾",
        "辨認介詞與連詞的連接功能",
        "判斷同一詞在不同語境中的詞性",
        "辨識文言名詞活用為動詞的現象",
        "用句法位置檢驗詞性判斷",
      ],
    },
    {
      key: "PHRASE_SENTENCE_STRUCTURE",
      title: "Phrase and sentence structure",
      authorityCodes: ["Ab-Ⅳ-6", "Ac-Ⅳ-2", "Ac-Ⅳ-3", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["PARTS_OF_SPEECH_FUNCTION"],
      skills: [
        "辨認主語與述語的搭配關係",
        "辨認動詞與受詞的支配關係",
        "辨認修飾語與中心語",
        "區分並列偏正動賓與主謂短語",
        "找出句中成分殘缺的位置",
        "找出句中搭配不當的成分",
        "以縮句法掌握長句主要結構",
      ],
    },
    {
      key: "SIMPLE_COMPLEX_TRANSFORMED",
      title: "Simple, complex and transformed sentences",
      authorityCodes: ["Ac-Ⅳ-2", "Ac-Ⅳ-3", "5-Ⅳ-2", "6-Ⅳ-3"],
      prerequisiteFamilyKeys: ["PHRASE_SENTENCE_STRUCTURE"],
      skills: [
        "辨識敘事句所表達的動作事件",
        "辨識有無句與存在關係",
        "辨識判斷句的主語與判斷內容",
        "辨識表態句的情感或評價",
        "區分單句與複句的結構",
        "依因果轉折條件組合複句",
        "改寫句式並維持原意與重點",
      ],
    },
    {
      key: "COHESION_REFERENCE_LOGIC",
      title: "Cohesion, reference and logical relations",
      authorityCodes: ["Ac-Ⅳ-3", "Ad-Ⅳ-1", "1-Ⅳ-3", "2-Ⅳ-2", "5-Ⅳ-2", "6-Ⅳ-2"],
      prerequisiteFamilyKeys: ["SIMPLE_COMPLEX_TRANSFORMED"],
      skills: [
        "追蹤代詞所指的人事物",
        "運用重複與同義詞辨認語意銜接",
        "由關聯詞判斷因果轉折與條件",
        "找出句間缺少的承接資訊",
        "依已知與新資訊排列句序",
        "辨認前後矛盾或推論跳躍",
        "選擇能維持段落連貫的句子",
      ],
    },
    {
      key: "PUNCTUATION_TYPOGRAPHY",
      title: "Punctuation and typography",
      authorityCodes: ["Ac-Ⅳ-1", "5-Ⅳ-1", "6-Ⅳ-1"],
      prerequisiteFamilyKeys: ["COHESION_REFERENCE_LOGIC"],
      skills: [
        "依語意停頓選用逗號與頓號",
        "依分句關係選用分號與句號",
        "正確使用冒號引出說明或引語",
        "區分引號書名號與專名號用途",
        "使用問號與驚嘆號表現語氣",
        "比較標點改變造成的語意差異",
        "訂正標點與引文層次錯誤",
      ],
    },
    {
      key: "RHETORICAL_DEVICES_EFFECTS",
      title: "Rhetorical devices and expressive effects",
      authorityCodes: ["Ba-Ⅳ-2", "Bb-Ⅳ-4", "Bb-Ⅳ-5", "Bd-Ⅳ-2", "5-Ⅳ-3", "6-Ⅳ-3"],
      prerequisiteFamilyKeys: ["PUNCTUATION_TYPOGRAPHY"],
      skills: [
        "辨識譬喻的本體喻體與相似點",
        "辨識擬人如何賦予事物人的特徵",
        "辨識排比與層遞的語勢效果",
        "辨識映襯對比所凸顯的差異",
        "辨識設問反問與呼告的語氣",
        "比較直接抒情與間接抒情效果",
        "依語境判斷修辭是否貼切",
      ],
    },
    {
      key: "NARRATIVE_COMPREHENSION",
      title: "Narrative text comprehension",
      authorityCodes: ["Ad-Ⅳ-1", "Ad-Ⅳ-2", "Ad-Ⅳ-4", "Ba-Ⅳ-1", "Ba-Ⅳ-2", "Bb-Ⅳ-1", "Bb-Ⅳ-3", "5-Ⅳ-2", "5-Ⅳ-3"],
      prerequisiteFamilyKeys: ["RHETORICAL_DEVICES_EFFECTS"],
      skills: [
        "找出敘事文本的人物時間地點與事件",
        "依因果整理事件發展",
        "區分順敘倒敘插敘與補敘",
        "判斷敘事視角對資訊的限制",
        "由行動與描寫推論人物心情",
        "辨認轉折事件對結局的作用",
        "用關鍵事件概括敘事主旨",
      ],
    },
    {
      key: "EXPOSITORY_COMPREHENSION",
      title: "Expository text comprehension",
      authorityCodes: ["Bc-Ⅳ-1", "Bc-Ⅳ-2", "Bc-Ⅳ-3", "5-Ⅳ-2", "5-Ⅳ-3", "5-Ⅳ-4"],
      prerequisiteFamilyKeys: ["NARRATIVE_COMPREHENSION"],
      skills: [
        "找出說明對象與核心特徵",
        "辨識定義列舉分類與比較方法",
        "辨識因果與問題解決的說明架構",
        "整合數據圖表與正文資訊",
        "區分客觀說明與作者評價",
        "依說明順序重組操作或過程",
        "檢驗結論是否受到文中資料支持",
      ],
    },
    {
      key: "ARGUMENTATIVE_COMPREHENSION",
      title: "Argumentative text comprehension",
      authorityCodes: ["Bd-Ⅳ-1", "Bd-Ⅳ-2", "1-Ⅳ-3", "2-Ⅳ-3", "2-Ⅳ-5", "5-Ⅳ-2", "5-Ⅳ-3"],
      prerequisiteFamilyKeys: ["EXPOSITORY_COMPREHENSION"],
      skills: [
        "區分論點論據與論證",
        "辨認事實論據與理論論據",
        "判斷論據與論點是否相關",
        "辨識比較與比喻論證的作用",
        "找出推論中缺少的必要條件",
        "比較正反觀點的理由與證據",
        "評估結論是否超出論據能支持的範圍",
      ],
    },
    {
      key: "PRACTICAL_FUNCTIONAL_TEXTS",
      title: "Practical and functional texts",
      authorityCodes: ["Be-Ⅳ-1", "Be-Ⅳ-2", "Be-Ⅳ-3", "2-Ⅳ-1", "2-Ⅳ-5", "5-Ⅳ-2", "6-Ⅳ-4"],
      prerequisiteFamilyKeys: ["ARGUMENTATIVE_COMPREHENSION"],
      skills: [
        "辨識書信稱謂提稱語與祝福語",
        "判讀便條中的對象事項與時間",
        "掌握新聞稿的人事時地物與事件",
        "辨識自傳的經歷選材與敘寫目的",
        "讀懂簡報與演講稿的層次標示",
        "依情境選擇合宜的應用文格式",
        "檢查應用文資訊是否完整且一致",
      ],
    },
    {
      key: "MODERN_POETRY_SONG_TEXTS",
      title: "Modern poetry and song-like texts",
      authorityCodes: ["Ad-Ⅳ-2", "Bb-Ⅳ-1", "Bb-Ⅳ-2", "Bb-Ⅳ-3", "Bb-Ⅳ-4", "Bb-Ⅳ-5", "5-Ⅳ-1", "5-Ⅳ-2", "5-Ⅳ-3"],
      prerequisiteFamilyKeys: ["PRACTICAL_FUNCTIONAL_TEXTS"],
      skills: [
        "由意象與語句掌握現代詩主題",
        "辨認分行與留白形成的節奏",
        "由重複與音韻感受詩歌語氣",
        "分析象徵意象所承載的情感",
        "區分敘事片段與抒情核心",
        "由說話者立場判斷詩中觀點",
        "比較詩句改寫前後的表達效果",
      ],
    },
    {
      key: "CLASSICAL_POETRY_VERSE",
      title: "Classical poetry and regulated verse",
      authorityCodes: ["Ad-Ⅳ-3", "Bb-Ⅳ-1", "Bb-Ⅳ-2", "Bb-Ⅳ-3", "Cc-Ⅳ-1", "5-Ⅳ-1", "5-Ⅳ-2", "5-Ⅳ-3"],
      prerequisiteFamilyKeys: ["MODERN_POETRY_SONG_TEXTS"],
      skills: [
        "區分古體詩樂府與近體詩基本形式",
        "由字數句數辨識絕句與律詩",
        "掌握近體詩押韻與對仗的基本特徵",
        "依景物意象理解詩人情感",
        "辨認借景抒情與情景交融",
        "由轉折詞掌握詩意變化",
        "將詩句語意連成完整情境",
      ],
    },
    {
      key: "CLASSICAL_PROSE_HISTORY",
      title: "Classical prose and historical narrative",
      authorityCodes: ["Ab-Ⅳ-6", "Ab-Ⅳ-7", "Ad-Ⅳ-4", "Ba-Ⅳ-1", "Cb-Ⅳ-1", "5-Ⅳ-2", "5-Ⅳ-3"],
      prerequisiteFamilyKeys: ["CLASSICAL_POETRY_VERSE"],
      skills: [
        "依語序與省略補足文言句意",
        "辨識文言判斷倒裝與被動句式",
        "由人物言行整理史傳事件",
        "區分作者敘述與人物言論",
        "辨認史事中的因果與轉折",
        "由細節推論人物品格與抉擇",
        "比較史傳評語與事件證據",
      ],
    },
    {
      key: "FICTION_CHARACTERIZATION",
      title: "Fiction and characterization",
      authorityCodes: ["Ad-Ⅳ-2", "Ad-Ⅳ-4", "Ba-Ⅳ-1", "Ba-Ⅳ-2", "Bb-Ⅳ-1", "Bb-Ⅳ-3", "5-Ⅳ-2", "5-Ⅳ-3"],
      prerequisiteFamilyKeys: ["CLASSICAL_PROSE_HISTORY"],
      skills: [
        "由外貌語言行動與心理描寫分析人物",
        "比較直接描寫與側面烘托",
        "追蹤人物目標衝突與轉變",
        "辨識場景描寫對情節的作用",
        "由伏筆與照應推測情節安排",
        "區分敘事者觀點與人物觀點",
        "用文本細節支持人物評價",
      ],
    },
    {
      key: "DRAMA_DIALOGUE_VIEWPOINT",
      title: "Drama/dialogue and viewpoint",
      authorityCodes: ["Ad-Ⅳ-2", "Be-Ⅳ-3", "1-Ⅳ-1", "1-Ⅳ-2", "2-Ⅳ-1", "2-Ⅳ-2", "2-Ⅳ-3", "2-Ⅳ-5", "5-Ⅳ-2", "5-Ⅳ-3"],
      prerequisiteFamilyKeys: ["FICTION_CHARACTERIZATION"],
      skills: [
        "辨識劇本角色臺詞與舞臺提示",
        "由對話內容推論角色關係",
        "由語氣與停頓推論未明說的態度",
        "比較不同角色對同一事件的觀點",
        "判斷舞臺提示如何影響臺詞理解",
        "依情境補出合乎人物目的的對話",
        "從對話衝突歸納劇情核心問題",
      ],
    },
    {
      key: "MAIN_IDEA_TOPIC_SENTENCE",
      title: "Main idea and topic sentence",
      authorityCodes: ["Ad-Ⅳ-1", "5-Ⅳ-2", "5-Ⅳ-3"],
      prerequisiteFamilyKeys: ["DRAMA_DIALOGUE_VIEWPOINT"],
      skills: [
        "區分篇章主旨與局部細節",
        "由重複概念歸納段落重點",
        "辨認明示主題句的位置",
        "由支持句推回未明示的主題句",
        "選擇涵蓋全文且不過度延伸的主旨",
        "比較標題與主旨的涵蓋範圍",
        "由結尾轉折確認作者真正重點",
      ],
    },
    {
      key: "DETAIL_INTEGRATION_EVIDENCE",
      title: "Detail integration and evidence",
      authorityCodes: ["Ad-Ⅳ-1", "5-Ⅳ-2", "5-Ⅳ-3", "5-Ⅳ-4"],
      prerequisiteFamilyKeys: ["MAIN_IDEA_TOPIC_SENTENCE"],
      skills: [
        "依題幹關鍵詞定位明示資訊",
        "辨認選項改寫而非原句重現的細節",
        "整合相隔段落的相關證據",
        "區分文本資訊與選項新增推測",
        "由多項條件篩選符合者",
        "判斷引文能否支持指定結論",
        "指出答案所依據的具體句段",
      ],
    },
    {
      key: "INFERENCE_UNSTATED",
      title: "Inference and unstated meaning",
      authorityCodes: ["Ad-Ⅳ-1", "1-Ⅳ-3", "5-Ⅳ-2", "5-Ⅳ-4", "5-Ⅳ-5"],
      prerequisiteFamilyKeys: ["DETAIL_INTEGRATION_EVIDENCE"],
      skills: [
        "由兩項以上線索推出隱含結論",
        "由人物反應推論情緒與動機",
        "由因果關係推論事件後果",
        "辨認反語與言外之意",
        "區分合理推論與無據猜測",
        "由缺席資訊判斷作者刻意保留之處",
        "檢驗推論是否能回扣原文證據",
      ],
    },
    {
      key: "PURPOSE_AUDIENCE_TONE",
      title: "Purpose, audience, tone and attitude",
      authorityCodes: ["Bb-Ⅳ-1", "Bb-Ⅳ-2", "Bb-Ⅳ-3", "Be-Ⅳ-1", "Be-Ⅳ-2", "Be-Ⅳ-3", "5-Ⅳ-2", "5-Ⅳ-3"],
      prerequisiteFamilyKeys: ["INFERENCE_UNSTATED"],
      skills: [
        "由文體與內容判斷寫作目的",
        "由稱謂與資訊判斷預期讀者",
        "由措辭與標點判斷語氣",
        "由評價語句判斷作者態度",
        "區分作者立場與引用人物立場",
        "辨認語氣轉折造成的態度變化",
        "選擇有文本證據支持的目的描述",
      ],
    },
    {
      key: "PARAGRAPH_WHOLE_STRUCTURE",
      title: "Paragraph and whole-text structure",
      authorityCodes: ["Ad-Ⅳ-1", "Ba-Ⅳ-1", "Bc-Ⅳ-2", "Bd-Ⅳ-1", "5-Ⅳ-2", "5-Ⅳ-3", "6-Ⅳ-2"],
      prerequisiteFamilyKeys: ["PURPOSE_AUDIENCE_TONE"],
      skills: [
        "辨認段落的起承轉合功能",
        "依時間因果與邏輯排列段落",
        "辨認總分總與並列結構",
        "辨認問題提出分析與解決結構",
        "判斷插入句最合適的位置",
        "由承接詞追蹤跨段關係",
        "以篇章架構摘要全文",
      ],
    },
    {
      key: "WRITING_TECHNIQUE_FORM",
      title: "Writing technique and formal feature",
      authorityCodes: ["Ba-Ⅳ-1", "Ba-Ⅳ-2", "Bb-Ⅳ-4", "Bb-Ⅳ-5", "Bc-Ⅳ-2", "Bd-Ⅳ-2", "5-Ⅳ-3", "6-Ⅳ-3"],
      prerequisiteFamilyKeys: ["PARAGRAPH_WHOLE_STRUCTURE"],
      skills: [
        "判斷敘述描寫抒情說明議論的主要功能",
        "分析倒敘與插敘造成的閱讀效果",
        "分析人物景物與場面描寫的作用",
        "辨認直接與間接抒情的安排",
        "分析舉例比較分類與定義的效果",
        "判斷首尾呼應伏筆與照應",
        "比較不同寫法對焦點與語氣的影響",
      ],
    },
    {
      key: "CROSS_TEXT_COMPARISON",
      title: "Comparison across texts",
      authorityCodes: ["Ad-Ⅳ-1", "5-Ⅳ-2", "5-Ⅳ-3", "5-Ⅳ-4", "5-Ⅳ-5"],
      prerequisiteFamilyKeys: ["WRITING_TECHNIQUE_FORM"],
      skills: [
        "比較兩文主旨的共同與差異",
        "比較兩文選材與證據",
        "比較兩文敘事觀點與語氣",
        "比較不同文體處理同一議題的方式",
        "整合兩文互補資訊形成結論",
        "辨認兩文觀點衝突的原因",
        "判斷哪篇文本能支持指定主張",
      ],
    },
    {
      key: "CHARTS_MIXED_MEDIA_DATA_TEXT",
      title: "Charts, mixed media and data-to-text",
      authorityCodes: ["Bc-Ⅳ-3", "1-Ⅳ-4", "2-Ⅳ-4", "5-Ⅳ-4", "5-Ⅳ-6", "6-Ⅳ-6"],
      prerequisiteFamilyKeys: ["CROSS_TEXT_COMPARISON"],
      skills: [
        "讀取表格標題列與資料列",
        "讀取長條折線圓餅圖的數值與趨勢",
        "整合圖片圖說與正文訊息",
        "將圖表數據轉述為不誇大的文字",
        "檢查文字結論是否符合圖表尺度",
        "比較多種媒材提供的共同與新增資訊",
        "運用圖文資料解決生活情境問題",
      ],
    },
    {
      key: "MEDIA_INFORMATION_LITERACY",
      title: "Media and information literacy",
      authorityCodes: ["Ca-Ⅳ-2", "1-Ⅳ-3", "1-Ⅳ-4", "2-Ⅳ-3", "2-Ⅳ-4", "5-Ⅳ-4", "5-Ⅳ-5", "5-Ⅳ-6", "6-Ⅳ-6"],
      prerequisiteFamilyKeys: ["CHARTS_MIXED_MEDIA_DATA_TEXT"],
      skills: [
        "區分可查證事實與個人意見",
        "辨識標題與內容不一致的訊息",
        "檢查資訊來源作者日期與證據",
        "比較不同媒體對同一事件的取材",
        "辨認廣告與貼文的說服策略",
        "用多個可靠來源交叉查證資訊",
      ],
    },
    {
      key: "CULTURAL_CUSTOMS_MATERIAL",
      title: "Cultural customs and material culture",
      authorityCodes: ["Ca-Ⅳ-1", "Ca-Ⅳ-2", "Cb-Ⅳ-1", "Cb-Ⅳ-2", "Cc-Ⅳ-1", "5-Ⅳ-5"],
      prerequisiteFamilyKeys: ["MEDIA_INFORMATION_LITERACY"],
      skills: [
        "由文本辨識飲食服飾與建築文化",
        "由交通娛樂與名勝理解時代生活",
        "由科技與環境描寫判斷文明變遷",
        "由儀式風俗理解群體價值",
        "比較不同地域或時代的生活文化",
        "以文本證據避免用現代習慣套解古代生活",
      ],
    },
    {
      key: "CLASSICAL_INSTITUTIONS_CHRONOLOGY",
      title: "Classical institutions, titles and chronology",
      authorityCodes: ["Ca-Ⅳ-1", "Cb-Ⅳ-1", "Cb-Ⅳ-2", "Ad-Ⅳ-3", "Ad-Ⅳ-4", "5-Ⅳ-5"],
      prerequisiteFamilyKeys: ["CULTURAL_CUSTOMS_MATERIAL"],
      skills: [
        "依親屬稱謂判斷人物關係",
        "辨識常見古代官職與身分稱呼",
        "由年號干支與紀年線索理解先後",
        "辨認書信謙稱敬稱與對象",
        "由禮俗制度解釋人物行動",
        "區分文本證據與後世想像的制度描述",
      ],
    },
    {
      key: "LITERARY_HISTORY_GENRE",
      title: "Literary history and genre knowledge",
      authorityCodes: ["Ad-Ⅳ-2", "Ad-Ⅳ-3", "Ad-Ⅳ-4", "Cc-Ⅳ-1", "5-Ⅳ-3"],
      prerequisiteFamilyKeys: ["CLASSICAL_INSTITUTIONS_CHRONOLOGY"],
      skills: [
        "區分詩詞曲與散文的基本體裁",
        "辨識先秦語錄寓言與史傳特色",
        "辨識古典小說與現代小說形式差異",
        "辨識新詩散文劇本的主要形式",
        "依作品形式判斷可能體裁",
        "避免僅憑年代而忽略文本特徵",
      ],
    },
    {
      key: "AUTHORS_WORKS_CONTEXT",
      title: "Authors, works and contextual knowledge",
      authorityCodes: ["Ad-Ⅳ-2", "Ad-Ⅳ-3", "Ad-Ⅳ-4", "Ca-Ⅳ-2", "Cb-Ⅳ-2", "Cc-Ⅳ-1", "5-Ⅳ-5"],
      prerequisiteFamilyKeys: ["LITERARY_HISTORY_GENRE"],
      skills: [
        "由必要背景理解作品寫作情境",
        "辨別作者生平資訊與文本可證內容",
        "連結作品體裁與所處文學傳統",
        "判斷時代背景如何影響題材",
        "比較同一作者不同作品的可證特色",
        "排除張冠李戴的作者作品敘述",
      ],
    },
    {
      key: "CALLIGRAPHY_SCRIPTS_INSCRIPTIONS",
      title: "Calligraphy, scripts and inscriptions",
      authorityCodes: ["Ab-Ⅳ-8", "4-Ⅳ-4", "4-Ⅳ-5"],
      prerequisiteFamilyKeys: ["AUTHORS_WORKS_CONTEXT"],
      skills: [
        "辨認篆隸楷行草的基本字形特色",
        "依筆畫與結構比較不同書體",
        "辨識碑帖拓本與墨跡的呈現差異",
        "觀察行款布局與字距行距",
        "由行氣與用筆描述書法風格",
        "以可見特徵欣賞作品而不臆測作者意圖",
      ],
    },
    {
      key: "REFERENCE_TOOLS_SOURCE_EVALUATION",
      title: "Reference tools and source evaluation",
      authorityCodes: ["4-Ⅳ-3", "1-Ⅳ-4", "2-Ⅳ-4", "5-Ⅳ-4", "5-Ⅳ-6", "6-Ⅳ-6"],
      prerequisiteFamilyKeys: ["CALLIGRAPHY_SCRIPTS_INSCRIPTIONS"],
      skills: [
        "依查詢目的選擇字典辭典或百科資料",
        "讀懂工具書凡例與縮寫標示",
        "以關鍵詞搜尋並縮小資料範圍",
        "記錄來源作者日期與出版資訊",
        "比較第一手與轉述資料的證據距離",
        "排除無來源或內容互相矛盾的資料",
      ],
    },
    {
      key: "TEXTBOOK_UNION_MODERN_PROSE",
      title: "Textbook-edition union modern prose skills",
      authorityCodes: ["Ad-Ⅳ-1", "Ad-Ⅳ-2", "Ba-Ⅳ-1", "Ba-Ⅳ-2", "Bb-Ⅳ-1", "Bb-Ⅳ-2", "Bb-Ⅳ-3", "5-Ⅳ-2", "5-Ⅳ-3"],
      prerequisiteFamilyKeys: ["REFERENCE_TOOLS_SOURCE_EVALUATION"],
      skills: [
        "以跨版本共同閱讀能力分析現代散文",
        "由敘事與描寫理解散文情感",
        "辨識散文題材與主旨的連結",
        "分析段落轉折與首尾照應",
        "比較寫人記事寫景作品的取材",
        "將陌生現代散文轉用既有閱讀策略",
      ],
    },
    {
      key: "TEXTBOOK_UNION_MODERN_POETRY",
      title: "Textbook-edition union modern poetry skills",
      authorityCodes: ["Ad-Ⅳ-1", "Ad-Ⅳ-2", "Bb-Ⅳ-3", "Bb-Ⅳ-4", "Bb-Ⅳ-5", "5-Ⅳ-1", "5-Ⅳ-2", "5-Ⅳ-3"],
      prerequisiteFamilyKeys: ["TEXTBOOK_UNION_MODERN_PROSE"],
      skills: [
        "以跨版本共同方法掌握陌生新詩",
        "由意象群辨認詩中情感線索",
        "由語序斷裂與留白補足語意",
        "分析反覆對比與象徵的效果",
        "比較詩題與內容的關係",
        "以詩句證據排除過度主觀詮釋",
      ],
    },
    {
      key: "TEXTBOOK_UNION_CLASSICAL",
      title: "Textbook-edition union classical text skills",
      authorityCodes: ["Ab-Ⅳ-6", "Ab-Ⅳ-7", "Ad-Ⅳ-3", "Ad-Ⅳ-4", "5-Ⅳ-2", "5-Ⅳ-3"],
      prerequisiteFamilyKeys: ["TEXTBOOK_UNION_MODERN_POETRY"],
      skills: [
        "以常見實詞虛字讀懂陌生文言短文",
        "用語境與句法判斷古今義",
        "補出文言省略主語與受詞",
        "依事件與人物言論整理文意",
        "由篇章結構歸納寓意或觀點",
        "避免依單一版本背誦代替文本理解",
      ],
    },
    {
      key: "PUBLIC_DOMAIN_CLASSICAL_CORPUS",
      title: "Public-domain classical core corpus",
      authorityCodes: ["Ab-Ⅳ-6", "Ab-Ⅳ-7", "Ad-Ⅳ-3", "Ad-Ⅳ-4", "Ca-Ⅳ-1", "Cb-Ⅳ-1", "Cc-Ⅳ-1", "5-Ⅳ-2", "5-Ⅳ-3", "5-Ⅳ-5"],
      prerequisiteFamilyKeys: ["TEXTBOOK_UNION_CLASSICAL"],
      skills: [
        "辨讀公版古典文本中的常用文言詞",
        "依完整上下文翻譯公版古典句段",
        "比較公版詩文中的共同文化母題",
        "由原文證據分析人物與寓意",
        "辨別後人注釋與原始文本層次",
        "比較古典原文與白話解說是否保持文意",
      ],
    },
    {
      key: "RECITATION_MEMORY_COMPREHENSION",
      title: "Recitation and memory with comprehension",
      authorityCodes: ["Ad-Ⅳ-3", "Ad-Ⅳ-4", "1-Ⅳ-2", "2-Ⅳ-1", "5-Ⅳ-1", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["PUBLIC_DOMAIN_CLASSICAL_CORPUS"],
      skills: [
        "依語意單位停頓朗讀文本",
        "以聲情變化表現句段轉折",
        "用結構與意象線索協助記憶",
        "由背誦句補回前後文語意",
        "說明名句在原篇章中的作用",
        "避免脫離上下文套用背誦語句",
      ],
    },
    {
      key: "EDITING_ERROR_REVISION",
      title: "Editing, error diagnosis and revision",
      authorityCodes: ["Ac-Ⅳ-1", "Ac-Ⅳ-3", "6-Ⅳ-1", "6-Ⅳ-2", "6-Ⅳ-3", "6-Ⅳ-4", "6-Ⅳ-6"],
      prerequisiteFamilyKeys: ["RECITATION_MEMORY_COMPREHENSION"],
      skills: [
        "訂正錯別字與不當詞語",
        "修正成分殘缺重複與搭配不當",
        "修正前後矛盾與指涉不清",
        "調整句序與連接詞提升連貫",
        "調整標點與分段改善閱讀節奏",
        "比較修訂前後是否保留原意",
      ],
    },
    {
      key: "GUIDED_WRITING_TASK_MATERIAL",
      title: "Guided writing: task analysis and material selection",
      authorityCodes: ["2-Ⅳ-1", "2-Ⅳ-2", "2-Ⅳ-3", "2-Ⅳ-5", "6-Ⅳ-2", "6-Ⅳ-4", "6-Ⅳ-5"],
      prerequisiteFamilyKeys: ["EDITING_ERROR_REVISION"],
      skills: [
        "從題目找出寫作對象目的與限制",
        "辨識命題關鍵詞與隱含任務",
        "依主旨選擇相關生活經驗",
        "區分核心材料與可刪除枝節",
        "以觀察細節補強空泛材料",
        "檢查取材是否回應全部題意",
      ],
    },
    {
      key: "GUIDED_WRITING_ORGANIZATION",
      title: "Guided writing: organization, evidence and expression",
      authorityCodes: ["Ba-Ⅳ-1", "Ba-Ⅳ-2", "Bc-Ⅳ-2", "Bd-Ⅳ-1", "2-Ⅳ-3", "6-Ⅳ-1", "6-Ⅳ-2", "6-Ⅳ-3", "6-Ⅳ-4"],
      prerequisiteFamilyKeys: ["GUIDED_WRITING_TASK_MATERIAL"],
      skills: [
        "依主旨安排開頭發展轉折與結尾",
        "用事件因果組織敘事材料",
        "用分類比較組織說明材料",
        "用主張理由例證組織議論材料",
        "運用具體描寫與精確用詞表達",
        "以段落中心維持全文一致",
      ],
    },
    {
      key: "GUIDED_WRITING_REVISION_RUBRIC",
      title: "Guided writing: revision and six-level rubric",
      authorityCodes: ["2-Ⅳ-4", "6-Ⅳ-1", "6-Ⅳ-2", "6-Ⅳ-3", "6-Ⅳ-4", "6-Ⅳ-5", "6-Ⅳ-6"],
      prerequisiteFamilyKeys: ["GUIDED_WRITING_ORGANIZATION"],
      skills: [
        "依題意內容結構與語言逐層自評",
        "檢查主旨是否明確且前後一致",
        "補足關鍵細節並刪除無關內容",
        "修正文句標點錯字與贅詞",
        "依六級分評分觀察作品優缺點",
        "根據具體回饋完成第二稿並說明修改理由",
      ],
    },
  ],
});
