export const CIVICS_SKILL_PLAN = Object.freeze({
  schemaVersion: "cap8-r4-subject-skill-plan-v1",
  subject: "civics",
  expectedSkills: 240,
  expectedAuthorityNodes: 100,
  families: [
    {
      key: "SELF_IDENTITY_SOCIALIZATION",
      title: "Self, identity and socialization",
      authorityCodes: ["公Aa-Ⅳ-1", "公Aa-Ⅳ-2", "公1a-Ⅳ-1", "社1a-Ⅳ-1", "社2c-Ⅳ-1"],
      prerequisiteFamilyKeys: [],
      skills: [
        "區分自然人居民國民與公民概念",
        "辨識個人多重身分的形成來源",
        "分析家庭學校同儕與媒體的社會化影響",
        "比較自主選擇與社會期待的互動",
        "由生活行動辨識公民德性",
        "反思身分認同如何隨經驗改變",
        "以公民概念解釋日常公共責任",
      ],
    },
    {
      key: "GROUPS_COMMUNITIES_NETWORKS",
      title: "Groups, communities and social networks",
      authorityCodes: ["公Ba-Ⅳ-2", "公Bb-Ⅳ-1", "公Bb-Ⅳ-2", "社2b-Ⅳ-1", "社3c-Ⅳ-2"],
      prerequisiteFamilyKeys: ["SELF_IDENTITY_SOCIALIZATION"],
      skills: [
        "區分初級團體與次級團體互動特色",
        "說明個人參與不同團體的需求",
        "辨識正式組織與非正式群體",
        "分析社會網絡提供的支持與壓力",
        "理解部落作為原住民族社會組織的意義",
        "比較志願結社與非自願隸屬關係",
        "評估團體規範對成員選擇的影響",
      ],
    },
    {
      key: "CULTURE_DIVERSITY_INCLUSION",
      title: "Culture, diversity and inclusion",
      authorityCodes: ["公Bc-Ⅳ-2", "公Bc-Ⅳ-3", "公Dc-Ⅳ-1", "公Dc-Ⅳ-2", "公Dc-Ⅳ-3", "社2a-Ⅳ-3", "社2b-Ⅳ-2"],
      prerequisiteFamilyKeys: ["GROUPS_COMMUNITIES_NETWORKS"],
      skills: [
        "由語言價值習俗辨識文化要素",
        "比較文化差異與個人差異",
        "分析文化規範隨時間空間改變",
        "辨識主流文化造成的位階與排除",
        "區分尊重差異與無條件接受傷害行為",
        "由多元觀點避免刻板印象",
        "提出兼顧差異與平等參與的作法",
      ],
    },
    {
      key: "FAMILY_GENDER_GENERATIONS",
      title: "Family, gender and intergenerational relations",
      authorityCodes: ["公Ba-Ⅳ-1", "公Ba-Ⅳ-3", "公Ba-Ⅳ-4", "公Ba-Ⅳ-5", "公Cd-Ⅳ-2", "社2b-Ⅳ-1", "社2c-Ⅳ-2"],
      prerequisiteFamilyKeys: ["CULTURE_DIVERSITY_INCLUSION"],
      skills: [
        "說明家庭作為社會組織的功能",
        "辨識親屬關係形成與基本權利義務",
        "比較多樣家庭型態與共同需求",
        "分析家庭職能隨社會變遷調整",
        "辨識家務與照顧分工中的性別不平等",
        "分析世代資源需求與責任衝突",
        "評估公權力介入家庭的必要性與界線",
      ],
    },
    {
      key: "SCHOOL_COMMUNITY_PUBLIC_LIFE",
      title: "School, community and public life",
      authorityCodes: ["公Ab-Ⅳ-2", "公Ca-Ⅳ-3", "公Aa-Ⅳ-2", "公1c-Ⅳ-1", "社2a-Ⅳ-2", "社2c-Ⅳ-2"],
      prerequisiteFamilyKeys: ["FAMILY_GENDER_GENERATIONS"],
      skills: [
        "辨識學生在校園中的權利與責任",
        "區分個人事務班級事務與校園公共事務",
        "由校園規則判斷目的與正當程序",
        "運用提案討論與表決參與校園決策",
        "比較社區公共設施的多元需求",
        "以在地資料提出社區改善意見",
        "檢討參與行動是否尊重他人權利",
      ],
    },
    {
      key: "STATUS_ROLES_NORMS_CONTROL",
      title: "Status, roles, norms and social control",
      authorityCodes: ["公Bc-Ⅳ-1", "公Bc-Ⅳ-2", "公Bc-Ⅳ-3", "公Bm-Ⅳ-1", "公Bm-Ⅳ-2", "社1b-Ⅳ-1"],
      prerequisiteFamilyKeys: ["SCHOOL_COMMUNITY_PUBLIC_LIFE"],
      skills: [
        "區分社會地位與角色期待",
        "辨識同一身分可能面臨的角色衝突",
        "比較習俗道德宗教與法律規範",
        "說明社會規範維持秩序的功能",
        "分析獎勵懲罰與誘因如何影響行為",
        "比較不同人對同一誘因的反應",
        "評估規範改變的社會背景與影響",
      ],
    },
    {
      key: "STRATIFICATION_INEQUALITY",
      title: "Social stratification and inequality",
      authorityCodes: ["公Da-Ⅳ-1", "公Da-Ⅳ-2", "公Da-Ⅳ-3", "公Db-Ⅳ-1", "公Db-Ⅳ-2", "公Dc-Ⅳ-2", "社2b-Ⅳ-1", "社1c-Ⅳ-1"],
      prerequisiteFamilyKeys: ["STATUS_ROLES_NORMS_CONTROL"],
      skills: [
        "辨識所得財富教育與權力差距",
        "區分個人差異與制度性不平等",
        "分析不利處境中的多重因素",
        "比較形式平等與實質平等",
        "評估機會資源與結果分配原則",
        "說明個人行善不能取代公共制度",
        "用資料而非標籤分析社會不平等",
      ],
    },
    {
      key: "RIGHTS_DUTIES_DIGNITY",
      title: "Rights, duties and human dignity",
      authorityCodes: ["公Ab-Ⅳ-1", "公Ad-Ⅳ-1", "公Aa-Ⅳ-2", "公Bg-Ⅳ-1", "公Db-Ⅳ-1", "公1a-Ⅳ-1", "社2c-Ⅳ-2"],
      prerequisiteFamilyKeys: ["STRATIFICATION_INEQUALITY"],
      skills: [
        "區分政府權力與人民權利",
        "說明人性尊嚴是基本權保障基礎",
        "辨識權利行使與他人權利的界線",
        "區分道德責任法律義務與公民責任",
        "分析基本生活保障與選擇自由關係",
        "判斷權利限制是否具有正當目的",
        "由情境比較權利衝突與平衡方式",
      ],
    },
    {
      key: "HUMAN_RIGHTS_MINORITY",
      title: "Human rights and minority protection",
      authorityCodes: ["公Ad-Ⅳ-1", "公Ad-Ⅳ-2", "公Da-Ⅳ-2", "公Dc-Ⅳ-2", "公Dc-Ⅳ-3", "公Bk-Ⅳ-1", "社2b-Ⅳ-1", "社2b-Ⅳ-2"],
      prerequisiteFamilyKeys: ["RIGHTS_DUTIES_DIGNITY"],
      skills: [
        "說明人權普遍性與不可任意剝奪",
        "辨識直接歧視與間接不利效果",
        "分析少數群體在多數決下的風險",
        "區分合理差別待遇與不當歧視",
        "理解兒童少年需要特別保障的原因",
        "比較平等保護無障礙與合理調整",
        "由當事人處境評估保障措施是否有效",
      ],
    },
    {
      key: "RULE_OF_LAW_HIERARCHY",
      title: "Rule of law and legal hierarchy",
      authorityCodes: ["公Bf-Ⅳ-1", "公Bf-Ⅳ-2", "公Bh-Ⅳ-1", "公Bi-Ⅳ-1", "公1a-Ⅳ-1"],
      prerequisiteFamilyKeys: ["HUMAN_RIGHTS_MINORITY"],
      skills: [
        "比較法治與人治的差異",
        "說明政府與人民同受法律規範",
        "辨識憲法法律與命令的位階",
        "判斷低位階規範不得牴觸高位階規範",
        "理解法律明確與可預見的重要性",
        "說明刑罰須有法律明文依據",
        "由案例辨識依法行政與恣意決定",
      ],
    },
    {
      key: "CONSTITUTION_CONSTITUTIONALISM",
      title: "Constitution and constitutionalism",
      authorityCodes: ["公Be-Ⅳ-1", "公Be-Ⅳ-2", "公Bf-Ⅳ-2", "公Bg-Ⅳ-1", "公Ab-Ⅳ-1", "公1a-Ⅳ-1"],
      prerequisiteFamilyKeys: ["RULE_OF_LAW_HIERARCHY"],
      skills: [
        "說明憲法規範政府組織與人民權利",
        "理解憲法作為最高法規範的意義",
        "區分憲法條文與一般政策選擇",
        "辨識多數決仍受基本權限制",
        "分析憲政制度限制公權力的方式",
        "由權利爭議判斷憲法保障面向",
        "說明修憲穩定性與民主正當性的平衡",
      ],
    },
    {
      key: "SEPARATION_CHECKS_BALANCES",
      title: "Separation of powers and checks and balances",
      authorityCodes: ["公Be-Ⅳ-1", "公Be-Ⅳ-2", "公Be-Ⅳ-3", "公Bd-Ⅳ-1", "公1a-Ⅳ-1", "公1b-Ⅳ-1"],
      prerequisiteFamilyKeys: ["CONSTITUTION_CONSTITUTIONALISM"],
      skills: [
        "說明權力分立用來防止權力集中",
        "區分立法行政與司法基本功能",
        "辨認機關間制衡與合作關係",
        "由事件判斷主要涉及哪種國家權力",
        "分析制衡可能降低效率但保障權利",
        "區分權力分立與機關彼此完全獨立",
        "比較不同制度安排的責任歸屬",
      ],
    },
    {
      key: "CENTRAL_GOVERNMENT",
      title: "Central government institutions",
      authorityCodes: ["公Bd-Ⅳ-1", "公Be-Ⅳ-2", "公Be-Ⅳ-3", "公Bh-Ⅳ-1", "公Bi-Ⅳ-3", "公1a-Ⅳ-1"],
      prerequisiteFamilyKeys: ["SEPARATION_CHECKS_BALANCES"],
      skills: [
        "區分國家政府與行政機關概念",
        "辨認中央政府主要機關與基本職權",
        "依法定職權判斷公共事件負責機關",
        "分析政策形成執行監督與審判流程",
        "區分政治責任行政責任與司法判斷",
        "由權限衝突判斷應查閱的法規層級",
        "以官方現行資料核對政府組織資訊",
      ],
    },
    {
      key: "LOCAL_SELF_GOVERNMENT",
      title: "Local self-government",
      authorityCodes: ["公Be-Ⅳ-3", "公Ca-Ⅳ-2", "公Ca-Ⅳ-3", "公1a-Ⅳ-1", "社2a-Ⅳ-2", "社3d-Ⅳ-1"],
      prerequisiteFamilyKeys: ["CENTRAL_GOVERNMENT"],
      skills: [
        "區分中央與地方公共事務",
        "辨認地方自治機關的基本組成",
        "依事務性質判斷較適合的治理層級",
        "分析地方自治與中央監督關係",
        "由預算服務與需求比較地方政策",
        "運用公開程序參與地方事務",
        "以現行官方資料核對地方制度變動",
      ],
    },
    {
      key: "ELECTIONS_PARTIES",
      title: "Elections, voting systems and political parties",
      authorityCodes: ["公Cc-Ⅳ-1", "公Cc-Ⅳ-2", "公Cc-Ⅳ-3", "公Aa-Ⅳ-2", "公1a-Ⅳ-1", "公1b-Ⅳ-1", "社2c-Ⅳ-2"],
      prerequisiteFamilyKeys: ["LOCAL_SELF_GOVERNMENT"],
      skills: [
        "說明選舉與民主政治參與的關係",
        "辨認公平投票的基本原則",
        "區分選舉罷免公民投票與其他參與",
        "比較不同投票規則可能產生的結果",
        "說明政黨整合意見與競爭執政的功能",
        "辨識買票脅迫與不實資訊對選舉的傷害",
        "以官方現行規定核對選舉制度資訊",
      ],
    },
    {
      key: "PUBLIC_OPINION_MEDIA",
      title: "Public opinion, media and political communication",
      authorityCodes: ["公Cb-Ⅳ-1", "公Cb-Ⅳ-2", "公Cc-Ⅳ-1", "公De-Ⅳ-1", "公De-Ⅳ-2", "公1b-Ⅳ-1", "社3b-Ⅳ-2"],
      prerequisiteFamilyKeys: ["ELECTIONS_PARTIES"],
      skills: [
        "說明公共意見多元流動與可變特性",
        "區分民意調查媒體報導與社群聲量",
        "檢查民調樣本題目時間與誤差資訊",
        "辨識媒體選材框架與議題設定",
        "分析社群演算法與同溫層影響",
        "區分政治宣傳事實查核與意見表達",
        "以多來源資料判斷公共意見",
      ],
    },
    {
      key: "CIVIL_SOCIETY_MOVEMENTS",
      title: "Civil society, associations and social movements",
      authorityCodes: ["公Bb-Ⅳ-1", "公Bb-Ⅳ-2", "公Cc-Ⅳ-1", "公Ca-Ⅳ-1", "公Aa-Ⅳ-2", "社2c-Ⅳ-2", "社3d-Ⅳ-1"],
      prerequisiteFamilyKeys: ["PUBLIC_OPINION_MEDIA"],
      skills: [
        "說明志願結社的自主性與共同目的",
        "比較利益團體非營利組織與社會運動",
        "分析公民團體影響公共政策的方式",
        "辨識集會倡議監督與服務等行動",
        "評估團體代表性資源與責任",
        "說明非暴力行動與民主秩序關係",
        "以具體證據分析社會運動成效與代價",
      ],
    },
    {
      key: "PUBLIC_PARTICIPATION_DELIBERATION",
      title: "Public participation and deliberation",
      authorityCodes: ["公Ca-Ⅳ-1", "公Ca-Ⅳ-2", "公Ca-Ⅳ-3", "公Cc-Ⅳ-1", "公1c-Ⅳ-1", "社3c-Ⅳ-1", "社3c-Ⅳ-2", "社3d-Ⅳ-1"],
      prerequisiteFamilyKeys: ["CIVIL_SOCIETY_MOVEMENTS"],
      skills: [
        "區分知情表達協商決策與監督參與",
        "說明政策形成前提供參與機會的意義",
        "整理利害關係人的需求理由與證據",
        "以傾聽提問回應進行公共討論",
        "區分多數偏好與有理由的公共判斷",
        "比較參與管道的門檻與影響力",
        "檢討決策程序是否公開平等且可追責",
      ],
    },
    {
      key: "JUSTICE_DISPUTE_RESOLUTION",
      title: "Justice, fairness and dispute resolution",
      authorityCodes: ["公Ca-Ⅳ-1", "公Da-Ⅳ-1", "公Da-Ⅳ-2", "公Da-Ⅳ-3", "公Bj-Ⅳ-5", "公1b-Ⅳ-1", "社2c-Ⅳ-2"],
      prerequisiteFamilyKeys: ["PUBLIC_PARTICIPATION_DELIBERATION"],
      skills: [
        "比較需要功績平等與補償等公平原則",
        "辨認同一事件中不同公平主張",
        "區分權利爭議利益衝突與事實爭議",
        "比較協商調解仲裁與訴訟特性",
        "依關係成本時間與執行力選擇方法",
        "說明非暴力解決爭議的公共價值",
        "評估解決方案是否兼顧程序與結果公平",
      ],
    },
    {
      key: "CIVIL_LAW_RELATIONSHIPS",
      title: "Civil law and everyday relationships",
      authorityCodes: ["公Ba-Ⅳ-3", "公Bj-Ⅳ-1", "公Bj-Ⅳ-2", "公Bj-Ⅳ-3", "公Bj-Ⅳ-5", "公1a-Ⅳ-1"],
      prerequisiteFamilyKeys: ["JUSTICE_DISPUTE_RESOLUTION"],
      skills: [
        "區分民事關係中的權利與義務",
        "辨識契約成立的合意與特殊要件",
        "理解限制行為能力制度的保護目的",
        "判斷契約不履行可能產生的民事責任",
        "辨識侵權行為損害與責任關係",
        "比較民事爭議解決途徑",
        "以現行官方法規查證個案要件",
      ],
    },
    {
      key: "CRIMINAL_LAW_DUE_PROCESS",
      title: "Criminal law, responsibility and due process",
      authorityCodes: ["公Bi-Ⅳ-1", "公Bi-Ⅳ-2", "公Bi-Ⅳ-3", "公Bf-Ⅳ-1", "公Ad-Ⅳ-1", "公1a-Ⅳ-1"],
      prerequisiteFamilyKeys: ["CIVIL_LAW_RELATIONSHIPS"],
      skills: [
        "說明刑法保護法益與限制國家處罰權",
        "理解罪刑法定與禁止事後處罰",
        "區分犯罪行為刑事責任與刑罰目的",
        "辨認警察檢察官與法官功能差異",
        "說明無罪推定辯護與公平審判意義",
        "區分報案偵查起訴審判與執行階段",
        "以現行法律核對責任年齡與處理程序",
      ],
    },
    {
      key: "ADMINISTRATIVE_LAW_REMEDIES",
      title: "Administrative law and remedies",
      authorityCodes: ["公Bh-Ⅳ-1", "公Bh-Ⅳ-2", "公Bf-Ⅳ-1", "公Be-Ⅳ-2", "公1a-Ⅳ-1"],
      prerequisiteFamilyKeys: ["CRIMINAL_LAW_DUE_PROCESS"],
      skills: [
        "辨認日常生活中的行政管制與給付",
        "說明依法行政與法律保留的意義",
        "區分行政規則處分與一般政策資訊",
        "判斷行政決定是否說明理由與救濟方式",
        "比較陳情申訴與法定行政救濟",
        "由案例辨識公權力侵害與權益影響",
        "以現行官方程序查證救濟期限與機關",
      ],
    },
    {
      key: "YOUTH_ONLINE_LEGAL_RISK",
      title: "Youth rights, online behavior and legal risk",
      authorityCodes: ["公Bk-Ⅳ-1", "公Bj-Ⅳ-2", "公Bj-Ⅳ-3", "公Bj-Ⅳ-4", "公Bi-Ⅳ-1", "公De-Ⅳ-1", "公De-Ⅳ-2", "社2c-Ⅳ-2"],
      prerequisiteFamilyKeys: ["ADMINISTRATIVE_LAW_REMEDIES"],
      skills: [
        "辨識兒童少年保護制度的目的",
        "區分網路言論自由與侵害他人權利",
        "分析轉傳影像個資與誹謗等法律風險",
        "辨識網路交易契約與詐騙警訊",
        "理解著作利用需考量授權與合理使用",
        "依事件保留證據尋求可信成人與正式協助",
        "以現行官方來源查證少年相關規定",
      ],
    },
    {
      key: "PROPERTY_CONTRACTS_CONSUMERS",
      title: "Property, contracts and consumer protection",
      authorityCodes: ["公Bj-Ⅳ-1", "公Bj-Ⅳ-2", "公Bj-Ⅳ-3", "公Bj-Ⅳ-4", "公Bj-Ⅳ-5", "公Bn-Ⅳ-2", "公Bn-Ⅳ-3", "公1a-Ⅳ-1"],
      prerequisiteFamilyKeys: ["YOUTH_ONLINE_LEGAL_RISK"],
      skills: [
        "區分所有占有使用與處分的生活情境",
        "辨認買賣租賃借貸等契約關係",
        "檢查契約對象標的價金與重要條款",
        "辨識定型化契約與不合理風險",
        "保存廣告訂單收據與溝通紀錄",
        "比較協商申訴調解與訴訟途徑",
        "以現行官方資訊查證消費者權益",
      ],
    },
    {
      key: "LABOR_EMPLOYMENT_INSURANCE",
      title: "Labor, employment and social insurance",
      authorityCodes: ["公Cd-Ⅳ-1", "公Cd-Ⅳ-2", "公Cd-Ⅳ-3", "公Db-Ⅳ-1", "公Db-Ⅳ-2", "公Da-Ⅳ-2", "社2b-Ⅳ-1"],
      prerequisiteFamilyKeys: ["PROPERTY_CONTRACTS_CONSUMERS"],
      skills: [
        "說明勞動參與對個人與社會的意義",
        "區分有酬工作與無酬照顧勞動",
        "辨識市場勞動中的性別與身分不平等",
        "理解立法保障公平勞動參與的理由",
        "比較雇主勞工與政府的基本責任",
        "說明社會保險分擔風險與保障生活的功能",
      ],
    },
    {
      key: "SCARCITY_OPPORTUNITY_COST",
      title: "Scarcity, choice and opportunity cost",
      authorityCodes: ["公Bl-Ⅳ-1", "公Bl-Ⅳ-2", "公Bl-Ⅳ-3", "公Bl-Ⅳ-5", "公Bm-Ⅳ-1", "公Bm-Ⅳ-2", "公1a-Ⅳ-1"],
      prerequisiteFamilyKeys: ["LABOR_EMPLOYMENT_INSURANCE"],
      skills: [
        "由有限資源與多元欲望辨識稀少性",
        "列出選擇中可行且互斥的方案",
        "找出放棄方案中價值最高者作為機會成本",
        "區分金錢成本與完整機會成本",
        "用機會成本解釋個人家庭與公共選擇",
        "分析誘因改變如何影響選擇",
      ],
    },
    {
      key: "MARKETS_PRICE_FAILURE",
      title: "Markets, price, competition and failure",
      authorityCodes: ["公Bl-Ⅳ-4", "公Bl-Ⅳ-5", "公Bn-Ⅳ-2", "公Bn-Ⅳ-3", "公Cf-Ⅳ-1", "公Cf-Ⅳ-2", "公Cf-Ⅳ-3", "公1a-Ⅳ-1"],
      prerequisiteFamilyKeys: ["SCARCITY_OPPORTUNITY_COST"],
      skills: [
        "說明價格傳遞稀少與選擇訊息",
        "由供需變化判斷價格與數量方向",
        "說明自願交易可能使雙方受益",
        "分析競爭對價格品質與選擇的影響",
        "由進入障礙判斷市場競爭程度",
        "辨識市場無法充分處理的外部成本與資訊問題",
      ],
    },
    {
      key: "FIRMS_PRODUCTION_ENTREPRENEURSHIP",
      title: "Firms, production and entrepreneurship",
      authorityCodes: ["公Cf-Ⅳ-1", "公Cf-Ⅳ-2", "公Cf-Ⅳ-3", "公Bn-Ⅳ-1", "公Bn-Ⅳ-2", "公Bm-Ⅳ-1", "公1b-Ⅳ-1"],
      prerequisiteFamilyKeys: ["MARKETS_PRICE_FAILURE"],
      skills: [
        "辨識生產投入成本收益與風險",
        "說明分工與專業化提高效率的條件",
        "比較價格品質服務與創新競爭方式",
        "分析創業者如何發現需求並承擔風險",
        "判斷企業決策對消費者勞工與環境影響",
        "以完整資料避免只用營收判斷企業表現",
      ],
    },
    {
      key: "MONEY_BANKING_CREDIT_FINANCE",
      title: "Money, banking, credit and personal finance",
      authorityCodes: ["公Bp-Ⅳ-1", "公Bp-Ⅳ-2", "公Bp-Ⅳ-3", "公Bp-Ⅳ-4", "公Bl-Ⅳ-1", "公1a-Ⅳ-1"],
      prerequisiteFamilyKeys: ["FIRMS_PRODUCTION_ENTREPRENEURSHIP"],
      skills: [
        "說明貨幣作為交易計價與保存價值工具",
        "區分現金儲值支付與信用支付",
        "辨識信用卡先消費後付款與借貸風險",
        "由收入支出建立基本預算與緊急準備",
        "比較儲蓄借款利息費用與還款能力",
        "由外幣買賣需求理解匯兌情境",
      ],
    },
    {
      key: "GOVERNMENT_ECONOMIC_POLICY",
      title: "Government revenue, spending and economic policy",
      authorityCodes: ["公Bd-Ⅳ-1", "公Be-Ⅳ-2", "公Bh-Ⅳ-1", "公Da-Ⅳ-3", "公Db-Ⅳ-1", "公Db-Ⅳ-2", "公Bl-Ⅳ-5", "公1c-Ⅳ-1"],
      prerequisiteFamilyKeys: ["MONEY_BANKING_CREDIT_FINANCE"],
      skills: [
        "說明政府收入支出與公共服務關係",
        "辨識稅收使用者付費與政府移轉",
        "分析預算選擇的機會成本",
        "比較效率穩定成長與公平等政策目標",
        "辨識政策利益成本與分配效果",
        "以現行官方預算資料查證公共支出",
      ],
    },
    {
      key: "TRADE_GLOBALIZATION_DIVISION",
      title: "Trade, globalization and international division of labor",
      authorityCodes: ["公Bn-Ⅳ-2", "公Bn-Ⅳ-3", "公Bn-Ⅳ-4", "公Bp-Ⅳ-4", "公Dd-Ⅳ-1", "公Dd-Ⅳ-2", "公1b-Ⅳ-1", "社2a-Ⅳ-3"],
      prerequisiteFamilyKeys: ["GOVERNMENT_ECONOMIC_POLICY"],
      skills: [
        "說明交易與專業分工的可能利益",
        "追蹤商品服務資金與工作跨國流動",
        "比較開放進口對消費者與生產者影響",
        "分析國際分工帶來的效率與依賴",
        "由匯率情境辨識外幣供需角色",
        "評估全球化對不同群體的利弊",
      ],
    },
    {
      key: "WELFARE_POVERTY_SOCIAL_POLICY",
      title: "Welfare, poverty and social policy",
      authorityCodes: ["公Da-Ⅳ-2", "公Da-Ⅳ-3", "公Db-Ⅳ-1", "公Db-Ⅳ-2", "公Cd-Ⅳ-3", "公1c-Ⅳ-1", "社2b-Ⅳ-1"],
      prerequisiteFamilyKeys: ["TRADE_GLOBALIZATION_DIVISION"],
      skills: [
        "區分所得不足多重剝奪與生活風險",
        "說明保障基本生活與人性尊嚴關係",
        "比較社會保險社會救助與福利服務功能",
        "分析普遍給付與需求審查的取捨",
        "評估政策對貧窮風險與工作誘因的影響",
        "以多項資料檢驗社會政策成效",
      ],
    },
    {
      key: "DEMOCRACY_TENSIONS",
      title: "Democracy ideals and real-world tensions",
      authorityCodes: ["公Aa-Ⅳ-2", "公Ab-Ⅳ-1", "公Ad-Ⅳ-2", "公Ca-Ⅳ-1", "公Cb-Ⅳ-1", "公Cc-Ⅳ-1", "公Cc-Ⅳ-2", "公Cc-Ⅳ-3", "公1b-Ⅳ-1", "公1c-Ⅳ-1", "社2c-Ⅳ-2"],
      prerequisiteFamilyKeys: ["WELFARE_POVERTY_SOCIAL_POLICY"],
      skills: [
        "比較人民主權政治平等自由與法治理想",
        "分析多數決與少數權利的緊張",
        "比較效率安全自由與隱私的政策取捨",
        "辨識假訊息極化與政治冷漠的民主風險",
        "以制度程序與證據評估民主品質",
        "提出可受檢驗而非只有口號的改善意見",
      ],
    },
    {
      key: "INTERNATIONAL_GLOBAL_CITIZENSHIP",
      title: "International organizations and global citizenship",
      authorityCodes: ["公Dd-Ⅳ-1", "公Dd-Ⅳ-2", "公Dd-Ⅳ-3", "公Ad-Ⅳ-2", "公1b-Ⅳ-1", "公1c-Ⅳ-1", "社2a-Ⅳ-3", "社2c-Ⅳ-2"],
      prerequisiteFamilyKeys: ["DEMOCRACY_TENSIONS"],
      skills: [
        "區分國家國際組織與非政府組織角色",
        "說明跨國問題需要合作的原因",
        "比較國際規範協調援助與制裁工具",
        "分析臺海關係與我國國際參與處境",
        "由多國資料理解全球責任分配爭議",
        "以人權互惠與永續觀點評估全球公民行動",
      ],
    },
    {
      key: "DIGITAL_CITIZENSHIP_PRIVACY",
      title: "Digital citizenship, privacy and information literacy",
      authorityCodes: ["公Cb-Ⅳ-2", "公De-Ⅳ-1", "公De-Ⅳ-2", "公Bj-Ⅳ-3", "公Bj-Ⅳ-4", "公1b-Ⅳ-1", "社3b-Ⅳ-1", "社3b-Ⅳ-2"],
      prerequisiteFamilyKeys: ["INTERNATIONAL_GLOBAL_CITIZENSHIP"],
      skills: [
        "辨識個人資料足跡隱私與同意",
        "比較公開分享與限縮蒐集的風險",
        "查核網路資訊來源日期證據與脈絡",
        "辨識演算法推薦與注意力設計影響",
        "區分引用改作合理使用與侵權風險",
        "設計兼顧參與安全與責任的線上行動",
      ],
    },
    {
      key: "SUSTAINABILITY_PUBLIC_POLICY",
      title: "Sustainability, public policy and evidence-based decisions",
      authorityCodes: ["公Ca-Ⅳ-2", "公Da-Ⅳ-1", "公Da-Ⅳ-2", "公Dd-Ⅳ-1", "公Dd-Ⅳ-2", "公De-Ⅳ-1", "公1a-Ⅳ-1", "公1b-Ⅳ-1", "公1c-Ⅳ-1", "社1a-Ⅳ-1", "社1b-Ⅳ-1", "社1c-Ⅳ-1", "社2a-Ⅳ-1", "社2a-Ⅳ-2", "社2a-Ⅳ-3", "社2b-Ⅳ-1", "社2b-Ⅳ-2", "社2b-Ⅳ-3", "社2c-Ⅳ-1", "社2c-Ⅳ-2", "社2c-Ⅳ-3", "社3a-Ⅳ-1", "社3b-Ⅳ-1", "社3b-Ⅳ-2", "社3b-Ⅳ-3", "社3c-Ⅳ-1", "社3c-Ⅳ-2", "社3d-Ⅳ-1", "社3d-Ⅳ-2", "社3d-Ⅳ-3"],
      prerequisiteFamilyKeys: ["DIGITAL_CITIZENSHIP_PRIVACY"],
      skills: [
        "把公共問題轉成可查證的政策問題",
        "整理利害關係人權利成本與風險",
        "比較政策替代方案與不作為後果",
        "檢查資料品質因果推論與不確定性",
        "選擇兼顧環境社會與世代公平的方案",
        "規劃執行並檢討可持續的公共行動",
      ],
    },
  ],
});
