export const EARTH_SCIENCE_SKILL_PLAN = Object.freeze({
  schemaVersion: "cap8-r4-subject-skill-plan-v1",
  subject: "earth_science",
  expectedSkills: 220,
  expectedAuthorityNodes: 69,
  families: [
    {
      key: "EARTH_SYSTEM_EVIDENCE",
      title: "Earth-system thinking and scientific evidence",
      authorityCodes: ["Fa-Ⅳ-1", "INg-Ⅳ-1", "ah-Ⅳ-1", "ah-Ⅳ-2", "ai-Ⅳ-3", "an-Ⅳ-1", "an-Ⅳ-2", "tm-Ⅳ-1", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: [],
      skills: [
        "辨認大氣圈水圈與岩石圈的主要組成",
        "追蹤太陽能在地球各系統間的流動",
        "說明地球系統間物質與能量的交互作用",
        "區分地球科學觀察資料與推論",
        "依問題界定系統範圍與重要變因",
        "比較不同證據來源的可靠性與限制",
        "評估地球系統模型能解釋與省略之處",
        "以證據檢核媒體中的地球科學主張",
      ],
    },
    {
      key: "MINERALS_IDENTIFICATION",
      title: "Minerals and identification properties",
      authorityCodes: ["Fa-Ⅳ-2", "pe-Ⅳ-2", "pa-Ⅳ-2", "pc-Ⅳ-2"],
      prerequisiteFamilyKeys: ["EARTH_SYSTEM_EVIDENCE"],
      skills: [
        "區分礦物與岩石的概念",
        "依顏色條痕與光澤描述礦物",
        "使用硬度比較礦物的相對性質",
        "辨識解理與斷口的差異",
        "以磁性或酸反應補充礦物鑑定",
        "選擇不破壞樣本的優先檢測順序",
        "由多項性質排除不符合的礦物",
        "記錄礦物檢測證據並說明鑑定限制",
      ],
    },
    {
      key: "THREE_ROCK_TYPES",
      title: "Igneous, sedimentary and metamorphic rocks",
      authorityCodes: ["Fa-Ⅳ-2", "pe-Ⅳ-2", "pa-Ⅳ-2", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["MINERALS_IDENTIFICATION"],
      skills: [
        "依形成方式區分火成沉積與變質岩",
        "由晶粒與構造判讀火成岩冷卻環境",
        "由層理顆粒或化石辨識沉積岩線索",
        "由片理與再結晶辨識變質作用線索",
        "比較岩石組成與礦物顆粒特徵",
        "連結常見岩石性質與生活用途",
        "由樣本證據判斷岩石類別而非只看顏色",
        "說明單一外觀不足以確定岩石成因",
      ],
    },
    {
      key: "ROCK_CYCLE_MATERIALS",
      title: "Rock cycle and Earth materials",
      authorityCodes: ["Fa-Ⅳ-2", "Ia-Ⅳ-1", "INg-Ⅳ-1", "tm-Ⅳ-1", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["THREE_ROCK_TYPES"],
      skills: [
        "連結冷卻凝固與火成岩形成",
        "連結風化搬運沉積成岩作用",
        "連結高溫高壓與變質岩形成",
        "由熔融作用判斷岩石循環路徑",
        "用箭頭圖表示岩石類型間轉換",
        "判斷同一岩石可能經歷的多種後續變化",
        "由地表與地下條件解釋轉換所需時間",
        "評估岩石循環模型沒有固定起點的意義",
      ],
    },
    {
      key: "EARTH_INTERIOR_SEISMIC",
      title: "Earth interior and seismic evidence",
      authorityCodes: ["Ia-Ⅳ-2", "Ia-Ⅳ-3", "Md-Ⅳ-4", "pa-Ⅳ-1", "pa-Ⅳ-2", "tm-Ⅳ-1"],
      prerequisiteFamilyKeys: ["ROCK_CYCLE_MATERIALS"],
      skills: [
        "區分地殼地函與地核的基本位置",
        "由地震波資料推論地球內部具有分層",
        "比較P波與S波的傳播特性",
        "由地震波到時差理解震源距離資訊",
        "說明人類無法直接觀察全部地球內部",
        "比較物質組成分層與力學性質分層概念",
        "用剖面模型連結岩石圈與板塊",
        "評估地球內部模型隨新證據修正的原因",
      ],
    },
    {
      key: "PLATE_TECTONICS_BOUNDARIES",
      title: "Plate tectonics and boundary processes",
      authorityCodes: ["Ia-Ⅳ-2", "Ia-Ⅳ-3", "Ia-Ⅳ-4", "pa-Ⅳ-1", "tm-Ⅳ-1", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["EARTH_INTERIOR_SEISMIC"],
      skills: [
        "由全球地震火山分布辨認板塊邊界",
        "區分張裂聚合與錯動型板塊邊界",
        "解釋張裂邊界的地形與岩漿活動",
        "解釋聚合邊界的隱沒碰撞與造山",
        "解釋錯動邊界的相對運動與地震",
        "由海陸板塊組合判讀可能地質作用",
        "用剖面圖連結板塊運動與地表現象",
        "避免把板塊邊界誤認為國界或海岸線",
      ],
    },
    {
      key: "EARTHQUAKES_HAZARDS",
      title: "Earthquakes, waves and hazard interpretation",
      authorityCodes: ["Ia-Ⅳ-3", "Ia-Ⅳ-4", "Md-Ⅳ-4", "pa-Ⅳ-1", "pa-Ⅳ-2", "pc-Ⅳ-2"],
      prerequisiteFamilyKeys: ["PLATE_TECTONICS_BOUNDARIES"],
      skills: [
        "區分震源震央與震源深度",
        "區分地震規模與各地震度",
        "由P波S波到時判讀地震紀錄",
        "比較距震央遠近與搖晃到達時間",
        "由等震度圖分析地表影響差異",
        "解釋地質地形與建物會改變災害程度",
        "閱讀地震報告而不把規模當成震度",
        "依情境選擇地震前中後的安全行動",
      ],
    },
    {
      key: "VOLCANOES_HAZARDS",
      title: "Volcanoes and volcanic hazards",
      authorityCodes: ["Ia-Ⅳ-3", "Ia-Ⅳ-4", "INg-Ⅳ-1", "Md-Ⅳ-4", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["EARTHQUAKES_HAZARDS"],
      skills: [
        "連結岩漿上升與火山活動",
        "辨認熔岩火山灰與火山氣體等產物",
        "比較岩漿性質與噴發方式的基本關係",
        "由全球分布圖連結火山與板塊邊界",
        "區分火山直接危害與後續環境影響",
        "由地形沉積與監測資料辨識火山證據",
        "說明休眠狀態不代表未來沒有活動",
        "依警戒資訊規劃火山災害避難原則",
      ],
    },
    {
      key: "GEOLOGIC_TIME_FOSSILS",
      title: "Geologic time, fossils and relative dating",
      authorityCodes: ["Hb-Ⅳ-1", "Hb-Ⅳ-2", "Ia-Ⅳ-1", "pa-Ⅳ-1", "pa-Ⅳ-2", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["VOLCANOES_HAZARDS"],
      skills: [
        "用疊置原理判斷未翻轉地層先後",
        "用截切關係判斷斷層或岩脈年代",
        "由沉積接觸關係辨認地質事件順序",
        "以化石比較不同地層的相對年代",
        "區分相對年代與實際年數",
        "從褶皺侵蝕沉積重建事件序列",
        "辨識證據不足時不能唯一排序的情況",
        "用時間尺度理解地球歷史遠長於人類歷史",
      ],
    },
    {
      key: "WEATHERING_EROSION_DEPOSITION",
      title: "Weathering, erosion, transport and deposition",
      authorityCodes: ["Ia-Ⅳ-1", "Fa-Ⅳ-1", "INg-Ⅳ-1", "pa-Ⅳ-1", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["GEOLOGIC_TIME_FOSSILS"],
      skills: [
        "區分風化侵蝕搬運與沉積",
        "比較物理風化與化學風化作用",
        "由水流風冰與重力判斷主要外營力",
        "連結流速改變與顆粒搬運沉積",
        "由顆粒大小圓度與分選推論搬運歷程",
        "辨認侵蝕地形與沉積地形的證據",
        "解釋內營力與外營力共同塑造地貌",
        "由連續影像判斷地貌改變不是瞬間完成",
      ],
    },
    {
      key: "RIVERS_GROUNDWATER_RESOURCES",
      title: "Rivers, groundwater and water resources",
      authorityCodes: ["Fa-Ⅳ-1", "Ia-Ⅳ-1", "INg-Ⅳ-1", "Na-Ⅳ-6", "Na-Ⅳ-7", "pa-Ⅳ-2"],
      prerequisiteFamilyKeys: ["WEATHERING_EROSION_DEPOSITION"],
      skills: [
        "由地形坡度判斷地表逕流方向",
        "比較河流上中下游侵蝕搬運與沉積",
        "由河道彎曲判讀凹岸侵蝕與凸岸沉積",
        "說明入滲地下水面與含水層概念",
        "比較地表水與地下水補注時間",
        "由用水資料評估供需與水質風險",
        "提出兼顧補注與節水的水資源方案",
      ],
    },
    {
      key: "OCEANS_CURRENTS_COASTS",
      title: "Oceans, currents, waves and coasts",
      authorityCodes: ["Fa-Ⅳ-5", "Ic-Ⅳ-1", "Ic-Ⅳ-2", "Ic-Ⅳ-3", "Ia-Ⅳ-1", "pa-Ⅳ-1"],
      prerequisiteFamilyKeys: ["RIVERS_GROUNDWATER_RESOURCES"],
      skills: [
        "比較海水鹽度溫度與密度的基本差異",
        "區分波浪海流與潮汐的運動方式",
        "由風向與海陸分布理解表層海流",
        "判讀臺灣附近海流的季節變化",
        "說明暖流寒流對沿岸氣候的影響",
        "由波浪方向判讀海岸侵蝕與沉積",
        "整合海流圖水溫圖與海岸資料形成解釋",
      ],
    },
    {
      key: "ATMOSPHERE_STRUCTURE_COMPOSITION",
      title: "Atmosphere structure and composition",
      authorityCodes: ["Fa-Ⅳ-1", "Fa-Ⅳ-3", "Fa-Ⅳ-4", "INg-Ⅳ-1", "INg-Ⅳ-2", "pa-Ⅳ-1"],
      prerequisiteFamilyKeys: ["OCEANS_CURRENTS_COASTS"],
      skills: [
        "說明大氣主要由氮氣與氧氣組成",
        "辨認水氣二氧化碳等變動氣體",
        "由溫度隨高度變化區分大氣分層",
        "比較對流層與平流層的主要特徵",
        "連結天氣現象主要發生在對流層",
        "說明臭氧層位置與吸收紫外線作用",
        "由垂直剖面圖判讀高度溫度與層界",
      ],
    },
    {
      key: "WEATHER_ELEMENTS_INSTRUMENTS",
      title: "Weather elements and instruments",
      authorityCodes: ["Ib-Ⅳ-1", "Ib-Ⅳ-2", "Ib-Ⅳ-4", "pe-Ⅳ-2", "pa-Ⅳ-1", "pc-Ⅳ-2"],
      prerequisiteFamilyKeys: ["ATMOSPHERE_STRUCTURE_COMPOSITION"],
      skills: [
        "區分氣溫氣壓濕度風與降水等天氣要素",
        "選擇溫度計氣壓計與濕度計量測要素",
        "使用風向風速與雨量資料描述天氣",
        "依儀器位置與讀值時間控制觀測條件",
        "把逐時觀測整理成表格與折線圖",
        "辨識單次讀值不足以代表長期氣候",
        "比較地面觀測雷達與衛星資料的用途",
      ],
    },
    {
      key: "AIR_PRESSURE_WIND_CIRCULATION",
      title: "Air pressure, wind and circulation",
      authorityCodes: ["Ib-Ⅳ-2", "Ib-Ⅳ-3", "INg-Ⅳ-1", "pa-Ⅳ-1", "tm-Ⅳ-1"],
      prerequisiteFamilyKeys: ["WEATHER_ELEMENTS_INSTRUMENTS"],
      skills: [
        "由氣壓差判斷近地面空氣流動方向",
        "用等壓線疏密比較氣壓梯度與風勢",
        "辨認北半球高低氣壓的環流方向",
        "連結地球自轉與大尺度風向偏轉",
        "比較海陸受熱差異造成的局部環流",
        "由地形判斷風向與降水可能改變",
        "用氣壓風向資料檢查環流模型是否合理",
      ],
    },
    {
      key: "AIR_MASSES_FRONTS_MAPS",
      title: "Air masses, fronts and weather maps",
      authorityCodes: ["Ib-Ⅳ-1", "Ib-Ⅳ-2", "Ib-Ⅳ-3", "Ib-Ⅳ-4", "pa-Ⅳ-1", "pa-Ⅳ-2"],
      prerequisiteFamilyKeys: ["AIR_PRESSURE_WIND_CIRCULATION"],
      skills: [
        "依源地判斷氣團溫度與濕度特性",
        "區分冷鋒暖鋒與滯留鋒符號",
        "比較不同鋒面通過前後的天氣變化",
        "由溫度氣壓風向資料定位鋒面",
        "讀取地面天氣圖的高低氣壓與等壓線",
        "整合衛星雲圖與雷達回波判讀降雨區",
        "用連續天氣圖推估系統移動而非只看單張",
      ],
    },
    {
      key: "TYPHOONS_MONSOONS_SEVERE",
      title: "Typhoons, monsoons and severe weather",
      authorityCodes: ["Ib-Ⅳ-5", "Ib-Ⅳ-6", "Md-Ⅳ-2", "Md-Ⅳ-3", "INg-Ⅳ-1", "pa-Ⅳ-1"],
      prerequisiteFamilyKeys: ["AIR_MASSES_FRONTS_MAPS"],
      skills: [
        "辨認颱風形成所需的暖海面與大氣條件",
        "由路徑暴風圈與預報時間判讀風險",
        "區分颱風中心位置與最強風雨區域",
        "解釋狂風豪雨暴潮等颱風危害",
        "比較東北季風與西南季風造成的季節差異",
        "連結梅雨寒潮乾旱與臺灣天氣型態",
        "依官方警報與在地條件選擇防災行動",
      ],
    },
    {
      key: "CLIMATE_SYSTEMS_GRAPHS",
      title: "Climate systems and climate graphs",
      authorityCodes: ["Ib-Ⅳ-6", "Ic-Ⅳ-2", "Id-Ⅳ-1", "Id-Ⅳ-2", "Id-Ⅳ-3", "INg-Ⅳ-3", "pa-Ⅳ-1", "pa-Ⅳ-2"],
      prerequisiteFamilyKeys: ["TYPHOONS_MONSOONS_SEVERE"],
      skills: [
        "區分短期天氣與長期氣候統計",
        "讀取月均溫與月降水氣候圖",
        "比較緯度海陸分布地形與海流對氣候影響",
        "連結日照角度與地表吸收能量差異",
        "說明水陸比熱差異對溫度變化的影響",
        "由季節風與降水資料比較臺灣區域氣候",
        "用多年資料檢查氣候結論而非單一事件",
      ],
    },
    {
      key: "TAIWAN_GEOLOGY_HAZARDS",
      title: "Taiwan geology and natural hazards",
      authorityCodes: ["Ia-Ⅳ-2", "Ia-Ⅳ-3", "Ia-Ⅳ-4", "Md-Ⅳ-4", "Md-Ⅳ-5", "pa-Ⅳ-1", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["CLIMATE_SYSTEMS_GRAPHS"],
      skills: [
        "連結臺灣位置與歐亞板塊菲律賓海板塊互動",
        "由地形地震火山分布辨識板塊作用證據",
        "說明造山作用與臺灣地形起伏的關係",
        "區分地震危害與地震引發的次生災害",
        "由坡度地層方向與降雨判斷山崩風險",
        "辨識順向坡不等於每次都必然發生山崩",
        "整合地質圖雨量圖與聚落資料評估風險",
      ],
    },
    {
      key: "EARTH_MOON_SUN_MOTIONS",
      title: "Earth-Moon-Sun motions",
      authorityCodes: ["Fb-Ⅳ-1", "Fb-Ⅳ-3", "Fb-Ⅳ-4", "Id-Ⅳ-1", "Id-Ⅳ-3", "tm-Ⅳ-1"],
      prerequisiteFamilyKeys: ["TAIWAN_GEOLOGY_HAZARDS"],
      skills: [
        "區分地球自轉公轉與月球公轉",
        "由觀察者位置說明天體視運動",
        "比較恆星日行與太陽東升西落的共同原因",
        "用日月地相對位置解釋週期現象",
        "區分軌道運動與天體本身自轉",
        "由比例模型說明示意圖不代表真實距離",
        "判讀俯視與側視天體運動圖的一致關係",
      ],
    },
    {
      key: "DAY_NIGHT_SEASONS_CALENDARS",
      title: "Day/night, seasons and calendars",
      authorityCodes: ["Fb-Ⅳ-1", "Id-Ⅳ-1", "Id-Ⅳ-2", "Id-Ⅳ-3", "pa-Ⅳ-1", "tm-Ⅳ-1"],
      prerequisiteFamilyKeys: ["EARTH_MOON_SUN_MOTIONS"],
      skills: [
        "由地球自轉解釋晝夜交替",
        "由自轉方向判斷不同地區先後見到日出",
        "比較不同季節的晝夜長短",
        "由太陽高度角比較地表受能量大小",
        "說明地軸傾斜與公轉共同造成四季",
        "排除地球離太陽遠近是四季主因的誤解",
        "連結地球公轉週期與曆年調整概念",
      ],
    },
    {
      key: "MOON_PHASES_ECLIPSES_TIDES",
      title: "Moon phases, eclipses and tides",
      authorityCodes: ["Fb-Ⅳ-3", "Fb-Ⅳ-4", "Ic-Ⅳ-1", "Ic-Ⅳ-4", "pa-Ⅳ-1", "tm-Ⅳ-1"],
      prerequisiteFamilyKeys: ["DAY_NIGHT_SEASONS_CALENDARS"],
      skills: [
        "由日月地位置判斷月相",
        "連結月相名稱出沒時間與可見方向",
        "說明月相來自受光面可見比例而非月影",
        "判斷日食發生時的天體排列",
        "判斷月食發生時的天體排列",
        "由日月引潮力理解潮汐週期",
        "比較大潮小潮與月相的關係",
      ],
    },
    {
      key: "SOLAR_SYSTEM_SCALE",
      title: "Solar system objects and scale",
      authorityCodes: ["Fb-Ⅳ-1", "Fb-Ⅳ-2", "pa-Ⅳ-1", "pc-Ⅳ-2", "tm-Ⅳ-1"],
      prerequisiteFamilyKeys: ["MOON_PHASES_ECLIPSES_TIDES"],
      skills: [
        "說明太陽是太陽系主要成員與能量來源",
        "依繞日軌道辨認行星的共同特徵",
        "比較類地行星環境的基本差異",
        "區分行星衛星小行星與彗星",
        "用科學記號或比例尺比較天體尺度",
        "說明太陽系示意圖常放大天體而壓縮距離",
        "由資料表比較天體而不以圖中大小直接判斷",
      ],
    },
    {
      key: "STARS_BRIGHTNESS_LIFE",
      title: "Stars, brightness, color and life cycles",
      authorityCodes: ["Ed-Ⅳ-1", "Ed-Ⅳ-2", "INg-Ⅳ-1", "an-Ⅳ-2", "pa-Ⅳ-1"],
      prerequisiteFamilyKeys: ["SOLAR_SYSTEM_SCALE"],
      skills: [
        "辨認太陽是一顆恆星",
        "區分恆星自行發光與行星反射光",
        "說明視亮度同時受發光能力與距離影響",
        "由恆星顏色比較表面溫度高低",
        "依質量差異理解恆星演化路徑不同",
        "排列恆星形成主序與末期變化的基本順序",
        "說明恆星生命史模型來自長期多種觀測證據",
      ],
    },
    {
      key: "GALAXIES_UNIVERSE",
      title: "Galaxies, universe and observation",
      authorityCodes: ["Ed-Ⅳ-1", "Ed-Ⅳ-2", "pa-Ⅳ-1", "tm-Ⅳ-1", "tr-Ⅳ-1"],
      prerequisiteFamilyKeys: ["STARS_BRIGHTNESS_LIFE"],
      skills: [
        "說明星系由大量恆星與其他物質組成",
        "辨認太陽是銀河系成員而非宇宙中心",
        "區分太陽系銀河系與宇宙的尺度層級",
        "由影像特徵辨認常見星系外形",
        "使用光年表達巨大距離而非時間",
        "比較不同波段觀測提供的天體資訊",
        "說明宇宙模型會隨觀測證據更新",
      ],
    },
    {
      key: "ASTRONOMICAL_INSTRUMENTS_MAPS",
      title: "Astronomical instruments and sky maps",
      authorityCodes: ["Ed-Ⅳ-1", "Ed-Ⅳ-2", "Fb-Ⅳ-1", "pe-Ⅳ-2", "pc-Ⅳ-2", "Mb-Ⅳ-2", "an-Ⅳ-3"],
      prerequisiteFamilyKeys: ["GALAXIES_UNIVERSE"],
      skills: [
        "依觀測目標選擇肉眼雙筒鏡或望遠鏡",
        "說明望遠鏡集光能力與口徑的關係",
        "辨認觀測太陽必須使用合格安全設備",
        "依方位高度與時間讀取簡化星圖",
        "考量緯度季節與光害規劃觀測",
        "比較可見光電波與太空望遠鏡的觀測限制",
        "由科學史案例評估儀器如何改變天文理解",
      ],
    },
    {
      key: "SPACE_EXPLORATION_SATELLITES",
      title: "Space exploration and satellites",
      authorityCodes: ["Fb-Ⅳ-1", "Fb-Ⅳ-2", "INg-Ⅳ-6", "ah-Ⅳ-1", "ah-Ⅳ-2", "pc-Ⅳ-1"],
      prerequisiteFamilyKeys: ["ASTRONOMICAL_INSTRUMENTS_MAPS"],
      skills: [
        "區分人造衛星與自然衛星",
        "連結衛星軌道與通訊定位氣象觀測用途",
        "比較地面遙測與衛星觀測的資訊範圍",
        "由任務目標判斷探測器所需儀器",
        "評估太空探索資料的證據與不確定性",
        "分析太空科技效益資源需求與環境影響",
        "查核太空新聞是否提供來源日期與可驗證資料",
      ],
    },
    {
      key: "CLIMATE_CHANGE_EVIDENCE",
      title: "Climate change evidence and mechanisms",
      authorityCodes: ["INg-Ⅳ-2", "INg-Ⅳ-3", "INg-Ⅳ-4", "INg-Ⅳ-5", "INg-Ⅳ-6", "INg-Ⅳ-7", "INg-Ⅳ-8", "INg-Ⅳ-9", "Nb-Ⅳ-2", "Nb-Ⅳ-3", "pa-Ⅳ-1", "pa-Ⅳ-2"],
      prerequisiteFamilyKeys: ["SPACE_EXPLORATION_SATELLITES"],
      skills: [
        "區分自然溫室效應與人為增強效應",
        "追蹤碳在大氣海洋生物與岩石圈間流動",
        "由長期多來源資料辨識氣候變遷證據",
        "連結溫室氣體增加與全球能量收支改變",
        "分析升溫海平面與異常降水等連鎖衝擊",
        "區分氣候變遷減緩與調適措施",
        "評估氣候主張時區分趨勢變動與單一天氣事件",
      ],
    },
    {
      key: "DISASTER_SUSTAINABILITY",
      title: "Disaster prevention and sustainability",
      authorityCodes: ["Md-Ⅳ-2", "Md-Ⅳ-3", "Md-Ⅳ-4", "Md-Ⅳ-5", "Na-Ⅳ-6", "Na-Ⅳ-7", "INg-Ⅳ-5", "INg-Ⅳ-6", "INg-Ⅳ-8", "INg-Ⅳ-9", "Ma-Ⅳ-5", "ah-Ⅳ-2"],
      prerequisiteFamilyKeys: ["CLIMATE_CHANGE_EVIDENCE"],
      skills: [
        "區分天然危害暴露度脆弱度與災害風險",
        "依地震颱風洪水與山崩情境選擇應變",
        "由風險圖規劃避難路線集合點與替代方案",
        "比較工程防護預警土地使用與教育措施",
        "把減量回收再利用與綠能連結永續目標",
        "結合在地與原住民族知識評估環境調適",
        "依成本效益公平與不確定性比較防災方案",
      ],
    },
    {
      key: "INTEGRATED_EARTH_DATA_REASONING",
      title: "Integrated maps, satellite data, graphs and system reasoning",
      authorityCodes: ["ah-Ⅳ-1", "ah-Ⅳ-2", "ai-Ⅳ-1", "ai-Ⅳ-2", "ai-Ⅳ-3", "an-Ⅳ-1", "an-Ⅳ-2", "an-Ⅳ-3", "pa-Ⅳ-1", "pa-Ⅳ-2", "pc-Ⅳ-1", "pc-Ⅳ-2", "pe-Ⅳ-1", "pe-Ⅳ-2", "po-Ⅳ-1", "po-Ⅳ-2", "tc-Ⅳ-1", "ti-Ⅳ-1", "tm-Ⅳ-1", "tr-Ⅳ-1", "Mb-Ⅳ-2"],
      prerequisiteFamilyKeys: ["DISASTER_SUSTAINABILITY"],
      skills: [
        "把地圖剖面衛星圖與時間序列對準共同時空範圍",
        "由多變量資料找出關聯並避免直接斷言因果",
        "提出可由地球科學資料檢驗的問題與假說",
        "規劃重複觀測控制條件與資料品質檢查",
        "比較模型預測與實際觀測並說明偏差來源",
        "整合多項證據形成結論並標示不確定性",
        "以圖表文字與來源資訊完整溝通探究結果",
      ],
    },
  ],
});
