export const ENGLISH_SKILL_PLAN = Object.freeze({
  schemaVersion: "cap8-r4-subject-skill-plan-v1",
  subject: "english",
  expectedSkills: 320,
  expectedAuthorityNodes: 116,
  families: [
    {
      key: "ALPHABET_SPELLING_PHONICS",
      title: "Alphabet, spelling, phonics and sound-symbol awareness",
      authorityCodes: ["Aa-Ⅳ-1", "Ab-Ⅳ-2", "Ab-Ⅳ-3", "1-Ⅳ-10", "3-Ⅳ-1", "3-Ⅳ-2", "4-Ⅳ-1", "5-Ⅳ-4", "5-Ⅳ-5"],
      prerequisiteFamilyKeys: [],
      skills: [
        "辨認連續書寫體的大寫與小寫字母",
        "連結字母名稱與常見字母音",
        "辨識單音節字的起首音與結尾音",
        "運用短母音拼讀常見單音節字",
        "運用字尾e判讀常見長母音",
        "辨識常見子音組合與字母組合音",
        "用拼讀規則檢查基本字詞的拼寫",
      ],
    },
    {
      key: "CLASSROOM_LANGUAGE",
      title: "Classroom language and learning instructions",
      authorityCodes: ["Ac-Ⅳ-2", "1-Ⅳ-1", "1-Ⅳ-2", "2-Ⅳ-1", "2-Ⅳ-3", "6-Ⅳ-1", "6-Ⅳ-2", "7-Ⅳ-5"],
      prerequisiteFamilyKeys: ["ALPHABET_SPELLING_PHONICS"],
      skills: [
        "聽辨課堂中常見的單一步驟指令",
        "依序執行含兩個動作的課堂指令",
        "看懂課本與作業中的常見指示語",
        "用英語請求重說或進一步說明",
        "用簡短英語回應點名與課堂提問",
        "從課堂指示判斷應使用的學習材料",
        "依課堂任務整理預習與複習重點",
      ],
    },
    {
      key: "PERSONAL_INFORMATION",
      title: "Personal information, greetings and introductions",
      authorityCodes: ["Ac-Ⅳ-3", "B-Ⅳ-1", "B-Ⅳ-5", "2-Ⅳ-2", "2-Ⅳ-4", "2-Ⅳ-6", "2-Ⅳ-7", "2-Ⅳ-13"],
      prerequisiteFamilyKeys: ["CLASSROOM_LANGUAGE"],
      skills: [
        "依情境選用合宜的問候與道別語",
        "交換姓名年齡年級與居住地資訊",
        "介紹自己與他人的基本身分",
        "詢問並回答興趣與日常活動",
        "介紹家人朋友及彼此關係",
        "依正式程度選擇稱呼與開場方式",
        "在初次見面對話中維持自然輪替",
      ],
    },
    {
      key: "PRONOUNS_BE_EXISTENTIAL",
      title: "Pronouns, be verbs and existential structures",
      authorityCodes: ["Ad-Ⅳ-1", "B-Ⅳ-2", "1-Ⅳ-3", "3-Ⅳ-6", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["PERSONAL_INFORMATION"],
      skills: [
        "依先行對象選用正確人稱代名詞",
        "依主詞與時態選用be動詞",
        "組成be動詞肯定句與否定句",
        "組成be動詞問句與簡答",
        "區分主格代名詞與受格代名詞",
        "使用there is與there are描述存在",
        "依單複數與時態調整存在句",
      ],
    },
    {
      key: "ARTICLES_DEMONSTRATIVES_DETERMINERS",
      title: "Articles, demonstratives and determiners",
      authorityCodes: ["Ad-Ⅳ-1", "B-Ⅳ-2", "1-Ⅳ-3", "3-Ⅳ-6", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["PRONOUNS_BE_EXISTENTIAL"],
      skills: [
        "依可數單數名詞選用a或an",
        "判斷何時使用定冠詞the",
        "辨識零冠詞的基本使用情境",
        "依距離與單複數選用指示詞",
        "使用this與that指涉單一事物",
        "使用these與those指涉複數事物",
        "整合冠詞指示詞與名詞形成名詞組",
      ],
    },
    {
      key: "COUNTABILITY_QUANTITY",
      title: "Singular/plural, countability and quantity",
      authorityCodes: ["Ad-Ⅳ-1", "B-Ⅳ-2", "1-Ⅳ-3", "3-Ⅳ-6", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["ARTICLES_DEMONSTRATIVES_DETERMINERS"],
      skills: [
        "形成規則名詞複數並辨識拼字變化",
        "辨識常見不規則名詞複數",
        "區分可數名詞與不可數名詞",
        "依名詞類型選用many與much",
        "依語意選用some與any",
        "使用a few與a little表示少量",
        "使用a lot of與enough表達數量",
      ],
    },
    {
      key: "POSSESSION",
      title: "Possession and possessive forms",
      authorityCodes: ["Ad-Ⅳ-1", "B-Ⅳ-1", "B-Ⅳ-2", "2-Ⅳ-4", "3-Ⅳ-6", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["COUNTABILITY_QUANTITY"],
      skills: [
        "用所有格符號表示單數名詞的所有關係",
        "用所有格符號表示規則複數名詞的所有關係",
        "區分所有格形容詞與所有格代名詞",
        "依指涉對象選用正確所有格形式",
        "使用whose詢問物品或關係的歸屬",
        "使用of片語表達事物之間的所屬關係",
        "避免在人稱代名詞所有格中誤加撇號",
      ],
    },
    {
      key: "PRESENT_SIMPLE",
      title: "Present simple and frequency",
      authorityCodes: ["Ad-Ⅳ-1", "B-Ⅳ-2", "B-Ⅳ-5", "1-Ⅳ-3", "2-Ⅳ-6", "3-Ⅳ-6", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["POSSESSION"],
      skills: [
        "用現在簡單式表達習慣與事實",
        "依第三人稱單數變化動詞",
        "使用do與does形成現在式問句",
        "使用do not與does not形成否定句",
        "依主詞選用現在式簡短回答",
        "將頻率副詞放在句中正確位置",
        "依時間線索判斷現在簡單式",
      ],
    },
    {
      key: "PRESENT_PROGRESSIVE",
      title: "Present progressive and current situations",
      authorityCodes: ["Ad-Ⅳ-1", "B-Ⅳ-2", "B-Ⅳ-5", "1-Ⅳ-3", "2-Ⅳ-6", "3-Ⅳ-6", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["PRESENT_SIMPLE"],
      skills: [
        "用現在進行式表達正在發生的動作",
        "依主詞選用be動詞搭配現在分詞",
        "形成現在分詞的規則拼字變化",
        "組成現在進行式問句與否定句",
        "區分現在簡單式與現在進行式",
        "依now與look等線索判斷進行式",
        "辨識通常不使用進行式的狀態動詞",
      ],
    },
    {
      key: "PAST_SIMPLE",
      title: "Past simple and past-time narratives",
      authorityCodes: ["Ad-Ⅳ-1", "Ae-Ⅳ-6", "B-Ⅳ-2", "B-Ⅳ-5", "1-Ⅳ-3", "3-Ⅳ-6", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["PRESENT_PROGRESSIVE"],
      skills: [
        "用過去簡單式表達已完成事件",
        "形成規則動詞的過去式",
        "辨識常見不規則動詞過去式",
        "使用did形成過去式問句與否定句",
        "依主詞選用was與were",
        "依過去時間線索選擇正確時態",
        "用過去式排列敘事事件先後",
      ],
    },
    {
      key: "FUTURE_FORMS",
      title: "Future forms, plans and predictions",
      authorityCodes: ["Ad-Ⅳ-1", "B-Ⅳ-2", "B-Ⅳ-4", "B-Ⅳ-5", "1-Ⅳ-3", "2-Ⅳ-5", "3-Ⅳ-6", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["PAST_SIMPLE"],
      skills: [
        "使用will表達預測與當下決定",
        "使用be going to表達已有計畫",
        "依證據選用be going to表達預測",
        "形成未來式問句與否定句",
        "用現在進行式表達確定安排",
        "區分will與be going to的語意",
        "依未來時間線索組成完整句",
      ],
    },
    {
      key: "PRESENT_PERFECT",
      title: "Present perfect and experience/result",
      authorityCodes: ["Ad-Ⅳ-1", "B-Ⅳ-2", "B-Ⅳ-4", "B-Ⅳ-5", "1-Ⅳ-3", "2-Ⅳ-5", "3-Ⅳ-6", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["FUTURE_FORMS"],
      skills: [
        "用現在完成式表達過去經驗",
        "依主詞選用have與has",
        "辨識常見動詞的過去分詞",
        "使用ever與never談論經驗",
        "使用already與yet表達完成狀態",
        "使用since與for表達持續時間",
        "區分現在完成式與明確過去時間",
      ],
    },
    {
      key: "MODAL_VERBS",
      title: "Modal verbs and communicative force",
      authorityCodes: ["Ad-Ⅳ-1", "B-Ⅳ-2", "B-Ⅳ-4", "1-Ⅳ-3", "2-Ⅳ-5", "3-Ⅳ-6", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["PRESENT_PERFECT"],
      skills: [
        "使用can與could表達能力",
        "使用may與might表達可能性",
        "使用must表達必要與強烈推論",
        "使用have to表達外在義務",
        "使用should提出建議",
        "區分must not與do not have to",
        "在情境中判斷助動詞的語氣強度",
      ],
    },
    {
      key: "IMPERATIVES_REQUESTS_OFFERS",
      title: "Imperatives, requests, offers and suggestions",
      authorityCodes: ["Ad-Ⅳ-1", "B-Ⅳ-2", "B-Ⅳ-3", "B-Ⅳ-4", "1-Ⅳ-3", "2-Ⅳ-2", "2-Ⅳ-5", "3-Ⅳ-5", "5-Ⅳ-3", "7-Ⅳ-3"],
      prerequisiteFamilyKeys: ["MODAL_VERBS"],
      skills: [
        "使用肯定與否定祈使句給予指示",
        "以please與could提出禮貌請求",
        "依情境選擇接受或婉拒請求的回應",
        "使用would you like提出邀請或提供",
        "使用let us與how about提出建議",
        "依人際關係調整請求與建議語氣",
        "從回應判斷說話者的真正溝通目的",
      ],
    },
    {
      key: "QUESTION_FORMS",
      title: "Yes/no, wh- and embedded questions",
      authorityCodes: ["Ad-Ⅳ-1", "B-Ⅳ-5", "1-Ⅳ-3", "2-Ⅳ-7", "3-Ⅳ-6", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["IMPERATIVES_REQUESTS_OFFERS"],
      skills: [
        "依句中動詞形成yes-no問句",
        "依所求資訊選擇wh疑問詞",
        "安排wh問句中的助動詞與主詞",
        "區分主詞問句與受詞問句語序",
        "使用how系列問句詢問方式與程度",
        "使用間接問句的直述句語序",
        "依上下文配對問句與合理回答",
      ],
    },
    {
      key: "NEGATION_AGREEMENT_RESPONSES",
      title: "Negation, agreement and short responses",
      authorityCodes: ["Ad-Ⅳ-1", "B-Ⅳ-2", "B-Ⅳ-3", "1-Ⅳ-3", "2-Ⅳ-2", "3-Ⅳ-7", "5-Ⅳ-3"],
      prerequisiteFamilyKeys: ["QUESTION_FORMS"],
      skills: [
        "依助動詞形成正確否定句",
        "避免在同一子句使用雙重否定",
        "依問句動詞選用肯定與否定簡答",
        "使用too與either表示相同情況",
        "使用so與neither形成附和句",
        "辨識否定問句回答所指的事實",
        "依對話內容選擇一致或相反回應",
      ],
    },
    {
      key: "NOUNS_PRONOUNS_REFERENCE",
      title: "Nouns, pronouns and reference",
      authorityCodes: ["Ac-Ⅳ-4", "Ad-Ⅳ-1", "B-Ⅳ-2", "D-Ⅳ-1", "3-Ⅳ-2", "3-Ⅳ-12", "5-Ⅳ-1", "7-Ⅳ-1"],
      prerequisiteFamilyKeys: ["NEGATION_AGREEMENT_RESPONSES"],
      skills: [
        "依句法位置判斷名詞的功能",
        "使用代名詞避免不必要的名詞重複",
        "追蹤人稱代名詞在句中的指涉",
        "追蹤指示代名詞所指的前文資訊",
        "判斷one與ones替代的名詞",
        "依單複數與語意維持指涉一致",
        "排除可能造成兩種解讀的代名詞",
      ],
    },
    {
      key: "ADJECTIVES_COMPARISON",
      title: "Adjectives and comparison",
      authorityCodes: ["Ad-Ⅳ-1", "B-Ⅳ-1", "B-Ⅳ-5", "1-Ⅳ-3", "2-Ⅳ-4", "2-Ⅳ-6", "3-Ⅳ-6", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["NOUNS_PRONOUNS_REFERENCE"],
      skills: [
        "將形容詞放在名詞前或連綴動詞後",
        "形成短形容詞比較級與最高級",
        "形成長形容詞比較級與最高級",
        "辨識不規則比較級與最高級",
        "使用than比較兩個對象",
        "使用as as表達同等比較",
        "從比較範圍判斷最高級結構",
      ],
    },
    {
      key: "ADVERBS_DEGREE_MANNER",
      title: "Adverbs, degree and manner",
      authorityCodes: ["Ad-Ⅳ-1", "B-Ⅳ-2", "B-Ⅳ-5", "1-Ⅳ-3", "2-Ⅳ-6", "3-Ⅳ-6", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["ADJECTIVES_COMPARISON"],
      skills: [
        "區分形容詞與副詞的句法功能",
        "形成常見方式副詞",
        "將方式副詞放在適當句中位置",
        "使用very too與enough表達程度",
        "辨識常見同形形容詞與副詞",
        "使用副詞比較動作方式",
        "依連綴動詞選擇形容詞而非副詞",
      ],
    },
    {
      key: "PREPOSITIONS",
      title: "Prepositions of time, place and movement",
      authorityCodes: ["Ad-Ⅳ-1", "B-Ⅳ-2", "B-Ⅳ-5", "1-Ⅳ-3", "2-Ⅳ-6", "3-Ⅳ-6", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["ADVERBS_DEGREE_MANNER"],
      skills: [
        "依時間尺度選用at on與in",
        "使用before after during與until表達時間關係",
        "依位置關係選用in on與at",
        "使用above below over與under描述位置",
        "使用between among beside與near描述相對位置",
        "使用to into onto與through描述移動",
        "區分arrive in arrive at與reach的結構",
      ],
    },
    {
      key: "CONJUNCTIONS_CLAUSE_RELATIONS",
      title: "Conjunctions and clause relations",
      authorityCodes: ["Ad-Ⅳ-1", "D-Ⅳ-3", "1-Ⅳ-3", "3-Ⅳ-6", "3-Ⅳ-12", "5-Ⅳ-2", "9-Ⅳ-3"],
      prerequisiteFamilyKeys: ["PREPOSITIONS"],
      skills: [
        "使用and連接同類資訊",
        "使用but與yet表達轉折",
        "使用or表達選擇與條件結果",
        "使用because與so區分原因和結果",
        "使用although連接讓步關係",
        "使用when before與after連接時間子句",
        "依邏輯關係選擇適當連接詞",
      ],
    },
    {
      key: "INFINITIVES_GERUNDS_COMPLEMENTS",
      title: "Infinitives, gerunds and complements",
      authorityCodes: ["Ad-Ⅳ-1", "B-Ⅳ-2", "B-Ⅳ-4", "1-Ⅳ-3", "2-Ⅳ-5", "3-Ⅳ-6", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["CONJUNCTIONS_CLAUSE_RELATIONS"],
      skills: [
        "使用不定詞表達目的",
        "辨識後接不定詞的常見動詞",
        "辨識後接動名詞的常見動詞",
        "將動名詞作為句子主詞",
        "區分to作不定詞標記與介系詞",
        "依固定搭配選擇不定詞或動名詞",
        "辨識改變補語後語意不同的常見動詞",
      ],
    },
    {
      key: "PASSIVE_VOICE",
      title: "Passive voice",
      authorityCodes: ["Ad-Ⅳ-1", "Ae-Ⅳ-5", "B-Ⅳ-2", "1-Ⅳ-3", "3-Ⅳ-6", "3-Ⅳ-16", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["INFINITIVES_GERUNDS_COMPLEMENTS"],
      skills: [
        "辨識主動句中的動作者與承受者",
        "用be動詞加過去分詞形成被動語態",
        "依時態調整被動句的be動詞",
        "判斷何時省略被動句的動作者",
        "使用by片語補充必要的動作者",
        "區分被動語態與單純狀態描述",
        "在通知與說明文中判讀被動句焦點",
      ],
    },
    {
      key: "RELATIVE_CLAUSES",
      title: "Relative clauses and modifiers",
      authorityCodes: ["Ad-Ⅳ-1", "Ae-Ⅳ-5", "B-Ⅳ-5", "1-Ⅳ-3", "3-Ⅳ-6", "3-Ⅳ-16", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["PASSIVE_VOICE"],
      skills: [
        "辨識關係子句所修飾的先行詞",
        "依人物或事物選用who與which",
        "使用that連接基本限定關係子句",
        "判斷關係代名詞在子句中的功能",
        "避免在關係子句重複主詞或受詞",
        "整合兩句形成不改變原意的關係子句",
        "用上下文判斷關係子句提供的辨識資訊",
      ],
    },
    {
      key: "CONDITIONALS_HYPOTHETICAL",
      title: "Conditionals and hypothetical meaning",
      authorityCodes: ["Ad-Ⅳ-1", "B-Ⅳ-4", "D-Ⅳ-1", "1-Ⅳ-3", "2-Ⅳ-5", "3-Ⅳ-6", "5-Ⅳ-2", "9-Ⅳ-1"],
      prerequisiteFamilyKeys: ["RELATIVE_CLAUSES"],
      skills: [
        "使用if連接條件與結果",
        "用現在式條件表達一般事實",
        "用第一類條件句表達可能未來",
        "辨識unless所表達的否定條件",
        "避免在一般if子句誤用will",
        "由條件是否成立推論合理結果",
        "辨識基本假設語氣與現實的差距",
      ],
    },
    {
      key: "REPORTED_MEANING_SEQUENCE",
      title: "Reported meaning and sequence",
      authorityCodes: ["Ad-Ⅳ-1", "Ae-Ⅳ-6", "B-Ⅳ-2", "D-Ⅳ-2", "1-Ⅳ-4", "3-Ⅳ-7", "3-Ⅳ-9", "5-Ⅳ-6", "9-Ⅳ-2"],
      prerequisiteFamilyKeys: ["CONDITIONALS_HYPOTHETICAL"],
      skills: [
        "區分直接引語與轉述內容",
        "使用say與tell的正確受詞結構",
        "在轉述中調整人稱代名詞",
        "在轉述中調整時間與地點詞",
        "依敘事時間理解基本時態回溯",
        "轉述對話時保留原說話者意圖",
        "依上下文排列多位說話者的訊息",
      ],
    },
    {
      key: "COMPLEX_PATTERNS",
      title: "Causative/perception/basic complex patterns",
      authorityCodes: ["Ad-Ⅳ-1", "B-Ⅳ-2", "B-Ⅳ-5", "1-Ⅳ-3", "2-Ⅳ-6", "3-Ⅳ-6", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["REPORTED_MEANING_SEQUENCE"],
      skills: [
        "辨識使役動詞後的受詞與動詞形式",
        "使用make加受詞加原形動詞",
        "使用have加受詞加原形動詞",
        "使用let加受詞加原形動詞",
        "依感官動詞判斷原形與現在分詞語意",
        "辨識ask tell want加受詞加不定詞",
        "依句型角色避免重複或缺少受詞",
      ],
    },
    {
      key: "WORD_FORMATION_PARTS_OF_SPEECH",
      title: "Word formation and parts of speech",
      authorityCodes: ["Ac-Ⅳ-4", "Ad-Ⅳ-1", "3-Ⅳ-2", "3-Ⅳ-12", "4-Ⅳ-1", "5-Ⅳ-1", "5-Ⅳ-5", "6-Ⅳ-5", "7-Ⅳ-1"],
      prerequisiteFamilyKeys: ["COMPLEX_PATTERNS"],
      skills: [
        "由句法位置判斷空格所需詞性",
        "辨識常見名詞字尾",
        "辨識常見形容詞字尾",
        "辨識常見副詞字尾",
        "使用否定字首推測詞義方向",
        "依字根與字尾選擇正確詞形",
        "用字典詞性標記確認語境中的詞形",
      ],
    },
    {
      key: "COLLOCATION_CHUNKS_PHRASAL_VERBS",
      title: "Collocation, chunks and phrasal verbs",
      authorityCodes: ["Ac-Ⅳ-3", "Ac-Ⅳ-4", "B-Ⅳ-2", "3-Ⅳ-2", "3-Ⅳ-5", "5-Ⅳ-1", "5-Ⅳ-2"],
      prerequisiteFamilyKeys: ["WORD_FORMATION_PARTS_OF_SPEECH"],
      skills: [
        "辨識常見動詞與名詞搭配",
        "辨識常見形容詞與介系詞搭配",
        "依語境選用日常固定語塊",
        "判讀基本片語動詞的整體意思",
        "區分可分與不可分的常見片語動詞",
        "依受詞位置使用可分片語動詞",
        "排除逐字翻譯造成的不自然搭配",
      ],
    },
    {
      key: "COMMUNICATION_PRAGMATICS",
      title: "Communication functions and pragmatics",
      authorityCodes: ["B-Ⅳ-3", "B-Ⅳ-4", "B-Ⅳ-7", "B-Ⅳ-8", "2-Ⅳ-2", "2-Ⅳ-5", "2-Ⅳ-9", "2-Ⅳ-12", "2-Ⅳ-13", "5-Ⅳ-3", "7-Ⅳ-3"],
      prerequisiteFamilyKeys: ["COLLOCATION_CHUNKS_PHRASAL_VERBS"],
      skills: [
        "從語句判斷請求邀請道歉與感謝功能",
        "依場合選擇直接或較委婉的表達",
        "用澄清問題修復溝通誤解",
        "依表情手勢與語氣補足字面訊息",
        "選擇能延續對話而非中斷話題的回應",
        "在不同意時使用尊重且清楚的說法",
        "依對方需求給予相關而足夠的資訊",
      ],
    },
    {
      key: "SIGNS_NOTICES_LABELS_FORMS",
      title: "Signs, notices, labels and forms",
      authorityCodes: ["Ac-Ⅳ-1", "Ae-Ⅳ-2", "3-Ⅳ-3", "3-Ⅳ-4", "4-Ⅳ-4", "5-Ⅳ-11"],
      prerequisiteFamilyKeys: ["COMMUNICATION_PRAGMATICS"],
      skills: [
        "由標示關鍵字判斷場所與用途",
        "看懂禁止警告與指示類標誌",
        "從營業時間與日期標示判斷限制",
        "讀取票券標籤與簡易使用說明",
        "依欄位名稱填寫個人基本資料",
        "整合表格標題列與資料列取得答案",
        "辨別公告中的對象行動與期限",
      ],
    },
    {
      key: "MESSAGES_EMAILS_LETTERS_POSTS",
      title: "Messages, emails, letters and social posts",
      authorityCodes: ["Ae-Ⅳ-4", "3-Ⅳ-8", "4-Ⅳ-3", "4-Ⅳ-5", "4-Ⅳ-6", "4-Ⅳ-7", "4-Ⅳ-8", "5-Ⅳ-12"],
      prerequisiteFamilyKeys: ["SIGNS_NOTICES_LABELS_FORMS"],
      skills: [
        "辨識簡訊留言與電子郵件的基本格式",
        "從主旨與開頭判斷訊息目的",
        "找出訊息中的時間地點與待辦事項",
        "依收件人關係選擇合宜稱呼與結尾",
        "撰寫包含必要資訊的簡短回覆",
        "辨識社群貼文中的事實與個人反應",
        "比較原訊息與回覆是否完整對應",
      ],
    },
    {
      key: "DIALOG_COHERENCE",
      title: "Dialog and conversational coherence",
      authorityCodes: ["B-Ⅳ-3", "B-Ⅳ-5", "B-Ⅳ-7", "B-Ⅳ-8", "1-Ⅳ-4", "2-Ⅳ-9", "2-Ⅳ-11", "2-Ⅳ-12", "2-Ⅳ-13", "3-Ⅳ-7", "5-Ⅳ-3", "5-Ⅳ-6", "5-Ⅳ-7", "7-Ⅳ-3", "7-Ⅳ-4"],
      prerequisiteFamilyKeys: ["MESSAGES_EMAILS_LETTERS_POSTS"],
      skills: [
        "用前後語意判斷對話缺句",
        "依問句形式選擇直接相關回答",
        "追蹤對話中的人事時地物",
        "辨識話題轉換與承接訊號",
        "依說話者目的排列對話順序",
        "從簡短回應推論同意疑問或拒絕",
      ],
    },
    {
      key: "CLOZE_GRAMMAR_VOCAB_COHESION",
      title: "Cloze: grammar, vocabulary and cohesion",
      authorityCodes: ["Ac-Ⅳ-4", "Ad-Ⅳ-1", "D-Ⅳ-1", "D-Ⅳ-2", "D-Ⅳ-3", "D-Ⅳ-4", "3-Ⅳ-12", "9-Ⅳ-1", "9-Ⅳ-2", "9-Ⅳ-3", "9-Ⅳ-4"],
      prerequisiteFamilyKeys: ["DIALOG_COHERENCE"],
      skills: [
        "由單句結構判斷克漏空格詞性",
        "由時態線索選擇克漏動詞形式",
        "由搭配與語意選擇克漏字詞",
        "由代名詞追蹤克漏段落指涉",
        "由連接詞判斷前後邏輯關係",
        "跨句整合資訊排除局部合理選項",
      ],
    },
    {
      key: "REFERENCE_SUBSTITUTION_MARKERS",
      title: "Reference, substitution and discourse markers",
      authorityCodes: ["D-Ⅳ-1", "D-Ⅳ-2", "D-Ⅳ-3", "3-Ⅳ-12", "9-Ⅳ-1", "9-Ⅳ-2", "9-Ⅳ-3"],
      prerequisiteFamilyKeys: ["CLOZE_GRAMMAR_VOCAB_COHESION"],
      skills: [
        "找出代名詞指向的前文名詞或事件",
        "判斷this與that指涉整句內容",
        "辨識one do so等替代形式",
        "依轉折因果例證標記連結句意",
        "用重複詞與同義詞追蹤段落主題",
        "排除距離較近但語意不合的指涉對象",
      ],
    },
    {
      key: "MAIN_IDEA_TOPIC",
      title: "Main idea and topic",
      authorityCodes: ["Ae-Ⅳ-8", "1-Ⅳ-7", "1-Ⅳ-8", "3-Ⅳ-8", "3-Ⅳ-9", "3-Ⅳ-13", "3-Ⅳ-14", "5-Ⅳ-10"],
      prerequisiteFamilyKeys: ["REFERENCE_SUBSTITUTION_MARKERS"],
      skills: [
        "區分文章主題與單一細節",
        "由重複概念歸納段落大意",
        "由開頭結尾確認全文中心",
        "選擇涵蓋全文且不過度延伸的主旨",
        "為短文選擇不洩漏局部的適切標題",
        "辨識轉折後真正受到強調的主張",
      ],
    },
    {
      key: "EXPLICIT_DETAIL_SCANNING",
      title: "Explicit detail and scanning",
      authorityCodes: ["Ae-Ⅳ-5", "D-Ⅳ-2", "1-Ⅳ-7", "3-Ⅳ-8", "3-Ⅳ-9", "3-Ⅳ-14", "5-Ⅳ-7", "5-Ⅳ-8", "5-Ⅳ-9"],
      prerequisiteFamilyKeys: ["MAIN_IDEA_TOPIC"],
      skills: [
        "由題目關鍵詞定位相同或改寫資訊",
        "掃讀人名數字日期與地點",
        "區分文中明示資訊與選項新增資訊",
        "整合相隔兩句的相關細節",
        "用表格或清單快速核對限制條件",
        "依事件順序回答何時與接著發生什麼",
      ],
    },
    {
      key: "INFERENCE_IMPLIED_MEANING",
      title: "Inference and implied meaning",
      authorityCodes: ["D-Ⅳ-1", "D-Ⅳ-3", "1-Ⅳ-7", "3-Ⅳ-11", "3-Ⅳ-12", "7-Ⅳ-2", "9-Ⅳ-1", "9-Ⅳ-3"],
      prerequisiteFamilyKeys: ["EXPLICIT_DETAIL_SCANNING"],
      skills: [
        "用兩項明示線索推出未直接說明的結果",
        "由人物行動與對話推論感受",
        "由原因與結果推論事件關係",
        "區分合理推論與缺乏證據的猜測",
        "由圖文共同線索推論情境",
        "預測故事下一步且不超出既有線索",
      ],
    },
    {
      key: "VOCABULARY_IN_CONTEXT",
      title: "Vocabulary in context",
      authorityCodes: ["Ac-Ⅳ-4", "D-Ⅳ-1", "3-Ⅳ-2", "3-Ⅳ-12", "6-Ⅳ-5", "7-Ⅳ-1", "9-Ⅳ-1"],
      prerequisiteFamilyKeys: ["INFERENCE_IMPLIED_MEANING"],
      skills: [
        "由同句定義線索推測字義",
        "由例子與對比線索推測字義",
        "由前後因果關係縮小字義範圍",
        "依詞性與搭配排除不合語境的解釋",
        "用字典義項配合上下文選擇字義",
        "區分熟字常見義與文中延伸義",
      ],
    },
    {
      key: "PURPOSE_AUDIENCE_TONE_ATTITUDE",
      title: "Purpose, audience, tone and attitude",
      authorityCodes: ["Ae-Ⅳ-7", "D-Ⅳ-4", "1-Ⅳ-9", "3-Ⅳ-15", "9-Ⅳ-4"],
      prerequisiteFamilyKeys: ["VOCABULARY_IN_CONTEXT"],
      skills: [
        "由文體與內容判斷作者寫作目的",
        "由稱呼資訊與媒介判斷預期讀者",
        "由評價詞判斷敘述者態度",
        "由語調與回應判斷說話者情緒",
        "區分作者陳述事實與表達意見",
        "選擇有文本證據支持的語氣描述",
      ],
    },
    {
      key: "TEXT_ORGANIZATION_SEQUENCE",
      title: "Text organization and sequencing",
      authorityCodes: ["Ae-Ⅳ-6", "Ae-Ⅳ-8", "D-Ⅳ-2", "D-Ⅳ-3", "3-Ⅳ-9", "3-Ⅳ-10", "3-Ⅳ-12", "3-Ⅳ-13", "3-Ⅳ-14", "9-Ⅳ-2", "9-Ⅳ-3"],
      prerequisiteFamilyKeys: ["PURPOSE_AUDIENCE_TONE_ATTITUDE"],
      skills: [
        "依時間詞排列敘事段落",
        "依代名詞與已知資訊判斷句序",
        "辨識總說分說與例證結構",
        "辨識原因結果與問題解決結構",
        "判斷插入句與前後文的銜接位置",
        "由段落功能建立全文架構",
      ],
    },
    {
      key: "CHARTS_SCHEDULES_MENUS_INFOGRAPHICS",
      title: "Charts, schedules, menus and infographics",
      authorityCodes: ["Ae-Ⅳ-2", "B-Ⅳ-6", "2-Ⅳ-10", "3-Ⅳ-4", "4-Ⅳ-2", "4-Ⅳ-4", "5-Ⅳ-11"],
      prerequisiteFamilyKeys: ["TEXT_ORGANIZATION_SEQUENCE"],
      skills: [
        "讀取時刻表的列欄與時間資訊",
        "整合菜單品項價格與限制",
        "由圖例與標籤讀取簡易資訊圖",
        "比較長條折線或圓餅圖中的數值",
        "把圖表資訊轉述為正確英文句",
        "整合圖表與附註解決生活問題",
      ],
    },
    {
      key: "MULTIPLE_DOCUMENTS_COMPARISON",
      title: "Multiple documents and comparison",
      authorityCodes: ["D-Ⅳ-2", "D-Ⅳ-3", "D-Ⅳ-4", "3-Ⅳ-14", "3-Ⅳ-16", "9-Ⅳ-2", "9-Ⅳ-3", "9-Ⅳ-4"],
      prerequisiteFamilyKeys: ["CHARTS_SCHEDULES_MENUS_INFOGRAPHICS"],
      skills: [
        "找出兩份文件的共同資訊",
        "比較兩份文件在目的與對象上的差異",
        "整合公告與時刻表判斷可行選擇",
        "辨識文件間互補或衝突的資訊",
        "依多項條件篩選同時符合的方案",
        "判斷哪份文件能支持特定結論",
      ],
    },
    {
      key: "NARRATIVE_READING",
      title: "Narrative reading",
      authorityCodes: ["Ae-Ⅳ-1", "Ae-Ⅳ-5", "Ae-Ⅳ-6", "Ae-Ⅳ-8", "1-Ⅳ-6", "3-Ⅳ-9", "3-Ⅳ-10", "3-Ⅳ-11", "3-Ⅳ-12", "3-Ⅳ-16", "5-Ⅳ-8", "5-Ⅳ-10"],
      prerequisiteFamilyKeys: ["MULTIPLE_DOCUMENTS_COMPARISON"],
      skills: [
        "辨識故事背景人物事件與結局",
        "依事件與反應追蹤人物目標",
        "辨識造成故事轉折的關鍵事件",
        "由行動與對話推論人物特質",
        "比較故事開始與結尾的人物變化",
        "用因果鏈摘要故事而不堆列細節",
      ],
    },
    {
      key: "EXPOSITORY_SCIENTIFIC_READING",
      title: "Expository/scientific reading",
      authorityCodes: ["Ae-Ⅳ-5", "Ae-Ⅳ-8", "D-Ⅳ-2", "D-Ⅳ-3", "1-Ⅳ-7", "1-Ⅳ-8", "3-Ⅳ-12", "3-Ⅳ-14", "3-Ⅳ-16", "7-Ⅳ-2", "9-Ⅳ-2", "9-Ⅳ-3"],
      prerequisiteFamilyKeys: ["NARRATIVE_READING"],
      skills: [
        "辨識說明文的主題與核心概念",
        "區分定義例子原因與結果",
        "依程序順序理解簡易科學說明",
        "整合文字與數據判斷說明重點",
        "辨識比較分類與問題解決結構",
        "判斷結論是否受到文中證據支持",
      ],
    },
    {
      key: "ARGUMENT_OPINION_MEDIA_LITERACY",
      title: "Argument, opinion and media literacy",
      authorityCodes: ["Ae-Ⅳ-5", "Ae-Ⅳ-7", "D-Ⅳ-4", "3-Ⅳ-15", "3-Ⅳ-16", "6-Ⅳ-3", "6-Ⅳ-4", "6-Ⅳ-6", "7-Ⅳ-2", "7-Ⅳ-4", "9-Ⅳ-4"],
      prerequisiteFamilyKeys: ["EXPOSITORY_SCIENTIFIC_READING"],
      skills: [
        "辨識作者主張與支持理由",
        "區分可查證事實與個人意見",
        "判斷例子是否真正支持主張",
        "辨識廣告與社群貼文的說服目的",
        "比較不同來源對同一事件的觀點",
        "以來源內容而非個人立場評估選項",
      ],
    },
    {
      key: "LISTENING_SENTENCE_PICTURE",
      title: "Listening: sentence-picture recognition",
      authorityCodes: ["Ab-Ⅳ-1", "B-Ⅳ-6", "1-Ⅳ-1", "1-Ⅳ-3", "1-Ⅳ-7", "1-Ⅳ-9", "2-Ⅳ-8", "2-Ⅳ-10", "5-Ⅳ-4"],
      prerequisiteFamilyKeys: ["ARGUMENT_OPINION_MEDIA_LITERACY"],
      skills: [
        "由關鍵名詞配對語句與圖片",
        "由動作與進行狀態區分相似圖片",
        "由位置介系詞判斷物件關係",
        "由人物數量與特徵排除干擾圖",
        "由否定與比較語意避免選反",
        "由重音與語調辨識句子焦點",
      ],
    },
    {
      key: "LISTENING_RESPONSES_DISCOURSE",
      title: "Listening: basic responses and discourse comprehension",
      authorityCodes: ["Ae-Ⅳ-3", "B-Ⅳ-2", "B-Ⅳ-3", "B-Ⅳ-4", "B-Ⅳ-5", "B-Ⅳ-7", "C-Ⅳ-1", "C-Ⅳ-2", "C-Ⅳ-3", "C-Ⅳ-4", "C-Ⅳ-5", "1-Ⅳ-2", "1-Ⅳ-4", "1-Ⅳ-5", "1-Ⅳ-6", "1-Ⅳ-8", "1-Ⅳ-11", "2-Ⅳ-5", "2-Ⅳ-6", "2-Ⅳ-8", "2-Ⅳ-9", "2-Ⅳ-13", "2-Ⅳ-14", "5-Ⅳ-3", "5-Ⅳ-6", "5-Ⅳ-7", "5-Ⅳ-8", "5-Ⅳ-9", "7-Ⅳ-3", "8-Ⅳ-1", "8-Ⅳ-2", "8-Ⅳ-3", "8-Ⅳ-4", "8-Ⅳ-5", "8-Ⅳ-6"],
      prerequisiteFamilyKeys: ["LISTENING_SENTENCE_PICTURE"],
      skills: [
        "依問句功能選擇自然口語回應",
        "由關鍵細節掌握短對話情境",
        "由說話者語氣推論態度與意圖",
        "從簡短敘述擷取人物時間地點與事件",
        "聽懂公共場所廣播的行動與限制",
        "整合多輪對話判斷問題與決定",
      ],
    },
  ],
});
