export const GEOGRAPHY_SKILL_PLAN = Object.freeze({
  schemaVersion: "cap8-r4-subject-skill-plan-v1",
  subject: "geography",
  expectedSkills: 240,
  expectedAuthorityNodes: 94,
  families: [
    {
      key: "GEOGRAPHIC_INQUIRY",
      title: "Geographic inquiry and spatial questions",
      authorityCodes: ["地1a-Ⅳ-1", "地1a-Ⅳ-2", "地1b-Ⅳ-1", "地1b-Ⅳ-2", "地1c-Ⅳ-1", "地1c-Ⅳ-2", "社1a-Ⅳ-1", "社1b-Ⅳ-1", "社1c-Ⅳ-1", "社3a-Ⅳ-1", "社3b-Ⅳ-1", "社3b-Ⅳ-2", "社3c-Ⅳ-1", "社3c-Ⅳ-2", "社3d-Ⅳ-1"],
      prerequisiteFamilyKeys: [],
      skills: [
        "把生活現象轉成可探究的地理問題",
        "區分位置分布互動與變遷問題",
        "由空間尺度界定探究範圍",
        "選擇適合問題的地圖統計與訪查資料",
        "檢查資料來源時間與空間是否相符",
        "以證據解釋自然與人文現象關係",
        "比較多種方案並提出有條件的地理判斷",
      ],
    },
    {
      key: "DIRECTION_COORDINATES_LOCATION",
      title: "Direction, coordinates and location",
      authorityCodes: ["地Aa-Ⅳ-1", "地Aa-Ⅳ-2", "地Aa-Ⅳ-3", "地1a-Ⅳ-1", "地1c-Ⅳ-1"],
      prerequisiteFamilyKeys: ["GEOGRAPHIC_INQUIRY"],
      skills: [
        "用方位詞描述兩地相對位置",
        "辨認赤道本初經線與南北半球",
        "依緯度判斷南北位置",
        "依經度判斷東西位置",
        "從經緯度定位地表地點",
        "比較絕對位置與相對位置",
        "由臺灣位置推論交通與交流條件",
      ],
    },
    {
      key: "SCALE_DISTANCE_MEASUREMENT",
      title: "Scale, distance and map measurement",
      authorityCodes: ["地1a-Ⅳ-1", "地1c-Ⅳ-1", "社3b-Ⅳ-2", "社3b-Ⅳ-3"],
      prerequisiteFamilyKeys: ["DIRECTION_COORDINATES_LOCATION"],
      skills: [
        "辨識文字比例尺線段比例尺與數字比例尺",
        "由比例尺換算地圖與實際距離",
        "由實際距離求地圖距離",
        "比較大比例尺與小比例尺資訊詳略",
        "選擇適合社區或世界尺度的地圖",
        "沿道路或河道估算曲線距離",
        "檢查單位換算與估算結果是否合理",
      ],
    },
    {
      key: "CONTOURS_TERRAIN",
      title: "Contour lines and terrain interpretation",
      authorityCodes: ["地Ab-Ⅳ-1", "地Ab-Ⅳ-2", "地Ab-Ⅳ-4", "地1a-Ⅳ-1", "地1b-Ⅳ-1"],
      prerequisiteFamilyKeys: ["SCALE_DISTANCE_MEASUREMENT"],
      skills: [
        "讀取等高線標示的海拔高度",
        "由等高線疏密判斷坡度陡緩",
        "辨識山峰稜線與谷地等高線形態",
        "由等高線判斷河流可能流向",
        "比較平原丘陵盆地與山地地形",
        "依地形圖判斷道路與聚落選址",
        "評估坡地利用可能造成的災害風險",
      ],
    },
    {
      key: "MAP_PROJECTION_DISTORTION",
      title: "Map projection and distortion",
      authorityCodes: ["地Aa-Ⅳ-1", "地Aa-Ⅳ-2", "地1a-Ⅳ-1", "地1c-Ⅳ-1", "社3b-Ⅳ-2"],
      prerequisiteFamilyKeys: ["CONTOURS_TERRAIN"],
      skills: [
        "理解球面轉成平面必然產生變形",
        "辨識地圖可能改變面積形狀距離或方向",
        "比較高緯地區在不同世界地圖上的大小",
        "依用途判斷應重視的地圖性質",
        "避免直接以平面圖面積判斷實際國土大小",
        "由經緯線形態辨認投影變形位置",
        "說明單一世界地圖不能同時保留所有性質",
      ],
    },
    {
      key: "GIS_REMOTE_SENSING",
      title: "GIS, remote sensing and layered information",
      authorityCodes: ["地1a-Ⅳ-1", "地1b-Ⅳ-1", "地1c-Ⅳ-1", "社3b-Ⅳ-1", "社3b-Ⅳ-2", "社3b-Ⅳ-3", "社3d-Ⅳ-1"],
      prerequisiteFamilyKeys: ["MAP_PROJECTION_DISTORTION"],
      skills: [
        "區分地理資訊圖層中的點線面資料",
        "疊合地形人口與交通圖層回答問題",
        "由衛星影像辨識土地覆蓋差異",
        "比較不同日期影像判斷環境變化",
        "依圖例與拍攝時間解讀遙測影像",
        "選擇適合設施設址的必要圖層",
        "說明圖層資料不足時判斷的限制",
      ],
    },
    {
      key: "SURFACE_PROCESSES_LANDFORMS",
      title: "Earth surface processes and landforms",
      authorityCodes: ["地Ab-Ⅳ-1", "地Ab-Ⅳ-2", "地Ab-Ⅳ-4", "地Bd-Ⅳ-1", "地Be-Ⅳ-1", "地Bf-Ⅳ-1", "地Bg-Ⅳ-1", "地Bh-Ⅳ-1", "地Bi-Ⅳ-1", "地1a-Ⅳ-1", "地1b-Ⅳ-1"],
      prerequisiteFamilyKeys: ["GIS_REMOTE_SENSING"],
      skills: [
        "區分內營力與外營力對地表的作用",
        "由板塊活動解釋主要山脈與地震帶",
        "由侵蝕搬運堆積解釋河流地形",
        "由海浪作用辨識侵蝕與堆積海岸",
        "由石灰岩溶蝕理解喀斯特地形",
        "由冰河或風力作用辨認典型地貌",
        "連結地形條件與人類土地利用",
      ],
    },
    {
      key: "WEATHER_CLIMATE_GRAPHS",
      title: "Weather elements and climate graphs",
      authorityCodes: ["地Ac-Ⅳ-1", "地Ac-Ⅳ-2", "地Ac-Ⅳ-4", "地1a-Ⅳ-1", "社3b-Ⅳ-3"],
      prerequisiteFamilyKeys: ["SURFACE_PROCESSES_LANDFORMS"],
      skills: [
        "區分短期天氣與長期氣候",
        "讀取氣溫降水風向與氣壓資料",
        "由等壓線判斷氣壓分布與風勢",
        "讀取氣候圖的月均溫與月降水量",
        "計算年溫差與年降水量",
        "判斷雨季乾季與高低溫月份",
        "以完整氣候資料而非單月現象下結論",
      ],
    },
    {
      key: "CLIMATE_CONTROLS_CLASSIFICATION",
      title: "Climate controls and climate classification",
      authorityCodes: ["地Ac-Ⅳ-1", "地Ac-Ⅳ-2", "地Ba-Ⅳ-1", "地Bc-Ⅳ-1", "地Bd-Ⅳ-1", "地Be-Ⅳ-1", "地Bf-Ⅳ-1", "地Bg-Ⅳ-1", "地Bh-Ⅳ-1", "地Bi-Ⅳ-1", "地1a-Ⅳ-1", "地1b-Ⅳ-1"],
      prerequisiteFamilyKeys: ["WEATHER_CLIMATE_GRAPHS"],
      skills: [
        "由緯度解釋日照與氣溫差異",
        "由海陸位置解釋年溫差差異",
        "由海拔解釋垂直氣溫變化",
        "由盛行風與地形解釋降水差異",
        "由洋流解釋沿岸氣候特徵",
        "依氣溫與降水型態辨識主要氣候",
        "綜合多項控制因素解釋區域氣候",
      ],
    },
    {
      key: "HYDROLOGY_WATERSHEDS",
      title: "Hydrology, watersheds and water resources",
      authorityCodes: ["地Ac-Ⅳ-3", "地Ac-Ⅳ-4", "地Bc-Ⅳ-1", "地Cb-Ⅳ-1", "地1a-Ⅳ-2", "地1b-Ⅳ-1", "地1c-Ⅳ-2", "社2b-Ⅳ-3"],
      prerequisiteFamilyKeys: ["CLIMATE_CONTROLS_CLASSIFICATION"],
      skills: [
        "辨識集水區分水嶺與河川系統",
        "由地形與降水解釋河川流量變化",
        "比較地表水與地下水來源",
        "分析水庫蓄水供水與淤積問題",
        "由用水結構判斷缺水壓力",
        "比較節水調度與開發新水源方案",
        "從上下游關係評估水資源決策",
      ],
    },
    {
      key: "POPULATION_MIGRATION",
      title: "Population distribution, structure and migration",
      authorityCodes: ["地Ad-Ⅳ-1", "地Ad-Ⅳ-2", "地Ad-Ⅳ-4", "地Ba-Ⅳ-2", "地Ba-Ⅳ-3", "地Bi-Ⅳ-2", "地1a-Ⅳ-1", "地1a-Ⅳ-2", "社2b-Ⅳ-1"],
      prerequisiteFamilyKeys: ["HYDROLOGY_WATERSHEDS"],
      skills: [
        "由自然與人文條件解釋人口分布",
        "讀取出生死亡與自然增加資料",
        "由人口金字塔判斷年齡性別結構",
        "辨識人口轉型不同階段特徵",
        "區分推力拉力與遷移方向",
        "分析移民對遷出地與遷入地的影響",
        "依人口問題比較可能政策及限制",
      ],
    },
    {
      key: "SETTLEMENT_URBAN_SYSTEMS",
      title: "Settlement, urbanization and urban systems",
      authorityCodes: ["地Af-Ⅳ-1", "地Af-Ⅳ-2", "地Af-Ⅳ-3", "地Ca-Ⅳ-2", "地Ca-Ⅳ-3", "地1a-Ⅳ-1", "地1b-Ⅳ-1", "地1b-Ⅳ-2"],
      prerequisiteFamilyKeys: ["POPULATION_MIGRATION"],
      skills: [
        "由水源地形交通解釋聚落選址",
        "比較集村散村與都市聚落特徵",
        "由服務範圍理解聚落層級",
        "解釋交通網絡與都市成長關係",
        "由資料判斷都市化程度與速度",
        "分析都市擴張帶來的居住交通問題",
        "比較都市更新與區域均衡方案",
      ],
    },
    {
      key: "CULTURE_ETHNICITY_LANDSCAPE",
      title: "Culture, ethnicity and human landscape",
      authorityCodes: ["地Ad-Ⅳ-3", "地Af-Ⅳ-4", "地Ba-Ⅳ-3", "地Bd-Ⅳ-2", "地Bd-Ⅳ-4", "地Be-Ⅳ-2", "地Bf-Ⅳ-2", "地Bf-Ⅳ-4", "地Bg-Ⅳ-2", "地Bc-Ⅳ-4", "地Ca-Ⅳ-1", "地Ca-Ⅳ-2", "地Ca-Ⅳ-3", "社2a-Ⅳ-3", "社2b-Ⅳ-1", "社2b-Ⅳ-2", "社2c-Ⅳ-1"],
      prerequisiteFamilyKeys: ["SETTLEMENT_URBAN_SYSTEMS"],
      skills: [
        "由語言宗教族群辨識文化景觀",
        "由地名追蹤環境與族群變遷",
        "分析文化擴散與在地調適",
        "區分文化區域界線與政治界線",
        "以多元觀點理解族群空間經驗",
        "比較文化交流融合與衝突情境",
        "用證據避免把文化差異簡化成刻板印象",
      ],
    },
    {
      key: "AGRICULTURE_FOOD_SYSTEMS",
      title: "Agriculture, fisheries and food systems",
      authorityCodes: ["地Ae-Ⅳ-1", "地Ae-Ⅳ-4", "地Ba-Ⅳ-2", "地Cb-Ⅳ-1", "地Cb-Ⅳ-2", "地Cb-Ⅳ-3", "地Cb-Ⅳ-4", "地1a-Ⅳ-2", "地1b-Ⅳ-1", "社2a-Ⅳ-1"],
      prerequisiteFamilyKeys: ["CULTURE_ETHNICITY_LANDSCAPE"],
      skills: [
        "由氣候地形土壤判斷農業條件",
        "比較集約粗放自給與商業農業",
        "由海域洋流與市場解釋漁業分布",
        "追蹤食物從生產加工運輸到消費",
        "分析國際貿易對糧食供應的影響",
        "辨識食品加工與基因改造議題中的證據",
        "從生產消費與監管提出食安改善方案",
      ],
    },
    {
      key: "INDUSTRY_PRODUCTION_NETWORKS",
      title: "Industry, location and production networks",
      authorityCodes: ["地Ae-Ⅳ-2", "地Ae-Ⅳ-4", "地Bb-Ⅳ-1", "地Bb-Ⅳ-2", "地Bb-Ⅳ-3", "地Bd-Ⅳ-2", "地Bd-Ⅳ-3", "地Be-Ⅳ-3", "地Bg-Ⅳ-3", "地Bh-Ⅳ-2", "地Bi-Ⅳ-2", "地1a-Ⅳ-2"],
      prerequisiteFamilyKeys: ["AGRICULTURE_FOOD_SYSTEMS"],
      skills: [
        "由原料市場勞力交通判斷工業區位",
        "比較勞力密集資本密集與技術密集產業",
        "解釋產業聚集形成的優勢與風險",
        "追蹤跨國生產網絡中的分工",
        "分析產業外移與升級對地區的影響",
        "由供應鏈中斷資料判斷依賴關係",
        "比較產業政策的經濟與環境代價",
      ],
    },
    {
      key: "SERVICES_TRADE_TRANSPORT_TOURISM",
      title: "Services, trade, transport and tourism",
      authorityCodes: ["地Ae-Ⅳ-3", "地Af-Ⅳ-1", "地Ba-Ⅳ-3", "地Bb-Ⅳ-3", "地Bd-Ⅳ-3", "地Be-Ⅳ-3", "地Bh-Ⅳ-3", "地Bi-Ⅳ-2", "地1a-Ⅳ-2", "地1b-Ⅳ-2"],
      prerequisiteFamilyKeys: ["INDUSTRY_PRODUCTION_NETWORKS"],
      skills: [
        "區分生產者服務與消費者服務",
        "由成本速度與貨物性質選擇運輸方式",
        "解釋港口機場與交通節點的區位",
        "讀取進出口與貿易依存資料",
        "分析觀光資源交通與市場關係",
        "比較觀光收益與環境社會衝擊",
        "由服務網絡判斷區域中心功能",
      ],
    },
    {
      key: "DEVELOPMENT_INEQUALITY",
      title: "Development indicators and regional inequality",
      authorityCodes: ["地Af-Ⅳ-3", "地Bb-Ⅳ-2", "地Bb-Ⅳ-3", "地Bg-Ⅳ-3", "地Bh-Ⅳ-3", "地Bi-Ⅳ-3", "地1a-Ⅳ-2", "地1c-Ⅳ-2", "社1c-Ⅳ-1", "社2b-Ⅳ-1"],
      prerequisiteFamilyKeys: ["SERVICES_TRADE_TRANSPORT_TOURISM"],
      skills: [
        "區分所得產值健康與教育等發展指標",
        "由多項指標比較區域發展",
        "辨識平均值掩蓋的內部差距",
        "分析資源集中與周邊地區發展落差",
        "比較城鄉與區域不均的成因",
        "評估交通產業與公共服務改善方案",
        "說明發展程度不能由單一指標決定",
      ],
    },
    {
      key: "TAIWAN_LOCATION_PHYSICAL",
      title: "Taiwan location and physical environment",
      authorityCodes: ["地Aa-Ⅳ-2", "地Aa-Ⅳ-3", "地Aa-Ⅳ-4", "地Ab-Ⅳ-1", "地Ab-Ⅳ-2", "地Ab-Ⅳ-3", "地1a-Ⅳ-1", "地1b-Ⅳ-1", "社2a-Ⅳ-2"],
      prerequisiteFamilyKeys: ["DEVELOPMENT_INEQUALITY"],
      skills: [
        "由經緯度與海陸位置描述臺灣位置",
        "解釋臺灣位於板塊交界的地形影響",
        "辨識臺灣山地丘陵盆地平原臺地分布",
        "比較臺灣東西部海岸地形",
        "區分領海與經濟海域的空間概念",
        "由地形判斷交通聚落與土地利用限制",
        "分析臺灣位置與區域交流的關聯",
      ],
    },
    {
      key: "TAIWAN_CLIMATE_WATER_HAZARDS",
      title: "Taiwan climate, water and hazards",
      authorityCodes: ["地Ac-Ⅳ-1", "地Ac-Ⅳ-2", "地Ac-Ⅳ-3", "地Ac-Ⅳ-4", "地Ab-Ⅳ-4", "地1a-Ⅳ-2", "地1b-Ⅳ-1", "地1c-Ⅳ-2", "社2b-Ⅳ-3"],
      prerequisiteFamilyKeys: ["TAIWAN_LOCATION_PHYSICAL"],
      skills: [
        "由緯度季風地形解釋臺灣氣候",
        "比較臺灣南北東西部降水差異",
        "解釋臺灣河川短急與流量變化",
        "由降水季節與地形理解缺水風險",
        "分析颱風帶來的水資源與災害",
        "判斷地震坡地與淹水風險的空間差異",
        "比較防災減災與調適措施的適用條件",
      ],
    },
    {
      key: "TAIWAN_POPULATION_SETTLEMENT",
      title: "Taiwan population and settlement",
      authorityCodes: ["地Ad-Ⅳ-1", "地Ad-Ⅳ-2", "地Ad-Ⅳ-3", "地Ad-Ⅳ-4", "地Af-Ⅳ-1", "地Af-Ⅳ-2", "地Ca-Ⅳ-2", "地Ca-Ⅳ-3", "地1a-Ⅳ-1", "社2a-Ⅳ-2"],
      prerequisiteFamilyKeys: ["TAIWAN_CLIMATE_WATER_HAZARDS"],
      skills: [
        "由地形交通產業解釋臺灣人口分布",
        "讀取臺灣人口成長與年齡結構變化",
        "分析少子化高齡化與人口移動",
        "比較都市與非都市聚落發展",
        "解釋都會區擴張與通勤關係",
        "由地名辨識環境族群與產業線索",
        "評估人口政策對不同地區的影響",
      ],
    },
    {
      key: "TAIWAN_ECONOMY_REGIONAL",
      title: "Taiwan economic change and regional development",
      authorityCodes: ["地Ae-Ⅳ-1", "地Ae-Ⅳ-2", "地Ae-Ⅳ-3", "地Ae-Ⅳ-4", "地Af-Ⅳ-1", "地Af-Ⅳ-3", "地Ca-Ⅳ-4", "地1a-Ⅳ-2", "地1b-Ⅳ-2"],
      prerequisiteFamilyKeys: ["TAIWAN_POPULATION_SETTLEMENT"],
      skills: [
        "比較臺灣農業經營轉型與挑戰",
        "整理臺灣工業發展與區位變化",
        "分析出口貿易與全球生產網絡",
        "解釋交通建設與區域發展差異",
        "比較北中南東產業與人口特色",
        "分析地方產品與地名行銷關係",
        "評估產業調適方案的區域效果",
      ],
    },
    {
      key: "TAIWAN_ENVIRONMENT_SUSTAINABILITY",
      title: "Taiwan environmental issues and sustainability",
      authorityCodes: ["地Ab-Ⅳ-4", "地Ac-Ⅳ-4", "地Ad-Ⅳ-4", "地Ae-Ⅳ-4", "地Af-Ⅳ-4", "地Cb-Ⅳ-4", "地1c-Ⅳ-1", "地1c-Ⅳ-2", "社2a-Ⅳ-2", "社2b-Ⅳ-3", "社2c-Ⅳ-2", "社2c-Ⅳ-3", "社3d-Ⅳ-2", "社3d-Ⅳ-3"],
      prerequisiteFamilyKeys: ["TAIWAN_ECONOMY_REGIONAL"],
      skills: [
        "辨認臺灣土地利用衝突中的利害關係人",
        "比較開發保育與原住民族空間權益",
        "分析水土能源與廢棄物議題的空間差異",
        "以環境承載與世代公平評估方案",
        "區分降低衝擊調適與復原措施",
        "用在地資料提出可檢驗的永續行動",
        "檢討行動成果及未解決的限制",
      ],
    },
    {
      key: "CHINA_EAST_ASIA",
      title: "China and East Asia",
      authorityCodes: ["地Ba-Ⅳ-1", "地Ba-Ⅳ-2", "地Ba-Ⅳ-3", "地Bb-Ⅳ-1", "地Bb-Ⅳ-2", "地Bb-Ⅳ-3", "地Bb-Ⅳ-4", "地Bd-Ⅳ-1", "地Bd-Ⅳ-2", "地Bd-Ⅳ-3", "地Bd-Ⅳ-4", "地1a-Ⅳ-1", "地1a-Ⅳ-2"],
      prerequisiteFamilyKeys: ["TAIWAN_ENVIRONMENT_SUSTAINABILITY"],
      skills: [
        "比較中國主要地形氣候與河川分布",
        "由自然環境解釋人口與農業分布",
        "分析人口遷移都市化與區域差異",
        "整理產業轉型與全球連結",
        "比較日本韓國等東北亞產業條件",
        "分析東北亞人口能源與環境挑戰",
        "以文化交流證據理解臺灣與東亞關係",
      ],
    },
    {
      key: "SOUTHEAST_ASIA",
      title: "Southeast Asia",
      authorityCodes: ["地Be-Ⅳ-1", "地Be-Ⅳ-2", "地Be-Ⅳ-3", "地Be-Ⅳ-4", "地1a-Ⅳ-1", "地1a-Ⅳ-2", "社2a-Ⅳ-3"],
      prerequisiteFamilyKeys: ["CHINA_EAST_ASIA"],
      skills: [
        "由季風海陸與群島理解東南亞環境",
        "解釋稻作熱帶作物與人口分布",
        "比較大陸與島嶼東南亞交通條件",
        "分析宗教族群語言的多元文化",
        "整理工業化觀光與都市發展",
        "理解區域結盟與國際分工",
        "分析東南亞市場與臺灣產業連結",
      ],
    },
    {
      key: "SOUTH_ASIA",
      title: "South Asia",
      authorityCodes: ["地Be-Ⅳ-1", "地Be-Ⅳ-2", "地Be-Ⅳ-3", "地Be-Ⅳ-4", "地1a-Ⅳ-1", "地1a-Ⅳ-2"],
      prerequisiteFamilyKeys: ["SOUTHEAST_ASIA"],
      skills: [
        "由地形季風解釋南亞環境差異",
        "分析季風降水對農業與生活的影響",
        "由人口資料理解都市與發展壓力",
        "辨識南亞宗教語言與社會多樣性",
        "整理服務業工業與新興市場發展",
        "分析南亞與全球生產服務網絡的連結",
      ],
    },
    {
      key: "CENTRAL_WEST_ASIA",
      title: "Central and West Asia",
      authorityCodes: ["地Bf-Ⅳ-1", "地Bf-Ⅳ-2", "地Bf-Ⅳ-3", "地Bf-Ⅳ-4", "地1a-Ⅳ-1", "地1a-Ⅳ-2", "社2a-Ⅳ-3"],
      prerequisiteFamilyKeys: ["SOUTH_ASIA"],
      skills: [
        "由乾燥氣候理解中亞西亞水資源限制",
        "分析綠洲游牧與灌溉農業分布",
        "由油氣資源解釋產業與國際關係",
        "理解伊斯蘭文化的空間分布與多樣性",
        "從多重因素分析區域衝突而不單因歸因",
        "比較文化互動交流與緊張的證據",
      ],
    },
    {
      key: "EUROPE_RUSSIA",
      title: "Europe and Russia",
      authorityCodes: ["地Bh-Ⅳ-1", "地Bh-Ⅳ-2", "地Bh-Ⅳ-3", "地Bh-Ⅳ-4", "地1a-Ⅳ-1", "地1a-Ⅳ-2"],
      prerequisiteFamilyKeys: ["CENTRAL_WEST_ASIA"],
      skills: [
        "比較歐洲海陸地形與氣候區域",
        "解釋歐洲人口都市與產業分布",
        "分析區域結盟形成的跨國連結",
        "由資源幅員與緯度理解俄羅斯區域差異",
        "比較歐洲不同地區的發展條件",
        "評估歐洲綠能發展的原因與限制",
      ],
    },
    {
      key: "AFRICA",
      title: "Africa",
      authorityCodes: ["地Bg-Ⅳ-1", "地Bg-Ⅳ-2", "地Bg-Ⅳ-3", "地Bg-Ⅳ-4", "地1a-Ⅳ-1", "地1a-Ⅳ-2", "社2b-Ⅳ-1", "社2b-Ⅳ-2"],
      prerequisiteFamilyKeys: ["EUROPE_RUSSIA"],
      skills: [
        "由緯度地形解釋非洲氣候帶分布",
        "分析水資源礦產與土地利用",
        "理解漠南非洲族群語言文化多樣性",
        "由殖民與貿易脈絡理解發展差異",
        "分析都市化產業與公共服務挑戰",
        "評估公平貿易對生產者與消費者的影響",
      ],
    },
    {
      key: "NORTH_AMERICA",
      title: "North America",
      authorityCodes: ["地Bi-Ⅳ-1", "地Bi-Ⅳ-2", "地Bi-Ⅳ-3", "地1a-Ⅳ-1", "地1a-Ⅳ-2", "社2a-Ⅳ-3"],
      prerequisiteFamilyKeys: ["AFRICA"],
      skills: [
        "由地形氣候理解北美區域差異",
        "解釋農業帶與自然市場條件",
        "分析工業服務業與都市系統",
        "由移民資料理解人口文化變遷",
        "比較美加與區域內部發展差異",
        "分析北美與全球貿易生產網絡",
      ],
    },
    {
      key: "LATIN_AMERICA",
      title: "Latin America",
      authorityCodes: ["地Bi-Ⅳ-1", "地Bi-Ⅳ-2", "地Bi-Ⅳ-3", "地Bi-Ⅳ-4", "地1a-Ⅳ-1", "地1a-Ⅳ-2", "社2b-Ⅳ-3"],
      prerequisiteFamilyKeys: ["NORTH_AMERICA"],
      skills: [
        "由山地高原雨林解釋拉丁美洲環境",
        "分析殖民移民與多元文化景觀",
        "比較農礦產品與工業都市發展",
        "由資料判斷區域與城鄉差距",
        "分析熱帶雨林開發的利害關係",
        "比較保育生計與國際合作方案",
      ],
    },
    {
      key: "OCEANIA_POLAR",
      title: "Oceania and polar regions",
      authorityCodes: ["地Bc-Ⅳ-1", "地Bc-Ⅳ-2", "地Bc-Ⅳ-3", "地Bc-Ⅳ-4", "地1a-Ⅳ-1", "地1a-Ⅳ-2", "社2c-Ⅳ-1"],
      prerequisiteFamilyKeys: ["LATIN_AMERICA"],
      skills: [
        "比較澳洲紐西蘭與太平洋島嶼環境",
        "分析大洋洲資源人口與產業分布",
        "由遷徙語言證據理解南島文化連結",
        "分析小島國面對海平面變化的風險",
        "比較南北極自然環境與人類活動",
        "評估極地資源科研與保育的競合",
      ],
    },
    {
      key: "GLOBALIZATION_INTERDEPENDENCE",
      title: "Globalization and interdependence",
      authorityCodes: ["地Ae-Ⅳ-3", "地Bb-Ⅳ-3", "地Bc-Ⅳ-3", "地Bd-Ⅳ-3", "地Be-Ⅳ-3", "地Bh-Ⅳ-3", "地Bi-Ⅳ-2", "地1a-Ⅳ-2", "地1b-Ⅳ-2", "社1b-Ⅳ-1", "社1c-Ⅳ-1"],
      prerequisiteFamilyKeys: ["OCEANIA_POLAR"],
      skills: [
        "追蹤商品資訊資金與人口跨國流動",
        "由供應鏈理解區域相互依賴",
        "比較全球化對不同地區的機會與風險",
        "分析區域結盟與戰略競合",
        "由事件評估供應中斷的連鎖影響",
        "提出兼顧效率安全與公平的調整方案",
      ],
    },
    {
      key: "ENERGY_RESOURCES_JUSTICE",
      title: "Energy, resources and environmental justice",
      authorityCodes: ["地Bc-Ⅳ-1", "地Bb-Ⅳ-4", "地Bf-Ⅳ-1", "地Bf-Ⅳ-3", "地Bg-Ⅳ-4", "地Bh-Ⅳ-4", "地1a-Ⅳ-2", "地1c-Ⅳ-2", "社2b-Ⅳ-1", "社2b-Ⅳ-3", "社2c-Ⅳ-2", "社3d-Ⅳ-2"],
      prerequisiteFamilyKeys: ["GLOBALIZATION_INTERDEPENDENCE"],
      skills: [
        "比較再生與非再生能源的空間條件",
        "由能源流向理解生產消費地關係",
        "分析開採資源造成的環境與社會成本",
        "辨認風險利益在群體間分配不均",
        "比較節能轉型補償與監管方案",
        "以利害關係人證據評估環境正義",
      ],
    },
    {
      key: "CLIMATE_CHANGE_ADAPTATION",
      title: "Climate change, mitigation and adaptation",
      authorityCodes: ["地Bc-Ⅳ-2", "地Bc-Ⅳ-3", "地Ac-Ⅳ-4", "地Bh-Ⅳ-4", "地Bi-Ⅳ-4", "地1a-Ⅳ-2", "地1c-Ⅳ-2", "社2b-Ⅳ-3", "社3d-Ⅳ-2"],
      prerequisiteFamilyKeys: ["ENERGY_RESOURCES_JUSTICE"],
      skills: [
        "區分天氣波動與長期氣候變化",
        "由多項資料判斷氣候變遷趨勢",
        "連結暖化與海洋水文生態衝擊",
        "區分減緩排放與調適風險措施",
        "比較不同地區的暴露與調適能力",
        "評估個人地方與國際行動的尺度限制",
      ],
    },
    {
      key: "DISASTERS_RISK_RESILIENCE",
      title: "Disasters, risk and resilience",
      authorityCodes: ["地Ab-Ⅳ-4", "地Ac-Ⅳ-4", "地Bc-Ⅳ-2", "地1a-Ⅳ-2", "地1c-Ⅳ-1", "地1c-Ⅳ-2", "社2a-Ⅳ-1", "社2b-Ⅳ-3", "社3d-Ⅳ-1", "社3d-Ⅳ-2", "社3d-Ⅳ-3"],
      prerequisiteFamilyKeys: ["CLIMATE_CHANGE_ADAPTATION"],
      skills: [
        "區分自然現象危害暴露與脆弱度",
        "由地圖判斷災害風險空間差異",
        "分析土地利用如何放大或降低災損",
        "比較預防應變復原與調適措施",
        "依不同族群需求規劃避難與資訊",
        "用事件資料檢討韌性方案成效",
      ],
    },
    {
      key: "INTEGRATED_MULTI_SOURCE",
      title: "Integrated maps, tables, photos and multi-source reasoning",
      authorityCodes: ["地Aa-Ⅳ-4", "地Ca-Ⅳ-4", "地Cb-Ⅳ-4", "地1a-Ⅳ-1", "地1a-Ⅳ-2", "地1b-Ⅳ-1", "地1b-Ⅳ-2", "地1c-Ⅳ-1", "地1c-Ⅳ-2", "社3b-Ⅳ-1", "社3b-Ⅳ-2", "社3b-Ⅳ-3", "社3c-Ⅳ-1", "社3c-Ⅳ-2", "社3d-Ⅳ-1", "社3d-Ⅳ-2", "社3d-Ⅳ-3"],
      prerequisiteFamilyKeys: ["DISASTERS_RISK_RESILIENCE"],
      skills: [
        "對齊地圖圖表照片與文字的時間空間",
        "從多來源找出一致互補與衝突資訊",
        "以圖例單位尺度檢查資料可比性",
        "綜合自然人文線索解釋空間現象",
        "用證據比較方案並標示不確定性",
        "以地圖圖表與文字清楚呈現探究結論",
      ],
    },
  ],
});
