export const HISTORY_SKILL_PLAN = Object.freeze({
  schemaVersion: "cap8-r4-subject-skill-plan-v1",
  subject: "history",
  expectedSkills: 240,
  expectedAuthorityNodes: 94,
  families: [
    {
      key: "HISTORICAL_TIME_PERIODIZATION",
      title: "Historical time, chronology and periodization",
      authorityCodes: ["歷A-Ⅳ-1", "歷1a-Ⅳ-1", "歷1a-Ⅳ-2", "社3b-Ⅳ-3"],
      prerequisiteFamilyKeys: [],
      skills: [
        "換算西元世紀與年代",
        "辨識民國年西元年與帝王紀年的差異",
        "依先後關係排列歷史事件",
        "用時間軸呈現延續轉折與同時性",
        "區分短期事件與長期歷史變遷",
        "理解分期是解釋工具而非自然界線",
        "比較不同分期方式凸顯的歷史重點",
      ],
    },
    {
      key: "EVIDENCE_INTERPRETATION",
      title: "Evidence, sources and historical interpretation",
      authorityCodes: ["歷1b-Ⅳ-1", "歷1b-Ⅳ-2", "歷1c-Ⅳ-1", "歷1c-Ⅳ-2", "社1a-Ⅳ-1", "社1b-Ⅳ-1", "社1c-Ⅳ-1", "社3a-Ⅳ-1", "社3b-Ⅳ-1", "社3b-Ⅳ-2", "社3c-Ⅳ-1", "社3c-Ⅳ-2"],
      prerequisiteFamilyKeys: ["HISTORICAL_TIME_PERIODIZATION"],
      skills: [
        "區分第一手史料與後來研究敘述",
        "辨認史料作者時間對象與目的",
        "區別可核對的歷史事實與後人解釋",
        "以兩份以上史料交叉查證事件",
        "判斷史料能回答與不能回答的問題",
        "比較不同立場對同一事件的詮釋",
        "以證據提出暫時性結論並標明限制",
      ],
    },
    {
      key: "PREHISTORIC_TAIWAN",
      title: "Prehistoric Taiwan and archaeology",
      authorityCodes: ["歷Ba-Ⅳ-1", "歷D-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-1", "社2a-Ⅳ-1", "社3a-Ⅳ-1"],
      prerequisiteFamilyKeys: ["EVIDENCE_INTERPRETATION"],
      skills: [
        "由地層器物與遺址理解考古證據",
        "區分史前時代與有文字記錄時代",
        "由石器陶器與生業推論生活方式",
        "比較臺灣不同史前文化的時空分布",
        "由遺址環境解釋聚落選擇",
        "辨認考古推論與直接證據的差別",
        "用地方遺址資料建立史前文化時間線",
      ],
    },
    {
      key: "INDIGENOUS_AUSTRONESIAN",
      title: "Indigenous peoples and Austronesian connections",
      authorityCodes: ["歷Ba-Ⅳ-2", "歷Bb-Ⅳ-2", "歷Cb-Ⅳ-1", "歷Ea-Ⅳ-3", "歷Fa-Ⅳ-3", "歷1b-Ⅳ-1", "歷1c-Ⅳ-2", "社2b-Ⅳ-1", "社2b-Ⅳ-2", "社2c-Ⅳ-1"],
      prerequisiteFamilyKeys: ["PREHISTORIC_TAIWAN"],
      skills: [
        "區分考古語言傳說與文獻證據",
        "由語言與文化線索理解南島民族連結",
        "比較原住民族多樣的社會與生活方式",
        "分析遷徙接觸與環境調適",
        "由不同時期政策理解原住民族處境",
        "比較官方記錄與族群口述觀點",
        "避免把不同原住民族視為單一文化",
      ],
    },
    {
      key: "EUROPEAN_ZHENG",
      title: "European presence and Zheng regime",
      authorityCodes: ["歷Bb-Ⅳ-1", "歷Bb-Ⅳ-2", "歷D-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2", "社2a-Ⅳ-3"],
      prerequisiteFamilyKeys: ["INDIGENOUS_AUSTRONESIAN"],
      skills: [
        "由航路與貿易理解十七世紀東亞海域",
        "辨識荷蘭西班牙與各方勢力的活動",
        "分析外來政權與原住民族的接觸",
        "理解鄭氏政權建立的區域背景",
        "比較不同政權在臺灣的統治與經濟措施",
        "由史料辨識移民貿易與土地變化",
        "用多方觀點解釋政權更替影響",
      ],
    },
    {
      key: "QING_TAIWAN",
      title: "Qing rule and society in Taiwan",
      authorityCodes: ["歷Ca-Ⅳ-1", "歷Ca-Ⅳ-2", "歷Cb-Ⅳ-1", "歷Cb-Ⅳ-2", "歷D-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2"],
      prerequisiteFamilyKeys: ["EUROPEAN_ZHENG"],
      skills: [
        "整理清帝國治臺政策的變化",
        "分析移民開墾與行政區調整",
        "由農商業資料理解社會發展",
        "比較原住民族與漢人社會變化",
        "分析分類械鬥民變與地方秩序背景",
        "由契約地圖與地方志重建地方生活",
        "區分制度規定與實際社會運作",
      ],
    },
    {
      key: "OPEN_PORTS_LATE_QING_TAIWAN",
      title: "Opening ports and late-Qing change",
      authorityCodes: ["歷Ca-Ⅳ-1", "歷Ca-Ⅳ-2", "歷Cb-Ⅳ-2", "歷D-Ⅳ-1", "歷D-Ⅳ-2", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2", "社2a-Ⅳ-2"],
      prerequisiteFamilyKeys: ["QING_TAIWAN"],
      skills: [
        "由國際局勢理解臺灣開港背景",
        "辨識開港地點與主要出口商品",
        "分析港口商業與地方社會變化",
        "比較開港前後外來者活動",
        "理解晚清建設與防務調整的原因",
        "用貿易統計與地圖判斷變遷",
        "從地方史料評估開港影響的不均",
      ],
    },
    {
      key: "JAPANESE_COLONIAL_GOVERNANCE",
      title: "Japanese colonial governance and society",
      authorityCodes: ["歷Ea-Ⅳ-1", "歷Ea-Ⅳ-2", "歷Ea-Ⅳ-3", "歷Eb-Ⅳ-1", "歷Eb-Ⅳ-2", "歷Eb-Ⅳ-3", "歷G-Ⅳ-1", "歷1a-Ⅳ-2", "歷1c-Ⅳ-2"],
      prerequisiteFamilyKeys: ["OPEN_PORTS_LATE_QING_TAIWAN"],
      skills: [
        "整理殖民統治體制建立與調整",
        "分析警察地方行政與社會控制",
        "比較基礎建設的統治與生活影響",
        "理解產業政策與殖民經濟關係",
        "分析殖民政府所稱理蕃政策與原住民族回應",
        "比較現代教育與文化啟蒙活動",
        "以不同群體史料評估殖民治理",
      ],
    },
    {
      key: "WAR_MOBILIZATION_COLONIAL_TAIWAN",
      title: "War, mobilization and late colonial Taiwan",
      authorityCodes: ["歷Ea-Ⅳ-1", "歷Ea-Ⅳ-2", "歷Ea-Ⅳ-3", "歷Eb-Ⅳ-3", "歷G-Ⅳ-1", "歷G-Ⅳ-2", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2", "社2b-Ⅳ-1"],
      prerequisiteFamilyKeys: ["JAPANESE_COLONIAL_GOVERNANCE"],
      skills: [
        "由戰爭時序理解殖民政策轉變",
        "分析動員政策對教育文化與生活的影響",
        "辨認軍事徵用與產業調整的史料",
        "比較不同群體在戰時的處境與選擇",
        "區分官方宣傳與個人經驗記錄",
        "由人口物資資料判斷戰爭影響",
        "說明晚期殖民經驗的多樣性與限制",
      ],
    },
    {
      key: "POSTWAR_AUTHORITARIAN_TAIWAN",
      title: "Postwar takeover, authoritarian rule and society",
      authorityCodes: ["歷Fa-Ⅳ-1", "歷Fa-Ⅳ-2", "歷Fa-Ⅳ-3", "歷Fa-Ⅳ-4", "歷G-Ⅳ-1", "歷1a-Ⅳ-2", "歷1c-Ⅳ-1", "歷1c-Ⅳ-2", "社2c-Ⅳ-1", "社2c-Ⅳ-2"],
      prerequisiteFamilyKeys: ["WAR_MOBILIZATION_COLONIAL_TAIWAN"],
      skills: [
        "整理戰後統治體制移入與轉變",
        "由時序與史料理解二二八事件",
        "辨識戒嚴與白色恐怖的制度背景",
        "比較國家政策對不同群體的影響",
        "分析兩岸關係與國際處境變化",
        "區分政府文件受難者記錄與後來研究",
        "以人權觀點理解威權時期社會處境",
      ],
    },
    {
      key: "TAIWAN_ECONOMIC_SOCIAL_CHANGE",
      title: "Economic transformation and social change in Taiwan",
      authorityCodes: ["歷Fb-Ⅳ-1", "歷Fb-Ⅳ-2", "歷Fa-Ⅳ-4", "歷G-Ⅳ-1", "歷G-Ⅳ-2", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2", "社1b-Ⅳ-1"],
      prerequisiteFamilyKeys: ["POSTWAR_AUTHORITARIAN_TAIWAN"],
      skills: [
        "由政策與國際環境解釋經濟發展",
        "整理農業工業與服務業結構轉變",
        "分析出口成長都市化與人口移動",
        "比較經濟成長對不同群體的影響",
        "由家庭教育消費資料理解社會變遷",
        "追蹤大眾媒體與流行文化演變",
        "檢驗單一成因能否解釋長期轉型",
      ],
    },
    {
      key: "DEMOCRATIZATION_TRANSITIONAL_JUSTICE",
      title: "Democratization, transitional justice and contemporary Taiwan",
      authorityCodes: ["歷Fa-Ⅳ-1", "歷Fa-Ⅳ-2", "歷Fa-Ⅳ-4", "歷Fb-Ⅳ-1", "歷Fb-Ⅳ-2", "歷G-Ⅳ-2", "歷1a-Ⅳ-2", "歷1c-Ⅳ-2", "社2c-Ⅳ-2", "社3d-Ⅳ-2"],
      prerequisiteFamilyKeys: ["TAIWAN_ECONOMIC_SOCIAL_CHANGE"],
      skills: [
        "整理解除戒嚴與民主化重要進程",
        "分析社會運動與政治開放的互動",
        "理解選舉制度與公民參與的歷史變化",
        "由不同史料探討威權記憶與正義議題",
        "區分史實釐清責任判斷與價值討論",
        "比較不同群體對轉型正義的觀點",
        "連結民主發展與當代臺灣處境",
      ],
    },
    {
      key: "EARLY_CHINESE_CIVILIZATIONS",
      title: "Early Chinese civilizations",
      authorityCodes: ["歷Ha-Ⅳ-1", "歷Ha-Ⅳ-2", "歷J-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-1"],
      prerequisiteFamilyKeys: ["DEMOCRATIZATION_TRANSITIONAL_JUSTICE"],
      skills: [
        "由考古與文字資料理解早期國家形成",
        "整理商周政治社會與文化變遷",
        "比較封建制度與後來郡縣治理",
        "分析春秋戰國變局與思想發展",
        "由統一措施理解秦漢帝國形成",
        "比較不同史料對早期文明的證據",
        "避免把後世制度直接套用早期社會",
      ],
    },
    {
      key: "IMPERIAL_INSTITUTIONS_SOCIETY",
      title: "Imperial institutions and society",
      authorityCodes: ["歷Ha-Ⅳ-1", "歷Ha-Ⅳ-2", "歷Hb-Ⅳ-1", "歷Ia-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2"],
      prerequisiteFamilyKeys: ["EARLY_CHINESE_CIVILIZATIONS"],
      skills: [
        "比較中央集權制度的延續與調整",
        "理解官僚選任制度的變化",
        "分析土地賦役與社會階層關係",
        "比較皇權地方治理與邊疆統治",
        "由制度資料理解家庭與性別角色",
        "區分制度理想與實際社會情況",
        "用長時段觀點解釋制度變遷",
      ],
    },
    {
      key: "MEDIEVAL_CHINA_EXCHANGE",
      title: "Medieval China and cultural exchange",
      authorityCodes: ["歷Ha-Ⅳ-1", "歷Ha-Ⅳ-2", "歷Hb-Ⅳ-1", "歷Hb-Ⅳ-2", "歷1a-Ⅳ-2", "歷1b-Ⅳ-1", "社2a-Ⅳ-3"],
      prerequisiteFamilyKeys: ["IMPERIAL_INSTITUTIONS_SOCIETY"],
      skills: [
        "整理魏晉南北朝政權與人口移動",
        "分析民族互動與文化融合",
        "理解隋唐制度與帝國秩序",
        "由交通路線解釋對外交流",
        "追蹤宗教技術與物產的傳播",
        "比較都城商業與多元文化證據",
        "評估交流中的吸收轉化與衝突",
      ],
    },
    {
      key: "SONG_YUAN_MING_QING",
      title: "Song-Yuan-Ming-Qing transformations",
      authorityCodes: ["歷Hb-Ⅳ-1", "歷Hb-Ⅳ-2", "歷Ia-Ⅳ-1", "歷Ia-Ⅳ-2", "歷Ic-Ⅳ-1", "歷Ic-Ⅳ-2", "歷J-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2"],
      prerequisiteFamilyKeys: ["MEDIEVAL_CHINA_EXCHANGE"],
      skills: [
        "分析宋代商業都市與社會變化",
        "由海陸交通理解宋元國際互動",
        "比較元明清政治統治與疆域治理",
        "整理明清東亞商貿與文化交流",
        "由新媒體與城市風貌理解生活改變",
        "分析家族婦女角色的延續與變化",
        "用比較表辨認長期變遷而非朝代背誦",
      ],
    },
    {
      key: "LATE_QING_CRISIS_REFORM",
      title: "Late Qing crisis and reform",
      authorityCodes: ["歷Ib-Ⅳ-1", "歷Ib-Ⅳ-2", "歷Ic-Ⅳ-1", "歷Ic-Ⅳ-2", "歷J-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2"],
      prerequisiteFamilyKeys: ["SONG_YUAN_MING_QING"],
      skills: [
        "由國際貿易與戰爭理解晚清危機",
        "整理東西方接觸衝突與條約影響",
        "比較自強改革與政治制度變革",
        "分析甲午戰爭後改革加速的背景",
        "由報刊學校城市資料理解社會變化",
        "比較改革者不同主張與限制",
        "以內外多重因素解釋清末變局",
      ],
    },
    {
      key: "REPUBLICAN_REVOLUTION_WARLORD",
      title: "Republican revolution and warlord era",
      authorityCodes: ["歷Ka-Ⅳ-1", "歷Ka-Ⅳ-2", "歷Kb-Ⅳ-1", "歷J-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2", "歷1c-Ⅳ-2"],
      prerequisiteFamilyKeys: ["LATE_QING_CRISIS_REFORM"],
      skills: [
        "整理革命運動與中華民國建立過程",
        "分析共和制度建立面臨的困難",
        "由政局資料理解軍閥割據背景",
        "比較不同政治力量的國家建設主張",
        "理解新文化與社會思潮的衝擊",
        "由外交事件分析民族運動發展",
        "區分革命目標與後續政治結果",
      ],
    },
    {
      key: "NATIONALIST_COMMUNIST_JAPAN_WAR",
      title: "Nationalist-Communist conflict and war against Japan",
      authorityCodes: ["歷Kb-Ⅳ-1", "歷Kb-Ⅳ-2", "歷Ka-Ⅳ-2", "歷M-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2", "歷1c-Ⅳ-2"],
      prerequisiteFamilyKeys: ["REPUBLICAN_REVOLUTION_WARLORD"],
      skills: [
        "整理國民政府建制與政局發展",
        "分析國共合作衝突與政治競爭",
        "由時序理解日本對外擴張",
        "分析抗日戰爭對社會與政權的影響",
        "比較政府軍隊民眾等不同戰時經驗",
        "辨識戰時宣傳與多方史料差異",
        "以多重原因解釋戰後國共衝突結果",
      ],
    },
    {
      key: "PRC_ROC_POSTWAR_EAST_ASIA",
      title: "PRC, ROC and postwar East Asia",
      authorityCodes: ["歷La-Ⅳ-1", "歷La-Ⅳ-2", "歷Lb-Ⅳ-1", "歷Lb-Ⅳ-2", "歷Fa-Ⅳ-4", "歷M-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2"],
      prerequisiteFamilyKeys: ["NATIONALIST_COMMUNIST_JAPAN_WAR"],
      skills: [
        "整理中華人民共和國建立與早期發展",
        "分析改革開放後政經社會變化",
        "理解中華民國政府遷臺後的區域處境",
        "比較冷戰下東亞國家不同發展道路",
        "分析美蘇競爭與東亞國際關係",
        "理解東南亞區域組織形成與影響",
        "由跨區域資料解釋兩岸與東亞互動",
      ],
    },
    {
      key: "ANCIENT_WEST_ASIA_EGYPT",
      title: "Ancient West Asian and Egyptian civilizations",
      authorityCodes: ["歷Na-Ⅳ-1", "歷P-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-1"],
      prerequisiteFamilyKeys: ["PRC_ROC_POSTWAR_EAST_ASIA"],
      skills: [
        "由河川環境理解早期農業文明",
        "比較兩河與埃及政治社會特色",
        "由文字法律建築辨識文明證據",
        "分析灌溉貿易與國家形成關係",
        "辨識神話宗教與統治的互動",
        "由考古材料推論日常生活",
        "避免把不同早期文明混為同一模式",
      ],
    },
    {
      key: "ANCIENT_GREECE_ROME",
      title: "Ancient Greece and Rome",
      authorityCodes: ["歷Na-Ⅳ-2", "歷P-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2"],
      prerequisiteFamilyKeys: ["ANCIENT_WEST_ASIA_EGYPT"],
      skills: [
        "比較希臘城邦政治與社會特色",
        "理解雅典民主的參與範圍與限制",
        "由戰爭交流理解希臘文化擴散",
        "整理羅馬共和到帝國的變遷",
        "分析法律道路與城市治理影響",
        "比較希臘羅馬政治文化遺產",
        "以當時條件而非現代標準解釋制度",
      ],
    },
    {
      key: "RELIGIONS_DIFFUSION",
      title: "Major religions and cultural diffusion",
      authorityCodes: ["歷Nb-Ⅳ-1", "歷Nb-Ⅳ-2", "歷Nb-Ⅳ-3", "歷Ha-Ⅳ-2", "歷P-Ⅳ-1", "歷1a-Ⅳ-2", "社2a-Ⅳ-3", "社2b-Ⅳ-2"],
      prerequisiteFamilyKeys: ["ANCIENT_GREECE_ROME"],
      skills: [
        "整理佛教起源教義傳播與在地化",
        "整理基督教起源發展與傳播",
        "整理伊斯蘭教起源發展與傳播",
        "由商路政權與移民解釋宗教擴散",
        "比較宗教共同關懷與歷史差異",
        "辨識宗教交流衝突與文化創造",
        "避免以單一印象概括信仰群體",
      ],
    },
    {
      key: "MEDIEVAL_EUROPE_ISLAMIC_WORLDS",
      title: "Medieval Europe and Islamic worlds",
      authorityCodes: ["歷Nb-Ⅳ-2", "歷Nb-Ⅳ-3", "歷Oa-Ⅳ-1", "歷Oa-Ⅳ-2", "歷P-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2", "社2a-Ⅳ-3"],
      prerequisiteFamilyKeys: ["RELIGIONS_DIFFUSION"],
      skills: [
        "理解中世紀歐洲封建與教會關係",
        "分析莊園城市與商業發展變化",
        "整理伊斯蘭世界的政治商貿與學術",
        "由交流路線理解知識技術傳播",
        "比較基督教與伊斯蘭世界的接觸",
        "辨識戰爭之外的貿易與文化交流",
        "解釋中世紀後期社會轉變的多重因素",
      ],
    },
    {
      key: "RENAISSANCE_REFORMATION_SCIENCE",
      title: "Renaissance, Reformation and scientific change",
      authorityCodes: ["歷Oa-Ⅳ-1", "歷Oa-Ⅳ-2", "歷Oa-Ⅳ-3", "歷P-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2"],
      prerequisiteFamilyKeys: ["MEDIEVAL_EUROPE_ISLAMIC_WORLDS"],
      skills: [
        "由城市商業與古典文化理解文藝復興",
        "分析人文思想在藝術學術上的表現",
        "由教會問題印刷與政治理解宗教改革",
        "比較宗教改革不同主張與影響",
        "整理科學革命的觀察驗證與世界觀改變",
        "連結啟蒙思想與後來政治社會變革",
      ],
    },
    {
      key: "MARITIME_EXPANSION_EXCHANGE",
      title: "Maritime expansion and global exchange",
      authorityCodes: ["歷Ob-Ⅳ-1", "歷Ob-Ⅳ-2", "歷Ob-Ⅳ-3", "歷Bb-Ⅳ-1", "歷P-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2", "社2a-Ⅳ-3"],
      prerequisiteFamilyKeys: ["RENAISSANCE_REFORMATION_SCIENCE"],
      skills: [
        "由技術商業與政治競爭理解海外擴張",
        "用航路圖追蹤歐亞非美洲連結",
        "分析物種商品人口與疾病交換",
        "比較傳教貿易征服與殖民活動",
        "理解美洲澳洲原有社會與外來衝擊",
        "從不同群體史料評估全球交換代價",
      ],
    },
    {
      key: "POLITICAL_REVOLUTIONS_CITIZENSHIP",
      title: "Political revolutions and modern citizenship",
      authorityCodes: ["歷Qa-Ⅳ-1", "歷Oa-Ⅳ-3", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2", "歷1c-Ⅳ-2", "社2c-Ⅳ-2"],
      prerequisiteFamilyKeys: ["MARITIME_EXPANSION_EXCHANGE"],
      skills: [
        "由殖民治理與啟蒙思想理解美國獨立",
        "整理法國大革命的背景進程與影響",
        "比較兩場革命中的權利與政治主張",
        "分析公民身分擴張與排除的並存",
        "區分革命宣言理念與實際制度結果",
        "連結政治革命與近代憲政發展",
      ],
    },
    {
      key: "INDUSTRIAL_REVOLUTION_CAPITALISM",
      title: "Industrial Revolution and capitalism",
      authorityCodes: ["歷Qa-Ⅳ-2", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2", "社1b-Ⅳ-1", "社2b-Ⅳ-1"],
      prerequisiteFamilyKeys: ["POLITICAL_REVOLUTIONS_CITIZENSHIP"],
      skills: [
        "由能源技術資本與市場解釋工業革命",
        "比較工場手工業與工廠生產",
        "分析交通都市化與人口生活變化",
        "由勞動史料理解工人處境與改革",
        "比較工業化帶來的成長與不平等",
        "說明工業革命是長期累積而非單一發明",
      ],
    },
    {
      key: "NATIONALISM_NATION_STATES",
      title: "Nationalism and nation-state formation",
      authorityCodes: ["歷Qa-Ⅳ-3", "歷Qb-Ⅳ-1", "歷Qb-Ⅳ-2", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2", "歷1c-Ⅳ-2", "社2c-Ⅳ-1"],
      prerequisiteFamilyKeys: ["INDUSTRIAL_REVOLUTION_CAPITALISM"],
      skills: [
        "理解民族認同與國家疆界的歷史形成",
        "整理德義等地國家建立進程",
        "分析帝國內民族運動的不同訴求",
        "比較民族主義促成統一與衝突的作用",
        "由語言教育象徵辨識國族建構",
        "避免把今日國界投射為古代固定事實",
      ],
    },
    {
      key: "IMPERIALISM_COLONIALISM",
      title: "Imperialism and colonialism",
      authorityCodes: ["歷Qb-Ⅳ-1", "歷Qb-Ⅳ-2", "歷Ob-Ⅳ-2", "歷Ob-Ⅳ-3", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2", "歷1c-Ⅳ-2", "社2b-Ⅳ-1"],
      prerequisiteFamilyKeys: ["NATIONALISM_NATION_STATES"],
      skills: [
        "由工業資本戰略與思想解釋帝國擴張",
        "用地圖比較殖民勢力分布變化",
        "分析殖民統治的經濟社會文化影響",
        "比較亞洲非洲美洲不同回應方式",
        "由被殖民者史料理解能動性與抵抗",
        "評估殖民遺緒對後來國家社會的影響",
      ],
    },
    {
      key: "FIRST_WORLD_WAR_INTERWAR",
      title: "First World War and interwar world",
      authorityCodes: ["歷Qb-Ⅳ-3", "歷Qc-Ⅳ-1", "歷R-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2", "歷1c-Ⅳ-2"],
      prerequisiteFamilyKeys: ["IMPERIALISM_COLONIALISM"],
      skills: [
        "以長短期因素解釋第一次世界大戰",
        "由戰線科技與動員理解總體戰",
        "分析戰爭對平民帝國與國際秩序的影響",
        "評估戰後和約與國際組織的限制",
        "由經濟社會資料理解戰間期危機",
        "比較不同國家威權政治興起的條件",
      ],
    },
    {
      key: "SECOND_WORLD_WAR_CONSEQUENCES",
      title: "Second World War and its consequences",
      authorityCodes: ["歷Qc-Ⅳ-1", "歷Qc-Ⅳ-2", "歷R-Ⅳ-1", "歷Kb-Ⅳ-2", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2", "歷1c-Ⅳ-2", "社2c-Ⅳ-2"],
      prerequisiteFamilyKeys: ["FIRST_WORLD_WAR_INTERWAR"],
      skills: [
        "整理歐亞戰場擴大的主要進程",
        "分析法西斯擴張與戰爭爆發關係",
        "由平民史料理解占領迫害與大屠殺",
        "比較各地動員抵抗與戰時生活",
        "分析戰爭科技與原子武器的影響",
        "連結戰後審判國際組織與人權發展",
      ],
    },
    {
      key: "COLD_WAR_DECOLONIZATION",
      title: "Cold War and decolonization",
      authorityCodes: ["歷Qc-Ⅳ-3", "歷Lb-Ⅳ-1", "歷Lb-Ⅳ-2", "歷R-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2", "社2a-Ⅳ-3"],
      prerequisiteFamilyKeys: ["SECOND_WORLD_WAR_CONSEQUENCES"],
      skills: [
        "由意識形態安全與勢力範圍理解冷戰",
        "比較美蘇陣營競爭與代理衝突",
        "分析亞洲非洲去殖民化的多樣道路",
        "理解新國家面對疆界經濟與認同問題",
        "由不結盟與區域組織理解第三種選擇",
        "說明冷戰格局與地方因素共同作用",
      ],
    },
    {
      key: "GLOBALIZATION_POST_COLD_WAR",
      title: "Globalization and post-Cold-War change",
      authorityCodes: ["歷Qc-Ⅳ-3", "歷La-Ⅳ-2", "歷Lb-Ⅳ-1", "歷Lb-Ⅳ-2", "歷R-Ⅳ-1", "歷1a-Ⅳ-2", "社1b-Ⅳ-1", "社2a-Ⅳ-3"],
      prerequisiteFamilyKeys: ["COLD_WAR_DECOLONIZATION"],
      skills: [
        "整理冷戰結束後國際秩序變化",
        "由科技貿易移民理解全球連結加深",
        "分析區域組織與跨國議題的發展",
        "比較全球化對不同地區群體的影響",
        "以歷史脈絡理解當代衝突與合作",
        "避免把尚在發展的事件當成固定結論",
      ],
    },
    {
      key: "TAIWAN_REGIONAL_GLOBAL_HISTORY",
      title: "Taiwan in regional and global history",
      authorityCodes: ["歷Bb-Ⅳ-1", "歷Fa-Ⅳ-4", "歷Fb-Ⅳ-1", "歷G-Ⅳ-2", "歷La-Ⅳ-2", "歷Lb-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-2", "社2a-Ⅳ-2", "社2a-Ⅳ-3"],
      prerequisiteFamilyKeys: ["GLOBALIZATION_POST_COLD_WAR"],
      skills: [
        "把臺灣史事件放回東亞海域脈絡",
        "追蹤移民商品思想與制度跨域流動",
        "比較臺灣與鄰近地區的共同變遷",
        "分析戰爭冷戰與全球經濟對臺灣影響",
        "由多國史料理解臺灣國際處境",
        "用跨尺度證據連結地方區域與世界史",
      ],
    },
    {
      key: "INTEGRATED_DOCUMENT_REASONING",
      title: "Integrated document, map, timeline and causation reasoning",
      authorityCodes: ["歷D-Ⅳ-2", "歷G-Ⅳ-2", "歷J-Ⅳ-1", "歷M-Ⅳ-1", "歷P-Ⅳ-1", "歷R-Ⅳ-1", "歷1a-Ⅳ-1", "歷1a-Ⅳ-2", "歷1b-Ⅳ-1", "歷1b-Ⅳ-2", "歷1c-Ⅳ-1", "歷1c-Ⅳ-2", "社2b-Ⅳ-3", "社2c-Ⅳ-3", "社3a-Ⅳ-1", "社3b-Ⅳ-1", "社3b-Ⅳ-2", "社3b-Ⅳ-3", "社3c-Ⅳ-1", "社3c-Ⅳ-2", "社3d-Ⅳ-1", "社3d-Ⅳ-2", "社3d-Ⅳ-3"],
      prerequisiteFamilyKeys: ["TAIWAN_REGIONAL_GLOBAL_HISTORY"],
      skills: [
        "對齊史料地圖年表的時間與空間",
        "從多份資料辨認一致互補與衝突證據",
        "區分事件導火線條件與長期成因",
        "比較變遷中的延續轉折與影響範圍",
        "提出有史料依據且承認限制的解釋",
        "以文字圖表年表清楚呈現探究結果",
      ],
    },
  ],
});
