const UNIT_ID = "ENG_R4_U12";

function lecture(id, skillId, content) {
  return {
    id,
    skillId,
    ...content,
    sections: content.sections.map((section, index) => ({
      id: `${id}_SEC_${String(index + 1).padStart(2, "0")}`,
      ...section,
    })),
  };
}

function question({ id, skillId, difficulty, stem, options, answerIndex, reasons, reviews, cognitiveProcess, representationType = "sentence-cloze", misconceptionTargets = [] }) {
  return { id, skillId, stem, options, answerIndex, reasons, difficulty, cognitiveProcess, representationType, misconceptionTargets, reviews };
}

export const ENGLISH_U12_LECTURES = [
  lecture("ENG_R4_L_S078", "ENG_R4_S078", {
    objectives: ["使用 have 或 has 加過去分詞談過去經驗。", "辨認沒有指出確切過去時間、但和現在有關的經驗句。"],
    sections: [
      { title: "現在完成式的基本結構", content: "現在完成式由 subject + have/has + past participle 組成，例如 I have visited Tainan。have 或 has 負責形成時態，主要動詞必須改成過去分詞，不能只放原形或一般過去式。" },
      { title: "經驗重點在有沒有做過", content: "談人生經驗時，說話者關心的是某件事是否曾發生，不一定說明哪一天。例如 We have tried the game twice 表示到目前為止有兩次經驗；twice 是次數，不是確切日期。" },
      { title: "不和已結束的明確時間直接並用", content: "若句中明確說 yesterday、last Sunday 或 in 2024，通常使用過去簡單式，例如 I visited Tainan last year。現在完成式保留過去與現在的連結，不把事件鎖在一個已結束的過去時點。" },
      { title: "經驗和目前結果要分清楚", content: "I have lost my key 可強調現在仍受遺失影響；I have been to Hualien 則談曾去過的經驗。兩者都使用現在完成式，但一個凸顯目前結果，一個回答是否有過該經驗。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S078_EX_01", prompt: "Up to now, I ___ that museum twice. (have visited / visited / has visit)", steps: ["up to now 把範圍延伸到現在。", "twice 表示累計次數。", "主詞 I 搭配 have visited。"], answer: "have visited", why: "up to now 與 twice 要統計截至目前的兩次參觀經驗，因此用 have visited。visited 切斷現在連結，has visit 則同時錯在主詞搭配與分詞形式。" },
      { id: "ENG_R4_L_S078_EX_02", prompt: "Leo has seen snow before. What do we know? (at least one experience / a daily habit / a plan for tomorrow)", steps: ["before 不指定日期。", "has seen 表示目前以前的經驗。", "排除句中未提到的習慣與未來。"], answer: "at least one experience", why: "has seen snow before 只保證 Leo 截至目前至少看過一次雪，沒有說他每天看雪，也沒有預告明天。答案必須保留原句的經驗範圍。" },
      { id: "ENG_R4_L_S078_EX_03", prompt: "Since January, we ___ this song many times. (have heard / heard / has hearing)", steps: ["Since January 建立延續至今的範圍。", "many times 給出累計次數。", "We 搭配 have heard。"], answer: "have heard", why: "從一月到現在的時間範圍尚與目前相連，many times 又要求累計次數，所以完整形式是 we have heard。heard 只報過去，has hearing 也不合結構。" },
    ],
    misconceptions: [
      { belief: "現在完成式只是把 have 放在一般過去式前面。", whyWrong: "主要動詞必須使用過去分詞，有些不規則動詞的過去式和過去分詞不同。", correction: "逐一確認 have/has 與 past participle，像 has seen 而不是 has saw。" },
      { belief: "只要事情發生在過去，就一定要用現在完成式。", whyWrong: "明確指出已結束時間時，通常改用過去簡單式。", correction: "先看重點是經驗與現在連結，還是某個已完成的過去時點。" },
      { belief: "twice 和 many times 都是明確過去時間，所以不能用現在完成式。", whyWrong: "它們表示次數，沒有說事件發生在哪一天。", correction: "次數可和現在完成式一起累計到目前為止的經驗。" },
      { belief: "have been to 和 have gone to 在所有情境意思完全相同。", whyWrong: "been to 常表示去過且已回來；gone to 常表示已去而目前不在原處。", correction: "依人物目前位置判斷是在談經驗，還是人已經前往別處。" },
    ],
    checks: [
      { prompt: "has saw 應改哪個字？", answer: "saw → seen", reason: "has 後需要 see 的過去分詞 seen。" },
      { prompt: "twice 是確切日期還是經驗次數？", answer: "an experience count", reason: "twice 說明做過兩次，沒有指出日期。" },
      { prompt: "I visited there last year 為何不用 have visited？", answer: "last year is a finished past time", reason: "last year 把事件放在已結束的明確過去時段。" },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S079", "ENG_R4_S079", {
    objectives: ["依主詞選用 have 或 has 形成現在完成式。", "在肯定、否定、問句與簡答中維持相同助動詞。"],
    sections: [
      { title: "I、you 與複數主詞用 have", content: "I、you、we、they 以及複數名詞搭配 have，例如 They have finished the work。have 在此是形成現在完成式的助動詞，後面仍要接過去分詞。" },
      { title: "第三人稱單數用 has", content: "he、she、it、單一人名與單數名詞搭配 has，例如 Mia has written the note。不要因後面動詞是 write 就忽略主詞，或把 has 後面的分詞改回原形。" },
      { title: "問句與否定移動 have 或 has", content: "問句把 Have 或 Has 放到主詞前：Has Ben arrived? 否定把 not 放在 have/has 後：Ben has not arrived。have not 和 has not 可縮寫為 haven't 與 hasn't。" },
      { title: "簡答要回應原問句", content: "Have they eaten? 的簡答是 Yes, they have 或 No, they haven't；Has Amy called? 則回答 Yes, she has 或 No, she hasn't。不能換成 do、did 或 is，因為原問句使用 have/has。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S079_EX_01", prompt: "My parents ___ finished dinner. (have / has / are)", steps: ["My parents 是複數。", "複數主詞搭配 have。", "have 後已有過去分詞 finished。"], answer: "have", why: "My parents 指兩位家長，因此現在完成式使用 have finished。has 只配第三人稱單數，are finished 會改變原本主動完成晚餐的意思。" },
      { id: "ENG_R4_L_S079_EX_02", prompt: "Nora ___ not read the message yet. (has / have / does)", steps: ["Nora 是第三人稱單數。", "否定詞放在 has 後。", "read 是此處的過去分詞。"], answer: "has", why: "單一人名 Nora 搭配 has，形成 has not read。have 不合主詞，does not read 會改成現在簡單式，無法保留 yet 所指的尚未完成狀態。" },
      { id: "ENG_R4_L_S079_EX_03", prompt: "___ the students left the room? (Have / Has / Did have)", steps: ["the students 是複數。", "把 Have 移到主詞前。", "left 保持 leave 的過去分詞。"], answer: "Have", why: "複數主詞 the students 在現在完成式問句使用 Have，答案為 Have the students left the room?。Has 不合主詞，Did have 疊加了不需要的助動詞。" },
    ],
    misconceptions: [
      { belief: "只要主詞超過一個字，就要使用 have。", whyWrong: "主詞長短不決定單複數，The new student 仍是單數。", correction: "找出主詞中心名詞，再依單數或複數選 has 或 have。" },
      { belief: "has 後的主要動詞要加 s，形成 has writes。", whyWrong: "第三人稱變化已由 has 表示，主要動詞要用過去分詞。", correction: "寫 has written、has eaten 或 has finished。" },
      { belief: "現在完成式問句要在前面另加 do。", whyWrong: "have 或 has 本身可以移到主詞前形成問句。", correction: "直接使用 Have you...? 或 Has she...?，不要疊加 do。" },
      { belief: "Have you...? 可以回答 Yes, I do。", whyWrong: "簡答必須沿用原問句的助動詞 have。", correction: "回答 Yes, I have 或 No, I haven't。" },
    ],
    checks: [
      { prompt: "The dog have eaten. 哪個字要改？", answer: "have → has", reason: "The dog 是第三人稱單數。" },
      { prompt: "Have they arrived? 的肯定簡答是什麼？", answer: "Yes, they have.", reason: "簡答沿用 Have 與主詞 they。" },
      { prompt: "hasn't 中已包含哪兩個字？", answer: "has not", reason: "hasn't 是 has not 的縮寫。" },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S080", "ENG_R4_S080", {
    objectives: ["辨識規則與常見不規則動詞的過去分詞。", "區分原形、一般過去式與過去分詞在句中的位置。"],
    sections: [
      { title: "規則動詞的過去分詞", content: "多數規則動詞的過去式和過去分詞同為 -ed 形式，例如 visit–visited–visited、finish–finished–finished。即使形式相同，has visited 中的 visited 仍由前面的 has 判斷為過去分詞。" },
      { title: "不規則動詞要分三種形式", content: "有些動詞三種形式不同，例如 write–wrote–written、see–saw–seen、take–took–taken。一般過去式用 wrote、saw、took；have/has 後則用 written、seen、taken。" },
      { title: "有些形式相同仍要看結構", content: "buy–bought–bought、hear–heard–heard 的過去式與過去分詞相同。I bought it yesterday 是過去簡單式；I have bought it before 中 bought 因 have 而成為過去分詞。" },
      { title: "be、go 與 do 的常見分詞", content: "be 的過去分詞是 been，go 是 gone，do 是 done。have been 常用於經驗或持續狀態；has gone 常表示某人已前往別處；have done 表示已完成。必須依句意選字，不能只背中文。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S080_EX_01", prompt: "She has ___ the letter. (written / wrote / write)", steps: ["has 後需要過去分詞。", "write 的三態是 write–wrote–written。", "選 written。"], answer: "written", why: "句中 has 已建立現在完成式，write 必須改成過去分詞 written。wrote 只能單獨作一般過去式，write 則是原形。" },
      { id: "ENG_R4_L_S080_EX_02", prompt: "We have ___ that picture before. (seen / saw / see)", steps: ["have 後接過去分詞。", "see 的過去分詞是 seen。", "before 表過去到現在以前。"], answer: "seen", why: "have seen 是現在完成式，表示以前看過該圖片。saw 是 see 的一般過去式，不能直接放在 have 後；see 也不是所需分詞。" },
      { id: "ENG_R4_L_S080_EX_03", prompt: "Ben has ___ his work. (done / did / do)", steps: ["has 要接過去分詞。", "do–did–done 三種形式不同。", "使用 done。"], answer: "done", why: "完成式需要 has done，done 是 do 的過去分詞。did 已經是一般過去式，do 是原形，兩者都不能接在 has 後形成本句。" },
    ],
    misconceptions: [
      { belief: "所有過去分詞都等於動詞加 -ed。", whyWrong: "許多常見動詞是不規則變化，例如 seen、written、done。", correction: "把不規則動詞的原形、過去式與過去分詞一起比較記憶。" },
      { belief: "wrote 表示過去，所以可以寫 has wrote。", whyWrong: "wrote 是一般過去式，has 後需要 written。", correction: "看見 have/has 時先找第三態，而不是任一過去形式。" },
      { belief: "過去式和過去分詞長得相同時，兩者功能也完全相同。", whyWrong: "bought 雖形式相同，是否有 have/has 仍決定句型。", correction: "從整個動詞組判斷時態，不只看單一字的外形。" },
      { belief: "been 與 gone 都只表示去過某地，沒有差別。", whyWrong: "been to 通常談去過且已回來；gone to 常表示人目前已去那裡。", correction: "配合人物目前是否在場，選擇 been 或 gone。" },
    ],
    checks: [
      { prompt: "see–saw–___ 的第三個形式是什麼？", answer: "seen", reason: "seen 是 see 的過去分詞。" },
      { prompt: "has wrote 應改成什麼？", answer: "has written", reason: "has 後需用 write 的過去分詞 written。" },
      { prompt: "bought 可同時是過去式與過去分詞嗎？", answer: "yes", reason: "buy 的後兩種形式都是 bought，但句中結構不同。" },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S081", "ENG_R4_S081", {
    objectives: ["使用 ever 詢問截至目前是否有某種經驗。", "使用 never 表達截至目前一次也沒有的經驗。"],
    sections: [
      { title: "ever 常用於經驗問句", content: "ever 表示在到目前為止的任何時候，常放在 have/has 與過去分詞之間，例如 Have you ever ridden a horse?。它詢問有沒有這項經驗，不要求回答確切日期。" },
      { title: "never 本身已有否定意思", content: "never 表示一次也沒有，位置同樣在 have/has 後、過去分詞前，例如 I have never ridden a horse。因為 never 已是否定，不再寫 haven't never。" },
      { title: "回答經驗後可再補過去細節", content: "對 Have you ever...? 可先回答 Yes, I have，再用過去簡單式補充 When did you do it? 或 I did it last summer。經驗與確切事件可分成兩句，時態也隨資訊改變。" },
      { title: "ever 並非每句都必須出現", content: "Have you visited Japan? 也能詢問截至目前的經驗；ever 讓「任何時候曾否」更明確。never 則是說話者的否定陳述，不能拿來代替一般問句中的 ever。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S081_EX_01", prompt: "Have you ___ seen a whale? (ever / never / yesterday)", steps: ["句子詢問有沒有經驗。", "ever 放在 have 與 seen 之間。", "不加入明確過去時間。"], answer: "ever", why: "問句要詢問到目前為止是否看過鯨魚，ever 正好表示任何過去時候。never 會把問題變成帶否定預設，yesterday 則和現在完成式不合。" },
      { id: "ENG_R4_L_S081_EX_02", prompt: "Mia has ___ flown in a plane. (never / ever did / not never)", steps: ["句子陳述零次經驗。", "never 本身是否定。", "放在 has 與 flown 之間。"], answer: "never", why: "Mia has never flown 表示截至現在一次也沒有搭飛機的經驗。ever did 破壞完成式，not never 形成不必要的雙重否定。" },
      { id: "ENG_R4_L_S081_EX_03", prompt: "A: Have they ever won a game? B: Yes, they ___. (have / did yesterday / has)", steps: ["問句助動詞是 Have。", "主詞 they 保持不變。", "肯定簡答使用 have。"], answer: "have", why: "簡答必須沿用原問句的 have，所以回答 Yes, they have。did yesterday 改成另一個過去事件，has 不配複數 they。" },
    ],
    misconceptions: [
      { belief: "ever 只能翻成曾經，所以肯定句一定要加 ever。", whyWrong: "一般經驗肯定句可不用 ever，語意仍完整。", correction: "把 ever 視為強調任何時候，常用於問句，而非每句必備。" },
      { belief: "never 前還要加 not 才有否定意思。", whyWrong: "never 本身已表示一次也沒有，再加 not 會改變或混亂意思。", correction: "直接使用 have/has never + 過去分詞。" },
      { belief: "Have you ever...? 必須用確切日期作答。", whyWrong: "問句先問有沒有經驗，可只回答 Yes, I have 或 No, I haven't。", correction: "若要補日期，再另用過去簡單式說明那次事件。" },
      { belief: "ever 和 never 可放在句尾任何位置。", whyWrong: "本課經驗句通常把它們放在 have/has 與過去分詞之間。", correction: "寫 Have you ever tried...? 與 I have never tried...。" },
    ],
    checks: [
      { prompt: "Have you ever eaten this? 中 ever 放在哪兩部分之間？", answer: "have and eaten", reason: "經驗問句把 ever 放在助動詞與分詞之間。" },
      { prompt: "I haven't never seen it 有何問題？", answer: "double negative", reason: "haven't 與 never 都是否定，不能在本意中重複。" },
      { prompt: "Have they ever won? 的肯定簡答是什麼？", answer: "Yes, they have.", reason: "沿用問句的 have。" },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S082", "ENG_R4_S082", {
    objectives: ["使用 already 表達事情比預期早或已經完成。", "使用 yet 詢問或否定截至目前是否完成。"],
    sections: [
      { title: "already 常出現在肯定完成句", content: "already 表示事情已經發生，常放在 have/has 與過去分詞之間，例如 She has already finished。它有時帶出比預期早的感覺，但核心是截至現在事情已完成。" },
      { title: "yet 常放在問句與否定句尾", content: "Have you finished yet? 詢問到現在完成了嗎；I haven't finished yet 表示到現在仍未完成。國中常見用法把 yet 放在句尾，讀題時也要注意問號或否定詞。" },
      { title: "already 與 yet 不只靠中文判斷", content: "兩者都可能翻成「已經／還」，但句型位置與說話目的不同。already 多陳述已完成，yet 多詢問是否完成或說明尚未完成；不要只看中文翻譯互換。" },
      { title: "真實英語有變化，題目需給明確限制", content: "口語中 already 也可能出現在句尾，yet 偶爾可出現在肯定語境。學習基本形式時先掌握常見位置；考題若要求唯一答案，應利用肯定、否定、問句與字序提供清楚依據。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S082_EX_01", prompt: "The bus has ___ left. (already / yet / last night)", steps: ["句子是肯定完成式。", "事件已發生。", "already 放在 has 與 left 之間。"], answer: "already", why: "has already left 表示公車已經離開，肯定句與字序都完整。yet 在本課基本用法多出現在問句或否定句尾，last night 則是明確過去時間。" },
      { id: "ENG_R4_L_S082_EX_02", prompt: "Have you read the note ___? (yet / already did / yesterday)", steps: ["這是詢問完成狀態的問句。", "yet 常放在問句尾。", "不加入 did 或明確過去時間。"], answer: "yet", why: "問句要確認到現在是否讀完，因此句尾使用 yet。already did 破壞 have read 結構，yesterday 會把問題轉成明確過去事件。" },
      { id: "ENG_R4_L_S082_EX_03", prompt: "We haven't eaten dinner ___. (yet / already / last Sunday)", steps: ["haven't 表示尚未完成。", "yet 放在否定句尾。", "句子關心目前狀態。"], answer: "yet", why: "haven't eaten...yet 表示到現在還沒吃晚餐，否定與句尾位置互相配合。already 與否定句在此不合預期語意，last Sunday 則和完成式衝突。" },
    ],
    misconceptions: [
      { belief: "already 只能放在整句最後。", whyWrong: "國中常見完成式把 already 放在 have/has 與分詞之間。", correction: "先掌握 has already finished 這個基本位置。" },
      { belief: "yet 一律表示否定，所以不能出現在問句。", whyWrong: "yet 常用來詢問截至目前是否已完成。", correction: "在 Have you finished yet? 中，yet 位於問句尾。" },
      { belief: "看到中文的「已經」就不必檢查時態和字序。", whyWrong: "選項可能混入明確過去時間或錯誤助動詞。", correction: "同時確認 have/has、過去分詞、肯否定與副詞位置。" },
      { belief: "already 與 yet 在任何句型都能自由互換。", whyWrong: "兩者的常見語用與位置不同，互換可能改變說話目的。", correction: "用 already 陳述已完成，用 yet 詢問或表示尚未完成的基本情境。" },
    ],
    checks: [
      { prompt: "has already finished 中 already 在哪裡？", answer: "between has and finished", reason: "基本肯定句把 already 放在助動詞與分詞之間。" },
      { prompt: "Have you called her ___? 應填什麼？", answer: "yet", reason: "問句詢問到現在是否完成，yet 放在句尾。" },
      { prompt: "I haven't finished yet 表示什麼？", answer: "the work is still not finished", reason: "截至目前事情仍未完成。" },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S083", "ENG_R4_S083", {
    objectives: ["使用 since 加起點表示狀態從過去延續至今。", "使用 for 加一段時間表示持續長度。"],
    sections: [
      { title: "since 後接開始點", content: "since 指出持續狀態從何時開始，後面接時間點，例如 since Monday、since 2022、since I was ten。現在完成式表示該狀態從起點延續到現在。" },
      { title: "for 後接持續長度", content: "for 回答持續多久，後面接一段時間，例如 for two hours、for three years、for a long time。不能把一段長度直接放在 since 後。" },
      { title: "先分辨點與段，再看是否延續", content: "Monday 是時間點，two days 是時間長度；因此說 since Monday、for two days。還要確認動作或狀態能延續到現在，若事件在明確過去已結束，可能需要過去簡單式。" },
      { title: "部分動詞的持續表達要符合語意", content: "live、know、be 等狀態可自然延續，例如 I have known Amy for years。一次完成的短動作若要表示持續，通常需改寫成可延續狀態，不能只套 since 或 for。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S083_EX_01", prompt: "We have lived here ___ 2021. (since / for / ago)", steps: ["2021 是開始時間點。", "狀態從該年延續到現在。", "時間點前使用 since。"], answer: "since", why: "2021 是居住開始的時間點，因此使用 since 形成 have lived here since 2021。for 要接一段長度，ago 則把時間往過去定位，不能放入此完成式。" },
      { id: "ENG_R4_L_S083_EX_02", prompt: "Ben has studied English ___ two hours. (for / since / from)", steps: ["two hours 是時間長度。", "問的是持續多久。", "長度前使用 for。"], answer: "for", why: "two hours 表示讀英文持續的長度，所以選 for。since 要接起點，例如 since seven；from 若要表時間範圍，通常還需另一端。" },
      { id: "ENG_R4_L_S083_EX_03", prompt: "I have known Grace ___ we were children. (since / for / during)", steps: ["we were children 是起點子句。", "認識的狀態延續至今。", "起點前使用 since。"], answer: "since", why: "since 可接一個說明起點的子句，since we were children 表示從兒時開始認識到現在。for 不能直接接完整起點子句，during 也不形成此持續結構。" },
    ],
    misconceptions: [
      { belief: "since 和 for 都表示持續，所以可以任意互換。", whyWrong: "since 接起點，for 接時間長度，後面的資訊類型不同。", correction: "先問是何時開始，還是持續多久，再選 since 或 for。" },
      { belief: "two years 是時間點，所以應寫 since two years。", whyWrong: "two years 是一段長度，不是開始日期。", correction: "寫 for two years；若給 2022 這類起點才用 since。" },
      { belief: "since 後面只能接單一日期，不能接句子。", whyWrong: "since 也可接描述起點的子句，例如 since I was ten。", correction: "確認子句說明開始時刻，並讓主句狀態延續至今。" },
      { belief: "任何已完成一次的動作都能加 for 表示持續。", whyWrong: "一次性動作本身沒有可持續的長度，硬加 for 會使語意不自然。", correction: "改用能延續的動作或狀態，再表達持續時間。" },
    ],
    checks: [
      { prompt: "Monday 是時間點還是時間長度？", answer: "a point in time", reason: "它指出開始的日子，前面使用 since。" },
      { prompt: "three months 前使用 since 還是 for？", answer: "for", reason: "three months 是持續長度。" },
      { prompt: "since I was ten 中 since 後接的是什麼？", answer: "a clause showing the starting point", reason: "子句交代狀態開始的時候。" },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S084", "ENG_R4_S084", {
    objectives: ["依時間是否明確且已結束，區分現在完成式與過去簡單式。", "依經驗、目前結果或延續狀態選擇合適時態。"],
    sections: [
      { title: "明確且已結束的過去時間", content: "yesterday、last night、two days ago 與 in 2020 都把事件放在已結束的過去時點，通常使用過去簡單式，例如 I saw the movie last night，而不是 I have seen it last night。" },
      { title: "沒有確切時間的經驗", content: "若重點是到目前為止是否有過經驗，可用現在完成式，例如 I have seen the movie before。before 在此沒有指出哪一天，只把經驗放在現在以前。" },
      { title: "目前結果與延續狀態", content: "She has lost her key 可表示鑰匙現在仍不在；We have lived here for five years 表示居住延續至今。現在完成式不只是「過去」，還要保留和現在的結果或時間連結。" },
      { title: "today 等未結束時段要看情境", content: "today、this week 等時間可能尚未結束，因此不一定排斥現在完成式，例如 I have read two books this week。若說話者把事件當作已完成的特定時點，也可能用過去式；不能把單一時間詞當成永遠規則。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S084_EX_01", prompt: "I ___ the book last night. (finished / have finished / has finished)", steps: ["last night 是已結束時間。", "使用過去簡單式。", "finish 的過去式是 finished。"], answer: "finished", why: "last night 指定閱讀完成的明確過去時間，因此選 finished。have finished 會保留到現在的連結，卻不應直接和這個已結束時點搭配。" },
      { id: "ENG_R4_L_S084_EX_02", prompt: "The reading happened in 2023. Which sentence says this? (I read this book in 2023. / I have read this book in 2023. / I will read this book in 2023.)", steps: ["in 2023 是已結束的過去年份。", "已完成事件使用過去簡單式。", "read 在此讀作過去式。"], answer: "I read this book in 2023.", why: "題目已把閱讀放在 2023 這個明確過去年份，所以用過去簡單式 I read。現在完成式不能直接和該年份並用，will read 則把事件錯放成未來。" },
      { id: "ENG_R4_L_S084_EX_03", prompt: "Mia's key is still missing. Which sentence explains this? (She has lost it. / She found it yesterday. / She will lose it tomorrow.)", steps: ["still missing 指出目前狀態。", "找出能造成此狀態的過去事件。", "以 has lost 連結事件和結果。"], answer: "She has lost it.", why: "鑰匙目前仍找不到，She has lost it 能把先前遺失和現在結果連起來。found yesterday 與仍遺失矛盾，will lose tomorrow 也不能解釋眼前狀態。" },
    ],
    misconceptions: [
      { belief: "現在完成式和過去簡單式都談過去，所以任何句子都能互換。", whyWrong: "兩者對時間定位與現在連結的焦點不同。", correction: "檢查是否有已結束時點、人生經驗、目前結果或延續狀態。" },
      { belief: "句中出現 yesterday 仍可直接使用 have 加過去分詞。", whyWrong: "yesterday 是已結束的明確過去時間，通常要求過去簡單式。", correction: "寫 I saw it yesterday；移除確切時間後才可依經驗使用 have seen。" },
      { belief: "before 一定和 yesterday 一樣，都是明確日期。", whyWrong: "before 在經驗句中只表示現在以前，沒有說哪一天。", correction: "依是否提供確切過去時點，區分 have seen before 與 saw it yesterday。" },
      { belief: "today 一出現就只能用過去簡單式。", whyWrong: "today 可能尚未結束，事件也可能累計到目前。", correction: "判斷說話者是否把 today 視為仍進行的時間區段，並閱讀完整情境。" },
    ],
    checks: [
      { prompt: "last year 通常搭配哪個時態？", answer: "past simple", reason: "它是已結束的明確過去時間。" },
      { prompt: "have visited before 強調日期還是經驗？", answer: "experience", reason: "before 沒有提供確切日期。" },
      { prompt: "has lost the key 為何可和 now 有關？", answer: "the key is still missing", reason: "過去遺失造成目前仍找不到鑰匙的結果。" },
    ],
    assets: [],
  }),
];

export const ENGLISH_U12_QUESTIONS = [
  question({ id: "ENG_R4_Q_078_01", skillId: "ENG_R4_S078", difficulty: "foundation", stem: "Up to now, I ___ that museum twice.", options: ["have visited", "visited", "has visit", "am visiting"], answerIndex: 0,
    reasons: ["have visited 可累計截至目前的兩次參觀經驗。", "visited 是一般過去式，沒有保留 up to now 的現在連結。", "I 不搭配 has，且 visit 不是過去分詞。", "am visiting 表示此刻正在參觀，不能累計兩次經驗。"],
    reviews: ["up to now 與 twice 共同限定截至目前的經驗次數。", "第一項完整使用 I have visited；其餘選項不是切斷現在連結，就是破壞動詞結構。"], cognitiveProcess: ["combine-up-to-now-with-experience-count", "apply-have-visited-with-i"], misconceptionTargets: ["ignore-explicit-up-to-now-frame"] }),
  question({ id: "ENG_R4_Q_078_02", skillId: "ENG_R4_S078", difficulty: "foundation", stem: "Leo has seen snow before. What does the sentence tell us?", options: ["He is watching snow now.", "He has had this experience at least once.", "He sees snow every night.", "He will see snow tomorrow."], answerIndex: 1,
    reasons: ["現在完成式沒有表示此刻正在看雪。", "before 表示截至目前至少有過一次看雪經驗。", "句中沒有 every night 這類習慣線索。", "句子回顧目前以前，不是預告明天。"],
    reviews: ["本題要讀懂 has seen...before，而不是只辨認動詞形式。", "第二項保留非特定經驗的範圍；其他選項擅自加入現在動作、習慣或未來。"], cognitiveProcess: ["interpret-leo-has-seen-snow", "exclude-added-time-claims"], representationType: "experience-meaning-selection", misconceptionTargets: ["treat-present-perfect-as-present-action"] }),
  question({ id: "ENG_R4_Q_078_03", skillId: "ENG_R4_S078", difficulty: "foundation", stem: "Since January, we ___ this song many times.", options: ["heard", "has hearing", "have heard", "have hear"], answerIndex: 2,
    reasons: ["heard 是一般過去式，未呈現從一月累計至今。", "We 不搭配 has，hearing 也不是所需分詞。", "have heard 正確連結一月起點與多次收聽經驗。", "hear 是原形，不能直接接在 have 後。"],
    reviews: ["Since January 建立延續到現在的時間範圍，many times 則給出累計次數。", "第三項的主詞、助動詞與 heard 分詞都符合這兩項線索。"], cognitiveProcess: ["combine-since-january-with-repeat-count", "form-we-have-heard"], misconceptionTargets: ["use-simple-past-inside-continuing-period"] }),
  question({ id: "ENG_R4_Q_078_04", skillId: "ENG_R4_S078", difficulty: "standard", stem: "Grace has ___ in a school play before.", options: ["be", "was", "being", "been"], answerIndex: 3,
    reasons: ["be 是原形，不能直接接在 has 後。", "was 是一般過去式，不是過去分詞。", "being 是現在分詞，不能組成此處的現在完成式。", "been 是 be 的過去分詞，可表達曾有參加校內演出的經驗。"],
    reviews: ["before 表示截至目前曾經有過這項經驗，has 後需接過去分詞。", "第四項形成 Grace has been；其餘三項都不是 has 在此需要的動詞形式。"], cognitiveProcess: ["identify-prior-school-play-experience", "select-been-after-has"], representationType: "experience-participle-cloze", misconceptionTargets: ["substitute-past-form-for-past-participle"] }),
  question({ id: "ENG_R4_Q_078_05", skillId: "ENG_R4_S078", difficulty: "standard", stem: "“I have ridden a horse twice.” What does twice tell us?", options: ["The number of experiences", "The date of the first ride", "The horse's age", "How long each ride was"], answerIndex: 0,
    reasons: ["twice 表示騎過兩次。", "句中沒有提供第一次的日期。", "文中沒有馬的年齡。", "twice 不是每次騎乘的長度。"],
    reviews: ["現在完成式可和次數一起統計到目前為止的經驗。", "第一項只說明次數，不把 twice 誤讀成日期、年齡或時間長度。"], cognitiveProcess: ["interpret-twice-with-have-ridden", "exclude-date-age-duration-readings"], representationType: "experience-count-comprehension", misconceptionTargets: ["read-twice-as-date"] }),
  question({ id: "ENG_R4_Q_078_06", skillId: "ENG_R4_S078", difficulty: "standard", stem: "Which sentence asks about an experience without giving a date?", options: ["Did you swim yesterday?", "Have you tried this game before?", "Were you at home last night?", "Do you play every Friday?"], answerIndex: 1,
    reasons: ["yesterday 指定已結束的過去日期。", "Have you tried...before 詢問目前以前是否有過經驗。", "last night 是明確過去時間。", "every Friday 詢問固定習慣。"],
    reviews: ["題目要求經驗且不能給日期，before 只表示現在以前。", "第二項符合兩項條件；其他句子分別問昨天、昨夜或習慣。"], cognitiveProcess: ["classify-experience-question-without-date", "separate-experience-from-event-and-habit"], representationType: "sentence-purpose-classification", misconceptionTargets: ["choose-any-past-related-question"] }),
  question({ id: "ENG_R4_Q_078_07", skillId: "ENG_R4_S078", difficulty: "standard", stem: "Sam is here now. He has ___ to Japan twice.", options: ["went", "go", "been", "being"], answerIndex: 2,
    reasons: ["went 是一般過去式，不能接在 has 後。", "go 是原形。", "been to 表示去過且 Sam 現在已回來。", "being 不能表示這項旅遊經驗。"],
    reviews: ["Sam is here now 排除目前仍在日本的 gone 解讀。", "第三項形成 has been to Japan，並由 twice 表示兩次經驗。"], cognitiveProcess: ["use-current-presence-to-select-been", "complete-has-been-to-japan"], representationType: "presence-informed-experience", misconceptionTargets: ["use-went-after-has"] }),
  question({ id: "ENG_R4_Q_078_08", skillId: "ENG_R4_S078", difficulty: "advanced", stem: "Mia is not at home. Her father says, “She has ___ to the library.”", options: ["been", "go", "going", "gone"], answerIndex: 3,
    reasons: ["has been to 通常表示去過且已回來，與目前不在家不合。", "go 不是過去分詞。", "going 不能直接接 has。", "has gone 表示 Mia 已前往圖書館，目前尚未回家。"],
    reviews: ["is not at home 是判斷 been 與 gone 的重要現在資訊。", "第四項保留她已離開且尚未回家的結果；其他形式不合結構。"], cognitiveProcess: ["infer-absence-from-has-gone", "contrast-gone-with-returned-experience"], representationType: "current-location-inference", misconceptionTargets: ["treat-been-and-gone-as-identical"] }),
  question({ id: "ENG_R4_Q_078_09", skillId: "ENG_R4_S078", difficulty: "advanced", stem: "Which sentence reports life experience without a finished past time?", options: ["I have eaten this food before.", "I ate it at noon yesterday.", "I was hungry last night.", "I eat it every week."], answerIndex: 0,
    reasons: ["have eaten...before 表示到目前為止的經驗。", "at noon yesterday 是已結束的明確時間。", "last night 報告過去狀態。", "every week 表示習慣。"],
    reviews: ["life experience 的重點是做過與否，不需指定日期。", "第一項只有 before 這個非特定線索；其餘句子各有過去時點或頻率。"], cognitiveProcess: ["identify-life-experience-among-time-frames", "verify-no-finished-past-time"], representationType: "time-frame-discrimination", misconceptionTargets: ["confuse-frequency-with-experience"] }),
  question({ id: "ENG_R4_Q_078_10", skillId: "ENG_R4_S078", difficulty: "advanced", stem: "“I have lost my ticket.” What present problem does the sentence suggest?", options: ["The ticket was used last year.", "The speaker cannot find the ticket now.", "The speaker buys a ticket every day.", "The ticket will be lost tomorrow."], answerIndex: 1,
    reasons: ["句子沒有說去年使用。", "has lost 可連結到現在仍找不到票。", "文中沒有每日購票習慣。", "遺失已在現在以前發生，不是明天。"],
    reviews: ["現在完成式也可凸顯過去事件留下的目前結果。", "第二項解釋眼前問題；其他選項加入不存在的時間或習慣。"], cognitiveProcess: ["infer-current-result-from-have-lost", "reject-unmentioned-times-and-habit"], representationType: "present-result-inference", misconceptionTargets: ["read-present-perfect-as-future"] }),
  question({ id: "ENG_R4_Q_078_11", skillId: "ENG_R4_S078", difficulty: "transfer", stem: "A: Have you ever visited Penghu? B: Yes, I have. I went there last summer. Why does B use two tenses?", options: ["The first sentence is a plan; the second is a habit.", "Both sentences describe tomorrow.", "The first answers about experience; the second gives a finished past time.", "The second sentence corrects a spelling error."], answerIndex: 2,
    reasons: ["對話沒有未來計畫或習慣。", "last summer 明確指過去，不是明天。", "have 回答有無經驗，went 則配合已結束的去年夏天。", "時態改變來自資訊焦點，不是拼字修正。"],
    reviews: ["同一段對話可先用完成式回答經驗，再用過去式補確切時間。", "第三項正確連結兩句功能，沒有把時態差異誤當衝突。"], cognitiveProcess: ["explain-tense-shift-from-experience-to-event", "map-last-summer-to-simple-past"], representationType: "dialogue-tense-explanation", misconceptionTargets: ["force-one-tense-across-dialogue"] }),
  question({ id: "ENG_R4_Q_078_12", skillId: "ENG_R4_S078", difficulty: "transfer", stem: "A note says, “Nora has read the book three times.” What can we know from the note?", options: ["She read it only yesterday.", "She is reading it at this moment.", "She will read it three years from now.", "She has had three reading experiences up to now."], answerIndex: 3,
    reasons: ["three times 不等於只在昨天閱讀。", "完成式沒有說她此刻正在讀。", "句子不談三年後。", "three times 累計到目前為止的閱讀經驗。"],
    reviews: ["題目提供的是經驗次數，而不是每次的日期或當前動作。", "第四項保留完成式與 three times 的資訊，其他選項改變時間。"], cognitiveProcess: ["translate-three-times-into-cumulative-experience", "avoid-current-and-future-overread"], representationType: "experience-note-interpretation", misconceptionTargets: ["equate-present-perfect-with-action-now"] }),

  question({ id: "ENG_R4_Q_079_01", skillId: "ENG_R4_S079", difficulty: "foundation", stem: "My parents ___ finished dinner.", options: ["have", "has", "are", "did have"], answerIndex: 0,
    reasons: ["My parents 是複數，搭配 have。", "has 只配第三人稱單數。", "are finished 會改變句型與原意。", "did have 不形成本題現在完成式。"],
    reviews: ["先找主詞中心 parents，再判斷為複數。", "第一項和 finished 組成 have finished；其他助動詞不合主詞或時態。"], cognitiveProcess: ["identify-parents-as-plural-subject", "choose-have-before-finished"], misconceptionTargets: ["choose-has-for-long-subject"] }),
  question({ id: "ENG_R4_Q_079_02", skillId: "ENG_R4_S079", difficulty: "foundation", stem: "Nora ___ not read the message yet.", options: ["have", "has", "does", "is"], answerIndex: 1,
    reasons: ["Nora 是單數，不搭配 have。", "has not read 與 yet 形成尚未完成的意思。", "does not read 會改成現在簡單式。", "is not read 在此不是所需完成式。"],
    reviews: ["單一人名 Nora 使用 has，否定詞緊接其後。", "第二項保留 read 的過去分詞與句尾 yet；其餘選項改變結構。"], cognitiveProcess: ["agree-nora-with-has", "form-has-not-read-yet"], misconceptionTargets: ["use-does-with-present-perfect"] }),
  question({ id: "ENG_R4_Q_079_03", skillId: "ENG_R4_S079", difficulty: "foundation", stem: "___ the students left the room?", options: ["Has", "Did have", "Have", "Are"], answerIndex: 2,
    reasons: ["Has 不配複數 students。", "Did have 疊加不需要的助動詞。", "Have 可移到複數主詞前形成完成式問句。", "Are left 不是本題主動離開的完成式。"],
    reviews: ["the students 是複數，問句使用 Have they...? 的結構。", "第三項形成 Have the students left...?；其他選項不合主詞或時態。"], cognitiveProcess: ["invert-have-before-plural-students", "retain-left-as-participle"], misconceptionTargets: ["insert-did-before-have"] }),
  question({ id: "ENG_R4_Q_079_04", skillId: "ENG_R4_S079", difficulty: "standard", stem: "The new student ___ already joined the club.", options: ["have", "are", "do", "has"], answerIndex: 3,
    reasons: ["The new student 雖有三個字，中心名詞仍是單數。", "are joined 會變成不同語態。", "do already joined 不合助動詞結構。", "has already joined 配合單數主詞。"],
    reviews: ["主詞長度不等於複數，student 才是判斷核心。", "第四項與 joined 形成現在完成式，並保留 already 的位置。"], cognitiveProcess: ["find-singular-head-in-long-subject", "select-has-already-joined"], representationType: "subject-head-agreement", misconceptionTargets: ["count-words-instead-of-subject-number"] }),
  question({ id: "ENG_R4_Q_079_05", skillId: "ENG_R4_S079", difficulty: "standard", stem: "I ___ never tried that food.", options: ["have", "has", "am", "did"], answerIndex: 0,
    reasons: ["I 搭配 have，形成 have never tried。", "I 不使用 has。", "am never tried 會產生不合本意的被動形式。", "did never tried 同時錯用 did 與 tried。"],
    reviews: ["主詞 I 是 have/has 配對中的固定 have 類。", "第一項讓 never 位於助動詞與分詞之間；其他形式不成立。"], cognitiveProcess: ["pair-first-person-i-with-have", "place-never-before-tried"], misconceptionTargets: ["use-am-from-first-person-be-rule"] }),
  question({ id: "ENG_R4_Q_079_06", skillId: "ENG_R4_S079", difficulty: "standard", stem: "No food is left now. The dog ___ eaten all its food.", options: ["have", "has", "does", "is"], answerIndex: 1,
    reasons: ["The dog 是單數，不用 have。", "has eaten 配合單數，也能解釋目前沒有食物的結果。", "does 之後不能直接接過去分詞 eaten。", "is eaten all its food 不是可接受的主動完成式結構。"],
    reviews: ["單數主詞 The dog 使用 has，eaten 是 eat 的過去分詞。", "第二項保留主動進食；was 會造成不合理被動語意。"], cognitiveProcess: ["agree-singular-dog-with-has", "prevent-passive-meaning-reversal"], representationType: "agreement-and-voice-cloze", misconceptionTargets: ["choose-was-before-eaten"] }),
  question({ id: "ENG_R4_Q_079_07", skillId: "ENG_R4_S079", difficulty: "standard", stem: "You and Ben ___ known each other for years.", options: ["has", "is", "have", "does"], answerIndex: 2,
    reasons: ["You and Ben 是複合主詞，不用 has。", "is known 會改成被動且不合 each other。", "have known 配合兩人並表示持續關係。", "does known 不是正確完成式。"],
    reviews: ["and 連接 you 與 Ben，整體視為複數。", "第三項形成 have known each other；其他選項忽略複數或誤用助動詞。"], cognitiveProcess: ["treat-you-and-ben-as-compound-subject", "form-have-known-each-other"], representationType: "compound-subject-completion", misconceptionTargets: ["agree-with-nearest-singular-name"] }),
  question({ id: "ENG_R4_Q_079_08", skillId: "ENG_R4_S079", difficulty: "advanced", stem: "___ Amy and Lily finished the poster?", options: ["Has", "Are", "Did has", "Have"], answerIndex: 3,
    reasons: ["Has 不配 Amy and Lily。", "Are finished 會改變主動完成海報的意思。", "Did has 疊加且形式錯誤。", "Have 搭配兩人並移到主詞前。"],
    reviews: ["Amy and Lily 是複數，完成式問句使用 Have。", "第四項保留 finished 作過去分詞；其他選項有一致或助動詞問題。"], cognitiveProcess: ["invert-have-with-two-named-subjects", "distinguish-active-finished-from-passive"], representationType: "compound-subject-question", misconceptionTargets: ["use-has-before-first-name"] }),
  question({ id: "ENG_R4_Q_079_09", skillId: "ENG_R4_S079", difficulty: "advanced", stem: "“Has Sam called?” Which short answer says no?", options: ["No, he hasn't.", "No, he doesn't.", "No, he isn't.", "No, he didn't called."], answerIndex: 0,
    reasons: ["hasn't 正確回應 Has 與主詞 he。", "doesn't 對應現在簡單式，不是原問句。", "isn't 沒有沿用 has。", "didn't 後也不應接 called。"],
    reviews: ["簡答要保留原問句的助動詞 has，並依 Sam 改用 he。", "第一項完整；其他答案換成 do、be 或錯誤過去式。"], cognitiveProcess: ["match-negative-short-answer-to-has", "replace-sam-with-he"], representationType: "present-perfect-short-answer", misconceptionTargets: ["answer-has-question-with-do"] }),
  question({ id: "ENG_R4_Q_079_10", skillId: "ENG_R4_S079", difficulty: "advanced", stem: "Which question keeps has as the only helping verb?", options: ["Does Mia has finished?", "Has Mia finished?", "Is Mia has finished?", "Did Mia has finish?"], answerIndex: 1,
    reasons: ["does 與 has 不需並用。", "Has Mia finished 正確倒裝 has。", "is 和 has 疊加兩個助動詞。", "did、has 與 finish 混用多種結構。"],
    reviews: ["現在完成式問句只需把 has 移到 Mia 前。", "第二項沒有新增 do、did 或 is，也保留 finished 分詞。"], cognitiveProcess: ["audit-single-auxiliary-in-has-question", "identify-has-mia-finished-order"], representationType: "auxiliary-count-audit", misconceptionTargets: ["stack-helping-verbs"] }),
  question({ id: "ENG_R4_Q_079_11", skillId: "ENG_R4_S079", difficulty: "transfer", stem: "A class list says, “Ben and Nora ___ returned their books.” Which word completes the report?", options: ["has", "is", "have", "does"], answerIndex: 2,
    reasons: ["has 不配兩位學生。", "is returned 會形成不自然的被動。", "have returned 配合複數並表示已歸還。", "does returned 不是正確時態。"],
    reviews: ["班級名單以 and 連接兩人，助動詞必須使用 have。", "第三項和 returned 組成主動完成式；其餘選項不合人數或結構。"], cognitiveProcess: ["read-class-list-compound-subject", "complete-have-returned-report"], representationType: "class-report-transfer", misconceptionTargets: ["agree-with-nearest-nora-using-has"] }),
  question({ id: "ENG_R4_Q_079_12", skillId: "ENG_R4_S079", difficulty: "transfer", stem: "A message asks, “Have you finished?” Which answer keeps the same time meaning?", options: ["Yes, I did tomorrow.", "Yes, I am finish.", "Yes, I has.", "Yes, I have."], answerIndex: 3,
    reasons: ["did tomorrow 混用過去與未來時間。", "am finish 不是完成式簡答。", "I 不搭配 has。", "Yes, I have 正確沿用問句助動詞。"],
    reviews: ["短答不必重複 finished，但必須保留 Have 的時間結構。", "第四項最精簡且一致；其他選項改變時間或主詞搭配。"], cognitiveProcess: ["retain-present-perfect-in-message-reply", "elliptically-answer-with-have"], representationType: "message-short-answer-transfer", misconceptionTargets: ["switch-auxiliary-in-ellipsis"] }),

  question({ id: "ENG_R4_Q_080_01", skillId: "ENG_R4_S080", difficulty: "foundation", stem: "She has ___ the letter.", options: ["written", "wrote", "write", "writing"], answerIndex: 0,
    reasons: ["written 是 write 的過去分詞。", "wrote 是一般過去式，不能接在 has 後。", "write 是原形。", "writing 是現在分詞。"],
    reviews: ["has 後需要動詞第三態，write–wrote–written 要分清楚。", "第一項形成 has written；其餘三項分別是過去式、原形與 V-ing。"], cognitiveProcess: ["retrieve-written-after-has", "distinguish-write-wrote-written-writing"], misconceptionTargets: ["use-wrote-as-participle"] }),
  question({ id: "ENG_R4_Q_080_02", skillId: "ENG_R4_S080", difficulty: "foundation", stem: "We have ___ that picture before.", options: ["saw", "seen", "see", "seeing"], answerIndex: 1,
    reasons: ["saw 是 see 的一般過去式。", "seen 是 have 後所需的過去分詞。", "see 是動詞原形。", "seeing 不能直接接在 have 後。"],
    reviews: ["before 表示目前以前，have 已要求使用過去分詞。", "第二項完成 have seen；其他選項不是第三態。"], cognitiveProcess: ["restore-seen-in-have-phrase", "separate-saw-from-seen"], misconceptionTargets: ["choose-familiar-past-saw"] }),
  question({ id: "ENG_R4_Q_080_03", skillId: "ENG_R4_S080", difficulty: "foundation", stem: "Ben has ___ his work.", options: ["did", "do", "done", "doing"], answerIndex: 2,
    reasons: ["did 是 do 的一般過去式。", "do 是原形。", "done 是過去分詞，可接在 has 後。", "doing 是現在分詞。"],
    reviews: ["do 的三態是 do–did–done，完成式使用第三個形式。", "第三項形成 has done，並表示工作已完成。"], cognitiveProcess: ["select-done-as-third-form", "complete-ben-has-done"], misconceptionTargets: ["place-did-after-has"] }),
  question({ id: "ENG_R4_Q_080_04", skillId: "ENG_R4_S080", difficulty: "standard", stem: "Mia has ___ the last piece of cake.", options: ["take", "took", "taking", "taken"], answerIndex: 3,
    reasons: ["take 是原形。", "took 是一般過去式。", "taking 不是過去分詞。", "taken 是 take 的過去分詞。"],
    reviews: ["has 決定後面的 take 要使用第三態 taken。", "第四項是唯一可形成現在完成式的選擇；took 不能因表示過去就直接使用。"], cognitiveProcess: ["apply-take-took-taken-sequence", "choose-taken-after-has"], misconceptionTargets: ["treat-took-as-any-past-form"] }),
  question({ id: "ENG_R4_Q_080_05", skillId: "ENG_R4_S080", difficulty: "standard", stem: "What is the past participle of go?", options: ["gone", "went", "going", "goes"], answerIndex: 0,
    reasons: ["gone 是 go 的過去分詞。", "went 是一般過去式。", "going 是現在分詞。", "goes 是第三人稱現在式。"],
    reviews: ["go–went–gone 的後兩種形式不同。", "第一項可用於 has gone 或 have gone；其餘選項各屬其他動詞形式。"], cognitiveProcess: ["recall-go-went-gone-paradigm", "label-gone-as-participle"], representationType: "verb-form-identification", misconceptionTargets: ["confuse-went-with-gone"] }),
  question({ id: "ENG_R4_Q_080_06", skillId: "ENG_R4_S080", difficulty: "standard", stem: "Which line gives the base form, past form, and past participle in that order?", options: ["write / written / wrote", "write / wrote / written", "wrote / write / written", "written / wrote / write"], answerIndex: 1,
    reasons: ["後兩個位置顛倒。", "write、wrote、written 依序是原形、過去式與過去分詞。", "第一與第二個位置互換。", "整組由第三態倒排，不合指定順序。"],
    reviews: ["題目指定三種功能的固定順序，不只問哪三個字。", "第二項把 write 放原形、wrote 放過去式、written 放完成式所需位置。"], cognitiveProcess: ["order-three-forms-of-write", "verify-base-past-participle-columns"], representationType: "three-form-sequence", misconceptionTargets: ["memorize-forms-without-order"] }),
  question({ id: "ENG_R4_Q_080_07", skillId: "ENG_R4_S080", difficulty: "standard", stem: "The children have ___ all the bread.", options: ["ate", "eat", "eaten", "eating"], answerIndex: 2,
    reasons: ["ate 是一般過去式。", "eat 是原形。", "eaten 是 eat 的過去分詞。", "eating 不能接在 have 後形成本句。"],
    reviews: ["複數 children 使用 have，主要動詞要選 eat 的第三態。", "第三項形成 have eaten；ate 雖表示過去，功能仍不同。"], cognitiveProcess: ["map-eat-ate-eaten-after-have", "agree-children-with-completed-eating"], representationType: "irregular-participle-cloze", misconceptionTargets: ["use-ate-after-have"] }),
  question({ id: "ENG_R4_Q_080_08", skillId: "ENG_R4_S080", difficulty: "advanced", stem: "Nora has ___ the window by accident.", options: ["break", "broke", "breaking", "broken"], answerIndex: 3,
    reasons: ["break 是原形。", "broke 是一般過去式。", "breaking 是現在分詞。", "broken 是 break 的過去分詞。"],
    reviews: ["has 後選 break–broke–broken 中的第三態。", "第四項表示窗戶已被 Nora 不小心弄破；其他形式不能接 has。"], cognitiveProcess: ["retrieve-broken-from-break-family", "apply-participle-in-accident-context"], representationType: "result-participle-cloze", misconceptionTargets: ["substitute-broke-for-broken"] }),
  question({ id: "ENG_R4_Q_080_09", skillId: "ENG_R4_S080", difficulty: "advanced", stem: "Which sentence uses wrote as a simple past verb, not a past participle?", options: ["Ben wrote the note yesterday.", "Ben has written the note.", "The note has been written.", "Ben may write the note."], answerIndex: 0,
    reasons: ["wrote 單獨配合 yesterday，是一般過去式。", "has written 使用過去分詞 written。", "has been written 含被動完成結構。", "may write 使用原形。"],
    reviews: ["題目要找 wrote 的一般過去式功能，而非任何與書寫相關的句子。", "第一項有明確過去時間且沒有 have/has；其他句子使用分詞或原形。"], cognitiveProcess: ["locate-simple-past-wrote-by-syntax", "contrast-written-and-base-write"], representationType: "verb-function-classification", misconceptionTargets: ["label-every-past-looking-form-participle"] }),
  question({ id: "ENG_R4_Q_080_10", skillId: "ENG_R4_S080", difficulty: "advanced", stem: "Mia has gone to the store, and she is not home now. What does gone help us understand?", options: ["She visits the store every day.", "She went there and has not returned yet.", "She will go there next year.", "She was never at the store."], answerIndex: 1,
    reasons: ["句中沒有每日習慣。", "has gone 配合不在家，表示已前往且尚未回來。", "句子描述目前結果，不是明年計畫。", "gone 表示已去，與從未去過相反。"],
    reviews: ["過去分詞不只要形式正確，也要和情境意義一致。", "第二項結合 gone 與 not home now；其他選項改成習慣、未來或相反經驗。"], cognitiveProcess: ["infer-not-returned-from-has-gone", "connect-participle-choice-to-current-location"], representationType: "participle-meaning-inference", misconceptionTargets: ["treat-gone-as-future-go"] }),
  question({ id: "ENG_R4_Q_080_11", skillId: "ENG_R4_S080", difficulty: "transfer", stem: "A class report says, “The students have took the books to Room 3.” Which change repairs the verb form?", options: ["took → take", "have → did", "took → taken", "students → student"], answerIndex: 2,
    reasons: ["have take 仍把原形放在 have 後。", "did took 同時使用助動詞 did 與過去式 took，形式仍錯。", "have taken 使用 take 的過去分詞，完整保留學生已搬書的意思。", "把 students 改成單數不會修正 have took。"],
    reviews: ["本句主動者是 students，問題只在 have 後誤用了過去式 took。", "第三項改成 have taken，既修正第三態，也不額外改變原句的主動關係。"], cognitiveProcess: ["diagnose-took-after-have-in-active-report", "replace-past-form-with-taken"], representationType: "active-participle-report-repair", misconceptionTargets: ["add-auxiliary-without-changing-past-form"] }),
  question({ id: "ENG_R4_Q_080_12", skillId: "ENG_R4_S080", difficulty: "transfer", stem: "A study card shows drink / drank / ___. Which word completes the third place?", options: ["drinking", "drink", "drank", "drunk"], answerIndex: 3,
    reasons: ["drinking 是現在分詞。", "drink 已在原形位置。", "drank 是第二格的一般過去式。", "drunk 是 drink 的過去分詞。"],
    reviews: ["卡片依原形、過去式、過去分詞排列。", "第四項完成 drink–drank–drunk；重複 drank 會混淆第二態與第三態。"], cognitiveProcess: ["complete-drink-drank-drunk-card", "assign-drunk-to-third-column"], representationType: "study-card-transfer", misconceptionTargets: ["repeat-past-form-as-participle"] }),

  question({ id: "ENG_R4_Q_081_01", skillId: "ENG_R4_S081", difficulty: "foundation", stem: "Have you ___ seen a whale?", options: ["ever", "never", "yesterday", "ago"], answerIndex: 0,
    reasons: ["ever 詢問到目前為止任何時候是否看過。", "never 帶否定意思，不是一般經驗問句的基本選擇。", "yesterday 是明確過去時間。", "ago 需要搭配一段時間並使用過去式。"],
    reviews: ["問句在確認有沒有看鯨魚的經驗，沒有指定日期。", "第一項位於 Have you 與 seen 之間；其他選項改變否定或時間結構。"], cognitiveProcess: ["place-ever-in-whale-experience-question", "exclude-finished-time-markers"], misconceptionTargets: ["insert-yesterday-into-present-perfect"] }),
  question({ id: "ENG_R4_Q_081_02", skillId: "ENG_R4_S081", difficulty: "foundation", stem: "Mia has ___ flown in a plane.", options: ["ever did", "never", "not never", "last year"], answerIndex: 1,
    reasons: ["ever did 不能放在 has 與 flown 之間。", "never 表示截至現在零次搭機經驗。", "not never 形成不必要的雙重否定。", "last year 是明確過去時間。"],
    reviews: ["never 本身已有一次也沒有的否定意義。", "第二項形成 has never flown；其他選項混用助動詞、雙重否定或過去時間。"], cognitiveProcess: ["express-zero-flight-experience-with-never", "avoid-not-never-double-negative"], misconceptionTargets: ["add-not-before-never"] }),
  question({ id: "ENG_R4_Q_081_03", skillId: "ENG_R4_S081", difficulty: "foundation", stem: "A: Have they ever won a game? B: Yes, they ___.", options: ["did yesterday", "has", "have", "are"], answerIndex: 2,
    reasons: ["did yesterday 不沿用原問句，且加入多餘時間。", "has 不配複數 they。", "have 正確回應 Have they...?。", "are 不對應完成式問句。"],
    reviews: ["問句的助動詞是 Have，簡答不必重複 won。", "第三項形成 Yes, they have；其他選項換了助動詞或主詞搭配。"], cognitiveProcess: ["answer-ever-question-with-have", "preserve-they-in-short-response"], representationType: "experience-short-answer", misconceptionTargets: ["answer-have-question-with-did"] }),
  question({ id: "ENG_R4_Q_081_04", skillId: "ENG_R4_S081", difficulty: "standard", stem: "I ___ this kind of food.", options: ["have not never eaten", "never ate tomorrow", "has never eat", "have never eaten"], answerIndex: 3,
    reasons: ["have not never 含兩個否定。", "never ate tomorrow 同時混用過去與未來。", "I 不搭配 has，eat 也不是分詞。", "have never eaten 正確表示零次經驗。"],
    reviews: ["主詞 I 使用 have，never 放在助動詞與 eaten 之間。", "第四項只有一個否定並使用正確分詞；其餘選項有多重問題。"], cognitiveProcess: ["construct-i-have-never-eaten", "screen-double-negative-and-form-errors"], misconceptionTargets: ["combine-not-and-never"] }),
  question({ id: "ENG_R4_Q_081_05", skillId: "ENG_R4_S081", difficulty: "standard", stem: "“Leo has never ridden a horse.” How many times has Leo ridden one?", options: ["Zero", "One", "Two", "The sentence says nothing about a horse"], answerIndex: 0,
    reasons: ["never 表示一次也沒有。", "若有一次就不能使用 never 表達零次。", "句中沒有兩次的資訊。", "句子明確提到 a horse。"],
    reviews: ["never 在完成式經驗句中把次數限定為零。", "第一項直接對應句意；其餘選項增加不存在的次數或忽略受詞。"], cognitiveProcess: ["translate-never-into-zero-experience", "retain-horse-as-experience-object"], representationType: "never-quantity-interpretation", misconceptionTargets: ["treat-never-as-unknown-frequency"] }),
  question({ id: "ENG_R4_Q_081_06", skillId: "ENG_R4_S081", difficulty: "standard", stem: "Where does ever belong in this question: “Have you seen this play?”", options: ["Ever Have you seen this play?", "Have you ever seen this play?", "Have ever you seen this play?", "Have you seen ever this play?"], answerIndex: 1,
    reasons: ["ever 不放在整個問句最前面。", "ever 位於 you 與 seen 之間，亦即助動詞後、分詞前。", "ever 不能插在 Have 與主詞 you 之間。", "本課基本位置不在 seen 後。"],
    reviews: ["完成式經驗問句的常見順序是 Have + subject + ever + participle。", "第二項保持原句其他字序，只把 ever 放到正確位置。"], cognitiveProcess: ["insert-ever-into-given-question", "preserve-have-subject-participle-order"], representationType: "adverb-placement-task", misconceptionTargets: ["place-ever-at-sentence-edge"] }),
  question({ id: "ENG_R4_Q_081_07", skillId: "ENG_R4_S081", difficulty: "standard", stem: "A: Have you ever been to Penghu? B: No, I ___.", options: ["did never", "hasn't", "haven't", "am not"], answerIndex: 2,
    reasons: ["did never 不回應 Have you。", "hasn't 不配主詞 I。", "haven't 正確形成 No, I haven't。", "am not 對應 be 動詞問句，不是此完成式。"],
    reviews: ["否定簡答沿用 Have，主詞由 you 轉成 I。", "第三項同時符合助動詞與主詞；其餘選項不對應原問句。"], cognitiveProcess: ["shift-you-to-i-in-negative-answer", "contract-have-not-as-havent"], representationType: "experience-dialogue-response", misconceptionTargets: ["use-hasnt-with-i"] }),
  question({ id: "ENG_R4_Q_081_08", skillId: "ENG_R4_S081", difficulty: "advanced", stem: "A: Have you ever seen snow? B: Yes, I have. I saw it in 2024. What does the last sentence add?", options: ["A plan for next year", "A daily snow habit", "A second negative answer", "The finished time of one experience"], answerIndex: 3,
    reasons: ["in 2024 是過去，不是明年計畫。", "看雪不是句中的每日習慣。", "Yes, I have 已是肯定回答。", "in 2024 指出其中一次經驗的確切過去時間。"],
    reviews: ["完成式先回答有無經驗，過去式再補事件發生時間。", "第四項說明時態轉換的功能；其他選項不符合對話。"], cognitiveProcess: ["identify-detail-added-by-simple-past-followup", "link-in-2024-to-one-experience"], representationType: "experience-followup-analysis", misconceptionTargets: ["expect-present-perfect-in-every-turn"] }),
  question({ id: "ENG_R4_Q_081_09", skillId: "ENG_R4_S081", difficulty: "advanced", stem: "Which sentence has two negatives but is meant to give one negative idea?", options: ["I haven't never seen the sea.", "I have never seen the sea.", "I haven't seen the sea yet.", "I saw no boats from the room."], answerIndex: 0,
    reasons: ["haven't 與 never 疊加兩個否定。", "have never 只有 never 一個否定。", "haven't 搭配 yet 仍是一個否定。", "no 修飾 boats，但句中沒有第二個否定詞。"],
    reviews: ["題目要求找出表達一次否定卻用了兩個否定標記的句子。", "第一項同時含 haven't 和 never；第二、三項才是本課可用形式。"], cognitiveProcess: ["detect-double-negative-markers", "distinguish-never-from-not-yet"], representationType: "double-negative-diagnosis", misconceptionTargets: ["treat-never-as-positive-adverb"] }),
  question({ id: "ENG_R4_Q_081_10", skillId: "ENG_R4_S081", difficulty: "advanced", stem: "Which question asks only whether the experience has happened at any time?", options: ["When did you climb the hill?", "Have you ever climbed the hill?", "Why are you climbing now?", "Will you climb it tomorrow?"], answerIndex: 1,
    reasons: ["When 要求確切發生時間。", "Have you ever 詢問到現在任何時候是否有此經驗。", "now 詢問目前動作。", "tomorrow 詢問未來計畫。"],
    reviews: ["only whether 表示只需回答有或沒有，不需日期或原因。", "第二項用 ever 建立經驗問句；其他句子詢問時間、現在或未來。"], cognitiveProcess: ["match-any-time-experience-to-ever-question", "exclude-when-now-tomorrow-questions"], representationType: "question-intent-selection", misconceptionTargets: ["choose-when-question-for-experience"] }),
  question({ id: "ENG_R4_Q_081_11", skillId: "ENG_R4_S081", difficulty: "transfer", stem: "A travel form asks, “Have you ever stayed on a small island?” Which answer reports no such experience?", options: ["Yes, I stayed last month.", "I will stay there next week.", "No, I have never stayed on one.", "I stay there every summer."], answerIndex: 2,
    reasons: ["這一項報告有過一次經驗。", "這一項是未來計畫，沒有回答過去經驗。", "have never stayed 清楚表示截至目前零次。", "每年夏天去表示有多次經驗。"],
    reviews: ["表單問目前以前是否曾住過小島，回答必須直接處理經驗。", "第三項以 No 和 never 一致表達零次；其他選項表示有過或尚未發生。"], cognitiveProcess: ["answer-travel-form-with-zero-experience", "reject-habit-plan-and-positive-event"], representationType: "form-response-transfer", misconceptionTargets: ["answer-experience-form-with-future-plan"] }),
  question({ id: "ENG_R4_Q_081_12", skillId: "ENG_R4_S081", difficulty: "transfer", stem: "“Mia has never missed the school bus.” What does this sentence allow us to say?", options: ["She missed it yesterday.", "She will miss it tomorrow.", "She has taken no buses in her life.", "Up to now, she has always caught the school bus."], answerIndex: 3,
    reasons: ["never missed 與昨天錯過相反。", "句子不能保證明天的結果。", "school bus 的特定經驗不等於從未搭過任何公車。", "截至現在零次錯過，表示每次都趕上校車。"],
    reviews: ["never 的範圍只到說話當下，也只針對 school bus。", "第四項保留這兩個界線；其他選項改成過去反例、未來保證或過度推論。"], cognitiveProcess: ["infer-caught-every-time-from-never-missed", "limit-never-claim-to-now-and-school-bus"], representationType: "bounded-never-inference", misconceptionTargets: ["extend-never-claim-into-future"] }),

  question({ id: "ENG_R4_Q_082_01", skillId: "ENG_R4_S082", difficulty: "foundation", stem: "The bus has ___ left.", options: ["already", "yet", "last night", "tomorrow"], answerIndex: 0,
    reasons: ["already 位於 has 與 left 之間，表示公車已離開。", "yet 在本課基本用法多放在問句或否定句尾。", "last night 是已結束的明確過去時間。", "tomorrow 與已完成的 has left 衝突。"],
    reviews: ["句子是肯定完成式，空格也位在助動詞與分詞之間。", "第一項同時符合 already 的語意和位置；其餘選項不合句型或時間。"], cognitiveProcess: ["place-already-between-has-and-left", "reject-yet-and-time-conflicts"], misconceptionTargets: ["put-yet-in-affirmative-mid-position"] }),
  question({ id: "ENG_R4_Q_082_02", skillId: "ENG_R4_S082", difficulty: "foundation", stem: "Have you read the note ___?", options: ["already did", "yet", "last Sunday", "ago"], answerIndex: 1,
    reasons: ["already did 破壞 Have you read 的結構。", "yet 放在問句尾，詢問到現在是否已讀。", "last Sunday 是明確過去時間。", "ago 不能單獨使用，也不配此完成式。"],
    reviews: ["問句關心截至目前的完成狀態，空格位於句尾。", "第二項形成 Have you read the note yet?；其他選項混入助動詞或過去時間。"], cognitiveProcess: ["complete-read-status-question-with-yet", "use-question-final-yet-position"], misconceptionTargets: ["answer-status-question-with-finished-time"] }),
  question({ id: "ENG_R4_Q_082_03", skillId: "ENG_R4_S082", difficulty: "foundation", stem: "We haven't eaten dinner ___.", options: ["already", "last year", "yet", "tomorrow"], answerIndex: 2,
    reasons: ["already 不符合此句要表達的尚未完成狀態。", "last year 與 haven't eaten 的目前狀態不合。", "yet 位於否定句尾，表示到現在仍未吃晚餐。", "tomorrow 把事件放在未來，不能說明目前尚未完成。"],
    reviews: ["haven't 已建立否定，句尾需要表達截至現在的 yet。", "第三項保留晚餐尚未吃的現況；其他選項改成已完成、過去或未來。"], cognitiveProcess: ["pair-havent-eaten-with-yet", "interpret-currently-unfinished-dinner"], misconceptionTargets: ["use-already-after-negative"] }),
  question({ id: "ENG_R4_Q_082_04", skillId: "ENG_R4_S082", difficulty: "standard", stem: "Mia has ___ done her homework, so she can go out now.", options: ["yet", "tomorrow", "last night", "already"], answerIndex: 3,
    reasons: ["yet 不放在此肯定句的中間位置作基本用法。", "tomorrow 與 can go out now 的已完成原因不合。", "last night 會把完成時間鎖在已結束的昨晚，不適合直接放入此完成式。", "already 表示作業已完成，能解釋現在可以外出。"],
    reviews: ["so she can go out now 說明完成作業產生目前結果。", "第四項形成 has already done，其他選項不合肯定完成式的語意或位置。"], cognitiveProcess: ["infer-completed-homework-from-current-permission", "insert-already-before-done"], representationType: "result-linked-adverb-cloze", misconceptionTargets: ["ignore-now-result-when-selecting-time-word"] }),
  question({ id: "ENG_R4_Q_082_05", skillId: "ENG_R4_S082", difficulty: "standard", stem: "“The show has already started.” What does already tell us here?", options: ["The show started before now.", "The show starts every day.", "The show will start next month.", "Nothing has happened yet."], answerIndex: 0,
    reasons: ["already 表示開始這件事在目前以前已發生。", "句中沒有每日頻率。", "has started 不是未來式。", "already started 正表示事情已發生。"],
    reviews: ["already 的核心是截至現在已完成或已發生。", "第一項保留時間關係；其他項目改成習慣、未來或否認開始。"], cognitiveProcess: ["interpret-already-started-relative-to-now", "exclude-habit-future-and-nonoccurrence"], representationType: "already-meaning-comprehension", misconceptionTargets: ["read-already-as-future-soon"] }),
  question({ id: "ENG_R4_Q_082_06", skillId: "ENG_R4_S082", difficulty: "standard", stem: "Where does yet belong in “Has Ben finished the work?”", options: ["Yet Has Ben finished the work?", "Has Ben finished the work yet?", "Has yet Ben finished the work?", "Has Ben yet finished the work yet?"], answerIndex: 1,
    reasons: ["yet 不放在整個問句最前面。", "本課基本問句把 yet 放在句尾。", "yet 不插在 Has 與主詞 Ben 之間。", "同一句重複 yet 兩次。"],
    reviews: ["完成狀態問句保留 Has + subject + participle，再把 yet 放到末尾。", "第二項只加入一個 yet 且字序自然；其他選項位置或數量錯誤。"], cognitiveProcess: ["append-yet-to-has-question", "avoid-duplicate-or-pre-subject-yet"], representationType: "yet-placement-task", misconceptionTargets: ["place-yet-before-subject"] }),
  question({ id: "ENG_R4_Q_082_07", skillId: "ENG_R4_S082", difficulty: "standard", stem: "The light is still on. Sam hasn't gone to bed ___.", options: ["already", "last night", "yet", "every day"], answerIndex: 2,
    reasons: ["already 會和 hasn't 的尚未語意衝突。", "last night 不能直接搭配此現在完成式。", "yet 表示 Sam 到現在仍未就寢。", "every day 會改成習慣，但句型仍不完整。"],
    reviews: ["still on 是目前可見結果，支持到現在尚未上床睡覺。", "第三項把 hasn't gone 與 yet 連起來；其他選項改變完成狀態或時間。"], cognitiveProcess: ["use-lit-light-as-unfinished-bedtime-evidence", "complete-hasnt-gone-yet"], representationType: "present-evidence-status-cloze", misconceptionTargets: ["select-already-despite-negative"] }),
  question({ id: "ENG_R4_Q_082_08", skillId: "ENG_R4_S082", difficulty: "advanced", stem: "School starts at eight. It is only seven, but Ben ___ at school.", options: ["hasn't arrived yet", "arrived tomorrow", "is arrive every day", "has already arrived"], answerIndex: 3,
    reasons: ["hasn't arrived yet 與 but 所呈現的提早到達不合。", "arrived 不能和 tomorrow 搭配。", "is arrive 不是正確結構。", "has already arrived 表示比預期早就到了。"],
    reviews: ["八點才上課而七點已到，明確構成早於預期的到達。", "第四項利用 already 表達已發生；第一項會說人仍未到校。"], cognitiveProcess: ["compare-seven-arrival-with-eight-start", "select-already-arrived"], representationType: "schedule-expectation-cloze", misconceptionTargets: ["choose-yet-despite-stated-early-arrival"] }),
  question({ id: "ENG_R4_Q_082_09", skillId: "ENG_R4_S082", difficulty: "advanced", stem: "Which sentence asks whether the work is complete up to now?", options: ["Have you washed the cups yet?", "Did you wash them last night?", "Will you wash them tomorrow?", "Do you wash them every Friday?"], answerIndex: 0,
    reasons: ["Have...yet 詢問截至目前的完成狀態。", "last night 問明確過去事件。", "tomorrow 問未來行動。", "every Friday 問固定習慣。"],
    reviews: ["up to now 要找現在完成式與句尾 yet 的組合。", "第一項符合；其他三項分別把洗杯子放在過去、未來或反覆習慣。"], cognitiveProcess: ["identify-up-to-now-task-question", "separate-status-from-event-plan-habit"], representationType: "completion-status-classification", misconceptionTargets: ["equate-did-question-with-current-status"] }),
  question({ id: "ENG_R4_Q_082_10", skillId: "ENG_R4_S082", difficulty: "advanced", stem: "A: Have you packed yet? B: Yes. I have already packed. How are yet and already used in this talk?", options: ["Both give a finished date.", "Yet asks if packing is finished; already says it is finished.", "Yet means tomorrow; already means yesterday.", "Both describe a daily habit."], answerIndex: 1,
    reasons: ["兩字都沒有提供日期。", "A 用 yet 詢問，B 用 already 陳述已完成。", "它們不等同明天與昨天。", "對話談單次打包狀態，不是習慣。"],
    reviews: ["同一情境可用 yet 提問，再用 already 回答已完成。", "第二項說明溝通功能差異，而不是把兩字硬配成日期翻譯。"], cognitiveProcess: ["contrast-yet-question-with-already-answer", "identify-ask-versus-state-functions"], representationType: "dialogue-adverb-contrast", misconceptionTargets: ["translate-adverbs-as-fixed-dates"] }),
  question({ id: "ENG_R4_Q_082_11", skillId: "ENG_R4_S082", difficulty: "transfer", stem: "A work note says, “Room A has already been cleaned. Room B hasn't been cleaned yet.” Which room still needs work?", options: ["Both rooms", "Room A", "Room B", "Neither room"], answerIndex: 2,
    reasons: ["Room A 已完成，不是兩間都需要。", "already been cleaned 表示 A 已清理。", "hasn't...yet 表示 B 到現在仍未清理。", "B 尚未完成，所以不能說都不需要。"],
    reviews: ["already 與 hasn't...yet 在同一張工作單上標出相反狀態。", "第三項由 Room B 的否定完成式直接得出；其他答案忽略其中一間狀態。"], cognitiveProcess: ["compare-two-room-completion-statuses", "map-hasnt-yet-to-pending-work"], representationType: "work-note-transfer", misconceptionTargets: ["treat-already-and-yet-as-same-status"] }),
  question({ id: "ENG_R4_Q_082_12", skillId: "ENG_R4_S082", difficulty: "transfer", stem: "A station message should say that the bus left sooner than expected. Which line does that?", options: ["The bus hasn't left yet.", "The bus left tomorrow.", "The bus has left every day.", "The bus has already left."], answerIndex: 3,
    reasons: ["hasn't left yet 表示仍未離開。", "left tomorrow 混用過去式與未來時間。", "has left every day 不是自然的頻率表達。", "has already left 表示公車已比預期早離開。"],
    reviews: ["訊息要求同時表達已離開與早於預期。", "第四項由 has left 表完成、already 表已經；其餘選項否定或扭曲時間。"], cognitiveProcess: ["compose-early-departure-station-message", "select-already-over-not-yet"], representationType: "station-message-transfer", misconceptionTargets: ["reverse-completed-and-pending-status"] }),

  question({ id: "ENG_R4_Q_083_01", skillId: "ENG_R4_S083", difficulty: "foundation", stem: "We have lived here ___ 2021.", options: ["since", "for", "ago", "during"], answerIndex: 0,
    reasons: ["since 接居住開始的時間點 2021。", "for 應接一段時間長度。", "ago 從現在往前定位，不能放在此處。", "during 不形成本題從起點延續的結構。"],
    reviews: ["2021 是何時開始，而不是住了多久。", "第一項形成 have lived here since 2021；其他介系詞不配起點與完成式。"], cognitiveProcess: ["classify-2021-as-starting-point", "choose-since-for-residence-start"], misconceptionTargets: ["use-for-before-calendar-year"] }),
  question({ id: "ENG_R4_Q_083_02", skillId: "ENG_R4_S083", difficulty: "foundation", stem: "Ben has studied English ___ two hours.", options: ["since", "for", "ago", "from"], answerIndex: 1,
    reasons: ["since 不能接 two hours 這段長度。", "for 表示讀書持續兩小時。", "ago 不接在此完成式末尾。", "from 若表範圍還需要起訖資訊。"],
    reviews: ["two hours 回答持續多久，因此使用 for。", "第二項讓 has studied 延續到現在；其餘選項把長度誤當起點或缺少結構。"], cognitiveProcess: ["recognize-two-hours-as-duration", "complete-for-two-hours-study"], misconceptionTargets: ["write-since-two-hours"] }),
  question({ id: "ENG_R4_Q_083_03", skillId: "ENG_R4_S083", difficulty: "foundation", stem: "I have known Grace ___ we were children.", options: ["for", "during", "since", "ago"], answerIndex: 2,
    reasons: ["for 不能直接接這個起點子句。", "during 不表示從兒時延續到現在。", "since 可接 we were children 說明開始時刻。", "ago 不能引導此子句。"],
    reviews: ["we were children 是關係開始的背景起點。", "第三項形成 have known...since...，表示認識狀態延續至今。"], cognitiveProcess: ["treat-childhood-clause-as-start-point", "link-known-state-with-since-clause"], representationType: "since-clause-cloze", misconceptionTargets: ["assume-since-only-precedes-dates"] }),
  question({ id: "ENG_R4_Q_083_04", skillId: "ENG_R4_S083", difficulty: "standard", stem: "Nora has played the piano ___ five years.", options: ["since", "ago", "from", "for"], answerIndex: 3,
    reasons: ["since 需要起點，不接 five years 長度。", "ago 與現在完成式不這樣搭配。", "from 單獨缺少另一端。", "for five years 表示持續長度。"],
    reviews: ["five years 是一段時間，回答彈琴持續多久。", "第四項與 has played 共同表達從過去延續到現在。"], cognitiveProcess: ["measure-piano-duration-as-five-years", "select-for-before-duration"], misconceptionTargets: ["treat-number-of-years-as-start-date"] }),
  question({ id: "ENG_R4_Q_083_05", skillId: "ENG_R4_S083", difficulty: "standard", stem: "Which item gives a starting point, not an amount of time?", options: ["Monday", "three weeks", "two hours", "many years"], answerIndex: 0,
    reasons: ["Monday 指出開始的日子。", "three weeks 是持續長度。", "two hours 是時間段。", "many years 仍表示長度。"],
    reviews: ["since/for 的第一步是分辨點與段。", "第一項可接 since；其他三項都回答多久，通常接 for。"], cognitiveProcess: ["classify-point-versus-duration-items", "identify-monday-as-only-point"], representationType: "time-type-classification", misconceptionTargets: ["classify-all-time-words-the-same"] }),
  question({ id: "ENG_R4_Q_083_06", skillId: "ENG_R4_S083", difficulty: "standard", stem: "Which sentence uses since with a clear starting point?", options: ["We have waited since two hours.", "We have waited since noon.", "We waited since for noon.", "We have since waited for at noon."], answerIndex: 1,
    reasons: ["two hours 是長度，應使用 for。", "noon 是開始時間點，可接 since。", "since 與 for 不需並列。", "字序與介系詞都不形成自然句子。"],
    reviews: ["題目指定 since 後要有明確起點，noon 符合。", "第二項結構完整；其他選項混淆長度、重複介系詞或字序錯誤。"], cognitiveProcess: ["validate-since-noon-start-point", "reject-duration-and-preposition-stacking"], representationType: "since-sentence-selection", misconceptionTargets: ["use-since-before-duration"] }),
  question({ id: "ENG_R4_Q_083_07", skillId: "ENG_R4_S083", difficulty: "standard", stem: "The rain has continued ___ noon.", options: ["for", "ago", "since", "during"], answerIndex: 2,
    reasons: ["for 不接 noon 這個時間點。", "ago 不能接在 has continued 後。", "since noon 表示從中午持續到現在。", "during noon 不是此延續起點的基本表達。"],
    reviews: ["noon 指雨開始或計算持續的基準時刻。", "第三項連結過去起點與現在仍持續的下雨狀態。"], cognitiveProcess: ["anchor-continuing-rain-at-noon", "complete-has-continued-since"], representationType: "ongoing-weather-cloze", misconceptionTargets: ["select-for-before-noon"] }),
  question({ id: "ENG_R4_Q_083_08", skillId: "ENG_R4_S083", difficulty: "advanced", stem: "The shop opened at two. It is now five. The shop has been open ___ three hours.", options: ["since", "ago", "from", "for"], answerIndex: 3,
    reasons: ["since 應接 two 或另一個起點。", "ago 會往過去定位，不能表示持續到現在。", "from 單獨不能填出持續長度。", "for three hours 符合五點減二點的三小時。"],
    reviews: ["先由 5 − 2 得到持續長度三小時，再選 for。", "第四項同時符合計算與完成式狀態；若題目留空接 two 才會用 since。"], cognitiveProcess: ["calculate-shop-open-duration", "map-three-hour-length-to-for"], representationType: "duration-calculation-cloze", misconceptionTargets: ["use-since-before-computed-duration"] }),
  question({ id: "ENG_R4_Q_083_09", skillId: "ENG_R4_S083", difficulty: "advanced", stem: "“Amy has lived here since two years” uses the wrong time phrase. Which phrase keeps the meaning?", options: ["for two years", "two years ago", "during two years", "from two years"], answerIndex: 0,
    reasons: ["for two years 正確表示居住持續長度。", "two years ago 只給過去時點，不能直接替換空間。", "during two years 不表延續至今的基本結構。", "from 需要明確起點與可能的終點。"],
    reviews: ["two years 是一段長度，因此錯的是 since 與後面資訊類型不合。", "第一項只改介系詞就保留原本持續兩年的意思。"], cognitiveProcess: ["repair-since-duration-mismatch", "preserve-two-year-continuation-meaning"], representationType: "time-phrase-repair", misconceptionTargets: ["replace-with-ago-without-changing-structure"] }),
  question({ id: "ENG_R4_Q_083_10", skillId: "ENG_R4_S083", difficulty: "advanced", stem: "“Amy has known Ben since Monday.” What does since Monday tell us?", options: ["They meet only on Mondays.", "They first met on Monday and still know each other now.", "They will meet next Monday.", "They knew each other for only one hour."], answerIndex: 1,
    reasons: ["句子不是每週一的習慣。", "since Monday 指認識關係從週一開始並延續到現在。", "沒有 next Monday 的未來資訊。", "句中沒有一小時的長度。"],
    reviews: ["know 是可延續狀態，since 標出它的開始點。", "第二項保留起點與目前連結；其他選項加入頻率、未來或不存在的長度。"], cognitiveProcess: ["interpret-since-monday-with-stative-know", "infer-continuation-to-present"], representationType: "since-state-inference", misconceptionTargets: ["read-monday-as-weekly-frequency"] }),
  question({ id: "ENG_R4_Q_083_11", skillId: "ENG_R4_S083", difficulty: "transfer", stem: "A club card says, “Member from September 1.” Today is December 1. Which sentence says she is still a member?", options: ["She was a member tomorrow.", "She is a member for September 1.", "She has been a member since September 1.", "She has been a member ago September 1."], answerIndex: 2,
    reasons: ["was tomorrow 混用過去與未來。", "for 不能接 September 1 這個起點。", "has been...since 表示會員身分從該日起持續。", "ago 不能放在日期前形成此完成式。"],
    reviews: ["卡片提供加入起點，而 today 顯示身分仍需連到現在。", "第三項使用 since September 1；其他選項錯置時間或介系詞。"], cognitiveProcess: ["translate-membership-card-into-present-perfect", "select-since-before-specific-date"], representationType: "membership-card-transfer", misconceptionTargets: ["use-for-before-start-date"] }),
  question({ id: "ENG_R4_Q_083_12", skillId: "ENG_R4_S083", difficulty: "transfer", stem: "“We have lived here for six years.” What can we know without knowing today's date?", options: ["The year they moved in", "Where they live", "The day they will leave", "How long they have lived here"], answerIndex: 3,
    reasons: ["沒有今天的年份就不能算出確切搬入年。", "句中沒有地址。", "完成式沒有提供離開日期。", "for six years 直接給出居住長度。"],
    reviews: ["for 回答多久，但不自動提供日曆上的開始日期。", "第四項是唯一能由原句直接確定的資訊；其他項目需要額外資料。"], cognitiveProcess: ["limit-inference-from-for-six-years", "distinguish-duration-from-start-date"], representationType: "duration-information-boundary", misconceptionTargets: ["infer-exact-start-year-without-current-year"] }),

  question({ id: "ENG_R4_Q_084_01", skillId: "ENG_R4_S084", difficulty: "foundation", stem: "I ___ the book last night.", options: ["finished", "have finished", "has finished", "finish tomorrow"], answerIndex: 0,
    reasons: ["finished 配合已結束的 last night。", "have finished 不直接搭配此明確過去時點。", "I 不搭配 has，時間也不合。", "finish tomorrow 與 last night 衝突。"],
    reviews: ["last night 把完成閱讀鎖定在已結束的過去。", "第一項使用過去簡單式；其他選項保留現在連結或加入未來。"], cognitiveProcess: ["map-last-night-to-simple-past-finished", "exclude-present-perfect-with-finished-time"], misconceptionTargets: ["use-have-finished-with-last-night"] }),
  question({ id: "ENG_R4_Q_084_02", skillId: "ENG_R4_S084", difficulty: "foundation", stem: "Which phrase names a past year?", options: ["before", "many times", "in 2023", "twice"], answerIndex: 2,
    reasons: ["before 保留未指明日期的經驗。", "many times 可累計到目前的閱讀次數。", "in 2023 指出已結束的明確過去年份，因此應改用 I read。", "twice 只給次數，仍可搭配現在完成式。"],
    reviews: ["本題比較非特定經驗線索與明確過去時間。", "第三項會形成 I read this book in 2023；其他三項都不必把經驗句改成一般過去式。"], cognitiveProcess: ["identify-added-finished-time-trigger", "change-have-read-to-read-for-2023"], representationType: "time-phrase-tense-shift", misconceptionTargets: ["treat-count-as-finished-date"] }),
  question({ id: "ENG_R4_Q_084_03", skillId: "ENG_R4_S084", difficulty: "foundation", stem: "Mia's key is still missing. She ___ it.", options: ["found yesterday", "has lose", "has lost", "will lose tomorrow"], answerIndex: 2,
    reasons: ["若昨天已找到鑰匙，就不符合 still missing。", "has 後不能使用原形 lose。", "has lost 表示遺失的結果持續到現在。", "未來才遺失與目前仍找不到相衝突。"],
    reviews: ["still missing 把過去的遺失事件連到現在，適合使用現在完成式。", "第三項形成 She has lost it；其他選項不是形式錯誤，就是和現況矛盾。"], cognitiveProcess: ["connect-still-missing-key-to-present-perfect", "exclude-found-and-future-contradictions"], misconceptionTargets: ["ignore-stated-current-result"] }),
  question({ id: "ENG_R4_Q_084_04", skillId: "ENG_R4_S084", difficulty: "standard", stem: "Sam ___ the zoo yesterday afternoon.", options: ["has visited", "have visited", "visits", "visited"], answerIndex: 3,
    reasons: ["has visited 不直接和 yesterday afternoon 搭配。", "Sam 不搭配 have，時間也已結束。", "visits 是現在簡單式，不能敘述昨天午後的一次參觀。", "visited 正確放在明確過去時間。"],
    reviews: ["yesterday afternoon 是已結束且具體的時間區段。", "第四項使用過去式 visited；其餘選項誤用完成式或現在式。"], cognitiveProcess: ["identify-yesterday-afternoon-as-finished-period", "apply-simple-past-visited"], misconceptionTargets: ["choose-has-visited-for-any-past-event"] }),
  question({ id: "ENG_R4_Q_084_05", skillId: "ENG_R4_S084", difficulty: "standard", stem: "Which fact most strongly supports “Ben has broken his glasses”?", options: ["He cannot use them now.", "He bought them in 2022.", "He cleans them every day.", "He will wear them tomorrow."], answerIndex: 0,
    reasons: ["現在不能使用眼鏡，是破損留下的目前結果。", "購買年份不表示現在已破。", "每日清潔是習慣，不能證明破損。", "明天的配戴計畫也不能證明眼鏡目前已破。"],
    reviews: ["現在完成式可由目前仍存在的結果得到支持。", "第一項直接連結 broken 與 now；其他線索只談過去購買、習慣或未來。"], cognitiveProcess: ["select-current-consequence-of-broken-glasses", "reject-unrelated-time-clues"], representationType: "present-result-evidence-selection", misconceptionTargets: ["choose-any-glasses-detail"] }),
  question({ id: "ENG_R4_Q_084_06", skillId: "ENG_R4_S084", difficulty: "standard", stem: "Which sentence places the event at a finished past time?", options: ["I have met her before.", "I met her on Monday.", "I have known her for years.", "I have just met her."], answerIndex: 1,
    reasons: ["before 未給確切日期，句子談經驗。", "on Monday 將見面放在明確且已結束的過去日。", "for years 表持續到現在。", "have just met 強調和現在很接近的結果。"],
    reviews: ["題目要求 finished past time，必須找出具體時間點。", "第二項同時有過去式 met 與 on Monday；其他句子保留現在連結。"], cognitiveProcess: ["locate-explicit-finished-time-among-perfect-uses", "pair-met-with-on-monday"], representationType: "tense-time-classification", misconceptionTargets: ["treat-before-as-exact-date"] }),
  question({ id: "ENG_R4_Q_084_07", skillId: "ENG_R4_S084", difficulty: "standard", stem: "It is ten in the morning, and the school day continues. “I have had two classes today.” What does the sentence count?", options: ["Classes from yesterday", "Classes completed so far today", "A plan for tomorrow", "Every class in the full school day"], answerIndex: 1,
    reasons: ["today 不表示昨天。", "two classes 是截至上午十點已完成的累計。", "have had 回顧已發生內容，不是明天計畫。", "school day continues 表示全天課程尚未全部結束。"],
    reviews: ["today 尚未結束，現在完成式在此統計目前為止的成果。", "第二項只涵蓋已完成的兩堂課，不把它誤讀為全天總數或未來安排。"], cognitiveProcess: ["interpret-have-had-with-unfinished-today", "limit-count-to-classes-completed-so-far"], representationType: "unfinished-period-meaning", misconceptionTargets: ["treat-so-far-count-as-full-day-total"] }),
  question({ id: "ENG_R4_Q_084_08", skillId: "ENG_R4_S084", difficulty: "advanced", stem: "A: Have you seen the new movie? B: Yes. I saw it on Saturday. Why is saw used in the second answer?", options: ["Saturday is a daily habit.", "The movie is playing now.", "Saw is a future form.", "On Saturday gives the finished time of the event."], answerIndex: 3,
    reasons: ["Saturday 在此是一次日期，不是每日習慣。", "對話沒有說電影正在播放。", "saw 是 see 的過去式，不是未來形式。", "on Saturday 把其中一次觀影放在明確過去時間。"],
    reviews: ["第一句問經驗，第二句補充該經驗發生的日期。", "第四項解釋為何由 have seen 轉成 saw；時態改變並不矛盾。"], cognitiveProcess: ["explain-saw-after-have-you-seen", "connect-on-saturday-to-event-time"], representationType: "followup-tense-rationale", misconceptionTargets: ["keep-perfect-despite-explicit-date"] }),
  question({ id: "ENG_R4_Q_084_09", skillId: "ENG_R4_S084", difficulty: "advanced", stem: "Which sentence mixes present perfect with a finished past time in the wrong way?", options: ["I have called her yesterday.", "I called her yesterday.", "I have called her before.", "I have called her twice."], answerIndex: 0,
    reasons: ["have called 不應直接搭配已結束的 yesterday。", "called yesterday 是正確過去事件。", "have called before 可談非特定經驗。", "have called twice 可累計到目前的次數。"],
    reviews: ["題目要找完成式和明確過去時間衝突的句子。", "第一項具有兩個不相容線索；其餘三句各自有合理的時間框架。"], cognitiveProcess: ["detect-present-perfect-yesterday-conflict", "contrast-date-with-before-and-count"], representationType: "tense-conflict-diagnosis", misconceptionTargets: ["accept-have-plus-yesterday"] }),
  question({ id: "ENG_R4_Q_084_10", skillId: "ENG_R4_S084", difficulty: "advanced", stem: "This week is not over. Which sentence counts work completed so far?", options: ["I will finish three jobs next week.", "I have finished three jobs this week.", "I finish three jobs every week.", "I finished three jobs last week."], answerIndex: 1,
    reasons: ["will finish next week 是未來計畫。", "have finished 累計尚未結束的本週成果。", "finish every week 表示固定習慣。", "finished last week 只報告已結束的上週。"],
    reviews: ["not over 與 so far 都要求把本週視為仍進行的區段。", "第二項是唯一統計本週目前成果的句子；其他句子各自談未來、習慣或已結束的過去。"], cognitiveProcess: ["separate-current-week-progress-from-other-time-frames", "choose-have-finished-this-week"], representationType: "unfinished-week-progress", misconceptionTargets: ["choose-grammatical-sentence-with-wrong-time-frame"] }),
  question({ id: "ENG_R4_Q_084_11", skillId: "ENG_R4_S084", difficulty: "transfer", stem: "The library worker asks, “Why can't you enter now?” The student answers, “I ___ my school card.”", options: ["found yesterday", "will lose", "have lost", "lose every day"], answerIndex: 2,
    reasons: ["若昨天已找到卡片，就不能說明現在無法入館。", "未來才遺失不會造成眼前的問題。", "have lost 表示卡片遺失且目前仍未找到。", "lose every day 把單次問題說成不合理的日常習慣。"],
    reviews: ["問句要求說明現在無法進入的原因，回答要呈現仍存在的遺失結果。", "第三項以 I have lost my school card 連結先前事件與目前狀態。"], cognitiveProcess: ["answer-current-access-question-with-present-result", "select-have-lost-over-contradictory-events"], representationType: "access-dialogue-transfer", misconceptionTargets: ["choose-any-grammatical-time-without-checking-context"] }),
  question({ id: "ENG_R4_Q_084_12", skillId: "ENG_R4_S084", difficulty: "transfer", stem: "A report needs one life experience and one dated event. Which pair gives them in that order?", options: ["I went there in 2023. / I have been there before.", "I go there every year. / I am going tomorrow.", "I have been there in 2023. / I went there before.", "I have been there before. / I went there in 2023."], answerIndex: 3,
    reasons: ["順序先是日期事件，再是經驗，與要求相反。", "兩句是習慣與未來計畫。", "第一句錯把完成式和 2023 直接並用，第二句也未給日期。", "have been...before 是經驗，went...in 2023 是明確事件。"],
    reviews: ["題目同時限定內容類型與排列順序。", "第四項先用現在完成式呈現經驗，再用過去式加 2023；其他組不是順序錯就是時態不合。"], cognitiveProcess: ["order-experience-before-dated-event", "validate-have-been-before-and-went-in-2023"], representationType: "dual-tense-report-transfer", misconceptionTargets: ["ignore-required-information-order"] }),
];

export const ENGLISH_U12_VOCABULARY_POLICY = Object.freeze({
  capQuestionBasis: "appendix-5-table-1",
  additionalLearningTerms: ["accident", "add", "amount", "complete", "continue", "daily", "describe", "event", "message", "mix", "negative", "neither", "repair", "return", "such", "suggest", "support", "travel", "whale"],
  properNames: ["Amy", "Ben", "Grace", "Hualien", "Japan", "Leo", "Lily", "Mia", "Nora", "Penghu", "Sam", "Tainan"],
  grammarNotation: ["-ed", "A", "B", "base form", "clause", "double negative", "past form", "past participle", "phrase", "present perfect", "verb"],
  malformedDistractors: [],
});

export const ENGLISH_U12_SOURCE = Object.freeze({ unitId: UNIT_ID, lectures: ENGLISH_U12_LECTURES, questions: ENGLISH_U12_QUESTIONS, vocabularyPolicy: ENGLISH_U12_VOCABULARY_POLICY });
export const ENGLISH_UNIT_SOURCE = ENGLISH_U12_SOURCE;
