const UNIT_ID = "ENG_R4_U24";

function lecture(id, skillId, content) {
  return { id, skillId, ...content, sections: content.sections.map((section, index) => ({ id: `${id}_SEC_${String(index + 1).padStart(2, "0")}`, ...section })) };
}

const DIFFICULTIES = ["foundation", "foundation", "foundation", "standard", "standard", "standard", "standard", "advanced", "advanced", "advanced", "transfer", "transfer"];

function skillQuestions(skillNumber, values) {
  if (values.length !== 12) throw new Error(`ENG_R4_S${skillNumber}: expected 12 authored questions`);
  return values.map((value, index) => ({ id: `ENG_R4_Q_${skillNumber}_${String(index + 1).padStart(2, "0")}`, skillId: `ENG_R4_S${skillNumber}`, difficulty: DIFFICULTIES[index], ...value }));
}

export const ENGLISH_U24_LECTURES = [
  lecture("ENG_R4_L_S162", "ENG_R4_S162", {
    objectives: ["找出關係子句真正修飾的先行詞。", "排除地點、時間與所有格等背景資訊造成的錯誤連結。"],
    sections: [
      { title: "關係子句緊接在要補充的名詞後", content: "The boy who is waving is Ben 中，who is waving 補充 the boy，告訴讀者是哪一位男孩。the boy 稱為先行詞；關係子句不是另一個無關句子，而是名詞的一部分。" },
      { title: "從子句語意確認先行詞", content: "I found the key that opens this door 裡，key 能開門，所以 that opens this door 修飾 key。不能只找前面任何名詞；要檢查該名詞能否合理放回子句缺少的位置。" },
      { title: "地點與所有格不會自動成為先行詞", content: "Nora thanked the nurse who helped her 的 who 指 nurse，不指 Nora；The bag that has a red star is under the chair 的 that 指 bag，不指 chair。句子位置與事件角色要一起判斷。" },
      { title: "先行詞的單複數會影響子句動詞", content: "The student who works here 與 The students who work here 的關係子句都修飾 student 或 students。當 who 是子句主詞時，後面的動詞要依先行詞單複數變化。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S162_EX_01", prompt: "The woman who teaches music is my aunt. Who teaches music?", steps: ["找出 who 前的名詞。", "把 woman 放回 teaches 的主詞位置。", "確認 aunt 是整句補充身分。"], answer: "The woman.", why: "who teaches music 緊接 the woman，並以 who 代替她作 teaches 的主詞。my aunt 是整句對這位女士的身分說明，不是另一位教音樂的人。" },
      { id: "ENG_R4_L_S162_EX_02", prompt: "Mia bought a book that tells the story of a young cook. What tells the story?", steps: ["定位 that tells the story。", "回看 that 前的 book。", "排除句尾的 cook。"], answer: "The book.", why: "that 代替 a book 作 tells 的主詞，因此是書在講述故事。young cook 位於故事內容中，並沒有在這個句子裡執行 tells。" },
      { id: "ENG_R4_L_S162_EX_03", prompt: "The cups which are on the table are clean. Which things are on the table?", steps: ["找出 which are on the table。", "確認 which 前是複數 cups。", "用 are 與複數先行詞互相驗證。"], answer: "The cups.", why: "which are on the table 用來指出那些杯子的位置，先行詞是複數 cups。後面的 are 也和 cups 一致，不是把 table 當成被修飾物。" },
    ],
    misconceptions: [
      { belief: "關係代名詞前出現兩個名詞時，第一個一定是先行詞。", whyWrong: "先行詞要由子句位置與語意共同判斷，不靠整句第一個名詞。", correction: "先找關係子句，再把候選名詞放回缺少的位置檢查。" },
      { belief: "關係子句最後一個名詞會被下一段關係子句修飾。", whyWrong: "基本限定關係子句通常緊接自己的先行詞，句尾名詞可能只是子句成分。", correction: "沿著關係代名詞往前找直接相連且語意合理的名詞。" },
      { belief: "先行詞一定是人，因為句子在描述誰做事。", whyWrong: "書、車、店與其他事物也能被關係子句限定。", correction: "先判斷子句缺少的是人物還是事物，再連回相符名詞。" },
      { belief: "先行詞單複數不影響關係子句中的動詞。", whyWrong: "關係代名詞作主詞時，動詞需與它所代替的先行詞一致。", correction: "比較 student who works 與 students who work 的差異。" },
    ],
    checks: [
      { prompt: "The bus that goes to the station stops here 中，that 修飾什麼？", answer: "the bus", reason: "goes 的主體是 bus，station 只是目的地。" },
      { prompt: "The teachers who are talking know Mia 中，誰在交談？", answer: "the teachers", reason: "who are talking 直接限定複數 teachers。" },
      { prompt: "The phone that Ben found is mine 中，Ben 是先行詞嗎？", answer: "不是", reason: "that 指 phone，Ben 是 found 的主詞。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S163", "ENG_R4_S163", {
    objectives: ["依先行詞為人物或事物選擇 who 與 which。", "同時維持子句動詞與先行詞的數量一致。"],
    sections: [
      { title: "who 在基本句型中連接人物", content: "The girl who called me is Amy 以 who 代替 the girl。who 可以在子句中作主詞或受詞，但先行詞必須是人物；不能因後面出現物品，就把選擇改成 which。" },
      { title: "which 連接事物與一般動物", content: "The bike which is near the gate is mine 中，which 指 bike。國中基本分類通常把物品與一般動物歸入 which；考題會提供清楚先行詞，不會要求用語風格上的特殊擬人選擇。" },
      { title: "選詞先看先行詞而非子句動詞", content: "The nurse who found the key 與 The key which opened the box 都有動作，但前者先行詞是人，後者是物。動詞是否主動、有沒有生命都不是唯一線索。" },
      { title: "關係代名詞作主詞時帶動數量一致", content: "The boy who lives here 與 The boys who live here 都使用 who，差別在 lives 和 live。which 也是如此：a bus which goes、buses which go。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S163_EX_01", prompt: "The man ___ works at the shop is my uncle. (who / which)", steps: ["找出先行詞 the man。", "確認 man 是人物。", "以 who 作 works 的主詞。"], answer: "who", why: "the man 是人物，因此用 who 連接 works at the shop。which 在基本分類中用於事物，放在這裡會使關係代名詞與先行詞類型不合。" },
      { id: "ENG_R4_L_S163_EX_02", prompt: "The train ___ stops here goes to the city. (who / which)", steps: ["定位先行詞 the train。", "判斷 train 是事物。", "用 which 代替 train 作 stops 的主詞。"], answer: "which", why: "train 是交通工具，不是人物，所以關係子句使用 which。which stops here 指定停靠此處的那班火車，who 不符合先行詞類型。" },
      { id: "ENG_R4_L_S163_EX_03", prompt: "The students ___ help in the library are in Class 2. (who / which)", steps: ["辨認 students 為人物複數。", "選 who 代替 students。", "確認後接複數動詞 help。"], answer: "who", why: "students 是人物，應使用 who；who 在子句中代替複數 students，因此接 help 而不是 helps。答案同時符合人物分類與動詞一致。" },
    ],
    misconceptions: [
      { belief: "who 只可用於單數人物，複數人物要改用 which。", whyWrong: "who 可代替單數或複數人物。", correction: "由先行詞數量調整子句動詞，不改變 who 的人物功能。" },
      { belief: "會移動的先行詞都使用 who。", whyWrong: "車輛與一般動物也會移動，但基本分類仍可用 which。", correction: "依人物或事物分類，不依動作能力選詞。" },
      { belief: "子句裡出現人名就一定選 who。", whyWrong: "關係代名詞連回先行詞，人名可能只是子句內的主詞。", correction: "在 The book which Amy read 中，先行詞 book 決定 which。" },
      { belief: "先選 who 或 which，再猜它前面修飾哪個名詞。", whyWrong: "這會把判斷順序倒轉，容易連錯對象。", correction: "先確認先行詞類型，再選相應關係代名詞。" },
    ],
    checks: [
      { prompt: "the doctor ___ helped us 應填什麼？", answer: "who", reason: "doctor 是人物先行詞。" },
      { prompt: "the map ___ is on the wall 應填什麼？", answer: "which", reason: "map 是事物先行詞。" },
      { prompt: "the girls who ___ here 應填 lives 還是 live？", answer: "live", reason: "who 代替複數 girls。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S164", "ENG_R4_S164", {
    objectives: ["用 that 連接基本限定關係子句。", "區分關係代名詞 that 與指示詞 that 的句中功能。"],
    sections: [
      { title: "that 可限定人物或事物", content: "The boy that won the race 與 The book that is on the desk 都是基本限定關係子句。that 代替前面的先行詞，提供辨識所需資訊；人物也可在這類句型中使用 that。" },
      { title: "限定資訊回答是哪一個", content: "Bring me the bag that has a blue star 的關係子句從多個袋子中指出目標。若拿掉 that has a blue star，讀者可能不知道要拿哪一個，因此這段資訊具有辨識功能。" },
      { title: "that 在子句中仍占一個角色", content: "The bus that stops here 中，that 是 stops 的主詞；The song that Mia likes 中，that 是 likes 的受詞。不能把 that 當成沒有功能的接合字而在子句內再補相同角色。" },
      { title: "指示詞 that 不一定開啟關係子句", content: "That is my bag 的 That 自己是整句主詞，前面沒有先行詞；I know that he is home 的 that 連接內容，也不是關係代名詞。本單元只在 that 緊接名詞並代替該名詞時分析關係子句。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S164_EX_01", prompt: "The student ___ sits by the door is Ben. (that / those)", steps: ["找出人物先行詞 student。", "確認空格需作 sits 的主詞。", "選 that 開啟限定子句。"], answer: "that", why: "that 可代替 the student 作 sits 的主詞，that sits by the door 指定坐在門邊的學生。those 是複數指示詞，不能放進這個單數關係子句。" },
      { id: "ENG_R4_L_S164_EX_02", prompt: "I returned the book ___ I borrowed yesterday. (that / it)", steps: ["辨認 book 是 borrowed 的對象。", "讓 that 代替 book 作受詞。", "排除重複受詞 it。"], answer: "that", why: "that 連回 the book，並填入 I borrowed 後缺少的受詞位置。若改用 it，兩句之間沒有關係代名詞，且無法形成題目要求的限定結構。" },
      { id: "ENG_R4_L_S164_EX_03", prompt: "That is the chair that Mia chose. Which use of that stands for the chair?", steps: ["檢查第一個 That 是否有先行詞。", "找出緊接 chair 的第二個 that。", "確認第二個 that 代替 chair 作 chose 的受詞。"], answer: "The second that.", why: "句首 That 是整句主詞，用來指出物品；chair 後的 that 才連接 Mia chose 並代替 chair。相同拼字必須依句中位置與功能區分。" },
    ],
    misconceptions: [
      { belief: "人物先行詞只能用 who，使用 that 一定錯。", whyWrong: "基本限定關係子句可用 that 指人物。", correction: "依題目要求與句型選 who 或 that，不把人物 that 一律刪除。" },
      { belief: "每個 that 都是關係代名詞。", whyWrong: "that 也可作指示詞或內容連接詞。", correction: "確認前面是否有先行詞，且 that 是否在後面子句占角色。" },
      { belief: "that 只負責把兩段文字接起來，不代替任何成分。", whyWrong: "關係代名詞 that 在子句中作主詞或受詞。", correction: "找出 that 代替的先行詞及它在子句中的空位。" },
      { belief: "限定子句拿掉後，讀者永遠仍知道是哪個人或物。", whyWrong: "多個候選對象存在時，限定資訊可能不可缺少。", correction: "檢查上下文是否需要子句來辨認目標。" },
    ],
    checks: [
      { prompt: "the chair that is near the window 中，that 指什麼？", answer: "the chair", reason: "that 緊接 chair 並作 is 的主詞。" },
      { prompt: "That is my chair 中有關係子句嗎？", answer: "沒有", reason: "句首 That 沒有先行詞。" },
      { prompt: "the friend that called me 可否在基本限定句中成立？", answer: "可以", reason: "that 可指人物並作 called 的主詞。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S165", "ENG_R4_S165", {
    objectives: ["判斷關係代名詞在子句中作主詞或受詞。", "利用子句結構辨識是否可省略受詞關係代名詞。"],
    sections: [
      { title: "關係代名詞後直接接動詞時常作主詞", content: "The girl who called me 中，who 後直接接 called，表示 girl 發出電話；who 填補子句主詞。主詞關係代名詞不能直接省略，否則會剩下 the girl called me，語意與結構都改變。" },
      { title: "關係代名詞後已有主詞時常作受詞", content: "The girl who I called 中，who 後已有 I 作 called 的主詞，所以 who 代替被打電話的 girl，功能是受詞。判讀時要看子句是否已經有明確動作者。" },
      { title: "受詞關係代名詞在基本限定句中可省略", content: "The book that Amy bought 可寫成 The book Amy bought，因為 Amy 已是子句主詞，book 的受詞空位仍能理解。但 The book that fell 不能刪成 The book fell 來表達相同結構，因為 that 本來是 fell 的主詞。" },
      { title: "主受詞功能決定後續動詞形式", content: "people who work here 中 who 作主詞，work 依 people；the person who we help 中 we 已作主詞，help 依 we。不能看到單數 person 就把第二句的 help 改成 helps。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S165_EX_01", prompt: "The boy who found the wallet called us. Is who the subject or object of found?", steps: ["查看 who 後是否另有主詞。", "確認 found 前只有 who。", "把 boy 還原成 found 的執行者。"], answer: "The subject.", why: "who 後直接接 found，沒有另一個人物執行尋找，因此 who 代替 the boy 作 found 的主詞。wallet 才是 found 的受詞。" },
      { id: "ENG_R4_L_S165_EX_02", prompt: "The boy who Mia called is here. Is who the subject or object of called?", steps: ["找出 called 前的 Mia。", "確認 Mia 已是子句主詞。", "把 who 放到 called 的受詞位置。"], answer: "The object.", why: "Mia 執行 called，所以子句主詞已經完整；who 代替被 Mia 打電話的 boy，位於受詞空位。不能把 boy 誤判成打電話的人。" },
      { id: "ENG_R4_L_S165_EX_03", prompt: "The song that we heard was beautiful. Can that be left out here?", steps: ["確認 we 是 heard 的主詞。", "判斷 that 代替 song 作受詞。", "檢查省略後仍有 we heard 的結構。"], answer: "Yes.", why: "we 已作 heard 的主詞，that 只代替被聽見的 song，因此限定句可寫成 The song we heard。省略後不能再加 it，否則受詞會重複。" },
    ],
    misconceptions: [
      { belief: "who 一律在關係子句中作主詞。", whyWrong: "who 後若已有主詞，who 可能作受詞。", correction: "比較 who called Mia 與 who Mia called 的詞序。" },
      { belief: "先行詞是單數時，關係子句動詞一定加 s。", whyWrong: "受詞關係代名詞後的動詞要配合子句內真正主詞。", correction: "the person who we help 中 help 配合 we。" },
      { belief: "所有關係代名詞都可以省略。", whyWrong: "作主詞的關係代名詞省略後會失去子句主詞。", correction: "只在基本限定句中確認它作受詞後才考慮省略。" },
      { belief: "省略受詞關係代名詞後要補 it 或 him。", whyWrong: "先行詞仍填補受詞空位，再補代名詞會重複。", correction: "保留 The book Amy read，不加 it。" },
    ],
    checks: [
      { prompt: "the nurse who helped Ben 中，who 是什麼功能？", answer: "主詞", reason: "who 直接執行 helped。" },
      { prompt: "the nurse who Ben helped 中，who 是什麼功能？", answer: "受詞", reason: "Ben 已是 helped 的主詞。" },
      { prompt: "the cake that fell 中可省略 that 嗎？", answer: "不可以", reason: "that 是 fell 的主詞。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S166", "ENG_R4_S166", {
    objectives: ["刪除關係子句中重複的主詞或受詞代名詞。", "在省略受詞關係代名詞時仍保留完整且不重複的結構。"],
    sections: [
      { title: "主詞關係代名詞後不再放 he、she 或 it", content: "The girl who sings 不寫成 The girl who she sings，因為 who 已代替 girl 作 sings 的主詞。多放 she 會讓同一個子句出現兩個競爭主詞。" },
      { title: "受詞關係代名詞後不再重複 it 或 him", content: "The book that I read 不寫成 The book that I read it。that 已代替 book 作 read 的受詞，再放 it 會重複同一角色。" },
      { title: "省略受詞關係代名詞不等於補回代名詞", content: "The bike that Ben rides 可簡化為 The bike Ben rides；兩種形式都只保留一個受詞空位。The bike Ben rides it 仍然錯，因為 it 與先行詞 bike 重複。" },
      { title: "檢查方式是還原兩個基本句子", content: "The boy who lives next door 可還原成 The boy lives next door；The boy who Mia knows 可還原成 Mia knows the boy。若還原時同一名詞出現兩次，就表示原關係子句可能多放代名詞。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S166_EX_01", prompt: "The woman who she works here is my aunt. Take out one word to fix the sentence.", steps: ["確認 who 代替 the woman。", "判斷 who 已作 works 的主詞。", "刪除重複主詞 she。"], answer: "Take out the word she.", why: "who 已指回 the woman 並作 works 的主詞，she 重複同一人物。刪除 she 後成為 The woman who works here，角色與動詞都完整。" },
      { id: "ENG_R4_L_S166_EX_02", prompt: "This is the bag that I found it on the bus. Take out one word.", steps: ["找出 I 作 found 的主詞。", "確認 that 代替 bag 作受詞。", "刪除重複的 it。"], answer: "Take out the word it.", why: "that 已把 the bag 放進 found 的受詞位置，it 又指同一個袋子，因此形成雙重受詞。保留 that I found on the bus 即可。" },
      { id: "ENG_R4_L_S166_EX_03", prompt: "The coat we bought it was blue. Which word should be taken out?", steps: ["辨認省略的受詞關係代名詞。", "確認 we 是 bought 的主詞。", "刪除補回的重複受詞 it。"], answer: "Take out the word it.", why: "The coat we bought 已能讓 coat 填補 bought 的受詞空位，省略 that 不會讓空位消失。再加 it 反而把 coat 重複一次。" },
    ],
    misconceptions: [
      { belief: "who 後一定要再放 he 或 she，句子才有主詞。", whyWrong: "who 作主詞時已承擔人物角色。", correction: "寫 who works、who called，不再加同指代名詞。" },
      { belief: "that 只是連接符號，所以受詞位置仍需 it。", whyWrong: "受詞 that 本身代替先行詞。", correction: "寫 the book that I read，不加 it。" },
      { belief: "省略 that 後，it 就可以補進受詞位置。", whyWrong: "省略只隱去關係代名詞，先行詞與空位的關係仍存在。", correction: "寫 the book I read，受詞不要重複。" },
      { belief: "看到兩個代名詞時，刪掉哪一個都不影響意思。", whyWrong: "刪錯關係代名詞可能破壞限定結構或改變主受詞。", correction: "先判斷每個詞的子句角色，再只刪除重複者。" },
    ],
    checks: [
      { prompt: "the boy who he won the game 應刪哪個詞？", answer: "he", reason: "who 已作 won 的主詞。" },
      { prompt: "the box that Mia opened it 應刪哪個詞？", answer: "it", reason: "that 已作 opened 的受詞。" },
      { prompt: "the box Mia opened it 仍正確嗎？", answer: "不正確", reason: "省略 that 後也不能重複受詞 it。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S167", "ENG_R4_S167", {
    objectives: ["找出兩句中的共同名詞並合併成關係子句。", "保留原句的時態、否定與人物角色，不加入新意思。"],
    sections: [
      { title: "先找兩句共同指向的人或物", content: "I know the boy. He won the race. 兩句的 the boy 與 He 指同一人，可合成 I know the boy who won the race。共同名詞成為先行詞，第二句代名詞改為關係代名詞。" },
      { title: "共同名詞作受詞時留下受詞空位", content: "This is the book. Amy bought it yesterday. 合成 This is the book that Amy bought yesterday。Amy 保留為 bought 的主詞，it 所代表的 book 改由 that 連回。" },
      { title: "合併不得改變原本事件關係", content: "The girl is Nora. She called Ben. 可合成 The girl who called Ben is Nora，不能改成 the girl who Ben called，因為後者交換了打電話的人與接電話的人。" },
      { title: "時間、否定與數量都要保留", content: "I met two students. They did not join the game. 合併時仍需保留 two、did not 與過去時態：I met two students who did not join the game。關係子句不是刪減重要條件的理由。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S167_EX_01", prompt: "I thanked the nurse. She helped my father. Join the ideas without changing who helped.", steps: ["確認 She 指 the nurse。", "讓 who 代替 She 作 helped 的主詞。", "把子句放在 nurse 後。"], answer: "I thanked the nurse who helped my father.", why: "nurse 與 She 是同一人，而且她執行 helped，所以用 who 作子句主詞。合併後父親仍是受到幫助的人，角色沒有交換。" },
      { id: "ENG_R4_L_S167_EX_02", prompt: "The movie was exciting. We watched it last night. Join the ideas.", steps: ["確認 it 指 the movie。", "保留 we 作 watched 的主詞。", "用 that 取代受詞 it。"], answer: "The movie that we watched last night was exciting.", why: "we 是觀看者，movie 是被看的對象，所以 that 在 we watched 後填補受詞。last night 和 exciting 都保留，沒有把電影寫成觀看者。" },
      { id: "ENG_R4_L_S167_EX_03", prompt: "The students are from Tainan. They won the game yesterday. Join the ideas.", steps: ["把 They 連回 the students。", "使用 who 作 won 的主詞。", "保留 yesterday 與複數 are。"], answer: "The students who won the game yesterday are from Tainan.", why: "who 代替複數 students 執行 won，yesterday 仍限定獲勝時間。主要句保留 are from Tainan，沒有把地點誤接到比賽上。" },
    ],
    misconceptions: [
      { belief: "合併兩句時只要把 who 放在任意兩句中間。", whyWrong: "關係子句必須緊接共同名詞，且 who 要占正確角色。", correction: "先找共同指涉，再依第二句主受詞安排詞序。" },
      { belief: "第二句的人稱代名詞與關係代名詞要一起保留。", whyWrong: "兩者若指同一先行詞會造成角色重複。", correction: "用關係代名詞取代共同名詞或代名詞，不並列兩者。" },
      { belief: "合併後可省略原句的 not、時間或數量。", whyWrong: "這些資訊會改變事件範圍與真假。", correction: "完成句型後逐項核對原本條件是否都保留。" },
      { belief: "主動與受動角色在合併時可以互換。", whyWrong: "交換角色會形成另一個事件。", correction: "還原兩個原句，檢查誰做事、誰承受仍相同。" },
    ],
    checks: [
      { prompt: "I know the girl. She sings here. 合併後 who 取代誰？", answer: "She，也就是 the girl", reason: "girl 是 sings 的執行者。" },
      { prompt: "This is the cake. Mia made it. 合併時保留 Mia 嗎？", answer: "保留", reason: "Mia 是 made 的主詞，it 才由 that 取代。" },
      { prompt: "兩句都有 yesterday，合併後可任意刪除嗎？", answer: "不可以", reason: "時間若屬必要原意就必須保留。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S168", "ENG_R4_S168", {
    objectives: ["用關係子句從多個候選人或事物中辨識目標。", "只依明示限定資訊推論，不把子句擴大成所有成員的共同特徵。"],
    sections: [
      { title: "限定子句把候選範圍縮小", content: "There are two bags. Take the bag that has a blue star. 關係子句指出要拿有藍星的袋子，不是任意一個。解題時要把子句中的每項特徵與候選物逐一比對。" },
      { title: "子句只描述它所連接的先行詞", content: "The students who finished may leave 不代表所有學生都完成；只說完成的那群可以離開。不能把限定條件移到未被子句修飾的人或物上。" },
      { title: "多個條件要一起滿足", content: "Choose the bus that stops here and goes to the station 要同時符合停靠此處與前往車站。只符合其中一項的公車仍不能確定是目標。" },
      { title: "不要從辨識資訊推測未寫出的原因", content: "The boy who is wearing a red hat is my brother 能辨認哥哥，卻不能推出他喜歡紅色、帽子是新的或其他男孩沒有帽子。關係子句提供的是限定證據，不是完整背景故事。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S168_EX_01", prompt: "Two keys are on the table. Use the key that has a green star. Which key should be used?", steps: ["列出兩把鑰匙。", "讀取限定條件 green star。", "選擇唯一符合條件者。"], answer: "The key with the green star.", why: "that has a green star 把目標從兩把鑰匙中分出來。題目沒有說另一把鑰匙不能開門，只能確定應使用帶綠色星號的那把。" },
      { id: "ENG_R4_L_S168_EX_02", prompt: "Students who finished the work may go home. Can a student who has not finished leave?", steps: ["找出可離開的先行詞 students。", "套用 who finished the work 的限制。", "檢查未完成者是否符合。"], answer: "No.", why: "may go home 只適用於符合 who finished the work 的學生。未完成者不在這個限定群體內，因此不能從句子取得離開許可。" },
      { id: "ENG_R4_L_S168_EX_03", prompt: "Three rooms are open. The room that has a green door is for the music club. Which room should the music club use?", steps: ["找出提供給 music club 的 room。", "讀取該 room 的限定資訊 green door。", "用門的顏色辨認正確教室。"], answer: "The room with the green door.", why: "that has a green door 只限定提供給音樂社的教室。其他教室雖然也開放，題目沒有說它們供音樂社使用，因此應選綠色門的教室。" },
    ],
    misconceptions: [
      { belief: "關係子句描述一群中的成員時，條件會自動套用到全群。", whyWrong: "限定子句常只挑出符合條件的子群。", correction: "把有條件與無條件的成員分開判讀。" },
      { belief: "候選物符合關係子句的一半條件就足以選定。", whyWrong: "and 連接的條件通常都必須成立。", correction: "逐項建立條件表，只選同時符合者。" },
      { belief: "辨認出目標後，可以補上合理但未寫出的原因。", whyWrong: "合理猜測仍不是文本證據。", correction: "答案只保留關係子句與上下文直接支持的資訊。" },
      { belief: "關係子句只是補充背景，刪掉不會影響讀者選擇。", whyWrong: "有多個候選時，它可能是唯一辨識線索。", correction: "先比較刪除前後是否仍能唯一找到目標。" },
    ],
    checks: [
      { prompt: "Take the cup that is clean 中，哪個杯子是目標？", answer: "乾淨的杯子", reason: "that is clean 是選擇條件。" },
      { prompt: "People who have tickets may enter 表示所有人都可進入嗎？", answer: "不是", reason: "只限定持票者。" },
      { prompt: "關係子句寫紅帽子，能推出帽子是新買的嗎？", answer: "不能", reason: "新舊沒有文本證據。" },
    ], assets: [],
  }),
];

export const ENGLISH_U24_QUESTIONS = [
  ...skillQuestions("162", [
    { stem: "The boy who is waving is Ben. Who is waving?", options: ["The boy", "Ben's friend", "No one", "The reader"], answerIndex: 0, reasons: ["who is waving 緊接 the boy，指出男孩正在揮手。", "句中沒有提到 Ben 的朋友。", "is waving 明確表示有人正在進行動作。", "reader 不在事件中。"], reviews: ["先行詞 the boy 填入 who 在子句中的主詞位置。", "第一項只使用關係子句明示的角色，沒有增加人物。"], cognitiveProcess: ["u24-s162-link-waving-clause-to-boy", "exclude-unmentioned-participants"], representationType: "antecedent-person-identification", misconceptionTargets: ["mistake-predicate-name-for-separate-person"] },
    { stem: "I found the key which opens this box. What opens the box?", options: ["I", "The key", "The box", "The finding"], answerIndex: 1, reasons: ["I 執行 found，不是 opens 的主詞。", "which 代替 key，因此是鑰匙開箱。", "box 承受 opens，不能開啟自己。", "finding 是動作概念，不是句中物品。"], reviews: ["which opens this box 直接限定 the key。", "第二項能放回 opens 前的空位，語法與常識都成立。"], cognitiveProcess: ["u24-s162-restore-key-as-opens-subject", "separate-main-clause-finder-from-relative-agent"], representationType: "thing-antecedent-role-restoration", misconceptionTargets: ["choose-main-subject-as-relative-subject"] },
    { stem: "The cakes which are on the table are for the class. What is on the table?", options: ["The class", "Only one plate", "The cakes", "The lesson"], answerIndex: 2, reasons: ["class 是蛋糕的預定對象，不是位置主體。", "句中沒有 plate，也沒有單數限制。", "which 指複數 cakes，are on the table 描述它們。", "lesson 未出現在原文。"], reviews: ["兩個 are 分屬關係子句與主要句，皆連回 cakes。", "第三項符合複數先行詞，也沒有把 for the class 當地點。"], cognitiveProcess: ["u24-s162-track-cakes-through-two-are-clauses", "reject-purpose-noun-as-location-subject"], representationType: "plural-antecedent-tracking", misconceptionTargets: ["attach-relative-clause-to-later-noun"] },
    { stem: "Nora thanked the nurse who helped her. Who helped Nora?", options: ["Nora", "No person", "A doctor", "The nurse"], answerIndex: 3, reasons: ["Nora 執行 thanked，並由 her 接受 help。", "who helped 明確指出有人提供幫助。", "doctor 沒有出現在句子中。", "who 緊接 the nurse，所以護士幫助 Nora。"], reviews: ["主要句與關係子句有不同動作者，不能只看第一個人名。", "第四項保留 nurse 到 Nora 的幫助方向。"], cognitiveProcess: ["u24-s162-resolve-nurse-as-helper-of-nora", "separate-thanking-agent-from-helping-agent"], representationType: "cross-clause-agent-resolution", misconceptionTargets: ["carry-main-subject-into-relative-clause"] },
    { stem: "The bag that has a red star is under the chair. What has a red star?", options: ["The bag", "The chair", "The floor", "The room"], answerIndex: 0, reasons: ["that 代替 bag 作 has 的主詞。", "chair 只出現在 under 後，表示袋子位置。", "floor 沒有被提及。", "room 也不是關係子句描述的物品。"], reviews: ["先把 under the chair 當位置背景移開，關係子句便清楚指向 bag。", "第一項同時符合 that 前的位置與星號特徵。"], cognitiveProcess: ["u24-s162-distinguish-starred-bag-from-chair-location", "filter-under-phrase-from-antecedent"], representationType: "antecedent-versus-location-object", misconceptionTargets: ["choose-nearby-location-noun"] },
    { stem: "The people who live next door know Ben. Who lives next door?", options: ["Ben", "The people", "The door", "Everyone in town"], answerIndex: 1, reasons: ["Ben 是 know 的受詞，未被說成住在隔壁。", "who 代替 people 作 live 的主詞。", "door 是地點片語的一部分，不會居住。", "原文只限定這些 people，沒有涵蓋全鎮。"], reviews: ["關係子句先限定 people，主要句再說他們認識 Ben。", "第二項沒有把受詞 Ben 或地點名詞誤升為先行詞。"], cognitiveProcess: ["u24-s162-identify-neighbor-people-before-know-ben", "limit-reference-to-stated-group"], representationType: "relative-group-identification", misconceptionTargets: ["extend-relative-property-to-main-object"] },
    { stem: "Mia bought a book that tells a story about a young cook. What tells the story?", options: ["Mia", "The cook", "The book", "The shop"], answerIndex: 2, reasons: ["Mia 買書，但 tells 的主詞由 that 代替。", "cook 是故事中的人物，不是講述媒介。", "that 連回 book，所以書承載故事。", "shop 沒有出現在句子中。"], reviews: ["about a young cook 位於故事內容內，不能向後搶走 that 的連結。", "第三項能合理執行 tells，並與關係代名詞位置相鄰。"], cognitiveProcess: ["u24-s162-link-story-telling-to-book-not-cook", "resist-content-noun-attachment"], representationType: "nested-content-antecedent-analysis", misconceptionTargets: ["mistake-story-character-for-antecedent"] },
    { stem: "The bus that goes to the station stops here. What goes to the station?", options: ["The station", "This place", "A person", "The bus"], answerIndex: 3, reasons: ["station 是 goes to 的目的地。", "here 表示停靠位置，不是移動主體。", "句子沒有提到搭車人物。", "that 指 bus，bus 執行 goes。"], reviews: ["to the station 回答方向，不能把 station 當成先行詞。", "第四項連回 that 前的名詞，也符合交通語意。"], cognitiveProcess: ["u24-s162-recover-bus-as-goes-agent", "exclude-destination-and-deictic-place"], representationType: "movement-antecedent-identification", misconceptionTargets: ["confuse-destination-with-moving-subject"] },
    { stem: "The teacher spoke to the students who were waiting outside. Who was waiting?", options: ["The students", "The teacher", "Everyone at school", "No one"], answerIndex: 0, reasons: ["who 代替複數 students，were 也與其一致。", "teacher 執行 spoke，但不在關係子句中。", "限定只涵蓋這些學生，不是全校。", "were waiting 明確陳述等待事件。"], reviews: ["to the students 是主要句受詞片語，緊接的 who 再描述 students。", "第一項利用複數 were 驗證先行詞，沒有套到 teacher。"], cognitiveProcess: ["u24-s162-use-were-to-confirm-student-antecedent", "separate-speaking-teacher-from-waiting-group"], representationType: "agreement-supported-antecedent", misconceptionTargets: ["select-main-agent-over-relative-antecedent"] },
    { stem: "Amy found the phone that Leo lost on the bus. What did Leo lose?", options: ["The bus", "The phone", "Amy", "A ticket"], answerIndex: 1, reasons: ["bus 是遺失發生的地點。", "that 代替 phone 作 lost 的受詞。", "Amy 是 found 的主詞，不是可遺失物。", "ticket 沒有文本依據。"], reviews: ["Leo 已作 lost 的主詞，因此 that 的空位是被遺失物。", "第二項保留 phone 在主要句被找到、在子句曾遺失的兩個關係。"], cognitiveProcess: ["u24-s162-resolve-phone-as-leo-lost-object", "separate-bus-location-and-amy-finder"], representationType: "object-gap-antecedent-recovery", misconceptionTargets: ["attach-relative-object-to-location"] },
    { stem: "The boxes that are by the door belong to Sam. What is by the door?", options: ["Sam", "One person", "The boxes", "The owner only"], answerIndex: 2, reasons: ["Sam 是 belong to 後的所有人。", "句中談複數物品，不是單一人物。", "that 代替 boxes，are by the door 描述它們位置。", "owner 與位置資訊無關。"], reviews: ["複數 are 與 boxes 相配，belong to Sam 則是主要句。", "第三項沒有把所有者誤當成被定位的物品。"], cognitiveProcess: ["u24-s162-separate-box-location-from-sam-ownership", "use-plural-agreement-to-anchor-reference"], representationType: "ownership-location-clause-separation", misconceptionTargets: ["mistake-owner-for-relative-antecedent"] },
    { stem: "The girl with the blue bag who is talking to Mia is Nora. Who is talking to Mia?", options: ["The bag", "A boy not in the sentence", "Mia's teacher", "The girl with the blue bag"], answerIndex: 3, reasons: ["bag 是 with 片語中的物品，不能談話。", "句中沒有 boy。", "teacher 也未出現在原文。", "who 連回 girl；with the blue bag 只補充辨識特徵。"], reviews: ["介於 girl 與 who 之間的 with 片語不會改變人物核心。", "第四項完整保留女孩的辨識資訊，並讓她執行 talking。"], cognitiveProcess: ["u24-s162-cross-with-phrase-to-girl-antecedent", "reject-inanimate-and-unmentioned-speakers"], representationType: "intervening-phrase-antecedent-resolution", misconceptionTargets: ["choose-nearest-noun-inside-modifier"] },
  ]),
  ...skillQuestions("163", [
    { stem: "The man ___ works at the shop is my uncle.", options: ["who", "which", "where", "when"], answerIndex: 0, reasons: ["who 連接人物 man，並作 works 的主詞。", "which 在基本分類中連接事物。", "where 連接地點，不代替人物。", "when 用於時間，無法指 uncle。"], reviews: ["先行詞 the man 已決定需要人物關係代名詞。", "第一項放入後，who works at the shop 完整限定該男子。"], cognitiveProcess: ["u24-s163-select-who-for-working-man", "reject-place-time-and-thing-relatives"], representationType: "person-relative-pronoun-cloze", misconceptionTargets: ["choose-relative-word-from-clause-topic"] },
    { stem: "The train ___ stops here goes to the city.", options: ["who", "which", "whose", "why"], answerIndex: 1, reasons: ["train 不是人物，不用 who。", "which 代替 train 作 stops 的主詞。", "whose 表所有關係，句中沒有名詞接續。", "why 不用來代替交通工具。"], reviews: ["關係子句指出停靠此處的那班火車。", "第二項符合事物先行詞，也能直接接動詞 stops。"], cognitiveProcess: ["u24-s163-select-which-for-stopping-train", "exclude-possession-and-reason-forms"], representationType: "thing-relative-pronoun-cloze", misconceptionTargets: ["use-who-for-moving-object"] },
    { stem: "The students who help in the library are in Class 2. Why is who used?", options: ["The library is a place.", "Class 2 is a number.", "The students are people.", "Help is an action."], answerIndex: 2, reasons: ["library 位於子句內，並非先行詞。", "班級編號不決定關係代名詞。", "who 連回人物 students。", "動詞類型不會取代先行詞分類。"], reviews: ["選 who 的依據是它前面的 students，而不是後面出現的字。", "第三項抓到人物類型，也保留複數 help。"], cognitiveProcess: ["u24-s163-explain-who-from-student-antecedent", "ignore-location-number-and-verb-distractors"], representationType: "relative-choice-reasoning-person", misconceptionTargets: ["choose-pronoun-from-later-word"] },
    { stem: "The map which is on the wall shows the old road. What does which stand for?", options: ["The wall", "The road", "The place", "The map"], answerIndex: 3, reasons: ["wall 是 on 後的地點名詞。", "old road 是主要句 shows 的內容。", "place 是泛稱，原句沒有這個先行詞。", "which 緊接 map 並作 is 的主詞。"], reviews: ["把 map 放回 is on the wall，會得到完整且合理的描述。", "第四項說明 which 選用事物形式的真正原因。"], cognitiveProcess: ["u24-s163-resolve-which-to-map", "separate-wall-and-shown-road"], representationType: "which-antecedent-replacement", misconceptionTargets: ["attach-which-to-relative-clause-object"] },
    { stem: "The doctor ___ helped Leo called his family.", options: ["who", "which", "where", "what"], answerIndex: 0, reasons: ["doctor 是人物，who 可代替他作 helped 的主詞。", "which 不符合人物先行詞的基本分類。", "where 需要地點先行詞。", "what 不在此連接已明示的 doctor。"], reviews: ["關係子句先指出幫助 Leo 的醫師，主要句再說醫師打電話。", "第一項維持同一人物跨兩個動作的角色。"], cognitiveProcess: ["u24-s163-connect-doctor-to-helped-with-who", "reject-nonperson-relative-forms"], representationType: "two-action-person-relative-cloze", misconceptionTargets: ["choose-which-because-leo-is-object"] },
    { stem: "This is the tool ___ opens the back door.", options: ["who", "which", "when", "where"], answerIndex: 1, reasons: ["tool 不是人物，因此不使用 who。", "which 代替 tool 並執行 opens。", "when 指時間，不能開門。", "where 指地點，無法代替工具。"], reviews: ["是否能執行 opens 不會把工具變成人物。", "第二項依先行詞的事物類型作選擇，而非依動作能力猜測。"], cognitiveProcess: ["u24-s163-use-which-for-functional-tool", "resist-agentive-verb-human-bias"], representationType: "inanimate-agent-relative-choice", misconceptionTargets: ["use-who-for-thing-performing-action"] },
    { stem: "The girls ___ sit near the window are my cousins.", options: ["near", "window", "who", "are"], answerIndex: 2, reasons: ["near 是位置介系詞，不能連接人物與動詞。", "window 是地點名詞，不能放在 girls 後作 sit 的主詞。", "who 代替 girls 作 sit 的主詞。", "are 屬於主要句動詞，放入空格會留下兩個動詞。"], reviews: ["空格位於先行詞 girls 與子句動詞 sit 之間。", "第三項同時具有人物連結與主詞功能。"], cognitiveProcess: ["u24-s163-identify-who-linking-girls-and-sit", "separate-main-verb-and-location-words"], representationType: "relative-pronoun-cloze", misconceptionTargets: ["mistake-preposition-or-main-verb-for-link"] },
    { stem: "The phone who rang during class was Nora's. Change who to ___.", options: ["when", "whose", "where", "which"], answerIndex: 3, reasons: ["when 需要時間先行詞。", "whose 表所有關係，後面還需要所屬名詞。", "phone 不是地點，不能用 where。", "which 連回事物 phone，並作 rang 的主詞。"], reviews: ["錯誤發生在人物形式 who 與事物先行詞 phone 不合。", "第四項只改關係代名詞，不改電話響起或 Nora 擁有它的意思。"], cognitiveProcess: ["u24-s163-repair-who-to-which-for-phone", "preserve-phone-ringing-and-ownership"], representationType: "relative-pronoun-error-repair", misconceptionTargets: ["let-later-person-name-control-pronoun"] },
    { stem: "Amy spoke to the man ___ found her bag.", options: ["who", "which", "when", "where"], answerIndex: 0, reasons: ["who 連回 man，表示他找到袋子。", "which 不用於此人物先行詞。", "when 需要時間名詞。", "where 需要地點名詞。"], reviews: ["Amy 是 spoke 的主詞，並不妨礙 man 成為 found 的主詞。", "第一項把兩個子句的不同動作者分開保留。"], cognitiveProcess: ["u24-s163-link-man-as-bag-finder", "distinguish-main-speaker-from-relative-agent"], representationType: "object-noun-person-relative-cloze", misconceptionTargets: ["reuse-main-subject-for-relative-action"] },
    { stem: "The picture ___ Mia drew is in the hall.", options: ["who", "which", "when", "where"], answerIndex: 1, reasons: ["picture 不是人物，不能用 who。", "which 代替 picture 作 drew 的受詞。", "when 無法指作品。", "where 不能填補 Mia drew 後的受詞空位。"], reviews: ["Mia 已是 drew 的主詞，因此 which 承接被畫的 picture。", "第二項依先行詞類型與子句空位都能成立。"], cognitiveProcess: ["u24-s163-select-which-for-drawn-picture-object", "reject-adverb-relatives-in-object-gap"], representationType: "object-relative-which-cloze", misconceptionTargets: ["choose-where-because-picture-is-in-hall"] },
    { stem: "The workers which are painting the gate will finish at noon. Change which to ___.", options: ["when", "where", "who", "whose"], answerIndex: 2, reasons: ["when 會把 workers 誤當時間。", "where 不能代替人作 are painting 的主詞。", "who 連接 workers 並作子句主詞。", "whose 表所有關係，不能直接接 are painting。"], reviews: ["at noon 位於主要句末，不會把人物先行詞改成時間。", "第三項與複數 are painting 共同形成完整子句。"], cognitiveProcess: ["u24-s163-repair-which-to-who-for-workers", "coordinate-who-with-plural-are"], representationType: "plural-person-relative-repair", misconceptionTargets: ["switch-who-by-number"] },
    { stem: "The buses ___ stop by the school go downtown.", options: ["who stops", "which stops", "who stop", "which stop"], answerIndex: 3, reasons: ["buses 不是人物，且 stops 也不合複數。", "which 類型正確，但 stops 不合複數 buses。", "stop 數量正確，who 卻不合事物先行詞。", "which 指 buses，stop 配合複數。"], reviews: ["這題要同時檢查先行詞類型與動詞一致，不能只對一半。", "第四項以 which stop 完整限定停靠學校旁的公車。"], cognitiveProcess: ["u24-s163-integrate-bus-which-and-plural-stop", "reject-half-correct-pronoun-verb-pairs"], representationType: "relative-pronoun-agreement-pair", misconceptionTargets: ["check-pronoun-without-verb-agreement"] },
  ]),
  ...skillQuestions("164", [
    { stem: "The boy ___ won the race is my cousin.", options: ["that", "those", "this", "these"], answerIndex: 0, reasons: ["that 可代替人物 boy 作 won 的主詞。", "those 是複數指示詞，不能開啟此子句。", "this 指單數近物，但不連接先行詞與 won。", "these 是複數形式，與 boy 及句型皆不合。"], reviews: ["題目要求一個能在 won 前代替 boy 的關係代名詞。", "第一項形成基本限定句，指出贏得比賽的男孩。"], cognitiveProcess: ["u24-s164-use-that-for-race-winning-boy", "reject-demonstratives-as-relative-connectors"], representationType: "that-person-subject-cloze", misconceptionTargets: ["ban-that-with-person"] },
    { stem: "I returned the book ___ I borrowed yesterday.", options: ["it", "that", "there", "then"], answerIndex: 1, reasons: ["it 會缺少關係連接，且重複 book。", "that 代替 book 作 borrowed 的受詞。", "there 指地點，不能填入物件空位。", "then 指時間，無法連回 book。"], reviews: ["I 已是 borrowed 的主詞，空格需要被借的物品。", "第二項讓 yesterday 保留時間功能，book 保留受詞角色。"], cognitiveProcess: ["u24-s164-insert-that-for-borrowed-book", "distinguish-object-relative-from-place-time-adverbs"], representationType: "that-thing-object-cloze", misconceptionTargets: ["insert-resumptive-it-instead-of-relative"] },
    { stem: "That is the bike that Leo rides to school. Which use of that stands for the bike?", options: ["The first That", "Both uses", "The second that", "Neither use"], answerIndex: 2, reasons: ["句首 That 是主要句主詞，前面沒有先行詞。", "只有 bike 後的 that 代替 bike。", "第二個 that 緊接 bike 並連到 Leo rides。", "第二個 that 確實有明確先行詞。"], reviews: ["相同拼字可有不同功能，必須查看它是否跟在名詞後。", "第三項代替 bike 作 rides 的受詞，符合關係代名詞條件。"], cognitiveProcess: ["u24-s164-distinguish-demonstrative-and-relative-that", "locate-relative-clause-boundary"], representationType: "that-function-disambiguation", misconceptionTargets: ["label-every-that-as-relative"] },
    { stem: "Bring me the bag ___ has a blue star.", options: ["it", "where", "there", "that"], answerIndex: 3, reasons: ["it 會留下兩句並列不明，也不能作關係連接。", "where 指地點，不代替 bag 作 has 的主詞。", "there 是地點副詞。", "that 代替 bag 並限定有藍星的那一個。"], reviews: ["多個袋子存在時，that has a blue star 提供必要辨識條件。", "第四項直接接 has，顯示 that 在子句中作主詞。"], cognitiveProcess: ["u24-s164-complete-blue-star-bag-restriction", "reject-pronoun-and-location-fillers"], representationType: "identifying-that-cloze", misconceptionTargets: ["treat-that-as-optional-when-identification-needed"] },
    { stem: "The student that sits by the door is Ben. What does that stand for?", options: ["The student", "The door", "Ben's chair", "The class"], answerIndex: 0, reasons: ["that 緊接 student，並作 sits 的主詞。", "door 是 by 後的地點參照。", "chair 沒有出現在句中。", "class 也沒有文本連結。"], reviews: ["把 the student 放回 sits by the door，會得到完整敘述。", "第一項證明人物先行詞在基本限定句也可使用 that。"], cognitiveProcess: ["u24-s164-map-subject-that-to-student", "exclude-door-and-unmentioned-nouns"], representationType: "that-person-antecedent-resolution", misconceptionTargets: ["assume-that-must-refer-to-thing"] },
    { stem: "I like the song that Mia sang at the show. What did Mia sing?", options: ["The show", "The song", "The time", "The singer"], answerIndex: 1, reasons: ["show 是演唱地點或活動。", "that 代替 song 作 sang 的受詞。", "句中沒有以 time 作被唱內容。", "Mia 才是歌手，singer 不是受詞。"], reviews: ["Mia 已是 sang 的主詞，that 的空位自然落在受詞。", "第二項同時連回先行詞並保留 at the show 的背景。"], cognitiveProcess: ["u24-s164-recover-song-as-sang-object", "separate-show-setting-from-relative-object"], representationType: "that-object-role-question", misconceptionTargets: ["choose-event-location-as-antecedent"] },
    { stem: "I know that he is home. Does that stand for a noun in this sentence?", options: ["Yes, it stands for home.", "Yes, it stands for the word I.", "No, there is no noun before it for it to stand for.", "No, because that can only point to things."], answerIndex: 2, reasons: ["home 出現在 that 後，且不是它的先行詞。", "I 是 know 的主詞，沒有被 that 限定。", "that 連接 know 的內容，前面沒有被代替名詞。", "that 不只作指示詞，也有其他連接功能。"], reviews: ["關係代名詞必須連回先行詞並在子句中占角色。", "第三項指出這裡缺少關係結構所需的名詞連結。"], cognitiveProcess: ["u24-s164-reject-content-that-as-relative", "apply-antecedent-and-gap-test"], representationType: "nonrelative-that-classification", misconceptionTargets: ["overgeneralize-that-function"] },
    { stem: "The chair that is by the window is free. In 'that is by the window,' what does that stand for?", options: ["A time", "The window", "A different chair", "The chair"], answerIndex: 3, reasons: ["關係子句沒有時間意義。", "window 位於 by 後，不是 that 指向的事物。", "that 沒有另指一張椅子。", "that 代替前面的 chair，直接作 is 的主詞。"], reviews: ["把 The chair 放回 is by the window，可得到完整句意。", "第四項也說明為何 that 後不能再加 it。"], cognitiveProcess: ["u24-s164-identify-that-as-is-subject", "reject-time-object-and-new-reference-readings"], representationType: "that-clause-function-analysis", misconceptionTargets: ["treat-that-as-roleless-link"] },
    { stem: "The friend that called me left a message. Who called?", options: ["The friend", "The message", "Me", "No one"], answerIndex: 0, reasons: ["that 代替 friend 作 called 的主詞。", "message 是 left 的受詞，不會打電話。", "me 是 called 的受詞。", "called 明確有 that 所代表的動作者。"], reviews: ["主要句說朋友留言，關係子句再指出同一位朋友曾打電話。", "第一項保留人物 that 的合法用途與事件方向。"], cognitiveProcess: ["u24-s164-resolve-friend-as-caller-through-that", "separate-message-and-call-recipient"], representationType: "person-that-event-role", misconceptionTargets: ["reject-person-antecedent-for-that"] },
    { stem: "This is the cake. Ben made it this morning. Which sentence joins the ideas with that?", options: ["This is Ben that made the cake this morning.", "This is the cake that Ben made this morning.", "This that is the cake Ben made it.", "The cake made Ben that morning."], answerIndex: 1, reasons: ["先行詞應是 cake，不是 Ben。", "that 取代 it，Ben 保留為 made 的主詞。", "第三項同時錯置 that 並重複 it。", "第四項顛倒蛋糕與 Ben 的角色。"], reviews: ["兩句共同項目是 the cake 與 it，合併時只取代 it。", "第二項保留 this morning、製作者與被製作物。"], cognitiveProcess: ["u24-s164-join-cake-and-it-with-that", "preserve-maker-object-and-time"], representationType: "that-sentence-combination", misconceptionTargets: ["replace-wrong-shared-noun-or-keep-it"] },
    { stem: "The game that we watched was close. What does that stand for?", options: ["We", "The players", "The game", "The place"], answerIndex: 2, reasons: ["we 已在子句中作 watched 的主詞。", "players 沒有出現在句中。", "that 代替 game 作 watched 的受詞。", "沒有地點名詞可供連結。"], reviews: ["that 雖位於 we 前，仍回指前面的 game。", "第三項可還原成 We watched the game，角色完整。"], cognitiveProcess: ["u24-s164-restore-game-from-object-that", "exclude-relative-subject-and-invented-details"], representationType: "that-object-antecedent-identification", misconceptionTargets: ["mistake-following-subject-for-antecedent"] },
    { stem: "There are four coats. Take the coat ___ has your name inside.", options: ["it", "this", "where", "that"], answerIndex: 3, reasons: ["it 不能在 coat 後開啟限定子句。", "this 會形成不完整的指示結構。", "where 不能作 has 的主詞。", "that 代替 coat 並用姓名辨認目標。"], reviews: ["四件外套使限定資訊成為選擇所必需。", "第四項讓 has your name inside 只描述應拿取的那件。"], cognitiveProcess: ["u24-s164-select-named-coat-with-that", "use-restrictive-information-under-multiple-options"], representationType: "contextual-that-selection", misconceptionTargets: ["drop-relative-link-in-multiple-choice-context"] },
  ]),
  ...skillQuestions("165", [
    { stem: "The boy who found the wallet called us. In 'who found the wallet,' is who the subject or the object?", options: ["It is the subject.", "It is the object.", "It marks the place.", "It marks the time."], answerIndex: 0, reasons: ["who 代替 boy，直接執行 found。", "wallet 才是 found 的受詞。", "關係子句沒有地點標記功能。", "who 也不表示時間。"], reviews: ["who 後沒有另一個主詞，因此它自己填補主詞空位。", "第一項可還原成 The boy found the wallet。"], cognitiveProcess: ["u24-s165-classify-who-as-found-subject", "restore-boy-wallet-base-clause"], representationType: "relative-subject-function", misconceptionTargets: ["assume-who-is-object-because-wallet-follows"] },
    { stem: "The boy who Mia called is here. In 'who Mia called,' is who the subject or the object?", options: ["It is the subject.", "It is the object.", "It is a time word.", "It is Mia's name."], answerIndex: 1, reasons: ["Mia 已作 called 的主詞。", "who 代替被 Mia 打電話的 boy，作受詞。", "句中沒有時間功能。", "who 回指 boy，不改變 Mia 的名字。"], reviews: ["看見 who 後的 Mia，便可判定子句已有動作者。", "第二項可還原成 Mia called the boy，方向不變。"], cognitiveProcess: ["u24-s165-classify-who-as-called-object", "use-explicit-mia-subject-to-find-gap"], representationType: "relative-object-function", misconceptionTargets: ["treat-every-who-as-subject"] },
    { stem: "The song that we heard was beautiful. Can that be left out without changing the meaning?", options: ["No, because song is a thing.", "No, because we is a subject.", "Yes, because that is the object of heard.", "Yes, because every relative word can be left out."], answerIndex: 2, reasons: ["先行詞類型不決定能否省略。", "we 作主詞正是受詞空位仍可理解的條件。", "that 代替 song 作 heard 的受詞，可在此限定句省略。", "主詞關係代名詞不能一律省略。"], reviews: ["省略後成為 The song we heard，we heard 仍留下可連回 song 的受詞位置。", "第三項給出正確結構理由，不是無條件刪字。"], cognitiveProcess: ["u24-s165-test-object-relative-omission", "reject-category-and-universal-omission-rules"], representationType: "object-relative-omission-judgment", misconceptionTargets: ["omit-based-on-antecedent-type"] },
    { stem: "The student who works here is my cousin. Can who be left out?", options: ["Yes, because only one student is named.", "Yes, if here stays.", "Yes, because cousin names the person.", "No, because who is the subject of works."], answerIndex: 3, reasons: ["只談一位學生也不能刪除子句主詞。", "保留 here 也不能補足 works 的主詞。", "主要句的 cousin 不取代關係子句角色。", "who 代替 student 執行 works，不能省略。"], reviews: ["刪除後會把 The student works here 變成主要句並破壞原結構。", "第四項依 who 的主詞功能作判斷。"], cognitiveProcess: ["u24-s165-protect-subject-who-from-omission", "reject-number-place-and-predicate-justifications"], representationType: "subject-relative-nonomission", misconceptionTargets: ["omit-all-relative-pronouns"] },
    { stem: "The people who ___ here help us after school.", options: ["work", "works", "working", "is work"], answerIndex: 0, reasons: ["who 代替複數 people，需接 work。", "works 只配合第三人稱單數。", "working 缺少限定動詞。", "is work 形式不成立，且不合複數。"], reviews: ["當 who 作主詞時，動詞數量由先行詞 people 決定。", "第一項也讓主要句複數 help 與同一群人一致。"], cognitiveProcess: ["u24-s165-agree-subject-who-with-people", "reject-nonfinite-and-singular-forms"], representationType: "relative-subject-agreement-cloze", misconceptionTargets: ["treat-who-as-singular"] },
    { stem: "The person who we ___ every morning works on the second floor.", options: ["helps", "help", "helping", "is help"], answerIndex: 1, reasons: ["helps 會錯把單數 person 當子句主詞。", "we 是 help 的主詞，所以使用原形 help。", "helping 無法單獨作此子句限定動詞。", "is help 不是正確動詞結構。"], reviews: ["who 在 we help 中作受詞，不能控制 help 的數量。", "第二項依真正主詞 we 選形，同時保留 person 為被幫助者。"], cognitiveProcess: ["u24-s165-agree-object-relative-clause-with-we", "separate-antecedent-number-from-clause-subject"], representationType: "object-relative-verb-agreement", misconceptionTargets: ["make-verb-agree-with-object-antecedent"] },
    { stem: "The boy who called Mia waited outside. What happened?", options: ["Mia called the boy.", "Outside called Mia.", "The boy called Mia.", "No call happened."], answerIndex: 2, reasons: ["第一項交換 who 與 Mia 的角色。", "outside 是地點副詞，不能打電話。", "who 代替 boy 作 called 的主詞。", "called 明確表示通話事件。"], reviews: ["who called Mia 可直接還原成 The boy called Mia。", "第三項保留主詞關係代名詞所建立的動作方向。"], cognitiveProcess: ["u24-s165-interpret-who-called-mia-subject", "reject-reversal-location-agent-and-denial"], representationType: "subject-relative-event-paraphrase", misconceptionTargets: ["reverse-subject-relative-action"] },
    { stem: "The boy who Mia called waited outside. What happened?", options: ["The boy called Mia.", "Outside called the boy.", "No one used a phone.", "Mia called the boy."], answerIndex: 3, reasons: ["boy 是 who 所代替的受詞。", "outside 不能執行 called。", "原句明確包含 called。", "Mia 已作子句主詞，who 代替被打電話的 boy。"], reviews: ["只改變 who 與 Mia 的詞序，就會改變誰打給誰。", "第四項還原受詞關係子句時沒有交換角色。"], cognitiveProcess: ["u24-s165-interpret-who-mia-called-object", "contrast-word-order-driven-role-change"], representationType: "object-relative-event-paraphrase", misconceptionTargets: ["read-object-who-as-agent"] },
    { stem: "The bus that ___ here goes to the station.", options: ["stops", "stop", "we take it", "the driver"], answerIndex: 0, reasons: ["that 代替單數 bus 作 stops 的主詞。", "stop 不合單數先行詞。", "we take it 會讓 that 與 it 重複同一受詞。", "the driver 不能在 that 後直接形成完整謂語。"], reviews: ["空格緊接 that，需補上單數子句動詞。", "第一項形成 that stops here，station 仍是主要句目的地。"], cognitiveProcess: ["u24-s165-complete-bus-subject-relative-with-stops", "distinguish-subject-and-object-relative-continuations"], representationType: "subject-relative-continuation-cloze", misconceptionTargets: ["ignore-antecedent-agreement-and-gap-type"] },
    { stem: "The bus that we ___ every day is late.", options: ["takes", "take", "stops", "goes"], answerIndex: 1, reasons: ["takes 不合子句主詞 we。", "we take the bus 還原後角色完整。", "stops 會缺少 we 的合理功能。", "goes 同樣無法接在 we 後。"], reviews: ["that 是 take 的受詞，真正控制動詞的是 we。", "第二項將每日搭乘的公車與主要句 late 正確連接。"], cognitiveProcess: ["u24-s165-complete-bus-object-relative-with-take", "apply-we-agreement-inside-relative-clause"], representationType: "object-relative-continuation-cloze", misconceptionTargets: ["use-singular-verb-from-bus-antecedent"] },
    { stem: "The teacher who the students thanked smiled. Who did the students thank?", options: ["The students", "The time", "The teacher", "Someone else"], answerIndex: 2, reasons: ["students 是執行 thanked 的人。", "who 不提供時間。", "who 代替 teacher，表示學生感謝老師。", "句中沒有另一位被感謝的人。"], reviews: ["還原句為 The students thanked the teacher。", "第三項顯示 who 在 thanked 後填入被感謝者的位置。"], cognitiveProcess: ["u24-s165-identify-teacher-who-as-thanked-object", "preserve-student-subject-in-restoration"], representationType: "embedded-plural-subject-object-relative", misconceptionTargets: ["assign-relative-pronoun-subject-by-position-alone"] },
    { stem: "The book that Amy read was helpful. Which sentence leaves out that and keeps the same meaning?", options: ["The book that read Amy was helpful.", "The book Amy read it was helpful.", "Amy read was the helpful book.", "The book Amy read was helpful."], answerIndex: 3, reasons: ["第一項顛倒 Amy 與 book 的角色。", "省略 that 後又加 it，受詞重複。", "第三項破壞主要句與先行詞結構。", "that 作受詞可省略，Amy read 仍留下 book 的空位。"], reviews: ["縮短只移除受詞關係代名詞，不改動其他詞序。", "第四項仍可還原 Amy read the book，且保留 helpful。"], cognitiveProcess: ["u24-s165-omit-object-that-without-resumptive", "preserve-main-predicate-and-role-order"], representationType: "object-relative-shortening", misconceptionTargets: ["add-it-after-relative-omission"] },
  ]),
  ...skillQuestions("166", [
    { stem: "The woman who she works here is my aunt. Which word should be taken out?", options: ["she", "who", "woman", "here"], answerIndex: 0, reasons: ["who 已代替 woman 作 works 的主詞，she 重複。", "刪 who 會失去連接且留下兩個獨立結構。", "woman 是必要先行詞。", "here 提供工作地點，不造成角色重複。"], reviews: ["主詞型關係代名詞後不可再放同指的 she。", "第一項刪除後得到 The woman who works here。"], cognitiveProcess: ["u24-s166-remove-she-after-subject-who", "protect-antecedent-link-and-place-detail"], representationType: "duplicate-relative-subject-removal", misconceptionTargets: ["add-personal-pronoun-after-subject-relative"] },
    { stem: "This is the bag that I found it on the bus. Which word should be taken out?", options: ["that", "it", "bus", "I"], answerIndex: 1, reasons: ["that 連回 bag 並作 found 的受詞。", "it 與 that 都指 bag，形成重複受詞。", "bus 提供發現地點。", "I 是 found 的必要主詞。"], reviews: ["受詞 that 已占據 I found 後的空位。", "第二項刪除後保留誰找到、找到什麼及在哪裡三項資訊。"], cognitiveProcess: ["u24-s166-remove-it-after-object-that", "retain-finder-location-and-relative-link"], representationType: "duplicate-relative-object-removal", misconceptionTargets: ["keep-resumptive-it-with-that"] },
    { stem: "The song we heard it was new. Which word should be taken out?", options: ["song", "we", "it", "new"], answerIndex: 2, reasons: ["song 是主要句先行詞。", "we 是 heard 的主詞。", "省略 that 後，song 仍填補 heard 的受詞，因此 it 重複。", "new 是主要句的重要描述。"], reviews: ["看不見 that 不代表先行詞與受詞空位的關係消失。", "第三項刪除後形成 The song we heard was new。"], cognitiveProcess: ["u24-s166-remove-it-after-zero-object-relative", "preserve-zero-relative-connection"], representationType: "zero-relative-duplicate-object-repair", misconceptionTargets: ["restore-it-when-that-is-omitted"] },
    { stem: "The boy who he won the game is Ben. Which sentence uses who without he?", options: ["The boy he won the game is Ben.", "Who the boy won the game is Ben.", "The boy who the game won is Ben.", "The boy who won the game is Ben."], answerIndex: 3, reasons: ["第一項刪掉連接詞，he 仍無法形成限定關係。", "第二項顛倒先行詞與 who 的位置。", "第三項把 game 誤寫成動作者。", "who 已代替 boy 作 won 的主詞，不再加 he。"], reviews: ["修正只需刪除與 who 同指的 he，其他角色不動。", "第四項可還原成 The boy won the game。"], cognitiveProcess: ["u24-s166-repair-boy-who-he-won", "preserve-boy-agent-and-game-object"], representationType: "subject-relative-full-sentence-repair", misconceptionTargets: ["delete-relative-link-instead-of-duplicate-pronoun"] },
    { stem: "The book that it is on the desk is mine. Which word repeats the subject of is?", options: ["it", "book", "desk", "mine"], answerIndex: 0, reasons: ["that 已代替 book 作 is 的主詞，it 再次指 book。", "book 是先行詞，不能刪除。", "desk 是位置參照物。", "mine 是主要句的所有關係。"], reviews: ["主詞重複不只發生在人物代名詞，事物 it 也會造成同樣問題。", "第一項移除後，that is on the desk 完整描述 book。"], cognitiveProcess: ["u24-s166-detect-it-duplicate-after-subject-that", "separate-location-and-main-possession"], representationType: "inanimate-duplicate-subject-detection", misconceptionTargets: ["allow-it-after-thing-relative"] },
    { stem: "The girl who Ben knows her is in my class. Which word should go?", options: ["who", "her", "Ben", "class"], answerIndex: 1, reasons: ["who 連回 girl 作 knows 的受詞。", "her 與 who 都指 girl，重複受詞。", "Ben 是 knows 的主詞。", "class 完成主要句地點資訊。"], reviews: ["人物受詞也不能同時使用 who 與 her。", "第二項刪除後可還原為 Ben knows the girl。"], cognitiveProcess: ["u24-s166-remove-her-after-object-who", "retain-ben-as-relative-clause-subject"], representationType: "person-duplicate-object-repair", misconceptionTargets: ["keep-object-pronoun-after-who"] },
    { stem: "The teacher who the students thanked smiled. Which sentence has a repeated object?", options: ["The teacher who thanked the students smiled.", "The students thanked the teacher who smiled.", "The teacher who the students thanked her smiled.", "The teacher thanked the students and smiled."], answerIndex: 2, reasons: ["第一項交換感謝的方向，但沒有重複受詞。", "第二項改寫詞序，teacher 仍只出現一次於 thanked 的受詞位置。", "who 已代替 teacher 作 thanked 的受詞，her 又重複同一人。", "第四項把 teacher 改成感謝學生的人，也沒有重複受詞。"], reviews: ["要找的是同一個受詞在關係代名詞與人稱代名詞中出現兩次。", "第三項同時保留 who 與 her，因此正是要辨認的錯誤。"], cognitiveProcess: ["u24-s166-detect-added-her-after-object-who", "separate-role-change-from-duplicate-object"], representationType: "duplicate-object-error-identification", misconceptionTargets: ["confuse-role-change-with-resumptive-object"] },
    { stem: "The dog that it follows me lives next door. Which sentence takes out the repeated subject without changing who follows and who is followed?", options: ["The dog it follows me lives next door.", "That the dog follows me lives next door.", "The dog that me follows lives next door.", "The dog that follows me lives next door."], answerIndex: 3, reasons: ["第一項缺少關係連接且 it 角色不明。", "第二項沒有正確先行詞結構。", "第三項把 me 放成動作者。", "that 代替 dog 作 follows 的唯一主詞。"], reviews: ["dog 是跟隨者，me 是被跟隨的人，不能為刪重複而交換。", "第四項只移除多餘 it，並保留 next door。"], cognitiveProcess: ["u24-s166-repair-dog-that-it-follows", "maintain-follower-recipient-and-home-location"], representationType: "thing-subject-relative-sentence-repair", misconceptionTargets: ["repair-duplicate-by-role-reversal"] },
    { stem: "A note says, 'Use the phone that I found it by the gate.' Which word makes the note wrong?", options: ["it", "phone", "gate", "found"], answerIndex: 0, reasons: ["that 已代替 phone 作 found 的受詞，it 多出。", "phone 是要使用的目標物。", "gate 提供尋獲地點。", "found 說明如何辨認這支電話。"], reviews: ["公告中的小錯誤仍要依句法角色判斷，不能刪除實用資訊。", "第一項移除後，that I found by the gate 能清楚限定 phone。"], cognitiveProcess: ["u24-s166-proofread-notice-duplicate-it", "retain-operational-object-and-location"], representationType: "notice-relative-error-edit", misconceptionTargets: ["delete-context-detail-instead-of-duplicate"] },
    { stem: "Which words name one song without using the object twice?", options: ["the song that we heard it", "the song we heard", "the song we heard it", "the song that it heard us"], answerIndex: 1, reasons: ["that 與 it 同時作 heard 的受詞。", "省略受詞 that 後，we heard 保留正確空位。", "第三項同樣多放 it。", "第四項顛倒歌曲與人的角色。"], reviews: ["這裡檢查的是受詞只出現一次，不是單純挑最短片語。", "第二項可還原為 We heard the song，且沒有重複代名詞。"], cognitiveProcess: ["u24-s166-select-clean-zero-relative-song-phrase", "reject-overt-and-zero-relative-resumptives"], representationType: "nonrepetitive-relative-phrase-selection", misconceptionTargets: ["equate-omission-with-pronoun-replacement"] },
    { stem: "The players who they practice after school are ready. Which word repeats the same subject as who?", options: ["players", "practice", "they", "ready"], answerIndex: 2, reasons: ["players 是必要先行詞。", "practice 是關係子句動詞。", "who 已代替 players 作主詞，they 重複。", "ready 是主要句補語。"], reviews: ["複數 who 仍然能自己作主詞，不需 they 支援。", "第三項刪除後，practice 與 players 的複數一致。"], cognitiveProcess: ["u24-s166-identify-they-duplicate-after-who", "retain-plural-agreement-and-main-state"], representationType: "plural-duplicate-subject-identification", misconceptionTargets: ["add-they-after-plural-who"] },
    { stem: "The bag Nora brought it is on the chair. Which sentence takes out the repeated object?", options: ["The bag brought Nora is on the chair.", "Nora the bag brought is on the chair.", "The bag Nora brought it on the chair.", "The bag Nora brought is on the chair."], answerIndex: 3, reasons: ["第一項把 bag 寫成動作者。", "第二項詞序無法建立先行詞與主要句。", "第三項仍保留多餘 it，並改變地點。", "省略 that 的 Nora brought 已讓 bag 作受詞。"], reviews: ["修正要同時保留 Nora 帶袋子與袋子在椅子上的兩個事實。", "第四項只刪重複 it，沒有移動其他成分。"], cognitiveProcess: ["u24-s166-repair-zero-relative-bag-brought-it", "preserve-main-location-and-relative-agent"], representationType: "zero-relative-full-sentence-repair", misconceptionTargets: ["move-words-instead-of-removing-extra-object"] },
  ]),
  ...skillQuestions("167", [
    { stem: "I thanked the nurse. She helped my father. Which sentence keeps both facts?", options: ["I thanked the nurse who helped my father.", "I thanked my father who helped the nurse.", "The nurse thanked me because my father helped.", "My father thanked the nurse who I helped."], answerIndex: 0, reasons: ["who 代替 nurse 作 helped 的主詞，兩事實都保留。", "第二項交換 nurse 與 father 的角色。", "原句沒有 nurse 感謝我或 because 關係。", "第四項改成我幫助護士，與原文不同。"], reviews: ["共同人物是 nurse 與 She，合併時應取代 She。", "第一項仍是我感謝護士、護士幫助父親。"], cognitiveProcess: ["u24-s167-join-nurse-she-helper-facts", "lock-thanker-helper-and-recipient-roles"], representationType: "person-subject-relative-combination", misconceptionTargets: ["combine-by-swapping-person-roles"] },
    { stem: "The movie was exciting. We watched it last night. Which sentence joins the ideas?", options: ["We were exciting in the movie last night.", "The movie that we watched last night was exciting.", "The movie watched us because it was exciting.", "Last night that was exciting watched the movie."], answerIndex: 1, reasons: ["exciting 描述 movie，不是 we。", "that 取代 it 作 watched 的受詞，其他資訊不變。", "第三項把 movie 寫成觀看者。", "第四項把時間誤當動作者。"], reviews: ["共同事物是 movie 與 it，we 必須保留為觀看者。", "第二項同時保留 last night 與 exciting。"], cognitiveProcess: ["u24-s167-join-movie-it-object-relative", "preserve-viewer-time-and-description"], representationType: "thing-object-relative-combination", misconceptionTargets: ["turn-antecedent-into-agent-during-merge"] },
    { stem: "The students are from Tainan. They won the game yesterday. Which sentence keeps the place and time?", options: ["Tainan won the students yesterday.", "The game that is from Tainan won yesterday.", "The students who won the game yesterday are from Tainan.", "The students are from the game that Tainan won."], answerIndex: 2, reasons: ["Tainan 是來源地，不是比賽動作者。", "game 不會來自 Tainan，也未被指定為贏家。", "who 取代 They，yesterday 與 from Tainan 都保留。", "第四項混合地點與比賽角色。"], reviews: ["複數 students 同時是 won 的主詞與主要句 are 的主詞。", "第三項沒有遺漏原句的時間或地點條件。"], cognitiveProcess: ["u24-s167-merge-students-they-with-place-time", "retain-two-clause-predicates-and-modifiers"], representationType: "plural-subject-relative-integration", misconceptionTargets: ["attach-place-to-wrong-noun-when-combining"] },
    { stem: "The girl is Nora. She called Ben after school. Which sentence says that Nora called Ben?", options: ["The girl who Ben called after school is Nora.", "Ben is the girl who called Nora after school.", "The girl who called Nora after school is Ben.", "The girl who called Ben after school is Nora."], answerIndex: 3, reasons: ["第一項改成 Ben 打給女孩。", "第二項把 Ben 寫成女孩並交換通話角色。", "第三項把接聽者改成 Nora。", "who 取代 She，所以女孩 Nora 打給 Ben。"], reviews: ["人名很多時，先還原 She called Ben 再進行合併。", "第四項保留 after school 與兩人的原始方向。"], cognitiveProcess: ["u24-s167-combine-nora-she-called-ben", "prevent-name-role-reversal"], representationType: "multi-person-relative-combination", misconceptionTargets: ["lose-pronoun-reference-among-names"] },
    { stem: "This is the book. Amy bought it at the school sale. Which sentence keeps the same object and place?", options: ["This is the book that Amy bought at the school sale.", "This is Amy who the book bought at school.", "The school sale bought the book that is Amy.", "Amy is the book that the school bought."], answerIndex: 0, reasons: ["that 取代 it，Amy 與 sale 地點都保留。", "第二項顛倒 Amy 與 book。", "sale 是活動背景，不能買書。", "第四項把 Amy 等同於書。"], reviews: ["共同項目 the book 與 it 在第二句是受詞。", "第一項只進行必要取代，沒有創造出售者身分。"], cognitiveProcess: ["u24-s167-join-book-it-bought-at-sale", "preserve-buyer-object-and-event-place"], representationType: "object-relative-with-setting-combination", misconceptionTargets: ["turn-setting-into-agent-during-join"] },
    { stem: "I met two students. They did not join the game. Which sentence keeps the number two and the words did not join?", options: ["I met the game that did not join two students.", "I met two students who did not join the game.", "Two students met me and joined the game.", "I did not meet two students who joined the game."], answerIndex: 1, reasons: ["第一項把 game 當主詞並打亂數量。", "who 取代 They，two 與 did not 都保留。", "第三項刪掉否定並改變 met 的方向。", "第四項把否定移到 met，意思不同。"], reviews: ["否定位置會決定哪個事件沒有發生，不能在合併時任意移動。", "第二項完整保存兩位學生與未參加比賽的事實。"], cognitiveProcess: ["u24-s167-preserve-two-students-and-did-not", "keep-negation-on-join-event"], representationType: "quantity-negation-relative-combination", misconceptionTargets: ["drop-or-move-negation-when-merging"] },
    { stem: "The man is my uncle. He works at the post office. Which words join the two ideas without repeating he?", options: ["the man which the post office works", "the uncle where he works", "the man who works at the post office", "the post office who is my uncle"], answerIndex: 2, reasons: ["which 不合人物且詞序錯誤。", "where 不代替人物，he 也重複。", "who 取代 He 並連回 the man。", "post office 不是 uncle，也不用 who。"], reviews: ["兩句共同人物是 the man 與 He，不是工作地點。", "第三項可放入 The man who works at the post office is my uncle。"], cognitiveProcess: ["u24-s167-build-man-who-works-phrase", "separate-person-antecedent-from-workplace"], representationType: "shared-subject-relative-phrase-construction", misconceptionTargets: ["select-location-as-shared-noun"] },
    { stem: "The key is on the desk. Ben found it near the gate. Which sentence keeps the key on the desk and the finding near the gate?", options: ["The key found Ben on the desk near the gate.", "Ben is on the desk that found the key.", "The gate that Ben found is on the key.", "The key that Ben found near the gate is on the desk."], answerIndex: 3, reasons: ["第一項把 key 寫成發現者。", "第二項把 Ben 放到桌上並讓 desk 發現鑰匙。", "第三項改成 Ben 找到 gate。", "that 取代 it，near the gate 修飾 found，on the desk 留在主要句。"], reviews: ["兩個地點分屬不同事件，合併時不能互換。", "第四項保留尋獲地點與目前位置的時間層次。"], cognitiveProcess: ["u24-s167-join-key-it-with-two-locations", "attach-each-location-to-correct-event"], representationType: "multi-location-relative-integration", misconceptionTargets: ["move-modifiers-between-clauses"] },
    { stem: "A bus comes at seven. It goes downtown. Which sentence tells both facts?", options: ["The bus that goes downtown comes at seven.", "Downtown comes at seven on the bus.", "The bus that comes downtown is seven.", "Seven goes downtown by bus."], answerIndex: 0, reasons: ["that 取代 It，路線與時間都保留。", "downtown 不是移動或到達的主體。", "第三項把 seven 寫成 bus 的身分。", "數字 seven 不能搭車前往市區。"], reviews: ["共同項目 bus 與 It 在兩句都作主詞。", "第一項讓讀者同時知道目的地與到站時間。"], cognitiveProcess: ["u24-s167-combine-bus-route-and-arrival-time", "retain-travel-information-for-action"], representationType: "transport-information-relative-merge", misconceptionTargets: ["promote-destination-or-time-to-agent"] },
    { stem: "The dog belongs to Mia. It followed us home. Which sentence keeps the owner and the action?", options: ["Mia who followed the dog belongs to us.", "The dog that followed us home belongs to Mia.", "We belong to the dog that Mia followed home.", "Home belongs to Mia's dog and followed us."], answerIndex: 1, reasons: ["第一項改成 Mia 跟隨狗，且所有關係錯置。", "that 取代 It，dog 仍屬 Mia 並跟隨我們。", "第三項把我們寫成狗的所有物。", "home 是目的地，不能擁有或跟隨。"], reviews: ["It 的指涉由前句唯一的 dog 決定。", "第二項把 followed us home 放在 dog 後，沒有改變 belongs to Mia。"], cognitiveProcess: ["u24-s167-join-dog-it-followed-and-ownership", "preserve-owner-follower-and-destination"], representationType: "animal-relative-reference-combination", misconceptionTargets: ["misresolve-it-and-reverse-ownership"] },
    { stem: "We visited the store. It closed at five that day. Which sentence keeps the visit and closing time?", options: ["Five visited the store that day.", "The store visited us when it closed.", "We visited the store that closed at five that day.", "We closed at five in the store that visited."], answerIndex: 2, reasons: ["five 是時間，不是訪客。", "第二項把 store 寫成拜訪者。", "that 取代 It 作 closed 的主詞，主要句仍是 we visited。", "第四項讓 we 成為關閉的對象並顛倒 visit。"], reviews: ["共同事物 store 與 It 在第二句執行 closed。", "第三項讓 at five that day 只修飾關店事件。"], cognitiveProcess: ["u24-s167-integrate-store-visit-and-closing-time", "separate-visitor-action-from-store-state-change"], representationType: "event-time-relative-combination", misconceptionTargets: ["assign-time-or-place-as-main-agent"] },
    { stem: "I chose the chair. It was near the window and had a red seat. Which sentence keeps all the facts?", options: ["I chose the window that had a chair and a red seat.", "The chair chose me near the red window.", "I chose the red seat that was a window.", "I chose the chair that was near the window and had a red seat."], answerIndex: 3, reasons: ["第一項把 window 誤作選擇目標。", "第二項把 chair 寫成選擇者。", "第三項把 seat 與 window 錯誤等同。", "that 取代 It，位置與座面顏色兩項都保留。"], reviews: ["and 連接的兩個條件都屬於同一張 chair。", "第四項沒有省略用來辨認椅子的任一特徵。"], cognitiveProcess: ["u24-s167-combine-chair-it-with-two-identifiers", "retain-conjoined-relative-predicates"], representationType: "multi-feature-relative-combination", misconceptionTargets: ["drop-or-reattach-one-identifying-detail"] },
  ]),
  ...skillQuestions("168", [
    { stem: "Two bags are by the door. Take the bag that has a blue star. Which bag should be taken?", options: ["The bag with the blue star", "Both bags", "The first bag", "Any bag without a star"], answerIndex: 0, reasons: ["關係子句明確指定有藍星的袋子。", "two bags 是候選範圍，不表示兩個都拿。", "原文沒有交代袋子的順序。", "沒有星星的袋子不符合限定條件。"], reviews: ["that has a blue star 的功能是從兩個候選物中辨認一個。", "第一項只使用明示特徵，沒有自行增加位置條件。"], cognitiveProcess: ["u24-s168-select-blue-star-bag", "reject-all-size-and-opposite-feature-options"], representationType: "single-feature-object-selection", misconceptionTargets: ["ignore-restrictive-feature-under-two-candidates"] },
    { stem: "Students who finished the work may leave. Leo has not finished. May Leo leave under this rule?", options: ["Yes, because Leo is a student.", "No, because he does not meet the rule.", "Yes, because the work is there.", "No, because no student may ever leave."], answerIndex: 1, reasons: ["student 身分不足，還需 finished the work。", "Leo 未完成，因此不在獲准群體內。", "工作存在不等於完成。", "規則允許符合條件的學生離開。"], reviews: ["who finished the work 把全體學生縮小成一個子群。", "第二項套用明示條件，沒有把 may 誇大為永久禁止。"], cognitiveProcess: ["u24-s168-apply-finished-work-condition-to-leo", "separate-group-membership-from-condition-satisfaction"], representationType: "relative-rule-eligibility", misconceptionTargets: ["apply-main-predicate-to-entire-antecedent-class"] },
    { stem: "The bus that stops at Gate 2 goes to the museum. Where should a museum visitor wait?", options: ["At the museum door", "At every gate", "At Gate 2", "At home"], answerIndex: 2, reasons: ["museum 是目的地，不是上車處。", "句子只指定 Gate 2，沒有涵蓋所有 gate。", "that stops at Gate 2 限定前往 museum 的 bus。", "home 與搭車資訊無關。"], reviews: ["關係子句的地點能直接轉成旅客等待位置。", "第三項保留公車與 museum 的連結，不把終點當起點。"], cognitiveProcess: ["u24-s168-infer-museum-bus-waiting-gate", "distinguish-stop-from-destination"], representationType: "travel-action-from-relative-detail", misconceptionTargets: ["confuse-relative-location-with-main-destination"] },
    { stem: "Four cups are on a shelf. Use the cup that is clean and has a handle. Which cup is clean and has a handle?", options: ["A clean cup without a handle", "A cup with a handle that is not clean", "Any cup on the shelf", "A clean cup with a handle"], answerIndex: 3, reasons: ["只符合 clean，缺少 handle。", "只符合 handle，卻違反 clean。", "on the shelf 只是共同位置，無法唯一辨認。", "第四項同時滿足兩個 and 條件。"], reviews: ["複合限定資訊不能只抓到其中一半。", "第四項逐項通過 clean 與 has a handle 的檢查。"], cognitiveProcess: ["u24-s168-intersect-clean-and-handle-cup-conditions", "reject-partial-and-background-matches"], representationType: "conjoined-feature-selection", misconceptionTargets: ["accept-candidate-matching-one-of-two-conditions"] },
    { stem: "People who have tickets may enter the hall. Who is clearly allowed to enter?", options: ["People with tickets", "Everyone near the hall", "People who lost their tickets", "Only the workers"], answerIndex: 0, reasons: ["who have tickets 是明示許可條件。", "地點接近不等於持票。", "遺失票券者不符合 have tickets。", "規則沒有把許可限於 workers。"], reviews: ["主要句 may enter 只套用到關係子句限定的人。", "第一項把 have tickets 轉成同義條件，沒有擴張群體。"], cognitiveProcess: ["u24-s168-identify-ticket-holder-entry-group", "prevent-location-loss-and-worker-overreach"], representationType: "restricted-group-permission", misconceptionTargets: ["generalize-permission-beyond-relative-group"] },
    { stem: "The boy who is wearing a red hat is my brother. Which sentence keeps the meaning?", options: ["Every boy has a red hat.", "The boy in the red hat is the speaker's brother.", "The hat is new.", "The brother likes red more than blue."], answerIndex: 1, reasons: ["關係子句只描述用來辨認的 boy。", "第二項直接改述原句的身分連結。", "帽子新舊沒有被提到。", "顏色喜好是未提供的原因猜測。"], reviews: ["wearing a red hat 是辨識證據，不是所有男孩的共同特徵。", "第二項停在文本能證明的範圍內。"], cognitiveProcess: ["u24-s168-limit-red-hat-inference-to-brother-identity", "reject-universal-age-and-preference-inferences"], representationType: "evidence-bounded-person-identification", misconceptionTargets: ["invent-background-from-identifying-detail"] },
    { stem: "A person needs the bus that stops here and goes to the station. Which bus should the person take?", options: ["The first bus stops here but goes to the park.", "The second bus passes here but does not stop.", "The third bus stops here and goes to the station.", "Every bus on the road."], answerIndex: 2, reasons: ["第一班車符合停靠，目的地卻錯。", "第二班車經過此地，卻不符合 stops here。", "第三班車同時符合停靠與車站方向。", "道路上的公車不一定具備兩條件。"], reviews: ["that 子句中的 and 要求候選車輛通過兩項限制。", "第三項不是因順序，而是完整交集。"], cognitiveProcess: ["u24-s168-match-bus-to-stop-and-destination", "eliminate-one-condition-and-unbounded-candidates"], representationType: "two-condition-transport-selection", misconceptionTargets: ["choose-candidate-with-only-one-relative-condition"] },
    { stem: "Four coats are here. The two coats that are wet are outside. Which sentence says more than the two sentences?", options: ["Two coats are wet.", "The wet coats are outside.", "There are four coats here.", "Every coat is wet."], answerIndex: 3, reasons: ["the two coats that are wet 明示數量為二。", "主要句說這兩件濕外套在外面。", "第一句交代共有四件外套。", "只有兩件被限定為 wet，不能說四件都濕。"], reviews: ["關係子句挑出四件中的兩件，而非替全體加特徵。", "第四項把子群條件錯誤擴張到所有 coats。"], cognitiveProcess: ["u24-s168-separate-two-wet-coats-from-four-total", "detect-universal-overgeneralization"], representationType: "subset-relative-logic", misconceptionTargets: ["spread-relative-property-to-whole-set"] },
    { stem: "The books that are on the table are mine. What can be said about the books on the shelf?", options: ["The sentence does not say who owns them.", "They must also be mine.", "They cannot belong to anyone.", "They are all on the table."], answerIndex: 0, reasons: ["關係子句只限定 table 上的 books，未談 shelf 上的書。", "mine 不能自動擴大到另一位置。", "沒有所有權資訊不等於無人所有。", "shelf 上的書不可能同時因本句變到 table。"], reviews: ["沒有被關係子句涵蓋的對象要保留未知。", "第一項正確區分明示所有權與未提供資訊。"], cognitiveProcess: ["u24-s168-preserve-unknown-ownership-for-shelf-books", "avoid-property-transfer-across-location-groups"], representationType: "unmentioned-group-evidence-boundary", misconceptionTargets: ["extend-main-predicate-to-unmodified-items"] },
    { stem: "Two nurses helped the team. The nurse who called yesterday left a message. Which nurse left it?", options: ["Both nurses", "The nurse who called yesterday", "A nurse who did not call", "The team"], answerIndex: 1, reasons: ["限定句使用單數 the nurse，沒有指兩人。", "who called yesterday 從兩位護士中辨認留言者。", "未打電話者不符合條件。", "team 是受幫助群體，不是 nurse。"], reviews: ["前句建立兩個候選人，後句靠關係子句縮小到一人。", "第二項只選擇具備明示通話特徵的護士。"], cognitiveProcess: ["u24-s168-resolve-message-nurse-among-two", "use-relative-event-as-discriminator"], representationType: "multi-person-context-resolution", misconceptionTargets: ["ignore-relative-clause-after-plural-context"] },
    { stem: "NOTICE: Students who need help may stay after class. Who may clearly stay?", options: ["Every student", "Only students who already went home", "Students who need help", "People who are not students"], answerIndex: 2, reasons: ["關係子句沒有讓所有 students 都留下。", "已回家者不是公告限定群體。", "who need help 明確指定可留下者。", "先行詞 students 排除非學生。"], reviews: ["公告中的關係子句是行動資格，不是可忽略的背景。", "第三項同時符合學生身分與需要協助兩層限制。"], cognitiveProcess: ["u24-s168-apply-help-need-stay-permission", "intersect-antecedent-class-and-relative-condition"], representationType: "notice-eligibility-interpretation", misconceptionTargets: ["delete-relative-condition-from-rule"] },
    { stem: "Three keys are in a box. The key that opens the back door has a green star. Nora needs the back door. Which key should she take?", options: ["Any key without a star", "All three keys", "The first key in the box", "The key with the green star"], answerIndex: 3, reasons: ["沒有 star 的鑰匙不符合唯一辨識線索。", "Nora 只需能開後門的一把。", "順序條件未在原文出現。", "green star 連到能開 back door 的 key。"], reviews: ["先用需要開後門確定功能，再用綠色星號辨認實物。", "第四項串接兩句證據，卻沒有假設其他鑰匙用途。"], cognitiveProcess: ["u24-s168-chain-back-door-key-to-green-star", "reject-quantity-order-and-opposite-feature"], representationType: "cross-sentence-relative-feature-action", misconceptionTargets: ["fail-to-transfer-identifying-feature-to-task"] },
  ]),
];

export const ENGLISH_UNIT_SOURCE = {
  unitId: UNIT_ID,
  lectures: ENGLISH_U24_LECTURES,
  questions: ENGLISH_U24_QUESTIONS,
  vocabularyPolicy: {
    capQuestionBasis: "appendix-5-table-1",
    additionalLearningTerms: ["downtown", "hall", "handle", "message", "neither", "return", "shelf"],
    properNames: ["Amy", "Ben", "Leo", "Mia", "Nora", "Sam", "Tainan"],
    grammarNotation: ["drew", "noun", "object", "sang"],
    malformedDistractors: [],
  },
};
