import { defineChoiceQuestions as questions, defineEnglishUnit } from "../define-unit.mjs";

const skills = [
  {
    id: "ENG_R4_S249", process: "locate-explicit-paraphrase", evidence: "題目關鍵概念與原文同義改寫指向同一資訊",
    objectives: ["從題目圈出人物、動作、對象與限制詞。", "在原文找相同字或同義改寫，不要求逐字一致。", "將定位句與前後一句一起讀，確認答案角色正確。"],
    sections: [
      ["先拆題目關鍵詞", "不要把整個問句拿去逐字搜尋。先圈人物、核心動作與時間或地點限制，例如 How did Mia solve the problem? 可拆成 Mia、solve、problem。"],
      ["預期作者會改寫", "題目中的 buy 可能在原文寫 get、purchase 或 pay for；問題中的 reason 可能由 because、so 或事件結果呈現。找概念相同，不只找相同拼字。"],
      ["定位後讀一個小窗口", "找到關鍵字後，至少讀該句與相鄰一句。代名詞、否定與真正受詞可能在旁邊；只看單一字容易把誰做什麼配錯。"],
      ["以原文證據作答", "答案要能指出原文哪一段支持。若選項只是常識上合理但找不到對應句，就不能當作明示資訊。"],
    ],
    examples: [
      ["Question: How did Leo fix the dark path? Text: He placed small lights beside it.", ["圈 fix 與 dark path。", "原文未重複 fix，而以 placed lights 表示解法。", "核對 it 回指 path。"], "He added lights.", "added lights 是 placed small lights 的等義概括。"],
      ["Question: Why was the trip delayed? Text: Heavy rain kept the bus from leaving.", ["圈 why 與 delayed。", "kept ... from leaving 表示延誤。", "原因是 heavy rain。"], "Because of heavy rain.", "問題與原文以不同字呈現同一因果。"],
      ["Question: Where can visitors leave coats? Text: Use the room next to the front desk.", ["圈 leave coats 與 where。", "原文以 use 指示可放置地點。", "保留完整位置。"], "In the room next to the front desk.", "不能只答 front desk，因原文說的是旁邊房間。"],
    ],
    misconceptions: [
      ["找不到題目原字就表示沒有答案。", "閱讀題常使用同義改寫。", "搜尋概念、角色與因果，而非只比拼字。"],
      ["看到一個相同字就立即選。", "同字可能出現在錯的人物或時間。", "讀定位句前後並核對限制。"],
      ["常識合理就等於原文明示。", "明示題只接受文本證據。", "要求自己指出支持句。"],
      ["題目問 why，只找 because。", "原因也可用 so、結果或事件鏈表達。", "辨認因果功能，不限單一標記詞。"],
    ],
    checks: [
      ["題目寫 purchase，原文寫 buy，能互相定位嗎？", "能", "兩字在此表相同購買行動。"],
      ["定位到關鍵詞後最少還要讀什麼？", "該句前後的小範圍", "用來確認代名詞、否定與角色。"],
      ["明示題可用原文沒有的常識作答嗎？", "不可", "必須有可指出的文本證據。"],
    ],
    questions: questions([
      ["Notice: The east gate is being repaired. Students should enter through the library door this week. Which entrance should students use?", "the library door", "enter through 直接改寫 entrance should use。", [["the east gate", "原文說 east gate 正在修理，不能使用。"], ["the gym window", "原文沒有提 gym window。"], ["the main office", "原文沒有指定 office 為入口。"]]],
      ["Ben wanted the soup to be less salty, so he poured in a cup of water. How did Ben change the soup?", "He added water", "poured in a cup of water 等義於 added water。", [["He added salt", "與 less salty 的目標及原文行動相反。"], ["He bought another bowl", "原文沒有購買。"], ["He served it cold", "原文沒有溫度資訊。"]]],
      ["The club moved its meeting from Tuesday to Thursday because the hall was busy. Why was the meeting moved?", "The hall was in use", "hall was busy 表示場地當時有人使用。", [["Tuesday was a holiday", "原文沒有 holiday。"], ["The club needed a larger hall", "原文只說 busy，沒有大小問題。"], ["Thursday was canceled", "Thursday 是新日期，未被取消。"]]],
      ["Mia left her bike at the shop. The worker replaced the broken chain and called her at noon. What repair did the worker make?", "He put in a new chain", "replaced the broken chain 即換上新鏈條。", [["He fixed the phone", "called her 不等於修 phone。"], ["He painted the bike", "原文沒有 paint。"], ["He changed both wheels", "原文明確是 chain，不是 wheels。"]]],
      ["Library message: Books due on May 8 may be returned by May 10 without an extra charge. What is the last free return date?", "May 10", "by May 10 without an extra charge 直接界定免費期限。", [["May 8", "May 8 是原到期日，不是寬限後最後日期。"], ["May 18", "原文沒有這個日期。"], ["any day in May", "原文明確限制到 May 10。"]]],
      ["Jay could not hear the video well, so he borrowed headphones from the front desk. What helped Jay hear better?", "the borrowed headphones", "borrowed headphones 是針對聽不清楚採取的解法。", [["the front desk itself", "front desk 是借用地點，不是聽聲工具。"], ["a new video", "原文沒有更換 video。"], ["closed captions", "原文未提 captions。"]]],
      ["The morning train was full. Nora waited twenty minutes and took the next one. How did Nora continue her trip?", "She boarded a later train", "took the next one 改寫為 boarded a later train。", [["She walked the whole way", "原文說搭下一班 train。"], ["She entered the full train", "她等待而未搭 morning train。"], ["She ended the trip", "原文明說 continue 並搭車。"]]],
      ["A sign beside the river says, 'Path closed after sunset. Use Green Street instead.' Where should evening walkers go?", "Green Street", "after sunset 的替代路線明示為 Green Street。", [["the closed river path", "該時段 path closed。"], ["Blue Street", "原文沒有 Blue Street。"], ["the river itself", "原文要求 use street，不是進入河中。"]]],
      ["The cafe stopped offering plastic spoons and now gives wooden ones when customers ask. What material are the new spoons made from?", "wood", "wooden ones 指由 wood 製成的新湯匙。", [["plastic", "原文說停止提供 plastic spoons。"], ["glass", "原文沒有 glass。"], ["paper", "原文沒有 paper spoons。"]]],
      ["Leo practiced the difficult part slowly each night. After a week, he could play it without stopping. What shows Leo improved?", "He played the part continuously", "without stopping 改寫為 continuously。", [["He practiced only once", "原文說 each night。"], ["He chose an easier part", "原文仍是 difficult part。"], ["He stopped playing music", "與 could play 相反。"]]],
      ["Town update: The market will open at nine rather than eight during winter. How has the winter opening time changed?", "It is one hour later", "from eight to nine 表示延後一小時。", [["It is one hour earlier", "方向相反。"], ["It is two hours later", "八到九只有一小時。"], ["The market stays closed all winter", "原文仍會開門。"]]],
      ["Amy put the wet poster flat under several books. The next morning it was smooth enough to hang. What did the books do?", "They pressed the poster flat", "poster 在書下變 smooth，表示 books 壓平它。", [["They made the poster wet", "poster 原先已 wet。"], ["They hid the wall", "原文沒有 wall 被遮住。"], ["They added words to the poster", "沒有新增文字。"]]],
    ], { type: "explicit-paraphrase", operation: "match-question-wording-to-source", misconception: "require-exact-word-match" }),
  },
  {
    id: "ENG_R4_S250", process: "scan-proper-nouns-and-numbers", evidence: "人名、數字、日期或地點附近的完整欄位資訊",
    objectives: ["依題目所問類型快速掃讀專有名稱與數字。", "辨認相鄰數字的單位與欄位，不交換日期、價格或時間。", "定位後回讀整列或整句確認限制。"],
    sections: [
      ["先知道要掃什麼", "who 找人名，when 找日期或時間，where 找地點，how much 找價格或數量。先決定資料類型，眼睛才不會被其他數字帶走。"],
      ["數字必須帶單位", "15 可能是日期、年齡、分鐘或價格。掃到數字後，把前後單位與欄名一起讀，不能只抄數字。"],
      ["同列資料不可串錯", "行程表常同時有地點與時間。找到 Green Park 後，要沿同一列讀 departure，不可跳到下一列的時間。"],
      ["最後核對限定詞", "題目可能問 first、last、under 12、after noon。找到資料後再檢查比較或邊界，避免答成最醒目但不符合條件的項目。"],
    ],
    examples: [
      ["List: May 4—Hall A; May 6—Hall B. Where is the May 6 event?", ["掃日期 May 6。", "沿同一項讀地點。", "不取 May 4 的 Hall A。"], "Hall B", "日期與地點保持同項。"],
      ["Prices: child $40; adult $80. How much is one adult ticket?", ["題目鎖定 adult。", "沿該列找 price。", "保留貨幣單位。"], "$80", "$40 是另一類票價。"],
      ["Bus 1: 8:10; Bus 2: 8:35. Which leaves later?", ["掃兩個時間。", "比較小時相同時的分鐘。", "35 晚於 10。"], "Bus 2", "8:35 比 8:10 晚。"],
    ],
    misconceptions: [
      ["看到第一個數字就抄。", "文章可能有多種數值。", "先定位題目欄位與單位。"],
      ["同一表格的資訊可以跨列組合。", "每列通常是一筆完整資料。", "沿同一列或同一項核對。"],
      ["較大的數字一定代表較晚。", "日期、時間與價格需依單位比較。", "先判斷數值類型。"],
      ["掃讀等於不用回讀。", "掃讀只負責定位。", "找到後仍需讀完整欄位與限制。"],
    ],
    checks: [
      ["題目問 where，優先掃哪類資訊？", "地點名稱", "再讀其所在整項。"],
      ["找到 20 後還要檢查什麼？", "單位與欄位", "20 可能代表多種資料。"],
      ["表格中可把 A 列地點配 B 列時間嗎？", "不可", "應維持同一筆資料。"],
    ],
    questions: questions([
      ["Event list: May 12—River Clean-up—East Gate; May 19—Tree Day—City Park. Where is Tree Day?", "City Park", "Tree Day 同項的地點是 City Park。", [["East Gate", "East Gate 屬 May 12 clean-up。"], ["River Clean-up", "這是另一活動名稱。"], ["May 19", "這是日期，不是地點。"]]],
      ["Shop hours: Mon–Fri 9:00–18:00; Sat 10:00–16:00; Sun closed. When does the shop open on Saturday?", "10:00", "Saturday 欄的開門時間為 10:00。", [["9:00", "這是 weekdays 開門時間。"], ["16:00", "這是 Saturday 關門時間。"], ["18:00", "這是 weekdays 關門時間。"]]],
      ["Workshop: Art with Mia, Room 3, 13:30; Maps with Ben, Room 5, 14:10. Who leads the map workshop?", "Ben", "Maps with Ben 直接標示帶領者。", [["Mia", "Mia 帶領 Art。"], ["Room 5", "這是地點。"], ["14:10", "這是時間。"]]],
      ["Ticket prices: ages 6–11, $50; ages 12–17, $70; adults, $100. How much does a 14-year-old pay?", "$70", "14 歲落在 ages 12–17。", [["$50", "只適用 6–11 歲。"], ["$100", "成人票價。"], ["$14", "14 是年齡，不是價格。"]]],
      ["Train board: Coast Line 07:45 Platform 2; Lake Line 08:05 Platform 4. Which platform serves the Lake Line?", "Platform 4", "Lake Line 同列的月台為 4。", [["Platform 2", "屬 Coast Line。"], ["08:05", "這是時間。"], ["07:45", "這是另一班時間。"]]],
      ["Library rooms: Green Room—20 seats; Blue Room—35 seats; Gold Room—12 seats. Which room holds the most people?", "Blue Room", "35 是三者最大座位數。", [["Green Room", "20 少於 35。"], ["Gold Room", "12 最少。"], ["Library Hall", "清單沒有此名稱。"]]],
      ["Delivery note: Nora—12 Pine Road—July 8; Jay—8 Lake Street—July 9. Where should Nora's package go?", "12 Pine Road", "Nora 同列地址為 12 Pine Road。", [["8 Lake Street", "這是 Jay 的地址。"], ["July 8", "這是日期。"], ["July 9", "這是 Jay 的日期。"]]],
      ["Race results: Leo 18:42; Amy 19:05; Sam 18:57. Who finished first?", "Leo", "完成時間最短的 18:42 屬 Leo。", [["Amy", "19:05 比兩個 18 分時間慢。"], ["Sam", "18:57 比 18:42 慢。"], ["all three together", "時間不同。"]]],
      ["Club calendar: Aug 2 practice; Aug 9 no meeting; Aug 16 final show. What happens on August 9?", "There is no meeting", "Aug 9 的項目明示 no meeting。", [["practice", "practice 在 Aug 2。"], ["final show", "final show 在 Aug 16。"], ["a new class", "清單沒有此活動。"]]],
      ["Menu: vegetable soup $45; chicken rice $85; fruit cup $35. Which item is cheapest?", "fruit cup", "$35 低於 $45 與 $85。", [["vegetable soup", "$45 不是最低。"], ["chicken rice", "$85 最高。"], ["rice and soup together", "菜單未列組合價。"]]],
      ["Museum map: Information—first floor; Cafe—second floor; History Hall—third floor. Where is the cafe?", "the second floor", "Cafe 同項明示 second floor。", [["the first floor", "Information 位於此層。"], ["the third floor", "History Hall 位於此層。"], ["outside the museum", "地圖未說在館外。"]]],
      ["Phone list: school office 2345-1000; city library 2345-2200; sports center 2345-3100. Which number reaches the library?", "2345-2200", "city library 同列電話是 2345-2200。", [["2345-1000", "這是 school office。"], ["2345-3100", "這是 sports center。"], ["2345-2000", "清單沒有此號碼。"]]],
    ], { type: "scanning-records", operation: "scan-and-keep-row-alignment", misconception: "take-first-number" }),
  },
  {
    id: "ENG_R4_S251", process: "separate-explicit-from-added-information", evidence: "選項每一部分都能由原文字句直接支持",
    objectives: ["逐詞核對選項是否完全受原文支持。", "辨認合理推測、常識與作者未說的因果。", "排除半真半假的選項。"],
    sections: [
      ["明示等於文本可指出", "正確選項中的人物、動作、時間與程度都應能在文中找到。只要多加一個原文沒有的理由或結果，就不再是純明示。"],
      ["合理不等於有寫", "看到 dark clouds 可以合理猜會下雨，但若原文只說雲變黑，明示答案不能說 rain began。把推論留給 inference 題。"],
      ["小心半真選項", "選項前半可能照抄原文，後半偷偷換時間、增加目的或使用 always。逐段核對，不因熟悉開頭就接受整項。"],
      ["用最小承諾作答", "兩項都看似合理時，選只重述原文、承諾較少者。明示題不需要替作者補空白。"],
    ],
    examples: [
      ["Text: The shop closed at five. Choice: It closed early because workers were tired.", ["closed at five 有支持。", "early 未比較平常時間。", "workers tired 完全未提。"], "The choice adds information.", "一半正確不能救回新增理由。"],
      ["Text: Mia carried an umbrella. Choice: Mia expected rain.", ["有 umbrella。", "沒有 stated expectation。", "屬合理推測。"], "Not explicit.", "帶傘原因需由文中另給證據。"],
      ["Text: The bus arrived at 8:10. Choice: The bus arrived at 8:10.", ["人物相同。", "動作相同。", "時間相同。"], "Explicit.", "每一部分都可直接對應。"],
    ],
    misconceptions: [
      ["符合常識就是明示。", "明示要求文字證據。", "把常識與文本分開。"],
      ["選項有一半照抄就可選。", "另一半可能新增錯誤。", "核對整個選項。"],
      ["比較級可由單一數值推出。", "需要比較基準。", "原文沒有基準就不加 earlier、better 等。"],
      ["作者沒否定就代表肯定。", "未提不等於成立。", "只接受文中說出的內容。"],
    ],
    checks: [
      ["原文未說原因，選項可自行補 because 嗎？", "不可", "新增因果不屬明示。"],
      ["半真半假的選項算正確嗎？", "不算", "所有部分都需有證據。"],
      ["明示題應偏好承諾較多還是較少的選項？", "較少且完整受支持", "避免擴張作者內容。"],
    ],
    questions: questions([
      ["Text: The class will meet in Room 4 at three. Which statement is explicitly given?", "The meeting is at 3:00 in Room 4", "時間與地點都直接出現在原文。", [["Room 4 is the largest room", "原文沒有大小比較。"], ["The meeting was moved because of rain", "沒有改期或原因。"], ["Every class meets there", "原文只談 the class。"]]],
      ["Text: Nora bought two apples and one loaf of bread. Which statement adds no new information?", "Nora bought three items", "two apples 加 one loaf，共三項物品。", [["Nora bought the food for dinner", "用途 dinner 未提。"], ["The bread was fresh", "品質未提。"], ["The apples cost less than the bread", "沒有價格。"]]],
      ["Text: A dog waited beside the closed gate until Ben arrived. What is explicit?", "The dog was by the gate before Ben came", "waited ... until Ben arrived 表示抵達前狗在門旁。", [["Ben owned the dog", "所有關係未提。"], ["The gate was closed because it was late", "closed 有寫，但原因未寫。"], ["The dog waited every day", "只描述一次事件。"]]],
      ["Text: The path is 800 meters long and has three rest areas. Which claim is directly supported?", "There are three places to rest", "three rest areas 是直接改寫。", [["The path is easier than all others", "沒有難度比較。"], ["Each rest area has water", "沒有設備資訊。"], ["Walking it takes exactly eight minutes", "長度不能直接決定時間。"]]],
      ["Text: Mia emailed the form on Monday and received a reply on Wednesday. Which statement is explicit?", "The reply came two days after the email", "Monday 到 Wednesday 相隔兩天。", [["The reply accepted the form", "回覆內容未提。"], ["Mia sent the form late", "沒有期限比較。"], ["She called on Tuesday", "沒有電話行動。"]]],
      ["Text: The cafe offers free water to anyone who orders food. Which statement stays within the text?", "Food customers may get water without paying for it", "free water 與 orders food 的條件完整保留。", [["All drinks are free", "原文只說 water。"], ["People may get water without ordering", "違反 orders food 條件。"], ["The cafe does this to reduce waste", "目的未提。"]]],
      ["Text: Leo wore a blue coat and carried a small black bag. What is explicitly stated?", "Leo's bag was black", "black 直接描述 bag。", [["The coat belonged to Leo's brother", "所有者未提。"], ["The bag was heavier than the coat", "沒有重量比較。"], ["Leo dislikes bright colors", "個人偏好未提。"]]],
      ["Text: The town planted fifty trees last spring; forty-seven are still growing. Which statement is explicit?", "Three of the trees are no longer growing", "50 減 47 得 3，完全由明示數量推出。", [["The three trees died from heat", "原因 heat 未提。"], ["This spring will have more trees", "未提供本春計畫。"], ["The town planted the most trees in the country", "沒有全國比較。"]]],
      ["Text: The final bus leaves at 10:20 p.m. Which claim is stated?", "No later bus is listed after 10:20 p.m.", "final bus 直接表示該服務中最後一班。", [["The bus is always full", "載客量未提。"], ["The driver goes home at 10:30", "司機行程未提。"], ["The bus trip lasts twenty minutes", "10:20 是離站時間，不是時長。"]]],
      ["Text: Amy chose the paper map when her phone battery reached zero. Which statement is explicit?", "Amy used a paper map after her phone lost power", "battery reached zero 改寫為 phone lost power。", [["Paper maps are better in every situation", "一次選擇不能支持 every situation。"], ["Amy forgot to charge the phone on purpose", "原因與意圖未提。"], ["The map was free", "價格未提。"]]],
      ["Text: The museum is closed on Mondays except July 15, when it opens from noon to five. What is explicit?", "The museum is open on Monday, July 15", "except 明確建立該星期一的例外。", [["It opens every Monday in July", "只有 July 15 例外。"], ["July 15 admission is free", "票價未提。"], ["It opens at five on July 15", "five 是關門時間，開門是 noon。"]]],
      ["Text: Sam read the directions twice before starting the test. Which statement adds nothing?", "Sam reviewed the directions before he began", "read twice 可概括為 reviewed，時間關係保留。", [["Sam found the directions difficult", "感受未提。"], ["The teacher told him to read twice", "指示來源未提。"], ["He finished earlier than everyone", "結果比較未提。"]]],
    ], { type: "explicit-versus-added", operation: "verify-every-part-of-choice", misconception: "accept-plausible-addition" }),
  },
  {
    id: "ENG_R4_S252", process: "integrate-separated-details", evidence: "相隔句子分別提供的條件合併後得到唯一答案",
    objectives: ["辨認題目需要的兩個以上資訊欄位。", "回到不同句子收集各部分證據。", "合併時保持人物、時間與條件一致。"],
    sections: [
      ["先列答案需要什麼", "問題若問 Which plan can Mia use on Friday?，至少需要 Mia 的需求、各 plan 日期與限制。把需求拆成欄位，避免找到第一個相關句就停止。"],
      ["用同一角色串線索", "相隔句子可能用 Mia、she、the student 承接同一人。先確認指涉，再合併她的目標與後續條件。"],
      ["交集不是聯集", "答案必須同時符合所有條件。A 選項只合時間、B 只合價格都不夠；找條件集合的交集。"],
      ["標記證據位置", "在草稿寫 C1、C2，分別指出哪一句支持。若某條件找不到來源，表示選項可能加入資訊。"],
    ],
    examples: [
      ["Mia is free after four. The art class starts at 4:30; the music class starts at three.", ["條件一：after four。", "比較兩課開始時間。", "只有 art 符合。"], "the art class", "需合併第一句需求與第二句時刻。"],
      ["Ben needs a room for 25. Room A holds 20. Room B holds 30 but is closed Friday.", ["條件一：25 seats。", "Room A 容量不足。", "若是 Friday，Room B 也不行。"], "Neither room on Friday.", "必須同時合容量與日期。"],
      ["The blue route is shorter. Later the text says bikes are not allowed on it. Nora is riding a bike.", ["短只是優點。", "禁 bike 是硬限制。", "Nora 不能選 blue。"], "not the blue route", "較遠句子的限制推翻局部吸引項。"],
    ],
    misconceptions: [
      ["找到一個符合條件就停止。", "題目可能要求多條件交集。", "列出全部限制再選。"],
      ["相隔句子一定無關。", "代名詞與主題可跨句延續。", "追蹤同一人物或物件。"],
      ["好處可以抵消硬限制。", "closed、must、not allowed 等不能被偏好取代。", "先處理必要條件。"],
      ["可把不同人的條件混在一起。", "會產生原文沒有的角色。", "每條證據標註所屬人物。"],
    ],
    checks: [
      ["多條件題應找聯集還是交集？", "交集", "答案需同時滿足所有條件。"],
      ["容量足夠但當天 closed，能選嗎？", "不能", "日期限制仍未通過。"],
      ["合併前要先確認什麼？", "線索屬於同一角色或對象", "避免跨人物錯配。"],
    ],
    questions: questions([
      ["Nora needs a room after 5:00 for twenty people. Room A holds 25 but closes at 5:00. Room B holds 20 and stays open until 7:00. Which room works?", "Room B", "Room B 同時合容量二十與五點後開放。", [["Room A", "容量足夠但五點關閉。"], ["both rooms", "Room A 不合時間。"], ["neither room", "Room B 完全符合。"]]],
      ["Jay has $60 and wants a plant that can live in low light. The fern costs $55 and needs little light. The rose costs $45 and needs full sun. What can Jay buy for his room?", "the fern", "fern 同時低於預算且符合低光需求。", [["the rose", "價格可行但需要 full sun。"], ["both plants", "合計超過 $60，且 rose 環境不合。"], ["neither plant", "fern 符合兩條件。"]]],
      ["The trip is on Saturday. Mia cannot leave before nine. Bus 1 leaves at 8:30 on Saturday; Bus 2 leaves at 9:20 but runs only Monday to Friday. Which bus can she take?", "neither bus", "Bus 1 太早；Bus 2 星期六不行。", [["Bus 1", "違反 cannot leave before nine。"], ["Bus 2", "時間可行但服務日不含 Saturday。"], ["both buses", "兩班各違反一條硬限制。"]]],
      ["A coat drive accepts clean coats through November 20. Leo washed his coat on November 18 and brought it on November 19. Is it accepted?", "Yes, it is clean and arrives before the deadline", "兩句分別證明 clean 與 deadline 前送達。", [["No, it was washed too early", "沒有最早清洗限制。"], ["No, the drive ended November 18", "期限是 November 20。"], ["Yes, because every kind of clothing is accepted", "原文只說 coats，理由擴張。"]]],
      ["The Green Path allows bikes but is closed after sunset. The River Path stays open late but does not allow bikes. Sam is cycling home at 8 p.m. Which path fits both facts?", "neither path", "Green 在夜間 closed；River 禁 bikes。", [["Green Path", "bike 可行但 after sunset 關閉。"], ["River Path", "時間可行但 cycling 不允許。"], ["both paths", "各有一項衝突。"]]],
      ["Amy wants a workshop for beginners on July 6. Clay Art is for beginners on July 6. Photo Walk is on July 6 but requires experience. Which should she choose?", "Clay Art", "日期與 beginner level 皆符合。", [["Photo Walk", "日期合但 requires experience。"], ["both workshops", "Photo Walk 不合程度。"], ["no workshop", "Clay Art 明確符合。"]]],
      ["The cafe coupon is valid after 2 p.m. and only for drinks. Nora orders tea at 3 p.m. and a sandwich. What can the coupon cover?", "the tea", "tea 是 drink 且時間在兩點後。", [["the sandwich", "不是 drink。"], ["both items", "coupon 只限 drinks。"], ["nothing", "tea 符合時間與品項。"]]],
      ["A museum room holds twelve visitors. A school group has ten students and three adults. The rule counts everyone in the room. Can the whole group enter together?", "No, the group has thirteen people", "10 加 3 為 13，超過容量 12。", [["Yes, only students count", "規則說 everyone。"], ["Yes, thirteen is under twelve", "數值比較錯誤。"], ["No, because adults may never enter", "成人可進，只是總數超量。"]]],
      ["The library lends games for seven days. Jay borrowed one on March 1 and the library was closed March 8. A note says returns due on closed days move to the next open day, March 9. When may he return it?", "March 9", "原到期日遇 closed day，規則移到 next open day。", [["March 1", "這是借出日。"], ["March 8 only", "當天 library closed 且有延期規則。"], ["any day in April", "延長只到 March 9。"]]],
      ["Mia needs a train arriving before noon. Coast Train arrives 11:50 but does not run Sundays. Lake Train runs Sunday and arrives 12:10. Her trip is Sunday. Which train meets both needs?", "neither train", "Coast 不在 Sunday 運行；Lake 晚於 noon。", [["Coast Train", "時間合但日期不合。"], ["Lake Train", "日期合但 12:10 超過 noon。"], ["both trains", "兩者各失敗一條件。"]]],
      ["A volunteer task requires age 15 or older and availability Saturday morning. Ben is 16 but works Saturday morning. Eva is 14 and is free then. Who qualifies?", "neither Ben nor Eva", "Ben 時間不合；Eva 年齡不足。", [["Ben", "年齡合但不可用 Saturday morning。"], ["Eva", "時間合但未滿 15。"], ["both", "兩人各缺一條件。"]]],
      ["The recipe needs two cups of flour and one egg. Nora has three cups of flour but no eggs. The store is already closed. Can she make it now?", "No, she lacks an egg", "麵粉足夠，但必要 egg 缺少且無法購買。", [["Yes, extra flour replaces the egg", "不同材料不能由規則推定互換。"], ["Yes, the store is closed", "closed 使補材料更不可能。"], ["No, she lacks flour", "她有 3 cups，高於所需 2。"]]],
    ], { type: "separated-detail-integration", operation: "intersect-multiple-constraints", misconception: "stop-after-one-matching-detail" }),
  },
  {
    id: "ENG_R4_S253", process: "verify-list-constraints", evidence: "清單每一欄與題目限制逐項核對後全部通過",
    objectives: ["將清單項目轉成固定欄位比較。", "先套用硬限制，再比較偏好。", "在多個候選中保留同時符合全部條件者。"],
    sections: [
      ["把題目變成檢查表", "例如 under $100、after 4、for beginners 各是一欄。每個選項逐欄打勾或叉，不要靠整體印象。"],
      ["硬限制先處理", "must、only、closed、not allowed 先篩掉不合者；cheaper、closer、preferred 等偏好只在剩餘候選中比較。"],
      ["邊界字要精確", "under 12 不含 12，by Friday 通常含 Friday，after 3 不含正好 3。將邊界寫成簡單比較可防止直覺誤判。"],
      ["允許答案是無或多個", "若題目問 Which options，可能不只一個；若問 Which one，仍可能由資料得出 none。不要為了湊一項而放寬限制。"],
    ],
    examples: [
      ["Need: under $50, open Sunday. A: $45 closed Sunday. B: $55 open Sunday.", ["A 價格合但日期不合。", "B 日期合但價格不合。", "沒有交集。"], "Neither", "不能把兩項各自的優點拼成一個候選。"],
      ["Rule: age under 12. Leo is 12.", ["under 表嚴格小於。", "12 不小於 12。", "排除。"], "Leo does not qualify.", "under 12 不等於 12 or under。"],
      ["Need: 20 seats, projector. Room A: 25/no projector. Room B: 20/projector.", ["先檢查容量。", "再檢查設備。", "B 兩欄皆合。"], "Room B", "A 的容量優勢不能抵消設備缺少。"],
    ],
    misconceptions: [
      ["候選符合大部分條件就可以。", "硬限制要求全部通過。", "逐欄核對交集。"],
      ["under 與 at most 相同。", "at most 含邊界，under 不含。", "將字詞改成數學比較。"],
      ["較便宜一定優先。", "便宜不能抵消日期或功能不合。", "先硬限制、後偏好。"],
      ["清單題一定有一個答案。", "資料可能顯示 none 或 multiple。", "忠於檢查結果。"],
    ],
    checks: [
      ["by May 5 通常包含 May 5 嗎？", "包含", "它表示不晚於該日。"],
      ["符合三項中的兩項可通過 must 條件嗎？", "不可", "must 條件需全部符合。"],
      ["偏好應在何時比較？", "硬限制篩選後", "先確保候選可行。"],
    ],
    questions: questions([
      ["Need: a room for at least 30 people with a screen. Cedar: 35, screen yes. Pine: 40, screen no. Lake: 25, screen yes. Which room works?", "Cedar", "35≥30 且有 screen。", [["Pine", "容量合但沒有 screen。"], ["Lake", "有 screen 但 25 不足 30。"], ["Pine and Lake", "兩者各缺一硬條件。"]]],
      ["Rule: children under 10 enter free. Ages: Mia 9, Ben 10, Leo 11. Who enters free?", "Mia only", "9 小於 10；10 與 11 都不小於 10。", [["Ben only", "under 10 不含正好 10。"], ["Mia and Ben", "Ben 位於不含的邊界。"], ["all three", "Ben、Leo 都不合。"]]],
      ["Need: class after 4 p.m., beginner level. Art: 4:30 beginner. Music: 5:00 advanced. Dance: 3:30 beginner. Which class fits?", "Art", "時間 4:30 在四點後且 beginner。", [["Music", "時間合但 advanced。"], ["Dance", "程度合但 3:30 太早。"], ["Music and Dance", "各缺一條件。"]]],
      ["Coupon: valid Monday–Thursday for orders of $100 or more. Orders: Mon $90; Wed $120; Fri $150. Which order qualifies?", "Wednesday's $120 order", "Wednesday 在日期範圍且 120≥100。", [["Monday's $90 order", "日期合但金額不足。"], ["Friday's $150 order", "金額合但 Friday 不在範圍。"], ["all orders", "兩筆各有不合條件。"]]],
      ["Trail rules: Blue—bikes yes, dogs no; Green—bikes no, dogs yes; Red—bikes yes, dogs yes. Sam has a bike and a dog. Which trail may he use?", "Red", "Red 同時允許 bikes 與 dogs。", [["Blue", "dogs no。"], ["Green", "bikes no。"], ["Blue or Green", "兩條各缺一允許。"]]],
      ["Need: a meal without meat, under $80. Salad $70 no meat; soup $60 contains chicken; rice $85 no meat. What works?", "the salad", "無肉且 $70 低於 $80。", [["the soup", "價格合但 contains chicken。"], ["the rice", "無肉但 $85 不低於 $80。"], ["soup and rice", "各違反一條件。"]]],
      ["Delivery choices: A arrives Tue $90; B arrives Mon $120; C arrives Mon $100. Need arrival by Monday and price at most $100. Which choice?", "C", "Monday 符合 by Monday，$100 符合 at most 100。", [["A", "價格合但 Tuesday 太晚。"], ["B", "日期合但 $120 超標。"], ["A and B", "各缺一條件。"]]],
      ["Library rule: borrow at most three books and return within 14 days. Jay takes three for 14 days; Mia takes four for 10 days. Who follows both rules?", "Jay only", "three 與 14 都包含在 at most/within 邊界。", [["Mia only", "四本超過三本上限。"], ["both", "Mia 不合數量。"], ["neither", "Jay 兩條都合。"]]],
      ["Volunteer list: Nora—Saturday yes, age 16; Ben—Saturday no, age 18; Eva—Saturday yes, age 14. Need Saturday and age 15+. Who qualifies?", "Nora", "Nora 可用 Saturday 且 16≥15。", [["Ben", "年齡合但 Saturday no。"], ["Eva", "時間合但 14 不足。"], ["Ben and Eva", "兩人各缺一條件。"]]],
      ["Phone plans: Light—5 GB $300; Plus—10 GB $450; Max—20 GB $700. Need at least 10 GB under $500. Which plan works?", "Plus", "10 GB 達下限且 $450 低於 $500。", [["Light", "價格合但只有 5 GB。"], ["Max", "資料量合但 $700 超標。"], ["Light and Max", "各缺一條件。"]]],
      ["Museum tours: 10:00 Chinese; 11:30 English; 14:00 English. Mia arrives noon and needs English. Which tour can she join?", "the 14:00 tour", "只有 14:00 同時在 noon 後且 English。", [["10:00", "太早且語言不合。"], ["11:30", "語言合但她尚未抵達。"], ["both English tours", "11:30 在抵達前。"]]],
      ["Contest rules: form by June 1, work under 500 words. Entry A: May 31, 480 words. Entry B: June 1, 520 words. Entry C: June 2, 450 words. Which entry qualifies?", "Entry A", "日期在期限內且 480<500。", [["Entry B", "日期合但 520 不 under 500。"], ["Entry C", "字數合但日期太晚。"], ["B and C", "兩者各違反一條件。"]]],
    ], { type: "constraint-list", operation: "apply-all-list-constraints", misconception: "accept-most-conditions" }),
  },
  {
    id: "ENG_R4_S254", process: "answer-event-sequence", evidence: "時間標記、代名詞與必要動作建立的事件先後",
    objectives: ["依 first、after、before、then、finally 建立事件線。", "沒有時間詞時使用必要條件判斷先後。", "回答 before、after、next 等問題時保持參考事件正確。"],
    sections: [
      ["先找時間路標", "first、then、later、after、before、finally 是直接路標。將事件寫成簡短動作並排入時間線。"],
      ["用必要條件補空白", "沒有路標時，open the box 必須先於 take out the key；arrive at the stop 先於 board the bus。問哪件事要先成立。"],
      ["參考點不能換", "What happened after the call? 要以 call 為中心找下一事件，不是找全文最後一件事。before/after 的方向要在草稿畫箭頭。"],
      ["區分同時與接著", "while 表同時，after 表後續。若兩人同時做事，不能硬排成一前一後；只依文本提供的關係。"],
    ],
    examples: [
      ["Nora washed the cups. After they dried, she put them away.", ["wash 先。", "dry 在 after 子句。", "put away 最後。"], "She put them away after they dried.", "回答 next 時不可跳回 washing。"],
      ["The bus arrived. Ben got on and found a seat.", ["公車先抵達。", "之後才能上車。", "上車後找座位。"], "arrive → board → find a seat", "現實必要條件補足未寫 then 的順序。"],
      ["While Mia read the map, Leo checked the signs.", ["while 表同時。", "兩人動作並行。", "不能宣稱其中一人先完成。"], "The actions happened at the same time.", "文本未提供先後。"],
    ],
    misconceptions: [
      ["段落最後一句就是 next 的答案。", "next 取決於題目參考事件。", "在時間線上找緊接一格。"],
      ["沒有 then 就沒有順序。", "事件必要條件也能排序。", "問哪一步必須先成立。"],
      ["while 表先後。", "while 通常表示同時。", "除非另有時間線索，不硬排。"],
      ["after A, B 表 B 在 A 前。", "after 引出較早參考事件，主要事件在後。", "畫 A → B。"],
    ],
    checks: [
      ["after the show, we ate 中誰先？", "the show", "吃飯發生在表演後。"],
      ["while 連接的動作可直接判先後嗎？", "通常不可", "它表同時進行。"],
      ["next 題應找全文最後還是參考事件下一步？", "參考事件下一步", "保持問題中心。"],
    ],
    questions: questions([
      ["First, Mia cut the paper. Then she folded it. Finally, she wrote a name on it. What happened after the paper was cut?", "Mia folded it", "then 直接標示 cut 後的下一步。", [["She wrote a name", "這是 finally 的較後一步，不是緊接。"], ["She bought the paper", "原文沒有購買。"], ["She cut it again", "原文只說 first cut。"]]],
      ["Ben reached the stop at 7:50. The bus came five minutes later, and he got on. What happened immediately before Ben boarded?", "The bus arrived", "必須先 bus came 才能 get on。", [["Ben reached home", "原文沒有到家。"], ["The bus left", "上車前文說 bus came，不是 left。"], ["It became 7:50 again", "7:50 是較早到站時間。"]]],
      ["Nora checked the weather before packing her bag. After packing, she called Jay. What did she do last?", "She called Jay", "call 明示在 packing 後，且 packing 在 checking 後。", [["She checked the weather", "這是第一步。"], ["She packed her bag", "在 call 之前。"], ["She met Jay", "只有 called，沒有 met。"]]],
      ["While Leo washed the vegetables, Amy heated the soup. What can be said about the two actions?", "They happened at the same time", "while 表兩動作同時。", [["Leo finished first", "沒有完成先後。"], ["Amy began after Leo stopped", "與 while 的重疊關係不合。"], ["Neither action happened", "原文明示兩者進行。"]]],
      ["The light turned green. The cars moved, and then walkers crossed after the cars had turned. What happened next after the light changed?", "The cars moved", "光變綠後第一個事件是 cars moved。", [["Walkers crossed", "這是 cars turned 後的較晚事件。"], ["The light stayed red", "與 turned green 相反。"], ["Everyone went home", "原文沒有。"]]],
      ["Jay opened the email, read the new time, and changed his calendar. What did he do just before changing the calendar?", "He read the new time", "列舉順序中 read 緊接在 changed 前。", [["He sent the email", "原文是 opened，不是 sent。"], ["He closed the calendar", "原文沒有 close。"], ["He changed the meeting time himself", "他只讀到 new time 並更新 calendar。"]]],
      ["After the rain stopped, the workers dried the seats. They opened the gate when the seats were ready. What allowed the gate to open?", "The seats had been dried", "when the seats were ready 承接 workers dried seats。", [["The rain began", "順序是 rain stopped。"], ["Visitors painted the gate", "原文沒有。"], ["The workers removed the seats", "他們 dried 而非 removed。"]]],
      ["Eva paid for the ticket online. A code arrived by email, which she showed at the door. What happened between payment and entry?", "Eva received a code", "code arrived 位於 paid 與 showed at door 之間。", [["She lost the ticket", "原文沒有遺失。"], ["She entered before paying", "順序相反。"], ["She printed a paper map", "原文沒有 map。"]]],
      ["Sam planted a seed on Monday. He watered it each morning. Two weeks later, a leaf appeared. What happened over the two weeks before the leaf appeared?", "Sam watered the seed regularly", "each morning 描述種下後到出葉前的持續行動。", [["He planted a new seed each day", "只在 Monday planted one seed。"], ["The leaf appeared before Monday", "順序相反。"], ["He stopped all care", "與 watered each morning 相反。"]]],
      ["The guide gave a safety talk. Next, visitors put on helmets. Only then did the bike tour begin. What directly preceded the tour?", "Visitors put on helmets", "only then 把 tour 放在戴 helmet 後。", [["The safety talk", "較早但不是直接前一步。"], ["Visitors removed helmets", "原文是 put on。"], ["The tour ended", "題目問 begin 前。"]]],
      ["Mia found a wallet under a chair. She asked the cafe worker for help, and together they called the owner. What did Mia do before calling the owner?", "She asked the worker for help", "ask worker 位於 found 與 called 之間，直接先於 call。", [["She gave the wallet to the owner", "後續歸還未寫。"], ["She left the cafe", "原文沒有。"], ["She called before finding it", "順序相反。"]]],
      ["At noon, the team tested the model. It failed, so they changed one part. The second test worked at three. What happened between the two tests?", "The team changed a part", "失敗後、第二測試前明示 changed one part。", [["They built a different team", "changed 的是 part。"], ["The first test worked", "原文說 failed。"], ["They waited until the next day", "第二次在同日 three。"]]],
    ], { type: "event-sequence", operation: "locate-relative-event-order", misconception: "choose-final-event-instead-of-next" }),
  },
];

export const ENGLISH_UNIT_SOURCE = defineEnglishUnit({
  unitId: "ENG_R4_U37",
  skills,
  vocabularyPolicy: {
    capQuestionBasis: "appendix-5-table-1",
    additionalLearningTerms: ["accept", "add", "adult", "beginner", "board", "calendar", "cancel", "charge", "coast", "continue", "customer", "direct", "direction", "entrance", "event", "extra", "final", "fit", "flat", "flour", "form", "gold", "guide", "hall", "improve", "information", "lack", "leaf", "loaf", "message", "model", "neither", "none", "nor", "path", "platform", "plus", "print", "purpose", "rather", "receive", "regular", "repair", "result", "return", "review", "safety", "serve", "solve", "state", "support", "waste", "weekday", "wheel", "whole", "wood"],
    contextualizedAboveRangeTerms: ["admission", "advanced", "arrival", "availability", "battery", "cafe", "caption", "chain", "claim", "clay", "clothing", "code", "contain", "contest", "continuous", "coupon", "cycle", "deadline", "delay", "delivery", "departure", "dislike", "due", "email", "entry", "exact", "expectation", "explicit", "fern", "fold", "headphone", "helmet", "immediate", "inference", "instead", "largest", "material", "multiple", "online", "option", "payment", "plastic", "pour", "precede", "prefer", "press", "projector", "purchase", "qualify", "recipe", "reduce", "remove", "replace", "reply", "require", "route", "salty", "situation", "smooth", "statement", "sunset", "task", "text", "tour", "trail", "update", "valid", "volunteer", "within", "wooden", "workshop"],
    properNames: ["Amy", "Ben", "Cedar", "Eva", "Jay", "Leo", "Max", "Mia", "Nora", "Pine", "Sam"],
    grammarNotation: ["A", "B", "C", "C1", "C2", "Aug", "Fri", "GB", "Mon", "Tue", "Wed"],
    malformedDistractors: [],
  },
});
