const UNIT_ID = "ENG_R4_U17";

function lecture(id, skillId, content) {
  return { id, skillId, ...content, sections: content.sections.map((section, index) => ({ id: `${id}_SEC_${String(index + 1).padStart(2, "0")}`, ...section })) };
}

const DIFFICULTIES = ["foundation", "foundation", "foundation", "standard", "standard", "standard", "standard", "advanced", "advanced", "advanced", "transfer", "transfer"];

function skillQuestions(skillNumber, values) {
  if (values.length !== 12) throw new Error(`ENG_R4_S${skillNumber}: expected 12 authored questions`);
  return values.map((value, index) => ({ id: `ENG_R4_Q_${skillNumber}_${String(index + 1).padStart(2, "0")}`, skillId: `ENG_R4_S${skillNumber}`, difficulty: DIFFICULTIES[index], ...value }));
}

export const ENGLISH_U17_LECTURES = [
  lecture("ENG_R4_L_S113", "ENG_R4_S113", {
    objectives: ["依名詞在句中的位置辨認主詞、受詞與補語功能。", "用動詞與介系詞判斷名詞和句中其他成分的關係。"],
    sections: [
      { title: "動詞前的名詞常是主詞", content: "The nurse opened the window. 中 the nurse 位於主要動詞 opened 前，指出執行開窗動作的人，所以是主詞。不能只因 window 是具體物品就把它當主詞；句法功能要看它和動詞的關係。" },
      { title: "及物動詞後的名詞可作受詞", content: "The nurse opened the window. 中 the window 承受 opened 的動作，是受詞。判斷時可問『誰做動作』與『動作影響誰或什麼』；同一個名詞換到別句，功能也可能改變。" },
      { title: "be 動詞後可用名詞說明身分", content: "Mia is the team leader. 中 the team leader 不是動作受詞，而是補充 Mia 的身分。be 動詞連接主詞和後方說明；若後面是形容詞，如 Mia is careful，則後方也不是名詞受詞。" },
      { title: "介系詞後的名詞屬於介系詞片語", content: "We waited at the gate. 中 the gate 接在介系詞 at 後，構成 at the gate。它不是 waited 的直接受詞。遇到 for、with、from、to、near 等詞，先確認後方名詞是否由介系詞帶出。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S113_EX_01", prompt: "The dog followed Ben. Which noun is the subject?", steps: ["找主要動詞 followed。", "查看動詞前誰執行跟隨。", "確認 the dog 是動作者。"], answer: "The dog", why: "followed 前的 the dog 執行跟隨動作，因此是主詞；Ben 位於及物動詞後，是被跟隨的受詞，不能因為是人名就判成主詞。" },
      { id: "ENG_R4_L_S113_EX_02", prompt: "Grace became the class leader. What is the function of 'the class leader'?", steps: ["辨認 became 表示身分變化。", "確認後方名詞說明 Grace。", "判定為主詞補語。"], answer: "It shows Grace's new role.", why: "the class leader 說明 Grace 成為什麼身分，並未承受一個外加動作，所以它是補充主詞身分的名詞，不是一般動作受詞。" },
      { id: "ENG_R4_L_S113_EX_03", prompt: "We left the bags near the door. Which noun follows a preposition?", steps: ["找介系詞 near。", "查看 near 後的名詞片語。", "選出 the door。"], answer: "the door", why: "near 是介系詞，後面的 the door 組成地點片語 near the door。the bags 則直接跟在 left 後，兩個名詞在句中的功能不同。" },
    ],
    misconceptions: [
      { belief: "句中第一個名詞一定是主詞。", whyWrong: "時間或地點片語可能先出現，真正主詞仍由主要動詞關係決定。", correction: "先找主要動詞，再問誰執行或處於該狀態。" },
      { belief: "動詞後的每個名詞都是直接受詞。", whyWrong: "be 動詞後可說明身分，介系詞後也有自己的受詞。", correction: "先分辨動詞類型與名詞前是否有介系詞。" },
      { belief: "人一定作主詞，物一定作受詞。", whyWrong: "The ball hit Ben 中 ball 是主詞，Ben 是受詞。", correction: "依句法位置與動作方向判定，不依人物類別。" },
      { belief: "同一個名詞在所有句子中功能固定。", whyWrong: "Mia called Ben 與 Ben called Mia 中兩個人名的功能互換。", correction: "每次都以該句的動詞與位置重新分析。" },
    ],
    checks: [
      { prompt: "The students carried the chairs 中誰是動作者？", answer: "the students", reason: "它位於 carried 前並執行動作。" },
      { prompt: "Leo is my cousin 中 my cousin 是受詞嗎？", answer: "不是", reason: "它在 be 動詞後說明 Leo 的身分。" },
      { prompt: "We met at the park 中 the park 跟在哪個詞後？", answer: "at", reason: "它是介系詞片語的一部分。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S114", "ENG_R4_S114", {
    objectives: ["用適當人稱代名詞取代已明確出現的名詞。", "依主詞或受詞位置選擇 he、him、they、them、it 等形式。"],
    sections: [
      { title: "重複主詞可改用主格代名詞", content: "Mia found the key. She put it on the table. 第二句用 she 代替 Mia，讀者仍能知道動作者。單數男性常用 he，複數人物或事物用 they，單數物品或動物在未特別說明性別時常用 it。" },
      { title: "受詞位置使用受格形式", content: "I saw Ben and called him. 中 Ben 在第二個動作後改成 him，不寫 he。常見對應為 I/me、he/him、she/her、we/us、they/them；you 與 it 的主格和受格外形相同。" },
      { title: "代名詞要保留原名詞的單複數與類別", content: "The books are new. They are on the desk. 不能用 it 取代 books。若前文是 the book，則可用 it。先確認要省略的是一人、一物或一組，再選代名詞。" },
      { title: "只有指涉清楚時才省略重複名詞", content: "Nora spoke to Mia, and she smiled. 若沒有其他線索，she 可能指 Nora 或 Mia。代名詞雖能減少重複，卻不能犧牲清楚度；必要時重複人名比勉強使用 she 更好。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S114_EX_01", prompt: "Jack opened the box. ___ found a note inside. (He / Him / It)", steps: ["第二句缺主詞。", "代替 Jack 需男性單數主格。", "選擇 He。"], answer: "He", why: "空格位於 found 前，是第二句主詞；Jack 是男性單數，因此使用 He。Him 只能作受詞，It 會錯指前句的 box。" },
      { id: "ENG_R4_L_S114_EX_02", prompt: "I met Amy and gave ___ the book. (she / her / it)", steps: ["gave 後需要接受物品的人。", "代替 Amy 且位於受詞位置。", "使用 her。"], answer: "her", why: "Amy 是收到書的人，代名詞放在 gave 後作受詞，所以用 her。she 是主格；it 會指物品，無法表示把書交給 Amy。" },
      { id: "ENG_R4_L_S114_EX_03", prompt: "The chairs are wet. Please move ___. (it / them / they)", steps: ["move 後缺受詞。", "chairs 是複數物品。", "選擇複數受格 them。"], answer: "them", why: "要移動的是複數 chairs，而且代名詞在 move 後作受詞，因此用 them。it 是單數，they 雖為複數卻是主格。" },
    ],
    misconceptions: [
      { belief: "只要代替男性人名，he 和 him 可以互換。", whyWrong: "he 作主詞，him 作動詞或介系詞後的受詞。", correction: "用空格在句中的位置決定格位。" },
      { belief: "所有非人的名詞都用 it。", whyWrong: "複數物品要依位置使用 they 或 them。", correction: "先檢查單複數，再判斷主格或受格。" },
      { belief: "使用代名詞一定比重複名詞好。", whyWrong: "兩個可能先行詞會讓 he、she 或 it 的指向不明。", correction: "有歧義時保留必要的人名或名詞。" },
      { belief: "動詞後看到人就仍使用 she 或 he。", whyWrong: "動詞直接影響的人通常位於受詞位置。", correction: "例如 called her、helped him、saw them。" },
    ],
    checks: [
      { prompt: "Mia is here. ___ is waiting 中應用 she 還是 her？", answer: "she", reason: "空格作 is waiting 的主詞。" },
      { prompt: "I thanked Ben. 中 Ben 可換成什麼？", answer: "him", reason: "Ben 位於 thanked 後作受詞。" },
      { prompt: "the windows 作 move 的受詞時用什麼？", answer: "them", reason: "windows 是複數，且空格為受詞。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S115", "ENG_R4_S115", {
    objectives: ["依人稱、單複數、句法與語意追蹤人稱代名詞。", "用前後事件判定 he、she、it、they、him、her、them 的先行詞。"],
    sections: [
      { title: "先用單複數與人或物縮小範圍", content: "The boys found a dog. They gave it water. 中 they 只能承接複數 boys，it 則承接單數 dog。這些形式線索通常是第一步，但若仍有兩個符合者，還要讀事件關係。" },
      { title: "主格與受格顯示代名詞在新句的角色", content: "Amy called Nora because she needed help. she 是 needed 的主詞，但光靠主格仍不能確定是 Amy 或 Nora。相反地，Amy called Nora and thanked her 中 her 是 thanked 的受詞，語意較可能承接 Nora。" },
      { title: "動作順序與常識只能在文字支持時使用", content: "Leo put the ice in the cup because it was hot. it 最自然指 cup；若寫 because it was getting smaller，則較可能指 ice。判讀應以形容詞或動作能合理描述哪個名詞為依據，不可只選最近的名詞。" },
      { title: "無法唯一判定時要承認資訊不足", content: "Ben told Jack that he won. 中 he 可指 Ben 或 Jack，句子本身沒有唯一答案。考題若要求判定，必須另有前文、動作結果或身分線索；沒有線索時，正確分析是指涉不清。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S115_EX_01", prompt: "The girls tried to get on two buses, but they were full. What does 'they' refer to?", steps: ["they 可承接複數名詞。", "full 說明為何無法上車。", "選擇 two buses。"], answer: "the two buses", why: "girls 與 buses 都是複數，但 full 在此說明公車沒有空位，正好解釋女孩為何無法上車，因此 they 指 two buses。" },
      { id: "ENG_R4_L_S115_EX_02", prompt: "Mia washed the cup and put it away. What does 'it' replace?", steps: ["it 需要單數事物先行詞。", "washed 的受詞是 the cup。", "put away 延續處理同一物品。"], answer: "the cup", why: "the cup 是前句唯一單數物品，也是 Mia 洗完後會收起的東西，所以 it 明確承接 the cup，而不是承接人物 Mia。" },
      { id: "ENG_R4_L_S115_EX_03", prompt: "Ben told Jack that he won. Who won?", steps: ["列出 Ben 與 Jack 兩個男性人名。", "he 可在形式上承接任何一人。", "確認句中沒有額外線索。"], answer: "The sentence does not say clearly.", why: "Ben 和 Jack 都符合單數男性 he，that 子句也未提供比賽角色或結果線索，因此不能武斷選最近的 Jack 或較前面的 Ben。" },
    ],
    misconceptions: [
      { belief: "代名詞一定指前面最近的名詞。", whyWrong: "最近名詞可能在單複數或語意上不合。", correction: "同時檢查形式、句法與事件關係。" },
      { belief: "看到 they 就一定指人。", whyWrong: "they 也能代替複數物品、動物或地點。", correction: "從先行詞數量與後續敘述判斷。" },
      { belief: "常識覺得合理就能補出文章沒說的指涉。", whyWrong: "兩個候選者都合理時，文字仍可能有歧義。", correction: "只有明確語法或內容線索才可排除候選者。" },
      { belief: "he 或 she 出現後，同段所有相同代名詞都指同一人。", whyWrong: "主詞可能在不同句子間轉換。", correction: "每次出現都重新核對最近事件與角色。" },
    ],
    checks: [
      { prompt: "The cats chased a bird, but it went over the wall 中 it 指什麼？", answer: "a bird", reason: "it 是單數，且越過牆的是鳥。" },
      { prompt: "Amy met Nora after she called 中 she 一定指誰嗎？", answer: "不一定", reason: "兩位女性人名都符合 she，句子缺少線索。" },
      { prompt: "The keys were wet, so I dried them 中 them 指什麼？", answer: "the keys", reason: "複數受格與被擦乾的物品一致。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S116", "ENG_R4_S116", {
    objectives: ["辨認 this、that、these、those 所承接的名詞或前文事件。", "依單複數、距離與篇章關係判斷指示代名詞。"],
    sections: [
      { title: "this 與 that 可單獨代替單數事物", content: "This is my bag. 與 That belongs to Leo. 中 this、that 本身作代名詞。一般而言 this 指較近事物，that 指較遠事物；若後面直接接名詞，如 this bag，它們則限定該名詞。" },
      { title: "these 與 those 承接複數名詞", content: "These are fresh, but those are old. 兩個字都需承接複數事物。不能用 this 代替 books，也不能用 those 代替單一 chair；動詞 are 也會提供複數線索。" },
      { title: "this 或 that 也可指前面整件事", content: "The bus left early. This made us late. 中 This 不是只代替 bus，而是指公車提早離開這整件事。若後句談前一事件造成的結果，應把指涉範圍擴到整個命題。" },
      { title: "選擇指示詞仍要靠明確情境", content: "Here are two shirts. This one is clean, but that one near the door is wet. 距離詞 here、near me、over there 可幫助判斷。若沒有距離或前文線索，不能自行斷定 this 與 that 的對象。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S116_EX_01", prompt: "The road was closed. This made the trip longer. What does 'This' mean?", steps: ["找 This 前的完整資訊。", "確認 made the trip longer 的原因。", "承接道路封閉這件事。"], answer: "the fact that the road was closed", why: "讓行程變長的是道路封閉這整個情況，不是 road 這個名詞本身。This 在此承接前句事件，形成原因與結果。" },
      { id: "ENG_R4_L_S116_EX_02", prompt: "I like the shoes by me, but ___ over there are too large. (that / those / this)", steps: ["空格後用 are。", "代替複數 shoes。", "over there 表示較遠，選 those。"], answer: "those", why: "shoes 與 are 都要求複數，over there 又指較遠位置，因此用 those。that 與 this 都是單數，無法配合 are。" },
      { id: "ENG_R4_L_S116_EX_03", prompt: "Please take this cup. ___ on the high shelf is mine. (That / These / Those)", steps: ["後句動詞是 is。", "承接單數 cup。", "high shelf 表示較遠，選 That。"], answer: "That", why: "is 與 cup 都是單數線索，而高架上的杯子離說話者較遠，所以 That 最合適。These、Those 需要複數名詞與 are。" },
    ],
    misconceptions: [
      { belief: "This 永遠只代替前一個名詞。", whyWrong: "This 也能承接前面整個事件或想法。", correction: "查看後句是在描述物品，還是在說前事造成的結果。" },
      { belief: "that 與 those 只差距離，不差單複數。", whyWrong: "that 是單數，those 是複數。", correction: "先配合名詞與動詞數量，再看距離。" },
      { belief: "看到 are 就可以隨意選 these 或 those。", whyWrong: "兩者還需靠近遠情境或對照線索區分。", correction: "尋找 here、near、over there 等位置資訊。" },
      { belief: "指示代名詞後一定要再重複名詞。", whyWrong: "This is mine 中 This 已可獨立作主詞。", correction: "區分 this book 的限定用法與 This is... 的代名詞用法。" },
    ],
    checks: [
      { prompt: "those 搭配 is 還是 are？", answer: "are", reason: "those 承接複數名詞。" },
      { prompt: "The rain stopped. This helped us. 中 This 指什麼？", answer: "雨停這件事", reason: "後句說的是前一事件帶來幫助。" },
      { prompt: "單數且較遠的物品用哪個指示代名詞？", answer: "that", reason: "that 同時表單數與較遠。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S117", "ENG_R4_S117", {
    objectives: ["用 one 或 ones 代替前文已知的可數名詞。", "依單複數與修飾語判斷 one、ones 所指對象。"],
    sections: [
      { title: "one 代替單數可數名詞", content: "This bag is heavy. I need a lighter one. 中 one 代替 bag，避免重複 a lighter bag。one 必須能承接單數可數名詞；water、music 等不可數名詞通常不以 one 直接代替。" },
      { title: "ones 代替複數可數名詞", content: "The red shoes are small. Try the black ones. 中 ones 代替 shoes。前面的 the black 提供選擇條件，而複數形式 ones 與 shoes 一致。" },
      { title: "修飾語幫助找出被替代的名詞", content: "I like the chair by the window, not the one near the door. one 前後的 the、形容詞或介系詞片語用來辨認哪一個同類物品。不能只看到 one 就解成數字一。" },
      { title: "one 與 it 的功能不同", content: "I lost my pen and found it. 中 it 指原來那一枝筆；I lost my pen and bought a new one. 中 one 指同類但不同的一枝筆。判斷時要問後句談的是原物，還是另一個同類物。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S117_EX_01", prompt: "This chair is broken. Please bring another ___. (one / ones / it)", steps: ["another 表示另一個同類物。", "chair 是單數可數名詞。", "選擇 one。"], answer: "one", why: "需要的是另一張椅子，不是原本壞掉的那張，所以用 one 代替單數 chair。ones 為複數，it 則會指回原椅子。" },
      { id: "ENG_R4_L_S117_EX_02", prompt: "The large plates are wet. Use the small ___. (one / ones / them)", steps: ["small 前有 the，可形成名詞片語。", "要代替複數 plates。", "使用 ones。"], answer: "ones", why: "large plates 是複數，另一組 small plates 也要用複數替代詞，因此是 the small ones。one 數量不合；them 不能直接接在 the small 後。" },
      { id: "ENG_R4_L_S117_EX_03", prompt: "I found my lost key and put ___ in my bag. (it / one / ones)", steps: ["後句仍指同一把 key。", "空格作 put 的受詞。", "使用 it 而非 one。"], answer: "it", why: "找到後放進包包的是原本遺失的同一把鑰匙，所以使用 it。one 會變成另一把同類鑰匙，改變事件內容。" },
    ],
    misconceptions: [
      { belief: "one 在任何句子裡都表示數字一。", whyWrong: "它也可代替前文單數可數名詞。", correction: "查看前文是否已出現同類名詞與修飾語。" },
      { belief: "one 與 ones 可以不看單複數互換。", whyWrong: "one 承接單數，ones 承接複數。", correction: "用 a、another、these、those 或動詞形式確認數量。" },
      { belief: "one 和 it 都能指原來同一件物品。", whyWrong: "one 常指另一個同類物，it 指已知的同一物。", correction: "比較 replace the item 與 continue with the same item。" },
      { belief: "不可數名詞後也能直接用 a new one。", whyWrong: "one 需要可單獨計數的名詞先行詞。", correction: "不可數物質須改用適當量詞或重述名詞。" },
    ],
    checks: [
      { prompt: "two blue shirts 可用 one 還是 ones 代替 shirts？", answer: "ones", reason: "shirts 是複數可數名詞。" },
      { prompt: "I fixed the bike and used it to go home 中 it 是同一台嗎？", answer: "是", reason: "it 指前文已知的原物。" },
      { prompt: "a cheaper one 中 one 通常承接哪類名詞？", answer: "單數可數名詞", reason: "a 與 cheaper 共同修飾一個同類物。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S118", "ENG_R4_S118", {
    objectives: ["讓代名詞與先行詞在單複數及人、物語意上保持一致。", "檢查主格、受格與指示形式是否符合句中角色。"],
    sections: [
      { title: "單數先行詞配單數代名詞", content: "The camera is new. It works well. 中 camera 是單數物品，所以用 it。若前文是 cameras，則改用 they。單複數不一致會讓讀者誤以為後句換了對象。" },
      { title: "複數先行詞依位置選 they 或 them", content: "The players arrived. They were early. 主詞位置用 they；The coach thanked them. 受詞位置用 them。數量一致只是第一步，還要確認新句中的句法位置。" },
      { title: "人與物的代名詞不能任意互換", content: "Nora found a phone and returned it to Ben. it 指 phone，him 才能在需要時代替 Ben。判斷人或物時要以先行詞實際所指為準，不只看哪個名詞較近。" },
      { title: "整段指涉要保持同一條線", content: "The book has three maps. They are useful. 中 they 指 maps，不是單數 book。讀到後句形容詞或動作時，要重新核對哪個候選先行詞在數量與語意上都合理。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S118_EX_01", prompt: "The window is open. Please close ___. (it / them / they)", steps: ["window 是單數物品。", "空格位於 close 後作受詞。", "選擇 it。"], answer: "it", why: "the window 是單數，且代名詞在 close 後作受詞，所以 it 同時符合數量與位置。them 是複數，they 是主格。" },
      { id: "ENG_R4_L_S118_EX_02", prompt: "The girls found the tickets. ___ put them in a bag. (She / They / It)", steps: ["第二句缺動作主詞。", "執行 put 的是複數 girls。", "選擇 They。"], answer: "They", why: "the girls 是複數人物，第二句又需要主格，因此使用 They。She 只指一人，It 則不指複數人物。" },
      { id: "ENG_R4_L_S118_EX_03", prompt: "Mia spoke to the boys and gave ___ a map. (they / them / it)", steps: ["得到 map 的是 the boys。", "代名詞位於 gave 後。", "使用複數受格 them。"], answer: "them", why: "the boys 是複數人物，且在 gave 後作接受者，所以用 them。they 是主格，it 會錯指單數物品。" },
    ],
    misconceptions: [
      { belief: "先行詞是複數就一律用 they。", whyWrong: "受詞位置需使用 them。", correction: "先決定數量，再決定主格或受格。" },
      { belief: "距離最近的名詞可忽略單複數直接承接。", whyWrong: "代名詞形式必須和真正先行詞一致。", correction: "用動作與描述排除數量或類別不合者。" },
      { belief: "it 可以代替任何未知性別的人。", whyWrong: "一般人物應依語境使用 he、she、they 或重複名詞。", correction: "不要把指人的名詞當成物品代名詞。" },
      { belief: "一段文字選定 they 後就不必再檢查。", whyWrong: "後面可能出現另一個複數先行詞。", correction: "每次出現代名詞都核對當下句意。" },
    ],
    checks: [
      { prompt: "the bags 作 carry 的受詞時用 they 還是 them？", answer: "them", reason: "複數受詞使用 them。" },
      { prompt: "a bird 在下一句作主詞時可用什麼？", answer: "it", reason: "單數動物在未說明性別時可用 it。" },
      { prompt: "Mia and Nora 在新句作主詞時用什麼？", answer: "they", reason: "兩人組成複數人物主詞。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S119", "ENG_R4_S119", {
    objectives: ["辨認可能同時指向兩個先行詞的模糊代名詞。", "以重複關鍵名詞或改寫句子排除兩種解讀。"],
    sections: [
      { title: "兩個符合形式的先行詞會造成歧義", content: "Amy called Nora when she arrived. 中 she 可指 Amy，也可指 Nora。兩人都是單數女性，句子沒有說誰抵達。不能因較靠近 Nora 就自動判定，因為英文代名詞並沒有永遠指最近名詞的規則。" },
      { title: "用具名主詞寫出真正意思", content: "若意思是 Amy 抵達後打電話，可寫 Amy called Nora when Amy arrived.；若是 Nora 抵達，則重複 Nora。必要的名詞重複不是壞文筆，而是避免錯誤理解。" },
      { title: "改變句構也能消除模糊", content: "After arriving, Amy called Nora. 明確讓 arriving 的執行者是 Amy。也可拆成兩句：Nora arrived. Then Amy called her.。改寫時必須保留原事件順序，不可為了清楚而改變事實。" },
      { title: "有充分內容線索時才可保留代名詞", content: "The glass fell from the table, and it broke. 中 broke 合理承接 glass，指涉清楚。若兩個單數物品都可能破裂，如 The cup hit the plate, and it broke，則需說 the cup 或 the plate。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S119_EX_01", prompt: "Ben told Jack that he had won. Is 'he' clear?", steps: ["找出 Ben 與 Jack。", "確認兩者都可由 he 代替。", "檢查是否有勝者線索。"], answer: "No. It may mean Ben or Jack.", why: "Ben 和 Jack 都是單數男性，句中又沒有比賽角色或其他事件線索，所以 he 有兩種合理指向，不能假定是最近的 Jack。" },
      { id: "ENG_R4_L_S119_EX_02", prompt: "Amy called Nora after Amy arrived. Who arrived?", steps: ["after 子句直接寫 Amy。", "不需猜測 she 的先行詞。", "判定 Amy 抵達。"], answer: "Amy", why: "從句明確重複 Amy，因此抵達者只有 Amy。這個重複排除了 Nora arrived 的第二種解讀，也保留先抵達再打電話的順序。" },
      { id: "ENG_R4_L_S119_EX_03", prompt: "The cup hit the plate, and it broke. How can the writer make the meaning clear?", steps: ["列出 cup 與 plate 兩個單數物品。", "確認兩者都可能破裂。", "用真正破裂的名詞取代 it。"], answer: "Write either 'the cup broke' or 'the plate broke' to fit the event.", why: "it 在形式與常識上都可能承接 cup 或 plate。作者必須依實際事件寫出 the cup 或 the plate，不能只換另一個同樣模糊的代名詞。" },
    ],
    misconceptions: [
      { belief: "代名詞總是指前面最近的同類名詞。", whyWrong: "句法、篇章主題或事件關係都可能指向較早名詞。", correction: "若兩個候選都合理，就判定句子需要改寫。" },
      { belief: "重複人名一定是不好的英文。", whyWrong: "為排除歧義而重複關鍵名詞能提升清楚度。", correction: "在可能誤解的位置保留必要名詞。" },
      { belief: "只要讀者大概猜得到就算指涉清楚。", whyWrong: "考題與實用訊息都要求唯一可支持的解讀。", correction: "檢查是否仍有第二個符合形式與語意的先行詞。" },
      { belief: "把模糊句拆成兩句一定不會改變意思。", whyWrong: "若事件順序或主詞安排改錯，內容仍會變質。", correction: "改寫後逐項核對誰、何時、做了什麼。" },
    ],
    checks: [
      { prompt: "Mia thanked Amy because she helped 中 she 清楚嗎？", answer: "不清楚", reason: "兩位女性都可能是幫助者。" },
      { prompt: "The phone rang, so I answered it 中 it 清楚嗎？", answer: "清楚", reason: "只有 phone 是可被接聽的單數先行詞。" },
      { prompt: "消除 he 的兩種解讀時最直接的方法是什麼？", answer: "寫出真正的人名", reason: "具名主詞可排除另一候選者。" },
    ], assets: [],
  }),
];

export const ENGLISH_U17_QUESTIONS = [
  ...skillQuestions("113", [
    { stem: "The nurse opened the window. Which words name the person who opened it?", options: ["The nurse", "the window", "opened", "the nurse opened"], answerIndex: 0, reasons: ["The nurse 位於 opened 前，也是執行開窗的人。", "the window 承受 opened 的動作。", "opened 是動詞，不是名詞主詞。", "the nurse opened 包含主詞與動詞，不只是一個名詞片語。"], reviews: ["誰執行 opened，就由哪個名詞片語作主詞。", "第一項精確選出動作者，沒有把動詞一起算入。"], cognitiveProcess: ["locate-opener-before-opened", "isolate-subject-noun-phrase"], representationType: "noun-subject-identification", misconceptionTargets: ["choose-object-because-it-is-concrete"] },
    { stem: "Sam carried the bags upstairs. What is the job of 'the bags' in this sentence?", options: ["They tell who carried something.", "They name what Sam carried.", "They tell where Sam went.", "They describe how Sam moved."], answerIndex: 1, reasons: ["執行 carried 的人是 Sam，不是 bags。", "the bags 是 carried 影響的事物，作動詞受詞。", "upstairs 才提供移動方向，bags 不表示地點。", "the bags 是名詞片語，沒有描述動作方式。"], reviews: ["可用『Sam 搬了什麼』找到 the bags。", "第二項說明受詞功能，而非只背誦它在動詞後。"], cognitiveProcess: ["ask-what-sam-carried", "classify-bags-as-action-object"], representationType: "noun-object-function", misconceptionTargets: ["call-every-postverb-word-a-place"] },
    { stem: "Mia is the team captain. What does 'the team captain' do in the sentence?", options: ["It receives an action from Mia.", "It tells where Mia is.", "It shows Mia's role.", "It names a second person beside Mia."], answerIndex: 2, reasons: ["is 不表示 Mia 對 captain 做動作。", "the team captain 是身分，不是地點。", "be 動詞把 Mia 與她的隊長身分連接。", "此名詞片語和 Mia 指同一個人，不是另一人。"], reviews: ["is 在這裡連接主詞與身分說明。", "第三項保留 Mia 和 captain 指同一人的關係。"], cognitiveProcess: ["read-is-as-identity-link", "classify-captain-as-subject-description"], representationType: "noun-complement-role", misconceptionTargets: ["treat-be-complement-as-action-object"] },
    { stem: "We waited near the gate. Which words form the place phrase after 'near'?", options: ["We waited", "waited near", "near the", "the gate"], answerIndex: 3, reasons: ["We waited 是主詞加動詞，不是 near 的後接名詞。", "waited near 包含動詞與介系詞，仍缺地點名詞。", "near the 只有介系詞與限定詞，片語尚未完整。", "the gate 接在 near 後，合成 near the gate。"], reviews: ["介系詞 near 需要後方名詞片語完成地點關係。", "第四項只選出 near 所帶出的名詞部分。"], cognitiveProcess: ["segment-near-prepositional-phrase", "select-gate-as-preposition-object"], representationType: "preposition-noun-function", misconceptionTargets: ["label-gate-as-direct-object-of-waited"] },
    { stem: "After lunch, the students visited the museum. Who visited the museum?", options: ["the students", "lunch", "the museum", "After lunch"], answerIndex: 0, reasons: ["the students 位於 visited 前並執行參觀。", "lunch 位於時間片語中，不執行 visited。", "the museum 是參觀的地點與受詞。", "After lunch 表示時間，不是人物。"], reviews: ["句首時間片語不會自動成為主詞。", "第一項由動詞關係而非句中第一個名詞決定。"], cognitiveProcess: ["ignore-leading-time-phrase", "identify-visitors-as-subject"], representationType: "subject-after-fronted-phrase", misconceptionTargets: ["take-first-noun-lunch-as-subject"] },
    { stem: "The ball hit the window. Which noun receives the action 'hit'?", options: ["The ball", "the window", "hit", "the ball hit"], answerIndex: 1, reasons: ["The ball 是造成撞擊的主詞。", "the window 是被球撞到的對象。", "hit 是動詞，不能作此題的名詞答案。", "the ball hit 包含動作者和動作，未指出承受者。"], reviews: ["人或物都能作主詞，也都可能作受詞。", "第二項以動作方向確認 window，而不是依生物與否判斷。"], cognitiveProcess: ["trace-impact-from-ball-to-window", "name-window-as-receiver"], representationType: "action-direction-object", misconceptionTargets: ["assume-object-must-be-person"] },
    { stem: "Leo became a doctor last year. What does 'a doctor' tell us?", options: ["What Leo carried", "Where Leo worked", "What role Leo took", "When Leo changed jobs"], answerIndex: 2, reasons: ["became 不表示搬運 doctor。", "a doctor 是職業身分，不是工作地點。", "a doctor 說明 Leo 成為的身分。", "last year 才回答時間，a doctor 不回答何時。"], reviews: ["became 後的名詞用來補充主詞的新身分。", "第三項沒有把時間片語的功能混入。"], cognitiveProcess: ["separate-role-from-time-after-became", "interpret-doctor-as-new-identity"], representationType: "linking-verb-noun-complement", misconceptionTargets: ["classify-doctor-as-direct-object"] },
    { stem: "Grace spoke with Nora after class. Which name is part of the phrase beginning with 'with'?", options: ["Grace", "class", "Grace and Nora", "Nora"], answerIndex: 3, reasons: ["Grace 是 spoke 的主詞，不在 with 後。", "class 接在 after 後，屬於另一個片語。", "Grace and Nora 並未一起出現在 with 後。", "Nora 直接接在 with 後，形成 with Nora。"], reviews: ["一句可同時有 with Nora 與 after class 兩個介系詞片語。", "第四項依實際位置鎖定 with 的後接名詞。"], cognitiveProcess: ["distinguish-two-prepositional-phrases", "attach-nora-to-with"], representationType: "multiple-preposition-analysis", misconceptionTargets: ["merge-subject-into-with-phrase"] },
    { stem: "In which sentence is 'the book' the subject?", options: ["The book fell from the shelf.", "Mia opened the book.", "I put a note in the book.", "The cover of the book is blue."], answerIndex: 0, reasons: ["the book 位於 fell 前，是發生掉落的主詞。", "the book 在 opened 後承受動作。", "the book 接在介系詞 in 後。", "the book 接在 of 後，整句主詞核心是 cover。"], reviews: ["同一名詞 the book 在不同句子可有不同功能。", "第一項唯一讓完整片語 the book 直接作主要動詞的主詞。"], cognitiveProcess: ["compare-book-functions-across-sentences", "select-book-as-fell-subject"], representationType: "same-noun-role-comparison", misconceptionTargets: ["assume-repeated-noun-keeps-one-role"] },
    { stem: "In which line is 'Ben' the person receiving the action?", options: ["Ben called Amy.", "Amy called Ben.", "Ben is Amy's cousin.", "Amy spoke with Ben."], answerIndex: 1, reasons: ["Ben 在 called 前，是打電話的人。", "Ben 在 called 後，是 Amy 打電話的對象。", "Ben 是 be 動詞前的主詞，cousin 說明身分。", "Ben 接在 with 後，不是 spoke 的直接受詞。"], reviews: ["題目要求 receiving the action，需找 called 作用到誰。", "第二項把 Ben 放在及物動詞後，功能最明確。"], cognitiveProcess: ["contrast-ben-before-and-after-called", "exclude-prepositional-ben"], representationType: "person-object-selection", misconceptionTargets: ["choose-ben-as-subject-because-name-first"] },
    { stem: "The dog followed Mia. Later, Mia washed the dog. How does the job of 'the dog' change?", options: ["It is a place in both sentences.", "It is an object in both sentences.", "It is first a subject, then an object.", "It is first an object, then a subject."], answerIndex: 2, reasons: ["the dog 不是地點名詞片語。", "第一句中 the dog 位於 followed 前，不是受詞。", "先由 dog 執行 follow，後由 Mia 對 dog 執行 wash。", "第四項把兩句的動作方向完全顛倒。"], reviews: ["先分別問每句誰做動作，再比較功能。", "第三項證明名詞本身不會把句法角色固定住。"], cognitiveProcess: ["track-dog-role-across-two-actions", "order-subject-then-object"], representationType: "cross-sentence-noun-role-shift", misconceptionTargets: ["freeze-dog-as-one-grammatical-role"] },
    { stem: "A club notice says, 'The library is our meeting place.' What is the job of 'our meeting place'?", options: ["It tells when the club meets.", "It names an action done to the library.", "It tells who owns the library.", "It shows the library's role for the club."], answerIndex: 3, reasons: ["名詞片語沒有提供日期或時間。", "is 是連接身分與用途，不是施加動作。", "our 表示團體關係，但整個片語重點不是所有權。", "be 動詞後的 meeting place 說明圖書館對社團的用途。"], reviews: ["實用公告中的 is 仍可用相同句法方法分析。", "第四項連結 library 與 meeting place，沒有添入未說明的會面時間。"], cognitiveProcess: ["analyze-notice-identity-clause", "interpret-meeting-place-as-library-role"], representationType: "notice-noun-complement-transfer", misconceptionTargets: ["read-our-as-main-function"] },
  ]),
  ...skillQuestions("114", [
    { stem: "Jack opened the box. ___ found a note inside.", options: ["He", "Him", "It", "Them"], answerIndex: 0, reasons: ["He 作第二句主詞並承接男性單數 Jack。", "Him 是受格，不能直接放在 found 前作主詞。", "It 會較自然地指 box，而 box 不能 find a note。", "Them 是複數受格，數量與位置都不合。"], reviews: ["空格執行 found，必須使用主格代名詞。", "第一項同時保留 Jack 的人稱與單數。"], cognitiveProcess: ["replace-jack-as-second-sentence-subject", "choose-masculine-singular-subject-form"], representationType: "subject-pronoun-cloze", misconceptionTargets: ["use-him-as-subject"] },
    { stem: "I met Amy at the gate and gave ___ the map.", options: ["she", "her", "it", "they"], answerIndex: 1, reasons: ["she 是主格，不能作 gave 的接受者。", "her 位於 gave 後作受詞並代替 Amy。", "it 會把接受者誤成物品。", "they 是複數主格，無法承接單數 Amy。"], reviews: ["give someone something 中 someone 位於受詞位置。", "第二項避免重複 Amy，也不改變誰收到地圖。"], cognitiveProcess: ["map-amy-to-recipient-position", "select-her-after-gave"], representationType: "person-object-pronoun-cloze", misconceptionTargets: ["retain-she-after-verb"] },
    { stem: "The chairs are wet. Please move ___.", options: ["it", "they", "them", "her"], answerIndex: 2, reasons: ["it 是單數，不能代替 chairs。", "they 是複數主格，不能作 move 的直接受詞。", "them 是複數受格，正確承接 chairs。", "her 指單數女性人物，語意不合。"], reviews: ["chairs 提供複數線索，move 後提供受詞線索。", "第三項同時符合數量、類別與格位。"], cognitiveProcess: ["combine-chair-plural-with-object-position", "choose-them-for-moved-items"], representationType: "plural-object-pronoun", misconceptionTargets: ["use-they-after-move"] },
    { stem: "Mia found a key and put ___ in her bag.", options: ["she", "them", "her", "it"], answerIndex: 3, reasons: ["she 會指 Mia，但 put 的受詞是找到的物品。", "them 是複數，key 是單數。", "her 指女性人物，不能代替鑰匙。", "it 是單數事物受格，承接 a key。"], reviews: ["put 之後缺的是被放進包包的東西。", "第四項讓兩個動作連續作用於同一把 key。"], cognitiveProcess: ["trace-key-from-found-to-put", "replace-single-object-with-it"], representationType: "object-continuity-pronoun", misconceptionTargets: ["choose-she-from-nearest-person"] },
    { stem: "Which line does not repeat 'Leo' and keeps Leo as the person who was tired?", options: ["Leo walked home because he was tired.", "Leo walked home because him was tired.", "Leo walked home because it was tired.", "Leo walked home because they were tired."], answerIndex: 0, reasons: ["he 作 was tired 的主詞並明確承接 Leo。", "him 不能在 was 前作主詞。", "it 通常不代替人物 Leo。", "they 是複數，與單數 Leo 不一致。"], reviews: ["第二個子句需要一個代替 Leo 的主格。", "第一項減少重複，同時沒有更換疲倦的人。"], cognitiveProcess: ["preserve-leo-as-tired-person", "select-he-in-reason-clause"], representationType: "repetition-reduction-selection", misconceptionTargets: ["use-object-pronoun-in-clause-subject"] },
    { stem: "The books are on the desk. ___ belong to Nora.", options: ["It", "They", "Them", "She"], answerIndex: 1, reasons: ["It 是單數，不能承接 books。", "They 是複數主格，可作 belong 的主詞。", "Them 是受格，不能直接放在 belong 前。", "She 指單數女性人物，會改成 Nora 屬於自己。"], reviews: ["books 是複數物品，第二句空格又是主詞。", "第二項讓 belong 的動作者與前句名詞一致。"], cognitiveProcess: ["replace-plural-books-as-subject", "distinguish-they-from-them-before-belong"], representationType: "plural-subject-pronoun", misconceptionTargets: ["use-it-for-all-objects"] },
    { stem: "Mia and I finished the work. ___ left together.", options: ["They", "Us", "We", "Them"], answerIndex: 2, reasons: ["They 排除說話者 I，沒有保留原主詞視角。", "Us 是受格，不能作 left 的主詞。", "We 包含 Mia 與說話者 I，並可作主詞。", "Them 既是受格，也把 I 改成第三人稱。"], reviews: ["Mia and I 包含說話者，所以代名詞人稱是 we。", "第三項同時配合複數與 left 前的主詞位置。"], cognitiveProcess: ["combine-mia-and-speaker-as-we", "maintain-first-person-plural-subject"], representationType: "compound-subject-pronoun", misconceptionTargets: ["replace-mia-and-i-with-they"] },
    { stem: "Leo spoke to Nora and later thanked ___.", options: ["she", "they", "he", "her"], answerIndex: 3, reasons: ["she 是主格，不能接在 thanked 後。", "they 是複數主格，Nora 是單數。", "he 會錯指 Leo，且也是主格。", "her 是單數女性受格，承接 Nora。"], reviews: ["兩個動作的另一位參與者是 Nora。", "第四項在 thanked 的受詞位置保留 Nora 的人稱。"], cognitiveProcess: ["carry-nora-into-thanked-object", "exclude-leo-self-reference"], representationType: "cross-verb-object-pronoun", misconceptionTargets: ["choose-he-because-leo-is-subject"] },
    { stem: "Which line does not repeat 'Amy' and keeps her as the person who turned on the light?", options: ["Amy opened the door, and she turned on the light.", "Amy opened the door, and her turned on the light.", "Amy opened the door, and it turned on the light.", "Amy opened the door, and them turned on the light."], answerIndex: 0, reasons: ["she 清楚承接 Amy 並作 turned on 的主詞。", "her 不能作第二個動作的主詞。", "it 會指物品，無法合理承接 Amy。", "them 是複數受格，與 Amy 和主詞位置都不合。"], reviews: ["兩個動作都由 Amy 執行，第二次可用 she。", "第一項只省略重複名稱，未省略必要的主詞。"], cognitiveProcess: ["join-two-amy-actions-with-she", "retain-single-agent-across-coordination"], representationType: "coordinated-action-pronoun", misconceptionTargets: ["replace-person-with-it"] },
    { stem: "The teacher thanked the students and gave ___ more time.", options: ["they", "them", "it", "her"], answerIndex: 1, reasons: ["they 是主格，不能作 gave 的接受者。", "them 是複數受格，代替 the students。", "it 是單數物品，無法承接學生。", "her 只指一位女性，數量不合。"], reviews: ["得到更多時間的人仍是複數 students。", "第二項在 gave 後使用正確受格，沒有重複整個名詞片語。"], cognitiveProcess: ["identify-students-as-time-recipients", "select-plural-object-them"], representationType: "indirect-object-pronoun", misconceptionTargets: ["put-they-after-gave"] },
    { stem: "A student writes, 'Amy saw Ben and waved to he.' Which change is needed?", options: ["Amy → Her", "Ben → They", "he → him", "saw → sees"], answerIndex: 2, reasons: ["Amy 是原句主詞，改為 Her 會破壞句型。", "Ben 是單數人物，They 數量不合。", "介系詞 to 後需要受格 him 代替 Ben。", "改變 saw 的時態不能修正 he 的格位。"], reviews: ["問題出現在 to 後的代名詞形式。", "第三項只修正受格，不改人物、事件或時間。"], cognitiveProcess: ["diagnose-he-after-preposition", "repair-to-him-without-tense-change"], representationType: "pronoun-case-edit", misconceptionTargets: ["change-main-verb-instead-of-pronoun-case"] },
    { stem: "A room notice says, 'Move the chairs beside the wall, then clean them.' What does 'them' replace?", options: ["the room", "the wall", "the notice", "the chairs"], answerIndex: 3, reasons: ["room 是單數，也不是被移動後清潔的直接物品。", "wall 是單數且只提供位置。", "notice 是說明文字，不是清潔對象。", "them 是複數受格，承接前面要移動的 chairs。"], reviews: ["指令中的兩個動作連續作用於同一組物品。", "第四項由複數形式與事件關係共同確認。"], cognitiveProcess: ["track-chairs-across-notice-actions", "resolve-them-in-procedural-text"], representationType: "notice-pronoun-transfer", misconceptionTargets: ["choose-nearest-wall-despite-number"] },
  ]),
  ...skillQuestions("115", [
    { stem: "The boys found a dog. They gave it water. What does 'They' replace?", options: ["the boys", "a dog", "water", "the boys and the dog"], answerIndex: 0, reasons: ["They 是複數主格，承接執行 gave 的 boys。", "a dog 是單數，後文由 it 承接。", "water 是不可數事物，也不是給水的動作者。", "前文沒有把 boys 與 dog 組成共同主詞。"], reviews: ["大寫 They 位於第二句主詞位置。", "第一項同時符合複數形式與給水行動者。"], cognitiveProcess: ["separate-they-and-it-antecedents", "assign-boys-as-water-givers"], representationType: "personal-pronoun-reference", misconceptionTargets: ["attach-they-to-nearest-dog"] },
    { stem: "Mia washed the cup and put it away. What does 'it' replace?", options: ["Mia", "the cup", "away", "the washing"], answerIndex: 1, reasons: ["Mia 是人物，且仍是 put 的主詞。", "the cup 是被洗後又被收起的單數物品。", "away 是方向副詞，不是名詞先行詞。", "the washing 不是原句中出現的名詞對象。"], reviews: ["兩個動作 washed 與 put away 延續處理同一物品。", "第二項由單數形式與事件連續性共同支持。"], cognitiveProcess: ["follow-cup-through-wash-and-storage", "exclude-person-and-adverb-antecedents"], representationType: "object-pronoun-reference", misconceptionTargets: ["choose-mia-because-she-is-subject"] },
    { stem: "The girls tried to get on two buses, but they were full. What does 'they' replace?", options: ["the girls", "the drivers", "the two buses", "the seats"], answerIndex: 2, reasons: ["girls 雖為複數，但女孩吃飽不能說明為何無法上車。", "drivers 並未在句中出現。", "公車載滿能直接解釋 tried to get on 卻未成功。", "seats 也未出現，不能自行補入先行詞。"], reviews: ["單複數只能留下 girls 與 buses，還需使用轉折後的原因。", "第三項讓 full 表示交通工具沒有空位，事件關係完整。"], cognitiveProcess: ["resolve-two-plural-antecedent-candidates", "use-full-buses-to-explain-failed-boarding"], representationType: "semantic-pronoun-resolution", misconceptionTargets: ["stop-after-number-agreement"] },
    { stem: "Ben told Jack that he had won. Who does 'he' name?", options: ["Ben only", "Jack only", "another player", "The sentence does not say clearly."], answerIndex: 3, reasons: ["Ben 符合 he，但沒有線索排除 Jack。", "Jack 也符合 he，不能只因較近就選他。", "句中沒有第三位選手可作先行詞。", "兩位男性都可能獲勝，所以指涉不唯一。"], reviews: ["形式檢查留下兩個單數男性候選。", "第四項承認缺少內容線索，不替句子補寫事實。"], cognitiveProcess: ["enumerate-ben-and-jack-as-he-candidates", "declare-reference-underdetermined"], representationType: "ambiguous-personal-pronoun", misconceptionTargets: ["always-pick-nearest-male-name"] },
    { stem: "The cats chased a bird, but it went over the wall. What does 'it' replace?", options: ["a bird", "the cats", "the wall", "the chase"], answerIndex: 0, reasons: ["a bird 是單數，也是能越過牆的移動對象。", "the cats 是複數，應由 they 承接。", "the wall 在代名詞後才出現，也不是移動者。", "the chase 是事件名稱，未在原句中作單數先行詞。"], reviews: ["it 的單數先排除 cats，移動方向再鎖定 bird。", "第一項不依最近位置，而依形式與動作合理性。"], cognitiveProcess: ["combine-singular-it-with-wall-crossing", "resolve-bird-as-moving-antecedent"], representationType: "animal-pronoun-reference", misconceptionTargets: ["choose-wall-as-nearest-noun"] },
    { stem: "The keys were wet, so I dried them. What does 'them' replace?", options: ["water", "the keys", "I", "the floor"], answerIndex: 1, reasons: ["water 未作原句名詞先行詞，且通常不可數。", "the keys 是複數，也是需要擦乾的物品。", "I 是執行 dried 的主詞，不能由 them 承接。", "the floor 未在句中出現。"], reviews: ["wet 提供後續 dried 的原因。", "第二項符合複數受格 them 與被擦乾的對象。"], cognitiveProcess: ["link-wet-keys-to-dried-them", "reject-unstated-floor-reference"], representationType: "cause-result-pronoun-reference", misconceptionTargets: ["invent-related-object-as-antecedent"] },
    { stem: "Mia gave Amy her book. Whose book was it?", options: ["Mia's book only", "Amy's book only", "The sentence does not make the owner clear.", "The book belonged to both girls."], answerIndex: 2, reasons: ["her 可承接 Mia，但也可承接 Amy，不能限定 Mia。", "Amy 同樣符合 her，卻沒有線索排除 Mia。", "兩位都是單數女性，所有者有兩種合理解讀。", "模糊不等於共同擁有，句中也沒有 both。"], reviews: ["受詞 Amy 與主詞 Mia 都能成為 her 的先行詞。", "第三項區分『不清楚是誰』與『兩人共有』。"], cognitiveProcess: ["test-two-female-owners-for-her", "separate-ambiguity-from-joint-ownership"], representationType: "possessive-reference-ambiguity", misconceptionTargets: ["assign-her-to-nearest-amy-automatically"] },
    { stem: "The table was beside the chair, but it was broken. What was broken?", options: ["the table", "the chair", "both pieces of furniture", "The sentence does not say clearly."], answerIndex: 3, reasons: ["table 符合單數 it，但沒有線索排除 chair。", "chair 較近卻不因此成為唯一答案。", "it 是單數，不能直接推出兩件都壞。", "兩個單數物品都可能 broken，句子有歧義。"], reviews: ["table 與 chair 在形式與常識上都可被 it 承接。", "第四項拒絕把最近名詞規則當成不存在的證據。"], cognitiveProcess: ["compare-two-breakable-singular-nouns", "identify-unresolved-it-reference"], representationType: "object-reference-ambiguity", misconceptionTargets: ["select-chair-only-by-distance"] },
    { stem: "Leo took the bottle off the table because water was coming out of it. What does 'it' most likely replace?", options: ["the bottle", "Leo", "the table", "the floor"], answerIndex: 0, reasons: ["bottle 是單數容器，水從瓶中流出能合理說明 Leo 為何把它移開。", "Leo 是人物，不能由 it 承接。", "table 雖是單數且位置較近，但前文沒有水從桌中流出的線索。", "floor 未在句中出現。"], reviews: ["water was coming out 提供移開 bottle 的原因，語意與單數形式一致。", "most likely 表示依現有線索選最合理先行詞，而不是把最近名詞當固定答案。"], cognitiveProcess: ["connect-water-from-bottle-to-removal", "reject-nearest-table-as-automatic-reference"], representationType: "contextual-object-reference", misconceptionTargets: ["choose-table-because-nearest"] },
    { stem: "The workers lifted the boxes after they put on gloves. Who put on gloves?", options: ["the boxes", "the workers", "the gloves", "the writer"], answerIndex: 1, reasons: ["boxes 是物品，不能自行穿戴手套。", "workers 是複數人物，也是穿手套後搬箱子的人。", "gloves 是被穿戴的物品，不是動作者。", "writer 未參與句中事件。"], reviews: ["they 是複數主格，四個選項中需再看 put on gloves 的能力。", "第二項把準備動作與後續 lifted 連到同一群人。"], cognitiveProcess: ["identify-glove-wearers-before-lifting", "resolve-they-to-workers-not-boxes"], representationType: "human-action-reference", misconceptionTargets: ["match-they-to-nearest-plural-boxes"] },
    { stem: "Nora met Mia at the station. Mia carried a heavy bag, so Nora helped her. Who received help?", options: ["Nora", "the station worker", "Mia", "both girls"], answerIndex: 2, reasons: ["Nora 是 helped 的動作者，不是 her 所指受助者。", "句中沒有 station worker。", "Mia 帶著重包，her 承接 Mia 並符合需要協助的原因。", "her 是單數，原文也沒有說兩人互相幫助。"], reviews: ["heavy bag 建立 Mia 需要幫忙的明確內容線索。", "第三項同時符合女性單數與動作角色。"], cognitiveProcess: ["use-heavy-bag-to-resolve-her", "distinguish-helper-nora-from-helped-mia"], representationType: "multi-sentence-person-reference", misconceptionTargets: ["take-clause-subject-as-object-reference"] },
    { stem: "The red bus passed the blue bus while it turned left. Which bus turned left?", options: ["the red bus", "the blue bus", "both buses", "The sentence does not say clearly."], answerIndex: 3, reasons: ["red bus 符合單數 it，但句法沒有排除 blue bus。", "blue bus 也符合，而且較近並不足以形成唯一答案。", "it 是單數，不能直接表示兩班車都轉彎。", "兩個單數 bus 都可能是轉彎者，需更多資訊。"], reviews: ["顏色使兩車可區分，卻沒有指出 it 對應哪一色。", "第四項保留文本證據界線，不以交通常識硬猜。"], cognitiveProcess: ["test-two-buses-as-turning-candidates", "flag-ambiguous-traffic-pronoun"], representationType: "traffic-reference-transfer", misconceptionTargets: ["pick-blue-bus-as-nearest"] },
  ]),
  ...skillQuestions("116", [
    { stem: "The road was closed. This made the trip longer. What does 'This' mean?", options: ["The road was closed.", "The trip was longer.", "The road was long.", "The trip was closed."], answerIndex: 0, reasons: ["道路封閉這件事造成行程變長。", "trip was longer 是結果，不是 This 所承接的原因。", "原文沒有說道路本身很長。", "closed 描述 road，不描述 trip。"], reviews: ["This 可承接前面整個主詞加狀態，而非只承接 road。", "第一項建立與 made the trip longer 相符的原因。"], cognitiveProcess: ["resolve-this-to-road-closure-event", "separate-cause-from-longer-trip-result"], representationType: "demonstrative-event-reference", misconceptionTargets: ["reduce-this-to-road-noun-only"] },
    { stem: "I like the shoes beside me, but ___ over there are too large.", options: ["that", "those", "this", "it"], answerIndex: 1, reasons: ["that 是單數，不能配合 shoes 與 are。", "those 表複數且較遠，符合 over there。", "this 是單數且通常較近。", "it 是單數人稱代名詞，也不表遠近對照。"], reviews: ["shoes 與 are 先鎖定複數形式。", "over there 再從複數選項中確定 those。"], cognitiveProcess: ["combine-plural-shoes-with-distance", "select-those-for-far-footwear"], representationType: "demonstrative-distance-cloze", misconceptionTargets: ["choose-that-for-any-far-object"] },
    { stem: "Please take this cup. ___ over there on the shelf is mine.", options: ["These", "Those", "That", "They"], answerIndex: 2, reasons: ["These 是複數，不能配合 is 與 cup。", "Those 同樣是複數形式。", "That 指 over there 的單數杯子。", "They 是複數人稱代名詞，也沒有表達單數對照。"], reviews: ["is 和 cup 都要求單數。", "over there 明確提供較遠位置，因此第三項比 this 更合適。"], cognitiveProcess: ["use-is-to-fix-singular-demonstrative", "map-over-there-shelf-to-that"], representationType: "far-singular-demonstrative", misconceptionTargets: ["ignore-is-and-select-those"] },
    { stem: "The books beside me are new. ___ have not been opened.", options: ["That", "This", "It", "These"], answerIndex: 3, reasons: ["That 是單數且通常較遠。", "This 是單數，不能承接 books。", "It 也是單數，與 have 不合。", "These 表複數且可指身旁的 books。"], reviews: ["books 與 have 提供兩個複數線索。", "beside me 又支持使用近距離的 these。"], cognitiveProcess: ["align-books-have-with-plural-form", "choose-near-demonstrative-these"], representationType: "near-plural-demonstrative", misconceptionTargets: ["use-this-for-plural-near-items"] },
    { stem: "In which line does 'This' stand alone as a pronoun?", options: ["This is my seat.", "This seat is mine.", "I chose this seat.", "Please clean this seat."], answerIndex: 0, reasons: ["This 單獨作 is 的主詞，後面沒有名詞。", "This 直接限定名詞 seat。", "this 同樣與 seat 組成名詞片語。", "this 後仍有 seat，因此不是單獨代名詞。"], reviews: ["判斷重點是 This 後是否立即帶名詞。", "第一項的 This 本身取代一個已知座位。"], cognitiveProcess: ["distinguish-pronoun-this-from-determiner-this", "select-standalone-this-before-is"], representationType: "demonstrative-function-comparison", misconceptionTargets: ["call-every-this-a-pronoun"] },
    { stem: "The team missed the bus. This caused a long wait. What caused the wait?", options: ["the team", "missing the bus", "the driver", "the next bus"], answerIndex: 1, reasons: ["team 是事件參與者，但不是 This 所概括的完整原因。", "This 承接整個 missed the bus 事件。", "driver 未在前句中出現。", "next bus 也未被提到，不能自行補入。"], reviews: ["caused 要求找前文能造成等待的事件。", "第二項把動作與受詞一起保留，指涉範圍正確。"], cognitiveProcess: ["expand-this-into-missed-bus-event", "identify-wait-cause-without-new-actors"], representationType: "event-cause-demonstrative", misconceptionTargets: ["resolve-this-to-team-only"] },
    { stem: "Here are four clean towels. Please use ___.", options: ["this", "that", "these", "it"], answerIndex: 2, reasons: ["this 是單數，不能承接 four towels。", "that 也是單數且偏遠。", "these 是複數並符合 Here 的近距離。", "it 為單數，且不表這些近處物品。"], reviews: ["four 與 towels 明確要求複數。", "Here 讓第三項的近距離意思也和情境一致。"], cognitiveProcess: ["combine-four-towels-with-here", "supply-these-as-plural-object"], representationType: "demonstrative-object-cloze", misconceptionTargets: ["choose-this-because-here"] },
    { stem: "This chair is dry, but ___ one over there near the door is wet.", options: ["these", "those", "this", "that"], answerIndex: 3, reasons: ["these 為複數，不能修飾 one。", "those 也是複數形式。", "this 會指近處，與 over there 不合。", "that one 指門邊較遠的單數椅子。"], reviews: ["one 先把選項限定為單數 this 或 that。", "句首 This chair 與 over there 建立近遠對照，故選 that。"], cognitiveProcess: ["use-one-to-require-singular-demonstrative", "contrast-this-chair-with-that-one"], representationType: "demonstrative-one-contrast", misconceptionTargets: ["pair-those-with-singular-one"] },
    { stem: "The school moved the game inside because of rain. This helped the players stay dry. What does 'This' refer to?", options: ["moving the game inside", "the rain", "the school building", "the players"], answerIndex: 0, reasons: ["把比賽移到室內這個決定幫助球員保持乾燥。", "rain 會讓人淋濕，不是保持乾燥的直接措施。", "前文沒有單獨介紹 building。", "players 是受益者，不是 This 所指措施。"], reviews: ["This 承接前一句完成的應變行動。", "第一項保留 moved、game、inside 三項關鍵資訊。"], cognitiveProcess: ["resolve-this-to-inside-move", "distinguish-protective-action-from-beneficiaries"], representationType: "policy-action-demonstrative", misconceptionTargets: ["attach-this-to-nearest-rain"] },
    { stem: "Which line keeps the demonstrative and verb in the same number?", options: ["Those is my books.", "Those are my books.", "That are my books.", "This are my books."], answerIndex: 1, reasons: ["Those 是複數，不能搭配 is。", "Those、are、books 三者都為複數。", "That 是單數，不能搭配 are 與 books。", "This 是單數，也不搭配 are。"], reviews: ["先由 books 判定複數，再檢查指示詞與 be 動詞。", "第二項是唯一三處數量一致的句子。"], cognitiveProcess: ["cross-check-demonstrative-be-and-noun-number", "select-those-are-books"], representationType: "demonstrative-number-agreement", misconceptionTargets: ["check-only-demonstrative-distance"] },
    { stem: "The lights went out during the show. That frightened the children. What frightened them?", options: ["the children", "the show", "the lights going out", "the room"], answerIndex: 2, reasons: ["children 是感到害怕的人，不是原因。", "show 提供時間背景，但 That 承接的是停電事件。", "lights went out 這整件事能造成驚嚇。", "room 未在句中出現。"], reviews: ["That 位於新句主詞位置，可概括前句事件。", "第三項保留動作 went out，不只選名詞 lights。"], cognitiveProcess: ["interpret-that-as-blackout-event", "separate-frightened-children-from-cause"], representationType: "that-event-reference", misconceptionTargets: ["choose-nearest-show-as-that"] },
    { stem: "A ticket note says, 'Keep these new tickets. Those on the desk were used yesterday.' What does 'Those' replace?", options: ["the desks", "the notes", "the new tickets", "the tickets on the desk"], answerIndex: 3, reasons: ["desk 是單數，不能由 Those 代替。", "notes 不是前文對照的物品。", "these new tickets 指要保留的新票，不是已使用的那組。", "Those 承接另一組位於桌上的複數 tickets。"], reviews: ["these 與 Those 建立兩組票的對照。", "第四項同時保留複數、位置與 used yesterday 的資訊。"], cognitiveProcess: ["resolve-those-across-two-ticket-groups", "preserve-desk-location-in-reference"], representationType: "notice-demonstrative-transfer", misconceptionTargets: ["equate-those-with-nearest-desk"] },
  ]),
  ...skillQuestions("117", [
    { stem: "This chair is broken. Please bring another ___.", options: ["one", "ones", "it", "them"], answerIndex: 0, reasons: ["one 代替另一張單數 chair。", "ones 是複數，與 another 不合。", "it 會指原本那張壞椅子，不是另一張。", "them 是複數受格，沒有承接單數 chair。"], reviews: ["another 表示要換成同類的另一件物品。", "第一項同時符合 chair 的可數單數與替代關係。"], cognitiveProcess: ["interpret-another-as-different-chair", "select-singular-substitute-one"], representationType: "one-singular-substitution", misconceptionTargets: ["use-it-for-replacement-item"] },
    { stem: "The red shoes are too small. Try the black ___.", options: ["one", "ones", "it", "shoe"], answerIndex: 1, reasons: ["one 是單數，不能代替 shoes。", "ones 代替複數 shoes，並由 black 修飾。", "it 是單數且通常指原來同一物。", "shoe 是單數，與要試穿的一雙不一致。"], reviews: ["前文 shoes 與語境中的一雙都要求複數。", "第二項形成 the black ones，避免重複 shoes。"], cognitiveProcess: ["replace-plural-shoes-after-color-change", "choose-ones-under-black-modifier"], representationType: "ones-plural-substitution", misconceptionTargets: ["use-one-after-plural-shoes"] },
    { stem: "I found my lost key and put ___ in my pocket.", options: ["one", "ones", "it", "another"], answerIndex: 2, reasons: ["one 會指另一把同類鑰匙，不是找到的原物。", "ones 是複數，key 為單數。", "it 指回同一把 lost key，並作 put 的受詞。", "another 需要後接名詞或 one，且會改成另一物。"], reviews: ["found 與 put 延續同一把鑰匙。", "第三項測的是原物回指，不是同類替代。"], cognitiveProcess: ["preserve-same-key-across-actions", "contrast-it-with-substitute-one"], representationType: "it-versus-one-continuity", misconceptionTargets: ["choose-one-whenever-noun-is-singular"] },
    { stem: "This water is dirty. I need ___.", options: ["a clean one", "clean ones", "it", "some clean water"], answerIndex: 3, reasons: ["water 不可數，不能直接用 a...one 代替。", "ones 需要複數可數名詞先行詞。", "it 會指原來的髒水，和 need 的需求不合。", "some clean water 正確表達另一份乾淨的水。"], reviews: ["one/ones 的先行詞必須能以個數計算。", "第四項保留不可數名詞 water 並改變其品質。"], cognitiveProcess: ["classify-water-as-uncountable", "replace-invalid-one-with-some-water"], representationType: "uncountable-one-boundary", misconceptionTargets: ["substitute-one-for-mass-noun"] },
    { stem: "In which line does 'one' replace a countable noun?", options: ["My pen is dry, so I need a new one.", "The milk is old, so I need a new one.", "The water is dirty, so I need a clean one.", "The air is dirty, so I need a clean one."], answerIndex: 0, reasons: ["pen 是單數可數名詞，a new one 可代替另一枝筆。", "milk 通常不可數，不能直接說 a new one。", "water 不以一個一個計數，此處替代不成立。", "air 也是不可數物質，不能直接由 a clean one 代替。"], reviews: ["題目同時要求 one 的替代功能與可數先行詞。", "第一項唯一能還原成 a new pen。"], cognitiveProcess: ["compare-countability-of-four-antecedents", "restore-one-as-new-pen"], representationType: "one-countability-selection", misconceptionTargets: ["treat-all-nouns-as-countable-for-one"] },
    { stem: "I like the large plates, but the small ___ fit this table better.", options: ["one", "ones", "it", "them"], answerIndex: 1, reasons: ["one 是單數，large plates 建立的類別是複數。", "ones 由 small 修飾並代替複數 plates。", "it 是單數，也會指原來同一物。", "them 前不能直接使用 the small 形成此結構。"], reviews: ["fit 的主詞需要與 plates 同為複數。", "第二項將 the small ones 還原為 the small plates。"], cognitiveProcess: ["infer-plural-substitute-from-fit-and-plates", "build-small-ones-noun-phrase"], representationType: "modified-ones-cloze", misconceptionTargets: ["choose-them-after-adjective"] },
    { stem: "Nora repaired her bike and used ___ to go home.", options: ["one", "another one", "it", "ones"], answerIndex: 2, reasons: ["one 會表示另一台同類腳踏車。", "another one 更明確改成另一台車。", "it 指 Nora 剛修好的同一台 bike。", "ones 是複數，與單數 bike 不合。"], reviews: ["repaired 後緊接 used，事件沒有換車線索。", "第三項維持同一物，不把修車與回家拆成兩台車。"], cognitiveProcess: ["track-repaired-bike-into-trip-home", "select-it-for-same-vehicle"], representationType: "same-item-reference-versus-one", misconceptionTargets: ["replace-known-bike-with-one"] },
    { stem: "The large boxes are heavy. Please move the small ___.", options: ["it", "one", "them", "ones"], answerIndex: 3, reasons: ["it 是單數且指原來已知物。", "one 是單數，不能承接 boxes。", "them 無法直接接在 the small 後。", "ones 代替複數 boxes，形成 the small ones。"], reviews: ["large boxes 與 small 建立同類物的對照。", "第四項符合複數，也允許前方形容詞修飾。"], cognitiveProcess: ["contrast-large-and-small-box-groups", "complete-the-small-ones"], representationType: "adjective-ones-substitution", misconceptionTargets: ["use-them-after-the-small"] },
    { stem: "I do not want the chair by the door. I want the one by the window. Which chair does 'the one' mean?", options: ["the chair by the window", "the chair by the door", "both chairs", "a chair outside"], answerIndex: 0, reasons: ["by the window 直接修飾 one，指出想要的椅子。", "第一句明確排除門邊椅子。", "one 是單數，也沒有表示兩張都要。", "outside 並未在句中出現。"], reviews: ["the one 先承接 chair，再由 by the window 選出個體。", "第一項保留修飾語，沒有只回答泛稱 chair。"], cognitiveProcess: ["resolve-one-through-window-modifier", "exclude-rejected-door-chair"], representationType: "one-modifier-reference", misconceptionTargets: ["attach-one-to-nearest-door-chair"] },
    { stem: "A student writes, 'I like the red shoes, not the blue one.' Which change is needed?", options: ["red → reds", "one → ones", "shoes → shoe", "blue → blues"], answerIndex: 1, reasons: ["red 作形容詞不加 s。", "one 應改為複數 ones 承接 shoes。", "把 shoes 改單數會改變原來喜歡的物品數量。", "blue 也是形容詞，不使用複數形式。"], reviews: ["對照的是 red shoes 與 blue shoes 兩組複數鞋。", "第二項只修正替代詞數量，不改顏色或物品。"], cognitiveProcess: ["diagnose-singular-one-after-plural-shoes", "repair-color-contrast-with-ones"], representationType: "one-ones-number-edit", misconceptionTargets: ["pluralize-color-adjective"] },
    { stem: "A store note says, 'Your old phone cannot be fixed. You may choose a new one.' What does 'one' replace?", options: ["a store", "a note", "a phone", "a repair"], answerIndex: 2, reasons: ["store 是地點，不是可選的新物品類別。", "note 是訊息本身，沒有新舊對照。", "new one 還原為 a new phone，與 old phone 對照。", "repair 是動作概念，且不是被選的產品。"], reviews: ["形容詞 old 與 new 建立同類商品替換。", "第三項由可數單數和購物行動共同確認。"], cognitiveProcess: ["restore-new-one-as-phone", "follow-product-replacement-in-store-note"], representationType: "commercial-one-reference", misconceptionTargets: ["resolve-one-to-nearest-fix-action"] },
    { stem: "This soup is cold. Which sentence correctly asks for some hot soup?", options: ["May I have a hot one?", "May I have hot ones?", "May I have some hot?", "May I have some hot soup?"], answerIndex: 3, reasons: ["soup 通常不可數，a hot one 不適合直接代替。", "ones 也要求複數可數先行詞。", "some hot 缺少要的食物名稱，句意不完整。", "some hot soup 正確要求另一份熱湯。"], reviews: ["想要另一份不會讓 soup 本身自動變成 one 的可數先行詞。", "第四項用 some 保留不可數用法與實際點餐目的。"], cognitiveProcess: ["apply-mass-noun-boundary-in-order", "choose-some-soup-over-one"], representationType: "service-context-one-boundary", misconceptionTargets: ["use-one-for-any-replacement-order"] },
  ]),
  ...skillQuestions("118", [
    { stem: "The light is still on. Please turn ___ off before you leave.", options: ["it", "them", "they", "her"], answerIndex: 0, reasons: ["it 是單數受格，可承接 the light。", "them 是複數受格，數量不合。", "they 是複數主格，不能放在 turn 後作受詞。", "her 指女性人物，不指 light。"], reviews: ["light 是單數物品，空格又位於 turn 與 off 之間。", "第一項同時符合單數、物品與受詞位置。"], cognitiveProcess: ["match-light-to-singular-object-pronoun", "place-it-inside-turn-off"], representationType: "singular-object-agreement", misconceptionTargets: ["use-them-for-single-light"] },
    { stem: "The lamp is old, but the two chairs are new. ___ came from Nora's house.", options: ["It", "They", "Them", "She"], answerIndex: 1, reasons: ["It 是單數，會錯指 lamp。", "They 是複數主格，可承接 the two chairs。", "Them 是複數受格，不能放在 came 前作主詞。", "She 指 Nora，不指 chairs。"], reviews: ["new 與 two chairs 建立第二句要延續的複數物品。", "第二項在 came 前使用主格，也不會回指單數 lamp。"], cognitiveProcess: ["contrast-old-lamp-with-new-chairs", "select-they-for-chair-origin"], representationType: "plural-subject-agreement", misconceptionTargets: ["attach-it-to-first-singular-lamp"] },
    { stem: "The players are waiting. Please give ___ the new plan.", options: ["they", "it", "them", "him"], answerIndex: 2, reasons: ["they 是主格，不能作 give 的接受者。", "it 是單數物品代名詞，不能指複數 players。", "them 是複數受格，可承接 players。", "him 只指一位男性，數量不合。"], reviews: ["players 是複數人物，空格在 give 後表示收到計畫的人。", "第三項在數量與受格形式上都正確。"], cognitiveProcess: ["identify-players-as-plan-recipients", "choose-plural-object-them-after-give"], representationType: "plural-person-object-agreement", misconceptionTargets: ["keep-they-after-give"] },
    { stem: "Ben left his bag here. Please give it to ___ when he returns.", options: ["he", "they", "her", "him"], answerIndex: 3, reasons: ["he 是主格，不能接在 to 後。", "they 是複數主格，也不承接單數 Ben。", "her 指女性人物，與 Ben 不合。", "him 是男性單數受格，可接在 to 後指 Ben。"], reviews: ["to 後需要受格，前文的物主詞 his 也指出 bag 屬於 Ben。", "第四項同時符合人物、性別、數量與介系詞後的位置。"], cognitiveProcess: ["use-his-bag-to-identify-ben", "supply-him-after-to"], representationType: "singular-person-object-case", misconceptionTargets: ["place-he-after-preposition"] },
    { stem: "Mia and Nora are at the gate. ___ will meet us there.", options: ["They", "Them", "She", "It"], answerIndex: 0, reasons: ["They 是複數主格，可承接 Mia and Nora。", "Them 是受格，不能作 will meet 的主詞。", "She 只指一位女性，遺漏另一人。", "It 指單數事物，不指兩位人物。"], reviews: ["and 把 Mia 與 Nora 組成複數主詞。", "第一項在 will 前作主詞，也完整保留兩位見面者。"], cognitiveProcess: ["combine-two-names-into-plural-antecedent", "replace-mia-and-nora-with-they"], representationType: "compound-person-subject-agreement", misconceptionTargets: ["use-she-for-two-women"] },
    { stem: "I put the phone beside the bags. Please move ___ to the shelf; the bags can stay.", options: ["they", "it", "them", "these"], answerIndex: 1, reasons: ["they 是複數主格，不能指單數 phone。", "it 是單數受格，且 the bags can stay 排除 bags。", "them 會承接複數 bags，與後句不合。", "these 是複數指示代名詞，也不能指 phone。"], reviews: ["分號後明說 bags 不必移動，因此要移的是 phone。", "第二項保持單數，並在 move 後作受詞。"], cognitiveProcess: ["use-bags-can-stay-to-isolate-phone", "choose-it-for-moved-phone"], representationType: "contrastive-number-reference", misconceptionTargets: ["attach-pronoun-to-nearest-bags"] },
    { stem: "Which line uses a plural subject pronoun for 'the cameras'?", options: ["The camera is new. They work well.", "The cameras are new. It works well.", "The cameras are new. They work well.", "The cameras are new. Them work well."], answerIndex: 2, reasons: ["camera 是單數，不能由 They 承接。", "cameras 是複數，It 的數量不合。", "cameras 與 They 都是複數，They 也作 work 的主詞。", "Them 是受格，不能作 work 的主詞。"], reviews: ["題目要求同時檢查先行詞數量與代名詞句法位置。", "第三項是唯一使用複數主格承接 cameras 的句子。"], cognitiveProcess: ["compare-camera-number-across-four-lines", "verify-they-as-work-subject"], representationType: "sentence-level-pronoun-agreement", misconceptionTargets: ["check-number-without-case"] },
    { stem: "The tickets are on the desk. Put it in my bag. Which change keeps all the tickets and fixes the pronoun?", options: ["tickets → ticket", "desk → desks", "Put → Puts", "it → them"], answerIndex: 3, reasons: ["改成 ticket 會把多張票變成一張，改變原意。", "desk 的數量和代名詞錯誤無關。", "祈使句使用原形 Put，不加 s。", "them 是複數受格，可承接 tickets 並保留全部票。"], reviews: ["需要修的是 it 與 tickets 的單複數不一致。", "第四項只調整代名詞，不改票的數量或指令內容。"], cognitiveProcess: ["locate-number-error-in-ticket-instruction", "replace-singular-it-with-plural-them"], representationType: "pronoun-number-edit", misconceptionTargets: ["singularize-tickets-to-fit-it"] },
    { stem: "The book has three maps. They show different roads. What does 'They' replace?", options: ["the three maps", "the book", "different roads", "the table"], answerIndex: 0, reasons: ["the three maps 是複數，也是能顯示道路的圖。", "the book 是單數，不能由 They 承接。", "roads 在 They 之後才出現，且是 maps 所顯示的內容。", "table 未在句中出現。"], reviews: ["複數形式先排除 book，再由 show roads 的功能確認 maps。", "第一項保留 three 所表示的數量。"], cognitiveProcess: ["resolve-they-with-map-function", "exclude-later-roads-as-antecedent"], representationType: "plural-reference-in-description", misconceptionTargets: ["choose-book-as-main-topic"] },
    { stem: "The girls left their bags by the door. Later, the teacher gave them to the girls. What does 'them' replace?", options: ["the girls", "their bags", "the teacher", "the door"], answerIndex: 1, reasons: ["girls 是 to 後的接受者，不是被交還的物品。", "their bags 是複數物品，能作 gave 的直接受詞。", "teacher 是交還物品的動作者。", "door 是單數地點，也不是被交還的東西。"], reviews: ["gave them to the girls 把物品與接受者分開表示。", "第二項符合複數受格，也延續前句留在門邊的物品。"], cognitiveProcess: ["separate-given-items-from-recipients", "resolve-them-to-left-bags"], representationType: "two-object-reference", misconceptionTargets: ["attach-them-to-later-girls"] },
    { stem: "Amy picked up the baby bird and showed it to Nora. What does 'it' replace?", options: ["Amy", "Nora", "the baby bird", "the ground"], answerIndex: 2, reasons: ["Amy 是 picked up 與 showed 的動作者。", "Nora 是 to 後看到小鳥的人。", "the baby bird 是被撿起後又被展示的單數物品。", "ground 未在句中出現。"], reviews: ["兩個動作延續同一隻 baby bird，且 it 在 showed 後作受詞。", "第三項同時符合事件連續性與單數形式。"], cognitiveProcess: ["track-baby-bird-through-two-actions", "distinguish-shown-object-from-viewer"], representationType: "person-object-reference-consistency", misconceptionTargets: ["resolve-it-to-nearest-person-nora"] },
    { stem: "The two doors are locked. Do not open ___.", options: ["it", "that", "this", "them"], answerIndex: 3, reasons: ["it 是單數，不能承接 two doors。", "that 是單數指示代名詞。", "this 也是單數形式。", "them 是複數受格，可放在 open 後承接 doors。"], reviews: ["two 明確要求複數，空格又是 open 的受詞。", "第四項讓數量與句法位置都保持一致。"], cognitiveProcess: ["use-two-doors-to-fix-plurality", "complete-warning-with-them"], representationType: "notice-pronoun-number-consistency", misconceptionTargets: ["use-it-as-default-object-pronoun"] },
  ]),
  ...skillQuestions("119", [
    { stem: "Amy called Nora when she arrived. Which line clearly says that Nora arrived before the call?", options: ["Nora arrived, and then Amy called her.", "Amy arrived, and then she called Nora.", "Amy called Nora, and then Nora arrived.", "Amy called Nora when she arrived."], answerIndex: 0, reasons: ["Nora 是 arrived 的主詞，then 又把 Amy 的電話排在後面。", "此句先抵達的是 Amy。", "此句讓 Nora 在電話之後才抵達。", "she 可指 Amy 或 Nora，抵達者仍不清楚。"], reviews: ["題目同時指定 Nora 是抵達者，且抵達發生在電話以前。", "第一項用兩個具名主詞保留人物與先後順序。"], cognitiveProcess: ["compare-nora-arrival-and-call-order", "select-explicit-nora-first-rewrite"], representationType: "time-clause-reference-repair", misconceptionTargets: ["repair-person-but-reverse-event-order"] },
    { stem: "Leo called Sam after Leo got home. Who got home?", options: ["Sam", "Leo", "both boys", "The sentence does not say clearly."], answerIndex: 1, reasons: ["after 子句沒有寫 Sam。", "after Leo got home 直接指出回家者是 Leo。", "句中只陳述 Leo 回家，沒有 both。", "重複 Leo 已排除代名詞的兩種解讀。"], reviews: ["明確重複姓名有時比使用 he 更能避免誤會。", "第二項可直接由 after 子句定位，不需猜最近名詞。"], cognitiveProcess: ["read-repeated-leo-in-time-clause", "identify-leo-as-sole-arriver-home"], representationType: "explicit-name-reference", misconceptionTargets: ["assume-repeated-name-must-be-an-error"] },
    { stem: "The bottle hit the glass, and it broke. Which line clearly says that the glass broke?", options: ["The bottle hit the glass, and it broke.", "The glass hit the bottle, and the bottle broke.", "The bottle hit the glass, and the glass broke.", "The bottle and the glass both broke."], answerIndex: 2, reasons: ["it 仍可指 bottle 或 glass。", "此句改變碰撞方向，且破的是 bottle。", "第二次直接寫 the glass，沒有另一種指涉。", "此句增加兩件都破的資訊，超出指定意思。"], reviews: ["清楚改寫不能順便改變動作方向或損壞數量。", "第三項只把模糊 it 換成真正破裂的名詞。"], cognitiveProcess: ["compare-four-bottle-glass-rewrites", "select-explicit-glass-breakage"], representationType: "object-reference-repair", misconceptionTargets: ["remove-pronoun-by-changing-event"] },
    { stem: "Which line makes Mia the person who left?", options: ["Mia told Amy that she would leave.", "Mia met Amy before she left.", "When Mia met Amy, she was leaving.", "Mia met Amy and then Mia left."], answerIndex: 3, reasons: ["she 可指 Mia 或 Amy，離開者不唯一。", "she 同樣可能承接兩位女性。", "主句與從句仍沒有排除 Amy。", "第二個 Mia 直接指出見面後離開的人。"], reviews: ["題目要求的不只是句子通順，而是離開者只能解讀為 Mia。", "第四項重複姓名，保留先見面、後離開的事件順序。"], cognitiveProcess: ["compare-four-mia-amy-reference-patterns", "select-explicit-mia-departure"], representationType: "clarity-rewrite-selection", misconceptionTargets: ["treat-any-she-after-mia-as-clear"] },
    { stem: "Which line clearly says that Sam won?", options: ["Sam won, and Leo told him the news.", "Leo told Sam that he won.", "Leo won before he spoke to Sam.", "Leo and Sam won together."], answerIndex: 0, reasons: ["Sam 直接作 won 的主詞，him 也承接 Sam。", "he 可指 Leo 或 Sam，勝者不唯一。", "此句明說勝者是 Leo。", "此句增加 Leo 也獲勝的資訊。"], reviews: ["題目只要求 Sam 獲勝，不能加入另一位勝者。", "第一項用具名主詞消除歧義，後句代名詞也有唯一先行詞。"], cognitiveProcess: ["compare-four-winner-statements", "select-sam-as-explicit-sole-winner"], representationType: "winner-reference-repair", misconceptionTargets: ["accept-ambiguous-he-as-sam"] },
    { stem: "Ben told Jack, 'You won.' Who won?", options: ["Ben", "Jack", "both boys", "The sentence does not say clearly."], answerIndex: 1, reasons: ["引號內 I 才會指說話者 Ben，但原句使用 You。", "Ben 對 Jack 說話，因此 You 指聽者 Jack。", "You 在此指單一聽者，沒有 both。", "說話者與聽者都已明確，不存在兩種指涉。"], reviews: ["直接引語中的 You 由對話角色決定。", "第二項利用 told Jack 鎖定聽者，不再依模糊的 he 猜測。"], cognitiveProcess: ["map-you-to-jack-as-listener", "resolve-direct-speech-winner"], representationType: "direct-speech-reference", misconceptionTargets: ["treat-you-as-ben-the-speaker"] },
    { stem: "The phone rang, so Amy answered it. What does 'it' replace?", options: ["Amy", "rang", "the phone", "the room"], answerIndex: 2, reasons: ["Amy 是 answered 的動作者，不由 it 承接。", "rang 是動作，不是可被接聽的名詞。", "the phone 是單數，也是能被 answered 的對象。", "原句沒有提到 room。"], reviews: ["單數形式與 answered 的語意都指向 phone。", "第三項有兩種獨立線索支持，因此不是只靠名詞距離。"], cognitiveProcess: ["link-ringing-phone-to-answered-it", "exclude-verb-and-unstated-room"], representationType: "clear-object-reference", misconceptionTargets: ["claim-all-pronouns-are-ambiguous"] },
    { stem: "Grace thanked Wendy because she had helped with the work. Who helped?", options: ["Grace", "Wendy", "both girls", "The sentence does not say clearly."], answerIndex: 3, reasons: ["Grace 可能是 she，但感謝的原因也可能由 Wendy 提供。", "Wendy 也可能是幫忙者，形式上不能排除 Grace。", "she 是單數，不能直接推成兩人都幫忙。", "兩位女性都符合 she，原句缺少唯一線索。"], reviews: ["因果關係使 Wendy 看似較合理，卻仍不是文法上唯一解讀。", "第四項提醒推測合理不等於文本已明說。"], cognitiveProcess: ["distinguish-likely-helper-from-certain-reference", "flag-grace-wendy-she-ambiguity"], representationType: "causal-person-reference-ambiguity", misconceptionTargets: ["treat-thanked-person-as-certain-helper"] },
    { stem: "Which line clearly says that Leo left first and saw Ben later?", options: ["Leo left and then saw Ben.", "After Ben left, Leo saw him.", "Leo saw Ben, and then Ben left.", "Leo saw Ben after he left."], answerIndex: 0, reasons: ["left and then saw 明確排出 Leo 先離開、後看見 Ben。", "此句先離開的是 Ben。", "此句先看見，之後才是 Ben 離開。", "he 可指 Leo 或 Ben，先離開者不清楚。"], reviews: ["事件先後與動作者都必須保持題目指定的意思。", "第一項用同一主詞連接兩個動作，不留下 he 的第二種解讀。"], cognitiveProcess: ["compare-departure-and-seeing-order", "select-leo-first-sequence"], representationType: "event-order-clarity", misconceptionTargets: ["choose-grammatical-line-with-wrong-order"] },
    { stem: "The box was beside the bag before it fell. Which line clearly says that the bag fell?", options: ["The box was beside the bag before it fell.", "The box was beside the bag before the bag fell.", "The box fell beside the bag.", "The box and the bag fell together."], answerIndex: 1, reasons: ["it 可指 box 或 bag，仍有歧義。", "第二次直接寫 the bag，明確指出掉落物。", "此句掉落的是 box。", "此句增加兩件物品一起掉落的資訊。"], reviews: ["改寫目標是只消除指涉，不改動物品數量與事件。", "第二項保留 beside 關係，並用名詞取代模糊 it。"], cognitiveProcess: ["compare-four-box-bag-fall-lines", "select-explicit-bag-fall"], representationType: "spatial-reference-repair", misconceptionTargets: ["clarify-by-changing-falling-object"] },
    { stem: "The bird ate the bread because it was hungry. What was hungry?", options: ["the bread", "the plate", "the bird", "The sentence does not say clearly."], answerIndex: 2, reasons: ["bread 不能感到飢餓，且是被吃的食物。", "plate 未在句中出現。", "bird 是單數生物，hungry 也能解釋牠吃 bread 的原因。", "形式與因果語意都留下唯一合理先行詞。"], reviews: ["並非所有 it 都有歧義；內容線索足夠時可確定指涉。", "第三項同時符合生物特性與 because 所建立的原因。"], cognitiveProcess: ["use-hunger-to-identify-living-antecedent", "resolve-it-to-bird-with-causal-evidence"], representationType: "semantic-disambiguation", misconceptionTargets: ["mark-every-two-noun-pronoun-as-unclear"] },
    { stem: "Which line clearly says that the red cup will be washed?", options: ["Put the red cup beside the blue cup before it is washed.", "Put the red cup beside the blue cup before the cup is washed.", "Before it is washed, put the red cup beside the blue cup.", "Wash the red cup after you put it beside the blue cup."], answerIndex: 3, reasons: ["it 可指 red cup 或 blue cup。", "the cup 仍可能是任一只杯子，顏色未指定。", "前置 it 也沒有唯一先行詞。", "Wash 的受詞直接寫 the red cup，清楚指出要洗的杯子。"], reviews: ["換位置不會自動修好模糊指涉，關鍵是明寫顏色與名詞。", "第四項也保留先放到藍杯旁、再清洗紅杯的事件順序。"], cognitiveProcess: ["evaluate-four-red-blue-cup-rewrites", "select-explicit-red-cup-washing"], representationType: "procedural-reference-repair", misconceptionTargets: ["believe-fronting-pronoun-removes-ambiguity"] },
  ]),
];

export const ENGLISH_U17_VOCABULARY_POLICY = Object.freeze({
  capQuestionBasis: "appendix-5-table-1",
  additionalLearningTerms: ["alone", "ball", "captain", "cause", "chase", "coach", "continue", "describe", "event", "fit", "form", "frighten", "furniture", "lift", "lock", "receive", "repair", "return", "role", "shelf", "upstairs"],
  properNames: ["Amy", "Ben", "Grace", "Jack", "Leo", "Mia", "Nora", "Sam", "Wendy"],
  grammarNotation: ["A", "B", "clause", "countable", "demonstrative", "function", "noun", "object", "phrase", "plural", "preposition", "pronoun", "refer", "replace", "subject", "verb"],
  malformedDistractors: [],
});

export const ENGLISH_U17_SOURCE = Object.freeze({ unitId: UNIT_ID, lectures: ENGLISH_U17_LECTURES, questions: ENGLISH_U17_QUESTIONS, vocabularyPolicy: ENGLISH_U17_VOCABULARY_POLICY });
export const ENGLISH_UNIT_SOURCE = ENGLISH_U17_SOURCE;
