const UNIT_ID = "ENG_R4_U41";

function lecture(id, skillId, content) {
  return { id, skillId, ...content, sections: content.sections.map((section, index) => ({ id: id + "_SEC_" + String(index + 1).padStart(2, "0"), ...section })) };
}

const DIFFICULTIES = ["foundation", "foundation", "foundation", "standard", "standard", "standard", "standard", "advanced", "advanced", "advanced", "transfer", "transfer"];

function skillQuestions(skillNumber, values) {
  if (values.length !== 12) throw new Error("ENG_R4_S" + skillNumber + ": expected 12 authored questions");
  return values.map((value, index) => ({ id: "ENG_R4_Q_" + skillNumber + "_" + String(index + 1).padStart(2, "0"), skillId: "ENG_R4_S" + skillNumber, difficulty: DIFFICULTIES[index], ...value }));
}

function q(stem, options, answerIndex, reasons, reviews, cognitiveProcess, representationType, misconceptionTargets) {
  return { stem, options, answerIndex, reasons, reviews, cognitiveProcess, representationType, misconceptionTargets };
}

export const ENGLISH_U41_LECTURES = [
  lecture("ENG_R4_L_S273", "ENG_R4_S273", {
    objectives: ["能利用時間詞建立敘事事件的先後順序。", "能以事件之間的必要關係檢查排列是否合理。"],
    sections: [
      { title: "先圈出時間路標", content: "故事中的 first、then、later、after that、finally 是明顯的時間路標。first 通常引出起點，then 與 later 接續發展，finally 常引出最後結果。排列時先把這些詞標出，再把沒有路標的句子放回合理位置。" },
      { title: "動作本身也有先後", content: "沒有時間詞時，仍可由事件關係排序。Ava opened the box 必須早於 She found a key inside；The rain stopped 必須早於 We went outside。先問哪一件事要先成立，下一件事才可能發生。" },
      { title: "日期與時段要落在同一條線", content: "yesterday、that morning、at noon、in the evening 會建立較大的時間框架。若段落已說 on Saturday，後面的 that afternoon 仍指星期六下午，不可自行移到星期日。" },
      { title: "排完後讀成完整因果鏈", content: "正確句序不只時間遞增，也要保持人物、物品與結果一致。排完後從頭讀一次，確認沒有先慶祝再得知好消息、先歸還物品再找到物品等倒置情形。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S273_EX_01", prompt: "(A) Finally, the soup was ready. (B) First, Nora cut the carrots. (C) Then she put them in the pot.", steps: ["first 指出起點 B。", "them 回指 carrots，所以 C 接在 B 後。", "finally 引出完成結果 A。"], answer: "B → C → A", why: "切胡蘿蔔後才能把它們放入鍋中，湯煮好則是整個過程的結果。時間詞與動作關係給出同一順序。" },
      { id: "ENG_R4_L_S273_EX_02", prompt: "Mia reached the stop. The bus came two minutes later. She got on and found a seat.", steps: ["先到站牌才能等車。", "two minutes later 把公車到達放在第二。", "上車找座位必須在公車抵達後。"], answer: "Reach the stop → bus comes → get on.", why: "每一步都需要前一步提供條件；若先找座位再等公車，事件在現實上無法成立。" },
      { id: "ENG_R4_L_S273_EX_03", prompt: "On Sunday morning, Leo planted a seed. That afternoon, he watered it. A week later, a small green leaf appeared.", steps: ["Sunday morning 是最早時間。", "that afternoon 仍在同一天但較晚。", "a week later 跳到下一週。"], answer: "Plant → water → leaf appears.", why: "三個時間範圍由同日早晚推進到一週後，且植物先被種下並澆水，之後才出現葉子。" },
    ],
    misconceptions: [
      { belief: "看到 finally 就把整句放在第一句。", whyWrong: "finally 表示一連串事件的最後階段。", correction: "先找起點與中間事件，再把 finally 句放到結果位置。" },
      { belief: "只依句子長短排序，短句一定在前。", whyWrong: "句長不提供時間資訊。", correction: "使用時間詞、代名詞與事件必要關係判斷。" },
      { belief: "that evening 一定表示隔天晚上。", whyWrong: "that 通常承接前文已建立的同一天。", correction: "先找最近的日期框架，再定位當天的時段。" },
      { belief: "每個 later 都代表過了一整天。", whyWrong: "later 只表示較晚，間隔可能是幾分鐘或幾年。", correction: "以全文提供的單位或事件內容判斷間隔。" },
    ],
    checks: [
      { prompt: "First、next、finally 中，哪一個通常引出結局？", answer: "finally", reason: "它標示一連串事件的最後一步。" },
      { prompt: "She dried the cups 應在 She washed the cups 之前還是之後？", answer: "之後", reason: "杯子先洗過，才有需要擦乾。" },
      { prompt: "that night 的日期要從哪裡找？", answer: "前文最近建立的日期", reason: "that 回指已知的時間框架。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S274", "ENG_R4_S274", {
    objectives: ["能由代名詞回指判斷介紹句與承接句的先後。", "能利用新舊資訊安排句子，使讀者先知道對象再讀細節。"],
    sections: [
      { title: "名詞通常先於代名詞", content: "A small dog waited by the gate. It looked hungry. 第一個句子介紹 dog，第二句的 It 才有清楚對象。若段落一開始只有 he、she、it、they 或 this idea，讀者往往不知道它們指什麼。" },
      { title: "the 與 this 常表示已知資訊", content: "a photo 第一次介紹照片，the photo 再談同一張；a plan 先出現後，this plan 才能承接。安排句序時，帶 a 或完整名稱的句子常負責介紹，帶 the、this、these 的句子常負責延伸。" },
      { title: "不是所有代名詞都只看最近名詞", content: "Leo put the book beside the lamp because it was too dark to read. it 的文法可能有歧義，必須看語意與後文。若兩個名詞都合理，正確做法是承認不清楚，不任意選最近者。" },
      { title: "已知到新知形成資訊鏈", content: "良好段落常讓前一句末尾的資訊成為下一句主題。例如 We found an old map. The map showed a river. This river went to the lake。map 與 river 依序被介紹再承接，使句子連成一條鏈。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S274_EX_01", prompt: "(A) It had a red name card. (B) A cat sat outside our door.", steps: ["A 的 It 尚未有對象。", "B 先介紹 a cat。", "把 A 放後面，It 回指 cat。"], answer: "B → A", why: "讀者先知道門外有一隻貓，之後才能理解紅色名牌屬於牠。" },
      { id: "ENG_R4_L_S274_EX_02", prompt: "We chose a place near the river. This place had a large open area. The area was good for our games.", steps: ["a place 是首次介紹。", "This place 承接該地點。", "The area 承接第二句新加入的 area。"], answer: "The given order is clear.", why: "每個已知指示詞都能向前找到唯一對象，資訊從地點推進到場地用途。" },
      { id: "ENG_R4_L_S274_EX_03", prompt: "Nora spoke to Amy after she finished the report.", steps: ["列出 Nora 與 Amy 兩個女性對象。", "she 在形式上可回指任一人。", "檢查是否有其他句子能限定報告作者。"], answer: "The writer must add more information.", why: "單句沒有足夠證據判定誰完成報告；把 she 一律配最近的 Amy 會製造原文沒有的確定性。" },
    ],
    misconceptions: [
      { belief: "代名詞句可以直接放段首，讀者自然會猜到。", whyWrong: "沒有先行詞時，代名詞缺少可確認的對象。", correction: "先放介紹人物或物品的完整名詞句。" },
      { belief: "the book 與 a book 都表示第一次出現。", whyWrong: "a 常引入新對象，the 常指向已知的特定對象。", correction: "由限定詞判斷資訊是新引入還是承接。" },
      { belief: "it 永遠指前面最近的名詞。", whyWrong: "語意、單複數和全文線索都可能排除最近名詞。", correction: "同時檢查文法一致與事件合理性。" },
      { belief: "this idea 可在完全沒有想法內容前先出現。", whyWrong: "this idea 需要前文提供可被概括的想法。", correction: "先放提出觀點的句子，再用 this idea 評論。" },
    ],
    checks: [
      { prompt: "A bird landed on the wall. It began to sing. It 指什麼？", answer: "a bird", reason: "單數動物是前文唯一合理的先行詞。" },
      { prompt: "第一次介紹一個袋子，較自然用 a bag 還是 the bag？", answer: "a bag", reason: "a 用來引入尚未成為已知資訊的單數名詞。" },
      { prompt: "兩個人物都可能是 she 的先行詞時，可以硬選最近的人嗎？", answer: "不可以", reason: "線索不足時應保留歧義或要求補充資訊。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S275", "ENG_R4_S275", {
    objectives: ["能分辨主旨總說、支持細節與具體例子。", "能判斷例證是否屬於前文提出的類別或觀點。"],
    sections: [
      { title: "總說句涵蓋整段", content: "總說句說明段落共同在談什麼，例如 Our school garden helps students in three ways。後面可分別說學習植物、一起工作與享用食物。總說不能只涵蓋其中一個小細節。" },
      { title: "分說句回答哪裡或怎麼樣", content: "分說句把總說拆成不同面向。若總說是 The town has many ways to travel，分說可談 buses、bikes 和 walking paths。每一句仍回到 travel，而不是突然介紹餐廳。" },
      { title: "例子要能放進上位概念", content: "for example、such as 常引出具體例子。若上位概念是 ways to save water，taking shorter showers 是有效例子；buying a louder radio 則不屬於此類。" },
      { title: "例子不能反過來代表全部", content: "一個例子只證明某種情況存在，不必代表所有情況。The park has night activities. For example, people can watch stars on Friday 支持公園有一項夜間活動，但不能證明每天晚上都有活動。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S275_EX_01", prompt: "Our class uses less paper in several ways. We write on both sides. We also share one large notice, not many small ones.", steps: ["第一句提出共同主題 less paper。", "第二句提供雙面書寫方式。", "第三句提供共用公告方式。"], answer: "Sentence 1 is the general sentence; sentences 2 and 3 give facts.", why: "兩個做法都屬於減少紙張使用，且第一句能涵蓋後面的不同方法。" },
      { id: "ENG_R4_L_S275_EX_02", prompt: "Some animals work at night. For example, this small bird looks for food after dark.", steps: ["找出上位概念 animals work at night。", "辨認 for example。", "確認小鳥夜間找食物屬於該概念。"], answer: "The bird is an example of a night-active animal.", why: "具體動物與牠在天黑後的行動，直接支持前一句的概括。" },
      { id: "ENG_R4_L_S275_EX_03", prompt: "The center offers activities inside. Visitors can paint, play board games, and read comics.", steps: ["第一句建立 inside activities 類別。", "後句列出三項活動。", "確認每一項都可在室內進行。"], answer: "The list develops the general sentence.", why: "畫畫、桌上遊戲與閱讀都是中心可提供的室內活動，沒有離開主題。" },
    ],
    misconceptions: [
      { belief: "最長的句子一定是總說句。", whyWrong: "句長與涵蓋範圍沒有固定關係。", correction: "檢查哪一句能包含其餘細節。" },
      { belief: "看到 for example 就表示後面內容是新主題。", whyWrong: "例子通常用來具體化前面的概念。", correction: "把例子放回前一句的類別測試。" },
      { belief: "一個例子可以證明 every 或 always。", whyWrong: "單一案例不能支持無例外的普遍結論。", correction: "讓結論強度不超過證據範圍。" },
      { belief: "分說句只要有相同名詞就一定相關。", whyWrong: "相同名詞可能出現在不同話題中。", correction: "比較句子實際在說的面向與功能。" },
    ],
    checks: [
      { prompt: "總說句應只涵蓋一個例子，還是涵蓋整段？", answer: "涵蓋整段", reason: "它提供所有分說與例子的共同主題。" },
      { prompt: "such as 後面通常接上位概念還是具體例子？", answer: "具體例子", reason: "這個片語把抽象類別轉成可辨認項目。" },
      { prompt: "一位學生騎車上學，能證明所有學生都騎車嗎？", answer: "不能", reason: "一個人的例子不足以支持全部學生的結論。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S276", "ENG_R4_S276", {
    objectives: ["能區分原因、結果、問題與解決方法在段落中的功能。", "能避免把先後發生誤判為因果，並檢查解法是否對準問題。"],
    sections: [
      { title: "原因回答 why，結果回答 what happened", content: "because、since 可引出原因，so、as a result 常引出結果。The road was wet because it rained 中，下雨是原因，道路濕是結果。換成 so 時，句序通常改為 It rained, so the road was wet。" },
      { title: "先後不等於因果", content: "Leo opened his book, and then the bell rang 只表示兩件事依序發生，不能推成 Leo 打開書造成鐘響。要主張因果，需有 because、therefore 或事件機制支持。" },
      { title: "問題先說明阻礙", content: "問題解決段落先指出目標受到什麼阻礙，例如 Students could not see the board clearly。解法應直接處理視線問題，如 moving the front desks closer，而不是更換午餐。" },
      { title: "檢查解法的結果與代價", content: "有效解法要改善原問題，且文章可能補充限制。The class moved the desks, so everyone could see, but the walk space became narrow。讀者需同時保留改善與新限制，不能只讀一半。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S276_EX_01", prompt: "The wind was strong, so the boat stayed near the land.", steps: ["so 前是強風。", "so 後是船的反應。", "判定強風造成不遠行的結果。"], answer: "Cause: strong wind; result: the boat stayed near land.", why: "連接詞明確把天氣條件與船的行動連起來，方向不能顛倒。" },
      { id: "ENG_R4_L_S276_EX_02", prompt: "The library line was long. A worker opened a second desk. The line moved faster.", steps: ["長隊伍是待解決問題。", "增開櫃檯是採取的方法。", "隊伍加快是解法後的結果。"], answer: "Problem → second desk → faster line.", why: "第二個服務點增加處理能力，直接回應排隊過久，而第三句提供改善證據。" },
      { id: "ENG_R4_L_S276_EX_03", prompt: "Mia had on a blue coat. Ten minutes later, the rain began.", steps: ["辨認兩件事的時間順序。", "檢查是否有因果詞。", "檢查穿外套是否能造成下雨。"], answer: "The reading shows time order, not cause.", why: "ten minutes later 只定位時間，沒有證據說藍外套導致天氣改變。" },
    ],
    misconceptions: [
      { belief: "so 後面的內容一定是原因。", whyWrong: "so 通常把前面原因帶到後面結果。", correction: "先問哪一件事解釋另一件事發生。" },
      { belief: "較早發生的事都造成較晚發生的事。", whyWrong: "時間順序本身不證明因果關係。", correction: "尋找因果詞、合理機制或明確說明。" },
      { belief: "任何正面行動都可當成問題的解法。", whyWrong: "解法必須處理文章指出的具體阻礙。", correction: "把解法的效果直接對回問題關鍵字。" },
      { belief: "問題解決後就可忽略 but 後的新限制。", whyWrong: "轉折後可能改變解法的整體評估。", correction: "同時記錄改善結果與剩餘代價。" },
    ],
    checks: [
      { prompt: "because 後通常提供原因還是結果？", answer: "原因", reason: "because 引出事情為何發生。" },
      { prompt: "兩件事用 then 連接，就一定有因果嗎？", answer: "不一定", reason: "then 只明示先後順序。" },
      { prompt: "教室太暗，增加照明是否對準問題？", answer: "是", reason: "增加光線直接改善看不清楚的阻礙。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S277", "ENG_R4_S277", {
    objectives: ["能依指示詞、重複概念與邏輯關係判斷插入句位置。", "能同時檢查插入句前後兩側，而非只配對一個關鍵字。"],
    sections: [
      { title: "插入句要有前接點", content: "以 This change、These animals、For this reason 開頭的句子，需要前文先提供 change、animals 或 reason 的內容。若把它放在相關資訊之前，指示詞就沒有清楚對象。" },
      { title: "也要有後接功能", content: "插入句不只回顧前文，也常為下一句鋪路。句子說 The new window also saved energy，後句若接 As a result, the school paid less for power，兩句形成特點到結果的關係。" },
      { title: "轉折與例子決定縫隙", content: "However 應放在可形成對比的兩句之間；For example 應放在一般概念之後、具體說明之前。先標示句子功能，再找前後關係都成立的位置。" },
      { title: "代入每個空格完整朗讀", content: "同一個名詞可能在多處出現，只有一處能讓代名詞、時態與邏輯同時順暢。逐一代入候選位置，檢查前句是否提供已知資訊、後句是否自然承接。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S277_EX_01", prompt: "Sentence to add: This small change saved ten minutes each morning. Reading: The family put all keys beside the door. [ ] No one had to look for a key before leaving.", steps: ["This small change 回指把鑰匙集中。", "saved ten minutes 應先於不用找鑰匙的說明。", "放入唯一空格後形成做法與結果。"], answer: "Add it between the two given sentences.", why: "前句提供 change 的內容，後句解釋節省時間的具體原因，兩側都能銜接。" },
      { id: "ENG_R4_L_S277_EX_02", prompt: "Sentence to add: However, the room became too hot in the afternoon. Reading: The large windows gave the room more light. [ ] The class then added a light cover.", steps: ["However 要對比 more light 的好處。", "too hot 提出新問題。", "added a cover 是對問題的處理。"], answer: "Place it after the first sentence.", why: "插入句把優點轉成熱度問題，後句的加裝遮蓋才有明確動機。" },
      { id: "ENG_R4_L_S277_EX_03", prompt: "Sentence to add: For example, students can borrow a ball at lunch. Reading: The new desk lends things for free. [ ] It also keeps board games for rainy days.", steps: ["For example 需要一般服務概念。", "借球是 lends things 的具體例子。", "It also 再增加另一項服務。"], answer: "Add the example before the last sentence.", why: "順序由總說、具例到另一項補充；若把例句放段首，讀者尚不知道它在例證什麼。" },
    ],
    misconceptions: [
      { belief: "只要插入句與某句都有 school，就可放在旁邊。", whyWrong: "重複名詞不足以建立完整邏輯。", correction: "同時檢查指示詞、句子功能與後續結果。" },
      { belief: "However 可以放在兩個意思相同的句子中間。", whyWrong: "However 需要前後存在可辨認的對比。", correction: "找出好處與限制、預期與實際等反向關係。" },
      { belief: "For example 句應永遠放在全文第一句。", whyWrong: "例子通常需要前文先提出上位概念。", correction: "先總說，再放能具體支持它的例子。" },
      { belief: "找到合理前句後，不必看插入句後面。", whyWrong: "錯誤位置也可能只在後接處露出問題。", correction: "每次都讀前句、插入句與後句三段。" },
    ],
    checks: [
      { prompt: "This result 之前需要什麼？", answer: "能產生該結果的事件或資料", reason: "this 必須回指已知內容。" },
      { prompt: "However 應連接相似還是對比資訊？", answer: "對比資訊", reason: "它提示讀者方向發生轉折。" },
      { prompt: "判斷空格時只讀前一句夠嗎？", answer: "不夠", reason: "插入句也必須讓後一句自然接續。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S278", "ENG_R4_S278", {
    objectives: ["能辨認開頭、發展、轉折與結尾段落的功能。", "能依段落間的承接關係建立全文架構並排除細節堆列。"],
    sections: [
      { title: "先為每段寫功能標籤", content: "讀完一段後，用短語標記功能，例如 introduce a problem、give two examples、show a change、state the result。功能標籤比抄整段更容易看出全文如何推進。" },
      { title: "開頭建立主題與閱讀問題", content: "開頭段常介紹人物、情境、主題或待回答問題。若第一段已直接說 In the past, the river was dirty，後段才能說居民採取什麼行動以及現在有何改變。" },
      { title: "中段負責發展而非重說", content: "中段可用例子、原因、比較或步驟展開主題。兩段若功能完全相同且資訊重複，可能需要合併；若一段提出方法、下一段提供結果，則兩者各有必要。" },
      { title: "結尾回收全文但不新增大主題", content: "結尾常回答開頭問題、概括結果或提出由全文支持的提醒。若最後突然介紹未曾出現的新人物和新事件，通常破壞架構；若回到主題並整合前文，則能完成全文。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S278_EX_01", prompt: "Part 1: A town had too much street trash. Part 2: Shops offered boxes for used cups. Part 3: Street trash fell by half.", steps: ["第一段提出問題。", "第二段說明方法。", "第三段提供結果。"], answer: "Problem → action → result.", why: "三段各負責一項必要功能，且後段逐步回答前段提出的問題。" },
      { id: "ENG_R4_L_S278_EX_02", prompt: "P1 introduces two kinds of school trips. P2 explains day trips. P3 explains trips with one night away. P4 compares their costs.", steps: ["第一段建立兩類。", "第二、三段平行分說。", "第四段在已介紹兩類後比較。"], answer: "Opening → type A → type B → comparing.", why: "讀者先知道分類，再分別理解每一類，最後才有足夠資訊比較成本。" },
      { id: "ENG_R4_L_S278_EX_03", prompt: "A reading asks why the lake looks green, explains tiny plants in the water, and ends by saying the color can change with plant numbers.", steps: ["開頭提出 why 問題。", "中段提供科學解釋。", "結尾把植物數量連回顏色變化。"], answer: "Question → reason → supported final idea.", why: "結尾沒有另開新題，而是用中段資訊回答開頭問題並限定結論。" },
    ],
    misconceptions: [
      { belief: "全文架構就是把每一個小細節照抄一次。", whyWrong: "細節清單看不出段落之間的功能關係。", correction: "先用問題、方法、例子、結果等功能詞概括。" },
      { belief: "只要是第一段，就一定是結論。", whyWrong: "多數文章先建立主題或問題。", correction: "看該段是否提出後文要發展的內容。" },
      { belief: "兩個中段都談同一主題，所以功能必定相同。", whyWrong: "一段可能說原因，另一段可能說結果。", correction: "比較每段在全文中完成的任務。" },
      { belief: "結尾越多新資訊越好。", whyWrong: "未鋪陳的大主題會使全文失去收束。", correction: "結尾應整合或回應前文，新增內容只能是自然延伸。" },
    ],
    checks: [
      { prompt: "問題、方法、結果三段中，哪一段通常先出現？", answer: "問題", reason: "讀者先知道阻礙，才理解方法為何需要。" },
      { prompt: "段落功能標籤應抄整段還是用短語概括？", answer: "用短語概括", reason: "短功能詞能顯示段落間的關係。" },
      { prompt: "結尾可以完全離開全文主題嗎？", answer: "不可以", reason: "結尾需回收已建立的問題、發展或證據。" },
    ], assets: [],
  }),
];

export const ENGLISH_U41_QUESTIONS = [
  ...skillQuestions("273", [
    q("Nora found a wet puppy beside the road. She carried it home and dried it with a towel. Later, its owner came for it. What happened first?", ["Nora found the puppy.", "The owner came.", "The puppy was dried.", "Nora returned the towel."], 0, ["故事第一句先交代 Nora 發現小狗。", "主人前來由 later 標示為較晚事件。", "擦乾小狗發生在帶回家之後。", "文章沒有提到歸還毛巾。"], ["起點由首句的完整事件直接確定。", "其餘選項或發生較晚，或不在文本中。"], ["u41-s273-q01-locate-opening-event", "separate-first-event-from-later-actions"], "short-narrative-first-event", ["choose-most-important-as-first"]),
    q("(A) At last, the kite rose above the trees. (B) First, Ken fixed the broken string. (C) Next, he waited for a strong wind. Which order tells the event correctly?", ["A → B → C", "B → C → A", "C → A → B", "B → A → C"], 1, ["風箏升起是結果，不能在修線以前。", "先修線、再等風、最後升起符合路標。", "先等風不能解釋之後才修斷線。", "at last 應放在 next 事件之後。"], ["三個明示時間詞建立唯一排列。", "事件必要關係也支持第二個選項。"], ["u41-s273-q02-order-three-marked-events", "align-first-next-at-last"], "sentence-order-set", ["place-at-last-first"]),
    q("On Tuesday morning, Mia left bread on the table. That afternoon, she found only an empty plate. When was the plate found?", ["Monday afternoon", "Tuesday morning", "Tuesday afternoon", "Wednesday afternoon"], 2, ["前文沒有星期一。", "早上是放麵包的時間。", "that afternoon 承接星期二並移到下午。", "that 不會自動改成隔日。"], ["日期框架由 Tuesday 建立。", "時段回指把答案限定為同日下午。"], ["u41-s273-q03-resolve-that-afternoon", "keep-day-frame-across-time-reference"], "day-part-reference", ["move-that-to-next-day"]),
    q("Leo locked the shop, walked to the bus stop, and then noticed his key was still inside. Which event cannot come before he locked the shop?", ["He owned a key.", "He was at the shop.", "The key was inside.", "He noticed the key problem."], 3, ["擁有鑰匙可早於關店。", "人在店裡是關店前的合理狀態。", "鑰匙留在店內可在鎖門前已成立。", "then 明確把察覺問題放在鎖店與走到站牌之後。"], ["問題詢問受文本限制的較晚事件。", "只有察覺由 then 鎖定在關店之後。"], ["u41-s273-q04-find-event-forced-after-locking", "distinguish-state-from-discovery-time"], "narrative-boundary-question", ["confuse-existing-state-with-notice-time"]),
    q("Amy washed the apples before she cut them. She put the pieces in a bowl after that. Which action was second?", ["She cut the apples.", "She put the pieces in a bowl.", "She washed the bowl.", "She ate the apples."], 0, ["before 建立先洗後切，所以切是第二步。", "放入碗中是 after that 指出的第三步。", "文本沒有洗碗事件。", "文本沒有說她吃了蘋果。"], ["兩個連接詞共同建立三步鏈。", "答案保留動作受詞，不加入未寫事件。"], ["u41-s273-q05-identify-middle-action", "combine-before-and-after-that"], "action-chain-middle-step", ["choose-final-container-action"]),
    q("The class reached the hill at nine. Half an hour later, they began to draw the view. They left at eleven. How long after arriving did they start drawing?", ["Two hours", "Thirty minutes", "Nine minutes", "Eleven minutes"], 1, ["兩小時接近整段停留，不是開始等待。", "half an hour 等於三十分鐘。", "九是抵達時刻，不是經過時間。", "十一是離開時刻的一部分。"], ["時間詞直接給出抵達到作畫的間隔。", "時鐘數字與經過時間已分開處理。"], ["u41-s273-q06-convert-half-hour-delay", "separate-clock-time-from-duration"], "elapsed-time-in-narrative", ["subtract-unrelated-departure-time"]),
    q("A seed was placed in wet soil. ___ A green shoot then came out of the soil. Which sentence best fills the time gap?", ["The flower was sold at a market.", "The pot had always been blue.", "For several days, the soil was kept wet.", "The seed returned to its bag."], 2, ["販售花朵跳到尚未出現的結果。", "花盆顏色不推進種子生長。", "持續保持濕潤自然連接播種與發芽。", "把種子放回袋中會中止已建立的過程。"], ["缺句需要填補播種到發芽的時間發展。", "第三項同時維持對象與事件方向。"], ["u41-s273-q07-fill-growth-time-gap", "select-bridge-event-between-start-and-result"], "narrative-gap-completion", ["insert-related-noun-without-sequence-role"]),
    q("Friday: Tara borrowed a book. Saturday: she finished it. Monday: she returned it. Which statement matches the timeline?", ["Tara returned the book before reading it.", "She borrowed and returned it on Friday.", "She read it after Monday.", "She kept the book through the weekend."], 3, ["完成閱讀在歸還之前。", "借與還分別在星期五和星期一。", "她星期六已讀完。", "從星期五到週末結束，書仍由她借用。"], ["三個日期已按週序比較。", "through the weekend 準確概括借閱跨越週末。"], ["u41-s273-q08-summarize-dated-timeline", "infer-state-across-weekend"], "dated-event-timeline", ["collapse-separated-dates"]),
    q("Paragraph 1: A family planned a garden. Paragraph 2: They cleared a sunny corner. Paragraph 3: Vegetables were ready in summer. Which event belongs between clearing the corner and the summer result?", ["They planted seeds in the clean soil.", "They moved away before spring.", "They covered the corner with stone.", "They decided never to grow food."], 0, ["播種能連接整理土地與夏季收成。", "搬走會切斷後續照料。", "鋪滿石頭不支持蔬菜生長。", "放棄種植與結局衝突。"], ["中間事件必須使結果可達成。", "第一項補上園藝因果鏈中的必要步驟。"], ["u41-s273-q09-supply-missing-garden-event", "complete-causal-sequence-across-paragraphs"], "paragraph-sequence-gap", ["select-thematic-but-blocking-action"]),
    q("Ben waited until the rain stopped. He left the cafe and walked home under a clear sky. What happened immediately before Ben left?", ["He reached home.", "The rain stopped.", "The sky became dark at home.", "He ordered dinner."], 1, ["到家發生在離開與步行之後。", "until 把停止下雨設為離開前的界線。", "文本說天空晴朗，沒有變暗事件。", "文章未提點餐。"], ["until 建立等待結束與下一動作的緊鄰關係。", "第二項是唯一由句法與內容同時支持的事件。"], ["u41-s273-q10-find-event-before-departure", "interpret-until-as-action-boundary"], "immediate-predecessor", ["choose-later-destination-event"]),
    q("A repair note says: 8:10 — problem reported; 8:25 — worker arrived; 8:40 — power turned off; 9:15 — repair finished. What was the last event before the repair work could safely begin?", ["The problem was reported.", "The repair was finished.", "The power was turned off.", "The worker arrived."], 2, ["通報是最早事件，仍未處理電源。", "修理完成在工作開始之後。", "關閉電源是安全開始修理前最後列出的事件。", "工作者到場早於關閉電源。"], ["時間表須結合安全前置條件判讀。", "答案找的是開始工作前最後必要步驟，不是最早準備。"], ["u41-s273-q11-integrate-log-times-with-safety", "identify-final-prerequisite-event"], "service-log-sequence", ["choose-worker-arrival-as-automatic-start"]),
    q("A diary has these lines: 'I put the letter in my bag.' 'At the post office, the bag was empty.' 'Back at home, I saw the letter on my desk.' Which conclusion best respects the event order?", ["The post office sent the letter back.", "The writer mailed the letter before leaving home.", "The desk was inside the post office.", "The letter did not stay in the bag when the writer left home."], 3, ["信件從未交給郵局，無法被退回。", "郵局時袋中沒有信，不能證明已寄出。", "最後一句明說回到家才在書桌看到。", "原先放入袋中，後來在家中書桌，表示離家時未成功帶走。"], ["結論保留三個地點與發現順序。", "第四項不杜撰信件如何離開袋子，只說文本能支持的結果。"], ["u41-s273-q12-draw-bounded-sequence-conclusion", "track-object-state-across-locations"], "diary-object-timeline", ["invent-unseen-mailing-event"]),
  ]),
  ...skillQuestions("274", [
    q("Which sentence should come before 'It had one white foot and a long tail'?", ["A black cat came into the yard.", "The yard was quiet after lunch.", "We put water near the tree.", "Our neighbor closed her window."], 0, ["這句先介紹單數動物，It 可清楚回指黑貓。", "yard 是地點，沒有腳與尾巴。", "water 無法合理擁有腳和尾巴。", "neighbor 是人，不符合後句的動物特徵。"], ["先行詞需同時符合單數形式與語意特徵。", "第一項讓後句的 It 只有一個合理對象。"], ["u41-s274-q01-supply-animal-antecedent", "match-pronoun-number-and-features"], "antecedent-selection", ["choose-nearest-place-noun"]),
    q("(A) These lights use less power. (B) The school changed every old lamp in the hall. (C) The change also made the hall brighter. Which order is clearest?", ["A → C → B", "B → A → C", "C → B → A", "B → C → A"], 1, ["These lights 出現時尚未介紹燈。", "先說換燈，再說這些燈省電，最後概括改變的另一效果。", "The change 在段首沒有已知改變可回指。", "C 緊接 B 尚可，但 A 的 These lights 被隔開且省電與 also 關係顛倒。"], ["完整名詞先建立對象，指示詞再承接。", "第二個排列也讓 also 自然增加第二項效果。"], ["u41-s274-q02-order-known-information-chain", "sequence-full-noun-these-and-change"], "three-sentence-reference-order", ["open-with-demonstrative-reference"]),
    q("Mina found a map under a chair. The map showed a path to a small lake. This path crossed two fields. What does 'This path' mean?", ["The chair", "The small lake", "The path on the map", "The map itself"], 2, ["椅子是發現地點，不是路線。", "湖是路徑通往的目的地。", "第二句新介紹的 path 正是指示詞承接對象。", "地圖展示路徑，但本身不是穿越田地的道路。"], ["資訊鏈由 map 推進到 path。", "語意動作 crossed fields 也排除物品地圖。"], ["u41-s274-q03-resolve-this-path", "follow-new-to-given-information"], "demonstrative-reference", ["choose-most-recent-any-noun"]),
    q("Rita told Eva that she had won the photo contest. The sentence alone does not say who won. Which revision makes Eva the winner?", ["Rita told Eva about the contest.", "She told her that the contest was over.", "Rita, who won, told Eva the news.", "Rita said to Eva, 'You won the photo contest.'"], 3, ["這個改寫刪除了得獎者資訊。", "兩個代名詞仍未指定得獎者。", "關係子句明確把 Rita 設為得獎者。", "直接引語中的 You 指向 Eva，清楚指定她得獎。"], ["修訂目標是消除 she 的雙重可能。", "第四項利用說話對象與第二人稱提供唯一指涉。"], ["u41-s274-q04-revise-ambiguous-winner", "replace-unclear-pronoun-with-direct-address"], "ambiguity-repair", ["assume-nearest-female-antecedent"]),
    q("The team moved its meeting from noon to four because two members had class. This change allowed everyone to attend. What is 'This change'?", ["Moving the meeting to four", "Having a class at noon", "Joining a different team", "Adding two new members"], 0, ["前句唯一的安排改變就是把會議移到四點。", "上課是改期原因，不是 change 本身。", "文章沒有換隊資訊。", "two members 是原成員，不是新增人員。"], ["指示詞回指前句的完整調整事件。", "答案區分造成改變的理由與改變內容。"], ["u41-s274-q05-identify-this-change-event", "separate-change-from-cause"], "event-reference", ["refer-this-to-nearest-number"]),
    q("A paragraph begins, 'The shop has a new way to return bottles.' Which next sentence best treats the idea as known information?", ["A new shop opened near the river.", "The new way gives customers a point for each bottle.", "Some bottles are green and some are clear.", "People often carry water on hot days."], 1, ["這介紹另一家店，沒有承接退瓶方式。", "The new way 明確回指前句已介紹的方法並補充運作。", "瓶子顏色沒有說明該方式。", "炎熱天氣與退瓶制度沒有資訊鏈。"], ["限定詞 The 將既有 idea 轉成後句主題。", "第二項增加新細節而不改換對象。"], ["u41-s274-q06-extend-known-return-system", "use-the-to-maintain-topic"], "given-information-continuation", ["repeat-topic-word-with-unrelated-detail"]),
    q("Sentence to insert: 'They carried the boxes to the school hall.' Text: Students collected books from each classroom. [ ] In the hall, the books were placed on long tables. Where does the sentence belong?", ["Before students collected books", "After the books were placed on tables", "Between the two given sentences", "The sentence cannot belong in this text"], 2, ["They 在段首沒有已介紹的 students 可回指。", "放到最後會先在會堂擺書，再把箱子搬過去。", "They 回指學生，the boxes 承接收集結果，且帶出 hall。", "句子正好補上教室到會堂的移動。"], ["插入句前後各有一個清楚接點。", "第三項維持人物、物品與地點的資訊推進。"], ["u41-s274-q07-insert-pronoun-location-bridge", "connect-students-boxes-and-hall"], "reference-based-insertion", ["check-only-pronoun-not-next-location"]),
    q("Sam put the cup beside the phone after it fell. Why is the sentence unclear?", ["A cup cannot be beside a phone.", "Sam cannot move a cup.", "The sentence has no past-time verb.", "Either the cup or the phone may be what fell."], 3, ["兩件物品可以相鄰。", "put 已表明 Sam 能移動杯子。", "put 與 fell 都可表過去事件。", "it 在兩個單數物品後沒有足夠線索限定先行詞。"], ["不清楚之處是代名詞對象，而非事件可行性。", "第四項完整列出兩個文法與語意上可行的候選。"], ["u41-s274-q08-diagnose-object-pronoun-ambiguity", "recognize-two-valid-antecedents"], "ambiguous-object-reference", ["force-it-to-nearest-phone"]),
    q("We visited a farm that grows tea. The tea plants covered the lower hill. Their leaves were picked by hand. What information chain holds the paragraph together?", ["farm → tea plants → their leaves", "visit → lower → hand", "we → hill → farm", "tea → visited → covered"], 0, ["每一項先被介紹，再成為下一句的已知主題。", "三個詞不是可回指的同一對象鏈。", "we 與 hill 沒有所有關係可接到 farm。", "動作與名詞被任意重排，無法顯示指涉。"], ["段落先縮小到農場中的茶樹，再到葉子。", "所有格 their 清楚把 leaves 接回 plants。"], ["u41-s274-q09-trace-nested-information-chain", "map-whole-place-to-plants-to-parts"], "paragraph-reference-chain", ["list-repeated-words-without-reference"]),
    q("A notice says, 'New students should meet the guides at Gate 2. They will lead the group to the main room.' Who will lead the group?", ["The new students", "The guides", "The gate workers", "The people already in the main room"], 1, ["新生是被帶領的 group，不是明示帶領者。", "複數 guides 是前句中能執行 lead 的合理對象。", "公告沒有介紹 gate workers。", "主教室內的人尚未在文本出現。"], ["代名詞數量與動作角色共同限定 guides。", "答案不只依最近名詞，也檢查誰能帶隊。"], ["u41-s274-q10-resolve-they-in-notice", "combine-plural-agreement-with-agent-role"], "notice-pronoun-reference", ["choose-target-group-as-agent"]),
    q("Original: 'Jo showed Kim the cracked bowl before she packed it.' The writer means Jo packed the bowl. Which change is clearest?", ["Jo showed Kim it before she packed the bowl.", "She showed her the bowl before packing it.", "Before Jo packed the cracked bowl, she showed it to Kim.", "The cracked bowl was shown before she packed it."], 2, ["she 仍可能回指 Kim。", "兩個人物都被代名詞取代，使指涉更差。", "Jo 在時間子句中明示為 packed 的執行者。", "被動句仍沒有說清楚 she 是誰。"], ["修訂需同時保留展示先於打包與 Jo 的角色。", "第三項以重複名字換取必要清楚度。"], ["u41-s274-q11-repair-packer-reference", "repeat-name-to-preserve-agent"], "pronoun-revision", ["avoid-repeating-name-even-when-needed"]),
    q("Four lines appear in a guide: (1) This rule keeps the room quiet. (2) Visitors may use the study room. (3) The rule asks everyone to silence phones. (4) It also asks people to speak softly. Which line should open the paragraph?", ["Line 1", "Line 3", "Line 4", "Line 2"], 3, ["This rule 尚未被介紹。", "The rule 也假設讀者已知是哪一條規則。", "It 在段首沒有先行詞。", "Line 2 先建立 study room 情境，之後才能介紹其中規則。"], ["四個候選中只有第四行不依賴前文指涉。", "開頭先給場所與使用者，後續規則才有框架。"], ["u41-s274-q12-select-independent-opening-line", "identify-sentence-without-back-reference"], "paragraph-opening-choice", ["open-with-this-rule"]),
  ]),
  ...skillQuestions("275", [
    q("Our town library serves people outside its building. A van brings books to far villages. Workers also take story boxes to hospitals. Which sentence is the general statement?", ["Our town library serves people outside its building.", "A van brings books to far villages.", "Workers take story boxes to hospitals.", "Hospitals are far from every village."], 0, ["第一句涵蓋後面兩種館外服務。", "這只是送書到村落的一項方式。", "這只是醫院故事箱的另一項方式。", "文本沒有比較醫院與村落距離。"], ["總說需能同時包含兩個後續細節。", "第一項提出共同概念而未侷限單一地點。"], ["u41-s275-q01-identify-general-library-service", "distinguish-topic-from-two-examples"], "general-detail-paragraph", ["choose-most-concrete-detail"]),
    q("Many small actions can save water at home. Which sentence is a fitting example?", ["Water covers much of the earth.", "Turn off the water while brushing your teeth.", "The kitchen window faces east.", "Some cups are made of glass."], 1, ["這是關於地球水量的一般事實，不是居家節水動作。", "刷牙時關水是個人可做的具體節水行動。", "窗戶方向不影響用水。", "杯子材質沒有說明如何少用水。"], ["例子必須同時符合 small action、save water 與 at home。", "第二項把抽象建議轉成可執行行為。"], ["u41-s275-q02-select-home-water-saving-example", "test-example-against-three-part-category"], "example-selection", ["match-only-water-topic"]),
    q("The first sentence says, 'The night market offers food for many tastes.' The next lines name rice meals, fruit drinks, and hot soup. What do the next lines do?", ["Explain why the market closes", "Compare the market with a farm", "Give kinds of food and drink that support the first sentence", "Introduce a new topic about cooking at home"], 2, ["營業時間沒有出現。", "文本未提農場。", "三類品項具體展開 many tastes。", "清單仍在夜市食物主題內。"], ["分說內容與總說的 food for many tastes 逐項對應。", "第三項正確描述列舉功能而非重述內容。"], ["u41-s275-q03-name-function-of-market-list", "link-listed-items-to-general-claim"], "detail-function-question", ["treat-list-as-topic-change"]),
    q("A report says, 'One student used the new path and reached school five minutes sooner.' Which conclusion goes too far?", ["The path helped that student on that trip.", "The student reached school sooner than usual.", "The report gives one example of path use.", "The path always saves every student five minutes."], 3, ["單一案例直接支持這次有幫助。", "五分鐘較快就是 sooner 的具體結果。", "文本確實只提供一位學生的案例。", "one student 不能支持 always 與 every student。"], ["結論強度需受樣本數與時間範圍限制。", "第四項同時把個案擴張成人群與永久規則。"], ["u41-s275-q04-detect-overgeneralization-from-one-student", "compare-evidence-scope-with-every-always"], "evidence-scope", ["treat-one-example-as-universal-proof"]),
    q("Details: The roof keeps rain off the reading tables. Tall trees keep the area cool. Small lights make evening reading possible. Which topic sentence covers all three?", ["The outdoor reading area works in different weather and times.", "Rain is common every evening.", "The trees are older than the library.", "Readers prefer tables without a roof."], 0, ["屋頂、樹蔭與燈光共同讓空間在不同條件下可用。", "文本沒有說每天晚上下雨。", "樹齡未提供，也不能涵蓋屋頂和燈。", "細節反而顯示有屋頂的桌區可使用。"], ["主題句需概括三種設計帶來的共同功能。", "第一項涵蓋天氣、白天熱度與晚間使用。"], ["u41-s275-q05-build-topic-sentence-from-three-details", "abstract-shared-function-across-features"], "topic-sentence-construction", ["summarize-only-first-detail"]),
    q("Paragraph topic: Ways a school cuts food waste. Which sentence does not belong?", ["Students take only the amount they can eat.", "The gym floor was painted blue last summer.", "Unopened fruit is placed on a share table.", "The kitchen counts what is left each day."], 1, ["控制取餐量能減少剩食。", "體育館地板顏色與食物浪費無關。", "分享未開封水果可避免丟棄。", "記錄剩餘量有助掌握浪費。"], ["不相關句即使是學校資訊，也不支持指定主題。", "第二項缺少 food 或 waste 的功能連結。"], ["u41-s275-q06-remove-off-topic-school-detail", "separate-shared-setting-from-paragraph-purpose"], "irrelevant-detail-detection", ["keep-any-sentence-about-school"]),
    q("Some jobs begin before most people wake up. Which example best develops the idea?", ["Many people enjoy sleeping late on holidays.", "A baker sells bread in the afternoon.", "A bus driver starts the first route at five in the morning.", "An office has large windows."], 2, ["這談休假睡眠，不是工作開始時間。", "下午不符合 before most people wake up。", "清晨五點開始首班路線是明確工作例子。", "窗戶特徵與上班時間無關。"], ["例證要呈現一項 job 以及極早 start time。", "第三項具體而不把一例擴成所有司機。"], ["u41-s275-q07-choose-early-job-example", "match-example-to-time-based-generalization"], "generalization-example-match", ["select-sentence-with-job-only"]),
    q("The center has free activities for families. For example, families can paint together on Sunday. What does the example prove?", ["Every activity is art.", "The center is open every day.", "All families visit on Sunday.", "At least one free family activity is offered."], 3, ["一個繪畫例子不代表所有活動都是藝術。", "星期日活動不能證明每日開放。", "提供活動不表示所有家庭都參加。", "例句確實證明至少存在一項家庭活動。"], ["例子的最低充分結論是存在該類的一個成員。", "第四項避免加入全稱或固定出席推論。"], ["u41-s275-q08-state-minimum-proof-from-example", "limit-example-to-existence-claim"], "example-proof-boundary", ["upgrade-some-to-all"]),
    q("General idea: Things visitors can learn at the sea center. Detail groups: (1) fish homes, (2) safe ways to clean beaches, (3) how boats read weather signs. What structure is used?", ["One general idea followed by three learning areas", "A problem followed by one answer", "A story told from ending to beginning", "Two opinions with no shared subject"], 0, ["三組細節都屬於 visitors can learn 的分說。", "沒有單一問題與解法配對。", "清單不是按故事事件排列。", "三項有共同的海洋中心學習主題。"], ["先辨認總說，再計算其下平行面向。", "第一項準確描述一對多的段落層次。"], ["u41-s275-q09-classify-general-three-detail-structure", "recognize-parallel-subtopics"], "text-structure-identification", ["mistake-list-for-narrative"]),
    q("Four sentences form a paragraph: (A) One change helps birds find food. (B) People can make city yards better for birds. (C) For example, growing local plants brings more small insects. (D) A shallow water dish is another helpful change. Which sentence should introduce the paragraph?", ["Sentence A", "Sentence B", "Sentence C", "Sentence D"], 1, ["One change 需要前文先建立改變的類別。", "B 提出可涵蓋後面各種改善做法的總說。", "For example 明示它依賴前文概念。", "another 表示先前已有一項改變。"], ["開頭句不能依賴 one、for example 或 another 的回指。", "第二項是唯一獨立且範圍足夠的總說。"], ["u41-s275-q10-select-general-opening-among-dependent-details", "use-discourse-markers-to-order-general-and-examples"], "paragraph-introduction-order", ["open-with-for-example"]),
    q("A guide says, 'Keep a small repair set at home: a light, tape, and simple tools.' What is the role of the three named items?", ["They are three homes.", "They are steps that must happen in that order.", "They are examples of things in the repair set.", "They are reasons repairs should never be tried."], 2, ["清單是物品，不是住家。", "逗號列舉沒有建立操作順序。", "冒號後把 repair set 具體化成三類物品。", "文本建議準備工具，沒有禁止修理。"], ["標點與上位名詞共同顯示例證功能。", "第三項不把並列清單誤讀成程序。"], ["u41-s275-q11-interpret-colon-example-list", "distinguish-items-from-ordered-steps"], "list-function", ["read-any-list-as-sequence"]),
    q("A poster claims, 'Students like the longer lunch break.' Its only support is, 'Three students near the gate said they liked it.' Which response best evaluates the support?", ["It proves every student likes the break.", "It proves students at every school agree.", "It proves the break is longer than one hour.", "It gives a positive example but not enough evidence for all students."], 3, ["三位學生不足以代表全校。", "資料只來自一所學校的一小群人。", "支持句沒有提供休息長度。", "它能顯示有人喜歡，但無法支撐廣泛主張。"], ["評估同時承認例子的有效部分與代表性限制。", "第四項讓結論範圍與證據人數保持一致。"], ["u41-s275-q12-evaluate-small-example-against-broad-claim", "balance-support-value-and-sampling-limit"], "claim-example-evaluation", ["reject-all-evidence-or-accept-universal-claim"]),
  ]),
  ...skillQuestions("276", [
    q("The outdoor concert moved inside because dark clouds brought heavy rain. What caused the move?", ["Heavy rain", "The indoor stage", "The concert music", "The audience seats"], 0, ["because 後明示大雨是改到室內的原因。", "室內舞台是新地點的一部分，不是移動原因。", "音樂內容沒有造成場地變更。", "座位未被描述成問題。"], ["因果方向由 because 與 move inside 共同決定。", "第一項回答 why，而非移動後的狀態。"], ["u41-s276-q01-identify-rain-cause", "separate-cause-from-new-setting"], "explicit-cause-question", ["choose-result-location-as-cause"]),
    q("The shop put clear labels on every box, so workers found orders faster. What was the result of the labels?", ["The boxes became heavier.", "Workers found orders faster.", "The shop sold every box.", "Workers stopped using labels."], 1, ["標籤不會由文本推成重量增加。", "so 後直接寫出找訂單更快的結果。", "文章沒有銷售箱子的事件。", "結果依賴標籤使用，並非停止使用。"], ["題目要求結果，需讀取 so 後分句。", "第二項保留 faster 的比較意義。"], ["u41-s276-q02-extract-label-result", "read-so-clause-as-effect"], "cause-effect-result", ["repeat-cause-instead-of-effect"]),
    q("Tina opened the window. A minute later, a bird landed on the roof. What can the text show for sure?", ["Opening the window called the bird.", "The bird opened the window.", "The window opened before the bird landed.", "The bird had waited inside the room."], 2, ["時間接近不能證明窗戶吸引鳥。", "主詞 Tina 明確執行開窗。", "a minute later 只確定兩事件先後。", "鳥原先位置未提供。"], ["文本提供時間證據但沒有因果機制。", "第三項是唯一不超過 later 所支持範圍的結論。"], ["u41-s276-q03-limit-later-to-sequence", "reject-post-event-causal-assumption"], "sequence-versus-cause", ["turn-temporal-order-into-causation"]),
    q("Problem: Wheelchairs could not pass between the cafe tables. Which change directly solves the problem?", ["Add music near the door.", "Print a longer menu.", "Paint every table green.", "Move the tables farther apart."], 3, ["音樂不會增加通道寬度。", "菜單長度與通行無關。", "顏色不改變桌距。", "拉開桌子能直接形成較寬通道。"], ["解法必須對準 cannot pass 與 between tables。", "第四項改變造成阻礙的空間條件。"], ["u41-s276-q04-match-access-problem-to-solution", "map-obstacle-to-physical-change"], "problem-solution-match", ["choose-positive-but-unrelated-improvement"]),
    q("The school garden was healthy, but students often forgot which class should water it. They made a weekly chart, and missed watering days became rare. What was the original problem?", ["The watering duty was unclear.", "The plants received too much sun.", "The chart was too large.", "The garden had no students."], 0, ["忘記輪到哪班澆水就是責任安排不清。", "文本說花園健康，未提陽光過多。", "表格大小沒有出現。", "學生正是照顧花園的人。"], ["原問題需能解釋為何 weekly chart 有效。", "第一項與忘記班級責任直接對應。"], ["u41-s276-q05-reconstruct-original-duty-problem", "infer-problem-from-solution-and-outcome"], "problem-identification", ["mistake-tool-feature-for-problem"]),
    q("A reading room is too noisy during lunch. Which plan fails to address that problem?", ["Put a quiet sign at the entrance.", "Buy brighter lamps for the tables.", "Open a separate talking area.", "Ask visitors to silence phones."], 1, ["安靜標示直接提醒進入者。", "更亮的燈改善視線，卻不降低聲音。", "另設交談區可把談話移開。", "手機靜音能減少鈴聲。"], ["題目要求找未處理 noise 的方案。", "第二項可能有益，但利益屬於另一個問題。"], ["u41-s276-q06-find-solution-target-mismatch", "separate-lighting-benefit-from-noise-control"], "solution-relevance", ["accept-any-room-improvement-as-solution"]),
    q("The bus arrived late because a tree blocked the road. As a result, Maya missed the opening song. Which chain is correct?", ["Missed song → blocked road → late bus", "Late bus → missed song → blocked road", "Blocked road → late bus → missed song", "Blocked road → missed song → bus arrived early"], 2, ["結果被錯放成最早原因。", "道路阻塞應先於公車延誤。", "樹阻路造成晚到，晚到再造成錯過歌曲。", "文本說公車晚到，不是早到。"], ["兩組因果詞串成三節鏈。", "第三項保持每一箭頭的原因與結果方向。"], ["u41-s276-q07-order-two-stage-causal-chain", "combine-because-and-as-a-result"], "multi-step-cause-chain", ["reverse-causal-direction"]),
    q("The town added evening buses, so more workers could ride home. However, each trip cost the town extra money. Which statement includes both the benefit and the cost?", ["The buses helped no one and cost nothing.", "Workers paid all town costs.", "The buses ran only in the morning.", "Evening travel improved, but the service required more money."], 3, ["第一句明示更多工作者受益，且後句有額外成本。", "沒有資料說工作者負擔全部成本。", "服務新增於 evening。", "第四項同時保留改善與 however 後的代價。"], ["完整評估不能省略轉折任一側。", "答案概括兩個結果而未增加付款來源。"], ["u41-s276-q08-summarize-benefit-and-cost", "integrate-positive-effect-with-drawback"], "solution-tradeoff", ["report-only-benefit"]),
    q("The path was covered with ice; therefore, the park closed it for the morning. Which word best describes the relation?", ["The ice caused the closing.", "The closing caused the ice.", "The two events happened in different parks.", "No relation is given."], 0, ["therefore 把結冰條件連到封閉結果。", "因果方向被顛倒。", "文本只有同一條 park path。", "連接詞已明示關係。"], ["分號前提供理由，therefore 後提供決定。", "第一項用最少資訊準確重述因果。"], ["u41-s276-q09-interpret-therefore-relation", "map-punctuation-linked-cause-and-decision"], "causal-connector-meaning", ["ignore-explicit-causal-marker"]),
    q("Because the room had only six chairs, two guests stood by the wall. Which phrase names the effect?", ["Because the room", "two guests stood by the wall", "only six chairs", "the room had"], 1, ["這只是原因子句的開頭。", "缺少座位造成兩位客人站立。", "六張椅子是限制原因。", "不完整片語沒有表達結果事件。"], ["效果是由座位不足所造成的完整事件。", "第二項包含結果的主詞、動作與地點。"], ["u41-s276-q10-locate-effect-clause", "distinguish-cause-noun-from-result-event"], "cause-effect-clause-role", ["select-number-as-effect"]),
    q("A cafe changed its cups on Monday. Sales rose on Tuesday. Which new fact would most strongly support the claim that the cup change helped sales?", ["Tuesday was after Monday.", "The cups and the walls were both white.", "Customers said the new cups made drinks easier to carry, and many bought a second drink.", "A nearby shop sold fewer books that week."], 2, ["單純先後仍不足以建立原因。", "共同顏色與購買行為沒有機制連結。", "顧客回應與第二次購買提供從杯子到銷售的直接路徑。", "書店銷售屬於不同商品與場所。"], ["較強支持需要合理機制加上相關行為證據。", "第三項仍是支持而非絕對證明，但比時間先後更有力。"], ["u41-s276-q11-add-mechanism-to-causal-claim", "compare-strength-of-causal-evidence"], "causal-evidence-selection", ["treat-after-as-proof-of-because"]),
    q("A community fridge often runs out of food before evening. Records show that most food is taken by noon, while many donors can come only after work. Which plan best uses the evidence?", ["Close the fridge at noon.", "Remove the record book.", "Ask donors to bring less food.", "Add an evening delivery time and tell users when new food arrives."], 3, ["中午關閉會讓晚間需要者更難取得食物。", "刪除紀錄不會增加食物。", "要求捐得更少會加重不足。", "晚間補貨對準捐贈者時間，也把供應資訊告知使用者。"], ["解法需同時回應午前取完與捐贈者晚到兩項資料。", "第四項從證據建立可執行且不與目標衝突的安排。"], ["u41-s276-q12-design-evidence-based-fridge-solution", "integrate-demand-time-and-donor-time"], "problem-data-solution-transfer", ["choose-action-that-worsens-shortage"]),
  ]),
  ...skillQuestions("277", [
    q("Sentence to insert: 'This choice kept the books dry.' Text: The club moved its book sale from the yard to the hall. [A] Rain began before noon. [B] More visitors came after lunch. [C] Where should the sentence go?", ["At A", "At B", "At C", "Before the first sentence"], 0, ["This choice 回指移到會堂，接著下雨說明選擇的價值。", "放在雨後仍可回指，但會切斷下雨與訪客增加的時間發展，且效果應先交代。", "段末才解釋 choice，與原因距離過遠。", "choice 在移動決定以前沒有對象。"], ["前句提供選擇內容，後句提供需要防雨的情境。", "A 位置讓指涉與效果最緊密。"], ["u41-s277-q01-place-this-choice-after-decision", "link-decision-to-protective-effect"], "labeled-sentence-insertion", ["place-reference-before-antecedent"]),
    q("Sentence to insert: 'However, the boxes were too heavy for younger students.' Text: The class packed all the food quickly. [A] They planned to carry it to the bus. [B] A teacher found two small carts. [C] The carts made the trip easy. [D] Which position is best?", ["A", "B", "C", "D"], 1, ["在計畫搬運前提出重量問題，尚未建立 boxes 要被搬走的需求。", "計畫搬運後出現困難，再接老師找到推車的解法。", "放在找到推車後會割裂解法與效果。", "段末才提問題，順序成為先解決再說明阻礙。"], ["However 形成計畫與實際困難的轉折。", "B 位置也為下一句推車解法提供原因。"], ["u41-s277-q02-insert-obstacle-before-cart-solution", "use-however-to-open-problem-slot"], "problem-bridge-insertion", ["attach-however-to-unrelated-speed"]),
    q("Sentence to insert: 'For example, one wall shows how the river changed over fifty years.' Text: The town museum has displays about local history. [A] Many students visit with their classes. [B] Each display uses old pictures and short notes. [C] Visitors may ask workers questions. [D] Where does the example fit best?", ["A", "B", "C", "D"], 2, ["A 之後會使例子看似說明學生參訪，而非 displays。", "B 前尚可接 museum displays，但下一句才介紹 display 的呈現方式，具體例子放在該句後更完整。", "C 位置讓 one wall 具體化前句的 each display，並維持展示主題。", "D 前是詢問服務，河流牆面不例證提問。"], ["例句應緊接可被具體化的展示說明。", "C 使上位概念、呈現方式與一項實例連續。"], ["u41-s277-q03-position-museum-display-example", "attach-for-example-to-display-description"], "example-sentence-insertion", ["attach-example-to-nearest-visitor-sentence"]),
    q("Sentence to insert: 'It also has a low shelf for children.' Text: The waiting room has a table with free magazines. [A] The windows face the garden. [B] Tea is sold near the door. [C] Families often wait here. [D] Where should it go?", ["After A", "After B", "After C", "At A"], 3, ["在窗戶句後，It 容易錯指 windows 或 garden。", "在茶販售句後，It 的先行詞不清楚。", "在 families 後，It 可能被誤讀成 waiting place，但距 table 太遠。", "緊接第一句時 It 明確回指 waiting room，also 增加另一項設施。"], ["插入句需要 waiting room 作單數地點先行詞。", "第一個空格讓 also 與已有 table 形成設施並列。"], ["u41-s277-q04-place-also-facility-near-room", "avoid-intervening-antecedent-confusion"], "pronoun-based-insertion", ["insert-near-any-family-word"]),
    q("Sentence to insert: 'For this reason, the team practiced indoors.' Text: Strong wind made the field unsafe. [A] The players used the school hall. [B] They worked on short passes. [C] The coach ended practice at five. [D] Which position is best?", ["A", "B", "C", "D"], 0, ["For this reason 回指強風危險，並先概括改到室內，再由 hall 具體化。", "放在 hall 後會重說已知地點，且原因與決定被隔開。", "短傳練習已在室內，之後才說決定順序太晚。", "結束練習後才說室內決定不合時間。"], ["原因句後應立即接由此產生的主要決定。", "A 位置讓 hall 與 indoor 形成總說到細節。"], ["u41-s277-q05-insert-for-this-reason-after-hazard", "connect-cause-to-location-decision"], "reason-result-insertion", ["delay-result-until-after-details"]),
    q("Sentence to insert: 'They placed it beside the front window.' Text: The art club finished a large paper bird. [A] The bright colors could be seen from outside. [B] A small sign gave the artists' names. [C] Visitors stopped to take pictures. [D] Where does the sentence belong?", ["Before the art club finished the bird", "At A", "At C", "At D"], 1, ["They 與 it 在作品和社團出現前沒有清楚對象。", "They 回指 club members，it 回指 paper bird，且窗邊位置解釋下一句可從外面看見。", "放到 C 會讓亮色可見先於作品擺到窗邊。", "段末才擺放，卻已有訪客拍照，事件顛倒。"], ["兩個代名詞都需向前找到對象。", "A 位置還能為可見效果提供地點原因。"], ["u41-s277-q06-insert-dual-pronoun-display-action", "resolve-they-and-it-before-visibility-result"], "object-placement-insertion", ["check-only-they-antecedent"]),
    q("Sentence to insert: 'After the paint dried, the students added the street names.' Text: Students drew a large town map. [A] They painted parks green and water blue. [B] The finished map was hung near the office. [C] New students used it to find rooms. [D] Which position preserves the process?", ["A", "C", "D", "B"], 2, ["放在第一次上色前會讓 dried 沒有已完成的 paint 可回指。", "掛起後才補街名不符合 finished map。", "B 位置接在 painting 後，乾燥再加名稱，之後才是 finished map。", "使用地圖後才補街名會破壞製作順序。"], ["After 子句需要前一步上色已發生。", "第三個選項也讓 finished 準確涵蓋所有製作步驟。"], ["u41-s277-q07-place-after-paint-dried-step", "align-production-step-before-finished-state"], "procedure-insertion", ["place-after-clause-before-trigger-event"]),
    q("Sentence to insert: 'The second route is longer, but it passes the hospital.' Text: Two buses go from the station to the lake. [A] Route 1 takes twenty minutes. [B] Route 2 takes thirty minutes. [C] Sick travelers sometimes choose Route 2. [D] Where should the sentence go?", ["A", "B", "Before the first sentence", "C"], 3, ["在 Route 1 後提 second route，但尚未提供 Route 2 的時間比較基準。", "在 Route 2 時間前先稱 longer，讀者尚未看到三十分鐘資料。", "second route 在兩路線被介紹前無法辨認。", "接在兩個時間後可比較 longer，後句再說醫院路線的使用者。"], ["插入句需同時依賴兩條路線的時間資料。", "C 位置也讓 hospital 成為病患選第二路線的理由。"], ["u41-s277-q08-insert-route-comparison-before-user-choice", "use-both-prior-times-and-next-reason"], "comparison-insertion", ["place-comparison-before-comparable-data"]),
    q("Sentence to insert: 'This result surprised the garden group.' Text: The group gave one bed less water than the others. [A] Plants in that bed grew taller. [B] The group checked the soil again. [C] It found that the soil there stayed wet longer. [D] Which position is best?", ["B", "A", "C", "D"], 0, ["放在植物長得更高之後，This result 有明確結果，並帶出重新檢查。", "在結果出現前，This result 尚無對象。", "重新檢查已開始後才表達驚訝，動機順序較弱。", "段末才說驚訝，無法解釋前面的檢查行動。"], ["result 指向較少水卻長得更高的反常發現。", "B 位置讓情緒反應自然成為再次檢查的動機。"], ["u41-s277-q09-place-surprise-between-result-and-check", "link-unexpected-result-to-followup-action"], "result-reaction-insertion", ["refer-result-to-treatment-before-outcome"]),
    q("Sentence to insert: 'Yet the service is not useful after six in the evening.' Text: The town bike desk makes short trips easy. [A] A bike can be borrowed for two hours. [B] The desk closes at six. [C] Morning users often find many bikes. [D] Where does the sentence fit best?", ["A", "C", "Before the first sentence", "D"], 1, ["放在借用時間前，after six 的限制尚未有關門資訊支持。", "接在關門事實後能以 Yet 對比第一句的 useful，並解釋夜間限制。", "Yet 在開頭沒有可轉折的正面內容。", "晨間供車資訊後才談六點限制，會使限制證據距離過遠。"], ["轉折句需要前文先建立服務優點與關門事實。", "C 位置把 closing time 立即轉成使用限制。"], ["u41-s277-q10-insert-yet-after-closing-fact", "convert-service-hour-into-contrast-limit"], "constraint-insertion", ["place-yet-at-paragraph-start"]),
    q("Sentence to insert: 'There, each bag was weighed before it was loaded.' Text: Farmers brought rice to the town center. [A] A truck carried the bags to the train station. [B] The train left at noon. [C] Buyers received the rice that evening. [D] Where should the sentence go?", ["A", "C", "B", "D"], 2, ["At A 時 There 會回指 town center，但後句說 truck 前往車站，無法確定裝載在哪裡。", "在火車離開後才秤重裝載，時間太晚。", "接在到達 train station 後，There 清楚回指車站，且裝載先於列車離開。", "買家收到米後才裝上火車，事件顛倒。"], ["地點副詞與程序先後都指向 train station 後。", "第三項建立運送、秤重裝載、發車的完整鏈。"], ["u41-s277-q11-place-there-weighing-at-station", "combine-location-reference-with-loading-sequence"], "logistics-insertion", ["resolve-there-to-nearest-place-only"]),
    q("Sentence to insert: 'For example, the moon is made of green glass.' Text: The science club checks ideas with simple tests. [A] Members write what they think will happen. [B] They compare the result with the idea. [C] Claims without test results are not accepted. [D] What is the best decision?", ["Put it at A.", "Put it at B.", "Put it at C.", "Do not insert it because it is an unsupported claim, not an example of the stated process."], 3, ["未經測試的月亮材料主張不例證寫預測的程序。", "它也沒有提供比較結果。", "放在不接受無證據主張前仍會把錯誤內容當真。", "該句缺少測試與結果，且與科學社所述標準衝突。"], ["插入題也可能沒有語意合格的位置。", "第四項依全文規則評估句子內容，而非只靠 For example。"], ["u41-s277-q12-reject-unsupported-insertion", "evaluate-content-fit-beyond-discourse-marker"], "no-valid-insertion", ["force-any-for-example-into-text"]),
  ]),
  ...skillQuestions("278", [
    q("A text has three paragraphs: (1) The beach had many plastic cups. (2) Shops began using cups that customers could return. (3) Beach workers later collected much less plastic. Which outline matches the text?", ["Problem → action → result", "Result → example → question", "Two opinions → no conclusion", "Place → person → time"], 0, ["污染問題、商店行動與減量結果依序對應。", "第一段不是結果，全文也沒有問題句。", "段落陳述事件，沒有兩個立場。", "雖有地點，後兩段功能不是人物與時間介紹。"], ["功能標籤比表面名詞更能顯示三段推進。", "第一項保留問題如何被處理以及後續證據。"], ["u41-s278-q01-map-three-paragraph-problem-structure", "label-problem-action-result"], "whole-text-outline", ["outline-by-visible-nouns"]),
    q("Paragraph 1 introduces two ways to reach an island. Paragraph 2 explains the boat. Paragraph 3 explains the small plane. Paragraph 4 compares price and travel time. What is the main job of Paragraph 4?", ["Introduce a third kind of travel", "Bring the two explained choices together for comparison", "Tell a story about one passenger", "Repeat only the boat details"], 1, ["前文只建立兩種選擇，第四段未新增第三種。", "分別說明後，最後一段整合價格與時間作比較。", "功能描述沒有敘事人物。", "比較同時涉及 boat 與 plane。"], ["第四段依賴前兩個分說段提供的資料。", "第二項說明它在全文層次的整合作用。"], ["u41-s278-q02-identify-final-comparison-function", "connect-parallel-sections-in-conclusion"], "paragraph-function", ["treat-final-paragraph-as-new-topic"]),
    q("A text opens by asking why some city streets are cooler. It then explains tree shade and water leaving leaves. Which closing sentence best completes the text?", ["Many streets have names from old people.", "Cars can be different colors.", "Trees can cool streets by blocking sun and releasing water.", "The writer planted a tree on a birthday."], 2, ["街名未在解釋中出現。", "車色與街道溫度機制無關。", "結尾整合 shade 與 leaf water 兩項已說明原因。", "個人種樹故事是未鋪陳的新主題。"], ["結尾應回答開頭 why 問題。", "第三項回收兩個中段機制而未擴張到所有街道。"], ["u41-s278-q03-select-supported-tree-cooling-close", "synthesize-two-explanations-into-answer"], "closing-sentence-selection", ["end-with-related-tree-anecdote"]),
    q("A four-part article is ordered as follows: (1) how to choose a safe bike, (2) how to check the brakes, (3) a history of a king's dinner, (4) how to wear a helmet. Which part breaks the structure?", ["Part 1", "Part 2", "Part 4", "Part 3"], 3, ["選安全腳踏車符合安全指南。", "檢查煞車是必要安全步驟。", "戴安全帽也屬騎乘安全。", "國王晚餐與腳踏車安全完全不同。"], ["全文共同功能是提供騎車前的安全準備。", "第三部分既不延伸程序，也不提供相關理由。"], ["u41-s278-q04-find-structural-break", "detect-unrelated-middle-section"], "article-coherence", ["keep-any-historical-detail-for-interest"]),
    q("Paragraph 1 describes a dark unused lot. Paragraph 2 tells how neighbors cleaned it and added seats. Paragraph 3 describes children reading there today. What does Paragraph 2 do?", ["It shows the change from the old problem to the present use.", "It introduces a different neighborhood.", "It proves every child likes reading.", "It gives the final date of the lot sale."], 0, ["清理與加座位把舊空地轉成今日閱讀空間。", "三段都在同一個 lot。", "第三段有兒童閱讀，但不能證明每位兒童喜歡。", "文本沒有出售日期。"], ["中段是舊狀態與新用途之間的轉換橋梁。", "第一項描述功能，不把方法誤當最終結果。"], ["u41-s278-q05-label-transformation-middle-paragraph", "bridge-before-and-after-states"], "middle-paragraph-role", ["summarize-only-present-scene"]),
    q("Four paragraph functions are mixed: (A) report that bird visits increased, (B) explain the lack of food for birds, (C) introduce the school yard study, (D) describe planting local flowers. Which order forms a clear report?", ["A → D → B → C", "C → B → D → A", "B → A → C → D", "D → C → A → B"], 1, ["以結果開頭且最後才介紹研究，讀者缺少框架。", "先介紹研究，再說問題、採取種花方法，最後報告結果。", "結果插在問題後但方法尚未出現。", "先說做法再介紹研究，且問題留到結果後。"], ["研究報告需要情境、問題、處理與觀察結果。", "第二項讓每段都回答上一段自然引出的問題。"], ["u41-s278-q06-order-study-paragraph-functions", "sequence-context-problem-action-finding"], "functional-paragraph-order", ["lead-with-result-without-context"]),
    q("Opening question: 'Can a shorter school day give students more rest without reducing learning time?' The text explains that lessons were shortened but practice time was added at home. Which fact must the conclusion consider?", ["The school walls are white.", "Some students carry blue bags.", "Learning time includes both shorter lessons and added home practice.", "The town has three other schools."], 2, ["牆色不影響開頭問題。", "書包顏色與休息或學習時間無關。", "結論必須把校內縮短與在家增加一起計算。", "其他學校數量未回答此方案效果。"], ["開頭用 without 設定兩項需同時評估的條件。", "第三項防止只看 school day 而漏掉轉移到家的時間。"], ["u41-s278-q07-identify-required-conclusion-factor", "track-compensating-time-across-text"], "question-to-conclusion-link", ["answer-opening-question-from-one-side-only"]),
    q("An article outline reads: I. Why old phones become waste. II. Parts that can be used again. III. Places that take old phones. Which final section would best extend the outline?", ["IV. A story about a mountain race", "IV. The writer's favorite lunch", "IV. Names for stars seen in winter", "IV. Steps a phone owner can take before giving a phone away"], 3, ["山地比賽不承接電子廢棄物。", "午餐偏好是新主題。", "星星名稱與手機處理無關。", "交出手機前的行動自然接在回收地點與再利用資訊後。"], ["延伸段應保留 old phones 的主題並增加實用下一步。", "第四項把前三節資訊轉為讀者可採取的完整流程。"], ["u41-s278-q08-extend-electronic-waste-outline", "choose-coherent-action-oriented-final-section"], "outline-extension", ["add-interesting-unrelated-section"]),
    q("A report uses Paragraph 2 for survey numbers and Paragraph 3 for students' written comments. Why keep both paragraphs?", ["One shows how many students answered each way; the other shows reasons in their own words.", "Both paragraphs provide exactly the same evidence.", "The comments replace every survey number.", "The numbers tell which comments are true."], 0, ["數量分布與文字理由提供互補證據。", "資料形式與回答問題不同。", "評論不能取代整體人數分布。", "數字本身不判定個別意見真假。"], ["兩段共享主題但承擔不同證據功能。", "第一項說清楚量化結果與質性說明的分工。"], ["u41-s278-q09-explain-complementary-evidence-paragraphs", "distinguish-counts-from-comment-reasons"], "parallel-evidence-functions", ["merge-paragraphs-because-topic-matches"]),
    q("Paragraph 2 explains that a new door opens with less force. Paragraph 3 repeats the same explanation with the same example and adds no fact. What is the clearest edit?", ["Delete Paragraph 1 instead.", "Combine or remove Paragraph 3 because it repeats Paragraph 2.", "Move Paragraph 3 before the title.", "Add a different topic to Paragraph 3."], 1, ["第一段功能未提供，不能任意刪除。", "完全重複且無新功能的段落可合併或移除。", "把重複段放標題前不解決問題。", "加入無關主題會破壞全文一致。"], ["段落是否保留取決於它是否完成獨立任務。", "第二項以最小修改消除沒有功能的新段。"], ["u41-s278-q10-edit-redundant-paragraph", "remove-functionless-repetition"], "structural-revision", ["preserve-repetition-by-moving-it"]),
    q("Text A explains how a rain tank collects water. Text B lists three safe uses for the stored water. Which combined structure best helps a new reader?", ["List the uses first, then hide how water arrives.", "Mix every sentence from both texts without headings.", "Explain collection first, then organize the safe uses by purpose.", "Keep only the tank color and remove the uses."], 2, ["用途前若完全不說來源，讀者缺少系統框架。", "隨機交錯會破壞程序與分類。", "先理解收集過程，再讀用途分類，資訊依賴清楚。", "顏色不是兩文的核心功能。"], ["整合多段內容需保留 how 與 what for 的依序關係。", "第三項讓第二文本建立在第一文本已知概念上。"], ["u41-s278-q11-merge-process-and-use-texts", "order-mechanism-before-applications"], "cross-text-architecture", ["mix-sentences-to-seem-integrated"]),
    q("A long article begins with a family's high power bill, explains where their power use was greatest, describes two changes, and ends with a lower bill. Which one-line outline keeps the essential chain?", ["Family names → house color → month names", "A bill → a list of every device → no ending", "Two changes → an unrelated weather story → a bill", "High cost → use data → changes → lower cost"], 3, ["姓名、房色與月份不是文章發展重點。", "只列設備會漏掉分析、行動與結果。", "天氣故事不在原文架構。", "第四項保留問題、證據、處理與結果四個必要功能。"], ["摘要架構要刪除枝節但保留因果節點。", "最後一項呈現全文如何從問題走到改善。"], ["u41-s278-q12-compress-power-article-architecture", "retain-essential-problem-data-action-result"], "whole-text-structure-summary", ["outline-with-colorful-minor-details"]),
  ]),
];

export const ENGLISH_UNIT_SOURCE = {
  unitId: UNIT_ID,
  lectures: ENGLISH_U41_LECTURES,
  questions: ENGLISH_U41_QUESTIONS,
  vocabularyPolicy: {
    capQuestionBasis: "appendix-5-table-1",
    additionalLearningTerms: ["accept", "active", "activity", "add", "address", "alone", "amount", "artist", "ball", "bill", "board", "carrot", "cause", "chart", "coach", "comment", "compare", "complete", "consider", "customer", "decision", "describe", "develop", "diary", "direct", "duty", "empty", "energy", "entrance", "event", "extra", "final", "fit", "form", "general", "guest", "guide", "hall", "improve", "include", "increase", "information", "introduce", "lack", "leaf", "local", "lock", "magazine", "match", "mix", "narrow", "opinion", "passenger", "path", "position", "positive", "print", "provide", "purpose", "rare", "receive", "record", "repair", "respect", "result", "return", "role", "roof", "section", "serve", "shelf", "shoot", "silence", "soft", "solve", "state", "step", "stone", "such", "support", "tank", "therefore", "tiny", "title", "travel", "usual", "village", "waste", "winner"],
    contextualizedAboveRangeTerms: ["apart", "article", "attend", "audience", "benefit", "brakes", "cafe", "carts", "chain", "claim", "claims", "collection", "combine", "combined", "community", "comparison", "concert", "conclusion", "contest", "cracked", "data", "delete", "delivery", "detail", "details", "device", "display", "displays", "donors", "edit", "effect", "essential", "evaluates", "evidence", "exactly", "explanation", "extend", "farther", "field", "fields", "force", "functions", "gap", "helmet", "hung", "immediately", "indoor", "indoors", "insert", "instead", "labels", "loaded", "nearby", "neighborhood", "organize", "original", "outdoor", "outline", "paragraph", "paragraphs", "phrase", "plastic", "prefer", "preserves", "process", "prove", "proves", "reducing", "relation", "releasing", "remove", "replace", "required", "response", "revision", "route", "separate", "shade", "shallow", "shortened", "soil", "stage", "statement", "structure", "survey", "text", "texts", "timeline", "unclear", "unopened", "unrelated", "unsafe", "unsupported", "unused", "users", "van", "verb", "view", "weighed", "wheelchairs"],
    properNames: ["Amy", "Ava", "Ben", "Eva", "Jo", "Ken", "Kim", "Leo", "Maya", "Mia", "Mina", "Nora", "Rita", "Sam", "Tara", "Tina"],
    grammarNotation: ["A", "B", "C", "D", "I", "II", "III", "IV"],
    malformedDistractors: [],
  },
};
