const UNIT_ID = "ENG_R4_U14";

function lecture(id, skillId, content) {
  return {
    id,
    skillId,
    ...content,
    sections: content.sections.map((section, index) => ({
      id: `${id}_SEC_${String(index + 1).padStart(2, "0")}`,
      ...section,
    })),
  };
}

function question({ id, skillId, difficulty, stem, options, answerIndex, reasons, reviews, cognitiveProcess, representationType = "sentence-cloze", misconceptionTargets = [] }) {
  return { id, skillId, stem, options, answerIndex, reasons, difficulty, cognitiveProcess, representationType, misconceptionTargets, reviews };
}

export const ENGLISH_U14_LECTURES = [
  lecture("ENG_R4_L_S092", "ENG_R4_S092", {
    objectives: ["使用動詞原形開頭的肯定祈使句給予指示。", "用 do not 或 don't 加動詞原形表達禁止或提醒，並判讀 be 祈使句。"],
    sections: [
      { title: "肯定祈使句直接從動詞原形開始", content: "祈使句常省略聽話者 you，直接用動詞原形開頭，例如 Open the window. 或 Turn left at the bank.。它可以是指示、提醒或命令，真正語氣仍要看關係、場合與說話方式，不能只靠句型判斷是否無禮。" },
      { title: "否定祈使句用 do not 或 don't", content: "要請人不要做某事，使用 Do not + base form 或 Don't + base form，例如 Don't touch the wet paint.。don't 後仍接 touch，不加 s、不改過去式，也不能只把 not 放在主要動詞前。" },
      { title: "be 也能作祈使句的開頭", content: "Be careful.、Be quiet. 都是祈使句；be 保持原形，用來要求對方進入某種狀態。否定形式是 Don't be late.，不是 Don't is late，也不是 Not be late。" },
      { title: "依上下文判斷功能與先後順序", content: "食譜、路線、規則與安全提醒都常使用祈使句。閱讀多個指示時，要注意 first、then、before、after 等線索；同樣是動詞原形開頭，Please wait here. 是較柔和的請求，Run! 在危險時則可能是急迫警告。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S092_EX_01", prompt: "Please ___ the door quietly. (close / closes / closed)", steps: ["辨認句子是在請對方採取行動。", "祈使句使用動詞原形。", "把 close 放在 please 後完成指示。"], answer: "close", why: "Please 後的指示仍以原形 close 表達，因此句子是請對方輕聲關門。closes 帶第三人稱單數形式，closed 則是不需要的過去式。" },
      { id: "ENG_R4_L_S092_EX_02", prompt: "___ run beside the pool. The floor is wet. (Don't / Doesn't / Not)", steps: ["濕地板表示奔跑會有危險。", "需要否定祈使句阻止動作。", "使用 Don't 加原形 run。"], answer: "Don't", why: "對聽話者提出禁止時寫 Don't run。Doesn't 需要明說第三人稱主詞，Not 也不能單獨放在 run 前形成完整祈使句。" },
      { id: "ENG_R4_L_S092_EX_03", prompt: "___ careful with the hot bowl. (Be / Are / Being)", steps: ["句子要求對方保持小心。", "祈使句省略主詞 you。", "be 動詞使用原形 Be。"], answer: "Be", why: "Be careful 是要求對方保持小心的祈使句，開頭使用原形 Be。Are 需要明示主詞，Being 也不能獨立承擔這項指示。" },
    ],
    misconceptions: [
      { belief: "祈使句省略 you 後，動詞要配合想像中的第三人稱加 s。", whyWrong: "祈使句開頭固定使用動詞原形，不做第三人稱變化。", correction: "寫 Open the book.，不寫 Opens the book.。" },
      { belief: "只要把 not 放在動詞前，就能形成否定指示。", whyWrong: "英語否定祈使句需要 do not 或 don't。", correction: "使用 Don't push the door.，不要寫 Not push the door.。" },
      { belief: "Don't 後的動詞要改成過去式，表示動作不該發生。", whyWrong: "don't 已負責否定，後面仍接原形。", correction: "使用 Don't step there.，不使用 Don't stepped there.。" },
      { belief: "所有祈使句都一定是在生氣地下命令。", whyWrong: "祈使句也可用於路線、食譜、邀請、提醒與禮貌請求。", correction: "結合 please、說話關係與情境判斷實際語氣。" },
    ],
    checks: [
      { prompt: "Open your book 中省略的主詞是誰？", answer: "you", reason: "祈使句通常把聽話者 you 省略。" },
      { prompt: "Don't touches the glass 要改哪個字？", answer: "touches → touch", reason: "Don't 後使用動詞原形 touch。" },
      { prompt: "Be patient 是不是祈使句？", answer: "是", reason: "原形 Be 開頭，要求聽話者保持耐心。" },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S093", "ENG_R4_S093", {
    objectives: ["使用 please、Can you...? 與 Could you...? 提出清楚而有禮的請求。", "分辨 could 的禮貌請求功能與過去能力功能。"],
    sections: [
      { title: "please 可讓直接指示較柔和", content: "Please + base form 可提出簡潔請求，例如 Please wait by the door.。please 也可放在句尾：Wait here, please.。它能增加禮貌，但內容仍應合理；加入 please 不會把危險或不當要求自動變成合宜請求。" },
      { title: "Can you 與 Could you 後接原形", content: "Can you carry this box? 和 Could you carry this box? 都是在請對方幫忙。Could you...? 通常較委婉，後面使用 carry 原形；不能寫 Could you carried，也不需要再加 do。" },
      { title: "Could you 常問意願而非過去能力", content: "在 Could you pass the salt? 中，說話者希望對方現在遞鹽，不是在考查對方以前會不會遞東西。若句中出現 when you were five 等過去背景，could 才較可能表示過去能力。" },
      { title: "請求要包含可執行的動作與足夠資訊", content: "有禮不等於含糊。Could you meet me? 若時間地點都缺少，對方仍難以行動；Could you meet me at the gate at four? 才提供必要資訊。會考對話題常要求依場合、關係與前後句選出最自然的請求。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S093_EX_01", prompt: "Could you ___ this bag for me? (carry / carried / carrying)", steps: ["辨認 Could you 是當下請求。", "情態助動詞後接原形。", "選 carry 完成請求。"], answer: "carry", why: "Could you 後直接接原形 carry，整句是在有禮地請對方幫忙拿袋子。carried 是過去式，carrying 則少了能帶出分詞的結構。" },
      { id: "ENG_R4_L_S093_EX_02", prompt: "You need the menu. What can you say to the person working there? (Could I see the menu, please? / Do you use menus every day? / The menu was here yesterday.)", steps: ["確認說話者想向服務人員提出請求。", "選擇有完整動作與受詞的句子。", "保留 Could I 與 please 的禮貌語氣。"], answer: "Could I see the menu, please?", why: "Could I see the menu, please? 清楚說出想看菜單，也符合對服務人員的禮貌語氣。另兩句只詢問日常習慣或談過去位置，沒有索取眼前菜單。" },
      { id: "ENG_R4_L_S093_EX_03", prompt: "Could you open the window? What does the speaker want?", steps: ["查看句中沒有過去時間。", "找出 you 後的動作 open。", "判斷說話者希望對方現在開窗。"], answer: "The speaker wants the other person to open the window.", why: "這裡的 Could you...? 是較客氣的請求。說話者要的是對方現在開窗；若解讀成詢問過去能力，就無法說明這段對話的即時目的。" },
    ],
    misconceptions: [
      { belief: "看到 could 就一律翻成『以前能夠』。", whyWrong: "Could you...? 在對話中常用來提出當下請求。", correction: "用時間線索與說話目的區分過去能力和禮貌請求。" },
      { belief: "Could you 後要使用過去式，才能配合 could。", whyWrong: "情態助動詞後需要動詞原形。", correction: "寫 Could you help me?，不寫 Could you helped me?。" },
      { belief: "任何不完整命令加上 please 都會變成自然英文。", whyWrong: "請求仍需完整的動作、對象與必要情境。", correction: "先把意思說清楚，再以 please 或 Could you 調整語氣。" },
      { belief: "Can you...? 只是在測量能力，不能用來請人做事。", whyWrong: "日常對話常以 Can you...? 提出直接但可接受的請求。", correction: "依上下文判斷是在問能力，還是在期待對方採取行動。" },
    ],
    checks: [
      { prompt: "Could you carried this box? 要改哪個字？", answer: "carried → carry", reason: "Could you 後使用動詞原形。" },
      { prompt: "Wait here, please. 中 please 的作用是什麼？", answer: "讓請求較有禮", reason: "please 調整語氣，但不改變 wait 的原形。" },
      { prompt: "Could you swim when you were six? 是當下請求嗎？", answer: "不是", reason: "when you were six 建立過去背景，句子詢問過去能力。" },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S094", "ENG_R4_S094", {
    objectives: ["依請求內容選擇能真正回應對方的接受語。", "以簡短理由婉拒無法做到的請求，避免把道歉誤當接受。"],
    sections: [
      { title: "接受請求要承接對方要做的事", content: "對 Could you close the door? 可回答 Sure.、Of course. 或 No problem.，再採取相應行動。自然回應不只看肯定字眼，也要確認內容相符；Yes, I like the door. 雖有 Yes，卻沒有回答是否願意關門。" },
      { title: "婉拒常由道歉加真實理由組成", content: "若無法幫忙，可說 Sorry, I can't. I have to leave now.。道歉表示在意對方，理由則說明限制。I can't 不是『不准』，而是說話者此刻無法答應；也不必編造過長故事。" },
      { title: "No 並不總是拒絕", content: "Can you help me? — No problem. 的 No problem 表示願意幫忙，不是拒絕。相反地，I am afraid I can't. 雖沒有單獨的 No，整句仍是婉拒。判讀時要看完整片語，不能只抓一個否定字。" },
      { title: "回應後的下一步可驗證真正意思", content: "若對方回答 Sure, I will get it now.，後續行動顯示接受；若說 Sorry, I need it myself.，則表示不能借出。閱讀對話時，把回應、理由與下一句連在一起，才能排除表面禮貌但功能不合的選項。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S094_EX_01", prompt: "A: Could you hold the door? B: ___. (Sure / I held it yesterday / The door is blue)", steps: ["找出 A 要 B 幫忙扶門。", "判斷回應是否表示願意採取該動作。", "選 Sure 接受請求。"], answer: "Sure", why: "Sure 直接表示願意扶門，能讓對話繼續。I held it yesterday 把時間轉到過去，The door is blue 則只描述顏色，都沒有回應當下請求。" },
      { id: "ENG_R4_L_S094_EX_02", prompt: "A: Can you join us at six? B: Sorry, I have a class then. What does B mean?", steps: ["注意 Sorry 帶出婉轉語氣。", "then 指回六點。", "有課使 B 無法參加。"], answer: "B cannot join at six.", why: "B 說六點另有課，理由直接和邀請時間衝突，所以是在婉拒。Sorry 不是接受的開場，也不能因語氣客氣就忽略後面的限制。" },
      { id: "ENG_R4_L_S094_EX_03", prompt: "A: Please pass me the water. B: No problem. What will B probably do?", steps: ["把 No problem 視為完整片語。", "確認它常用來接受請求。", "推論 B 會把水遞過去。"], answer: "B will pass the water.", why: "No problem 在此表示『可以，沒問題』，因此 B 很可能照請求遞水。若只看到 No 就判成拒絕，會忽略整個片語的慣用功能。" },
    ],
    misconceptions: [
      { belief: "回應中出現 Yes 就一定自然地接受了請求。", whyWrong: "Yes 後的內容仍可能答非所問。", correction: "檢查回應是否承接請求中的實際動作。" },
      { belief: "No problem 既然有 No，就是明確拒絕。", whyWrong: "No problem 是常見接受語，表示做這件事沒有問題。", correction: "把固定片語當整體理解，不拆成單字判斷。" },
      { belief: "說 Sorry 就代表已經答應，只是先表現禮貌。", whyWrong: "Sorry 常用來引出無法答應的理由。", correction: "繼續讀 I can't、I need... 等後文再判斷。" },
      { belief: "婉拒一定要提供很長的私人故事才算有禮。", whyWrong: "簡短真實的限制通常已足以說明。", correction: "可用 Sorry 加一項相關理由，避免不必要或不可信的細節。" },
    ],
    checks: [
      { prompt: "No problem. 在接受請求時是肯定還是否定？", answer: "肯定", reason: "完整片語表示願意幫忙。" },
      { prompt: "Sorry, I need this chair. 是接受借椅子嗎？", answer: "不是", reason: "說話者自己需要椅子，因此是在婉拒。" },
      { prompt: "Sure, I can do it after lunch. 提供了哪些資訊？", answer: "接受請求並說明時間", reason: "Sure 表接受，after lunch 說明何時完成。" },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S095", "ENG_R4_S095", {
    objectives: ["使用 Would you like + 名詞提出提供，使用 Would you like to + 原形提出邀請。", "以合宜語句接受或婉拒提供與邀請，並和 Do you like...? 分開。"],
    sections: [
      { title: "Would you like 加名詞可提出提供", content: "Would you like some tea? 是問對方現在是否想要茶，常用於招待或提供。可回答 Yes, please. 或 No, thank you.。some 在這類提供問句中很自然，不能因一般疑問句常見 any 就機械地全部替換。" },
      { title: "Would you like to 加原形可提出邀請", content: "Would you like to join us? 是邀請對方參加。to 後接 join 原形；不能寫 Would you like joining us?。接受可說 Yes, I would love to.，婉拒可說 I would like to, but I have a test tomorrow.。" },
      { title: "Do you like 與 Would you like 功能不同", content: "Do you like coffee? 通常問一般喜好；Would you like some coffee? 則在當下提供咖啡。兩句可能談同一物品，卻期待不同回答，必須依時間與情境判斷。" },
      { title: "回應要分清物品、活動與後續條件", content: "接受食物可用 Yes, please.；接受活動邀請則常用 Yes, I would love to.。若邀請包含時間，要確認回應是否能配合；I would love to, but I work then. 實際上仍是婉拒，不能只讀前半句。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S095_EX_01", prompt: "Would you like ___ orange juice? (some / to / joining)", steps: ["辨認說話者正在提供飲料。", "飲料是名詞片語，不需要不定詞。", "用 some 修飾 orange juice。"], answer: "some", why: "Would you like some orange juice? 是自然的飲料提供。to 後缺少動詞，joining 也不能直接放在 juice 前，所以只有 some 能完成名詞片語。" },
      { id: "ENG_R4_L_S095_EX_02", prompt: "Would you like to ___ the school walk? (join / joins / joining)", steps: ["to 已標示後方需要動詞。", "邀請內容是參加健走。", "不定詞使用原形 join。"], answer: "join", why: "邀請句型是 Would you like to join...?，to 後接原形 join。joins 帶第三人稱變化，joining 則不能接在這個 to 後。" },
      { id: "ENG_R4_L_S095_EX_03", prompt: "A: Would you like some cake? B: No, thank you. What does B mean?", steps: ["確認 A 正在提供蛋糕。", "把 No, thank you 當成完整回應。", "判斷 B 有禮地不接受。"], answer: "B does not want the cake.", why: "No, thank you 同時表達婉拒與感謝，因此 B 不接受這次蛋糕提供。這不等於 B 永遠不喜歡蛋糕，只能判斷眼前這一次。" },
    ],
    misconceptions: [
      { belief: "Would you like...? 和 Do you like...? 都只是在問一般喜好。", whyWrong: "Would you like 常針對當下提供或邀請。", correction: "用對話情境判斷是在問平常喜好，還是現在要不要。" },
      { belief: "Would you like to 後面要接 V-ing。", whyWrong: "這裡的 to 是不定詞標記，後面使用原形。", correction: "寫 Would you like to come?，不寫 to coming。" },
      { belief: "I would love to, but... 前半肯定，所以一定接受。", whyWrong: "but 後的時間衝突可能使整句成為婉拒。", correction: "讀到句尾，確認說話者最後是否能參加。" },
      { belief: "No, thank you 表示說話者討厭被提供的東西。", whyWrong: "它只婉拒當下提供，沒有說明長期喜好。", correction: "不要把一次選擇推論成永久態度。" },
    ],
    checks: [
      { prompt: "Would you like to coming? 要改哪個字？", answer: "coming → come", reason: "would like to 後使用動詞原形。" },
      { prompt: "Do you like tea? 通常問什麼？", answer: "一般喜好", reason: "Do you like 常詢問平時是否喜歡某物。" },
      { prompt: "Yes, please. 可自然回應飲料提供嗎？", answer: "可以", reason: "它簡潔表示接受對方提供的物品。" },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S096", "ENG_R4_S096", {
    objectives: ["使用 Let's 加動詞原形提出共同活動，並以 Let's not 提出共同避免事項。", "使用 How about 加名詞或 V-ing 提出建議，選擇合宜回應。"],
    sections: [
      { title: "Let's 加原形邀請大家一起行動", content: "Let's 是 Let us 的常用縮寫，後接動詞原形，例如 Let's take the bus.。說話者把自己也包含在行動中，因此和命令 You take the bus. 不同；它通常是在提出共同建議。" },
      { title: "Let's not 加原形提出共同避免", content: "Let's not wait outside. 表示建議大家不要在外面等。not 放在原形動詞前，而且不使用 don't；Let's don't wait 在標準課堂英文中不是本單元採用的形式。" },
      { title: "How about 後接名詞或 V-ing", content: "How about the bus? 可提出一個選項；How about taking the bus? 則明說建議的動作。about 是介系詞，所以後面接 taking，不接 take 或 to take。" },
      { title: "建議是否合適要看共同目標", content: "That sounds good. 可接受建議；I am afraid that is too late. 可說明不合適。選答案時不能只找正確句型，還要確認建議能否解決問題，例如趕時間時提出走更遠的路就不一定合理。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S096_EX_01", prompt: "Let's ___ at the front gate. (meet / meets / meeting)", steps: ["Let's 表示共同建議。", "Let's 後接動詞原形。", "選 meet 表達集合。"], answer: "meet", why: "Let's meet at the front gate 邀請大家在前門會合。meets 帶第三人稱單數形式，meeting 則不能直接接在 Let's 後。" },
      { id: "ENG_R4_L_S096_EX_02", prompt: "How about ___ lunch outside? (eat / eating / to eat)", steps: ["about 是介系詞。", "介系詞後的動作要用 V-ing。", "選 eating 完成建議。"], answer: "eating", why: "How about eating lunch outside? 以 eating 表達建議的活動。eat 與 to eat 都不能直接接在介系詞 about 後。" },
      { id: "ENG_R4_L_S096_EX_03", prompt: "It is raining. A: Let's walk to the park. B: I am afraid we will get wet. What does B mean?", steps: ["把下雨與步行連在一起。", "I am afraid 引出顧慮。", "B 認為這項建議不合適。"], answer: "B does not accept the idea.", why: "B 指出下雨步行會淋濕，理由直接反對這項建議，因此並未接受。I am afraid 在此是委婉表達顧慮，不是說 B 害怕 A。" },
    ],
    misconceptions: [
      { belief: "Let's 後面要配合 people 改成動詞複數或加 s。", whyWrong: "Let's 後固定使用動詞原形。", correction: "寫 Let's start now.，不寫 Let's starts now.。" },
      { belief: "How about 後可直接接原形，因為是在建議動作。", whyWrong: "about 是介系詞，動作需使用 V-ing。", correction: "使用 How about walking?，不使用 How about walk?。" },
      { belief: "Let's 是對另一個人下命令，說話者不包含在內。", whyWrong: "Let's 通常邀請說話者與聽話者共同參與。", correction: "把它理解為『我們一起……吧』，再由情境判斷範圍。" },
      { belief: "That sounds good 表示聲音很好，和建議無關。", whyWrong: "它在對話中常表示認同剛才的想法。", correction: "結合前一句建議理解 sounds good 的回應功能。" },
    ],
    checks: [
      { prompt: "Let's goes home 要改哪個字？", answer: "goes → go", reason: "Let's 後使用原形 go。" },
      { prompt: "How about taking the train? 中 taking 為何加 ing？", answer: "about 後接 V-ing", reason: "about 是介系詞。" },
      { prompt: "Let's not be late. 是肯定還是否定建議？", answer: "否定建議", reason: "not 表示建議大家避免遲到。" },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S097", "ENG_R4_S097", {
    objectives: ["依熟悉程度、角色與情境選擇直接或較委婉的請求。", "辨認緊急警告可直接明確，而一般請求仍需提供尊重與足夠資訊。"],
    sections: [
      { title: "語氣選擇取決於關係與負擔", content: "向熟悉同學借一支筆，可說 Can I use your pen?；向不熟悉的人提出較大請求，Could you help me move this table, please? 通常更合宜。不是句子越長越禮貌，而是要考慮對方、負擔與場合。" },
      { title: "服務與正式場合常需要清楚又尊重", content: "向店員詢問可用 Excuse me. Could you tell me the price?。Excuse me 先取得注意，Could you 降低直接命令感；同時保留具體問題，避免只說 Help me, please 而缺乏資訊。" },
      { title: "安全警告可以短而直接", content: "看到腳踏車即將撞到朋友時，Stop! 或 Watch out! 比冗長請求有效。直接不等於失禮；當延遲會造成危險，清楚與速度優先。危險解除後，語氣才回到一般人際互動。" },
      { title: "沒有一個句型在所有情境都最禮貌", content: "Could you...? 常較委婉，但對小孩發出緊急安全指示時不必包成長問句；Please 也不能補救不合理要求。判斷題應比較整個情境中的目的、急迫性與雙方關係，而非背固定禮貌排名。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S097_EX_01", prompt: "You need help from a person at the library. Which opening fits best? (Excuse me. Could you help me? / Give me that book. / You work here.)", steps: ["辨認對方是不熟悉的館員。", "請求需要先取得注意並保持尊重。", "選含 Excuse me 與 Could you 的句子。"], answer: "Excuse me. Could you help me?", why: "向館員求助時，Excuse me 能先禮貌取得注意，Could you help me 則清楚提出需求。另兩句分別是過度直接的命令與單純身分陳述，都不適合作為求助開場。" },
      { id: "ENG_R4_L_S097_EX_02", prompt: "A ball is flying toward a child. What should you shout? (Watch out! / Could you perhaps move later? / Would you like a ball?)", steps: ["判斷危險正在發生。", "需要讓孩子立即注意並避開。", "選短而明確的 Watch out。"], answer: "Watch out!", why: "球正飛向孩子時，Watch out! 能最快傳達危險。較長的委婉問句會延誤反應，邀請對方要球更完全改變了溝通目的。" },
      { id: "ENG_R4_L_S097_EX_03", prompt: "You ask a classmate to move one book. Does “Can you move this book, please?” work well here?", steps: ["請求的負擔很小。", "雙方是同學關係。", "句子清楚且帶 please。"], answer: "Yes, it works well here.", why: "對同學提出小幅度協助時，Can you move this book, please? 已清楚且有禮，不必硬改成更長的正式句。禮貌程度應和情境相稱。" },
    ],
    misconceptions: [
      { belief: "Could you...? 在任何時候都一定比其他說法更好。", whyWrong: "緊急安全警告若太長，可能讓對方來不及反應。", correction: "先判斷急迫性，再選擇直接警告或委婉請求。" },
      { belief: "只要加 please，再大的要求都會變得合宜。", whyWrong: "禮貌詞不能消除不合理負擔或缺乏資訊的問題。", correction: "說明具體需求，也尊重對方能否答應。" },
      { belief: "對朋友永遠可以只用命令，因為彼此熟悉。", whyWrong: "熟悉關係仍需要尊重，尤其要求需要時間或心力時。", correction: "依負擔調整語氣，不把熟悉當成強迫的理由。" },
      { belief: "直接句一定無禮，不能出現在好英文裡。", whyWrong: "警告、路標與簡明操作指示常需要直接形式。", correction: "把直接度和溝通目的連在一起評估。" },
    ],
    checks: [
      { prompt: "向陌生店員問價錢，可先說什麼？", answer: "Excuse me.", reason: "它能先禮貌取得對方注意。" },
      { prompt: "火警時應使用長請求還是短警告？", answer: "短警告", reason: "安全情境需要立即而清楚的訊息。" },
      { prompt: "please 能使不合理要求自動合理嗎？", answer: "不能", reason: "仍要考慮負擔、資訊與對方選擇。" },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S098", "ENG_R4_S098", {
    objectives: ["從問句、回應與理由判斷請求、邀請、提供、建議或警告。", "辨認間接回應與表面字詞的差異，不加入對話沒有提供的動機。"],
    sections: [
      { title: "先找說話者希望下一步發生什麼", content: "Could you pass the map? 希望對方遞地圖；Would you like some soup? 希望對方決定是否接受湯。分類溝通目的時，不只看 could 或 would，而要找動作的執行者與期待的下一步。" },
      { title: "回應可揭示前一句的真正功能", content: "A 說 Could you come at four?，B 回 Sure, I will be there.，可知 A 在提出請求或安排，而非詢問過去能力。若 B 回 No, thank you.，通常前句可能是提供或邀請；回應形式是重要線索。" },
      { title: "間接婉拒常把限制放在後半句", content: "That sounds fun, but I have to work. 前半表達正面態度，but 後才給出無法參加的原因。整體功能是婉拒，不可只截取 sounds fun 就判成接受，也不能推論說話者不喜歡活動。" },
      { title: "推論要停在證據允許的範圍", content: "Can you turn down the music? 表示希望音量降低，但不能由此確定說話者討厭所有音樂。閱讀情境題時，答案應能解釋完整對話，又不添加性格、長期喜好或未說出的事件。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S098_EX_01", prompt: "A: Would you like to see the show? B: I would love to. What is A doing?", steps: ["辨認 Would you like to 加活動。", "查看 B 表示願意參加。", "判斷 A 正在邀請 B。"], answer: "A is inviting B to the show.", why: "Would you like to see the show? 提出共同活動，B 的接受回應也證實這是一項邀請。它不是詢問 B 平常是否喜歡所有表演。" },
      { id: "ENG_R4_L_S098_EX_02", prompt: "A: Could you lower your voice? B: Sorry. I did not know I was so loud. What will B probably do?", steps: ["找出 A 要求降低音量。", "B 道歉並承認音量過大。", "推論 B 會說得小聲一些。"], answer: "B will probably speak more quietly.", why: "B 的道歉直接承接 lower your voice，並承認自己太大聲，因此合理下一步是降低音量。對話沒有證據顯示 B 會離開或停止說話。" },
      { id: "ENG_R4_L_S098_EX_03", prompt: "A: How about taking the early bus? B: That may help us arrive on time. What is B doing?", steps: ["辨認 A 以 How about 提出建議。", "B 說明提早搭車的好處。", "判斷 B 傾向接受建議。"], answer: "B is supporting the idea.", why: "B 指出早班車能幫助準時到達，這是在提供支持理由，也表示建議可行。回應不是保證一定準時，只是肯定它有幫助。" },
    ],
    misconceptions: [
      { belief: "只要看到 could，就能把句子分類成過去能力。", whyWrong: "對話回應可能顯示它是當下請求。", correction: "同時查看動作、時間與對方如何回應。" },
      { belief: "回應先說 That sounds good，就一定接受後面的安排。", whyWrong: "but 後可能出現無法參加的限制。", correction: "以完整回應的最後立場判斷接受或婉拒。" },
      { belief: "說話者要求降低音量，表示他討厭音樂。", whyWrong: "一次音量請求不足以證明長期喜好。", correction: "只推論對方希望目前聲音變小。" },
      { belief: "判斷溝通目的只要認出句型，不必讀回答。", whyWrong: "同一形式在不同上下文可能有不同功能。", correction: "把問句、回應、理由與後續行動連起來判讀。" },
    ],
    checks: [
      { prompt: "Would you like some water? 主要是提供還是命令？", answer: "提供", reason: "說話者讓對方決定是否接受水。" },
      { prompt: "That sounds nice, but I am busy then. 最後是接受嗎？", answer: "不是", reason: "but 後的忙碌限制使整句成為婉拒。" },
      { prompt: "Could you close the gate? 可推論說話者討厭所有大門嗎？", answer: "不能", reason: "只能確定他希望這扇門現在關上。" },
    ],
    assets: [],
  }),
];

export const ENGLISH_U14_QUESTIONS = [
  question({ id: "ENG_R4_Q_092_01", skillId: "ENG_R4_S092", difficulty: "foundation", stem: "Please ___ the gate after you come in.", options: ["close", "closes", "closed", "closing"], answerIndex: 0,
    reasons: ["祈使句在 please 後使用原形 close。", "closes 是第三人稱單數形式，不能接在省略 you 的指示中。", "closed 是過去式，題目不是敘述已完成事件。", "closing 是分詞，這裡缺少能帶出它的結構。"],
    reviews: ["句子要求聽者進門後關門，核心結構是 Please + base form。", "第一項同時符合指示功能與動詞形式；其他三項都對 close 做了不必要變化。"], cognitiveProcess: ["complete-gate-closing-imperative", "retain-close-base-form-after-please"], misconceptionTargets: ["inflect-verb-in-imperative"] }),
  question({ id: "ENG_R4_Q_092_02", skillId: "ENG_R4_S092", difficulty: "foundation", stem: "The glass is hot. ___ touch it.", options: ["Not", "Do not", "Does not", "No"], answerIndex: 1,
    reasons: ["Not 不能單獨放在 touch 前形成否定祈使句。", "Do not touch 正確阻止聽者碰觸熱玻璃。", "Does not 需要第三人稱主詞，並非對聽者的直接指示。", "No 後缺少可連接 touch 的結構。"],
    reviews: ["hot 說明碰觸有風險，因此句子需要完整的否定指示。", "第二項以 Do not 加原形 touch；其餘選項不是標準否定祈使句。"], cognitiveProcess: ["form-hot-glass-prohibition", "choose-do-not-before-touch"], misconceptionTargets: ["place-bare-not-before-imperative"] }),
  question({ id: "ENG_R4_Q_092_03", skillId: "ENG_R4_S092", difficulty: "foundation", stem: "___ quiet while the baby is sleeping.", options: ["Are", "Being", "Be", "Is"], answerIndex: 2,
    reasons: ["Are 需要明說主詞，不能單獨開啟這項指示。", "Being 不是祈使句所需的 be 原形。", "Be quiet 正確要求聽者保持安靜。", "Is 是第三人稱單數形式，和省略 you 的祈使句不合。"],
    reviews: ["嬰兒正在睡覺，所以說話者要求聽者進入安靜狀態。", "第三項使用原形 Be；另外三項都把 be 改成不適用於祈使句的形式。"], cognitiveProcess: ["select-be-for-quiet-state-command", "connect-sleeping-baby-to-imperative-state"], representationType: "be-imperative-cloze", misconceptionTargets: ["use-finite-be-in-imperative"] }),
  question({ id: "ENG_R4_Q_092_04", skillId: "ENG_R4_S092", difficulty: "standard", stem: "___ your name at the top of the page.", options: ["Writes", "Writing", "Wrote", "Write"], answerIndex: 3,
    reasons: ["Writes 帶第三人稱單數標記，不是直接指示的形式。", "Writing 不能獨立作為完整祈使句的主要動詞。", "Wrote 是過去式，會把指示誤寫成敘事片段。", "Write 以原形開頭，正確告訴學生要做的事。"],
    reviews: ["at the top of the page 提供書寫位置，前方只需原形動詞發出指示。", "第四項形成完整課堂指令；其他選項都不符合省略 you 的祈使句。"], cognitiveProcess: ["complete-page-name-instruction", "identify-write-as-imperative-base"], representationType: "classroom-instruction-cloze", misconceptionTargets: ["use-past-or-participle-as-command"] }),
  question({ id: "ENG_R4_Q_092_05", skillId: "ENG_R4_S092", difficulty: "standard", stem: "Which notice tells visitors to leave their bikes outside?", options: ["Leave your bike outside before you enter.", "Bikes were outside this morning.", "The bike outside belongs to Leo.", "Visitors can see bikes from the window."], answerIndex: 0,
    reasons: ["原形 Leave 直接指示訪客進入前把腳踏車留在外面。", "第二項只敘述今天早上的位置，沒有要求訪客行動。", "第三項說明腳踏車的主人，並非館內規則。", "第四項談可看到腳踏車，也沒有指示停放地點。"],
    reviews: ["題目要找能使訪客採取特定行動的 notice，不是任何含 outside 的句子。", "第一項同時具祈使形式、動作 leave 與時間 before you enter。"], cognitiveProcess: ["match-bike-notice-to-required-action", "separate-imperative-notice-from-bike-facts"], representationType: "notice-function-selection", misconceptionTargets: ["select-keyword-match-without-instruction"] }),
  question({ id: "ENG_R4_Q_092_06", skillId: "ENG_R4_S092", difficulty: "standard", stem: "The floor has just been painted. ___ on it.", options: ["Does not step", "Don't step", "Not stepping", "No step"], answerIndex: 1,
    reasons: ["Does not step 需要明確的第三人稱主詞，不能用來直接警告聽者。", "Don't step 正確要求對方不要踩上新漆地板。", "Not stepping 是片語，未形成完整指示。", "No step 不是此情境的標準句子。"],
    reviews: ["just been painted 說明踩踏會破壞表面，否定範圍應落在 step on it。", "第二項是完整的 Don't + base form；其他形式都無法自然承擔警告。"], cognitiveProcess: ["prevent-stepping-on-new-paint", "apply-dont-plus-step-in-warning"], representationType: "fresh-paint-prohibition", misconceptionTargets: ["use-does-not-for-direct-command"] }),
  question({ id: "ENG_R4_Q_092_07", skillId: "ENG_R4_S092", difficulty: "standard", stem: "First, wash the apples. Then cut them into small pieces. What should you do second?", options: ["Buy more apples.", "Wash the pieces again.", "Cut the apples.", "Put the apples back."], answerIndex: 2,
    reasons: ["指示沒有要求購買更多蘋果。", "wash 出現在 first，不是第二個新動作。", "Then 引出的 cut 是第二步。", "把蘋果放回去不在給定流程中。"],
    reviews: ["這題需依 First 與 Then 排列兩個祈使指示，而非只找食物相關選項。", "第三項精確重述第二步 cut them；其他動作未出現在流程或順序不對。"], cognitiveProcess: ["sequence-apple-preparation-imperatives", "resolve-then-as-second-action"], representationType: "ordered-instruction-reading", misconceptionTargets: ["ignore-order-marker-in-directions"] }),
  question({ id: "ENG_R4_Q_092_08", skillId: "ENG_R4_S092", difficulty: "advanced", stem: "Don't ___ the red button until the light turns green.", options: ["pushed", "pushes", "pushing", "push"], answerIndex: 3,
    reasons: ["pushed 是過去式，不能接在 Don't 後。", "pushes 多了第三人稱單數變化。", "pushing 是分詞，不是此否定祈使句所需形式。", "push 是原形，正確把動作延後到綠燈亮起。"],
    reviews: ["until 建立時間限制，但不改變 Don't 後接原形的規則。", "第四項形成 Don't push；前三項都把主要動詞加上了不必要詞尾。"], cognitiveProcess: ["apply-delayed-button-prohibition", "retain-push-base-under-dont"], representationType: "timed-negative-imperative", misconceptionTargets: ["change-verb-form-after-dont"] }),
  question({ id: "ENG_R4_Q_092_09", skillId: "ENG_R4_S092", difficulty: "advanced", stem: "A cooking note says, “Heat the soup. Add the milk after it is hot.” When should you add the milk?", options: ["After the soup is hot", "Before heating the soup", "While buying the milk", "After the meal is over"], answerIndex: 0,
    reasons: ["after it is hot 明確指出湯熱了才加牛奶。", "題目先要求 Heat the soup，不能在加熱前加入。", "購買牛奶不是食譜中的步驟。", "餐後才加會錯過烹調流程。"],
    reviews: ["兩個祈使句由 after 建立條件順序，it 指的是前句的 soup。", "第一項保留加熱完成後再加入的時間關係，其他時點都違反食譜。"], cognitiveProcess: ["interpret-after-condition-in-recipe", "link-it-to-heated-soup"], representationType: "recipe-sequence-inference", misconceptionTargets: ["reverse-after-sequence"] }),
  question({ id: "ENG_R4_Q_092_10", skillId: "ENG_R4_S092", difficulty: "advanced", stem: "Which line tells someone about danger right away rather than giving a fact?", options: ["A bus comes every ten minutes.", "Watch out! A bike is coming.", "The bike is beside the bus.", "Many people ride bikes here."], answerIndex: 1,
    reasons: ["第一項提供公車頻率資訊，沒有要求立即反應。", "Watch out 直接警告眼前有腳踏車接近。", "第三項只陳述兩個物體的位置。", "第四項描述當地一般情況。"],
    reviews: ["迫切警告必須同時包含即時風險與讓聽者反應的功能。", "第二項的祈使語 Watch out 加上 is coming，符合迫切警告；其餘都是陳述。"], cognitiveProcess: ["classify-watch-out-as-urgent-warning", "distinguish-immediate-danger-from-bike-information"], representationType: "speech-function-contrast", misconceptionTargets: ["treat-all-bike-sentences-as-warnings"] }),
  question({ id: "ENG_R4_Q_092_11", skillId: "ENG_R4_S092", difficulty: "transfer", stem: "Smoke is coming from a pan. What should the cook say to a child standing near it?", options: ["The pan was new last week.", "You like this pan.", "Stay back and don't touch it!", "The kitchen has two windows."], answerIndex: 2,
    reasons: ["鍋子的購買時間無法阻止孩子接近危險。", "第二項談喜好，沒有安全功能。", "Stay back 與 don't touch it 提供兩項立即且明確的安全指示。", "窗戶數量與孩子目前應做的事無關。"],
    reviews: ["冒煙的鍋子需要對附近孩子發出可立即執行的警告。", "第三項兼具保持距離與禁止碰觸；其他句子即使合文法，也不能處理風險。"], cognitiveProcess: ["compose-child-safety-response-to-smoking-pan", "select-two-action-emergency-imperative"], representationType: "safety-message-transfer", misconceptionTargets: ["choose-descriptive-fact-instead-of-warning"] }),
  question({ id: "ENG_R4_Q_092_12", skillId: "ENG_R4_S092", difficulty: "transfer", stem: "The room must stay quiet during the test. Which sign tells visitors what to do?", options: ["The test was quiet yesterday.", "Visitors heard a quiet song.", "This room has a test every month.", "Please keep your voice low."], answerIndex: 3,
    reasons: ["過去安靜不等於現在的訪客指示。", "聽到安靜歌曲與考試規則沒有直接關係。", "第三項只提供考試頻率。", "Please keep your voice low 直接要求訪客降低音量。"],
    reviews: ["sign 必須把 must stay quiet 轉成聽者可採取的行動。", "第四項使用禮貌祈使句達成目的；其他選項只是關於房間或聲音的資訊。"], cognitiveProcess: ["convert-test-quiet-rule-to-visitor-instruction", "choose-keep-voice-low-imperative"], representationType: "rule-to-sign-transfer", misconceptionTargets: ["confuse-related-information-with-instruction"] }),

  question({ id: "ENG_R4_Q_093_01", skillId: "ENG_R4_S093", difficulty: "foundation", stem: "Could you ___ this box for me?", options: ["carry", "carried", "carries", "carrying"], answerIndex: 0,
    reasons: ["Could you 後使用原形 carry，形成當下幫忙請求。", "carried 是過去式，不能跟在情態助動詞後。", "carries 帶第三人稱單數詞尾，但主詞前已有 could。", "carrying 是分詞，不符合 Could you + base form。"],
    reviews: ["for me 顯示說話者希望對方現在幫忙拿箱子。", "第一項符合禮貌請求形式；另外三項都錯改了 carry。"], cognitiveProcess: ["complete-polite-box-carry-request", "use-carry-base-after-could-you"], misconceptionTargets: ["use-past-form-after-could-request"] }),
  question({ id: "ENG_R4_Q_093_02", skillId: "ENG_R4_S093", difficulty: "foundation", stem: "You did not hear the teacher. What can you say?", options: ["You speak again.", "Could you say that again, please?", "I could hear yesterday.", "What did the teacher say yesterday?"], answerIndex: 1,
    reasons: ["第一項像直接命令，且缺少自然禮貌語氣。", "Could you say that again, please? 清楚請老師重說一次。", "第三項談昨天的能力，無法解決現在沒聽見。", "第四項詢問昨天的內容，並未請眼前的老師重複剛才話語。"],
    reviews: ["需求是請老師重複剛才內容，因此答案要包含 say that again。", "第二項的 Could you 與 please 適合師生情境，並直接處理未聽清楚的問題。"], cognitiveProcess: ["form-teacher-repeat-request-after-missed-speech", "select-polite-complete-repetition-line"], representationType: "classroom-request-selection", misconceptionTargets: ["describe-hearing-problem-without-requesting-repair"] }),
  question({ id: "ENG_R4_Q_093_03", skillId: "ENG_R4_S093", difficulty: "foundation", stem: "A customer asks, “Could you hold this bag for a moment?” What does the customer want?", options: ["To know what happened yesterday", "To buy a different bag", "Someone to hold the bag now", "Someone to close the store"], answerIndex: 2,
    reasons: ["句中沒有過去時間，也不是回顧事件。", "顧客沒有表示要購買另一個袋子。", "Could you hold... 是請對方現在暫時拿著袋子。", "請求的動作是 hold the bag，不是關店。"],
    reviews: ["for a moment 建立短暫的當下協助，排除過去能力解讀。", "第三項準確指出期待的行動者與動作；其他選項添加了對話未提的目的。"], cognitiveProcess: ["infer-customer-intent-from-could-you-hold", "separate-present-help-from-past-ability"], representationType: "polite-request-function", misconceptionTargets: ["read-could-request-as-past-event"] }),
  question({ id: "ENG_R4_Q_093_04", skillId: "ENG_R4_S093", difficulty: "standard", stem: "Please ___ me when the bus arrives.", options: ["told", "telling", "tells", "tell"], answerIndex: 3,
    reasons: ["told 是過去式，不能放在 please 後提出未來要做的事。", "telling 是分詞，句中沒有支撐它的 be 動詞。", "tells 是第三人稱單數形式，不適用於省略 you 的請求。", "tell 是原形，正確請對方在公車到達時告知。"],
    reviews: ["when the bus arrives 說明告知時點，但主句仍是 Please + base form。", "第四項完成可執行的請求，其他形式都不符合祈使結構。"], cognitiveProcess: ["complete-bus-arrival-notification-request", "retain-tell-base-after-please"], representationType: "timed-polite-imperative", misconceptionTargets: ["match-main-verb-to-arrives"] }),
  question({ id: "ENG_R4_Q_093_05", skillId: "ENG_R4_S093", difficulty: "standard", stem: "Which question gives the listener enough information to meet?", options: ["Could you meet me at the front gate at four?", "Could you meet me later?", "Meeting is good.", "You know a place."], answerIndex: 0,
    reasons: ["第一項同時說明前門與四點，聽者能據此赴約。", "later 沒有明確時間，也沒有地點。", "第三項只評論會面，並未提出安排。", "第四項沒有說要在哪裡或何時碰面。"],
    reviews: ["有禮請求仍需提供完成行動所需的 time 與 place。", "第一項不靠冗長描述，而是補齊實際安排；另外三項資訊不足或不是請求。"], cognitiveProcess: ["evaluate-meeting-request-information-completeness", "identify-gate-and-four-as-actionable-details"], representationType: "request-completeness-comparison", misconceptionTargets: ["equate-polite-modal-with-complete-message"] }),
  question({ id: "ENG_R4_Q_093_06", skillId: "ENG_R4_S093", difficulty: "standard", stem: "You want a stranger to take a photo of your group. Which line is best?", options: ["Take us now.", "Excuse me. Could you take a photo for us, please?", "You have a camera.", "We took a photo yesterday."], answerIndex: 1,
    reasons: ["第一項過度直接，也沒有先取得陌生人注意。", "Excuse me 加 Could you 與 please，清楚又尊重地提出拍照請求。", "第三項只陳述對方有相機，沒有說明希望他做什麼。", "第四項談昨天的照片，和眼前協助無關。"],
    reviews: ["對陌生人提出額外協助時，需要清楚動作、受益者與合宜語氣。", "第二項具備 take a photo for us 的完整內容，其餘選項不是自然請求。"], cognitiveProcess: ["select-stranger-photo-request-tone", "combine-excuse-me-could-you-and-purpose"], representationType: "social-request-choice", misconceptionTargets: ["use-bare-command-with-stranger"] }),
  question({ id: "ENG_R4_Q_093_07", skillId: "ENG_R4_S093", difficulty: "standard", stem: "Ben says, “Can you send me the address?” What is Ben doing?", options: ["Testing someone's reading skill", "Reporting where he lived before", "Asking someone to send information", "Giving an order to leave"], answerIndex: 2,
    reasons: ["句子沒有測驗閱讀能力。", "address 是要被傳送的資訊，不是過去住址敘事。", "Can you send me...? 在此提出傳送地址的請求。", "句中沒有 leave 或離開指令。"],
    reviews: ["me 指出資訊接收者，send 則指出說話者期待的下一步。", "第三項完整對應對話功能；不能只把 Can you 解讀成能力測量。"], cognitiveProcess: ["classify-address-can-you-as-request", "trace-send-action-to-ben-as-receiver"], representationType: "can-you-pragmatic-reading", misconceptionTargets: ["treat-all-can-you-questions-as-ability-tests"] }),
  question({ id: "ENG_R4_Q_093_08", skillId: "ENG_R4_S093", difficulty: "advanced", stem: "Which sentence asks what a person was able to do in the past, rather than asking the listener to do something now?", options: ["Could you open the gate now?", "Could you pass the bread, please?", "Could you wait here for a minute?", "Could you read before you started school?"], answerIndex: 3,
    reasons: ["now 顯示說話者要對方當下開門。", "pass the bread 是餐桌上的即時請求。", "wait here for a minute 期待現在採取行動。", "before you started school 建立過去時段，詢問當時是否會閱讀。"],
    reviews: ["四句形式相同，必須用時間背景與期待行動區分功能。", "第四項沒有要求現在做事，而是回顧入學前能力；前三項都是禮貌請求。"], cognitiveProcess: ["contrast-four-could-you-functions", "use-before-school-to-identify-past-ability"], representationType: "could-function-comparison", misconceptionTargets: ["assign-one-meaning-to-all-could-you-forms"] }),
  question({ id: "ENG_R4_Q_093_09", skillId: "ENG_R4_S093", difficulty: "advanced", stem: "It starts to rain, and you forgot your umbrella. What can you ask a friend?", options: ["Could I share your umbrella, please?", "Your umbrella is blue.", "I shared an umbrella last year.", "Can you tell me if it will rain?"], answerIndex: 0,
    reasons: ["Could I share your umbrella, please? 清楚請求朋友讓自己共撐。", "第二項只描述顏色，沒有處理淋雨問題。", "過去共傘經驗不能取得眼前許可。", "雨已經開始，第四項再問是否會下雨既不需要，也沒有取得遮雨協助。"],
    reviews: ["忘記雨傘後的合理目標是獲准共享朋友的雨傘。", "第一項以 Could I 詢問許可並指出 share；其餘句子沒有可行的當下功能。"], cognitiveProcess: ["form-umbrella-sharing-permission-request", "connect-rain-problem-to-could-i-share"], representationType: "weather-request-transfer", misconceptionTargets: ["state-related-fact-instead-of-asking-permission"] }),
  question({ id: "ENG_R4_Q_093_10", skillId: "ENG_R4_S093", difficulty: "advanced", stem: "A: Could you check this answer for me? B: ___.", options: ["I checked my answer yesterday.", "Sure. Show me the question.", "“Could” may talk about the past.", "An answer is on the page."], answerIndex: 1,
    reasons: ["第一項只說 B 昨天檢查自己的答案，沒有接受 A 的請求。", "Sure 表示接受，後句要求看到題目以便檢查。", "第三項討論 could 的功能，沒有回應是否幫忙。", "第四項指出答案位置，卻未表示是否願意檢查。"],
    reviews: ["自然回應應表明能否 check，並和完成檢查所需資訊連接。", "第二項先接受再要求題目，形成可繼續的對話；其他選項答非所問。"], cognitiveProcess: ["complete-answer-check-request-dialogue", "select-acceptance-plus-needed-material"], representationType: "request-response-completion", misconceptionTargets: ["reply-with-related-fact-not-action"] }),
  question({ id: "ENG_R4_Q_093_11", skillId: "ENG_R4_S093", difficulty: "transfer", stem: "A message says, “Could you bring it later?” Which change makes the message clear?", options: ["Could you bring things?", "Please later.", "Could you bring my science book to Room 3 after lunch?", "You know what I mean."], answerIndex: 2,
    reasons: ["things 仍未指出要帶哪一件物品。", "第二項缺少主要動作與受詞。", "第三項補出物品、地點與時間，收訊者能照做。", "第四項假設對方知道內容，沒有消除含糊。"],
    reviews: ["原訊息中的 it 與 later 都缺乏可辨識指向，需要具體化而非只增加禮貌字。", "第三項提供 my science book、Room 3 與 after lunch，是唯一可執行的版本。"], cognitiveProcess: ["repair-unclear-bring-it-later-request", "supply-object-place-and-time-details"], representationType: "message-clarity-transfer", misconceptionTargets: ["use-pronoun-and-vague-time-without-context"] }),
  question({ id: "ENG_R4_Q_093_12", skillId: "ENG_R4_S093", difficulty: "transfer", stem: "You write to a person at the library because a book is hard to find. Which line politely asks for help?", options: ["Find it for me.", "This book has many pages.", "I found a book yesterday.", "Could you tell me where this book is, please?"], answerIndex: 3,
    reasons: ["第一項像命令，也沒有清楚尊重館員的協助選擇。", "頁數資訊不能幫助詢問書的位置。", "第三項只敘述昨天找到一本書，偏離現在的找書需求。", "第四項有禮地請館員說明這本書的位置。"],
    reviews: ["訊息目的在取得 location information，而不是評論書本或談過去。", "第四項使用 Could you tell me where... 並加 please，語意完整且場合合宜。"], cognitiveProcess: ["select-librarian-location-request-in-writing", "align-polite-form-with-book-finding-goal"], representationType: "written-service-request-transfer", misconceptionTargets: ["use-command-or-biography-in-help-message"] }),

  question({ id: "ENG_R4_Q_094_01", skillId: "ENG_R4_S094", difficulty: "foundation", stem: "A: Could you close the window? B: ___.", options: ["Sure. I will close it now.", "The window was open yesterday.", "I like sunny days.", "The question is about yesterday."], answerIndex: 0,
    reasons: ["Sure 表示接受，後句也承諾立即關窗。", "第二項只談昨天，沒有回應是否願意關窗。", "喜歡晴天和眼前請求無直接關係。", "解釋 could 的一種意思不是自然對話回應。"],
    reviews: ["A 期待 B 採取 close the window 的動作，回應應表明是否願意。", "第一項的接受語與後續行動一致；其餘內容沒有承接當下請求。"], cognitiveProcess: ["complete-window-request-with-acceptance", "verify-promised-action-matches-close"], representationType: "acceptance-dialogue", misconceptionTargets: ["answer-request-with-related-background-fact"] }),
  question({ id: "ENG_R4_Q_094_02", skillId: "ENG_R4_S094", difficulty: "foundation", stem: "A: Can you join us at four? B: ___. I have a class then.", options: ["Of course", "Sorry, I can't", "No problem", "Yes, please"], answerIndex: 1,
    reasons: ["Of course 表示接受，卻和四點有課衝突。", "Sorry, I can't 能自然引出無法參加的理由。", "No problem 通常表示可以做到，和後句不一致。", "Yes, please 多用於接受提供，也無法接上限制。"],
    reviews: ["then 指四點，而有課使 B 不能參加，所以空格必須是婉拒。", "第二項同時維持禮貌與邏輯；其他回應會先接受再立刻否定自己。"], cognitiveProcess: ["complete-four-oclock-invitation-refusal", "use-class-conflict-to-select-cant"], representationType: "reasoned-refusal-cloze", misconceptionTargets: ["choose-positive-politeness-despite-time-conflict"] }),
  question({ id: "ENG_R4_Q_094_03", skillId: "ENG_R4_S094", difficulty: "foundation", stem: "A: Please help me move this chair. B: No problem. What does B mean?", options: ["B thinks the chair is broken.", "B wants a different chair.", "B agrees to help.", "B did the work yesterday."], answerIndex: 2,
    reasons: ["回應沒有評論椅子狀況。", "B 沒有要求更換椅子。", "No problem 在此表示願意協助搬椅子。", "句子是對當下請求的回應，不是過去敘事。"],
    reviews: ["No problem 必須當作完整接受語理解，不能把 No 單獨抽出。", "第三項說明 B 的實際立場，也能預測下一步是幫忙移動椅子。"], cognitiveProcess: ["interpret-no-problem-after-chair-request", "infer-agreement-from-fixed-response"], representationType: "acceptance-phrase-meaning", misconceptionTargets: ["treat-no-problem-as-refusal"] }),
  question({ id: "ENG_R4_Q_094_04", skillId: "ENG_R4_S094", difficulty: "standard", stem: "A: Could you pass the salt? B: ___.", options: ["Salt is white.", "I passed the store.", "Do you use salt every day?", "Of course. Here you are."], answerIndex: 3,
    reasons: ["顏色資訊沒有回應遞鹽請求。", "passed the store 使用不同意思，也把事件放在過去。", "第三項詢問日常用鹽習慣，沒有表示是否遞過去。", "Of course 接受請求，Here you are 表示正在交給對方。"],
    reviews: ["自然餐桌回應應承接 pass the salt，並可配合交付動作。", "第四項前後一致；其他選項只共享 salt 或 pass 等字面元素，功能不合。"], cognitiveProcess: ["select-table-request-fulfillment-response", "connect-here-you-are-to-passing-salt"], representationType: "table-dialogue-completion", misconceptionTargets: ["select-shared-word-without-response-function"] }),
  question({ id: "ENG_R4_Q_094_05", skillId: "ENG_R4_S094", difficulty: "standard", stem: "Which answer politely says no to lending a bike and gives a reason?", options: ["Sorry, I need it this afternoon.", "Yes, my bike is outside.", "Red bikes are easy to see.", "Of course, I cannot ride."], answerIndex: 0,
    reasons: ["道歉加上下午自己要用，清楚且有關地婉拒借車。", "第二項只說車在外面，沒有表明是否借出。", "第三項只評論紅色腳踏車的可見度，沒有回應借用。", "Of course 表接受，但 cannot ride 又與借車問題沒有直接邏輯。"],
    reviews: ["題目同時要求 refusal 與 reason，兩項條件都要出現在回應中。", "第一項的 need it this afternoon 說明無法借出的限制，沒有添加不必要故事。"], cognitiveProcess: ["identify-bike-loan-refusal-with-relevant-reason", "distinguish-decline-from-bike-location-fact"], representationType: "refusal-quality-comparison", misconceptionTargets: ["mistake-related-bike-fact-for-refusal"] }),
  question({ id: "ENG_R4_Q_094_06", skillId: "ENG_R4_S094", difficulty: "standard", stem: "A: Can I use your ruler for a minute? B: ___.", options: ["A ruler has numbers.", "Sure. It is on my desk.", "I used it last Monday.", "Can I use your desk?"], answerIndex: 1,
    reasons: ["描述尺上有數字，沒有給予或拒絕許可。", "Sure 表示同意，並告知尺在桌上方便取得。", "過去使用時間不回答現在能否借用。", "第四項反過來提出另一個借桌子的問題，沒有回答 A。"],
    reviews: ["Can I use...? 是詢問許可，回應要說明是否可借。", "第二項接受後補出物品位置，能自然推進對話；其餘答案沒有處理許可。"], cognitiveProcess: ["complete-ruler-permission-response", "pair-sure-with-access-location"], representationType: "permission-response-dialogue", misconceptionTargets: ["answer-permission-question-with-object-description"] }),
  question({ id: "ENG_R4_Q_094_07", skillId: "ENG_R4_S094", difficulty: "standard", stem: "A: Could you come by eight tomorrow? B: I would like to, but the first bus arrives at nine. What does B mean?", options: ["B will drive the first bus.", "B wants A to arrive at nine.", "B cannot come by eight.", "B came early yesterday."], answerIndex: 2,
    reasons: ["回應沒有說 B 是公車駕駛。", "B 沒有要求 A 改變到達時間。", "首班車九點才到，明確晚於 A 要求的八點。", "對話談 tomorrow，不是昨天。"],
    reviews: ["I would like to 表達意願，但 8:00 與 9:00 的時間比較顯示 B 無法配合。", "第三項直接由班車限制推出，沒有擴大成 B 不喜歡活動或永遠不能早到。"], cognitiveProcess: ["infer-eight-oclock-refusal-from-nine-oclock-bus", "compare-requested-arrival-with-first-available-bus"], representationType: "indirect-refusal-inference", misconceptionTargets: ["stop-reading-after-would-like-to"] }),
  question({ id: "ENG_R4_Q_094_08", skillId: "ENG_R4_S094", difficulty: "advanced", stem: "A: Please water my plants on Friday. Which answer does not tell A whether the person will do it?", options: ["Sure. I will do it Friday morning.", "Sorry, I will be away that day.", "I can do it after school.", "Plants need water to grow."], answerIndex: 3,
    reasons: ["第一項接受並給出執行時段。", "第二項以不在家為理由婉拒。", "第三項表示能在放學後澆水。", "第四項只是植物常識，沒有說是否會幫忙。"],
    reviews: ["回答請求不一定要接受，但至少要表明能否 water the plants。", "第四項和主題相關卻沒有立場，是典型答非所問；前三項都真正回應了任務。"], cognitiveProcess: ["detect-nonresponse-in-plant-watering-dialogue", "separate-topic-relevance-from-request-answer"], representationType: "response-relevance-audit", misconceptionTargets: ["accept-related-fact-as-valid-response"] }),
  question({ id: "ENG_R4_Q_094_09", skillId: "ENG_R4_S094", difficulty: "advanced", stem: "A: Can you bring the blue book? B: Sure. I will get it from my room. What will B probably do next?", options: ["Go to the room for the book", "Ask A to buy a book", "Leave the book at school tomorrow", "Explain why blue is a color"], answerIndex: 0,
    reasons: ["B 已接受，並明說要去房間拿資料夾。", "對話沒有購買需求。", "第三項會違反當下 bring 的承諾。", "說明顏色無法完成拿資料夾的行動。"],
    reviews: ["Sure 與 I will get it 共同建立接受和下一步，it 指 blue book。", "第一項是由原話可直接推出的行動；其他選項都新增未提及目的。"], cognitiveProcess: ["predict-folder-fetch-after-acceptance", "resolve-it-to-blue-folder"], representationType: "accepted-request-next-action", misconceptionTargets: ["ignore-pronoun-link-in-follow-up-action"] }),
  question({ id: "ENG_R4_Q_094_10", skillId: "ENG_R4_S094", difficulty: "advanced", stem: "What does “I am afraid I can't help tonight” mean after someone asks for help?", options: ["It gives a strong order.", "It politely refuses.", "It asks about a past skill.", "It accepts without a time."], answerIndex: 1,
    reasons: ["句子沒有命令別人做事。", "I am afraid 加 I can't 委婉表示今晚無法協助。", "它不在詢問任何人的過去能力。", "can't 明確否定能否幫忙，並非接受。"],
    reviews: ["I am afraid 在這裡是柔化負面回答，不是字面描述恐懼。", "第二項保留整句功能；其他選項把婉拒誤判成命令、能力問題或接受。"], cognitiveProcess: ["classify-im-afraid-cant-as-polite-refusal", "interpret-softener-with-negative-ability"], representationType: "refusal-phrase-function", misconceptionTargets: ["read-afraid-literally-and-miss-refusal"] }),
  question({ id: "ENG_R4_Q_094_11", skillId: "ENG_R4_S094", difficulty: "transfer", stem: "A: Could we move our meeting from Tuesday to Wednesday? Which answer accepts the change?", options: ["Tuesday comes before Wednesday.", "I have never seen that room.", "Wednesday works for me.", "Meetings can be long."], answerIndex: 2,
    reasons: ["日序常識沒有表明是否同意改期。", "第二項談房間經驗，和日期變更無關。", "Wednesday works for me 表示新日期可配合。", "會議可能很長不回答能否改到星期三。"],
    reviews: ["接受改期必須對 Wednesday 的可行性做出肯定。", "第三項以 works for me 清楚表示配合；其他答案雖提到會議或日期，仍沒有接受。"], cognitiveProcess: ["identify-acceptance-of-meeting-date-change", "map-works-for-me-to-schedule-agreement"], representationType: "schedule-change-response", misconceptionTargets: ["select-calendar-fact-instead-of-agreement"] }),
  question({ id: "ENG_R4_Q_094_12", skillId: "ENG_R4_S094", difficulty: "transfer", stem: "A: Please feed my cat tonight. B: Sorry, I have to work, but my sister can do it. What is the best reading?", options: ["B accepts and will feed the cat alone.", "B refuses and offers no help.", "B asks A to feed another cat.", "B cannot do it but offers another person who can."], answerIndex: 3,
    reasons: ["B 明說要工作，因此不會親自完成。", "B 雖婉拒本人執行，仍提出妹妹可以幫忙。", "貓屬於 A，B 沒有反向提出請求。", "第四項同時保留 B 的限制與替代協助。"],
    reviews: ["回應包含兩層：Sorry 加工作理由是婉拒，but 後則提供解決方案。", "第四項完整解釋整句，不能只依前半或後半把它簡化成純接受或純拒絕。"], cognitiveProcess: ["integrate-cat-request-refusal-and-alternative", "distinguish-personal-inability-from-no-help"], representationType: "compound-response-transfer", misconceptionTargets: ["ignore-alternative-after-refusal"] }),

  question({ id: "ENG_R4_Q_095_01", skillId: "ENG_R4_S095", difficulty: "foundation", stem: "Would you like ___ tea?", options: ["some", "to", "drink", "drank"], answerIndex: 0,
    reasons: ["some 可修飾 tea，形成當下提供飲料的問句。", "to 後缺少動詞，不能直接接 tea。", "drink 和 tea 之間缺少必要結構。", "drank 是過去式，與提供問句不合。"],
    reviews: ["Would you like 後直接接名詞片語時，可用 some tea 表示提供。", "第一項完成自然餐飲問句；其餘項目不是可放在 tea 前的合適形式。"], cognitiveProcess: ["complete-current-tea-offer-with-some", "distinguish-noun-offer-from-infinitive-invitation"], representationType: "food-offer-cloze", misconceptionTargets: ["insert-to-before-offered-noun"] }),
  question({ id: "ENG_R4_Q_095_02", skillId: "ENG_R4_S095", difficulty: "foundation", stem: "Would you like ___ us for lunch?", options: ["joining", "to join", "joins", "joined"], answerIndex: 1,
    reasons: ["joining 不能直接跟在 would like 後表達這項邀請。", "to join 正確邀請對方加入午餐。", "joins 是第三人稱單數形式。", "joined 是過去式，無法表達眼前邀請。"],
    reviews: ["邀請活動使用 Would you like to + base form，受詞 us 跟在 join 後。", "第二項符合句型與語意；其他選項都缺少不定詞或使用錯誤動詞形式。"], cognitiveProcess: ["form-lunch-invitation-with-to-join", "attach-us-as-object-of-join"], representationType: "invitation-form-cloze", misconceptionTargets: ["use-gerund-after-would-like"] }),
  question({ id: "ENG_R4_Q_095_03", skillId: "ENG_R4_S095", difficulty: "foundation", stem: "A: Would you like some cake? B: No, thank you. What does B mean?", options: ["B wants two pieces.", "B wants to make a cake.", "B does not accept the cake now.", "B never eats cake."], answerIndex: 2,
    reasons: ["No, thank you 沒有要求兩塊。", "B 沒有提到製作蛋糕。", "這是對當下提供的有禮婉拒。", "一次拒絕不足以證明 B 永遠不吃蛋糕。"],
    reviews: ["判讀範圍只限這次 cake offer，不能擴大成永久喜好。", "第三項精確描述眼前選擇；第四項是超出證據的絕對推論。"], cognitiveProcess: ["interpret-no-thank-you-in-cake-offer", "limit-decline-inference-to-current-offer"], representationType: "offer-response-meaning", misconceptionTargets: ["infer-permanent-dislike-from-one-decline"] }),
  question({ id: "ENG_R4_Q_095_04", skillId: "ENG_R4_S095", difficulty: "standard", stem: "Which question asks about a person's usual taste rather than offering a drink now?", options: ["Would you like some water?", "Would you like a cup of milk?", "Would you like some juice now?", "Do you like coffee?"], answerIndex: 3,
    reasons: ["第一項在當下提供水。", "第二項提供一杯牛奶。", "now 使第三項明確成為眼前果汁提供。", "Do you like coffee? 通常詢問一般喜好。"],
    reviews: ["usual taste 要找長期偏好，而非是否接受眼前物品。", "第四項使用 Do you like；前三項都以 Would you like 提供特定飲料。"], cognitiveProcess: ["contrast-usual-coffee-preference-with-current-offers", "identify-do-you-like-function"], representationType: "preference-offer-contrast", misconceptionTargets: ["equate-do-you-like-with-immediate-offer"] }),
  question({ id: "ENG_R4_Q_095_05", skillId: "ENG_R4_S095", difficulty: "standard", stem: "A: Would you like to play basketball after school? B wants to accept. What can B say?", options: ["Yes, I would love to.", "Sorry, I have a class then.", "The team played yesterday.", "I like basketball at school."], answerIndex: 0,
    reasons: ["Yes, I would love to 自然接受活動邀請。", "第二項是有時間理由的婉拒，不符合 B 想接受的條件。", "第三項只敘述球隊昨天比賽。", "第四項表達一般喜好，仍未明確接受這次活動。"],
    reviews: ["題幹明說 B wants to accept，因此答案必須清楚承諾參加。", "第一項接受邀請且可省略重複的 play basketball；其餘回應是拒絕、過去資訊或一般喜好。"], cognitiveProcess: ["select-basketball-acceptance-under-explicit-intent", "interpret-would-love-to-as-join-response"], representationType: "activity-invitation-dialogue", misconceptionTargets: ["respond-to-activity-as-general-preference"] }),
  question({ id: "ENG_R4_Q_095_06", skillId: "ENG_R4_S095", difficulty: "standard", stem: "A worker at a restaurant asks, “Would you like rice or noodles?” What is the worker doing?", options: ["Asking what the customer ate yesterday", "Offering two food choices", "Testing whether the customer can cook", "Inviting the customer to work"], answerIndex: 1,
    reasons: ["問題沒有過去時間或已吃內容。", "rice or noodles 提供兩個當下餐點選擇。", "它不在測量烹飪能力。", "句中沒有工作邀請。"],
    reviews: ["餐廳角色與兩項食物指出這是 offer with choices。", "第二項說明服務生的實際目的；其他選項改變時間、能力或活動。"], cognitiveProcess: ["classify-server-rice-noodle-offer", "use-role-and-food-alternatives-as-evidence"], representationType: "service-offer-function", misconceptionTargets: ["read-would-you-like-as-general-preference-test"] }),
  question({ id: "ENG_R4_Q_095_07", skillId: "ENG_R4_S095", difficulty: "standard", stem: "A: Would you like to come to the beach on Sunday? B: I would like to, but I have to visit my aunt. What does B mean?", options: ["B will bring the aunt to the beach.", "B asks A to change the beach.", "B cannot accept the invitation.", "B does not like beaches."], answerIndex: 2,
    reasons: ["回應沒有說阿姨會同行。", "B 沒有要求更換地點。", "星期日探望阿姨造成時間衝突，所以 B 婉拒。", "B 的 I would like to 反而顯示活動本身可能有吸引力。"],
    reviews: ["but 後的既定安排決定 B 最終無法參加，不能停在正面開頭。", "第三項只推論邀請結果，不把婉拒錯誤擴大成討厭海灘。"], cognitiveProcess: ["infer-sunday-beach-decline-from-family-duty", "separate-unavailability-from-dislike"], representationType: "invitation-refusal-reading", misconceptionTargets: ["interpret-decline-as-negative-preference"] }),
  question({ id: "ENG_R4_Q_095_08", skillId: "ENG_R4_S095", difficulty: "advanced", stem: "Would you like to ___ the art club with me?", options: ["joining", "joined", "joins", "join"], answerIndex: 3,
    reasons: ["joining 不能接在 would like to 後。", "joined 是過去式，和邀請形式不合。", "joins 把社團邀請中的主要動詞誤加了第三人稱詞尾。", "join 是 to 後所需原形，表示加入社團。"],
    reviews: ["with me 顯示說話者邀請對方共同加入，而不是詢問既有喜好。", "第四項完成 to join；前三項都對主要動詞做了錯誤屈折。"], cognitiveProcess: ["complete-art-club-invitation-form", "retain-join-base-after-would-like-to"], representationType: "club-invitation-cloze", misconceptionTargets: ["inflect-verb-after-invitation-to"] }),
  question({ id: "ENG_R4_Q_095_09", skillId: "ENG_R4_S095", difficulty: "advanced", stem: "A guest has just arrived. Which line naturally offers something to drink?", options: ["Would you like some water?", "Do you drink water every day?", "You had water last night.", "Could you close the door, please?"], answerIndex: 0,
    reasons: ["Would you like some water? 直接向剛到的客人提供飲料。", "第二項詢問日常習慣，不是眼前招待。", "第三項談昨晚，沒有提供現在的水。", "第四項是關門請求，雖然自然卻沒有提供飲料。"],
    reviews: ["guest has just arrived 建立招待場景，答案需讓對方決定是否接受飲品。", "第一項符合角色與時點；其餘句子只是習慣、過去事件或無意義問句。"], cognitiveProcess: ["select-arriving-guest-drink-offer", "match-would-you-like-to-hosting-context"], representationType: "hosting-offer-transfer", misconceptionTargets: ["ask-general-habit-instead-of-offering-now"] }),
  question({ id: "ENG_R4_Q_095_10", skillId: "ENG_R4_S095", difficulty: "advanced", stem: "Mia says, “I would like to learn to cook.” What is Mia expressing?", options: ["An offer of food", "A wish to learn", "An invitation to a meal", "A rule about cooking"], answerIndex: 1,
    reasons: ["Mia 沒有把食物提供給別人。", "I would like to learn 表達她想學習的願望。", "句中沒有邀請對象或活動時間。", "這不是要求所有人遵守的規則。"],
    reviews: ["主詞 I 與 learn 指向說話者自己的願望，功能不同於 Would you like...? 問句。", "第二項保留陳述句的內容；不能看到 would like 就一律判成邀請或提供。"], cognitiveProcess: ["classify-i-would-like-to-learn-as-wish", "separate-personal-desire-from-question-functions"], representationType: "would-like-statement-function", misconceptionTargets: ["treat-all-would-like-forms-as-offers"] }),
  question({ id: "ENG_R4_Q_095_11", skillId: "ENG_R4_S095", difficulty: "transfer", stem: "A: Would you like to see a movie at seven? B: That sounds fun, but I work until eight. What is true?", options: ["B will leave work at seven.", "B thinks the movie starts at eight.", "B cannot join at the given time.", "B asks A for a job."], answerIndex: 2,
    reasons: ["B 說工作到八點，沒有證據會七點離開。", "電影時間由 A 說是七點，B 沒有改成八點。", "工作結束晚於電影開始，使 B 無法按時參加。", "對話沒有求職內容。"],
    reviews: ["sounds fun 顯示正面態度，but 後的時間線卻決定邀請結果。", "第三項可由 7:00 與 until 8:00 比較得到，沒有推論 B 不喜歡電影。"], cognitiveProcess: ["compare-movie-start-with-work-end", "infer-decline-despite-positive-reaction"], representationType: "time-conflict-invitation-transfer", misconceptionTargets: ["equate-positive-comment-with-availability"] }),
  question({ id: "ENG_R4_Q_095_12", skillId: "ENG_R4_S095", difficulty: "transfer", stem: "Which line offers an item rather than inviting someone to an activity?", options: ["Would you like to walk with us?", "Would you like to watch the game?", "Would you like to visit the market?", "Would you like a clean towel?"], answerIndex: 3,
    reasons: ["to walk 邀請對方參與步行。", "to watch 邀請對方看比賽。", "to visit 邀請對方去市場。", "a clean towel 是可接受或婉拒的物品提供。"],
    reviews: ["item offer 的 Would you like 後直接接名詞，而活動邀請使用 to + verb。", "第四項是唯一名詞片語；前三項都期待對方參與某項行動。"], cognitiveProcess: ["distinguish-towel-offer-from-three-activity-invitations", "use-noun-versus-infinitive-structure"], representationType: "offer-invitation-structure-transfer", misconceptionTargets: ["classify-all-would-you-like-as-invitations"] }),

  question({ id: "ENG_R4_Q_096_01", skillId: "ENG_R4_S096", difficulty: "foundation", stem: "Let's ___ at the front gate at three.", options: ["meet", "meets", "met", "meeting"], answerIndex: 0,
    reasons: ["Let's 後使用原形 meet，提出共同會合建議。", "meets 帶第三人稱單數詞尾。", "met 是過去式，不能接在 Let's 後。", "meeting 是分詞，不是此結構所需形式。"],
    reviews: ["at the front gate at three 提供共同見面的地點與時間。", "第一項符合 Let's + base form；其他三項都錯改了 meet。"], cognitiveProcess: ["complete-front-gate-meeting-suggestion", "retain-meet-base-after-lets"], misconceptionTargets: ["inflect-verb-after-lets"] }),
  question({ id: "ENG_R4_Q_096_02", skillId: "ENG_R4_S096", difficulty: "foundation", stem: "How about ___ lunch in the park?", options: ["eat", "eating", "to eat", "ate"], answerIndex: 1,
    reasons: ["原形 eat 不能直接跟在介系詞 about 後。", "eating 是 V-ing，正確表達在公園吃午餐的建議。", "to eat 不是本句 How about 後採用的形式。", "ate 是過去式，無法提出共同計畫。"],
    reviews: ["about 後要把動作名詞化，因此選 eating，而不是看 lunch 決定時態。", "第二項完成 How about eating...?；另外三項都不符合介系詞後的形式。"], cognitiveProcess: ["form-park-lunch-suggestion-with-gerund", "apply-ing-after-how-about"], representationType: "how-about-gerund-cloze", misconceptionTargets: ["use-base-or-infinitive-after-about"] }),
  question({ id: "ENG_R4_Q_096_03", skillId: "ENG_R4_S096", difficulty: "foundation", stem: "The bus is almost here. Let's ___ go back to the store.", options: ["don't", "no", "not", "doesn't"], answerIndex: 2,
    reasons: ["Let's don't 不是本單元採用的標準否定建議。", "no 不能直接修飾 go 形成此句。", "Let's not go 正確建議大家不要折返商店。", "doesn't 需要第三人稱主詞，不能放在 Let's 後。"],
    reviews: ["公車即將到站，說話者建議共同避免回頭，需用 Let's not。", "第三項把 not 放在原形 go 前；其餘否定形式無法構成此建議。"], cognitiveProcess: ["form-negative-return-to-store-suggestion", "place-not-between-lets-and-go"], representationType: "negative-lets-cloze", misconceptionTargets: ["use-dont-after-lets"] }),
  question({ id: "ENG_R4_Q_096_04", skillId: "ENG_R4_S096", difficulty: "standard", stem: "A: Let's take the train. B: ___. It will save time.", options: ["The train was late yesterday.", "I cannot hear a train.", "A train has many seats.", "That sounds good."], answerIndex: 3,
    reasons: ["過去誤點資訊未必接受眼前建議，也無法接上節省時間。", "第二項談聽覺，和搭車計畫無關。", "座位數量只是火車資訊，不能自然引出節省時間。", "That sounds good 表示認同，後句再提供節省時間的理由。"],
    reviews: ["It will save time 支持搭火車，因此前句應是正面接受語。", "第四項讓立場與理由一致；其他回應無法自然連接後句。"], cognitiveProcess: ["complete-train-suggestion-acceptance-with-reason", "link-time-saving-to-sounds-good"], representationType: "suggestion-response-cloze", misconceptionTargets: ["choose-transport-fact-instead-of-acceptance"] }),
  question({ id: "ENG_R4_Q_096_05", skillId: "ENG_R4_S096", difficulty: "standard", stem: "It is raining, and the picnic tables are outside. Which idea solves the problem?", options: ["Let's eat inside.", "Let's put more food outside.", "How about wearing wet shoes?", "Let's not look at the rain."], answerIndex: 0,
    reasons: ["移到室內用餐能避開雨水，直接處理戶外桌子的問題。", "把更多食物放到外面會使問題更嚴重。", "穿濕鞋不能讓野餐保持乾燥。", "不看雨不會改變桌子在戶外的事實。"],
    reviews: ["有效建議須同時回應 rain 與 outside tables，而非只使用正確句型。", "第一項改變用餐地點，能達成保持乾燥的目標；其他選項沒有解決因果。"], cognitiveProcess: ["evaluate-rainy-picnic-solutions", "choose-indoor-eating-as-cause-focused-suggestion"], representationType: "problem-solving-suggestion", misconceptionTargets: ["select-grammatical-but-ineffective-suggestion"] }),
  question({ id: "ENG_R4_Q_096_06", skillId: "ENG_R4_S096", difficulty: "standard", stem: "Which words can follow “How about” to suggest a bike ride?", options: ["ride our bikes", "riding our bikes", "to riding our bikes", "used our bikes yesterday"], answerIndex: 1,
    reasons: ["ride 是原形，不能直接接在 about 後。", "riding our bikes 是合適的 V-ing 片語。", "to riding 疊加了不需要的 to。", "used our bikes yesterday 是過去敘述，不能填入這項建議。"],
    reviews: ["題目指定接在 How about 後，因此判斷依據是介系詞後的動詞形式。", "第二項形成 How about riding our bikes?；其餘三項都不符合該位置。"], cognitiveProcess: ["select-bike-ride-gerund-phrase", "exclude-base-infinitive-and-past-after-about"], representationType: "suggestion-phrase-form", misconceptionTargets: ["treat-about-like-infinitive-marker"] }),
  question({ id: "ENG_R4_Q_096_07", skillId: "ENG_R4_S096", difficulty: "standard", stem: "What does “Let's check the map before we leave” ask people to do?", options: ["Buy a new map tomorrow", "Remember a trip from last year", "Check the map together first", "Leave before anyone sees the map"], answerIndex: 2,
    reasons: ["句子沒有要求購買，也沒有 tomorrow。", "它不是回顧過去旅行。", "Let's 包含說話者，before 指明離開前共同查看地圖。", "第四項把 before 的順序反轉。"],
    reviews: ["這項建議同時包含共同動作 check 與時間關係 before we leave。", "第三項保留兩個資訊；其他答案添加新事件或顛倒順序。"], cognitiveProcess: ["interpret-map-checking-lets-suggestion", "resolve-before-leaving-order"], representationType: "suggestion-meaning-reading", misconceptionTargets: ["treat-lets-as-order-to-others-only"] }),
  question({ id: "ENG_R4_Q_096_08", skillId: "ENG_R4_S096", difficulty: "advanced", stem: "How is “Let's open the window” different from “Open the window”?", options: ["Only the second sentence is about a window.", "The first is always a question.", "The second can only describe the past.", "The first suggests a shared action; the second directly tells the listener what to do."], answerIndex: 3,
    reasons: ["兩句都明確談到 window。", "Let's 句形式是建議，不是疑問句。", "Open 開頭的是祈使句，不是過去敘事。", "Let's 通常包含說話者，單獨 Open 則直接指向聽者行動。"],
    reviews: ["比較重點是參與者範圍與溝通功能，不是單看同一個動詞 open。", "第四項呈現共同建議和直接指示的差異，沒有把任何形式絕對化成無禮。"], cognitiveProcess: ["contrast-shared-lets-with-listener-imperative", "identify-participant-scope-in-open-sentences"], representationType: "suggestion-command-contrast", misconceptionTargets: ["treat-lets-as-identical-to-direct-command"] }),
  question({ id: "ENG_R4_Q_096_09", skillId: "ENG_R4_S096", difficulty: "advanced", stem: "A: We need a quiet place to study. B: How about the library? Why does B say this?", options: ["To suggest a place", "To ask who built it", "To report a lost book", "To refuse to study"], answerIndex: 0,
    reasons: ["How about the library? 提出一個符合安靜需求的地點選項。", "B 沒有詢問建造者。", "對話沒有遺失書本。", "提出圖書館並非拒絕讀書。"],
    reviews: ["How about 後可接名詞，這裡省略的是完整前往或在該處讀書的想法。", "第一項由 quiet place 的需求直接支持；其他目的都沒有文本證據。"], cognitiveProcess: ["infer-library-as-noun-phrase-suggestion", "connect-quiet-study-goal-to-place-option"], representationType: "elliptical-suggestion-function", misconceptionTargets: ["expect-gerund-after-every-how-about"] }),
  question({ id: "ENG_R4_Q_096_10", skillId: "ENG_R4_S096", difficulty: "advanced", stem: "A: The line for food is very long. B: How about eating after the game? What is B suggesting?", options: ["Leaving the game now", "Waiting to eat until the game ends", "Buying all the food", "Playing while standing in line"], answerIndex: 1,
    reasons: ["B 沒有建議離開比賽。", "after the game 表示把吃東西延後到比賽結束。", "句中沒有購買全部食物。", "B 的做法是改變用餐時間，不是排隊時比賽。"],
    reviews: ["長隊伍是問題，after the game 是 B 提出的時間調整。", "第二項準確解讀 eating 的時點；其他選項都加入未提到的行動。"], cognitiveProcess: ["interpret-delayed-eating-suggestion", "use-after-game-to-set-new-time"], representationType: "timing-suggestion-inference", misconceptionTargets: ["ignore-time-phrase-in-how-about"] }),
  question({ id: "ENG_R4_Q_096_11", skillId: "ENG_R4_S096", difficulty: "transfer", stem: "The first bus is full, but another one comes in five minutes. Which idea is most useful?", options: ["Let's walk away from the bus stop.", "How about forgetting the trip?", "Let's wait for the next bus.", "Let's get on the full bus without space."], answerIndex: 2,
    reasons: ["離開站牌會錯過五分鐘後的公車。", "放棄旅程沒有利用可用資訊解決交通問題。", "等下一班能避開已滿車輛，且只需五分鐘。", "沒有空間仍上車既不實際，也忽略 full。"],
    reviews: ["有效建議應利用 another one comes in five minutes 這項關鍵條件。", "第三項直接回應容量問題，代價也由題幹限定；其餘方案放棄目標或不安全。"], cognitiveProcess: ["choose-next-bus-solution-from-capacity-and-wait", "evaluate-suggestion-against-trip-goal"], representationType: "transport-suggestion-transfer", misconceptionTargets: ["choose-action-unrelated-to-available-alternative"] }),
  question({ id: "ENG_R4_Q_096_12", skillId: "ENG_R4_S096", difficulty: "transfer", stem: "A: Let's visit the market after dinner. B: It closes at six, before dinner. What does B mean?", options: ["The market serves dinner.", "B visited at six yesterday.", "B is inviting A to eat there.", "The time in the idea will not work."], answerIndex: 3,
    reasons: ["B 沒有說市場供餐。", "句子是一般關門時間，不是昨天的造訪。", "B 未提出在市場吃飯。", "市場在晚餐前已關門，所以晚餐後去不可行。"],
    reviews: ["B 沒有直接說 No，卻用 closing time 否定了建議的可行性。", "第四項由時間先後得到，且沒有超出對話推論 B 的個人喜好。"], cognitiveProcess: ["infer-market-suggestion-rejection-from-closing-time", "compare-after-dinner-with-before-dinner-closure"], representationType: "indirect-suggestion-rejection", misconceptionTargets: ["miss-refusal-without-explicit-no"] }),

  question({ id: "ENG_R4_Q_097_01", skillId: "ENG_R4_S097", difficulty: "foundation", stem: "You need help from a person at the library. Which opening is best?", options: ["Excuse me. Could you help me find this book?", "Find this book now.", "You work at the library.", "A book is on a shelf."], answerIndex: 0,
    reasons: ["Excuse me 先取得注意，Could you 再清楚而尊重地求助。", "第二項對不熟悉的館員過度直接。", "說明對方身分沒有提出具體需求。", "第四項只是一般事實，無法指出要找哪本書。"],
    reviews: ["服務情境需要兼顧 attention、specific action 與尊重。", "第一項具備三項資訊；其他句子不是合宜請求或無法讓館員採取行動。"], cognitiveProcess: ["select-respectful-librarian-help-opening", "balance-attention-and-specific-book-request"], representationType: "formal-help-request", misconceptionTargets: ["use-bare-command-in-service-setting"] }),
  question({ id: "ENG_R4_Q_097_02", skillId: "ENG_R4_S097", difficulty: "foundation", stem: "A bike is moving toward a child who does not see it. What should you shout?", options: ["Could you move later?", "Watch out!", "Would you like a bike?", "The bike is green."], answerIndex: 1,
    reasons: ["later 太含糊且太慢，不能處理眼前危險。", "Watch out! 短而明確，能讓孩子立即注意。", "第三項像在提供腳踏車，完全改變目的。", "顏色資訊無法警告孩子避開。"],
    reviews: ["即時安全風險使反應速度比委婉長句更重要。", "第二項是直接但合宜的警告；其他選項延誤、誤導或只描述物體。"], cognitiveProcess: ["choose-urgent-bike-warning-for-child", "prioritize-immediate-safety-over-politeness-length"], representationType: "emergency-tone-selection", misconceptionTargets: ["use-overly-polite-delay-in-danger"] }),
  question({ id: "ENG_R4_Q_097_03", skillId: "ENG_R4_S097", difficulty: "foundation", stem: "You ask a classmate to move one notebook. Which line is polite and not overly formal?", options: ["Move it.", "You must move this notebook for me.", "Can you move this notebook, please?", "Is this notebook heavy for you?"], answerIndex: 2,
    reasons: ["第一項缺少柔和語氣，容易像命令。", "第二項用語不自然，對小協助過度正式。", "Can you 加 please 清楚且符合同學間的小請求。", "第四項沒有直接請同學採取行動。"],
    reviews: ["情境負擔很小，目標是自然尊重，不是選最長句。", "第三項的直接程度與同學關係相稱；其餘選項太硬、太怪或太含糊。"], cognitiveProcess: ["calibrate-classmate-notebook-request-tone", "avoid-under-and-over-formality"], representationType: "peer-request-register", misconceptionTargets: ["equate-longer-sentence-with-better-politeness"] }),
  question({ id: "ENG_R4_Q_097_04", skillId: "ENG_R4_S097", difficulty: "standard", stem: "You need a teacher to explain one step again. Which line works best here?", options: ["Explain it.", "You did not teach.", "One step is on the board.", "Could you explain this step again, please?"], answerIndex: 3,
    reasons: ["第一項過度直接，沒有顯示對老師的尊重。", "第二項像指責老師，也未清楚指出要重說哪一步。", "第三項只是位置資訊。", "第四項具體指出 this step 與 again，並使用合宜請求語氣。"],
    reviews: ["學生需要的是針對單一步驟的再說明，而不是批評或泛稱不懂。", "第四項資訊完整且尊重角色關係；其餘句子不能自然達成學習需求。"], cognitiveProcess: ["select-teacher-step-reexplanation-request", "combine-specific-reference-with-respectful-could"], representationType: "teacher-request-register", misconceptionTargets: ["replace-request-with-blame"] }),
  question({ id: "ENG_R4_Q_097_05", skillId: "ENG_R4_S097", difficulty: "standard", stem: "A guide tells a group how to reach the river. Which line gives clear directions?", options: ["Turn right at the bridge, then walk for five minutes.", "Could you tell me if rivers are long?", "Would everyone enjoy the idea of a bridge?", "The river was long last year."], answerIndex: 0,
    reasons: ["路線指示需清楚給出轉向與步行時間，祈使句在此合宜。", "第二項詢問河流長度，沒有提供前往方向。", "第三項詢問感受，不能帶領隊伍抵達。", "第四項是無關的過去描述。"],
    reviews: ["guide 的任務是有效傳達 directions，直接形式不等同失禮。", "第一項能被立即照做；其他句子為了看似委婉而失去路線資訊。"], cognitiveProcess: ["identify-direct-route-guidance-as-appropriate", "value-actionable-directions-over-empty-politeness"], representationType: "instruction-register-context", misconceptionTargets: ["reject-all-direct-imperatives-as-rude"] }),
  question({ id: "ENG_R4_Q_097_06", skillId: "ENG_R4_S097", difficulty: "standard", stem: "Which line still asks too much even though it includes “please”?", options: ["Please pass me the pencil beside you.", "Please do all my homework tonight.", "Please wait here for one minute.", "Please tell me when the store opens."], answerIndex: 1,
    reasons: ["遞旁邊的鉛筆是小而明確的協助。", "要求別人完成全部作業負擔過大，please 不能使它合理。", "等一分鐘是有限且清楚的請求。", "詢問開店時間是一般資訊需求。"],
    reviews: ["禮貌評估不能只掃描 please，還要考慮負擔與要求本身。", "第二項把自己的全部責任轉給他人，即使有禮貌詞仍不合宜。"], cognitiveProcess: ["evaluate-request-burden-beyond-please", "identify-homework-demand-as-unreasonable"], representationType: "politeness-boundary-comparison", misconceptionTargets: ["assume-please-makes-any-demand-acceptable"] }),
  question({ id: "ENG_R4_Q_097_07", skillId: "ENG_R4_S097", difficulty: "standard", stem: "You ask a neighbor you do not know well to watch your dog for two days. Which line best respects the neighbor's time?", options: ["Watch my dog.", "My dog likes people.", "Could you watch my dog for two days? It is fine if you cannot.", "Dogs need food every day."], answerIndex: 2,
    reasons: ["第一項把較大的協助說成直接命令。", "描述狗的個性沒有詢問鄰居是否願意。", "第三項說明期限，並明確保留鄰居拒絕的空間。", "第四項只是照顧常識，沒有提出請求。"],
    reviews: ["兩天照顧需要時間與責任，因此語氣應承認對方可能無法答應。", "第三項在清楚需求之外保留選擇，最符合不熟鄰居與較大負擔。"], cognitiveProcess: ["calibrate-two-day-dog-care-request", "preserve-neighbor-option-to-decline"], representationType: "high-burden-request-register", misconceptionTargets: ["use-command-for-large-favor"] }),
  question({ id: "ENG_R4_Q_097_08", skillId: "ENG_R4_S097", difficulty: "advanced", stem: "What is true when you ask people for help?", options: ["The longest line is always best.", "A line with please can never be rude.", "Direct words are never useful.", "The best wording depends on the people, the work, and whether help is needed right away."], answerIndex: 3,
    reasons: ["長度不保證清楚或尊重。", "please 不能補救不合理內容或不當關係。", "警告與操作指示常需要直接。", "關係、負擔與急迫性共同決定合宜語氣。"],
    reviews: ["題目要求可跨情境成立的原則，前三項都使用 always 或 never 過度絕對化。", "第四項保留語用判斷所需變因，符合本技能的邊界。"], cognitiveProcess: ["state-context-dependent-politeness-principle", "reject-absolute-length-please-and-directness-rules"], representationType: "register-principle-boundary", misconceptionTargets: ["memorize-fixed-politeness-ranking"] }),
  question({ id: "ENG_R4_Q_097_09", skillId: "ENG_R4_S097", difficulty: "advanced", stem: "You see smoke near a classroom door. Which message should come first?", options: ["Stay back and tell a teacher now!", "Would you like to think about smoke later?", "Could everyone perhaps discuss the door tomorrow?", "The classroom door is brown."], answerIndex: 0,
    reasons: ["第一項立即讓人遠離風險並通知教師。", "延後思考不能處理正在發生的煙霧。", "明天討論會錯過眼前安全需求。", "門的顏色與危險處置無關。"],
    reviews: ["smoke near a classroom 是需要立即反應的安全情境。", "第一項直接度具有功能必要性；其他句子過慢、迴避行動或只描述外觀。"], cognitiveProcess: ["prioritize-smoke-safety-message", "combine-distance-and-adult-alert-actions"], representationType: "urgent-school-safety-transfer", misconceptionTargets: ["choose-politeness-over-immediate-hazard-response"] }),
  question({ id: "ENG_R4_Q_097_10", skillId: "ENG_R4_S097", difficulty: "advanced", stem: "You want an older passenger to move a bag so you can sit. Which line is best?", options: ["Move your bag.", "Excuse me. Could you move your bag, please?", "Your bag has a seat.", "I sat here yesterday."], answerIndex: 1,
    reasons: ["第一項太像直接命令，未尊重陌生乘客。", "Excuse me 取得注意，Could you 與 please 合宜提出小幅移動請求。", "第三項語意不自然，也未說明要做什麼。", "昨天座位情況不回答眼前需求。"],
    reviews: ["陌生人與公共交通場景需要禮貌開場，動作仍要明確。", "第二項兼顧關係與目的；其他選項過硬、含糊或偏離現在。"], cognitiveProcess: ["select-public-seat-bag-request-register", "use-excuse-me-before-stranger-favor"], representationType: "public-space-request", misconceptionTargets: ["issue-command-to-unfamiliar-passenger"] }),
  question({ id: "ENG_R4_Q_097_11", skillId: "ENG_R4_S097", difficulty: "transfer", stem: "A club leader wants members to change Saturday's meeting time. Which message best asks for an answer?", options: ["The meeting changes. Follow it.", "Saturday has many hours.", "Could we meet at ten, not nine? Please tell me if that works for you.", "Meetings are important."], answerIndex: 2,
    reasons: ["第一項直接宣布，沒有讓成員回應是否可配合。", "第二項是一般事實，沒有提出新時間。", "第三項清楚比較十點與九點，並邀請成員回覆。", "第四項評論會議重要，仍缺少變更內容。"],
    reviews: ["團體改期會影響多人，訊息需要明確 proposal 與 feedback path。", "第三項尊重成員安排，也能取得是否可行的資訊；其餘句子沒有完成協調。"], cognitiveProcess: ["evaluate-club-time-change-message", "select-specific-proposal-with-feedback-request"], representationType: "group-coordination-transfer", misconceptionTargets: ["announce-change-without-consulting-affected-people"] }),
  question({ id: "ENG_R4_Q_097_12", skillId: "ENG_R4_S097", difficulty: "transfer", stem: "Why can “Stop!” work in one case but “Could you stop, please?” in another?", options: ["Stop is only used in books.", "“Could you” always means something in the past.", "Adding please changes the question into a test of skill.", "Danger happening now needs fast words; a question for help when there is no danger can be more gentle."], answerIndex: 3,
    reasons: ["Stop 也常出現在真實警告，不只書本。", "Could you 可提出現在的請求，不一定談過去。", "please 調整語氣，不會把動作改成能力測驗。", "急迫程度不同會合理改變句子的直接度。"],
    reviews: ["兩種形式都可能正確，必須由 danger versus ordinary interaction 決定。", "第四項解釋功能差異，而不是把其中一種永遠判成不禮貌或錯誤。"], cognitiveProcess: ["explain-contextual-choice-between-stop-forms", "relate-urgency-to-directness"], representationType: "register-reasoning-transfer", misconceptionTargets: ["apply-one-politeness-form-to-all-contexts"] }),

  question({ id: "ENG_R4_Q_098_01", skillId: "ENG_R4_S098", difficulty: "foundation", stem: "A: Would you like some soup? B: Yes, please. What is A doing?", options: ["Offering soup", "Telling B about danger", "Asking about a past meal", "Refusing an invitation"], answerIndex: 0,
    reasons: ["Would you like some soup? 讓 B 決定是否接受眼前的湯。", "對話沒有危險或警告。", "句中沒有過去時間，也不是問已吃內容。", "A 是提出物品，不是在拒絕他人。"],
    reviews: ["some soup 與 Yes, please 的回應組合可確認這是 offer。", "第一項解釋雙方下一步；其餘功能都無法說明 B 為何用接受提供的回應。"], cognitiveProcess: ["infer-soup-offer-from-question-and-acceptance", "use-yes-please-as-function-evidence"], representationType: "offer-dialogue-function", misconceptionTargets: ["classify-would-you-like-without-object-structure"] }),
  question({ id: "ENG_R4_Q_098_02", skillId: "ENG_R4_S098", difficulty: "foundation", stem: "A: Would you like to come to our game? B: I would love to. What is A doing?", options: ["Selling a game", "Inviting B to go to the game", "Testing whether B can play", "Ordering B to play"], answerIndex: 1,
    reasons: ["A 沒有談價格或交易。", "Would you like to come...? 加上 B 的接受，表示出席邀請。", "問句不是在測量 B 能不能完成某技能。", "B 可自行接受或拒絕，不是命令參賽。"],
    reviews: ["to come to our game 指向一項未來活動，I would love to 證實 B 願意參加。", "第二項保留 invitation 的選擇性；其他答案把活動改成買賣、測驗或命令。"], cognitiveProcess: ["identify-game-attendance-invitation", "confirm-function-through-would-love-to-response"], representationType: "invitation-dialogue-function", misconceptionTargets: ["mistake-invitation-for-command"] }),
  question({ id: "ENG_R4_Q_098_03", skillId: "ENG_R4_S098", difficulty: "foundation", stem: "A: Could you turn down the music? B: Sure. What does A want?", options: ["A wants to buy music.", "A wants B to leave.", "A wants the music to be quieter.", "A wants to know what B could do as a child."], answerIndex: 2,
    reasons: ["turn down 在此不是購買音樂。", "A 沒有要求 B 離開。", "turn down the music 表示降低音量，Sure 顯示 B 接受請求。", "沒有過去背景或童年時間。"],
    reviews: ["B 的 Sure 顯示 A 期待一項可立即完成的動作。", "第三項精確限定目前音量；不能由請求推成 A 討厭音樂或否定 B 的能力。"], cognitiveProcess: ["infer-volume-reduction-request", "interpret-turn-down-through-accepted-action"], representationType: "phrasal-request-purpose", misconceptionTargets: ["force-past-ability-reading-on-could-you"] }),
  question({ id: "ENG_R4_Q_098_04", skillId: "ENG_R4_S098", difficulty: "standard", stem: "A: How about taking the early train? B: That may help us arrive on time. What is B doing?", options: ["Asking A to miss the train", "Saying that all trains are full", "Refusing to travel", "Saying the idea may help"], answerIndex: 3,
    reasons: ["B 沒有要 A 錯過火車。", "對話沒有提到車廂容量。", "B 認為方案有助準時，並非拒絕旅行。", "說明好處是在支持搭早班車的建議。"],
    reviews: ["That may help 提供正面因果理由，對應 A 的 How about 建議。", "第四項準確描述 B 的立場，同時保留 may 並非百分之百保證。"], cognitiveProcess: ["classify-on-time-reason-as-suggestion-support", "preserve-may-as-benefit-not-guarantee"], representationType: "suggestion-support-function", misconceptionTargets: ["mistake-cautious-support-for-refusal"] }),
  question({ id: "ENG_R4_Q_098_05", skillId: "ENG_R4_S098", difficulty: "standard", stem: "A: Can you bring the keys? B: No problem. What will B probably do?", options: ["Bring the keys", "Hide the keys", "Ask what a key is", "Leave without the keys"], answerIndex: 0,
    reasons: ["No problem 接受 bring the keys，因此最可能把鑰匙帶來。", "隱藏鑰匙和請求方向相反。", "B 沒有表示不知道 key 的意思。", "空手離開會違反剛接受的任務。"],
    reviews: ["回應不是單看 No，而要把 No problem 視為接受語。", "第一項直接延續 B 的承諾；其餘行動都缺乏文本支持或與請求衝突。"], cognitiveProcess: ["predict-key-delivery-after-no-problem", "map-accepted-bring-request-to-next-action"], representationType: "response-to-action-prediction", misconceptionTargets: ["treat-no-problem-as-negative-answer"] }),
  question({ id: "ENG_R4_Q_098_06", skillId: "ENG_R4_S098", difficulty: "standard", stem: "A: Would you like to go hiking on Saturday? B: That sounds fun, but I have to work. What does B mean in the end?", options: ["B will work on the hiking path.", "B cannot go hiking on Saturday.", "B wants to move work outside.", "B thinks hiking is never fun."], answerIndex: 1,
    reasons: ["B 沒有把工作地點改到步道。", "but 後的工作義務使 B 星期六無法參加。", "第三項不是對話提出的安排。", "sounds fun 顯示 B 並未否定健行本身。"],
    reviews: ["正面開頭表態對活動有興趣，最終可否參加則由工作衝突決定。", "第二項限於指定日期，避免把一次婉拒錯推成永久不喜歡健行。"], cognitiveProcess: ["derive-final-hiking-response-from-but-clause", "separate-positive-attitude-from-schedule-availability"], representationType: "final-stance-inference", misconceptionTargets: ["read-positive-opening-as-acceptance"] }),
  question({ id: "ENG_R4_Q_098_07", skillId: "ENG_R4_S098", difficulty: "standard", stem: "A: Let's use the smaller room. B: It has enough chairs for everyone. What does B mean?", options: ["B wants everyone to stand.", "B is asking for more rooms.", "B gives a reason to accept the idea.", "B says the chairs are too small."], answerIndex: 2,
    reasons: ["enough chairs 表示不必站著。", "B 沒有要求增加房間。", "座位足夠支持使用較小房間的建議。", "smaller 修飾 room，不是 chairs。"],
    reviews: ["B 沒有直接說 yes，但提供了讓方案可行的證據。", "第三項解釋回應的支持功能；第四項錯把形容詞的修飾對象換成椅子。"], cognitiveProcess: ["infer-support-from-enough-chair-evidence", "resolve-smaller-as-room-not-chair-property"], representationType: "implicit-suggestion-support", misconceptionTargets: ["miss-acceptance-without-explicit-yes"] }),
  question({ id: "ENG_R4_Q_098_08", skillId: "ENG_R4_S098", difficulty: "advanced", stem: "A: Could you speak more slowly, please? Which purpose best explains these words?", options: ["A is praising the speaker's speed.", "A is asking about an old speech.", "A is offering to speak first.", "A wants the current speech to be easy to follow."], answerIndex: 3,
    reasons: ["要求 more slowly 並不是稱讚目前速度。", "句中沒有過去時間或舊演講。", "A 沒有提出自己先發言。", "放慢目前說話速度能讓 A 更容易理解內容。"],
    reviews: ["more slowly 是對當下說話方式的調整請求，please 則使語氣較柔和。", "第四項說明合理目的但沒有添加 A 的能力、國籍或其他未提供原因。"], cognitiveProcess: ["infer-comprehension-goal-from-slow-speech-request", "limit-purpose-to-current-followability"], representationType: "request-goal-inference", misconceptionTargets: ["invent-background-reason-for-speech-request"] }),
  question({ id: "ENG_R4_Q_098_09", skillId: "ENG_R4_S098", difficulty: "advanced", stem: "A: Stop! There is a bike behind you. B: I did not see it. What is A doing?", options: ["Telling B about danger", "Inviting B to ride", "Offering B a new bike", "Asking B to repair the bike"], answerIndex: 0,
    reasons: ["Stop 與 behind you 的腳踏車共同形成即時危險警告。", "A 沒有邀請 B 騎乘。", "對話沒有提供新腳踏車。", "B 看不見車不是修理請求。"],
    reviews: ["B 的 I did not see it 證實警告補足了他未察覺的風險。", "第一項能解釋直接語氣與位置資訊；其他功能都和避免碰撞無關。"], cognitiveProcess: ["classify-stop-bike-behind-as-warning", "use-b-response-to-confirm-unseen-danger"], representationType: "warning-dialogue-inference", misconceptionTargets: ["treat-direct-stop-as-rude-request"] }),
  question({ id: "ENG_R4_Q_098_10", skillId: "ENG_R4_S098", difficulty: "advanced", stem: "A: Do you like tea? B: Yes, I drink it every morning. What is A most likely asking about?", options: ["Whether B wants this cup now", "What B usually likes", "Whether B can make tea", "A rule about morning drinks"], answerIndex: 1,
    reasons: ["A 沒有使用 Would you like 或指出眼前一杯茶。", "B 以每天早上的習慣支持一般喜好解讀。", "對話沒有詢問泡茶能力。", "沒有規則或 must 等必要語氣。"],
    reviews: ["every morning 把回答連到 routine，能反向確認 Do you like 的功能。", "第二項依問答共同判斷；第一項則把一般喜好誤當成即時提供。"], cognitiveProcess: ["infer-usual-tea-preference-from-habit-response", "contrast-do-you-like-with-current-cup-offer"], representationType: "response-guided-question-function", misconceptionTargets: ["read-preference-question-as-offer"] }),
  question({ id: "ENG_R4_Q_098_11", skillId: "ENG_R4_S098", difficulty: "transfer", stem: "A: The room is getting dark. Could you turn on the light? B: I will do it now. What is happening in this talk?", options: ["A asks whether B knew about lights as a child.", "B refuses because the room is dark.", "A asks B to do something, and B says yes.", "A offers B a light to take home."], answerIndex: 2,
    reasons: ["getting dark 與 now 都指眼前情境，不是童年能力。", "I will do it now 表示接受，不是拒絕。", "A 請 B 開燈，B 承諾立即完成。", "turn on 是啟動房內燈光，不是把物品送人。"],
    reviews: ["前因是房間變暗，請求動作是 turn on，it 指開燈這件事。", "第三項串起問題、請求與回應；其他選項都無法解釋 B 的即時承諾。"], cognitiveProcess: ["integrate-dark-room-request-and-acceptance", "resolve-do-it-to-turning-on-light"], representationType: "complete-exchange-function-transfer", misconceptionTargets: ["interpret-could-as-past-despite-now-evidence"] }),
  question({ id: "ENG_R4_Q_098_12", skillId: "ENG_R4_S098", difficulty: "transfer", stem: "A: Can you close the gate? B: Sure. Which choice is not supported by the talk?", options: ["A wants the gate closed.", "B agrees to help A.", "B will probably close the gate.", "A does not like any gate."], answerIndex: 3,
    reasons: ["close the gate 直接說明 A 的眼前目標。", "Sure 是對請求的接受。", "接受後最合理的下一步是關上這扇門。", "一次關門請求無法證明 A 對所有大門的長期態度。"],
    reviews: ["前三項都能由明說動作或接受回應支持，第四項則擴大到永久喜好。", "答案要求辨認 over-inference，不是找任何可能為真的句子；沒有證據就不能加入個性判斷。"], cognitiveProcess: ["identify-overreach-in-gate-request-inferences", "separate-supported-next-action-from-global-dislike"], representationType: "evidence-boundary-transfer", misconceptionTargets: ["generalize-single-request-to-permanent-preference"] }),
];

export const ENGLISH_U14_VOCABULARY_POLICY = Object.freeze({
  capQuestionBasis: "appendix-5-table-1",
  additionalLearningTerms: ["accept", "activity", "add", "address", "alone", "ball", "board", "current", "customer", "danger", "depend", "describe", "direct", "direction", "discuss", "express", "fit", "formal", "gentle", "guest", "guide", "include", "information", "invitation", "message", "natural", "pan", "passenger", "path", "patient", "praise", "purpose", "rather", "refuse", "repair", "respect", "rude", "serve", "shelf", "skill", "solve", "speech", "speed", "step", "suggest", "support", "toward", "travel", "usual"],
  properNames: ["Amy", "Ben", "Grace", "Jack", "Leo", "Lily", "Mia", "Nora", "Sam", "Tina", "Victor", "Wendy"],
  grammarNotation: ["A", "B", "base form", "imperative", "modal", "V-ing"],
  malformedDistractors: [],
});

export const ENGLISH_U14_SOURCE = Object.freeze({ unitId: UNIT_ID, lectures: ENGLISH_U14_LECTURES, questions: ENGLISH_U14_QUESTIONS, vocabularyPolicy: ENGLISH_U14_VOCABULARY_POLICY });
export const ENGLISH_UNIT_SOURCE = ENGLISH_U14_SOURCE;
