const UNIT_ID = "ENG_R4_U20";

function lecture(id, skillId, content) {
  return { id, skillId, ...content, sections: content.sections.map((section, index) => ({ id: `${id}_SEC_${String(index + 1).padStart(2, "0")}`, ...section })) };
}

const DIFFICULTIES = ["foundation", "foundation", "foundation", "standard", "standard", "standard", "standard", "advanced", "advanced", "advanced", "transfer", "transfer"];

function skillQuestions(skillNumber, values) {
  if (values.length !== 12) throw new Error(`ENG_R4_S${skillNumber}: expected 12 authored questions`);
  return values.map((value, index) => ({ id: `ENG_R4_Q_${skillNumber}_${String(index + 1).padStart(2, "0")}`, skillId: `ENG_R4_S${skillNumber}`, difficulty: DIFFICULTIES[index], ...value }));
}

export const ENGLISH_U20_LECTURES = [
  lecture("ENG_R4_L_S134", "ENG_R4_S134", {
    objectives: ["依時間單位與固定用法選擇 at、on 或 in。", "辨識星期加早晚、at night 與不加介系詞的時間片語。"],
    sections: [
      { title: "at 指向明確時間點", content: "at 7:20、at noon、at midnight 都把事件放在一個時間點。at night 是常見固定用法；雖然 night 看似一段時間，不能因此改寫成 in night。" },
      { title: "on 配合日期與星期", content: "on Tuesday、on May 4、on my birthday 都指特定一天。若早晚前已有星期或日期，也用 on，例如 on Tuesday morning，而不是 in Tuesday morning。" },
      { title: "in 配合較長時段", content: "in June、in 2026、in summer 用於月份、年份與季節；in the morning、in the afternoon、in the evening 則是一天中的較長部分。判斷時要讀完整時間片語。" },
      { title: "部分時間片語前不加介系詞", content: "this morning、last night、next Friday、every Sunday 前通常不再加 at、on 或 in。這些限定詞本身已把時間說清楚，多加介系詞反而形成錯誤結構。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S134_EX_01", prompt: "The meeting begins ___ 6:45.", steps: ["找時間 6:45。", "判斷它是明確鐘點。", "使用 at。"], answer: "at", why: "6:45 是鐘面上的明確時間點，因此寫 at 6:45。on 用於某一天，in 用於月份、年份或較長時段，都不符合這個尺度。" },
      { id: "ENG_R4_L_S134_EX_02", prompt: "The library is closed ___ August 12.", steps: ["辨認 August 12 是日期。", "日期視為特定一天。", "使用 on。"], answer: "on", why: "August 12 包含月份與日數，整體是一個明確日期，所以用 on。不能只看到 August 就選 in，必須讀完完整片語。" },
      { id: "ENG_R4_L_S134_EX_03", prompt: "My family moved here ___ 2021.", steps: ["找年份 2021。", "年份是較長時間範圍。", "使用 in。"], answer: "in", why: "2021 指一整年的範圍，沒有指定某一天或鐘點，因此用 in。若題目改成 March 3, 2021，才會依完整日期改用 on。" },
    ],
    misconceptions: [
      { belief: "看到月份就一定選 in。", whyWrong: "月份後若帶日期，如 May 4，整體是特定一天。", correction: "先讀完整時間片語，再判斷是月份或日期。" },
      { belief: "morning 前永遠使用 in。", whyWrong: "Tuesday morning 已由星期限定，應使用 on。", correction: "區分 in the morning 與 on Tuesday morning。" },
      { belief: "night 是一段時間，所以要寫 in night。", whyWrong: "一般夜間用法是固定片語 at night。", correction: "將 at night 與 in the evening 分開記。" },
      { belief: "next Monday 前仍需加 on。", whyWrong: "next 已經直接限定時間，不再需要介系詞。", correction: "直接寫 next Monday，不寫 on next Monday。" },
    ],
    checks: [
      { prompt: "9:10 前用哪個介系詞？", answer: "at", reason: "鐘點視為明確時間點。" },
      { prompt: "Friday evening 前用哪個介系詞？", answer: "on", reason: "星期限定了 evening。" },
      { prompt: "last summer 前是否要加 in？", answer: "不用", reason: "last 已直接限定時間。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S135", "ENG_R4_S135", {
    objectives: ["使用 before、after 表示事件先後，並用 until 表示持續終點。", "區分 during 後接名詞與完整子句的結構。"],
    sections: [
      { title: "before 與 after 建立先後順序", content: "Wash your hands before dinner 表示先洗手再吃晚餐；We talked after class 表示下課之後才交談。兩字的判斷要依事件順序，不只看它們在句中的位置。" },
      { title: "during 接一段活動或時期的名詞", content: "during the movie、during lunch、during the trip 都把事件放在某段期間內。during 後通常接名詞片語；若後面是主詞加動詞，常要改用 while 等連接方式。" },
      { title: "until 指向持續動作的終點", content: "The shop stays open until nine 表示營業狀態一直維持到九點。until 不是只說事情發生在九點，而是連接前面的持續過程與結束界線。" },
      { title: "同一時間資料可能問不同關係", content: "A class runs from one until three 著重結束點；Students talk after the class 著重前後；No one talks during the class 著重期間內。先找題目要表達的是順序、期間還是終點。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S135_EX_01", prompt: "Turn off the light ___ you leave.", steps: ["辨認兩個動作。", "關燈應先於離開。", "選 before。"], answer: "before", why: "安全指示要求先關燈，之後才離開，因此用 before 連接正確順序。after 會變成離開後才關燈，與情境不合。" },
      { id: "ENG_R4_L_S135_EX_02", prompt: "No one spoke ___ the short film.", steps: ["short film 是名詞片語。", "沉默發生在影片播放期間。", "使用 during。"], answer: "during", why: "題意是整段短片播放時沒有人說話，during 可直接接 the short film。before 或 after 都會把沉默移到影片之外。" },
      { id: "ENG_R4_L_S135_EX_03", prompt: "The rain continued ___ midnight.", steps: ["continued 表示持續。", "midnight 是結束界線。", "使用 until。"], answer: "until", why: "continued 說明下雨狀態延續，midnight 則給出終點，所以用 until。這不表示雨只在午夜那一刻發生。" },
    ],
    misconceptions: [
      { belief: "before 一定代表題幹第一個寫出的事件先發生。", whyWrong: "英文詞序與實際事件順序需要一起解讀。", correction: "把兩個事件畫成先後，再選 before 或 after。" },
      { belief: "during 後可以直接接任何完整句子。", whyWrong: "during 通常是介系詞，後面接名詞片語。", correction: "比較 during the game 與 while we played。" },
      { belief: "until nine 只表示事情在九點發生。", whyWrong: "until 把前面的狀態或動作延續到九點。", correction: "先找能持續的動作，再找其終點。" },
      { belief: "after 與 later 可以放在完全相同的位置。", whyWrong: "after 在本單元後接事件或名詞，later 常單獨表示之後。", correction: "使用 after school，而不是 later school。" },
    ],
    checks: [
      { prompt: "先吃早餐再出門，兩事件間可用哪個字？", answer: "after", reason: "出門發生在早餐之後。" },
      { prompt: "during the meeting 中 during 後接什麼？", answer: "名詞片語", reason: "the meeting 是一段活動。" },
      { prompt: "wait until six 表示等待到何時？", answer: "六點", reason: "six 是等待的終點。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S136", "ENG_R4_S136", {
    objectives: ["依封閉範圍、表面與特定地點選擇 in、on 或 at。", "辨識同一地名在活動地點與建築內部兩種視角的差異。"],
    sections: [
      { title: "in 表示在範圍或空間之內", content: "in the room、in the box、in Taiwan 都把人或物放在一個有邊界的空間或地區內。重點是位於範圍之中，不一定真的碰到四面牆。" },
      { title: "on 表示接觸表面或位在線上", content: "on the desk、on the wall、on page ten 都把位置連到表面、平面或一條資訊線。物品通常接觸該表面；頁碼也使用 on，而不是 in page ten。" },
      { title: "at 把地點視為一個位置點", content: "at the door、at the bus stop、at school 著重人所在的地點或活動點，不特別描寫內部空間。若要強調人在教室內，才會用 in the classroom。" },
      { title: "介系詞反映說話者的視角", content: "Mia is at the station 表示她到了車站這個地點；Mia is in the station 強調她在建築內。兩句都可能正確，但回答的空間問題不同，不能脫離情境只背地名。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S136_EX_01", prompt: "The keys are ___ the bag.", steps: ["bag 提供可容納物品的空間。", "鑰匙位於袋子內。", "選 in。"], answer: "in", why: "bag 在此被視為有內部空間的容器，鑰匙位於其中，所以用 in。on the bag 會表示鑰匙在袋子表面。" },
      { id: "ENG_R4_L_S136_EX_02", prompt: "A map hangs ___ the wall.", steps: ["wall 是表面。", "地圖接觸並固定在牆面。", "選 on。"], answer: "on", why: "地圖與牆面接觸，因此使用 on the wall。in the wall 會把地圖理解成位於牆體內，並非一般懸掛情況。" },
      { id: "ENG_R4_L_S136_EX_03", prompt: "Meet me ___ the front door.", steps: ["front door 是會合位置。", "不需描述門的內部。", "選 at。"], answer: "at", why: "題目把 front door 當成雙方會合的明確地點，所以用 at。in the door 與 on the door 都會改變空間關係。" },
    ],
    misconceptions: [
      { belief: "大地方一律用 in，小地方一律用 at。", whyWrong: "實際選擇也取決於範圍、表面與位置點的視角。", correction: "先問是位於內部、接觸表面，還是只指出地點。" },
      { belief: "牆上的照片應寫 in the wall。", whyWrong: "一般照片接觸牆面，並不在牆體內。", correction: "使用 on the wall 表示表面位置。" },
      { belief: "at school 表示站在校門外。", whyWrong: "at school 通常表示人在學校這個活動地點。", correction: "若需強調建築內部，再用 in 加具體空間。" },
      { belief: "頁面上的資訊要用 in page。", whyWrong: "英文以 on page ten 表示頁面位置。", correction: "把頁面視為資訊承載的表面。" },
    ],
    checks: [
      { prompt: "杯子裡的水用哪個介系詞？", answer: "in", reason: "水位於容器內。" },
      { prompt: "桌面上的書用哪個介系詞？", answer: "on", reason: "書接觸桌面。" },
      { prompt: "在公車站等人用哪個介系詞？", answer: "at", reason: "bus stop 是會合位置點。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S137", "ENG_R4_S137", {
    objectives: ["區分 above、below 的一般高低關係與 over、under 的直接上下關係。", "依遮蓋、跨越或垂直對應等線索判斷位置。"],
    sections: [
      { title: "above 與 below 表示一般高低", content: "The clock is above the shelf 只要求時鐘位置較高；The shoes are below the window 表示鞋子位置較低。兩者不必正好垂直對齊，也不表示接觸。" },
      { title: "over 常帶有正上方或覆蓋關係", content: "A lamp hangs over the table 時，燈位於桌子上方；A blanket is over the child 時，也帶有覆蓋意思。over 的語意比單純較高更具體。" },
      { title: "under 常表示正下方或被遮住", content: "The cat is under the chair 表示貓在椅子下方的空間；The road goes under the bridge 則表示道路從橋下通過。只說海拔較低時，below 可能更合適。" },
      { title: "數值與位置都要看比較基準", content: "The temperature is below zero 比較數值；The sign is below the clock 比較位置。不能看到 lower 就固定選同一字，還要判斷是否有正上方、覆蓋或穿越等關係。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S137_EX_01", prompt: "The picture is ___ the sofa, but not directly over it. (above / over)", steps: ["找較高的位置關係。", "讀 not directly over it。", "選 above。"], answer: "above", why: "圖片比沙發高，但題目特別排除正上方，因此用較一般的 above。over 會和直接上下的線索衝突。" },
      { id: "ENG_R4_L_S137_EX_02", prompt: "The child held an umbrella ___ her head.", steps: ["雨傘位於頭部上方。", "它同時提供遮蓋。", "使用 over。"], answer: "over", why: "雨傘不只比頭高，還在頭頂形成遮蓋，因此 over 最符合情境。above 雖能表示較高，卻沒有呈現保護關係。" },
      { id: "ENG_R4_L_S137_EX_03", prompt: "The ball rolled ___ the bed and stopped there.", steps: ["球進入床下空間。", "床位於球的正上方。", "選 under。"], answer: "under", why: "球滾進床下並停住，under 清楚表示它被床的範圍遮在下方。below 只說位置較低，沒有呈現床下空間。" },
    ],
    misconceptions: [
      { belief: "above 與 over 在任何句子都能互換。", whyWrong: "over 可能含正上方、覆蓋或跨越，above 只需一般較高。", correction: "檢查是否有直接對齊或遮蓋線索。" },
      { belief: "under 只表示數值小於。", whyWrong: "under 常用於物體正下方或被遮住的位置。", correction: "數值可用 below，空間則依具體關係判斷。" },
      { belief: "below 一定表示兩物垂直對齊。", whyWrong: "below 只要求位置較低，不必正好在另一物底下。", correction: "需要直接下方時再考慮 under。" },
      { belief: "物體在上方就表示碰到另一物。", whyWrong: "above、over 都不必表示接觸。", correction: "接觸關係需由 on 或其他情境另外說明。" },
    ],
    checks: [
      { prompt: "below zero 比較的是什麼？", answer: "數值高低", reason: "zero 是溫度或數字基準。" },
      { prompt: "雨傘遮在頭上常用哪個字？", answer: "over", reason: "它帶有正上方與遮蓋關係。" },
      { prompt: "貓躲在桌子下常用哪個字？", answer: "under", reason: "貓位於桌面遮蔽的下方空間。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S138", "ENG_R4_S138", {
    objectives: ["使用 between、among 表達個別對象之間或群體中的位置。", "區分 beside 的緊鄰與 near 的一般接近。"],
    sections: [
      { title: "between 連接可分辨的對象", content: "The bank is between the school and the park 中，兩個邊界都被明確指出。between 常見於兩者，但若多個對象各自清楚可分，也不必只靠數量判斷。" },
      { title: "among 表示位於群體之中", content: "Mia stood among the students 強調她在一群學生裡，不逐一說出左右邊界。among 適合把周圍對象視為整體群體。" },
      { title: "beside 表示就在旁邊", content: "The chair is beside the desk 表示兩者緊鄰。beside 不等於 besides；本單元談位置，只使用沒有 s 的 beside。" },
      { title: "near 只保證距離接近", content: "The shop is near the station 表示距離不遠，但中間仍可能隔著其他建築。near 的範圍比 beside 寬，不能由 near 推出兩地一定相鄰。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S138_EX_01", prompt: "The shop is ___ the bank and the hotel.", steps: ["找兩個明確邊界。", "shop 位於兩者之間。", "選 between。"], answer: "between", why: "bank 和 hotel 是兩個清楚標出的參照點，shop 位在它們之間，因此用 between。among 會把周圍對象當成一個群體。" },
      { id: "ENG_R4_L_S138_EX_02", prompt: "A small bird was hiding ___ the leaves.", steps: ["leaves 構成群體。", "鳥藏在許多葉子之中。", "選 among。"], answer: "among", why: "題目把許多 leaves 視為包圍小鳥的群體，沒有指定兩片葉子作邊界，所以 among 比 between 合適。" },
      { id: "ENG_R4_L_S138_EX_03", prompt: "Nora sat ___ Mia, so their chairs touched.", steps: ["兩人距離非常近。", "椅子相接表示緊鄰。", "選 beside。"], answer: "beside", why: "chairs touched 提供相鄰證據，因此 beside 最精確。near 只能保證距離接近，不能自行推出兩張椅子碰在一起。" },
    ],
    misconceptions: [
      { belief: "between 只能在句中出現兩個人時使用。", whyWrong: "重點是對象是否個別清楚，不只是總數。", correction: "先判斷邊界是明確個體還是整體群體。" },
      { belief: "among 可以表示兩棟建築的中間點。", whyWrong: "兩個明確邊界通常用 between。", correction: "寫 between the school and the library。" },
      { belief: "near 就等於緊貼在旁邊。", whyWrong: "near 只表示距離近，中間仍可能有其他物體。", correction: "有緊鄰證據時使用 beside。" },
      { belief: "besides 是 beside 的另一種拼法。", whyWrong: "besides 常表示此外，不是本單元的位置介系詞。", correction: "描述緊鄰位置時使用 beside。" },
    ],
    checks: [
      { prompt: "兩個明確地點之間常用哪個字？", answer: "between", reason: "兩個邊界可分辨。" },
      { prompt: "在人群之中常用哪個字？", answer: "among", reason: "周圍對象形成群體。" },
      { prompt: "near 是否保證兩物相鄰？", answer: "不保證", reason: "near 只表示距離接近。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S139", "ENG_R4_S139", {
    objectives: ["依移動終點選擇 to、into 或 onto。", "使用 through 表示從空間或通道的一端進入並向另一端移動。"],
    sections: [
      { title: "to 指向目的地", content: "walk to school、send the letter to Mia 都指出移動或傳遞的終點，但不特別說明進入內部或登上表面。to 的重點是方向與目的地。" },
      { title: "into 表示移動到內部", content: "The cat jumped into the box 表示牠從外面移到箱子裡。in 描述已在內部的靜態位置，into 則保留跨過邊界的移動。" },
      { title: "onto 表示移動到表面", content: "The book fell onto the floor 說明書本移動後到達地面表面。on the floor 可描述最後位置，onto 則把到達表面的過程也寫出來。" },
      { title: "through 表示穿過內部路徑", content: "The train went through the tunnel 表示列車進入隧道並沿其中通過。若只到隧道入口，應用 to；若只進入而未說穿過，則可能用 into。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S139_EX_01", prompt: "We walked ___ the museum but did not enter.", steps: ["museum 是目的地。", "題目排除進入內部。", "選 to。"], answer: "to", why: "大家走到 museum，卻明確沒有進入，因此只需用 to 表示目的地。into 會和 did not enter 直接衝突。" },
      { id: "ENG_R4_L_S139_EX_02", prompt: "The toy moved ___ the box from the floor.", steps: ["from the floor 給出原來位置。", "終點在 box 內。", "選 into。"], answer: "into", why: "玩具原本在地上，之後跨過箱口到箱內，into 能表達這段方向改變。in the box 只描述箱內位置，不能完整保留從地面移入的關係。" },
      { id: "ENG_R4_L_S139_EX_03", prompt: "The bus drove ___ the long tunnel.", steps: ["公車進入隧道。", "路徑延伸到另一端。", "使用 through。"], answer: "through", why: "公車沿隧道內部前進並穿過通道，through 能表達完整路徑。to 只到入口，into 只強調進入，都少了穿越意思。" },
    ],
    misconceptions: [
      { belief: "to 與 into 都只表示到某地，所以能互換。", whyWrong: "into 明確包含進入內部，to 只指出目的地。", correction: "檢查是否跨過容器或空間邊界。" },
      { belief: "on 和 onto 完全相同。", whyWrong: "on 常描述位置，onto 強調移動到表面。", correction: "有移動過程時依終點表面考慮 onto。" },
      { belief: "through 只要看到隧道就一定使用。", whyWrong: "若只到入口或進入後停下，移動關係不同。", correction: "確認路徑是否穿過內部並向另一端延伸。" },
      { belief: "into 可以用來表示人在房間裡的靜態位置。", whyWrong: "靜態位置通常用 in，into 需要方向或移動。", correction: "比較 is in the room 與 walked into the room。" },
    ],
    checks: [
      { prompt: "只走到公園入口可用哪個字？", answer: "to", reason: "它只指出目的地。" },
      { prompt: "跳進水裡可用哪個字？", answer: "into", reason: "移動終點在水的內部範圍。" },
      { prompt: "穿過森林可用哪個字？", answer: "through", reason: "路徑在森林內延伸並通過。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S140", "ENG_R4_S140", {
    objectives: ["依目的地尺度選擇 arrive in 或 arrive at。", "使用 reach 直接接受詞，並辨識 arrive home 的特殊結構。"],
    sections: [
      { title: "arrive in 常接城市國家或較大地區", content: "arrive in Taipei、arrive in Japan 把目的地視為較大的地理範圍。in 不是單純依字數決定，而是配合人進入某個城市、國家或區域的視角。" },
      { title: "arrive at 常接明確地點", content: "arrive at the station、arrive at school、arrive at the hotel 把終點視為一個具體位置。即使建築物有內部空間，arrive 的搭配仍常用 at。" },
      { title: "reach 後直接接目的地", content: "reach the station、reach Taipei 都不在 reach 與地點間加 to、at 或 in。reach 本身已含到達意思，多加介系詞會破壞動詞受詞結構。" },
      { title: "home 是常見特殊情況", content: "arrive home、reach home 都不加 at 或 to；但 arrive at my house 需要 at，因為 my house 是一般名詞片語。不能把 home 的形式套用到所有住處名稱。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S140_EX_01", prompt: "The train arrived ___ Kaohsiung at noon.", steps: ["Kaohsiung 是城市。", "arrive 接較大地區。", "選 in。"], answer: "in", why: "Kaohsiung 是城市名稱，句子把列車看成進入這個地理範圍，因此使用 arrive in。若目的地是 the station，搭配會改成 arrive at。" },
      { id: "ENG_R4_L_S140_EX_02", prompt: "We arrived ___ the bus stop early.", steps: ["bus stop 是明確位置點。", "動詞是 arrived。", "選 at。"], answer: "at", why: "bus stop 是具體的停靠位置，arrive at 能指出抵達該點。arrive in 會把它當成城市或較大區域，尺度不合。" },
      { id: "ENG_R4_L_S140_EX_03", prompt: "Mia reached ___ the airport before six.", steps: ["reached 已表示到達。", "airport 是直接受詞。", "空格不填介系詞。"], answer: "不填介系詞", why: "reach 可直接接受詞 the airport，因此寫 reached the airport。加入 at 或 to 都會在動詞與受詞間多放不需要的介系詞。" },
    ],
    misconceptions: [
      { belief: "arrive 後一律接 at。", whyWrong: "城市、國家與較大地區通常搭配 arrive in。", correction: "依目的地尺度區分 arrive in 與 arrive at。" },
      { belief: "reach 後應寫 to 才有方向。", whyWrong: "reach 本身已包含到達意思，後面直接接受詞。", correction: "使用 reach the station，不寫 reach to the station。" },
      { belief: "arrive in the station 表示進入車站，所以一定正確。", whyWrong: "一般到達車站的搭配是 arrive at the station。", correction: "將 station 視為行程終點，而非用 in 強調建築內部。" },
      { belief: "arrive home 與 arrive at my house 使用相同形式。", whyWrong: "home 可直接接在 arrive 後，my house 則需要 at。", correction: "分開記 arrive home 與 arrive at my house。" },
    ],
    checks: [
      { prompt: "抵達某個國家常用 arrive 加哪個字？", answer: "in", reason: "國家是較大地理範圍。" },
      { prompt: "抵達車站常用哪個片語？", answer: "arrive at the station", reason: "車站是具體行程終點。" },
      { prompt: "reach the park 中要加 to 嗎？", answer: "不用", reason: "reach 直接接受詞。" },
    ], assets: [],
  }),
];

export const ENGLISH_U20_QUESTIONS = [
  ...skillQuestions("134", [
    { stem: "The train leaves ___ 7:15.", options: ["at", "on", "in", "from"], answerIndex: 0, reasons: ["at 接明確鐘點 7:15。", "on 用於星期或日期，不接單一鐘點。", "in 通常接月份、年份或較長時段。", "from 會表示起點，卻沒有後續時間範圍。"], reviews: ["7:15 是時刻，不是日期或月份。", "第一項建立 at + clock time 的完整片語。"], cognitiveProcess: ["classify-715-as-clock-time", "apply-at-to-departure-time"], representationType: "clock-time-preposition-cloze", misconceptionTargets: ["use-in-before-clock-time"] },
    { stem: "Our art class is ___ Wednesday.", options: ["at", "on", "in", "by"], answerIndex: 1, reasons: ["at 不用來直接接星期名稱。", "on Wednesday 表示課程在星期三。", "in Wednesday 不是標準星期搭配。", "by Wednesday 表示不晚於星期三，和上課日期不同。"], reviews: ["Wednesday 是一週中的特定一天。", "第二項用 on 指出課程日期，不加入截止意思。"], cognitiveProcess: ["identify-wednesday-as-day", "choose-on-for-class-day"], representationType: "weekday-preposition-cloze", misconceptionTargets: ["treat-weekday-as-long-period"] },
    { stem: "This town is warm ___ July.", options: ["at", "on", "in", "for"], answerIndex: 2, reasons: ["at 不接月份表示一般時間範圍。", "on 需要日期或特定一天。", "in July 表示在七月這個月份。", "for July 會偏向持續整月或用途，並非本句的一般時間定位。"], reviews: ["July 單獨出現，沒有日數。", "第三項把天氣放在月份範圍內。"], cognitiveProcess: ["read-july-without-date", "select-in-for-month"], representationType: "month-preposition-cloze", misconceptionTargets: ["use-on-for-month-alone"] },
    { stem: "Stars are easy to see ___ night.", options: ["on", "in", "during", "at"], answerIndex: 3, reasons: ["on night 不是一般固定搭配。", "in night 缺少 the，且本句採常見固定片語。", "during night 通常需更完整的名詞片語。", "at night 是表示一般夜間的固定用法。"], reviews: ["本句談一般夜間，不是某一個日期的夜晚。", "第四項不能只靠時段長短判斷，而要辨認固定搭配。"], cognitiveProcess: ["recognize-general-night-expression", "retrieve-at-night-collocation"], representationType: "fixed-night-time-phrase", misconceptionTargets: ["generalize-in-the-morning-to-night"] },
    { stem: "The game is ___ Saturday afternoon.", options: ["on", "at", "in", "every"], answerIndex: 0, reasons: ["on 接完整的 Saturday afternoon。", "at 不直接接星期加 afternoon。", "in the afternoon 可成立，但有 Saturday 時改用 on。", "every Saturday afternoon 不需要 is 後再填成此結構。"], reviews: ["afternoon 前已有 Saturday 限定特定一天。", "第一項以 on 保留星期與時段的整體。"], cognitiveProcess: ["combine-saturday-with-afternoon", "use-on-for-day-part"], representationType: "weekday-part-time-cloze", misconceptionTargets: ["select-in-from-afternoon-only"] },
    { stem: "This school opened ___ 2012.", options: ["on", "in", "at", "since"], answerIndex: 1, reasons: ["on 需要更完整的日期。", "in 2012 把開校時間放在該年份。", "at 不接年份表示一般時間。", "since 2012 需搭配延續到現在的結構，opened 是單次過去事件。"], reviews: ["2012 是年份，題目沒有月份或日期。", "第二項也符合 opened 所指的單次歷史時間。"], cognitiveProcess: ["classify-2012-as-year", "pair-opened-event-with-in-year"], representationType: "year-preposition-cloze", misconceptionTargets: ["use-since-with-simple-past-event"] },
    { stem: "A sign says, 'The shop opens in 8:30.' Which change fixes the time words?", options: ["opens → open", "shop → shops", "in → at", "8:30 → Wednesday"], answerIndex: 2, reasons: ["The shop 是單數，opens 正確。", "改成複數會造成 shops 與 opens 不一致。", "8:30 是鐘點，應寫 at 8:30。", "換成 Wednesday 會改掉原本營業時間資料。"], reviews: ["錯誤集中在鐘點前的介系詞。", "第三項只修正時間尺度，不改主詞、動詞或資料。"], cognitiveProcess: ["diagnose-in-before-830", "edit-to-at-clock-time"], representationType: "time-preposition-proofreading", misconceptionTargets: ["repair-unrelated-subject-agreement"] },
    { stem: "We will visit the farm ___ next Sunday.", options: ["in", "at", "on", "no word"], answerIndex: 3, reasons: ["in 不放在 next Sunday 前。", "at 不能接 next Sunday。", "on Sunday 可成立，但 next 已直接限定星期。", "next Sunday 前不需要介系詞。"], reviews: ["next 是判斷關鍵，不可只看到 Sunday 就選 on。", "第四項保留自然片語 visit the farm next Sunday。"], cognitiveProcess: ["detect-next-as-time-determiner", "omit-preposition-before-next-sunday"], representationType: "zero-time-preposition-cloze", misconceptionTargets: ["add-on-before-next-weekday"] },
    { stem: "Music show: June 6, 4:00 p.m. Which line gives the time correctly?", options: ["The show is on June 6 at 4:00 p.m.", "The show is in June 6 on 4:00 p.m.", "The show is at June 6 in 4:00 p.m.", "The show is on June at 6:00 p.m."], answerIndex: 0, reasons: ["on 接日期 June 6，at 接鐘點 4:00 p.m.。", "月份加日數不能用 in，鐘點也不能用 on。", "at 與 in 都放錯時間尺度。", "此項把日期 6 誤改成時間 6:00。"], reviews: ["卡片同時提供日期與鐘點，兩者要分開判斷。", "第一項完整保留 June 6 和 4:00 p.m.。"], cognitiveProcess: ["parse-date-and-time-from-show-card", "assign-on-date-and-at-clock"], representationType: "schedule-card-time-transfer", misconceptionTargets: ["swap-date-and-clock-prepositions"] },
    { stem: "Nora studies ___ the evening.", options: ["on", "in", "at", "from"], answerIndex: 1, reasons: ["沒有星期或日期時，不用 on the evening。", "in the evening 是一般晚間時段用法。", "at evening 不是本句採用的標準片語。", "from 需要另一個時間點完成範圍。"], reviews: ["the evening 是一天中的較長部分。", "第二項和固定用法 at night 不同。"], cognitiveProcess: ["classify-the-evening-as-day-period", "choose-in-the-evening"], representationType: "day-period-preposition-cloze", misconceptionTargets: ["copy-at-night-to-evening"] },
    { stem: "The trip begins ___.", options: ["at Monday", "on June", "on May 3", "in Friday evening"], answerIndex: 2, reasons: ["Monday 前應使用 on。", "June 單獨作月份時應使用 in。", "on May 3 正確表示特定日期。", "Friday evening 應整體搭配 on。"], reviews: ["四個選項都必須同時檢查介系詞與時間片語。", "第三項是唯一尺度與搭配都正確的日期。"], cognitiveProcess: ["evaluate-four-complete-time-phrases", "select-on-may-third"], representationType: "time-phrase-contrast-selection", misconceptionTargets: ["judge-preposition-without-full-phrase"] },
    { stem: "A camp card says, 'Meet at noon on July 2.' What can we know?", options: ["The camp lasts all July.", "The meeting is at night.", "July 2 is the meeting time.", "The meeting time is noon, and the date is July 2."], answerIndex: 3, reasons: ["卡片只提供一個日期，沒有說持續整月。", "noon 是中午，不是夜間。", "July 2 是日期，不是鐘點。", "at noon 指時間，on July 2 指日期。"], reviews: ["介系詞也在標示兩段資訊各自的角色。", "第四項沒有把日期與時間互換。"], cognitiveProcess: ["separate-noon-time-from-july2-date", "state-complete-camp-meeting-schedule"], representationType: "time-date-role-inference", misconceptionTargets: ["confuse-calendar-date-with-clock-time"] },
  ]),
  ...skillQuestions("135", [
    { stem: "Please call me before dinner. Which happens first?", options: ["The call", "Dinner", "Both at the same time", "The sentence does not say"], answerIndex: 0, reasons: ["before dinner 表示電話在晚餐前。", "dinner 是較後發生的事件。", "before 不表示同時。", "句子已明確提供先後。"], reviews: ["先找 before 兩側的事件：call 與 dinner。", "第一項把語序轉成實際時間順序。"], cognitiveProcess: ["order-call-and-dinner-events", "identify-call-before-dinner"], representationType: "before-event-order-inference", misconceptionTargets: ["treat-written-order-as-uncertain"] },
    { stem: "We played basketball ___ class ended.", options: ["during", "after", "until", "before of"], answerIndex: 1, reasons: ["during 後不能直接接 class ended 這個完整子句。", "after class ended 表示下課後才打球。", "until 會要求前面動作持續到下課，不合句意。", "before of 不是標準結構。"], reviews: ["class ended 是完整事件，可由 after 連接。", "第二項建立下課先、打球後的順序。"], cognitiveProcess: ["recognize-class-ended-clause", "link-later-basketball-with-after"], representationType: "after-clause-time-link", misconceptionTargets: ["place-during-before-clause"] },
    { stem: "No photos were taken while the show was running = No photos were taken ___ the show.", options: ["until", "after of", "during", "before to"], answerIndex: 2, reasons: ["until the show 會把表演當成終點，不能保留 while 的期間關係。", "after of 不是標準介系詞組合。", "during the show 與 while the show was running 都表示表演進行期間。", "before to 不能直接接 the show。"], reviews: ["等號兩邊必須保留同一段禁止拍照的時間。", "第三項以介系詞加名詞片語改寫 while 子句。"], cognitiveProcess: ["convert-while-clause-to-during-phrase", "preserve-no-photo-period"], representationType: "while-to-during-meaning-equivalence", misconceptionTargets: ["replace-period-with-until-endpoint"] },
    { stem: "The museum stays open ___ 5:30.", options: ["during", "after", "before", "until"], answerIndex: 3, reasons: ["during 不能直接接單一鐘點表示終點。", "after 5:30 會表示五點半之後才營業。", "before 5:30 只說較早，沒有表達持續到終點。", "until 5:30 表示營業狀態維持到五點半。"], reviews: ["stays open 是能延續的狀態。", "第四項把 5:30 指定為營業終點。"], cognitiveProcess: ["detect-continuing-open-state", "set-530-endpoint-with-until"], representationType: "until-closing-time-cloze", misconceptionTargets: ["read-until-as-single-event-time"] },
    { stem: "Nora left home at 7:40. Her bus arrived at 8:00. Nora left home ___ the bus arrived.", options: ["before", "during", "until", "after"], answerIndex: 0, reasons: ["7:40 早於 8:00，所以她在公車抵達前離家。", "during 不用來比較兩個時間點的先後。", "left 是單次動作，不能持續到 8:00。", "after 會和時間資料相反。"], reviews: ["先比較 7:40 與 8:00，再選關係字。", "第一項由數值證據得出，不靠句子排列猜測。"], cognitiveProcess: ["compare-740-and-800", "map-earlier-departure-to-before"], representationType: "timeline-before-transfer", misconceptionTargets: ["reverse-earlier-and-later-times"] },
    { stem: "Which sentence means that rain continued and stopped at ten?", options: ["It rained after ten.", "It rained until ten.", "It rained during ten.", "It rained before of ten."], answerIndex: 1, reasons: ["after ten 把下雨放到十點之後。", "until ten 表示下雨延續到十點為止。", "during 不能直接接鐘點 ten 表示持續終點。", "before of ten 不是標準時間片語。"], reviews: ["題幹同時給 continued 與 stopped 的概念。", "第二項用 until 把整段持續和結束點連起來。"], cognitiveProcess: ["translate-rain-duration-and-stop", "select-until-ten-sentence"], representationType: "until-meaning-selection", misconceptionTargets: ["replace-until-with-after"] },
    { stem: "A student writes, 'I slept during the movie played.' Which change makes the time part clear?", options: ["slept → sleep", "movie → movies", "during the movie played → during the movie", "I → Me"], answerIndex: 2, reasons: ["若事件在過去，slept 可保留。", "改複數不能修正 during 後的結構。", "during the movie 以名詞片語表達電影播放期間。", "主詞位置應保留 I。"], reviews: ["during 後已有 the movie，不必再硬接 played。", "第三項刪除多餘動詞，事件時間仍完整。"], cognitiveProcess: ["diagnose-during-noun-plus-stray-verb", "reduce-to-during-the-movie"], representationType: "during-phrase-proofreading", misconceptionTargets: ["attach-finite-verb-after-during-noun"] },
    { stem: "A screen says, 'Please wait here until your number appears.' When may you stop waiting?", options: ["Before getting a number", "During another visit", "After leaving the building", "When the number appears"], answerIndex: 3, reasons: ["沒有號碼前仍要等待。", "另一趟拜訪不是本次等待終點。", "離開建築是在等待結束後的其他行動。", "until 指定號碼出現為等待終點。"], reviews: ["wait 是持續動作，appears 是結束條件。", "第四項把文字指示轉成可執行的停止時機。"], cognitiveProcess: ["identify-until-condition-on-screen", "infer-waiting-stop-point"], representationType: "service-screen-until-inference", misconceptionTargets: ["stop-before-until-condition"] },
    { stem: "School plan: talk at 2:00; game at 3:00. The game begins ___ the talk.", options: ["after", "during", "until", "before"], answerIndex: 0, reasons: ["3:00 晚於 2:00，所以 game 在 talk 之後。", "兩活動不是同時進行。", "game 不是持續到 talk 的終點。", "before 會把時間順序顛倒。"], reviews: ["表格先給兩個鐘點，再要求轉成事件關係。", "第一項正確保留 2:00 到 3:00 的先後。"], cognitiveProcess: ["order-school-events-by-clock", "express-game-after-talk"], representationType: "event-plan-after-transfer", misconceptionTargets: ["follow-list-order-without-time-check"] },
    { stem: "Nora read a book ___ the train ride.", options: ["after of", "during", "until of", "before to"], answerIndex: 1, reasons: ["after 不和 of 組成這個片語。", "during the train ride 表示搭車期間。", "until of 不是標準形式。", "before to 不能直接接名詞片語。"], reviews: ["the train ride 是一段可容納閱讀活動的期間。", "第二項回答閱讀何時發生，不需建立另一個終點。"], cognitiveProcess: ["treat-train-ride-as-duration-noun", "place-reading-during-ride"], representationType: "travel-period-during-cloze", misconceptionTargets: ["invent-compound-preposition"] },
    { stem: "The light was on until midnight. What follows from the sentence?", options: ["The light came on at midnight.", "The light was never on.", "The light stayed on up to midnight.", "Midnight lasted all night."], answerIndex: 2, reasons: ["until 不表示動作到終點才開始。", "句子明確說燈處於開啟狀態。", "until midnight 表示狀態維持到午夜。", "midnight 是時間點，不是一整夜的期間。"], reviews: ["was on 是持續狀態，而非一次開燈動作。", "第三項只陳述 until 能保證的延續範圍。"], cognitiveProcess: ["interpret-state-plus-until-midnight", "infer-continuation-to-endpoint"], representationType: "until-state-inference-boundary", misconceptionTargets: ["treat-endpoint-as-start-time"] },
    { stem: "Wash the fruit ___ you eat it, and clean the table ___ dinner.", options: ["after / until", "during / before", "until / during", "before / after"], answerIndex: 3, reasons: ["水果應在吃之前清洗，第一空不能用 after。", "during you eat it 的結構不合，餐桌也不是餐前才清理的唯一意思。", "until 不適合單次洗水果，during dinner 也改變第二個指示。", "before you eat it 與 after dinner 建立合理衛生順序。"], reviews: ["兩個空格各有一組事件，不能用同一線索一起猜。", "第四項分別得到先洗再吃、餐後清桌。"], cognitiveProcess: ["order-washing-eating-and-cleaning-events", "fill-before-and-after-pair"], representationType: "two-event-sequence-cloze", misconceptionTargets: ["apply-one-time-relation-to-both-actions"] },
  ]),
  ...skillQuestions("136", [
    { stem: "The keys are ___ the drawer.", options: ["in", "on", "at", "to"], answerIndex: 0, reasons: ["in 表示鑰匙位於抽屜內部。", "on 會表示在抽屜表面。", "at 只指出抽屜附近的位置點，不夠精確。", "to 表示方向，不是靜態位置。"], reviews: ["drawer 是可容納物品的空間。", "第一項回答鑰匙在其內部。"], cognitiveProcess: ["classify-drawer-as-container", "place-keys-inside-with-in"], representationType: "container-place-preposition-cloze", misconceptionTargets: ["use-at-for-inside-location"] },
    { stem: "A photo is ___ the desk.", options: ["in", "on", "at", "into"], answerIndex: 1, reasons: ["in the desk 會表示位於桌子內部。", "on the desk 表示照片接觸桌面。", "at the desk 通常表示人在桌邊的位置。", "into 需要移動方向，句中只有 is。"], reviews: ["is 表示靜態位置，desk 提供表面。", "第二項同時符合接觸與靜態關係。"], cognitiveProcess: ["identify-desk-surface", "choose-on-for-photo-location"], representationType: "surface-place-preposition-cloze", misconceptionTargets: ["confuse-at-desk-with-on-desk"] },
    { stem: "Please wait for me ___ the front gate.", options: ["on", "in", "at", "onto"], answerIndex: 2, reasons: ["on the gate 會表示人在門的表面，語意不合。", "in the gate 不是一般會合位置。", "at the front gate 把大門當成明確會合點。", "onto 表示移動到表面，不接 wait 的靜態位置。"], reviews: ["wait for me 要指定雙方找到彼此的位置。", "第三項不必描述大門內外，只標示會合點。"], cognitiveProcess: ["interpret-gate-as-meeting-point", "select-at-for-waiting-location"], representationType: "meeting-point-preposition-cloze", misconceptionTargets: ["put-person-on-gate-surface"] },
    { stem: "The town is ___ Taiwan.", options: ["at", "on", "by", "in"], answerIndex: 3, reasons: ["at Taiwan 不能表示位於國家範圍內。", "on Taiwan 不是本句的一般地理位置用法。", "by Taiwan 會表示在旁邊，並非隸屬範圍。", "in Taiwan 表示城鎮位於臺灣境內。"], reviews: ["Taiwan 在這裡是有邊界的地理範圍。", "第四項描述 town 位於該範圍內。"], cognitiveProcess: ["treat-taiwan-as-geographic-area", "locate-town-with-in"], representationType: "region-place-preposition-cloze", misconceptionTargets: ["use-at-before-country"] },
    { stem: "The answer is ___ page 12.", options: ["on", "in", "at", "under"], answerIndex: 0, reasons: ["on page 12 是標準頁面位置用法。", "in page 12 不把頁面視為資訊表面。", "at page 12 不是本句的一般搭配。", "under page 12 會表示在頁面下方，意思不同。"], reviews: ["頁碼提供資訊所在的頁面。", "第一項和 on the wall 一樣使用表面視角。"], cognitiveProcess: ["identify-page-as-information-surface", "apply-on-to-page-number"], representationType: "page-location-preposition-cloze", misconceptionTargets: ["translate-in-a-page-literally"] },
    { stem: "Let's meet ___ the bus stop at five.", options: ["in", "at", "on", "inside of"], answerIndex: 1, reasons: ["in the bus stop 不能表示在站牌這個會合點。", "at the bus stop 正確指定見面的地點。", "on the bus stop 會誤把站牌當成表面。", "inside of 不適合沒有內部空間的站牌位置。"], reviews: ["bus stop 是路線上的明確位置點。", "第二項同時符合 meet 的地點需求與 at five 的時間安排。"], cognitiveProcess: ["identify-bus-stop-as-rendezvous-point", "choose-at-for-meeting-location"], representationType: "bus-stop-meeting-point-cloze", misconceptionTargets: ["treat-bus-stop-as-container"] },
    { stem: "A student writes, 'The picture is in the wall.' Which change gives the usual hanging position?", options: ["picture → pictures", "is → are", "in → on", "wall → room"], answerIndex: 2, reasons: ["主詞是單數 picture，不需改複數。", "picture 與 is 已保持單數一致，不能改成 are。", "掛著的圖片接觸牆面，應寫 on the wall。", "改成 room 會刪除牆面資訊，仍未處理介系詞。"], reviews: ["題目指一般懸掛位置，排除圖片嵌在牆體內的特殊情況。", "第三項只修正表面與內部的空間關係。"], cognitiveProcess: ["diagnose-in-wall-for-hanging-picture", "edit-to-on-wall-surface"], representationType: "place-preposition-proofreading", misconceptionTargets: ["treat-wall-as-container"] },
    { stem: "Mia is inside the station building. Mia is ___ the station.", options: ["on", "at the door of", "near", "in"], answerIndex: 3, reasons: ["on 會把位置放在車站表面，不是建築內部。", "at the door of 只把她放在車站門口。", "near 表示在附近，可能尚未進入。", "in 明確表示人在車站建築內。"], reviews: ["inside 是本題不能省略的空間細節。", "第四項完整保留人在建築內部的位置。"], cognitiveProcess: ["preserve-inside-building-detail", "select-in-station-cloze"], representationType: "location-perspective-cloze", misconceptionTargets: ["treat-near-and-in-as-identical-detail"] },
    { stem: "A book is in a bag. The bag is on a chair. Where is the book?", options: ["In the bag", "On the chair beside the bag", "At the chair", "Under the bag"], answerIndex: 0, reasons: ["第一句直接說書在袋子裡。", "袋子在椅子上，不代表書在袋子旁。", "at the chair 失去袋子的容器關係。", "書在袋內，不是在袋子下方。"], reviews: ["兩層位置中，先保留最直接包住 book 的 bag。", "第一項不把容器所在處誤當成物品與容器的關係。"], cognitiveProcess: ["track-book-inside-bag", "retain-nearest-container-location"], representationType: "nested-location-inference", misconceptionTargets: ["skip-container-and-attach-to-chair"] },
    { stem: "Ben is ___ school now, taking a class.", options: ["on", "at", "into", "under"], answerIndex: 1, reasons: ["on school 不是表示參與學校活動的搭配。", "at school 表示 Ben 正在學校這個活動地點。", "into 需要移動，is 表示靜態狀態。", "under school 會表示在學校下方，和上課不合。"], reviews: ["taking a class 支持人在學校活動，而非描述建築表面。", "第二項使用常見的 at school。"], cognitiveProcess: ["connect-class-activity-to-school-location", "choose-at-school-collocation"], representationType: "institution-activity-location", misconceptionTargets: ["treat-school-as-container-only"] },
    { stem: "A coin is on the box. What does this sentence tell us?", options: ["The coin is inside the box.", "The coin is moving toward the box.", "The coin touches the box.", "The coin is far from the box."], answerIndex: 2, reasons: ["inside 需要 in，不是 on。", "移動方向會使用 onto 等形式。", "on 表示硬幣位於並接觸盒子表面。", "on 表示直接位置關係，不是距離很遠。"], reviews: ["句子使用靜態 is on，沒有移動動詞。", "第三項只陳述 on 能確定的接觸關係。"], cognitiveProcess: ["interpret-static-on-box", "infer-surface-contact-only"], representationType: "surface-preposition-meaning", misconceptionTargets: ["confuse-on-with-onto-or-in"] },
    { stem: "Mia is ___ the room, and Ben is waiting ___ the door.", options: ["at / on", "on / in", "in / on", "in / at"], answerIndex: 3, reasons: ["at the room 不表示 Mia 在房內，on the door 也把 Ben 放到門面上。", "on the room 不是內部位置，in the door 不是正常等待點。", "第一空 in 正確，但 on the door 仍不符合等待位置。", "in the room 表示內部，at the door 表示門口位置點。"], reviews: ["兩空分別測封閉空間與會合位置。", "第四項讓 Mia 在室內，同時讓 Ben 位於門邊等待。"], cognitiveProcess: ["classify-room-interior-and-door-point", "fill-in-and-at-location-pair"], representationType: "dual-place-preposition-cloze", misconceptionTargets: ["apply-one-place-rule-to-two-relations"] },
  ]),
  ...skillQuestions("137", [
    { stem: "The clock is ___ the shelf, but not directly over it.", options: ["above", "over", "under", "on"], answerIndex: 0, reasons: ["above 只要求時鐘位置較高，符合 not directly over。", "over 會和題目排除的直接上方關係衝突。", "under 表示較低或在下方。", "on 會表示時鐘接觸架子表面。"], reviews: ["but 後的限制決定不能只看到較高就選 over。", "第一項保留一般高低，不增加垂直對齊。"], cognitiveProcess: ["use-not-directly-over-constraint", "select-general-above-relation"], representationType: "above-versus-over-cloze", misconceptionTargets: ["treat-any-higher-position-as-over"] },
    { stem: "A lamp hangs ___ the dining table.", options: ["below", "over", "under", "on"], answerIndex: 1, reasons: ["below 會把燈放到桌面較低處。", "over 表示燈位於餐桌正上方。", "under 會顛倒燈與桌子的上下關係。", "on 表示接觸桌面，與 hangs 不合。"], reviews: ["hanging lamp 與 dining table 建立直接上下照明關係。", "第二項不表示燈碰到桌子。"], cognitiveProcess: ["infer-lamp-table-vertical-alignment", "choose-over-for-directly-higher"], representationType: "over-direct-position-cloze", misconceptionTargets: ["confuse-over-with-surface-on"] },
    { stem: "The shoes are ___ the window.", options: ["above", "over", "below", "onto"], answerIndex: 2, reasons: ["above 會表示鞋子比窗戶高。", "over 會把鞋子放到窗戶上方。", "below 表示鞋子的位置低於窗戶。", "onto 需要移動到表面，句中只有 are。"], reviews: ["一般室內情境中鞋子在地面，窗戶位置較高。", "第三項只比較高低，不宣稱鞋子正好在窗下。"], cognitiveProcess: ["compare-shoe-and-window-heights", "apply-below-general-lower-position"], representationType: "below-position-cloze", misconceptionTargets: ["use-under-without-direct-relation"] },
    { stem: "The cat is sleeping ___ the chair, inside the space between its legs.", options: ["above", "over", "below", "under"], answerIndex: 3, reasons: ["above 會把貓放到椅子上方。", "over 也表示貓在較高處。", "below 只說位置較低，沒有指出貓在椅腳圍出的空間內。", "under the chair 表示貓睡在椅子正下方的空間。"], reviews: ["between its legs 把位置限制在椅子下方，而非任意較低處。", "第四項保留了椅子與貓的直接上下關係。"], cognitiveProcess: ["use-chair-leg-space-as-direct-under-evidence", "locate-cat-under-chair"], representationType: "under-object-bounded-space-cloze", misconceptionTargets: ["choose-below-without-direct-object-space"] },
    { stem: "Nora held an umbrella ___ her head.", options: ["over", "below", "under", "through"], answerIndex: 0, reasons: ["over 表示雨傘位在頭頂並提供遮蓋。", "below 會把雨傘放到頭部下方。", "under 會顛倒被保護者與雨傘的位置。", "through 表示穿越路徑，不是靜態遮蓋。"], reviews: ["held 與 umbrella 的用途提供直接上方線索。", "第一項同時表達位置和保護關係。"], cognitiveProcess: ["connect-umbrella-to-head-cover", "choose-over-for-protection"], representationType: "covering-over-cloze", misconceptionTargets: ["select-above-without-covering-nuance"] },
    { stem: "The temperature fell to 2°C ___ zero.", options: ["under", "below", "over", "onto"], answerIndex: 1, reasons: ["under zero 有時可見，但本單元的數值基準使用 below zero。", "below zero 表示溫度數值低於零。", "over zero 會表示高於零。", "onto 需要移動到表面。"], reviews: ["zero 是數值基準，不是會遮住溫度的物體。", "第二項將高低位置概念延伸到溫度刻度。"], cognitiveProcess: ["interpret-zero-as-temperature-reference", "select-below-for-negative-value"], representationType: "below-zero-data-cloze", misconceptionTargets: ["treat-numeric-lower-as-under-object"] },
    { stem: "A report says, 'The road goes below the bridge and passes directly under it.' Which change fits this meaning?", options: ["road → roads", "goes → going", "below → under", "bridge → river"], answerIndex: 2, reasons: ["單數 road 與 goes 一致。", "改成 going 會破壞主要動詞。", "directly under 表示道路從橋的正下方通過，under 更合適。", "改成 river 會更換原本的參照物。"], reviews: ["題目不是說 below 絕對不能用，而是要求更符合直接下方。", "第三項保留事件並提高位置精確度。"], cognitiveProcess: ["use-directly-beneath-as-precision-clue", "edit-below-to-under-bridge"], representationType: "vertical-relation-precision-edit", misconceptionTargets: ["ignore-direct-alignment-evidence"] },
    { stem: "A shelf is 2 meters above the floor. A picture is 1 meter above the floor. The picture is ___.", options: ["over the shelf", "on the shelf", "under the floor", "below the shelf"], answerIndex: 3, reasons: ["1 公尺位置不會高於 2 公尺的架子。", "資料沒有說圖片接觸架子。", "圖片仍在地板上方，不在地板下。", "1 公尺低於 2 公尺，所以圖片在架子下方。"], reviews: ["兩個高度都使用同一個 floor 基準。", "第四項由 1 小於 2 得出一般較低關係。"], cognitiveProcess: ["compare-two-heights-from-floor", "infer-picture-below-shelf"], representationType: "height-data-position-transfer", misconceptionTargets: ["reverse-height-order"] },
    { stem: "A bird flew over the park. What can we know from this alone?", options: ["The bird moved above the park without touching it.", "The bird landed in the park.", "The park covered the bird.", "The bird stayed under the park."], answerIndex: 0, reasons: ["flew over 表示鳥在公園上方移動，沒有接觸地面。", "句子沒有說鳥降落。", "覆蓋關係若存在也應是鳥在上、公園在下，不能反向解讀。", "under 與原句的 over 相反。"], reviews: ["動詞 flew 讓 over 同時帶有跨越路徑。", "第一項不額外推論終點。"], cognitiveProcess: ["interpret-motion-over-field", "limit-inference-to-above-path"], representationType: "over-motion-inference", misconceptionTargets: ["infer-landing-from-flying-over"] },
    { stem: "Which sentence says only that the bag is lower, not right under another thing?", options: ["The bag is under the desk.", "The bag is below the window.", "The bag is on the floor.", "The bag is through the door."], answerIndex: 1, reasons: ["under the desk 帶有較直接的桌下空間。", "below the window 只要求袋子位置較低。", "on the floor 表示接觸地面，不是相對窗戶的高低。", "through the door 是移動路徑，不是靜態較低。"], reviews: ["題目明確排除位於另一物正下方的關係。", "第二項符合 below 的一般高低範圍。"], cognitiveProcess: ["match-general-lower-without-alignment", "select-below-window-statement"], representationType: "below-definition-selection", misconceptionTargets: ["equate-below-with-direct-under"] },
    { stem: "The child pulled a blanket ___ herself to stay warm.", options: ["below", "under", "over", "above"], answerIndex: 2, reasons: ["below herself 會把毯子放在身體較低處。", "under herself 表示毯子在身體下面。", "over herself 表示毯子覆蓋身體。", "above 只說較高，沒有呈現覆蓋保暖。"], reviews: ["to stay warm 說明毯子要覆蓋使用者。", "第三項使用 over 的覆蓋意思，而非單純高度。"], cognitiveProcess: ["infer-blanket-covering-from-warmth", "apply-over-reflexive-object"], representationType: "covering-purpose-over-cloze", misconceptionTargets: ["choose-above-for-covering"] },
    { stem: "The plane is ___ the clouds, and the bag is ___ the seat.", options: ["under / above", "over / below", "below / on", "above / under"], answerIndex: 3, reasons: ["飛機不在雲下，袋子也不在座位上方。", "over 可表示飛機在雲上，但 below 只說袋子較低，沒有座位下空間。", "below clouds 與題意方向不合，on seat 也改成接觸座面。", "above the clouds 表示飛機較高，under the seat 表示袋子在座位下。"], reviews: ["兩空使用不同精細度：一般高度與直接下方。", "第四項分別符合 plane-clouds 和 bag-seat 關係。"], cognitiveProcess: ["classify-cloud-height-and-seat-space", "fill-above-and-under-pair"], representationType: "dual-vertical-relation-cloze", misconceptionTargets: ["use-same-vertical-term-for-different-relations"] },
  ]),
  ...skillQuestions("138", [
    { stem: "The school is on one side of the bank, and the park is on the other. The bank is ___ them.", options: ["between", "among", "beside", "near"], answerIndex: 0, reasons: ["between 表示 bank 位於兩個明確地點所形成的中間位置。", "among 會把周圍對象視為群體，不能保留兩側關係。", "beside 只指出緊鄰一個對象，沒有表達兩邊。", "near 只表示接近，無法說明 one side 與 the other。"], reviews: ["one side 與 the other 提供兩個相對邊界。", "第一項完整保留 bank 位於兩地中間的資料。"], cognitiveProcess: ["map-opposite-side-clues-to-two-boundaries", "place-bank-between-school-park"], representationType: "between-opposite-sides-cloze", misconceptionTargets: ["replace-middle-position-with-general-nearness"] },
    { stem: "Coins are all around a key. The key is ___ the coins.", options: ["between", "among", "beside", "under"], answerIndex: 1, reasons: ["between 需要把參照對象個別分開，題目卻描述整群硬幣。", "among 表示鑰匙位於許多硬幣所形成的群體中。", "beside 只表示在硬幣旁邊，與 all around 不合。", "under 會表示在硬幣下方，沒有表達周圍環繞。"], reviews: ["all around 把許多硬幣描述為周圍群體。", "第二項保留鑰匙位於硬幣群之中的位置。"], cognitiveProcess: ["use-all-around-as-group-evidence", "choose-among-for-key-in-coin-group"], representationType: "among-surrounding-group-cloze", misconceptionTargets: ["choose-beside-despite-surrounding-group"] },
    { stem: "The chair is not just near the bed; their sides touch. The chair is ___ the bed.", options: ["near", "among", "beside", "between"], answerIndex: 2, reasons: ["near 已被 not just 排除，因為題目要求比距離近更明確的關係。", "among 需要群體環繞。", "beside 表示就在床旁，符合兩側相接。", "between 需要另外指出兩個邊界。"], reviews: ["not just near 要求把一般接近改成緊鄰。", "第三項利用 sides touch 的直接證據。"], cognitiveProcess: ["upgrade-near-to-adjacency-from-contact", "select-beside-bed"], representationType: "near-to-beside-precision-cloze", misconceptionTargets: ["ignore-not-just-near-contrast"] },
    { stem: "The hotel is ___ the station, about a five-minute walk away.", options: ["among", "between", "beside", "near"], answerIndex: 3, reasons: ["among 需要旅館位於一群車站之中。", "between 缺少另一個明確邊界。", "beside 會暗示緊鄰，但五分鐘路程不保證相鄰。", "near 表示距離不遠，符合步行五分鐘。"], reviews: ["five-minute walk 提供接近但非接觸的距離。", "第四項不把附近誇大成就在旁邊。"], cognitiveProcess: ["interpret-five-minute-walk-as-near", "avoid-beside-without-adjacency"], representationType: "near-distance-cloze", misconceptionTargets: ["infer-beside-from-short-walk"] },
    { stem: "On a map, Road B lies after Road A and before Road C. Road B is ___.", options: ["between Road A and Road C", "among Road A and Road C", "beside all roads", "near no road"], answerIndex: 0, reasons: ["B 的位置由 A 與 C 兩個邊界夾定。", "among 不搭配兩個用 and 指出的道路邊界。", "資料沒有說所有道路彼此緊鄰。", "B 已與 A、C 建立順序關係，不能說不靠近任何路。"], reviews: ["after A 與 before C 共同定位 B。", "第一項把線性順序轉成 between 關係。"], cognitiveProcess: ["combine-before-and-after-map-order", "infer-road-b-between-a-c"], representationType: "ordered-map-between-transfer", misconceptionTargets: ["ignore-two-sided-order"] },
    { stem: "Mia stood ___ the students in the school hall, with students on every side.", options: ["beside", "among", "between", "near to"], answerIndex: 1, reasons: ["beside 只會把 Mia 放在學生群旁邊，無法表達四周都有人。", "among the students 表示她站在學生群中。", "between 需要明確分開的邊界或對象。", "near to 只說距離近，沒有保留 every side。"], reviews: ["with students on every side 表示周圍是一個學生群體。", "第二項同時保留 Mia 在群體內與四周有人的資訊。"], cognitiveProcess: ["use-every-side-as-group-surrounding-evidence", "place-mia-among-students"], representationType: "person-surrounded-by-group-cloze", misconceptionTargets: ["choose-near-despite-all-around-evidence"] },
    { stem: "A note says, 'Sit near me; our chairs must touch.' Which word shows this position?", options: ["among", "between", "beside", "far from"], answerIndex: 2, reasons: ["among 需要一個群體。", "between 需要兩側參照物。", "beside 表示坐在說話者旁邊，能配合椅子相碰。", "far from 與 must touch 相反。"], reviews: ["第二句把第一句的 near 進一步限定為緊鄰。", "第三項是符合接觸條件的精確位置字。"], cognitiveProcess: ["strengthen-near-with-chair-touch-condition", "replace-with-beside-position"], representationType: "near-to-beside-precision", misconceptionTargets: ["keep-vague-near-despite-contact"] },
    { stem: "A shop is near the library. What can we know for sure?", options: ["The shop touches the library wall.", "The shop is inside the library.", "The shop is between two libraries.", "The shop is not far from the library."], answerIndex: 3, reasons: ["near 不保證兩棟建築相接。", "接近不等於位於建築內。", "句子只提一間 library，沒有兩個邊界。", "near 能確定的只有兩地距離不遠。"], reviews: ["題目要求 for sure，需避免把近推成相鄰。", "第四項是 near 的最小充分意思。"], cognitiveProcess: ["limit-inference-from-near-library", "retain-not-far-only"], representationType: "near-inference-boundary", misconceptionTargets: ["infer-touching-from-near"] },
    { stem: "Each of three named towns has a road to the other two. The roads run ___ the towns.", options: ["between", "among", "beside", "under"], answerIndex: 0, reasons: ["between 可表達三座可逐一分辨城鎮之間的連接關係。", "among 會把城鎮當成未區分的群體，不能精確表達各城相連。", "beside 只表示道路在某城旁邊，不表示通往其他兩城。", "under 是上下位置，和城鎮連線無關。"], reviews: ["each 與 the other two 說明三座城鎮各自可辨。", "第一項依個別連接關係判斷，而非只背對象數量。"], cognitiveProcess: ["read-each-to-other-two-as-distinct-relations", "allow-between-for-three-named-towns"], representationType: "between-three-pairwise-connections", misconceptionTargets: ["force-among-whenever-more-than-two"] },
    { stem: "Which sentence places one person inside a group?", options: ["Ben stood beside the team.", "Ben stood among the team members.", "Ben stood between the door and the wall.", "Ben stood near the team."], answerIndex: 1, reasons: ["beside 表示在隊伍旁，不在群體內。", "among the team members 表示 Ben 位於成員之中。", "between 描述門與牆兩個邊界。", "near 只表示靠近隊伍。"], reviews: ["inside a group 是 among 的核心條件。", "第二項明確將 Ben 放入 team members 群體。"], cognitiveProcess: ["match-inside-group-definition", "select-among-team-members-sentence"], representationType: "among-function-selection", misconceptionTargets: ["confuse-near-group-with-among-group"] },
    { stem: "A student writes, 'The lamp is besides the bed.' Which change fixes the position word?", options: ["lamp → lamps", "is → are", "besides → beside", "bed → bedroom"], answerIndex: 2, reasons: ["lamp 是單數，不能只改成複數而保留 is。", "單數主詞應保留 is。", "beside 表示燈在床旁；besides 不是此處的位置字。", "換成 bedroom 仍未修正 besides。"], reviews: ["錯誤是多出的 s 改變了字的功能。", "第三項保留原有兩物相鄰關係。"], cognitiveProcess: ["diagnose-besides-as-nonlocation-form", "edit-to-beside-bed"], representationType: "beside-besides-proofreading", misconceptionTargets: ["treat-besides-as-spelling-variant"] },
    { stem: "The shop is next to the bank and a short walk from the school. Which line keeps both facts?", options: ["The shop is among the bank and school.", "The shop is between no buildings.", "The shop is near the bank and beside the school.", "The shop is beside the bank and near the school."], answerIndex: 3, reasons: ["among 不搭配兩個指定地點，且未表達 next to。", "此項否定了已提供的位置資料。", "它把 next to 與 short walk 的對象互換。", "beside the bank 對應 next to，near the school 對應 short walk。"], reviews: ["兩個距離線索分別指向不同建築。", "第四項保持 bank 與 school 的原始配對。"], cognitiveProcess: ["map-next-to-and-short-walk-to-relations", "preserve-bank-school-reference-pairs"], representationType: "two-distance-facts-paraphrase", misconceptionTargets: ["swap-relative-location-targets"] },
  ]),
  ...skillQuestions("139", [
    { stem: "We walked ___ the park but stayed outside the gate.", options: ["to", "into", "onto", "through"], answerIndex: 0, reasons: ["to 表示走到公園這個目的地，未必進入。", "into 會和 stayed outside the gate 衝突。", "onto 表示到表面，不適合公園目的地。", "through 會表示穿過公園內部。"], reviews: ["outside the gate 明確排除進入或穿越。", "第一項只保留方向與終點。"], cognitiveProcess: ["use-stayed-outside-gate-constraint", "choose-to-without-entry"], representationType: "to-destination-cloze", misconceptionTargets: ["infer-entry-from-movement-to-place"] },
    { stem: "The cat jumped ___ the open box and landed inside it.", options: ["to", "into", "onto", "through"], answerIndex: 1, reasons: ["to 只表示朝箱子去，不能保證最後在裡面。", "into 表示貓跨過箱口並落在箱內。", "onto 會把終點放在箱子表面，與 inside it 衝突。", "through 表示穿過後離開，不能保留箱內終點。"], reviews: ["landed inside it 明確指定移動後的位置。", "第二項同時表達方向、跨越邊界與箱內終點。"], cognitiveProcess: ["use-inside-landing-as-entry-evidence", "select-into-for-jump-entry"], representationType: "into-container-motion-with-endpoint", misconceptionTargets: ["ignore-inside-endpoint-and-choose-onto"] },
    { stem: "The cup fell ___ the floor.", options: ["into", "through", "onto", "to"], answerIndex: 2, reasons: ["into 需要地板有可進入的內部空間。", "through 會表示杯子穿過地板。", "onto 表示杯子移動後落到地面表面。", "to 只指出方向，沒有表面終點的細節。"], reviews: ["fell 是移動，floor 是最後接觸的表面。", "第三項比靜態 on 更清楚呈現落下過程。"], cognitiveProcess: ["combine-fall-motion-with-floor-surface", "choose-onto-as-landing-endpoint"], representationType: "onto-surface-motion-cloze", misconceptionTargets: ["use-into-before-surface"] },
    { stem: "The train passed ___ the tunnel and came out on the other side.", options: ["to", "onto", "into", "through"], answerIndex: 3, reasons: ["to 只到隧道，沒有進入與離開。", "onto 不適合隧道內部路徑。", "into 只強調進入，未表達從另一端出來。", "through 包含進入、沿內部前進並離開。"], reviews: ["came out on the other side 是穿越完成的明確證據。", "第四項涵蓋整條隧道路徑。"], cognitiveProcess: ["trace-train-entry-and-exit", "select-through-complete-path"], representationType: "through-tunnel-motion-cloze", misconceptionTargets: ["use-into-despite-exit-evidence"] },
    { stem: "The child ran ___ the classroom from the hall.", options: ["into", "on", "at", "through of"], answerIndex: 0, reasons: ["into 表示孩子從走廊進入教室。", "on 會把教室當成表面。", "at 只標示位置點，沒有跨入內部。", "through of 不是標準片語。"], reviews: ["from the hall 提供起點，classroom 是有內部的終點。", "第一項呈現由外到內的方向改變。"], cognitiveProcess: ["identify-hall-origin-and-room-interior", "encode-entry-with-into"], representationType: "room-entry-motion-cloze", misconceptionTargets: ["use-at-for-directional-entry"] },
    { stem: "A note fell ___ the desk from the shelf.", options: ["into", "onto", "through", "in"], answerIndex: 1, reasons: ["desk 在此提供表面，不是容器內部。", "onto 表示紙條從架上移到桌面。", "through 會表示穿過桌子。", "in 是靜態內部位置，也未呈現落下到表面。"], reviews: ["from the shelf 與 fell 共同說明位置發生改變。", "第二項把移動終點放在 desk 表面。"], cognitiveProcess: ["track-note-from-shelf-to-desk", "apply-onto-to-surface-endpoint"], representationType: "source-to-surface-motion", misconceptionTargets: ["choose-static-in-for-fall"] },
    { stem: "A report says, 'The bus went into the tunnel and came out at the far end.' Which change fits the full trip?", options: ["bus → buses", "went → go", "into → through", "tunnel → road"], answerIndex: 2, reasons: ["單數 bus 與 went 已一致。", "過去事件應保留 went。", "進入又從遠端出來表示完整穿越，through 更精確。", "改成 road 會刪除封閉通道路徑。"], reviews: ["題目要求表達完整路徑，不是否定 into 能表示入口動作。", "第三項把出口證據納入同一個介系詞。"], cognitiveProcess: ["combine-tunnel-entry-with-far-end-exit", "edit-into-to-through"], representationType: "motion-path-precision-edit", misconceptionTargets: ["ignore-exit-when-choosing-into"] },
    { stem: "Walk ___ the gate and stop there; do not pass it.", options: ["into", "onto", "through", "to"], answerIndex: 3, reasons: ["into 會表示進入門內的空間。", "onto 需要可登上的表面。", "through 會違反 do not pass it。", "to 表示走到 gate 並停在該目的地。"], reviews: ["stop there 與 do not pass it 限制移動只到入口。", "第四項不加入跨越動作。"], cognitiveProcess: ["apply-stop-at-gate-boundary", "select-to-not-through"], representationType: "movement-instruction-boundary", misconceptionTargets: ["overread-destination-as-passage"] },
    { stem: "Path: entrance → forest → exit. A walker follows the whole path. The walker goes ___ the forest.", options: ["through", "to", "onto", "at"], answerIndex: 0, reasons: ["through 表示由入口沿森林內路徑走到出口。", "to 只會把森林當目的地，少了出口資訊。", "onto 把森林當表面。", "at 是靜態位置，不描述整段行走。"], reviews: ["箭頭序列同時提供進入、內部路徑與離開。", "第一項把三段資料整合成穿越。"], cognitiveProcess: ["read-entrance-forest-exit-sequence", "infer-through-whole-path"], representationType: "route-diagram-through-transfer", misconceptionTargets: ["stop-reading-path-at-destination"] },
    { stem: "The cat is on the roof now. Which sentence describes the earlier movement to that position?", options: ["It jumped in the roof.", "It jumped onto the roof.", "It jumped through the roof.", "It jumped at the roof."], answerIndex: 1, reasons: ["in the roof 會把貓放在屋頂結構內。", "onto the roof 表示跳躍終點在屋頂表面。", "through the roof 表示穿破或穿過屋頂。", "at the roof 只指向位置，沒有到達表面的關係。"], reviews: ["現在的 on 提供最後位置，題目要求回推移動。", "第二項以 onto 連接跳躍與表面終點。"], cognitiveProcess: ["convert-static-on-roof-to-prior-motion", "choose-jumped-onto-roof"], representationType: "static-to-motion-rewrite", misconceptionTargets: ["reuse-in-for-surface-destination"] },
    { stem: "Ben walked to the library. What do we still not know?", options: ["The library was the place Ben walked to.", "Ben moved toward the library.", "Whether Ben went inside the library.", "Ben did not move."], answerIndex: 2, reasons: ["to the library 已指出行走終點。", "walked to 表示他朝圖書館移動。", "to 不保證跨入建築內部，因此是否進去仍未知。", "walked 明確表示有移動。"], reviews: ["題目要求找出原句無法確定的資訊，需區分 to 能保證與不能保證的內容。", "第三項正是 into 才會補充的進入細節。"], cognitiveProcess: ["separate-to-destination-from-entry", "identify-unknown-library-interior"], representationType: "to-inference-boundary", misconceptionTargets: ["assume-to-means-entered"] },
    { stem: "A bird flew ___ the open window and landed ___ the table.", options: ["to / in", "onto / through", "into / at", "through / onto"], answerIndex: 3, reasons: ["to the window 沒有穿過，in the table 也把桌子當容器。", "onto the window 與 through the table 把兩個終點顛倒。", "into 可表示進入房間，但 at the table 沒有呈現落到桌面。", "through the window 表示穿過開口，onto the table 表示落到表面。"], reviews: ["兩個動詞分別要求路徑與表面終點。", "第四項保留先穿窗、後落桌的事件順序。"], cognitiveProcess: ["classify-window-passage-and-table-landing", "fill-through-and-onto-motion-pair"], representationType: "two-stage-motion-cloze", misconceptionTargets: ["swap-passage-and-surface-prepositions"] },
  ]),
  ...skillQuestions("140", [
    { stem: "The train arrived ___ Taipei before noon.", options: ["in", "at", "to", "no word"], answerIndex: 0, reasons: ["arrive in 常接城市 Taipei。", "at 通常接車站、旅館等明確地點。", "arrive to 不是本單元的標準搭配。", "Taipei 前不能在此省略介系詞。"], reviews: ["Taipei 是城市範圍，不是站名。", "第一項符合 arrive in + city。"], cognitiveProcess: ["classify-taipei-as-city", "select-arrive-in-city"], representationType: "arrive-in-city-cloze", misconceptionTargets: ["use-arrive-at-before-city"] },
    { stem: "We arrived ___ the hotel front desk early.", options: ["in", "at", "to", "no word"], answerIndex: 1, reasons: ["in the hotel front desk 會把櫃檯誤當成內部空間。", "arrive at the hotel front desk 正確指出具體抵達點。", "arrive to 不是此處的標準形式。", "arrive 後接一般地點不能直接省略介系詞。"], reviews: ["front desk 是旅館內可明確指出的位置點。", "第二項精確保留抵達櫃檯的意思。"], cognitiveProcess: ["identify-hotel-front-desk-as-arrival-point", "choose-arrive-at-specific-desk"], representationType: "arrive-at-specific-point-cloze", misconceptionTargets: ["use-in-before-specific-front-desk"] },
    { stem: "Mia reached ___ school at eight.", options: ["at", "to", "no word", "in"], answerIndex: 2, reasons: ["reach 後不加 at 再接目的地。", "reach 本身已有到達意思，不加 to。", "reached school 直接以 school 作受詞。", "in 也不能插在 reached 與受詞間。"], reviews: ["先辨認動詞是 reached，不是 arrived。", "第三項保留直接動詞受詞結構。"], cognitiveProcess: ["identify-reach-transitive-pattern", "omit-preposition-before-school"], representationType: "reach-direct-object-cloze", misconceptionTargets: ["copy-arrive-at-pattern-to-reach"] },
    { stem: "Leo arrived ___ after the long trip.", options: ["at home", "to home", "in home", "home"], answerIndex: 3, reasons: ["arrive home 不加 at。", "to home 不是 arrive 的標準特殊搭配。", "in home 缺少必要限定且不是此句形式。", "home 可直接接在 arrived 後。"], reviews: ["home 是本技能需要單獨辨認的例外。", "第四項不同於 arrive at my house。"], cognitiveProcess: ["recognize-home-after-arrive", "select-zero-preposition-home"], representationType: "arrive-home-exception", misconceptionTargets: ["add-at-before-home"] },
    { stem: "Our flight arrived ___ Japan in the evening.", options: ["in", "at", "to", "onto"], answerIndex: 0, reasons: ["Japan 是國家，搭配 arrive in。", "at 不用來接國家名稱表示抵達。", "arrive to 不是本單元標準形式。", "onto 表示到表面，與國家目的地不合。"], reviews: ["國家和城市都屬較大地理範圍。", "第一項保留 in Japan 的區域視角。"], cognitiveProcess: ["classify-japan-as-country", "apply-arrive-in-country"], representationType: "arrive-in-country-cloze", misconceptionTargets: ["treat-country-as-point-with-at"] },
    { stem: "The bus arrived ___ Gate 4 at 6:20.", options: ["in", "at", "to", "no word"], answerIndex: 1, reasons: ["in Gate 4 不能把編號入口當成可進入的地區。", "arrive at Gate 4 正確指出明確抵達點。", "arrive to Gate 4 不是本單元形式。", "Gate 4 前不能像 home 一樣省略介系詞。"], reviews: ["編號把 gate 指定為單一位置點。", "第二項同時保留抵達地點與 6:20 的時間。"], cognitiveProcess: ["identify-numbered-gate-as-specific-point", "choose-arrive-at-gate-four"], representationType: "arrive-at-numbered-gate-cloze", misconceptionTargets: ["treat-numbered-gate-as-large-area"] },
    { stem: "A student writes, 'We reached to the park at noon.' Which change fixes the verb pattern?", options: ["We → Us", "park → parks", "reached to → reached", "at noon → on noon"], answerIndex: 2, reasons: ["We 是正確主詞。", "改複數不會修正 reach 的搭配。", "reach 直接接 the park，應刪除 to。", "noon 前使用 at，不能改成 on。"], reviews: ["句中同時有地點與時間介系詞，只有地點前的 to 多餘。", "第三項形成 reached the park at noon。"], cognitiveProcess: ["separate-reach-object-from-at-noon", "remove-to-after-reached"], representationType: "reach-pattern-proofreading", misconceptionTargets: ["delete-correct-time-preposition-instead"] },
    { stem: "Nora arrived ___ my house before dinner.", options: ["in", "to", "no word", "at"], answerIndex: 3, reasons: ["my house 作具體終點時不搭配 arrive in。", "arrive to 不是本句標準形式。", "只有 home 可在此類用法直接省略；my house 不行。", "arrive at my house 正確表示抵達住所地點。"], reviews: ["my house 雖與 home 意思相關，句法形式不同。", "第四項避免把 arrive home 的例外過度延伸。"], cognitiveProcess: ["contrast-my-house-with-home", "select-at-before-house-phrase"], representationType: "arrive-at-house-boundary", misconceptionTargets: ["omit-preposition-before-my-house"] },
    { stem: "Trip plan: enter Tainan; then check in at the hotel. Which line keeps both stops?", options: ["Arrive in Tainan, then arrive at the hotel.", "Arrive at Tainan, then arrive in the hotel.", "Reach to Tainan, then arrive to the hotel.", "Arrive Tainan, then reach at the hotel."], answerIndex: 0, reasons: ["in 配合城市 Tainan，at 配合特定 hotel。", "兩個目的地的尺度介系詞被互換。", "reach 與 arrive 後都多加了不合的 to。", "arrive Tainan 缺介系詞，reach at 也錯。"], reviews: ["行程有城市與旅館兩種不同尺度。", "第一項逐一配對，沒有用一條規則套兩站。"], cognitiveProcess: ["classify-city-and-hotel-stops", "pair-arrive-in-and-arrive-at"], representationType: "two-stop-arrival-plan", misconceptionTargets: ["use-one-arrive-preposition-for-all-places"] },
    { stem: "The team arrived at the park before noon = The team ___ the park before noon.", options: ["reached at", "reached", "reached to", "reached in"], answerIndex: 1, reasons: ["reached at 把 arrive 的 at 錯接到 reach 後。", "reached 直接接受詞 the park，完整保留原句的到達意思。", "reached to 多加了方向介系詞。", "reached in 也破壞 reach 直接接受詞的結構。"], reviews: ["等號兩邊必須保留抵達、公園與中午前這三項資訊。", "第二項只更換動詞結構，沒有改變事件內容。"], cognitiveProcess: ["rewrite-arrive-at-as-reach-direct-object", "preserve-park-and-before-noon-details"], representationType: "arrival-verb-meaning-equivalence", misconceptionTargets: ["carry-arrive-preposition-into-reach-rewrite"] },
    { stem: "The bus arrived ___ the station, but Nora reached ___ five minutes later.", options: ["in / at it", "to / it", "at / it", "at / at it"], answerIndex: 2, reasons: ["arrive in 不適合把 station 當具體到達點，reach 後也不加 at。", "arrive to the station 錯把方向介系詞接在 arrive 後。", "arrive at the station 與 reached it 分別使用介系詞結構和直接受詞結構。", "前半句正確，但 reached at it 多加了 at。"], reviews: ["同一目的地先以完整名詞、後以代名詞 it 表示。", "第三項同時符合 arrive at 與 reach 加受詞兩種框架。"], cognitiveProcess: ["coordinate-arrive-at-and-reach-pronoun-frames", "fill-two-linked-arrival-structures"], representationType: "paired-arrive-reach-structure-cloze", misconceptionTargets: ["insert-at-before-reach-pronoun-object"] },
    { stem: "The train should arrive at 8:00 and arrived at the station at 8:05. What happened?", options: ["It reached the station five minutes early.", "It arrived in a different city.", "It did not reach the station.", "It arrived at the station five minutes late."], answerIndex: 3, reasons: ["8:05 比 8:00 晚，不是早到。", "資料只談同一車站，沒有另一城市。", "arrived at the station 已證明列車抵達。", "實際時間比預定時間晚五分鐘。"], reviews: ["先比較預定時間與實際抵達時間的先後。", "第四項同時保留目的地與五分鐘延遲。"], cognitiveProcess: ["compare-due-and-arrival-times", "infer-five-minute-late-arrival"], representationType: "arrival-schedule-data-inference", misconceptionTargets: ["reverse-due-and-actual-time"] },
  ]),
];

export const ENGLISH_U20_VOCABULARY_POLICY = Object.freeze({
  capQuestionBasis: "appendix-5-table-1",
  additionalLearningTerms: ["alone", "among", "ball", "coin", "continue", "describe", "direct", "entrance", "exit", "film", "fit", "flight", "hall", "midnight", "movement", "path", "pattern", "position", "roof", "shelf", "temperature", "toward", "tunnel", "usual", "whole"],
  properNames: ["Amy", "Ben", "Grace", "Japan", "Kaohsiung", "Leo", "Mia", "Nora", "Sam", "Tainan", "Taipei"],
  grammarNotation: ["at", "B", "earlier", "flew", "in", "on", "onto", "stood", "verb"],
  malformedDistractors: [],
});

export const ENGLISH_U20_SOURCE = Object.freeze({ unitId: UNIT_ID, lectures: ENGLISH_U20_LECTURES, questions: ENGLISH_U20_QUESTIONS, vocabularyPolicy: ENGLISH_U20_VOCABULARY_POLICY });
export const ENGLISH_UNIT_SOURCE = ENGLISH_U20_SOURCE;
