import { defineChoiceQuestions as questions, defineEnglishUnit } from "../define-unit.mjs";

const labels = ["A", "B", "C", "D"];
const boards = [
  [[1,"standing","ball","under","hat"],[2,"walking","box","beside","scarf"],[1,"sitting","book","on","glasses"],[1,"pointing","umbrella","behind","none"]],
  [[2,"sitting","bottle","on","none"],[1,"pointing","bag","under","hat"],[1,"walking","kite","behind","glasses"],[1,"standing","cup","beside","scarf"]],
  [[1,"walking","key","beside","scarf"],[1,"sitting","clock","under","hat"],[2,"pointing","camera","on","none"],[1,"standing","guitar","behind","glasses"]],
  [[1,"pointing","box","behind","glasses"],[2,"standing","ball","on","hat"],[1,"walking","umbrella","under","none"],[1,"sitting","book","beside","scarf"]],
  [[2,"walking","cup","under","scarf"],[1,"standing","bottle","behind","none"],[1,"pointing","bag","beside","glasses"],[1,"sitting","kite","on","hat"]],
  [[1,"sitting","camera","behind","none"],[1,"walking","guitar","on","glasses"],[2,"standing","key","beside","scarf"],[1,"pointing","clock","under","hat"]],
  [[1,"standing","book","under","glasses"],[1,"pointing","umbrella","on","scarf"],[1,"sitting","box","behind","hat"],[2,"walking","ball","beside","none"]],
  [[2,"pointing","kite","beside","hat"],[1,"walking","cup","behind","none"],[1,"standing","bottle","under","scarf"],[1,"sitting","bag","on","glasses"]],
  [[1,"walking","guitar","under","hat"],[1,"sitting","camera","beside","scarf"],[2,"pointing","clock","behind","glasses"],[1,"standing","key","on","none"]],
  [[1,"sitting","umbrella","on","scarf"],[2,"standing","book","under","none"],[1,"walking","ball","behind","glasses"],[1,"pointing","box","beside","hat"]],
  [[1,"pointing","bag","under","none"],[1,"standing","kite","beside","glasses"],[1,"sitting","cup","behind","hat"],[2,"walking","bottle","on","scarf"]],
  [[2,"sitting","clock","beside","glasses"],[1,"walking","key","on","none"],[1,"pointing","guitar","under","hat"],[1,"standing","camera","behind","scarf"]],
];

export const ENGLISH_LISTENING_PICTURE_BOARDS=boards;

function objectSvg(kind, cx, cy) {
  if (kind === "ball") return `<circle cx="${cx}" cy="${cy}" r="15" fill="url(#dots)" stroke="#000" stroke-width="3"/>`;
  if (kind === "box") return `<rect x="${cx-17}" y="${cy-15}" width="34" height="30" fill="#fff" stroke="#000" stroke-width="3"/><path d="M${cx-17} ${cy-15}l34 30m0-30l-34 30" stroke="#000"/>`;
  if (kind === "book") return `<path d="M${cx-22} ${cy-12}q22-8 22 5q0-13 22-5v28q-22-8-22 5q0-13-22-5z" fill="#fff" stroke="#000" stroke-width="2"/>`;
  if (kind === "umbrella") return `<path d="M${cx-24} ${cy}q24-30 48 0zM${cx} ${cy}v28q0 10 10 10" fill="url(#dots)" stroke="#000" stroke-width="3"/>`;
  if (kind === "bottle") return `<path d="M${cx-7} ${cy-24}h14v10l7 9v28h-28v-28l7-9z" fill="#fff" stroke="#000" stroke-width="3"/>`;
  if (kind === "bag") return `<rect x="${cx-20}" y="${cy-12}" width="40" height="32" fill="url(#dots)" stroke="#000" stroke-width="3"/><path d="M${cx-10} ${cy-12}q10-18 20 0" fill="none" stroke="#000" stroke-width="3"/>`;
  if (kind === "kite") return `<path d="M${cx} ${cy-28}l22 28l-22 28l-22-28zM${cx} ${cy+28}q18 15 4 30" fill="url(#dots)" stroke="#000" stroke-width="3"/>`;
  if (kind === "cup") return `<path d="M${cx-16} ${cy-18}h32l-4 36h-24zM${cx+16} ${cy-10}q18 0 10 18q-5 8-13 3" fill="#fff" stroke="#000" stroke-width="3"/>`;
  if (kind === "key") return `<circle cx="${cx-13}" cy="${cy}" r="10" fill="#fff" stroke="#000" stroke-width="3"/><path d="M${cx-3} ${cy}h30m-8 0v10m-8-10v8" stroke="#000" stroke-width="4"/>`;
  if (kind === "clock") return `<circle cx="${cx}" cy="${cy}" r="22" fill="#fff" stroke="#000" stroke-width="3"/><path d="M${cx} ${cy}v-13m0 13l12 7" stroke="#000" stroke-width="3"/>`;
  if (kind === "camera") return `<rect x="${cx-25}" y="${cy-16}" width="50" height="32" fill="#fff" stroke="#000" stroke-width="3"/><circle cx="${cx}" cy="${cy}" r="10" fill="url(#dots)" stroke="#000"/><path d="M${cx-12} ${cy-16}l5-8h14l5 8" fill="#fff" stroke="#000"/>`;
  return `<ellipse cx="${cx-10}" cy="${cy+10}" rx="17" ry="24" fill="url(#dots)" stroke="#000" stroke-width="3"/><path d="M${cx} ${cy-5}l25-45m-18 34l14 8" stroke="#000" stroke-width="5"/>`;
}

function personSvg(scene, x, index) {
  const [count, action,,, feature] = scene;
  return Array.from({length: count}, (_, personIndex) => {
    const px=x+38+personIndex*42, headY=action==="sitting"?105:78, bodyEnd=action==="sitting"?143:135;
    const legs=action==="walking"?`M${px} ${bodyEnd}l-20 35m20-35l22 23`:`M${px} ${bodyEnd}l-15 34m15-34l15 34`;
    const arms=action==="pointing"?`M${px} 108h38M${px} 108l-22 22`:`M${px} 108l-22 24m22-24l22 24`;
    const chair=action==="sitting"?`<path d="M${px-18} 138h38v25m-38-25v25" stroke="#000" stroke-width="3"/>`:"";
    const extra=feature==="hat"?`<path d="M${px-18} ${headY-12}h36m-30 0q12-18 24 0" fill="#fff" stroke="#000" stroke-width="3"/>`:feature==="glasses"?`<circle cx="${px-8}" cy="${headY}" r="6" fill="none" stroke="#000"/><circle cx="${px+8}" cy="${headY}" r="6" fill="none" stroke="#000"/><path d="M${px-2} ${headY}h4" stroke="#000"/>`:feature==="scarf"?`<path d="M${px-12} ${headY+19}h24m-3 0v28" stroke="#000" stroke-width="4"/>`:"";
    return `${chair}<circle cx="${px}" cy="${headY}" r="17" fill="#fff" stroke="#000" stroke-width="3"/>${extra}<path d="M${px} ${headY+17}v${bodyEnd-headY-17}${arms}${legs}" fill="none" stroke="#000" stroke-width="4"/>`;
  }).join("");
}

function sceneSvg(scene, panel) {
  const x=panel*178;
  const relation=scene[3];
  const positions={on:[x+140,82],under:[x+140,161],beside:[x+105,145],behind:[x+140,121]};
  const [ox,oy]=positions[relation];
  const behind=relation==="behind"?objectSvg(scene[2],ox,oy):"";
  const front=relation!=="behind"?objectSvg(scene[2],ox,oy):"";
  return `<g>${behind}<path d="M${x+105} 118h65m-58 0v48m51-48v48" stroke="#000" stroke-width="4"/>${front}${personSvg(scene,x,panel)}<text x="${x+89}" y="24" text-anchor="middle" font-family="sans-serif" font-size="20" font-weight="700">${labels[panel]}</text></g>`;
}

const sceneText = ([count,action,object,position,feature]) => `${count===1?"one person":`${count} people`} ${action}; a ${object} is ${position} the table; visible feature: ${feature}`;
const assets=boards.map((board,index)=>{
  const id=`ENG_R4_FIG_47_${String(index+1).padStart(2,"0")}`;
  const details=board.map((scene,i)=>`Picture ${labels[i]} shows ${sceneText(scene)}.`).join(" ");
  return {id,skillIds:["ENG_R4_S309","ENG_R4_S310","ENG_R4_S311","ENG_R4_S312","ENG_R4_S313"],type:"figure",path:`英文會考作戰室/r4/runtime/assets/${id}.svg`,content:`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 712 200" role="img" aria-labelledby="title desc"><title id="title">Four listening-picture choices, board ${index+1}</title><desc id="desc">${details}</desc><defs><pattern id="dots" width="7" height="7" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1.1" fill="#000"/></pattern></defs><rect x="2" y="2" width="708" height="196" fill="#fff" stroke="#000" stroke-width="3"/>${board.map(sceneSvg).join("")}<path d="M178 2v196M356 2v196M534 2v196" stroke="#000" stroke-width="2"/></svg>`,caption:`聽力選圖第 ${index+1} 組`,altText:`四格黑白線圖 A 至 D，每格以人物數量、動作、物件位置與帽子等特徵區分。${details}`,longDescription:`本圖不依賴顏色。${details} 桌面、桌下、桌旁與桌後以相對位置和遮擋表現；所有人物與物件也可由下方資料表完整辨認。`,dataFallback:{summary:details,columns:["選圖","人物與動作","物件位置","可見特徵"],rows:board.map((scene,i)=>[`Picture ${labels[i]}`,`${scene[0]} people; ${scene[1]}`,`${scene[2]}; ${scene[3]} the table`,scene[4]])},technical:{drawingMode:"schematic",labels:["A","B","C","D"]}};
});

function pictureCase(boardNumber, stem, answerIndex, why) {
  const board=boards[boardNumber-1];
  return [stem,`Picture ${labels[answerIndex]}`,why,labels.map((label,i)=>[i,label]).filter(([i])=>i!==answerIndex).map(([i,label])=>[`Picture ${label}`,`圖 ${label} 顯示 ${sceneText(board[i])}，不符合所聽條件。`]),[`ENG_R4_FIG_47_${String(boardNumber).padStart(2,"0")}`]];
}
const pq=(cases,meta)=>questions(cases.map((value,index)=>pictureCase(index+1,...value)),meta);

const skills=[
  {id:"ENG_R4_S309",process:"match-heard-noun-to-picture",evidence:"語句中的關鍵名詞與圖中物件形狀唯一對應",objectives:["先抓人物與核心物件名詞。","由名詞排除不同物件圖。","再用其餘語意確認唯一圖。"],sections:[["名詞先行","聽到 camera、umbrella 等內容詞先在四圖找物件，不因人物衣著分心。"],["同義名稱","bag 可能畫成有把手的袋子；用整體形狀與語境辨認。"],["人物與物件都核對","若兩圖都有 ball，再用 man/woman 或動作排除。"],["不從選項反猜","先形成聽到的畫面，再看 A–D。"]],examples:[["She points to the umbrella.",["抓 umbrella。","找傘形。","核對 points。"],"umbrella picture","名詞先縮小。"],["They see a camera.",["they 表多人。","camera 為相機。","兩線索交集。"],"multi-person camera scene","不可只看人數。"],["The key is on the table.",["抓 key。","辨認鑰匙。","核對 on。"],"key-on-table scene","名詞與位置共同確認。"]],misconceptions:[["只聽到人物就選。","多圖可能同人數。","抓核心物件。"],["以圖中最大物件作答。","大小是版面。","依聽到名詞。"],["不熟名詞時猜動作。","會失去核心區別。","用字音與其他線索交集。"],["看到熟悉物件就停止。","可能位置不合。","再核對完整句。"]],checks:[["第一優先抓哪類詞？","核心人物與物件名詞","快速定位。"],["同物件兩圖怎麼辦？","再看動作位置","形成交集。"],["可依物件大小猜嗎？","不可","大小非語意。"]],questions:pq([
    ["You hear: The person is pointing toward an umbrella.",3,"圖 D 的核心物件是 umbrella。"],["You hear: One person is walking near a kite.",2,"圖 C 顯示單人與 kite。"],["You hear: Two people are pointing toward a camera.",2,"圖 C 有兩人並出現 camera。"],["You hear: The walking person has an umbrella nearby.",2,"圖 C 的物件是 umbrella。"],["You hear: Two people are walking near a cup.",0,"圖 A 有兩人與 cup。"],["You hear: The seated person is near a camera.",0,"圖 A 是 seated person 與 camera。"],["You hear: A seated person has a box behind the table.",2,"圖 C 的核心物件是 box。"],["You hear: The walking person is beside a cup.",1,"圖 B 有 walking person 與 cup。"],["You hear: Two people point toward a clock.",2,"圖 C 顯示兩人與 clock。"],["You hear: The seated person has an umbrella on the table.",0,"圖 A 是 umbrella-on-table。"],["You hear: One person points toward a bag.",0,"圖 A 顯示 bag。"],["You hear: A standing person is near a camera.",3,"圖 D 的物件是 camera。"]
  ],{type:"listening-picture-noun",operation:"match-key-noun-then-confirm-scene",misconception:"choose-by-salient-picture-detail"})},
  {id:"ENG_R4_S310",process:"distinguish-heard-action-state",evidence:"be 動詞加 V-ing 與動作詞對應圖中坐、走、站或指向的進行狀態",objectives:["辨認動作核心。","區分相似人物的不同進行狀態。","用 be + V-ing 核對正在發生的動作。"],sections:[["先抓動詞重音","walking、sitting、pointing、standing 是選圖關鍵。"],["進行狀態不是習慣","is walking 表當下畫面，不等於每天走路。"],["姿勢要完整","彎腿坐椅是 sitting；直立不移動是 standing。"],["物件是第二線索","動作相同時再用物件確認。"]],examples:[["They are walking.",["抓 are。","walking 進行。","找多人步行。"],"walking picture","人數再確認。"],["He is pointing.",["pointing 非 holding。","看伸臂方向。","排 standing。"],"pointing picture","動作形狀不同。"],["She is sitting.",["找座椅與彎腿。","排站立。","再核物件。"],"seated picture","姿勢是核心。"]],misconceptions:[["人物直立都算 walking。","walking 有步態。","看腿部方向。"],["看到手臂就算 pointing。","站立也可能伸手。","看明確水平指向。"],["is walking 當未來。","此處描述畫面。","依現在進行。"],["只用物件不聽動作。","會選到錯姿勢。","動作先行。"]],checks:[["is sitting 描述何時？","當下進行狀態","對應畫面。"],["standing 與 walking 差在哪？","是否有移動步態","看腿姿。"],["動作相同再看什麼？","人物物件等第二線索","排除。"]],questions:pq([
    ["You hear: Two people wearing scarves are walking beside a box.",1,"圖 B 顯示兩人 walking、scarf 與 box。"],["You hear: The person in a hat is pointing while a bag is under the table.",1,"圖 B 顯示戴帽者 pointing，bag 在桌下。"],["You hear: One person is sitting.",1,"圖 B 是單人 sitting。"],["You hear: The person with glasses is pointing.",0,"圖 A 的 glasses 人物正在 pointing。"],["You hear: The person with a hat is sitting.",3,"圖 D 顯示戴帽者 sitting。"],["You hear: One person is walking.",1,"圖 B 是單人 walking。"],["You hear: Two people are walking near a ball beside the table.",3,"圖 D 顯示兩人 walking 且 ball 在桌旁。"],["You hear: The person without a visible feature is walking.",1,"圖 B 的 none-feature 人物 walking。"],["You hear: The person with a scarf is sitting.",1,"圖 B 顯示 scarf 與 sitting。"],["You hear: The person in a hat points toward a box beside the table.",3,"圖 D 的 hat 人物 pointing，box 在桌旁。"],["You hear: Two people wearing scarves walk while a bottle is on the table.",3,"圖 D 顯示兩人 walking、scarf 與桌上 bottle。"],["You hear: One person is pointing.",2,"圖 C 是單人 pointing。"]
  ],{type:"listening-picture-action",operation:"match-progressive-action-and-feature",misconception:"choose-person-with-correct-object-but-wrong-action"})},
  {id:"ENG_R4_S311",process:"match-heard-spatial-relation",evidence:"on、under、beside、behind 與圖中桌面和物件的相對位置唯一對應",objectives:["辨認位置介系詞。","固定參照物再找目標物。","以遮擋與上下關係排除相似圖。"],sections:[["先定目標與參照","The ball is under the table 中 ball 是目標，table 是參照。不可反讀。"],["四種關係","on 有接觸桌面；under 在桌面下；beside 在側邊；behind 由桌子部分遮擋。"],["不要靠左右猜","題目未說 left/right 就不使用方向。只核對指定介系詞。"],["完整句回填","選完讀成 The key is on the table，確認物件與關係都合。"]],examples:[["The book is on the table.",["目標 book。","參照 table。","on 為桌面接觸。"],"book-on-table","三項對齊。"],["A ball is under the table.",["抓 ball。","找桌下。","排 beside。"],"ball-under-table","相對位置明確。"],["The bag is behind the table.",["behind 會部分遮擋。","核對 bag。","不當 under。"],"bag-behind-table","遮擋提供深度。"]],misconceptions:[["把目標與參照反讀。","會成 table under ball。","先圈兩名詞。"],["beside 當 behind。","側邊與遮擋不同。","看輪廓是否被桌遮。"],["on 只表示上方。","通常需接觸表面。","核對接觸。"],["未聽左右仍用左右作答。","加入未說條件。","只用聽到關係。"]],checks:[["位置句先找什麼？","目標物與參照物","固定角色。"],["behind 常有何視覺線索？","部分遮擋","與 beside 區分。"],["on 與 above 相同嗎？","不完全相同","on 通常接觸。"]],questions:pq([
    ["You hear: The ball is under the table.",0,"圖 A 的 ball 在桌下。"],["You hear: The bag is under the table.",1,"圖 B 的 bag 位於桌下。"],["You hear: The camera is on the table.",2,"圖 C 的 camera 在桌面。"],["You hear: The box is behind the table.",0,"圖 A 的 box 被桌子部分遮擋。"],["You hear: The bag is beside the table.",2,"圖 C 的 bag 在桌旁。"],["You hear: The clock is under the table.",3,"圖 D 的 clock 在桌下。"],["You hear: The umbrella is on the table.",1,"圖 B 的 umbrella 在桌面。"],["You hear: The bottle is under the table.",2,"圖 C 的 bottle 在桌下。"],["You hear: The key is on the table.",3,"圖 D 的 key 在桌面。"],["You hear: The ball is behind the table.",2,"圖 C 的 ball 在桌後。"],["You hear: The cup is behind the table.",2,"圖 C 的 cup 在桌後。"],["You hear: The guitar is under the table.",2,"圖 C 的 guitar 在桌下。"]
  ],{type:"listening-picture-position",operation:"bind-object-preposition-and-reference",misconception:"reverse-object-reference-relation"})},
  {id:"ENG_R4_S312",process:"filter-picture-by-count-and-feature",evidence:"人物數量與帽子、眼鏡、圍巾等可見特徵同時符合語句",objectives:["聽清單複數與數量詞。","辨認帽子眼鏡圍巾等特徵。","用數量與特徵交集排除。"],sections:[["單複數是硬條件","person/he 表一人，people/they 表多人。圖中兩人不可回答 one person。"],["特徵不是身份","hat、glasses、scarf 只描述可見外觀，不推職業或性格。"],["兩條件都要","two people with a scarf 需人數二且特徵 scarf。只符合其一仍錯。"],["沒有特徵不等於否定人物","without a hat 只排帽子，不代表沒有其他特徵。"]],examples:[["Two people wear scarves.",["two 複數。","找 scarf。","交集。"],"two-scarf picture","缺一不可。"],["The person has glasses.",["一人。","glasses 眼部雙圈。","不猜身份。"],"one-glasses picture","外觀描述。"],["A person without a hat",["一人。","排 hat。","其他特徵可有。"],"non-hat picture","否定範圍有限。"]],misconceptions:[["忽略 -s 與 people。","會選錯人數。","先記單複數。"],["戴帽就推成 worker。","圖未給職業。","只回答特徵。"],["符合人數就停止。","可能特徵錯。","再核第二條件。"],["without hat 等於無任何特徵。","否定只修飾 hat。","保留 glasses/scarf 可能。"]],checks:[["they 通常對應幾人？","兩人以上","複數。"],["戴眼鏡可推職業嗎？","不可","只支持外觀。"],["two with hats 需核幾條？","人數與帽子兩條","取交集。"]],questions:pq([
    ["You hear: Two people wearing scarves walk beside a box.",1,"圖 B 有兩人、scarf、walking 與 box。"],["You hear: One person wears a hat.",1,"圖 B 為單人戴帽。"],["You hear: Two people have no marked accessory.",2,"圖 C 有兩人且 feature 為 none。"],["You hear: Two people in hats stand near a ball on the table.",1,"圖 B 有兩人、hat、standing 與桌上 ball。"],["You hear: Two people wear scarves.",0,"圖 A 有兩人與 scarf。"],["You hear: Two people in scarves stand beside a key.",2,"圖 C 有兩人、scarf、standing 與 key。"],["You hear: One person sits and wears a hat.",2,"圖 C 單人 sitting 且 hat。"],["You hear: Two people in hats point toward a kite.",0,"圖 A 有兩人、hat、pointing 與 kite。"],["You hear: Two people wear glasses.",2,"圖 C 有兩人與 glasses。"],["You hear: Two people have no visible accessory.",1,"圖 B 有兩人且 none。"],["You hear: Two people wearing scarves walk near a bottle.",3,"圖 D 有兩人、scarf、walking 與 bottle。"],["You hear: Two seated people wear glasses.",0,"圖 A 有兩人 sitting 且 glasses。"]
  ],{type:"listening-picture-count-feature",operation:"intersect-number-action-and-visible-feature",misconception:"satisfy-count-but-ignore-feature"})},
  {id:"ENG_R4_S313",process:"interpret-negation-and-comparison-in-picture",evidence:"not、without、more than 等語意運算套入圖中動作、特徵或數量後排除反向選項",objectives:["辨認否定作用範圍。","處理比較語意與數量方向。","避免聽到關鍵詞卻選其正向圖。"],sections:[["先標否定詞","not walking 需找非 walking，不是看到 walking 就選。把否定寫在動作上。"],["without 只否定後項","without a hat 可有 scarf 或 glasses；不可把整個人物刪掉。"],["比較先找兩端","more people than one 表至少兩人；taller/shorter 需有明確比較圖才使用。"],["反向檢查","選後問：若拿掉 not，會選哪張？目前答案應不是那張。"]],examples:[["The person is not sitting.",["not 修飾 sitting。","排 seated。","其他姿勢皆可能，再用線索。"],"non-sitting picture","避免關鍵詞陷阱。"],["Two people, not one",["比較 two vs one。","選多人。","不看物件。"],"two-person picture","數量方向明確。"],["A walker without glasses",["walker 為正向。","without 否定 glasses。","交集。"],"walking non-glasses picture","否定範圍有限。"]],misconceptions:[["聽到 walking 就選 walking，忽略 not。","會選反。","先處理否定。"],["without hat 等於沒有任何人。","否定範圍錯。","只排 hat。"],["more than one 當 one。","比較方向反。","改寫 two or more。"],["否定後所有其他圖都正確。","仍需其他線索唯一化。","取完整交集。"]],checks:[["not sitting 應先排哪圖？","坐著的圖","否定修飾 sitting。"],["more than one 至少幾人？","兩人","大於一。"],["without glasses 可戴帽嗎？","可以","否定只限 glasses。"]],questions:pq([
    ["You hear: Choose the picture with more than one person who is not sitting.",1,"圖 B 有兩人 walking，符合多人且非坐。"],["You hear: The person in a hat is not standing.",1,"圖 B 戴帽者 pointing，並非 standing。"],["You hear: More than one person is pointing, not sitting.",2,"圖 C 有兩人 pointing。"],["You hear: The person with glasses is not sitting and points near a box.",0,"圖 A 有 glasses、pointing 與 box。"],["You hear: The person in a hat is not walking.",3,"圖 D 戴帽且 sitting。"],["You hear: The person with glasses is not standing.",1,"圖 B 有 glasses 且 walking。"],["You hear: The two people are not standing still.",3,"圖 D 兩人 walking。"],["You hear: The person with a scarf is not sitting.",2,"圖 C 有 scarf 且 standing。"],["You hear: More than one person is not walking.",2,"圖 C 兩人 pointing。"],["You hear: The person in a hat is not sitting.",3,"圖 D 戴帽且 pointing。"],["You hear: The person with glasses is not sitting and stands beside a kite.",1,"圖 B 有 glasses、standing 與 kite。"],["You hear: More than one person is sitting, not walking.",0,"圖 A 兩人 sitting。"]
  ],{type:"listening-picture-negation",operation:"apply-negation-and-quantity-before-matching",misconception:"select-picture-containing-negated-keyword"})},
  {id:"ENG_R4_S314",process:"infer-focus-from-prosody",evidence:"句子重音標出對比焦點，升降調顯示確認、未完或陳述完成等語用功能",objectives:["由對比重音找被修正資訊。","區分升調確認與降調陳述。","以語境解釋語調而非只看標點。"],sections:[["重音回答隱含對比","I wanted the BLUE bag 強調 color，暗含 not another color。"],["重音位置改焦點","I borrowed it 強調 I 是人物修正；borrowed 強調動作；it 強調物件。"],["升調常保留確認","一般 yes/no 問句升調表示等待答案；降調較像完整陳述。"],["語調不是情緒唯一證據","同一升調可表示確認或驚訝，仍需結合字句與情境。"]],examples:[["I said TUESDAY.",["重音 Tuesday。","對比其他日。","不是人物修正。"],"not another day","焦點為時間。"],["SHE called me.",["重音 she。","修正 caller。","動作不變。"],"she, not someone else","主詞焦點。"],["You're ready? rising",["yes/no。","升調。","等待確認。"],"genuine confirmation","非完成陳述。"]],misconceptions:[["重音只是說得更大聲，無語意。","它常標對比。","問被修正哪項。"],["任何升調都表示開心。","功能依句型情境。","先判確認。"],["標點完全決定語調。","實際聲音可改語用。","結合聽覺。"],["整句每字都同等焦點。","突出詞承擔對比。","定位核重音。"]],checks:[["BLUE 重音通常對比什麼？","其他顏色或選項","焦點在顏色。"],["主詞重音修正什麼？","誰做動作","人物焦點。"],["yes/no 升調常表示？","等待確認","語句未封閉。"]],questions:questions([
    ["You hear strong stress on BLUE in 'I wanted the BLUE bag.' What is being corrected?","the color of the bag","BLUE 重音對比其他顏色。",[["who wanted it","主詞未重讀。"],["whether it was a bag","bag 未成焦點。"],["when it was wanted","未提時間。"]]],
    ["You hear: 'I called the office,' with stress on I. What does the speaker emphasize?","the speaker, not another person, made the call","I 重音修正施事者。",[["the office was closed","未提。"],["the call happened tomorrow","未提。"],["calling was impossible","相反。"]]],
    ["In 'She BOUGHT the book,' BOUGHT is stressed. Which contrast is most likely?","She bought it rather than borrowed it.","動詞重音對比取得方式。",[["She, not he, got it.","需主詞重音。"],["It was a book, not a pen.","需 book 重音。"],["It happened on Monday.","未提時間。"]]],
    ["A yes-or-no question ends with a clear rise: 'Are you ready?' What does the rise usually signal?","The speaker is waiting for confirmation.","升調保留問題並等待回答。",[["The speaker has finished a firm statement.","較像降調。"],["The speaker is reading a list item only.","無清單情境。"],["The word ready is negated.","語調不加否定。"]]],
    ["You hear a falling tone at the end of 'Where did you put it?' What is most likely?","The question is presented as complete.","wh 問句降調常表示完整提問。",[["The speaker has not started the question.","相反。"],["The speaker changed where into when.","語調不改詞。"],["The sentence means no one put anything.","未加否定。"]]],
    ["You hear: 'We need it TODAY,' with stress on TODAY. What is contrasted?","today versus another time","時間詞重音形成時段對比。",[["we versus they","主詞未重讀。"],["need versus want","動詞未重讀。"],["it versus them","受詞未重讀。"]]],
    ["You hear: 'I didn't SAY he left,' with stress on SAY. Which meaning is suggested?","The speaker may have communicated it in another way.","SAY 重音否定說這個動作，不必否定整個訊息。",[["The speaker certainly said it.","與 didn't 相反。"],["He certainly never left.","否定範圍不是 left。"],["No communication happened in any form.","強度過度。"]]],
    ["The speaker says 'Really?' with a rising tone after surprising news. What is the likely function?","asking for confirmation","升調 Really? 在驚訝情境請求確認。",[["ending a formal speech","不合短問句。"],["giving a command","沒有命令。"],["changing the news to a schedule","未提。"]]],
    ["A tag question rises: 'You're coming, aren't you?' What does the rise imply?","The speaker genuinely wants an answer.","升調使 tag 保持詢問。",[["The speaker treats the answer as completely settled.","較偏降調。"],["The speaker orders the listener to leave.","內容相反。"],["The speaker cannot hear any words.","未提。"]]],
    ["You hear stress on DOOR in 'Close the DOOR, please.' What is the focus?","which thing should be closed","DOOR 重音修正受詞。",[["who should close it","未重讀主詞。"],["whether the action is polite","please 非核重音。"],["when the door was built","未提。"]]],
    ["You hear: 'She borrowed MY book,' with stress on MY. What contrast is strongest?","the owner of the book","MY 對比別人的書。",[["the action of borrowing","需 borrowed 重音。"],["the kind of object","需 book 重音。"],["the speaker's arrival time","未提。"]]],
    ["The speaker lists 'pens, paper, and folders' and uses a continuing rise on pens and paper, then a fall on folders. What does the final fall show?","the list is complete","前項延續升調、末項降調封閉清單。",[["folders begin a new question","未有問句。"],["pens are negated","語調不產生否定。"],["the speaker forgot every item","相反。"]]],
  ],{type:"listening-prosody",operation:"map-stress-or-intonation-to-focus-function",misconception:"ignore-focus-location-and-use-words-only"})},
];

export const ENGLISH_UNIT_SOURCE=defineEnglishUnit({unitId:"ENG_R4_U47",skills,assets,vocabularyPolicy:{capQuestionBasis:"appendix-5-table-1",additionalLearningTerms:["ball","certain","command","complete","continue","emphasize","final","focus","form","formal","impossible","none","object","rather","scarf","scene","speech","suggest","toward"],contextualizedAboveRangeTerms:["accessory","arrival","communicated","communication","confirmation","contrast","contrasted","feature","firm","folders","function","genuine","genuinely","imply","multi","nearby","negated","non","scarves","schedule","settled","signal","statement","stress","stressed","tag","tone","versus","visible","vs","wh"],properNames:[],grammarNotation:["A","B","C","D","V-ing"],malformedDistractors:[]}});
