const UNIT_ID = "ENG_R4_U08";

function lecture(id, skillId, content) {
  return { id, skillId, ...content };
}

function question({
  id,
  skillId,
  difficulty,
  stem,
  options,
  answerIndex,
  reasons,
  reviews,
  cognitiveProcess,
  representationType = "sentence-cloze",
  misconceptionTargets = [],
}) {
  return {
    id,
    skillId,
    stem,
    options,
    answerIndex,
    reasons,
    difficulty,
    cognitiveProcess,
    representationType,
    misconceptionTargets,
    reviews,
  };
}

export const ENGLISH_U08_LECTURES = [
  lecture("ENG_R4_L_S050", "ENG_R4_S050", {
    objectives: [
      "能從語意與時間線索判斷習慣、規律與普遍事實，並使用現在簡單式表達。",
      "能分辨現在簡單式、現在進行式與過去簡單式所表示的時間觀點。",
    ],
    sections: [
      {
        id: "ENG_R4_L_S050_SEC_01",
        title: "先看句子在說哪一種時間",
        content: "現在簡單式不是只表示『現在這一秒』。它主要說明反覆發生的習慣、固定規律、長期狀態或普遍事實，例如 I walk to school every day. 句中的 every day 告訴我們這是重複的行動。開始判斷前，先問：這件事只發生一次，還是平常如此？",
      },
      {
        id: "ENG_R4_L_S050_SEC_02",
        title: "習慣、事實與固定時刻",
        content: "習慣常和 usually、often、every week 等詞一起出現；普遍事實不一定有時間詞，例如 A week has seven days. 時刻表或固定行程也可用現在簡單式，例如 The train leaves at six. 這種句子雖可能指未來，重點仍是已排定的固定時間。",
      },
      {
        id: "ENG_R4_L_S050_SEC_03",
        title: "肯定句的基本結構",
        content: "肯定句以主詞加動詞為核心。I、you、we、they 和複數主詞使用原形動詞；he、she、it 或單數的人事物，動詞通常要加 -s 或 -es。第三人稱單數的拼字規則會在下一技能細分，本技能先把『句意要不要用現在簡單式』判斷正確。",
      },
      {
        id: "ENG_R4_L_S050_SEC_04",
        title: "不要只靠一個關鍵字",
        content: "時間詞是線索，不是機械答案。Today 有時表示今天的固定安排，也可能表示此刻的臨時情況；always 也可能出現在進行式中表達抱怨。會考題應把整句語意、動作是否反覆、其他動詞形式一起看，不能看到單一字就直接選時態。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S050_EX_01",
        prompt: "Every morning, Leo ___ his dog before breakfast. (walk / walks / is walking)",
        steps: ["Every morning 表示每天重複的習慣。", "主詞 Leo 是第三人稱單數。", "現在簡單式的動詞使用 walks。"],
        answer: "walks",
        why: "句子描述 Leo 每天早上的固定習慣，不是只描述此刻，因此用現在簡單式。Leo 是單數第三人稱，walk 必須加 -s，答案是 walks。",
      },
      {
        id: "ENG_R4_L_S050_EX_02",
        prompt: "Ice ___ into water when it gets warm. (turns / turned / is turning)",
        steps: ["句子說明一般情況，沒有指特定一次事件。", "主詞 Ice 視為單數。", "一般事實使用現在簡單式 turns。"],
        answer: "turns",
        why: "這句在說冰受熱會變成水的一般現象，並未限定昨天或正在觀察的某一塊冰。Ice 是單數主詞，所以正確形式為 turns。",
      },
      {
        id: "ENG_R4_L_S050_EX_03",
        prompt: "The last bus ___ at 10:30 tonight. (leaves / left / is leave)",
        steps: ["今晚雖是未來時間，但句子談的是固定班次。", "時刻表可用現在簡單式。", "單數主詞 bus 搭配 leaves。"],
        answer: "leaves",
        why: "班車時間屬於已排定的時刻表，因此即使有 tonight，仍可用現在簡單式。Left 會變成已發生的過去事件，is leave 則不是合法的動詞結構。",
      },
    ],
    misconceptions: [
      {
        belief: "現在簡單式只能描述說話當下。",
        whyWrong: "它主要表達習慣、規律、長期狀態與普遍事實；當下正在進行的動作通常用現在進行式。",
        correction: "先判斷事件是反覆、固定還是正在發生，再決定時態。",
      },
      {
        belief: "句中沒有 every day 就不能用現在簡單式。",
        whyWrong: "普遍事實與長期狀態常不帶明顯時間副詞，例如 Birds have wings.",
        correction: "時間詞只是線索，句子的時間意義才是主要依據。",
      },
      {
        belief: "看到 tonight 一定要使用 will。",
        whyWrong: "固定時刻表即使指未來，也常用現在簡單式表達。",
        correction: "確認句子是在說個人預測，還是已排定的班次與行程。",
      },
      {
        belief: "只要主詞是人，現在式動詞都使用原形。",
        whyWrong: "he、she 或單數姓名屬第三人稱單數，肯定句動詞通常要變化。",
        correction: "先找主詞的人稱與單複數，再選動詞形式。",
      },
    ],
    checks: [
      {
        prompt: "My parents cook at home on weekdays. 這句表達習慣還是此刻動作？",
        answer: "習慣",
        reason: "on weekdays 表示每逢平日都會發生的規律。",
      },
      {
        prompt: "The library opens at nine tomorrow. 為何可用 opens？",
        answer: "因為是固定開館時間",
        reason: "時刻表與固定安排可用現在簡單式表達。",
      },
      {
        prompt: "Look! The baby cries. 是否適合只描述此刻？",
        answer: "不適合，應改為 is crying",
        reason: "Look 指向正在發生的動作，應使用現在進行式。",
      },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S051", "ENG_R4_S051", {
    objectives: [
      "能找出現在簡單式肯定句的真正主詞，判斷是否為第三人稱單數。",
      "能依動詞字尾規則正確形成 -s、-es、-ies 及常見不規則形式。",
    ],
    sections: [
      {
        id: "ENG_R4_L_S051_SEC_01",
        title: "第三人稱單數是誰",
        content: "說話者 I 是第一人稱，聽話者 you 是第二人稱；談到的 he、she、it、單數姓名或單一事物，才是第三人稱單數。The boy、my mother、this machine 都屬這一類。主詞若由 and 連接兩人，通常已是複數，不再加第三人稱單數字尾。",
      },
      {
        id: "ENG_R4_L_S051_SEC_02",
        title: "大多數動詞直接加 -s",
        content: "play 變 plays，read 變 reads，help 變 helps。字尾變化寫在動詞上，不寫在主詞上。句中即使主詞和動詞之間插入其他文字，也要回頭找真正主詞，例如 The girl with two cats lives here. 真正主詞是單數 girl。",
      },
      {
        id: "ENG_R4_L_S051_SEC_03",
        title: "-es、-ies 與常見特殊形式",
        content: "動詞以 -s、-sh、-ch、-x 或 -o 結尾時，通常加 -es，如 watches、washes、goes。子音字母加 y 結尾時，先把 y 改成 i 再加 -es，如 studies；母音字母加 y 則直接加 -s，如 plays。have 的第三人稱單數是 has。",
      },
      {
        id: "ENG_R4_L_S051_SEC_04",
        title: "變化只出現在肯定句主要動詞",
        content: "本技能處理現在簡單式肯定句。若句中已有 does 或 does not，後面的主要動詞要回到原形；這是因為第三人稱的資訊已由 does 承擔。be 動詞則使用 is，不套用一般動詞的 -s 規則。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S051_EX_01",
        prompt: "Mia ___ English after dinner. (study / studies / studys)",
        steps: ["Mia 是第三人稱單數。", "study 以子音字母加 y 結尾。", "y 改成 i，再加 -es。"],
        answer: "studies",
        why: "主詞 Mia 是單數第三人稱；study 的 y 前是子音字母 d，因此不能寫 studys。依規則改 y 為 i 再加 -es，得到 studies。",
      },
      {
        id: "ENG_R4_L_S051_EX_02",
        prompt: "My uncle ___ the dishes every night. (wash / washes / washies)",
        steps: ["My uncle 是單數主詞。", "wash 以 -sh 結尾。", "動詞加 -es。"],
        answer: "washes",
        why: "wash 的字尾是 -sh，第三人稱單數要加 -es，所以使用 washes。Washies 並不是 wash 的現在式拼法，wash 則漏掉了主詞要求的變化。",
      },
      {
        id: "ENG_R4_L_S051_EX_03",
        prompt: "The student with two bags ___ a red bike. (have / has / haves)",
        steps: ["介系詞片語 with two bags 不改變主詞。", "真正主詞 student 是單數。", "have 的特殊形式是 has。"],
        answer: "has",
        why: "two bags 雖然是複數，卻位在 with 片語中；句子的主詞仍是單數 student。Have 的第三人稱單數不是 haves，而是不規則形式 has。",
      },
    ],
    misconceptions: [
      {
        belief: "只要句中出現複數名詞，動詞就使用原形。",
        whyWrong: "複數名詞可能只是介系詞片語的一部分，不一定是主詞。",
        correction: "先找出誰執行動作，再判斷主詞單複數。",
      },
      {
        belief: "所有 y 結尾的動詞都改成 -ies。",
        whyWrong: "play 的 y 前是母音字母，因此第三人稱單數是 plays。",
        correction: "檢查 y 前一個字母是母音還是子音。",
      },
      {
        belief: "have 加 -s 就寫成 haves。",
        whyWrong: "have 的第三人稱單數是特殊形式 has。",
        correction: "把 has 視為需要單獨記住的常見形式。",
      },
      {
        belief: "does 後面的動詞仍要加 -s。",
        whyWrong: "does 已經標示第三人稱單數，再加 -s 會重複標記。",
        correction: "does 或 doesn't 後一律接原形動詞。",
      },
    ],
    checks: [
      {
        prompt: "The bus pass / passes my house at seven. 應選哪一個？",
        answer: "passes",
        reason: "bus 是單數，pass 以 -s 結尾，所以加 -es。",
      },
      {
        prompt: "Jay and Ann cooks dinner. 哪裡有錯？",
        answer: "cooks 應改為 cook",
        reason: "Jay and Ann 是由 and 連接的複數主詞。",
      },
      {
        prompt: "My sister plays volleyball. 為何不是 plaies？",
        answer: "play 的 y 前是母音字母 a",
        reason: "母音字母加 y 結尾時直接加 -s。",
      },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S052", "ENG_R4_S052", {
    objectives: [
      "能依主詞選用 do 或 does，形成現在簡單式一般動詞的問句。",
      "能維持助動詞、主詞與原形動詞的正確語序。",
    ],
    sections: [
      {
        id: "ENG_R4_L_S052_SEC_01",
        title: "一般動詞問句需要 do 或 does",
        content: "現在簡單式的一般動詞肯定句若要改成 yes-no 問句，要把 do 或 does 放到主詞前面。I、you、we、they 與複數主詞用 do；he、she、it 與單數主詞用 does。Do they live here? 和 Does Ben live here? 都保留主要動詞原形。",
      },
      {
        id: "ENG_R4_L_S052_SEC_02",
        title: "does 後面不再加 -s",
        content: "肯定句 Ben lives here. 中，第三人稱單數資訊在 lives 的 -s。改成問句後，這項資訊移到 does，所以主要動詞回到 live。Does Ben lives here? 會重複標記，是常見錯誤。",
      },
      {
        id: "ENG_R4_L_S052_SEC_03",
        title: "問句語序要完整",
        content: "基本順序是 Do/Does + 主詞 + 原形動詞 + 其他資訊？若前面有疑問詞，順序是疑問詞 + do/does + 主詞 + 原形動詞。不能把主詞放在助動詞前，也不能漏掉主要動詞。",
      },
      {
        id: "ENG_R4_L_S052_SEC_04",
        title: "be 動詞與情態助動詞不用 do",
        content: "Is your sister at home? 直接把 be 動詞移到主詞前；Can she swim? 也直接把 can 放前面。Do/does 是一般動詞現在式問句的工具，不可與 is 或 can 隨意疊加。先辨認句中的動詞種類，才能選對問句結構。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S052_EX_01",
        prompt: "___ your parents work on Saturdays? (Do / Does / Are)",
        steps: ["主要動詞是 work。", "主詞 parents 是複數。", "一般動詞複數主詞問句使用 Do。"],
        answer: "Do",
        why: "work 是一般動詞，parents 是複數主詞，所以問句以 Do 開頭。Are 不能直接接原形 work，Does 則只配第三人稱單數主詞。",
      },
      {
        id: "ENG_R4_L_S052_EX_02",
        prompt: "Does the shop ___ at nine? (open / opens / opening)",
        steps: ["Does 已標示現在式與單數主詞。", "主要動詞使用原形。", "選擇 open。"],
        answer: "open",
        why: "問句中的 Does 已承擔第三人稱單數變化，後面的動詞必須用原形 open。Opens 會重複標記，opening 則缺少形成進行式所需的 be 動詞。",
      },
      {
        id: "ENG_R4_L_S052_EX_03",
        prompt: "Which question asks about Nina's usual lunch?",
        steps: ["題意要問固定習慣。", "Nina 是第三人稱單數。", "使用 Does + Nina + 原形動詞。"],
        answer: "What does Nina eat for lunch?",
        why: "要詢問 Nina 平常午餐吃什麼，疑問詞 What 後接 does，再放主詞 Nina 和原形動詞 eat。What Nina does eat 不是一般資訊問句的正常語序。",
      },
    ],
    misconceptions: [
      {
        belief: "第三人稱問句中的主要動詞也要加 -s。",
        whyWrong: "does 已經帶有第三人稱單數資訊，主要動詞再加 -s 會重複。",
        correction: "看到 does，立即檢查後方是否為原形動詞。",
      },
      {
        belief: "所有現在式問句都用 do 開頭。",
        whyWrong: "單數第三人稱一般動詞要用 does；be 動詞與 can 等助動詞又有自己的問句形式。",
        correction: "先辨認主詞與動詞種類，再決定問句開頭。",
      },
      {
        belief: "把問號加在肯定句後就形成問句。",
        whyWrong: "正式書面問句仍需要助動詞與主詞倒裝。",
        correction: "依 Do/Does + 主詞 + 原形動詞的順序重組。",
      },
      {
        belief: "疑問詞後面可以直接接第三人稱動詞。",
        whyWrong: "受詞資訊問句通常還需要 does 和主詞，例如 Where does he work?",
        correction: "找出疑問詞所問的資訊，再補完整助動詞與主詞。",
      },
    ],
    checks: [
      {
        prompt: "___ your brother play chess after school?",
        answer: "Does",
        reason: "brother 是第三人稱單數，主要動詞 play 是一般動詞。",
      },
      {
        prompt: "Does Amy likes tea? 應改哪一個字？",
        answer: "likes 改為 like",
        reason: "does 後的主要動詞要用原形。",
      },
      {
        prompt: "Do they are ready? 為何不對？",
        answer: "be 動詞問句不使用 do",
        reason: "應直接說 Are they ready?",
      },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S053", "ENG_R4_S053", {
    objectives: [
      "能依主詞選用 do not 或 does not，形成一般動詞現在式否定句。",
      "能在否定助動詞後使用原形動詞，並分辨一般動詞與 be 動詞否定。",
    ],
    sections: [
      {
        id: "ENG_R4_L_S053_SEC_01",
        title: "否定的是平常情況",
        content: "現在簡單式否定句表示某個習慣、事實或長期狀態不成立。I、you、we、they 與複數主詞使用 do not，縮寫為 don't；he、she、it 與單數主詞使用 does not，縮寫為 doesn't。",
      },
      {
        id: "ENG_R4_L_S053_SEC_02",
        title: "助動詞後接原形",
        content: "She walks to school. 改成否定句是 She doesn't walk to school. 第三人稱單數標記已移到 does，主要動詞 walk 必須回到原形。doesn't walks 同時標記兩次，不能接受。",
      },
      {
        id: "ENG_R4_L_S053_SEC_03",
        title: "be 動詞有自己的否定形式",
        content: "am、is、are 後直接加 not，例如 He isn't busy. 不寫 He doesn't be busy. 同樣地，can 等情態助動詞也直接加 not。判斷否定句前先圈出原句真正的動詞。",
      },
      {
        id: "ENG_R4_L_S053_SEC_04",
        title: "否定位置會改變句意",
        content: "not 應和 do/does 放在一起，位於主要動詞前。Everybody doesn't... 有時可能造成範圍解讀問題，初學時應優先使用清楚的主詞與否定結構。也要區分 never 與 don't ever，避免同一句出現不必要的雙重否定。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S053_EX_01",
        prompt: "Kevin ___ coffee in the evening. (doesn't drink / doesn't drinks / don't drink)",
        steps: ["Kevin 是第三人稱單數。", "否定助動詞使用 doesn't。", "doesn't 後接原形 drink。"],
        answer: "doesn't drink",
        why: "Kevin 是單數第三人稱，因此要用 doesn't；第三人稱變化已在 does 上，後面的 drink 保持原形。doesn't drinks 重複變化，don't drink 則與主詞不一致。",
      },
      {
        id: "ENG_R4_L_S053_EX_02",
        prompt: "We ___ extra paper today. (don't need / doesn't need / aren't need)",
        steps: ["need 是一般動詞。", "主詞 We 搭配 do not。", "選擇 don't need。"],
        answer: "don't need",
        why: "need 是一般動詞，We 要搭配 don't 形成現在式否定。doesn't 只配第三人稱單數；aren't 後也不能直接接原形 need。",
      },
      {
        id: "ENG_R4_L_S053_EX_03",
        prompt: "The museum isn't open on Mondays. 為何不用 doesn't？",
        steps: ["open 在此描述狀態。", "句中的動詞是 is。", "be 動詞後直接加 not。"],
        answer: "isn't open",
        why: "這裡 open 是形容詞，句子的動詞是 is，因此否定式直接變成 isn't。若寫 doesn't open，意思會轉成『博物館不開門』的動作結構，分析方式不同。",
      },
    ],
    misconceptions: [
      {
        belief: "doesn't 後的動詞仍維持第三人稱單數。",
        whyWrong: "第三人稱標記已經出現在 does，主要動詞必須使用原形。",
        correction: "把 doesn't walks 改為 doesn't walk。",
      },
      {
        belief: "單數名詞一律用 don't。",
        whyWrong: "現在簡單式一般動詞的單數第三人稱要搭配 doesn't。",
        correction: "將單數姓名或事物視為 he、she 或 it 來判斷。",
      },
      {
        belief: "be 動詞否定也要加入 doesn't。",
        whyWrong: "be 動詞可直接和 not 結合，不需要 do/does。",
        correction: "使用 isn't、aren't 或 am not。",
      },
      {
        belief: "never 前面還要加 don't 才表示否定。",
        whyWrong: "never 本身已含否定意義，don't never 會形成不標準的雙重否定。",
        correction: "使用 never 或 don't ever 其中一種清楚結構。",
      },
    ],
    checks: [
      {
        prompt: "My cat don't eat fish. 應改哪裡？",
        answer: "don't 改為 doesn't",
        reason: "cat 是單數第三人稱。",
      },
      {
        prompt: "Sara doesn't goes by bus. 應改哪裡？",
        answer: "goes 改為 go",
        reason: "doesn't 後接原形動詞。",
      },
      {
        prompt: "They don't tired after class. 為何不對？",
        answer: "應改為 They aren't tired",
        reason: "tired 前需要 be 動詞，不能以 don't 直接否定形容詞。",
      },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S054", "ENG_R4_S054", {
    objectives: [
      "能依問句中的 do 或 does，使用一致的肯定與否定簡短回答。",
      "能把問句中的名詞主詞轉成合宜代名詞，避免只回答 Yes 或 No 造成資訊不足。",
    ],
    sections: [
      {
        id: "ENG_R4_L_S054_SEC_01",
        title: "簡短回答要保留助動詞",
        content: "Do/Does 問句的標準簡短回答是 Yes, 主詞代名詞 + do/does. 或 No, 主詞代名詞 + don't/doesn't. 例如 Does Ken swim? 回答 Yes, he does. 只說 Yes 在口語可能聽得懂，但考題通常要求完整一致的形式。",
      },
      {
        id: "ENG_R4_L_S054_SEC_02",
        title: "名詞要換成合適代名詞",
        content: "問句主詞是 Linda，回答用 she；the dog 用 it；your parents 由回答者角度通常變成 they。若問 Do you...? 回答者談自己，要用 I。先確認誰在回答，才能正確轉換人稱。",
      },
      {
        id: "ENG_R4_L_S054_SEC_03",
        title: "肯定與否定必須符合事實",
        content: "語法正確不代表內容正確。若對話已說 Tom never cooks，問 Does Tom cook? 就應回答 No, he doesn't. 會考常把前文事實和簡答形式一起考，必須同時核對語意與助動詞。",
      },
      {
        id: "ENG_R4_L_S054_SEC_04",
        title: "不要在簡答中重複主要動詞",
        content: "標準簡答說 Yes, she does，不說 Yes, she does likes it. 若要提供完整資訊，可以另起完整句 She likes it. 簡短回答的功能是以助動詞代替前文的動作內容。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S054_EX_01",
        prompt: "Does your sister ride a bike? — Yes, ___.",
        steps: ["問句使用 does。", "your sister 在回答中用 she。", "肯定簡答為 she does。"],
        answer: "she does",
        why: "問句的主詞 your sister 是女性單數，回答時改用 she；原問句使用 does，肯定簡答也保留 does，因此是 Yes, she does.。",
      },
      {
        id: "ENG_R4_L_S054_EX_02",
        prompt: "Do the students need more time? — No, ___.",
        steps: ["students 是複數，代名詞為 they。", "問句助動詞是 do。", "否定簡答用 they don't。"],
        answer: "they don't",
        why: "the students 要換成複數代名詞 they，Do 問句的否定簡答用 don't。doesn't 只配第三人稱單數，不能和 they 搭配。",
      },
      {
        id: "ENG_R4_L_S054_EX_03",
        prompt: "A: I walk to work every day. B: Do you drive to work? A: ___",
        steps: ["第一句已說明走路上班。", "drive 與已知事實不符。", "回答者用 I，否定簡答為 I don't。"],
        answer: "No, I don't.",
        why: "A 已明確說自己每天走路上班，所以對 drive 的問題要否定。問句中的 you 從 A 的回答角度改成 I，形成 No, I don't.。",
      },
    ],
    misconceptions: [
      {
        belief: "Does 問句可以回答 Yes, she do。",
        whyWrong: "簡短回答的助動詞要和問句及主詞一致，she 應搭配 does。",
        correction: "保留問句中的 does，回答 Yes, she does。",
      },
      {
        belief: "問句中的 you 在回答時仍然寫 you。",
        whyWrong: "回答者是在談自己，所以通常要轉成 I 或 we。",
        correction: "先確認說話者角色，再轉換代名詞。",
      },
      {
        belief: "語法正確的 Yes 簡答一定能選。",
        whyWrong: "前文可能已提供否定事實，內容不符仍是錯誤答案。",
        correction: "同時核對對話資訊與簡答形式。",
      },
      {
        belief: "簡短回答要再寫一次主要動詞。",
        whyWrong: "do/does 已代替整個動作內容，重複主要動詞會破壞結構。",
        correction: "簡答停在 do、does、don't 或 doesn't。",
      },
    ],
    checks: [
      {
        prompt: "Do Mia and Jo live near here? — Yes, ___.",
        answer: "they do",
        reason: "兩人是複數，以 they 代替並保留 do。",
      },
      {
        prompt: "Does this key open the door? — No, ___.",
        answer: "it doesn't",
        reason: "this key 是單數事物，代名詞用 it。",
      },
      {
        prompt: "Do you read on the bus? 回答者若不讀，應如何回答？",
        answer: "No, I don't.",
        reason: "回答者把 you 轉成 I，並使用 do 的否定形式。",
      },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S055", "ENG_R4_S055", {
    objectives: [
      "能將 always、usually、often、sometimes、seldom、never 放在合宜的句中位置。",
      "能分辨一般動詞、be 動詞與助動詞結構中的頻率副詞位置。",
    ],
    sections: [
      {
        id: "ENG_R4_L_S055_SEC_01",
        title: "頻率副詞說明發生得多常",
        content: "always 表示總是，usually 表示通常，often 表示經常，sometimes 表示有時，seldom 表示很少，never 表示從不。它們不是精確次數，但能讓讀者知道習慣的頻繁程度。never 已含否定意義，不再和 don't 疊用。",
      },
      {
        id: "ENG_R4_L_S055_SEC_02",
        title: "一般動詞之前",
        content: "句中只有一般動詞時，頻率副詞通常放在主要動詞前：I usually eat breakfast.、She often walks home. 主詞和副詞之間不可任意插入 do，肯定句也不需要助動詞。",
      },
      {
        id: "ENG_R4_L_S055_SEC_03",
        title: "be 動詞之後",
        content: "若主要動詞是 am、is、are，頻率副詞通常放在 be 動詞後：He is always kind.、They are often busy. 不要照一般動詞規則寫成 He always is kind，除非特殊語氣需要強調；基礎考題以 be 後位置為準。",
      },
      {
        id: "ENG_R4_L_S055_SEC_04",
        title: "助動詞與較有彈性的位置",
        content: "有助動詞時，頻率副詞通常放在第一個助動詞後，例如 She can usually help. Sometimes 可放句首或一般動詞前；often 也可在某些語境移動。若選項有多個自然位置，題目必須提供足夠限制，不能把語感差異誤當唯一規則。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S055_EX_01",
        prompt: "Nora ___ checks her bag before leaving. (usually / is usually / checks usually)",
        steps: ["主要動詞是 checks。", "句中不需要 be 動詞。", "頻率副詞放在一般動詞前。"],
        answer: "usually",
        why: "checks 是一般動詞，usually 應放在它前面，形成 Nora usually checks...。is usually checks 同時放入 be 和變化動詞，無法構成正確時態。",
      },
      {
        id: "ENG_R4_L_S055_EX_02",
        prompt: "The park is ___ crowded on Sunday mornings. (often / never is / crowded often)",
        steps: ["句中的主要動詞是 is。", "頻率副詞放在 be 動詞後。", "is often crowded 的位置正確。"],
        answer: "often",
        why: "is 是 be 動詞，often 放在 is 後、形容詞 crowded 前最自然。選 often 可得到 The park is often crowded...，不需再加入另一個 is。",
      },
      {
        id: "ENG_R4_L_S055_EX_03",
        prompt: "Which sentence places usually correctly with can?",
        steps: ["can 是助動詞。", "頻率副詞通常放在助動詞後。", "主要動詞 help 維持原形。"],
        answer: "Sam can usually help after lunch.",
        why: "含 can 的句子通常把 usually 放在 can 與原形動詞 help 之間。Sam usually can help 雖可能出現在特定強調中，但基礎中性語序以 can usually help 為準。",
      },
    ],
    misconceptions: [
      {
        belief: "所有頻率副詞都只能放在句首。",
        whyWrong: "always、usually、often、never 等通常位在句中，位置要看動詞種類。",
        correction: "一般動詞前、be 動詞後，是最重要的基本對比。",
      },
      {
        belief: "be 動詞句也把副詞放在 be 前。",
        whyWrong: "中性語序通常是 is always、are often，而不是 always is。",
        correction: "看到 am、is、are，先把頻率副詞放到其後。",
      },
      {
        belief: "never 必須搭配 don't 才有否定意思。",
        whyWrong: "never 本身就表示零頻率，再加 don't 會造成雙重否定。",
        correction: "使用 I never eat... 或 I don't ever eat...，不要混在一起。",
      },
      {
        belief: "頻率副詞的位置永遠只有一種可能。",
        whyWrong: "sometimes 等副詞可有不同自然位置，語境和強調會影響排列。",
        correction: "考題若要求唯一答案，應依完整結構與其他選項判斷。",
      },
    ],
    checks: [
      {
        prompt: "I am late never. 應如何排列？",
        answer: "I am never late.",
        reason: "never 放在 be 動詞 am 後面。",
      },
      {
        prompt: "Leo often takes the train. often 為何在 takes 前？",
        answer: "takes 是一般動詞",
        reason: "頻率副詞通常放在一般動詞之前。",
      },
      {
        prompt: "She can always call me. always 位於哪兩個成分之間？",
        answer: "can 和 call 之間",
        reason: "有助動詞時，頻率副詞通常放在助動詞後。",
      },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S056", "ENG_R4_S056", {
    objectives: [
      "能由頻率、規律、事實與固定時刻等線索判斷現在簡單式。",
      "能在含有相反時間訊號時，以整句事件關係而非單一關鍵字決定時態。",
    ],
    sections: [
      {
        id: "ENG_R4_L_S056_SEC_01",
        title: "反覆時間詞",
        content: "every day、on weekends、once a month、usually、often 等常提示反覆發生的事情，因而常搭配現在簡單式。它們回答『多久一次』或『平常何時』，不是指出某一次正在進行的畫面。",
      },
      {
        id: "ENG_R4_L_S056_SEC_02",
        title: "沒有時間詞也可能是現在簡單式",
        content: "Birds build nests. 或 My aunt lives in Tainan. 都可表達一般事實或長期狀態，不需要 every day。相反地，right now、at the moment、look、listen 常把注意力拉到此刻，通常需要現在進行式。",
      },
      {
        id: "ENG_R4_L_S056_SEC_03",
        title: "過去與未來線索要分清楚",
        content: "yesterday、last night、two days ago 指向已結束的過去；tomorrow、next week 常指未來。不過固定時刻表可用現在簡單式談未來，例如 The class starts at eight tomorrow. 要先辨認事件是個人一次行動，還是制度化的安排。",
      },
      {
        id: "ENG_R4_L_S056_SEC_04",
        title: "同一句可以有兩種時態",
        content: "Grace usually walks to school, but today she is taking the bus. 前半句說平常習慣，後半句說今天的臨時改變。but、today、now 等線索需要和各自子句配對，不能讓一個時間詞支配整個句子。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S056_EX_01",
        prompt: "Dad ___ the plants twice a week. (waters / watered / is watering)",
        steps: ["twice a week 表示固定頻率。", "句子描述習慣。", "Dad 是單數，使用 waters。"],
        answer: "waters",
        why: "twice a week 清楚表示每週反覆兩次，不是某一次已完成或正在進行的動作。Dad 是單數第三人稱，所以選 waters。",
      },
      {
        id: "ENG_R4_L_S056_EX_02",
        prompt: "Listen! Someone ___ at the door. (knocks / is knocking / knocked)",
        steps: ["Listen 要求注意當下聲音。", "動作正在發生。", "使用現在進行式 is knocking。"],
        answer: "is knocking",
        why: "Listen! 把情境限定在說話當下，敲門聲正在發生，因此要用 is knocking。knocks 會表示規律，knocked 則表示已結束的過去。",
      },
      {
        id: "ENG_R4_L_S056_EX_03",
        prompt: "The art show ___ at noon next Saturday. (opens / opened / opening)",
        steps: ["next Saturday 是未來。", "展覽開幕時間是排定的活動時刻。", "固定行程可用現在簡單式 opens。"],
        answer: "opens",
        why: "雖然 next Saturday 指未來，句子談的是公告中已排定的開幕時刻，所以現在簡單式 opens 合理。opened 會表示過去，opening 缺少助動詞。",
      },
    ],
    misconceptions: [
      {
        belief: "看到 today 就一定使用現在進行式。",
        whyWrong: "today 可出現在固定安排或一般陳述中，仍要看動作是否正在發生。",
        correction: "把時間詞和它所屬的子句、事件類型一起判斷。",
      },
      {
        belief: "沒有頻率副詞就不能判定為現在簡單式。",
        whyWrong: "普遍事實與長期狀態通常可直接用現在簡單式。",
        correction: "問自己句子是否描述穩定、反覆或一般成立的情況。",
      },
      {
        belief: "tomorrow 前一定只能用 will。",
        whyWrong: "時刻表、課表和正式排程常以現在簡單式表達未來。",
        correction: "區分排定行程與臨時決定或預測。",
      },
      {
        belief: "一句話只能使用同一個時態。",
        whyWrong: "不同子句可以分別描述平常習慣與當下例外。",
        correction: "逐一找出每個動詞所對應的時間線索。",
      },
    ],
    checks: [
      {
        prompt: "once a year 通常提示哪一種時間觀點？",
        answer: "反覆發生的習慣或規律",
        reason: "它表示每年一次的固定頻率。",
      },
      {
        prompt: "right now 通常搭配哪一種時態？",
        answer: "現在進行式",
        reason: "它把動作限定在說話當下。",
      },
      {
        prompt: "The movie begins at 7:00 tomorrow. 為何 begins 合理？",
        answer: "電影時間是固定排程",
        reason: "正式時刻表可用現在簡單式表示未來。",
      },
    ],
    assets: [],
  }),
];

export const ENGLISH_U08_QUESTIONS = [
  question({
    id: "ENG_R4_Q_050_01",
    skillId: "ENG_R4_S050",
    difficulty: "foundation",
    stem: "Maya ___ to the library every Saturday.",
    options: ["is going", "goes", "went", "go"],
    answerIndex: 1,
    reasons: [
      "is going 表示一段正在進行的臨時動作，與 every Saturday 的固定習慣不合。",
      "goes 以現在簡單式表達每週六的習慣，並符合單數主詞 Maya。",
      "went 是過去式，句中沒有已結束的過去時間。",
      "go 未配合第三人稱單數主詞 Maya 變化。",
    ],
    reviews: [
      "every Saturday 表示反覆習慣，Maya 為第三人稱單數，因此推得 goes。",
      "逐一代入後，只有 goes 同時符合現在簡單式語意與主詞動詞一致。",
    ],
    cognitiveProcess: ["identify-recurring-time", "select-present-simple"],
    misconceptionTargets: ["present-simple-means-only-now"],
  }),
  question({
    id: "ENG_R4_Q_050_02",
    skillId: "ENG_R4_S050",
    difficulty: "foundation",
    stem: "The moon ___ around the earth.",
    options: ["move", "moved", "is move", "moves"],
    answerIndex: 3,
    reasons: [
      "move 沒有配合單數主詞 The moon 加 -s。",
      "moved 表示已結束的過去事件，不適合描述一般事實。",
      "is move 不是英文的現在式或進行式結構。",
      "moves 使用現在簡單式，正確表達一般成立的事實。",
    ],
    reviews: [
      "句子陳述一般事實，單數主詞 moon 要搭配現在式 moves。",
      "答案不靠時間副詞；由事實語意與主詞一致可唯一排除其餘三項。",
    ],
    cognitiveProcess: ["recognize-general-fact", "apply-subject-verb-agreement"],
    misconceptionTargets: ["time-word-required-for-present-simple"],
  }),
  question({
    id: "ENG_R4_Q_050_03",
    skillId: "ENG_R4_S050",
    difficulty: "foundation",
    stem: "Our first class ___ at 8:10 each morning.",
    options: ["starts", "is starting", "started", "start"],
    answerIndex: 0,
    reasons: [
      "starts 表示每天固定的上課時間，且 class 是單數。",
      "is starting 把固定課表誤寫成此刻正在開始。",
      "started 是過去式，無法表達每天反覆的課表。",
      "start 未配合單數主詞 class。",
    ],
    reviews: [
      "each morning 和 8:10 共同指出固定課表，故使用 starts。",
      "四項中只有 starts 兼具現在簡單式與第三人稱單數形式。",
    ],
    cognitiveProcess: ["read-schedule-clue", "select-present-simple"],
    misconceptionTargets: ["scheduled-event-needs-progressive"],
  }),
  question({
    id: "ENG_R4_Q_050_04",
    skillId: "ENG_R4_S050",
    difficulty: "standard",
    stem: "A: How does Ben usually get to school? B: He ___ the bus.",
    options: ["is taking", "took", "takes", "take"],
    answerIndex: 2,
    reasons: [
      "is taking 表示此刻或臨時情況，沒有回答 usually 所問的習慣。",
      "took 是過去式，與現在的固定通勤方式不合。",
      "takes 正確表達 Ben 通常搭公車上學。",
      "take 沒有配合代名詞 He 的第三人稱單數。",
    ],
    reviews: [
      "問句的 usually 要求回答平常方式；He 搭配 takes，答案為第三項。",
      "對話功能、時態與主詞一致三項檢核後，只有 takes 可成立。",
    ],
    cognitiveProcess: ["connect-question-and-response", "express-routine"],
    representationType: "dialogue-cloze",
    misconceptionTargets: ["answering-routine-with-current-action"],
  }),
  question({
    id: "ENG_R4_Q_050_05",
    skillId: "ENG_R4_S050",
    difficulty: "standard",
    stem: "Lina lives in Hualien, but this month she ___ with her aunt in Taipei.",
    options: ["lives", "lived", "is staying", "stay"],
    answerIndex: 2,
    reasons: [
      "lives 會把本月的暫時居住誤解成長期狀態，且與前句對比不足。",
      "lived 表示已結束的過去，但 this month 仍是目前期間。",
      "is staying 正確表示本月暫住臺北，和長期住花蓮形成對比。",
      "stay 不符合第三人稱單數，也沒有表達暫時進行情況。",
    ],
    reviews: [
      "but 對比長期住所 lives 與本月暫住，後句應為 is staying。",
      "this month 在此限定目前的臨時狀態；is staying 是唯一語意完整的選項。",
    ],
    cognitiveProcess: ["contrast-permanent-and-temporary", "select-tense-by-context"],
    misconceptionTargets: ["use-present-simple-for-every-current-state"],
  }),
  question({
    id: "ENG_R4_Q_050_06",
    skillId: "ENG_R4_S050",
    difficulty: "standard",
    stem: "A healthy plant ___ light and water.",
    options: ["needs", "needing", "needed", "is need"],
    answerIndex: 0,
    reasons: [
      "needs 以現在簡單式說明植物的一般需求。",
      "needing 單獨不能作本句的限定動詞。",
      "needed 把一般事實改成過去。",
      "is need 不是正確的 be 動詞加補語結構。",
    ],
    reviews: [
      "句子未指特定植物或時間，而是一般事實；plant 為單數，使用 needs。",
      "檢查句法後，needs 是唯一能獨立作謂語並符合一般事實的形式。",
    ],
    cognitiveProcess: ["recognize-general-condition", "select-finite-verb"],
    misconceptionTargets: ["general-fact-requires-time-marker"],
  }),
  question({
    id: "ENG_R4_Q_050_07",
    skillId: "ENG_R4_S050",
    difficulty: "standard",
    stem: "The store ___ at ten on Sundays, so we cannot shop there at eleven.",
    options: ["closing", "closed", "close", "closes"],
    answerIndex: 3,
    reasons: [
      "closing 缺少 be 動詞，不能獨立作本句謂語。",
      "closed 是過去式，和 on Sundays 的固定規律不合。",
      "close 未配合單數主詞 store。",
      "closes 正確表達商店每逢星期日的固定關門時間。",
    ],
    reviews: [
      "on Sundays 指固定規律，單數 store 要搭配 closes。",
      "後句 at eleven 的推論符合十點關門；只有 closes 提供固定時刻的意義。",
    ],
    cognitiveProcess: ["link-schedule-and-result", "apply-present-simple"],
    misconceptionTargets: ["past-form-for-scheduled-time"],
  }),
  question({
    id: "ENG_R4_Q_050_08",
    skillId: "ENG_R4_S050",
    difficulty: "advanced",
    stem: "Kai usually cooks dinner, but tonight his father ___.",
    options: ["cooks", "is cooking", "cooked", "cook"],
    answerIndex: 1,
    reasons: [
      "cooks 會把今晚的例外也寫成父親的固定習慣。",
      "is cooking 正確表示今晚正在發生、不同於平常的臨時安排。",
      "cooked 是已結束的過去式，tonight 的情境未表示事件已結束。",
      "cook 不符合單數主詞 father。",
    ],
    reviews: [
      "usually 與 but tonight 建立習慣和當下例外的對比，故選 is cooking。",
      "逐子句配對時間線索後，第二子句需要現在進行式而非現在簡單式。",
    ],
    cognitiveProcess: ["separate-clause-time-frames", "contrast-tenses"],
    misconceptionTargets: ["one-sentence-one-tense"],
  }),
  question({
    id: "ENG_R4_Q_050_09",
    skillId: "ENG_R4_S050",
    difficulty: "advanced",
    stem: "Which sentence states a general fact?",
    options: [
      "A week has seven days.",
      "The children are counting the days now.",
      "We visited the museum last week.",
      "I will call you in seven days.",
    ],
    answerIndex: 0,
    reasons: [
      "一週有七天是不受單次情境限制的一般事實。",
      "now 表示孩子此刻正在數日子，是進行情況。",
      "last week 指已結束的過去參觀。",
      "will call 表示未來一次行動。",
    ],
    reviews: [
      "四句的時間觀點不同；只有 A week has seven days 為普遍成立的事實。",
      "其餘三句分別有 now、last week、will，均指特定事件而非一般事實。",
    ],
    cognitiveProcess: ["classify-time-meaning", "distinguish-general-fact"],
    representationType: "sentence-classification",
    misconceptionTargets: ["present-simple-means-current-event"],
  }),
  question({
    id: "ENG_R4_Q_050_10",
    skillId: "ENG_R4_S050",
    difficulty: "advanced",
    stem: "The notice says the boat ___ at 6:40 tomorrow morning.",
    options: ["left", "is leave", "leaves", "leaving"],
    answerIndex: 2,
    reasons: [
      "left 表示渡輪已在過去離開，與 tomorrow 衝突。",
      "is leave 不是合法的現在式或進行式結構。",
      "leaves 可用現在簡單式表達時刻表上的固定班次。",
      "leaving 缺少 be 動詞，無法單獨完成謂語。",
    ],
    reviews: [
      "notice 提供固定出發時刻，所以 tomorrow 前仍可用 leaves。",
      "語意與句法雙重檢核顯示，只有 leaves 能表達已排定的未來班次。",
    ],
    cognitiveProcess: ["interpret-future-schedule", "apply-present-simple-to-timetable"],
    misconceptionTargets: ["tomorrow-always-needs-will"],
  }),
  question({
    id: "ENG_R4_Q_050_11",
    skillId: "ENG_R4_S050",
    difficulty: "transfer",
    stem: "The science club meets every other Tuesday. What does this sentence tell us?",
    options: [
      "The club met only once in the past.",
      "The club follows a regular meeting plan.",
      "The club is meeting at this moment.",
      "The club has not chosen a meeting day.",
    ],
    answerIndex: 1,
    reasons: [
      "meets 是現在簡單式，沒有表示過去只發生一次。",
      "every other Tuesday 表示每隔一個星期二開會的固定安排。",
      "句中沒有 now，也沒有 is meeting 的進行式。",
      "句子已清楚提供會議日，不是尚未決定。",
    ],
    reviews: [
      "every other Tuesday 和 meets 共同表達規律排程，故第二項正確。",
      "將各選項改寫回時間意義後，只有 regular meeting plan 與原句完全相符。",
    ],
    cognitiveProcess: ["interpret-grammar-in-notice", "infer-recurring-plan"],
    representationType: "notice-interpretation",
    misconceptionTargets: ["confuse-simple-with-single-event"],
  }),
  question({
    id: "ENG_R4_Q_050_12",
    skillId: "ENG_R4_S050",
    difficulty: "transfer",
    stem: "Rita usually walks to work. Which sentence gives that meaning?",
    options: [
      "Rita walked to work every day.",
      "Rita is walk to work every day.",
      "Rita is walking to work every day now.",
      "Rita walks to work on most days.",
    ],
    answerIndex: 3,
    reasons: [
      "walked 是過去式，未必表示目前仍維持的習慣。",
      "is walk 不是正確的英文動詞結構。",
      "is walking 和 now 把重點放在目前一段進行中的情況。",
      "walks 搭配 on most days，保留 usually 所表示的常態但不誇大為每天。",
    ],
    reviews: [
      "usually 表示大多數時候，現在簡單式 Rita walks to work on most days 最貼近原意。",
      "比較四句時間意義與句法後，第四項是唯一自然且精確的習慣表達。",
    ],
    cognitiveProcess: ["revise-for-intended-meaning", "choose-tense-and-form"],
    representationType: "meaning-preserving-revision",
    misconceptionTargets: ["progressive-for-routine"],
  }),
  question({
    id: "ENG_R4_Q_051_01",
    skillId: "ENG_R4_S051",
    difficulty: "foundation",
    stem: "My brother ___ soccer after school.",
    options: ["play", "plaies", "plays", "playing"],
    answerIndex: 2,
    reasons: [
      "play 沒有配合單數第三人稱主詞 brother。",
      "play 的 y 前是母音字母 a，不需改成 -ies。",
      "plays 直接在 play 後加 -s，拼字與主詞一致。",
      "playing 單獨不能作現在簡單式的謂語。",
    ],
    reviews: [
      "My brother 可代換為 he；play 的 y 前為母音，因此答案是 plays。",
      "檢查第三人稱單數與 y 字尾規則後，只有 plays 正確。",
    ],
    cognitiveProcess: ["identify-third-person-singular", "apply-s-ending"],
    misconceptionTargets: ["change-every-y-to-ies"],
  }),
  question({
    id: "ENG_R4_Q_051_02",
    skillId: "ENG_R4_S051",
    difficulty: "foundation",
    stem: "The nurse ___ the door before she leaves.",
    options: ["closes", "close", "closies", "closing"],
    answerIndex: 0,
    reasons: [
      "closes 是 close 的第三人稱單數形式，符合單數主詞 nurse。",
      "close 沒有標示第三人稱單數。",
      "closies 不是 e 結尾動詞的變化規則。",
      "closing 需要 be 動詞才能形成進行式。",
    ],
    reviews: [
      "nurse 是單數第三人稱，close 直接加 -s 成為 closes。",
      "四個形式中只有 closes 可作現在簡單式單數謂語。",
    ],
    cognitiveProcess: ["match-subject-and-verb", "form-third-person-singular"],
    misconceptionTargets: ["incorrect-e-ending-change"],
  }),
  question({
    id: "ENG_R4_Q_051_03",
    skillId: "ENG_R4_S051",
    difficulty: "foundation",
    stem: "Emma ___ math every evening.",
    options: ["study", "studys", "studying", "studies"],
    answerIndex: 3,
    reasons: [
      "study 未配合單數主詞 Emma。",
      "study 以子音字母加 y 結尾，不能直接寫 studys。",
      "studying 不是本句所需的現在簡單式限定動詞。",
      "studies 正確把 y 改成 i 再加 -es。",
    ],
    reviews: [
      "Emma 是第三人稱單數，study 的 y 前是 d，故變成 studies。",
      "依子音加 y 的拼字規則重建動詞，可唯一得到 studies。",
    ],
    cognitiveProcess: ["inspect-letter-before-y", "apply-ies-ending"],
    misconceptionTargets: ["write-studys"],
  }),
  question({
    id: "ENG_R4_Q_051_04",
    skillId: "ENG_R4_S051",
    difficulty: "standard",
    stem: "A baby sometimes ___ when it is hungry.",
    options: ["cry", "cries", "crys", "crying"],
    answerIndex: 1,
    reasons: [
      "cry 未配合單數主詞 baby。",
      "cries 依子音字母加 y 規則改 y 為 i，再加 -es。",
      "crys 漏掉 y 改 i 的拼字變化。",
      "crying 缺少 be 動詞，不能完成本句。",
    ],
    reviews: [
      "baby 是單數，cry 的 y 前為子音 r，因此正確形式是 cries。",
      "語意是習慣且主詞單數，依拼字規則只有 cries 可用。",
    ],
    cognitiveProcess: ["apply-y-ending-rule", "maintain-subject-agreement"],
    misconceptionTargets: ["omit-y-to-i-change"],
  }),
  question({
    id: "ENG_R4_Q_051_05",
    skillId: "ENG_R4_S051",
    difficulty: "standard",
    stem: "The bus ___ our house at 7:15 every morning.",
    options: ["pass", "passes", "passs", "passies"],
    answerIndex: 1,
    reasons: [
      "pass 缺少第三人稱單數字尾。",
      "passes 正確在 -ss 結尾後加 -es。",
      "passs 不是英文的字尾變化方式。",
      "passies 錯把非 y 結尾動詞套用 -ies。",
    ],
    reviews: [
      "bus 為單數主詞，pass 以 -ss 結尾，應加 -es 成為 passes。",
      "比對字尾規則與實際拼字，第二項是唯一正確形式。",
    ],
    cognitiveProcess: ["recognize-s-ending", "add-es"],
    misconceptionTargets: ["add-only-s-after-s-sound"],
  }),
  question({
    id: "ENG_R4_Q_051_06",
    skillId: "ENG_R4_S051",
    difficulty: "standard",
    stem: "Mr. Wu ___ two classes on Friday.",
    options: ["teach", "teachs", "teaching", "teaches"],
    answerIndex: 3,
    reasons: [
      "teach 未配合單數主詞 Mr. Wu。",
      "teachs 漏掉 -ch 結尾需要的 e。",
      "teaching 需要 be 動詞才能作進行式謂語。",
      "teaches 正確在 -ch 結尾後加 -es。",
    ],
    reviews: [
      "Mr. Wu 是單數第三人稱，teach 以 -ch 結尾，答案為 teaches。",
      "從主詞與字尾兩方面檢核，teaches 是唯一合法的現在式。",
    ],
    cognitiveProcess: ["apply-ch-ending-rule", "select-finite-form"],
    misconceptionTargets: ["write-teachs"],
  }),
  question({
    id: "ENG_R4_Q_051_07",
    skillId: "ENG_R4_S051",
    difficulty: "standard",
    stem: "This key ___ the small box.",
    options: ["opens", "open", "openes", "is open"],
    answerIndex: 0,
    reasons: [
      "opens 表示這把鑰匙能打開盒子，並符合單數主詞 key。",
      "open 未作第三人稱單數變化。",
      "openes 錯誤地在一般字尾後加 -es。",
      "is open 表示鑰匙本身是開著的，改變原句語意。",
    ],
    reviews: [
      "主詞 This key 是單數，動作 open 只需加 -s，得到 opens。",
      "第四項雖可成句但語意不合；能表達鑰匙作用的只有 opens。",
    ],
    cognitiveProcess: ["distinguish-verb-and-adjective", "form-s-ending"],
    misconceptionTargets: ["add-es-to-e-ending-verb"],
  }),
  question({
    id: "ENG_R4_Q_051_08",
    skillId: "ENG_R4_S051",
    difficulty: "advanced",
    stem: "The girl with three dogs ___ near the river.",
    options: ["live", "are living", "lives", "living"],
    answerIndex: 2,
    reasons: [
      "live 把鄰近的複數 dogs 誤當主詞，沒有配合真正主詞 girl。",
      "are living 也錯把 dogs 當主詞，且將長期居住寫成進行式。",
      "lives 配合單數主詞 girl；with three dogs 只是附加說明。",
      "living 沒有助動詞，不能獨立完成謂語。",
    ],
    reviews: [
      "拿掉 with three dogs 後為 The girl ___ near the river，故用 lives。",
      "主詞核心是 girl 而非 dogs；第三項同時符合長期狀態和單數形式。",
    ],
    cognitiveProcess: ["identify-head-of-subject", "ignore-intervening-noun"],
    misconceptionTargets: ["agree-with-nearest-noun"],
  }),
  question({
    id: "ENG_R4_Q_051_09",
    skillId: "ENG_R4_S051",
    difficulty: "advanced",
    stem: "One student uses the computer after lunch. Which sentence reports this correctly?",
    options: [
      "A student use the computer after lunch.",
      "A student using the computer after lunch.",
      "A student does uses the computer after lunch.",
      "A student uses the computer after lunch.",
    ],
    answerIndex: 3,
    reasons: [
      "單數 student 需要第三人稱單數動詞，use 不足。",
      "using 前缺少 be 動詞，句子沒有完整謂語。",
      "does 和 uses 重複標示第三人稱單數。",
      "uses 正確配合單數 student，句意也保持不變。",
    ],
    reviews: [
      "題目要求報告一名學生的固定行動，單數 student 應配 uses。",
      "逐句檢查限定動詞後，只有第四句結構完整且沒有重複變化。",
    ],
    cognitiveProcess: ["evaluate-complete-sentence", "apply-subject-agreement"],
    representationType: "meaning-preserving-sentence",
    misconceptionTargets: ["missing-or-double-third-person-marker"],
  }),
  question({
    id: "ENG_R4_Q_051_10",
    skillId: "ENG_R4_S051",
    difficulty: "advanced",
    stem: "Leo ___ to the chess club with his grandfather on Sundays.",
    options: ["goes", "gos", "go", "going"],
    answerIndex: 0,
    reasons: [
      "goes 是 go 的第三人稱單數形式，符合單數主詞 Leo。",
      "go 以 -o 結尾時要加 -es，不能只寫 gos。",
      "go 未標示單數第三人稱。",
      "going 前缺少 be 動詞，不能作現在簡單式謂語。",
    ],
    reviews: [
      "單數 Leo 的固定活動使用現在簡單式，go 以 -o 結尾，因此答案是 goes。",
      "逐一代入可排除漏變化的 go、錯拼的 gos 與缺 be 的 going。",
    ],
    cognitiveProcess: ["apply-o-ending-rule", "spell-third-person-form"],
    misconceptionTargets: ["add-s-without-es-after-o"],
  }),
  question({
    id: "ENG_R4_Q_051_11",
    skillId: "ENG_R4_S051",
    difficulty: "transfer",
    stem: "Each of the two shops ___ at nine.",
    options: ["open", "are opening", "opens", "opening"],
    answerIndex: 2,
    reasons: [
      "open 受 two shops 影響而誤用複數形式，但主詞核心是 Each。",
      "are opening 不僅誤判主詞，也把固定時間改為進行式。",
      "opens 配合單數代名詞 Each，並表達固定開門時間。",
      "opening 缺少限定動詞。",
    ],
    reviews: [
      "Each 表示逐一看待每家店，文法上是單數，因此使用 opens。",
      "介系詞片語 of the two shops 不決定動詞數，第三項為唯一正解。",
    ],
    cognitiveProcess: ["identify-grammatical-head", "resist-nearby-plural"],
    misconceptionTargets: ["agree-with-of-phrase-noun"],
  }),
  question({
    id: "ENG_R4_Q_051_12",
    skillId: "ENG_R4_S051",
    difficulty: "transfer",
    stem: "My aunt and uncle ___ a small bakery.",
    options: ["owns", "own", "ownes", "is owning"],
    answerIndex: 1,
    reasons: [
      "owns 將由 and 連接的兩人誤當成單數。",
      "own 配合複數主詞 My aunt and uncle，並表達長期所有狀態。",
      "ownes 不是 own 的現在式拼法。",
      "is owning 通常不適合表達穩定的所有關係，且主詞也應搭配 are。",
    ],
    reviews: [
      "aunt and uncle 是兩個人組成的複數主詞，所以主要動詞用原形 own。",
      "檢查主詞數量與 own 的狀態語意，第二項是唯一自然完整的答案。",
    ],
    cognitiveProcess: ["interpret-compound-subject", "choose-base-form"],
    misconceptionTargets: ["treat-compound-subject-as-singular"],
  }),
  question({
    id: "ENG_R4_Q_052_01",
    skillId: "ENG_R4_S052",
    difficulty: "foundation",
    stem: "___ your sister work at the hospital?",
    options: ["Do", "Does", "Is", "Are"],
    answerIndex: 1,
    reasons: [
      "Do 不和單數第三人稱主詞 your sister 搭配。",
      "Does 正確引導單數第三人稱的一般動詞問句。",
      "Is 後不能直接接原形一般動詞 work。",
      "Are 既不配合單數主詞，也不能形成本句的一般動詞問句。",
    ],
    reviews: [
      "work 是一般動詞，your sister 可代換為 she，因此問句使用 Does。",
      "主詞人稱與動詞種類都指向 Does；其餘選項無法形成合法結構。",
    ],
    cognitiveProcess: ["identify-subject-person", "select-do-or-does"],
    misconceptionTargets: ["use-do-with-third-person-singular"],
  }),
  question({
    id: "ENG_R4_Q_052_02",
    skillId: "ENG_R4_S052",
    difficulty: "foundation",
    stem: "___ the buses stop near the station?",
    options: ["Do", "Does", "Is", "Has"],
    answerIndex: 0,
    reasons: [
      "Do 正確搭配複數主詞 the buses 與原形 stop。",
      "Does 只搭配第三人稱單數，不能配 buses。",
      "Is 不配合複數主詞，也不能直接接 stop。",
      "Has 不能用來形成 stop 的現在簡單式問句。",
    ],
    reviews: [
      "buses 是複數，stop 是一般動詞，所以問句以 Do 開頭。",
      "將主詞換成 they 後得到 Do they stop...?，確認答案為第一項。",
    ],
    cognitiveProcess: ["recognize-plural-subject", "form-yes-no-question"],
    misconceptionTargets: ["use-does-for-all-noun-subjects"],
  }),
  question({
    id: "ENG_R4_Q_052_03",
    skillId: "ENG_R4_S052",
    difficulty: "foundation",
    stem: "Does Kevin ___ breakfast at home?",
    options: ["eats", "eating", "ate", "eat"],
    answerIndex: 3,
    reasons: [
      "eats 和 Does 重複標示第三人稱單數。",
      "eating 需要 be 動詞才能形成進行式。",
      "ate 是過去式，不能放在現在式 Does 問句後。",
      "eat 是原形，正確接在 Does 和主詞 Kevin 之後。",
    ],
    reviews: [
      "Does 已承擔現在式與單數標記，主要動詞必須回到原形 eat。",
      "移除 Does 後才會寫 Kevin eats；保留 Does 時唯一答案為 eat。",
    ],
    cognitiveProcess: ["remove-double-marking", "use-base-verb-after-does"],
    misconceptionTargets: ["retain-s-after-does"],
  }),
  question({
    id: "ENG_R4_Q_052_04",
    skillId: "ENG_R4_S052",
    difficulty: "standard",
    stem: "Which word order makes a correct written yes-no question about this machine?",
    options: [
      "Does use this machine power?",
      "This machine does use power?",
      "Does this machine use power?",
      "Does this machine power use?",
    ],
    answerIndex: 2,
    reasons: [
      "主要動詞 use 不能放在主詞 this machine 前面。",
      "這仍是陳述句語序；標準書面一般問句要把 Does 放到主詞前。",
      "Does + this machine + use 的助動詞、主詞與原形動詞順序正確。",
      "power 是 use 的受詞，不能移到主要動詞前形成此排列。",
    ],
    reviews: [
      "單數主詞 this machine 的一般動詞問句使用 Does，後接原形 use。",
      "第三項依序呈現助動詞、主詞、主要動詞與受詞，是唯一完整問句。",
    ],
    cognitiveProcess: ["arrange-question-elements", "retain-base-verb-after-does"],
    misconceptionTargets: ["retain-statement-order", "move-object-before-main-verb"],
  }),
  question({
    id: "ENG_R4_Q_052_05",
    skillId: "ENG_R4_S052",
    difficulty: "standard",
    stem: "Mia wants to know whether the shop sells maps. What should she ask?",
    options: [
      "Do the shop sells maps?",
      "Does the shop sells maps?",
      "Does the shop sell maps?",
      "The shop does sell maps?",
    ],
    answerIndex: 2,
    reasons: [
      "shop 是單數，不能用 Do；sells 也與助動詞重複變化。",
      "Does 正確，但後方主要動詞不應保留 -s。",
      "Does + the shop + sell 的助動詞、主詞與原形動詞順序完整。",
      "肯定句語序加問號不是本題所需的標準 yes-no 問句。",
    ],
    reviews: [
      "單數 shop 要用 Does，且 Does 後的 sell 保持原形，故第三句正確。",
      "檢查問句語序與雙重標記後，只有 Does the shop sell maps? 可成立。",
    ],
    cognitiveProcess: ["construct-question-for-purpose", "check-word-order"],
    representationType: "communicative-question-choice",
    misconceptionTargets: ["double-third-person-marking", "statement-order-with-question-mark"],
  }),
  question({
    id: "ENG_R4_Q_052_06",
    skillId: "ENG_R4_S052",
    difficulty: "standard",
    stem: "What time ___ the movie start?",
    options: ["do", "does", "is", "has"],
    answerIndex: 1,
    reasons: [
      "do 不配合單數主詞 the movie。",
      "does 放在疑問詞與單數主詞之間，後接原形 start。",
      "is 不能直接接原形 start。",
      "has 無法形成 start 的現在簡單式問句。",
    ],
    reviews: [
      "疑問詞 What time 後仍需助動詞；movie 是單數，所以填 does。",
      "還原 yes-no 問句 Does the movie start...? 可確認第二項。",
    ],
    cognitiveProcess: ["extend-yes-no-to-wh-question", "maintain-auxiliary-agreement"],
    misconceptionTargets: ["omit-does-after-wh-word"],
  }),
  question({
    id: "ENG_R4_Q_052_07",
    skillId: "ENG_R4_S052",
    difficulty: "standard",
    stem: "___ you and Tom need more chairs?",
    options: ["Do", "Does", "Is", "Are"],
    answerIndex: 0,
    reasons: [
      "Do 正確搭配由 and 連接的複數主詞 you and Tom。",
      "Does 只配第三人稱單數。",
      "Is 不配合複數主詞，也不能直接接 need。",
      "Are 雖配複數主詞，但不能直接接原形一般動詞 need。",
    ],
    reviews: [
      "you and Tom 是複數，need 為一般動詞，因此應用 Do。",
      "you and Tom 包含兩人，整體使用複數助動詞 Do；第一項是唯一完整形式。",
    ],
    cognitiveProcess: ["interpret-compound-subject", "form-present-question"],
    misconceptionTargets: ["use-does-for-named-person"],
  }),
  question({
    id: "ENG_R4_Q_052_08",
    skillId: "ENG_R4_S052",
    difficulty: "advanced",
    stem: "You need to ask about the class ending time. Which question does that?",
    options: [
      "What time the class ends?",
      "What time does the class ends?",
      "Does what time the class end?",
      "What time does the class end?",
    ],
    answerIndex: 3,
    reasons: [
      "直接問句在 What time 後缺少 does，且使用肯定句語序。",
      "does 後不應再把 end 變成 ends。",
      "疑問詞應放在 does 前，不是放在助動詞後。",
      "What time + does + the class + end 的語序與動詞形式都正確。",
    ],
    reviews: [
      "此為受詞資訊問句，依序使用 What time、does、主詞、原形 end。",
      "四句中只有第四句同時沒有漏助動詞、錯序或重複 -s。",
    ],
    cognitiveProcess: ["assemble-wh-question", "detect-multiple-form-errors"],
    representationType: "communicative-question-choice",
    misconceptionTargets: ["wh-question-word-order", "retain-s-after-does"],
  }),
  question({
    id: "ENG_R4_Q_052_09",
    skillId: "ENG_R4_S052",
    difficulty: "advanced",
    stem: "The two sisters practice after dinner. Which question checks this information?",
    options: [
      "Does the two sisters practice after dinner?",
      "Do the two sisters practice after dinner?",
      "Do the two sisters practices after dinner?",
      "Are the two sisters practice after dinner?",
    ],
    answerIndex: 1,
    reasons: [
      "two sisters 是複數，不能使用 Does。",
      "Do 配複數 two sisters，後接原形 practice，結構正確。",
      "Do 後主要動詞不應加 -s。",
      "Are 後不能直接接原形一般動詞 practice。",
    ],
    reviews: [
      "原句主詞 two sisters 為複數；改問句時在前面加入 Do，practice 保持原形。",
      "第二句是唯一保留原意並符合現在簡單式問句規則的選項。",
    ],
    cognitiveProcess: ["transform-statement-to-question", "preserve-meaning"],
    representationType: "sentence-transformation",
    misconceptionTargets: ["misread-plural-s-ending"],
  }),
  question({
    id: "ENG_R4_Q_052_10",
    skillId: "ENG_R4_S052",
    difficulty: "advanced",
    stem: "Where ___ your father work on weekdays?",
    options: ["do", "is", "does", "are"],
    answerIndex: 2,
    reasons: [
      "do 不配合單數第三人稱 father。",
      "is 不能直接接一般動詞 work。",
      "does 正確放在 Where 與主詞之間，後接 work。",
      "are 不配合 father，也無法接原形 work。",
    ],
    reviews: [
      "your father 可代換為 he，所以 Where 後使用 does，work 保持原形。",
      "動詞類型與主詞人稱均排除 do、is、are，答案為 does。",
    ],
    cognitiveProcess: ["identify-wh-question-auxiliary", "apply-subject-agreement"],
    misconceptionTargets: ["use-be-before-main-verb"],
  }),
  question({
    id: "ENG_R4_Q_052_11",
    skillId: "ENG_R4_S052",
    difficulty: "transfer",
    stem: "You want to know whether one bus goes directly to the zoo. What should you ask?",
    options: [
      "Do this bus goes directly to the zoo?",
      "Is this bus go directly to the zoo?",
      "This bus goes directly to the zoo?",
      "Does this bus go directly to the zoo?",
    ],
    answerIndex: 3,
    reasons: [
      "單數 bus 要用 Does，且助動詞後不能保留 goes。",
      "is 不能直接接原形一般動詞 go。",
      "肯定句語序在正式書面題中不是標準 yes-no 問句。",
      "Does 配單數 bus，go 使用原形，能清楚詢問路線。",
    ],
    reviews: [
      "此情境詢問單一公車路線，標準問法是 Does this bus go directly to the zoo?",
      "從溝通目的與句法兩面檢查，第四項是唯一自然且無雙重變化的問句。",
    ],
    cognitiveProcess: ["apply-question-form-in-travel-context", "evaluate-naturalness"],
    representationType: "travel-dialogue-choice",
    misconceptionTargets: ["statement-intonation-as-written-question"],
  }),
  question({
    id: "ENG_R4_Q_052_12",
    skillId: "ENG_R4_S052",
    difficulty: "transfer",
    stem: "The coffee shop serves breakfast. How do you ask if this is true?",
    options: [
      "Does the coffee shop serve breakfast?",
      "Do the coffee shop serves breakfast?",
      "Is the coffee shop serve breakfast?",
      "Does the coffee shop serves breakfast?",
    ],
    answerIndex: 0,
    reasons: [
      "Does 配單數 coffee shop，serve 回到原形，正確檢查原句資訊。",
      "Do 不配單數主詞，serves 也與助動詞重複變化。",
      "is 不能直接接原形一般動詞 serve。",
      "Does 後應用 serve，不應保留 serves。",
    ],
    reviews: [
      "把單數肯定句改問句時，加入 Does 並將 serves 還原為 serve。",
      "第一項完整保留早餐服務的語意，且助動詞與主要動詞形式一致。",
    ],
    cognitiveProcess: ["transform-declarative-to-interrogative", "restore-base-verb"],
    representationType: "sentence-transformation",
    misconceptionTargets: ["double-third-person-marking"],
  }),
  question({
    id: "ENG_R4_Q_053_01",
    skillId: "ENG_R4_S053",
    difficulty: "foundation",
    stem: "Evan ___ meat.",
    options: ["don't eats", "doesn't eats", "doesn't eat", "isn't eat"],
    answerIndex: 2,
    reasons: [
      "Evan 是單數第三人稱，不能用 don't，且助動詞後不加 -s。",
      "doesn't 與主詞一致，但 eats 應還原為 eat。",
      "doesn't eat 正確形成單數第三人稱的一般動詞否定句。",
      "isn't 不能直接接原形一般動詞 eat。",
    ],
    reviews: [
      "Evan 可代換為 he，所以使用 doesn't，後面接原形 eat。",
      "第三項是唯一同時符合助動詞一致與主要動詞原形的選項。",
    ],
    cognitiveProcess: ["select-negative-auxiliary", "restore-base-form"],
    misconceptionTargets: ["double-mark-after-doesnt"],
  }),
  question({
    id: "ENG_R4_Q_053_02",
    skillId: "ENG_R4_S053",
    difficulty: "foundation",
    stem: "We ___ classes on Sunday.",
    options: ["don't have", "doesn't have", "aren't have", "don't has"],
    answerIndex: 0,
    reasons: [
      "don't have 正確搭配主詞 We，have 保持原形。",
      "doesn't 只配第三人稱單數主詞。",
      "aren't 不能直接接一般動詞 have。",
      "don't 後不應使用第三人稱單數形式 has。",
    ],
    reviews: [
      "主詞 We 搭配 do not，主要動詞用原形 have，答案為 don't have。",
      "其餘選項分別有主詞不一致、錯用 be 或動詞未還原的問題。",
    ],
    cognitiveProcess: ["match-we-with-dont", "select-base-verb"],
    misconceptionTargets: ["use-doesnt-with-we"],
  }),
  question({
    id: "ENG_R4_Q_053_03",
    skillId: "ENG_R4_S053",
    difficulty: "foundation",
    stem: "Our printers don't print color pages, and this printer ___ them either.",
    options: ["don't print", "doesn't prints", "isn't print", "doesn't print"],
    answerIndex: 3,
    reasons: [
      "前半句雖用 don't，後半句主詞 this printer 是單數，不能照抄 don't。",
      "doesn't 已標示第三人稱單數，prints 會造成重複變化。",
      "print 是一般動詞，不能直接接在 isn't 後面。",
      "doesn't print 正確把複數 printers 的否定改為單數 this printer 的否定。",
    ],
    reviews: [
      "前句的 printers 是複數，後句改成單數 this printer，所以要換成 doesn't print。",
      "第四項同時處理主詞數的轉換與 does 後用原形，並和 either 的否定語意一致。",
    ],
    cognitiveProcess: ["shift-from-plural-to-singular-subject", "retain-negative-parallelism"],
    misconceptionTargets: ["copy-dont-across-subject-change", "use-isnt-before-main-verb"],
  }),
  question({
    id: "ENG_R4_Q_053_04",
    skillId: "ENG_R4_S053",
    difficulty: "standard",
    stem: "My cousins ___ near here.",
    options: ["doesn't live", "don't live", "aren't live", "don't lives"],
    answerIndex: 1,
    reasons: [
      "cousins 是複數，不能使用 doesn't。",
      "don't live 正確搭配複數主詞，live 為原形。",
      "aren't 不能直接接原形一般動詞 live。",
      "don't 後的 lives 不應有第三人稱單數字尾。",
    ],
    reviews: [
      "複數主詞 My cousins 等同 they，所以使用 don't live。",
      "第二項是唯一沒有主詞不一致、be 誤用或雙重標記的形式。",
    ],
    cognitiveProcess: ["recognize-plural-subject", "form-negative-with-dont"],
    misconceptionTargets: ["treat-every-third-person-noun-as-singular"],
  }),
  question({
    id: "ENG_R4_Q_053_05",
    skillId: "ENG_R4_S053",
    difficulty: "standard",
    stem: "Sara doesn't ___ to work on rainy days.",
    options: ["drives", "drive", "drove", "driving"],
    answerIndex: 1,
    reasons: [
      "drives 和 doesn't 重複標示第三人稱單數。",
      "drive 是原形，正確接在 doesn't 後。",
      "drove 是過去式，不能接在現在式助動詞後。",
      "driving 不是 does 後所需的原形動詞。",
    ],
    reviews: [
      "doesn't 已帶有時態與主詞資訊，空格只能放原形 drive。",
      "把否定句還原為肯定句 Sara drives...，可確認助動詞後要移除 -s。",
    ],
    cognitiveProcess: ["identify-auxiliary-carried-inflection", "choose-base-form"],
    misconceptionTargets: ["retain-inflected-main-verb"],
  }),
  question({
    id: "ENG_R4_Q_053_06",
    skillId: "ENG_R4_S053",
    difficulty: "standard",
    stem: "Owen likes milk. Which sentence says this is not true?",
    options: [
      "Owen don't likes milk.",
      "Owen isn't like milk.",
      "Owen doesn't likes milk.",
      "Owen doesn't like milk.",
    ],
    answerIndex: 3,
    reasons: [
      "單數 Owen 不配 don't，且 likes 未還原。",
      "isn't 不能直接否定一般動詞 like。",
      "doesn't 後不應保留 likes 的 -s。",
      "doesn't like 正確把肯定句改為相反的現在式否定。",
    ],
    reviews: [
      "Owen 是單數，否定 likes 時改為 doesn't like，故第四句正確。",
      "比較四種修正後，只有第四項既反轉語意又維持標準句法。",
    ],
    cognitiveProcess: ["negate-a-given-proposition", "preserve-tense"],
    representationType: "meaning-reversal",
    misconceptionTargets: ["negate-general-verb-with-be"],
  }),
  question({
    id: "ENG_R4_Q_053_07",
    skillId: "ENG_R4_S053",
    difficulty: "standard",
    stem: "The room ___ cold in summer.",
    options: ["isn't", "doesn't", "don't", "doesn't be"],
    answerIndex: 0,
    reasons: [
      "isn't 直接否定 be 動詞，後接形容詞 cold。",
      "doesn't 不能單獨接形容詞 cold。",
      "don't 不配單數 room，也不能直接接 cold。",
      "doesn't be 不是標準的 be 動詞現在式否定。",
    ],
    reviews: [
      "cold 是形容詞，本句需要 be 動詞；room 是單數，因此用 isn't。",
      "此題檢查一般動詞否定的邊界，只有第一項能和 cold 形成完整述語。",
    ],
    cognitiveProcess: ["distinguish-be-from-general-verb", "select-isnt"],
    misconceptionTargets: ["use-doesnt-for-be-sentence"],
  }),
  question({
    id: "ENG_R4_Q_053_08",
    skillId: "ENG_R4_S053",
    difficulty: "advanced",
    stem: "My dog never ___ on the bed.",
    options: ["doesn't sleep", "sleep", "sleeps", "don't sleep"],
    answerIndex: 2,
    reasons: [
      "never 已含否定意義，再用 doesn't 會形成不標準的雙重否定。",
      "sleep 未配合單數主詞 dog。",
      "sleeps 與單數主詞一致，never 已完整表達零頻率。",
      "don't 不配單數主詞，也和 never 重複否定。",
    ],
    reviews: [
      "never 本身表示從不，句子仍用肯定形式的第三人稱單數 sleeps。",
      "排除雙重否定並核對 dog 的單數形式後，第三項為唯一答案。",
    ],
    cognitiveProcess: ["interpret-negative-frequency", "avoid-double-negative"],
    misconceptionTargets: ["add-not-to-never"],
  }),
  question({
    id: "ENG_R4_Q_053_09",
    skillId: "ENG_R4_S053",
    difficulty: "advanced",
    stem: "The library doesn't close until nine. What does this mean?",
    options: [
      "The library closes before nine.",
      "The library is closed all day.",
      "The library opens at nine.",
      "The library stays open until nine.",
    ],
    answerIndex: 3,
    reasons: [
      "doesn't close until nine 表示九點前不關門，不是提早關門。",
      "原句只說關門時間，沒有表示全天休館。",
      "close 與 open 的事件不同，不能推得九點才開門。",
      "直到九點才關門，等同圖書館維持開放到九點。",
    ],
    reviews: [
      "not ... until nine 的時間範圍是九點前不發生 close，因此第四項正確。",
      "把否定範圍畫在九點之前，可排除提早關門、全天關閉與九點開門。",
    ],
    cognitiveProcess: ["interpret-negative-time-boundary", "paraphrase-meaning"],
    representationType: "sentence-interpretation",
    misconceptionTargets: ["reverse-not-until-meaning"],
  }),
  question({
    id: "ENG_R4_Q_053_10",
    skillId: "ENG_R4_S053",
    difficulty: "advanced",
    stem: "Nina and Paul ___ the same bus to school.",
    options: ["don't take", "doesn't take", "don't takes", "aren't take"],
    answerIndex: 0,
    reasons: [
      "Nina and Paul 是複數主詞，don't take 的助動詞與原形都正確。",
      "doesn't 不配由 and 連接的兩人。",
      "don't 後的 takes 不應有 -s。",
      "aren't 不能直接接原形一般動詞 take。",
    ],
    reviews: [
      "兩個姓名以 and 連接，等同 they，故否定式為 don't take。",
      "第一項是唯一同時處理複數主詞與助動詞後原形的答案。",
    ],
    cognitiveProcess: ["evaluate-compound-subject", "form-negative-predicate"],
    misconceptionTargets: ["use-doesnt-with-compound-subject"],
  }),
  question({
    id: "ENG_R4_Q_053_11",
    skillId: "ENG_R4_S053",
    difficulty: "transfer",
    stem: "This card does not work after June 30. What should a person understand?",
    options: [
      "The card starts working on June 30.",
      "The card works only after June 30.",
      "The card cannot be used after June 30.",
      "The card never works before June 30.",
    ],
    answerIndex: 2,
    reasons: [
      "does not work after 並不表示從該日開始可用。",
      "only after 會把原句限制完全反轉。",
      "原句直接表示 6 月 30 日之後卡片無法使用。",
      "原句沒有否定 6 月 30 日以前的效力。",
    ],
    reviews: [
      "否定詞 not 修飾 work，時間範圍是 after June 30，因此第三項為正確使用限制。",
      "逐項核對日期前後，只有 cannot be used after June 30 保留原句資訊。",
    ],
    cognitiveProcess: ["apply-negative-form-to-notice", "identify-validity-limit"],
    representationType: "public-notice-interpretation",
    misconceptionTargets: ["reverse-negative-date-limit"],
  }),
  question({
    id: "ENG_R4_Q_053_12",
    skillId: "ENG_R4_S053",
    difficulty: "transfer",
    stem: "Leo doesn't walks home on Fridays. Which sentence fixes the error?",
    options: [
      "Leo don't walk home on Fridays.",
      "Leo doesn't walk home on Fridays.",
      "Leo isn't walk home on Fridays.",
      "Leo doesn't walking home on Fridays.",
    ],
    answerIndex: 1,
    reasons: [
      "Leo 是單數，不能使用 don't。",
      "doesn't 後接原形 walk，正確修復重複的第三人稱標記。",
      "isn't 不能直接接原形一般動詞 walk。",
      "doesn't 後需要原形，不是現在分詞 walking。",
    ],
    reviews: [
      "原句唯一核心錯誤是 doesn't 後保留 walks；改成 doesn't walk 即可。",
      "第二項保留主詞、時間與否定意義，同時把主要動詞還原為原形。",
    ],
    cognitiveProcess: ["repair-specific-verb-phrase", "preserve-sentence-meaning"],
    representationType: "targeted-error-correction",
    misconceptionTargets: ["double-third-person-marking"],
  }),
  question({
    id: "ENG_R4_Q_054_01",
    skillId: "ENG_R4_S054",
    difficulty: "foundation",
    stem: "Does Amy read before bed? — Yes, ___.",
    options: ["she do", "she does", "Amy does read", "she is"],
    answerIndex: 1,
    reasons: [
      "she 是第三人稱單數，簡答不能用 do。",
      "she does 正確保留問句助動詞並以代名詞回答。",
      "標準簡短回答不在 does 後重複主要動詞 read。",
      "問句使用 does，不以 be 動詞 is 回答。",
    ],
    reviews: [
      "Amy 在回答中換成 she，Does 問句的肯定簡答為 she does。",
      "人稱與助動詞一致後，第二項是唯一完整的簡短回答。",
    ],
    cognitiveProcess: ["replace-name-with-pronoun", "match-short-answer-auxiliary"],
    representationType: "dialogue-completion",
    misconceptionTargets: ["answer-does-question-with-do"],
  }),
  question({
    id: "ENG_R4_Q_054_02",
    skillId: "ENG_R4_S054",
    difficulty: "foundation",
    stem: "Do the cats sleep outside? — No, ___.",
    options: ["they don't", "it doesn't", "they doesn't", "the cats not"],
    answerIndex: 0,
    reasons: [
      "they don't 正確以複數代名詞和 do 的否定形式回答。",
      "cats 是複數，不能用單數 it。",
      "they 不搭配 doesn't。",
      "the cats not 缺少助動詞，不能形成標準簡答。",
    ],
    reviews: [
      "the cats 轉為 they，Do 問句的否定簡答使用 don't。",
      "第一項完整處理複數代名詞與助動詞，其他形式皆不一致。",
    ],
    cognitiveProcess: ["convert-plural-noun-to-they", "form-negative-short-answer"],
    representationType: "dialogue-completion",
    misconceptionTargets: ["use-it-for-plural-animals"],
  }),
  question({
    id: "ENG_R4_Q_054_03",
    skillId: "ENG_R4_S054",
    difficulty: "foundation",
    stem: "Do you bring lunch from home? — Yes, ___.",
    options: ["you do", "I does", "I am", "I do"],
    answerIndex: 3,
    reasons: [
      "回答者談自己時，問句的 you 要轉成 I。",
      "I 不搭配 does。",
      "問句使用 do，不以 am 取代。",
      "I do 正確反映回答者視角並保留助動詞 do。",
    ],
    reviews: [
      "被問的人以 I 回答自己的行動，Do 問句的肯定形式為 I do。",
      "代名詞視角與助動詞搭配均正確的只有第四項。",
    ],
    cognitiveProcess: ["shift-speaker-perspective", "complete-short-answer"],
    representationType: "dialogue-completion",
    misconceptionTargets: ["keep-you-in-self-answer"],
  }),
  question({
    id: "ENG_R4_Q_054_04",
    skillId: "ENG_R4_S054",
    difficulty: "standard",
    stem: "Does this key open the back door? — No, ___.",
    options: ["this doesn't", "he doesn't", "it don't", "it doesn't"],
    answerIndex: 3,
    reasons: [
      "簡答以代名詞 it 代替 this key，不以 this 單獨作主詞。",
      "key 是事物，不能用 he。",
      "it 是第三人稱單數，否定形式不能用 don't。",
      "it doesn't 正確代替單數事物並搭配 Does 問句。",
    ],
    reviews: [
      "this key 是單數事物，回答代名詞為 it，否定助動詞為 doesn't。",
      "第四項在指涉、人稱與否定形式三方面皆和問句一致。",
    ],
    cognitiveProcess: ["resolve-object-reference", "match-does-with-doesnt"],
    representationType: "dialogue-completion",
    misconceptionTargets: ["use-demonstrative-as-short-answer-subject"],
  }),
  question({
    id: "ENG_R4_Q_054_05",
    skillId: "ENG_R4_S054",
    difficulty: "standard",
    stem: "A: Ken never orders tea at lunch. B: Does he order tea at lunch? A: ___",
    options: ["Yes, he does.", "No, he doesn't.", "No, he isn't.", "Yes, he drinks."],
    answerIndex: 1,
    reasons: [
      "前句 never orders tea，肯定回答會和已知事實衝突。",
      "No, he doesn't 同時符合前文語意與 Does 問句形式。",
      "問句是一般動詞 order，不使用 isn't 回答。",
      "此項重複主要動詞，且肯定內容與前文相反。",
    ],
    reviews: [
      "never orders tea 已直接否定午餐點茶，因此應以 No, he doesn't 回答。",
      "先核對對話事實，再核對助動詞，第二項是唯一一致答案。",
    ],
    cognitiveProcess: ["integrate-prior-statement", "select-semantic-short-answer"],
    representationType: "multi-turn-dialogue",
    misconceptionTargets: ["choose-grammatical-answer-with-wrong-fact"],
  }),
  question({
    id: "ENG_R4_Q_054_06",
    skillId: "ENG_R4_S054",
    difficulty: "standard",
    stem: "Do Mia and her brother share a room? — Yes, ___.",
    options: ["she does", "he does", "they do", "they does"],
    answerIndex: 2,
    reasons: [
      "主詞包含 Mia 和她的弟弟，不可只用 she。",
      "he 也只代表其中一人。",
      "they do 正確代替兩人並保留 Do。",
      "they 是複數，不搭配 does。",
    ],
    reviews: [
      "Mia and her brother 指兩人，代名詞用 they，肯定簡答搭配 do。",
      "第三項完整涵蓋原問句的複數主詞，且助動詞形式正確。",
    ],
    cognitiveProcess: ["resolve-compound-reference", "choose-plural-short-answer"],
    representationType: "dialogue-completion",
    misconceptionTargets: ["refer-to-only-one-member-of-compound-subject"],
  }),
  question({
    id: "ENG_R4_Q_054_07",
    skillId: "ENG_R4_S054",
    difficulty: "standard",
    stem: "Does your phone need more power? — Yes, ___.",
    options: ["it does", "this does", "it is", "it do"],
    answerIndex: 0,
    reasons: [
      "it does 正確以 it 代替 phone，並保留 does。",
      "簡答通常不用 this 代替前述名詞 phone。",
      "問句是一般動詞 need，不以 is 回答。",
      "it 是第三人稱單數，不能搭配 do。",
    ],
    reviews: [
      "phone 是單數事物，簡答主詞為 it；Does 問句回答 it does。",
      "第一項在指涉與助動詞上都精確對應原問句。",
    ],
    cognitiveProcess: ["replace-device-with-it", "retain-question-auxiliary"],
    representationType: "dialogue-completion",
    misconceptionTargets: ["answer-general-verb-question-with-be"],
  }),
  question({
    id: "ENG_R4_Q_054_08",
    skillId: "ENG_R4_S054",
    difficulty: "advanced",
    stem: "A: Our class begins at nine, not eight. B: Does it begin at eight? A: ___",
    options: ["Yes, it begins.", "No, it isn't.", "No, it doesn't.", "Yes, it does."],
    answerIndex: 2,
    reasons: [
      "前句明說不是八點，肯定回答不符內容；簡答也不重複 begins。",
      "begin 是一般動詞，不能以 isn't 作簡答。",
      "No, it doesn't 正確否定八點開始，並保留 Does 的助動詞。",
      "Yes 會和 not eight 直接衝突。",
    ],
    reviews: [
      "已知上課時間為九點，因此對八點開始的問句必須回答 No, it doesn't。",
      "內容真值和簡答句法分別檢查後，只有第三項兩者皆正確。",
    ],
    cognitiveProcess: ["evaluate-truth-from-context", "select-consistent-short-answer"],
    representationType: "multi-turn-dialogue",
    misconceptionTargets: ["ignore-negated-context"],
  }),
  question({
    id: "ENG_R4_Q_054_09",
    skillId: "ENG_R4_S054",
    difficulty: "advanced",
    stem: "Do your parents work on weekends? — No, ___.",
    options: ["you don't", "we don't", "they doesn't", "they don't"],
    answerIndex: 3,
    reasons: [
      "you 指聽話者，沒有代替問句中的 parents。",
      "除非 parents 本人回答，題面的一般回答應以 they 指稱他們。",
      "they 是複數，不能搭配 doesn't。",
      "they don't 正確代替 your parents 並回答 Do 問句。",
    ],
    reviews: [
      "your parents 從被問者口中仍指第三人稱複數，以 they don't 回答。",
      "第四項保持原主詞指涉，並使用複數助動詞 do 的否定形式。",
    ],
    cognitiveProcess: ["track-possessive-reference", "select-pronoun-in-answer"],
    representationType: "dialogue-completion",
    misconceptionTargets: ["copy-possessive-person-into-answer"],
  }),
  question({
    id: "ENG_R4_Q_054_10",
    skillId: "ENG_R4_S054",
    difficulty: "advanced",
    stem: "A: We need two more cups. B: Do we need more plates, too? A: No, ___.",
    options: ["we don't", "you don't", "we aren't", "we doesn't"],
    answerIndex: 0,
    reasons: [
      "we don't 正確延續雙方所屬的 we，並否定 need。",
      "you 改變了問句所指的共同群體。",
      "need 是一般動詞，不能用 aren't 回答。",
      "we 不搭配 doesn't。",
    ],
    reviews: [
      "問答雙方都以 we 指共同群體，Do 問句的否定簡答為 we don't。",
      "第一項保留人稱和一般動詞助動詞，沒有把 plates 的資訊誤轉給 you。",
    ],
    cognitiveProcess: ["maintain-inclusive-pronoun", "complete-negative-response"],
    representationType: "multi-turn-dialogue",
    misconceptionTargets: ["shift-we-to-you-without-context"],
  }),
  question({
    id: "ENG_R4_Q_054_11",
    skillId: "ENG_R4_S054",
    difficulty: "transfer",
    stem: "A sign says, “Buses stop here after 6 p.m.” Do buses stop here at 7 p.m.?",
    options: ["No, it doesn't.", "No, they don't.", "Yes, they do.", "Yes, it does."],
    answerIndex: 2,
    reasons: [
      "buses 是複數，不能用 it；內容也應為肯定。",
      "時間 7 p.m. 在六點之後，否定回答不符標示。",
      "標示指出六點後停靠，7 p.m. 應回答 Yes, they do。",
      "肯定語意正確，但單數 it 未代替複數 buses。",
    ],
    reviews: [
      "7 p.m. 屬 after 6 p.m.，所以事實為肯定；buses 以 they 代替。",
      "同時核對時間條件與複數簡答，可唯一得到第三項。",
    ],
    cognitiveProcess: ["apply-notice-condition", "form-evidence-based-short-answer"],
    representationType: "sign-and-question",
    misconceptionTargets: ["choose-correct-truth-with-wrong-pronoun"],
  }),
  question({
    id: "ENG_R4_Q_054_12",
    skillId: "ENG_R4_S054",
    difficulty: "transfer",
    stem: "A: The red line goes to City Hall. B: Does the blue line go there, too? A: ___ It goes to the park, not City Hall.",
    options: ["Yes, it goes.", "No, it doesn't.", "No, it isn't.", "Yes, it does."],
    answerIndex: 1,
    reasons: [
      "後句說藍線去公園，肯定回答去 City Hall 會矛盾。",
      "No, it doesn't 正確否定藍線去 City Hall，並與後句銜接。",
      "go 是一般動詞，不能用 isn't 作簡答。",
      "肯定回答與 It goes to the park 的對比不合。",
    ],
    reviews: [
      "there 指 City Hall，而藍線去 park，所以答案必須是 No, it doesn't。",
      "追蹤 there 的指涉並核對後句目的地後，第二項唯一符合對話。",
    ],
    cognitiveProcess: ["resolve-place-reference", "infer-negative-response"],
    representationType: "route-dialogue",
    misconceptionTargets: ["ignore-there-reference"],
  }),
  question({
    id: "ENG_R4_Q_055_01",
    skillId: "ENG_R4_S055",
    difficulty: "foundation",
    stem: "I ___ check the door before I leave home.",
    options: ["am always", "check always", "always", "always am"],
    answerIndex: 2,
    reasons: [
      "check 是本句一般動詞，不需要加入 am。",
      "頻率副詞在中性語序中不放在一般動詞 check 後。",
      "always 放在一般動詞 check 前，形成自然的習慣句。",
      "句中不需要 be 動詞，always am 也無法接 check。",
    ],
    reviews: [
      "主要動詞是 check，頻率副詞 always 應放在它前面，因此選第三項。",
      "代入後只有 I always check... 形成完整且自然的現在簡單式。",
    ],
    cognitiveProcess: ["identify-main-verb", "place-frequency-adverb"],
    misconceptionTargets: ["insert-be-before-frequency-adverb"],
  }),
  question({
    id: "ENG_R4_Q_055_02",
    skillId: "ENG_R4_S055",
    difficulty: "foundation",
    stem: "Ben is ___ late for class.",
    options: ["never", "not never", "never is", "doesn't"],
    answerIndex: 0,
    reasons: [
      "never 放在 be 動詞 is 後、形容詞 late 前，位置正確。",
      "not never 形成不必要的雙重否定，不能表達從不遲到。",
      "題幹已有 is，填入 never is 會重複 be 動詞。",
      "doesn't 不能放在 is 與形容詞 late 之間。",
    ],
    reviews: [
      "be 動詞句的頻率副詞通常置於 be 後，得到 Ben is never late。",
      "空格位置在 is 與 late 之間，只有 never 能直接完成自然句子。",
    ],
    cognitiveProcess: ["recognize-be-verb-pattern", "place-never-after-be"],
    misconceptionTargets: ["place-adverb-before-existing-be"],
  }),
  question({
    id: "ENG_R4_Q_055_03",
    skillId: "ENG_R4_S055",
    difficulty: "foundation",
    stem: "Our teacher answers questions after class on most school days. She can ___ help us then.",
    options: ["never", "seldom", "always", "usually"],
    answerIndex: 3,
    reasons: [
      "never 表示完全不會，和 most school days 提供的高頻率相反。",
      "seldom 表示很少，也低於題目所說的大多數上課日。",
      "always 表示每次都會，超過 most 所提供的資訊。",
      "usually 表示大多數時候，且自然位於 can 與 help 之間。",
    ],
    reviews: [
      "most school days 對應 usually；放入後形成 She can usually help us then。",
      "題目未說每天都提供協助，因此 always 過強，never 與 seldom 又和已知頻率衝突。",
    ],
    cognitiveProcess: ["locate-modal-auxiliary", "place-adverb-before-base-verb"],
    misconceptionTargets: ["inflect-verb-after-can"],
  }),
  question({
    id: "ENG_R4_Q_055_04",
    skillId: "ENG_R4_S055",
    difficulty: "standard",
    stem: "Mia is busy on most Friday evenings. Which sentence gives that meaning?",
    options: [
      "Mia often busy on Friday evenings.",
      "Mia is often busy on Friday evenings.",
      "Mia is sometimes busy on Friday evenings.",
      "Mia is never busy on Friday evenings.",
    ],
    answerIndex: 1,
    reasons: [
      "busy 是形容詞，前面缺少 be 動詞。",
      "is often busy 把頻率副詞放在 be 動詞後，符合題意。",
      "sometimes 只表示有時，低於 most Friday evenings 所給的頻率。",
      "never 表示從不，和大多數星期五都忙直接相反。",
    ],
    reviews: [
      "busy 需要 is，often 應放在 is 後，得到 Mia is often busy...。",
      "第二句是唯一採用標準中性語序並保留『大多數星期五』語意的選項。",
    ],
    cognitiveProcess: ["express-frequency-with-adjective", "select-neutral-word-order"],
    representationType: "meaning-preserving-sentence",
    misconceptionTargets: ["omit-be-before-adjective"],
  }),
  question({
    id: "ENG_R4_Q_055_05",
    skillId: "ENG_R4_S055",
    difficulty: "standard",
    stem: "We ___ eat outside on warm days.",
    options: ["are often", "often", "eat often", "do often"],
    answerIndex: 1,
    reasons: [
      "eat 已是本句主要動詞，are often 會造成兩個動詞結構衝突。",
      "often 放在一般動詞 eat 前，正確表達頻率。",
      "eat often 代入空格後會重複題幹中的 eat。",
      "肯定句不需要 do，且 do often 後還會出現第二個 eat。",
    ],
    reviews: [
      "題幹空格位於主詞與一般動詞 eat 之間，應填頻率副詞 often。",
      "只有第二項不增加多餘動詞，並形成 We often eat outside...。",
    ],
    cognitiveProcess: ["read-blank-position", "avoid-extra-auxiliary"],
    misconceptionTargets: ["add-be-to-frequency-sentence"],
  }),
  question({
    id: "ENG_R4_Q_055_06",
    skillId: "ENG_R4_S055",
    difficulty: "standard",
    stem: "The buses are ___ full before eight.",
    options: ["full often", "often are", "do often", "often"],
    answerIndex: 3,
    reasons: [
      "空格後已有 full，填入 full often 會重複形容詞。",
      "題幹已有 are，often are 會重複 be 動詞。",
      "be 動詞句不需要 do。",
      "often 正確位於 are 後、full 前。",
    ],
    reviews: [
      "主要動詞 are 已在題幹中，副詞 often 應直接放在其後。",
      "代入第四項得到 The buses are often full，結構與語意皆完整。",
    ],
    cognitiveProcess: ["place-adverb-in-be-clause", "complete-adjective-predicate"],
    misconceptionTargets: ["duplicate-be-around-adverb"],
  }),
  question({
    id: "ENG_R4_Q_055_07",
    skillId: "ENG_R4_S055",
    difficulty: "standard",
    stem: "Lily never ___ her lunch at home.",
    options: ["leaves", "doesn't leave", "leave", "is leaving"],
    answerIndex: 0,
    reasons: [
      "leaves 配合單數 Lily；never 已完整表示從不。",
      "never 和 doesn't 同時出現會形成不標準的雙重否定。",
      "leave 沒有配合第三人稱單數。",
      "is leaving 表示進行情況，也和 never 的習慣頻率不合。",
    ],
    reviews: [
      "never 是頻率副詞而非助動詞，主要動詞仍需用第三人稱單數 leaves。",
      "移除雙重否定並檢查主詞一致後，第一項是唯一答案。",
    ],
    cognitiveProcess: ["combine-negative-frequency-with-affirmative-form", "apply-s-ending"],
    misconceptionTargets: ["pair-never-with-doesnt"],
  }),
  question({
    id: "ENG_R4_Q_055_08",
    skillId: "ENG_R4_S055",
    difficulty: "advanced",
    stem: "The team has ___ finished practice before six.",
    options: ["finish usually", "usually has", "usually", "is usually"],
    answerIndex: 2,
    reasons: [
      "has 後需要過去分詞 finished，finish usually 會破壞完成式。",
      "題幹已有 has，usually has 會重複助動詞。",
      "usually 位在助動詞 has 與 finished 之間，詞序正確。",
      "has 後不能再加入 is usually。",
    ],
    reviews: [
      "有助動詞 has 時，頻率副詞通常置於 has 後，形成 has usually finished。",
      "空格兩側已是 has 與 finished，第三項能直接建立正確完成式語序。",
    ],
    cognitiveProcess: ["locate-first-auxiliary", "place-adverb-in-verb-phrase"],
    misconceptionTargets: ["place-adverb-before-first-auxiliary"],
  }),
  question({
    id: "ENG_R4_Q_055_09",
    skillId: "ENG_R4_S055",
    difficulty: "advanced",
    stem: "Nina takes the same train seven days a week. Which word best describes this habit?",
    options: ["never", "seldom", "sometimes", "always"],
    answerIndex: 3,
    reasons: [
      "never 表示零次，和七天都搭車相反。",
      "seldom 表示很少，不能描述每天。",
      "sometimes 表示有時，頻率低於題示的七天。",
      "always 最符合一週七天都搭同一班車的習慣。",
    ],
    reviews: [
      "seven days a week 表示沒有例外，對應最高頻率副詞 always。",
      "將四個副詞按頻率排列後，只有 always 能涵蓋題示全部七天。",
    ],
    cognitiveProcess: ["map-frequency-data-to-adverb", "compare-frequency-scale"],
    representationType: "frequency-interpretation",
    misconceptionTargets: ["treat-sometimes-as-any-repeated-action"],
  }),
  question({
    id: "ENG_R4_Q_055_10",
    skillId: "ENG_R4_S055",
    difficulty: "advanced",
    stem: "Eric rides his bike only once or twice a year. He ___ rides it.",
    options: ["seldom", "always", "usually", "often"],
    answerIndex: 0,
    reasons: [
      "seldom 表示很少，符合一年只有一兩次。",
      "always 表示每次或總是，頻率過高。",
      "usually 表示大多數時候，與一年一兩次不合。",
      "often 表示經常，也高於題示頻率。",
    ],
    reviews: [
      "once or twice a year 是很低的頻率，四項中以 seldom 最精確。",
      "比較副詞頻率層級後，always、usually、often 都明顯高於題目資料。",
    ],
    cognitiveProcess: ["interpret-low-frequency", "select-frequency-adverb"],
    representationType: "frequency-interpretation",
    misconceptionTargets: ["equate-any-repetition-with-often"],
  }),
  question({
    id: "ENG_R4_Q_055_11",
    skillId: "ENG_R4_S055",
    difficulty: "transfer",
    stem: "A hotel worker ___ at the front desk nearly every night.",
    options: ["usually working", "does usually", "is usually", "usually"],
    answerIndex: 2,
    reasons: [
      "usually working 缺少限定動詞，不能單獨完成現在簡單式。",
      "does usually 後面缺少原形主要動詞，不能直接接地點片語。",
      "is usually 先以 be 連接地點，再把頻率副詞放在 be 後。",
      "單獨填 usually 會使句子缺少動詞。",
    ],
    reviews: [
      "at the front desk 是地點補語，需要 is；頻率副詞 usually 接在 is 後。",
      "代入四項後，只有 is usually 同時補足動詞並呈現 nearly every night 的頻率。",
    ],
    cognitiveProcess: ["report-work-pattern", "choose-neutral-adverb-placement"],
    representationType: "workplace-report",
    misconceptionTargets: ["place-adverb-before-be-by-default"],
  }),
  question({
    id: "ENG_R4_Q_055_12",
    skillId: "ENG_R4_S055",
    difficulty: "transfer",
    stem: "Leo plays often basketball after dinner. Where should the word often go?",
    options: [
      "Leo is often plays basketball after dinner.",
      "Leo often plays basketball after dinner.",
      "Leo plays often basketball after dinner.",
      "Leo does plays often basketball after dinner.",
    ],
    answerIndex: 1,
    reasons: [
      "is 和 plays 不能同時作此現在簡單式的限定動詞。",
      "often 放在一般動詞 plays 前，句意與結構都自然。",
      "often 仍放在動詞與受詞 basketball 之間，沒有修正原來的詞序。",
      "does 後不應使用 plays，often 的位置也未修好。",
    ],
    reviews: [
      "原句只需把 often 移到一般動詞 plays 前，得到第二句。",
      "第二項保留全部原意且不增添助動詞或新頻率訊息，是最小而完整的修正。",
    ],
    cognitiveProcess: ["repair-adverb-placement", "preserve-original-meaning"],
    representationType: "targeted-error-correction",
    misconceptionTargets: ["place-often-after-transitive-verb"],
  }),
  question({
    id: "ENG_R4_Q_056_01",
    skillId: "ENG_R4_S056",
    difficulty: "foundation",
    stem: "Mr. Chen works at the town center every Monday. Which words show that this happens again each week?",
    options: ["at the town center", "Mr. Chen", "every Monday", "works at"],
    answerIndex: 2,
    reasons: [
      "at the town center 說明地點，沒有表示事情多久發生一次。",
      "Mr. Chen 指出人物，不是時間線索。",
      "every Monday 表示每逢星期一都會發生，形成固定週期。",
      "works at 連接動作與地點，本身沒有提供反覆頻率。",
    ],
    reviews: [
      "every Monday 直接回答多久一次，表示每週一反覆出現的工作安排。",
      "其餘選項分別提供人物、地點或動作關係，只有第三項建立時間週期。",
    ],
    cognitiveProcess: ["locate-repeated-time-marker", "separate-time-from-place"],
    representationType: "time-clue-identification",
    misconceptionTargets: ["treat-place-phrase-as-frequency-clue"],
  }),
  question({
    id: "ENG_R4_Q_056_02",
    skillId: "ENG_R4_S056",
    difficulty: "foundation",
    stem: "Look! The children ___ across the park right now.",
    options: ["are running", "run", "ran", "runs"],
    answerIndex: 0,
    reasons: [
      "are running 符合 Look 與 right now 所指的正在進行動作。",
      "run 會表達規律，沒有呈現眼前動作。",
      "ran 是已完成的過去式。",
      "runs 不配複數 children，也不是進行式。",
    ],
    reviews: [
      "Look 和 right now 都把事件限定在此刻，複數主詞使用 are running。",
      "即使本單元主題是現在簡單式，時間線索仍要求辨認此題應選進行式。",
    ],
    cognitiveProcess: ["recognize-current-action-clues", "reject-present-simple"],
    misconceptionTargets: ["choose-present-simple-for-any-present-time"],
  }),
  question({
    id: "ENG_R4_Q_056_03",
    skillId: "ENG_R4_S056",
    difficulty: "foundation",
    stem: "We ___ the old bridge yesterday afternoon.",
    options: ["cross", "are crossing", "crosses", "crossed"],
    answerIndex: 3,
    reasons: [
      "cross 是現在式原形，與 yesterday afternoon 不合。",
      "are crossing 表示正在進行，沒有表達已結束的昨天下午。",
      "crosses 不配主詞 We，也不是過去式。",
      "crossed 是規則過去式，正確對應 yesterday afternoon。",
    ],
    reviews: [
      "yesterday afternoon 指已結束的過去時間，因此 cross 要變為 crossed。",
      "時間線索先決定過去式，主詞 We 不影響規則過去式形式，答案為第四項。",
    ],
    cognitiveProcess: ["identify-completed-past-time", "select-past-simple"],
    misconceptionTargets: ["ignore-explicit-past-marker"],
  }),
  question({
    id: "ENG_R4_Q_056_04",
    skillId: "ENG_R4_S056",
    difficulty: "standard",
    stem: "The school show ___ at seven tomorrow evening.",
    options: ["started", "starts", "starting", "is start"],
    answerIndex: 1,
    reasons: [
      "started 是過去式，和 tomorrow 衝突。",
      "starts 可用現在簡單式表示節目表上排定的開始時間。",
      "starting 缺少 be 動詞，不能獨立作謂語。",
      "is start 不是正確的英文動詞結構。",
    ],
    reviews: [
      "school show 的開始時間屬固定安排，即使有 tomorrow 也可使用 starts。",
      "第二項是唯一同時符合未來排程語意與完整限定動詞形式的選項。",
    ],
    cognitiveProcess: ["distinguish-schedule-from-prediction", "use-simple-present-for-event-time"],
    misconceptionTargets: ["future-word-forces-will"],
  }),
  question({
    id: "ENG_R4_Q_056_05",
    skillId: "ENG_R4_S056",
    difficulty: "standard",
    stem: "June usually walks home, but today she is taking a taxi. Which word points to the change for today?",
    options: ["usually", "today", "walks", "home"],
    answerIndex: 1,
    reasons: [
      "usually 指向平常走路的習慣，不是今天的例外。",
      "today 把搭計程車限制在今天，因此指出臨時改變。",
      "walks 是平常子句的動詞，沒有標示例外發生的時間。",
      "home 說明目的地，不是時間線索。",
    ],
    reviews: [
      "usually 屬於 walks home，today 則限定 is taking a taxi；所以第二項指向臨時改變。",
      "分開兩個子句的線索後，可知人物與目的地都不提供時間，只有 today 符合。",
    ],
    cognitiveProcess: ["assign-clue-to-clause", "identify-temporary-time-marker"],
    representationType: "clause-scope-identification",
    misconceptionTargets: ["apply-usually-to-second-clause"],
  }),
  question({
    id: "ENG_R4_Q_056_06",
    skillId: "ENG_R4_S056",
    difficulty: "standard",
    stem: "A triangle ___ three sides.",
    options: ["had", "is having", "have", "has"],
    answerIndex: 3,
    reasons: [
      "had 是過去式，不能表達定義性事實。",
      "is having 不適合穩定的所有關係，也把事實寫成暫時狀態。",
      "have 未配合單數主詞 A triangle。",
      "has 以現在簡單式表達三角形的定義性特徵。",
    ],
    reviews: [
      "句中沒有時間詞，但三角形有三邊是一般定義，單數主詞使用 has。",
      "由一般事實而非關鍵字判斷時態，可唯一選出第四項。",
    ],
    cognitiveProcess: ["recognize-definition-without-time-marker", "apply-present-simple"],
    misconceptionTargets: ["require-frequency-word-for-simple-present"],
  }),
  question({
    id: "ENG_R4_Q_056_07",
    skillId: "ENG_R4_S056",
    difficulty: "standard",
    stem: "This week, Dad ___ from home while his office is closed.",
    options: ["is working", "works", "worked", "work"],
    answerIndex: 0,
    reasons: [
      "is working 表示只限 this week 的暫時安排。",
      "works 通常表示固定工作方式，沒有呈現辦公室暫時關閉的原因。",
      "worked 是已結束的過去，與 this week 的目前期間不合。",
      "work 不配單數 Dad。",
    ],
    reviews: [
      "this week 和 while his office is closed 都指出暫時狀況，應選 is working。",
      "第二項文法可成立於別的語境，但會錯失本題明示的有限期間，故第一項唯一。",
    ],
    cognitiveProcess: ["interpret-limited-current-period", "choose-progressive-over-habit"],
    misconceptionTargets: ["treat-any-week-phrase-as-routine"],
  }),
  question({
    id: "ENG_R4_Q_056_08",
    skillId: "ENG_R4_S056",
    difficulty: "advanced",
    stem: "The pool usually closes at eight, but it ___ open later tonight for the school event.",
    options: ["stays", "stayed", "is staying", "stay"],
    answerIndex: 2,
    reasons: [
      "stays 會把今晚延長開放誤寫成固定規律。",
      "stayed 是過去式，tonight 的活動尚屬目前安排。",
      "is staying 表示今晚一次性的臨時延長開放。",
      "stay 不配單數 it。",
    ],
    reviews: [
      "usually closes 與 later tonight 的活動例外相對，後句需要 is staying。",
      "辨認固定關門時間和單次特別開放兩層資訊後，第三項最精確。",
    ],
    cognitiveProcess: ["integrate-rule-and-special-event", "select-temporary-form"],
    misconceptionTargets: ["use-simple-present-for-explicit-one-night-exception"],
  }),
  question({
    id: "ENG_R4_Q_056_09",
    skillId: "ENG_R4_S056",
    difficulty: "advanced",
    stem: "Sam ___ lunch at school every day, but he ___ at home yesterday.",
    options: [
      "ate / eats",
      "is eating / eats",
      "eats / is eating",
      "eats / ate",
    ],
    answerIndex: 3,
    reasons: [
      "第一組把每天習慣與昨天事件的時態顛倒。",
      "every day 不需要現在進行式，第二格也不應用現在式。",
      "第一格正確，但 yesterday 要求過去式 ate，而非 is eating。",
      "eats 對應每天習慣，ate 對應昨天一次事件。",
    ],
    reviews: [
      "兩個子句各有獨立線索：every day 配 eats，yesterday 配 ate。",
      "依時間軸逐格判斷而非全句統一時態，可確認第四組。",
    ],
    cognitiveProcess: ["map-two-time-markers", "select-two-verb-forms"],
    representationType: "double-cloze",
    misconceptionTargets: ["force-same-tense-across-clauses"],
  }),
  question({
    id: "ENG_R4_Q_056_10",
    skillId: "ENG_R4_S056",
    difficulty: "advanced",
    stem: "Which words most clearly point to a repeated habit?",
    options: ["every other day", "right now", "last night", "next week"],
    answerIndex: 0,
    reasons: [
      "every other day 表示每隔一天反覆發生。",
      "right now 指說話當下。",
      "last night 指已結束的單一過去時段。",
      "next week 指未來時段，本身不表示反覆。",
    ],
    reviews: [
      "四個片語中只有 every other day 內含固定週期與重複概念。",
      "將片語放到時間軸上，第一項形成循環，其餘只定位某個時段。",
    ],
    cognitiveProcess: ["classify-time-expression", "identify-recurring-frequency"],
    representationType: "time-clue-classification",
    misconceptionTargets: ["treat-any-time-phrase-as-frequency"],
  }),
  question({
    id: "ENG_R4_Q_056_11",
    skillId: "ENG_R4_S056",
    difficulty: "transfer",
    stem: "A notice says, “The reading room opens at 9 a.m. during the holiday.” What is the role of opens?",
    options: [
      "It reports an action completed yesterday.",
      "It describes someone opening the room now.",
      "It gives a fixed opening time.",
      "It makes a promise with no fixed time.",
    ],
    answerIndex: 2,
    reasons: [
      "opens 是現在式，notice 沒有提到昨天完成。",
      "句中沒有正在開門的人，也沒有進行式。",
      "公告以現在簡單式列出固定開放時間。",
      "9 a.m. 已是明確時間，不是未知時間的承諾。",
    ],
    reviews: [
      "公告中的 at 9 a.m. 是固定時刻，opens 用來陳述排程，故第三項正確。",
      "從文體與時間資訊判斷，這是時刻表用法，不是過去、當下動作或承諾。",
    ],
    cognitiveProcess: ["interpret-tense-in-public-notice", "identify-schedule-function"],
    representationType: "public-notice-analysis",
    misconceptionTargets: ["read-present-form-as-action-now"],
  }),
  question({
    id: "ENG_R4_Q_056_12",
    skillId: "ENG_R4_S056",
    difficulty: "transfer",
    stem: "Every winter, many birds ___ to the lake. Right now, a large group ___ near the north side.",
    options: [
      "are coming / rests",
      "come / is resting",
      "came / rested",
      "comes / are resting",
    ],
    answerIndex: 1,
    reasons: [
      "Every winter 要表達規律，不宜用 are coming；第二格也未呈現當下群體。",
      "come 表達每年規律，is resting 表示現在看到的一群鳥。",
      "兩個過去式把仍有效的規律與目前觀察都寫成已結束。",
      "many birds 是複數不能用 comes；group 作單一群體時也應搭配 is。",
    ],
    reviews: [
      "第一句由 Every winter 判定 come；第二句由 Right now 判定 is resting。",
      "分別檢查週期性與當前觀察，再核對單數主詞，第二組唯一完整。",
    ],
    cognitiveProcess: ["integrate-general-pattern-and-current-observation", "choose-contrasting-forms"],
    representationType: "two-sentence-context",
    misconceptionTargets: ["apply-one-tense-to-related-sentences"],
  }),
];

export const ENGLISH_U08_VOCABULARY_POLICY = Object.freeze({
  capQuestionBasis: "appendix-5-table-1",
  additionalLearningTerms: [
    "chess", "complete", "crowded", "describe", "direct", "event", "extra", "general", "hall", "information",
    "nest", "print", "printer", "promise", "regular", "role", "serve", "state", "triangle", "usual",
    "volleyball", "weekday", "wing",
  ],
  properNames: [
    "Amy", "Ann", "Ben", "Chen", "City", "Emma", "Eric", "Evan", "Grace", "Hualien", "Jay", "Jo", "June",
    "Kai", "Ken", "Kevin", "Leo", "Lily", "Lina", "Linda", "Maya", "Mia", "Nina", "Nora", "Owen", "Paul",
    "Rita", "Sam", "Sara", "Taipei", "Tainan", "Tom", "Wu",
  ],
  grammarNotation: ["A", "B", "D", "-ch", "-d", "-es", "-ies", "-s", "-sh", "-ss", "-x", "-y"],
  malformedDistractors: [
    "closies", "crys", "gos", "haves", "openes", "ownes", "passies", "passs", "plaies", "playes", "studys", "teachs", "washies",
  ],
});

export const ENGLISH_U08_SOURCE = Object.freeze({
  unitId: UNIT_ID,
  lectures: ENGLISH_U08_LECTURES,
  questions: ENGLISH_U08_QUESTIONS,
  vocabularyPolicy: ENGLISH_U08_VOCABULARY_POLICY,
});

export const ENGLISH_UNIT_SOURCE = ENGLISH_U08_SOURCE;

export { question };
