const UNIT_ID = "ENG_R4_U23";

function lecture(id, skillId, content) {
  return { id, skillId, ...content, sections: content.sections.map((section, index) => ({ id: `${id}_SEC_${String(index + 1).padStart(2, "0")}`, ...section })) };
}

const DIFFICULTIES = ["foundation", "foundation", "foundation", "standard", "standard", "standard", "standard", "advanced", "advanced", "advanced", "transfer", "transfer"];

function skillQuestions(skillNumber, values) {
  if (values.length !== 12) throw new Error(`ENG_R4_S${skillNumber}: expected 12 authored questions`);
  return values.map((value, index) => ({ id: `ENG_R4_Q_${skillNumber}_${String(index + 1).padStart(2, "0")}`, skillId: `ENG_R4_S${skillNumber}`, difficulty: DIFFICULTIES[index], ...value }));
}

export const ENGLISH_U23_LECTURES = [
  lecture("ENG_R4_L_S155", "ENG_R4_S155", {
    objectives: ["從主動句辨認誰執行動作，以及誰或什麼承受動作。", "依動詞與句子結構判讀角色，不把第一個人物或最近的名詞一律當成動作者。"],
    sections: [
      { title: "主動句把動作者放在主詞位置", content: "Mia opened the door 中，Mia 主動執行 opened，所以是動作者；the door 因為受到開門這個動作影響，是承受者。先找主要動詞，再問誰做這件事，通常比只照單字排列猜角色可靠。" },
      { title: "受詞指出動作落在誰或什麼上", content: "The dog followed Ben 裡，the dog 是跟隨者，Ben 是被跟隨的人。承受者不一定受傷或改變，只要動作指向它，就可以是受詞；因此 follow、call、visit 等動詞也能建立動作者與承受者。" },
      { title: "修飾語不會搶走核心角色", content: "After lunch, Amy carried the boxes to the car 中，時間片語 After lunch 和地點片語 to the car 都提供背景。真正的角色仍由 Amy carried the boxes 決定：Amy 搬運，boxes 被搬運。" },
      { title: "有些動詞沒有承受者", content: "Leo slept well 只有 Leo 執行 sleep，後面沒有承受動作的受詞。判讀時不能為了湊出兩個角色而虛構承受者；要先確認主要動詞在該句是否真的把動作傳到另一個人或事物。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S155_EX_01", prompt: "Nora washed the cups. Who did the washing, and what was washed?", steps: ["找出主要動詞 washed。", "在動詞前找執行者 Nora。", "在動詞後確認承受者 the cups。"], answer: "Nora did the washing; the cups were washed.", why: "washed 表示清洗，Nora 位於主詞位置並完成動作；the cups 是洗的對象。不能因 cups 是複數或靠近句尾，就把它誤認成動作者。" },
      { id: "ENG_R4_L_S155_EX_02", prompt: "The strong wind closed the window. What caused the window to close?", steps: ["辨認 closed 是主要動詞。", "確認 the strong wind 位在動詞前。", "把 the window 判為受影響的事物。"], answer: "The strong wind.", why: "句子把風當成造成關窗結果的力量，所以 the strong wind 是動作者；the window 只承受 closed 的作用，沒有自行完成關窗動作。" },
      { id: "ENG_R4_L_S155_EX_03", prompt: "After dinner, Ben called Amy from the kitchen. Who received the call?", steps: ["略過時間與地點背景。", "讀取核心結構 Ben called Amy。", "找出 called 指向的對象。"], answer: "Amy.", why: "After dinner 和 from the kitchen 都不改變角色。核心句中 Ben 發出電話，Amy 接到這個動作，因此 Amy 是 called 的承受者。" },
    ],
    misconceptions: [
      { belief: "句中第一個人物一定是動作者，即使它只出現在時間或地點片語裡。", whyWrong: "片語中的名詞可能只是背景，未必是主要動詞的主詞。", correction: "先定位主要動詞，再找與它直接搭配的主詞。" },
      { belief: "承受者一定是沒有生命的物品。", whyWrong: "人也能被拜訪、呼叫、幫助或跟隨。", correction: "判斷動作指向誰，不用有無生命分類角色。" },
      { belief: "離動詞最近的名詞就是動作者。", whyWrong: "主動句的受詞常緊跟在動詞後，距離近卻是承受者。", correction: "用主詞位置和動詞意思共同確認執行者。" },
      { belief: "每個英文句子都必須找出一個承受者。", whyWrong: "sleep、arrive 等用法可以沒有受詞。", correction: "若動作沒有指向另一個對象，就只保留動作者。" },
    ],
    checks: [
      { prompt: "在 Sam fixed the bike 中，誰執行修理？", answer: "Sam", reason: "Sam 是 fixed 的主詞與動作者。" },
      { prompt: "在 The child kicked the ball 中，什麼承受動作？", answer: "the ball", reason: "踢的動作由 child 發出並落在 ball 上。" },
      { prompt: "Mia smiled 中是否一定有承受者？", answer: "沒有", reason: "此處 smiled 沒有受詞，不應自行補一個對象。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S156", "ENG_R4_S156", {
    objectives: ["用適當的 be 動詞加過去分詞形成基本被動語態。", "讓 be 動詞與新主詞一致，並區分過去分詞、過去式與現在分詞。"],
    sections: [
      { title: "被動句把承受者移到焦點位置", content: "主動句 Students clean the room every day 可改成 The room is cleaned every day。room 原本承受 clean，改寫後成為主詞；被動結構用 is 加 cleaned，語意仍是房間受到清理。" },
      { title: "be 動詞依新主詞決定單複數", content: "The window is opened 與 The windows are opened 的過去分詞都是 opened，差別在新主詞單複數。單數通常用 is，複數通常用 are；不能只看原主動句的動作者來選 be 動詞。" },
      { title: "過去分詞不等於一般過去式", content: "規則動詞的過去式與過去分詞常同形，如 cleaned；不規則動詞則更容易看出差別，例如 write、wrote、written。被動要用 is written，不用 is wrote，也不能用 is writing。" },
      { title: "只有能帶承受者的動作適合直接改被動", content: "Ben carried the box 能把 box 移到主詞位置，寫成 The box was carried by Ben。Leo slept well 沒有受詞可移動，因此不能憑空寫出一個被睡的對象；先確認主動句確實有承受者。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S156_EX_01", prompt: "People use this room for music. This room ___ for music. (is used / uses)", steps: ["找出承受 use 的 this room。", "依單數 room 選 is。", "把 use 改成過去分詞 used。"], answer: "is used", why: "this room 原本是 use 的對象，成為被動句主詞後需用單數 is 加 used。uses 會把房間寫成主動使用其他東西，角色正好相反。" },
      { id: "ENG_R4_L_S156_EX_02", prompt: "Workers make these bags by hand. These bags ___ by hand. (are made / are making)", steps: ["確認 these bags 是複數承受者。", "以 are 配合複數主詞。", "使用 make 的過去分詞 made。"], answer: "are made", why: "袋子是被製作的物品，these bags 要搭配 are，make 的過去分詞是 made。are making 會表示袋子正在主動製作，與原句角色不合。" },
      { id: "ENG_R4_L_S156_EX_03", prompt: "Amy writes the school news. The school news ___ by Amy. (is written / is wrote)", steps: ["將 the school news 放到主詞位置。", "依不可數 news 使用 is。", "選 write 的過去分詞 written。"], answer: "is written", why: "school news 承受 Amy 的寫作動作，因此使用 is written。wrote 是一般過去式，不是 be 後需要的過去分詞，不能寫 is wrote。" },
    ],
    misconceptions: [
      { belief: "被動語態只要在原形動詞前加 be 就完成。", whyWrong: "be 後必須接過去分詞，不是任意動詞形式。", correction: "同時檢查 be 與主詞一致，以及主要動詞已改成過去分詞。" },
      { belief: "主動句的動作者是複數，被動句就一定用 are。", whyWrong: "be 動詞要配合移到主詞位置的承受者。", correction: "先找被動句新主詞，再決定 is 或 are。" },
      { belief: "wrote、written 都能放在 is 後表示被寫。", whyWrong: "wrote 是過去式，written 才是過去分詞。", correction: "使用 is written，並個別記住常見不規則三態。" },
      { belief: "任何主動句都能把最後一個字移到前面改成被動。", whyWrong: "沒有受詞的動詞缺少可成為被動主詞的承受者。", correction: "改寫前先確認動詞後確實有受詞。" },
    ],
    checks: [
      { prompt: "The book is read by Mia 中，被動結構是哪一段？", answer: "is read", reason: "is 配合單數 book，read 在此是過去分詞。" },
      { prompt: "These cups 應接 is washed 還是 are washed？", answer: "are washed", reason: "these cups 是複數主詞，需搭配 are。" },
      { prompt: "is wrote 能表示被寫嗎？", answer: "不能", reason: "be 後應使用 write 的過去分詞 written。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S157", "ENG_R4_S157", {
    objectives: ["依現在、過去、未來與情態語意調整被動句的 be 動詞。", "保留主要動詞的過去分詞，避免把時間標記重複放在兩個位置。"],
    sections: [
      { title: "被動句的時間由 be 動詞承擔", content: "The room is cleaned every day 是現在習慣，The room was cleaned yesterday 是過去事件。cleaned 都維持過去分詞，時間差別放在 is 與 was；不能因 yesterday 再把 cleaned 任意改成其他形式。" },
      { title: "未來被動使用 will be 加過去分詞", content: "The letter will be sent tomorrow 表示信明天才會被寄出。will 後用 be 原形，再接 sent；漏掉 be 的 will sent 和改用 will be sending 都不是這個未來被動結構。" },
      { title: "情態動詞後保留 be 原形", content: "The answer can be found on this page 與 The door must be kept closed 都採情態動詞加 be 再接過去分詞。can、must 已占據情態位置，因此不能改成 can is found 或 must was kept。" },
      { title: "時間線索要和事件意義相互驗證", content: "last night 通常引出 was 或 were，every morning 常用 is 或 are，next week 可用 will be。不過不能只抓單一時間字；還要確認主詞單複數與句子是在描述習慣、已發生事件或未來安排。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S157_EX_01", prompt: "The windows ___ yesterday morning. (were cleaned / are cleaned)", steps: ["由 yesterday morning 判定過去時間。", "windows 為複數，選 were。", "接 clean 的過去分詞 cleaned。"], answer: "were cleaned", why: "清理發生在昨天，且 windows 是複數，所以過去被動要用 were cleaned。are cleaned 會較像現在習慣，無法對應明確的過去時間。" },
      { id: "ENG_R4_L_S157_EX_02", prompt: "The results ___ tomorrow. (will be shared / were shared)", steps: ["由 tomorrow 找出未來安排。", "在 will 後保留 be 原形。", "接 share 的過去分詞 shared。"], answer: "will be shared", why: "結果尚未公布，tomorrow 要用未來被動 will be shared。were shared 會表示過去已公布，和時間線索及事件狀態都衝突。" },
      { id: "ENG_R4_L_S157_EX_03", prompt: "This picture can ___ from the back of the room. (be seen / is seen)", steps: ["辨認 can 是情態動詞。", "can 後接 be 原形。", "使用 see 的過去分詞 seen。"], answer: "be seen", why: "畫是被看見的對象，can 後需接 be seen。can is seen 同時放入情態動詞與限定 be 動詞，結構不成立。" },
    ],
    misconceptions: [
      { belief: "被動句不論時間都固定使用 is 加過去分詞。", whyWrong: "is 只能配合部分現在時單數主詞，無法涵蓋過去或未來。", correction: "先判時間，再依主詞選 is、are、was、were 或 will be。" },
      { belief: "will 後直接接過去分詞就能形成未來被動。", whyWrong: "未來被動仍需要 be 連接 will 與過去分詞。", correction: "完整寫成 will be sent、will be opened 等形式。" },
      { belief: "can 後面的 be 要依主詞改成 is 或 are。", whyWrong: "情態動詞後只能接原形，be 不隨主詞變化。", correction: "使用 can be found，不寫 can is found。" },
      { belief: "看到 yesterday 就把句中每個動詞都改成過去式。", whyWrong: "被動句只由 was 或 were 標記過去，後面仍是過去分詞。", correction: "把時態與分詞功能分開檢查。" },
    ],
    checks: [
      { prompt: "every day 的複數主詞通常使用哪個現在被動 be 動詞？", answer: "are", reason: "複數主詞的現在被動採 are 加過去分詞。" },
      { prompt: "will be sent 中，哪個部分標示未來？", answer: "will", reason: "will 提供未來時間，be sent 建立被動。" },
      { prompt: "must 後可寫 is kept 嗎？", answer: "不可", reason: "must 後需接原形 be，形成 must be kept。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S158", "ENG_R4_S158", {
    objectives: ["判斷被動句何時可以不寫動作者。", "省略未知、顯而易見或不重要的動作者，同時避免補入文本沒有提供的人。"],
    sections: [
      { title: "動作者未知時不必猜測", content: "My bike was taken last night 只報告腳踏車被拿走；若沒有人看到是誰做的，就不應自行加 by a man 或 by a student。被動句讓說話者在不知道動作者時仍能清楚交代事件。" },
      { title: "動作者顯而易見時可省略", content: "The test papers will be given out at nine 的重點是考卷發放時間。即使大家可推測由老師或監考人員發放，通知通常不必寫出動作者，因為這項資訊不影響讀者行動。" },
      { title: "焦點在結果或承受者時可省略", content: "The road was closed after the heavy rain 關心的是道路無法通行及其時間背景，不一定需要知道由哪個單位關閉。若文章後續要追究決策者，才有補出動作者的理由。" },
      { title: "省略不等於句子沒有動作來源", content: "A window was broken 仍表示某個力量造成破裂，只是句子沒有說明來源。閱讀時應把未知保留為未知，不能把未寫出的動作者當成不存在，也不能把承受者誤判為自行完成動作。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S158_EX_01", prompt: "No one saw what happened. A classroom window was broken during the night. Should the report say who did it?", steps: ["確認報告明說沒有人看見。", "找出已知事實是窗戶破裂。", "不補入無證據的動作者。"], answer: "No.", why: "報告只知道窗戶在夜間被打破，不知道誰或什麼造成。省略動作者能保留事實邊界；任意加上某個人會把猜測寫成證據。" },
      { id: "ENG_R4_L_S158_EX_02", prompt: "At school, lunch is served at twelve. What information matters most to students?", steps: ["辨認公告焦點是 lunch。", "找出讀者需要的時間 twelve。", "判斷服務人員身分不影響用餐。"], answer: "Lunch is available at twelve.", why: "學生需要知道午餐在十二點供應，而不是哪位工作人員端出餐點。省略顯而易見或不重要的動作者，能讓公告把焦點放在實用資訊。" },
      { id: "ENG_R4_L_S158_EX_03", prompt: "The lost wallet was found near the gate, but the note does not name a finder. What can the reader learn?", steps: ["讀取確定結果 was found。", "確認地點 near the gate。", "不推測找回錢包的人。"], answer: "The wallet was found; who found it is not known or important here.", why: "便條證明錢包已在門口附近找到，卻沒有提供發現者身分。讀者只能保留這個空缺，不能據此認定是老師、學生或警衛找到。" },
    ],
    misconceptions: [
      { belief: "被動句沒有 by 片語，就代表沒有人做這件事。", whyWrong: "動作者可能未知、明顯或與訊息目的無關。", correction: "把未寫出與不存在分開理解。" },
      { belief: "為了讓句子完整，應替每個被動句補一位可能的動作者。", whyWrong: "推測的人物可能沒有文本證據，反而改變事實。", correction: "只有來源提供或溝通目的需要時才補動作者。" },
      { belief: "公告省略動作者，是因為作者忘了寫。", whyWrong: "公告常刻意突出時間、地點、規則或受影響事物。", correction: "先判斷讀者真正需要哪項資訊。" },
      { belief: "省略動作者後，承受者就變成動作者。", whyWrong: "主詞位置改變不會改變它承受動作的語意角色。", correction: "仍以過去分詞和事件意思確認誰受到作用。" },
    ],
    checks: [
      { prompt: "沒有人知道誰拿走雨傘時，是否必須寫 by 片語？", answer: "不必", reason: "未知的動作者不應由寫作者猜測補入。" },
      { prompt: "The library will be opened at eight 的公告焦點可能是什麼？", answer: "開放時間", reason: "讀者需要知道八點可進入，開門者通常不重要。" },
      { prompt: "被動句省略動作者後，事件還有造成來源嗎？", answer: "有可能", reason: "句子只是沒有指明來源，並非否定來源存在。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S159", "ENG_R4_S159", {
    objectives: ["在動作者身分重要時，用 by 片語補充是誰完成動作。", "區分 by 加動作者與 with 加工具，避免把方法或器具誤當成執行者。"],
    sections: [
      { title: "by 片語回答動作由誰完成", content: "The picture was painted by Amy 中，by Amy 指出 Amy 是畫圖的人。當作品歸屬、責任或不同人物造成的結果需要區分時，動作者是重要資訊，不能一律省略。" },
      { title: "by 後可接人、團體或造成作用的力量", content: "The song was sung by the school team 以團體作動作者；The tree was hit by strong wind 則把自然力量視為事件來源。判斷重點是該名詞是否造成過去分詞所表示的動作。" },
      { title: "with 通常補充使用的工具", content: "The door was opened by Ben with a key 中，Ben 是開門的人，key 是他使用的工具。by a key 會把鑰匙寫得像自主執行開門，不符合這個情境；要分清誰做與用什麼做。" },
      { title: "只有有資訊價值時才保留 by 片語", content: "The school song was written by a student 可能要強調創作者；The floor is cleaned every day 則通常不必加 by the cleaner。若動作者沒有幫助讀者理解或比較，省略可使句子更集中。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S159_EX_01", prompt: "This story was written ___ Nora. (by / with)", steps: ["找出 written 表示寫作。", "確認 Nora 是完成寫作的人。", "用 by 引入動作者。"], answer: "by", why: "Nora 是故事的作者，也就是 written 的動作者，所以接 by Nora。with 會把 Nora 當成工具或伴隨物，無法表達作者關係。" },
      { id: "ENG_R4_L_S159_EX_02", prompt: "The box was opened by Leo with a small key. What role does the key have?", steps: ["找出 by Leo 指出的執行者。", "讀取 with a small key 的功能。", "把 key 判為開箱工具。"], answer: "It was the tool Leo used.", why: "Leo 主動開箱，small key 只是他使用的工具。句中已用 by 標出動作者，再以 with 補充方法，因此不能把 key 當成開箱者。" },
      { id: "ENG_R4_L_S159_EX_03", prompt: "Two teams made posters. This poster was made by the blue team. Why are the words by the blue team useful?", steps: ["確認有兩個可能的團隊。", "辨認 made 的作品是 this poster。", "用 by 片語區分實際製作者。"], answer: "They tell which team made the poster.", why: "前文提供兩個可能來源，by the blue team 能排除另一隊並指出作品歸屬。若刪除片語，讀者只知道海報被製作，無法完成比較。" },
    ],
    misconceptions: [
      { belief: "被動句中的 by 都表示靠近某個地方。", whyWrong: "在 by Amy、by the team 等結構中，by 引入動作者。", correction: "看 by 後名詞是否完成過去分詞所表示的動作。" },
      { belief: "工具也用 by 引入，因為它幫助動作完成。", whyWrong: "一般工具用 with，動作者才用 by。", correction: "寫 opened by Ben with a key，分開人與器具。" },
      { belief: "每個被動句都加 by people 會更完整。", whyWrong: "模糊而無用的動作者會稀釋句子焦點。", correction: "只在身分能補足來源、責任或對比時使用 by 片語。" },
      { belief: "by 片語中的名詞是被動句的承受者。", whyWrong: "承受者通常已在主詞位置，by 後放的是動作者。", correction: "將主詞與 by 後名詞還原成誰對誰做什麼。" },
    ],
    checks: [
      { prompt: "The song was written by Mia 中，誰寫歌？", answer: "Mia", reason: "by Mia 明確指出 written 的動作者。" },
      { prompt: "opened with a key 中，key 是動作者嗎？", answer: "不是", reason: "with 引入使用的工具，不是有意識的執行者。" },
      { prompt: "何時保留 by 片語最有價值？", answer: "動作者身分影響來源、責任或對比時", reason: "此時省略會讓讀者失去必要資訊。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S160", "ENG_R4_S160", {
    objectives: ["依上下文區分被動事件與過去分詞形成的狀態描述。", "不把每個 be 加過去分詞機械判成同一功能，並保留單句可能存在的歧義。"],
    sections: [
      { title: "被動事件關心動作何時或由誰發生", content: "The door was closed by Ben at six 清楚報告 Ben 在六點完成關門，by Ben 與 at six 都把 closed 當成事件。這類句子能回答誰做、何時做，焦點在動作發生。" },
      { title: "狀態描述關心目前或當時的情況", content: "The door is closed, so use the other door 重點是門現在處於關閉狀態，讓讀者改走別處。句子不必回答誰關門；closed 在語意上較接近描述門的情況。" },
      { title: "上下文比表面形式更重要", content: "The window was broken 單獨看可能描述破裂事件，也可能交代窗戶當時的狀態。若後面寫 by a ball，就偏向事件；若寫 so cold air came in，則結果狀態更重要。沒有證據時不應假裝只有一種讀法。" },
      { title: "完成結果常能延伸成狀態", content: "The work is finished 表示工作已在完成狀態，說話者常接著安排下一步。這不代表 finish 從未發生，而是句子選擇把完成後的結果放在焦點；判讀要依溝通目的而非只看字形。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S160_EX_01", prompt: "The gate was locked by Sam at nine. Is locked mainly an event or a state here?", steps: ["找出動作者 by Sam。", "讀取明確時間 at nine。", "判斷句子在報告鎖門動作。"], answer: "An event.", why: "by Sam 說明誰鎖門，at nine 指出動作發生時間，兩項證據都把 locked 當成一次事件，而不是只描述門後來的狀態。" },
      { id: "ENG_R4_L_S160_EX_02", prompt: "A sign says, 'Use another entrance because this shop is closed now.' What does closed tell people?", steps: ["注意 now 指向目前。", "讀取不能進入的結果。", "把 closed 解為商店現況。"], answer: "The shop cannot be entered now.", why: "句子要讓讀者知道現在無法進入，沒有交代關店的人或關店動作。closed 的功能是描述商店目前不開放的狀態。" },
      { id: "ENG_R4_L_S160_EX_03", prompt: "The glass was broken. Can this sentence alone show who broke it?", steps: ["確認句中沒有 by 片語。", "檢查是否提供原因或人物。", "保留未確定的動作者。"], answer: "No.", why: "單句只說 glass 處於破裂結果或曾受到破壞，沒有任何人物證據。讀者不能從 was broken 推出是誰造成，也不能確定作者主要在敘述事件還是狀態。" },
    ],
    misconceptions: [
      { belief: "只要看到 be 加過去分詞，就一定是在報告一次被動事件。", whyWrong: "有些句子以過去分詞描述結果或當下狀態。", correction: "利用動作者、時間、原因與後續結果判斷焦點。" },
      { belief: "狀態描述表示先前從未發生任何動作。", whyWrong: "狀態可能正是先前動作留下的結果。", correction: "區分事件是否存在與句子目前選擇的焦點。" },
      { belief: "The window was broken 單獨出現時只能有一種分析。", whyWrong: "缺少情境時，事件與結果狀態都可能合理。", correction: "承認歧義並等待上下文提供證據。" },
      { belief: "只要有 now，句子就不可能包含被動語態。", whyWrong: "現在時間也能敘述正在或固定發生的被動事件。", correction: "時間詞只是線索之一，還要看動作與溝通目的。" },
    ],
    checks: [
      { prompt: "by Ben at five 比較支持事件還是狀態？", answer: "事件", reason: "動作者與明確時間共同定位一次動作。" },
      { prompt: "is closed, so use another door 主要描述什麼？", answer: "目前關閉的狀態", reason: "後續指示建立在讀者現在無法通行的情況。" },
      { prompt: "缺少上下文時，能否強迫 was broken 只有一種解讀？", answer: "不能", reason: "事件與結果狀態可能需要更多語境才能區分。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S161", "ENG_R4_S161", {
    objectives: ["在通知、公告與簡短說明中找出被動句真正突出的資訊。", "依受影響事物、時間、地點與規則採取行動，不因動作者省略而誤讀通知。"],
    sections: [
      { title: "通知常把受影響的事物放在句首", content: "The library will be closed on Friday 先寫 library，因為讀者關心哪個地方受影響。公告沒有必要指出誰關閉圖書館；真正影響使用者的是 Friday 無法使用。" },
      { title: "規則用被動句集中在物品或行為", content: "Bikes must be left outside 告訴騎車者腳踏車應放在哪裡。must be left 表達規定，outside 提供行動位置；讀者不應把它誤解成腳踏車會自己離開。" },
      { title: "時間與地點常比動作者重要", content: "Lunch is served at twelve in the hall 中，學生要找的是供餐時間和地點。通知選擇省略服務人員，使資訊更短；閱讀時應把 at twelve 與 in the hall 連回 served。" },
      { title: "判讀後要能推出合乎證據的行動", content: "The game was moved to Saturday because of rain 能推出原定日期已改、觀眾應在星期六前往，卻不能推出比賽取消。通知題常測讀者是否區分明示改動與自己額外猜出的結果。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S161_EX_01", prompt: "Notice: The music room will be used for a meeting after three. Where should students avoid practicing then?", steps: ["找出受影響地點 the music room。", "讀取時間 after three。", "把會議用途轉成行動判斷。"], answer: "The music room.", why: "公告說三點後音樂教室會作為會議場地，因此學生不該在那段時間進去練習。句子沒有禁止全天使用，也沒有關閉其他教室。" },
      { id: "ENG_R4_L_S161_EX_02", prompt: "Notice: All library books must be returned by Friday. What must a student do?", steps: ["辨認受規則影響的是 all library books。", "理解 must be returned 是義務。", "以 by Friday 確認期限。"], answer: "Return every library book no later than Friday.", why: "must be returned 把歸還責任放在所有借書上，by Friday 是最晚期限。公告沒有說只還一本，也沒有把 Friday 解成開始歸還的日期。" },
      { id: "ENG_R4_L_S161_EX_03", prompt: "Notice: The afternoon game was moved to the school hall because of rain. What changed?", steps: ["找出被移動的是 afternoon game。", "辨認新地點 the school hall。", "不把地點改變誤讀成取消。"], answer: "The place of the game.", why: "because of rain 說明改動原因，to the school hall 指出新場地。比賽仍在下午，公告沒有表示活動取消或改到另一日。" },
    ],
    misconceptions: [
      { belief: "公告沒寫動作者，就無法知道讀者該做什麼。", whyWrong: "時間、地點、受影響物與情態動詞通常已提供行動依據。", correction: "先提取通知中的規則與變更，再判斷讀者責任。" },
      { belief: "was moved 一定表示活動被取消。", whyWrong: "move 表示改變時間或地點，和 cancel 的意義不同。", correction: "找 to 後的新時間或地點，保留活動仍舉行的可能。" },
      { belief: "by Friday 表示只能在星期五當天完成。", whyWrong: "期限片語表示不晚於星期五，提前也符合。", correction: "把 by 加時間理解為最晚完成點。" },
      { belief: "must be left outside 表示物品會自己移到外面。", whyWrong: "被動規則省略了負責移動物品的人。", correction: "由持有人執行規定，物品是承受移動的對象。" },
    ],
    checks: [
      { prompt: "The pool will be closed on Monday 中，讀者最需要哪項資訊？", answer: "星期一不能使用游泳池", reason: "公告把受影響設施與日期放在焦點。" },
      { prompt: "must be kept inside 是描述建議還是規定？", answer: "規定", reason: "must 表示必須遵守的要求。" },
      { prompt: "was moved to Sunday 能直接推出活動取消嗎？", answer: "不能", reason: "句子只明示日期改到星期日。" },
    ], assets: [],
  }),
];

export const ENGLISH_U23_QUESTIONS = [
  ...skillQuestions("155", [
    { stem: "Mia carried the box upstairs. Who carried something?", options: ["Mia", "The box", "The stairs", "No one"], answerIndex: 0, reasons: ["Mia 是 carried 的主詞，執行搬運動作。", "the box 是被搬運的物品，不是搬運者。", "upstairs 說明移動方向，並非動作者。", "句子明確提供 Mia，不能判為無人執行。"], reviews: ["核心結構是 Mia carried the box，主詞與動作者一致。", "第一項能回答誰做了 carrying，其他項只表示物品、方向或否定。"], cognitiveProcess: ["u23-s155-locate-carrier-in-upstairs-event", "separate-agent-object-direction"], representationType: "active-agent-identification", misconceptionTargets: ["treat-nearest-noun-as-agent"] },
    { stem: "Ben opened the window before class. What received the action?", options: ["Ben", "The window", "The class", "The time"], answerIndex: 1, reasons: ["Ben 主動執行 opened，不是承受者。", "the window 是 Ben 打開的對象。", "class 出現在時間片語中，沒有受到 open。", "before 只標示時間關係，不構成物件角色。"], reviews: ["opened 把動作從 Ben 指向 the window。", "第二項是唯一能接在 Ben opened 之後作受詞的實際對象。"], cognitiveProcess: ["u23-s155-find-opened-receiver-before-class", "exclude-time-noun-from-object-role"], representationType: "active-receiver-identification", misconceptionTargets: ["mistake-background-noun-for-receiver"] },
    { stem: "The dog followed Nora to the park. What happened?", options: ["Nora followed the dog.", "The park followed Nora.", "Nora was the person the dog followed.", "Nora and the dog stayed home."], answerIndex: 2, reasons: ["這一項交換了動作者與承受者。", "park 是目的地，不能執行 followed。", "the dog 是跟隨者，Nora 是被跟隨的人。", "原句提到前往 park，並非兩者留在家中。"], reviews: ["followed 前的 the dog 決定跟隨動作的來源。", "第三項保留原來的角色與移動方向，沒有增添 Nora 必須走在何處。"], cognitiveProcess: ["u23-s155-map-following-roles-to-paraphrase", "reject-role-reversal-and-location-agent"], representationType: "active-role-paraphrase", misconceptionTargets: ["reverse-agent-and-receiver"] },
    { stem: "After lunch, Amy called Leo from the office. Who received the call?", options: ["Lunch", "Amy", "The office", "Leo"], answerIndex: 3, reasons: ["lunch 只位於時間片語，不會接電話。", "Amy 是發出電話的人。", "the office 說明 Amy 所在位置。", "Leo 是 called 的受詞，因此收到電話。"], reviews: ["略過 After lunch 與 from the office，核心句剩下 Amy called Leo。", "第四項是通話動作的接收者，並未把地點誤判成人物。"], cognitiveProcess: ["u23-s155-strip-time-place-to-find-call-receiver", "retain-object-after-called"], representationType: "background-filtered-role-reading", misconceptionTargets: ["let-background-phrases-control-role"] },
    { stem: "A falling branch broke the kitchen window. What caused the damage?", options: ["A falling branch", "The kitchen", "The window", "The damage"], answerIndex: 0, reasons: ["a falling branch 是 broke 的主詞與破壞來源。", "kitchen 只修飾 window 所在的位置。", "the window 承受破裂結果。", "damage 是題目對結果的概括，不是句中動作者。"], reviews: ["即使動作者不是人，自然物也能造成 broke 所表示的作用。", "第一項位於主要動詞前，且語意上確實能擊破窗戶。"], cognitiveProcess: ["u23-s155-identify-natural-force-as-agent", "separate-location-modifier-from-cause"], representationType: "nonhuman-agent-analysis", misconceptionTargets: ["require-human-agent"] },
    { stem: "Ben showed Nora a map. Who did Ben show the map to?", options: ["Ben", "Nora", "The map", "No person"], answerIndex: 1, reasons: ["Ben 執行 showed，不是地圖展示的接收者。", "Nora 是 Ben 展示地圖的對象。", "map 是被展示的物品，不能接收自己。", "句子明確寫出 Nora，不能說沒有人接收。"], reviews: ["showed 後的 Nora 是接收者，a map 是被展示內容。", "第二項根據雙受詞結構保留人物與物品的不同角色。"], cognitiveProcess: ["u23-s155-resolve-recipient-in-show-double-object", "distinguish-person-recipient-from-shown-item"], representationType: "double-object-role-inference", misconceptionTargets: ["treat-shown-item-as-recipient"] },
    { stem: "The students moved the chairs into the hall. What was moved?", options: ["The students", "The hall", "The chairs", "The lesson"], answerIndex: 2, reasons: ["students 是 moved 的動作者。", "hall 是移動目的地，不是被搬動的東西。", "the chairs 承受 moved 並進入大廳。", "lesson 未出現在句子中，沒有文本依據。"], reviews: ["into the hall 說明 chairs 的終點，不能把 hall 當受詞。", "第三項在動詞後直接承接移動作用，也符合複數語意。"], cognitiveProcess: ["u23-s155-track-moved-object-to-hall", "exclude-destination-from-patient-role"], representationType: "movement-patient-identification", misconceptionTargets: ["confuse-destination-with-moved-object"] },
    { stem: "The cat followed Sam across the yard. What role does Sam have?", options: ["He is the place they crossed.", "He is the animal that followed.", "He is not part of the event.", "He is the person being followed."], answerIndex: 3, reasons: ["yard 才是被穿越的地方，Sam 不是地點。", "the cat 是執行 followed 的動物。", "Sam 是 followed 的受詞，明確參與事件。", "Sam 位在 followed 後，是被貓跟隨的人。"], reviews: ["across the yard 只補充路徑，角色核心仍是 the cat followed Sam。", "第四項沒有因 Sam 是人就自動把他改成動作者。"], cognitiveProcess: ["u23-s155-assign-followed-person-role-across-yard", "resist-animacy-based-agent-switch"], representationType: "object-role-description", misconceptionTargets: ["assume-human-is-always-agent"] },
    { stem: "Leo slept well after the trip. What does the sentence tell us?", options: ["Leo slept, but the action did not pass to another person or thing.", "The trip received the sleeping action.", "Someone put Leo to sleep.", "Well is the person who slept."], answerIndex: 0, reasons: ["Leo 是 slept 的主詞，而此句沒有受詞。", "after the trip 是時間背景，trip 不承受 sleep。", "原文沒有說另一個人使 Leo 入睡。", "well 是副詞，描述睡眠情況，不是人物。"], reviews: ["sleep 在此不把動作傳到另一個對象，因此不必硬找承受者。", "第一項同時承認 Leo 的動作者角色與受詞缺席。"], cognitiveProcess: ["u23-s155-recognize-intransitive-sleep-role-set", "avoid-inventing-receiver-or-causer"], representationType: "no-receiver-active-analysis", misconceptionTargets: ["force-object-into-intransitive-clause"] },
    { stem: "A truck hit the sign near the bridge. What received the hit?", options: ["The truck", "The sign", "The bridge", "The road"], answerIndex: 1, reasons: ["truck 是造成碰撞的主詞，不是承受者。", "the sign 是 hit 後的受詞，承受卡車碰撞。", "bridge 只說明事件附近的地點。", "road 沒有出現在原句，也不是可推得的承受者。"], reviews: ["先略過 near the bridge，核心句是 A truck hit the sign。", "第二項直接承接 hit 的作用，角色與句子位置都吻合。"], cognitiveProcess: ["u23-s155-identify-hit-receiver-near-bridge", "filter-prepositional-location-from-core-roles"], representationType: "collision-receiver-identification", misconceptionTargets: ["reverse-action-direction"] },
    { stem: "Amy gave Ben the key to the art room. Which fact is supported?", options: ["Amy received the key from Ben.", "The art room gave away a key.", "Ben received the key from Amy.", "The key opened the room by itself."], answerIndex: 2, reasons: ["原句中 Amy 是給予者，不是接收者。", "art room 只說明 key 的用途，不能給東西。", "Ben 是 gave 後的接收者，key 來自 Amy。", "句子沒有說鑰匙自行開門。"], reviews: ["gave 的角色依序是 Amy、Ben、the key，分別為給予者、接收者與物品。", "第三項保留轉移方向，也不把 to the art room 誤當目的動作。"], cognitiveProcess: ["u23-s155-reconstruct-transfer-roles-from-gave", "separate-key-purpose-from-agenthood"], representationType: "transfer-role-inference", misconceptionTargets: ["reverse-giver-and-recipient"] },
    { stem: "Near the gate, Nora found Mia's notebook under a chair. Who found the notebook?", options: ["The gate", "Mia", "A chair", "Nora"], answerIndex: 3, reasons: ["gate 位於地點片語，沒有執行 found。", "Mia 是 notebook 的所有人，不等於發現者。", "chair 提供物品所在位置。", "Nora 是 found 的主詞，完成尋獲動作。"], reviews: ["所有格 Mia's 只連結筆記本歸屬，不能取代句子主詞。", "第四項在去除兩個地點片語後仍是核心句的動作者。"], cognitiveProcess: ["u23-s155-find-agent-amid-possession-and-location", "distinguish-owner-locator-and-finder"], representationType: "possessive-role-disambiguation", misconceptionTargets: ["mistake-owner-for-agent"] },
  ]),
  ...skillQuestions("156", [
    { stem: "The reading room ___ every afternoon.", options: ["is cleaned", "cleans", "is cleaning", "cleaned is"], answerIndex: 0, reasons: ["is cleaned 以單數 be 加過去分詞表示房間被清理。", "cleans 會把 reading room 寫成主動清理其他東西。", "is cleaning 缺少房間主動清理的受詞，也不是目標被動。", "cleaned is 顛倒 be 與過去分詞的順序。"], reviews: ["every afternoon 表示固定清理，room 是承受者。", "第一項同時符合單數主詞與 be + p.p. 結構。"], cognitiveProcess: ["u23-s156-form-singular-routine-passive", "reject-room-as-cleaning-agent"], representationType: "present-passive-cloze-singular", misconceptionTargets: ["omit-or-misorder-passive-be"] },
    { stem: "These bags ___ by hand.", options: ["is made", "are made", "are making", "make"], answerIndex: 1, reasons: ["is made 不和複數 these bags 一致。", "are made 表示這些袋子由手工製作。", "are making 把 bags 變成正在製作的動作者。", "make 是主動原形，沒有建立承受關係。"], reviews: ["these bags 是複數被動主詞，必須搭配 are。", "第二項使用 make 的不規則過去分詞 made。"], cognitiveProcess: ["u23-s156-agree-plural-bags-with-made", "separate-made-participle-from-making"], representationType: "plural-passive-agreement-cloze", misconceptionTargets: ["choose-be-from-original-agent"] },
    { stem: "The school news ___ by two students.", options: ["writes", "is wrote", "is written", "writing"], answerIndex: 2, reasons: ["writes 會使 news 成為寫作者。", "is wrote 把一般過去式錯放在 be 後。", "is written 正確表示校園新聞由學生撰寫。", "writing 既缺少 be，也沒有完成句子的限定動詞。"], reviews: ["news 在此視為單數內容，使用 is。", "第三項採 write 的過去分詞 written，而不是 wrote。"], cognitiveProcess: ["u23-s156-select-irregular-written-after-is", "block-past-form-wrote-in-passive"], representationType: "irregular-participle-passive-cloze", misconceptionTargets: ["equate-past-tense-with-past-participle"] },
    { stem: "The windows ___ before the students arrive.", options: ["opens", "are opening", "opened", "are opened"], answerIndex: 3, reasons: ["opens 不和複數 windows 一致，也把窗戶當動作者。", "are opening 表示窗戶正在主動開啟，與安排的被動焦點不同。", "opened 缺少建立現在被動所需的 be 動詞。", "are opened 以複數 are 加 opened 表示窗戶被打開。"], reviews: ["before 子句交代固定流程，windows 是受影響項目。", "第四項保留 opened 為過去分詞，並以 are 配合複數。"], cognitiveProcess: ["u23-s156-complete-window-preparation-passive", "distinguish-process-arrangement-from-progressive"], representationType: "scheduled-passive-form-cloze", misconceptionTargets: ["drop-be-before-participle"] },
    { stem: "People keep the door locked at night. Which sentence puts the door first and keeps the same meaning?", options: ["The door is kept locked at night.", "The door keeps people locked at night.", "People are kept by the door at night.", "At night keeps the door locked."], answerIndex: 0, reasons: ["第一項把 door 移成主詞並用 is kept，原意不變。", "第二項把門誤寫成囚禁人的動作者。", "第三項改成 people 被門留住，角色顛倒。", "第四項把時間片語當成動作者，結構與語意都不成立。"], reviews: ["主動句中 the door 承受 keep，所以能成為被動焦點。", "第一項仍保留 people 不重要而省略的安排，沒有創造新角色。"], cognitiveProcess: ["u23-s156-transform-keep-door-active-to-passive", "preserve-locked-result-complement"], representationType: "active-to-passive-focus-shift", misconceptionTargets: ["move-wrong-active-role-to-subject"] },
    { stem: "The class sings this song every Friday. This song ___ every Friday.", options: ["sings", "is sung", "is sang", "singing"], answerIndex: 1, reasons: ["sings 會讓 song 成為唱歌的人。", "is sung 使用 sing 的過去分詞，保留歌曲被演唱。", "is sang 把過去式 sang 誤作過去分詞。", "singing 缺少 be 動詞，也不能單獨完成句子。"], reviews: ["this song 原本是 sings 的受詞，改寫後成為單數主詞。", "第二項的 sung 是正確不規則分詞，every Friday 不改變它。"], cognitiveProcess: ["u23-s156-convert-song-object-with-sung", "differentiate-sang-and-sung"], representationType: "irregular-active-passive-conversion", misconceptionTargets: ["use-irregular-past-instead-of-participle"] },
    { stem: "The office sends these letters on Monday. These letters ___ on Monday.", options: ["send", "is sent", "are sent", "are sending"], answerIndex: 2, reasons: ["send 是主動原形，沒有配合複數主詞形成被動。", "is sent 的 is 不和 these letters 一致。", "are sent 正確表示信件被寄出。", "are sending 把信件當成正在寄東西的動作者。"], reviews: ["letters 從主動句受詞移到被動句主詞位置。", "第三項由複數 are 和 sent 組成，時間仍由 on Monday 補充。"], cognitiveProcess: ["u23-s156-build-plural-sent-passive-from-office", "maintain-letter-patient-role"], representationType: "plural-active-passive-rewrite", misconceptionTargets: ["singular-be-with-plural-patient"] },
    { stem: "Ben rides the blue bike to school. The blue bike ___ by Ben.", options: ["rides", "is rode", "riding", "is ridden"], answerIndex: 3, reasons: ["rides 會把 bike 當成騎乘者。", "is rode 使用一般過去式 rode，不是過去分詞。", "riding 缺少 be，也沒有表明車承受騎乘。", "is ridden 採 ride 的過去分詞 ridden，角色正確。"], reviews: ["blue bike 原本是 rides 的受詞，改寫後用單數 is。", "第四項保留 Ben 為 by 片語中的騎車者。"], cognitiveProcess: ["u23-s156-form-ridden-passive-for-bike", "preserve-rider-in-by-phrase"], representationType: "irregular-ridden-passive-conversion", misconceptionTargets: ["use-rode-after-be"] },
    { stem: "Food ___ cold in this box.", options: ["is kept", "keeps", "is keeping", "kept"], answerIndex: 0, reasons: ["is kept 表示食物被保持在低溫狀態。", "keeps 會需要 food 主動保存別的東西。", "is keeping 把 food 變成持續執行 keep 的動作者。", "kept 缺少現在被動所需的 be 動詞。"], reviews: ["cold 是 food 被維持的結果，不是另一個動作。", "第一項以 is kept 建立被動，再由 cold 補足狀態。"], cognitiveProcess: ["u23-s156-complete-kept-result-passive", "link-food-patient-to-cold-state"], representationType: "passive-with-result-complement", misconceptionTargets: ["read-patient-as-keeper"] },
    { stem: "A student wrote 'The report is wrote in English.' Which change fixes is wrote?", options: ["Change is to are.", "Change wrote to written.", "Take out in English.", "Change report to reports."], answerIndex: 1, reasons: ["report 是單數，is 不需要改成 are。", "be 後要用 write 的過去分詞 written。", "in English 提供語言資訊，並非錯誤來源。", "改成 reports 會改變原意，仍未修正 wrote。"], reviews: ["錯誤集中在 is 後的動詞形式，不在主詞或介系詞片語。", "第二項形成 The report is written in English，且只修改必要部分。"], cognitiveProcess: ["u23-s156-repair-is-wrote-to-written", "isolate-participle-error-from-agreement"], representationType: "targeted-passive-error-repair", misconceptionTargets: ["repair-correct-be-instead-of-participle"] },
    { stem: "People sell fruit here in the morning. Which sentence focuses on the fruit without changing the fact?", options: ["Fruit sells people here in the morning.", "Here is sold by fruit in the morning.", "Fruit is sold here in the morning.", "People are fruit in the morning."], answerIndex: 2, reasons: ["第一項把 fruit 誤寫成賣東西的動作者。", "第二項把地點副詞 here 當成被賣的主詞。", "第三項將 fruit 移為焦點並保留販售地點與時間。", "第四項改變 people 與 fruit 的關係，完全不是原句事實。"], reviews: ["fruit 是 sell 的承受者，因此可用 is sold 成為被動主詞。", "第三項省略一般賣方，沒有把 morning 或 here 當成角色。"], cognitiveProcess: ["u23-s156-refocus-selling-event-on-fruit", "preserve-place-time-under-passivization"], representationType: "fact-preserving-passive-selection", misconceptionTargets: ["passivize-adverb-instead-of-object"] },
    { stem: "The meals are cooked by Sam. Which sentence keeps who cooks what?", options: ["The meals cook Sam.", "Sam is cooked by the meals.", "Sam and the meals cook.", "Sam cooks the meals."], answerIndex: 3, reasons: ["第一項讓 meals 變成動作者並作用於 Sam。", "第二項把 Sam 寫成被烹煮的對象。", "第三項沒有交代誰烹煮什麼，也改變句意。", "第四項把 by Sam 還原為主詞，the meals 還原為受詞。"], reviews: ["被動主詞 meals 是承受者，by Sam 提供真正動作者。", "第四項準確恢復 Sam 對 meals 執行 cooks 的方向。"], cognitiveProcess: ["u23-s156-restore-active-roles-from-cooked-passive", "avoid-edible-agent-reversal"], representationType: "passive-to-active-role-restoration", misconceptionTargets: ["treat-passive-subject-as-active-agent"] },
  ]),
  ...skillQuestions("157", [
    { stem: "The front door ___ every morning before eight.", options: ["is checked", "was checked", "will be checked", "checks"], answerIndex: 0, reasons: ["is checked 符合 every morning 的現在例行被動。", "was checked 只指一次過去檢查，與每日習慣不合。", "will be checked 把例行事實縮成未來事件。", "checks 會把 front door 寫成檢查者。"], reviews: ["before eight 補充每日檢查時間，主詞 door 是承受者。", "第一項以 is 承擔現在時間，checked 維持過去分詞。"], cognitiveProcess: ["u23-s157-align-daily-door-check-with-present-passive", "exclude-past-future-and-active-forms"], representationType: "routine-time-passive-cloze", misconceptionTargets: ["choose-tense-from-event-imagination"] },
    { stem: "The classroom walls ___ last summer.", options: ["are painted", "were painted", "will be painted", "paint"], answerIndex: 1, reasons: ["are painted 表示現在習慣，沒有對應 last summer。", "were painted 以複數過去被動描述去年夏天的粉刷。", "will be painted 會把事件放到未來。", "paint 把 walls 當成主動粉刷者。"], reviews: ["last summer 鎖定過去，walls 又要求 were。", "第二項只在 be 動詞標過去，painted 保留分詞功能。"], cognitiveProcess: ["u23-s157-set-past-plural-be-for-wall-painting", "retain-participle-under-last-summer"], representationType: "past-plural-passive-cloze", misconceptionTargets: ["use-present-be-with-past-time"] },
    { stem: "The new bridge ___ next year.", options: ["was finished", "finishes", "will be finished", "is finishing"], answerIndex: 2, reasons: ["was finished 表示橋已在過去完成。", "finishes 使 bridge 成為完成其他事物的動作者。", "will be finished 對應 next year 的未來被動。", "is finishing 把橋寫成主動進行完成動作。"], reviews: ["next year 表示工程完成仍在未來。", "第三項包含 will be，finished 則指出橋是被完成的對象。"], cognitiveProcess: ["u23-s157-build-future-passive-for-bridge-completion", "separate-project-patient-from-builder"], representationType: "future-passive-cloze", misconceptionTargets: ["omit-be-after-will"] },
    { stem: "The mountain can ___ from the train on a clear day.", options: ["sees", "is seen", "seen", "be seen"], answerIndex: 3, reasons: ["sees 會讓 mountain 成為觀看者。", "can is seen 把兩個限定形式並列，結構不成立。", "seen 前缺少情態被動所需的 be。", "be seen 正確接在 can 後，表示山能被看見。"], reviews: ["can 已經是情態動詞，後面只能接原形 be。", "第四項讓 train 上的人是省略的觀看者，mountain 保持承受角色。"], cognitiveProcess: ["u23-s157-complete-modal-passive-visibility", "insert-base-be-after-can"], representationType: "modal-passive-form-cloze", misconceptionTargets: ["use-finite-be-after-modal"] },
    { stem: "The missing bag ___ near the bus stop yesterday.", options: ["was found", "is found", "will be found", "finds"], answerIndex: 0, reasons: ["was found 同時符合單數 bag、過去時間與被尋獲結果。", "is found 較像現在習慣或目前敘述，未對應 yesterday。", "will be found 表示尚未找到，與句中地點資訊不合。", "finds 會把 bag 寫成尋找者。"], reviews: ["yesterday 把 find 事件放在過去，near the bus stop 提供發現地點。", "第一項採 find 的過去分詞 found，沒有另加未知發現者。"], cognitiveProcess: ["u23-s157-anchor-found-bag-to-yesterday", "avoid-future-result-contradiction"], representationType: "past-result-passive-cloze", misconceptionTargets: ["confuse-found-form-with-active-present"] },
    { stem: "These computers ___ during Friday classes.", options: ["was used", "are used", "will used", "using"], answerIndex: 1, reasons: ["was used 不和複數 computers 一致。", "are used 表示電腦在星期五課堂中固定被使用。", "will used 缺少 be，且 Friday classes 不必然只指未來。", "using 沒有 be 動詞，無法完成句子。"], reviews: ["these computers 要搭配 are，during Friday classes 描述常態用途。", "第二項保持 used 為過去分詞，而不是因 classes 改變動詞。"], cognitiveProcess: ["u23-s157-match-recurring-class-use-to-are-used", "resolve-plural-agreement-and-schedule"], representationType: "scheduled-present-passive", misconceptionTargets: ["use-singular-past-be-with-plural"] },
    { stem: "The photo ___ to every team next Monday.", options: ["sent", "was sent", "will be sent", "will sent"], answerIndex: 2, reasons: ["sent 單獨缺少限定動詞。", "was sent 會表示照片已在過去寄出。", "will be sent 正確對應 next Monday 的未來安排。", "will sent 漏掉被動結構中的 be。"], reviews: ["照片是寄送的承受者，next Monday 又要求未來。", "第三項以 will 標未來、be sent 建立被動，三部分都不可省略。"], cognitiveProcess: ["u23-s157-compose-future-sent-photo-schedule", "detect-missing-be-after-will"], representationType: "future-delivery-passive", misconceptionTargets: ["drop-passive-auxiliary-in-future"] },
    { stem: "This medicine must ___ away from young children.", options: ["keeps", "is kept", "kept", "be kept"], answerIndex: 3, reasons: ["keeps 會讓 medicine 主動保存其他東西。", "must is kept 在情態動詞後錯用限定 is。", "kept 前缺少 must 後的 be。", "be kept 完成 must + be + p.p.，表示藥品必須被妥善放置。"], reviews: ["must 表示規則，medicine 是受到保管要求的物品。", "第四項的 be 不隨單數 medicine 改成 is，因為它位於 must 後。"], cognitiveProcess: ["u23-s157-form-must-be-kept-safety-rule", "hold-base-be-after-modal-obligation"], representationType: "modal-rule-passive-cloze", misconceptionTargets: ["agree-be-after-modal"] },
    { stem: "The chairs were moved into the hall last night. When were they moved?", options: ["Before today", "Every night", "Later today", "Right now"], answerIndex: 0, reasons: ["last night 位於今天之前，與 were moved 的過去時間一致。", "原句只說昨晚一次，沒有 every night 的反覆意思。", "later today 指尚未發生的未來時間。", "right now 是現在，與 last night 衝突。"], reviews: ["were moved 和 last night 都把搬動事件放在過去。", "第一項只回答題目所問的時間，沒有加入習慣或未來安排。"], cognitiveProcess: ["u23-s157-infer-time-from-were-moved-last-night", "reject-habit-future-and-present-time"], representationType: "passive-event-time-identification", misconceptionTargets: ["ignore-passive-auxiliary-tense"] },
    { stem: "Every afternoon, the mail is brought to the office. What does the sentence mean?", options: ["The mail brings people to the office every afternoon.", "Someone brings the mail to the office every afternoon.", "Someone brought the mail there only once in the past.", "Someone will begin bringing the mail next year."], answerIndex: 1, reasons: ["mail 是 brought 的承受者，不會載人前往辦公室。", "第二項保留省略的動作者、mail 的承受角色與每日安排。", "every afternoon 表示反覆發生，不是過去僅一次。", "句子使用現在式，也沒有 next year 的未來資訊。"], reviews: ["is brought 和 every afternoon 共同表達目前的固定送件安排。", "第二項改成主動敘述後，時間、地點與角色都沒有改變。"], cognitiveProcess: ["u23-s157-paraphrase-present-mail-routine", "combine-passive-role-and-frequency-cue"], representationType: "present-routine-passive-paraphrase", misconceptionTargets: ["reverse-mail-role-or-change-timeline"] },
    { stem: "The old station will be changed into a library next year. Which part carries the future time?", options: ["old station", "be changed", "will", "into a library"], answerIndex: 2, reasons: ["old station 是被改建的主詞，不標時間。", "be changed 建立被動，但單獨不指出未來。", "will 明確承擔未來時間。", "into a library 說明改建結果，不是時態標記。"], reviews: ["next year 與 will 相互呼應，changed 仍保持過去分詞。", "第三項說明被動結構中時態與主要動詞形式分工。"], cognitiveProcess: ["u23-s157-isolate-future-marker-in-station-change", "distinguish-result-phrase-from-tense"], representationType: "future-auxiliary-component-analysis", misconceptionTargets: ["assign-future-to-past-participle"] },
    { stem: "A visitor asks whether the back door can be opened after six. Which answer keeps the same time and meaning?", options: ["It opened every day before six.", "Someone was opening it at six.", "Opening it is never possible.", "It is possible for someone to open it after six."], answerIndex: 3, reasons: ["第一項改成過去或習慣且把時間改為六點前。", "第二項使用過去進行，沒有保留 can 的可能性。", "第三項把詢問的可能性改成永遠不可能。", "第四項還原 can be opened 的可能被開啟語意。"], reviews: ["can be opened 不保證門一定會開，只詢問是否可能。", "第四項保留 after six 和省略的開門者，沒有擅自作出否定。"], cognitiveProcess: ["u23-s157-paraphrase-modal-passive-door-possibility", "preserve-time-window-and-unknown-agent"], representationType: "modal-passive-meaning-transfer", misconceptionTargets: ["turn-possibility-into-event-or-ban"] },
  ]),
  ...skillQuestions("158", [
    { stem: "No one saw what happened. A window was broken during the night. Which report uses only the known facts?", options: ["A window was broken during the night.", "Ben broke a window during the night.", "A student broke the window for fun.", "The wind must have broken the window."], answerIndex: 0, reasons: ["第一項只陳述窗戶被打破與時間，沒有虛構來源。", "沒有人看見，不能指定 Ben。", "原文沒有提供學生或動機的證據。", "風雖可能造成破壞，但 must have 超出已知事實。"], reviews: ["被動句在動作者未知時能保留事件而不製造嫌疑人。", "第一項是唯一沒有添加人物、原因或確定語氣的報告。"], cognitiveProcess: ["u23-s158-report-broken-window-with-unknown-agent", "reject-invented-person-motive-and-cause"], representationType: "evidence-bounded-passive-report", misconceptionTargets: ["invent-agent-to-complete-passive"] },
    { stem: "School notice: Lunch is served at twelve. Why is no worker named?", options: ["No one prepares lunch.", "The serving time is the useful information.", "Students must guess whether lunch exists.", "The word served means students cook it."], answerIndex: 1, reasons: ["被動句沒有否定有人準備或供應午餐。", "公告要讓學生知道十二點可用餐，服務者身分不重要。", "is served 已確認午餐會供應，無須猜測是否存在。", "served 表示午餐受到供應，不代表學生負責烹煮。"], reviews: ["通知選擇省略可預期的工作人員，把版面留給時間。", "第二項能說明資訊焦點，也沒有把省略誤解為無人做事。"], cognitiveProcess: ["u23-s158-explain-agent-omission-in-lunch-notice", "prioritize-reader-relevant-service-time"], representationType: "notice-agent-omission-rationale", misconceptionTargets: ["equate-omitted-agent-with-no-agent"] },
    { stem: "The road was closed after the heavy rain. What does the sentence tell a driver?", options: ["Who made the final decision", "How long the workers talked", "The road could not be used after the rain.", "Which driver first saw the rain"], answerIndex: 2, reasons: ["句子沒有交代決策者。", "沒有任何討論時間或工作人員資訊。", "was closed 告知道路在大雨後無法通行。", "原文未提到特定駕駛或最早目擊者。"], reviews: ["省略動作者不妨礙駕駛理解道路狀況。", "第三項只把 closed 與 after the heavy rain 轉成可採取行動的資訊。"], cognitiveProcess: ["u23-s158-extract-road-status-without-closer", "separate-operational-fact-from-decision-maker"], representationType: "omitted-agent-focus-inference", misconceptionTargets: ["demand-agent-before-understanding-result"] },
    { stem: "The lost key was found under a desk. What do we still not know?", options: ["Whether the key exists", "Where the key was found", "Whether the key is lost now", "Who found the key"], answerIndex: 3, reasons: ["the lost key 明確是存在的物品。", "under a desk 已提供尋獲地點。", "was found 表示它已不再處於未尋獲狀態。", "句子省略 finder，因此無法確定是誰找到。"], reviews: ["被動句提供結果和地點，卻刻意保留動作者空缺。", "第四項區分未提供的資訊，沒有否定尋獲事件本身。"], cognitiveProcess: ["u23-s158-identify-missing-finder-information", "retain-known-key-result-and-location"], representationType: "missing-information-analysis", misconceptionTargets: ["treat-omitted-agent-as-missing-event"] },
    { stem: "The test papers will be given out at nine. What should students learn from this notice?", options: ["The papers become available at nine.", "A named student must give out every paper.", "The test ends at nine.", "The papers were given out yesterday."], answerIndex: 0, reasons: ["will be given out at nine 指出考卷九點開始發放。", "公告沒有指定學生負責發卷。", "given out 不是考試結束的意思。", "will 與 at nine 表示未來安排，不是昨天事件。"], reviews: ["讀者需要的是考卷何時取得，發放者可由情境推知或不重要。", "第一項忠實轉述時間與結果，沒有補入責任人。"], cognitiveProcess: ["u23-s158-interpret-paper-distribution-with-obvious-agent", "avoid-assigning-unnamed-student-duty"], representationType: "obvious-agent-notice-reading", misconceptionTargets: ["invent-specific-agent-from-school-context"] },
    { stem: "The lights are turned off at ten every night. Which part is not needed to keep the rule clear?", options: ["the lights", "the name of the person who turns them off", "at ten", "every night"], answerIndex: 1, reasons: ["the lights 指出受規則影響的設備，不能刪除。", "執行者身分不影響十點關燈的固定規則。", "at ten 是讀者需要的明確時間。", "every night 說明規則每天重複。"], reviews: ["規則的核心是何物、何時、多久一次，不是輪值者姓名。", "第二項可省略，因被動句仍完整傳達關燈安排。"], cognitiveProcess: ["u23-s158-remove-irrelevant-agent-from-light-rule", "preserve-object-time-and-frequency"], representationType: "agent-relevance-selection", misconceptionTargets: ["keep-agent-at-cost-of-rule-details"] },
    { stem: "Someone left a bag on the bus, but no passenger knows who. Which sentence uses only these facts?", options: ["The driver left the bag on the bus.", "A child left the bag on the bus.", "A bag was left on the bus.", "The bag placed itself on a seat."], answerIndex: 2, reasons: ["沒有人知道是誰，不能指定 driver。", "child 也是無證據的人物猜測。", "被動句保留 bag 與 bus，並省略未知動作者。", "物品不會自行放置，且原文明說 someone 做了動作。"], reviews: ["證據只支持有人遺留袋子，不支持其身分。", "第三項避免把未知乘客替換成看似合理卻未證實的人。"], cognitiveProcess: ["u23-s158-convert-unknown-bag-leaver-to-passive", "prevent-role-invention-and-self-placement"], representationType: "unknown-agent-rewrite", misconceptionTargets: ["choose-plausible-but-unsupported-agent"] },
    { stem: "The room is cleaned every day. What cannot be learned from this sentence alone?", options: ["The room receives cleaning", "Cleaning happens daily", "The sentence focuses on the room", "Who cleans the room"], answerIndex: 3, reasons: ["is cleaned 明確把 room 當成承受者。", "every day 提供每日頻率。", "room 位在主詞位置，確實是句子焦點。", "句中沒有 by 片語，無法知道清潔者。"], reviews: ["一般日常工作可以省略執行者，並不影響頻率資訊。", "第四項是唯一沒有被句中形式或時間詞支持的內容。"], cognitiveProcess: ["u23-s158-isolate-unknown-cleaner-from-daily-passive", "inventory-known-focus-frequency-patient"], representationType: "passive-information-boundary", misconceptionTargets: ["assume-routine-agent-from-context"] },
    { stem: "A school song was written in 1998. Which question does the sentence not answer?", options: ["Who wrote it?", "What was written?", "When was it written?", "Was the song already written before 2000?"], answerIndex: 0, reasons: ["沒有 by 片語，作者身分無法得知。", "a school song 回答作品是什麼。", "in 1998 清楚回答創作年份。", "1998 早於 2000，可由年份判定。"], reviews: ["省略動作者後，作品與年代仍足以構成完整歷史資訊。", "第一項需要額外來源，不能從 was written 自行推得作者。"], cognitiveProcess: ["u23-s158-find-unanswered-author-in-dated-passive", "use-year-without-inventing-writer"], representationType: "passive-question-answerability", misconceptionTargets: ["infer-author-from-institution-name"] },
    { stem: "A note says, 'Your package was sent this morning.' Which answer uses only the note?", options: ["The package was sent by the shop owner.", "The package was sent this morning, but the sender is not named.", "The package arrived this morning.", "The package was opened before it was sent."], answerIndex: 1, reasons: ["shop owner 是可能人物，但便條沒有證實。", "第二項完整保留寄出時間與未知寄件者。", "sent 不等於 arrived，不能推出已送達。", "句中完全沒有開包裹的資訊。"], reviews: ["被動訊息能證明寄送動作，卻不提供寄件人或抵達結果。", "第二項把已知與未知分開，是唯一不超出便條內容的推論。"], cognitiveProcess: ["u23-s158-bound-inference-from-package-sent-note", "distinguish-sender-and-arrival-unknowns"], representationType: "safe-passive-inference", misconceptionTargets: ["inflate-sent-into-arrived-or-named-sender"] },
    { stem: "The tables were moved before the meeting. Which added words tell who moved them rather than when?", options: ["before noon", "after lunch", "by the art team", "during the break"], answerIndex: 2, reasons: ["before noon 只補充時間。", "after lunch 仍是時間背景。", "by the art team 指出搬桌子的團體。", "during the break 說明事件發生時段。"], reviews: ["原被動句可不寫搬運者，但題目要求辨認能補出動作者的片語。", "第三項的 team 能執行 moved，其餘三項都只定位時間。"], cognitiveProcess: ["u23-s158-distinguish-agent-addition-from-time-phrases", "test-team-capacity-to-move-tables"], representationType: "agent-phrase-versus-time-phrase", misconceptionTargets: ["treat-any-by-or-time-phrase-as-agent"] },
    { stem: "A reporter knows only that the gate was opened at six. Which sentence adds nothing that was not given?", options: ["Sam opened the gate at six.", "The guard opened the gate at six.", "The wind opened the gate at six.", "The gate was opened at six."], answerIndex: 3, reasons: ["Sam 的身分沒有證據。", "guard 雖符合常識，仍是未證實的推測。", "風也只是可能來源，不能直接斷定。", "第四項只保留已知的 gate、opened 與 at six。"], reviews: ["合理猜測仍不等於報導可採用的事實。", "第四項利用被動省略未知動作者，沒有犧牲明確時間。"], cognitiveProcess: ["u23-s158-write-minimal-gate-report-from-limited-evidence", "reject-three-plausible-agent-guesses"], representationType: "journalistic-evidence-control", misconceptionTargets: ["confuse-plausibility-with-evidence"] },
  ]),
  ...skillQuestions("159", [
    { stem: "This story was written ___ Nora.", options: ["by", "with", "at", "from"], answerIndex: 0, reasons: ["by 引入完成 written 的作者 Nora。", "with 通常引入工具，不能表達 Nora 是作者。", "at 表示位置或時間，與作者角色不合。", "from 可表示來源，但不是此被動結構的動作者標記。"], reviews: ["Nora 是能執行 writing 的人，應由 by 放回事件。", "第一項形成 by Nora，清楚說明作品歸屬。"], cognitiveProcess: ["u23-s159-insert-by-before-story-author", "distinguish-agent-marker-from-tool-source-place"], representationType: "by-agent-preposition-cloze", misconceptionTargets: ["use-with-for-human-agent"] },
    { stem: "Leo opened the box with a key. The box was opened by Leo ___ a key.", options: ["by", "with", "from", "for"], answerIndex: 1, reasons: ["by 已用來引入開箱者 Leo，不能再把工具 key 當動作者。", "with 正確標示 Leo 使用的鑰匙。", "from 表示來源，不能說明開箱工具。", "for 常表示目的或受益者，與 key 功能不合。"], reviews: ["主動句已顯示 Leo 是動作者，key 只提供方法。", "第二項形成 The box was opened by Leo with a key，人物與工具角色都清楚。"], cognitiveProcess: ["u23-s159-complete-key-instrument-with", "reserve-by-for-box-opener"], representationType: "agent-instrument-preposition-cloze", misconceptionTargets: ["label-tool-as-agent"] },
    { stem: "Two teams made posters. This poster was made by the green team. What do the words by the green team tell us?", options: ["They give the time.", "They tell what the poster is made of.", "They tell which team made this poster.", "They say where the poster hangs."], answerIndex: 2, reasons: ["片語沒有時間詞。", "green 描述 team，不是海報材料。", "by the green team 從兩隊中指出實際製作者。", "句子沒有任何張貼地點。"], reviews: ["有多個可能來源時，by 片語提供必要對比。", "第三項解釋其資訊價值，並未把顏色誤當材料。"], cognitiveProcess: ["u23-s159-use-by-team-to-resolve-competing-makers", "exclude-time-material-and-location-functions"], representationType: "by-phrase-discourse-function", misconceptionTargets: ["ignore-agent-contrast-value"] },
    { stem: "The tree was knocked down ___ the strong wind.", options: ["with", "for", "from", "by"], answerIndex: 3, reasons: ["with 較適合工具，不能在此標自然力量來源。", "for 會引出目的或受益關係。", "from 可說來源方向，但不完成此被動動作者結構。", "by the strong wind 指出造成樹倒下的力量。"], reviews: ["動作者不一定是人，風能作為 knocked down 的原因力量。", "第四項把 wind 放在 by 後，與 tree 的承受角色形成清楚對應。"], cognitiveProcess: ["u23-s159-introduce-natural-force-with-by", "separate-causal-agent-from-instrument"], representationType: "nonhuman-by-agent-cloze", misconceptionTargets: ["limit-by-agent-to-people"] },
    { stem: "The cake was cut by Mia with a knife. What role does the knife have?", options: ["It is the tool used for cutting.", "It is the person who cut the cake.", "It is the cake's owner.", "It is the place where Mia worked."], answerIndex: 0, reasons: ["with a knife 明確補充切蛋糕的工具。", "by Mia 已指出實際執行切割的人。", "句中沒有談蛋糕所有權。", "knife 是物品，不是工作地點。"], reviews: ["同句同時展示 by 加動作者與 with 加工具。", "第一項依介系詞功能及現實角色都能成立。"], cognitiveProcess: ["u23-s159-classify-knife-in-dual-phrase-passive", "contrast-mia-agent-and-knife-instrument"], representationType: "agent-instrument-role-analysis", misconceptionTargets: ["swap-by-agent-and-with-tool"] },
    { stem: "Amy drew the picture. Which sentence puts the picture first but keeps Amy as the artist?", options: ["Amy was drawn by the picture.", "The picture was drawn by Amy.", "The picture drew Amy.", "The artist was a picture by Amy."], answerIndex: 1, reasons: ["第一項把 Amy 寫成被畫的對象。", "第二項把 picture 移為承受者焦點，by Amy 保留畫者。", "第三項讓 picture 主動畫人，角色顛倒。", "第四項改成不通順的身分類句，未保留原動作。"], reviews: ["主動句中 Amy 對 picture 執行 drew。", "第二項使用 draw 的過去分詞 drawn，且 by 片語維持作者資訊。"], cognitiveProcess: ["u23-s159-passivize-drawing-while-retaining-artist", "select-drawn-and-by-amy-role-order"], representationType: "active-passive-agent-preservation", misconceptionTargets: ["reverse-artist-and-artwork"] },
    { stem: "Return the book by Friday. Does by tell who returns the book?", options: ["Yes, Friday returns it.", "Yes, the book acts on Friday.", "No, it marks the latest time.", "No, it marks the tool used."], answerIndex: 2, reasons: ["Friday 是日期，不可能執行 return。", "book 也沒有對 Friday 執行動作。", "by Friday 表示最晚在星期五以前完成。", "日期不是歸還書本使用的工具。"], reviews: ["相同拼字 by 會依後接內容改變功能，不能一律判動作者。", "第三項以時間期限解讀，符合祈使句目的。"], cognitiveProcess: ["u23-s159-disambiguate-by-friday-as-deadline", "reject-date-as-agent-or-tool"], representationType: "by-function-contrast-deadline", misconceptionTargets: ["treat-every-by-phrase-as-agent"] },
    { stem: "Ben goes to school by bus. What does by bus describe?", options: ["Who drives every bus", "Who built the school", "Who receives the trip", "How Ben travels"], answerIndex: 3, reasons: ["句子沒有指出特定駕駛。", "by bus 不涉及學校建造者。", "trip 並沒有被某人接收。", "by bus 表示 Ben 的交通方式。"], reviews: ["這裡不是被動句，by 後也不是事件動作者。", "第四項說明交通方式，避免僅憑介系詞外形套用規則。"], cognitiveProcess: ["u23-s159-distinguish-travel-by-from-agent-by", "map-bus-phrase-to-transport-method"], representationType: "by-function-contrast-transport", misconceptionTargets: ["overgeneralize-passive-by-rule"] },
    { stem: "The window was broken by a ball during the game. What caused the break?", options: ["A ball", "The game", "The window", "The time"], answerIndex: 0, reasons: ["by a ball 指出造成破裂的物體。", "game 只是事件背景，不直接承擔 broke。", "window 是被打破的承受者。", "during 片語提供時段，不是原因力量。"], reviews: ["球雖不是有意識的人，仍可作為造成破壞的來源。", "第一項由 by 片語與現實因果共同支持。"], cognitiveProcess: ["u23-s159-read-ball-as-causal-agent", "separate-game-context-and-window-patient"], representationType: "causal-by-phrase-identification", misconceptionTargets: ["reject-inanimate-cause-as-by-agent"] },
    { stem: "Both Mia and Nora paint. The blue picture was painted by Nora. Why do we need by Nora?", options: ["It tells when the picture was painted.", "It tells which of the two artists painted it.", "It explains what color Nora had on.", "It shows where Mia stood."], answerIndex: 1, reasons: ["Nora 是人物，不提供作畫時間。", "前文有兩位畫者，by Nora 才能指出藍畫作者。", "blue 修飾 picture，沒有描述 Nora 衣著。", "句中不含 Mia 的位置資訊。"], reviews: ["若刪掉 by Nora，讀者無法在兩個候選人中判定作者。", "第二項說明此 by 片語不是多餘資訊，而是解決來源對比。"], cognitiveProcess: ["u23-s159-justify-agent-retention-under-two-artists", "link-by-nora-to-source-disambiguation"], representationType: "necessary-agent-discourse-analysis", misconceptionTargets: ["delete-informative-by-phrase"] },
    { stem: "The floor is cleaned every day by people. Which sentence is shorter without losing useful information?", options: ["People are cleaned by the floor every day.", "Every day is cleaned by people.", "The floor is cleaned every day.", "The floor cleans people every day."], answerIndex: 2, reasons: ["第一項顛倒 floor 與 people 的角色。", "第二項把時間片語誤作被清理主詞。", "第三項省略無資訊價值的泛稱動作者，保留例行清潔。", "第四項讓地板主動清理人，語意錯誤。"], reviews: ["by people 太籠統，無法提供來源、責任或對比。", "第三項保留真正需要的 floor 與 every day，表達更集中。"], cognitiveProcess: ["u23-s159-remove-uninformative-generic-by-people", "preserve-daily-cleaning-focus"], representationType: "by-phrase-relevance-edit", misconceptionTargets: ["keep-vague-agent-for-false-completeness"] },
    { stem: "The picture was drawn by Ben for the school show. Which sentence keeps all of that information?", options: ["The school show drew Ben's picture.", "The picture drew Ben for school.", "Ben was drawn at the school show.", "Ben drew the picture for the school show."], answerIndex: 3, reasons: ["school show 是用途，不是繪圖者。", "picture 是作品，不能主動 draw Ben。", "第三項把 Ben 改成被畫對象，也遺失作品。", "第四項讓 Ben 畫 picture，並保留用途片語。"], reviews: ["by Ben 還原成主動主詞，passive subject picture 還原成受詞。", "第四項也完整保留 for the school show，沒有把用途誤作動作者。"], cognitiveProcess: ["u23-s159-restore-active-from-drawn-by-ben", "carry-purpose-phrase-through-voice-change"], representationType: "by-agent-active-restoration", misconceptionTargets: ["promote-purpose-noun-to-agent"] },
  ]),
  ...skillQuestions("160", [
    { stem: "The gate was locked by Sam at nine. What does the sentence report?", options: ["Sam locked the gate at nine.", "The gate had a new color.", "Sam locks every gate as his usual job.", "The gate had never been open."], answerIndex: 0, reasons: ["by Sam 與 at nine 共同指出 Sam 在九點完成鎖門。", "locked 不是顏色資訊。", "單一事件無法證明 Sam 的固定工作。", "曾被鎖上不表示 gate 從未打開。"], reviews: ["動作者與明確時間讓 locked 偏向動作報告。", "第一項改為主動句後，人物、時間與事件方向都保持不變。"], cognitiveProcess: ["u23-s160-paraphrase-locked-agent-time-event", "reject-color-job-and-permanent-state"], representationType: "event-report-active-paraphrase", misconceptionTargets: ["treat-all-participles-as-static"] },
    { stem: "The shop is closed now, so we cannot go in. What is the focus?", options: ["Who closed it", "Its present state", "How the door was made", "When it will open next month"], answerIndex: 1, reasons: ["句子沒有提供關店者。", "now 與 cannot go in 強調目前不開放的狀態。", "沒有製造門或商店的資訊。", "原文未提下個月的開放時間。"], reviews: ["讀者需要根據現況決定不能進入，而非追查一次關門動作。", "第二項由 now 和結果子句共同支持。"], cognitiveProcess: ["u23-s160-read-closed-shop-as-current-state", "use-entry-result-rather-than-agent-question"], representationType: "state-focus-identification", misconceptionTargets: ["force-event-reading-without-event-evidence"] },
    { stem: "The glass was broken. What can we learn from this sentence alone?", options: ["Ben broke it.", "It broke at noon.", "The glass was broken, but the cause is not given.", "A ball must have hit it."], answerIndex: 2, reasons: ["Ben 未出現在句中，不能指定他。", "沒有時間詞支持 noon。", "第三項保留破裂事實，同時承認來源未明。", "球只是可能原因，must have 沒有證據。"], reviews: ["孤立句可以支持破裂結果，卻不足以鎖定事件來源或時間。", "第三項只重述可確定內容，不宣稱玻璃現在仍未修復。"], cognitiveProcess: ["u23-s160-bound-claims-from-isolated-broken-glass", "separate-result-condition-from-cause-and-time"], representationType: "ambiguous-participle-evidence-boundary", misconceptionTargets: ["invent-event-details-from-result-state"] },
    { stem: "The hall was cleaned by the students at five. Which words best show that this is an event report?", options: ["the hall", "was", "cleaned", "by the students at five"], answerIndex: 3, reasons: ["hall 只指出承受清潔的地方。", "was 可出現在事件或過去狀態描述中，單獨不夠。", "cleaned 也能表示清潔後的狀態。", "動作者與時間一起指出誰在何時完成清潔。"], reviews: ["by the students 回答誰做，at five 回答何時做。", "第四項提供最具區辨力的事件證據，而非只看 be + p.p. 外形。"], cognitiveProcess: ["u23-s160-identify-agent-time-as-event-cues", "compare-weak-form-cues-with-contextual-evidence"], representationType: "event-cue-selection", misconceptionTargets: ["classify-from-auxiliary-alone"] },
    { stem: "The work is finished, so the team can go home. What does finished emphasize?", options: ["The work's completed state", "The name of the worker", "A future plan to begin", "A place called Finished"], answerIndex: 0, reasons: ["完成狀態使團隊能離開，正是句子焦點。", "沒有 by 片語或人物身分。", "is finished 表示已完成，不是未來才開始。", "Finished 在此是分詞，不是地名。"], reviews: ["so 後的回家結果建立在工作已完成的狀態上。", "第一項不否定先前曾有完成動作，只指出目前溝通焦點。"], cognitiveProcess: ["u23-s160-link-finished-work-state-to-team-departure", "distinguish-result-state-from-future-action"], representationType: "result-state-inference", misconceptionTargets: ["deny-prior-event-when-reading-state"] },
    { stem: "The meals were cooked by Mia at six. What does the sentence report?", options: ["The meals stayed warm all day.", "Mia completed the cooking at a stated time.", "Mia likes cooking every day.", "The meals cooked Mia."], answerIndex: 1, reasons: ["沒有溫度或全天持續資訊。", "by Mia 與 at six 明確交代動作者和事件時間。", "一次過去事件不能證明每日喜好。", "第四項把食物與人的角色顛倒。"], reviews: ["were cooked 的時間由 at six 精確定位，不只是描述餐點狀態。", "第二項保留 Mia 的動作者身分，也沒有推測習慣。"], cognitiveProcess: ["u23-s160-interpret-cooked-by-mia-as-timed-event", "reject-temperature-habit-and-role-reversal"], representationType: "event-report-paraphrase", misconceptionTargets: ["convert-single-event-to-habit-or-state"] },
    { stem: "The lights are turned off at ten every night. How should turned off be read here?", options: ["As the lights' color", "As a state with no time pattern", "As an action that happens again at ten each night", "As an action the lights do to others"], answerIndex: 2, reasons: ["turned off 描述關燈，不是顏色。", "at ten every night 正好提供明確重複時間。", "第三項把固定時間與被動動作連結。", "lights 是被關閉的設備，不是動作者。"], reviews: ["every night 將關燈安排標為反覆事件。", "第三項比單純狀態分析更能解釋 at ten 的時間功能。"], cognitiveProcess: ["u23-s160-classify-nightly-lights-off-as-recurring-event", "use-frequency-to-prefer-event-reading"], representationType: "habitual-passive-event-analysis", misconceptionTargets: ["ignore-scheduled-action-cue"] },
    { stem: "The lights are off now. What information is missing for an event report?", options: ["The fact that the room has lights", "How the lights are now", "The word now", "Who turned them off or when that action happened"], answerIndex: 3, reasons: ["the lights 已證明房間相關設備存在。", "are off 正是在說目前狀況。", "now 已出現在句中。", "句子沒有動作者，也沒有關燈動作發生時間。"], reviews: ["這句可完整描述現況，卻不足以重建一次關燈事件。", "第四項指出事件分析真正欠缺的來源與時間，而非重複已知資訊。"], cognitiveProcess: ["u23-s160-identify-missing-event-data-in-lights-off-state", "separate-state-sufficiency-from-event-history"], representationType: "state-versus-event-information-gap", misconceptionTargets: ["assume-current-state-reveals-event-history"] },
    { stem: "The door is closed because the room is cold. Why does closed mainly describe a state?", options: ["The sentence explains why the door stays that way.", "The word door always creates a state.", "Present time can never report an event.", "Closed has nothing to do with any action."], answerIndex: 0, reasons: ["because 子句說明維持關閉狀態的理由。", "door 也能出現在關門事件中，名詞本身不決定功能。", "現在式可以描述例行被動事件。", "關閉狀態可能來自先前動作，不能說毫無關聯。"], reviews: ["冷的房間需要門保持關閉，語境關心持續結果。", "第一項使用因果關係作判斷，而不是訂出錯誤的絕對規則。"], cognitiveProcess: ["u23-s160-use-cold-room-cause-for-state-reading", "avoid-lexical-and-tense-absolutes"], representationType: "context-supported-state-reasoning", misconceptionTargets: ["classify-state-by-noun-or-tense-only"] },
    { stem: "The window was closed. No other sentence is given. What can the reader say?", options: ["A child must have closed it.", "More information is needed to know whether the focus is the event or the state after it.", "The window closed another object.", "The sentence can only describe something done every day."], answerIndex: 1, reasons: ["child 是沒有證據的動作者。", "單句缺少動作者、時間細節與結果情境，兩種焦點皆可能。", "window 在此是被動主詞，不是作用於其他物的動作者。", "was 與無頻率詞都不支持每日習慣。"], reviews: ["語法形式本身無法完全取代上下文判斷。", "第二項承認可確定的被動結果，也保留尚未解決的焦點歧義。"], cognitiveProcess: ["u23-s160-preserve-ambiguity-in-bare-window-closed", "reject-certain-agent-self-action-and-habit"], representationType: "context-insufficiency-judgment", misconceptionTargets: ["force-single-reading-for-isolated-participle"] },
    { stem: "The door was closed by the guard at six. The door stayed closed all night. What is different?", options: ["Both only name the door's color.", "The first is a state; the second names who closed it.", "The first reports an event; the second describes the state after it.", "Both say the guard stayed all night."], answerIndex: 2, reasons: ["closed 與 stayed closed 都不涉及顏色。", "第一句有 by the guard，第二句才以 stayed 描述狀態。", "第三項依動作者、時間及 stayed 正確區分兩種焦點。", "第二句只說門持續關閉，沒有說 guard 留下。"], reviews: ["兩句連在一起呈現先發生關門，再延續關閉狀態。", "第三項尊重事件與結果的時間順序，不把人物狀態加入原文。"], cognitiveProcess: ["u23-s160-contrast-closing-event-with-remained-state", "sequence-action-and-result-without-agent-extension"], representationType: "paired-event-state-contrast", misconceptionTargets: ["collapse-event-and-result-into-one-function"] },
    { stem: "The room was ready. The chairs were placed in a circle by the class at noon. What does the second sentence add?", options: ["The chairs' color", "A rule that circles are always better", "The idea that the chairs moved themselves", "A finished action, the class that did it, and the time"], answerIndex: 3, reasons: ["沒有顏色資訊。", "一次排列不構成所有場合的規則。", "by the class 排除 chairs 自行移動。", "were placed、by the class、at noon 共同建立完成的安排事件。"], reviews: ["前句 ready 是狀態，後句補出形成部分準備結果的具體行動。", "第四項整合動作者與時間，沒有把圓形排列誇大成普遍原則。"], cognitiveProcess: ["u23-s160-differentiate-ready-state-from-placement-event", "integrate-agent-time-and-arrangement-result"], representationType: "cross-sentence-state-event-integration", misconceptionTargets: ["read-event-as-static-description-only"] },
  ]),
  ...skillQuestions("161", [
    { stem: "NOTICE: The library will be closed on Friday. What should a student plan for?", options: ["Use the library on another day.", "Meet the person who closes it.", "Return only books with red covers.", "Wait inside the library all Friday."], answerIndex: 0, reasons: ["Friday 無法使用圖書館，改日辦理最符合公告。", "關館者身分不是學生需處理的資訊。", "公告沒有按書本顏色限制歸還。", "closed 表示不能在館內等候使用。"], reviews: ["通知把受影響地點與日期放在最前，要求讀者調整安排。", "第一項只根據關館日期行動，沒有增加不存在的規則。"], cognitiveProcess: ["u23-s161-plan-around-friday-library-closure", "exclude-agent-color-and-inside-waiting"], representationType: "closure-notice-action-inference", misconceptionTargets: ["seek-agent-instead-of-operational-impact"] },
    { stem: "NOTICE: Bikes must be left outside. What must a person with a bike do?", options: ["Ride through every room.", "Leave the bike outside.", "Ask the bike to move itself.", "Take every bike home."], answerIndex: 1, reasons: ["公告禁止把腳踏車帶入室內，不能騎過房間。", "第二項直接執行 must be left outside 的規定。", "被動句省略騎士，但腳踏車不會自行移動。", "規定只談放置地點，不要求帶走所有人的車。"], reviews: ["bike 是被放置的物品，持有腳踏車的人是未寫出的責任人。", "第二項把被動規則還原成使用者能執行的動作。"], cognitiveProcess: ["u23-s161-convert-bike-passive-rule-to-rider-action", "recover-implicit-responsible-person"], representationType: "passive-rule-to-action", misconceptionTargets: ["interpret-patient-as-self-moving-agent"] },
    { stem: "NOTICE: Lunch is served at twelve in the hall. Where and when should students go for lunch?", options: ["At twelve in the library", "At one in the hall", "At twelve in the hall", "At one outside"], answerIndex: 2, reasons: ["時間正確但 library 不是公告地點。", "hall 正確，時間卻被改成一點。", "第三項同時保留 at twelve 與 in the hall。", "時間和地點都不符合通知。"], reviews: ["served 的動作者可省略，讀者仍能提取兩項實用資訊。", "第三項交叉核對時間與地點，沒有只抓到其中一個。"], cognitiveProcess: ["u23-s161-combine-lunch-service-time-and-place", "reject-partially-matching-notice-details"], representationType: "two-detail-notice-retrieval", misconceptionTargets: ["select-option-with-only-one-matching-detail"] },
    { stem: "NOTICE: The game was moved to Saturday because of rain. What happened to the game?", options: ["It will never be held.", "It moved itself into a building.", "It ended before the rain.", "Its day changed to Saturday."], answerIndex: 3, reasons: ["moved 不等於永遠取消。", "game 是被調整的活動，不是自行移動。", "公告沒有說比賽已結束。", "to Saturday 明確表示日期改到星期六。"], reviews: ["because of rain 提供改期原因，to Saturday 提供新日期。", "第四項只陳述日程變更，不把 moved 擴大解讀成取消。"], cognitiveProcess: ["u23-s161-interpret-rain-game-date-change", "distinguish-reschedule-from-cancel-or-motion"], representationType: "rescheduled-event-notice-reading", misconceptionTargets: ["equate-moved-event-with-canceled-event"] },
    { stem: "NOTICE: All library books must be returned by Friday. Which action follows the rule?", options: ["Return every borrowed book no later than Friday.", "Begin reading a new book after Friday.", "Return one book only on Saturday.", "Keep the books until someone asks."], answerIndex: 0, reasons: ["all 與 by Friday 要求每本借書最晚星期五歸還。", "公告談歸還期限，不是開始閱讀時間。", "只還一本且延至星期六同時違反數量與期限。", "must 表示主動責任，不能無限期等待提醒。"], reviews: ["被動規則把 books 放在焦點，實際責任落在借閱者。", "第一項正確處理 all 與 by 的兩個限制。"], cognitiveProcess: ["u23-s161-apply-all-books-friday-deadline", "translate-passive-obligation-to-borrower-duty"], representationType: "deadline-rule-application", misconceptionTargets: ["misread-by-as-on-or-after"] },
    { stem: "NOTICE: The music room will be used for a meeting after three. Which plan does not use the room at the same time?", options: ["Practice there at four.", "Practice there before three.", "Move the meeting into the hall without asking.", "Enter during the meeting to use the piano."], answerIndex: 1, reasons: ["四點落在 after three 的會議使用時段。", "三點前不在公告限制的會議時段內。", "學生無權自行更改會議地點。", "會議期間進入彈琴仍造成使用衝突。"], reviews: ["will be used 指教室三點後已有用途，不等於全天封閉。", "第二項利用時間邊界安排練習，沒有改動公告內容。"], cognitiveProcess: ["u23-s161-schedule-practice-before-meeting-use", "respect-after-three-boundary-without-overreach"], representationType: "facility-notice-scheduling", misconceptionTargets: ["extend-or-ignore-notice-time-window"] },
    { stem: "NOTICE: The east road is closed. Please use the west road. What should a driver do?", options: ["Wait for the road worker's name.", "Drive on the east road slowly.", "Take the west road.", "Close both roads."], answerIndex: 2, reasons: ["動作者姓名不是改道前提。", "closed 表示東側道路不能使用，不是減速即可。", "公告明確要求改走 west road。", "駕駛沒有權責關閉兩條道路。"], reviews: ["第一句說明受影響道路，第二句直接提供替代路線。", "第三項整合狀況與指示，不因省略封路者而停下判讀。"], cognitiveProcess: ["u23-s161-follow-alternate-road-under-closure", "ignore-irrelevant-closer-identity"], representationType: "closure-and-alternative-route", misconceptionTargets: ["treat-agent-omission-as-action-blocker"] },
    { stem: "NOTICE: Bags will be checked at the front door. What should visitors expect?", options: ["The front door will be put inside a bag.", "Visitors must check the building's doors.", "Every bag has already been taken home.", "Their bags will be checked at the front door."], answerIndex: 3, reasons: ["第一項顛倒 door 與 bag 的現實角色。", "被動句不是要求訪客檢查門。", "will be checked 是未來安排，沒有說袋子已帶回家。", "第四項保留受檢物與公告指定地點。"], reviews: ["通知省略檢查人員，仍能讓訪客預期袋子受檢。", "第四項只重述明示流程，不推定檢查發生在進門前或離開前。"], cognitiveProcess: ["u23-s161-infer-entry-bag-check-process", "recover-patient-location-and-future-timing"], representationType: "entrance-process-notice-inference", misconceptionTargets: ["reverse-inspector-and-inspected-item"] },
    { stem: "NOTICE: The water will be turned off from two to four. When can people not use the water?", options: ["From two to four", "Before two only", "After four only", "All week"], answerIndex: 0, reasons: ["from two to four 明確界定停水時段。", "公告沒有說兩點前停水。", "四點後不在所列區間內。", "兩小時的安排不能擴大成整週。"], reviews: ["will be turned off 以 water 為受影響項目，時間範圍才是讀者焦點。", "第一項完整保留起點與終點，避免只抓其中一端。"], cognitiveProcess: ["u23-s161-extract-water-shutoff-interval", "prevent-time-window-overextension"], representationType: "service-time-range-reading", misconceptionTargets: ["generalize-limited-closure-to-longer-period"] },
    { stem: "NOTICE: The hall is cleaned after the evening class. Which event comes first?", options: ["The hall is cleaned.", "The evening class ends.", "The next morning begins.", "A week without classes starts."], answerIndex: 1, reasons: ["cleaning 位於 after 關係的後段。", "晚間課程結束後才清潔，因此下課先發生。", "公告沒有把隔天早晨放進流程。", "句子也未要求先有整週停課。"], reviews: ["after the evening class 明確建立課程先、清潔後的順序。", "第二項只使用公告提供的兩件事，不再臆測收椅時間。"], cognitiveProcess: ["u23-s161-order-evening-class-before-hall-cleaning", "read-after-as-two-event-sequence"], representationType: "notice-event-order-reading", misconceptionTargets: ["reverse-after-sequence"] },
    { stem: "NOTICE: The lost phone was found and is kept in the office. Where should its owner go?", options: ["To the bus stop", "To any classroom", "To the office", "To the shop that made the phone"], answerIndex: 2, reasons: ["bus stop 未出現在公告中。", "any classroom 不是 is kept 指定的位置。", "the office 是手機目前保管地點。", "製造商與尋獲後領取無關。"], reviews: ["was found 提供結果，is kept in the office 提供後續行動地點。", "第三項讓失主依現況領取，沒有追問不必要的發現者。"], cognitiveProcess: ["u23-s161-link-found-phone-to-current-office-location", "use-result-state-for-owner-action"], representationType: "lost-found-notice-action", misconceptionTargets: ["focus-on-finder-instead-of-recovery-location"] },
    { stem: "Two notices say: 'The morning class was moved to Room 3' and 'Room 3 will be cleaned after noon.' Which plan fits both?", options: ["Go to the old room for the morning class.", "Wait until after noon for the morning class.", "Cancel the class because Room 3 is cleaned later.", "Go to the morning class in Room 3."], answerIndex: 3, reasons: ["old room 已被新地點取代。", "morning class 不需等到中午後。", "稍後清潔不代表早上不能上課或必須取消。", "第四項依 moved to Room 3 前往新教室，且清潔在中午後才開始。"], reviews: ["兩則被動通知分別提供早上新地點與中午後的清潔安排。", "第四項按時間整合兩個事實，沒有把後續清潔誤作全天封閉。"], cognitiveProcess: ["u23-s161-integrate-room-move-and-later-cleaning-notices", "resolve-nonoverlapping-schedule-constraints"], representationType: "multi-notice-integration", misconceptionTargets: ["treat-later-use-as-all-day-conflict"] },
  ]),
];

export const ENGLISH_UNIT_SOURCE = {
  unitId: UNIT_ID,
  lectures: ENGLISH_U23_LECTURES,
  questions: ENGLISH_U23_QUESTIONS,
  vocabularyPolicy: {
    capQuestionBasis: "appendix-5-table-1",
    additionalLearningTerms: ["add", "alone", "artist", "available", "avoid", "ball", "branch", "cancel", "cause", "complete", "create", "daily", "damage", "decision", "describe", "emphasize", "entrance", "event", "exist", "final", "fit", "focus", "guard", "hall", "information", "latest", "lock", "object", "passenger", "pattern", "rather", "receive", "result", "return", "role", "serve", "state", "support", "travel", "upstairs", "usual"],
    properNames: ["Amy", "Ben", "Leo", "Mia", "Nora", "Sam"],
    grammarNotation: ["drawn", "drew", "kept", "passive", "rode", "sang", "sold", "stood", "sung"],
    malformedDistractors: [],
  },
};
