const UNIT_ID = "ENG_R4_U16";

function lecture(id, skillId, content) {
  return { id, skillId, ...content, sections: content.sections.map((section, index) => ({ id: `${id}_SEC_${String(index + 1).padStart(2, "0")}`, ...section })) };
}

const DIFFICULTIES = ["foundation", "foundation", "foundation", "standard", "standard", "standard", "standard", "advanced", "advanced", "advanced", "transfer", "transfer"];

function skillQuestions(skillNumber, values) {
  if (values.length !== 12) throw new Error(`ENG_R4_S${skillNumber}: expected 12 authored questions`);
  return values.map((value, index) => ({ id: `ENG_R4_Q_${skillNumber}_${String(index + 1).padStart(2, "0")}`, skillId: `ENG_R4_S${skillNumber}`, difficulty: DIFFICULTIES[index], ...value }));
}

export const ENGLISH_U16_LECTURES = [
  lecture("ENG_R4_L_S106", "ENG_R4_S106", {
    objectives: ["依 be 動詞、情態助動詞、完成式或一般動詞選擇正確否定結構。", "把人稱與時態放在助動詞上，避免否定後的主要動詞重複變化。"],
    sections: [
      { title: "be 動詞與情態助動詞直接接 not", content: "含 am、is、are、was、were 的句子，把 not 放在 be 動詞後，例如 She is not busy.。can、will、should、must 等情態助動詞也直接加 not，例如 We cannot stay.；這些結構不再另加 do。" },
      { title: "一般動詞用 do not、does not 或 did not", content: "現在簡單式依主詞選 do not 或 does not，過去簡單式用 did not。Mia does not walk home. 中 does 承擔第三人稱，walk 回到原形；They did not leave early. 中 leave 也不保留 left。" },
      { title: "完成式在 have 或 has 後加 not", content: "現在完成式已有 have 或 has，否定寫 have not 或 has not，再接過去分詞，例如 Leo has not finished.。不能寫 Leo does not has finished，也不能把 not 放到分詞後。" },
      { title: "縮寫不改變動詞分工", content: "isn't、doesn't、didn't、can't、hasn't 都只是助動詞加 not 的縮寫。判斷後面的動詞時仍遵守原規則：doesn't know、didn't see、can't swim、hasn't arrived。完成句子後要檢查時態是否只標示一次。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S106_EX_01", prompt: "Nora ___ ready yet. (isn't / doesn't / didn't)", steps: ["ready 是形容詞。", "句子需要 be 動詞連接狀態。", "在 is 後加入 not 的縮寫。"], answer: "isn't", why: "ready 由 be 動詞連接，Nora 是第三人稱單數，因此使用 isn't。doesn't 後需要一般動詞，didn't 又會引入不合題意的過去結構。" },
      { id: "ENG_R4_L_S106_EX_02", prompt: "Ben didn't ___ the door. (lock / locked / locks)", steps: ["didn't 已表示過去否定。", "主要動詞不能再標過去。", "選擇原形 lock。"], answer: "lock", why: "didn't 已承擔過去時態，後面接原形 lock。locked 會重複過去標記，locks 則是現在式第三人稱形式。" },
      { id: "ENG_R4_L_S106_EX_03", prompt: "Amy has not ___ the message. (read / reads / reading)", steps: ["has not 顯示現在完成式。", "後面需要過去分詞。", "read 的過去分詞拼法仍是 read。"], answer: "read", why: "has not 後要接過去分詞；read 的原形、過去式與過去分詞拼法相同，但此處由 has not 可判定它擔任分詞。" },
    ],
    misconceptions: [
      { belief: "任何否定句都在主要動詞前直接放 not。", whyWrong: "一般動詞簡單式需要 do、does 或 did 幫助承擔否定。", correction: "寫 She does not work here.，不寫 She not works here.。" },
      { belief: "doesn't 後仍要把動詞加 s。", whyWrong: "第三人稱變化已放在 does 上。", correction: "使用 He doesn't need help.。" },
      { belief: "didn't left 可以同時顯示否定和過去。", whyWrong: "did 已表示過去，left 會造成雙重時態標示。", correction: "改成 didn't leave。" },
      { belief: "has not finished 可以改成 does not has finished。", whyWrong: "完成式本來就由 has 承擔助動功能。", correction: "直接在 has 後加 not。" },
    ],
    checks: [
      { prompt: "She isn't tired 使用哪一個動詞否定？", answer: "is", reason: "tired 是由 be 動詞連接的狀態。" },
      { prompt: "didn't saw 應改成什麼？", answer: "didn't see", reason: "didn't 後使用原形 see。" },
      { prompt: "hasn't arrived 中 arrived 擔任什麼形式？", answer: "過去分詞", reason: "hasn't 建立現在完成式。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S107", "ENG_R4_S107", {
    objectives: ["在會考採用的標準書面英語中，一個子句使用一套清楚的否定結構。", "在 not...any 與 no、never 與 ever 等形式間選擇，不讓兩個否定詞互相衝突。"],
    sections: [
      { title: "標準書面英語通常避免同一子句雙重否定", content: "I don't have any money. 與 I have no money. 都表示沒有錢，但不能混成 I don't have no money 來表達相同意思。這是會考採用的標準書面規則；不同口語變體可能另有用法，不應因此評斷說話者。" },
      { title: "否定助動詞常搭配 any 系列", content: "don't、doesn't、didn't 之後可使用 any、anyone、anything，例如 We didn't see anyone.。若改用 nobody、nothing 等本身含否定意義的字，前面的動詞通常改為肯定形式：We saw nobody.。" },
      { title: "never 本身已包含 not 的意義", content: "She never drinks coffee. 已表示她從不喝咖啡，不再寫 doesn't never。詢問經驗時可用 ever，如 Have you ever been there?；否定回答則可說 I have never been there.。" },
      { title: "先找否定範圍，再選一套完整寫法", content: "看到 no、nobody、nothing、never 時，先確認同一子句是否又有 not、don't、didn't。修正時不是任意刪字，而是保留完整意思：I didn't buy anything 或 I bought nothing 都可以，時態與受詞也要一起檢查。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S107_EX_01", prompt: "I don't need ___ help. (any / no / never)", steps: ["don't 已提供否定。", "help 是否定範圍內的名詞。", "使用 any 避免第二個否定詞。"], answer: "any", why: "don't 已使 need 成為否定，所以搭配 any help。no 會和 don't 形成雙重否定，never 則不能直接修飾 help。" },
      { id: "ENG_R4_L_S107_EX_02", prompt: "___ called me last night. (Nobody / Anybody didn't / Nobody didn't)", steps: ["意思是昨晚沒有人打電話。", "選一個本身含否定的主詞。", "其後動詞保持肯定過去式 called。"], answer: "Nobody", why: "Nobody 本身表示沒有人，因此直接接 called。Nobody didn't 同時否定兩次，Anybody didn't 也不是這個意思的標準排列。" },
      { id: "ENG_R4_L_S107_EX_03", prompt: "Mia has ___ seen snow. (never / not never / no)", steps: ["has seen 是現在完成式。", "要表達從未有此經驗。", "使用單一否定副詞 never。"], answer: "never", why: "has never seen 用 never 表達到目前為止一次也沒有。not never 形成不同且不必要的雙重否定，no 不能放在 seen 前。" },
    ],
    misconceptions: [
      { belief: "兩個否定詞會讓否定語氣更強，所以考試中較正確。", whyWrong: "標準書面英語可能把兩個否定解成衝突或另一種意思。", correction: "在同一子句選 don't...any 或 no 其中一套。" },
      { belief: "nobody 前一定要再加 didn't 才能表示過去沒有發生。", whyWrong: "nobody 已否定主詞，過去時間由 called 等動詞表達。", correction: "使用 Nobody called.。" },
      { belief: "never 只是頻率副詞，不含否定。", whyWrong: "never 已表示在任何時候都沒有。", correction: "寫 She never goes there.，不加 doesn't。" },
      { belief: "刪掉任一否定字都一定能保留原意。", whyWrong: "刪字後還要檢查 any/no 與動詞時態是否構成完整句子。", correction: "比較 didn't buy anything 與 bought nothing，再完整改寫。" },
    ],
    checks: [
      { prompt: "I didn't see nobody 的標準寫法可如何改？", answer: "I didn't see anybody.", reason: "didn't 已否定動詞，受詞改用 anybody。" },
      { prompt: "Nothing happened 是否還要加 didn't？", answer: "不用", reason: "Nothing 已是否定主詞。" },
      { prompt: "never 和 not never 的意思相同嗎？", answer: "不同", reason: "not never 不是單純加強 never。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S108", "ENG_R4_S108", {
    objectives: ["依 yes-no 問句開頭的動詞形成肯定或否定簡答。", "把名詞主詞換成正確代名詞，並保持人稱、時態與事實一致。"],
    sections: [
      { title: "簡答沿用問句中的 be 動詞或助動詞", content: "Is Tina home? 回答 Yes, she is. 或 No, she isn't.；Does Leo cook? 回答 Yes, he does. 或 No, he doesn't.。簡答不必重複主要動詞，但助動詞必須和問句同一套。" },
      { title: "過去、未來與情態助動詞也要對應", content: "Did they leave? 可答 Yes, they did.；Will Amy come? 可答 No, she won't.；Can Ben swim? 可答 Yes, he can.。不要因中文意思相近就把 did、will、can 互換。" },
      { title: "完成式簡答使用 have 或 has", content: "Has Mia finished? 的回答是 Yes, she has. 或 No, she hasn't.。Have the buses left? 則使用 they have 或 they haven't；完成式簡答不改用 do。" },
      { title: "代名詞與肯否定都必須符合事實", content: "問句主詞 the students 在簡答中換成 they，your mother 對聽者而言通常換成 she。先確認實際答案是肯定還是否定，再選助動詞；不能只看到 Yes 就固定接 does。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S108_EX_01", prompt: "Is Grace busy? Yes, ___. (she is / she does / Grace is busy)", steps: ["問句由 Is 開頭。", "Grace 換成 she。", "肯定簡答保留 is。"], answer: "she is", why: "Is 開頭的 be 問句用 is 回答，Grace 可換成 she，所以 Yes, she is 正確。she does 換錯助動詞，完整重複句也不是題目要求的簡答。" },
      { id: "ENG_R4_L_S108_EX_02", prompt: "Did the boys win? No, ___. (they didn't / they don't / he didn't)", steps: ["Did 表示過去。", "the boys 換成 they。", "否定簡答使用 didn't。"], answer: "they didn't", why: "問句的 did 決定短答使用 didn't，複數 boys 則換成 they。don't 會改成現在，he 也不符合複數主詞。" },
      { id: "ENG_R4_L_S108_EX_03", prompt: "Has Nora arrived? No, ___. (she hasn't / she doesn't / Nora not)", steps: ["Has 表示現在完成式。", "Nora 換成 she。", "否定形式為 hasn't。"], answer: "she hasn't", why: "Has Nora arrived 要以 has 回應；否定縮寫是 hasn't，因此 No, she hasn't 正確。doesn't 不屬於完成式。" },
    ],
    misconceptions: [
      { belief: "所有肯定簡答都寫 Yes, I do.。", whyWrong: "助動詞必須依原問句選 is、did、can、has 等。", correction: "先圈出問句第一個動詞，再沿用到簡答。" },
      { belief: "the girls 在簡答中可換成 she。", whyWrong: "複數主詞需要 they。", correction: "使用 Yes, they are. 等對應形式。" },
      { belief: "Did he call? 可以回答 No, he doesn't.。", whyWrong: "doesn't 是現在式，與 did 的過去時間不一致。", correction: "回答 No, he didn't.。" },
      { belief: "Has she eaten? 應回答 Yes, she does.。", whyWrong: "問句使用完成式 has，不是一般現在式 do。", correction: "回答 Yes, she has.。" },
    ],
    checks: [
      { prompt: "Are the doors open 的肯定簡答是什麼？", answer: "Yes, they are.", reason: "doors 是複數，沿用 are。" },
      { prompt: "Can Sam drive 的否定簡答是什麼？", answer: "No, he can't.", reason: "沿用情態助動詞 can。" },
      { prompt: "Have Amy and Mia left 的主詞代名詞是什麼？", answer: "they", reason: "兩個人組成複數主詞。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S109", "ENG_R4_S109", {
    objectives: ["用 too 附和肯定陳述，用 either 附和否定陳述。", "依完整子句的肯否定判斷附和字，不受單一負面詞義干擾。"],
    sections: [
      { title: "肯定句末使用 too 表示也一樣", content: "Mia likes tea. I like tea, too. 中 too 表示第二個人有相同肯定情況，通常放在句尾。它在其他語境也可能表示太過，例如 too hot；本單元要依句子位置與意思區分。" },
      { title: "否定句末使用 either 表示也不", content: "Leo doesn't drive. Ben doesn't drive, either. 中 either 跟隨完整否定句，表示 Ben 也不開車。不能只在肯定句尾加入 either 來表達一般的也。" },
      { title: "附和句要保留自己的主詞與動詞", content: "I am tired, too.、She can't swim, either. 都是完整子句再加附和字。主詞改變時，be 動詞或助動詞仍要配合新主詞，不能只寫 Me too 作為正式句型題的唯一依據。" },
      { title: "先判斷整句極性再選 too 或 either", content: "unhappy 等字義雖負面，He is unhappy. 在文法形式上仍是肯定句，因此可說 I am unhappy, too.。真正選 either 的線索是 not、don't、can't、never 等否定結構。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S109_EX_01", prompt: "Amy enjoys the music. I enjoy it, ___. (too / either / not)", steps: ["第一句是肯定陳述。", "第二句表達相同肯定情況。", "在句尾使用 too。"], answer: "too", why: "兩人都喜歡音樂，第二句本身也是肯定式，所以句尾用 too。either 需要否定子句，not 不能單獨作這種附和。" },
      { id: "ENG_R4_L_S109_EX_02", prompt: "Nora can't come. Sam can't come, ___. (either / too / also can)", steps: ["兩句都有 can't。", "第二句附和相同否定。", "選擇句尾 either。"], answer: "either", why: "Sam can't come 已是完整否定句，either 表示 Sam 也不能來。too 通常附和肯定句，also can 反而改成能來。" },
      { id: "ENG_R4_L_S109_EX_03", prompt: "Ben is worried. I am worried, ___. (too / either / neither)", steps: ["worried 意義負面但句型沒有 not。", "第二句同樣是肯定 be 結構。", "使用 too 表示我也擔心。"], answer: "too", why: "is worried 與 am worried 在文法上都是肯定句，即使情緒不愉快仍用 too。either 不能只因 worried 意義負面就選。" },
    ],
    misconceptions: [
      { belief: "too 與 either 都翻成也，所以可以互換。", whyWrong: "too 通常附和肯定，either 通常放在否定句尾。", correction: "先圈出 not 或否定助動詞，再決定 either。" },
      { belief: "句中出現 sad 或 worried 就一定用 either。", whyWrong: "詞義負面不等於句法否定。", correction: "He is sad. 仍可接 I am sad, too.。" },
      { belief: "肯定句寫 I like it either 也能表示我也喜歡。", whyWrong: "這種句尾附和在標準題型中應使用 too。", correction: "改成 I like it, too.。" },
      { belief: "either 自己就能取代完整否定句。", whyWrong: "本句型需要先有主詞與否定動詞。", correction: "寫 I don't know, either.。" },
    ],
    checks: [
      { prompt: "She is ready. I am ready, ___ 應填什麼？", answer: "too", reason: "兩句都是肯定狀態。" },
      { prompt: "He didn't call. I didn't call, ___ 應填什麼？", answer: "either", reason: "第二句附和過去否定。" },
      { prompt: "unhappy 是否自動使句子成為文法否定？", answer: "不是", reason: "是否定要看句法結構，不只看詞義。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S110", "ENG_R4_S110", {
    objectives: ["用 So + 助動詞 + 主詞附和肯定句。", "用 Neither + 助動詞 + 主詞附和否定句，並讓助動詞配合原句時態與結構。"],
    sections: [
      { title: "肯定附和使用 So 加倒裝", content: "Mia likes tea. So do I. 中 do 代替 likes，放在新主詞 I 前。若原句是 be 動詞或情態助動詞，就沿用它：Leo is tired. So am I.；Amy can swim. So can Ben.。" },
      { title: "否定附和使用 Neither 加肯定形式助動詞", content: "Nora doesn't drive. Neither does Sam. 表示 Sam 也不開車。Neither 已包含否定方向，所以助動詞寫 does，不再寫 doesn't；過去式可用 Neither did I.，情態助動詞可用 Neither can she.。" },
      { title: "助動詞由前句決定，主詞由附和者決定", content: "前句的時態與動詞類型決定 do、did、is、has、can 等，新主詞則決定 am、is、are 或 do、does 的人稱。I am late. So is Ben. 中前句是 be 現在式，但 Ben 要配 is。" },
      { title: "So do I 與 I do, too 表達相近但語序不同", content: "So do I 使用倒裝的短附和結構；I do, too 則先形成簡答式子句再加 too。考題若給 So 或 Neither 開頭，就必須把助動詞放在主詞前，不能寫 So I do 來替代一般附和。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S110_EX_01", prompt: "Amy walks to school. So ___ Ben. (does / is / did)", steps: ["walks 是現在簡單式一般動詞。", "Ben 是第三人稱單數。", "使用 does 放在 Ben 前。"], answer: "does", why: "walks 需要 do 系列代替，Ben 為第三人稱單數，所以寫 So does Ben。is 不能代替 walks，did 會改成過去。" },
      { id: "ENG_R4_L_S110_EX_02", prompt: "I can't hear the music. Neither ___ Mia. (can / can't / does)", steps: ["前句由 can't 構成否定。", "Neither 已表示也不。", "沿用 can 並放在 Mia 前。"], answer: "can", why: "Neither 本身帶否定方向，後面使用肯定形式 can，形成 Neither can Mia。can't 會再加一次否定，does 也不能代替情態 can。" },
      { id: "ENG_R4_L_S110_EX_03", prompt: "Leo was tired. So ___ we. (were / did / was)", steps: ["前句使用 be 過去式。", "新主詞 we 是複數。", "選擇 were 放在 we 前。"], answer: "were", why: "附和沿用 be 的過去時間，但要配合新主詞 we，所以使用 So were we。was 不配合 we，did 不能代替 be 狀態。" },
    ],
    misconceptions: [
      { belief: "So do I 中 do 永遠固定，不需看前句。", whyWrong: "前句若使用 be、did、can 或 have，附和也要換成相應動詞。", correction: "依前句寫 So am I、So did I 或 So can I。" },
      { belief: "Neither 後應使用 doesn't 或 can't 才有否定。", whyWrong: "Neither 已含否定意義，助動詞使用肯定形式。", correction: "寫 Neither does she. 或 Neither can she.。" },
      { belief: "附和句直接複製前句助動詞，不必看新主詞。", whyWrong: "be 動詞與 do 系列仍需配合新主詞。", correction: "I am ready. So is Ben.。" },
      { belief: "So I do 與 So do I 在一般附和題中完全相同。", whyWrong: "本單元的肯定附和需要助動詞與主詞倒裝。", correction: "使用 So do I. 表示我也一樣。" },
    ],
    checks: [
      { prompt: "She has finished. So ___ I 應填什麼？", answer: "have", reason: "沿用完成式並配合主詞 I。" },
      { prompt: "They didn't leave. Neither ___ we 應填什麼？", answer: "did", reason: "Neither 後沿用過去助動詞的肯定形式。" },
      { prompt: "I am hungry. So is Leo 是否正確？", answer: "正確", reason: "is 配合新主詞 Leo。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S111", "ENG_R4_S111", {
    objectives: ["依回答中的 Yes 或 No 判斷否定問句所確認的實際事實。", "讓簡答中的助動詞與代名詞對應問句，不用中文否定問法直接套答案。"],
    sections: [
      { title: "Yes 肯定後面的事實，No 否定後面的事實", content: "Aren't you ready? — Yes, I am. 表示我準備好了；No, I am not. 表示我還沒準備好。英文 Yes 與 No 主要對應回答內容的肯定或否定，不因問句含 not 就顛倒。" },
      { title: "一般動詞否定問句仍沿用 do 系列簡答", content: "Doesn't Mia live here? — Yes, she does. 表示 Mia 住這裡；No, she doesn't. 表示她不住這裡。判讀時把簡答展開成 she does live 或 she doesn't live，較不易受中文語序影響。" },
      { title: "情態與完成式依原助動詞回答", content: "Can't Ben swim? — No, he can't. 表示 Ben 不會游泳；Hasn't Amy left? — Yes, she has. 表示 Amy 已離開。先讀簡答動詞，再判斷被確認的命題。" },
      { title: "附加理由能幫助檢查解讀", content: "Isn't the shop open? — No, it isn't. The door is locked. 後句支持店沒開。若簡答與理由看似衝突，應重新檢查代名詞、否定縮寫及指涉，不要只翻譯問句表面。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S111_EX_01", prompt: "Aren't you cold? Yes, I am. Is the speaker cold?", steps: ["Yes 引出肯定簡答。", "I am 肯定 cold 的狀態。", "判定說話者覺得冷。"], answer: "Yes, the speaker is cold.", why: "Yes, I am 肯定 I am cold，即使原問句寫 Aren't you cold。不能把中文的反問直覺套成不冷。" },
      { id: "ENG_R4_L_S111_EX_02", prompt: "Doesn't Leo need a ticket? No, he doesn't. Does Leo need one?", steps: ["No 引出否定簡答。", "he doesn't 展開為 he doesn't need a ticket。", "判定 Leo 不需要票。"], answer: "No, he does not need a ticket.", why: "No, he doesn't 否定 Leo needs a ticket 這件事，因此 Leo 不需要票。問句中的 doesn't 不會把 No 反轉成肯定。" },
      { id: "ENG_R4_L_S111_EX_03", prompt: "Hasn't the bus left? Yes, it has. Where is the bus now?", steps: ["Yes, it has 肯定完成式。", "已完成的動作是 leave。", "判定公車已不在原處。"], answer: "It has already left.", why: "Yes, it has 表示 the bus has left 為真，因此公車已離開。答案不能解成公車還在，只因問句含 hasn't。" },
    ],
    misconceptions: [
      { belief: "否定問句中的 Yes 一律要翻成中文的不是。", whyWrong: "英文 Yes 肯定回答子句，No 否定回答子句。", correction: "讀完整的 Yes, I am 或 No, I am not 再判斷事實。" },
      { belief: "Aren't you ready? — No, I am. 是標準一致簡答。", whyWrong: "No 應搭配否定內容，I am 卻是肯定。", correction: "選 Yes, I am 或 No, I am not。" },
      { belief: "Doesn't she work here? — Yes, she does 表示她不在這裡工作。", whyWrong: "she does 肯定 work here。", correction: "把短答展開後再決定事實。" },
      { belief: "只看問句的 not 就能判斷答案，不必讀簡答。", whyWrong: "同一否定問句可得到肯定或否定兩種真實回答。", correction: "以 Yes/No 後的完整助動詞結構為準。" },
    ],
    checks: [
      { prompt: "Isn't Mia home? Yes, she is 表示什麼？", answer: "Mia 在家", reason: "Yes, she is 肯定 home 狀態。" },
      { prompt: "Can't Sam drive? No, he can't 表示什麼？", answer: "Sam 不會開車", reason: "No, he can't 否定駕駛能力。" },
      { prompt: "Hasn't Amy called? Yes, she has 表示什麼？", answer: "Amy 已經打過電話", reason: "Yes, she has 肯定完成式動作。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S112", "ENG_R4_S112", {
    objectives: ["依前後句的事實、肯否定與說話目的選擇一致或相反回應。", "區分附和、反對、修正與提供新資訊，不從單一 yes 或 no 過度推論。"],
    sections: [
      { title: "一致回應要在內容與文法兩方面相符", content: "A 說 I like the plan.，B 可說 I do, too. 或 So do I.；若 A 說 I don't like the plan.，B 可說 I don't, either. 或 Neither do I.。助動詞與肯否定都要對上。" },
      { title: "相反回應要清楚指出不同事實", content: "A 說 I can't come tonight.，B 若能參加，可回 I can.。這不是附和，而是對比。選項即使使用 too 或 neither 很流利，只要把 B 的實際情況說反，仍不是合理答案。" },
      { title: "but 後常出現限制或轉折", content: "I like the room, but it is too small. 前半肯定喜好，後半指出問題。判斷回應時要看完整句，不可只抓 like 就認為毫無保留地贊成，也不可只抓 too small 就推成完全不喜歡。" },
      { title: "回應證據只支持對話中說出的範圍", content: "No, I can't. I have a class. 能推得說話者這次無法參加，不能推成永遠不參加。會考對話題常把合理附和與過度概括放在一起，應以時間、代名詞和實際命題逐項核對。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S112_EX_01", prompt: "A: I enjoy this song. B: ___. (I do, too / I don't, either / Neither do I)", steps: ["A 表達肯定喜好。", "B 要附和相同肯定情況。", "選擇 I do, too。"], answer: "I do, too", why: "A 的 enjoy 是肯定一般現在式，B 若有相同喜好可用 I do, too。另兩項都表示 B 不喜歡，與一致回應相反。" },
      { id: "ENG_R4_L_S112_EX_02", prompt: "A: I can't stay late. B: I can. Do they give the same answer?", steps: ["A 用 can't 表示不能留下。", "B 用 can 表示能留下。", "比較兩個助動詞的肯否定。"], answer: "No, their answers are different.", why: "A 不能晚留，B 卻能晚留，兩人的事實相反。B 的 I can 不是接受 A 的否定，而是省略 stay late 的對比回答。" },
      { id: "ENG_R4_L_S112_EX_03", prompt: "A: The trip sounds fun, but I work that day. What does A decide?", steps: ["sounds fun 表示正面看法。", "but 引出當天工作限制。", "以能否參加作最後判斷。"], answer: "A cannot join the trip that day.", why: "A 覺得行程有趣，但工作與日期衝突，所以當天不能參加。這不代表 A 永遠不喜歡旅行，只能判斷這一次。" },
    ],
    misconceptions: [
      { belief: "回應中出現 too 就一定和前句一致。", whyWrong: "too 也可能表示太過，且仍要檢查整句內容。", correction: "比較兩句實際命題與肯否定。" },
      { belief: "I can 回應 I can't 時是在同意對方。", whyWrong: "省略的動作相同，但 can 與 can't 表示相反能力或可能。", correction: "把省略部分補回後比較。" },
      { belief: "but 前的正面句決定最後一定接受。", whyWrong: "but 後可能提供使行動無法完成的限制。", correction: "讀到句末再判斷最終立場。" },
      { belief: "一次拒絕可以證明一個人的永久喜好。", whyWrong: "時間或行程衝突只解釋當次選擇。", correction: "結論限於對話明說的日期與事件。" },
    ],
    checks: [
      { prompt: "I am tired. So am I 是一致還是相反？", answer: "一致", reason: "兩人都表示疲倦。" },
      { prompt: "I won't go. I will. 是一致還是相反？", answer: "相反", reason: "will 與 won't 對同一行動給出不同答案。" },
      { prompt: "I would like to, but I have a test 能證明永久不喜歡嗎？", answer: "不能", reason: "只顯示這次受到考試限制。" },
    ], assets: [],
  }),
];

export const ENGLISH_U16_QUESTIONS = [
  ...skillQuestions("106", [
    { stem: "Nora ___ busy today.", options: ["isn't", "doesn't", "didn't", "hasn't"], answerIndex: 0, reasons: ["isn't 連接 Nora 與 busy，正確否定今天的狀態。", "doesn't 後需要一般動詞，不能直接接 busy。", "didn't 會加入過去時間且仍缺少主要動詞。", "hasn't 不能單獨連接形容詞 busy。"], reviews: ["busy 是形容詞，句子需要 be 動詞。", "第一項把 is 與 not 合併，不另加 do。"], cognitiveProcess: ["identify-busy-as-be-complement", "negate-is-for-nora"], representationType: "be-negative-cloze", misconceptionTargets: ["use-do-before-adjective"] },
    { stem: "Leo ___ like milk.", options: ["isn't", "doesn't", "didn't", "hasn't"], answerIndex: 1, reasons: ["isn't 不能帶原形 like 表示一般喜好。", "doesn't 配合 Leo，like 保持原形。", "didn't 會改成過去某段時間不喜歡。", "hasn't like 不是完成式正確形式。"], reviews: ["like 是現在簡單式的一般動詞。", "第二項承擔第三人稱與否定，沒有把 like 加 s。"], cognitiveProcess: ["classify-like-as-present-lexical-verb", "select-does-not-for-leo"], representationType: "present-negative-cloze", misconceptionTargets: ["negate-present-action-with-is-not"] },
    { stem: "They ___ arrive before the doors closed last night.", options: ["don't", "doesn't", "didn't", "aren't"], answerIndex: 2, reasons: ["don't 表示現在，和 last night 不合。", "doesn't 既是現在式，也不配合 they。", "didn't 表示過去否定，後接原形 arrive。", "aren't 不能直接連接 arrive。"], reviews: ["last night 與 closed 鎖定過去時間。", "第三項只在 did 上標過去，arrive 不再變化。"], cognitiveProcess: ["anchor-arrival-failure-to-last-night", "use-did-not-before-arrive"], representationType: "past-negative-cloze", misconceptionTargets: ["use-present-negative-with-past-context"] },
    { stem: "Amy ___ finished the report yet.", options: ["doesn't", "isn't", "didn't", "hasn't"], answerIndex: 3, reasons: ["doesn't 不能帶過去分詞 finished 形成完成式。", "isn't finished 會把 Amy 誤成被完成的事物。", "didn't 後應接 finish，而且不表達 yet 所需的到目前狀態。", "hasn't finished 正確形成現在完成式否定。"], reviews: ["yet 與 finished 指到目前仍未完成。", "第四項保留過去分詞，否定放在 has 上。"], cognitiveProcess: ["read-yet-as-unfinished-present-perfect", "combine-has-not-with-finished"], representationType: "perfect-negative-cloze", misconceptionTargets: ["replace-perfect-helper-with-do"] },
    { stem: "The pool is closed, so we ___ swim there today.", options: ["cannot", "do not can", "are not can", "did not can"], answerIndex: 0, reasons: ["cannot 直接否定情態助動詞 can，符合今天無法游泳。", "do not 與 can 不應在此堆疊。", "are not 不能再接 can。", "did not can 同時混合過去 do 與情態助動詞。"], reviews: ["closed 說明今天的限制，所需意思是 cannot swim。", "第一項後接 swim 原形，結構只有一個助動詞。"], cognitiveProcess: ["derive-current-swimming-impossibility", "negate-can-without-do-support"], representationType: "modal-negative-cloze", misconceptionTargets: ["add-do-before-modal"] },
    { stem: "The windows ___ open because the room is cold.", options: ["don't", "aren't", "didn't", "haven't"], answerIndex: 1, reasons: ["don't open 會表示窗戶不會開啟，並非現在開著與否的狀態。", "aren't open 正確否定複數窗戶目前開著的狀態。", "didn't 會轉成過去動作且缺少 close 的時態背景。", "haven't open 不是完成式。"], reviews: ["because the room is cold 說明眼前窗戶處於未開啟狀態。", "第二項以 are not 連接 plural windows 與形容詞 open。"], cognitiveProcess: ["interpret-open-as-current-window-state", "agree-are-not-with-windows"], representationType: "state-negative-cloze", misconceptionTargets: ["confuse-do-not-open-with-are-not-open"] },
    { stem: "Sam didn't ___ to the office yesterday.", options: ["went", "goes", "go", "going"], answerIndex: 2, reasons: ["went 會與 didn't 重複過去標記。", "goes 是現在第三人稱形式。", "go 是 didn't 後所需的原形。", "going 需要進行式助動結構。"], reviews: ["didn't 已承擔 yesterday 的過去時態。", "第三項讓主要動詞回到 go，避免 did 與 went 同時出現。"], cognitiveProcess: ["remove-past-from-go-after-didnt", "complete-office-absence-negative"], representationType: "base-form-after-negative-did", misconceptionTargets: ["retain-irregular-past-after-didnt"] },
    { stem: "Mia walks home after class. Which line correctly makes the sentence negative?", options: ["Mia not walks home after class.", "Mia isn't walk home after class.", "Mia don't walks home after class.", "Mia doesn't walk home after class."], answerIndex: 3, reasons: ["not 不能直接放在 walks 前。", "isn't 不能帶原形 walk 表示一般習慣。", "Mia 需要 does，而且 walks 不應保留 s。", "doesn't 配合 Mia，walk 回到原形。"], reviews: ["原句是第三人稱現在簡單式的一般動詞。", "第四項只改肯否定，不改 after class 的時間範圍。"], cognitiveProcess: ["negate-mia-walking-habit", "transfer-s-from-walks-to-doesnt"], representationType: "statement-negation-task", misconceptionTargets: ["place-not-before-inflected-main-verb"] },
    { stem: "Which line correctly says that the team will stay here?", options: ["The team will not leave.", "The team not will leave.", "The team doesn't will leave.", "The team will doesn't leave."], answerIndex: 0, reasons: ["will not leave 正確表示隊伍不會離開，也就是會留下。", "not 應放在 will 後，不放在它前。", "doesn't 不能和 will 同時使用。", "will 後不能接 doesn't。"], reviews: ["stay here 可由 will not leave 表達相同結果。", "第一項保留未來時間，否定位置也正確。"], cognitiveProcess: ["express-future-staying-through-not-leaving", "place-not-after-will"], representationType: "future-negative-equivalence", misconceptionTargets: ["insert-doesnt-with-will"] },
    { stem: "Ben has not eaten lunch. Which idea is true now?", options: ["Ben ate lunch twice.", "Ben has not eaten lunch yet.", "Ben will never eat lunch.", "Ben did not know what lunch was."], answerIndex: 1, reasons: ["句子否定的是完成用餐，不是說吃過兩次。", "has not eaten 表示到目前仍未吃午餐。", "現在尚未吃不代表未來永遠不吃。", "原句沒有談 Ben 是否知道 lunch 的意思。"], reviews: ["完成式否定的時間界線是到現在。", "第二項限縮在目前未吃午餐，沒有擴大成永久狀態。"], cognitiveProcess: ["interpret-present-perfect-negative-at-now", "avoid-never-inference-from-not-yet"], representationType: "negative-time-meaning", misconceptionTargets: ["turn-current-noncompletion-into-never"] },
    { stem: "A student writes 'The children doesn't need tickets.' Which change makes the sentence correct?", options: ["The children isn't need tickets.", "The children doesn't needs tickets.", "The children don't need tickets.", "The children didn't needs tickets."], answerIndex: 2, reasons: ["isn't 不能帶 need 表示一般需要。", "children 是複數，且 needs 仍重複人稱。", "don't 配合複數 children，need 保持原形。", "didn't 後不能接 needs，並會改成過去。"], reviews: ["錯誤同時涉及複數主詞與 does 的選擇。", "第三項修正助動詞而不改變現在需要票的命題。"], cognitiveProcess: ["diagnose-number-error-in-negative-helper", "repair-children-with-do-not"], representationType: "negative-agreement-repair", misconceptionTargets: ["use-doesnt-with-plural-subject"] },
    { stem: "A train notice says, 'The train does not leave at six.' Which line says this correctly?", options: ["The train isn't leave at six.", "The train not leaves at six.", "The train doesn't leaves at six.", "The train doesn't leave at six."], answerIndex: 3, reasons: ["isn't 不能直接帶 leave。", "not 不能直接否定 leaves。", "doesn't 後不保留 leaves 的 s。", "doesn't leave 正確否定單數 train 的固定班次。"], reviews: ["notice 談的是六點固定班次，不是一次臨時過去事件。", "第四項以現在簡單式描述時刻表，助動詞與原形分工正確。"], cognitiveProcess: ["translate-no-six-departure-into-negative-schedule", "use-doesnt-leave-for-train"], representationType: "notice-negation-transfer", misconceptionTargets: ["double-mark-third-person-in-negative"] },
  ]),
  ...skillQuestions("107", [
    { stem: "I don't have ___ money with me.", options: ["any", "no", "nothing", "never"], answerIndex: 0, reasons: ["any 可放在 don't have 的否定範圍內。", "no 會和 don't 形成雙重否定。", "nothing 不能直接修飾 money。", "never 不能作 money 的限定詞。"], reviews: ["don't 已經提供否定，名詞 money 使用 any。", "第一項保留我身上沒錢的單一否定意思。"], cognitiveProcess: ["pair-dont-have-with-any", "avoid-no-after-negative-helper"], representationType: "negative-any-cloze", misconceptionTargets: ["stack-dont-and-no"] },
    { stem: "___ called the office last night.", options: ["Anybody didn't", "Nobody", "Nobody didn't", "Not anybody"], answerIndex: 1, reasons: ["Anybody didn't 不是標準主詞與助動排列。", "Nobody 本身否定主詞，直接接 called。", "Nobody didn't 在同一子句使用兩個否定。", "Not anybody 缺少能形成自然主詞片語的結構。"], reviews: ["意思是沒有任何人打電話，nobody 已完整表達。", "第二項用 called 標過去，不再加入 didn't。"], cognitiveProcess: ["select-negative-pronoun-as-subject", "retain-affirmative-past-verb-after-nobody"], representationType: "negative-subject-cloze", misconceptionTargets: ["add-didnt-after-nobody"] },
    { stem: "Mia has ___ seen snow.", options: ["no", "not never", "never", "doesn't never"], answerIndex: 2, reasons: ["no 不能直接修飾 seen。", "not never 不是單純的從未經驗。", "never 放在 has 與 seen 間，表示到目前一次也沒有。", "doesn't 不能插入完成式，也和 never 重複否定。"], reviews: ["has seen 建立現在完成式，所缺的是經驗頻率副詞。", "第三項以單一 never 清楚否定所有過去到現在的經驗。"], cognitiveProcess: ["insert-never-in-perfect-experience", "reject-not-never-as-simple-negative"], representationType: "never-perfect-cloze", misconceptionTargets: ["combine-doesnt-with-never"] },
    { stem: "Which line clearly says that we bought nothing?", options: ["We didn't buy nothing.", "We never didn't buy anything.", "We don't bought no thing.", "We didn't buy anything."], answerIndex: 3, reasons: ["didn't 與 nothing 疊成雙重否定。", "never 與 didn't 同時否定且意思混亂。", "don't 與 bought 時態不合，no thing 也不自然。", "didn't buy anything 使用一套完整過去否定。"], reviews: ["目標意思是一次過去購買中沒有買任何東西。", "第四項由 didn't 承擔否定，anything 留在其範圍內。"], cognitiveProcess: ["express-zero-purchase-in-standard-negative", "choose-didnt-anything-pattern"], representationType: "standard-negative-selection", misconceptionTargets: ["use-nothing-after-didnt"] },
    { stem: "There is no food in the box. Which line has the same meaning?", options: ["There isn't any food in the box.", "There isn't no food in the box.", "There doesn't any food in the box.", "There never is no food in the box."], answerIndex: 0, reasons: ["isn't any 使用單一否定，等於 no food。", "isn't 與 no 同時否定。", "there is 結構不能改用 doesn't。", "never 與 no 疊加且改變時間範圍。"], reviews: ["no food 與 not any food 是兩套可互換的標準寫法。", "第一項只更換否定形式，仍限定同一個 box。"], cognitiveProcess: ["convert-no-food-to-not-any-food", "preserve-there-be-structure"], representationType: "negative-paraphrase", misconceptionTargets: ["combine-isnt-and-no"] },
    { stem: "A student writes 'I don't know nothing about the plan.' Which one-word change fixes it?", options: ["don't → doesn't", "nothing → anything", "know → knew", "plan → plans"], answerIndex: 1, reasons: ["I 不搭配 doesn't，且雙重否定仍存在。", "anything 與 don't know 搭配，保留完全不知道的意思。", "改成 knew 會造成 don't knew 錯誤。", "plans 的數量變化不能修正否定。"], reviews: ["問題在 don't 與 nothing 同時出現。", "第二項保留 don't，將受詞改為否定範圍內的 anything。"], cognitiveProcess: ["locate-double-negative-object", "repair-nothing-to-anything"], representationType: "one-word-negative-repair", misconceptionTargets: ["change-tense-instead-of-negative-pronoun"] },
    { stem: "Sam never ___ late for practice.", options: ["doesn't arrive", "don't arrive", "arrives", "not arrives"], answerIndex: 2, reasons: ["never 已否定，不能再加 doesn't。", "don't 既重複否定也不配合 Sam。", "arrives 配合 Sam，never 單獨表達從不遲到。", "not 不能直接放在 arrives 前形成此結構。"], reviews: ["never 本身已涵蓋每次練習的否定頻率。", "第三項讓動詞保持肯定形式並配合第三人稱。"], cognitiveProcess: ["treat-never-as-sole-negative-marker", "agree-arrives-with-sam"], representationType: "never-habit-cloze", misconceptionTargets: ["add-doesnt-after-never"] },
    { stem: "Which sentence has one negative part and no double negative?", options: ["Nobody didn't answer.", "I don't never eat fish.", "We can't find nothing.", "Nothing was broken."], answerIndex: 3, reasons: ["Nobody 與 didn't 同時否定。", "don't 與 never 重複否定。", "can't 與 nothing 疊加。", "Nothing 本身否定主詞，was broken 不再加 not。"], reviews: ["題目要求標準書面形式中的單一否定。", "第四項用 Nothing 一次完成否定，其餘各有兩個否定來源。"], cognitiveProcess: ["count-negative-markers-across-clauses", "identify-nothing-with-affirmative-verb"], representationType: "negative-form-classification", misconceptionTargets: ["count-only-not-and-ignore-negative-pronouns"] },
    { stem: "No letter came to the house all day. Which line says this with one negative?", options: ["No letter arrived.", "No letter didn't arrive.", "A letter never didn't arrive.", "Nothing didn't come no time."], answerIndex: 0, reasons: ["No letter 作否定主詞，arrived 保持肯定過去形式。", "no 與 didn't 同時否定。", "never 和 didn't 衝突，還把主詞改成一封信。", "nothing、didn't、no 疊加多重否定。"], reviews: ["no letter came 和 no letter arrived 指向相同的送達結果。", "第一項只用 no letter 一個否定來源，時間由 arrived 表示。"], cognitiveProcess: ["convert-empty-mailbox-evidence-to-no-message", "avoid-extra-didnt-after-no-subject"], representationType: "evidence-to-standard-negative", misconceptionTargets: ["add-negative-helper-after-no-noun"] },
    { stem: "Leo says, 'I am not unhappy, but I am not very happy, either.' How does Leo feel?", options: ["He is never happy.", "He does not feel unhappy or very happy.", "He does not feel anything.", "He is unhappy all the time."], answerIndex: 1, reasons: ["Leo 沒有說自己永遠不快樂。", "第二項分別保留 not unhappy 與 not very happy，沒有擴大語氣。", "句子仍清楚描述感受，不能推成沒有任何感覺。", "unhappy all the time 和 Leo 的兩個否定陳述都衝突。"], reviews: ["兩個 not 各自作用在不同形容詞片語，不是互相抵消。", "第二項同時保留不算難過與沒有非常開心這兩個界線。"], cognitiveProcess: ["interpret-negation-of-negative-adjective", "avoid-collapsing-not-unhappy-into-unhappy"], representationType: "negation-scope-meaning", misconceptionTargets: ["treat-two-negative-parts-as-strong-negative"] },
    { stem: "A writer means that the day was quiet but writes, 'Nothing didn't happen.' Which change says the idea clearly?", options: ["Anything didn't happen.", "Nothing not happened.", "Nothing happened.", "Nothing did happened."], answerIndex: 2, reasons: ["Anything didn't 不是自然主詞否定排列。", "not 不能直接放在 happened 前。", "Nothing 本身表示沒有事情發生，happened 保持肯定過去式。", "did happened 重複過去標記，且未解決否定。"], reviews: ["the day was quiet 提供沒有事情發生的目標意思。", "第三項刪除多餘 didn't，讓 Nothing 成為唯一否定主詞。"], cognitiveProcess: ["repair-nothing-didnt-with-intended-zero-event", "keep-past-happened-after-negative-subject"], representationType: "double-negative-repair", misconceptionTargets: ["remove-negative-pronoun-instead-of-helper"] },
    { stem: "A: Did you see anyone near the gate? B: ___. B saw no people there.", options: ["I didn't see nobody.", "I never didn't see anyone.", "I saw anybody.", "I didn't see anyone."], answerIndex: 3, reasons: ["didn't 與 nobody 形成雙重否定。", "never 與 didn't 疊加，無法表達單次事件。", "anybody 通常不直接放在此肯定句表示零人。", "didn't see anyone 清楚表示當時沒看到任何人。"], reviews: ["B saw no people 是過去一次事件的零人結果。", "第四項以 didn't 和 anyone 配對，也直接回應 Did you see。"], cognitiveProcess: ["answer-past-anyone-question-negatively", "select-didnt-see-anyone-dialogue-form"], representationType: "dialogue-negative-transfer", misconceptionTargets: ["reply-with-didnt-nobody"] },
  ]),
  ...skillQuestions("108", [
    { stem: "Is Amy at home? Yes, ___.", options: ["she is", "she does", "she has", "she can"], answerIndex: 0, reasons: ["問句以 is 開頭，肯定簡答沿用 is，並以 she 代替 Amy。", "does 用來回應一般動詞問句，不回應 Is Amy。", "has 並未出現在問句中，也不是此處的 be 動詞。", "can 表示能力，和詢問是否在家的問句不相符。"], reviews: ["Is Amy 決定簡答的助動詞是 is。", "Amy 是單數女性人名，簡答主詞應改為 she。"], cognitiveProcess: ["match-is-question-with-is-short-answer", "replace-amy-with-she-in-reply"], representationType: "be-short-answer-cloze", misconceptionTargets: ["answer-be-question-with-do"] },
    { stem: "Does Ben carry a lunch box? No, ___.", options: ["he isn't", "he doesn't", "he didn't", "he hasn't"], answerIndex: 1, reasons: ["isn't 回應 be 動詞問句，不能回應 Does Ben carry。", "問句使用 does，否定簡答應為 he doesn't。", "didn't 會把現在的一般問句改成過去。", "hasn't 屬於 have 或完成式的簡答，與 does 不配。"], reviews: ["Does 開頭的問句在否定簡答中變成 doesn't。", "Ben 在簡答中以代名詞 he 承接。"], cognitiveProcess: ["track-does-into-negative-short-answer", "pronoun-substitute-ben-as-he"], representationType: "do-short-answer-cloze", misconceptionTargets: ["switch-present-does-to-past-didnt"] },
    { stem: "Did the workers lock the gate? Yes, ___.", options: ["they do", "they were", "they did", "they have"], answerIndex: 2, reasons: ["do 是現在式，沒有保留問句的 did。", "were 屬於 be 動詞，問句問的是 lock 這個動作。", "did 與問句的過去式助動詞一致，they 也承接 workers。", "have 會改成完成式，並非原問句的時態。"], reviews: ["Did 已經標示過去，肯定簡答要重複 did。", "複數 workers 在回應中應使用 they。"], cognitiveProcess: ["retain-past-did-in-worker-reply", "map-plural-workers-to-they"], representationType: "past-short-answer-cloze", misconceptionTargets: ["answer-did-question-with-do"] },
    { stem: "Can Lily ride this bike? No, ___.", options: ["she doesn't", "she isn't", "she won't", "she can't"], answerIndex: 3, reasons: ["doesn't 回應一般動詞現在式，沒有沿用 can。", "isn't 回應 be 動詞，不能表示沒有騎車能力。", "won't 表示不願或未來不會，改變了能力問題。", "can't 是 can 的否定簡答，she 也正確代替 Lily。"], reviews: ["問句測的是 can 所表達的能力，不是習慣或未來意願。", "否定回答需同時保留 can 並把 Lily 換成 she。"], cognitiveProcess: ["negate-can-with-cant-in-short-reply", "preserve-ability-meaning-for-lily"], representationType: "modal-short-answer-cloze", misconceptionTargets: ["replace-cant-with-wont"] },
    { stem: "Have the buses arrived? Yes, ___.", options: ["they have", "they do", "it has", "they are"], answerIndex: 0, reasons: ["have 與問句的完成式一致，they 承接複數 buses。", "do 不回應 Have...arrived 這個完成式問句。", "it 是單數，不能代替 buses；has 也不配合複數。", "are 會把完成式誤當成 be 動詞問句。"], reviews: ["問句首的 Have 是簡答必須沿用的助動詞。", "buses 是複數，所以回答主詞與助動詞為 they have。"], cognitiveProcess: ["match-have-arrived-with-have-reply", "maintain-plural-buses-agreement"], representationType: "perfect-short-answer-cloze", misconceptionTargets: ["answer-have-question-with-are"] },
    { stem: "Will Sam join the game tonight? No, ___.", options: ["he doesn't", "he won't", "he isn't", "he didn't"], answerIndex: 1, reasons: ["doesn't 是一般現在式簡答，不能回應 will。", "won't 是 will not 的縮寫，正確回應未來是否參加。", "isn't 回應 be 動詞，與 join 的未來問句無關。", "didn't 會改成已發生的過去事件。"], reviews: ["tonight 與 will 建立未來情境，否定簡答應保留 will。", "Sam 以 he 承接，因此完整簡答是 he won't。"], cognitiveProcess: ["contract-will-not-in-sam-reply", "keep-future-time-in-short-answer"], representationType: "future-short-answer-cloze", misconceptionTargets: ["answer-will-question-with-doesnt"] },
    { stem: "Are the boys ready to leave? Yes, ___.", options: ["he is", "they do", "they are", "the boys do"], answerIndex: 2, reasons: ["he is 是單數，不能承接 boys。", "do 不回應 Are 開頭的 be 動詞問句。", "they are 同時配合複數 boys 與問句的 are。", "the boys do 不但未改成代名詞，也用了錯誤助動詞。"], reviews: ["Are 決定肯定簡答仍使用 are。", "the boys 是複數第三人稱，在簡答中換成 they。"], cognitiveProcess: ["coordinate-are-with-they-for-boys", "reject-singular-pronoun-in-plural-reply"], representationType: "plural-be-short-answer", misconceptionTargets: ["use-he-for-boys"] },
    { stem: "Has Nora finished the report? No, ___.", options: ["she isn't", "she doesn't", "she didn't", "she hasn't"], answerIndex: 3, reasons: ["isn't 不能回應 has finished 的完成式。", "doesn't 會把問題改成一般現在式。", "didn't 改變時態，也沒有沿用 has。", "hasn't 正確否定 has，she 則承接 Nora。"], reviews: ["Has...finished 是現在完成式，簡答不可改用 do 或 be。", "否定回答把 has not 縮寫為 hasn't。"], cognitiveProcess: ["form-negative-perfect-reply-for-nora", "retain-has-auxiliary-from-question"], representationType: "negative-perfect-short-answer", misconceptionTargets: ["answer-perfect-question-with-didnt"] },
    { stem: "Do your parents work on Sunday? Yes, ___.", options: ["they do", "you do", "they are", "we work"], answerIndex: 0, reasons: ["they do 以 they 代替 your parents，並沿用 do。", "you 指向聽者本人，沒有承接 parents。", "are 不回應 work 這個一般動詞問句。", "we 會把回答者算入 parents，且不是標準簡答形式。"], reviews: ["your parents 從提問者角度是複數第三人稱，回答時用 they。", "Do 開頭的肯定簡答保留 do，不重複主要動詞 work。"], cognitiveProcess: ["shift-your-parents-to-they", "shorten-do-work-question-with-do"], representationType: "perspective-shift-short-answer", misconceptionTargets: ["retain-you-in-answer-about-parents"] },
    { stem: "Was the phone on the table? No, ___.", options: ["it doesn't", "it wasn't", "it isn't", "they weren't"], answerIndex: 1, reasons: ["doesn't 不回應 was 開頭的過去 be 問句。", "wasn't 與問句時態一致，it 也承接單數 phone。", "isn't 是現在式，會改變問句的時間。", "they weren't 同時錯在複數代名詞與動詞形式。"], reviews: ["Was 已把位置問題放在過去，否定簡答需使用 wasn't。", "the phone 是單數物品，代名詞為 it。"], cognitiveProcess: ["preserve-past-be-in-phone-reply", "choose-it-for-singular-object"], representationType: "past-be-short-answer", misconceptionTargets: ["replace-wasnt-with-isnt"] },
    { stem: "May I open the window? Yes, ___.", options: ["you are", "you do", "you may", "I may"], answerIndex: 2, reasons: ["are 不回應 may 所提出的許可問題。", "do 不能代替情態助動詞 may。", "回答者對提問者說 you may，助動詞也與問句一致。", "I may 仍指提問者自己的 I，沒有完成視角轉換。"], reviews: ["問句中的 I 對回答者而言是 you。", "題目要求以同一助動詞形成簡答，因此選 you may。"], cognitiveProcess: ["shift-i-to-you-in-permission-reply", "echo-may-without-changing-modal"], representationType: "permission-short-answer", misconceptionTargets: ["keep-i-in-response-to-speaker"] },
    { stem: "Could Grace hear the news? No, ___.", options: ["she doesn't", "Grace wasn't", "she hasn't", "she couldn't"], answerIndex: 3, reasons: ["doesn't 會把 could 問句改成一般現在式。", "wasn't 回應 be 動詞，不能表示當時聽不到。", "hasn't 屬於完成式，未沿用 could。", "couldn't 是 could not 的縮寫，she 正確承接 Grace。"], reviews: ["Could 在此詢問過去是否聽得到，否定簡答必須保留 could。", "Grace 換成 she 後，唯一完整匹配是 she couldn't。"], cognitiveProcess: ["answer-past-ability-with-couldnt", "resolve-grace-pronoun-in-announcement-context"], representationType: "past-modal-short-answer", misconceptionTargets: ["answer-could-question-with-wasnt"] },
  ]),
  ...skillQuestions("109", [
    { stem: "Grace reads on the bus. I read on the bus, ___.", options: ["too", "either", "neither", "not"], answerIndex: 0, reasons: ["too 放在肯定句尾，表示我也在公車上閱讀。", "either 在此用法通常跟在否定句後。", "neither 不能單獨接在這個肯定完整句尾。", "not 會造成不完整結構，也與前句的相同情況不合。"], reviews: ["兩個 read on the bus 都是肯定陳述。", "句尾附和肯定情況時，too 是符合位置與語意的選項。"], cognitiveProcess: ["identify-two-positive-reading-habits", "place-too-after-second-clause"], representationType: "positive-too-cloze", misconceptionTargets: ["use-either-after-positive-clause"] },
    { stem: "Jack can't lift the box. Victor can't lift it, ___.", options: ["too", "either", "also", "neither"], answerIndex: 1, reasons: ["too 通常在肯定句尾表示也，這裡的 can't 是否定。", "either 放在否定句尾，表示 Victor 也搬不動。", "also 一般放在主要動詞前或 be 動詞後，不放在此句尾。", "neither 需要另組成 Neither can Victor，不能直接接在完整句尾。"], reviews: ["兩句都含 can't，因此是相同的否定情況。", "完整否定句後的附和字應為 either。"], cognitiveProcess: ["classify-cant-lift-as-negative-agreement", "select-sentence-final-either"], representationType: "negative-either-cloze", misconceptionTargets: ["append-too-to-negative-modal"] },
    { stem: "Ben was tired after the game. I was tired, ___.", options: ["either", "neither", "too", "no"], answerIndex: 2, reasons: ["either 通常接在否定句尾，但 was tired 是肯定句。", "neither 不能作為這個完整肯定句的句尾附和。", "too 表示我也累，和 Ben 的情況一致。", "no 不能放在逗號後形成此種附和句。"], reviews: ["tired 雖是不舒服的狀態，句法上仍是肯定的 was tired。", "第三項使用 too，不會因詞義不愉快而誤選 either。"], cognitiveProcess: ["separate-tired-meaning-from-clause-polarity", "attach-too-to-past-be-statement"], representationType: "positive-state-too-cloze", misconceptionTargets: ["treat-tired-as-grammatical-negative"] },
    { stem: "Nora doesn't eat fish. Lily doesn't eat fish, ___.", options: ["too", "also", "neither", "either"], answerIndex: 3, reasons: ["too 會與 doesn't 的否定形式不合。", "also 不放在此完整否定句的句尾。", "neither 若要使用，必須改成 Neither does Lily。", "either 正確放在第二個否定句尾，表示 Lily 也不吃魚。"], reviews: ["doesn't 明確標示兩句都是否定習慣。", "第四項保留完整句，再用 either 表示相同否定。"], cognitiveProcess: ["parallel-two-negative-eating-habits", "contrast-either-with-neither-inversion"], representationType: "negative-habit-either", misconceptionTargets: ["use-neither-as-final-adverb"] },
    { stem: "This bag is ___ heavy for the child to carry.", options: ["too", "either", "also", "neither"], answerIndex: 0, reasons: ["too heavy to carry 表示重到孩子無法搬動。", "either 不能在此修飾形容詞 heavy。", "also heavy 只表示也很重，不能和 to carry 組成程度結果。", "neither 不用來表示超過可承受的重量。"], reviews: ["for the child to carry 提供重量造成無法完成動作的結果。", "此處 too 是程度副詞，不是句尾的『也』。"], cognitiveProcess: ["read-too-heavy-as-excessive-degree", "distinguish-degree-too-from-agreement-too"], representationType: "too-degree-cloze", misconceptionTargets: ["assume-too-always-means-also"] },
    { stem: "Amy can come before noon. Sam can come, ___.", options: ["either", "too", "neither", "not"], answerIndex: 1, reasons: ["either 通常跟隨否定句，兩句都有 can。", "too 表示 Sam 也能來，和 Amy 的肯定能力一致。", "neither 需要搭配倒裝句，且語意為兩者都不能。", "not 會使第二句結構與意思都不完整。"], reviews: ["can come 在兩句中都是肯定形式。", "第二項位於完整肯定句末，表示 Sam 具有相同情況。"], cognitiveProcess: ["align-two-positive-can-clauses", "use-too-after-modal-statement"], representationType: "modal-too-cloze", misconceptionTargets: ["choose-either-because-can-is-auxiliary"] },
    { stem: "The bus didn't stop here. The train didn't stop here, ___.", options: ["too", "neither", "either", "also"], answerIndex: 2, reasons: ["too 不搭配 didn't 形成句尾否定附和。", "neither 不能直接接在已完整的否定句後。", "either 放在第二個 didn't 句尾，表示火車也沒有停。", "also 的正常位置不是此否定句句尾。"], reviews: ["兩個 didn't stop 描述相同的過去否定事件。", "第三項讓第二句保留完整語序，再以 either 附和。"], cognitiveProcess: ["compare-past-nonstop-events", "add-either-to-second-didnt-clause"], representationType: "past-negative-either", misconceptionTargets: ["append-neither-after-complete-negative"] },
    { stem: "Wendy is unhappy about the news. Ella is unhappy, ___.", options: ["either", "neither", "not", "too"], answerIndex: 3, reasons: ["either 需要句法上的否定，而 is unhappy 沒有 not。", "neither 不能放在這個肯定結構的句尾。", "not 無法完成第二句的附和意思。", "too 表示 Ella 也不快樂；unhappy 的字義不會把句子變成否定句。"], reviews: ["判斷 too 或 either 要看句法是否有否定標記，不看情緒好壞。", "兩句都是 be 動詞肯定句，所以第四項唯一合適。"], cognitiveProcess: ["treat-unhappy-as-positive-clause-grammar", "choose-too-despite-negative-emotion"], representationType: "semantic-negative-positive-syntax", misconceptionTargets: ["use-either-after-unhappy"] },
    { stem: "Leo doesn't watch TV at night. Mia doesn't watch TV, either. What is true?", options: ["Neither Leo nor Mia watches TV at night.", "Only Leo watches TV at night.", "Mia watches TV but Leo does not.", "Both of them watch TV at night."], answerIndex: 0, reasons: ["兩個否定句合起來表示 Leo 和 Mia 晚上都不看電視。", "原文沒有說 Leo 會看，反而明確說 doesn't watch。", "Mia 的句尾 either 表示她與 Leo 一樣不看。", "both watch 與兩個 doesn't watch 完全相反。"], reviews: ["either 把 Mia 的否定情況連到 Leo 的否定情況。", "第一項用 neither...nor 準確總結兩人都不看的事實。"], cognitiveProcess: ["infer-shared-negative-tv-habit", "paraphrase-two-either-clauses-with-neither-nor"], representationType: "either-meaning-interpretation", misconceptionTargets: ["read-either-as-choice-between-people"] },
    { stem: "The lights aren't on. The fan isn't on, ___.", options: ["too", "either", "also", "so"], answerIndex: 1, reasons: ["too 通常附和肯定完整句。", "either 接在 isn't on 後，表示風扇也沒有開。", "also 在這個否定句尾的位置不自然。", "so 不能直接放在完整句尾表達否定附和。"], reviews: ["aren't 與 isn't 都讓所在子句成為否定句。", "第二項以 either 連結兩個未開啟的設備狀態。"], cognitiveProcess: ["link-two-negative-device-states", "position-either-after-isnt-on"], representationType: "be-negative-either", misconceptionTargets: ["use-too-after-isnt"] },
    { stem: "A student wants to agree with 'I don't like the noise' but writes 'I don't like it, too.' Which change is needed?", options: ["don't → didn't", "like → likes", "too → either", "it → them"], answerIndex: 2, reasons: ["改成 didn't 只改變時間，仍留下否定句尾的 too。", "I 不搭配 likes，而且沒有處理附和字。", "否定完整句的句尾附和應把 too 改為 either。", "noise 可由 it 代替，改成 them 反而造成單複數錯誤。"], reviews: ["目標是附和 don't like 這個否定意見。", "唯一需要修正的是句尾副詞，第三項不改變原意或時態。"], cognitiveProcess: ["diagnose-too-in-negative-agreement", "repair-only-final-agreement-adverb"], representationType: "too-either-edit", misconceptionTargets: ["repair-agreement-by-changing-tense"] },
    { stem: "A: I finished my report this morning. B: I finished mine, ___.", options: ["either", "neither", "not", "too"], answerIndex: 3, reasons: ["either 不跟在 finished 這個肯定句後。", "neither 會表達否定附和，和 B 已完成的句子衝突。", "not 不能在句尾補出『也完成』的意思。", "too 表示 B 也完成自己的報告，正好回應 A。"], reviews: ["兩人都說 finished，對話要表達相同的肯定結果。", "mine 已代替 my report，句尾只需用 too 完成附和。"], cognitiveProcess: ["resolve-mine-and-shared-completion", "close-positive-dialogue-with-too"], representationType: "dialogue-too-transfer", misconceptionTargets: ["select-either-by-habit-without-reading-polarity"] },
  ]),
  ...skillQuestions("110", [
    { stem: "Mia plays tennis after school. So ___ I.", options: ["do", "am", "did", "have"], answerIndex: 0, reasons: ["plays 是一般現在式，附和句以 do 代替 play tennis。", "am 只適用於前句主要結構是 be 動詞。", "did 會把現在習慣改成過去。", "have 不對應 plays 的一般現在式。"], reviews: ["前句的 plays 決定使用 do 類助動詞。", "新主詞是 I，所以肯定附和為 So do I。"], cognitiveProcess: ["recover-do-from-present-plays", "form-so-do-i-inversion"], representationType: "so-present-inversion-cloze", misconceptionTargets: ["use-be-in-so-after-action-verb"] },
    { stem: "Leo is tired after work. So ___ Ben.", options: ["does", "is", "did", "has"], answerIndex: 1, reasons: ["does 不代替前句的 is tired。", "is 同時對應 be 動詞與新的單數主詞 Ben。", "did 會錯誤改成過去的一般動詞附和。", "has 不屬於前句的結構。"], reviews: ["前句核心是 is tired，不是一般動詞動作。", "So 後倒裝，應依 Ben 使用 is。"], cognitiveProcess: ["carry-be-from-leo-state", "agree-inverted-is-with-ben"], representationType: "so-be-inversion-cloze", misconceptionTargets: ["default-to-so-do-after-be"] },
    { stem: "Amy can swim across the pool. So ___ Nora.", options: ["does", "is", "can", "swims"], answerIndex: 2, reasons: ["does 不能取代前句已有的情態助動詞 can。", "is 與能力問法無關。", "can 保留相同能力，並置於 Nora 前形成倒裝。", "swims 不是附和倒裝所需的助動詞。"], reviews: ["附和內容是兩人都 can swim。", "第三項保留 can，語序為 So can Nora。"], cognitiveProcess: ["echo-can-in-positive-agreement", "invert-modal-before-nora"], representationType: "so-modal-inversion", misconceptionTargets: ["replace-modal-with-do-in-agreement"] },
    { stem: "Jack didn't take the early bus. Neither ___ Victor.", options: ["does", "was", "had", "did"], answerIndex: 3, reasons: ["does 是現在式，與 didn't 不同時間。", "was 不對應 take 這個一般動詞。", "had 會改成過去完成式。", "did 沿用前句的過去助動詞，表示 Victor 也沒搭。"], reviews: ["didn't take 標示過去的一般動詞否定。", "Neither 已表達否定，後面只需肯定形式 did。"], cognitiveProcess: ["extract-did-from-didnt-take", "avoid-negative-didnt-after-neither"], representationType: "neither-past-inversion", misconceptionTargets: ["use-didnt-after-neither"] },
    { stem: "Grace has finished the book. So ___ Wendy.", options: ["has", "does", "is", "did"], answerIndex: 0, reasons: ["has 保留現在完成式，並與單數 Wendy 配合。", "does 會把 has finished 誤改成一般現在式。", "is 不對應完成式助動詞 has。", "did 會把時間與結構都改成簡單過去。"], reviews: ["前句的有限助動詞是 has，附和句不重複 finished。", "So has Wendy 表示 Wendy 也已完成同一本書。"], cognitiveProcess: ["retain-has-from-present-perfect", "invert-has-before-wendy"], representationType: "so-perfect-inversion", misconceptionTargets: ["reduce-perfect-agreement-to-do"] },
    { stem: "I am ready to begin. So ___ Sam.", options: ["am", "is", "does", "are"], answerIndex: 1, reasons: ["am 只和 I 配合，不能放在 Sam 前。", "is 配合新的第三人稱單數主詞 Sam。", "does 不代替前句的 be 動詞 am。", "are 不和單數 Sam 配合。"], reviews: ["附和句沿用 be 動詞，但形式要依新主詞改變。", "Sam 是單數第三人稱，因此答案不是照抄 am，而是 is。"], cognitiveProcess: ["change-am-to-is-for-new-subject", "build-so-is-sam-agreement"], representationType: "so-be-subject-agreement", misconceptionTargets: ["copy-am-before-sam"] },
    { stem: "They don't eat meat. Neither ___ we.", options: ["are", "did", "do", "don't"], answerIndex: 2, reasons: ["are 不對應 eat 這個一般現在式動詞。", "did 會把習慣改成過去。", "do 取自 don't，並在 Neither 後保持肯定形式。", "don't 和 Neither 重複否定。"], reviews: ["前句的一般現在式助動詞是 do。", "Neither 已經帶否定，因此倒裝部分寫 do we。"], cognitiveProcess: ["derive-do-from-present-negative", "prevent-double-negative-in-neither-do-we"], representationType: "neither-present-inversion", misconceptionTargets: ["repeat-dont-after-neither"] },
    { stem: "The bus wasn't late. Neither ___ the train.", options: ["did", "is", "were", "was"], answerIndex: 3, reasons: ["did 不對應 was late 的 be 動詞結構。", "is 改成現在式，沒有保留 wasn't 的時間。", "were 不和單數 the train 配合。", "was 由 wasn't 還原為肯定形式，並配合單數 train。"], reviews: ["Neither 後使用 wasn't 所含的助動詞 was，但不再加 not。", "the train 是單數，排除複數 were。"], cognitiveProcess: ["restore-was-from-wasnt", "match-was-to-singular-train"], representationType: "neither-past-be-inversion", misconceptionTargets: ["use-wasnt-after-neither"] },
    { stem: "Nora won't join the club trip. Neither will Ella. What does this mean?", options: ["Neither girl will join the trip.", "Only Nora will join the trip.", "Ella will join, but Nora will not.", "Both girls have already joined."], answerIndex: 0, reasons: ["Neither will Ella 附和 Nora 的 won't join，兩人都不參加。", "原文說 Nora won't join，不是只有她參加。", "Ella 的 Neither will 表示她也不參加。", "句子談未來不參加，沒有說已經加入。"], reviews: ["Neither will Ella 省略了重複的 join the club trip。", "第一項同時保留兩位女孩與未來否定。"], cognitiveProcess: ["expand-neither-will-ella", "summarize-two-future-nonparticipants"], representationType: "neither-inversion-meaning", misconceptionTargets: ["interpret-neither-as-contrast"] },
    { stem: "I walk to the office every day. My brother does the same. Which line puts the two ideas together?", options: ["So do my brother.", "So does my brother.", "So is my brother.", "So did my brother."], answerIndex: 1, reasons: ["my brother 是單數，不能用 do。", "does 配合單數主詞，並代替 walks to the office。", "is 不對應 walk 這個一般動詞。", "did 會把 every day 的現在習慣改成過去。"], reviews: ["does the same 明確表示兄弟有相同的現在習慣。", "倒裝後助動詞仍須配合後方主詞 my brother。"], cognitiveProcess: ["combine-repeated-walking-habit", "inflect-do-for-inverted-brother"], representationType: "so-combination-task", misconceptionTargets: ["use-do-with-singular-in-inversion"] },
    { stem: "A student writes 'Ben can't skate, and neither can't Leo.' Which change is needed?", options: ["neither isn't Leo", "neither doesn't Leo", "neither can Leo", "neither could Leo"], answerIndex: 2, reasons: ["isn't 不對應前句的 can。", "doesn't 既換了助動詞，也仍在 Neither 後重複否定。", "can 保留相同能力助動詞，Neither 已提供否定。", "could 會改變 can 所表達的現在能力。"], reviews: ["錯誤在 Neither 後又用了 can't。", "第三項刪除多餘 not，並維持前句的 can 與現在時間。"], cognitiveProcess: ["diagnose-negative-modal-after-neither", "repair-cant-to-can-in-inversion"], representationType: "neither-modal-repair", misconceptionTargets: ["double-negate-neither-with-cant"] },
    { stem: "A: I have never visited that island. B: ___.", options: ["So have I", "Neither did I", "So did I", "Neither have I"], answerIndex: 3, reasons: ["So 表示肯定附和，不能回應 never visited。", "did 改變了前句的現在完成式 have visited。", "So did I 同時錯在肯定方向與時態。", "Neither 表示相同否定經驗，have 也沿用前句完成式。"], reviews: ["never 使 A 的經驗陳述為否定。", "B 要同時保留否定方向與 have visited 的完成式，因此選第四項。"], cognitiveProcess: ["treat-never-experience-as-negative-antecedent", "select-neither-have-i-for-perfect"], representationType: "dialogue-neither-perfect-transfer", misconceptionTargets: ["use-so-after-never"] },
  ]),
  ...skillQuestions("111", [
    { stem: "A: Aren't you ready? B: Yes, I am. Which fact is true?", options: ["B is ready.", "B is not ready.", "B was ready yesterday.", "B does not understand the question."], answerIndex: 0, reasons: ["Yes, I am 肯定 I am ready，所以 B 已準備好。", "若 B 尚未準備好，應回答 No, I am not。", "回答沒有提供 yesterday 的過去資訊。", "簡答直接回應 ready 狀態，不能推成不懂問題。"], reviews: ["否定問句中的 Yes 仍肯定後面的 I am。", "第一項只陳述回答可確定的現在事實。"], cognitiveProcess: ["interpret-yes-to-negative-ready-question", "recover-positive-ready-proposition"], representationType: "negative-question-fact-interpretation", misconceptionTargets: ["translate-yes-as-not-ready"] },
    { stem: "A: Doesn't Mia live near the station? B: No, she doesn't. What does B mean?", options: ["Mia lived there before.", "Mia does not live near the station.", "Mia is at the station now.", "Mia does not know where the station is."], answerIndex: 1, reasons: ["簡答沒有談以前住在哪裡。", "No, she doesn't 否定 she lives near the station。", "live near 不是現在人在車站的意思。", "住處回答不能推論 Mia 是否知道車站位置。"], reviews: ["No 後的 she doesn't 明確否定原命題。", "第二項保留相同主詞、地點與一般現在式。"], cognitiveProcess: ["decode-no-she-doesnt-after-negative-question", "limit-inference-to-mia-residence"], representationType: "negative-do-question-meaning", misconceptionTargets: ["treat-no-as-confirming-negative-word"] },
    { stem: "A: Can't Ben swim? B: Yes, he can. What does B say about Ben?", options: ["Ben chooses not to swim.", "Ben could swim only before.", "Ben can swim.", "Ben cannot swim."], answerIndex: 2, reasons: ["回答談能力，沒有提供 Ben 選擇不游泳的資訊。", "can 是現在能力，不是只限過去的 could。", "Yes, he can 肯定 Ben can swim。", "cannot 與肯定簡答 he can 相反。"], reviews: ["Yes 不受問句中的 n't 影響，仍肯定 can swim。", "第三項和簡答的人稱、情態與動作完全一致。"], cognitiveProcess: ["affirm-can-swim-despite-negative-question", "separate-ability-from-refusal"], representationType: "negative-modal-question-meaning", misconceptionTargets: ["read-yes-he-can-as-cannot"] },
    { stem: "A: Hasn't the bus left yet? B: No, it hasn't. What can they still do?", options: ["They can only wait for another bus.", "They can no longer see the bus.", "They must walk because the bus left.", "They may still catch this bus."], answerIndex: 3, reasons: ["No, it hasn't 表示這班車還沒離開，不必斷定只能等下一班。", "回答沒有說看不見公車。", "公車尚未離開，所以不能推成已離開而必須走路。", "既然車還沒走，他們仍可能趕上。"], reviews: ["No, it hasn't 否定 the bus has left。", "第四項是根據尚未離站可作的合理行動，不把可能性說成保證。"], cognitiveProcess: ["infer-opportunity-from-no-it-hasnt", "preserve-may-in-bus-conclusion"], representationType: "negative-perfect-question-inference", misconceptionTargets: ["assume-no-means-bus-left"] },
    { stem: "The door is locked. A asks, 'Isn't the door locked?' B should answer ___.", options: ["Yes, it is.", "No, it is.", "Yes, it isn't.", "No, it does."], answerIndex: 0, reasons: ["門確實鎖著，Yes 肯定 it is locked。", "No, it is 把否定詞與肯定簡答混在一起。", "Yes, it isn't 同時肯定又否定同一命題。", "does 不能回應 is locked 的 be 動詞結構。"], reviews: ["已知事實 the door is locked 決定回答方向。", "英文 Yes, it is 的 Yes 與肯定簡答相互一致。"], cognitiveProcess: ["answer-negative-be-question-from-locked-fact", "coordinate-yes-with-it-is"], representationType: "evidence-based-negative-question-reply", misconceptionTargets: ["pair-yes-with-isnt"] },
    { stem: "The call record shows no call from Jack. A asks, 'Didn't Jack call?' B should say ___.", options: ["Yes, he didn't.", "No, he didn't.", "No, he did.", "Yes, he does."], answerIndex: 1, reasons: ["Yes 不能和 he didn't 組成一致的標準簡答。", "沒有 Jack 的來電紀錄支持 No, he didn't。", "No, he did 前後方向衝突，且 did 表示有打。", "does 是現在式，也不符合沒有過去來電的證據。"], reviews: ["no call from Jack 表示 Jack did not call。", "第二項用 No 否定 did Jack call，並保留過去式 did。"], cognitiveProcess: ["use-call-record-to-answer-didnt-question", "align-no-with-he-didnt"], representationType: "record-evidence-negative-past-reply", misconceptionTargets: ["say-yes-he-didnt"] },
    { stem: "The players have agreed to join the game. A asks, 'Won't they join us?' B should answer ___.", options: ["No, they will.", "Yes, they won't.", "Yes, they will.", "No, they don't."], answerIndex: 2, reasons: ["No 與 they will 的肯定命題方向不一致。", "Yes, they won't 同時肯定與否定，不能表達已答應參加。", "已答應參加支持 Yes, they will。", "don't 不回應 will，而且改成一般現在式。"], reviews: ["agreed to join 提供未來參加的事實依據。", "第三項以 Yes 肯定 they will join us。"], cognitiveProcess: ["map-agreement-evidence-to-will-join", "answer-wont-question-affirmatively"], representationType: "future-negative-question-reply", misconceptionTargets: ["match-yes-to-wont-word-form"] },
    { stem: "The teacher's list shows that Wendy did not come to school. A asks, 'Wasn't Wendy at school?' B should answer ___.", options: ["Yes, she wasn't.", "No, she isn't.", "Yes, she was.", "No, she wasn't."], answerIndex: 3, reasons: ["Yes 不和 she wasn't 的否定簡答一致。", "isn't 是現在式，無法回應老師記下的過去情況。", "Yes, she was 表示 Wendy 當時在校，和 did not come 相反。", "No, she wasn't 表示 Wendy 當時不在校，符合清單資訊。"], reviews: ["did not come to school 支持 Wendy was not at school。", "第四項同時維持過去式與否定事實。"], cognitiveProcess: ["translate-absent-record-into-wasnt", "select-no-for-false-school-presence"], representationType: "negative-past-be-evidence", misconceptionTargets: ["answer-yes-because-question-hasnt"] },
    { stem: "A: Aren't the shops open today? B: No, they aren't. What should a visitor expect?", options: ["The shops are closed today.", "The shops were open yesterday.", "Only one shop is open.", "The shops will open in a few minutes."], answerIndex: 0, reasons: ["No, they aren't 否定 shops are open，所以應預期今天關門。", "回答沒有提供昨天是否營業的資訊。", "they aren't 表示這些商店不開，不能推成只開一家。", "簡答未提供稍後一定開門的資訊。"], reviews: ["No 後的 aren't 是判讀營業狀態的核心。", "第一項不增加時間或數量猜測，只改述目前可知事實。"], cognitiveProcess: ["derive-closed-state-from-no-they-arent", "avoid-unsupported-reopening-time"], representationType: "negative-question-practical-inference", misconceptionTargets: ["assume-no-confirms-open"] },
    { stem: "Every visitor needs a ticket, and Sam is a visitor. A asks, 'Doesn't Sam need a ticket?' B should say ___.", options: ["No, he doesn't.", "Yes, he does.", "No, he isn't.", "Yes, he is."], answerIndex: 1, reasons: ["規則涵蓋 Sam，因此不能否定他需要票。", "Yes, he does 肯定 Sam needs a ticket，符合兩項前提。", "isn't 不回應 need 這個一般動詞。", "is 雖為肯定，但助動詞沒有配合 Does 問句。"], reviews: ["all visitors 與 Sam is a visitor 可推出 Sam needs a ticket。", "第二項用 does 回應 Doesn't，並以 Yes 肯定該結論。"], cognitiveProcess: ["apply-visitor-ticket-rule-to-sam", "form-yes-he-does-to-negative-do-question"], representationType: "rule-based-negative-question", misconceptionTargets: ["let-negative-question-reverse-known-rule"] },
    { stem: "A: Haven't you read my message? B: I read it this morning. Which short answer should B use?", options: ["No, I haven't.", "Yes, I did.", "Yes, I have.", "No, I don't."], answerIndex: 2, reasons: ["I read it 已證明讀過，不能回答 haven't。", "did 與事實相容，但題目要求回應 Have 開頭問句的簡答。", "Yes, I have 肯定已讀訊息，並沿用問句助動詞。", "don't 既改變結構，也否定了已讀事實。"], reviews: ["this morning 的 read 提供完成閱讀的證據。", "簡答需回扣 Haven't you，因此第三項在方向與助動詞上都一致。"], cognitiveProcess: ["connect-read-evidence-to-have-read", "prefer-matching-have-in-short-reply"], representationType: "negative-perfect-dialogue-reply", misconceptionTargets: ["answer-have-question-with-did"] },
    { stem: "Amy asked the speaker to repeat the news because she did not hear it. A asks, 'Couldn't Amy hear the news?' B should answer ___.", options: ["Yes, she does.", "No, she doesn't.", "Yes, she could.", "No, she couldn't."], answerIndex: 3, reasons: ["does 不回應 could 的過去能力或情況。", "doesn't 雖是否定，仍使用錯誤的現在助動詞。", "Yes, she could 表示聽得到，和要求重說的原因衝突。", "No, she couldn't 正確表達 Amy 當時沒聽到。"], reviews: ["asked to repeat because she did not hear 是明確的過去否定證據。", "第四項用 couldn't 保留問句形式，也和事實一致。"], cognitiveProcess: ["infer-couldnt-hear-from-repeat-request", "answer-negative-could-question-with-no"], representationType: "contextual-negative-modal-reply", misconceptionTargets: ["choose-yes-by-mirroring-couldnt"] },
  ]),
  ...skillQuestions("112", [
    { stem: "A: I enjoy cooking for my family. B: So do I. Which idea is true?", options: ["Both speakers enjoy cooking.", "Only A enjoys cooking.", "B does not cook for the family.", "Neither speaker enjoys cooking."], answerIndex: 0, reasons: ["So do I 表示 B 與 A 有相同的肯定喜好。", "B 明確附和 A，不是只有 A 喜歡。", "B 沒有否定 cooking，也未限定不為家人煮。", "Neither 與兩人的肯定陳述相反。"], reviews: ["A 的 enjoy cooking 是肯定句，B 用 So do I 附和。", "第一項只總結兩人共同表達的喜好。"], cognitiveProcess: ["interpret-so-do-i-as-shared-enjoyment", "summarize-two-positive-speakers"], representationType: "dialogue-positive-agreement-meaning", misconceptionTargets: ["read-so-as-contrast"] },
    { stem: "A: I don't need help with this box. B: I don't, either. What do the speakers agree about?", options: ["Both want someone to carry the box.", "Neither speaker needs help.", "Only B needs help.", "A needs help but B does not."], answerIndex: 1, reasons: ["兩人都說不需要幫忙，沒有要求別人搬。", "B 的 either 附和 A 的 don't need help。", "B 也說 I don't，不能推成只有 B 需要。", "A 與 B 的回答方向相同，不是相反。"], reviews: ["either 連結兩個 don't need help 的否定陳述。", "第二項以 neither 準確概括兩人都不需要協助。"], cognitiveProcess: ["join-two-dont-need-help-statements", "convert-either-dialogue-to-neither-summary"], representationType: "dialogue-negative-agreement-meaning", misconceptionTargets: ["treat-either-as-one-person-only"] },
    { stem: "A: I can meet at four. B: I can't. How are their answers different?", options: ["Both can meet at four.", "Neither can meet at four.", "A can meet then, but B cannot.", "B can meet before A."], answerIndex: 2, reasons: ["B 的 can't 排除兩人都能見面。", "A 已說 I can，所以不是兩人都不能。", "A 的 can 與 B 的 can't 形成明確相反情況。", "對話沒有提供 B 能較早見面的資訊。"], reviews: ["兩個回答只在 can 與 can't 上相反。", "第三項不增加其他時間，只保留四點能否見面的差異。"], cognitiveProcess: ["contrast-can-and-cant-across-speakers", "avoid-inventing-earlier-meeting-time"], representationType: "dialogue-opposite-ability", misconceptionTargets: ["ignore-negation-in-second-speaker"] },
    { stem: "A: The trip sounds fun, but I have a test that day. What does A decide?", options: ["A has already taken the test.", "A thinks the trip is boring.", "A will move the test to another day.", "A cannot join the trip that day."], answerIndex: 3, reasons: ["have a test 指那天有考試，不是已經考完。", "sounds fun 表示 A 覺得活動有趣。", "對話沒有說 A 能更改考試日期。", "but 後提出當天考試，表示 A 那天無法參加。"], reviews: ["but 將前面的正面評價轉到實際阻礙。", "第四項只判斷那一天的參加結果，不延伸成永遠不參加。"], cognitiveProcess: ["resolve-final-stance-after-but", "limit-trip-refusal-to-test-day"], representationType: "dialogue-final-intent", misconceptionTargets: ["treat-positive-opening-as-acceptance"] },
    { stem: "A: I finished the work before lunch. Which answer shows that B did the same?", options: ["So did I.", "Neither did I.", "I didn't, either.", "I was still working at lunch."], answerIndex: 0, reasons: ["So did I 表示 B 也在午餐前完成。", "Neither did I 用於附和否定句，但 A 是肯定完成。", "I didn't, either 表示 B 未完成，和 A 不同。", "午餐時仍在工作也表示 B 沒有同樣結果。"], reviews: ["A 的 finished 是肯定的過去完成結果。", "第一項用 did 代替 finished the work 並表達肯定附和。"], cognitiveProcess: ["select-reply-sharing-finished-result", "match-so-did-to-past-positive-statement"], representationType: "same-result-reply-selection", misconceptionTargets: ["use-neither-after-positive-past"] },
    { stem: "A: I don't drink coffee. B: I do. What does B show?", options: ["B does not drink coffee, either.", "B has a different habit.", "B drank coffee only once.", "B does not understand A."], answerIndex: 1, reasons: ["I do 肯定 drink coffee，並非也不喝。", "A 的 don't 與 B 的 do 顯示習慣不同。", "一般現在式沒有說只喝過一次。", "B 直接以 do 回應，不能推成沒有理解。"], reviews: ["第二位說話者省略了重複的 drink coffee。", "肯定 do 與前句 don't 對比，支持第二項。"], cognitiveProcess: ["recover-drink-coffee-after-i-do", "classify-do-versus-dont-as-opposition"], representationType: "elliptical-opposite-habit", misconceptionTargets: ["assume-short-do-always-agrees"] },
    { stem: "A: I am not worried about the rain. Which answer shows a different feeling?", options: ["Neither am I.", "I am not worried, either.", "I am.", "I feel fine, too."], answerIndex: 2, reasons: ["Neither am I 表示 B 也不擔心。", "not worried, either 是相同的否定態度。", "I am 省略 worried，表示 B 確實擔心，與 A 相反。", "fine 表示 B 也不擔心，仍與 A 相同。"], reviews: ["題目要求找出不同感受，不能只看句型不同。", "第三項的 am 承接 worried，肯定 B 的擔心狀態。"], cognitiveProcess: ["identify-reply-opposing-not-worried", "resolve-elliptical-i-am-as-worried"], representationType: "opposite-state-reply", misconceptionTargets: ["mistake-neither-for-disagreement"] },
    { stem: "A: I won't visit the market today. B: Neither will I. What is their shared plan?", options: ["They will visit at different times.", "Only B will visit today.", "They are already at the market.", "Neither speaker will visit the market today."], answerIndex: 3, reasons: ["Neither will I 表示相同的不去計畫，不是不同時間前往。", "B 並沒有肯定 will visit。", "對話談今天的未來計畫，沒有說已在市場。", "兩位說話者都表達今天不去市場。"], reviews: ["Neither will I 將 B 的未來行動連到 A 的 won't visit。", "第四項保留 today 的時間限制，不增加刻意避開等語氣。"], cognitiveProcess: ["expand-neither-will-in-market-dialogue", "state-shared-future-absence"], representationType: "shared-negative-plan", misconceptionTargets: ["read-neither-will-as-b-will-go"] },
    { stem: "A: I wanted the blue bag, but it was too expensive, so I bought the black one. Which bag did A buy?", options: ["The black bag", "The blue bag", "Both bags", "No bag"], answerIndex: 0, reasons: ["bought the black one 直接指出最後購買黑色包。", "wanted the blue bag 只是原本偏好，but 後價格改變了決定。", "句中只說買了 the black one，沒有買兩個。", "A 明確使用 bought，因此不是沒買。"], reviews: ["判斷行動要讀到 so 後的結果，不停在 wanted。", "第一項和代名詞 one 所承接的 black bag 一致。"], cognitiveProcess: ["follow-wanted-but-so-purchase-sequence", "resolve-one-to-black-bag"], representationType: "dialogue-event-outcome", misconceptionTargets: ["choose-initial-preference-over-final-action"] },
    { stem: "A: Would you like to play today? B: I can't today because I must help my father. Which idea cannot be known from the talk?", options: ["B is busy helping a family member today.", "B never likes playing games.", "B cannot play today.", "B tells why the answer is no today."], answerIndex: 1, reasons: ["must help my father 支持 B 今天忙著協助家人。", "一次因事不能玩，不能證明 B 永遠不喜歡遊戲。", "I can't today 直接支持今天不能玩。", "because 後的內容正是今天回答 no 的理由。"], reviews: ["today 將拒絕限制在單一日期。", "第二項加入 never 與喜好判斷，超出對話證據。"], cognitiveProcess: ["separate-one-day-refusal-from-permanent-dislike", "identify-unsupported-never-conclusion"], representationType: "dialogue-overgeneralization-check", misconceptionTargets: ["infer-permanent-preference-from-one-refusal"] },
    { stem: "A: I may arrive after six if the bus is late. What can the listener know?", options: ["A will arrive before six.", "The bus is always late.", "A might arrive after six.", "A has decided not to come."], answerIndex: 2, reasons: ["may 與 if 不支持一定在六點前抵達。", "一次條件句不能推出公車總是誤點。", "may arrive after six 正好表示六點後抵達的可能性。", "句子仍談抵達時間，沒有說不來。"], reviews: ["may 表可能，if the bus is late 提供發生條件。", "第三項保留 might 的不確定性，不把條件改寫成事實。"], cognitiveProcess: ["preserve-possibility-in-may-if-statement", "reject-certainty-and-frequency-overreach"], representationType: "evidence-limited-dialogue-inference", misconceptionTargets: ["turn-may-into-will"] },
    { stem: "A: I thought the room was empty, but then Mia and Ben spoke to me from inside. What does A understand now?", options: ["The room was empty all day.", "Mia and Ben were outside.", "A has entered the room.", "Someone is inside the room."], answerIndex: 3, reasons: ["Mia and Ben spoke from inside 和房間無人的想法相反。", "from inside 明確排除兩人在室外。", "A 是否進入房間沒有被說明。", "兩人從房內說話，足以確定房內有人。"], reviews: ["but then 引入可推翻原先想法的新證據。", "第四項只下最低限度結論，不猜 A 是否進門。"], cognitiveProcess: ["revise-empty-room-belief-from-voices", "infer-minimum-presence-without-identity"], representationType: "dialogue-evidence-revision", misconceptionTargets: ["retain-initial-belief-after-new-evidence"] },
  ]),
];

export const ENGLISH_U16_VOCABULARY_POLICY = Object.freeze({
  capQuestionBasis: "appendix-5-table-1",
  additionalLearningTerms: ["double", "empty", "lift", "lock", "message", "neither", "nor", "record", "skate"],
  properNames: ["Amy", "Ben", "Ella", "Grace", "Jack", "Leo", "Lily", "Mia", "Nora", "Sam", "Tina", "Victor", "Wendy"],
  grammarNotation: ["A", "B", "auxiliary", "clause", "negative", "object", "positive", "subject", "yes-no"],
  malformedDistractors: [],
});

export const ENGLISH_U16_SOURCE = Object.freeze({ unitId: UNIT_ID, lectures: ENGLISH_U16_LECTURES, questions: ENGLISH_U16_QUESTIONS, vocabularyPolicy: ENGLISH_U16_VOCABULARY_POLICY });
export const ENGLISH_UNIT_SOURCE = ENGLISH_U16_SOURCE;
