const UNIT_ID = "ENG_R4_U09";

function lecture(id, skillId, content) {
  return {
    id,
    skillId,
    ...content,
    sections: content.sections.map((section, index) => ({
      id: `${id}_SEC_${String(index + 1).padStart(2, "0")}`,
      ...section,
    })),
  };
}

function question({
  id,
  skillId,
  difficulty,
  stem,
  options,
  answerIndex,
  reasons,
  reviews,
  cognitiveProcess,
  representationType = "sentence-cloze",
  misconceptionTargets = [],
}) {
  return {
    id,
    skillId,
    stem,
    options,
    answerIndex,
    reasons,
    difficulty,
    cognitiveProcess,
    representationType,
    misconceptionTargets,
    reviews,
  };
}

export const ENGLISH_U09_LECTURES = [
  lecture("ENG_R4_L_S057", "ENG_R4_S057", {
    objectives: [
      "能以 be 動詞加現在分詞描述說話當下正在發生的動作。",
      "能辨認目前一段期間的暫時情況，不把進行式誤當成固定習慣。",
    ],
    sections: [
      {
        title: "進行式把事件看成正在展開",
        content: "現在進行式的基本結構是主詞 + am/is/are + V-ing。它把動作放在說話當下或目前一段時間中，讓讀者看到事情尚在進行，例如 The children are playing outside now. 句子必須同時有 be 動詞和現在分詞，少掉任何一部分都不完整。",
      },
      {
        title: "正在發生不只是一秒鐘",
        content: "進行式可以描述眼前動作，也可以描述目前期間的暫時安排。Dad is working from home this week. 不表示他說話瞬間一定坐在電腦前，而是說本週的工作方式暫時如此。判斷時要看事件是否有開始、尚未結束，而且不是長期不變的規律。",
      },
      {
        title: "用完整結構連接主詞與動作",
        content: "I 搭配 am，單數第三人稱搭配 is，you、we、they 與複數主詞搭配 are；主要動詞再變成 -ing。She reading 和 She is read 都不是現在進行式。先選對 be，再檢查後面的動詞是否為現在分詞。",
      },
      {
        title: "和習慣或事實分開",
        content: "Every day、usually 等反覆線索多半配現在簡單式；now、right now 或眼前畫面多半配現在進行式。Mia walks to school every day 說習慣，Mia is walking to school now 說目前動作。時間詞有幫助，但仍須核對整句語意。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S057_EX_01",
        prompt: "Look! Ben ___ across the street. (runs / is running / ran)",
        steps: ["Look 指向眼前畫面。", "主詞 Ben 是單數，使用 is。", "run 變成 running。"],
        answer: "is running",
        why: "Look! 表示動作正在眼前發生，所以不能用習慣性的 runs 或已結束的 ran。Ben 搭配 is，run 的現在分詞是 running，完整答案為 is running。",
      },
      {
        id: "ENG_R4_L_S057_EX_02",
        prompt: "This month, my aunt ___ with us. (stays / is staying / stayed)",
        steps: ["This month 限定目前期間。", "和長期住所相比，這是暫時居住。", "單數主詞使用 is staying。"],
        answer: "is staying",
        why: "題目只把居住情況限制在這個月，表示目前的暫時安排，而非一向如此。my aunt 是單數，因此以 is staying 呈現尚在持續的狀態。",
      },
      {
        id: "ENG_R4_L_S057_EX_03",
        prompt: "We ___ the last page right now. (read / are reading / reads)",
        steps: ["right now 指說話當下。", "We 使用 are。", "read 後加 -ing。"],
        answer: "are reading",
        why: "right now 把閱讀動作限定在目前，We 又是複數概念，所以需要 are reading。read 會變成一般習慣，reads 則無法和 We 搭配。",
      },
    ],
    misconceptions: [
      {
        belief: "動詞加 -ing 就已經是完整的現在進行式。",
        whyWrong: "現在分詞不能獨自作限定動詞，前面還要有 am、is 或 are。",
        correction: "看到 V-ing 時，回頭確認主詞後是否有合適的 be 動詞。",
      },
      {
        belief: "只要句子談現在，就一定使用現在進行式。",
        whyWrong: "現在的習慣、事實與長期狀態通常使用現在簡單式。",
        correction: "分辨事件是反覆成立，還是目前正在展開。",
      },
      {
        belief: "this week 表示未來，所以不能用現在進行式。",
        whyWrong: "this week 可包含現在，常用來說明目前期間的暫時情況。",
        correction: "先判斷該週是否正在進行，再看事件是否暫時。",
      },
      {
        belief: "進行式只能描述肉眼看得到的動作。",
        whyWrong: "它也能描述目前進行中的工作、學習或暫時安排。",
        correction: "確認事件是否在目前期間尚未結束，不必侷限於眼前畫面。",
      },
    ],
    checks: [
      {
        prompt: "Listen! The baby is crying. 哪個部分表示正在進行？",
        answer: "is crying",
        reason: "is 加 crying 共同形成現在進行式。",
      },
      {
        prompt: "I am taking the bus this week. 是固定習慣還是暫時安排？",
        answer: "暫時安排",
        reason: "this week 把情況限制在目前這段期間。",
      },
      {
        prompt: "They playing outside now. 缺少什麼？",
        answer: "are",
        reason: "複數主詞 They 的進行式需要 are playing。",
      },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S058", "ENG_R4_S058", {
    objectives: [
      "能依進行式主詞選用 am、is 或 are。",
      "能排除鄰近名詞干擾，找出真正控制 be 動詞的主詞。",
    ],
    sections: [
      {
        title: "be 動詞要和主詞一致",
        content: "現在進行式中的 am、is、are 不只是附加字，它們負責標示主詞與現在時間。I am waiting；he、she、it 與單數名詞用 is；you、we、they 與複數名詞用 are。後面的 V-ing 不會隨主詞改變。",
      },
      {
        title: "先找完整主詞",
        content: "The boy with two dogs is running. 真正主詞是單數 boy，with two dogs 只是補充，所以不能因為看到 dogs 就選 are。反過來，Mia and Ben are cooking 的主詞包含兩人，and 通常把它變成複數。",
      },
      {
        title: "I、you 與集合名詞",
        content: "I 固定使用 am，you 無論指一人或多人都使用 are。初階題中的 family、team、class 若被視為一個整體，常配單數 is；若題目直接使用 members、students 等複數名詞，則配 are。要依實際主詞寫法判斷，不靠中文人數猜測。",
      },
      {
        title: "be 與 V-ing 各有工作",
        content: "be 動詞跟主詞一致，現在分詞表達進行中的動作。The students are studies 同時錯在分詞形式；The student studying 又少了 is。完成句子後要分別檢查這兩個位置，不能只看其中一項。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S058_EX_01",
        prompt: "I ___ waiting for the bus. (am / is / are)",
        steps: ["主詞是 I。", "I 在現在式搭配 am。", "am waiting 形成完整進行式。"],
        answer: "am",
        why: "I 的 be 動詞現在式固定為 am，因此應寫 I am waiting。is 只適合單數第三人稱，are 則用於 you 或複數主詞。",
      },
      {
        id: "ENG_R4_L_S058_EX_02",
        prompt: "The girls near the door ___ talking. (am / is / are)",
        steps: ["主詞核心是 girls。", "girls 是複數。", "複數主詞搭配 are。"],
        answer: "are",
        why: "near the door 只是說明位置，不改變主詞。girls 是複數，所以用 are talking；is talking 只適合單數主詞。",
      },
      {
        id: "ENG_R4_L_S058_EX_03",
        prompt: "The teacher with three students ___ walking upstairs. (am / is / are)",
        steps: ["with 片語不是主詞核心。", "真正主詞 teacher 是單數。", "使用 is walking。"],
        answer: "is",
        why: "three students 離空格較近，卻只屬於 with 片語；執行 walking 的主詞核心是單數 teacher。因此答案是 is，不是 are。",
      },
    ],
    misconceptions: [
      {
        belief: "離空格最近的名詞決定 am、is 或 are。",
        whyWrong: "最近的名詞可能在介系詞片語中，不是真正主詞。",
        correction: "先去掉附加片語，再判斷主詞核心。",
      },
      {
        belief: "you 指一個人時應搭配 is。",
        whyWrong: "英文的 you 無論單複數，在現在式都搭配 are。",
        correction: "把 you are 視為固定搭配。",
      },
      {
        belief: "兩個姓名以 and 連接仍可使用 is。",
        whyWrong: "and 通常把兩個人或事物合成複數主詞。",
        correction: "逐一數清 and 連接的主詞成員，兩者並列時用 are。",
      },
      {
        belief: "選對 be 動詞後，主要動詞可保留原形。",
        whyWrong: "現在進行式還要求主要動詞成為現在分詞。",
        correction: "完成 am/is/are 後，再檢查 V-ing 拼法。",
      },
    ],
    checks: [
      {
        prompt: "You is listening. 應改哪個字？",
        answer: "is 改為 are",
        reason: "you 在現在式固定搭配 are。",
      },
      {
        prompt: "My parents are cooking. 為何用 are？",
        answer: "parents 是複數主詞",
        reason: "be 動詞要和主詞數量一致。",
      },
      {
        prompt: "The cat beside the boxes ___ sleeping.",
        answer: "is",
        reason: "主詞是單數 cat，boxes 只在 beside 片語中。",
      },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S059", "ENG_R4_S059", {
    objectives: [
      "能依動詞字尾形成正確的現在分詞。",
      "能分辨直接加 -ing、去 e、重複字尾與 ie 改 y 等拼字規則。",
    ],
    sections: [
      {
        title: "多數動詞直接加 -ing",
        content: "大多數動詞直接在原形後加 -ing，例如 read → reading、play → playing、wash → washing。字尾是 y 時通常保留 y，與第三人稱單數的 -ies 規則不同，所以 study 變 studying，不是 studiing。",
      },
      {
        title: "不發音 e 通常先去掉",
        content: "make、write、ride 等以不發音 e 結尾的動詞，通常去 e 再加 -ing：making、writing、riding。若字尾是 ee，如 see，兩個 e 保留，形成 seeing。不要只看到 e 就全部刪除。",
      },
      {
        title: "短母音後的單一子音可能重複",
        content: "run → running、sit → sitting、stop → stopping 都重複最後一個子音。基本判斷是短而重讀的字尾呈現子音、母音、子音；但 w、x、y 通常不重複，所以 snowing、fixing、playing 不多寫一個字母。",
      },
      {
        title: "ie 改成 y 再加 -ing",
        content: "die、lie、tie 的 ie 先改成 y，再加 -ing，得到 dying、lying、tying。這項變化可避免連續出現不自然的母音拼法。完成後應把結果讀回原動詞，確認沒有改變詞根。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S059_EX_01",
        prompt: "Mia is ___ a card. (makeing / making / makking)",
        steps: ["原形是 make。", "字尾 e 不發音，先去 e。", "加 -ing 得到 making。"],
        answer: "making",
        why: "make 以不發音 e 結尾，形成現在分詞時先去掉 e，再加 -ing，所以是 making。makeing 保留了多餘的 e，makking 又不該重複 k。",
      },
      {
        id: "ENG_R4_L_S059_EX_02",
        prompt: "The boy is ___ to school. (runing / running / runeing)",
        steps: ["run 是短母音加單一子音結尾。", "重複最後的 n。", "再加 -ing。"],
        answer: "running",
        why: "run 的字尾符合短母音後接單一子音，現在分詞要重複 n，形成 running。runing 少一個 n，runeing 也不是 run 的拼法。",
      },
      {
        id: "ENG_R4_L_S059_EX_03",
        prompt: "The dog is ___ under the table. (lieing / lying / liying)",
        steps: ["原形是 lie。", "把 ie 改成 y。", "加 -ing 形成 lying。"],
        answer: "lying",
        why: "lie 的現在分詞不是直接接 -ing，而要先將 ie 改為 y，再寫 lying。lieing 保留 ie，liying 則多放了一個不屬於詞根的 i。",
      },
    ],
    misconceptions: [
      {
        belief: "所有動詞只要直接加 -ing 就完成。",
        whyWrong: "make、run、lie 等字尾需要去 e、重複子音或改 ie。",
        correction: "加字尾前先辨認原形最後幾個字母與發音。",
      },
      {
        belief: "看到 e 結尾就一定刪掉 e。",
        whyWrong: "see 的 ee 要保留，現在分詞是 seeing。",
        correction: "區分單一不發音 e 與 ee 字尾。",
      },
      {
        belief: "子音結尾的動詞都重複最後一個字母。",
        whyWrong: "helping、washing 等不符合短母音加單一字尾子音的條件。",
        correction: "檢查完整字尾結構，不以最後一個字母單獨決定。",
      },
      {
        belief: "study 形成現在分詞時也要把 y 改成 i。",
        whyWrong: "y 改 i 是某些第三人稱或過去式規則，studying 保留 y。",
        correction: "把現在分詞規則與 -ies 規則分開。",
      },
    ],
    checks: [
      {
        prompt: "write 的現在分詞是什麼？",
        answer: "writing",
        reason: "去掉不發音 e，再加 -ing。",
      },
      {
        prompt: "swim 為何變成 swimming？",
        answer: "重複最後的 m",
        reason: "字尾是短母音後接單一子音。",
      },
      {
        prompt: "fix 是否要寫成 fixxing？",
        answer: "不用，應寫 fixing",
        reason: "x 結尾通常不重複。",
      },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S060", "ENG_R4_S060", {
    objectives: [
      "能將 be 動詞移到主詞前形成現在進行式問句。",
      "能把 not 放在 be 動詞後形成否定句，並以一致的 be 動詞簡答。",
    ],
    sections: [
      {
        title: "問句移動的是 be 動詞",
        content: "肯定句 She is reading. 改成一般問句時，把 is 移到主詞前：Is she reading? 不加入 do 或 does，主要動詞仍保留 reading。複數句 They are waiting 則改為 Are they waiting?。",
      },
      {
        title: "否定詞放在 be 後",
        content: "現在進行式否定句是主詞 + am/is/are + not + V-ing，例如 We are not leaving. 縮寫可寫 isn't、aren't；am not 通常不縮成 amn't。not 不能直接放在主詞後，也不能取代 be 動詞。",
      },
      {
        title: "疑問詞仍保留倒裝",
        content: "詢問地點或動作時，使用疑問詞 + am/is/are + 主詞 + V-ing，例如 What are they doing?、Where is Ben going?。疑問詞放最前面，後方仍維持 be 在主詞前的順序。",
      },
      {
        title: "簡短回答沿用 be 動詞",
        content: "Is Mia sleeping? 的回答是 Yes, she is. 或 No, she isn't.；Are the boys running? 則回答 Yes, they are.。不能用 do/does 回答，因為原問句的限定動詞是 be。回答前也要先核對前文事實。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S060_EX_01",
        prompt: "___ Tom carrying the box? (Do / Is / Does)",
        steps: ["carrying 顯示進行式。", "Tom 是單數，使用 is。", "問句把 Is 放到主詞前。"],
        answer: "Is",
        why: "carrying 需要 be 動詞，Tom 是單數，因此肯定結構為 Tom is carrying。改成問句只需把 Is 移到前面，不使用 Do 或 Does。",
      },
      {
        id: "ENG_R4_L_S060_EX_02",
        prompt: "They are playing outside. 改成否定句。",
        steps: ["保留複數主詞與 are。", "把 not 放在 are 後。", "playing 不改變。"],
        answer: "They are not playing outside.",
        why: "現在進行式否定只在 be 動詞後加入 not，因此 are playing 變成 are not playing。主要動詞不退回 play，也不加入 don't。",
      },
      {
        id: "ENG_R4_L_S060_EX_03",
        prompt: "A: Are the students taking a test? B: No, ___.",
        steps: ["問句使用 are。", "students 以 they 代替。", "否定簡答使用 they aren't。"],
        answer: "they aren't",
        why: "the students 是複數，回答時用 they；原問句的助動詞是 are，所以否定簡答為 they aren't。don't 無法回答 be 動詞問句。",
      },
    ],
    misconceptions: [
      {
        belief: "現在進行式問句也要加入 do 或 does。",
        whyWrong: "句中已有 am、is、are，可直接移到主詞前形成問句。",
        correction: "先找 be 動詞，再做主詞與 be 的位置交換。",
      },
      {
        belief: "否定句可寫成 She not is reading。",
        whyWrong: "not 應放在 is 後，而不是拆開主詞與 be 的基本順序。",
        correction: "使用 She is not reading。",
      },
      {
        belief: "Is 開頭的問句可以回答 Yes, she does。",
        whyWrong: "簡答要沿用原問句的 be 動詞。",
        correction: "Is 問句以 Yes, she is 或 No, she isn't 回答。",
      },
      {
        belief: "疑問詞後直接接主詞即可。",
        whyWrong: "直接問句仍需把 be 放在主詞前，例如 What is he doing?。",
        correction: "依疑問詞 + be + 主詞 + V-ing 排列。",
      },
    ],
    checks: [
      {
        prompt: "Mia is cooking. 如何改成一般問句？",
        answer: "Is Mia cooking?",
        reason: "把 is 移到主詞 Mia 前面。",
      },
      {
        prompt: "We aren't waiting. not 位於哪裡？",
        answer: "are 與 waiting 之間",
        reason: "進行式否定詞接在 be 動詞後。",
      },
      {
        prompt: "Where they are going? 應如何改正？",
        answer: "Where are they going?",
        reason: "直接問句中 are 要放在主詞 they 前。",
      },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S061", "ENG_R4_S061", {
    objectives: [
      "能依習慣、事實、當下動作與暫時情況選擇現在簡單式或現在進行式。",
      "能在同一句中分別判斷不同子句的時間觀點。",
    ],
    sections: [
      {
        title: "兩種現在式看事情的角度不同",
        content: "現在簡單式把事件看成習慣、規律、事實或長期狀態；現在進行式把事件看成當下或目前期間正在展開。Tom works at a hospital 說他的工作，Tom is working at home today 則說今天的暫時安排。",
      },
      {
        title: "時間詞要和所屬子句配對",
        content: "usually、every week 常支持現在簡單式，now、at the moment 常支持現在進行式。若一句有 but，兩邊可能採不同形式：We usually eat at home, but we are eating out tonight. 不可讓一邊的時間詞控制整句。",
      },
      {
        title: "長期與暫時的對比",
        content: "有些句子沒有 now，仍可由語意看出暫時性，例如 Lina is living with her aunt while her room is being fixed. 相反地，live、work 等動詞也能用簡單式說長期狀況。時態選擇取決於說話者如何看這段情況。",
      },
      {
        title: "先確定語意再檢查形式",
        content: "選好時間觀點後，還要檢查主詞與動詞。現在簡單式可能需要第三人稱 -s；現在進行式需要 am/is/are + V-ing。只因看到 -ing 就選答案，可能忽略 be 錯誤或主詞不一致。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S061_EX_01",
        prompt: "Nora usually ___ tea, but she ___ milk now. (drinks / is drinking)",
        steps: ["usually 配平常習慣。", "now 配當下動作。", "分別使用 drinks 與 is drinking。"],
        answer: "drinks / is drinking",
        why: "usually 限定 Nora 平常喝茶，所以第一格用 drinks；now 只修飾目前喝牛奶的動作，第二格用 is drinking。兩個子句不必使用同一時態。",
      },
      {
        id: "ENG_R4_L_S061_EX_02",
        prompt: "My uncle ___ in Tainan, but this week he ___ in Taipei. (lives / is staying)",
        steps: ["第一句描述長期住所。", "this week 表示有限期間。", "選 lives 與 is staying。"],
        answer: "lives / is staying",
        why: "住在臺南是長期狀態，用 lives；本週待在臺北只是一段暫時安排，用 is staying。but 讓兩種時間觀點形成清楚對比。",
      },
      {
        id: "ENG_R4_L_S061_EX_03",
        prompt: "Look! The bus ___, so we must leave now. (comes / is coming)",
        steps: ["Look 指向眼前變化。", "公車正在接近。", "使用 is coming。"],
        answer: "is coming",
        why: "這裡不是說公車平常會來，而是提醒眼前的公車正在接近。Look 與 leave now 都支持當下情境，因此選 is coming。",
      },
    ],
    misconceptions: [
      {
        belief: "現在簡單式與現在進行式只是拼字不同，意思相同。",
        whyWrong: "兩者分別呈現反覆或長期情況，以及當下或暫時情況。",
        correction: "改寫前先用中文說清楚事件的時間觀點。",
      },
      {
        belief: "一句話裡的所有動詞必須使用同一時態。",
        whyWrong: "不同子句可分別描述平常習慣與當下例外。",
        correction: "把每個時間詞連回它所修飾的動作。",
      },
      {
        belief: "沒有 now 就不能用現在進行式。",
        whyWrong: "this week 或上下文也能表示目前的暫時情況。",
        correction: "看事件是否只在目前期間成立，不只搜尋 now。",
      },
      {
        belief: "看到 today 就一定使用進行式。",
        whyWrong: "today 也可能出現在時刻表、事實或已完成事件的語境。",
        correction: "結合動作性質與整句時間關係判斷。",
      },
    ],
    checks: [
      {
        prompt: "She walks to school every day. 表示哪一種情況？",
        answer: "固定習慣",
        reason: "every day 表示反覆發生。",
      },
      {
        prompt: "She is walking to school now. 和前句有何不同？",
        answer: "這句描述目前正在走路",
        reason: "is walking 與 now 共同指向當下。",
      },
      {
        prompt: "Dad usually cooks, but tonight Mom is cooking. 為何有兩種時態？",
        answer: "前句是習慣，後句是今晚的例外",
        reason: "usually 與 tonight 分別控制不同子句。",
      },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S062", "ENG_R4_S062", {
    objectives: [
      "能辨認 now、right now、look、listen 等當下線索，並連結到正確子句。",
      "能在沒有明示時間副詞時，從情境推得動作正在發生。",
    ],
    sections: [
      {
        title: "直接指向當下的時間詞",
        content: "now、right now、at the moment 直接把動作放在說話當下，因此常搭配 am/is/are + V-ing。若題幹已給 these days 或 this week，則可能描述目前一段期間，不一定是眼前一秒。",
      },
      {
        title: "Look 與 Listen 建立現場",
        content: "Look! 通常要求注意看正在出現的畫面，Listen! 則要求注意正在發生的聲音。Look! A bird is flying into the room. 與 Listen! Someone is calling your name. 都由命令語建立當下情境。",
      },
      {
        title: "情境也能取代明示線索",
        content: "電話中問 What are you doing?、看到地面變濕而說 It is raining，都可能沒有 now，卻由交談或現場證據表明動作正在進行。不要把進行式判斷縮成只找一張關鍵字清單。",
      },
      {
        title: "線索只控制相關動作",
        content: "Look! Ben is running, but his sister walks here every day. Look 控制眼前的 running；every day 控制另一子句的習慣 walks。長句中要先切分子句，再為每個動詞找最近且語意相合的線索。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S062_EX_01",
        prompt: "Listen! The phone ___. (rings / is ringing / rang)",
        steps: ["Listen 指向目前聽見的聲音。", "phone 是單數。", "使用 is ringing。"],
        answer: "is ringing",
        why: "Listen! 表示鈴聲正在發生，並非電話平常會響的習慣。單數 phone 配 is，ring 重複 g 後加 -ing，得到 is ringing。",
      },
      {
        id: "ENG_R4_L_S062_EX_02",
        prompt: "At the moment, we ___ for the teacher. (wait / are waiting / waited)",
        steps: ["at the moment 指此刻。", "we 搭配 are。", "wait 變 waiting。"],
        answer: "are waiting",
        why: "at the moment 明確表示目前正在等候，we 又要求 are，因此答案是 are waiting。wait 會表示常態，waited 則是已結束的過去。",
      },
      {
        id: "ENG_R4_L_S062_EX_03",
        prompt: "A: Why is the ground getting wet? B: It ___. (rains / is raining / rained every day)",
        steps: ["地面正在變濕是現場證據。", "回答解釋目前原因。", "使用 is raining。"],
        answer: "is raining",
        why: "雖然沒有 now，getting wet 表示地面仍在變濕，Why 問句是在追問目前原因。回答要說雨正在下，因此用 is raining；rains 只會說一般情況。",
      },
    ],
    misconceptions: [
      {
        belief: "沒有 now 的句子不可能使用現在進行式。",
        whyWrong: "Look、Listen、對話與現場證據都能建立當下情境。",
        correction: "搜尋時間詞之外，也要讀前後句提供的事件證據。",
      },
      {
        belief: "看到 look 這個字就一定選進行式。",
        whyWrong: "look 也可作一般動詞，如 She looks happy every day。",
        correction: "分辨 Look! 命令語與句中一般動詞的功能。",
      },
      {
        belief: "長句只要有 now，所有動詞都用進行式。",
        whyWrong: "now 只控制與它語意相關的子句，其他子句可能表達習慣。",
        correction: "切分子句並逐一配對時間線索。",
      },
      {
        belief: "at the moment 表示很短，所以動作一定馬上結束。",
        whyWrong: "它只說目前正在發生，沒有保證結束時間。",
        correction: "不要從當下線索推論題目未提供的持續長度。",
      },
    ],
    checks: [
      {
        prompt: "right now 通常把動作放在哪個時間？",
        answer: "說話當下",
        reason: "它是直接的目前時間線索。",
      },
      {
        prompt: "Look! The dog runs across the road. 哪個動詞形式較合適？",
        answer: "is running",
        reason: "Look! 建立眼前正在發生的畫面。",
      },
      {
        prompt: "These days, I am reading a long book. 是否一定指說話那一秒？",
        answer: "不一定",
        reason: "these days 可指目前一段期間的進行中活動。",
      },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S063", "ENG_R4_S063", {
    objectives: [
      "能辨識 know、want、need、like 等通常描述狀態的動詞。",
      "能依動詞在句中的實際意義，判斷 have、think 等是否表示狀態或動作。",
    ],
    sections: [
      {
        title: "狀態不是正在執行的動作",
        content: "know、understand、want、need、like、love、own 等常描述認知、需求、喜好或所有關係。這些意義通常沒有可觀察的起點與進行過程，因此說 I know the answer，不說 I am knowing the answer。",
      },
      {
        title: "通常不使用不等於永遠禁止",
        content: "規則要看動詞當下的意思。have 表示擁有時用簡單式：She has a bike；have 表示進行活動時可用進行式：She is having lunch。不能只背一張動詞清單而忽略語意。",
      },
      {
        title: "think 的兩種常見觀點",
        content: "I think this answer is right 表示目前看法，通常用簡單式。I am thinking about the question 表示正在思考的過程，可以用進行式。about 後的內容與上下文常幫助我們分辨看法和思考活動。",
      },
      {
        title: "先判斷意思再選形式",
        content: "若動詞表達持續存在的認知、感受、需求或所有關係，優先考慮現在簡單式；若同一字改為可進行的活動，再考慮進行式。最後仍須檢查主詞一致與 be + V-ing 的完整結構。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S063_EX_01",
        prompt: "I ___ the answer now. (know / am knowing / knows)",
        steps: ["know 在此表示認知狀態。", "認知狀態通常不用進行式。", "主詞 I 搭配原形 know。"],
        answer: "know",
        why: "now 不能推翻動詞本身的狀態意義；此處 know 表示已具有答案的認知。主詞 I 使用 know，am knowing 在一般考試語境中不自然。",
      },
      {
        id: "ENG_R4_L_S063_EX_02",
        prompt: "Mia ___ a new bike, and she ___ lunch now. (has / is having)",
        steps: ["第一格 have 表示擁有。", "第二格 have lunch 表示進行活動。", "分別使用 has 與 is having。"],
        answer: "has / is having",
        why: "第一格說 Mia 擁有腳踏車，屬穩定關係，所以用 has；第二格的 have lunch 是正在吃午餐的活動，now 支持 is having。",
      },
      {
        id: "ENG_R4_L_S063_EX_03",
        prompt: "I ___ this plan is good, but I ___ about one problem. (think / am thinking)",
        steps: ["第一格表達看法。", "第二格表達正在思考的過程。", "依語意分別選 think 與 am thinking。"],
        answer: "think / am thinking",
        why: "think this plan is good 是說話者的看法，用簡單式；think about one problem 描述正在進行的思考，搭配 am thinking。兩格不能只因同一動詞就選同一形式。",
      },
    ],
    misconceptions: [
      {
        belief: "句中有 now，所有動詞都必須使用進行式。",
        whyWrong: "know、need 等狀態動詞即使和 now 共現，通常仍用簡單式。",
        correction: "先判斷動詞意義，再使用時間線索。",
      },
      {
        belief: "have 永遠不能使用現在進行式。",
        whyWrong: "have lunch、have a good time 等活動意義可以使用進行式。",
        correction: "分辨 have 是擁有，還是參與某項活動。",
      },
      {
        belief: "think 永遠只用現在簡單式。",
        whyWrong: "表示正在思考某事時，think about 可使用進行式。",
        correction: "看 think 是表達看法，還是描述思考過程。",
      },
      {
        belief: "狀態動詞只要加 be 就能改成進行式。",
        whyWrong: "形式完整不代表語意自然，I am needing help 通常不合基礎用法。",
        correction: "同時檢查結構與動詞所表達的狀態或動作。",
      },
    ],
    checks: [
      {
        prompt: "She is knowing the answer. 應如何改正？",
        answer: "She knows the answer.",
        reason: "know 在此表示認知狀態。",
      },
      {
        prompt: "Dad is having dinner. have 為何可用進行式？",
        answer: "have dinner 表示正在進行的用餐活動",
        reason: "這裡不是表示擁有。",
      },
      {
        prompt: "I think you are right. think 表示什麼？",
        answer: "看法",
        reason: "它不是描述正在進行的思考步驟。",
      },
    ],
    assets: [],
  }),
];

export const ENGLISH_U09_QUESTIONS = [
  question({
    id: "ENG_R4_Q_057_01",
    skillId: "ENG_R4_S057",
    difficulty: "foundation",
    stem: "Look! The dog ___ across the road.",
    options: ["is running", "runs", "ran", "running"],
    answerIndex: 0,
    reasons: [
      "is running 以完整進行式描述眼前正在跑過馬路的動作。",
      "runs 會表示規律，沒有呈現 Look 指出的當下畫面。",
      "ran 是已完成的過去式，和眼前提醒不合。",
      "running 前缺少單數主詞 dog 所需的 is。",
    ],
    reviews: [
      "Look 建立眼前情境，單數 dog 搭配 is running，因此第一項正確。",
      "逐項檢查時間觀點與 be + V-ing 結構後，只有 is running 能完成句子。",
    ],
    cognitiveProcess: ["recognize-live-visual-action", "form-singular-progressive"],
    misconceptionTargets: ["omit-be-before-present-participle"],
  }),
  question({
    id: "ENG_R4_Q_057_02",
    skillId: "ENG_R4_S057",
    difficulty: "foundation",
    stem: "This week, my aunt ___ at a school near our home.",
    options: ["works", "is working", "worked", "work"],
    answerIndex: 1,
    reasons: [
      "works 通常描述長期工作地點，未呈現 this week 的暫時安排。",
      "is working 把工作情況限定在目前這一週，語意完整。",
      "worked 表示已結束的過去，但 this week 仍是目前期間。",
      "work 不配單數主詞 my aunt，也未形成進行式。",
    ],
    reviews: [
      "This week 表示目前有限期間，my aunt 為單數，所以使用 is working。",
      "第二項同時符合暫時語意與 is + working 的結構，其他形式各缺一項。",
    ],
    cognitiveProcess: ["interpret-current-limited-period", "choose-temporary-work-form"],
    misconceptionTargets: ["treat-current-period-as-permanent-habit"],
  }),
  question({
    id: "ENG_R4_Q_057_03",
    skillId: "ENG_R4_S057",
    difficulty: "foundation",
    stem: "We ___ the final page right now.",
    options: ["read", "reads", "are reading", "reading"],
    answerIndex: 2,
    reasons: [
      "read 會把動作寫成一般習慣，沒有回應 right now。",
      "reads 不配主詞 We，也不是進行式。",
      "are reading 正確配合 We，並表示目前正在閱讀。",
      "reading 前缺少複數主詞 We 所需的 are。",
    ],
    reviews: [
      "right now 指說話當下，We 搭配 are，故答案是 are reading。",
      "完整代入後，第三項是唯一同時具有正確 be 動詞與現在分詞的形式。",
    ],
    cognitiveProcess: ["use-explicit-now-clue", "assemble-plural-progressive"],
    misconceptionTargets: ["use-bare-participle-after-subject"],
  }),
  question({
    id: "ENG_R4_Q_057_04",
    skillId: "ENG_R4_S057",
    difficulty: "standard",
    stem: "A: Why is the kitchen so busy? B: Dad ___ dinner, and we are helping him.",
    options: ["cooks every day", "cooked yesterday", "cook", "is cooking"],
    answerIndex: 3,
    reasons: [
      "cooks every day 說固定習慣，沒有解釋現在忙碌的原因。",
      "cooked yesterday 指過去，無法連接 we are helping 的當下情境。",
      "cook 不配單數 Dad，也缺少進行式結構。",
      "is cooking 描述父親正在做飯，能直接解釋目前廚房忙碌。",
    ],
    reviews: [
      "Why is... 與 we are helping 都把事件放在現在，Dad 應搭配 is cooking。",
      "第四項不只文法完整，也和對話所問的目前原因一致，因此沒有第二答案。",
    ],
    cognitiveProcess: ["infer-current-cause-from-dialogue", "align-parallel-actions"],
    representationType: "cause-dialogue",
    misconceptionTargets: ["answer-current-cause-with-routine"],
  }),
  question({
    id: "ENG_R4_Q_057_05",
    skillId: "ENG_R4_S057",
    difficulty: "standard",
    stem: "Lina usually lives in Hualien. For two months, she ___ with her sister in Tainan.",
    options: ["is staying", "stays every year", "stayed last year", "stay"],
    answerIndex: 0,
    reasons: [
      "is staying 呈現目前兩個月內的暫住，並和長期住所形成對比。",
      "stays every year 增加題目沒有提供的年度規律。",
      "stayed last year 把事件移到去年，和目前期間不合。",
      "stay 不配單數 she，也不是完整進行式。",
    ],
    reviews: [
      "長期住花蓮與目前暫住臺南形成對比，For two months 支持 is staying。",
      "第一項保留題面所有資訊；其他選項不是改變時間，就是缺少主詞一致。",
    ],
    cognitiveProcess: ["contrast-home-and-temporary-stay", "preserve-given-duration"],
    representationType: "limited-period-context",
    misconceptionTargets: ["invent-recurring-pattern-from-duration"],
  }),
  question({
    id: "ENG_R4_Q_057_06",
    skillId: "ENG_R4_S057",
    difficulty: "standard",
    stem: "The students are building a small boat this month. What does the sentence tell us?",
    options: [
      "They build the same boat every month.",
      "They are still working on the boat this month.",
      "They finished the boat last month.",
      "The boat is always ready before class.",
    ],
    answerIndex: 1,
    reasons: [
      "this month 沒有表示每個月都重複，也不能推得同一艘船。",
      "are building 表示造船計畫在本月仍進行中。",
      "句子未使用過去式，也沒有說已經完成。",
      "原句沒有 always、ready 或上課前等資訊。",
    ],
    reviews: [
      "are building 與 this month 共同表示目前期間尚未結束的計畫。",
      "第二項只重述可由原句確認的進行狀態，其他三項都加入未提供的時間或結果。",
    ],
    cognitiveProcess: ["interpret-progressive-over-current-period", "avoid-unsupported-result"],
    representationType: "tense-meaning-interpretation",
    misconceptionTargets: ["read-current-project-as-recurring-or-complete"],
  }),
  question({
    id: "ENG_R4_Q_057_07",
    skillId: "ENG_R4_S057",
    difficulty: "standard",
    stem: "The children ___ playing near the river now.",
    options: ["do", "is", "are", "have"],
    answerIndex: 2,
    reasons: [
      "do 不能和 playing 組成現在進行式。",
      "is 不配複數主詞 The children。",
      "are 放在 children 與 playing 之間，形成完整進行式。",
      "have playing 不是本題所需的現在式結構。",
    ],
    reviews: [
      "The children 是複數，playing 前缺 be 動詞，因此補 are。",
      "第三項修復唯一缺少的成分，沒有改動 now 或主要動詞的時間意義。",
    ],
    cognitiveProcess: ["diagnose-missing-progressive-auxiliary", "match-children-with-are"],
    representationType: "targeted-missing-word-repair",
    misconceptionTargets: ["treat-participle-as-finite-verb"],
  }),
  question({
    id: "ENG_R4_Q_057_08",
    skillId: "ENG_R4_S057",
    difficulty: "advanced",
    stem: "While the nurse is talking to my mother, I ___ in the hall.",
    options: ["waits", "waited every day", "waiting", "am waiting"],
    answerIndex: 3,
    reasons: [
      "waits 不配主詞 I，也沒有和 is talking 呈現同時進行。",
      "waited every day 混合過去式與習慣語意，和目前子句衝突。",
      "waiting 前缺少 I 所需的 am。",
      "am waiting 表示我在談話進行期間同時等候。",
    ],
    reviews: [
      "while 連結兩個同時進行的目前動作，I 搭配 am waiting。",
      "第四項是唯一能與 is talking 平行且形成完整限定動詞的選項。",
    ],
    cognitiveProcess: ["coordinate-simultaneous-current-actions", "select-i-am-form"],
    representationType: "while-clause-completion",
    misconceptionTargets: ["omit-am-in-parallel-progressive"],
  }),
  question({
    id: "ENG_R4_Q_057_09",
    skillId: "ENG_R4_S057",
    difficulty: "advanced",
    stem: "A: I can hear water. What are you doing? B: I ___ the dishes.",
    options: ["am washing", "wash on Fridays", "washed", "washing"],
    answerIndex: 0,
    reasons: [
      "am washing 直接回答目前水聲所對應的動作。",
      "wash on Fridays 說固定習慣，沒有回答現在正在做什麼。",
      "washed 是已完成的過去，無法解釋目前仍聽到的水聲。",
      "washing 缺少主詞 I 所需的 am。",
    ],
    reviews: [
      "hear water 與 What are you doing 建立當下情境，I 應回答 am washing。",
      "第一項同時符合對話問題、現場證據與完整進行式，其餘各少至少一項。",
    ],
    cognitiveProcess: ["connect-sound-evidence-to-current-action", "answer-progressive-question"],
    representationType: "phone-dialogue",
    misconceptionTargets: ["respond-to-now-question-with-routine"],
  }),
  question({
    id: "ENG_R4_Q_057_10",
    skillId: "ENG_R4_S057",
    difficulty: "advanced",
    stem: "The school library is closed for two days. During this time, workers ___ the floor.",
    options: ["fix every day", "are fixing", "fixed last month", "are fix"],
    answerIndex: 1,
    reasons: [
      "fix every day 把兩天的工作改成永久規律。",
      "are fixing 描述圖書館關閉期間正在進行的修理。",
      "fixed last month 與題目目前的 two days 無關。",
      "are 後需要 fixing，不能直接接原形 fix。",
    ],
    reviews: [
      "closed for two days 與 During this time 都限定目前的修理期間，應選 are fixing。",
      "第二項說明暫時關閉的實際原因，且 workers 與 are 的搭配正確。",
    ],
    cognitiveProcess: ["infer-temporary-maintenance-window", "match-workers-with-progressive"],
    representationType: "school-notice-context",
    misconceptionTargets: ["replace-limited-project-with-daily-habit"],
  }),
  question({
    id: "ENG_R4_Q_057_11",
    skillId: "ENG_R4_S057",
    difficulty: "transfer",
    stem: "A photo shows Amy at a table with an open math book and a pen. Which sentence tells what Amy is doing in the photo?",
    options: [
      "Amy studies math every Tuesday.",
      "Amy studied math before dinner.",
      "Amy is doing her math work.",
      "Amy will buy a math book.",
    ],
    answerIndex: 2,
    reasons: [
      "照片只能顯示一個當下畫面，不能證明每週二的習慣。",
      "照片未提供 before dinner，也不能確認動作已結束。",
      "is doing 描述照片中正在進行的數學作業情況。",
      "畫面已有書本，且沒有未來購買的證據。",
    ],
    reviews: [
      "open book 與手中的筆支持 Amy 正在做數學作業，故第三項最符合畫面。",
      "其餘選項分別加入週期、過去時間或未來計畫，皆超出照片可確認的資訊。",
    ],
    cognitiveProcess: ["write-caption-from-visible-evidence", "reject-unsupported-time-claims"],
    representationType: "text-described-photo-caption",
    misconceptionTargets: ["infer-habit-from-single-scene"],
  }),
  question({
    id: "ENG_R4_Q_057_12",
    skillId: "ENG_R4_S057",
    difficulty: "transfer",
    stem: "A message says, “Please be quiet. The baby ___.”",
    options: ["sleeps at nine", "slept an hour ago", "sleep", "is sleeping"],
    answerIndex: 3,
    reasons: [
      "sleeps at nine 只說固定時間，無法解釋現在要安靜。",
      "slept an hour ago 表示睡眠已在過去，和目前請求缺乏連結。",
      "sleep 不配單數 baby，也不是完整進行式。",
      "is sleeping 說明嬰兒現在正在睡，因此需要保持安靜。",
    ],
    reviews: [
      "Please be quiet 提供目前情境，單數 baby 搭配 is sleeping。",
      "第四項是唯一能成為安靜請求的即時理由，沒有加入未提供的固定或過去時間。",
    ],
    cognitiveProcess: ["infer-current-action-from-request", "complete-message-reason"],
    representationType: "situational-message",
    misconceptionTargets: ["choose-routine-when-context-needs-current-reason"],
  }),
  question({
    id: "ENG_R4_Q_058_01",
    skillId: "ENG_R4_S058",
    difficulty: "foundation",
    stem: "I ___ waiting for the next bus.",
    options: ["am", "is", "are", "be"],
    answerIndex: 0,
    reasons: [
      "am 是 I 在現在式唯一搭配的 be 動詞。",
      "is 用於單數第三人稱，不和 I 搭配。",
      "are 可配 you 或複數主詞，但不配 I。",
      "be 是原形，不能直接在此標示現在時間與主詞。",
    ],
    reviews: [
      "主詞 I 的現在式 be 固定為 am，代入後形成 I am waiting。",
      "第一項是唯一能和 I 及 waiting 組成完整現在進行式的形式。",
    ],
    cognitiveProcess: ["recall-i-am-agreement", "complete-progressive-auxiliary"],
    misconceptionTargets: ["use-are-with-i"],
  }),
  question({
    id: "ENG_R4_Q_058_02",
    skillId: "ENG_R4_S058",
    difficulty: "foundation",
    stem: "The girls near the door ___ talking quietly.",
    options: ["is", "are", "am", "be"],
    answerIndex: 1,
    reasons: [
      "is 不配複數主詞 The girls。",
      "are 正確連接複數主詞 girls 與 talking。",
      "am 只和 I 搭配。",
      "be 未依主詞與現在時間變化。",
    ],
    reviews: [
      "near the door 只是地點說明，主詞核心 girls 是複數，所以選 are。",
      "第二項形成 The girls are talking，其他三項都無法和複數主詞一致。",
    ],
    cognitiveProcess: ["identify-plural-head-before-place-phrase", "select-are"],
    misconceptionTargets: ["treat-door-as-subject-head"],
  }),
  question({
    id: "ENG_R4_Q_058_03",
    skillId: "ENG_R4_S058",
    difficulty: "foundation",
    stem: "The teacher with three students ___ walking upstairs.",
    options: ["are", "am", "is", "be"],
    answerIndex: 2,
    reasons: [
      "are 受到 students 干擾，但 students 位在 with 片語中。",
      "am 只配主詞 I。",
      "is 配合真正的單數主詞 The teacher。",
      "be 是原形，不能完成現在進行式。",
    ],
    reviews: [
      "去掉 with three students 後主幹是 The teacher ___ walking，因此使用 is。",
      "第三項依主詞核心而非最近名詞判斷，能唯一形成正確進行式。",
    ],
    cognitiveProcess: ["ignore-with-phrase-number", "match-teacher-with-is"],
    misconceptionTargets: ["agree-with-nearest-plural-noun"],
  }),
  question({
    id: "ENG_R4_Q_058_04",
    skillId: "ENG_R4_S058",
    difficulty: "standard",
    stem: "Why ___ you carrying two bags?",
    options: ["am", "is", "be", "are"],
    answerIndex: 3,
    reasons: [
      "am 只配 I，不能放在主詞 you 前。",
      "is 不和 you 搭配。",
      "be 未變化，無法形成直接問句。",
      "are 在 Why 後、主詞 you 前，與 carrying 組成正確問句。",
    ],
    reviews: [
      "you 無論指一人或多人都搭配 are，故問句為 Why are you carrying...?。",
      "第四項同時符合 you 的 be 形式與疑問詞後倒裝，其他形式無法成立。",
    ],
    cognitiveProcess: ["apply-you-are-in-wh-question", "place-be-before-subject"],
    representationType: "wh-question-cloze",
    misconceptionTargets: ["use-is-when-you-means-one-person"],
  }),
  question({
    id: "ENG_R4_Q_058_05",
    skillId: "ENG_R4_S058",
    difficulty: "standard",
    stem: "Mia and her brother ___ making lunch together.",
    options: ["are", "is", "am", "does"],
    answerIndex: 0,
    reasons: [
      "are 配合由 and 連接的兩人，後接 making。",
      "is 把 Mia and her brother 誤當成單數。",
      "am 只和 I 搭配。",
      "does 不能和 making 組成現在進行式。",
    ],
    reviews: [
      "Mia and her brother 包含兩人，整體是複數，因此使用 are making。",
      "第一項是唯一兼顧複數主詞與進行式結構的選項。",
    ],
    cognitiveProcess: ["combine-and-subjects", "choose-plural-progressive-be"],
    misconceptionTargets: ["follow-first-singular-name-only"],
  }),
  question({
    id: "ENG_R4_Q_058_06",
    skillId: "ENG_R4_S058",
    difficulty: "standard",
    stem: "Our class ___ taking a test now.",
    options: ["are", "is", "am", "do"],
    answerIndex: 1,
    reasons: [
      "題句把 class 當成一個整體，初階書面用法搭配單數 is。",
      "is 正確連接單一班級與 taking。",
      "am 只配 I。",
      "do 不能接 taking 形成進行式。",
    ],
    reviews: [
      "Our class 在此指一個班級整體，視為單數，所以答案是 is。",
      "第二項形成 Our class is taking a test；題面未改用複數 students，因此不選 are。",
    ],
    cognitiveProcess: ["treat-class-as-single-group", "select-collective-is"],
    misconceptionTargets: ["choose-are-from-real-world-member-count"],
  }),
  question({
    id: "ENG_R4_Q_058_07",
    skillId: "ENG_R4_S058",
    difficulty: "standard",
    stem: "In “My parents are waiting outside,” which words are the subject?",
    options: ["waiting outside", "outside", "My parents", "are waiting"],
    answerIndex: 2,
    reasons: [
      "waiting outside 是動作與地點，不能決定主詞數量。",
      "outside 只說明位置。",
      "My parents 是複數主詞，因此控制 be 動詞選用 are。",
      "are waiting 已包含答案形式，卻沒有說明哪個成分決定它。",
    ],
    reviews: [
      "be 動詞和主詞一致；My parents 是複數，所以句中使用 are。",
      "第三項指出真正的控制成分，其他選項只是述語或地點資訊。",
    ],
    cognitiveProcess: ["identify-agreement-controller", "separate-subject-from-predicate"],
    representationType: "sentence-part-analysis",
    misconceptionTargets: ["attribute-be-choice-to-participle"],
  }),
  question({
    id: "ENG_R4_Q_058_08",
    skillId: "ENG_R4_S058",
    difficulty: "advanced",
    stem: "The boxes beside the door ___ blocking the way.",
    options: ["is", "am", "does", "are"],
    answerIndex: 3,
    reasons: [
      "is 不配複數主詞 boxes。",
      "am 只和 I 搭配。",
      "does 不能接 blocking 形成進行式。",
      "are 配合 boxes，beside the door 不改變主詞。",
    ],
    reviews: [
      "主詞核心 boxes 是複數，地點片語 beside the door 不影響一致，因此用 are。",
      "第四項能形成 are blocking；其餘選項或主詞不合，或動詞結構錯誤。",
    ],
    cognitiveProcess: ["retain-plural-head-before-singular-object", "complete-are-blocking"],
    misconceptionTargets: ["agree-with-nearby-door"],
  }),
  question({
    id: "ENG_R4_Q_058_09",
    skillId: "ENG_R4_S058",
    difficulty: "advanced",
    stem: "A: Who is making that sound? B: I ___.",
    options: ["am", "is", "are", "do"],
    answerIndex: 0,
    reasons: [
      "am 可代替前文的 am making that sound，並與 I 一致。",
      "is 不配 I。",
      "are 不配 I。",
      "do 不能沿用進行式問答中的 be 動詞。",
    ],
    reviews: [
      "回答者以 I 指自己，完整意思是 I am making that sound，因此選 am。",
      "第一項同時保持人稱一致與進行式的 be，其他三項不能代回。",
    ],
    cognitiveProcess: ["recover-omitted-progressive-predicate", "use-i-am-response"],
    representationType: "elliptical-dialogue",
    misconceptionTargets: ["answer-progressive-prompt-with-do"],
  }),
  question({
    id: "ENG_R4_Q_058_10",
    skillId: "ENG_R4_S058",
    difficulty: "advanced",
    stem: "The boy near my cousins are carrying a box. Which one-word change corrects the sentence without changing its meaning?",
    options: ["Change boy to boys.", "Change are to is.", "Change carrying to carry.", "Change box to boxes."],
    answerIndex: 1,
    reasons: [
      "改成 boys 會更動原來的一名男孩，不是必要修正。",
      "真正主詞 boy 是單數，把 are 改為 is 即可。",
      "進行式需要 carrying，改成 carry 會破壞結構。",
      "受詞 box 的數量不控制 be 動詞。",
    ],
    reviews: [
      "near my cousins 是附加位置說明，主詞核心 boy 應搭配 is carrying。",
      "第二項只修正錯誤的 be 一致，不改變人物、動作或受詞資訊。",
    ],
    cognitiveProcess: ["repair-nearest-noun-agreement-error", "make-minimal-be-change"],
    representationType: "specific-agreement-repair",
    misconceptionTargets: ["change-content-to-fit-wrong-auxiliary"],
  }),
  question({
    id: "ENG_R4_Q_058_11",
    skillId: "ENG_R4_S058",
    difficulty: "transfer",
    stem: "A message says, “Ben and I ___ bringing the chairs. Please open the room.”",
    options: ["am", "is", "are", "be"],
    answerIndex: 2,
    reasons: [
      "am 只適合主詞單獨為 I，不能忽略 Ben。",
      "is 把 Ben and I 誤當成一人。",
      "are 配合由 and 連接的兩人，後接 bringing。",
      "be 未依現在時間與複數主詞變化。",
    ],
    reviews: [
      "Ben and I 可改為 we，是複數主詞，因此訊息中應寫 are bringing。",
      "第三項保留兩位搬椅子的人，也形成完整進行式，沒有改動原意。",
    ],
    cognitiveProcess: ["convert-ben-and-i-to-we", "complete-message-progressive"],
    representationType: "practical-message-cloze",
    misconceptionTargets: ["let-i-force-am-in-compound-subject"],
  }),
  question({
    id: "ENG_R4_Q_058_12",
    skillId: "ENG_R4_S058",
    difficulty: "transfer",
    stem: "I ___ taking the train today, while my parents ___ driving.",
    options: ["is / is", "are / are", "am / is", "am / are"],
    answerIndex: 3,
    reasons: [
      "I 不配 is，parents 也不配 is。",
      "I 不配 are，雖然第二格 are 正確。",
      "第一格 am 正確，但複數 parents 不能用 is。",
      "I 搭配 am，複數 my parents 搭配 are，兩格皆正確。",
    ],
    reviews: [
      "兩個子句分別以 I 和 my parents 為主詞，故使用 am taking 與 are driving。",
      "逐格核對主詞而非讓 while 兩邊共用同一 be，可唯一得到第四組。",
    ],
    cognitiveProcess: ["switch-be-across-coordinated-subjects", "solve-two-progressive-slots"],
    representationType: "dual-agreement-cloze",
    misconceptionTargets: ["reuse-one-be-form-across-clauses"],
  }),
  question({
    id: "ENG_R4_Q_059_01",
    skillId: "ENG_R4_S059",
    difficulty: "foundation",
    stem: "The students are ___ a short story. (read)",
    options: ["reading", "readig", "readding", "read"],
    answerIndex: 0,
    reasons: [
      "reading 直接在 read 後加 -ing，拼字正確。",
      "readig 少了 -ing 中的 n。",
      "readding 不應重複原形最後的 d。",
      "read 是原形，不能直接接在 are 後形成進行式。",
    ],
    reviews: [
      "read 不需去字母或重複字尾，直接加 -ing 得到 reading。",
      "第一項保留完整詞根 read 與字尾 ing，其他形式不是漏字、重複，就是未變化。",
    ],
    cognitiveProcess: ["apply-direct-ing-addition", "preserve-read-root"],
    misconceptionTargets: ["double-final-consonant-without-condition"],
  }),
  question({
    id: "ENG_R4_Q_059_02",
    skillId: "ENG_R4_S059",
    difficulty: "foundation",
    stem: "Maya is ___ a card for her mother. (make)",
    options: ["makeing", "making", "makking", "make"],
    answerIndex: 1,
    reasons: [
      "makeing 錯誤保留不發音的 e。",
      "making 先去掉 make 的 e，再加 -ing。",
      "makking 不應重複 k，且改變了詞根拼法。",
      "make 是原形，不能完成 is 後的進行式。",
    ],
    reviews: [
      "make 以不發音 e 結尾，去 e 後接 -ing，答案為 making。",
      "第二項是唯一可由 make 按規則形成的現在分詞，沒有多留或多寫字母。",
    ],
    cognitiveProcess: ["drop-silent-e-before-ing", "spell-making"],
    misconceptionTargets: ["keep-silent-e-before-ing"],
  }),
  question({
    id: "ENG_R4_Q_059_03",
    skillId: "ENG_R4_S059",
    difficulty: "foundation",
    stem: "The boy is ___ to the bus stop. (run)",
    options: ["runing", "runeing", "running", "run"],
    answerIndex: 2,
    reasons: [
      "runing 少了短母音字尾需要重複的 n。",
      "runeing 在 run 後錯加 e。",
      "running 重複 n 後加 -ing，拼字正確。",
      "run 是原形，不能直接接在 is 後。",
    ],
    reviews: [
      "run 的字尾是短母音加單一子音，形成現在分詞時重複 n，寫成 running。",
      "第三項能還原回 run 並符合字尾規則，其餘形式各有漏寫、增寫或未變化。",
    ],
    cognitiveProcess: ["double-final-n-after-short-vowel", "spell-running"],
    misconceptionTargets: ["omit-doubled-consonant-in-running"],
  }),
  question({
    id: "ENG_R4_Q_059_04",
    skillId: "ENG_R4_S059",
    difficulty: "standard",
    stem: "The cat is ___ under the chair. (lie)",
    options: ["lieing", "liying", "lie", "lying"],
    answerIndex: 3,
    reasons: [
      "lieing 未把 ie 改為 y。",
      "liying 在改成 y 前又保留了多餘的 i。",
      "lie 是原形，不能完成 is 後的進行式。",
      "lying 正確把 ie 改成 y，再加 -ing。",
    ],
    reviews: [
      "lie 的 ie 先改成 y，再加 -ing，所以答案是 lying。",
      "第四項符合 ie → y 的特殊變化，並能和 is 組成完整進行式。",
    ],
    cognitiveProcess: ["change-ie-to-y-before-ing", "spell-lying"],
    misconceptionTargets: ["attach-ing-directly-to-ie"],
  }),
  question({
    id: "ENG_R4_Q_059_05",
    skillId: "ENG_R4_S059",
    difficulty: "standard",
    stem: "Nina is ___ for the science test. (study)",
    options: ["studying", "studiing", "studies", "studyying"],
    answerIndex: 0,
    reasons: [
      "studying 保留 y，直接加 -ing。",
      "studiing 錯把 y 改成 i，混用了第三人稱 -ies 規則。",
      "studies 是現在簡單式第三人稱形式，不接在 is 後。",
      "studyying 不應重複 y。",
    ],
    reviews: [
      "study 形成現在分詞時保留 y，答案是 studying，不使用 studies 的變化。",
      "第一項清楚區分 -ing 與 -ies 兩套規則，其他選項都誤改或重複字母。",
    ],
    cognitiveProcess: ["keep-y-before-ing", "separate-ing-from-ies-rule"],
    misconceptionTargets: ["apply-third-person-y-rule-to-participle"],
  }),
  question({
    id: "ENG_R4_Q_059_06",
    skillId: "ENG_R4_S059",
    difficulty: "standard",
    stem: "We are ___ a bright light in the sky. (see)",
    options: ["seing", "seeing", "seeeing", "sseeing"],
    answerIndex: 1,
    reasons: [
      "seing 錯刪 see 中的一個 e。",
      "seeing 保留 ee，再加 -ing。",
      "seeeing 多寫了一個 e。",
      "sseeing 錯誤重複字首 s。",
    ],
    reviews: [
      "see 以 ee 結尾，不套用單一不發音 e 的刪除規則，因此寫 seeing。",
      "第二項完整保留詞根 see；其餘選項刪錯、增寫或重複了不相關字母。",
    ],
    cognitiveProcess: ["preserve-double-e-before-ing", "spell-seeing"],
    misconceptionTargets: ["drop-one-e-from-see"],
  }),
  question({
    id: "ENG_R4_Q_059_07",
    skillId: "ENG_R4_S059",
    difficulty: "standard",
    stem: "Dad is ___ my bike now. (fix)",
    options: ["fixxing", "fixeing", "fixing", "fix"],
    answerIndex: 2,
    reasons: [
      "fixxing 錯誤重複 x；x 結尾通常不重複。",
      "fixeing 在 fix 後加入了不屬於原形的 e。",
      "fixing 直接在 fix 後加 -ing，拼字正確。",
      "fix 是原形，不能直接接在 is 後。",
    ],
    reviews: [
      "fix 雖以子音結尾，但 x 不重複，直接加 -ing 得到 fixing。",
      "第三項保留詞根且符合 x 字尾規則，其他形式都添加了多餘字母或未變化。",
    ],
    cognitiveProcess: ["apply-no-double-x-exception", "spell-fixing"],
    misconceptionTargets: ["double-x-before-ing"],
  }),
  question({
    id: "ENG_R4_Q_059_08",
    skillId: "ENG_R4_S059",
    difficulty: "advanced",
    stem: "The children are ___ in the pool. (swim)",
    options: ["swiming", "swimeing", "swim", "swimming"],
    answerIndex: 3,
    reasons: [
      "swiming 少了短母音字尾需要重複的 m。",
      "swimeing 在 swim 後錯加 e。",
      "swim 是原形，不能完成 are 後的進行式。",
      "swimming 重複最後的 m 再加 -ing。",
    ],
    reviews: [
      "swim 的結尾符合短母音加單一子音，故重複 m，形成 swimming。",
      "第四項能從正確詞根與重複規則推得，其他三項不是少字、多字，就是未變化。",
    ],
    cognitiveProcess: ["double-final-m-in-swim", "verify-swimming-spelling"],
    misconceptionTargets: ["write-single-m-in-swimming"],
  }),
  question({
    id: "ENG_R4_Q_059_09",
    skillId: "ENG_R4_S059",
    difficulty: "advanced",
    stem: "How do you spell write with -ing?",
    options: [
      "Drop the final e and add -ing.",
      "Keep the final e and add -ing.",
      "Double t and add -ing.",
      "Change ie to y and add -ing.",
    ],
    answerIndex: 0,
    reasons: [
      "write 的不發音 e 要先去掉，再加 -ing，得到 writing。",
      "保留 e 會形成錯誤的 writeing。",
      "write 不符合重複 t 的字尾條件。",
      "ie 改 y 適用 lie、tie 等，不適用 write。",
    ],
    reviews: [
      "write → writ + ing → writing，因此第一項描述正確步驟。",
      "其餘三項分別會多留 e、錯重複 t 或套用不屬於 write 的 ie 規則。",
    ],
    cognitiveProcess: ["explain-writing-transformation", "distinguish-silent-e-from-ie"],
    representationType: "spelling-process-selection",
    misconceptionTargets: ["confuse-write-ending-with-ie-ending"],
  }),
  question({
    id: "ENG_R4_Q_059_10",
    skillId: "ENG_R4_S059",
    difficulty: "advanced",
    stem: "The sign should read, “Bus 5 is ___ here.”",
    options: ["stoping", "stopping", "stopeing", "stoppping"],
    answerIndex: 1,
    reasons: [
      "stoping 仍少了應重複的 p。",
      "stopping 重複一個 p 後加 -ing，拼字正確。",
      "stopeing 錯誤加入 e。",
      "stoppping 寫了三個連續 p，超過規則所需。",
    ],
    reviews: [
      "stop 是短母音後接單一 p，現在分詞重複 p，應改為 stopping。",
      "第二項只增加規則要求的一個 p；其他選項不是未修正，就是加入錯誤字母數量。",
    ],
    cognitiveProcess: ["proofread-stop-participle", "repair-one-letter-doubling"],
    representationType: "sign-proofreading",
    misconceptionTargets: ["under-or-over-double-p"],
  }),
  question({
    id: "ENG_R4_Q_059_11",
    skillId: "ENG_R4_S059",
    difficulty: "transfer",
    stem: "Ann is ___ her shoes while her brother is ___ his bike. (tie / ride)",
    options: ["tieing / rideing", "tying / rideing", "tying / riding", "tiying / riding"],
    answerIndex: 2,
    reasons: [
      "tieing 未把 tie 的 ie 改 y，rideing 也未去 e。",
      "tying 正確，但 rideing 仍多留不發音 e。",
      "tying 由 ie 改 y，riding 由 ride 去 e，兩格皆正確。",
      "tiying 多留 i，雖然 riding 正確，整組仍不可選。",
    ],
    reviews: [
      "tie 使用 ie → y 得 tying；ride 去掉不發音 e 得 riding，因此選第三組。",
      "兩格使用不同規則，逐字還原原形後，只有第三項沒有遺漏或多餘字母。",
    ],
    cognitiveProcess: ["combine-ie-and-silent-e-rules", "solve-two-participle-forms"],
    representationType: "dual-spelling-cloze",
    misconceptionTargets: ["apply-one-ending-rule-to-two-verbs"],
  }),
  question({
    id: "ENG_R4_Q_059_12",
    skillId: "ENG_R4_S059",
    difficulty: "transfer",
    stem: "Which line spells all three -ing words correctly?",
    options: [
      "play → plaing; wash → washing; sit → siting",
      "play → playing; wash → washeing; sit → sitting",
      "play → playying; wash → washing; sit → sitting",
      "play → playing; wash → washing; sit → sitting",
    ],
    answerIndex: 3,
    reasons: [
      "plaing 錯刪 y，siting 又少了需要重複的 t。",
      "washeing 錯誤加入 e；wash 應直接加 -ing。",
      "playying 不應重複 y。",
      "playing 保留 y，washing 直接加 -ing，sitting 重複 t，三者皆正確。",
    ],
    reviews: [
      "三個原形分別考 y 保留、直接加 -ing 與短母音重複子音，第四列全部正確。",
      "逐格檢查而非只看其中一字後，前三列各至少有一個可明確定位的拼字錯誤。",
    ],
    cognitiveProcess: ["audit-mixed-participle-rules", "verify-entire-spelling-row"],
    representationType: "multi-verb-proofreading",
    misconceptionTargets: ["accept-row-after-checking-only-one-word"],
  }),
  question({
    id: "ENG_R4_Q_060_01",
    skillId: "ENG_R4_S060",
    difficulty: "foundation",
    stem: "___ Tom carrying the blue box?",
    options: ["Is", "Does", "Do", "Are"],
    answerIndex: 0,
    reasons: [
      "Is 配合單數 Tom，並移到主詞前形成進行式問句。",
      "Does 不和 carrying 組成現在進行式。",
      "Do 不配單數 Tom，也不能接 carrying。",
      "Are 不和單數主詞 Tom 搭配。",
    ],
    reviews: [
      "肯定句為 Tom is carrying the blue box；問句把 Is 移到 Tom 前。",
      "第一項保留原本的進行式 be，其餘助動詞或主詞一致都不成立。",
    ],
    cognitiveProcess: ["invert-is-for-progressive-question", "match-tom-with-is"],
    misconceptionTargets: ["insert-does-before-participle"],
  }),
  question({
    id: "ENG_R4_Q_060_02",
    skillId: "ENG_R4_S060",
    difficulty: "foundation",
    stem: "We ___ leaving the school yet.",
    options: ["don't", "are not", "doesn't", "not are"],
    answerIndex: 1,
    reasons: [
      "don't 不能直接接 leaving 形成進行式否定。",
      "are not 正確放在主詞 We 與 leaving 之間。",
      "doesn't 不配 We，也不能接 leaving。",
      "not are 的順序錯誤，be 應接在主詞後。",
    ],
    reviews: [
      "We 的進行式使用 are leaving，否定時在 are 後加 not，得到 are not leaving。",
      "第二項是唯一同時保留 be、一致主詞與正確 not 位置的形式。",
    ],
    cognitiveProcess: ["insert-not-after-are", "form-plural-progressive-negative"],
    misconceptionTargets: ["use-dont-before-participle"],
  }),
  question({
    id: "ENG_R4_Q_060_03",
    skillId: "ENG_R4_S060",
    difficulty: "foundation",
    stem: "Are the students taking a test? — No, ___.",
    options: ["they don't", "the students not", "they aren't", "they isn't"],
    answerIndex: 2,
    reasons: [
      "原問句使用 are，不以 don't 回答。",
      "the students not 缺少 be 動詞，不能形成標準簡答。",
      "they aren't 以複數代名詞與 are 的否定形式回答。",
      "they 不搭配 isn't。",
    ],
    reviews: [
      "the students 轉成 they，Are 問句的否定簡答為 they aren't。",
      "第三項保留原問句 be 並符合複數主詞，其餘形式在助動詞或一致上有錯。",
    ],
    cognitiveProcess: ["answer-are-question-negatively", "replace-students-with-they"],
    misconceptionTargets: ["answer-be-question-with-do"],
  }),
  question({
    id: "ENG_R4_Q_060_04",
    skillId: "ENG_R4_S060",
    difficulty: "standard",
    stem: "You want to know where Ben is going right now. What do you ask?",
    options: [
      "Where Ben is going?",
      "Is where Ben going?",
      "Where going is Ben?",
      "Where is Ben going?",
    ],
    answerIndex: 3,
    reasons: [
      "疑問詞後仍需把 is 放在主詞 Ben 前。",
      "where 後應接 is，再接主詞 Ben。",
      "going 不能放在 is 與主詞前形成此語序。",
      "Where + is + Ben + going 的疑問詞、be、主詞與分詞順序正確。",
    ],
    reviews: [
      "詢問目的地以 Where 開頭，進行式直接問句再把 is 放到 Ben 前。",
      "第四項是唯一能按 Where is Ben going? 完成標準書面問句的排列。",
    ],
    cognitiveProcess: ["arrange-progressive-wh-question", "place-where-before-inversion"],
    representationType: "destination-question-order",
    misconceptionTargets: ["keep-statement-order-after-where"],
  }),
  question({
    id: "ENG_R4_Q_060_05",
    skillId: "ENG_R4_S060",
    difficulty: "standard",
    stem: "Mia is reading in her room. Which question checks whether this is happening?",
    options: [
      "Is Mia reading in her room?",
      "Does Mia reading in her room?",
      "Do Mia read in her room?",
      "Is reading Mia in her room?",
    ],
    answerIndex: 0,
    reasons: [
      "Is Mia reading...? 正確把原句 is 移到主詞前。",
      "does 不能接 reading，且會和原本 be 結構衝突。",
      "do 不配 Mia，也把目前動作改成一般式。",
      "reading 不能放在 Mia 前；is 後應先接主詞。",
    ],
    reviews: [
      "原句的限定動詞是 is，改問句只需移到 Mia 前，故第一項正確。",
      "第一項保留房間與閱讀資訊，且未加入 do/does 或改變時態。",
    ],
    cognitiveProcess: ["transform-progressive-statement-to-question", "preserve-current-action"],
    representationType: "statement-question-transformation",
    misconceptionTargets: ["add-do-to-existing-be"],
  }),
  question({
    id: "ENG_R4_Q_060_06",
    skillId: "ENG_R4_S060",
    difficulty: "standard",
    stem: "Mia is talking on the phone. Which sentence means that she is not doing this now?",
    options: [
      "Mia doesn't talking on the phone.",
      "Mia isn't talking on the phone.",
      "Mia not is talking on the phone.",
      "Mia isn't talk on the phone.",
    ],
    answerIndex: 1,
    reasons: [
      "doesn't 不能直接接 talking。",
      "isn't talking 在 is 後加入 not，正確反轉目前動作。",
      "not 應位在 is 後，不是主詞與 is 之間。",
      "isn't 後要保留 talking，不能退回原形 talk。",
    ],
    reviews: [
      "原句為 is talking，否定只需改成 is not talking，也就是 isn't talking。",
      "第二項完整保留人、電話與進行時間，只改變肯定與否定。",
    ],
    cognitiveProcess: ["negate-current-action-with-isnt", "preserve-participle-after-not"],
    representationType: "meaning-reversal",
    misconceptionTargets: ["replace-be-not-with-do-not"],
  }),
  question({
    id: "ENG_R4_Q_060_07",
    skillId: "ENG_R4_S060",
    difficulty: "standard",
    stem: "___ Nina and Paul waiting outside?",
    options: ["Is", "Do", "Are", "Does"],
    answerIndex: 2,
    reasons: [
      "is 不配由 and 連接的兩人。",
      "do 不能和 waiting 組成進行式。",
      "are 配複數主詞 Nina and Paul，問句位置正確。",
      "does 不配複數主詞，也不能接 waiting。",
    ],
    reviews: [
      "Nina and Paul 等同 they，肯定結構是 they are waiting，問句以 Are 開頭。",
      "第三項同時處理複數一致與進行式倒裝，其餘選項至少違反其中一項。",
    ],
    cognitiveProcess: ["invert-are-with-compound-subject", "reject-do-before-waiting"],
    misconceptionTargets: ["use-is-from-first-singular-name"],
  }),
  question({
    id: "ENG_R4_Q_060_08",
    skillId: "ENG_R4_S060",
    difficulty: "advanced",
    stem: "A: Is Eric riding his bike? B: No, ___. His bike is in the shop.",
    options: ["he doesn't", "he not", "he aren't", "he isn't"],
    answerIndex: 3,
    reasons: [
      "Is 問句不能以 doesn't 簡答。",
      "he not 缺少 be 動詞。",
      "he 不搭配 aren't。",
      "he isn't 正確沿用 is，且符合腳踏車在店裡的事實。",
    ],
    reviews: [
      "bike is in the shop 支持否定，Eric 以 he 代替，Is 問句回答 he isn't。",
      "第四項在內容真值、代名詞與 be 三方面都一致，因此可唯一選出。",
    ],
    cognitiveProcess: ["combine-context-fact-with-isnt-answer", "resolve-eric-to-he"],
    representationType: "evidence-based-short-answer",
    misconceptionTargets: ["choose-doesnt-from-main-verb-ride"],
  }),
  question({
    id: "ENG_R4_Q_060_09",
    skillId: "ENG_R4_S060",
    difficulty: "advanced",
    stem: "The workers are fixing the floor. You want to check that this is true. What do you ask?",
    options: [
      "Are the workers fixing the floor?",
      "Do the workers fix the floor?",
      "Did the workers fix the floor?",
      "Are fixing the workers the floor?",
    ],
    answerIndex: 0,
    reasons: [
      "Are 放到 workers 前，保留目前正在修理的意義。",
      "Do...fix 改成一般現在式，時間觀點不同。",
      "Did...fix 改成過去式。",
      "Are 後應先接主詞 the workers，不能先放 fixing。",
    ],
    reviews: [
      "要保留 are fixing 的當下進行，只能將 Are 移到主詞前。",
      "第一項是唯一沒有改動時態與事件資訊的標準確認問句。",
    ],
    cognitiveProcess: ["preserve-progressive-during-confirmation", "compare-question-tenses"],
    representationType: "time-preserving-question-rewrite",
    misconceptionTargets: ["change-progressive-to-simple-when-questioning"],
  }),
  question({
    id: "ENG_R4_Q_060_10",
    skillId: "ENG_R4_S060",
    difficulty: "advanced",
    stem: "The team is not leaving until the rain stops. What can you tell about the team now?",
    options: [
      "The team has already left.",
      "The team has not left yet.",
      "The team leaves every time it rains.",
      "The team never plans to leave.",
    ],
    answerIndex: 1,
    reasons: [
      "is not leaving until 表示目前尚未離開。",
      "在雨停以前不離開，所以隊伍目前還沒有離開。",
      "原句沒有 every time，也未描述固定習慣。",
      "until 表示條件達成後可能離開，不是永遠不打算離開。",
    ],
    reviews: [
      "not leaving until the rain stops 把離開延後，因此現在可確認隊伍尚未離開。",
      "第二項不超出原句；其餘選項分別反轉時間、虛構規律或把暫時否定誇大。",
    ],
    cognitiveProcess: ["interpret-progressive-negative-until", "infer-not-left-yet"],
    representationType: "negative-time-meaning",
    misconceptionTargets: ["read-not-leaving-as-never-leaving"],
  }),
  question({
    id: "ENG_R4_Q_060_11",
    skillId: "ENG_R4_S060",
    difficulty: "transfer",
    stem: "A notice says, “The front door is not working. Are you using the side door?” Which words say that the front door does not work now?",
    options: ["the front door", "using the side door", "is not working", "Are you"],
    answerIndex: 2,
    reasons: [
      "the front door 是主詞名詞片語，不是否定動詞。",
      "using the side door 屬後方問句的動作。",
      "is not working 由 be、not 與分詞共同形成進行式否定。",
      "Are you 是問句開頭，沒有 not。",
    ],
    reviews: [
      "負面訊息由 is + not + working 完整表達，因此第三項是動詞片語。",
      "逐句分開後可避免把 side door 問句成分混入前一句的否定結構。",
    ],
    cognitiveProcess: ["locate-negative-progressive-phrase", "separate-notice-sentences"],
    representationType: "notice-structure-analysis",
    misconceptionTargets: ["identify-not-alone-or-wrong-clause"],
  }),
  question({
    id: "ENG_R4_Q_060_12",
    skillId: "ENG_R4_S060",
    difficulty: "transfer",
    stem: "A: ___ your parents waiting in the car? B: Yes, ___.",
    options: ["Is / they are", "Do / they do", "Are / they do", "Are / they are"],
    answerIndex: 3,
    reasons: [
      "parents 是複數，第一格不能用 Is。",
      "waiting 需要 be，不能以 Do 問或 do 回答。",
      "第一格 Are 正確，但簡答仍需沿用 are。",
      "Are 配複數 parents，they are 也正確回應同一 be 問句。",
    ],
    reviews: [
      "複數 parents 的進行式問句以 Are 開頭，肯定簡答為 Yes, they are。",
      "兩格分別檢查問句與簡答後，只有第四組在主詞和 be 上完全一致。",
    ],
    cognitiveProcess: ["pair-are-question-with-are-answer", "solve-progressive-dialogue-slots"],
    representationType: "question-answer-dual-cloze",
    misconceptionTargets: ["switch-from-be-to-do-in-short-answer"],
  }),
  question({
    id: "ENG_R4_Q_061_01",
    skillId: "ENG_R4_S061",
    difficulty: "foundation",
    stem: "Mia ___ the bus to school every day.",
    options: ["takes", "is taking", "took", "taking"],
    answerIndex: 0,
    reasons: [
      "takes 以現在簡單式表示每天反覆的上學方式。",
      "is taking 會把固定習慣改成目前暫時動作。",
      "took 是過去式，和 every day 的現行規律不合。",
      "taking 前缺少 be 動詞，不能完成句子。",
    ],
    reviews: [
      "every day 指固定習慣，單數 Mia 使用第三人稱形式 takes。",
      "第一項同時符合習慣語意與主詞一致，其他形式改變時間或不完整。",
    ],
    cognitiveProcess: ["select-simple-present-for-daily-transport", "apply-mia-takes"],
    misconceptionTargets: ["use-progressive-for-every-repeated-action"],
  }),
  question({
    id: "ENG_R4_Q_061_02",
    skillId: "ENG_R4_S061",
    difficulty: "foundation",
    stem: "Please wait. Mr. Wu ___ with another student now.",
    options: ["talks", "is talking", "talked", "talk"],
    answerIndex: 1,
    reasons: [
      "talks 表示一般習慣，不能解釋目前需要等候。",
      "is talking 描述 Mr. Wu 此刻正在和另一位學生談話。",
      "talked 表示談話已結束，與 Please wait 衝突。",
      "talk 不配單數 Mr. Wu，也未形成進行式。",
    ],
    reviews: [
      "Please wait 與 now 共同建立當下情境，單數 Mr. Wu 搭配 is talking。",
      "第二項是唯一能成為目前等候理由的形式，其餘不是習慣、過去，就是不完整。",
    ],
    cognitiveProcess: ["use-current-action-as-request-reason", "choose-is-talking"],
    representationType: "request-and-reason",
    misconceptionTargets: ["choose-simple-form-from-singular-subject-only"],
  }),
  question({
    id: "ENG_R4_Q_061_03",
    skillId: "ENG_R4_S061",
    difficulty: "foundation",
    stem: "My uncle ___ in Tainan, but this week he ___ in Taipei.",
    options: ["is living / stays", "lived / stays", "lives / is staying", "lives / stayed"],
    answerIndex: 2,
    reasons: [
      "第一格把長期住所寫成暫時，第二格又把本週寫成習慣。",
      "lived 把目前住所移到過去，stays 也未呈現 this week 的暫時性。",
      "lives 表長期住所，is staying 表本週暫住，兩格都符合。",
      "第一格正確，但 stayed 把仍在進行的 this week 寫成已結束。",
    ],
    reviews: [
      "住臺南是長期狀態，本週待臺北是暫時安排，因此選 lives / is staying。",
      "but 兩側各有不同時間觀點，第三組是唯一沒有把長期與暫時顛倒的答案。",
    ],
    cognitiveProcess: ["contrast-residence-with-current-visit", "solve-simple-progressive-pair"],
    representationType: "long-term-temporary-dual-cloze",
    misconceptionTargets: ["assign-one-tense-to-both-locations"],
  }),
  question({
    id: "ENG_R4_Q_061_04",
    skillId: "ENG_R4_S061",
    difficulty: "standard",
    stem: "Nora works at the hospital, but today she is helping at a school. What do these two facts tell us?",
    options: [
      "Nora no longer works at the hospital.",
      "Nora helps at the school every day.",
      "She usually works at the hospital and is helping at the school today.",
      "Nora worked at the hospital only in the past.",
    ],
    answerIndex: 2,
    reasons: [
      "works 是目前長期狀態，不能推得她已離職。",
      "today 只說今天，沒有 every day 的規律。",
      "簡單式 works 對應通常工作，is helping 對應今天的臨時工作。",
      "works 不是過去式，醫院工作並未被限定在過去。",
    ],
    reviews: [
      "兩個時態分別呈現長期工作與今日例外，第三項完整保留這個對比。",
      "其他選項把 today 誇大為永久改變或每日規律；第三項沒有增加題目未說的資訊。",
    ],
    cognitiveProcess: ["interpret-workplace-tense-contrast", "reject-permanent-change-inference"],
    representationType: "dual-fact-interpretation",
    misconceptionTargets: ["read-temporary-help-as-job-change"],
  }),
  question({
    id: "ENG_R4_Q_061_05",
    skillId: "ENG_R4_S061",
    difficulty: "standard",
    stem: "The shop usually closes at nine. Tonight it ___ open until eleven for a school event.",
    options: ["is staying", "stays every night", "stayed yesterday", "stay"],
    answerIndex: 0,
    reasons: [
      "is staying 把延長開放限定在今晚的活動。",
      "stays every night 與 usually closes at nine 及 Tonight 的例外衝突。",
      "stayed yesterday 改成昨天，沒有回應今晚安排。",
      "stay 不配單數 it，也缺少進行式。",
    ],
    reviews: [
      "usually 說平常九點關門，Tonight 引出一次性延長，因此選 is staying。",
      "第一項保留活動造成的今晚例外；其他選項虛構每晚規律、改變日期或不完整。",
    ],
    cognitiveProcess: ["contrast-usual-closing-with-one-night-extension", "choose-is-staying-open"],
    representationType: "event-hours-context",
    misconceptionTargets: ["turn-one-night-exception-into-routine"],
  }),
  question({
    id: "ENG_R4_Q_061_06",
    skillId: "ENG_R4_S061",
    difficulty: "standard",
    stem: "A picture shows two children kicking a ball. Which sentence describes only the pictured moment?",
    options: [
      "The children play soccer after school.",
      "The children are playing soccer.",
      "The children played soccer yesterday.",
      "The children will play soccer next week.",
    ],
    answerIndex: 1,
    reasons: [
      "after school 表示規律，單張圖片不能證明這項習慣。",
      "are playing 只描述圖片中的目前動作。",
      "yesterday 是圖片未提供的過去時間。",
      "next week 是圖片未提供的未來計畫。",
    ],
    reviews: [
      "圖片只呈現球正在被踢的畫面，複數 children 使用 are playing。",
      "第二項沒有額外加入過去、未來或反覆時間，是唯一只描述眼前畫面的句子。",
    ],
    cognitiveProcess: ["separate-single-scene-from-habit", "choose-moment-only-caption"],
    representationType: "text-described-picture-tense",
    misconceptionTargets: ["infer-routine-from-one-photo"],
  }),
  question({
    id: "ENG_R4_Q_061_07",
    skillId: "ENG_R4_S061",
    difficulty: "standard",
    stem: "Sam reads before bed every night, but he reading in the park now. Which word is missing?",
    options: ["does", "has", "is", "reads"],
    answerIndex: 2,
    reasons: [
      "does 不能直接接 reading 形成進行式。",
      "has reading 不是本題所需的現在形式。",
      "is 補在 he 與 reading 之間，呈現 now 的目前動作。",
      "reads reading 會同時放入兩個主要動詞形式。",
    ],
    reviews: [
      "前句 reads 表每晚習慣，後句 now 需要 he is reading，因此缺 is。",
      "第三項只補足進行式 be，保留 park 與現在閱讀的原意。",
    ],
    cognitiveProcess: ["repair-simple-progressive-contrast", "supply-is-before-reading"],
    representationType: "contrast-sentence-repair",
    misconceptionTargets: ["reuse-simple-verb-in-now-clause"],
  }),
  question({
    id: "ENG_R4_Q_061_08",
    skillId: "ENG_R4_S061",
    difficulty: "advanced",
    stem: "The bus leaves at 7:00 every morning. Workers are checking it today, so it ___ at 8:00.",
    options: ["leaves every day", "left yesterday", "leave", "is leaving"],
    answerIndex: 3,
    reasons: [
      "leaves every day 重複一般班次，無法表達 today 的臨時改點。",
      "left yesterday 與今天八點的安排無關。",
      "leave 不配單數 it，也沒有暫時安排的結構。",
      "is leaving 表示今天因檢查而採用的臨時出發時間。",
    ],
    reviews: [
      "第一句是固定班次，Today 與 workers are checking 引出今日例外，故用 is leaving。",
      "第四項是唯一能把八點限制在今天且與單數 it 搭配的答案。",
    ],
    cognitiveProcess: ["contrast-timetable-with-one-day-change", "select-progressive-for-arranged-exception"],
    representationType: "transport-change-notice",
    misconceptionTargets: ["keep-schedule-form-for-temporary-change"],
  }),
  question({
    id: "ENG_R4_Q_061_09",
    skillId: "ENG_R4_S061",
    difficulty: "advanced",
    stem: "“Paul is working at home this month.” What does this sentence tell us?",
    options: [
      "Paul's work at home is for this month.",
      "Paul works at home every month.",
      "Paul finished working at home.",
      "Paul never works in another place.",
    ],
    answerIndex: 0,
    reasons: [
      "is working 與 this month 共同表示目前有限期間。",
      "this month 不等於 every month，不能推成規律。",
      "句子是現在進行式，沒有表示已完成。",
      "原句未排除其他工作地點或時間。",
    ],
    reviews: [
      "this month 限定目前一段期間，is working 將安排看成暫時，故第一項正確。",
      "其餘選項分別虛構週期、完成或絕對限制，都超出原句。",
    ],
    cognitiveProcess: ["interpret-temporary-work-progressive", "distinguish-this-from-every-month"],
    representationType: "aspect-meaning-selection",
    misconceptionTargets: ["turn-this-month-into-monthly-habit"],
  }),
  question({
    id: "ENG_R4_Q_061_10",
    skillId: "ENG_R4_S061",
    difficulty: "advanced",
    stem: "A: Why can't Grace answer the phone? B: She ___ a test at the moment.",
    options: ["takes every Friday", "is taking", "took last week", "take"],
    answerIndex: 1,
    reasons: [
      "每週五考試的習慣不能說明她此刻無法接電話。",
      "is taking 和 at the moment 表示她正在考試。",
      "last week 的過去考試不會造成現在無法接聽。",
      "take 不配單數 she，也缺少進行式。",
    ],
    reviews: [
      "at the moment 與不能接電話的目前原因要求 is taking。",
      "第二項能直接連結當下限制，其他答案不是不同時間，就是句法不完整。",
    ],
    cognitiveProcess: ["explain-present-unavailability", "choose-current-test-action"],
    representationType: "availability-dialogue",
    misconceptionTargets: ["answer-present-why-with-recurring-event"],
  }),
  question({
    id: "ENG_R4_Q_061_11",
    skillId: "ENG_R4_S061",
    difficulty: "transfer",
    stem: "Ken usually walks to work. Because of the rain this week, he is taking the bus. Which words show what Ken does most of the time?",
    options: ["Because of the rain", "this week", "is taking the bus", "usually walks to work"],
    answerIndex: 3,
    reasons: [
      "Because of the rain 說明改變原因，不是平常習慣。",
      "this week 限定目前的短期期間。",
      "is taking the bus 是這週的暫時作法。",
      "usually 與 walks 共同指出平常走路上班的規律。",
    ],
    reviews: [
      "題目詢問多數時間的做法，usually walks to work 正是現在簡單式的習慣部分。",
      "其餘三項都屬於下雨造成的本週例外，不能當成 Ken 的通常方式。",
    ],
    cognitiveProcess: ["locate-routine-within-temporary-change", "separate-cause-period-and-action"],
    representationType: "contrast-component-identification",
    misconceptionTargets: ["label-current-bus-use-as-routine"],
  }),
  question({
    id: "ENG_R4_Q_061_12",
    skillId: "ENG_R4_S061",
    difficulty: "transfer",
    stem: "Every summer, many families ___ the lake. Right now, one family ___ lunch beside the water.",
    options: ["are visiting / has", "visited / had", "visits / are having", "visit / is having"],
    answerIndex: 3,
    reasons: [
      "Every summer 需要習慣形式 visit，不是 are visiting；第二格也未呈現當下進行。",
      "兩個過去式與每年規律及 right now 都不合。",
      "families 是複數不能用 visits，family 作一個群體也不搭配 are。",
      "visit 表每年規律，is having 表一個家庭目前正在吃午餐。",
    ],
    reviews: [
      "Every summer 控制複數 families 的 visit；Right now 控制單數 family 的 is having。",
      "逐子句檢查時間與主詞後，只有第四組同時符合兩種現在式。",
    ],
    cognitiveProcess: ["combine-seasonal-routine-with-live-scene", "resolve-families-versus-family"],
    representationType: "dual-subject-dual-aspect-cloze",
    misconceptionTargets: ["carry-plural-and-tense-across-sentences"],
  }),
  question({
    id: "ENG_R4_Q_062_01",
    skillId: "ENG_R4_S062",
    difficulty: "foundation",
    stem: "What time does “at the moment” point to?",
    options: ["The time when someone is speaking", "Every Monday", "Last night", "Next year"],
    answerIndex: 0,
    reasons: [
      "at the moment 指說話者正在談論的目前時間。",
      "Every Monday 表示每週反覆的時間，不是此刻。",
      "Last night 指已經過去的昨晚。",
      "Next year 指尚未到來的未來時間。",
    ],
    reviews: [
      "at the moment 把事件放在說話當下，因此第一項正確。",
      "其餘選項分別是反覆、過去與未來時間，不能解釋這個片語。",
    ],
    cognitiveProcess: ["interpret-at-the-moment-as-current", "separate-current-from-routine-past-future"],
    representationType: "time-expression-interpretation",
    misconceptionTargets: ["ignore-explicit-current-time-phrase"],
  }),
  question({
    id: "ENG_R4_Q_062_02",
    skillId: "ENG_R4_S062",
    difficulty: "foundation",
    stem: "Listen! The phone ___.",
    options: ["rings every hour", "is ringing", "rang", "ring"],
    answerIndex: 1,
    reasons: [
      "every hour 表示規律，不能描述 Listen 指出的這次鈴聲。",
      "is ringing 表示電話現在正在響。",
      "rang 表示鈴聲已在過去結束。",
      "ring 不配單數 phone，也未形成進行式。",
    ],
    reviews: [
      "Listen 要求注意目前聲音，單數 phone 搭配 is ringing。",
      "第二項能解釋為何現在要聽；其他形式指習慣、過去或不完整。",
    ],
    cognitiveProcess: ["use-listen-as-sound-scene-cue", "choose-is-ringing"],
    misconceptionTargets: ["interpret-audible-event-as-hourly-habit"],
  }),
  question({
    id: "ENG_R4_Q_062_03",
    skillId: "ENG_R4_S062",
    difficulty: "foundation",
    stem: "Look! A girl is running toward the bus. What does Look! tell us here?",
    options: ["She runs only on Mondays.", "She finished running yesterday.", "Her running is happening now.", "She never runs."],
    answerIndex: 2,
    reasons: [
      "Look! 沒有提供 only on Mondays 的固定規律。",
      "Look! 指向眼前畫面，不是昨天已完成的動作。",
      "Look! 要聽者注意目前畫面，因此跑步正在發生。",
      "題面直接說女孩正在跑，never runs 與內容相反。",
    ],
    reviews: [
      "句首 Look! 建立眼前情境，is running 說明動作正在此刻進行。",
      "第三項只解釋 Look! 的時間作用；其他選項加入題目沒有或直接否定的資訊。",
    ],
    cognitiveProcess: ["interpret-look-as-live-scene-cue", "reject-unprovided-routine-past-and-never"],
    representationType: "cue-function-interpretation",
    misconceptionTargets: ["treat-look-command-as-routine-marker"],
  }),
  question({
    id: "ENG_R4_Q_062_04",
    skillId: "ENG_R4_S062",
    difficulty: "standard",
    stem: "In “The children are eating lunch right now,” which words place the action at the speaking time?",
    options: ["The children", "are eating", "eating lunch", "right now"],
    answerIndex: 3,
    reasons: [
      "The children 指出誰在行動，沒有提供時間。",
      "are eating 是進行式形式，但題目問的是明示時間線索。",
      "eating lunch 說明動作內容。",
      "right now 直接把午餐動作放在說話當下。",
    ],
    reviews: [
      "right now 是句中直接回答何時發生的時間片語，因此選第四項。",
      "主詞、動詞形式與受詞各有其他功能，只有 right now 明確定位說話時間。",
    ],
    cognitiveProcess: ["locate-explicit-speaking-time-marker", "distinguish-clue-from-verb-form"],
    representationType: "time-marker-identification",
    misconceptionTargets: ["name-progressive-form-instead-of-time-clue"],
  }),
  question({
    id: "ENG_R4_Q_062_05",
    skillId: "ENG_R4_S062",
    difficulty: "standard",
    stem: "A: Why is the ground getting wet? B: It ___.",
    options: ["is raining", "rains every summer", "rained last night", "rain"],
    answerIndex: 0,
    reasons: [
      "is raining 說明地面目前持續變濕的直接原因。",
      "每年夏天的規律無法單獨解釋眼前正在變濕。",
      "昨晚的雨可能已停，和 getting wet 的目前變化不一致。",
      "rain 不配單數 it，也不是完整進行式。",
    ],
    reviews: [
      "getting wet 顯示地面正在變化，回答目前原因應使用 It is raining。",
      "第一項由現場結果推回同時發生的動作，其他選項改成規律、過去或不完整。",
    ],
    cognitiveProcess: ["infer-current-rain-from-changing-ground", "answer-present-cause"],
    representationType: "evidence-to-current-cause",
    misconceptionTargets: ["prefer-past-rain-without-matching-getting"],
  }),
  question({
    id: "ENG_R4_Q_062_06",
    skillId: "ENG_R4_S062",
    difficulty: "standard",
    stem: "These days, I am reading a long book. What does these days mean here?",
    options: [
      "Only the second when I speak",
      "A time that can include several days",
      "A habit that happens every year",
      "A time that ended before now",
    ],
    answerIndex: 1,
    reasons: [
      "these days 不只限說話的一秒。",
      "它可涵蓋目前一段日子，閱讀活動仍在進行中。",
      "句子沒有 every year，不能推成年度習慣。",
      "am reading 不是已完成的過去式。",
    ],
    reviews: [
      "these days 在此指目前一段期間，可能跨越數日而非眼前一秒。",
      "第二項符合長書尚在閱讀中的語意，其他選項縮得過窄或改變時間。",
    ],
    cognitiveProcess: ["interpret-broad-current-period", "avoid-one-second-reading-of-progressive"],
    representationType: "time-expression-meaning",
    misconceptionTargets: ["equate-all-progressive-with-instant-only"],
  }),
  question({
    id: "ENG_R4_Q_062_07",
    skillId: "ENG_R4_S062",
    difficulty: "standard",
    stem: "Sara looks tired after every long practice. Why does looks stay in the simple present?",
    options: [
      "Because tired is a place.",
      "Because looks always means to watch.",
      "Because this happens after every long practice; Look! is not used here.",
      "Because Sara means two people.",
    ],
    answerIndex: 2,
    reasons: [
      "tired 描述狀態，不是地點。",
      "looks 在此表示看起來，不是觀看，而且 always 的說法過度。",
      "every long practice 建立反覆情況，句首也沒有命令語 Look!。",
      "Sara 是單數，這正是 looks 加 -s 的原因。",
    ],
    reviews: [
      "此處 look 是句中動詞 looks，配合每次練習後的重複狀態，不是 Look! 命令。",
      "第三項同時辨認字義位置與 every 的週期，能排除只看到 look 就選進行式的誤判。",
    ],
    cognitiveProcess: ["distinguish-look-verb-from-look-command", "retain-simple-for-repeated-state"],
    representationType: "look-function-contrast",
    misconceptionTargets: ["treat-any-look-token-as-progressive-cue"],
  }),
  question({
    id: "ENG_R4_Q_062_08",
    skillId: "ENG_R4_S062",
    difficulty: "advanced",
    stem: "Look! Ben ___ for the bus, but his sister ___ to school every day.",
    options: ["waits / is walking", "waited / walks", "is waiting / is walking", "is waiting / walks"],
    answerIndex: 3,
    reasons: [
      "Look 控制第一格，不能用 waits；every day 控制第二格，也不需進行式。",
      "waited 是過去式，沒有描述眼前 Ben。",
      "第一格正確，但第二格把每日習慣錯寫成目前動作。",
      "is waiting 配 Look，walks 配 every day，兩個線索各控制自己的子句。",
    ],
    reviews: [
      "Look! 對應 Ben 的 is waiting；every day 對應 sister 的 walks。",
      "第四組證明線索不能支配整句，逐子句配對後沒有其他完整答案。",
    ],
    cognitiveProcess: ["limit-look-cue-to-first-clause", "pair-every-day-with-simple-second-clause"],
    representationType: "dual-clue-scope-cloze",
    misconceptionTargets: ["spread-look-cue-over-both-clauses"],
  }),
  question({
    id: "ENG_R4_Q_062_09",
    skillId: "ENG_R4_S062",
    difficulty: "advanced",
    stem: "During a phone call, Nina asks, “What ___ you ___?”",
    options: ["are / doing", "do / doing", "are / do", "is / doing"],
    answerIndex: 0,
    reasons: [
      "are / doing 形成 What are you doing?，詢問通話當下的活動。",
      "do 不能直接和 doing 並用。",
      "are 後需要現在分詞 doing，不是原形 do。",
      "you 不搭配 is。",
    ],
    reviews: [
      "電話情境可建立目前時間，you 搭配 are，主要動詞用 doing。",
      "第一組同時滿足問句倒裝、主詞一致與現在分詞，其餘各有明確結構錯誤。",
    ],
    cognitiveProcess: ["infer-now-from-live-phone-call", "assemble-what-are-you-doing"],
    representationType: "live-call-question",
    misconceptionTargets: ["require-written-now-before-progressive"],
  }),
  question({
    id: "ENG_R4_Q_062_10",
    skillId: "ENG_R4_S062",
    difficulty: "advanced",
    stem: "The window is open, papers are moving, and Ann is holding her hat. What is most likely happening?",
    options: [
      "Ann opens the window every morning.",
      "A strong wind is coming through the window.",
      "The papers moved yesterday.",
      "Ann will buy a new hat next week.",
    ],
    answerIndex: 1,
    reasons: [
      "畫面未提供 every morning 的固定習慣。",
      "紙張正在移動且 Ann 正抓帽子，支持風目前正吹入。",
      "are moving 表示目前，不是昨天已結束的動作。",
      "題面沒有購買或下週的資訊。",
    ],
    reviews: [
      "moving papers 與 holding her hat 是同時的現場證據，最合理解釋是風正在吹入。",
      "第二項由多項目前證據共同支持，其他選項都加入題面沒有的時間或事件。",
    ],
    cognitiveProcess: ["infer-unwritten-current-event-from-clues", "combine-multiple-live-observations"],
    representationType: "scene-evidence-inference",
    misconceptionTargets: ["demand-explicit-now-despite-live-evidence"],
  }),
  question({
    id: "ENG_R4_Q_062_11",
    skillId: "ENG_R4_S062",
    difficulty: "transfer",
    stem: "“Dad usually cooks dinner, but right now he is fixing the door.” Which action does right now describe?",
    options: ["cooks", "dinner", "is fixing the door", "usually cooks dinner"],
    answerIndex: 2,
    reasons: [
      "cooks 屬於 usually 所修飾的平常習慣。",
      "dinner 是受詞，不是 right now 所描述的動作。",
      "right now 直接放在第二子句前，控制 is fixing the door。",
      "usually cooks dinner 是完整習慣片語，與當下例外相對。",
    ],
    reviews: [
      "but 後的 right now 緊接 he is fixing，故只描述目前修門的動作。",
      "第三項符合子句位置與語意，其他選項都屬前半句習慣或不是動作。",
    ],
    cognitiveProcess: ["trace-right-now-to-nearest-clause", "separate-object-from-action"],
    representationType: "clue-scope-question",
    misconceptionTargets: ["attach-now-to-earlier-usual-action"],
  }),
  question({
    id: "ENG_R4_Q_062_12",
    skillId: "ENG_R4_S062",
    difficulty: "transfer",
    stem: "A library message says, “Please use the side room. A class ___ in the reading room now.”",
    options: ["meets there every Friday", "met there last week", "meet", "is meeting"],
    answerIndex: 3,
    reasons: [
      "每週五的規律不足以解釋現在必須改用側室。",
      "上週的會議已結束，不能成為目前指示的原因。",
      "meet 不配單數 A class，也不是進行式。",
      "is meeting 與 now 說明閱讀室目前正在被一個班級使用。",
    ],
    reviews: [
      "Please use the side room 與 now 共同要求目前原因，A class 搭配 is meeting。",
      "第四項能解釋即時改用房間的指示，其他選項改成規律、過去或不完整。",
    ],
    cognitiveProcess: ["link-room-direction-to-current-use", "complete-library-message"],
    representationType: "facility-message-context",
    misconceptionTargets: ["answer-live-room-conflict-with-weekly-schedule"],
  }),
  question({
    id: "ENG_R4_Q_063_01",
    skillId: "ENG_R4_S063",
    difficulty: "foundation",
    stem: "I ___ the answer now.",
    options: ["know", "am knowing", "knows", "knowing"],
    answerIndex: 0,
    reasons: [
      "know 在此表示目前具有的認知，主詞 I 使用原形。",
      "am knowing 不符合 know 表認知狀態的基礎用法。",
      "knows 不配主詞 I。",
      "knowing 前缺少 be，且此語意也不需進行式。",
    ],
    reviews: [
      "now 只說認知在目前成立，know 仍是狀態動詞，因此使用 I know。",
      "第一項在語意與主詞上皆正確；其餘選項不是不自然的進行式，就是形式不合。",
    ],
    cognitiveProcess: ["keep-know-simple-despite-now", "match-i-with-know"],
    misconceptionTargets: ["let-now-force-knowing"],
  }),
  question({
    id: "ENG_R4_Q_063_02",
    skillId: "ENG_R4_S063",
    difficulty: "foundation",
    stem: "Mia ___ a glass of water after the long walk.",
    options: ["is wanting", "wants", "want", "wanting"],
    answerIndex: 1,
    reasons: [
      "want 表需求狀態時，基礎用法通常不採進行式。",
      "wants 配合單數 Mia，表示她目前想要水。",
      "want 未配合第三人稱單數。",
      "wanting 不能獨立作謂語，也不適合此狀態意義。",
    ],
    reviews: [
      "Mia 是單數，want 表示想要的狀態，所以用現在簡單式 wants。",
      "第二項同時符合狀態動詞與主詞一致，其他形式不是進行式誤用，就是缺少變化。",
    ],
    cognitiveProcess: ["classify-want-as-current-state", "apply-third-person-wants"],
    misconceptionTargets: ["use-is-wanting-for-immediate-desire"],
  }),
  question({
    id: "ENG_R4_Q_063_03",
    skillId: "ENG_R4_S063",
    difficulty: "foundation",
    stem: "We ___ more time to finish the work.",
    options: ["are needing", "needs", "need", "needing"],
    answerIndex: 2,
    reasons: [
      "need 表需求狀態，通常不寫 are needing。",
      "needs 不配複數概念 We。",
      "need 以現在簡單式配合 We，語意自然。",
      "needing 前缺少限定動詞，也非此處標準用法。",
    ],
    reviews: [
      "題目說目前需要更多時間，need 是狀態動詞，We 搭配原形 need。",
      "第三項既不誤用進行式，也沒有第三人稱單數錯誤。",
    ],
    cognitiveProcess: ["express-need-as-state", "select-we-need-form"],
    misconceptionTargets: ["treat-urgent-need-as-progressive-action"],
  }),
  question({
    id: "ENG_R4_Q_063_04",
    skillId: "ENG_R4_S063",
    difficulty: "standard",
    stem: "Nora ___ this song very much.",
    options: ["is like", "liking", "is liking", "likes"],
    answerIndex: 3,
    reasons: [
      "is like 不是 like 表喜好的現在式結構。",
      "liking 前缺少 be，且此處喜好不需進行式。",
      "is liking 把穩定喜好寫成進行動作，不合基礎語意。",
      "likes 以現在簡單式表達 Nora 的喜好，並符合單數主詞。",
    ],
    reviews: [
      "like 在此表示喜好狀態，單數 Nora 使用 likes，因此第四項正確。",
      "只有 likes 同時符合動詞意義與第三人稱形式，其他選項各有結構或語意問題。",
    ],
    cognitiveProcess: ["recognize-like-as-preference-state", "choose-nora-likes"],
    misconceptionTargets: ["turn-preference-into-visible-process"],
  }),
  question({
    id: "ENG_R4_Q_063_05",
    skillId: "ENG_R4_S063",
    difficulty: "standard",
    stem: "My family ___ a small shop near the station.",
    options: ["owns", "is owning", "owning", "own"],
    answerIndex: 0,
    reasons: [
      "owns 以現在簡單式表示家庭擁有商店的關係。",
      "is owning 把所有關係誤寫成正在進行的活動。",
      "owning 前缺少限定動詞，也不適合此處。",
      "題句把 family 視為一個整體，原形 own 未配合單數。",
    ],
    reviews: [
      "own 表所有關係，通常使用簡單式；family 在此為單數整體，所以選 owns。",
      "第一項同時處理狀態意義與主詞一致，其他形式不是進行式誤用，就是不完整。",
    ],
    cognitiveProcess: ["treat-ownership-as-stable-relation", "agree-family-with-owns"],
    misconceptionTargets: ["use-progressive-because-shop-is-currently-owned"],
  }),
  question({
    id: "ENG_R4_Q_063_06",
    skillId: "ENG_R4_S063",
    difficulty: "standard",
    stem: "Mia ___ a new bike, and she ___ lunch now.",
    options: ["is having / has", "has / is having", "has / has", "is having / is having"],
    answerIndex: 1,
    reasons: [
      "第一格擁有腳踏車不使用 is having，第二格吃午餐也不宜寫 has。",
      "has 表擁有，is having lunch 表目前正在用餐，兩格意義都正確。",
      "第二個 has 把 now 的用餐活動寫成一般狀態。",
      "第一個 is having 把所有關係誤當成進行活動。",
    ],
    reviews: [
      "同一 have 在第一格表示擁有，用 has；第二格是 have lunch 的活動，用 is having。",
      "第二組依語意分開判斷，不因動詞相同就強迫兩格使用同一形式。",
    ],
    cognitiveProcess: ["separate-possession-have-from-meal-have", "choose-two-have-aspects"],
    representationType: "same-verb-different-meaning-cloze",
    misconceptionTargets: ["apply-one-have-form-to-both-meanings"],
  }),
  question({
    id: "ENG_R4_Q_063_07",
    skillId: "ENG_R4_S063",
    difficulty: "standard",
    stem: "I ___ this plan is good, but I ___ about one problem.",
    options: ["am thinking / think", "think / think", "think / am thinking", "am thinking / am thinking"],
    answerIndex: 2,
    reasons: [
      "第一格表看法不需進行式，第二格正在思考則可用進行式。",
      "第一格正確，但第二格未呈現目前思考過程。",
      "think 表達看法，am thinking about 表示正在思考，兩格皆合。",
      "第一格 am thinking 不適合直接表達既有看法。",
    ],
    reviews: [
      "think + 子句說看法；think about 說正在進行的思考，因此選 think / am thinking。",
      "第三項以動詞實際意義而非字面相同決定形式，能唯一保留兩個語意。",
    ],
    cognitiveProcess: ["distinguish-opinion-think-from-process-think", "solve-think-meaning-pair"],
    representationType: "polysemy-aspect-cloze",
    misconceptionTargets: ["ban-or-force-progressive-for-all-think-uses"],
  }),
  question({
    id: "ENG_R4_Q_063_08",
    skillId: "ENG_R4_S063",
    difficulty: "advanced",
    stem: "The teacher is speaking clearly, and I ___ every word now.",
    options: ["am understand", "am understanding", "understands", "understand"],
    answerIndex: 3,
    reasons: [
      "am understand 不是 be 加現在分詞的合法形式。",
      "understand 表認知狀態，基礎用法通常不寫 am understanding。",
      "understands 不配主詞 I。",
      "understand 以簡單式表示目前理解，並配合 I。",
    ],
    reviews: [
      "now 不會使認知狀態自動進行化；主詞 I 應使用 understand。",
      "第四項同時符合狀態動詞與主詞形式，另外三項各有明確結構或一致錯誤。",
    ],
    cognitiveProcess: ["resist-now-with-understand-state", "select-i-understand"],
    misconceptionTargets: ["apply-progressive-to-current-comprehension"],
  }),
  question({
    id: "ENG_R4_Q_063_09",
    skillId: "ENG_R4_S063",
    difficulty: "advanced",
    stem: "“I know the answer, and Ben is writing it down now.” Which pair keeps both time meanings?",
    options: [
      "I know the answer. / Ben is writing it down.",
      "I am knowing the answer. / Ben writes it down right now.",
      "I know the answer. / Ben writing it down.",
      "I am know the answer. / Ben is write it down.",
    ],
    answerIndex: 0,
    reasons: [
      "know 以簡單式表認知，is writing 表目前動作，兩句都自然。",
      "am knowing 不自然，right now 的動作也應用進行式。",
      "第二句缺少 is，只有 writing 不能作完整謂語。",
      "am know 與 is write 都不是正確進行式。",
    ],
    reviews: [
      "第一組把認知狀態和正在記錄的動作分別處理，沒有強迫使用同一形式。",
      "其餘三組至少包含一個狀態動詞誤用或缺少 V-ing 的結構錯誤。",
    ],
    cognitiveProcess: ["coordinate-state-and-action-sentences", "validate-both-members-of-pair"],
    representationType: "state-action-pair-selection",
    misconceptionTargets: ["make-state-and-action-share-one-aspect"],
  }),
  question({
    id: "ENG_R4_Q_063_10",
    skillId: "ENG_R4_S063",
    difficulty: "advanced",
    stem: "“I am knowing the answer” is not used in this lesson. Why?",
    options: [
      "Because know must take -s after I.",
      "Because know tells what a person understands; it is not an action happening now.",
      "Because answer must come before know.",
      "Because now always changes know to knew.",
    ],
    answerIndex: 1,
    reasons: [
      "I 搭配原形 know，不加 -s；這不是進行式不適用的原因。",
      "know 在此表示已有的認知狀態，通常使用現在簡單式。",
      "受詞 answer 正常放在 know 後，字序不需要對調。",
      "now 表示目前，不會把 know 自動改成過去式 knew。",
    ],
    reviews: [
      "問題在 know 的狀態意義，不在主詞或受詞；因此第二項精確說明原因。",
      "第二項可直接導回 I know the answer，其餘選項都談到無關或錯誤規則。",
    ],
    cognitiveProcess: ["explain-stative-know-restriction", "reject-unrelated-grammar-causes"],
    representationType: "specific-error-explanation",
    misconceptionTargets: ["memorize-form-without-semantic-reason"],
  }),
  question({
    id: "ENG_R4_Q_063_11",
    skillId: "ENG_R4_S063",
    difficulty: "transfer",
    stem: "A teacher asks, “Do you understand the next step?” Which answer says that the student understands it now?",
    options: ["I am understanding it now.", "I understanding it.", "Yes, I understand it.", "Yes, I am understand it."],
    answerIndex: 2,
    reasons: [
      "am understanding 不符合本課對 understand 認知狀態的基礎用法。",
      "understanding 前缺少 be，句子也不完整。",
      "I understand 以簡單式清楚報告目前理解狀態。",
      "am 後不能直接接原形 understand。",
    ],
    reviews: [
      "老師詢問目前是否理解，狀態動詞 understand 用簡單式，故第三項正確。",
      "第三項同時回答 Yes 並給完整狀態句；其他形式都誤用或缺少動詞結構。",
    ],
    cognitiveProcess: ["respond-to-comprehension-check", "use-understand-in-present-state"],
    representationType: "classroom-understanding-dialogue",
    misconceptionTargets: ["use-progressive-because-teacher-says-present"],
  }),
  question({
    id: "ENG_R4_Q_063_12",
    skillId: "ENG_R4_S063",
    difficulty: "transfer",
    stem: "We ___ this computer today because our own computer is being fixed.",
    options: ["are needing", "needs", "are use", "need"],
    answerIndex: 3,
    reasons: [
      "need 表需求狀態，基礎用法不因 today 自動改成 are needing。",
      "needs 不配主詞 We。",
      "are use 不是現在進行式，且意思改成使用而非需要。",
      "need 配合 We，清楚表達今天存在的需求。",
    ],
    reviews: [
      "today 限定需求的時間，但 need 仍是狀態動詞；We 使用原形 need。",
      "第四項保留題目要表達的需求，並符合主詞一致，其他選項或誤用進行式或改變意思。",
    ],
    cognitiveProcess: ["apply-stative-need-in-temporary-context", "separate-duration-from-aspect"],
    representationType: "temporary-need-context",
    misconceptionTargets: ["force-progressive-from-temporary-time-word"],
  }),
];

export const ENGLISH_U09_VOCABULARY_POLICY = Object.freeze({
  capQuestionBasis: "appendix-5-table-1",
  additionalLearningTerms: ["add", "ball", "describe", "double", "event", "final", "hall", "include", "message", "step", "toward", "upstairs"],
  properNames: ["Amy", "Ann", "Ben", "Chen", "Eric", "Grace", "Hualien", "Jay", "June", "Ken", "Kevin", "Leo", "Lily", "Lina", "Linda", "Maya", "Mia", "Nina", "Nora", "Owen", "Paul", "Rita", "Sam", "Sara", "Tainan", "Taipei", "Tom", "Wu"],
  grammarNotation: ["B", "D", "-ee", "-g", "-ie", "-ies", "-ing", "-k", "-n", "-V", "V-ing", "-w", "-x", "-y"],
  malformedDistractors: [
    "amn't",
    "fixeing",
    "fixxing",
    "lieing",
    "liying",
    "makeing",
    "makking",
    "plaing",
    "playying",
    "readding",
    "readig",
    "rideing",
    "runeing",
    "runing",
    "seeeing",
    "seing",
    "siting",
    "sseeing",
    "stopeing",
    "stoping",
    "stoppping",
    "studiing",
    "studyying",
    "swimeing",
    "swiming",
    "tieing",
    "tiying",
    "washeing",
  ],
});

export const ENGLISH_U09_SOURCE = Object.freeze({
  unitId: UNIT_ID,
  lectures: ENGLISH_U09_LECTURES,
  questions: ENGLISH_U09_QUESTIONS,
  vocabularyPolicy: ENGLISH_U09_VOCABULARY_POLICY,
});

export const ENGLISH_UNIT_SOURCE = ENGLISH_U09_SOURCE;

export { question };
