const UNIT_ID = "ENG_R4_U27";

function lecture(id, skillId, content) {
  return { id, skillId, ...content, sections: content.sections.map((section, index) => ({ id: id + "_SEC_" + String(index + 1).padStart(2, "0"), ...section })) };
}

const DIFFICULTIES = ["foundation", "foundation", "foundation", "standard", "standard", "standard", "standard", "advanced", "advanced", "advanced", "transfer", "transfer"];

function skillQuestions(skillNumber, values) {
  if (values.length !== 12) throw new Error("ENG_R4_S" + skillNumber + ": expected 12 authored questions");
  return values.map((value, index) => ({ id: "ENG_R4_Q_" + skillNumber + "_" + String(index + 1).padStart(2, "0"), skillId: "ENG_R4_S" + skillNumber, difficulty: DIFFICULTIES[index], ...value }));
}

export const ENGLISH_U27_LECTURES = [
  lecture("ENG_R4_L_S183", "ENG_R4_S183", {
    objectives: ["辨認受詞是接受影響或執行後續動作的人。", "依第一個動詞判斷後續應接原形動詞、to 加原形或 V-ing。"],
    sections: [
      { title: "先找第一個動詞，再分配人物角色", content: "在 The joke made Amy laugh 中，made 是句子的主要動詞，Amy 是受到笑話影響的人，也是 laugh 的執行者。受詞不是多餘的人名；它把前面的原因和後面的動作連起來。" },
      { title: "不同動詞要求不同的後續形式", content: "make、have、let 後常用受詞加原形動詞，例如 made us wait。ask、tell、want 後用受詞加 to V，例如 told us to wait。see、hear、watch 等感官動詞則可依語意使用原形或 V-ing。" },
      { title: "時態通常落在第一個動詞", content: "The teacher made us stay、The teacher will make us stay 和 The teacher does not make us stay 都保留 stay 原形。過去、未來或否定由 made、will make、does not make 表示，不要再把後面的動詞也改成過去式。" },
      { title: "形式正確仍要核對句意", content: "made Leo leave 表示使 Leo 離開，let Leo leave 表示允許 Leo 離開，told Leo to leave 表示告知或指示 Leo 離開。三句的執行者都是 Leo，但前一個動詞所表達的關係不同，不能只靠看到 leave 就判斷。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S183_EX_01", prompt: "The joke made us laugh. Who laughed?", steps: ["找出 made 後的受詞。", "找出受詞後的動作。", "把受詞和動作配成事件。"], answer: "We laughed.", why: "made 後的 us 是受詞，也承接後面的 laugh，因此笑的人是 we。The joke 是造成笑的事物，不是執行 laugh 的人。" },
      { id: "ENG_R4_L_S183_EX_02", prompt: "Mia asked Leo to wait. Which words name Leo's action?", steps: ["定位 asked 的受詞 Leo。", "查看 Leo 後的不定詞。", "用不定詞說明 Leo 要做的事。"], answer: "to wait", why: "ask + person + to V 中，person 執行 to V。Leo 是被請求的人，to wait 才是他被請求執行的動作。" },
      { id: "ENG_R4_L_S183_EX_03", prompt: "I saw Amy crossing the street. What was Amy doing?", steps: ["找出 saw 後的人物。", "辨認人物後的 V-ing。", "把進行中的動作還原成意思。"], answer: "She was crossing the street.", why: "Amy 是 saw 的受詞，crossing 描寫看見當時正在發生的動作。句子只支持看見過程中的一段，不保證看見完整路程。" },
    ],
    misconceptions: [
      { belief: "把第一個動詞的受詞當成只接受動作、不能執行後續動作的人。", whyWrong: "這類句型的受詞通常正是後續動詞的語意主詞。", correction: "將受詞和它後面的動作連起來判讀。" },
      { belief: "句子是過去式時，把兩個動詞都改成過去式。", whyWrong: "時態已由 made、had 等第一個動詞承擔。", correction: "依句型保留後續原形或不定詞形式。" },
      { belief: "make、let、tell 後面的人都接相同的動詞形式。", whyWrong: "tell 要接 person + to V，make 和 let 則接 person + 原形。", correction: "先辨認第一個動詞，再選它要求的結構。" },
      { belief: "只要句中有兩個人物，第二個人物就是整句主詞。", whyWrong: "整句主詞位於主要動詞前，後面人物通常是受詞。", correction: "分開標出整句主詞、主要動詞和受詞。" },
    ],
    checks: [
      { prompt: "The coach made us run 中，誰執行 run？", answer: "us 所代表的人", reason: "受詞 us 承接後面的原形動詞 run。" },
      { prompt: "told Amy to sit 中，哪一部分是 Amy 的動作？", answer: "to sit", reason: "tell + person + to V 指出該人物要做的事。" },
      { prompt: "made him stayed 是否正確？", answer: "不正確", reason: "made + object 後應接原形 stay。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S184", "ENG_R4_S184", {
    objectives: ["使用 make + 受詞 + 原形動詞表達使某人做某事。", "由句中證據區分造成結果、允許行動與口頭要求。"],
    sections: [
      { title: "make 把原因和後續行動連起來", content: "The loud noise made the baby cry 表示大聲噪音造成嬰兒哭。make 後先放受影響的人，再放原形動詞；baby 執行 cry，而 noise 是造成結果的原因。" },
      { title: "後面的動詞保持原形", content: "makes me laugh、made me laugh、will make me laugh 都使用 laugh。第三人稱、過去式與未來標記放在 make 上；寫成 makes me laughs 或 made me laughed 都把時態或人稱重複標記了。" },
      { title: "否定與問句也不改後續形式", content: "The rule does not make us stay 和 Did the rule make us stay? 都保留 make 與 stay 原形。助動詞 does 或 did 已承擔文法變化，受詞後不再加 to。" },
      { title: "make 不等於每次都強迫", content: "A sad song made Mia cry 可以表示歌曲引起反應，不必解讀成歌曲有意命令她。判斷使役關係時，要看主詞是人、事件或事物，再依上下文說明原因與結果。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S184_EX_01", prompt: "The funny story made Ben ___. (laugh / laughed)", steps: ["辨認 made 是使役動詞。", "找到受詞 Ben。", "在受詞後使用原形動詞。"], answer: "laugh", why: "made 已表示過去，Ben 後面只需原形 laugh。laughed 會在同一結構中重複標記過去式，所以不能放在此空格。" },
      { id: "ENG_R4_L_S184_EX_02", prompt: "What caused the window to shake? The wind made the window shake.", steps: ["找出 made 前的主詞。", "確認受影響的受詞。", "核對後續結果。"], answer: "The wind.", why: "The wind 是 made 的主詞，window 是受影響的物體，shake 是發生的結果。句子因此把風標示為造成窗戶搖動的原因。" },
      { id: "ENG_R4_L_S184_EX_03", prompt: "Does this sentence show permission? The cold weather made us stay inside.", steps: ["判斷 make 的基本關係。", "讀取 cold weather 造成的結果。", "比較 permission 與 cause。"], answer: "No. It shows a cause and result.", why: "寒冷天氣造成我們待在室內，句子沒有任何人給予選擇或許可。若要表達允許，通常會用 let，而不是此處的 made。" },
    ],
    misconceptions: [
      { belief: "在 made 後把第二個動詞也寫成過去式，形成 made me waited。", whyWrong: "made 已承擔過去時態，waited 破壞使役結構。", correction: "使用 made me wait。" },
      { belief: "認為 make 後一定要加 to，所以寫 make us to leave。", whyWrong: "主動句的 make + object 後直接接原形動詞。", correction: "寫成 make us leave。" },
      { belief: "看到 made 就一律解釋為某人下命令。", whyWrong: "天氣、聲音或消息也能自然造成反應。", correction: "依主詞與情境判斷是造成結果還是人的要求。" },
      { belief: "把受詞誤認為造成事件的人，例如把 baby 當成使哭聲發生的原因。", whyWrong: "make 前的主詞才是原因，受詞執行後續動作。", correction: "依序讀成 cause + make + person + action。" },
    ],
    checks: [
      { prompt: "made Leo clean 中，clean 要不要改成 cleaned？", answer: "不要", reason: "使役 make 的受詞後接原形動詞。" },
      { prompt: "The news made Amy smile 中，造成笑容的是什麼？", answer: "the news", reason: "news 是 made 前的主詞。" },
      { prompt: "doesn't make me worry 中，哪個詞承擔否定？", answer: "doesn't", reason: "後面的 worry 仍保持原形。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S185", "ENG_R4_S185", {
    objectives: ["使用 have + 受詞 + 原形動詞表達安排或請某人執行。", "區分 have someone do、have to do 與一般擁有的 have。"],
    sections: [
      { title: "have 可表示安排某人做事", content: "The teacher had Leo read the first page 表示老師安排 Leo 朗讀。Leo 是受詞，也是 read 的執行者；read 使用原形，因為過去時態已由 had 表示。" },
      { title: "時態與助動詞放在 have 上", content: "She has Ben check the list、She had Ben check the list 和 She will have Ben check the list 都保留 check 原形。若有 does、did 或 will，have 也依助動詞回到原形。" },
      { title: "have someone do 不等於 have to do", content: "I had Sam carry the box 是我安排 Sam 搬箱子；I had to carry the box 是我必須自己搬。前者在 have 後有一個人作受詞，後者直接以 to V 表示必要性，人物角色不能互換。" },
      { title: "安排不必推論成強迫", content: "The coach had us meet at six 只明示教練安排集合。沒有更多情境時，不能斷言隊員是自願、被強迫或已經喜歡這個安排；閱讀時只保留句子確實提供的關係。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S185_EX_01", prompt: "Dad had Mia ___ the map. (check / checked)", steps: ["辨認 had 的使役用法。", "找出受詞 Mia。", "在受詞後選原形。"], answer: "check", why: "had 已交代安排發生在過去，Mia 後的動作使用原形 check。checked 會把過去形式錯放到第二個動詞。" },
      { id: "ENG_R4_L_S185_EX_02", prompt: "I had to wash the cups. Did I arrange another person to wash them?", steps: ["查看 had 後是否有人物受詞。", "辨認 had to 的必要性。", "判斷真正執行者。"], answer: "No. I needed to wash them myself.", why: "had 後立刻接 to wash，沒有另一個人物受詞，因此這是 have to 的過去式。洗杯子的人是 I，不是被安排的另一個人。" },
      { id: "ENG_R4_L_S185_EX_03", prompt: "The manager will have Ben call Amy. Who will make the call?", steps: ["找出 have 後的受詞。", "把受詞連到 call。", "排除安排者與接電話者。"], answer: "Ben.", why: "Ben 位於 have 與 call 之間，是被安排執行 call 的人。manager 負責安排，Amy 是電話的接收者，都不是撥電話的人。" },
    ],
    misconceptions: [
      { belief: "把 had someone do 和 had to do 都解讀成必須自己做。", whyWrong: "someone 的出現建立了另一位執行者。", correction: "先看 have 後是人物受詞還是 to。" },
      { belief: "寫成 had Amy to check，將 have 和 ask 的結構混在一起。", whyWrong: "此使役 have 的受詞後接原形，不接 to。", correction: "使用 had Amy check。" },
      { belief: "把安排者當成後續動作的執行者。", whyWrong: "have 後的受詞才執行原形動詞。", correction: "分別標出安排者、受詞和行動。" },
      { belief: "由 had us meet 直接推論每個人都不願意出席。", whyWrong: "句型只提供安排，沒有說明每個人的態度。", correction: "不把未明示的意願加入句意。" },
    ],
    checks: [
      { prompt: "will have Nora bring the key 中，誰帶鑰匙？", answer: "Nora", reason: "Nora 是 have 的受詞，也是 bring 的執行者。" },
      { prompt: "had to leave 中是否有被安排的另一個人？", answer: "沒有", reason: "這是 had to 表示必須離開。" },
      { prompt: "has Ben checks 是否正確？", answer: "不正確", reason: "受詞 Ben 後應接原形 check。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S186", "ENG_R4_S186", {
    objectives: ["使用 let + 受詞 + 原形動詞表達允許。", "處理 let 句型中的否定、受格代名詞與 Let's 的不同功能。"],
    sections: [
      { title: "let 表示讓某人可以做某事", content: "Dad let me use his bike 表示爸爸允許我使用腳踏車。me 是受詞，也是 use 的執行者；let 後不加 to，代名詞要用 me、him、her、us、them 等受格。" },
      { title: "let 的形式不因過去式改變", content: "let 的原形和過去式拼法相同。Yesterday Dad let me stay late 中，yesterday 與上下文說明過去時間；不能寫 let me stayed，也不能用 leted。" },
      { title: "否定放在 let 前或行動前", content: "Mom did not let us go 表示媽媽不允許我們去；Mom let us not go 在一般國中語境較少用且意思不同。基本題型以 did not let + object + base verb 表達不允許最清楚。" },
      { title: "Let's 是提出共同建議", content: "Let's take a break 是 let us 的固定縮寫用法，常用來提議說話者和聽話者一起休息。它和 Dad let us take a break 的允許句不同：後者有明確允許者 Dad，前者是說話者提出建議。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S186_EX_01", prompt: "The teacher let us ___ early. (leave / to leave)", steps: ["辨認 let 是允許動詞。", "找到受詞 us。", "在受詞後使用原形。"], answer: "leave", why: "let + object 後直接接原形 leave，不使用 to leave。us 表示獲得允許的人，也是實際離開的人。" },
      { id: "ENG_R4_L_S186_EX_02", prompt: "Yesterday, Amy let Ben use the phone. What shows the past time?", steps: ["查看時間詞。", "注意 let 的拼法沒有改變。", "用上下文判定時態。"], answer: "Yesterday.", why: "let 的過去式仍寫 let，所以單看拼法無法區分時態。Yesterday 明確把允許使用電話的事件放在過去。" },
      { id: "ENG_R4_L_S186_EX_03", prompt: "Does Let's walk home mean that another person gave permission?", steps: ["辨認 Let's 的縮寫。", "判斷句子的溝通功能。", "查看是否有外部允許者。"], answer: "No. It is a suggestion to walk together.", why: "Let's 在此提出一起走回家的建議，句中沒有爸爸、老師等外部人物給予許可。不能只因看到 let 就把功能判成允許。" },
    ],
    misconceptions: [
      { belief: "在 let 後固定加入 to，寫成 let him to go。", whyWrong: "let 的主動結構要求受詞後接原形動詞。", correction: "改為 let him go。" },
      { belief: "把 he、she、they 直接放在 let 後。", whyWrong: "let 後的位置是受詞，要使用受格代名詞。", correction: "分別使用 him、her、them。" },
      { belief: "認為 let 的過去式必須加 -ed。", whyWrong: "let 是原形、過去式同形的動詞。", correction: "由時間詞和上下文判斷時態。" },
      { belief: "把所有 Let's 句都解釋成某人允許我們做事。", whyWrong: "Let's 通常是說話者提出共同建議。", correction: "查看句中是否另有明確允許者。" },
    ],
    checks: [
      { prompt: "let her sing 中，為何用 her？", answer: "因為她位於受詞位置", reason: "let 後先接受詞，再接原形動詞。" },
      { prompt: "didn't let us entered 是否正確？", answer: "不正確", reason: "didn't 後用 let，受詞後用 enter。" },
      { prompt: "Let's eat 表示什麼功能？", answer: "提出一起吃東西的建議", reason: "Let's 常用於共同建議。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S187", "ENG_R4_S187", {
    objectives: ["依感官動詞後的原形與 V-ing 判斷看見或聽見的動作範圍。", "避免把觀察到的一段過程誤寫成已完成的全部事件。"],
    sections: [
      { title: "感官動詞後先放被觀察者", content: "I saw Ben cross the street 和 I saw Ben crossing the street 都以 Ben 為 saw 的受詞，也是 cross 的執行者。代名詞放在此處時使用 him、her、us、them 等受格。" },
      { title: "原形常呈現較完整的動作", content: "I watched Amy open the box 常表示看見她完成開盒這個動作。原形可把事件視為一個整體；不過仍應依上下文判斷，不能把句子沒有提供的前因後果一併補上。" },
      { title: "V-ing 強調觀察當時正在進行", content: "I saw Amy opening the box 聚焦於看見她正在開盒的過程，不必表示看見盒子最後完全打開。V-ing 回答的是觀察當時在做什麼，而不是自動保證動作完成。" },
      { title: "hear、see、watch 要配合可感知證據", content: "heard Leo sing 表示聽到 Leo 唱歌，saw the door close 表示看見門關上。若只知道別人轉述，就不能改寫成自己親眼看見或親耳聽見；感官動詞帶有證據來源的限制。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S187_EX_01", prompt: "I watched Sam carry the box into the room. Did I see the whole action?", steps: ["找出 watched 後的形式。", "辨認 carry 是原形。", "判斷事件呈現範圍。"], answer: "Yes, the sentence presents the action as a whole.", why: "carry 使用原形，且 into the room 提供終點，因此句子把搬箱子進房間視為完整事件。若只看到過程，常會使用 carrying。" },
      { id: "ENG_R4_L_S187_EX_02", prompt: "Mia saw Leo running in the park. Must Leo have finished his run?", steps: ["確認 running 是 V-ing。", "讀取觀察發生時的畫面。", "排除未明示的完成結果。"], answer: "No.", why: "running 只說明 Mia 看見時 Leo 正在跑。句子沒有提供開始或結束時間，因此不能斷言他已完成整段跑步。" },
      { id: "ENG_R4_L_S187_EX_03", prompt: "We heard her play the song from start to finish. Which form fits the complete event?", steps: ["找出 from start to finish。", "判斷事件被完整聽見。", "選感官動詞後的原形。"], answer: "play", why: "from start to finish 明確表示整首歌都被聽見，因此用原形 play 將演奏視為完整事件。her 是 heard 的受詞，也是 play 的執行者。" },
    ],
    misconceptions: [
      { belief: "把 see someone V-ing 一律解釋成看見動作完成。", whyWrong: "V-ing 聚焦進行中的片段，未必包含終點。", correction: "只推論觀察當時動作正在發生。" },
      { belief: "在 saw 後用主格代名詞 she 或 he。", whyWrong: "感官動詞後的人物位於受詞位置。", correction: "使用 her 或 him，再接原形或 V-ing。" },
      { belief: "認為原形和 V-ing 只是拼字差異，意思完全相同。", whyWrong: "兩者常分別呈現整體事件與進行片段。", correction: "用時間線索和完成證據選擇形式。" },
      { belief: "聽別人說過某事，就改寫成 I saw 或 I heard。", whyWrong: "感官動詞表示直接感知，轉述不等於親自看見或聽見。", correction: "保留訊息來源，不製造直接證據。" },
    ],
    checks: [
      { prompt: "saw him crossing 是否保證他已到對面？", answer: "不保證", reason: "crossing 只呈現正在進行的片段。" },
      { prompt: "heard them sing 中為何用 them？", answer: "them 是 heard 的受詞", reason: "受詞同時執行 sing。" },
      { prompt: "from start to finish 較支持原形還是 V-ing？", answer: "原形", reason: "這個線索把動作呈現為完整事件。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S188", "ENG_R4_S188", {
    objectives: ["正確使用 ask、tell、want + 受詞 + to V。", "依請求、指示與希望的語意選擇第一個動詞。"],
    sections: [
      { title: "ask someone to do 表達請求", content: "Mia asked Leo to wait 表示 Mia 請 Leo 等待。Leo 是被請求的人，也是 wait 的執行者。若 ask 用來詢問資訊，則可能接 a question、if 或疑問詞，不一定出現 to V。" },
      { title: "tell someone to do 表達告知或指示", content: "The teacher told us to open our books 指出老師要求我們打開書。tell 後的受詞不可省略成 told to open，也不能寫 told us open；基本結構需要 person + to V。" },
      { title: "want someone to do 表達希望另一人行動", content: "I want Ben to join us 表示 I 希望 Ben 加入。若寫 I want to join，則加入的人變成 I。是否有受詞會改變後續動作的執行者。" },
      { title: "否定放在 to 前保留禁止或不希望", content: "Dad told me not to touch it 和 Dad wants me not to touch it 都以 not to V 否定後續行動。第一句較像指示，第二句表達希望；不能改成 did not touch，因為那會變成已發生事實。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S188_EX_01", prompt: "Nora asked Ben ___ the door. (to close / close)", steps: ["辨認 asked 後有人物受詞。", "確認 Ben 是執行者。", "在受詞後使用 to V。"], answer: "to close", why: "ask + person + to V 表示請某人做事，因此 Ben 後應接 to close。只放 close 會漏掉此句型要求的不定詞標記。" },
      { id: "ENG_R4_L_S188_EX_02", prompt: "The coach told us not to leave. What were we told to avoid?", steps: ["找出 told 的受詞 us。", "定位 not to 後的動作。", "將否定套在 leave 上。"], answer: "Leaving.", why: "not to leave 否定 us 要執行的後續動作，所以教練要求我們不要離開。它不是在陳述我們已經沒有離開。" },
      { id: "ENG_R4_L_S188_EX_03", prompt: "I want Amy to call Leo. Who should call Leo?", steps: ["找到 want 後的受詞 Amy。", "把 Amy 連到 to call。", "區分說話者與動作執行者。"], answer: "Amy.", why: "Amy 位於 want 與 to call 之間，因此她是預期撥電話的人。I 表達希望，Leo 則是電話的接收者。" },
    ],
    misconceptions: [
      { belief: "在 ask、tell、want 的受詞後直接接原形動詞。", whyWrong: "這三種基本結構需要 person + to V。", correction: "寫 asked me to wait、told me to wait、wanted me to wait。" },
      { belief: "省略 tell 後的受詞，寫成 The teacher told to open the book。", whyWrong: "句子沒有交代誰接受指示並執行動作。", correction: "補出 told us to open 等明確受詞。" },
      { belief: "把 I want Ben to go 解讀成 I 要去。", whyWrong: "Ben 是 to go 的語意主詞。", correction: "由 want 後是否有人物受詞判斷執行者。" },
      { belief: "把 told me not to call 改成 told me did not call。", whyWrong: "後者把尚待遵守的指示誤成過去事實。", correction: "使用 not to + 原形保留否定指示。" },
    ],
    checks: [
      { prompt: "asked her to come 中，誰來？", answer: "her 所代表的人", reason: "受詞 her 承接 to come。" },
      { prompt: "want to read 和 want Leo to read 的執行者相同嗎？", answer: "不同", reason: "前者是主詞，後者是 Leo。" },
      { prompt: "told us wait 是否完整？", answer: "不完整", reason: "tell + object 後應接 to wait。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S189", "ENG_R4_S189", {
    objectives: ["依主要動詞建立完整且不重複的受詞補語結構。", "在多人物句中追蹤要求者、受詞、執行者與接收者。"],
    sections: [
      { title: "每個句型只放一次必要角色", content: "The teacher made us read 中，us 同時是 made 的受詞和 read 的執行者，不需再寫 made us we read。The teacher told us to read 則需要 to，但也不重複 us。" },
      { title: "由主要動詞選擇 bare V 或 to V", content: "make、have、let 接 object + bare V；ask、tell、want 接 object + to V。感官動詞可接 object + bare V 或 V-ing。若先決定主要動詞，就能避免把兩種結構拼成 made me to go 或 told me go。" },
      { title: "代名詞形式跟句中位置走", content: "She made him wait、She told him to wait、She saw him waiting 都用 him，因為他位於第一個動詞後的受詞位置。雖然 him 執行 wait，英文形式仍是受格而非 he。" },
      { title: "角色完整不代表可以補寫事實", content: "Amy had Ben call Nora 只表示 Amy 安排 Ben 打電話給 Nora。句子沒有保證 Nora 接聽、同意或完成任何後續行動。檢查結構之外，也要限制推論在明示證據內。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S189_EX_01", prompt: "Repair: The rain made us we stay inside.", steps: ["找出 made 的受詞 us。", "確認 us 已是 stay 的執行者。", "刪除重複主格 we。"], answer: "The rain made us stay inside.", why: "us 已同時連接 made 和 stay，再放 we 會重複同一角色並破壞結構。保留 made + us + stay 即完整表達雨使我們待在室內。" },
      { id: "ENG_R4_L_S189_EX_02", prompt: "Repair: Dad told to clean the table.", steps: ["辨認 tell 需要接收指示的人。", "補上適當受詞。", "保留受詞後的 to V。"], answer: "Dad told me to clean the table.", why: "原句缺少誰要清理桌子。加入 me 後，Dad 是指示者，me 是 told 的受詞，也是 to clean 的執行者。" },
      { id: "ENG_R4_L_S189_EX_03", prompt: "Amy had Ben call Nora. Did the sentence say Nora answered?", steps: ["標出安排者 Amy。", "確認 Ben 執行 call。", "檢查是否提供接聽結果。"], answer: "No.", why: "句子只交代 Amy 安排 Ben 撥電話給 Nora，沒有 answered 或其他接聽證據。結構完整也不能證明電話已被接起。" },
    ],
    misconceptions: [
      { belief: "在受詞後再加同一人的主格，寫成 let him he leave。", whyWrong: "him 已是 leave 的語意主詞，he 造成角色重複。", correction: "保留 let him leave。" },
      { belief: "省略 tell 或 ask 後的人物，只留下 to V。", whyWrong: "基本結構缺少接受指示或請求的人。", correction: "補出 tell/ask + object + to V。" },
      { belief: "把 make 和 tell 的形式混合成 made me to wait。", whyWrong: "主動 make 的受詞後不使用 to。", correction: "依主要動詞選 made me wait 或 told me to wait。" },
      { belief: "從 call someone 推論對方已接聽並同意。", whyWrong: "撥電話和接聽、同意是不同事件。", correction: "只保留題幹明示的動作與結果。" },
    ],
    checks: [
      { prompt: "made her she laugh 多了哪個詞？", answer: "she", reason: "her 已承接 laugh，不需再放主格。" },
      { prompt: "told to wait 缺少哪種角色？", answer: "接受指示的受詞", reason: "tell 的基本結構需要 person + to V。" },
      { prompt: "had Leo send a message 是否證明訊息被讀取？", answer: "不能證明", reason: "send 與 read 是不同事件。" },
    ], assets: [],
  }),
];

export const ENGLISH_U27_QUESTIONS = [
  ...skillQuestions("183", [
    { stem: "The coach made us run. Which word names the people who ran?", options: ["us", "coach", "made", "the"], answerIndex: 0, reasons: ["us 是 made 的受詞，也是 run 的執行者。", "coach 是造成或要求跑步的人。", "made 是主要動詞。", "the 只是限定 coach。"], reviews: ["將受詞 us 連到後續原形 run。", "第一項是唯一代表跑步者的選項。"], cognitiveProcess: ["u27-s183-link-make-object-us-to-runner", "identify-semantic-subject-of-bare-verb"], representationType: "causative-role-identification", misconceptionTargets: ["treat-main-subject-as-second-verb-agent"] },
    { stem: "Mia asked Leo to wait near the gate. What was Leo asked to do?", options: ["Ask Mia a question", "Wait near the gate", "Open the gate", "Leave before Mia"], answerIndex: 1, reasons: ["Mia 是提出請求的人，不是 Leo 要詢問的對象。", "to wait near the gate 是 Leo 被請求執行的完整行動。", "gate 是等待地點，句中沒有要求開門。", "題幹沒有要求 Leo 離開，也沒有 before。"], reviews: ["把 Leo 後的不定詞和地點一起讀取。", "第二項保留人物、動作與位置。"], cognitiveProcess: ["u27-s183-recover-leo-gate-wait-request", "map-object-infinitive-to-complete-requested-action"], representationType: "requested-action-recovery", misconceptionTargets: ["treat-location-noun-as-commanded-action"] },
    { stem: "I heard Sam singing. What was Sam doing when I heard him?", options: ["Listening to me", "Ending every song", "Singing", "Asking a question"], answerIndex: 2, reasons: ["I 是聽見的人，不是 Sam 聽我。", "singing 不保證每首歌已唱完。", "V-ing 明示 Sam 當時正在唱。", "句中沒有 ask。"], reviews: ["將 heard 的受詞 Sam 與 singing 連起來。", "第三項不加入完成結果。"], cognitiveProcess: ["u27-s183-read-heard-object-ing-event", "infer-observed-ongoing-action-without-completion"], representationType: "perception-event-interpretation", misconceptionTargets: ["reverse-perceiver-and-performer"] },
    { stem: "The joke made Amy laugh. Who received the effect of the joke?", options: ["The joke", "Made", "Laugh", "Amy"], answerIndex: 3, reasons: ["joke 是造成效果的事物。", "made 是連接原因與結果的動詞。", "laugh 是結果動作。", "Amy 位於 made 後，是受影響並笑的人。"], reviews: ["受詞位於 make 與後續動作之間。", "第四項同時符合位置和語意。"], cognitiveProcess: ["u27-s183-identify-amy-as-affected-object", "distinguish-cause-object-and-result"], representationType: "cause-effect-role-map", misconceptionTargets: ["choose-cause-as-affected-person"] },
    { stem: "Dad let me use his bike. Which form follows the object me?", options: ["use", "to use", "used", "using to"], answerIndex: 0, reasons: ["let + object 後接原形 use。", "主動 let 結構不加 to。", "used 錯把時態放在第二個動詞。", "using to 不是此句型。"], reviews: ["先以 let 決定動詞形式。", "第一項是未加 to 的原形。"], cognitiveProcess: ["u27-s183-select-bare-use-after-let-object", "apply-governing-verb-complement-form"], representationType: "object-complement-form-cloze", misconceptionTargets: ["add-to-after-let"] },
    { stem: "Nora told Ben ___ near the door.", options: ["wait", "to wait", "waited", "waiting him"], answerIndex: 1, reasons: ["tell + person 後不能只接原形。", "told Ben to wait 是完整結構。", "waited 會誤成過去事件片段。", "waiting him 形式與角色都不合。"], reviews: ["Ben 是 told 的受詞，也是 wait 的執行者。", "第二項保留 tell 要求的 to V。"], cognitiveProcess: ["u27-s183-insert-to-wait-after-told-ben", "contrast-tell-frame-with-bare-verb-causatives"], representationType: "tell-complement-cloze", misconceptionTargets: ["use-bare-verb-after-tell"] },
    { stem: "We saw Leo cross the street. Who crossed the street?", options: ["We", "The street", "Leo", "No one"], answerIndex: 2, reasons: ["We 是看見動作的人。", "street 是 cross 的地點目標。", "Leo 是 saw 的受詞，也是 cross 的執行者。", "句中明示有人過街。"], reviews: ["感官動詞後的受詞可承接後續原形。", "第三項沒有把觀察者誤當行動者。"], cognitiveProcess: ["u27-s183-resolve-leo-as-cross-agent", "map-perception-object-to-embedded-action"], representationType: "perception-agent-question", misconceptionTargets: ["assign-crossing-to-observer"] },
    { stem: "The teacher had us open our books. Which pattern appears?", options: ["verb + to + object", "object + past verb", "question word + clause", "have + object + base verb"], answerIndex: 3, reasons: ["句中沒有 have to。", "open 不是過去式。", "句中沒有疑問詞。", "had + us + open 是 have + object + base verb。"], reviews: ["忽略時態差異後，had 對應 have。", "第四項正確描述三個相鄰成分。"], cognitiveProcess: ["u27-s183-classify-had-us-open-frame", "abstract-surface-sentence-into-complement-pattern"], representationType: "sentence-pattern-classification", misconceptionTargets: ["confuse-had-object-with-have-to"] },
    { stem: "A sad song ___ Mia cry, but her friend ___ her choose a new song.", options: ["made / let", "let / made", "told / made", "asked / let"], answerIndex: 0, reasons: ["歌曲造成哭泣用 made，朋友允許選歌用 let。", "歌曲不是允許者，朋友也未造成她選歌。", "told 需接 Mia to cry。", "asked 需接 Mia to cry。"], reviews: ["用主詞性質和情境區分 cause 與 permission。", "第一項兩個空格的形式與語意都成立。"], cognitiveProcess: ["u27-s183-contrast-made-cause-with-let-permission", "select-governing-verbs-from-two-event-roles"], representationType: "paired-causative-selection", misconceptionTargets: ["treat-make-and-let-as-synonyms"] },
    { stem: "The rule is make + object + base verb. Which line follows it?", options: ["The noise made to wake the baby.", "The noise made the baby wake.", "The noise made the baby to wake.", "The noise made the baby was wake."], answerIndex: 1, reasons: ["第一項把 to 放在受詞前且缺少正確結構。", "made + the baby + wake 完整符合規則。", "make 的受詞後不加 to。", "was wake 不能直接放在 made 的受詞後。"], reviews: ["四項都保留相同情境，只比較結構。", "第二項有受詞且後接原形。"], cognitiveProcess: ["u27-s183-apply-explicit-make-frame-to-full-line", "reject-missing-object-to-and-finite-form-errors"], representationType: "rule-to-sentence-selection", misconceptionTargets: ["multiply-mark-complement-form"] },
    { stem: "I watched Ben carrying the chairs. Which fact is directly supported?", options: ["Ben had carried every chair before I arrived.", "I ordered Ben to carry the chairs.", "Ben was carrying chairs while I watched.", "The chairs carried Ben."], answerIndex: 2, reasons: ["carrying 不證明觀察前已完成全部。", "watched 不表示下命令。", "V-ing 直接支持觀察時正在搬。", "chairs 不是 carry 的執行者。"], reviews: ["只使用 watched + object + V-ing 的可見證據。", "第三項保留事件方向與時間範圍。"], cognitiveProcess: ["u27-s183-limit-inference-from-watched-carrying", "distinguish-direct-observation-from-command-and-completion"], representationType: "evidence-bound-perception-inference", misconceptionTargets: ["infer-completion-from-ing"] },
    { stem: "Which line needs to before the action because of its first verb?", options: ["The joke made us laugh.", "Dad let me leave.", "We saw Amy open it.", "The coach told us to practice."], answerIndex: 3, reasons: ["make + object 接原形。", "let + object 接原形。", "see + object 可接原形。", "tell + object 需要 to V。"], reviews: ["題目要求依第一個動詞決定形式。", "第四項的 told 是唯一要求 object + to V 的動詞。"], cognitiveProcess: ["u27-s183-sort-tell-from-bare-complement-verbs", "compare-complement-requirements-across-four-frames"], representationType: "governing-verb-form-sort", misconceptionTargets: ["generalize-one-form-to-all-two-verb-sentences"] },
  ]),
  ...skillQuestions("184", [
    { stem: "The funny film made us ___.", options: ["laugh", "to laugh", "laughed", "laughing to"], answerIndex: 0, reasons: ["made + us 後接原形 laugh。", "主動 make 不接 to laugh。", "made 已標示過去，不再用 laughed。", "laughing to 不是此結構。"], reviews: ["us 是受詞也是笑的人。", "第一項保留正確原形。"], cognitiveProcess: ["u27-s184-complete-film-made-us-laugh", "apply-bare-infinitive-after-past-make"], representationType: "make-result-cloze", misconceptionTargets: ["add-tense-to-second-verb"] },
    { stem: "Dad made Leo ___ his room before dinner.", options: ["cleaned", "clean", "to clean", "cleaning"], answerIndex: 1, reasons: ["cleaned 會重複過去形式。", "made Leo clean 是正確使役結構。", "主動 make 後不加 to。", "此處不是進行中的感官事件。"], reviews: ["before dinner 不改變補語形式。", "第二項是 base verb。"], cognitiveProcess: ["u27-s184-select-clean-after-made-leo", "ignore-time-adverb-when-form-is-governed-by-make"], representationType: "make-housework-cloze", misconceptionTargets: ["choose-ing-from-context-alone"] },
    { stem: "Which sentence uses make with an action after the object?", options: ["The rain made the road wet.", "The box is made of wood.", "The bell made the students leave.", "Amy made a cake."], answerIndex: 2, reasons: ["wet 是形容詞，不是後續動作。", "is made of 表示材質。", "students 後接原形 leave，符合目標結構。", "made a cake 表示製作蛋糕。"], reviews: ["同一動詞可有不同用法，需查看後續成分。", "第三項唯一呈現 make + object + action。"], cognitiveProcess: ["u27-s184-distinguish-causative-action-use-of-make", "separate-action-complement-from-adjective-material-and-create"], representationType: "polysemy-structure-discrimination", misconceptionTargets: ["classify-every-make-as-same-pattern"] },
    { stem: "Yesterday the teacher made us ___ after class.", options: ["to stay", "stayed", "staying", "stay"], answerIndex: 3, reasons: ["主動 made 後不加 to。", "yesterday 的過去已由 made 表示。", "V-ing 不符合 make 的此用法。", "stay 是受詞 us 後的原形。"], reviews: ["時間詞只決定 made 的時態。", "第四項不重複標記過去。"], cognitiveProcess: ["u27-s184-preserve-stay-base-under-yesterday-made", "place-past-tense-on-matrix-causative"], representationType: "past-causative-time-cloze", misconceptionTargets: ["copy-yesterday-past-onto-complement"] },
    { stem: "This song always makes me ___.", options: ["smile", "smiles", "to smile", "smiled"], answerIndex: 0, reasons: ["makes me 後接原形 smile。", "smiles 錯把第三人稱標記加到第二動詞。", "主動 make 不使用 to。", "always 不要求過去式。"], reviews: ["主詞 song 的第三人稱變化已在 makes。", "第一項是未變化原形。"], cognitiveProcess: ["u27-s184-hold-smile-base-after-third-person-makes", "avoid-duplicated-subject-agreement"], representationType: "present-habit-causative-cloze", misconceptionTargets: ["add-s-to-embedded-verb"] },
    { stem: "The new rule does not make students ___ on Saturday.", options: ["to come", "come", "came", "coming to"], answerIndex: 1, reasons: ["students 後的動作不使用 to come。", "does not make students come 結構完整。", "does 已承擔時態，不能用 came。", "coming to 不是此補語。"], reviews: ["否定助動詞不改變後續原形要求。", "第二項同時配合 does not make。"], cognitiveProcess: ["u27-s184-complete-negative-rule-make-students-come", "maintain-base-form-across-do-support"], representationType: "negative-causative-cloze", misconceptionTargets: ["past-form-after-do-support"] },
    { stem: "The loud sound made the baby wake up. What caused the waking?", options: ["The baby", "Wake up", "The loud sound", "A teacher not named here"], answerIndex: 2, reasons: ["baby 是受到影響並醒來的人。", "wake up 是結果。", "loud sound 是 made 前的原因主詞。", "題幹沒有 teacher。"], reviews: ["依 cause + made + person + action 讀取角色。", "第三項是唯一明示原因。"], cognitiveProcess: ["u27-s184-trace-waking-cause-to-loud-sound", "read-causal-agent-from-make-subject"], representationType: "causative-source-question", misconceptionTargets: ["confuse-affected-person-with-cause"] },
    { stem: "Amy saw that the door was open when she arrived. Which statement is not supported?", options: ["Amy saw an open door.", "The door was already open at that time.", "Someone may have opened it before Amy arrived.", "Amy made Ben open the door."], answerIndex: 3, reasons: ["saw that the door was open 直接支持她看見開著的門。", "when she arrived 表示她到達時門已開著。", "may 表示可能，沒有斷言是誰。", "題幹沒有 Ben，也沒有 Amy 造成開門的證據。"], reviews: ["不能只因練習 make 就把使役事件補進情境。", "第四項加入兩個未明示角色與因果。"], cognitiveProcess: ["u27-s184-reject-unsupported-made-ben-statement", "separate-state-evidence-from-invented-causation"], representationType: "causative-evidence-limit", misconceptionTargets: ["invent-cause-from-result-state"] },
    { stem: "One more joke may ___ everyone laugh.", options: ["make", "makes", "made", "making"], answerIndex: 0, reasons: ["may 後接原形 make，make 後再接 everyone laugh。", "modal 後不能用 makes。", "may 後不能用 made。", "may 後不能直接用 making。"], reviews: ["此題同時有 may + make 與 make + object + base verb。", "第一項保留兩層原形要求。"], cognitiveProcess: ["u27-s184-stack-modal-base-with-causative-frame", "coordinate-two-base-form-constraints"], representationType: "modal-causative-cloze", misconceptionTargets: ["inflect-make-after-modal"] },
    { stem: "Change only the wrong verb: The cold wind made my eyes watered.", options: ["made → make", "watered → water", "my → mine", "eyes → eyeing"], answerIndex: 1, reasons: ["主詞與過去情境可保留 made。", "made + object 後應接原形 water。", "my 正確修飾 eyes。", "eyeing 不是此處名詞形式。"], reviews: ["錯誤集中在受詞後的動詞。", "第二項修正後不改變原意。"], cognitiveProcess: ["u27-s184-edit-embedded-watered-to-water", "locate-overinflected-causative-complement"], representationType: "single-error-causative-edit", misconceptionTargets: ["repair-correct-matrix-tense"] },
    { stem: "A sudden message made Leo leave the meeting. What does the sentence mean?", options: ["Leo allowed the message to leave.", "The meeting asked Leo a question.", "The message caused Leo to leave.", "Leo made the message at home."], answerIndex: 2, reasons: ["Leo 不是允許 message 離開。", "meeting 不能由題幹推出發問。", "made 在此連接 message 與 Leo leave 的因果。", "句中 made 不是製作訊息。"], reviews: ["用主詞 message 的性質判斷自然因果。", "第三項保留角色與事件方向。"], cognitiveProcess: ["u27-s184-paraphrase-message-caused-leo-to-leave", "interpret-inanimate-cause-with-make"], representationType: "causative-meaning-paraphrase", misconceptionTargets: ["read-make-only-as-create"] },
    { stem: "The alarm made Mia wake, but it did not make her get up. What happened?", options: ["Mia got up before the alarm.", "Mia never heard anything.", "The alarm made another person wake.", "Mia did wake, but the sentence does not say she got up."], answerIndex: 3, reasons: ["題幹沒有說起床發生在鬧鐘前。", "wake 表示鬧鐘確實造成她醒來。", "受詞是 Mia/her，同一人。", "第一個結果成立，第二個結果被否定。"], reviews: ["分開讀兩個 make 子句，不把 wake 與 get up 視為同義。", "第四項保留明示差異。"], cognitiveProcess: ["u27-s184-integrate-positive-wake-negative-get-up", "track-two-distinct-causative-results"], representationType: "paired-result-logic", misconceptionTargets: ["collapse-wake-and-get-up"] },
  ]),
  ...skillQuestions("185", [
    { stem: "The teacher had Leo ___ the first page.", options: ["read", "to read", "reads", "reading to"], answerIndex: 0, reasons: ["had + Leo 後接原形 read。", "此使役 have 不接 to。", "reads 錯加第三人稱變化。", "reading to 不是此結構。"], reviews: ["Leo 是被安排朗讀的人。", "第一項保留 read 原形。"], cognitiveProcess: ["u27-s185-complete-had-leo-read", "apply-bare-verb-after-causative-have"], representationType: "have-read-cloze", misconceptionTargets: ["add-to-after-causative-have"] },
    { stem: "Mia has Ben ___ the list every morning.", options: ["checks", "check", "checked", "to checking"], answerIndex: 1, reasons: ["has 已配合 Mia，第二動詞不加 s。", "has Ben check 是正確安排結構。", "every morning 不要求 checked。", "to checking 形式錯誤。"], reviews: ["第三人稱標記只落在 has。", "第二項是受詞後的原形。"], cognitiveProcess: ["u27-s185-keep-check-base-after-has-ben", "avoid-double-third-person-marking-in-have-frame"], representationType: "present-arrangement-cloze", misconceptionTargets: ["agree-embedded-verb-with-object"] },
    { stem: "We will have Nora bring the key. Who will bring it?", options: ["We", "The key", "Nora", "No one"], answerIndex: 2, reasons: ["We 是安排者。", "key 是被帶的物品。", "Nora 是 have 的受詞，也是 bring 的執行者。", "句中明示 Nora 將帶。"], reviews: ["將 Nora 與 bring 連成後續事件。", "第三項不把安排者當成執行者。"], cognitiveProcess: ["u27-s185-resolve-nora-as-key-bringer", "separate-arranger-agent-and-object"], representationType: "have-role-resolution", misconceptionTargets: ["assign-action-to-have-subject"] },
    { stem: "The coach did not have us ___ on Sunday.", options: ["to practice", "practiced", "practicing", "practice"], answerIndex: 3, reasons: ["have + object 後不加 to。", "did 已承擔過去，不能用 practiced。", "V-ing 不符合此安排結構。", "did not have us practice 正確。"], reviews: ["否定落在 did not have。", "第四項維持後續原形。"], cognitiveProcess: ["u27-s185-complete-negative-have-us-practice", "preserve-bare-complement-under-past-do-support"], representationType: "negative-arrangement-cloze", misconceptionTargets: ["inflect-second-verb-after-did"] },
    { stem: "I had Sam carry the box. Which role belongs to Sam?", options: ["The person arranged to carry it", "The box owner in every case", "The person who arranged the work", "The place where the box went"], answerIndex: 0, reasons: ["Sam 是 had 的受詞，也是 carry 的執行者。", "句子沒有交代所有權。", "I 才是安排者。", "Sam 是人，不是地點。"], reviews: ["只根據位置判定安排與執行角色。", "第一項不加入所有權。"], cognitiveProcess: ["u27-s185-label-sam-as-arranged-worker", "avoid-owner-inference-in-have-carry-frame"], representationType: "arrangement-role-label", misconceptionTargets: ["infer-object-ownership-from-agent"] },
    { stem: "I had to carry the box myself. Which statement is true?", options: ["Sam carried it for me.", "I needed to carry it.", "I had Sam carry it.", "The box carried me."], answerIndex: 1, reasons: ["句中沒有 Sam。", "had to 表示我必須執行 carry。", "原句沒有人物受詞置於 had 後。", "事件方向顛倒。"], reviews: ["myself 加強 I 是執行者。", "第二項與 have to 的必要性相符。"], cognitiveProcess: ["u27-s185-distinguish-had-to-from-had-someone", "identify-obligation-without-causative-object"], representationType: "have-to-contrast", misconceptionTargets: ["read-have-to-as-arrangement"] },
    { stem: "The manager had Amy call Ben. Which part names the receiver of the call?", options: ["The manager", "Amy", "Ben", "had"], answerIndex: 2, reasons: ["manager 是安排者。", "Amy 是撥電話的人。", "Ben 是 call 的對象。", "had 是安排動詞。"], reviews: ["三個人物角色需分別追蹤。", "第三項位於 call 後，接收電話。"], cognitiveProcess: ["u27-s185-identify-ben-as-call-recipient", "map-three-participant-causative-event"], representationType: "multi-participant-call-role", misconceptionTargets: ["confuse-arranged-agent-with-recipient"] },
    { stem: "The teacher had the students work in pairs. What can we safely know?", options: ["No student liked the plan.", "The teacher did all the work.", "The pairs chose the teacher.", "The teacher arranged for the students to work in pairs."], answerIndex: 3, reasons: ["句中沒有學生態度。", "students 才執行 work。", "題幹沒有選老師的事件。", "had + students + work 表示老師安排此活動。"], reviews: ["安排不自動表示強迫或喜好。", "第四項只重述明示關係。"], cognitiveProcess: ["u27-s185-limit-inference-from-class-pair-arrangement", "paraphrase-have-causative-without-attitude-statement"], representationType: "arrangement-evidence-inference", misconceptionTargets: ["infer-emotion-from-have-causative"] },
    { stem: "Tomorrow, Dad may have Leo ___ the car.", options: ["wash", "washes", "washed", "to wash"], answerIndex: 0, reasons: ["may 後用 have，have Leo 後用原形 wash。", "Leo 不控制 washes 的人稱變化。", "tomorrow 不要求 washed。", "此使役 have 後不加 to。"], reviews: ["同時檢查 modal + have 與 have + object + base verb。", "第一項符合兩層原形。"], cognitiveProcess: ["u27-s185-complete-modal-have-leo-wash", "coordinate-future-context-with-two-base-forms"], representationType: "modal-arrangement-cloze", misconceptionTargets: ["use-future-time-to-select-past-or-s-form"] },
    { stem: "Repair only the action form: The guide had us to follow the blue line.", options: ["had → has", "to follow → follow", "us → we", "line → lined"], answerIndex: 1, reasons: ["若情境在過去，had 可保留。", "使役 have 的受詞後用原形 follow。", "have 後需要受格 us。", "line 是正確名詞。"], reviews: ["題目只要求修正 action form。", "第二項移除多餘 to，不改角色。"], cognitiveProcess: ["u27-s185-remove-to-from-had-us-follow", "edit-only-governed-complement-form"], representationType: "focused-have-frame-edit", misconceptionTargets: ["replace-correct-object-pronoun"] },
    { stem: "The shop owner had Ben put the chairs outside before opening. What happened first?", options: ["The shop closed for the day.", "Customers took every chair.", "Ben put the chairs outside.", "Ben opened another shop."], answerIndex: 2, reasons: ["題幹沒有關店。", "沒有顧客拿椅子的資訊。", "before opening 表示搬椅子先發生。", "Ben 沒有開另一家店。"], reviews: ["結合 have 的角色與 before 的順序。", "第三項是唯一明示且較早的事件。"], cognitiveProcess: ["u27-s185-sequence-chair-task-before-opening", "integrate-arranged-action-with-time-order"], representationType: "arrangement-timeline", misconceptionTargets: ["invent-later-events-from-shop-context"] },
    { stem: "Amy had Leo send Nora a message. Which result is not certain?", options: ["Amy arranged the sending.", "Leo was the sender.", "Nora was the person meant to receive it.", "Nora read the message."], answerIndex: 3, reasons: ["Amy 是 had 的主詞，負責安排。", "Leo 是 send 的執行者。", "Nora 位於 send 後，是預定接收者。", "send 不保證訊息已被讀取。"], reviews: ["區分執行 send 與完成 read。", "第四項超出句子提供的結果。"], cognitiveProcess: ["u27-s185-mark-reading-as-uncertain-after-send", "audit-event-chain-for-unstated-outcome"], representationType: "arrangement-result-boundary", misconceptionTargets: ["equate-sent-with-read"] },
  ]),
  ...skillQuestions("186", [
    { stem: "The teacher let us ___ early.", options: ["leave", "to leave", "left", "leaving to"], answerIndex: 0, reasons: ["let + us 後接原形 leave。", "let 的主動結構不加 to。", "left 錯把過去式放在後續動詞。", "leaving to 形式錯誤。"], reviews: ["us 是獲得允許並離開的人。", "第一項符合 let + object + base verb。"], cognitiveProcess: ["u27-s186-complete-let-us-leave", "apply-permission-frame-with-bare-verb"], representationType: "let-permission-cloze", misconceptionTargets: ["add-to-after-let"] },
    { stem: "Dad let ___ use the camera.", options: ["I", "me", "my", "mine"], answerIndex: 1, reasons: ["I 是主格，不能放在 let 後受詞位置。", "me 是正確受格。", "my 需修飾名詞。", "mine 是所有格代名詞。"], reviews: ["空格同時承接 use 的執行者，但文法位置仍是受詞。", "第二項符合受格要求。"], cognitiveProcess: ["u27-s186-select-object-pronoun-me-after-let", "separate-semantic-agent-from-case-form"], representationType: "let-pronoun-case-cloze", misconceptionTargets: ["use-subject-case-for-embedded-agent"] },
    { stem: "Yesterday Amy let Ben use her phone. Which word places the event in the past?", options: ["use", "phone", "Yesterday", "her"], answerIndex: 2, reasons: ["use 保持原形。", "phone 是物品。", "Yesterday 明確表示過去時間。", "her 表示 phone 與 Amy 的關係。"], reviews: ["let 的過去式拼法不變。", "第三項是唯一時間線索。"], cognitiveProcess: ["u27-s186-locate-yesterday-as-let-past-marker", "infer-irregular-same-form-tense-from-context"], representationType: "let-tense-context-identification", misconceptionTargets: ["expect-visible-ed-on-let"] },
    { stem: "Mom did not let Leo ___ after ten.", options: ["to call", "called", "calling", "call"], answerIndex: 3, reasons: ["let 的受詞後不加 to。", "did 已承擔過去，不能用 called。", "calling 不符合此 permission frame。", "did not let Leo call 正確。"], reviews: ["不允許由 did not let 表達。", "第四項保留受詞後原形。"], cognitiveProcess: ["u27-s186-complete-negative-let-leo-call", "maintain-bare-verb-under-negative-permission"], representationType: "negative-permission-cloze", misconceptionTargets: ["past-form-after-did-not-let"] },
    { stem: "The rain stopped, so Dad let us play outside. What did Dad do?", options: ["He allowed us to play outside.", "He made the rain play.", "He asked outside a question.", "He played, and we did not."], answerIndex: 0, reasons: ["let us play 表示允許我們出去玩。", "rain 不是 play 的受詞。", "outside 是地點副詞，不是人物。", "us 才是 play 的執行者。"], reviews: ["用情境與 let 的基本功能判讀。", "第一項保留允許者和行動者。"], cognitiveProcess: ["u27-s186-paraphrase-dad-permission-after-rain", "interpret-let-with-causal-context"], representationType: "permission-meaning-paraphrase", misconceptionTargets: ["assign-action-to-let-subject"] },
    { stem: "Which line means that Mia received permission?", options: ["Mia made Ben leave.", "Ben let Mia stay.", "Mia told Ben to stay.", "Ben wanted to stay."], answerIndex: 1, reasons: ["Mia 是使 Ben 離開的人。", "Ben 是允許者，Mia 是獲准留下的人。", "Mia 發出指示，沒有獲得許可。", "Ben 表達自己的希望。"], reviews: ["題目要求找 Mia 作為 let 的受詞。", "第二項唯一把 permission 指向 Mia。"], cognitiveProcess: ["u27-s186-find-mia-as-permission-recipient", "contrast-let-object-with-make-and-tell-subject"], representationType: "permission-recipient-selection", misconceptionTargets: ["confuse-giver-and-receiver-of-permission"] },
    { stem: "Let's take a break. What is the speaker doing?", options: ["Reporting a past break", "Making another person stop", "Suggesting a break together", "Asking who owns the break"], answerIndex: 2, reasons: ["Let's 不報導過去。", "句子不是強迫某人停止。", "Let's + verb 常提出共同建議。", "沒有所有權問題。"], reviews: ["辨認 Let's 而非一般 let + object。", "第三項保留 together 的溝通功能。"], cognitiveProcess: ["u27-s186-interpret-lets-as-shared-suggestion", "distinguish-fixed-suggestion-from-permission"], representationType: "lets-function-identification", misconceptionTargets: ["read-lets-as-external-permission"] },
    { stem: "The sign says, 'Do not enter.' Did the sign let visitors enter?", options: ["Yes, because enter is a base verb.", "Yes, because every sign gives permission.", "The sentence gives no information about visitors.", "No, it told visitors not to enter."], answerIndex: 3, reasons: ["原形本身不代表允許。", "sign 可以禁止，不一定給許可。", "文字直接針對進入者。", "Do not enter 是禁止進入。"], reviews: ["不能只看 enter 形式而忽略溝通功能。", "第四項符合 sign 的明示內容。"], cognitiveProcess: ["u27-s186-reject-permission-reading-of-do-not-enter", "prioritize-negative-directive-over-base-form-shape"], representationType: "permission-versus-prohibition", misconceptionTargets: ["equate-base-verb-with-let-pattern"] },
    { stem: "Will the manager ___ the team leave early?", options: ["let", "lets", "letting", "let to"], answerIndex: 0, reasons: ["will 後接原形 let，後面再接 team leave。", "will 後不能用 lets。", "will 後不能直接用 letting。", "let 後不加 to。"], reviews: ["同時檢查 will + let 與 let + object + base verb。", "第一項滿足兩層形式。"], cognitiveProcess: ["u27-s186-complete-will-let-team-leave", "coordinate-modal-and-permission-base-forms"], representationType: "future-permission-cloze", misconceptionTargets: ["inflect-let-after-will"] },
    { stem: "Change only the pronoun: The teacher let they work together.", options: ["teacher → teachers", "they → them", "let → lets", "work → worked"], answerIndex: 1, reasons: ["teacher 可作單數主詞。", "let 後需受格 them。", "若為過去或原形 let，不需改 lets。", "受詞後的 work 應保持原形。"], reviews: ["題目指定只修 pronoun。", "第二項保留原本人物與動作。"], cognitiveProcess: ["u27-s186-edit-they-to-them-after-let", "repair-object-case-without-altering-correct-verbs"], representationType: "focused-pronoun-edit", misconceptionTargets: ["change-correct-bare-verb-during-case-repair"] },
    { stem: "Amy let Ben borrow her book until Friday. Which limit is stated?", options: ["Ben must buy the book on Friday.", "Amy cannot read any book.", "Ben may keep the book only until Friday.", "Friday allowed Amy to borrow Ben."], answerIndex: 2, reasons: ["題幹沒有購買。", "沒有說 Amy 不能閱讀。", "until Friday 限制借用期限。", "Friday 不是允許者，角色也顛倒。"], reviews: ["結合 let 的允許與 until 的時間邊界。", "第三項沒有擴大允許範圍。"], cognitiveProcess: ["u27-s186-derive-friday-limit-on-borrow-permission", "integrate-permission-with-end-point"], representationType: "permission-time-boundary", misconceptionTargets: ["ignore-until-limit"] },
    { stem: "Dad let Mia use the car, but Mia chose to walk. What is true?", options: ["Dad made Mia drive.", "Mia was not allowed to use the car.", "Mia drove and walked at the same time.", "Permission did not mean Mia had to use the car."], answerIndex: 3, reasons: ["let 表示允許，不是強迫。", "題幹明示 Dad let her use it。", "句子說她選擇走路。", "獲得允許不等於必須執行。"], reviews: ["區分 permission 與 actual choice。", "第四項能同時容納允許與未使用。"], cognitiveProcess: ["u27-s186-separate-car-permission-from-actual-choice", "reason-about-modal-possibility-without-actualization"], representationType: "permission-action-logic", misconceptionTargets: ["equate-being-allowed-with-doing"] },
  ]),
  ...skillQuestions("187", [
    { stem: "I saw Leo ___ the door from start to finish.", options: ["open", "to open", "opened", "opening to"], answerIndex: 0, reasons: ["完整事件線索支持 saw + object + base verb。", "感官動詞此結構不加 to。", "opened 不是 saw Leo 後的形式。", "opening to 形式錯誤。"], reviews: ["from start to finish 明示完整範圍。", "第一項將 open 視為整體動作。"], cognitiveProcess: ["u27-s187-select-open-for-complete-seen-event", "map-completion-cue-to-bare-perception-complement"], representationType: "complete-perception-cloze", misconceptionTargets: ["add-to-after-see"] },
    { stem: "Mia saw Ben ___ across the park when she looked out.", options: ["run", "running", "ran", "to running"], answerIndex: 1, reasons: ["run 可能呈現整體，但 when she looked out 強調當時畫面。", "running 描寫看見時正在跑。", "ran 不能直接接 saw Ben。", "to running 形式錯誤。"], reviews: ["題幹聚焦某一觀看時點。", "第二項最符合進行中的片段。"], cognitiveProcess: ["u27-s187-select-running-for-glimpse-in-park", "use-simultaneous-viewpoint-to-choose-ing"], representationType: "ongoing-perception-cloze", misconceptionTargets: ["use-past-form-after-saw-object"] },
    { stem: "We heard Nora sing the whole song. What did we hear?", options: ["Only the first sound", "A report about Nora", "The whole song", "Nora asking us to sing"], answerIndex: 2, reasons: ["whole song 排除只聽第一個聲音。", "heard 表示直接聽見，不是轉述。", "sing 原形配合 whole song 呈現完整表演。", "句中沒有請求。"], reviews: ["將 whole 與原形 sing 一起判讀。", "第三項不增加說話行為。"], cognitiveProcess: ["u27-s187-infer-whole-song-from-heard-sing", "combine-lexical-completion-with-bare-form"], representationType: "auditory-event-scope", misconceptionTargets: ["ignore-whole-event-marker"] },
    { stem: "I watched Amy painting when the lights went out. What is not certain?", options: ["I watched Amy.", "Amy was painting.", "The lights went out.", "Amy finished the painting."], answerIndex: 3, reasons: ["watched Amy 明示觀察。", "painting 明示當時活動。", "when 子句明示燈熄滅。", "V-ing 和中斷事件都不保證完成。"], reviews: ["題目要求找未獲支持的完成結果。", "第四項超出觀察範圍。"], cognitiveProcess: ["u27-s187-reject-finished-painting-after-interruption", "limit-conclusion-from-ing-and-lights-out"], representationType: "ongoing-event-completion-boundary", misconceptionTargets: ["infer-finish-from-observed-process"] },
    { stem: "Dad heard ___ playing the piano.", options: ["her", "she", "hers", "herself was"], answerIndex: 0, reasons: ["her 是 heard 後的受格，也承接 playing。", "she 是主格。", "hers 表示所有關係，不能作此受詞。", "herself was 破壞結構。"], reviews: ["語意上她彈琴，形式上仍位於受詞位置。", "第一項符合 object + V-ing。"], cognitiveProcess: ["u27-s187-select-her-before-playing", "apply-object-case-in-perception-frame"], representationType: "perception-pronoun-case", misconceptionTargets: ["use-subject-pronoun-before-ing"] },
    { stem: "Which line presents a complete action most clearly?", options: ["I saw Sam crossing the road when the bus came.", "I watched Sam cross the road from one side to the other.", "I heard Sam talking when I entered.", "I noticed Sam waiting at noon."], answerIndex: 1, reasons: ["crossing 與 when 子句聚焦進行片段。", "原形 cross 加完整起終點呈現整體。", "talking 是進行中的片段。", "waiting 只說明當時狀態。"], reviews: ["不是只看原形，還核對 from one side to the other。", "第二項的形式與語意線索一致。"], cognitiveProcess: ["u27-s187-choose-cross-with-explicit-endpoints", "compare-four-perception-event-spans"], representationType: "event-span-comparison", misconceptionTargets: ["treat-all-perception-complements-as-complete"] },
    { stem: "Leo told me that Amy was singing. Which statement would be too strong?", options: ["Leo gave me a report.", "The report was about Amy singing.", "I heard Amy with my own ears.", "Leo used words to share information."], answerIndex: 2, reasons: ["told me 支持 Leo 轉述。", "that 子句提供報導內容。", "題幹只說 Leo 告訴我，沒有我親耳聽見的證據。", "told 表示以話語傳遞資訊。"], reviews: ["區分 reported evidence 與 direct hearing。", "第三項把轉述升格成親身感知。"], cognitiveProcess: ["u27-s187-reject-own-hearing-from-told-report", "distinguish-hearsay-from-sensory-evidence"], representationType: "evidence-source-discrimination", misconceptionTargets: ["convert-report-to-direct-perception"] },
    { stem: "I saw Ben opening the window. Which later event may not have happened?", options: ["I saw Ben.", "Ben was doing something to the window.", "The action was in progress when seen.", "The window opened all the way."], answerIndex: 3, reasons: ["saw Ben 明示人物。", "opening 連到 window。", "V-ing 表示觀察時正在進行。", "句子未提供完成終點。"], reviews: ["opening 與 opened 的結果要分開。", "第四項可成立也可不成立，因此仍未知。"], cognitiveProcess: ["u27-s187-mark-all-the-way-open-result-as-uncertain", "separate-process-observation-from-result-state"], representationType: "process-result-distinction", misconceptionTargets: ["equate-opening-with-opened"] },
    { stem: "From my seat, I could see the train ___ the station and stop.", options: ["enter", "entered", "to enter", "entering to"], answerIndex: 0, reasons: ["enter and stop 呈現連續完整動作，用原形 enter。", "could see 後不能接 object + entered。", "此感官結構不加 to。", "entering to 不能與 stop 平行。"], reviews: ["stop 提供到站後的終點事件。", "第一項也與 stop 保持平行原形。"], cognitiveProcess: ["u27-s187-complete-train-enter-and-stop-sequence", "use-parallel-bare-verbs-for-observed-chain"], representationType: "perceived-action-sequence", misconceptionTargets: ["break-parallel-form-after-see"] },
    { stem: "Change only the object form: We watched they dance for an hour.", options: ["watched → watch", "they → them", "dance → danced", "hour → hourly"], answerIndex: 1, reasons: ["若事件在過去，watched 正確。", "watched 後的人物需受格 them。", "感官動詞後可用原形 dance。", "for an hour 是正確時間片語。"], reviews: ["題目指定 object form，不改其他正確部分。", "第二項修正格位並保留 dance。"], cognitiveProcess: ["u27-s187-edit-they-to-them-before-dance", "repair-case-in-bare-perception-frame"], representationType: "perception-case-edit", misconceptionTargets: ["alter-correct-event-form-during-pronoun-repair"] },
    { stem: "At 3:00, Mia saw Leo carrying boxes. At 3:10, the boxes were still outside. Which reading fits both facts?", options: ["Leo had finished every box before 3:00.", "Mia told Leo never to carry boxes.", "Mia saw part of the carrying process, which was not complete by 3:10.", "The boxes carried Leo inside."], answerIndex: 2, reasons: ["第一項和 3:10 的狀態衝突。", "saw 不是禁止。", "carrying 表示進行片段，3:10 仍在外支持尚未完成。", "事件角色顛倒。"], reviews: ["整合 V-ing 與後續時間證據。", "第三項沒有誇大 Mia 看見的範圍。"], cognitiveProcess: ["u27-s187-integrate-carrying-with-later-unfinished-state", "reason-across-observation-and-follow-up-evidence"], representationType: "perception-timeline-integration", misconceptionTargets: ["force-completion-despite-later-evidence"] },
    { stem: "Amy heard a door close, then found the room quiet. What does heard a door close support?", options: ["Amy saw who closed it.", "The door had always been closed.", "Amy ordered someone to close it.", "Amy heard the closing event, but the person is not named."], answerIndex: 3, reasons: ["heard 不提供視覺身分。", "一次 close 不表示 always。", "感知事件不是命令。", "door close 提供聲音事件，但沒有行動者姓名。"], reviews: ["原形呈現關門事件，不能補出未知人物。", "第四項同時保留直接聽見與身分限制。"], cognitiveProcess: ["u27-s187-infer-closing-with-unknown-agent", "extract-event-without-inventing-performer"], representationType: "auditory-agent-unknown", misconceptionTargets: ["infer-agent-from-sound-alone"] },
  ]),
  ...skillQuestions("188", [
    { stem: "Nora asked Ben ___ the door.", options: ["to close", "close", "closed", "closing him"], answerIndex: 0, reasons: ["ask + person 後接 to V。", "close 缺少 to。", "closed 把動作誤成過去形式。", "closing him 角色與形式錯誤。"], reviews: ["Ben 是被請求關門的人。", "第一項完成 person + to close。"], cognitiveProcess: ["u27-s188-complete-asked-ben-to-close", "apply-request-object-infinitive-frame"], representationType: "ask-request-cloze", misconceptionTargets: ["use-bare-verb-after-ask-object"] },
    { stem: "The teacher told us ___ page ten.", options: ["open", "to open", "opened", "opening to"], answerIndex: 1, reasons: ["tell + object 後不能只用原形。", "told us to open 結構正確。", "opened 會變成不完整過去片段。", "opening to 形式不合。"], reviews: ["us 是接受指示並開書的人。", "第二項保留 to V。"], cognitiveProcess: ["u27-s188-complete-told-us-to-open", "map-instruction-to-object-infinitive"], representationType: "tell-instruction-cloze", misconceptionTargets: ["omit-to-after-tell"] },
    { stem: "I want Amy to call Leo. Who should make the call?", options: ["I", "Leo", "Amy", "No one"], answerIndex: 2, reasons: ["I 是表達希望的人。", "Leo 是電話接收者。", "Amy 位於 want 與 to call 間，是執行者。", "句中明示預期有電話行動。"], reviews: ["由 object + to V 決定後續執行者。", "第三項不把主詞或接收者混入。"], cognitiveProcess: ["u27-s188-resolve-amy-as-wanted-caller", "trace-agent-through-want-object-infinitive"], representationType: "want-role-question", misconceptionTargets: ["assign-infinitive-action-to-want-subject"] },
    { stem: "Dad told me ___ the wet floor.", options: ["did not touch", "not touching", "not touch", "not to touch"], answerIndex: 3, reasons: ["did not touch 會變成過去事實。", "not touching 不能完成 told me 結構。", "not touch 缺少 to。", "not to touch 正確表達否定指示。"], reviews: ["not 位於 to V 前，保留尚待遵守的要求。", "第四項沒有改成已發生事件。"], cognitiveProcess: ["u27-s188-form-negative-told-me-not-to-touch", "distinguish-prohibition-from-past-negative-fact"], representationType: "negative-instruction-cloze", misconceptionTargets: ["report-instruction-as-did-not-fact"] },
    { stem: "Mia ___ Leo to wait because she needed one more minute.", options: ["asked", "made", "let", "saw"], answerIndex: 0, reasons: ["asked Leo to wait 表達請求。", "made Leo to wait 中多了 to。", "let Leo to wait 中也多了 to，語意是允許。", "saw Leo to wait 形式不合。"], reviews: ["because 子句支持 Mia 提出等待請求。", "第一項是唯一同時接受 to V 且符合情境的動詞。"], cognitiveProcess: ["u27-s188-select-asked-for-one-minute-request", "use-form-and-intent-to-choose-matrix-verb"], representationType: "request-verb-selection", misconceptionTargets: ["choose-governing-verb-by-meaning-only"] },
    { stem: "Which line means that Ben, not Amy, will join?", options: ["Amy wants to join Ben.", "Amy wants Ben to join.", "Ben wants Amy to join.", "Amy asked to join Ben."], answerIndex: 1, reasons: ["主詞 Amy 執行 to join Ben。", "Ben 是 want 的受詞，也是 to join 的執行者。", "第三項改成 Amy 加入。", "第四項仍由 Amy 執行 join。"], reviews: ["是否出現 Ben 作受詞會改變執行者。", "第二項精確指定 Ben 加入。"], cognitiveProcess: ["u27-s188-choose-ben-as-joiner-in-want-frame", "contrast-subject-control-with-object-control"], representationType: "infinitive-agent-contrast", misconceptionTargets: ["ignore-object-before-to-verb"] },
    { stem: "The coach told the team to meet at six. What did the coach give?", options: ["A report that six had passed", "Permission to miss the meeting", "An instruction about the meeting time", "A question about who owned six"], answerIndex: 2, reasons: ["句子不是報導時間已過。", "told ... to meet 不是允許缺席。", "教練給團隊六點集合的指示。", "six 是時間，不是所有物。"], reviews: ["tell + team + to meet 在此表達指示。", "第三項保留時間與溝通功能。"], cognitiveProcess: ["u27-s188-interpret-coach-meeting-instruction", "classify-tell-object-infinitive-speech-act"], representationType: "instruction-function-identification", misconceptionTargets: ["read-tell-as-permission"] },
    { stem: "Amy asked Leo if the store was open. Which fact is true?", options: ["Amy ordered Leo to open it.", "Leo was asked to close it.", "Amy wanted the store to speak.", "Amy asked Leo for information."], answerIndex: 3, reasons: ["if 子句是詢問資訊，不是命令開門。", "題幹沒有 close。", "store 不是 speak 的執行者。", "asked Leo if 表示向 Leo 詢問是否營業。"], reviews: ["ask 不一定接 object + to V，也可接 if 子句。", "第四項保留 yes-no information request。"], cognitiveProcess: ["u27-s188-distinguish-ask-if-from-ask-to-act", "classify-information-question-versus-request"], representationType: "ask-frame-function-contrast", misconceptionTargets: ["put-every-ask-into-to-infinitive"] },
    { stem: "We would like the bus ___ near the school.", options: ["to stop", "stop", "stopped", "stopping to"], answerIndex: 0, reasons: ["would like + object + to V 表達希望。", "stop 缺少 to。", "stopped 不符合此不定詞結構。", "stopping to 形式不合。"], reviews: ["bus 是預期執行 stop 的對象。", "第一項與 want someone to do 同類。"], cognitiveProcess: ["u27-s188-complete-would-like-bus-to-stop", "extend-object-infinitive-to-polite-want-expression"], representationType: "polite-want-cloze", misconceptionTargets: ["omit-to-after-object-would-like"] },
    { stem: "Change only the missing word: The guide told us follow the path.", options: ["Add did before told", "Add to before follow", "Add were after us", "Add following after path"], answerIndex: 1, reasons: ["told 已可作過去主要動詞。", "tell + object 需要 to follow。", "us were 會破壞結構。", "path 後不需 following。"], reviews: ["錯誤是受詞與動作間缺少 to。", "第二項形成 told us to follow。"], cognitiveProcess: ["u27-s188-insert-to-in-told-us-follow", "repair-missing-infinitive-marker-only"], representationType: "missing-word-edit", misconceptionTargets: ["alter-correct-past-reporting-verb"] },
    { stem: "Nora wants Sam to bring the map, but Sam has not answered. What is known?", options: ["Sam has promised to bring it.", "The map is already with Nora.", "Nora hopes Sam will bring it.", "Sam refused the request."], answerIndex: 2, reasons: ["未回答不等於承諾。", "題幹沒有地圖現況。", "wants Sam to bring 明示 Nora 的希望。", "未回答也不等於拒絕。"], reviews: ["區分想要、回應與實際行動三層。", "第三項是唯一不超出證據的敘述。"], cognitiveProcess: ["u27-s188-limit-inference-from-unanswered-want", "separate-desire-from-promise-and-action"], representationType: "want-evidence-boundary", misconceptionTargets: ["treat-want-as-guaranteed-compliance"] },
    { stem: "Dad asked Mia not to call during class; the teacher told everyone to turn off phones. Which action appears in both messages?", options: ["Calling Dad after class", "Asking the teacher a question", "Keeping phones in a bag at all times", "Avoiding phone use during class"], answerIndex: 3, reasons: ["after class 不在兩個訊息共同內容。", "沒有詢問老師。", "at all times 超出時間範圍。", "not to call 與 turn off phones 都限制上課用手機。"], reviews: ["整合兩句不同動詞但相近的行動限制。", "第四項保留 during class 的共同時間。"], cognitiveProcess: ["u27-s188-synthesize-two-class-phone-directives", "find-shared-action-across-ask-and-tell-frames"], representationType: "multi-message-action-synthesis", misconceptionTargets: ["overgeneralize-time-limited-rule"] },
  ]),
  ...skillQuestions("189", [
    { stem: "The rain made us we stay inside. Which word should be taken out?", options: ["we", "us", "made", "inside"], answerIndex: 0, reasons: ["us 已是 made 的受詞和 stay 的執行者，we 重複角色。", "移除 us 會缺少受詞。", "made 表達因果。", "inside 提供地點。"], reviews: ["只刪除重複主格，不改正確結構。", "第一項刪除後形成 made us stay。"], cognitiveProcess: ["u27-s189-take-out-duplicate-we-after-us", "detect-repeated-embedded-agent"], representationType: "duplicate-role-deletion", misconceptionTargets: ["repeat-object-as-subject-pronoun"] },
    { stem: "Dad told ___ to clean the table.", options: ["to clean", "me", "cleaned", "that me"], answerIndex: 1, reasons: ["空格位置需要接受指示的人，不是另一個動作。", "me 是 told 的受詞，也執行 to clean。", "cleaned 不能作人物受詞。", "that me 不能接 to clean。"], reviews: ["tell 與 to clean 之間必須有 object。", "第二項補齊角色而不重複動作。"], cognitiveProcess: ["u27-s189-fill-missing-object-in-told-frame", "restore-required-recipient-role"], representationType: "missing-object-cloze", misconceptionTargets: ["omit-recipient-after-tell"] },
    { stem: "Which line has one complete object-complement frame?", options: ["Amy let him he leave.", "Amy asked to Ben leave.", "Amy had Ben check the door.", "Amy made Ben to checked it."], answerIndex: 2, reasons: ["him he 重複同一人物。", "ask 的順序應是 asked Ben to leave。", "had + Ben + check 完整且無重複。", "make 後多 to，checked 形式也錯。"], reviews: ["逐項檢查 object 是否一次且動詞形式合規。", "第三項唯一完整。"], cognitiveProcess: ["u27-s189-select-single-wellformed-have-frame", "compare-duplicate-order-and-form-errors"], representationType: "integrated-frame-selection", misconceptionTargets: ["accept-surface-presence-of-all-words"] },
    { stem: "Mia wants Leo to call Nora. Which role map is correct?", options: ["Mia receives the call; Leo wants; Nora calls.", "Nora wants; Mia calls; Leo receives.", "Leo wants; Nora calls; Mia receives.", "Mia wants; Leo calls; Nora receives."], answerIndex: 3, reasons: ["第一項顛倒三個角色。", "Nora 不是 wants 的主詞。", "Leo 不是表達希望的人。", "Mia 是主詞，Leo 執行 call，Nora 接收。"], reviews: ["依線性位置分配三位人物。", "第四項保留 want object to V 的控制關係。"], cognitiveProcess: ["u27-s189-map-three-roles-in-want-call", "resolve-wanter-agent-and-recipient"], representationType: "three-role-map", misconceptionTargets: ["swap-person-roles-in-object-infinitive"] },
    { stem: "The teacher made ___ read the note aloud.", options: ["him", "he", "his", "himself was"], answerIndex: 0, reasons: ["him 是 made 後的受格，也執行 read。", "he 是主格。", "his 需表達所有或修飾名詞。", "himself was 破壞 frame。"], reviews: ["語意執行者仍可使用受格，因為位置在 made 後。", "第一項形成 made him read。"], cognitiveProcess: ["u27-s189-select-him-in-make-read-frame", "apply-case-with-embedded-agent-role"], representationType: "integrated-pronoun-case", misconceptionTargets: ["choose-pronoun-by-semantic-agent-only"] },
    { stem: "The guide ___ us to wait, but the rain ___ us stay longer.", options: ["made / told", "told / made", "let / asked", "saw / wanted"], answerIndex: 1, reasons: ["made us to wait 多出 to，told us stay 缺 to。", "told us to wait 與 rain made us stay 都正確。", "let us to wait 形式錯，asked us stay 也缺 to。", "saw us to wait 與 wanted us stay 均不合。"], reviews: ["兩個空格分別由 to wait 與 stay 的既有形式反推。", "第二項在形式和因果語意上都成立。"], cognitiveProcess: ["u27-s189-coordinate-told-to-and-made-bare", "solve-two-governing-verbs-from-complement-forms"], representationType: "dual-frame-selection", misconceptionTargets: ["use-one-complement-pattern-for-all-verbs"] },
    { stem: "I saw Amy carrying a bag. Which word is both the object of saw and the person carrying?", options: ["I", "bag", "Amy", "saw"], answerIndex: 2, reasons: ["I 是觀察者。", "bag 是被搬的物品。", "Amy 位於 saw 後並執行 carrying。", "saw 是感官動詞。"], reviews: ["同一名詞可同時有文法受詞與語意行動者兩種角色。", "第三項符合兩個條件。"], cognitiveProcess: ["u27-s189-identify-dual-role-amy-in-perception", "combine-syntactic-object-and-semantic-agent"], representationType: "dual-role-identification", misconceptionTargets: ["assume-object-cannot-be-action-agent"] },
    { stem: "Ben was told to wait. If Amy was the teller, which active line keeps Ben's action?", options: ["Ben told Amy to wait.", "Amy made Ben waited.", "Amy waited for Ben to tell.", "Amy told Ben to wait."], answerIndex: 3, reasons: ["第一項改成 Ben 是 teller、Amy 等待。", "第二項改用 make 且 waited 形式錯。", "第三項是 Amy 等待 Ben 告知。", "第四項保留 Amy 為 teller、Ben 執行 wait。"], reviews: ["題幹已明示 Amy 是告知者，不需由被動句猜測。", "第四項沒有改變 action agent。"], cognitiveProcess: ["u27-s189-reconstruct-active-teller-with-role-preservation", "transform-voice-while-holding-embedded-agent"], representationType: "role-preserving-active-reconstruction", misconceptionTargets: ["swap-teller-and-waiter"] },
    { stem: "The message made Amy ask Leo to leave. Who was asked to leave?", options: ["Leo", "The message", "Amy", "No one"], answerIndex: 0, reasons: ["Leo 是 ask 的受詞，也是 to leave 的執行者。", "message 造成 Amy 提出請求。", "Amy 是 ask 的執行者。", "句中明示 ask + Leo + to leave。"], reviews: ["句中有兩層控制：message → Amy ask，Amy → Leo leave。", "第一項位於第二層受詞位置。"], cognitiveProcess: ["u27-s189-resolve-leo-in-nested-make-ask-frame", "trace-agent-through-two-complement-layers"], representationType: "nested-role-resolution", misconceptionTargets: ["assign-inner-action-to-outer-object"] },
    { stem: "Repair only the repeated role: The coach had us we carry the bags.", options: ["coach → coaches", "us we → us", "had → having", "bags → bagging"], answerIndex: 1, reasons: ["coach 可作單數主詞。", "us 已承接 carry，刪 we 可修正重複。", "had 是正確過去安排動詞。", "bags 是正確名詞。"], reviews: ["題目指定 repeated role，不動其他正確內容。", "第二項形成 had us carry。"], cognitiveProcess: ["u27-s189-collapse-us-we-to-single-object", "edit-duplicate-role-with-minimal-change"], representationType: "focused-duplicate-role-repair", misconceptionTargets: ["rewrite-unrelated-correct-fields"] },
    { stem: "Amy had Ben call Nora, and Nora did not answer. Which statement keeps every stated role?", options: ["Ben arranged Amy to call himself.", "Nora made Amy answer Ben.", "Amy arranged the call, Ben called, and Nora did not answer.", "Amy called Nora and Ben answered."], answerIndex: 2, reasons: ["第一項更換所有角色且結構錯。", "第二項加入未發生的使役與回答。", "第三項依序保留安排者、撥電話者與未接聽者。", "第四項把撥打與接聽者對調。"], reviews: ["將 have frame 與後續 negative result 一起追蹤。", "第三項沒有把未接聽改寫成未撥出。"], cognitiveProcess: ["u27-s189-preserve-call-roles-with-no-answer-result", "integrate-causative-action-and-follow-up-outcome"], representationType: "multi-event-role-preservation", misconceptionTargets: ["swap-roles-across-sentence-boundary"] },
    { stem: "The teacher let Mia read the note, then asked her to explain it. What did Mia do first?", options: ["She explained the note.", "She asked the teacher to read.", "The teacher explained it.", "She read the note."], answerIndex: 3, reasons: ["then 表示 explain 在 read 之後。", "Mia 不是提出 ask 的人。", "teacher 是允許者與請求者，非明示解釋者。", "let Mia read 是第一個行動。"], reviews: ["同時解析 let + bare V 與 ask + to V，再用 then 排序。", "第四項是 Mia 的較早動作。"], cognitiveProcess: ["u27-s189-sequence-let-read-before-ask-explain", "integrate-two-frames-with-temporal-order"], representationType: "cross-frame-event-sequencing", misconceptionTargets: ["ignore-then-and-reverse-actions"] },
  ]),
];

export const ENGLISH_UNIT_SOURCE = {
  unitId: UNIT_ID,
  lectures: ENGLISH_U27_LECTURES,
  questions: ENGLISH_U27_QUESTIONS,
  vocabularyPolicy: {
    capQuestionBasis: "appendix-5-table-1",
    additionalLearningTerms: ["add", "alarm", "aloud", "arrange", "avoid", "cause", "certain", "coach", "customer", "direct", "film", "fit", "guide", "information", "limit", "manager", "message", "path", "pattern", "progress", "promise", "receive", "refuse", "repair", "state", "sudden", "suggest", "support", "whole", "wood"],
    properNames: ["Amy", "Ben", "Leo", "Mia", "Nora", "Sam"],
    grammarNotation: ["action", "active", "agent", "arrangement", "bare", "base", "causative", "cause", "clause", "communication", "complement", "complete", "completion", "control", "directive", "ed", "effect", "event", "evidence", "form", "frame", "function", "governing", "infinitive", "ing", "instruction", "intent", "matrix", "modal", "object", "ongoing", "participant", "permission", "process", "pronoun", "receiver", "recipient", "report", "request", "result", "role", "scope", "semantic", "statement", "structure", "subject", "suggestion", "support", "tense", "transfer", "V", "verb", "viewpoint"],
    malformedDistractors: [],
  },
};
