const UNIT_ID = "ENG_R4_U22";

function lecture(id, skillId, content) {
  return { id, skillId, ...content, sections: content.sections.map((section, index) => ({ id: `${id}_SEC_${String(index + 1).padStart(2, "0")}`, ...section })) };
}

const DIFFICULTIES = ["foundation", "foundation", "foundation", "standard", "standard", "standard", "standard", "advanced", "advanced", "advanced", "transfer", "transfer"];

function skillQuestions(skillNumber, values) {
  if (values.length !== 12) throw new Error(`ENG_R4_S${skillNumber}: expected 12 authored questions`);
  return values.map((value, index) => ({ id: `ENG_R4_Q_${skillNumber}_${String(index + 1).padStart(2, "0")}`, skillId: `ENG_R4_S${skillNumber}`, difficulty: DIFFICULTIES[index], ...value }));
}

export const ENGLISH_U22_LECTURES = [
  lecture("ENG_R4_L_S148", "ENG_R4_S148", {
    objectives: ["看出 to 加原形動詞可以說明做某事的目的。", "區分目的、不相關的先後事件與結果，避免只看到 to 就作答。"],
    sections: [
      { title: "to 加原形動詞回答為了什麼", content: "Mia went to the library to study 中，to study 說明她去圖書館的目的。前半句先交代實際行動，後面的 to 加原形動詞補出她希望藉此完成的事，中文常可理解成「為了……」。" },
      { title: "目的必須和主句主詞相符", content: "Ben saved money to buy a bike 表示存錢與買腳踏車的行動者都是 Ben。若後面的動作由另一個人完成，就不能只接一個不定詞，通常要寫出新的主詞與完整子句。" },
      { title: "不是每個 to 都表示目的", content: "Nora went to school 裡的 to 後接地點 school，表示方向；Nora went to school to meet Amy 中，第二個 to meet 才說明目的。判斷時先看 to 後面是名詞還是原形動詞，再檢查語意。" },
      { title: "目的不等於最後一定成功", content: "Leo called to ask for help 只表示打電話的用意，不能推出他一定得到幫助。目的描述的是行動者想完成什麼；結果是否發生，仍要由後文提供證據。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S148_EX_01", prompt: "Amy opened the window ___ some fresh air in. (let / to let)", steps: ["找出 Amy 打開窗戶的行動。", "判斷後半要說明打開窗戶的目的。", "用 to let 接原形動詞。"], answer: "to let", why: "Amy 打開窗戶是為了讓新鮮空氣進來，因此目的成分要用 to let。只寫 let 會把兩個動詞直接放在一起，句子缺少連接。" },
      { id: "ENG_R4_L_S148_EX_02", prompt: "Nora went to the store to buy milk. Why did she go there?", steps: ["先找到主要行動 went to the store。", "讀取 to buy milk 提供的用意。", "以買牛奶回答 why。"], answer: "To buy milk.", why: "why 問 Nora 去商店的原因或目的；to buy milk 正好補出她想做的事。句子沒有說她去工作或見朋友，不能加入原文沒有的目的。" },
      { id: "ENG_R4_L_S148_EX_03", prompt: "Ben left early ___ the first bus. (catch / to catch)", steps: ["確認 left early 是已做的行動。", "後面要交代提早離開的目的。", "選 to catch。"], answer: "to catch", why: "提早離開與搭上第一班公車之間是目的關係，所以用 to catch。catch 單獨接在 left early 後面沒有結構可連接兩個動作。" },
    ],
    misconceptions: [
      { belief: "看到句中有兩個動作，就把第二個動詞一律改成 to 加原形。", whyWrong: "第二個動作可能表示時間、原因或另一位主詞的行動，不一定是目的。", correction: "先問主句行動是為了完成什麼，再決定是否使用目的不定詞。" },
      { belief: "to 後面接任何字都能表示目的。", whyWrong: "to school 的 to 是方向介系詞，後面不是原形動詞。", correction: "目的用法須見到 to 加原形動詞，並能回答 why。" },
      { belief: "句子用了 to buy，就代表東西最後一定買到。", whyWrong: "目的只呈現原先打算，不保證行動成功。", correction: "另找 bought、could not buy 等結果證據。" },
      { belief: "目的不定詞的行動者可以和主句主詞毫無關係。", whyWrong: "沒有另寫主詞時，兩個動作通常由同一人或事物執行。", correction: "核對誰做主句動作，也由誰完成 to 後的動作。" },
    ],
    checks: [
      { prompt: "to read 在 I sat down to read 中回答哪一類問題？", answer: "為了什麼而坐下", reason: "to read 說明 sat down 的目的。" },
      { prompt: "went to Taipei 中的 to 是目的標記嗎？", answer: "不是", reason: "Taipei 是地點名詞，to 表示前往方向。" },
      { prompt: "目的句能保證結果發生嗎？", answer: "不能", reason: "它只交代原先想完成的事。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S149", "ENG_R4_S149", {
    objectives: ["熟悉 want、hope、plan、decide、need 等動詞後接 to 加原形動詞。", "依句中控制動詞選擇補語形式，而不是依中文表面順序猜測。"],
    sections: [
      { title: "有些動詞以不定詞補足內容", content: "want to leave、hope to win、plan to visit 都用 to 加原形動詞說明想要、希望或計畫的內容。to 不是時態，真正決定時間的是前面的 want、hoped、planned 等動詞。" },
      { title: "常見搭配要整組學習", content: "decide to stay、need to finish、learn to cook、choose to walk 都是常見組合。不能因為中文都像「做某事」，就把後面的動詞自由換成動名詞；先認出前面的控制動詞。" },
      { title: "有人作受詞時結構會多一層", content: "Amy asked Ben to wait 中，Ben 是 asked 的受詞，也是 wait 的執行者。Mia expects the bus to arrive 也由 the bus 執行 arrive；若沒有插入受詞，如 Amy hoped to wait，等待的人就是 Amy。" },
      { title: "不定詞形式不隨主詞或時間變化", content: "Mia wants to go 與 Mia wanted to go 都保留 to go，不寫 to goes 或 to went。agree to help、promise to come home 等搭配也把人稱和時態放在主要動詞，to 後維持原形。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S149_EX_01", prompt: "Leo hopes ___ the game. (win / to win)", steps: ["辨認主要動詞 hopes。", "回想 hope 後接不定詞。", "保留 win 的原形。"], answer: "to win", why: "hope 的內容以 to 加原形動詞表示，所以用 to win。hopes 已承擔第三人稱單數變化，後面的 win 不再加 s。" },
      { id: "ENG_R4_L_S149_EX_02", prompt: "Nora decided ___ home. (stay / to stay)", steps: ["找出 decided 表示已作決定。", "決定的內容接 to 加原形。", "填入 to stay。"], answer: "to stay", why: "decided 後用 to stay 說明 Nora 決定做的事。句子的過去時間已由 decided 表示，不能把 stay 再改成 stayed。" },
      { id: "ENG_R4_L_S149_EX_03", prompt: "Mia asked Ben ___ outside. (wait / to wait)", steps: ["確認 Ben 是 asked 的受詞。", "Ben 同時是 wait 的行動者。", "在受詞後接 to wait。"], answer: "to wait", why: "ask someone to do something 的結構要在 Ben 後接 to wait。若只寫 wait，asked Ben 與後面的動作之間缺少必要的不定詞標記。" },
    ],
    misconceptions: [
      { belief: "前面是過去式，to 後的動詞也必須改成過去式。", whyWrong: "不定詞中的動詞維持原形，時間由主要動詞負責。", correction: "寫 planned to leave，不寫 planned to left。" },
      { belief: "want 後可直接接另一個帶人稱變化的動詞。", whyWrong: "wants goes 把兩個限定動詞並排，缺少正確補語結構。", correction: "使用 wants to go。" },
      { belief: "所有表達喜好的動詞都接 to 加原形。", whyWrong: "enjoy 通常接動名詞，不能由中文意思直接類推。", correction: "分別記住 want to read 與 enjoy reading。" },
      { belief: "ask Ben to wait 和 hope to wait 的動作者都只能是句首主詞。", whyWrong: "ask 結構中的 Ben 是 wait 的執行者。", correction: "有受詞時先確認不定詞的動作由誰完成。" },
    ],
    checks: [
      { prompt: "plan 後要用 visit 還是 to visit？", answer: "to visit", reason: "plan 以不定詞補出計畫內容。" },
      { prompt: "wanted to went 的錯誤在哪裡？", answer: "went 應改為 go", reason: "to 後使用原形動詞。" },
      { prompt: "Amy told Leo to sit 中，誰坐下？", answer: "Leo", reason: "受詞 Leo 是不定詞動作的執行者。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S150", "ENG_R4_S150", {
    objectives: ["熟悉 enjoy、finish、keep、practice、mind 等動詞後接動名詞。", "辨識 -ing 是補語形式，不把它誤當成每一題都在描述現在進行。"],
    sections: [
      { title: "動名詞讓動作成為談論的內容", content: "enjoy reading、finish washing、practice speaking 中，reading、washing、speaking 都把動作當成前面動詞的內容。這些 -ing 形式不是因為句子一定正在進行，而是固定搭配所需。" },
      { title: "常見動詞後面不能直接放原形", content: "Mia enjoys cooking 不寫 enjoys cook；Ben finished cleaning 不寫 finished clean。avoid running、give up looking、suggest taking the bus 也使用動名詞，主要動詞負責表示人稱或時間。" },
      { title: "keep 表示動作持續", content: "The baby keeps crying 表示哭泣沒有停止。keep 後接動名詞時，重點是同一動作延續；若只看現在時間而選 cries，就會破壞 keep 的補語形式。" },
      { title: "其他常見的動名詞結構", content: "Do you mind opening the door? 是詢問是否介意開門，回答 No 通常表示不介意。spend time building 與 be busy cooking 也要接動名詞；它們分別說明時間花在哪裡，以及當下忙著做什麼。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S150_EX_01", prompt: "Ben enjoys ___ after dinner. (walk / walking)", steps: ["辨認 enjoys 是控制動詞。", "enjoy 後接動名詞。", "選 walking。"], answer: "walking", why: "enjoy 後面以 walking 表示 Ben 喜歡的活動。walk 原形不能直接作 enjoys 的補語，且這裡的 -ing 不表示他此刻正在走路。" },
      { id: "ENG_R4_L_S150_EX_02", prompt: "Amy finished ___ the cups. (wash / washing)", steps: ["finished 表示工作已完成。", "finish 後面接動名詞。", "使用 washing。"], answer: "washing", why: "washing the cups 是 Amy 完成的工作，因此 finish 後用動名詞。句子的過去時間由 finished 表示，不需要把 washing 改成 washed。" },
      { id: "ENG_R4_L_S150_EX_03", prompt: "Would you mind ___ the window? (close / closing)", steps: ["認出 Would you mind 的詢問結構。", "mind 後接動名詞。", "填 closing。"], answer: "closing", why: "Would you mind closing the window? 是禮貌詢問是否介意關窗。mind 後須接 closing，不能直接接 close；是否真的關窗仍看對方回應。" },
    ],
    misconceptions: [
      { belief: "只要看到 -ing，就判定句子是現在進行式。", whyWrong: "動名詞可作動詞的補語，前面不一定有 be 動詞。", correction: "先看 -ing 前是 be，還是 enjoy、finish、keep 等控制動詞。" },
      { belief: "finished 後應接 washed，因為兩個動作都發生在過去。", whyWrong: "finish 後需要動名詞，時態只標在 finished。", correction: "寫 finished washing。" },
      { belief: "keep crying 表示哭了一次就結束。", whyWrong: "keep 加動名詞強調動作持續或反覆。", correction: "由上下文判斷動作延續到何時。" },
      { belief: "Do you mind...? 回答 No 就是拒絕。", whyWrong: "No 通常回答「不介意」，語意上可接受請求。", correction: "先把 mind 理解成「介意」，再解讀 yes 或 no。" },
    ],
    checks: [
      { prompt: "enjoy 後用 read 還是 reading？", answer: "reading", reason: "enjoy 後接動名詞。" },
      { prompt: "finished cleaning 的過去時間由哪個字表示？", answer: "finished", reason: "cleaning 是補語形式，不另標過去式。" },
      { prompt: "keeps running 表示動作停止了嗎？", answer: "沒有", reason: "keeps 顯示 running 持續。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S151", "ENG_R4_S151", {
    objectives: ["把動名詞片語放在句首作主詞，並判斷整體的單數動詞形式。", "分清活動名稱、正在進行的動作與命令句。"],
    sections: [
      { title: "動名詞片語可以當一件活動", content: "Reading before bed helps me sleep 中，Reading before bed 是整個句子的主詞，指「睡前閱讀」這項活動。它不是省略主詞的進行式，後面也不需要再補一個人稱主詞。" },
      { title: "一項活動通常視為單數", content: "Swimming is good exercise 與 Getting up early takes practice 都用 is、takes。即使動名詞後有複數名詞，如 Reading books，整個片語仍被視為一件活動。" },
      { title: "兩項活動以 and 連接才形成複數", content: "Reading and writing are both useful 把兩項活動並列，所以用 are。若是 Reading books is useful，books 只是 reading 的受詞，不能因離動詞較近就改用 are。" },
      { title: "活動主詞可表達影響或評價", content: "Walking to school saves money 說明活動帶來的結果；Cooking with friends is fun 則評價這項活動。先圈出完整主詞範圍，再選後面的動詞與補語。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S151_EX_01", prompt: "___ every day helps Leo stay healthy. (Walk / Walking)", steps: ["空格要放一項活動作主詞。", "把 walk 改成動名詞。", "以 Walking 開頭。"], answer: "Walking", why: "Walking every day 整體是 helps 的主詞，表示每天走路這項活動。Walk 會像命令句開頭，無法和後面的 helps 組成同一結構。" },
      { id: "ENG_R4_L_S151_EX_02", prompt: "Reading books ___ useful. (is / are)", steps: ["圈出 Reading books 這個主詞片語。", "把它視為一項閱讀活動。", "選單數 is。"], answer: "is", why: "Reading books 雖含複數 books，核心仍是「閱讀書籍」這一項活動，所以用 is。若只看最近的 books 而選 are，會判錯主詞中心。" },
      { id: "ENG_R4_L_S151_EX_03", prompt: "Cooking and cleaning ___ time. (takes / take)", steps: ["找出 cooking 與 cleaning 兩項活動。", "and 使主詞成為複數。", "使用 take。"], answer: "take", why: "Cooking and cleaning 是兩個並列的動名詞主詞，因此搭配 take。若只有 Cooking for the family，才會把整項活動視為單數而用 takes。" },
    ],
    misconceptions: [
      { belief: "句首的 -ing 一定表示某人此刻正在做事。", whyWrong: "沒有 be 動詞時，動名詞片語常是活動名稱並作主詞。", correction: "找句子的主要動詞，再判斷句首片語扮演的角色。" },
      { belief: "Reading books 後一定用 are，因為 books 是複數。", whyWrong: "books 是 reading 的受詞，完整主詞是一項活動。", correction: "把 Reading books 整體視為單數。" },
      { belief: "兩個動名詞以 and 連接後仍一律用 is。", whyWrong: "兩項不同活動形成複數主詞。", correction: "Reading and writing 後使用 are。" },
      { belief: "Walking every day helps... 是少寫了 He 的進行式。", whyWrong: "Walking every day 已是完整主詞，不需另加人稱。", correction: "將中文理解為「每天走路這件事有幫助」。" },
    ],
    checks: [
      { prompt: "Getting enough sleep 後用 is 還是 are？", answer: "is", reason: "完整片語代表一件事。" },
      { prompt: "Reading and drawing 後用 helps 還是 help？", answer: "help", reason: "and 連接兩項活動，主詞為複數。" },
      { prompt: "句首動名詞片語可以是主詞嗎？", answer: "可以", reason: "它能把動作當作一項活動來談。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S152", "ENG_R4_S152", {
    objectives: ["從 to 後的成分判斷它是不定詞標記還是介系詞。", "熟悉 look forward to、be used to 等接動名詞的完整搭配。"],
    sections: [
      { title: "不定詞的 to 後接原形動詞", content: "Mia wants to read 中，to 是不定詞標記，後面接原形 read。這個 to 和 want 合作補出想做的事，因此不能改成 reading 或 reads。" },
      { title: "介系詞 to 後接名詞或代名詞", content: "Ben walked to school 與 Amy spoke to him 中，school、him 都不是動詞，to 表示方向或對象。看到 to 時不要立刻套用原形動詞，要先辨認它後面的詞類。" },
      { title: "介系詞後若放動作要用動名詞", content: "Nora looks forward to seeing Leo 中，to 屬於 look forward to 的一部分，後面若接動作要用 seeing。be used to getting up early 也同樣使用動名詞，表示已習慣某事。" },
      { title: "同一句可出現兩種 to", content: "Leo went to the kitchen to get water 中，第一個 to 後接地點，第二個 to 後接原形 get 並說明目的。逐一檢查每個 to，不能用前一個的功能替後一個作答。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S152_EX_01", prompt: "Amy wants to dance. What word follows to?", steps: ["找到 wants to 的搭配。", "查看 to 後的 dance。", "判定 dance 是原形動詞。"], answer: "dance", why: "wants to dance 裡的 to 是不定詞標記，dance 維持原形。若寫 dances，會把人稱變化錯放到不定詞內。" },
      { id: "ENG_R4_L_S152_EX_02", prompt: "Ben looks forward to ___ Mia. (see / seeing)", steps: ["認出完整片語 look forward to。", "此處 to 是介系詞。", "介系詞後用 seeing。"], answer: "seeing", why: "look forward to 的 to 不是不定詞標記，所以動作要改為 seeing。選 see 是把這個固定片語誤拆成一般的 to 加原形動詞。" },
      { id: "ENG_R4_L_S152_EX_03", prompt: "Nora went to the park to run. Which to tells why she went?", steps: ["第一個 to 後是地點 the park。", "第二個 to 後是原形 run。", "目的由 to run 表示。"], answer: "The second to.", why: "to the park 指 Nora 前往的地點；to run 回答她去公園要做什麼。因此只有第二個 to 是目的不定詞。" },
    ],
    misconceptions: [
      { belief: "任何 to 後面都只能接原形動詞。", whyWrong: "介系詞 to 可接地點、人物或動名詞。", correction: "先辨認完整搭配，再看 to 後成分。" },
      { belief: "look forward to see 是正確的不定詞。", whyWrong: "look forward to 中的 to 是介系詞，不能接原形 see。", correction: "寫 look forward to seeing。" },
      { belief: "be used to getting up 表示以前常常早起、現在不再如此。", whyWrong: "be used to 表示已習慣；used to 加原形才表示過去習慣。", correction: "比較 is used to getting up 與 used to get up。" },
      { belief: "一句中所有 to 的功能必定相同。", whyWrong: "to school to study 同時含方向介系詞與目的不定詞。", correction: "對每個 to 分別檢查後接名詞或原形動詞。" },
    ],
    checks: [
      { prompt: "spoke to Amy 中，to 後接哪一類字？", answer: "名詞", reason: "Amy 是說話的對象。" },
      { prompt: "look forward to meet 還是 meeting？", answer: "meeting", reason: "此處 to 是介系詞。" },
      { prompt: "to the station to take a bus 有幾種 to？", answer: "兩種", reason: "前者表方向，後者表目的。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S153", "ENG_R4_S153", {
    objectives: ["依前面的動詞或固定片語選擇 to 加原形或動名詞。", "以搭配與句意共同判斷，不用單一中文翻譯類推。"],
    sections: [
      { title: "先找決定形式的控制動詞", content: "want、hope、plan、decide、need 後通常接 to 加原形；enjoy、finish、keep、practice、mind、avoid 後通常接動名詞。解題時先圈出這個控制動詞，再處理後面的動作。" },
      { title: "時間變化不會改掉補語規則", content: "She plans to visit 與 She planned to visit 都用 to visit；He enjoys reading 與 He enjoyed reading 都用 reading。時態改在前面的主要動詞，固定搭配仍保留。" },
      { title: "相近中文不代表英文搭配相同", content: "想要閱讀是 want to read，享受閱讀是 enjoy reading，完成閱讀是 finish reading。三句都談閱讀，卻因控制動詞不同而選用不同形式。" },
      { title: "完整情境可排除形式正確但意思錯的選項", content: "If the work is done, Mia finished washing 比 keeps washing 合理；若文字說動作沒有停止，則應用 keeps washing。除了形式，還要核對完成、持續、希望或決定等語意。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S153_EX_01", prompt: "Leo plans ___ Japan. (visit / to visit / visiting)", steps: ["圈出 plans。", "plan 後接不定詞。", "選 to visit。"], answer: "to visit", why: "plans 需要 to visit 補出 Leo 的計畫內容。visiting 不符合 plan 的常用搭配，visit 原形也少了 to。" },
      { id: "ENG_R4_L_S153_EX_02", prompt: "Mia practiced ___ English. (speak / to speak / speaking)", steps: ["找出 practiced。", "practice 後接動名詞。", "填 speaking。"], answer: "speaking", why: "speaking English 是 Mia 練習的活動，因此 practice 後用動名詞。to speak 與 speak 都不符合這個固定搭配。" },
      { id: "ENG_R4_L_S153_EX_03", prompt: "Ben finished ___ and decided ___ home. (cleaning; to go)", steps: ["finish 後選動名詞。", "decide 後選不定詞。", "分別填 cleaning 與 to go。"], answer: "cleaning; to go", why: "同一句有兩個不同控制動詞：finished 要接 cleaning，decided 要接 to go。不能為了形式整齊而把兩個空格都填成同一類。" },
    ],
    misconceptions: [
      { belief: "同一句的兩個動作補語必須使用相同形式。", whyWrong: "每個補語由自己前面的控制動詞決定。", correction: "逐一配對 finished cleaning 與 decided to go。" },
      { belief: "只要句意談未來，就一律使用 to 加原形。", whyWrong: "enjoy、practice 等仍接動名詞，與事件時間無關。", correction: "先查固定搭配，再判斷時態。" },
      { belief: "動詞變成過去式後，後面的補語形式也跟著改變。", whyWrong: "planned to leave 與 practiced speaking 的補語規則不變。", correction: "只在主要動詞標示時態。" },
      { belief: "中文都有「做某事」，英文就能在 reading 與 to read 間自由替換。", whyWrong: "不同控制動詞限制不同形式。", correction: "把 want to、finish doing 等整組記憶並放回句中確認。" },
    ],
    checks: [
      { prompt: "decide 後接 staying 還是 to stay？", answer: "to stay", reason: "decide 接不定詞。" },
      { prompt: "practice 後接 speak 還是 speaking？", answer: "speaking", reason: "practice 接動名詞。" },
      { prompt: "一個句子能同時出現兩種補語形式嗎？", answer: "可以", reason: "不同控制動詞可要求不同形式。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S154", "ENG_R4_S154", {
    objectives: ["區分 stop、remember、forget、try 後接不定詞或動名詞時的語意。", "依時間順序與事件是否發生判斷形式，而不是只背字尾。"],
    sections: [
      { title: "stop doing 與 stop to do", content: "Ben stopped talking 表示他不再說話；Ben stopped to talk 表示他先停止原來的活動，目的是開始談話。判斷時要問：停止的是後面的動作，還是停下來去做後面的動作？" },
      { title: "remember doing 與 remember to do", content: "remember locking the door 是記得自己鎖過門，動作先發生、記憶留到現在；remember to lock the door 是沒有忘記該做的事，先想起責任，再完成鎖門。" },
      { title: "forget doing 與 forget to do", content: "forget to call 表示該打電話卻沒有做；forget calling 表示電話打過了，但後來不記得這段經驗。題目若明說事情沒有發生，通常要用 forget to do。" },
      { title: "try to do 與 try doing", content: "try to open the box 表示努力嘗試打開，成功與否未知；try using a key 是把使用鑰匙當成可試的方法。前者重在完成目標，後者重在測試一種辦法。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S154_EX_01", prompt: "The teacher came in, so the class stopped ___. (talk / talking)", steps: ["後文表示談話結束。", "停止的正是 talk 這個動作。", "選 talking。"], answer: "talking", why: "老師進來後，全班不再說話，因此 stop 的受詞是 talking。stopped to talk 反而會表示大家停下原來的事，開始說話。" },
      { id: "ENG_R4_L_S154_EX_02", prompt: "Remember ___ the light before you leave. (turn off / to turn off)", steps: ["說話者提醒尚未完成的工作。", "先記得責任，之後才關燈。", "用 to turn off。"], answer: "to turn off", why: "before you leave 顯示關燈是接下來要完成的責任，所以用 remember to turn off。turning off 會變成回想已關燈的經驗。" },
      { id: "ENG_R4_L_S154_EX_03", prompt: "The door will not open. Try ___ this key. (use / using)", steps: ["開門是既定目標。", "使用鑰匙是一個可測試的方法。", "選 using。"], answer: "using", why: "門打不開時，using this key 是建議試驗的一種方法，因此用 try doing。try to use 會較著重努力完成使用鑰匙這件事，不符合此處提供解法的焦點。" },
    ],
    misconceptions: [
      { belief: "stop talking 與 stop to talk 都表示停止說話。", whyWrong: "to talk 表示停下原活動後開始談話，意思相反。", correction: "判斷後面的動作是被停止，還是停下來要做。" },
      { belief: "remember locking 是提醒未來要鎖門。", whyWrong: "動名詞指向已發生的鎖門經驗。", correction: "未來責任用 remember to lock。" },
      { belief: "forgot to bring 表示東西帶了，只是現在不記得。", whyWrong: "不定詞形式表示該做的帶東西行動沒有完成。", correction: "若行動發生但記憶消失，才用 forget doing。" },
      { belief: "try doing 與 try to do 可以在所有句子中互換。", whyWrong: "前者測試方法，後者努力達成目標，焦點不同。", correction: "從情境找目標與被提出的辦法。" },
    ],
    checks: [
      { prompt: "stopped eating 表示什麼？", answer: "不再吃東西", reason: "eating 是被停止的動作。" },
      { prompt: "remember to call 中，電話原本已經打過了嗎？", answer: "不一定，重點是別忘記去打", reason: "不定詞指待完成的責任。" },
      { prompt: "try adding water 重在目標還是方法？", answer: "方法", reason: "adding water 是被測試的做法。" },
    ], assets: [],
  }),
];

export const ENGLISH_U22_QUESTIONS = [
  ...skillQuestions("148", [
    { stem: "Mia went to the library ___ for tomorrow's test.", options: ["to study", "studying", "studied", "studies"], answerIndex: 0, reasons: ["to study 說明 Mia 去圖書館的目的。", "studying 不能直接接在 went to the library 後表示目的。", "studied 會多放一個過去式動詞，缺少連接。", "studies 是第三人稱單數，無法補出此行目的。"], reviews: ["去圖書館在先，準備考試是她想完成的事。", "第一項同時符合 to 加原形與目的關係。"], cognitiveProcess: ["u22-s148-locate-library-visit-goal", "encode-study-as-purpose-infinitive"], representationType: "destination-plus-purpose-cloze", misconceptionTargets: ["replace-purpose-infinitive-with-tense-form"] },
    { stem: "Ben saved money ___ a new bike.", options: ["for buy", "to buy", "buying", "bought"], answerIndex: 1, reasons: ["for 後不能直接接原形 buy。", "to buy 補出 Ben 存錢想達成的目的。", "buying 缺少能把存錢與購買目的連接起來的結構。", "bought 是過去式，與 saved 並排後沒有連接詞。"], reviews: ["存錢是手段，買新腳踏車是目標。", "第二項保留同一主詞並使用目的不定詞。"], cognitiveProcess: ["u22-s148-relate-saving-to-planned-purchase", "reject-for-plus-base-verb"], representationType: "means-goal-money-cloze", misconceptionTargets: ["use-for-before-base-verb"] },
    { stem: "Nora opened the window ___ some fresh air in.", options: ["letting", "let", "to let", "lets"], answerIndex: 2, reasons: ["letting 若無其他結構，不能清楚標示開窗目的。", "let 原形直接接在 opened 後會形成兩個未連接動詞。", "to let 表示 Nora 開窗是為了讓空氣進來。", "lets 帶人稱變化，也不能作 opened 的目的補語。"], reviews: ["開窗與讓空氣進來由 Nora 的同一行動計畫連結。", "第三項是唯一能回答她為何開窗的形式。"], cognitiveProcess: ["u22-s148-infer-window-opening-purpose", "select-to-let-over-bare-let"], representationType: "physical-action-purpose-cloze", misconceptionTargets: ["join-two-finite-verbs-without-marker"] },
    { stem: "Amy called Leo ___ him about the new meeting time.", options: ["told", "telling", "tells", "to tell"], answerIndex: 3, reasons: ["told 與 called 都是過去式，不能無連接詞並列。", "telling 沒有明確標示打電話的用意。", "tells 的現在式與 called 的結構不合。", "to tell 說明 Amy 打電話是為了告知新時間。"], reviews: ["called 是主要行動，告知 Leo 是電話的用途。", "第四項讓兩個動作由同一主詞串成目的關係。"], cognitiveProcess: ["u22-s148-connect-call-with-information-goal", "preserve-shared-agent-in-infinitive"], representationType: "communication-purpose-cloze", misconceptionTargets: ["stack-called-and-told"] },
    { stem: "Why did Sam turn on the light? He turned it on ___ his book.", options: ["to read", "read", "reading", "reads"], answerIndex: 0, reasons: ["to read 直接回答開燈是為了閱讀。", "read 原形缺少目的標記，不能接在完整句後。", "reading 在這個位置不能單獨表示開燈的目的。", "reads 是限定動詞，會與 turned 產生結構衝突。"], reviews: ["why 問的是 turn on the light 的用意。", "第一項提供合理目的，未額外聲稱書已讀完。"], cognitiveProcess: ["u22-s148-answer-why-from-light-use", "distinguish-purpose-from-completed-result"], representationType: "why-question-purpose-completion", misconceptionTargets: ["treat-purpose-as-second-finite-action"] },
    { stem: "Mia went to the market. She wanted to buy fruit. Which sentence keeps both ideas?", options: ["Mia went to the market buying fruit.", "Mia went to the market to buy fruit.", "Mia went to buy fruit to the market.", "Mia to the market went buy fruit."], answerIndex: 1, reasons: ["buying fruit 會讓目的關係不如原句明確。", "to buy fruit 正確說明前往市場的目的。", "地點片語被錯放在目的成分後，語序不自然。", "主詞、地點與動詞順序都被打亂。"], reviews: ["原文先交代前往市場，再說明想買水果。", "第二項保留兩個資訊且沒有加入購買成功的結果。"], cognitiveProcess: ["u22-s148-compress-market-intention-pair", "retain-destination-before-purpose"], representationType: "two-sentence-purpose-combination", misconceptionTargets: ["misorder-destination-and-goal"] },
    { stem: "The club meets early ___ enough time to clean the room.", options: ["had", "having", "to have", "has"], answerIndex: 2, reasons: ["had 是過去式，不能直接補在 meets 後。", "having 未清楚指出提早集合的目的。", "to have 表示提早集合是為了有足夠時間。", "has 會成為另一個限定動詞，句中缺少連接。"], reviews: ["enough time 是早集合想取得的條件。", "第三項把安排與目的連起來，主詞仍是 the club。"], cognitiveProcess: ["u22-s148-map-early-meeting-to-time-goal", "choose-purpose-before-have-enough-time"], representationType: "schedule-purpose-cloze", misconceptionTargets: ["use-having-after-finite-meets"] },
    { stem: "Ben took a map to find the park. What did he want to do with the map?", options: ["Draw a new park.", "Give the map away.", "Take the park home.", "Find the park."], answerIndex: 3, reasons: ["句中沒有說 Ben 要畫公園。", "地圖的用途不是送人，原文無此資訊。", "公園不能由 take the park 解讀，這也不是目的片語內容。", "to find the park 明說他想找到公園。"], reviews: ["問題要求從 to find 還原拿地圖的用意。", "第四項只重述目的，沒有把意圖誤當成功結果。"], cognitiveProcess: ["u22-s148-recover-map-use-from-infinitive", "avoid-inventing-map-action"], representationType: "purpose-infinitive-reading-inference", misconceptionTargets: ["infer-unsupported-tool-use"] },
    { stem: "Nora uses this box ___ old letters.", options: ["to keep", "keep", "keeping", "keeps"], answerIndex: 0, reasons: ["to keep 說明箱子的用途是保存舊信。", "keep 原形直接接在 uses 後，缺少目的標記。", "keeping 在此不能單獨回答箱子拿來做什麼。", "keeps 會與 uses 形成兩個沒有連接的限定動詞。"], reviews: ["this box 是工具，保存信件是使用目的。", "第一項讓用途清楚，也未改變 uses 的現在時態。"], cognitiveProcess: ["u22-s148-identify-container-function", "express-keep-letters-as-use-purpose"], representationType: "object-function-infinitive-cloze", misconceptionTargets: ["place-bare-keep-after-uses"] },
    { stem: "Which sentence says Amy visited Ben because she wanted to help him?", options: ["Amy visited Ben, and he helped her.", "Amy visited Ben to help him.", "Amy visited Ben because he helped her.", "Amy helped Ben before he visited her."], answerIndex: 1, reasons: ["第一句的幫助者是 Ben，方向與題意相反。", "to help him 表示 Amy 拜訪 Ben 的目的是幫他。", "because he helped her 把 Ben 幫 Amy 當成拜訪原因。", "第四句改成 Ben 拜訪 Amy，事件與人物關係都變了。"], reviews: ["題目限定 Amy 是幫助者、Ben 是受助者。", "第二項以目的不定詞完整保留人物與行動方向。"], cognitiveProcess: ["u22-s148-match-agent-patient-purpose", "reject-reversed-help-relations"], representationType: "agent-sensitive-purpose-selection", misconceptionTargets: ["reverse-helper-and-recipient"] },
    { stem: "Leo left home early so that he could catch the first bus. Keep the meaning: Leo left home early ___ the first bus.", options: ["caught", "catching", "to catch", "catches"], answerIndex: 2, reasons: ["caught 會把搭車寫成已發生結果，原句只說目的。", "catching 未正確取代 so that he could 的目的功能。", "to catch 可把 so that he could catch 簡化為同主詞目的。", "catches 是現在式，既不配 left 也不標示目的。"], reviews: ["兩個分句的行動者都是 Leo，適合縮成不定詞。", "第三項保留目的但不保證他真的搭上公車。"], cognitiveProcess: ["u22-s148-reduce-so-that-purpose-clause", "preserve-nonresult-status"], representationType: "purpose-clause-paraphrase", misconceptionTargets: ["turn-intention-into-past-result"] },
    { stem: "Mia went back to the desk, not to sit down, but ___ her book.", options: ["getting", "got", "gets", "to get"], answerIndex: 3, reasons: ["getting 不能與前面的 to sit 形成清楚的對比平行。", "got 是過去式，會破壞 not to...but to... 的結構。", "gets 帶人稱變化，也不與 to sit 同層。", "to get 和 to sit 平行，指出真正目的。"], reviews: ["not...but... 對比兩個可能的回桌目的。", "第四項保持兩邊都是 to 加原形，並選出取書的用意。"], cognitiveProcess: ["u22-s148-resolve-not-but-purpose-contrast", "parallelize-two-infinitive-goals"], representationType: "contrastive-purpose-infinitive", misconceptionTargets: ["break-not-to-but-to-parallelism"] },
  ]),
  ...skillQuestions("149", [
    { stem: "Amy wants ___ the school team.", options: ["to join", "joining", "joined", "joins"], answerIndex: 0, reasons: ["want 後用 to join 補出 Amy 想做的事。", "joining 不符合 want 的一般補語形式。", "joined 是過去式，不能直接接 wants。", "joins 帶第三人稱變化，會和 wants 並列衝突。"], reviews: ["wants 已標示主詞與現在時間。", "第一項保留 join 原形並由 to 引入內容。"], cognitiveProcess: ["u22-s149-complete-want-team-membership", "hold-infinitive-base-after-wants"], representationType: "want-infinitive-cloze", misconceptionTargets: ["add-person-marking-inside-infinitive"] },
    { stem: "Ben hopes ___ his old friend this summer.", options: ["seeing", "to see", "saw", "sees"], answerIndex: 1, reasons: ["seeing 不是 hope 後的標準補語。", "to see 表示 Ben 希望暑假見到朋友。", "saw 是過去式，與 this summer 的希望內容不合。", "sees 是現在式限定動詞，不能直接跟在 hopes 後。"], reviews: ["hope 控制後面的動詞形式，時間線索不改變這項搭配。", "第二項表達尚未實現的希望而未保證見面。"], cognitiveProcess: ["u22-s149-link-hope-to-summer-meeting", "exclude-finite-see-forms"], representationType: "hope-future-content-cloze", misconceptionTargets: ["choose-tense-form-after-hope"] },
    { stem: "Nora plans ___ her aunt on Sunday.", options: ["visiting", "visited", "to visit", "visits"], answerIndex: 2, reasons: ["visiting 不符合 plans 後的補語搭配。", "visited 會把計畫內容錯寫成過去事件。", "to visit 正確補出星期日的計畫。", "visits 是另一個限定動詞，不能直接接 plans。"], reviews: ["on Sunday 交代計畫時間，plans 才是主要動詞。", "第三項用原形 visit 並不聲稱拜訪已完成。"], cognitiveProcess: ["u22-s149-encode-sunday-plan", "separate-plan-time-from-visit-form"], representationType: "plan-calendar-infinitive", misconceptionTargets: ["turn-planned-event-into-past"] },
    { stem: "After reading the note, Leo decided ___ at home.", options: ["stayed", "staying", "stays", "to stay"], answerIndex: 3, reasons: ["stayed 不能直接作 decided 的補語。", "staying 不是 decide 在此要求的形式。", "stays 會產生第二個帶人稱的動詞。", "to stay 說明 Leo 看完紙條後作出的決定。"], reviews: ["after 片語提供決定前的背景，並不控制空格形式。", "第四項由 decided 決定使用不定詞。"], cognitiveProcess: ["u22-s149-ignore-leading-time-phrase", "complete-decide-with-to-stay"], representationType: "decision-after-event-cloze", misconceptionTargets: ["let-nearby-reading-control-complement"] },
    { stem: "The plants need ___ every morning.", options: ["to get water", "getting water", "got water", "gets water"], answerIndex: 0, reasons: ["to get water 說明植物每天需要獲得水分。", "getting water 在此不符合 need 的目標結構。", "got water 是過去形式，與 every morning 的一般需要不合。", "gets water 不能直接接在 need 後。"], reviews: ["主詞是 plants，need 為主要動詞。", "第一項是不定詞內容，不把 get 改成第三人稱形式。"], cognitiveProcess: ["u22-s149-state-plant-need", "retain-base-get-after-to"], representationType: "need-routine-infinitive", misconceptionTargets: ["agree-infinitive-with-plural-subject"] },
    { stem: "Mia learned ___ rice from her father.", options: ["cooking", "to cook", "cooked", "cooks"], answerIndex: 1, reasons: ["cooking 不能在此直接補出學會的技能。", "to cook 表示 Mia 學會煮飯。", "cooked 是過去式，與 learned 無連接詞。", "cooks 是現在式限定動詞，不能作 learned 的補語。"], reviews: ["from her father 說明學習來源，不改變 learn 的搭配。", "第二項讓 learned 保留時態，cook 維持原形。"], cognitiveProcess: ["u22-s149-complete-learned-skill", "separate-teacher-source-from-complement"], representationType: "learn-skill-infinitive", misconceptionTargets: ["copy-past-tense-onto-learned-content"] },
    { stem: "Amy asked Ben ___ by the door.", options: ["waits", "waited", "to wait", "waiting"], answerIndex: 2, reasons: ["waits 不能放在受詞 Ben 後作補語。", "waited 會成為另一個未連接的過去式。", "to wait 表示 Amy 要 Ben 在門邊等。", "waiting 少了 ask someone to do 所需的不定詞形式。"], reviews: ["Ben 既是 asked 的受詞，也是 wait 的執行者。", "第三項維持 ask + 人 + to + 原形的結構。"], cognitiveProcess: ["u22-s149-assign-wait-action-to-object", "build-ask-person-infinitive"], representationType: "object-controlled-infinitive", misconceptionTargets: ["treat-asked-and-waited-as-serial-verbs"] },
    { stem: "We would like ___ two bowls of soup.", options: ["ordered", "ordering", "orders", "to order"], answerIndex: 3, reasons: ["ordered 是過去式，不能接 would like。", "ordering 不符合 would like 在此表達點餐意願的形式。", "orders 帶人稱變化，也不接在 would like 後。", "to order 正確補出想點的內容。"], reviews: ["would like 是較有禮貌的想要表達。", "第四項用 to order，且 two bowls 與複數數量一致。"], cognitiveProcess: ["u22-s149-form-polite-order-intention", "choose-would-like-to-order"], representationType: "polite-request-infinitive", misconceptionTargets: ["use-gerund-after-would-like"] },
    { stem: "Leo chose ___ because he did not want to take the bus.", options: ["to walk", "walking", "walked", "walks"], answerIndex: 0, reasons: ["to walk 說明 Leo 選擇的做法。", "walking 在此不符合 chose 的補語形式。", "walked 是過去式，不能直接跟在 chose 後。", "walks 是現在式限定動詞，與 chose 結構不合。"], reviews: ["不想搭公車提供選擇步行的理由。", "第一項由 chose 控制，後面的 to take 不會改變空格形式。"], cognitiveProcess: ["u22-s149-resolve-choice-against-bus-alternative", "resist-nearby-infinitive-attraction"], representationType: "choice-versus-alternative-infinitive", misconceptionTargets: ["copy-form-from-because-clause"] },
    { stem: "Ben asked for fresh air, and Nora agreed ___ the window.", options: ["opening", "to open", "opened", "opens"], answerIndex: 1, reasons: ["opening 不符合 agreed 後表示同意去做的形式。", "to open 表示 Nora 同意開窗。", "opened 與 agreed 都是過去式，不能直接相接。", "opens 是現在式，也不能作 agreed 的補語。"], reviews: ["Ben 的請求提供 Nora 同意內容的背景。", "第二項使用 agree to do，並由 Nora 執行開窗動作。"], cognitiveProcess: ["u22-s149-link-agreement-to-requested-action", "exclude-double-past-verbs"], representationType: "agreed-request-infinitive", misconceptionTargets: ["interpret-agreed-as-gerund-controller"] },
    { stem: "Ben promised ___ before nine.", options: ["came home", "coming home", "to come home", "comes home"], answerIndex: 2, reasons: ["came home 會形成未連接的過去式子句片段。", "coming home 不符合 promise 後的承諾內容形式。", "to come home 表示 Ben 承諾九點前回家。", "comes home 帶第三人稱變化，不能接 promised。"], reviews: ["承諾內容是 Ben 自己在九點前回家。", "第三項讓 promised 保留過去式，come 維持不定詞原形。"], cognitiveProcess: ["u22-s149-identify-agent-of-promised-return", "encode-return-home-commitment"], representationType: "promise-infinitive-cloze", misconceptionTargets: ["place-past-come-after-promised"] },
    { stem: "Mia expects the bus ___ soon.", options: ["arriving", "arrived", "arrives", "to arrive"], answerIndex: 3, reasons: ["arriving 不能直接作 the bus 後的預期內容。", "arrived 會把尚未發生的事寫成過去。", "arrives 是限定動詞，若使用須另有完整子句結構。", "to arrive 讓 the bus 成為 arrive 的行動主體。"], reviews: ["soon 與 expects 表示對接下來事件的預期。", "第四項採 expect + 受詞 + to 原形，答案唯一。"], cognitiveProcess: ["u22-s149-build-expect-object-infinitive", "align-bus-with-arrive-action"], representationType: "expect-event-infinitive", misconceptionTargets: ["place-finite-arrives-after-object"] },
  ]),
  ...skillQuestions("150", [
    { stem: "Ben enjoys ___ to music after dinner.", options: ["listening", "to listened", "listened", "listens"], answerIndex: 0, reasons: ["listening 是 enjoy 後表示喜愛活動的動名詞。", "to listened 把 to 後錯接過去式，也不符合 enjoy 的搭配。", "listened 不能直接作 enjoys 的補語。", "listens 是另一個帶人稱變化的動詞。"], reviews: ["after dinner 交代活動時間，不代表正在進行。", "第一項由 enjoys 的固定搭配決定，to music 屬於 listen 的搭配。"], cognitiveProcess: ["u22-s150-complete-enjoyed-music-activity", "distinguish-gerund-from-progressive"], representationType: "enjoy-listening-gerund-cloze", misconceptionTargets: ["treat-ing-only-as-progressive"] },
    { stem: "Amy finished ___ the dishes before eight.", options: ["to wash", "washing", "washed", "washes"], answerIndex: 1, reasons: ["to wash 不符合 finish 後的補語形式。", "washing 指 Amy 在八點前完成的工作。", "washed 與 finished 都是過去式，不能直接相接。", "washes 是現在式限定動詞，不能作 finished 的補語。"], reviews: ["before eight 說明完成時間，時態已在 finished。", "第二項把洗碗當成被完成的活動。"], cognitiveProcess: ["u22-s150-link-finish-to-completed-task", "keep-time-marking-on-main-verb"], representationType: "finish-task-gerund-cloze", misconceptionTargets: ["repeat-past-tense-on-complement"] },
    { stem: "The baby keeps ___ even after the door closes.", options: ["to cry", "cried", "crying", "cries"], answerIndex: 2, reasons: ["to cry 不是 keep 表示持續時的常用補語。", "cried 是過去式，不能接在 keeps 後。", "crying 表示關門後哭聲仍持續。", "cries 不能直接作 keeps 的補語。"], reviews: ["even after the door closes 顯示哭泣沒有停止。", "第三項同時符合 keep doing 與延續語意。"], cognitiveProcess: ["u22-s150-infer-continuation-after-door-event", "select-keeps-crying"], representationType: "continued-action-gerund", misconceptionTargets: ["replace-continued-action-with-second-finite-verb"] },
    { stem: "Nora practices ___ English with Leo every day.", options: ["to speak", "spoke", "speaks", "speaking"], answerIndex: 3, reasons: ["to speak 不符合 practice 後的固定形式。", "spoke 是過去式，與 every day 的習慣也不合。", "speaks 不能直接接在 practices 後。", "speaking 是 Nora 每天練習的活動。"], reviews: ["practices 已承擔第三人稱單數變化。", "第四項不受 every day 影響，仍採動名詞。"], cognitiveProcess: ["u22-s150-map-practice-to-language-activity", "prevent-double-third-person-marking"], representationType: "practice-skill-gerund", misconceptionTargets: ["add-s-to-complement-after-practices"] },
    { stem: "Would you mind ___ the window?", options: ["closing", "to close", "closed", "closes"], answerIndex: 0, reasons: ["closing 是 mind 後用來詢問的動名詞。", "to close 不符合 Would you mind 的結構。", "closed 是過去式，不能作 mind 的補語。", "closes 帶人稱變化，也不能放在此處。"], reviews: ["句子詢問對方是否介意關窗，而不是描述已關窗。", "第一項是唯一合乎 mind doing 的形式。"], cognitiveProcess: ["u22-s150-form-mind-request", "reject-infinitive-in-polite-mind-frame"], representationType: "mind-request-gerund", misconceptionTargets: ["apply-polite-to-infinitive-analogy"] },
    { stem: "Mia does not mind waiting ten more minutes. What does she mean?", options: ["She has already left.", "She is willing to wait.", "She forgot the time.", "She wants everyone to leave."], answerIndex: 1, reasons: ["does not mind 不能推出她已離開。", "不介意等待表示她願意再等十分鐘。", "句子沒有說 Mia 忘記時間。", "她的態度針對自己等待，沒有要求別人離開。"], reviews: ["否定 mind 要理解為「不介意」，不是拒絕。", "第二項忠實呈現態度，未添加原因。"], cognitiveProcess: ["u22-s150-interpret-negative-mind-attitude", "separate-willingness-from-action-result"], representationType: "mind-dialogue-meaning-inference", misconceptionTargets: ["read-not-mind-as-refusal"] },
    { stem: "The sign says, 'Please avoid ___ on the wet floor.'", options: ["to run", "ran", "running", "runs"], answerIndex: 2, reasons: ["to run 不符合 avoid 後的補語形式。", "ran 是過去式，無法補出告示禁止的活動。", "running 表示應避免在濕地板上奔跑。", "runs 是第三人稱形式，不能接 avoid。"], reviews: ["告示要求人們避開某項行為，並非敘述過去事件。", "第三項符合 avoid doing，也和 wet floor 的安全情境一致。"], cognitiveProcess: ["u22-s150-interpret-wet-floor-warning", "complete-avoid-with-running"], representationType: "safety-sign-gerund-cloze", misconceptionTargets: ["use-infinitive-after-avoid"] },
    { stem: "Leo gave up ___ for the lost key after an hour.", options: ["to look", "looked", "looks", "looking"], answerIndex: 3, reasons: ["to look 不符合 give up 後表示放棄活動的形式。", "looked 是過去式，不能直接接 gave up。", "looks 是現在式，與 after an hour 的過去情境不合。", "looking 表示 Leo 放棄繼續找鑰匙。"], reviews: ["after an hour 顯示搜尋持續過，後來停止。", "第四項讓 looking 成為被放棄的活動。"], cognitiveProcess: ["u22-s150-map-give-up-to-ended-search", "retain-gerund-after-phrasal-controller"], representationType: "abandoned-search-gerund", misconceptionTargets: ["treat-up-as-purpose-marker"] },
    { stem: "Amy suggested ___ the bus because it was raining.", options: ["taking", "to take", "took", "takes"], answerIndex: 0, reasons: ["taking 是 suggested 後提出的做法。", "to take 不符合 suggest 在此的補語形式。", "took 會把建議錯寫成已發生事件。", "takes 是限定動詞，不能直接接 suggested。"], reviews: ["下雨是提出搭公車方案的背景。", "第一項只表示建議，沒有聲稱大家最後真的搭車。"], cognitiveProcess: ["u22-s150-link-suggestion-to-rain-plan", "avoid-turning-advice-into-result"], representationType: "suggested-action-gerund", misconceptionTargets: ["use-suggest-to-infinitive"] },
    { stem: "Ben spends the afternoon ___ a paper plane.", options: ["to build", "building", "built", "builds"], answerIndex: 1, reasons: ["to build 不能接在 spends the afternoon 後描述時間用途。", "building 說明 Ben 下午進行的活動。", "built 是過去式，不能直接接在 spends 後。", "builds 會形成兩個帶人稱變化的動詞。"], reviews: ["spend time doing 表示時間花在哪項活動上。", "第二項符合結構，但不必推論紙飛機一定完成。"], cognitiveProcess: ["u22-s150-assign-afternoon-time-to-building", "separate-duration-from-completion"], representationType: "spend-time-gerund", misconceptionTargets: ["infer-completion-from-spent-time"] },
    { stem: "Nora is busy ___ dinner, so she cannot answer the phone.", options: ["to cook", "cooked", "cooking", "cooks"], answerIndex: 2, reasons: ["to cook 不符合 be busy 後描述正在忙的活動。", "cooked 是過去式，不能接在 is busy 後。", "cooking 說明 Nora 正忙著準備晚餐。", "cooks 是一般現在式，無法作 busy 的補語。"], reviews: ["cannot answer the phone 提供她當下被事情占用的證據。", "第三項使用 busy doing，不把 cooking 誤當主要動詞。"], cognitiveProcess: ["u22-s150-infer-busy-activity-from-phone-context", "complete-be-busy-with-gerund"], representationType: "busy-context-gerund", misconceptionTargets: ["place-finite-cooks-after-busy"] },
    { stem: "The rain does not stop, but the players keep ___.", options: ["to practice", "practiced", "practices", "practicing"], answerIndex: 3, reasons: ["to practice 不符合 keep 表示持續時的搭配。", "practiced 是過去式，不能接在 keep 後。", "practices 是第三人稱形式，結構錯誤。", "practicing 表示球員在雨中仍持續練習。"], reviews: ["but 顯示雨勢未停與持續練習形成反差。", "第四項把 practicing 指定為延續中的活動。"], cognitiveProcess: ["u22-s150-read-persistence-under-rain", "select-gerund-as-continued-action"], representationType: "keep-continuation-gerund", misconceptionTargets: ["use-infinitive-after-keep"] },
  ]),
  ...skillQuestions("151", [
    { stem: "___ carefully in class helps Leo learn.", options: ["Listening", "Listened", "Listens", "To listened"], answerIndex: 0, reasons: ["Listening carefully in class 整體作 helps 的主詞。", "Listened 是過去式，無法在此把活動當主詞。", "Listens 會像缺少主詞的限定動詞。", "to 後不能接過去式 listened。"], reviews: ["句子的主要動詞是 helps，前面需要一個活動主詞。", "第一項把專心聆聽當成一件事，並與 helps 搭配。"], cognitiveProcess: ["u22-s151-nominalize-careful-listening", "identify-activity-before-helps"], representationType: "gerund-subject-cloze", misconceptionTargets: ["read-leading-ing-as-progressive"] },
    { stem: "___ before bed helps Mia sleep.", options: ["To reading", "Reading", "Reads", "Read"], answerIndex: 1, reasons: ["to 後不能直接接 reading 形成這個主詞。", "Reading before bed 是完整的活動主詞。", "Reads 缺少執行閱讀的人，不能作此句開頭。", "Read 會像命令，無法與 helps 組成題意。"], reviews: ["before bed 屬於 reading 活動的一部分。", "第二項讓睡前閱讀成為帶來幫助的原因。"], cognitiveProcess: ["u22-s151-frame-bedtime-reading-as-subject", "separate-command-read-from-gerund"], representationType: "time-modified-gerund-subject", misconceptionTargets: ["treat-base-verb-as-noun-activity"] },
    { stem: "___ up early takes practice.", options: ["Get", "Gets", "Getting", "Got"], answerIndex: 2, reasons: ["Get 會形成命令式開頭，後面卻又出現 takes。", "Gets 是限定動詞，句中沒有它的主詞。", "Getting up early 整體表示早起這項活動。", "Got 是過去式，不能把一般活動當主詞。"], reviews: ["takes 是主要動詞，因此空格部分應先構成主詞。", "第三項把 get up 轉成動名詞片語，語意完整。"], cognitiveProcess: ["u22-s151-build-early-rising-subject", "locate-main-verb-takes"], representationType: "phrasal-gerund-subject", misconceptionTargets: ["mistake-particle-up-for-main-structure"] },
    { stem: "___ music late at night makes the baby wake up.", options: ["Played", "Plays", "Play", "Playing"], answerIndex: 3, reasons: ["Played 是過去式，不能作 makes 的活動主詞。", "Plays 缺少自己的主詞，且會和 makes 衝突。", "Play 會像命令句開頭，不符合後續結構。", "Playing music late at night 整體是 makes 的主詞。"], reviews: ["題目談的是深夜播放音樂這件事造成的影響。", "第四項讓活動成為單數主詞，所以後面用 makes。"], cognitiveProcess: ["u22-s151-cast-late-music-as-cause", "pair-gerund-activity-with-makes"], representationType: "causal-gerund-subject", misconceptionTargets: ["insert-second-finite-verb-before-makes"] },
    { stem: "Reading books ___ useful for this class.", options: ["is", "are", "be", "being"], answerIndex: 0, reasons: ["is 配合 Reading books 這一項活動。", "are 只看見 books 的複數，忽略完整主詞中心。", "be 是原形，句中沒有助動詞可搭配。", "being 不能單獨作此句的主要動詞。"], reviews: ["books 是 reading 的受詞，不是主要動詞的主詞中心。", "第一項把整個閱讀活動視為單數。"], cognitiveProcess: ["u22-s151-find-head-of-reading-books", "choose-singular-copula-for-activity"], representationType: "gerund-phrase-agreement", misconceptionTargets: ["agree-verb-with-gerund-object"] },
    { stem: "Cooking and cleaning ___ time.", options: ["takes", "take", "taking", "to take"], answerIndex: 1, reasons: ["takes 適合單一活動，這裡卻有兩項並列主詞。", "take 配合 Cooking and cleaning 的複數概念。", "taking 不能作這個句子的主要動詞。", "to take 缺少能引入不定詞的前置結構。"], reviews: ["and 連接 cooking 與 cleaning 兩件不同工作。", "第二項依複數主詞使用原形 take。"], cognitiveProcess: ["u22-s151-count-two-gerund-subjects", "shift-takes-to-plural-take"], representationType: "compound-gerund-subject-agreement", misconceptionTargets: ["treat-all-leading-gerunds-as-singular"] },
    { stem: "Helping other people ___ Amy happy.", options: ["make", "making", "makes", "to make"], answerIndex: 2, reasons: ["make 不符合單一活動主詞的第三人稱形式。", "making 不能接在 Helping other people 後作主要動詞。", "makes 配合 Helping other people 這件事。", "to make 會讓句子缺少限定動詞。"], reviews: ["other people 是 helping 的受詞，並未使主詞變複數。", "第三項表達助人這項活動帶給 Amy 的感受。"], cognitiveProcess: ["u22-s151-isolate-object-inside-helping-phrase", "apply-singular-makes-to-whole-activity"], representationType: "object-bearing-gerund-agreement", misconceptionTargets: ["use-nearby-plural-noun-for-agreement"] },
    { stem: "Using both hands makes carrying this box easy. What makes the job easy?", options: ["The size of the box", "The place of the box", "Using one hand", "Using both hands"], answerIndex: 3, reasons: ["句子沒有提到箱子的大小。", "箱子所在位置也不是 makes 的主詞。", "原文說的是 both hands，不是 one hand。", "Using both hands 是 makes 的完整主詞。"], reviews: ["問題要求找出造成工作變容易的活動。", "第四項直接對應句首動名詞主詞，沒有把 hands 單獨拆出。"], cognitiveProcess: ["u22-s151-recover-gerund-subject-as-cause", "distinguish-whole-activity-from-inner-noun"], representationType: "gerund-subject-cause-identification", misconceptionTargets: ["select-inner-noun-instead-of-whole-phrase"] },
    { stem: "Which sentence uses an activity as its subject and says the activity takes time?", options: ["Building a table takes time.", "Ben is building a table.", "Build the table today.", "Ben wants to build a table."], answerIndex: 0, reasons: ["Building a table 是主詞，takes time 說明這項活動所需時間。", "第二句的主詞是 Ben，building 是進行式的一部分。", "第三句是命令句，沒有把活動當成被說明的主詞。", "第四句談 Ben 的意願，主詞仍是 Ben。"], reviews: ["題目同時限定活動作主詞並由 takes time 描述。", "第一項符合兩條件，其餘各有明確人稱主詞或命令語氣。"], cognitiveProcess: ["u22-s151-classify-building-as-gerund-subject", "separate-nominal-gerund-from-progressive"], representationType: "gerund-role-sentence-classification", misconceptionTargets: ["group-all-ing-forms-as-subjects"] },
    { stem: "Swimming and running ___ good for the heart.", options: ["is", "are", "being", "to be"], answerIndex: 1, reasons: ["is 忽略 and 連接兩項不同運動。", "are 配合 Swimming and running 的複數主詞。", "being 不能單獨作主要動詞。", "to be 會讓句子沒有時態動詞。"], reviews: ["題目列出游泳與跑步兩項活動，不是一個帶受詞的片語。", "第二項的複數 be 動詞與並列主詞一致。"], cognitiveProcess: ["u22-s151-distinguish-two-exercises-from-one-phrase", "select-are-for-coordinated-gerunds"], representationType: "two-activity-copula-agreement", misconceptionTargets: ["default-gerund-subject-to-is"] },
    { stem: "It is fun to cook with friends. Which sentence gives the same idea with the activity first?", options: ["Friends are cooking for fun.", "Cook with friends for fun.", "Cooking with friends is fun.", "To friends, cooking is fun."], answerIndex: 2, reasons: ["第一句改成朋友正在為了樂趣煮飯，並非原句評價。", "第二句是命令，沒有保留 is fun 的判斷。", "Cooking with friends 作主詞，完整保留原意。", "To friends 改變句法關係，也未明確表達一起煮飯。"], reviews: ["改寫要求把活動移到句首，不能改事件或語氣。", "第三項用動名詞主詞對應原來的 to cook 內容。"], cognitiveProcess: ["u22-s151-transform-it-to-gerund-subject", "preserve-fun-evaluation"], representationType: "extraposition-to-gerund-paraphrase", misconceptionTargets: ["turn-evaluation-into-command"] },
    { stem: "Reading the two notes ___ only five minutes.", options: ["take", "are taking", "have taken", "takes"], answerIndex: 3, reasons: ["take 會把完整活動錯當成複數主詞。", "are taking 把 two notes 誤當主詞，且變成進行式。", "have taken 也依 notes 錯配複數，並改變時間意義。", "takes 配合 Reading the two notes 這一項活動。"], reviews: ["the two notes 是 reading 的受詞，數量不控制主要動詞。", "第四項說完成這項閱讀活動需要五分鐘。"], cognitiveProcess: ["u22-s151-resist-two-notes-number-attraction", "assign-duration-to-reading-event"], representationType: "duration-gerund-subject-agreement", misconceptionTargets: ["let-object-number-control-verb"] },
  ]),
  ...skillQuestions("152", [
    { stem: "Mia wants ___ before dinner.", options: ["to read", "to reading", "to reads", "to readed"], answerIndex: 0, reasons: ["to read 是 want 後的不定詞，read 保持原形。", "to reading 把不定詞標記後錯接動名詞。", "to reads 在 to 後多加第三人稱字尾。", "readed 不是 read 的正確形式，也不能放在 to 後。"], reviews: ["wants 是控制動詞，此處 to 不表示方向。", "第一項符合 to 加原形，不受 Mia 的人稱影響。"], cognitiveProcess: ["u22-s152-recognize-infinitive-to-after-wants", "enforce-base-read-after-marker"], representationType: "infinitive-marker-form-cloze", misconceptionTargets: ["treat-to-as-preposition-before-gerund"] },
    { stem: "Ben walked to school. Where did he walk?", options: ["In the morning", "To school", "For a class", "With a friend"], answerIndex: 1, reasons: ["句中沒有提供 morning 這個時間。", "to school 直接指出 Ben 前往的地點。", "原文未把上課寫成行走原因。", "句中也沒有同行的朋友。"], reviews: ["school 是地點名詞，因此 to 在此表方向。", "第二項回答 where，沒有把方向誤判成目的。"], cognitiveProcess: ["u22-s152-interpret-to-before-school", "separate-destination-from-purpose"], representationType: "prepositional-to-destination-reading", misconceptionTargets: ["label-every-to-as-purpose"] },
    { stem: "Nora looks forward to ___ Leo again.", options: ["see", "saw", "seeing", "sees"], answerIndex: 2, reasons: ["see 原形不能接在 look forward to 後。", "saw 是過去式，無法作介系詞 to 的補語。", "seeing 是介系詞 to 後的動名詞。", "sees 帶人稱變化，也不能接在此片語後。"], reviews: ["look forward to 是完整搭配，不能把 to 單獨拆成不定詞。", "第三項表示 Nora 期待再次見到 Leo。"], cognitiveProcess: ["u22-s152-preserve-look-forward-to-unit", "choose-gerund-after-prepositional-to"], representationType: "fixed-prepositional-to-gerund", misconceptionTargets: ["split-look-forward-to-as-infinitive"] },
    { stem: "After a month, Amy is used to ___ up at six.", options: ["get", "to get", "got", "getting"], answerIndex: 3, reasons: ["get 原形不能直接接在介系詞 to 後。", "to get 會多出第二個 to，且改變結構。", "got 是過去式，不能作 to 的補語。", "getting 表示 Amy 已習慣六點起床。"], reviews: ["After a month 提供逐漸習慣新作息的背景。", "第四項屬 be used to doing，不是過去常做的 used to do。"], cognitiveProcess: ["u22-s152-read-acclimation-context", "distinguish-be-used-to-getting"], representationType: "be-used-to-gerund-cloze", misconceptionTargets: ["confuse-accustomed-with-past-habit"] },
    { stem: "Leo went to the kitchen to get water. Which words tell why he went there?", options: ["to get water", "to the kitchen", "Leo went", "the kitchen"], answerIndex: 0, reasons: ["to get water 是原形動詞不定詞，說明前往目的。", "to the kitchen 只指出前往地點。", "Leo went 是主要事件，不是原因內容。", "the kitchen 單獨只是地點名稱。"], reviews: ["同句兩個 to 必須逐一判斷，不能視為同功能。", "第一項回答 why；第二項只能回答 where。"], cognitiveProcess: ["u22-s152-contrast-two-to-functions-in-one-sentence", "select-why-answer-not-where-answer"], representationType: "dual-to-purpose-identification", misconceptionTargets: ["assign-purpose-to-first-to"] },
    { stem: "Amy wrote to Leo to invite him. Which words name the person who got the note?", options: ["to invite", "to Leo", "Amy wrote", "invite him"], answerIndex: 1, reasons: ["to invite 說明 Amy 寫信的目的。", "to Leo 指出紙條傳給 Leo。", "Amy wrote 只包含寫信者與行動。", "invite him 是目的內容的一部分，不是收訊者片語。"], reviews: ["Leo 是 wrote to 的對象；him 也指 Leo，但題目要找完整片語。", "第二項中的 to 是介系詞，後接人名。"], cognitiveProcess: ["u22-s152-locate-note-recipient", "separate-recipient-to-from-purpose-to"], representationType: "dual-to-recipient-identification", misconceptionTargets: ["choose-purpose-phrase-for-recipient"] },
    { stem: "Mia used to ___ to school, but now she takes the bus.", options: ["walking", "walked", "walk", "walks"], answerIndex: 2, reasons: ["walking 適用於 be used to doing，不是此處過去習慣。", "walked 不能接在 used to 後。", "walk 是 used to 後的原形，表示以前常走路。", "walks 帶第三人稱字尾，不能放在 to 後。"], reviews: ["but now 提供過去習慣已改變的對比。", "第三項是 used to do，不是 is used to doing。"], cognitiveProcess: ["u22-s152-use-now-contrast-to-detect-past-habit", "choose-base-verb-after-used-to"], representationType: "used-to-past-habit-cloze", misconceptionTargets: ["merge-used-to-with-be-used-to"] },
    { stem: "Ben is used to taking the early bus now. What can we know?", options: ["He never takes an early bus.", "He took it only once.", "He will stop taking buses.", "Taking the early bus is no longer new to him."], answerIndex: 3, reasons: ["is used to 不表示 Ben 從不搭早班車。", "已習慣通常不只一次經驗，句子也未說 only once。", "原文沒有他將停止搭車的計畫。", "is used to taking 表示這件事對他已不陌生。"], reviews: ["now 確認目前的習慣狀態，不是已結束的過去習慣。", "第四項以日常語意正確解釋 be used to。"], cognitiveProcess: ["u22-s152-infer-accustomed-state", "reject-past-habit-and-future-inferences"], representationType: "be-used-to-meaning-inference", misconceptionTargets: ["read-is-used-to-as-discontinued-habit"] },
    { stem: "Nora spoke to Amy to ask for help. Which words show who listened to Nora?", options: ["to Amy", "to ask", "for help", "Nora spoke"], answerIndex: 0, reasons: ["to Amy 指出 Nora 說話的對象。", "to ask 是她開口的目的，不是聽者。", "for help 說明所求內容，沒有命名人物。", "Nora spoke 只指出說話者。"], reviews: ["Amy 位在介系詞 to 後，是接收話語的人。", "第一項與 to ask 的目的功能形成清楚對比。"], cognitiveProcess: ["u22-s152-identify-listener-after-preposition", "disentangle-person-object-from-goal"], representationType: "speech-recipient-to-analysis", misconceptionTargets: ["mistake-purpose-verb-for-listener"] },
    { stem: "The class looks forward to watching the science show next week. What can we know?", options: ["They watched it last week.", "They are happy about the coming show.", "They want the show to end early.", "They have decided not to watch it."], answerIndex: 1, reasons: ["next week 表示觀看尚未發生，不是上週完成。", "looks forward to 表示學生期待即將到來的科學表演。", "期待觀看不能推出希望表演提早結束。", "原句表達期待，與決定不看相反。"], reviews: ["此題改考固定片語的實際語意，不再重複填 watching。", "第二項保留未來時間與正向期待，沒有加入結果。"], cognitiveProcess: ["u22-s152-infer-attitude-from-look-forward-to", "preserve-future-event-status"], representationType: "look-forward-meaning-inference", misconceptionTargets: ["read-forward-as-time-direction-only"] },
    { stem: "Nora wrote a note to thank Ben. What does to thank Ben explain?", options: ["Where Nora wrote", "When Nora wrote", "Why Nora wrote", "Who wrote the note"], answerIndex: 2, reasons: ["to thank Ben 沒有提供地點。", "不定詞片語也沒有交代書寫時間。", "它說明 Nora 寫紙條是為了感謝 Ben。", "寫信者已由主詞 Nora 指出。"], reviews: ["to 後接原形 thank，且語意能回答 why。", "第三項判定它是目的不定詞，而非方向介系詞。"], cognitiveProcess: ["u22-s152-classify-thank-infinitive-by-question-role", "map-infinitive-to-why-not-where"], representationType: "purpose-to-function-classification", misconceptionTargets: ["equate-to-with-location-only"] },
    { stem: "The answer to the question helped Mia decide to stay. What did Mia decide to do?", options: ["Answer the question", "Help another person", "Read the answer", "Stay"], answerIndex: 3, reasons: ["The answer 是幫助她決定的事物，不是她要做的動作。", "helped Mia 表示 Mia 得到幫助，沒有說她要幫別人。", "句中沒有說 Mia 決定閱讀答案。", "to stay 補出 Mia 決定留下。"], reviews: ["第一個 to 後接名詞，第二個 to 後接原形動詞。", "第四項還原 decide to stay 的實際內容。"], cognitiveProcess: ["u22-s152-parse-noun-to-and-infinitive-to", "locate-decision-content"], representationType: "mixed-to-functions-reading", misconceptionTargets: ["treat-identical-spelling-as-identical-role"] },
  ]),
  ...skillQuestions("153", [
    { stem: "Leo plans ___ Japan and enjoys ___ about the country.", options: ["to visit; learning", "visiting; to learn", "visit; learn", "visited; learned"], answerIndex: 0, reasons: ["plans to visit 與 enjoys learning 分別符合兩個控制動詞。", "plan 不接 visiting，enjoy 也不接 to learn。", "兩個原形都缺少各自需要的形式。", "visited 與 learned 把計畫和喜好錯寫成兩個過去動作。"], reviews: ["拜訪日本是 Leo 的計畫，了解該國是他喜愛的活動。", "第一項同時使用不定詞與動名詞，沒有把未來計畫說成已完成。"], cognitiveProcess: ["u22-s153-integrate-plan-and-enjoy-complements", "keep-country-learning-as-current-interest"], representationType: "plan-enjoy-double-cloze", misconceptionTargets: ["swap-plan-and-enjoy-complement-forms"] },
    { stem: "Mia practices speaking every day because she hopes to speak clearly. Which sentence keeps both facts?", options: ["Mia practices to speak and hopes speaking clearly.", "Mia practices speaking and hopes to speak clearly.", "Mia practiced speak and hopes speaking.", "Mia speaks clearly and no longer practices."], answerIndex: 1, reasons: ["practice 與 hope 的補語形式被顛倒。", "practices speaking 與 hopes to speak 正確保留練習和希望。", "practiced speak 與 hopes speaking 都不符合搭配。", "原文沒有說 Mia 已說得清楚或停止練習。"], reviews: ["題幹提供每天練習與希望進步兩項事實。", "第二項沒有把希望誤寫成結果，也維持兩種補語形式。"], cognitiveProcess: ["u22-s153-preserve-practice-and-hope-facts", "reject-result-inflation-in-paraphrase"], representationType: "mixed-complement-sentence-paraphrase", misconceptionTargets: ["reverse-practice-and-hope-forms"] },
    { stem: "Ben finished ___ the room and decided ___ home.", options: ["to clean; going", "clean; go", "cleaning; to go", "cleaned; went"], answerIndex: 2, reasons: ["finish 不接 to clean，decide 也不接 going。", "兩個原形都缺少各自所需的補語標記。", "finished cleaning 與 decided to go 分別符合兩種搭配。", "cleaned 與 went 都是限定過去式，不能直接作補語。"], reviews: ["同句兩個控制動詞必須分開判斷，不能追求形式相同。", "第三項先用動名詞，再用不定詞，且事件順序合理。"], cognitiveProcess: ["u22-s153-solve-two-controller-complements", "assign-gerund-then-infinitive"], representationType: "dual-complement-form-cloze", misconceptionTargets: ["force-parallel-complements-across-different-verbs"] },
    { stem: "Nora enjoys ___ stories and hopes ___ one soon.", options: ["to read; writing", "read; write", "readed; wrote", "reading; to write"], answerIndex: 3, reasons: ["enjoy 不接 to read，hope 也不接 writing。", "兩個原形缺少 enjoy 與 hope 要求的結構。", "readed 不是正確形式，wrote 也不能接 hopes。", "enjoys reading 與 hopes to write 都正確。"], reviews: ["reading 是 Nora 喜愛的活動，to write 是她的希望。", "第四項依兩個控制動詞分配形式，沒有把 soon 當成形式線索。"], cognitiveProcess: ["u22-s153-contrast-enjoy-and-hope-complements", "map-present-interest-to-future-goal"], representationType: "mixed-preference-hope-complements", misconceptionTargets: ["swap-gerund-and-infinitive-between-verbs"] },
    { stem: "Amy needs ___ the report and enjoys ___ with her team.", options: ["to finish; working", "finishing; to work", "finish; work", "finished; worked"], answerIndex: 0, reasons: ["needs to finish 與 enjoys working 各自符合搭配。", "need 不接 finishing，enjoy 也不接 to work。", "兩個原形都不能直接作前面動詞的補語。", "finished 與 worked 把需要和喜好錯寫成已完成事件。"], reviews: ["完成報告是必要工作，與團隊合作則是 Amy 喜歡的活動。", "第一項依 needs 與 enjoys 分別選用不定詞和動名詞。"], cognitiveProcess: ["u22-s153-integrate-need-and-enjoy-complements", "separate-required-task-from-liked-activity"], representationType: "need-enjoy-double-cloze", misconceptionTargets: ["use-same-form-after-need-and-enjoy"] },
    { stem: "The rain keeps ___, but Nora hopes ___ soon.", options: ["to fall; leaving", "falling; to leave", "fell; leave", "falls; left"], answerIndex: 1, reasons: ["keep 不接 to fall，hope 也不接 leaving。", "keeps falling 與 hopes to leave 同時符合形式與句意。", "fell 與 leave 都不能直接作前面動詞的補語。", "falls 與 left 是限定動詞，無法填入兩個補語位置。"], reviews: ["雨持續落下是現況，Nora 離開則是尚未實現的希望。", "第二項以動名詞表示持續活動，再以不定詞表示希望內容。"], cognitiveProcess: ["u22-s153-contrast-continuing-rain-with-leaving-hope", "assign-gerund-then-infinitive-across-but"], representationType: "keep-hope-double-cloze", misconceptionTargets: ["swap-keep-and-hope-complements"] },
    { stem: "Nora asks, 'Would you mind ___ the music down? I plan ___ now.'", options: ["to turn; studying", "turned; study", "turning; to study", "turns; studied"], answerIndex: 2, reasons: ["mind 不接 to turn，plan 也不接 studying。", "turned 與 study 都不符合各自的補語位置。", "mind turning 與 plan to study 正確表達請求和計畫。", "turns 與 studied 是限定動詞，不能直接接 mind、plan。"], reviews: ["Nora 先提出降低音量的請求，再交代要讀書的計畫。", "第三項依 mind 與 plan 使用不同形式，兩個行動者也都清楚。"], cognitiveProcess: ["u22-s153-combine-mind-request-with-study-plan", "assign-gerund-and-infinitive-in-dialogue"], representationType: "mind-plan-dialogue-double-cloze", misconceptionTargets: ["let-would-force-infinitive-after-mind"] },
    { stem: "Mia chose ___ and avoided ___ in the rain.", options: ["walking; to drive", "walk; drive", "walked; drove", "to walk; driving"], answerIndex: 3, reasons: ["choose 不接 walking，avoid 也不接 to drive。", "兩個原形都缺少必要形式。", "walked 與 drove 不能直接接在 chose、avoided 後。", "chose to walk 與 avoided driving 各自符合搭配。"], reviews: ["第一個動作是選擇，第二個是避開的行為。", "第四項分別使用不定詞與動名詞，並保留下雨情境。"], cognitiveProcess: ["u22-s153-coordinate-choice-and-avoidance", "assign-opposite-complement-forms"], representationType: "choice-avoidance-double-cloze", misconceptionTargets: ["reverse-choose-and-avoid-forms"] },
    { stem: "Amy hopes ___ the race and practices ___ every morning.", options: ["to win; running", "winning; to run", "win; run", "won; ran"], answerIndex: 0, reasons: ["hopes to win 與 practices running 分別符合兩個搭配。", "hope 不接 winning，practice 也不接 to run。", "兩個原形都少了必要的不定詞或動名詞形式。", "won 與 ran 是過去式，不能作目前希望與練習的補語。"], reviews: ["希望勝出是目標，每天跑步是反覆練習的活動。", "第一項同時符合形式與兩件事的語意關係。"], cognitiveProcess: ["u22-s153-link-race-goal-to-training-routine", "pair-hope-infinitive-practice-gerund"], representationType: "goal-training-complement-pair", misconceptionTargets: ["match-both-complements-by-surface-parallelism"] },
    { stem: "Leo enjoys to cook for his family. Change only the wrong part.", options: ["to cooking", "cooking", "cooked", "cooks"], answerIndex: 1, reasons: ["to cooking 仍保留不必要的 to。", "cooking 正確接在 enjoys 後。", "cooked 是過去式，不能作 enjoys 的補語。", "cooks 是限定動詞，會和 enjoys 衝突。"], reviews: ["題目只修補語，不改 Leo 或句子時間。", "第二項形成 enjoys cooking，原意仍是喜歡為家人煮飯。"], cognitiveProcess: ["u22-s153-repair-enjoy-to-cook", "remove-to-and-form-gerund"], representationType: "targeted-complement-error-repair", misconceptionTargets: ["retain-to-before-gerund"] },
    { stem: "Nora decided ___ for one more day and finished ___ her bag.", options: ["staying; to pack", "stay; pack", "to stay; packing", "stayed; packed"], answerIndex: 2, reasons: ["decide 不接 staying，finish 也不接 to pack。", "原形 stay 與 pack 都缺少所需結構。", "decided to stay 與 finished packing 都正確。", "兩個過去式不能直接作 decided、finished 的補語。"], reviews: ["留下是 Nora 的決定，收好行李是她完成的工作。", "第三項依事件功能而非 one more day 的時間詞選形式。"], cognitiveProcess: ["u22-s153-separate-stay-decision-from-packing-completion", "map-two-actions-to-distinct-controllers"], representationType: "decision-completion-double-cloze", misconceptionTargets: ["use-past-forms-after-past-controllers"] },
    { stem: "Ben wants ___ early because he hopes to avoid ___ in heavy rain.", options: ["leaving; to drive", "leave; drive", "left; drove", "to leave; driving"], answerIndex: 3, reasons: ["want 不接 leaving，avoid 也不接 to drive。", "兩個原形都無法直接作 wants、avoid 的補語。", "left 與 drove 把尚未發生的計畫錯寫成過去。", "wants to leave 與 avoid driving 皆符合固定搭配。"], reviews: ["提早離開是意願，避免的是在大雨中開車這項行為。", "第四項也與 hopes to avoid 的目的鏈一致。"], cognitiveProcess: ["u22-s153-build-want-avoid-cause-chain", "select-infinitive-then-gerund-under-hope"], representationType: "nested-goal-avoidance-complements", misconceptionTargets: ["let-heavy-rain-trigger-past-tense"] },
  ]),
  ...skillQuestions("154", [
    { stem: "The rain began, so the children stopped ___ outside.", options: ["playing", "to play", "played", "plays"], answerIndex: 0, reasons: ["playing 是孩子停止進行的戶外活動。", "to play 會表示孩子停下原活動後去外面玩，與下雨情境相反。", "played 是過去式，不能接在 stopped 後。", "plays 是現在式限定動詞，結構不合。"], reviews: ["下雨後的合理變化是戶外遊戲結束。", "第一項採 stop doing，與 to play 的開始新目的不同。"], cognitiveProcess: ["u22-s154-infer-ended-play-from-rain", "contrast-stop-playing-with-stop-to-play"], representationType: "stop-doing-weather-cloze", misconceptionTargets: ["reverse-ended-action-and-new-purpose"] },
    { stem: "During the long walk, Ben stopped walking ___ some water.", options: ["drinking", "to drink", "drank", "drinks"], answerIndex: 1, reasons: ["drinking 不能直接接在 stopped walking 後標示停走的目的。", "to drink 說明他停止走路是為了喝水。", "drank 不能在此連接停走與喝水兩件事。", "drinks 是現在式，也無法作 walking 的目的補語。"], reviews: ["題幹已明說被停止的是 walking，喝水是接下來的新行動。", "第二項屬目的不定詞，不再容許「停止喝水」的另一解讀。"], cognitiveProcess: ["u22-s154-identify-drinking-as-purpose-after-stopping-walk", "separate-ended-walk-from-new-action"], representationType: "stop-walking-purpose-infinitive", misconceptionTargets: ["attach-drinking-as-ended-action"] },
    { stem: "Remember ___ the door before you leave.", options: ["locking", "locked", "to lock", "locks"], answerIndex: 2, reasons: ["locking 會偏向回想已鎖門的經驗，不是提醒。", "locked 是過去式，不能接 remember。", "to lock 表示離開前別忘記完成鎖門責任。", "locks 帶人稱變化，不能作 remember 的補語。"], reviews: ["before you leave 表示鎖門仍是接下來要做的事。", "第三項採 remember to do，而不是記憶已發生事件。"], cognitiveProcess: ["u22-s154-read-future-reminder-before-leaving", "choose-remember-to-lock"], representationType: "remember-duty-infinitive", misconceptionTargets: ["use-memory-of-past-form-for-reminder"] },
    { stem: "Nora remembers ___ Leo at the school party last year.", options: ["to meet", "met", "meets", "meeting"], answerIndex: 3, reasons: ["to meet 會把見面當成待完成責任，不符合 last year。", "met 是過去式，不能直接接 remembers。", "meets 是現在式限定動詞，結構錯誤。", "meeting 表示 Nora 記得去年見過 Leo 的經驗。"], reviews: ["last year 與 remembers 共同指出事件已發生且仍有記憶。", "第四項是 remember doing，沒有把回憶改成提醒。"], cognitiveProcess: ["u22-s154-anchor-memory-to-past-party", "select-remember-meeting"], representationType: "remember-past-experience-gerund", misconceptionTargets: ["use-infinitive-despite-completed-event"] },
    { stem: "Amy forgot ___ her book, so she had nothing to read in class.", options: ["to bring", "bringing", "brought", "brings"], answerIndex: 0, reasons: ["to bring 表示 Amy 該帶書卻沒有完成。", "bringing 會表示書帶過了但她忘記那段經驗，與沒有書矛盾。", "brought 不能直接接 forgot。", "brings 是現在式，也不符合過去結果。"], reviews: ["had nothing to read 證明帶書這件事未發生。", "第一項由實際結果排除 forget doing 的解讀。"], cognitiveProcess: ["u22-s154-use-missing-book-as-noncompletion-evidence", "select-forgot-to-bring"], representationType: "forget-duty-result-inference", misconceptionTargets: ["confuse-forgot-action-with-forgot-memory"] },
    { stem: "Leo will never forget ___ the game with his father.", options: ["to watch", "watching", "watched", "watches"], answerIndex: 1, reasons: ["to watch 會像尚待完成的事情，與 will never forget 的珍貴回憶不合。", "watching 表示 Leo 不會忘記一起看比賽的經驗。", "watched 是過去式，不能作 forget 的補語。", "watches 是現在式限定動詞，結構不合。"], reviews: ["with his father 形成可被記住的共同經驗。", "第二項屬 forget doing 的否定形式，表示記憶不會消失。"], cognitiveProcess: ["u22-s154-interpret-never-forget-shared-experience", "choose-watching-as-remembered-event"], representationType: "never-forget-memory-gerund", misconceptionTargets: ["read-never-forget-as-future-reminder"] },
    { stem: "The box would not open. Mia tried hard ___ it, but it stayed closed.", options: ["opening", "opened", "to open", "opens"], answerIndex: 2, reasons: ["opening 較適合測試一種方法，不能接在 tried hard 後表達努力目標。", "opened 是過去式，不能接 tried hard。", "to open 表示 Mia 很努力想打開箱子，但後文證明失敗。", "opens 是現在式限定動詞，結構錯誤。"], reviews: ["tried hard 明確標示努力達成開箱目標。", "第三項用 try hard to do，stayed closed 又證明嘗試不等於成功。"], cognitiveProcess: ["u22-s154-link-hard-effort-to-opening-goal", "use-closed-result-to-check-meaning"], representationType: "try-hard-goal-infinitive", misconceptionTargets: ["treat-effort-goal-as-method-test"] },
    { stem: "Ben is testing ways to make the soup taste better. He says, 'Try ___ some salt, and then check the taste.'", options: ["to add", "added", "adds", "adding"], answerIndex: 3, reasons: ["to add 著重努力完成加鹽，不符合 testing ways 指出的測試方法。", "added 是過去式，不能接 try。", "adds 是現在式限定動詞，也不能作建議內容。", "adding 把加鹽當成可試的一種改善方法。"], reviews: ["testing ways 與 check the taste 共同建立試驗方法的情境。", "第四項屬 try doing，結果好不好要在加鹽後再檢查。"], cognitiveProcess: ["u22-s154-identify-salt-as-experimental-method", "select-try-adding-under-test-frame"], representationType: "try-method-experiment-gerund", misconceptionTargets: ["ignore-explicit-method-testing-context"] },
    { stem: "Ben stopped working at six. What happened at six?", options: ["He ended his work.", "He began to work.", "He planned tomorrow's work.", "He forgot where he worked."], answerIndex: 0, reasons: ["stopped working 表示工作在六點結束。", "開始工作應表達 started working，不是 stopped working。", "句子沒有提到明天的計畫。", "stop doing 也不表示忘記工作地點。"], reviews: ["working 是被 stopped 終止的活動。", "第一項只重述停止工作，沒有加入原因或後續安排。"], cognitiveProcess: ["u22-s154-paraphrase-stopped-working-time", "exclude-start-plan-memory-readings"], representationType: "stop-doing-meaning-paraphrase", misconceptionTargets: ["read-stop-doing-as-pause-to-start"] },
    { stem: "Ben stopped to work at six. What was he doing just before six?", options: ["He was already working.", "He was doing something else.", "He was sleeping all day.", "He had finished every job."], answerIndex: 1, reasons: ["stop to work 表示六點才停下原活動去工作，並非早已工作。", "不定詞指出新目的，所以六點前在做別的事。", "句中沒有足夠證據說他睡了一整天。", "開始去工作不代表所有工作已完成。"], reviews: ["to work 是停下來後的新行動，而非被停止的行動。", "第二項保留未知的原活動，不擅自指定它是什麼。"], cognitiveProcess: ["u22-s154-infer-prior-activity-from-stop-to-work", "avoid-inventing-original-action"], representationType: "stop-to-do-timeline-inference", misconceptionTargets: ["equate-stop-to-work-with-end-work"] },
    { stem: "Mia said, 'I remember calling Amy, so I will not call her again.' What does Mia remember?", options: ["A call she still needs to make", "A call Amy will make", "A call she already made", "A call she did not want to make"], answerIndex: 2, reasons: ["calling 表示已發生的回憶，不是待辦電話。", "句中打電話的人是 Mia，不是 Amy。", "remember calling 加上 not call again 證明 Mia 記得自己打過。", "原文沒有說 Mia 當時不想打電話。"], reviews: ["so I will not call her again 是完成過電話的結果證據。", "第三項正確排列先打電話、後保有記憶的時間線。"], cognitiveProcess: ["u22-s154-use-no-repeat-call-as-memory-evidence", "identify-agent-of-remembered-action"], representationType: "remember-doing-dialogue-inference", misconceptionTargets: ["interpret-calling-as-future-task"] },
    { stem: "The computer is slow. Leo first tries to close the page, but it does not close. Amy then says, 'Try ___ the computer off and on.'", options: ["to turn", "turned", "turns", "turning"], answerIndex: 3, reasons: ["to turn 會重複努力達成單一目標的焦點，不如情境中的替代方法精確。", "turned 是過去式，不能接 Amy 的 Try。", "turns 是第三人稱形式，也不能作命令後的補語。", "turning the computer off and on 是 Amy 提出的另一個可試方法。"], reviews: ["前一方法失敗後，Amy 改提重新開關電腦的做法。", "第四項以 try doing 表示測試方案，不保證一定修好。"], cognitiveProcess: ["u22-s154-shift-from-failed-goal-to-new-method", "encode-restart-as-gerund-experiment"], representationType: "try-to-versus-try-doing-dialogue", misconceptionTargets: ["ignore-method-shift-after-failure"] },
  ]),
];

export const ENGLISH_UNIT_SOURCE = {
  unitId: UNIT_ID,
  lectures: ENGLISH_U22_LECTURES,
  questions: ENGLISH_U22_QUESTIONS,
  vocabularyPolicy: {
    capQuestionBasis: "appendix-5-table-1",
    additionalLearningTerms: ["activity", "add", "avoid", "forward", "lock", "promise", "suggest"],
    properNames: ["Amy", "Ben", "Japan", "Leo", "Mia", "Nora", "Sam", "Taipei"],
    grammarNotation: ["ing", "to"],
    malformedDistractors: ["readed"],
  },
};
