const UNIT_ID = "ENG_R4_U21";

function lecture(id, skillId, content) {
  return { id, skillId, ...content, sections: content.sections.map((section, index) => ({ id: `${id}_SEC_${String(index + 1).padStart(2, "0")}`, ...section })) };
}

const DIFFICULTIES = ["foundation", "foundation", "foundation", "standard", "standard", "standard", "standard", "advanced", "advanced", "advanced", "transfer", "transfer"];

function skillQuestions(skillNumber, values) {
  if (values.length !== 12) throw new Error(`ENG_R4_S${skillNumber}: expected 12 authored questions`);
  return values.map((value, index) => ({ id: `ENG_R4_Q_${skillNumber}_${String(index + 1).padStart(2, "0")}`, skillId: `ENG_R4_S${skillNumber}`, difficulty: DIFFICULTIES[index], ...value }));
}

export const ENGLISH_U21_LECTURES = [
  lecture("ENG_R4_L_S141", "ENG_R4_S141", {
    objectives: ["使用 and 連接功能相同的字、片語或子句。", "維持平行結構，並判斷 and 連接主詞時的單複數。"],
    sections: [
      { title: "and 加入同一層級的資訊", content: "and 可以連接名詞、動作、形容詞或完整子句，例如 tea and milk、washed and dried、small and clean。兩邊必須在句中做相近的工作，不能只因中文都有「和」就任意相接。" },
      { title: "並列項目要維持平行", content: "Mia likes reading and drawing 以兩個動名詞形式並列；若寫 reading and to draw，意思雖可猜到，形式卻不平行。判斷時要比較 and 左右最接近的兩個成分。" },
      { title: "and 連接兩個主詞通常用複數動詞", content: "Ben and Leo are ready 中，兩個人共同形成複合主詞，所以用 are。若 and 只連接同一主詞的兩個動作，如 Ben reads and writes，動詞仍依 Ben 使用第三人稱單數。" },
      { title: "and 不會自動表示轉折或因果", content: "The room is small and clean 只是加入第二個特徵；若資訊相反，通常要用 but 或 yet。事件前後相接也不代表前者一定造成後者，因果仍需由 because、so 或情境證據建立。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S141_EX_01", prompt: "Ben packed both items: bread ___ water.", steps: ["bread 與 water 都是 packed 的受詞。", "both 表示兩項都要保留。", "填入 and。"], answer: "and", why: "both items 指 bread 和 water 兩樣都裝，且兩者同為名詞受詞，因此用 and 加入第二項。or 會改成擇一，與 both 矛盾。" },
      { id: "ENG_R4_L_S141_EX_02", prompt: "Mia washed and ___ the cups. (dry / dried)", steps: ["washed 是過去式動作。", "and 後接同一主詞的第二個動作。", "選 dried。"], answer: "dried", why: "washed 與 dried 是 Mia 依序完成的兩個過去動作，形式需保持一致。dry 是原形，無法和前面的 washed 平行。" },
      { id: "ENG_R4_L_S141_EX_03", prompt: "Ben and Leo ___ on the same team. (is / are)", steps: ["and 連接 Ben 與 Leo。", "主詞包含兩個人。", "使用 are。"], answer: "are", why: "Ben and Leo 合起來是複數主詞，因此 be 動詞用 are。不能只看離動詞較近的 Leo 是單數，就誤選 is。" },
    ],
    misconceptions: [
      { belief: "只要中文可翻成「和」，and 左右形式就不必相同。", whyWrong: "英文並列成分需在句中具相近功能，形式混亂會破壞結構。", correction: "圈出 and 兩側成分，確認名詞對名詞、動作對動作。" },
      { belief: "and 後出現第二個動詞時，一定要再寫一次主詞。", whyWrong: "同一主詞可共用兩個並列動詞。", correction: "可寫 Mia opened the box and took out the book。" },
      { belief: "兩個人以 and 連接後仍使用 is。", whyWrong: "兩個不同人物形成複數主詞。", correction: "使用 Ben and Mia are，而不是 Ben and Mia is。" },
      { belief: "and 連接的第一件事一定是第二件事的原因。", whyWrong: "and 只保證資訊並列，不自行建立因果。", correction: "需要因果時另找 because、so 或明確情境證據。" },
    ],
    checks: [
      { prompt: "reading and swimming 是否平行？", answer: "是", reason: "兩側都是動名詞形式並作同類活動。" },
      { prompt: "Amy and Nora 後用 is 還是 are？", answer: "are", reason: "兩人構成複數主詞。" },
      { prompt: "and 本身能證明因果嗎？", answer: "不能", reason: "它主要加入同層資訊。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S142", "ENG_R4_S142", {
    objectives: ["使用 but 與 yet 連接相反或出乎預期的資訊。", "區分轉折、並列與因果，並避免重複轉折標記。"],
    sections: [
      { title: "but 連接明確對比", content: "The bag is old but useful 把 old 與 useful 放在對比關係中；前者可能讓人預期物品不好用，後者修正這個預期。若兩項只是同方向增加，應使用 and。" },
      { title: "yet 常凸顯出乎預期", content: "The road was long, yet we arrived early 表示結果和一般預期不同。yet 在這種用法接近 but，但通常更強調「儘管如此仍然」的落差，不是表示時間上的「尚未」。" },
      { title: "轉折詞兩側要各自完整", content: "but 或 yet 可連接兩個形容詞、片語或子句；比較層級仍要一致。The room is small but has two windows 把特徵與動作結構混接，改成 The room is small but bright，或另寫完整子句較清楚。" },
      { title: "一個轉折關係不必重複標記", content: "Although it was cold, we went out 已由 although 建立讓步，不再接 but。相同地，but 本身已足以表達轉折，不能因中文習慣再加另一個功能相同的連接詞。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S142_EX_01", prompt: "The box is small ___ heavy. (and / but)", steps: ["small 與 heavy 都描述 box。", "兩個特徵形成反差。", "選 but。"], answer: "but", why: "small 容易讓人預期重量不大，heavy 卻推翻這個預期，所以在兩個指定選項中使用 but。and 只會平列兩項，無法呈現反差。" },
      { id: "ENG_R4_L_S142_EX_02", prompt: "Mia was tired, ___ she did not stop working.", steps: ["先看到 tired。", "後句仍持續工作。", "用 yet 表示意外轉折。"], answer: "yet", why: "疲累通常讓人預期 Mia 停下工作，實際卻沒有停止，yet 正好標示這個出乎預期的結果。so 反而會表示順勢結果。" },
      { id: "ENG_R4_L_S142_EX_03", prompt: "The coat is warm ___ light. (and / but)", steps: ["warm 與 light 同為形容詞。", "保暖衣物常被預期較重。", "填 but。"], answer: "but", why: "warm 與 light 在形式上平行，但題目要從 and、but 中表達「保暖卻輕」的對比，因此選 but。若只是列出同方向優點，才會選 and。" },
    ],
    misconceptions: [
      { belief: "but 只要放在兩個句子中間，前後意思不必有反差。", whyWrong: "but 的核心功能就是修正或對比前面的預期。", correction: "先用中文說出「但是」前後究竟相反在哪裡。" },
      { belief: "yet 在任何句子中都只表示「尚未」。", whyWrong: "yet 作連接詞時可表示出乎預期的轉折。", correction: "看 yet 後是否接另一個完整子句並對比前文。" },
      { belief: "Although 開頭的句子仍要在主句前加 but。", whyWrong: "although 已建立讓步，再加 but 會重複連接。", correction: "保留 although 或 but 其中一個完整結構。" },
      { belief: "看到兩個不同形容詞就一定用 but。", whyWrong: "不同不等於對比，small and clean 可以只是並列特徵。", correction: "判斷後項是否推翻前項帶來的預期。" },
    ],
    checks: [
      { prompt: "old but useful 表示何種關係？", answer: "轉折", reason: "useful 修正 old 帶來的負面預期。" },
      { prompt: "yet 連接兩個子句時可能表示什麼？", answer: "出乎預期的轉折", reason: "它不一定是時間副詞。" },
      { prompt: "Although 與 but 是否要成對同時使用？", answer: "不用", reason: "一個讓步關係只需一個主要連接標記。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S143", "ENG_R4_S143", {
    objectives: ["使用 or 表達選擇、替代方案與否則結果。", "依語境區分自由選擇、二選一與警告中的條件關係。"],
    sections: [
      { title: "or 提供選擇或替代方案", content: "You may take the bus or walk 提供兩種到達方式；tea or coffee 則列出飲料選項。or 不一定表示兩者永遠不能同時發生，是否只能選一個要由情境決定。" },
      { title: "否定句中的 or 可連接兩個都不成立的項目", content: "Mia does not eat meat or fish 表示兩者都不吃。不能直接把否定句中的 or 理解成只否定其中一項；否定範圍要連同動詞與並列項目一起讀。" },
      { title: "命令句加 or 可表示否則結果", content: "Hurry, or you will miss the bus 可理解為 If you do not hurry, you will miss the bus。前半提出必要行動，後半說明不照做可能產生的結果。" },
      { title: "選擇與否則結果要靠句型區分", content: "Would you like rice or noodles? 是選擇；Wear a coat, or you will feel cold 是警告。不要只看到 or 就套用同一中文意思，應先判斷前半是否為命令或必要行動。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S143_EX_01", prompt: "Choose one thing to eat: Would you like bread ___ rice?", steps: ["句子限定一種食物。", "兩項是替代方案。", "使用 or。"], answer: "or", why: "Choose one thing to eat 要對方在 bread 與 rice 中擇一，因此用 or。and 會變成詢問是否兩種都要，違反單選限制。" },
      { id: "ENG_R4_L_S143_EX_02", prompt: "If you do not hurry, you will miss the bus. Hurry, ___ you will miss the bus.", steps: ["前句指定 if-not 意思。", "後半是不照做的結果。", "填 or。"], answer: "or", why: "第一句指定「不快一點就會錯過公車」，or 能把命令與否則結果連起來。because 只會提供理由，不能重現同一個 if-not 條件。" },
      { id: "ENG_R4_L_S143_EX_03", prompt: "Ben does not drink tea ___ coffee.", steps: ["否定詞 not 管到飲料項目。", "tea 與 coffee 都被否定。", "使用 or。"], answer: "or", why: "在這個否定句中，or 連接兩個都不喝的飲料，意思是 Ben 不喝茶，也不喝咖啡。使用 and 容易讓否定範圍變得不清楚。" },
    ],
    misconceptions: [
      { belief: "or 永遠表示只能選一個，兩者絕不可能同時成立。", whyWrong: "有些語境只列替代方案，是否互斥由規則或情境決定。", correction: "找是否有 only one、one ticket 等限制線索。" },
      { belief: "命令句後的 or 只是再增加一個選項。", whyWrong: "Hurry, or... 的後半通常是不照做的結果。", correction: "嘗試改寫為 If you do not..., 看意思是否相同。" },
      { belief: "否定句中連接兩個項目一定要用 and。", whyWrong: "not...or... 常表示兩項都不成立。", correction: "把否定範圍連同兩個並列受詞一起解讀。" },
      { belief: "or 可以直接代替 because 表示原因。", whyWrong: "or 本身不說明前件是後件的原因。", correction: "區分替代、否則結果與明確因果。" },
    ],
    checks: [
      { prompt: "tea or coffee 通常提供什麼？", answer: "選擇", reason: "兩項是替代方案。" },
      { prompt: "Hurry, or you will be late 可改寫成哪種條件？", answer: "If you do not hurry, you will be late.", reason: "or 後是不照做的結果。" },
      { prompt: "does not eat meat or fish 表示吃其中一種嗎？", answer: "不是", reason: "此處兩項都在否定範圍內。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S144", "ENG_R4_S144", {
    objectives: ["使用 because 引出原因，使用 so 引出結果。", "保留因果方向，並避免在同一結構重複使用 because 與 so。"],
    sections: [
      { title: "because 後說明原因", content: "We stayed home because it rained 中，stayed home 是結果，it rained 是原因。because 子句可以放在後面，也可移到句首，但原因與結果的角色不會因此交換。" },
      { title: "so 後說明結果", content: "It rained, so we stayed home 先提出原因，再用 so 接結果。若把 so 改成 because，句子就會要求後半解釋原因，邏輯方向會改變。" },
      { title: "because 與 so 不在同一主從結構重複", content: "Because it rained, we stayed home 已完整；標準寫法不再加 so。中文常說「因為……所以……」，但英文通常選 because 引原因或 so 引結果其中一種架構。" },
      { title: "因果必須有合理證據", content: "兩件事先後發生不必然代表因果。The bell rang, and Mia got up 只陳述兩件事；若題目說她因鈴聲而起身，才可用 because 或 so 明確連接。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S144_EX_01", prompt: "The dark sky was the reason: We took an umbrella ___ the sky was dark.", steps: ["帶傘是結果。", "天空變暗是指定原因。", "選 because。"], answer: "because", why: "題目明說 the sky was dark 是帶傘理由，因此放在 because 後。若使用 when，只會表示同一時間，沒有保留指定因果。" },
      { id: "ENG_R4_L_S144_EX_02", prompt: "Use so: The rain became strong, ___ we stayed inside.", steps: ["雨勢變強是原因。", "留在室內是結果。", "使用 so。"], answer: "so", why: "the rain became strong 提供原因，stayed inside 是因而採取的行動；依題目指定，用 so 引出結果，不能交換兩個子句的角色。" },
      { id: "ENG_R4_L_S144_EX_03", prompt: "Because the bus was full, we ___. (waited / so waited)", steps: ["Because 已引出原因。", "主句直接接結果。", "選 waited。"], answer: "waited", why: "Because the bus was full 已標示原因，逗點後直接寫結果 we waited 即可。再加 so 會把同一因果關係重複標記。" },
    ],
    misconceptions: [
      { belief: "because 後面一定放結果。", whyWrong: "because 引導的是原因，主句才陳述結果。", correction: "先問「為什麼」，能回答的內容放在 because 後。" },
      { belief: "so 後面是在解釋前句的原因。", whyWrong: "so 通常由前面的原因推到後面的結果。", correction: "用箭頭檢查前因是否能導向 so 後的結果。" },
      { belief: "英文必須同時使用 because 和 so 才算完整。", whyWrong: "兩者同時標記同一因果會造成重複結構。", correction: "選 Because A, B 或 A, so B 其中一種。" },
      { belief: "只要 A 先發生、B 後發生，就能寫 A so B。", whyWrong: "時間先後不等於 A 造成 B。", correction: "確認情境是否明確支持因果，而非只有順序。" },
    ],
    checks: [
      { prompt: "because 後通常接原因還是結果？", answer: "原因", reason: "because 回答為什麼。" },
      { prompt: "so 後通常接什麼？", answer: "結果", reason: "它由前因推向後果。" },
      { prompt: "Because A, so B 是本單元標準寫法嗎？", answer: "不是", reason: "同一因果關係被重複標記。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S145", "ENG_R4_S145", {
    objectives: ["使用 although 引出與主句形成反差的讓步資訊。", "辨識讓步不是單純並列，並避免 although 與 but 重複。"],
    sections: [
      { title: "although 承認一項事實再提出意外結果", content: "Although the test was hard, Mia finished it 先承認考試困難，再說 Mia 仍完成。主句不是否定 although 子句，而是呈現即使有阻礙，結果仍發生。" },
      { title: "although 子句可前可後", content: "Although it was late, we did not stop talking 與 We did not stop talking although it was late 都建立相同讓步關係。位置改變不會交換事實，只會調整讀者先接收到哪一部分。" },
      { title: "although 與 but 不重複使用", content: "Although the bag is old, it is useful 已完整。若改用 but，可寫 The bag is old, but it is useful；不能把兩個架構疊成 Although..., but...。" },
      { title: "讓步需要真實的預期落差", content: "Although the water was cold, Ben went swimming 中，cold 構成可能阻礙，went swimming 卻仍發生。若兩項同方向，例如天氣好又出去玩，就不需要 although。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S145_EX_01", prompt: "The rain did not stop the game: ___ it was raining, the players stayed outside. (Although / Because)", steps: ["下雨是可能阻礙。", "球員仍留在外面。", "填 Although。"], answer: "Although", why: "前句明說雨沒有阻止比賽，players stayed outside 與 raining 形成讓步，因此在指定選項中用 Although。Because 會誤寫成雨造成他們留在外面。" },
      { id: "ENG_R4_L_S145_EX_02", prompt: "Use although: Nora smiled ___ she was tired.", steps: ["疲累與微笑形成預期落差。", "although 子句可放句尾。", "選 although。"], answer: "although", why: "Nora 疲累是事實，但她仍微笑；依題目指定，空格填 although，在句尾引出這項阻礙。它保留兩件事都成立，也表達預期落差。" },
      { id: "ENG_R4_L_S145_EX_03", prompt: "Although the room was small, it ___ bright. (was / but was)", steps: ["Although 已建立讓步。", "主句直接陳述 bright。", "選 was。"], answer: "was", why: "although 子句已說明房間雖小，主句直接寫 it was bright 即可。but was 會在同一讓步架構中重複加入轉折詞。" },
    ],
    misconceptions: [
      { belief: "although 表示前半句不是真的。", whyWrong: "讓步句承認前半事實，再指出結果仍不同於預期。", correction: "把兩邊都視為成立，尋找它們之間的落差。" },
      { belief: "Although 開頭後一定要搭配 but。", whyWrong: "although 已負責連接從句與主句。", correction: "寫 Although A, B，不再加入 but。" },
      { belief: "兩個正確事實放在一起就能使用 although。", whyWrong: "讓步還需要阻礙與結果間的預期反差。", correction: "檢查是否能自然說成「雖然 A，仍然 B」。" },
      { belief: "although 只能放在句首。", whyWrong: "although 子句也可以放在主句之後。", correction: "比較 Although A, B 與 B although A。" },
    ],
    checks: [
      { prompt: "although 子句中的事實仍成立嗎？", answer: "成立", reason: "讓步不是否定該事實。" },
      { prompt: "Although A, but B 是否重複？", answer: "是", reason: "兩個詞重複標記同一轉折。" },
      { prompt: "although 子句能放在主句後嗎？", answer: "可以", reason: "位置可變但邏輯關係不變。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S146", "ENG_R4_S146", {
    objectives: ["使用 when、before、after 連接時間子句並判斷事件順序。", "在未來時間子句中使用現在式，並辨識子句前後位置。"],
    sections: [
      { title: "when 指出某時刻或事件發生時", content: "Call me when you arrive 表示抵達時打電話；When the bell rang, students left 說明鈴響時發生離開。when 不會自行說明哪一件事較早很久，重點是時間連結。" },
      { title: "before 與 after 決定事件順序", content: "Wash your hands before you eat 表示洗手先發生；We cleaned the table after everyone left 表示人先離開。子句放前或放後，都要依 before、after 重新排列事件。" },
      { title: "未來時間子句通常使用現在式", content: "We will leave when the rain stops 中，主句用 will leave，when 子句用 stops，不寫 when the rain will stop。before 與 after 引導未來時間時也遵守相同原則。" },
      { title: "子句移位不改變時間關係", content: "After Mia finished dinner, she washed the dishes 與 Mia washed the dishes after she finished dinner 的順序相同。句首時間子句常以逗點和主句分開，閱讀時仍以連接詞判斷先後。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S146_EX_01", prompt: "Please turn off the light ___ you leave. (before / after)", steps: ["離開是時間界線。", "關燈要先完成。", "選 before。"], answer: "before", why: "指示要求先關燈再離開，所以在兩個指定選項中用 before。after 會變成已離開後才關燈，在情境中無法執行。" },
      { id: "ENG_R4_L_S146_EX_02", prompt: "We will eat when Dad ___. (arrives / will arrive)", steps: ["主句已用 will eat。", "when 引導未來時間子句。", "選 arrives。"], answer: "arrives", why: "雖然抵達尚未發生，when 子句仍用現在式 arrives；未來意思由主句 will eat 和整體情境表達，不再寫 will arrive。" },
      { id: "ENG_R4_L_S146_EX_03", prompt: "Nora called me after she ___ home. (got / called)", steps: ["after 後是較早事件。", "先到家，後打電話。", "選 got。"], answer: "got", why: "after she got home 表示 Nora 先到家，之後才打電話。called 會變成「她打電話後又打電話」，無法保留題目要測的兩件不同事件。" },
    ],
    misconceptions: [
      { belief: "when 一出現就表示兩件事完全同時開始和結束。", whyWrong: "when 也可標示某事件發生時的時間點，不保證全程重疊。", correction: "依動詞判斷是時間點、期間或觸發事件。" },
      { belief: "before 子句永遠排在句子前面。", whyWrong: "子句位置與實際先後是兩回事。", correction: "用 before 的意義排列事件，不靠文字左右順序。" },
      { belief: "談未來時，when 子句也必須使用 will。", whyWrong: "未來時間子句通常使用現在式。", correction: "寫 I will call when I arrive。" },
      { belief: "after 子句放到句首就會改變事件順序。", whyWrong: "移位只改變句子組織，不改變 after 的時間關係。", correction: "分別標出先發生與後發生的事件再比較。" },
    ],
    checks: [
      { prompt: "I will call when I arrive 中哪個子句用現在式？", answer: "when I arrive", reason: "未來時間子句不用 will arrive。" },
      { prompt: "A after B 表示哪件事先發生？", answer: "B", reason: "after 後接較早的參照事件。" },
      { prompt: "時間子句移到句首會改變先後嗎？", answer: "不會", reason: "連接詞所建立的關係保持不變。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S147", "ENG_R4_S147", {
    objectives: ["依加入、轉折、選擇、因果、讓步與時間關係選擇連接詞。", "整合句法與情境證據，不以單一關鍵字猜答案。"],
    sections: [
      { title: "先辨認兩段資訊的邏輯", content: "and 加入同類資訊，but 或 yet 修正預期，or 提供選擇或否則結果。作答前先用自己的話說明兩段資訊如何相關，再檢查連接詞後的句法是否完整。" },
      { title: "因果與讓步方向不同", content: "because 引原因，so 引結果；although 則表示阻礙存在但結果仍發生。The road was wet because it rained 與 Although it rained, we went out 使用相同雨勢資料，邏輯任務卻不同。" },
      { title: "時間連接詞要重排事件", content: "when 連到某時刻，before、after 建立先後。連接詞可能放在句中或句首，不能把文字先出現誤當成事件先發生；必要時把事件寫成時間線。" },
      { title: "最後同時檢查意義與形式", content: "正確選項要保留所有情境資料，也要避免 because...so、although...but 等重複結構。即使某個詞符合大意，只要造成否定範圍、平行形式或子句時態錯誤，仍不能選。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S147_EX_01", prompt: "The map was old, ___ it was still useful. (but / because)", steps: ["old 帶來可能無用的預期。", "useful 修正這個預期。", "選 but。"], answer: "but", why: "地圖雖舊卻仍有用，前後是轉折而非原因；在兩個指定選項中應選 but。because 會把 useful 誤當成地圖老舊的原因。" },
      { id: "ENG_R4_L_S147_EX_02", prompt: "The dark sky is why we need an umbrella: Take an umbrella ___ the sky is dark.", steps: ["帶傘是行動。", "天色暗是指定原因。", "選 because。"], answer: "because", why: "題目明說 the sky is dark 解釋帶傘理由，因此由 because 引出原因。when 只能表示時間重疊，不能保留 why 指定的因果。" },
      { id: "ENG_R4_L_S147_EX_03", prompt: "The start time is the moment everyone is ready: We will start ___ everyone is ready.", steps: ["ready 是開始時刻。", "主句使用 will start。", "選 when。"], answer: "when", why: "題目把大家準備好的時刻定為開始時間，因此使用 when。because 只表示原因，不能精確保留 the moment 指定的時間界線。" },
    ],
    misconceptions: [
      { belief: "看見兩個完整句子時，任一連接詞都能使用。", whyWrong: "連接詞會改變加入、轉折、因果或時間等邏輯。", correction: "先說明兩句的關係，再檢查選項。" },
      { belief: "出現負面字就一定選 but 或 although。", whyWrong: "負面內容也可能是原因、結果或時間背景。", correction: "判斷後項是在反轉預期，還是在說明因果。" },
      { belief: "because 和 although 都接子句，所以意思相近。", whyWrong: "because 提供原因，although 承認阻礙後呈現反差。", correction: "比較「因為 A 所以 B」與「雖然 A 仍 B」。" },
      { belief: "只要連接詞意思大致合理，就不必檢查句法。", whyWrong: "重複連接、時態或平行結構錯誤仍會使句子不成立。", correction: "完成邏輯判斷後再讀一次完整句型。" },
    ],
    checks: [
      { prompt: "前後同方向增加資訊時先考慮哪個字？", answer: "and", reason: "它連接同層並列資訊。" },
      { prompt: "前因後果且空格在結果前時先考慮哪個字？", answer: "so", reason: "so 引出結果。" },
      { prompt: "阻礙存在但結果仍發生時先考慮哪個字？", answer: "although", reason: "它建立讓步關係。" },
    ], assets: [],
  }),
];

export const ENGLISH_U21_QUESTIONS = [
  ...skillQuestions("141", [
    { stem: "Nora bought two things: bread ___ milk.", options: ["and", "but", "or", "because"], answerIndex: 0, reasons: ["and 連接兩個同為 bought 受詞的物品。", "but 需要前後有轉折，two things 沒有反差。", "or 會把兩項改成替代選擇，違反 two things。", "because 後應接原因子句，不能只接 milk。"], reviews: ["two things 表示 bread 與 milk 都買了。", "第一項保留 Nora 兩樣都買的資訊。"], cognitiveProcess: ["identify-two-coobjects-of-bought", "join-bread-and-milk-additively"], representationType: "parallel-noun-object-cloze", misconceptionTargets: ["turn-two-purchases-into-choice"] },
    { stem: "Ben did both jobs: he washed ___ dried the cups.", options: ["but", "and", "because", "although"], answerIndex: 1, reasons: ["but 會加入 both jobs 沒有指定的動作反差。", "and 連接 Ben 完成的兩個過去動作。", "because 不能直接在此接單一過去式動詞作原因子句。", "although 需要形成讓步子句，句中沒有新的主詞結構。"], reviews: ["both jobs 指 washed 與 dried 都由 Ben 完成。", "第二項維持兩個同層動作的平行關係。"], cognitiveProcess: ["recognize-shared-subject-past-verbs", "coordinate-washed-and-dried"], representationType: "parallel-past-verbs-cloze", misconceptionTargets: ["invent-contrast-between-routine-actions"] },
    { stem: "Amy and Leo ___ ready.", options: ["is", "am", "are", "be"], answerIndex: 2, reasons: ["is 不搭配 Amy and Leo 形成的複數主詞。", "am 只搭配第一人稱 I。", "are 正確配合兩個人組成的主詞。", "be 原形不能直接作本句現在式主要動詞。"], reviews: ["and 連接兩位不同人物。", "第三項符合複合主詞的數量。"], cognitiveProcess: ["count-two-names-in-compound-subject", "select-plural-be-form"], representationType: "compound-subject-agreement-cloze", misconceptionTargets: ["use-singular-be-with-two-names"] },
    { stem: "Mia likes reading and ___.", options: ["to draw", "draw", "draws", "drawing"], answerIndex: 3, reasons: ["to draw 與 reading 的形式不平行。", "draw 原形不能和前面的動名詞並列。", "draws 是現在式動詞，不能作 likes 後的第二個活動名稱。", "drawing 與 reading 同為 likes 後的動名詞活動。"], reviews: ["and 左邊最接近的並列項是 reading。", "第四項讓兩個喜好活動保持相同形式。"], cognitiveProcess: ["compare-gerund-form-across-and", "complete-parallel-hobby-pair"], representationType: "parallel-gerund-completion", misconceptionTargets: ["mix-gerund-and-finite-verb-forms"] },
    { stem: "The room has two good points: it is bright ___ clean.", options: ["and", "or", "so", "although"], answerIndex: 0, reasons: ["and 平列 bright 與 clean 兩個優點。", "or 會把兩個已知優點變成二選一。", "so 不能直接連接兩個同層形容詞表示結果。", "although 需要接讓步子句，不接單一 clean。"], reviews: ["two good points 表示兩項都要保留。", "第一項沒有添加選擇或因果。"], cognitiveProcess: ["classify-two-codomain-adjectives", "add-room-properties-with-and"], representationType: "parallel-adjective-cloze", misconceptionTargets: ["treat-description-list-as-alternative"] },
    { stem: "Nora opened the door and ___ inside.", options: ["walk", "walked", "walking", "to walk"], answerIndex: 1, reasons: ["walk 原形無法和 opened 保持過去式平行。", "walked 與 opened 都是 Nora 完成的過去動作。", "walking 會改成分詞，缺少相應結構。", "to walk 會變成目的用法，不是第二個並列事件。"], reviews: ["兩個動作依序發生且共用主詞 Nora。", "第二項維持 opened and walked 的相同時態。"], cognitiveProcess: ["track-open-then-enter-sequence", "match-past-tense-after-and"], representationType: "shared-subject-verb-form-cloze", misconceptionTargets: ["reset-second-verb-to-base-form"] },
    { stem: "A note says, 'Ben and Mia is outside.' Which change fixes it?", options: ["Ben → He", "Mia → she", "is → are", "outside → out"], answerIndex: 2, reasons: ["改成 He 會刪除 Ben 的姓名且未解決兩人主詞。", "在 Mia 前加 she 會造成不必要的重複主詞。", "Ben and Mia 是複數主詞，應將 is 改為 are。", "outside 本來即可作位置補語，不需改成 out。"], reviews: ["錯誤發生在複合主詞與 be 動詞的一致。", "第三項保留兩個姓名與原本位置。"], cognitiveProcess: ["diagnose-compound-subject-be-disagreement", "repair-is-to-are-only"], representationType: "and-subject-agreement-proofreading", misconceptionTargets: ["edit-noun-instead-of-agreement"] },
    { stem: "The bus came, ___ everyone got on.", options: ["because", "but", "or", "and"], answerIndex: 3, reasons: ["because 會把 everyone got on 當成公車來的原因，方向不合。", "but 需要第二件事推翻前面的預期。", "or 會把兩件已發生的事改成選擇。", "and 依序加入公車到達與大家上車兩件事。"], reviews: ["題目只提供事件接續，沒有明說因果或轉折。", "第四項保留兩件事都發生的事實。"], cognitiveProcess: ["separate-event-sequence-from-explicit-cause", "coordinate-bus-arrival-and-boarding"], representationType: "two-clause-sequence-connector", misconceptionTargets: ["infer-cause-from-time-order-alone"] },
    { stem: "The club needs someone to wash, dry, and pack the cups. Which plan follows the list?", options: ["Wash the cups, dry them, and pack them.", "Wash the cups but dry them.", "Dry the cups or pack all of them.", "Because the cups are washed, pack."], answerIndex: 0, reasons: ["第一項保留 wash、dry、pack 三個都要完成的平行動作。", "第二項只含兩項，且 but 誤加轉折。", "第三項把 dry 與 pack 改成只能擇一。", "第四項遺漏 dry，也把 pack 寫成不完整命令。"], reviews: ["原清單要求三項工作，不是替代方案。", "第一項以三個祈使動詞對應全部步驟。"], cognitiveProcess: ["map-three-required-club-actions", "select-complete-parallel-command-list"], representationType: "task-list-to-parallel-instruction", misconceptionTargets: ["drop-or-alternate-required-action"] },
    { stem: "The light came on, and the door opened. What do we know for sure?", options: ["The light made the door open.", "Both things happened.", "Only one thing happened.", "The door opened before the light came on."], answerIndex: 1, reasons: ["and 本身不能證明燈光使門打開。", "兩個子句由 and 並列，因此兩件事都發生。", "and 不是二選一，不會只保留其中一事。", "句子未提供足以確定先後的時間標記。"], reviews: ["問題只取原句能保證的最少資訊。", "第二項不加入原因或時間順序。"], cognitiveProcess: ["limit-inference-to-additive-connector", "reject-causal-and-temporal-overreading"], representationType: "and-minimum-inference", misconceptionTargets: ["treat-and-as-proof-of-causation"] },
    { stem: "Mia read the note. Mia called Ben. Keep one subject and both facts.", options: ["Mia read the note but Ben.", "Mia read or called the note.", "Mia read the note and called Ben.", "Mia called the note because Ben."], answerIndex: 2, reasons: ["第一項把 Ben 錯接成 but 後的殘缺成分。", "第二項改成選擇，且 called the note 搭配不合。", "第三項共用 Mia，並保留讀便條與打電話兩件事。", "第四項把 note 當成可撥打對象，也形成不完整原因。"], reviews: ["兩個原句主詞相同，可省略第二次 Mia。", "第三項的兩個過去動詞各自保留原受詞。"], cognitiveProcess: ["merge-repeated-subject-sentences", "preserve-read-note-and-call-ben"], representationType: "shared-subject-sentence-combination", misconceptionTargets: ["misattach-object-while-combining"] },
    { stem: "Nora sings. Leo sings. Keep both facts about what they do now.", options: ["Nora and Leo sings.", "Nora or Leo sing.", "Nora sings but Leo.", "Nora and Leo sing."], answerIndex: 3, reasons: ["第一項主詞變複數後仍誤用 sings。", "第二項把兩人都唱歌改成二選一。", "第三項遺漏 Leo 的動詞，且加入無據轉折。", "第四項用 and 合併兩人，並以 sing 配合複數主詞。"], reviews: ["原資料明確說兩個人目前都唱歌。", "第四項同時鎖住連接關係與動詞形式。"], cognitiveProcess: ["combine-two-sing-facts-into-compound-subject", "shift-third-person-verb-to-plural-form"], representationType: "fact-merger-with-agreement-change", misconceptionTargets: ["retain-singular-s-after-compound-subject"] },
  ]),
  ...skillQuestions("142", [
    { stem: "The bag is old ___ still useful.", options: ["but", "because", "or", "when"], answerIndex: 0, reasons: ["but 配合 still 表示袋子雖舊仍有用。", "because 不能直接接 still useful 作完整原因。", "or 會把兩個都成立的特徵改成選擇。", "when 不能在此連接同一物品的兩個特徵。"], reviews: ["still 明確標出 useful 出乎 old 帶來的預期。", "第一項把老舊阻礙與仍有用的結果連起來。"], cognitiveProcess: ["detect-old-versus-useful-expectation", "select-but-for-adjective-contrast"], representationType: "adjective-contrast-cloze", misconceptionTargets: ["flatten-contrast-into-addition"] },
    { stem: "The team was tired, ___ it did not stop playing.", options: ["so", "yet", "because", "and then"], answerIndex: 1, reasons: ["so 會把不停比賽寫成疲累的自然結果。", "yet 凸顯隊伍疲累卻沒有停下。", "because 會把後句當成疲累原因，邏輯顛倒。", "and then 只說接續，沒有保留意外落差。"], reviews: ["did not stop playing 與 tired 形成逆預期。", "第二項使用轉折連接兩個完整子句。"], cognitiveProcess: ["compare-fatigue-with-continuing-action", "choose-yet-for-unexpected-persistence"], representationType: "unexpected-result-yet-cloze", misconceptionTargets: ["treat-fatigue-as-cause-to-continue"] },
    { stem: "The room is small ___ still bright.", options: ["or", "so", "but", "because"], answerIndex: 2, reasons: ["or 會把房間小與仍明亮改成替代。", "so 不能把 bright 當成 small 必然造成的結果。", "but 配合 still 表達空間雖小卻明亮。", "because 不能直接接 still bright 作完整原因。"], reviews: ["still 使 bright 成為與 small 預期不同的結果。", "第三項保留兩項事實並標出逆預期。"], cognitiveProcess: ["hold-parallel-form-while-testing-contrast", "connect-small-but-bright"], representationType: "parallel-adjective-but-cloze", misconceptionTargets: ["choose-so-from-adjective-order"] },
    { stem: "Nora is young, ___ she leads the team well.", options: ["because", "so", "or", "yet"], answerIndex: 3, reasons: ["because 會把領導良好寫成年輕的原因。", "so 會把好表現當成由年齡自然導出的結果。", "or 會把兩個同時成立的事實改成選擇。", "yet 表示年輕卻能把隊伍帶好。"], reviews: ["前句建立經驗可能不足的預期。", "第四項保留年輕與領導良好都成立。"], cognitiveProcess: ["infer-age-leadership-expectation-gap", "apply-yet-to-surprising-competence"], representationType: "age-performance-concession-yet", misconceptionTargets: ["convert-surprise-into-causation"] },
    { stem: "The bag is not blue ___ green.", options: ["but", "and", "so", "because"], answerIndex: 0, reasons: ["but 建立 not blue but green 的更正結構。", "and 會讓 blue 與 green 都落在否定範圍，意思改變。", "so 不能連接被否定與更正的顏色。", "because 後的 green 不是完整原因子句。"], reviews: ["句子先排除 blue，再指出真正顏色。", "第一項保留「不是 A，而是 B」的修正功能。"], cognitiveProcess: ["recognize-not-a-but-b-correction", "replace-blue-expectation-with-green"], representationType: "not-but-correction-cloze", misconceptionTargets: ["extend-negation-over-corrected-color"] },
    { stem: "The walk was long. It was not difficult. Keep both facts and show the surprise.", options: ["The walk was long because it was not difficult.", "The walk was long, but it was not difficult.", "The walk was long or not difficult.", "Although the walk was long, but it was not difficult."], answerIndex: 1, reasons: ["第一項錯把不困難當成路程長的原因。", "第二項用 but 保留長路程卻不難的反差。", "第三項將兩個都成立的事實改成選擇。", "第四項同時使用 although 與 but，重複標記轉折。"], reviews: ["原資料要求 long 與 not difficult 都保留。", "第二項只新增一個必要轉折詞。"], cognitiveProcess: ["combine-long-walk-and-easy-experience", "avoid-double-concession-marking"], representationType: "two-fact-contrast-combination", misconceptionTargets: ["double-although-and-but"] },
    { stem: "A student writes, 'Although it was cold, but we went out.' Which change fixes it without changing either fact?", options: ["cold → warm", "went → go", "take out but", "Although → Because and keep but"], answerIndex: 2, reasons: ["改成 warm 會竄改天氣資料，未處理雙重連接。", "went 的過去式與句意一致，不需修改。", "拿掉 but 後形成完整的 Although 子句加主句。", "because 與 but 仍會造成不合的因果轉折混接。"], reviews: ["Although 已經負責建立讓步關係。", "第三項保留寒冷和外出兩項原始事實。"], cognitiveProcess: ["spot-although-but-redundancy", "delete-only-second-contrast-marker"], representationType: "double-contrast-proofreading", misconceptionTargets: ["repair-logic-by-changing-factual-adjective"] },
    { stem: "The coat has both facts, and the second is surprising: it is light ___ warm.", options: ["so", "because", "or", "yet"], answerIndex: 3, reasons: ["so 會把保暖寫成輕盈造成的結果。", "because 不能直接接 warm 作完整原因。", "or 會讓兩個已知特徵變成只能擇一。", "yet 表示外套輕卻仍然保暖。"], reviews: ["both facts 排除 or，surprising 指出預期落差。", "第四項凸顯 warm 與 light 帶來的預期不同。"], cognitiveProcess: ["contrast-low-weight-with-warmth", "select-yet-between-adjectives"], representationType: "compact-adjective-yet-contrast", misconceptionTargets: ["treat-two-coexisting-features-as-choice"] },
    { stem: "Ben wanted to go, but he stayed home. What can we know?", options: ["He wanted to go, but he did not go.", "He stayed home because he wanted to go.", "He went out and stayed home.", "The sentence does not tell what he did."], answerIndex: 0, reasons: ["第一項正確抓到想去與實際未外出的落差。", "句子沒有說想外出是留在家的原因。", "but 不會讓互相衝突的兩個行動同時完成。", "後句已明說他實際留在家中。"], reviews: ["wanted 描述意願，stayed 描述實際行動。", "第一項只根據兩個子句的轉折作答。"], cognitiveProcess: ["separate-intention-from-actual-action", "infer-contrast-without-inventing-cause"], representationType: "but-intention-outcome-inference", misconceptionTargets: ["treat-desire-as-completed-action"] },
    { stem: "Plan: the road is narrow; buses can still use it. Which report keeps the surprise?", options: ["The road is narrow because buses use it.", "The road is narrow, yet buses can use it.", "The road is narrow or buses can use it.", "The road is narrow, so buses cannot use it."], answerIndex: 1, reasons: ["第一項沒有證據說公車通行造成道路狹窄。", "第二項保留路窄但公車仍可通行的意外結果。", "第三項誤把兩項資料改成二選一。", "第四項把 can 改為 cannot，直接違反計畫資料。"], reviews: ["still 是結果出乎一般預期的明確線索。", "第二項沒有更動 road 或 buses 的事實。"], cognitiveProcess: ["map-still-to-unexpected-access", "choose-yet-with-narrow-road-data"], representationType: "plan-fact-to-yet-report", misconceptionTargets: ["reverse-can-to-cannot-for-easy-causality"] },
    { stem: "The room is clean and quiet. Which pair also joins two facts with and?", options: ["old but useful", "hurry or be late", "warm and bright", "tired yet working"], answerIndex: 2, reasons: ["old but useful 是轉折，不是同方向加入。", "hurry or be late 表示否則後果。", "warm and bright 與原句一樣平列兩個特徵。", "tired yet working 凸顯逆預期。"], reviews: ["原句的 clean、quiet 都是 room 的並列特徵。", "第三項使用相同的 and 加入方式。"], cognitiveProcess: ["abstract-additive-relation-from-model", "match-warm-and-bright-pair"], representationType: "connector-relation-analogy", misconceptionTargets: ["group-all-two-adjective-phrases-together"] },
    { stem: "The road was closed, yet the bus arrived on time. Which fact is the surprise?", options: ["The road was there.", "The road was closed.", "The bus had a driver.", "The bus arrived on time."], answerIndex: 3, reasons: ["道路存在不是 yet 後的資訊焦點。", "封路是建立預期的前件，不是被凸顯的結果。", "句中沒有提到駕駛。", "封路情況下仍準時抵達，這是 yet 標出的意外結果。"], reviews: ["yet 前後分別是阻礙與仍發生的事件。", "第四項位於轉折後且違反封路預期。"], cognitiveProcess: ["locate-unexpected-clause-after-yet", "identify-on-time-arrival-as-surprise"], representationType: "yet-focus-identification", misconceptionTargets: ["select-obstacle-instead-of-unexpected-result"] },
  ]),
  ...skillQuestions("143", [
    { stem: "Choose one drink: Would you like water ___ juice?", options: ["or", "and", "because", "yet"], answerIndex: 0, reasons: ["or 提供 water 與 juice 兩種飲料選擇。", "and 會詢問是否兩種都要，違反 one drink。", "because 不能把 juice 當成原因子句。", "yet 需要轉折，兩種飲料沒有預期落差。"], reviews: ["Choose one 要求對方在飲料間擇一。", "第一項保留兩個替代方案。"], cognitiveProcess: ["recognize-beverage-alternative-question", "join-water-or-juice"], representationType: "choice-question-cloze", misconceptionTargets: ["turn-choice-into-double-order"] },
    { stem: "If you do not leave now, you will be late. Keep the same meaning: Leave now, ___ you will be late.", options: ["and", "or", "because", "although"], answerIndex: 1, reasons: ["and 只會加入第二件事，未保留 if-not 後果。", "or 建立不現在離開就會遲到的警告。", "because 只提供現在離開的理由，不能重現 if-not 條件。", "although 需要讓步，前半命令不是從句。"], reviews: ["第一句明確指定不離開的後果。", "第二項把相同條件改寫成命令加 or。"], cognitiveProcess: ["interpret-imperative-plus-negative-consequence", "select-warning-or"], representationType: "imperative-or-warning-cloze", misconceptionTargets: ["read-warning-as-simple-sequence"] },
    { stem: "Ben drinks no tea and no coffee. Ben does not drink tea ___ coffee.", options: ["but", "and then", "or", "so"], answerIndex: 2, reasons: ["but 會暗示兩項有更正或轉折。", "and then 表示事件順序，不能連接飲料受詞。", "or 讓 tea 與 coffee 都落在 does not drink 的否定範圍。", "so 需要由原因推到結果。"], reviews: ["第一句明確表示兩種飲料都不喝。", "第三項讓 not 的作用延伸到 tea 與 coffee。"], cognitiveProcess: ["extend-negation-over-two-drink-objects", "use-or-in-negative-scope"], representationType: "negative-object-or-cloze", misconceptionTargets: ["use-and-with-negative-alternatives"] },
    { stem: "One call is enough: Call me tonight ___ tomorrow morning.", options: ["because", "but", "so", "or"], answerIndex: 3, reasons: ["because 會把 tomorrow morning 當成原因。", "but 需要兩個時間有預期反差。", "so 不能把明早當作今晚打電話的結果。", "or 提供今晚與明早兩個可用時間。"], reviews: ["One call is enough 排除兩個時間都打電話。", "第四項提供兩個可接受的替代時間。"], cognitiveProcess: ["identify-two-acceptable-call-times", "coordinate-tonight-or-tomorrow"], representationType: "time-alternative-cloze", misconceptionTargets: ["require-both-call-times-with-and"] },
    { stem: "If you do not wear a coat, you may feel cold. Keep the same meaning: Wear a coat, ___ you may feel cold.", options: ["or", "and", "but", "although"], answerIndex: 0, reasons: ["or 保留不穿外套可能會冷的 if-not 意思。", "and 只會說穿外套後接著可能感到冷。", "but 會把穿外套與可能感到冷寫成轉折。", "although 不能在此直接連接完整命令與主句。"], reviews: ["第一句已指定不照做時的後果。", "第一項把相同條件改寫成命令加 or。"], cognitiveProcess: ["derive-cold-risk-from-ignored-command", "apply-or-to-preventive-advice"], representationType: "advice-or-consequence-cloze", misconceptionTargets: ["choose-and-after-imperative"] },
    { stem: "A meal card says, 'Choose one: rice / noodles.' Which order follows the card?", options: ["I will have rice and noodles.", "I will have rice or noodles.", "I will have rice because noodles.", "I will have rice, yet noodles."], answerIndex: 1, reasons: ["第一項點了兩樣，違反 choose one。", "第二項用 or 保留兩個選項與單選限制。", "第三項把 noodles 當成不完整原因。", "第四項沒有形成可理解的轉折句。"], reviews: ["Choose one 是只能從兩項擇一的明確限制。", "第二項對應卡片上的斜線選項。"], cognitiveProcess: ["translate-one-choice-menu-rule", "select-rice-or-noodles-order"], representationType: "menu-rule-to-or-sentence", misconceptionTargets: ["ignore-one-item-limit"] },
    { stem: "A student writes, 'Hurry, and you will miss the bus.' Which change gives this meaning: If you do not hurry, you will miss the bus?", options: ["Hurry → Wait", "will → did", "and → or", "miss → take"], answerIndex: 2, reasons: ["改成 Wait 會更換要求的行動，不是修正連接。", "did 無法接在 will 後形成未來警告。", "or 表示不快一點就會錯過公車。", "改成 take 會把負面後果改成搭上車。"], reviews: ["題目指定不快一點就會錯過公車的意思。", "第三項只修正邏輯連接，不改事件內容。"], cognitiveProcess: ["diagnose-and-in-failed-warning", "replace-with-or-conditional-result"], representationType: "warning-connector-proofreading", misconceptionTargets: ["repair-warning-by-changing-outcome"] },
    { stem: "You can take the bus or walk. What does the sentence offer?", options: ["Why someone walks", "Two trips that are very different", "Two things a person must do", "Two ways to get there"], answerIndex: 3, reasons: ["句子沒有說明走路的原因。", "or 不在此比較兩趟行程的差異。", "兩種方式不是都必須完成。", "公車與步行是可選的兩種移動方式。"], reviews: ["can 與 or 共同建立可行方案。", "第四項不擅自加入單選規則以外的限制。"], cognitiveProcess: ["interpret-modal-or-as-available-alternatives", "identify-two-travel-methods"], representationType: "or-option-inference", misconceptionTargets: ["read-or-as-both-required"] },
    { stem: "Mia did not see Ben or Leo. What follows from this sentence?", options: ["She did not see Ben, and she did not see Leo.", "She saw only Ben.", "She saw both people.", "She chose who to see."], answerIndex: 0, reasons: ["第一項正確說明兩個人都在否定範圍內。", "原句沒有保留看見 Ben 的例外。", "did not see 與看見兩人直接矛盾。", "句子報告結果，不是描述選擇過程。"], reviews: ["or 連接 Ben、Leo 兩個受詞。", "第一項把相同否定範圍拆成兩個句子重述。"], cognitiveProcess: ["map-not-a-or-b-to-neither-nor", "reject-partial-positive-reading"], representationType: "negative-or-scope-inference", misconceptionTargets: ["negate-only-nearest-name"] },
    { stem: "Pay by Friday, or your seat will be given to another person. What does the second part tell us?", options: ["Another way to pay.", "What happens if the person pays late.", "Why Friday comes first.", "One more thing the person must do."], answerIndex: 1, reasons: ["後句沒有提供另一種付款方式。", "後句說明逾期未付時座位會被轉給別人。", "內容不在解釋日期順序。", "座位被轉讓不是讀者必須做的第二行動。"], reviews: ["命令加 or 後接的是違反期限的後果。", "第二項保留 by Friday 的條件界線。"], cognitiveProcess: ["identify-deadline-warning-consequence", "interpret-or-clause-as-noncompliance-result"], representationType: "deadline-or-function-analysis", misconceptionTargets: ["treat-consequence-as-alternative-action"] },
    { stem: "You need a card and a ticket. Which sentence keeps both needs?", options: ["Bring a card or stay home.", "Bring a card but a ticket.", "Bring your card and ticket.", "Bring a card because a ticket."], answerIndex: 2, reasons: ["第一項沒有要求攜帶票，還新增回家後果。", "第二項缺少可與 but 配合的完整結構。", "第三項以 and 保留卡片與票兩項必備物。", "第四項把 ticket 當成不完整原因。"], reviews: ["need 明確表示兩項都不能省略。", "第三項沒有把必備物改成選擇。"], cognitiveProcess: ["distinguish-required-pair-from-alternatives", "write-and-reminder-for-card-ticket"], representationType: "requirement-list-connector-selection", misconceptionTargets: ["use-or-for-two-mandatory-items"] },
    { stem: "Which line gives a choice of one drink?", options: ["Tea and milk.", "Tea because milk.", "Tea but milk.", "Tea or milk?"], answerIndex: 3, reasons: ["第一項同時列出兩種飲料，不是單選。", "第二項不是飲料選擇的完整因果句。", "第三項無法用轉折表達飲料選擇。", "第四項用 or 提供茶或牛奶兩個替代項。"], reviews: ["題目要求提供 one drink 的選擇。", "第四項是唯一用 or 連接兩種替代飲料的問句。"], cognitiveProcess: ["apply-one-drink-limit-to-request", "choose-or-under-exclusive-rule"], representationType: "rule-constrained-choice-request", misconceptionTargets: ["ignore-only-and-order-both"] },
  ]),
  ...skillQuestions("144", [
    { stem: "We closed the window ___ the rain was coming in.", options: ["because", "so", "although", "or"], answerIndex: 0, reasons: ["because 引出關窗的原因：雨正飄進來。", "so 應由原因接到結果，放此處會顛倒方向。", "although 會表示即使雨進來仍關窗，沒有合理反差。", "or 會把兩個事實改成替代或警告。"], reviews: ["後半句回答為何要關窗。", "第一項把原因放在 because 子句。"], cognitiveProcess: ["ask-why-window-was-closed", "select-because-before-rain-cause"], representationType: "result-because-cause-cloze", misconceptionTargets: ["reverse-because-and-so-direction"] },
    { stem: "The road was closed, ___ we took another way.", options: ["because", "so", "although", "when"], answerIndex: 1, reasons: ["because 會把改道寫成道路封閉的原因。", "so 由道路封閉推到改走別條路的結果。", "although 會表示改道是逆預期，情境沒有此意。", "when 只標示時間，未保留因果。"], reviews: ["前句提供造成改道的情況。", "第二項引出實際採取的結果。"], cognitiveProcess: ["trace-road-closure-to-route-change", "place-so-before-result-clause"], representationType: "cause-so-result-cloze", misconceptionTargets: ["use-because-before-consequence"] },
    { stem: "Because the bus was full, we ___ for the next one.", options: ["so waited", "although waited", "waited", "because waited"], answerIndex: 2, reasons: ["so waited 會在 Because 已標示原因後再加 so。", "although waited 把讓步詞塞在主句動詞前，結構不完整。", "waited 直接完成結果主句，不重複因果標記。", "because waited 會重複原因詞，也缺少新的完整子句。"], reviews: ["Because the bus was full 已經說明等待的原因。", "第三項讓 we waited for the next one 成為完整主句。"], cognitiveProcess: ["complete-main-clause-after-because", "avoid-second-cause-result-marker"], representationType: "because-main-clause-cloze", misconceptionTargets: ["insert-so-after-fronted-because"] },
    { stem: "The road was wet because it rained. Which part tells why the road was wet?", options: ["The road", "was wet", "The road was wet", "it rained"], answerIndex: 3, reasons: ["The road 只是受影響的事物。", "was wet 描述結果狀態，未包含原因事件。", "The road was wet 是 because 前的結果。", "it rained 位於 because 後並解釋路面為何濕。"], reviews: ["because 後的完整子句回答 why。", "第四項是造成路濕的事件。"], cognitiveProcess: ["locate-cause-clause-after-because", "separate-wet-result-from-rain-cause"], representationType: "causal-clause-role-identification", misconceptionTargets: ["select-result-before-because-as-cause"] },
    { stem: "Mia was sick, ___ she stayed home.", options: ["so", "because", "although", "or"], answerIndex: 0, reasons: ["so 由生病推到留在家的結果。", "because 會把 stayed home 當作生病原因，方向相反。", "although 會表示生病卻留在家，沒有預期落差。", "or 會把兩個已發生的事改成替代。"], reviews: ["sick 是前因，stayed home 是合理後果。", "第一項依資料順序引出結果。"], cognitiveProcess: ["map-illness-to-staying-home", "choose-so-after-explicit-cause"], representationType: "health-cause-result-cloze", misconceptionTargets: ["treat-result-as-because-cause"] },
    { stem: "We stayed inside for one reason: the air was bad. We stayed inside ___ the air was bad.", options: ["so", "because", "but", "when"], answerIndex: 1, reasons: ["so 會把空氣不好寫成待在室內造成的結果。", "because 引出留在室內的原因。", "but 需要前後有逆預期，題目已指定原因。", "when 只標示時間重疊，沒有保留 for one reason。"], reviews: ["第一句明確指定 the air was bad 是理由。", "第二項維持結果在前、原因在後的架構。"], cognitiveProcess: ["identify-bad-air-as-reason-for-staying", "insert-because-after-result-clause"], representationType: "action-because-condition-cloze", misconceptionTargets: ["reduce-cause-to-time-coincidence"] },
    { stem: "Because it rained, the game did not happen. Use so without changing the meaning.", options: ["The game did not happen, so it rained.", "It rained because the game did not happen.", "It rained, so the game did not happen.", "Although it rained, the game did not happen."], answerIndex: 2, reasons: ["第一項顛倒為比賽未舉行造成下雨。", "第二項也把比賽未舉行寫成雨勢原因。", "第三項先放原因 it rained，再以 so 引出比賽未舉行的結果。", "第四項改成讓步，暗示比賽未舉行出乎下雨預期。"], reviews: ["改寫只能調整句型，不能交換因果角色。", "第三項保持 rain → game did not happen 的方向。"], cognitiveProcess: ["transform-because-order-into-so-order", "preserve-rain-causes-cancellation"], representationType: "because-to-so-causal-rewrite", misconceptionTargets: ["reverse-causal-arrow-during-rewrite"] },
    { stem: "A student writes, 'Because the store was closed, so we left.' Which change keeps why they left?", options: ["closed → open", "left → stayed", "Because → And", "take out so"], answerIndex: 3, reasons: ["改成 open 會竄改商店狀態。", "改成 stayed 會更換原本離開的結果。", "And the store was closed, so we left 需要重新處理句首結構，並非最小修正。", "拿掉 so 後，Because 子句與 we left 主句已完整。"], reviews: ["原因是商店關門，結果是大家離開。", "第四項只刪重複標記，不改兩項內容。"], cognitiveProcess: ["retain-store-closure-and-leaving", "edit-double-causal-link-minimally"], representationType: "because-so-minimal-edit", misconceptionTargets: ["repair-connector-by-changing-event-outcome"] },
    { stem: "The floor was wet because a bottle fell. What can we know?", options: ["The bottle fell and made the floor wet.", "The wet floor made the bottle fall.", "The floor and bottle are two choices.", "The sentence does not tell why the floor was wet."], answerIndex: 0, reasons: ["第一項依 because 的方向連接瓶子掉落與地板濕。", "第二項把原因和結果倒置。", "句中沒有 or，也不是替代選擇。", "because 明確表示已有原因說明。"], reviews: ["because 前是濕地板結果，後是瓶子掉落原因。", "第一項不額外推測瓶內裝了什麼。"], cognitiveProcess: ["read-explicit-bottle-floor-causality", "avoid-reversing-because-direction"], representationType: "because-evidence-conclusion", misconceptionTargets: ["infer-wet-floor-caused-fall"] },
    { stem: "The bell rang, and the students got up. What can we NOT know for sure?", options: ["The bell rang.", "The bell made the students get up.", "The students got up.", "Both things happened."], answerIndex: 1, reasons: ["第一項由第一個子句直接得知。", "and 只並列事件，不能單獨證明鈴聲造成起立。", "第三項由第二個子句明說。", "兩個子句確實都被報告為發生。"], reviews: ["題目要求排除沒有明確連接詞支持的推論。", "第二項需要額外因果情境或 so、because 證據。"], cognitiveProcess: ["test-causal-claim-against-and-only", "identify-unsupported-bell-causation"], representationType: "and-versus-cause-inference-limit", misconceptionTargets: ["convert-sequence-into-cause"] },
    { stem: "The shop had no water. It closed early for that reason. Use so to join the facts.", options: ["The shop had no water, but it closed early.", "The shop had no water or it closed early.", "The shop had no water, so it closed early.", "Although the shop had no water, it closed early."], answerIndex: 2, reasons: ["but 會把關門寫成出乎預期的轉折。", "or 會讓缺水與關門變成替代事實。", "so 依題目指定的原因將缺水連到提早關門。", "although 會暗示即使缺水仍關門，邏輯方向不合。"], reviews: ["for that reason 明確宣告第一事造成第二事。", "第三項先保留原因，再用 so 引結果。"], cognitiveProcess: ["apply-explicit-for-that-reason-cue", "combine-no-water-so-early-close"], representationType: "stated-cause-to-so-sentence", misconceptionTargets: ["misread-causal-result-as-concession"] },
    { stem: "Because Nora missed the bus, she was late. Which answer shows why she was late?", options: ["Being late made her miss the bus.", "She had to choose between two things.", "The sentence only tells us the time.", "Missing the bus is why she was late."], answerIndex: 3, reasons: ["第一項把 because 的方向反過來。", "句中沒有 or，也不是選擇題意。", "because 不只提供時間，也明確指出遲到的原因。", "第四項正確以 missed the bus 解釋 late。"], reviews: ["Because 子句位於句首仍然是原因。", "第四項保留 Nora 的兩個事件與因果方向。"], cognitiveProcess: ["interpret-fronted-because-clause", "identify-missed-bus-as-lateness-cause"], representationType: "fronted-cause-role-inference", misconceptionTargets: ["treat-first-clause-as-result-because-of-position"] },
  ]),
  ...skillQuestions("145", [
    { stem: "The rain did not stop the game: ___ it was raining, the game did not stop.", options: ["Although", "Because", "So", "Or"], answerIndex: 0, reasons: ["Although 表示下雨形成阻礙，但比賽仍未停止。", "Because 會把下雨寫成比賽未停止的原因，違反前句。", "So 不能放句首直接引導這個從句。", "Or 不會建立雨勢與比賽的讓步關係。"], reviews: ["第一句明確指出下雨沒有阻止比賽。", "第一項承認下雨事實，同時保留比賽結果。"], cognitiveProcess: ["identify-rain-as-obstacle-not-cause", "front-concession-with-although"], representationType: "although-obstacle-result-cloze", misconceptionTargets: ["treat-obstacle-as-because-cause"] },
    { stem: "Being tired did not stop Nora from smiling: Nora smiled ___ she was tired.", options: ["because", "although", "so", "and then"], answerIndex: 1, reasons: ["because 會表示她因疲累而微笑，違反前句指定的阻礙關係。", "although 表示她雖累仍微笑。", "so 不能放在結果後再接 tired 作原因。", "and then 會改成先微笑後疲累的時間順序。"], reviews: ["前半句指定 tired 是沒有阻止 smile 的狀態。", "第二項可放句尾引出讓步資訊。"], cognitiveProcess: ["contrast-smiling-with-tiredness", "use-postposed-although-clause"], representationType: "sentence-final-although-cloze", misconceptionTargets: ["infer-tiredness-causes-smile"] },
    { stem: "A student writes, 'Although the bag was old, but it was useful.' Which change fixes it without changing either fact?", options: ["old → new", "useful → broken", "take out but", "Although → Because and keep but"], answerIndex: 2, reasons: ["改成 new 會竄改袋子老舊的事實。", "改成 broken 會更換 useful 的資訊。", "拿掉 but 後，although 已能完整連接老舊與仍有用。", "because 和 but 混接後無法建立清楚因果。"], reviews: ["錯誤是同一讓步關係用了兩個主要標記。", "第三項只移除多餘詞，不改內容。"], cognitiveProcess: ["preserve-old-useful-concession", "remove-but-after-although"], representationType: "although-but-proofreading", misconceptionTargets: ["repair-double-marker-by-changing-facts"] },
    { stem: "Although the box was small, it ___ many books.", options: ["but held", "so held", "because held", "held"], answerIndex: 3, reasons: ["but held 會重複 although 的轉折功能。", "so held 把裝很多書寫成箱子小的自然結果。", "because held 不能在主句動詞前另加原因詞。", "held 直接完成主句，表示箱子雖小仍裝得下許多書。"], reviews: ["Although 子句已提供阻礙與預期。", "第四項讓主句保留單一過去式動詞。"], cognitiveProcess: ["complete-main-clause-after-fronted-concession", "avoid-second-linker-before-held"], representationType: "although-main-clause-completion", misconceptionTargets: ["insert-but-after-fronted-although"] },
    { stem: "Although Leo was afraid, he opened the door. What can we know?", options: ["He was afraid and still opened the door.", "Opening the door made him afraid.", "He did not open the door.", "He was not really afraid."], answerIndex: 0, reasons: ["第一項保留害怕與開門兩項都成立。", "although 沒有說開門使他害怕。", "第三項直接否定主句已陳述的行動。", "讓步句承認他害怕，不能說他其實不怕。"], reviews: ["although 不會取消從句中的事實。", "第一項呈現阻礙存在但行動仍發生。"], cognitiveProcess: ["retain-both-concession-facts", "infer-action-despite-fear"], representationType: "although-two-fact-inference", misconceptionTargets: ["negate-obstacle-clause"] },
    { stem: "Although it was late, we did not stop talking. Which sentence keeps the same meaning?", options: ["We did not stop talking because it was late.", "We did not stop talking although it was late.", "We were late, so we talked.", "We did not stop talking or it was late."], answerIndex: 1, reasons: ["第一項把 late 改成持續交談的原因。", "第二項只把 although 子句移到後面，讓步不變。", "第三項改變主詞資訊，也換成因果。", "第四項將兩個都成立的事實改成選擇。"], reviews: ["子句位置可改，late 與 did not stop talking 的角色不能換。", "第二項維持相同的阻礙與結果。"], cognitiveProcess: ["move-although-clause-without-logic-change", "match-postposed-concession-equivalent"], representationType: "although-clause-order-equivalence", misconceptionTargets: ["turn-concession-into-because-cause"] },
    { stem: "The water was cold. Ben still went swimming. Which line keeps both facts?", options: ["Ben went swimming because the water was cold.", "The water was cold, so Ben stayed out.", "Although the water was cold, Ben went swimming.", "The water was cold or Ben went swimming."], answerIndex: 2, reasons: ["第一項捏造冷水是游泳原因。", "第二項把實際 went swimming 改成 stayed out。", "第三項用 although 表示冷水阻礙下仍游泳。", "第四項把兩項已知事實改成二選一。"], reviews: ["still 明確提示結果不受阻礙改變。", "第三項完整保留 cold 與 went swimming。"], cognitiveProcess: ["map-anyway-to-concession", "combine-cold-water-and-swimming"], representationType: "two-fact-anyway-to-although", misconceptionTargets: ["replace-actual-action-for-simple-causality"] },
    { stem: "The tea was hot, but Nora drank it. Use although without changing the meaning.", options: ["Nora drank it because the tea was hot.", "The tea was hot, so Nora drank it.", "Although Nora drank it, so the tea was hot.", "Although the tea was hot, Nora drank it."], answerIndex: 3, reasons: ["第一項改成熱茶造成飲用的原因。", "第二項同樣把轉折改為因果。", "第三項顛倒從句角色，並重複 although 與 so。", "第四項以 hot 為阻礙，保留 Nora 仍喝茶。"], reviews: ["原句 but 後是出乎熱茶預期的行動。", "第四項只改連接架構，沒有改事實。"], cognitiveProcess: ["convert-but-contrast-to-although-clause", "preserve-hot-tea-drinking"], representationType: "but-to-although-rewrite", misconceptionTargets: ["reverse-concession-clause-roles"] },
    { stem: "The day was warm ___ sunny; both facts made the picnic good.", options: ["and", "although", "but", "or"], answerIndex: 0, reasons: ["and 加入 warm 與 sunny 兩個同方向條件。", "although 需要其中一項形成阻礙，題目卻說兩者都有幫助。", "but 會製造不存在的天氣反差。", "or 會把兩個都成立的事實改成選擇。"], reviews: ["both facts 明確排除替代與讓步。", "第一項保留兩種好天氣條件。"], cognitiveProcess: ["use-both-positive-facts-to-reject-concession", "join-warm-and-sunny"], representationType: "nonconcession-additive-cloze", misconceptionTargets: ["choose-but-from-different-adjectives-alone"] },
    { stem: "Although the store was open, no one was inside. What is the surprise?", options: ["The store had a door.", "No one was inside even though it was open.", "The store was not open.", "People were inside before it opened."], answerIndex: 1, reasons: ["句中沒有提到門。", "第二項指出營業中卻沒人的預期落差。", "第三項否定 although 子句已承認的 open。", "第四項加入原文沒有的時間事件。"], reviews: ["open 通常讓人預期店內有人。", "第二項位於主句並與該預期相反。"], cognitiveProcess: ["derive-expectation-from-open-store", "locate-empty-store-as-concession-result"], representationType: "although-unexpected-result-identification", misconceptionTargets: ["deny-open-fact-to-resolve-contrast"] },
    { stem: "A note says, 'Although Mia was busy, but she answered.' Which change fixes only the joining-word error?", options: ["busy → free", "answered → waited", "take out but", "Mia → she"], answerIndex: 2, reasons: ["改成 free 會移除原本阻礙。", "改成 waited 會更換主句行動。", "拿掉 but 後，although 已足以連接忙碌與仍回覆。", "替換姓名不能修正雙重轉折標記。"], reviews: ["題目要求只處理連接詞錯誤。", "第三項使兩個事實和時態都保持原樣。"], cognitiveProcess: ["isolate-connector-only-error", "delete-redundant-but-in-note"], representationType: "minimal-although-repair", misconceptionTargets: ["change-content-instead-of-connector"] },
    { stem: "Nora had only ten minutes. She finished the work. Which report shows the surprise?", options: ["Nora finished because she had only ten minutes.", "Nora had ten minutes, so she did not finish.", "Nora had ten minutes or she finished.", "Although Nora had only ten minutes, she finished the work."], answerIndex: 3, reasons: ["第一項將短時間捏造成完成工作的原因。", "第二項把 finished 改成 did not finish。", "第三項把兩項都成立的資料改成選擇。", "第四項表示時間很少但仍完成。"], reviews: ["only ten minutes 是可能妨礙完成的條件。", "第四項保留時間很少卻仍完成的結果。"], cognitiveProcess: ["frame-time-shortage-as-obstacle", "write-although-completion-report"], representationType: "limited-time-concession-report", misconceptionTargets: ["reverse-completion-to-fit-cause"] },
  ]),
  ...skillQuestions("146", [
    { stem: "Turn off the computer ___ you leave.", options: ["before", "after", "when after", "because of"], answerIndex: 0, reasons: ["before 表示先關電腦再離開。", "after 會要求離開後才關機，無法執行。", "when after 是重複且不合的連接形式。", "because of 後需接名詞片語，不能直接接 you leave。"], reviews: ["關機必須發生在仍能操作電腦時。", "第一項建立可執行的安全順序。"], cognitiveProcess: ["order-shutdown-before-departure", "select-before-time-clause"], representationType: "instruction-before-clause-cloze", misconceptionTargets: ["follow-word-order-instead-of-action-feasibility"] },
    { stem: "We will start when the rain ___.", options: ["will stop", "stops", "stopped", "stopping"], answerIndex: 1, reasons: ["when 未來時間子句不再使用 will stop。", "stops 以現在式表達未來的時間界線。", "stopped 會把雨停寫成已完成過去事件。", "stopping 缺少能完成子句的限定動詞。"], reviews: ["主句 will start 已表達未來。", "第二項符合 when 子句使用現在式的規則。"], cognitiveProcess: ["detect-future-time-clause-after-when", "use-present-stops-not-will-stop"], representationType: "future-when-clause-form-cloze", misconceptionTargets: ["repeat-will-in-time-clause"] },
    { stem: "Nora called me after she ___ home.", options: ["called", "was calling", "got", "gets"], answerIndex: 2, reasons: ["called 會變成她打電話後又打電話，少了到家事件。", "was calling 表示進行中的通話，不能提供較早的到家點。", "got home 表示先到家，之後才打電話。", "gets 是現在式，與 called 的過去敘事不一致。"], reviews: ["after 子句應提供打電話前已發生的事件。", "第三項建立 got home → called 的順序。"], cognitiveProcess: ["seek-prior-event-inside-after-clause", "choose-got-home-before-call"], representationType: "after-clause-event-completion", misconceptionTargets: ["repeat-main-action-in-time-clause"] },
    { stem: "___ the bell rang, the students left the room.", options: ["Because of", "Although of", "So", "When"], answerIndex: 3, reasons: ["Because of 後不能直接接 the bell rang 完整子句。", "Although of 不是標準連接形式。", "So 不能在此引導句首時間子句。", "When 連接鈴響時與學生離開的事件。"], reviews: ["the bell rang 是主句行動發生的時間點。", "第四項形成完整的 When 子句。"], cognitiveProcess: ["classify-bell-ringing-as-time-trigger", "front-when-clause-before-departure"], representationType: "fronted-when-event-cloze", misconceptionTargets: ["choose-cause-form-with-of-before-clause"] },
    { stem: "Ben washed the cup before he put it away. What happened first?", options: ["Ben washed the cup.", "Ben put the cup away.", "Both actions ended at the same time.", "The sentence does not give an order."], answerIndex: 0, reasons: ["before 明確表示洗杯子先發生。", "收杯子位於 before 後的較晚事件。", "句子不是描述兩件事同時。", "before 已提供順序，不能說未知。"], reviews: ["文字中 washed 雖先出現，仍要以 before 驗證。", "第一項也是實際較早的動作。"], cognitiveProcess: ["sequence-wash-and-put-away-via-before", "identify-washing-as-first-event"], representationType: "before-order-inference", misconceptionTargets: ["ignore-explicit-before-order"] },
    { stem: "After Mia ate dinner, she washed the dishes. Which sentence has the same order?", options: ["Mia ate dinner after she washed the dishes.", "Mia washed the dishes after she ate dinner.", "Mia washed dishes before she ate.", "When Mia washed dishes, dinner was not eaten."], answerIndex: 1, reasons: ["第一項把洗碗改成較早事件。", "第二項仍是先吃晚餐、後洗碗。", "第三項同樣顛倒兩個行動。", "第四項加入晚餐未吃的新資訊。"], reviews: ["after 子句移到句尾不會改變先後。", "第二項保持 ate → washed 的時間線。"], cognitiveProcess: ["move-after-clause-to-sentence-end", "preserve-dinner-before-dishes"], representationType: "after-clause-order-equivalence", misconceptionTargets: ["reverse-events-while-moving-clause"] },
    { stem: "A student writes, 'I will call when I will arrive.' Which change fixes the time words?", options: ["I → Me", "call → called", "will arrive → arrive", "when → because"], answerIndex: 2, reasons: ["I 是正確主詞，不需改受格 Me。", "called 會把主句改成過去式。", "when 未來時間子句使用現在式 arrive。", "because 會把抵達改成打電話原因，並未修正時態原則。"], reviews: ["第一個 will 已在主句標示未來。", "第三項形成 I will call when I arrive。"], cognitiveProcess: ["locate-extra-will-inside-when-clause", "replace-with-present-arrive"], representationType: "future-time-clause-proofreading", misconceptionTargets: ["change-main-tense-instead-of-subordinate-will"] },
    { stem: "Please call me ___ you reach the station.", options: ["so", "although", "or", "when"], answerIndex: 3, reasons: ["so 會把到站寫成打電話造成的結果。", "although 需要逆預期，題目只是指定時間。", "or 會變成不打電話的後果或選擇，但句子沒有後句。", "when 表示到站時打電話。"], reviews: ["reach the station 是通話應發生的時間界線。", "第四項不擅自增加原因或警告。"], cognitiveProcess: ["use-arrival-as-call-time", "select-when-for-contact-instruction"], representationType: "when-contact-time-cloze", misconceptionTargets: ["misread-time-condition-as-cause"] },
    { stem: "Plan: talk ends at 3:00; game begins at 3:10. Which line follows the plan?", options: ["The game begins after the talk ends.", "The game begins before the talk ends.", "The talk begins after the game.", "The game and talk must begin together."], answerIndex: 0, reasons: ["3:10 晚於 3:00，因此比賽在談話結束後開始。", "第二項與時間數字的先後相反。", "計畫只給談話結束，且比賽較晚。", "兩個時間相差十分鐘，不是同時。"], reviews: ["先比較 3:00 與 3:10，再選時間連接詞。", "第一項完整保留活動名稱和順序。"], cognitiveProcess: ["translate-schedule-times-into-after-relation", "place-game-after-talk"], representationType: "schedule-to-after-sentence", misconceptionTargets: ["reverse-clock-order-in-clause"] },
    { stem: "Nora closed the door after everyone left. Who acted first?", options: ["Nora closed the door first.", "Everyone left first.", "Both acted at the same moment.", "No person acted."], answerIndex: 1, reasons: ["closed 位於主句不代表關門先發生。", "after everyone left 表示大家先離開。", "after 建立前後，不是完全同時。", "兩個子句都明說有人行動。"], reviews: ["要依 after 解讀，不依句子左右順序。", "第二項是 after 子句所指的較早事件。"], cognitiveProcess: ["override-text-order-with-after-logic", "identify-everyone-leaving-first"], representationType: "after-inverted-text-order-inference", misconceptionTargets: ["equate-first-written-with-first-happened"] },
    { stem: "Dad will arrive later. We will eat after that. Which sentence uses the future time words correctly?", options: ["We eat after Dad will arrive.", "We will eat after Dad will arrive.", "We will eat after Dad arrives.", "We will ate after Dad arrives."], answerIndex: 2, reasons: ["第一項主句沒有表達已給定的未來安排，子句又多用 will。", "第二項在 after 子句重複 will。", "第三項主句用 will eat，after 子句用現在式 arrives。", "第四項 will 後誤用過去式 ate。"], reviews: ["兩個事件都在未來，不代表兩個子句都用 will。", "第三項同時鎖住主句與時間子句形式。"], cognitiveProcess: ["construct-future-main-plus-present-after-clause", "select-will-eat-after-arrives"], representationType: "future-after-clause-selection", misconceptionTargets: ["put-will-in-both-clauses"] },
    { stem: "Rule: leave the room only after the light is off. Which sentence follows it?", options: ["Leave before you turn off the light.", "Leave when the light is still on.", "Turn on the light after you leave.", "Turn off the light before you leave."], answerIndex: 3, reasons: ["第一項直接違反 only after 的先後限制。", "第二項仍在燈亮著時離開。", "第三項要求離開後開燈，和規則無關。", "第四項確保關燈先於離開。"], reviews: ["only after the light is off 把關燈設為必要前件。", "第四項以 before 從相反方向表達同一順序。"], cognitiveProcess: ["convert-only-after-rule-to-before-sentence", "verify-light-off-precedes-leaving"], representationType: "rule-time-rewrite", misconceptionTargets: ["reverse-required-order"] },
  ]),
  ...skillQuestions("147", [
    { stem: "The teacher was friendly ___ helpful; both made the trip better.", options: ["and", "but", "or", "because"], answerIndex: 0, reasons: ["and 加入 friendly、helpful 兩項同方向特質。", "but 會製造題目沒有的反差。", "or 會把兩項都成立的特質改成選擇。", "because 不能直接接 helpful 形成原因子句。"], reviews: ["both 是明確的加法線索。", "第一項維持兩個形容詞的平行。"], cognitiveProcess: ["classify-both-positive-qualities-as-addition", "choose-and-in-integrated-item"], representationType: "mixed-connector-addition-cloze", misconceptionTargets: ["choose-but-for-different-adjectives"] },
    { stem: "The work looked easy, ___ it took two hours.", options: ["so", "but", "because", "when"], answerIndex: 1, reasons: ["so 會把耗時兩小時寫成看似容易的自然結果。", "but 表示外觀看似容易，實際卻很耗時。", "because 會把耗時當成看似容易的原因。", "when 只會建立時間關係，未表達落差。"], reviews: ["looked easy 建立應快速完成的預期。", "第二項由 two hours 修正該預期。"], cognitiveProcess: ["contrast-easy-appearance-with-long-duration", "select-but-among-mixed-connectors"], representationType: "mixed-connector-contrast-cloze", misconceptionTargets: ["turn-unexpected-duration-into-so-result"] },
    { stem: "You may read here ___ take the book home.", options: ["because", "although", "or", "so"], answerIndex: 2, reasons: ["because 會把帶書回家當成在此閱讀的原因。", "although 需要讓步，兩項是方案。", "or 提供在此閱讀或帶回家兩種選擇。", "so 會把帶回家寫成前項結果。"], reviews: ["may 表示兩種允許的做法。", "第三項保留替代方案而非因果。"], cognitiveProcess: ["recognize-two-permitted-actions", "choose-or-for-library-options"], representationType: "mixed-connector-option-cloze", misconceptionTargets: ["misread-permission-options-as-result"] },
    { stem: "The wind became strong, and that made us move inside. We moved inside ___ the wind became strong.", options: ["so", "yet", "and", "because"], answerIndex: 3, reasons: ["so 會把強風寫成移到室內造成的結果。", "yet 需要出乎預期的轉折。", "and 只能並列，不能保留 made us move 的理由。", "because 引出移到室內的原因。"], reviews: ["第一句明確指定強風造成移動。", "第四項維持結果在前、原因在後。"], cognitiveProcess: ["identify-strong-wind-as-movement-cause", "choose-because-in-mixed-set"], representationType: "mixed-connector-because-cloze", misconceptionTargets: ["select-and-for-related-events-without-cause"] },
    { stem: "The road was not safe. The park closed it for that reason. Use so to join the facts.", options: ["The road was not safe, so the park closed it.", "Although the road was not safe, the park closed it.", "The road was not safe or the park closed it.", "The road was not safe before the park closed it."], answerIndex: 0, reasons: ["第一項用 so 由道路不安全推到公園封閉的結果。", "第二項改成讓步，沒有保留 for that reason。", "第三項把道路不安全與公園封閉誤寫成只能擇一。", "第四項只建立時間，不能保留因果。"], reviews: ["for that reason 指定道路不安全是封路原因。", "第一項先放原因，再用 so 接管理行動。"], cognitiveProcess: ["trace-unsafe-path-to-closure", "select-so-in-integrated-causal-item"], representationType: "mixed-connector-so-rewrite", misconceptionTargets: ["replace-cause-with-time-before"] },
    { stem: "___ the line was long, we got our tickets on time.", options: ["Because", "Although", "So", "After of"], answerIndex: 1, reasons: ["Because 會把長隊伍當成準時拿票的原因。", "Although 表示排隊很長但仍及時拿到票。", "So 不能直接引導此句首從句。", "After of 不是可接 the line was long 的連接形式。"], reviews: ["long line 是可能造成延誤的阻礙。", "第二項保留 on time 的逆預期結果。"], cognitiveProcess: ["frame-long-line-as-concession-obstacle", "choose-although-in-mixed-set"], representationType: "mixed-connector-concession-cloze", misconceptionTargets: ["choose-because-for-obstacle"] },
    { stem: "We will begin ___ everyone is ready.", options: ["because of", "so", "when", "although"], answerIndex: 2, reasons: ["because of 後不能直接接 everyone is ready 完整子句。", "so 不能把 ready 子句放成結果接在此處。", "when 把大家準備好設為開始時刻。", "although 會表示即使準備好仍開始，沒有反差。"], reviews: ["ready 是未來開始的時間界線。", "第三項也要求子句保持現在式 is。"], cognitiveProcess: ["classify-readiness-as-start-time", "choose-when-in-mixed-set"], representationType: "mixed-connector-when-cloze", misconceptionTargets: ["use-cause-form-before-complete-clause"] },
    { stem: "Mia checked the meeting place at 8:00. She left home at 8:10. Mia checked the meeting place ___ she left home.", options: ["so", "because", "although", "before"], answerIndex: 3, reasons: ["so 會把離家寫成確認地點的結果，沒有表達兩個時間的先後。", "because 會表示她因離家而確認地點，方向與時間不合。", "although 需要讓步落差，題目只有明確順序。", "before 表示 8:00 的確認早於 8:10 的離家。"], reviews: ["8:00 早於 8:10，提供明確時間線。", "第四項把兩個行動依資料順序連起來。"], cognitiveProcess: ["order-address-check-before-departure", "choose-before-in-mixed-set"], representationType: "mixed-connector-before-cloze", misconceptionTargets: ["replace-time-order-with-vague-cause"] },
    { stem: "Rain stopped. The game began. The ground was still wet. Which report keeps the time order and the surprise?", options: ["When the rain stopped, the game began, but the ground was still wet.", "Because the ground was wet, the rain stopped or the game began.", "Although the game began, so the ground was wet.", "The rain stopped and the ground was dry before the game."], answerIndex: 0, reasons: ["第一項以 when 連接開始時間，再用 but 保留地面仍濕。", "第二項捏造濕地造成停雨，並把事件改成選擇。", "第三項重複 although 與 so，且因果不明。", "第四項把 still wet 改成 dry，違反資料。"], reviews: ["三項資料包含時間接續與停雨後地面仍濕的狀態。", "第一項使用兩種不同連接功能而不改事實。"], cognitiveProcess: ["integrate-rain-stop-game-start-and-wet-field", "assign-when-then-but-relations"], representationType: "multi-connector-three-fact-report", misconceptionTargets: ["simplify-by-reversing-wet-to-dry"] },
    { stem: "The lights went out because the rain became strong. Use so without changing why the lights went out.", options: ["The lights went out, so the rain became strong.", "The rain became strong, so the lights went out.", "Although the rain became strong, the lights went out.", "The rain became strong or the lights went out."], answerIndex: 1, reasons: ["第一項反轉為停電造成雨勢變強。", "第二項先放 rain became strong 原因，再以 so 接 lights went out 結果。", "第三項改成讓步，表示停電出乎強雨預期。", "第四項把兩個都發生的事件改成選擇。"], reviews: ["改寫時要交換子句位置，但不能交換因果角色。", "第二項保持 strong rain → lights out 的方向。"], cognitiveProcess: ["rewrite-because-cause-after-result-into-so-order", "preserve-storm-power-loss-arrow"], representationType: "integrated-because-to-so-rewrite", misconceptionTargets: ["swap-cause-and-result-with-clause-order"] },
    { stem: "Which line uses one joining word for each meaning?", options: ["Although it was cold, but we walked.", "Because it was late, so we left.", "It was cold, but we walked, and we talked.", "When we arrived, so the door opened."], answerIndex: 2, reasons: ["第一項用 although 和 but 重複標記同一讓步。", "第二項用 because 和 so 重複標記同一因果。", "第三項分別以 but 表轉折、and 加入另一行動，每個關係只有一個標記。", "第四項將 when 與 so 不當疊在同一連接位置。"], reviews: ["題目不是只數連接詞，而要分辨它們各自負責的關係。", "第三項有兩個不同邏輯連結，所以可各用一詞。"], cognitiveProcess: ["audit-one-marker-per-logical-link", "distinguish-two-valid-links-from-double-marking"], representationType: "connector-stack-structure-audit", misconceptionTargets: ["treat-any-two-connectors-as-redundant"] },
    { stem: "Mia needed the book that day. The library was closed, and this made her borrow it from Ben.", options: ["Mia borrowed the book, although the library was closed.", "The library was closed or Mia borrowed the book.", "Mia needed the book before the library was closed.", "Because the library was closed, Mia borrowed the book from Ben."], answerIndex: 3, reasons: ["第一項改成讓步，沒有保留關門造成借書的因果。", "第二項把關門與借書改成替代事件。", "第三項只寫時間順序，且遺漏向 Ben 借書的結果。", "第四項以 because 引出關門原因並保留借書結果。"], reviews: ["this made her 明確指定因果，不只是背景。", "第四項也保留借書來源 Ben。"], cognitiveProcess: ["map-explicit-closure-caused-borrowing", "select-because-report-with-source-detail"], representationType: "integrated-context-causal-report", misconceptionTargets: ["downgrade-explicit-cause-to-concession"] },
  ]),
];

export const ENGLISH_U21_VOCABULARY_POLICY = Object.freeze({
  capQuestionBasis: "appendix-5-table-1",
  additionalLearningTerms: ["narrow"],
  properNames: ["Amy", "Ben", "Leo", "Mia", "Nora"],
  grammarNotation: ["B"],
  malformedDistractors: [],
});

export const ENGLISH_U21_SOURCE = Object.freeze({ unitId: UNIT_ID, lectures: ENGLISH_U21_LECTURES, questions: ENGLISH_U21_QUESTIONS, vocabularyPolicy: ENGLISH_U21_VOCABULARY_POLICY });
export const ENGLISH_UNIT_SOURCE = ENGLISH_U21_SOURCE;
