const UNIT_ID = "ENG_R4_U25";

function lecture(id, skillId, content) {
  return { id, skillId, ...content, sections: content.sections.map((section, index) => ({ id: id + "_SEC_" + String(index + 1).padStart(2, "0"), ...section })) };
}

const DIFFICULTIES = ["foundation", "foundation", "foundation", "standard", "standard", "standard", "standard", "advanced", "advanced", "advanced", "transfer", "transfer"];

function skillQuestions(skillNumber, values) {
  if (values.length !== 12) throw new Error("ENG_R4_S" + skillNumber + ": expected 12 authored questions");
  return values.map((value, index) => ({ id: "ENG_R4_Q_" + skillNumber + "_" + String(index + 1).padStart(2, "0"), skillId: "ENG_R4_S" + skillNumber, difficulty: DIFFICULTIES[index], ...value }));
}

export const ENGLISH_U25_LECTURES = [
  lecture("ENG_R4_L_S169", "ENG_R4_S169", {
    objectives: ["辨認 if 子句所提出的條件與主要子句所說的結果。", "在兩種子句順序中保留相同的條件關係。"],
    sections: [
      { title: "if 引出結果成立的條件", content: "If you push this button, the light turns on 中，push this button 是條件，the light turns on 是條件成立時的結果。if 不是單純表示先後順序；它建立的是「在這個條件下，結果才適用」的關係。" },
      { title: "條件與結果都需要完整意思", content: "if 子句通常有自己的主詞與動詞，例如 if the bus is late。主要子句也要說明結果，例如 we will walk。只寫 If the bus is late. 會留下尚未說完的條件，讀者不知道接著會怎樣。" },
      { title: "兩個子句可以交換位置", content: "If it rains, we will stay home 與 We will stay home if it rains 表達同一個基本條件。if 子句在前時，書寫上通常用逗號分隔；放在後面時，本單元的基本句型不加逗號。" },
      { title: "先分清楚哪件事是條件", content: "在 If Nora calls, I will tell her the news 中，Nora calls 是觸發後續行動的條件，tell her the news 才是結果。不能因主要句比較長，就把它誤認成條件，也不能把兩個事件任意倒轉。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S169_EX_01", prompt: "If the door is open, the room gets cold. What is the condition?", steps: ["找出 if 開頭的子句。", "確認子句中的主詞與動詞。", "把另一子句保留為結果。"], answer: "The door is open.", why: "if 直接引出 the door is open，所以這是結果成立的條件；the room gets cold 說明條件成立時房間的變化，不能把兩者對調。" },
      { id: "ENG_R4_L_S169_EX_02", prompt: "We will take the bus if the rain starts. What will happen as a result?", steps: ["定位句尾的 if 子句。", "把 the rain starts 判為條件。", "讀取主要子句中的行動。"], answer: "We will take the bus.", why: "句尾 if the rain starts 提出下雨這個條件，主要子句 We will take the bus 才是預定結果。if 子句放後面不會改變兩者角色。" },
      { id: "ENG_R4_L_S169_EX_03", prompt: "Join the ideas: You need help. Call me. Use if.", steps: ["判斷需要幫助是條件。", "把 call me 放在結果位置。", "用 if 連成完整句。"], answer: "If you need help, call me.", why: "需要幫助時才採取打電話的行動，因此 if you need help 是條件，call me 是祈使結果。這個句型不需要再重複 you 作祈使句主詞。" },
    ],
    misconceptions: [
      { belief: "看到 if 就把後面整句都當成結果。", whyWrong: "if 引出的子句本身通常是條件，結果位於另一個子句。", correction: "先圈出 if 子句，再問條件成立時會發生什麼。" },
      { belief: "條件子句一定要放在整句最前面。", whyWrong: "if 子句也能放在主要子句後面，基本關係不變。", correction: "比較 If it rains, we will wait 與 We will wait if it rains。" },
      { belief: "只有未來式的主要句才能和 if 連用。", whyWrong: "一般事實、祈使句與情態動詞也能作為結果。", correction: "依要表達的事實或行動選結果形式，不只尋找 will。" },
      { belief: "只寫 if 子句就已經表達完整結果。", whyWrong: "單獨條件通常沒有交代條件成立後的情況。", correction: "檢查整句是否同時具備條件與結果兩部分。" },
    ],
    checks: [
      { prompt: "If the shop is closed, we will come back 中，條件是什麼？", answer: "the shop is closed", reason: "這一段由 if 直接引出。" },
      { prompt: "I will call you if the time changes 中，結果是什麼？", answer: "I will call you", reason: "句尾 if 子句提出 time changes 這個條件。" },
      { prompt: "if 子句放後面會把條件變成結果嗎？", answer: "不會", reason: "位置可交換，角色仍由 if 與句意決定。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S170", "ENG_R4_S170", {
    objectives: ["用現在式條件句表達反覆成立的一般事實與規則。", "區分一般結果與只發生一次的未來預測。"],
    sections: [
      { title: "一般事實常用現在式配現在式", content: "If water gets very cold, it turns into ice 描述可反覆觀察的結果，因此條件與結果都用現在式。這種句型重點不在某一次未來事件，而在每當條件成立，通常就會出現相同結果。" },
      { title: "習慣與操作規則也能使用相同結構", content: "If I miss the early bus, I walk to school 說明說話者的慣常做法；If you push the green button, the door opens 則說明操作結果。現在式在這裡表達規律，不代表事情正在此刻發生。" },
      { title: "一般事實不需要 will", content: "If plants do not get water, they die 是一般條件與結果，主要句使用 die。若改成 will die，句意容易轉成某次可能的未來結果，不再是本技能要表達的普遍或反覆關係。" },
      { title: "不能只因兩句都是現在式就建立因果", content: "兩個現在式事件仍需有合理條件關係。If the library opens, the sun is hot 雖然形式像條件句，內容卻沒有可支持的一般關聯。語法形式與句意都要檢查。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S170_EX_01", prompt: "If ice gets warm enough, it ___. (turns to water / turned to water yesterday)", steps: ["判斷句子描述一般現象。", "保留兩個子句的現在式。", "選擇不帶特定過去時間的結果。"], answer: "turns to water", why: "冰的溫度高到無法維持固態時會變成水，這是可反覆觀察的一般現象，所以主要句用現在式 turns to water。yesterday 只表示某一次過去，不符合題意。" },
      { id: "ENG_R4_L_S170_EX_02", prompt: "If Mia has time after school, she reads in the library. Is this a habit or one future plan?", steps: ["查看兩個子句的時態。", "尋找固定未來時間。", "判斷條件是否可反覆發生。"], answer: "A habit.", why: "has 與 reads 都是現在式，而且沒有指出某一個日期；句子說明 Mia 每逢課後有時間時的習慣，不是一次性的未來安排。" },
      { id: "ENG_R4_L_S170_EX_03", prompt: "Complete the rule: If the red light is on, the machine ___. (stops / stopped)", steps: ["把內容讀成設備規則。", "確認 if 子句使用現在式。", "用現在式表示固定反應。"], answer: "stops", why: "紅燈亮起時機器停止，是設備反覆遵循的規則。is on 與 stops 都使用現在式；stopped 會把結果放到已結束的過去事件。" },
    ],
    misconceptions: [
      { belief: "現在式只表示說話當下正在發生的事。", whyWrong: "現在式也可表達習慣、規則與一般事實。", correction: "從 always、every time 或可反覆條件判斷一般用法。" },
      { belief: "if 句提到結果時，主要句一定要加 will。", whyWrong: "一般事實的結果通常仍用現在式。", correction: "先判斷是普遍規律還是某次未來可能。" },
      { belief: "條件與結果都是現在式，就一定是一個正確的一般事實。", whyWrong: "內容還必須具有合理且可理解的條件關係。", correction: "檢查結果是否真的會在該條件下反覆成立。" },
      { belief: "一般條件句只能描述自然現象。", whyWrong: "習慣、操作說明與固定規則也可使用。", correction: "辨認條件是否每次都導向相同做法或結果。" },
    ],
    checks: [
      { prompt: "If I feel tired, I go to bed early 是習慣還是單次未來？", answer: "習慣", reason: "兩個子句都用現在式，表示反覆做法。" },
      { prompt: "If you mix blue and yellow, you get green 的結果動詞是什麼？", answer: "get", reason: "一般結果使用現在式。" },
      { prompt: "一般事實句是否必須包含 tomorrow？", answer: "不必", reason: "特定未來時間反而會改變一般性。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S171", "ENG_R4_S171", {
    objectives: ["用第一類條件句表達真實且可能發生的未來條件。", "在結果子句中選用 will、can、may 或合理行動。"],
    sections: [
      { title: "可能未來使用 if 加現在式", content: "If it rains tomorrow, we will stay home 表示明天可能下雨，也可能不下雨。雖然條件指向未來，if 子句仍使用 rains；主要句以 will stay 說明條件成立後的未來結果。" },
      { title: "第一類條件句不保證條件一定成立", content: "If Ben finishes early, he will join us 並沒有說 Ben 已經完成，也沒有保證他一定參加。它只建立一個仍可能發生的條件與預期結果，解題時不能把可能讀成已確定。" },
      { title: "結果不只一種形式", content: "If you finish the work, you can leave 表示能力或許可；If the road is busy, we may be late 表示可能；If you see Nora, tell her 則用祈使句提出行動。這些結果都依語意選擇。" },
      { title: "交換順序不改變時間關係", content: "We will start if everyone is ready 與 If everyone is ready, we will start 都把 is ready 放在未來條件中。不能因 if 子句移到後面就改成 will be ready。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S171_EX_01", prompt: "If the weather ___ good tomorrow, we will play outside. (is / was)", steps: ["辨認 tomorrow 指未來。", "確認這是可能實現的條件。", "在 if 子句使用現在式。"], answer: "is", why: "這是明天仍可能成立的真實條件，if 子句用現在式 is；主要句 will play 已表達未來結果。was 會把條件錯放到過去。" },
      { id: "ENG_R4_L_S171_EX_02", prompt: "If Amy finishes the book tonight, she can return it tomorrow. What becomes possible?", steps: ["找出 finishes the book 這個條件。", "讀取 can 所表示的可能行動。", "不要把條件當成已完成事實。"], answer: "She can return the book tomorrow.", why: "完成閱讀是尚未確定的今晚條件；只有條件成立，Amy 明天才可以還書。句子沒有宣稱她已經讀完，也沒有保證她一定會還。" },
      { id: "ENG_R4_L_S171_EX_03", prompt: "Join the ideas: The bus may be late. Then call me. Use if.", steps: ["把 bus is late 設為可能條件。", "保留 call me 作行動結果。", "使用現在式表達未來條件。"], answer: "If the bus is late, call me.", why: "公車遲到是未來可能發生的條件，因此寫 if the bus is late；call me 是條件成立時要採取的行動，不需要改成 will call me。" },
    ],
    misconceptions: [
      { belief: "未來條件一定要在 if 子句使用 will。", whyWrong: "第一類條件句的 if 子句通常用現在式表達未來條件。", correction: "寫 If it rains，而不是 If it will rain。" },
      { belief: "第一類條件句表示說話者確定條件會發生。", whyWrong: "它表達真實可能性，不等於事實已成立。", correction: "分開條件是否發生與發生後的預期結果。" },
      { belief: "結果子句只能使用 will。", whyWrong: "can、may 與祈使句可依能力、可能或指示使用。", correction: "先判斷結果想表達預測、許可、可能或行動。" },
      { belief: "if 子句放後面就應改用未來式。", whyWrong: "子句位置不會改變第一類條件句的時態原則。", correction: "無論前後都維持 if 加現在式。" },
    ],
    checks: [
      { prompt: "If Leo comes tomorrow 中，comes 指現在還是可能未來？", answer: "可能未來", reason: "if 子句用現在式形式表達未來條件。" },
      { prompt: "If you are free, you can join us 的 can 表達什麼？", answer: "條件成立後可以參加", reason: "結果是能力或許可，不是必然預測。" },
      { prompt: "If it rains tomorrow 是否表示一定會下雨？", answer: "不是", reason: "第一類條件仍保留條件未成立的可能。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S172", "ENG_R4_S172", {
    objectives: ["把 unless 理解為 if 加否定條件。", "避免在 unless 子句中再加入不必要的否定。"],
    sections: [
      { title: "unless 表示除非或如果不", content: "You cannot enter unless you have a ticket 可理解為 You cannot enter if you do not have a ticket。unless 引出使主要結果不再適用的例外條件，基本改寫時要注意主要句的意思不能跟著反轉。" },
      { title: "unless 子句通常不用再加 not", content: "Unless it rains, we will walk 表示如果不下雨，我們就走路。若寫 Unless it does not rain，在基本題型中會形成雙重否定，意思反而接近「如果下雨」，容易與原意相反。" },
      { title: "先找出被否定的是哪個條件", content: "Mia will miss the bus unless she leaves now 中，被否定的是 she leaves now：如果她現在不離開，就會錯過公車。不能把 unless 直接翻成主要句不發生。" },
      { title: "unless 不適合所有 if 句機械替換", content: "if 子句本身已有複雜否定或語意不是「若不」時，直接換 unless 可能改變意思。本單元只處理能清楚改寫為 if ... not 的基本否定條件。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S172_EX_01", prompt: "Unless you hurry, you will miss the train. Which if sentence has the same meaning?", steps: ["把 unless 改讀成 if not。", "保留主詞 you。", "維持主要結果 will miss。"], answer: "If you do not hurry, you will miss the train.", why: "unless you hurry 表示 if you do not hurry；主要句仍是 you will miss the train。不能把 miss 改成 will not miss，否則條件與結果都被反轉。" },
      { id: "ENG_R4_L_S172_EX_02", prompt: "We will eat outside unless it ___. (rains / does not rain)", steps: ["確認在不下雨時去戶外。", "讓 unless 自己承擔否定。", "選擇肯定形式 rains。"], answer: "rains", why: "整句表示除非下雨，否則會在戶外用餐。unless 已包含「如果不」的條件作用，所以子句使用 rains，不再加 does not。" },
      { id: "ENG_R4_L_S172_EX_03", prompt: "Ben cannot finish on time unless Amy helps him. What does Ben need?", steps: ["找出 unless 後的例外條件。", "判斷何時 cannot finish 不再成立。", "用肯定句說出需要。"], answer: "He needs Amy's help.", why: "沒有 Amy 幫忙時，Ben 無法準時完成；Amy helps him 是改變結果的必要條件。因此可確定他需要 Amy 的協助，不能推成他應獨自完成。" },
    ],
    misconceptions: [
      { belief: "unless 和 if 完全相同，替換時不必改否定。", whyWrong: "unless 通常相當於 if not，否定位置需要調整。", correction: "先寫出 if ... not 的同義句，再核對主要句。" },
      { belief: "unless 後一定要加 not 才有否定意思。", whyWrong: "unless 本身已帶有否定條件。", correction: "基本句型寫 unless it rains，不寫 unless it does not rain。" },
      { belief: "unless 會把主要句的肯定與否定一起反轉。", whyWrong: "改寫只改條件表達，主要結果應保持原意。", correction: "逐字核對主要句在改寫前後是否相同。" },
      { belief: "看到 unless 就表示後面的事件一定不會發生。", whyWrong: "unless 引出可能使結果改變的條件，並未判定它是否實現。", correction: "分開條件內容與條件是否真的成立。" },
    ],
    checks: [
      { prompt: "Unless you call me 相當於哪個基本條件？", answer: "if you do not call me", reason: "unless 表示 if not。" },
      { prompt: "Unless it is late 中要再加 not 嗎？", answer: "不要", reason: "unless 已承擔否定條件。" },
      { prompt: "I will wait unless the bus comes 表示公車來時一定等嗎？", answer: "不是", reason: "公車來是停止等待的例外條件。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S173", "ENG_R4_S173", {
    objectives: ["在一般未來條件的 if 子句中使用現在式而非 will。", "區分條件用 if 與表示是否的 if。"],
    sections: [
      { title: "未來條件由現在式形式承擔", content: "If Sam arrives early, we will start at eight 中，arrives 雖是現在式形式，卻指未來可能到達。第一類條件句把未來標記放在主要結果 will start，不在 if 子句重複 will。" },
      { title: "常見錯誤是兩邊都放 will", content: "If Sam will arrive early, we will start at eight 在本單元的一般條件用法中不採用。修正時保留主要句的 will，將 if 子句改成 arrives；不是把整句所有 will 一起刪掉。" },
      { title: "其他未來形式也遵守相同邊界", content: "If the shop is open tomorrow, we can buy the book 與 If Nora finishes, call me 都在 if 子句使用現在式。結果可以是 can 或祈使句，但不改變條件子句的基本形式。" },
      { title: "表示是否的 if 是另一種功能", content: "I do not know if Leo will come 中，if 可理解為 whether，表示「是否」，不是提出 Leo 來了才會發生的結果。這種內容子句可以出現 will；判斷時要看句子是否有另一個條件結果。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S173_EX_01", prompt: "If Nora ___ tomorrow, we will give her the key. (comes / will come)", steps: ["確認 if 引出未來條件。", "在條件子句選現在式。", "保留主要句 will give。"], answer: "comes", why: "Nora 明天來是主要結果成立的條件，所以使用第一類條件句的現在式 comes。will 已在主要句表達給鑰匙的未來行動。" },
      { id: "ENG_R4_L_S173_EX_02", prompt: "I do not know if the bus will come. Does if introduce a condition and result here?", steps: ["尋找條件成立後的另一結果。", "把 if 試讀成 whether。", "判斷它是是否內容。"], answer: "No. It means whether.", why: "I do not know if the bus will come 只說我不知道公車是否會來，沒有另一個由此觸發的結果。這裡 if 等於 whether，因此 will come 可以保留。" },
      { id: "ENG_R4_L_S173_EX_03", prompt: "Repair the condition: If the store will close early, we will go now.", steps: ["找出真正的條件子句。", "把 will close 改為現在式。", "維持主要句的未來結果。"], answer: "If the store closes early, we will go now.", why: "商店提早關門是促使我們現在出發的條件，條件子句應用 closes。主要句 we will go now 仍保留 will，因為它才是預期結果。" },
    ],
    misconceptions: [
      { belief: "只要句子提到 tomorrow，每個動詞都要加 will。", whyWrong: "一般未來條件的 if 子句使用現在式。", correction: "由子句功能決定時態，不由 tomorrow 機械決定。" },
      { belief: "修正 if 子句後，主要句的 will 也必須刪除。", whyWrong: "主要句常需要 will 表達未來結果。", correction: "只修改條件子句中多餘的 will。" },
      { belief: "任何 if 後出現 will 都一定錯。", whyWrong: "表示是否的內容子句不是一般條件句。", correction: "檢查 if 是否可換成 whether，以及是否有條件結果。" },
      { belief: "if 子句放在句尾時就可使用 will。", whyWrong: "位置不會改變一般未來條件的時態原則。", correction: "寫 We will leave if it rains，不寫 if it will rain。" },
    ],
    checks: [
      { prompt: "If Amy will call, I will answer 中應改哪一處？", answer: "will call 改為 calls", reason: "這是一般未來條件。" },
      { prompt: "I asked if Amy would call 中的 if 表示什麼？", answer: "是否", reason: "它引出 asked 的內容，不是條件結果。" },
      { prompt: "主要句使用 can 時，if 子句可改用 will 嗎？", answer: "不可以", reason: "結果形式不會改變條件子句用現在式的原則。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S174", "ENG_R4_S174", {
    objectives: ["依條件是否明確成立，判斷結果能否由句子推出。", "避免把條件句錯讀成雙向保證。"],
    sections: [
      { title: "條件成立時才能套用明示結果", content: "If a student has a ticket, the student may enter。已知 Mia 有票，就可依規則判斷她可以進入；若只知道 Ben 是學生，仍缺少有票這個條件，不能直接套用結果。" },
      { title: "條件不成立不代表相反結果一定成立", content: "If it rains, the game will stop。若沒有下雨，句子只告訴我們這條規則沒有被觸發；比賽可能繼續，也可能因其他原因停止。不能自行補成「不下雨就一定繼續」。" },
      { title: "看到結果也不一定能倒推唯一原因", content: "If the school bell rings, Nora goes to class。Nora 已在教室不保證校鈴一定響過，她也可能提早進教室。條件句通常保證從條件到結果的方向，不自動保證結果只可能由該條件造成。" },
      { title: "多個條件必須逐一核對", content: "If the door is open and the green light is on, you may enter 要同時具備兩項條件。只有門開或只有綠燈亮，都不足以從這條規則取得進入許可。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S174_EX_01", prompt: "Rule: If a book has a blue mark, it is for Class 3. This book has a blue mark. Which class is it for?", steps: ["列出規則的條件 blue mark。", "確認這本書符合條件。", "套用結果 for Class 3。"], answer: "Class 3.", why: "題目明示這本書有藍色記號，完整符合 if 子句，因此可套用結果，判定它是給三班的。這個結論不需要猜測書的內容。" },
      { id: "ENG_R4_L_S174_EX_02", prompt: "If it is windy, the school closes the window. The window is closed. Must it be windy?", steps: ["辨認 windy 到 closed 的方向。", "檢查結果是否只有一個可能原因。", "避免把結果倒推成條件。"], answer: "No.", why: "規則只說有風時學校會關窗，沒有說關窗只能因為有風。窗戶也可能在放學後關閉，所以看到結果不能證明條件必然成立。" },
      { id: "ENG_R4_L_S174_EX_03", prompt: "Students may use the room if a teacher is there and the door is open. A teacher is there, but the door is closed. May the students use it under this rule?", steps: ["拆出 teacher 與 open door 兩個條件。", "逐項比對目前資訊。", "在缺少一項時不套用許可。"], answer: "No.", why: "規則用 and 要求老師在場且門開著。雖然第一項成立，門仍關著，所以條件未完整滿足；不能只符合一半就取得使用教室的許可。" },
    ],
    misconceptions: [
      { belief: "知道人物屬於某群體，就能套用該群體中的附加條件結果。", whyWrong: "還必須確認 if 子句列出的實際條件。", correction: "把身分與資格條件分成不同欄位核對。" },
      { belief: "條件不成立時，主要句的相反敘述一定成立。", whyWrong: "條件句通常未排除其他可能結果或原因。", correction: "若規則沒有另外說明，就保留未知。" },
      { belief: "看到結果就能證明 if 子句的條件已經發生。", whyWrong: "同一結果可能由其他原因造成。", correction: "只沿著規則寫出的條件到結果方向推論。" },
      { belief: "and 連接兩個條件時，只符合其中一個也足夠。", whyWrong: "and 表示兩項都要成立。", correction: "逐項打勾，所有必要條件齊全才套用結果。" },
    ],
    checks: [
      { prompt: "If a card is red, put it here。已知卡片是紅色，可以放這裡嗎？", answer: "可以", reason: "明示條件已成立。" },
      { prompt: "If it rains, the road gets wet。路濕能證明一定下雨嗎？", answer: "不能", reason: "可能有其他使道路變濕的原因。" },
      { prompt: "條件是 A and B，只知道 A 時能套用結果嗎？", answer: "不能", reason: "仍缺少 B。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S175", "ENG_R4_S175", {
    objectives: ["辨認 if 加過去式與 would 所表達的現在假設。", "從假設句推回說話者暗示的現實情況。"],
    sections: [
      { title: "過去式形式可表示與現在有距離的假設", content: "If I had more time, I would read more 並非談過去擁有時間，而是假設現在有更多時間。說話者通常暗示現實中時間不夠，所以使用 had 與 would read 拉開假設和現實的距離。" },
      { title: "基本形式是 if 加過去式、結果用 would", content: "If Mia knew the answer, she would tell us 中，knew 位於 if 子句，would tell 位於結果子句。would 後接原形動詞，不能寫 would told，也不在同一個基本 if 子句再放 would knew。" },
      { title: "If I were you 用於站在他人立場給建議", content: "If I were you, I would talk to the teacher 表示說話者不是真的對方，而是假設自己處在對方位置。國中基本題型通常使用 were，不寫 If I was you 來考這個固定假設語氣。" },
      { title: "真實可能與非現實假設要分開", content: "If I have time tonight, I will call you 表示今晚仍可能有時間；If I had more time, I would call you 暗示目前時間不足。判讀不能只看 if，還要配對兩邊的動詞形式與上下文。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S175_EX_01", prompt: "If I ___ you, I would ask for help. (were / am)", steps: ["辨認說話者不可能真的成為對方。", "套用 If I were you 的基本形式。", "確認結果以 would 加原形表達建議。"], answer: "were", why: "說話者假設自己處在對方的位置，現實身分並未改變，因此使用固定的 If I were you。後面的 would ask 說明在這個假設下會採取的做法。" },
      { id: "ENG_R4_L_S175_EX_02", prompt: "If Leo had a bike, he would ride to school. Does the sentence suggest that Leo has a bike now?", steps: ["配對 had 與 would ride。", "辨認這是現在非現實假設。", "推回被暗示的現況。"], answer: "No.", why: "had 與 would ride 建立和現在現實有距離的假設，通常暗示 Leo 現在沒有腳踏車。句子不是在回報他過去曾擁有一輛。" },
      { id: "ENG_R4_L_S175_EX_03", prompt: "If we lived near the station, we would walk there. What is probably true now?", steps: ["找出假設條件 lived near。", "讀取 would walk 的假設結果。", "把現實理解為與條件有差距。"], answer: "We probably do not live near the station.", why: "lived near 與 would walk 描述一個和現況不同的想像情形，因此可合理理解為我們目前大概不住在車站附近。句子沒有說我們永遠不走路。" },
    ],
    misconceptions: [
      { belief: "if 子句用了過去式，就一定在敘述過去事件。", whyWrong: "基本假設語氣可用過去式形式表示現在非現實。", correction: "搭配 would 與上下文判斷時間和現實距離。" },
      { belief: "would 後面應接過去式，因為句子是假設語氣。", whyWrong: "would 後接原形動詞。", correction: "寫 would go、would help，不寫 would went、would helped。" },
      { belief: "If I were you 表示說話者真的變成對方。", whyWrong: "它是假設站在對方立場提出建議。", correction: "把 were 理解為與現實身分不同的想像。" },
      { belief: "第一類條件句與現在非現實假設可以任意混用。", whyWrong: "兩者對條件可能性與現況的暗示不同。", correction: "比較 if I have / will 與 if I had / would 的配對。" },
    ],
    checks: [
      { prompt: "If I were you 通常用來做什麼？", answer: "站在對方立場給建議", reason: "說話者與對方不是同一人。" },
      { prompt: "would 後接 go 還是 went？", answer: "go", reason: "情態動詞 would 後接原形。" },
      { prompt: "If she had time, she would join us 暗示什麼？", answer: "她現在可能沒有時間", reason: "had 與 would 表示和現況有距離的假設。" },
    ], assets: [],
  }),
];

export const ENGLISH_U25_QUESTIONS = [
  ...skillQuestions("169", [
    { stem: "If the library is open, we will study there. What is the condition?", options: ["The library is open.", "We study every day.", "The library is quiet.", "We will study there."], answerIndex: 0, reasons: ["if 直接引出 library is open，這是條件。", "every day 不在原句中。", "quiet 也沒有文本依據。", "will study there 是條件成立後的結果。"], reviews: ["先以 if 的範圍切開兩個子句。", "第一項只保留觸發讀書行動的狀態。"], cognitiveProcess: ["u25-s169-identify-open-library-condition", "separate-study-result-from-condition"], representationType: "condition-clause-identification", misconceptionTargets: ["label-main-result-as-condition"] },
    { stem: "We will wait inside if the rain starts. What is the result?", options: ["The rain starts.", "We will wait inside.", "The rain stops.", "We are already inside."], answerIndex: 1, reasons: ["rain starts 是句尾 if 子句的條件。", "主要句說明下雨後等待的位置。", "句中沒有 rain stops。", "will wait 表示尚未確定已在室內。"], reviews: ["if 子句放後面時，主要句仍是結果。", "第二項保留 will 所標出的後續行動。"], cognitiveProcess: ["u25-s169-read-result-before-final-if-clause", "reject-assumed-present-location"], representationType: "postposed-condition-result-reading", misconceptionTargets: ["treat-final-if-clause-as-result"] },
    { stem: "Which sentence puts the same condition first: We will walk if the bus is late?", options: ["We will walk, and the bus is late.", "The bus is late because we will walk.", "If the bus is late, we will walk.", "If we walk, the bus will be late."], answerIndex: 2, reasons: ["and 只並列事件，沒有保留條件。", "because 改成步行造成公車遲到。", "if the bus is late 仍是條件，walk 仍是結果。", "第四項把條件與結果顛倒。"], reviews: ["交換子句位置時不能交換事件角色。", "第三項只移動整個 if 子句並補上逗號。"], cognitiveProcess: ["u25-s169-front-postposed-bus-late-condition", "preserve-condition-result-direction"], representationType: "condition-order-transformation", misconceptionTargets: ["reverse-events-while-reordering"] },
    { stem: "Which ending completes the sentence: If the door is locked, ___", options: ["if the key", "because the door", "the locked door", "use the side door."], answerIndex: 3, reasons: ["if the key 仍缺少動詞與結果。", "because the door 也是未完成片語。", "名詞片語沒有說要採取什麼行動。", "祈使句清楚交代條件成立時的做法。"], reviews: ["if the door is locked 已是完整條件，空格需要結果。", "第四項能獨立形成主要句。"], cognitiveProcess: ["u25-s169-complete-locked-door-condition-with-action", "reject-fragments-as-results"], representationType: "condition-sentence-completion", misconceptionTargets: ["leave-condition-without-main-clause"] },
    { stem: "If Mia needs a ride, she will call Ben. Which event is the stated condition for the call?", options: ["Mia needs a ride.", "Ben calls Mia first.", "Mia buys a bike.", "Ben needs a ride."], answerIndex: 0, reasons: ["這正是 if 子句提出的條件。", "原句沒有要求 Ben 先打電話。", "買車並非已寫條件。", "需要接送的人是 Mia，不是 Ben。"], reviews: ["問題只找句中明示條件，不宣稱它是打電話的唯一原因。", "第一項能直接連到 she will call Ben。"], cognitiveProcess: ["u25-s169-recover-trigger-before-mia-call-result", "maintain-participant-roles"], representationType: "event-trigger-identification", misconceptionTargets: ["swap-condition-participants"] },
    { stem: "Call the office ___ the meeting time changes.", options: ["because", "if", "but", "although"], answerIndex: 1, reasons: ["because 會把變更寫成已知原因，而非可能條件。", "if 連接時間變更的條件與打電話行動。", "but 只表轉折，沒有條件關係。", "although 表讓步，不能表達變更時才通知的規則。"], reviews: ["meeting time changes 尚未被說成確定發生。", "第二項建立「若變更就通知」的行動規則。"], cognitiveProcess: ["u25-s169-insert-if-for-office-call-contingency", "distinguish-condition-from-cause-and-contrast"], representationType: "condition-connector-cloze", misconceptionTargets: ["choose-connector-without-event-relation"] },
    { stem: "NOTICE: If the red light is on, stop the machine. What should a worker do when the red light is on?", options: ["Turn on every light.", "Leave the room at once.", "Stop the machine.", "Wait until the light turns green before reading the notice."], answerIndex: 2, reasons: ["公告沒有要求開啟其他燈。", "離開房間不是明示結果。", "條件 red light is on 成立時，指示是 stop the machine。", "閱讀公告不以綠燈為條件。"], reviews: ["祈使句可以作 if 條件成立後的結果。", "第三項直接套用公告，沒有增加安全程序。"], cognitiveProcess: ["u25-s169-apply-red-light-imperative-result", "exclude-unstated-workplace-actions"], representationType: "notice-condition-action", misconceptionTargets: ["miss-imperative-as-result-clause"] },
    { stem: "Which sentence places the condition first and marks its end with a comma?", options: ["We will eat outside, if the weather is warm.", "If, the weather is warm we will eat outside.", "The weather is warm, if we will eat outside.", "If the weather is warm, we will eat outside."], answerIndex: 3, reasons: ["條件放後面，且此基本句型不需該逗號。", "逗號不能拆開 if 與主詞。", "第三項顛倒條件，也在 if 子句誤用 will。", "if 子句完整置前，逗號標示其結束。"], reviews: ["標點要跟隨完整子句邊界。", "第四項同時保留條件方向與基本書寫格式。"], cognitiveProcess: ["u25-s169-punctuate-fronted-warm-weather-condition", "locate-full-clause-boundary"], representationType: "fronted-if-clause-punctuation", misconceptionTargets: ["place-comma-after-if-word"] },
    { stem: "If the key fits, the box will open. Which pair names the condition and then the result?", options: ["the key fits / the box will open", "the box opens / the key will fit", "the key is lost / the box is closed", "the box fits / the key opens"], answerIndex: 0, reasons: ["兩段依原句順序正確標示條件與結果。", "第二項交換事件並改變時態。", "lost 與 closed 都未出現在原文。", "box 與 key 的功能被錯置。"], reviews: ["斜線前後需分別對應 if 子句與主要句。", "第一項保持物品角色與事件方向。"], cognitiveProcess: ["u25-s169-label-key-fit-and-box-open-pair", "reject-object-function-reversal"], representationType: "condition-result-pair-classification", misconceptionTargets: ["reverse-condition-result-object-roles"] },
    { stem: "A: What should I do if I cannot find the room? What should B say?", options: ["Ask the room for help.", "Call me, and I will help you.", "The room is large.", "You could not find it yesterday."], answerIndex: 1, reasons: ["房間不能回答求助，也未提供可行做法。", "打電話是條件成立時可採取的清楚行動。", "房間大小沒有解決找不到地點的問題。", "過去資訊沒有提供目前解決方法。"], reviews: ["A 已提出 cannot find the room 這個可能條件。", "第二項提供可執行結果，也維持對話人物關係。"], cognitiveProcess: ["u25-s169-answer-lost-room-if-question-with-action", "select-result-that-resolves-condition"], representationType: "dialogue-condition-response", misconceptionTargets: ["respond-with-background-not-result"] },
    { stem: "Which line is only a condition and still needs a result?", options: ["The class starts at nine.", "Bring your book to class.", "If the teacher is absent.", "We will meet in the library."], answerIndex: 2, reasons: ["第一項是完整陳述句。", "第二項是完整祈使句。", "if 子句只提出老師缺席，尚未說接著怎麼辦。", "第四項有完整主詞與結果內容。"], reviews: ["句尾句點不會讓未完成的條件自動成句。", "第三項需要另一個主要子句才交代完整意思。"], cognitiveProcess: ["u25-s169-detect-absent-teacher-condition-fragment", "distinguish-clause-form-from-complete-message"], representationType: "condition-fragment-detection", misconceptionTargets: ["treat-punctuation-as-completeness"] },
    { stem: "Nora will send a message if the train arrives late. What does the sentence mean?", options: ["A late message causes the train.", "Nora arrives after the message.", "The train always arrives late.", "Nora will send a message when the train is late."], answerIndex: 3, reasons: ["message 不會造成列車，也沒有 late message。", "句子沒有說 Nora 到達。", "if 保留列車不遲到的可能。", "第四項保留列車遲到這個條件與 Nora 將傳訊息的結果。"], reviews: ["主要句在前不代表它是原因。", "第四項精確保留條件、結果與不確定性。"], cognitiveProcess: ["u25-s169-explain-message-before-final-train-condition", "avoid-certainty-and-causation-overreach"], representationType: "condition-relationship-paraphrase", misconceptionTargets: ["read-if-as-certainty-or-cause"] },
  ]),
  ...skillQuestions("170", [
    { stem: "As a general rule, if ice gets warm enough, it ___.", options: ["turns to water", "turned to water yesterday", "will turn to water tomorrow", "is turning to water now"], answerIndex: 0, reasons: ["一般現象用現在式 turns to water。", "yesterday 把結果改成單一過去事件。", "tomorrow 把結果縮成一次未來預測。", "now 改成此刻正在進行，不是一般規律。"], reviews: ["general rule 明示條件與結果可反覆觀察。", "第一項也與單數 it 保持動詞一致。"], cognitiveProcess: ["u25-s170-complete-ice-warming-general-result", "apply-present-present-natural-fact"], representationType: "zero-condition-natural-result-cloze", misconceptionTargets: ["force-future-or-past-into-general-fact"] },
    { stem: "If Leo misses the early bus, he walks to school. What does the sentence describe?", options: ["One walk that ended yesterday", "What Leo usually does when he misses the bus", "A walk happening at this moment", "A promise that Leo will never take a bus"], answerIndex: 1, reasons: ["句中沒有 yesterday 或已結束標記。", "misses 與 walks 說明條件反覆發生時的習慣。", "現在式不等於正在進行式。", "句子沒有 never，也沒有承諾。"], reviews: ["兩個現在式與可重複條件共同表示習慣。", "第二項沒有把 usual 擴大成永遠。"], cognitiveProcess: ["u25-s170-interpret-missed-bus-walking-as-habit", "separate-simple-present-from-now-and-never"], representationType: "habitual-condition-interpretation", misconceptionTargets: ["read-simple-present-as-current-event"] },
    { stem: "As a general rule, if the green light is on, the door ___.", options: ["opened last week", "will open tomorrow", "opens", "is opening now"], answerIndex: 2, reasons: ["last week 只描述一次過去。", "tomorrow 把固定操作改成一次未來。", "opens 以現在式表示每次都適用的門禁反應。", "now 只描述此刻正在發生。"], reviews: ["general rule 要求可反覆適用的設備反應。", "第三項配合單數 door，也保留一般性。"], cognitiveProcess: ["u25-s170-complete-green-light-door-rule", "select-simple-present-for-repeated-operation"], representationType: "machine-rule-present-cloze", misconceptionTargets: ["mistake-operating-rule-for-single-future"] },
    { stem: "Which sentence tells a fact that is true each time?", options: ["If plants needed water yesterday, they are green tomorrow.", "If plants will need water, the sun is hot.", "Plants get water if the clock is loud.", "If plants never get water, they die."], answerIndex: 3, reasons: ["時態混合，且未形成一般事實。", "需要水與太陽很熱沒有此條件關係。", "時鐘聲與植物得到水沒有合理規律。", "植物一直沒有水會死亡，是可理解的一般關係。"], reviews: ["形式正確仍需搭配合理內容。", "第四項用現在式說明條件持續成立時的結果。"], cognitiveProcess: ["u25-s170-select-repeatable-plant-water-fact", "reject-formal-looking-noncausal-pairs"], representationType: "general-fact-selection", misconceptionTargets: ["judge-zero-condition-by-tense-alone"] },
    { stem: "Every night, if I feel cold, I ___ the window.", options: ["close", "closed yesterday", "will close tomorrow", "am closing now"], answerIndex: 0, reasons: ["close 表示每逢這個情況的慣常做法。", "yesterday 把行動縮成一次過去事件。", "tomorrow 改成一次未來計畫。", "now 只描述此刻正在關窗。"], reviews: ["Every night 明確提供可重複時段。", "第一項以原形配合主詞 I。"], cognitiveProcess: ["u25-s170-complete-night-cold-window-habit", "distinguish-close-verb-from-close-adjective"], representationType: "habit-result-verb-cloze", misconceptionTargets: ["confuse-routine-with-one-event"] },
    { stem: "If a student has a question, the student asks the teacher. Which time meaning is most likely?", options: ["A finished event before school", "What students usually do in class", "A plan for one named day", "An action happening only now"], answerIndex: 1, reasons: ["沒有過去時間或完成形式。", "現在式條件與結果描述一般課堂做法。", "句中沒有特定日期。", "asks 不是 is asking。"], reviews: ["a student 是泛指，支持規則而非單一人物。", "第二項符合句型與情境的重複性。"], cognitiveProcess: ["u25-s170-classify-student-question-teacher-rule", "use-generic-subject-and-tense-evidence"], representationType: "routine-time-meaning-classification", misconceptionTargets: ["assign-one-time-event-to-generic-rule"] },
    { stem: "Which sentence tells what happens each time the button is pushed?", options: ["The button was pushed before lunch.", "The bell will ring only tomorrow.", "If you push the button, the bell rings.", "The bell is ringing, so the button is blue."], answerIndex: 2, reasons: ["第一項只有一次過去動作，沒有結果規則。", "only tomorrow 限定一次未來。", "現在式 push 與 rings 表達每次操作的固定結果。", "正在響與按鈕顏色不是題目要求的條件規則。"], reviews: ["each time 要求可反覆出現的操作關係。", "第三項把動作與設備反應直接連接。"], cognitiveProcess: ["u25-s170-identify-repeatable-button-bell-operation", "exclude-one-time-and-unrelated-state"], representationType: "repeatable-operation-recognition", misconceptionTargets: ["replace-general-rule-with-single-event"] },
    { stem: "Which pair does not make sense as a general rule?", options: ["If people are tired, they rest.", "If you add one and one, you get two.", "If the school bell rings, students enter class.", "If a book is heavy, Tuesday comes next."], answerIndex: 3, reasons: ["疲累時休息是可理解的一般反應。", "一加一等於二是固定結果。", "校鈴可作進教室的日常信號。", "書的重量不會決定星期二是否來到。"], reviews: ["此題檢查條件與結果是否真正相關。", "第四項即使兩邊都是現在式，也不能建立合理規律。"], cognitiveProcess: ["u25-s170-detect-heavy-book-tuesday-nonrelation", "evaluate-semantic-link-beyond-verb-form"], representationType: "general-condition-semantic-validity", misconceptionTargets: ["accept-any-present-present-pair"] },
    { stem: "As a general rule, if dogs are hungry, they ___ for food.", options: ["look", "looks", "looked yesterday", "will look tomorrow"], answerIndex: 0, reasons: ["look 與複數 they 一致並表一般行為。", "looks 不與複數主詞一致。", "yesterday 只描述一次過去。", "tomorrow 只預測一次未來。"], reviews: ["general rule 要求反覆適用，也要檢查主詞動詞一致。", "第一項同時滿足複數與現在式。"], cognitiveProcess: ["u25-s170-apply-plural-agreement-in-hungry-dog-fact", "integrate-zero-condition-and-agreement"], representationType: "plural-general-result-cloze", misconceptionTargets: ["add-third-person-s-after-plural"] },
    { stem: "If Nora has free time after dinner, she draws. What can we know?", options: ["Nora is drawing right now.", "Drawing is her usual choice when she has time.", "Nora never eats dinner.", "She made only one picture in the past."], answerIndex: 1, reasons: ["簡單現在式不證明此刻正在畫。", "條件成立時 she draws，表示反覆選擇。", "句子反而以 after dinner 為背景。", "沒有 only one 或過去資訊。"], reviews: ["答案必須保留條件範圍。", "第二項不把習慣誤讀成正在進行或唯一一次。"], cognitiveProcess: ["u25-s170-infer-nora-drawing-routine-from-free-time", "bound-habit-to-stated-condition"], representationType: "habit-evidence-inference", misconceptionTargets: ["overgeneralize-habit-to-current-or-never"] },
    { stem: "RULE: If the number is even, put the card in Box A. The number is 8. Where does the card go?", options: ["Box B", "Either box without a rule", "Box A", "The card stays outside"], answerIndex: 2, reasons: ["Box B 沒有規則依據。", "條件已明確成立，不是任選。", "8 是偶數，因此套用 Box A 的固定規則。", "outside 也未被指定。"], reviews: ["一般規則也能用於一次具體判斷。", "第三項由 even 這個條件直接推出。"], cognitiveProcess: ["u25-s170-apply-even-number-box-a-rule", "map-specific-case-to-general-condition"], representationType: "general-rule-specific-application", misconceptionTargets: ["ignore-known-condition-in-rule"] },
    { stem: "How can this be written with if: Every time Ben feels sick, he stays home?", options: ["Ben stayed home because every time was sick.", "If Ben will feel sick, he stayed home.", "Ben is staying home if yesterday.", "If Ben feels sick, he stays home."], answerIndex: 3, reasons: ["第一項詞序與主詞不完整。", "時態混合，且在一般條件中誤用 will。", "if yesterday 不是完整條件。", "兩個現在式保留 every time 的慣常關係。"], reviews: ["每次都適用的做法不能改成單一過去或正在發生。", "第四項完整保留 Ben、感到不適與待在家三項資訊。"], cognitiveProcess: ["u25-s170-restate-ben-sick-routine-with-if", "preserve-repeated-time-meaning"], representationType: "routine-to-zero-condition-transformation", misconceptionTargets: ["convert-habit-to-mixed-time-event"] },
  ]),
  ...skillQuestions("171", [
    { stem: "If the weather ___ good tomorrow, we will eat outside.", options: ["is", "was", "will be", "being"], answerIndex: 0, reasons: ["第一類未來條件在 if 子句用現在式 is。", "was 指向過去或非現實語境。", "一般條件子句不在此使用 will be。", "being 不能獨立作謂語。"], reviews: ["tomorrow 不會迫使 if 子句改成未來式。", "第一項與主要句 will eat 形成標準時間配對。"], cognitiveProcess: ["u25-s171-select-is-for-tomorrow-weather-condition", "resist-future-marker-in-if-clause"], representationType: "first-condition-be-cloze", misconceptionTargets: ["use-will-in-future-condition"] },
    { stem: "If Amy finishes early, she can join the game. What becomes possible?", options: ["The game finishes Amy.", "Amy can join the game.", "Amy has already joined.", "The game cannot begin."], answerIndex: 1, reasons: ["人物與動作角色顛倒。", "can join 是條件成立後的可能行動。", "finishes early 尚未被說成已成立。", "句子沒有遊戲不能開始的資訊。"], reviews: ["結果使用 can，不是保證事件已經發生。", "第二項完整保留 Amy 的行動與條件性。"], cognitiveProcess: ["u25-s171-read-can-result-after-amy-finishes", "distinguish-possibility-from-completed-action"], representationType: "modal-result-interpretation", misconceptionTargets: ["read-can-as-already-done"] },
    { stem: "If the train is late tonight, we may take a taxi. What does may show?", options: ["The taxi trip happened yesterday.", "The train is always late.", "Taking a taxi is one possible result.", "No other travel choice exists."], answerIndex: 2, reasons: ["句中沒有 yesterday 或已發生旅程。", "if 表示遲到尚未確定，更不是 always。", "may 表達條件成立後的一種可能。", "may 不排除其他選擇。"], reviews: ["情態動詞強度是解讀結果的重要線索。", "第三項保留可能性，沒有把它擴大成唯一或事實。"], cognitiveProcess: ["u25-s171-interpret-may-in-late-train-taxi-result", "avoid-certainty-and-exclusivity-from-may"], representationType: "first-condition-modal-strength", misconceptionTargets: ["turn-may-result-into-certainty"] },
    { stem: "If Ben ___ the map tonight, he will bring it tomorrow.", options: ["found", "will find", "is finding", "finds"], answerIndex: 3, reasons: ["found 是過去式，與今晚的可能條件不合。", "一般未來條件的 if 子句不使用 will find。", "find 表示找到的完成點，此處不使用進行式。", "finds 以現在式表達今晚可能條件。"], reviews: ["主要句 will bring 已承擔未來結果。", "第四項也與第三人稱單數 Ben 一致。"], cognitiveProcess: ["u25-s171-complete-ben-map-future-condition", "integrate-present-form-and-singular-agreement"], representationType: "first-condition-action-cloze", misconceptionTargets: ["double-mark-future-and-break-agreement"] },
    { stem: "If you finish the form, you ___ leave the office.", options: ["can", "did", "are leaving yesterday", "have left before"], answerIndex: 0, reasons: ["can 表示完成表格後取得離開許可。", "did 不能直接接 leave。", "現在進行式與 yesterday 衝突。", "完成式改成較早已離開，不符條件結果。"], reviews: ["結果可用 can 表達許可，不必一律使用 will。", "第一項保留條件尚未確定與後續權利。"], cognitiveProcess: ["u25-s171-select-can-for-form-completion-permission", "choose-result-modal-by-function"], representationType: "conditional-permission-cloze", misconceptionTargets: ["assume-only-will-can-follow-if"] },
    { stem: "If the road is busy, we may arrive late. Which idea has the same meaning?", options: ["The road is surely busy now.", "We may be late when the road is busy.", "We arrived late before the road became busy.", "The road becomes busy because we arrive."], answerIndex: 1, reasons: ["if 未確認道路目前一定繁忙。", "may 正確表示繁忙時可能遲到。", "句子談未來可能，不是既定過去順序。", "條件方向是道路影響到達，不是相反。"], reviews: ["同時保留 if 的未定性與 may 的可能性。", "第二項沒有額外加入時間或因果。"], cognitiveProcess: ["u25-s171-paraphrase-busy-road-late-arrival-possibility", "preserve-direction-and-modal-strength"], representationType: "conditional-meaning-paraphrase", misconceptionTargets: ["convert-if-may-to-fact-or-reversed-cause"] },
    { stem: "You see Nora tomorrow. Tell her to call me. Which sentence makes seeing Nora the condition?", options: ["Nora will see me because tomorrow calls.", "Tell Nora if I see tomorrow.", "If you see Nora tomorrow, tell her to call me.", "If Nora calls me, you saw her tomorrow."], answerIndex: 2, reasons: ["第一項角色與時間詞都無法形成原意。", "第二項把看見的人改成 I，且 tomorrow 不能作受詞。", "if 子句保留 you see Nora，祈使句保留通知內容。", "第四項顛倒條件與結果，也混合時間。"], reviews: ["原句第二個動作是看到 Nora 後要採取的行動。", "第三項沒有補上多餘 will，也沒有改變人物。"], cognitiveProcess: ["u25-s171-combine-see-nora-with-imperative-result", "preserve-speaker-listener-and-message-roles"], representationType: "future-condition-imperative-combination", misconceptionTargets: ["reverse-condition-and-message-action"] },
    { stem: "Which sentence keeps the future condition but moves it to the end: If everyone is ready, we will start?", options: ["Everyone will start if we are ready.", "We started because everyone was ready.", "If we will start, everyone is ready.", "We will start if everyone is ready."], answerIndex: 3, reasons: ["第一項交換了 everyone 與 we 的角色。", "第二項改成已完成的過去原因。", "第三項倒轉條件並在 if 子句使用 will。", "第四項只交換子句位置，角色與時態不變。"], reviews: ["移動子句不能重新分配主詞。", "第四項仍把 everyone is ready 當未來條件。"], cognitiveProcess: ["u25-s171-postpose-everyone-ready-condition", "lock-participants-and-first-condition-tense"], representationType: "first-condition-order-rewrite", misconceptionTargets: ["change-agents-while-reordering"] },
    { stem: "NOTICE: If the rain stops by four, the game will begin at five. The rain stops at three. What will happen?", options: ["The game will begin at five.", "The game began at three.", "The rain will start again at five.", "The game must be inside."], answerIndex: 0, reasons: ["三點停止符合 by four 的條件，因此套用五點開始。", "三點是雨停時間，不是比賽開始時間。", "公告沒有說雨會再下。", "比賽地點也未被說明。"], reviews: ["by four 包含四點以前，三點符合限制。", "第一項只推出公告明示的結果。"], cognitiveProcess: ["u25-s171-apply-rain-stop-deadline-to-game-start", "separate-condition-time-from-result-time"], representationType: "future-notice-deadline-application", misconceptionTargets: ["transfer-condition-time-to-result"] },
    { stem: "We will visit the park if it does not rain. Which sentence has the same basic meaning?", options: ["Rain will visit the park with us.", "If it does not rain, we will visit the park.", "If we visit the park, it cannot rain.", "We visit every park when rain starts."], answerIndex: 1, reasons: ["rain 不能成為訪客，且角色錯誤。", "只把 if 子句移到前面，條件與結果不變。", "第三項把結果倒推成天氣條件。", "第四項改成一般習慣且意思相反。"], reviews: ["否定 not 必須跟著 rain condition 一起移動。", "第二項保留一次可能未來與原有方向。"], cognitiveProcess: ["u25-s171-front-negative-rain-condition-equivalently", "retain-negation-during-clause-movement"], representationType: "negative-first-condition-equivalence", misconceptionTargets: ["reverse-or-drop-negative-condition"] },
    { stem: "If Mia studies tonight, she will understand the lesson better. Which idea is not supported yet?", options: ["Studying is the condition.", "Better understanding is the expected result.", "Mia has already studied tonight.", "The condition is about tonight."], answerIndex: 2, reasons: ["if 子句明示 studying 是條件。", "will understand better 是預期結果。", "句子保留 Mia 今晚不讀書的可能，尚未證實完成。", "tonight 清楚限定條件時間。"], reviews: ["第一類條件描述可能情況，不是完成報告。", "第三項把尚未實現的條件誤讀成既成事實。"], cognitiveProcess: ["u25-s171-detect-unsupported-completion-in-study-condition", "separate-proposed-condition-from-established-fact"], representationType: "future-condition-evidence-boundary", misconceptionTargets: ["assume-if-condition-already-true"] },
    { stem: "If the shop is open and the book is there, Sam will buy it. When will Sam buy the book?", options: ["The shop is closed, but the book is there.", "The shop is open, but the book is gone.", "Sam is near a closed shop.", "The shop is open, and the book is there."], answerIndex: 3, reasons: ["closed 不符合第一個條件。", "book is gone 不符合第二個條件。", "near 不是規則列出的條件，且店關著。", "兩個 and 條件都成立，可套用 will buy。"], reviews: ["and 要求店開與書在兩項同時成立。", "第四項完整匹配，沒有用地點接近取代必要條件。"], cognitiveProcess: ["u25-s171-match-two-part-shop-book-future-condition", "reject-partial-condition-satisfaction"], representationType: "compound-first-condition-application", misconceptionTargets: ["accept-one-of-two-future-conditions"] },
  ]),
  ...skillQuestions("172", [
    { stem: "Unless you hurry, you will miss the train. Which if sentence keeps the meaning?", options: ["If you do not hurry, you will miss the train.", "If you hurry, you will miss the train.", "If the train hurries, you will wait.", "If you do not miss the train, you will not hurry."], answerIndex: 0, reasons: ["unless you hurry 等於 if you do not hurry，主要結果不變。", "第二項刪掉了條件中的否定，意思相反。", "第三項把 train 當成會趕路的主詞。", "第四項倒轉條件結果，也無法保持原意。"], reviews: ["改寫 unless 時只把條件轉成 if not。", "第一項完整保留趕車與錯過列車的方向。"], cognitiveProcess: ["u25-s172-rewrite-unless-hurry-as-if-not", "hold-miss-train-result-constant"], representationType: "unless-if-not-equivalence", misconceptionTargets: ["drop-negation-when-rewriting-unless"] },
    { stem: "We will play outside unless it ___.", options: ["does not rain", "rains", "will not rain", "not raining"], answerIndex: 1, reasons: ["unless 已表示 if not，再加 does not 會改變基本意思。", "rains 表示除非下雨，否則去戶外。", "will not rain 同時多加未來與否定。", "not raining 不能作完整有限子句。"], reviews: ["unless 後使用肯定形式表達例外條件。", "第二項讓下雨成為取消戶外活動的情況。"], cognitiveProcess: ["u25-s172-complete-outdoor-plan-unless-rain", "avoid-double-negative-after-unless"], representationType: "unless-condition-cloze", misconceptionTargets: ["add-not-after-unless"] },
    { stem: "Mia will miss the bus unless she leaves now. Which action is named as the exception?", options: ["Wait for another day.", "Call the bus driver.", "Leave now.", "Miss the bus first."], answerIndex: 2, reasons: ["等待不符合 leaves now 這個例外。", "句中沒有打電話的做法。", "unless she leaves now 表示現在離開會使原本的必然結果不再適用。", "先錯過公車不是例外條件。"], reviews: ["先把句子改讀為 if she does not leave now。", "第三項是句中明示的例外，不另保證她一定搭得上車。"], cognitiveProcess: ["u25-s172-infer-action-needed-to-avoid-missing-bus", "resolve-exception-condition-as-prevention"], representationType: "unless-action-inference", misconceptionTargets: ["treat-unless-condition-as-result"] },
    { stem: "Which sentence means that the walk happens if it does not rain?", options: ["Unless it does not rain, we will walk.", "Unless we walk, it will rain.", "We will not walk unless rain stops walking.", "Unless it rains, we will walk."], answerIndex: 3, reasons: ["雙重否定會使意思接近下雨時走路。", "第二項把 walk 改成避免下雨的條件。", "第三項角色與語意都不成立。", "unless it rains 等於 if it does not rain。"], reviews: ["題目已明示 if not rain，可直接轉成 unless rain。", "第四項沒有再額外加入 not。"], cognitiveProcess: ["u25-s172-select-unless-sentence-for-no-rain-walk", "map-explicit-negative-condition-to-unless"], representationType: "negative-condition-to-unless-selection", misconceptionTargets: ["create-double-negative-unless"] },
    { stem: "NOTICE: You cannot enter unless you have a ticket. Who does the notice clearly stop?", options: ["A person without a ticket", "Everyone near the door", "A person with a ticket", "Only the ticket seller"], answerIndex: 0, reasons: ["沒有票時 cannot enter 直接適用。", "靠近門口不等於沒有票。", "有票只表示此項禁止不再適用，不能由本句判定其他入場規則。", "公告沒有特別禁止售票者。"], reviews: ["unless you have a ticket 可改讀為 if you do not have a ticket。", "第一項直接符合禁止條件，不把必要條件誤當完整許可。"], cognitiveProcess: ["u25-s172-apply-ticket-entry-unless-rule", "separate-location-and-job-from-ticket-condition"], representationType: "unless-notice-prohibition", misconceptionTargets: ["infer-full-permission-from-necessary-condition"] },
    { stem: "You will not finish unless you ask for help. Which sentence gives the same condition?", options: ["If you ask for help, you will not finish.", "If you do not ask for help, you will not finish.", "If you finish, no one can help.", "If help finishes, you will ask."], answerIndex: 1, reasons: ["第一項移除了 unless 所含否定，變成求助也不完成。", "if you do not ask 正確展開 unless you ask。", "第三項倒推且加入 no one。", "第四項把 help 當成執行 finish 的人。"], reviews: ["主要句 will not finish 在改寫後必須保持。", "第二項只調整條件子句的否定位置。"], cognitiveProcess: ["u25-s172-expand-unless-ask-help-with-negative-if", "preserve-negative-main-result"], representationType: "unless-with-negative-main-clause-rewrite", misconceptionTargets: ["flip-main-clause-during-unless-rewrite"] },
    { stem: "Unless Ben calls by six, we will leave. What is the exception to leaving?", options: ["Six o'clock passes.", "We call Ben after leaving.", "Ben calls by six.", "No one uses a phone."], answerIndex: 2, reasons: ["時間經過而未來電不會阻止離開。", "離開後打電話不是句中例外。", "Ben 在六點前來電時，unless 條件使離開結果不再適用。", "電話使用情況沒有此限制。"], reviews: ["問題問的是什麼情況會改變主要結果。", "第三項完整對應 unless 後的肯定內容。"], cognitiveProcess: ["u25-s172-identify-ben-call-deadline-exception", "distinguish-exception-from-default-result"], representationType: "unless-exception-identification", misconceptionTargets: ["treat-default-result-as-exception"] },
    { stem: "Unless the light is green, do not open the door. Which action follows when the light is red?", options: ["Open every door.", "Turn the light off.", "Paint the door green.", "Do not open the door."], answerIndex: 3, reasons: ["紅燈不符合 green 例外，不能開門。", "關燈不是公告指示。", "顏色也不是由使用者改變。", "不是綠燈時，主要指示 do not open 適用。"], reviews: ["red 明確落在 unless the light is green 的預設情況。", "第四項只執行規則，沒有增加操作。"], cognitiveProcess: ["u25-s172-apply-red-light-to-unless-green-prohibition", "map-failed-exception-to-default-action"], representationType: "unless-imperative-application", misconceptionTargets: ["apply-exception-result-when-condition-fails"] },
    { stem: "Unless the store closes early, Amy will shop after work. The store keeps its usual hours. What will Amy do?", options: ["Shop after work", "Close the store herself", "Stay at work all night", "Shop before the store opens"], answerIndex: 0, reasons: ["沒有提早關門，因此預設結果 shop after work 適用。", "Amy 不是被說成店員。", "all night 沒有文本依據。", "句子沒有要求開店前購物。"], reviews: ["usual hours 表示 closes early 這個例外未成立。", "第一項沿用主要句，不把時間或角色改寫。"], cognitiveProcess: ["u25-s172-apply-unmet-early-close-exception-to-shopping", "connect-usual-hours-to-default-plan"], representationType: "unless-context-default-result", misconceptionTargets: ["misread-unmet-exception-as-cancelled-plan"] },
    { stem: "Sam cannot use the computer unless a teacher is there. A teacher is there. Which idea goes beyond the sentence?", options: ["The needed condition is met.", "Sam has already used the computer.", "Having a teacher there matters.", "Without a teacher, the rule blocks Sam."], answerIndex: 1, reasons: ["教師在場符合明示條件。", "條件成立只表示限制解除，不證明 Sam 已實際使用。", "unless 子句明示教師在場的重要性。", "若教師不在，cannot use 適用。"], reviews: ["permission or ability 不等於 action completed。", "第二項把可使用擴張成已使用。"], cognitiveProcess: ["u25-s172-detect-completed-use-overreach-after-exception-met", "separate-eligibility-from-action"], representationType: "unless-evidence-boundary", misconceptionTargets: ["infer-action-from-permission"] },
    { stem: "Which sentence uses unless without a double negative?", options: ["Unless you do not need help, call me.", "Unless not the room is open, wait.", "Unless the sign says OPEN, wait outside.", "Unless the bus does not come, keep waiting."], answerIndex: 2, reasons: ["unless 與 do not 疊加成雙重否定，不符合題目要求。", "not the room is open 詞序不成立。", "sign 未顯示 OPEN 時，wait outside 是清楚預設行動。", "does not come 也把 unless 與否定疊加。"], reviews: ["本技能的 unless 子句使用肯定形式表達例外。", "第三項的 sign says OPEN 是唯一解除等待的情況。"], cognitiveProcess: ["u25-s172-select-clean-unless-open-sign-instruction", "screen-double-negative-and-word-order-errors"], representationType: "unless-form-quality-selection", misconceptionTargets: ["assume-not-required-after-unless"] },
    { stem: "A plant will die unless it gets water. Plant A gets no water. What follows from the sentence?", options: ["Plant A will grow faster.", "Plant A has enough water.", "Nothing can be said about Plant A.", "Plant A will die."], answerIndex: 3, reasons: ["grow faster 與規則結果相反且無依據。", "題目明說 gets no water。", "條件已明確符合，不是完全未知。", "unless it gets water 等於 if it does not get water，故套用 will die。"], reviews: ["gets no water 直接對應 unless 的否定條件。", "第四項是規則明示結果，不需要額外生物知識。"], cognitiveProcess: ["u25-s172-apply-no-water-to-plant-unless-rule", "translate-explicit-absence-into-unless-default"], representationType: "unless-rule-specific-case", misconceptionTargets: ["fail-to-map-no-to-unless-default"] },
  ]),
  ...skillQuestions("173", [
    { stem: "If Nora ___ tomorrow, we will give her the key.", options: ["comes", "will come", "came yesterday", "coming"], answerIndex: 0, reasons: ["未來條件在 if 子句使用現在式 comes。", "一般條件用法不在此放 will come。", "yesterday 與 tomorrow 衝突。", "coming 不能獨立完成子句。"], reviews: ["主要句 will give 已表達未來結果。", "第一項也符合第三人稱單數 Nora。"], cognitiveProcess: ["u25-s173-remove-future-marker-from-nora-condition", "retain-singular-present-form"], representationType: "if-clause-will-avoidance-cloze", misconceptionTargets: ["double-future-marking"] },
    { stem: "I do not know if the bus will come. What does if mean here?", options: ["because", "whether", "unless", "after"], answerIndex: 1, reasons: ["because 會表示已知原因。", "if 引出不知道的內容，可換成 whether。", "unless 表示否定條件，與句意不合。", "after 會建立時間順序。"], reviews: ["全句沒有另一個由公車到來觸發的結果。", "第二項說明這裡可以保留 will come 的原因。"], cognitiveProcess: ["u25-s173-classify-content-if-as-whether", "separate-content-clause-from-condition"], representationType: "if-function-disambiguation", misconceptionTargets: ["ban-will-after-every-if"] },
    { stem: "If the store ___ early, we will go now.", options: ["will close", "closing", "closes", "closed last week"], answerIndex: 2, reasons: ["一般未來條件不使用 will close。", "closing 缺少有限動詞。", "closes 以現在式表達可能的提早關門。", "last week 與現在決定不合。"], reviews: ["store closes early 是促使 go now 的條件。", "第三項只修正 if 子句，不刪除主要句 will。"], cognitiveProcess: ["u25-s173-repair-store-close-condition-with-present", "preserve-will-in-main-result"], representationType: "future-condition-error-cloze", misconceptionTargets: ["put-will-in-both-clauses"] },
    { stem: "Which sentence asks whether Leo will join rather than setting a condition?", options: ["If Leo joins, we will begin.", "We will wait if Leo is late.", "If Leo has time, he can join.", "Amy asked if Leo would join."], answerIndex: 3, reasons: ["第一項是 Leo 加入後開始的條件。", "第二項是遲到時等待的條件。", "第三項是有時間才能參加的條件。", "asked if 引出 Amy 所問的「是否參加」。"], reviews: ["whether 測試能區分內容 if 與條件 if。", "第四項沒有另一個由 Leo 參加觸發的主要結果。"], cognitiveProcess: ["u25-s173-distinguish-asked-if-from-three-conditions", "identify-whether-content-under-reporting-verb"], representationType: "conditional-versus-content-if-selection", misconceptionTargets: ["treat-every-if-clause-as-condition"] },
    { stem: "We will call you if the time ___.", options: ["changes", "will change", "changed tomorrow", "is change"], answerIndex: 0, reasons: ["changes 以現在式表達未來可能變動。", "will change 不用在這個一般 if 條件。", "changed 與 tomorrow 不合。", "is change 不是正確動詞結構。"], reviews: ["if 子句放句尾仍遵守現在式原則。", "第一項與單數 time 保持一致。"], cognitiveProcess: ["u25-s173-complete-postposed-time-change-condition", "apply-rule-independent-of-clause-position"], representationType: "postposed-if-present-cloze", misconceptionTargets: ["allow-will-only-when-if-clause-follows"] },
    { stem: "If Amy is free tonight, she can help us. Why do we use \"is,\" not \"will be\"?", options: ["The sentence is about the past.", "The if clause gives a possible future condition.", "Amy is certainly free now.", "The result word \"can\" alone decides the form in the if clause."], answerIndex: 1, reasons: ["tonight 指可能未來，不是過去。", "第一類條件的 if 子句以現在式形式表達未來。", "句子沒有確認 Amy 目前或今晚一定有空。", "時態由 if 子句的功能決定，不是由 can 單獨控制。"], reviews: ["時態選擇來自子句功能，不是單一字詞替換。", "第二項同時保留未來意義與條件不確定性。"], cognitiveProcess: ["u25-s173-explain-present-is-in-tonight-condition", "reject-past-certainty-and-modal-substitution-explanations"], representationType: "if-clause-tense-rationale", misconceptionTargets: ["confuse-present-form-with-present-certainty"] },
    { stem: "The bus will leave if everyone ___ ready.", options: ["will be", "being", "is", "was tomorrow"], answerIndex: 2, reasons: ["will be 不用於此一般條件子句。", "being 單獨不能完成 everyone ___ ready 的條件子句。", "is 以現在式形成 everyone is ready。", "was 與 tomorrow 衝突。"], reviews: ["主要句 will leave 保留未來結果。", "第三項讓句尾 if 子句完整且不重複未來標記。"], cognitiveProcess: ["u25-s173-select-is-after-everyone-in-final-condition", "maintain-future-in-main-clause-only"], representationType: "be-form-future-if-cloze", misconceptionTargets: ["repeat-will-in-final-condition"] },
    { stem: "Which sentence may keep will after if because if means whether?", options: ["If it rains, we will stay inside.", "We will leave if the door opens.", "If Nora calls, tell me.", "I do not know if the shop will open early."], answerIndex: 3, reasons: ["第一項是下雨時待室內的條件。", "第二項是門開時離開的條件。", "第三項是 Nora 來電時採取行動。", "do not know if 表示不知道是否開店，可保留 will。"], reviews: ["判斷關鍵是 if 能否換成 whether。", "第四項沒有另一個 shop opens 所觸發的結果。"], cognitiveProcess: ["u25-s173-find-whether-if-allowing-will", "contrast-three-result-bearing-if-clauses"], representationType: "will-after-if-boundary-selection", misconceptionTargets: ["apply-condition-rule-to-content-if"] },
    { stem: "If Sam ___ the answer later, he will tell us.", options: ["finds", "will find", "found before", "is finding yesterday"], answerIndex: 0, reasons: ["finds 用現在式表達 later 的可能條件。", "will find 在一般 if 條件中多餘。", "before 改成較早已發現。", "進行式與 yesterday 都不合 later。"], reviews: ["later 指未來，但 if 子句仍以 finds 表示。", "第一項和主要句 will tell 分工清楚。"], cognitiveProcess: ["u25-s173-handle-later-with-present-finds", "resist-adverb-driven-will-choice"], representationType: "future-adverb-if-cloze", misconceptionTargets: ["choose-will-solely-from-later"] },
    { stem: "If the rain will stop, we will walk home. Which change fixes the condition clause?", options: ["Change walk to walked.", "Change will stop to stops.", "Change home to yesterday.", "Change If to Because."], answerIndex: 1, reasons: ["walk 是主要句 will 後的正確原形。", "stops 是一般未來條件所需現在式。", "yesterday 會造成時間矛盾。", "because 會把未確定條件改成已知原因。"], reviews: ["只修正錯誤位置，不連帶改壞其他成分。", "第二項保留雨停時走回家的原意。"], cognitiveProcess: ["u25-s173-edit-will-stop-to-stops-only", "isolate-condition-clause-error"], representationType: "targeted-if-clause-edit", misconceptionTargets: ["delete-or-change-correct-main-clause"] },
    { stem: "If the teacher will arrive by nine, the class can start. Why should will arrive change to arrives?", options: ["The class happened yesterday.", "The teacher can never come.", "A possible future condition uses the present form after if.", "By nine always needs the past tense."], answerIndex: 2, reasons: ["句中沒有 yesterday。", "if 保留到達可能，沒有說永遠不能來。", "教師可能在九點前到達是 if 條件，因此使用現在式 arrives。", "by nine 不會一律要求過去式。"], reviews: ["錯誤原因需指出子句角色與相應形式。", "第三項也保留 can start 作結果。"], cognitiveProcess: ["u25-s173-justify-arrives-in-teacher-deadline-condition", "locate-result-in-can-start-clause"], representationType: "future-if-error-explanation", misconceptionTargets: ["explain-correction-with-irrelevant-time-rule"] },
    { stem: "A: Should I bring a coat tomorrow? B: If it ___ cold, bring one.", options: ["was last week", "will be", "being", "is"], answerIndex: 3, reasons: ["last week 不回答明天的可能情況。", "一般未來條件不用 will be。", "being 無法獨立完成子句。", "is 以現在式表示明天若冷。"], reviews: ["祈使結果 bring one 不影響 if 子句的現在式。", "第四項形成自然且完整的條件式回應。"], cognitiveProcess: ["u25-s173-answer-coat-dialogue-with-present-condition", "combine-advice-imperative-and-future-if-form"], representationType: "dialogue-future-condition-cloze", misconceptionTargets: ["use-will-after-if-in-advice"] },
  ]),
  ...skillQuestions("174", [
    { stem: "RULE: If a card is red, put it in Box A. This card is red. Where should it go?", options: ["Box A", "Box B", "Either box", "Outside every box"], answerIndex: 0, reasons: ["red 條件已成立，直接套用 Box A。", "Box B 不在規則結果中。", "條件明確時不是任選。", "outside 也沒有規則依據。"], reviews: ["先比對具體卡片與 if 條件。", "第一項只採用規則明示的放置位置。"], cognitiveProcess: ["u25-s174-apply-red-card-box-a-rule", "map-known-condition-to-explicit-result"], representationType: "direct-condition-rule-application", misconceptionTargets: ["ignore-satisfied-condition"] },
    { stem: "If the school bell rings, Nora goes to class. Nora is in class. What can we know about the bell?", options: ["It must be broken.", "It may have rung, but we cannot know for sure.", "It surely did not ring.", "Nora is the bell."], answerIndex: 1, reasons: ["broken 沒有文本證據。", "Nora 進教室可能由校鈴或其他原因造成，不能唯一倒推。", "in class 也不能證明校鈴沒響。", "人物與物品角色完全不同。"], reviews: ["規則提供 bell rings 到 goes to class 的方向。", "第二項保留可能性，又避免把結果當成唯一原因。"], cognitiveProcess: ["u25-s174-reject-converse-from-classroom-result", "preserve-undetermined-cause"], representationType: "result-to-condition-uncertainty", misconceptionTargets: ["affirm-result-to-prove-condition"] },
    { stem: "If the door is open, visitors may enter. The door is closed. What does this rule allow us to say?", options: ["Visitors must enter through the closed door.", "The building has no visitors.", "The stated condition for entering is not met.", "The door will open by itself."], answerIndex: 2, reasons: ["closed 不符合進入條件。", "規則未說建築內目前有沒有人。", "door is open 這個條件明確未成立。", "自動開門並非規則結果。"], reviews: ["條件未成立時，只能停止套用這條許可。", "第三項沒有補上「因此永遠不能進入」等額外結論。"], cognitiveProcess: ["u25-s174-identify-unmet-open-door-entry-condition", "limit-inference-when-condition-fails"], representationType: "failed-condition-status", misconceptionTargets: ["invent-opposite-result-from-failed-condition"] },
    { stem: "Students may use the room if a teacher is there and the door is open. Which choice meets both conditions?", options: ["A teacher is there, but the door is closed.", "The door is open, but no teacher is there.", "A student is near a closed door.", "A teacher is there, and the door is open."], answerIndex: 3, reasons: ["第一項缺少 open door。", "第二項缺少 teacher present。", "第三項兩項必要條件都不完整。", "第四項同時符合 teacher 與 open door。"], reviews: ["and 建立的是交集，不是二選一。", "第四項才能套用 may use the room。"], cognitiveProcess: ["u25-s174-match-teacher-and-open-door-joint-condition", "reject-each-partial-permission-case"], representationType: "compound-condition-match", misconceptionTargets: ["treat-and-as-or"] },
    { stem: "Unless a student has a pass, the student must wait. Leo has no pass. What must Leo do?", options: ["Wait", "Enter at once", "Give everyone a pass", "Leave school"], answerIndex: 0, reasons: ["no pass 符合 unless 的預設情況，結果是 wait。", "enter at once 與規則相反。", "發放通行證不是 Leo 的任務。", "離開學校不是規則結果。"], reviews: ["先把 unless 改讀為 if the student does not have a pass。", "第一項精確套用結果，不誇大時間。"], cognitiveProcess: ["u25-s174-apply-no-pass-unless-wait-rule", "exclude-extreme-and-role-shift-results"], representationType: "unless-rule-inference", misconceptionTargets: ["fail-to-apply-negative-condition"] },
    { stem: "If it rains, the game will stop. It does not rain. What is known about the game from this sentence alone?", options: ["It must stop for another reason.", "Whether it stops is not decided by this rule.", "It must continue all day.", "It never started."], answerIndex: 1, reasons: ["另一原因沒有被提供。", "不下雨只表示此條規則未被觸發。", "continue all day 是相反結果的過度推論。", "開始與否也不在句中。"], reviews: ["if P then Q 不會自動提供 not P 時的結果。", "第二項保留規則之外的可能性。"], cognitiveProcess: ["u25-s174-hold-game-result-unknown-when-no-rain", "avoid-negating-antecedent-fallacy"], representationType: "failed-condition-underdetermination", misconceptionTargets: ["infer-opposite-result-from-no-condition"] },
    { stem: "If a bus stops at Gate 3, it goes to the museum. This bus goes to the museum. Which idea is too strong?", options: ["Gate 3 may be one possible stop.", "The bus goes to the museum.", "The bus must stop at Gate 3.", "The sentence gives a rule about buses at Gate 3."], answerIndex: 2, reasons: ["規則容許 Gate 3 是一種可能，但不證實。", "題目直接說此車前往博物館。", "結果成立不能證明該條件是唯一站點。", "原始條件句確實談 Gate 3 公車。"], reviews: ["前往 museum 的公車可能經過不同站點。", "第三項把單向規則誤讀成雙向保證。"], cognitiveProcess: ["u25-s174-detect-gate-three-converse-overclaim", "separate-route-result-from-specific-stop-proof"], representationType: "converse-overclaim-detection", misconceptionTargets: ["affirm-consequent-in-route-rule"] },
    { stem: "If the blue key opens the box, Nora will take the map. The blue key opens the box, and the map shows the station. What can Nora get?", options: ["A new box", "A red key", "A train ticket", "The map that shows the station"], answerIndex: 3, reasons: ["new box 不是條件結果。", "題目只提 blue key。", "車票沒有出現在資訊鏈中。", "條件成立使 Nora 取得 map，後句說明它顯示 station。"], reviews: ["先套用 key opens 到 take map，再連接 map 的內容。", "第四項保留兩句資訊，沒有把地圖誤作車票。"], cognitiveProcess: ["u25-s174-chain-blue-key-result-to-map-detail", "combine-condition-result-with-following-description"], representationType: "two-step-condition-information-chain", misconceptionTargets: ["drop-or-transform-result-object"] },
    { stem: "NOTICE: If your name is on the list, you may enter. Mia's name is on the list. What does the notice allow?", options: ["Mia may enter.", "Mia has already entered.", "Everyone may enter.", "Mia may change the list."], answerIndex: 0, reasons: ["Mia 符合名單條件，因此取得進入許可。", "may enter 不等於已完成進入。", "規則只涵蓋名單上的人。", "修改名單不是公告授權。"], reviews: ["條件成立時可推出 permission，不能推出 completed action。", "第一項維持 may 的語氣與適用人物。"], cognitiveProcess: ["u25-s174-apply-name-list-entry-permission-to-mia", "separate-permission-from-action-and-global-access"], representationType: "notice-permission-inference", misconceptionTargets: ["turn-may-into-did"] },
    { stem: "If Sam finishes before five, he will call Amy. Sam does not call Amy. Which idea is still possible?", options: ["Sam surely finished at four.", "Sam may not have finished before five.", "Amy called every student.", "The clock stopped because Sam called."], answerIndex: 1, reasons: ["若確定四點完成，依規則應來電，與資訊不合。", "未在五點前完成可解釋條件未觸發。", "Amy 的其他電話沒有文本依據。", "時鐘與電話的因果未被提及。"], reviews: ["這題不是要求證明唯一原因，而是找仍相容的情況。", "第二項不超過規則與未來電兩項證據。"], cognitiveProcess: ["u25-s174-find-compatible-unmet-deadline-after-no-call", "avoid-invented-causes-for-absent-result"], representationType: "condition-result-consistency-reasoning", misconceptionTargets: ["claim-condition-true-when-result-absent"] },
    { stem: "A club meets outside if it is warm and dry. Today is warm but wet. What can we know from the rule?", options: ["The club must meet outside.", "Warm weather alone is enough.", "The two conditions are not both met.", "Wet weather means the club has ended."], answerIndex: 2, reasons: ["wet 使 dry 條件不成立。", "and 明示不能只靠 warm。", "warm 成立但 dry 不成立，因此條件不完整。", "ended 不是規則所說結果。"], reviews: ["把 warm 與 dry 分開核對可避免漏掉第二項。", "第三項只判斷條件狀態，不猜實際會面地點。"], cognitiveProcess: ["u25-s174-evaluate-warm-but-wet-compound-condition", "withhold-unstated-meeting-outcome"], representationType: "compound-condition-partial-failure", misconceptionTargets: ["ignore-conflicting-second-condition"] },
    { stem: "If a room is quiet, students can make a sound file there. Room A is quiet. Room B has a large table. What can we know from the rule?", options: ["Room B is better for every job.", "Both rooms are quiet.", "A large table makes sound work impossible.", "Students can make a sound file in Room A."], answerIndex: 3, reasons: ["better for every job 超出規則。", "只知道 Room A 安靜。", "規則沒有談桌子影響聲音工作。", "Room A 符合 quiet 條件，因此可製作聲音檔。"], reviews: ["無關的 Room B 資訊不能取代 if 條件。", "第四項僅把明示規則套到已知個案。"], cognitiveProcess: ["u25-s174-ignore-large-table-distractor-and-apply-quiet-rule", "select-evidence-bounded-room-conclusion"], representationType: "condition-inference-with-irrelevant-detail", misconceptionTargets: ["use-salient-but-irrelevant-fact"] },
  ]),
  ...skillQuestions("175", [
    { stem: "If I ___ you, I would ask the teacher for help.", options: ["were", "am", "will be", "being"], answerIndex: 0, reasons: ["If I were you 是站在對方立場給建議的基本形式。", "am 會把不真實身分當成現在事實。", "will be 不符合此假設句配對。", "being 不能獨立完成子句。"], reviews: ["說話者並不是真的成為 you。", "第一項與 would ask 共同標示非現實建議。"], cognitiveProcess: ["u25-s175-select-were-in-advice-frame", "recognize-identity-counterfactual"], representationType: "if-i-were-you-cloze", misconceptionTargets: ["use-factual-am-in-counterfactual-advice"] },
    { stem: "If Leo had a bike, he would ride to school. What does the sentence suggest about Leo now?", options: ["He rides a bike to school every day.", "He probably does not have a bike.", "He had a bike yesterday.", "He will surely buy a bike tomorrow."], answerIndex: 1, reasons: ["would ride 是假設結果，不是現在習慣。", "had 與 would ride 暗示目前沒有腳踏車。", "yesterday 沒有文本依據。", "句子沒有明天的購買計畫。"], reviews: ["過去式形式在此表示與現在現實的距離。", "第二項只說 probably，符合假設語氣的暗示強度。"], cognitiveProcess: ["u25-s175-infer-leo-lacks-bike-from-counterfactual", "exclude-past-sale-and-future-purchase"], representationType: "counterfactual-reality-inference", misconceptionTargets: ["read-had-as-past-possession-report"] },
    { stem: "If Mia knew the answer, she would ___ us.", options: ["told", "telling", "tell", "tells"], answerIndex: 2, reasons: ["would 後不接過去式 told。", "telling 不能直接跟在 would 後。", "would 後接原形 tell。", "tells 是第三人稱現在式，不跟 would。"], reviews: ["knew 已標示假設條件，結果以 would 加原形。", "第三項形成 would tell us 的完整結構。"], cognitiveProcess: ["u25-s175-complete-would-tell-result-with-base-form", "reject-inflected-verbs-after-modal"], representationType: "counterfactual-result-verb-cloze", misconceptionTargets: ["use-past-after-would"] },
    { stem: "Which sentence describes an idea that is different from real life now?", options: ["If I have time tonight, I will call you.", "If the bus comes, we can leave.", "If water gets cold, it turns to ice.", "If I had more time, I would learn to cook."], answerIndex: 3, reasons: ["第一項是仍可能實現的今晚條件。", "第二項也是可能未來。", "第三項是一般事實。", "had 與 would learn 暗示現在時間不足。"], reviews: ["需同時查看 if 子句與結果形式。", "第四項清楚把想像狀況和目前現實拉開。"], cognitiveProcess: ["u25-s175-distinguish-counterfactual-from-first-and-zero-conditions", "classify-form-and-reality-distance"], representationType: "condition-type-discrimination", misconceptionTargets: ["treat-all-if-sentences-as-same-reality"] },
    { stem: "If we ___ near the station, we would walk there.", options: ["lived", "live tomorrow", "will live", "are living yesterday"], answerIndex: 0, reasons: ["lived 與 would walk 形成現在非現實假設。", "live tomorrow 把意思改成可能未來且形式不合配對。", "will live 不放在此假設 if 子句。", "進行式與 yesterday 衝突。"], reviews: ["句子想像目前住得更近會採取的做法。", "第一項不是過去居住報告，而是假設形式。"], cognitiveProcess: ["u25-s175-select-lived-for-station-distance-counterfactual", "separate-past-form-from-past-time"], representationType: "second-condition-past-form-cloze", misconceptionTargets: ["interpret-lived-only-as-past-event"] },
    { stem: "A: I am afraid to speak in class. What should B say?", options: ["I spoke yesterday", "If I were you, I would start with one short answer", "you are me", "the class will be afraid"], answerIndex: 1, reasons: ["過去事件不能提供目前假設建議。", "If I were you 與 would start 說明站在對方立場會採取的可行做法。", "說話者沒有真的變成對方。", "第四項把害怕者錯換成全班。"], reviews: ["回應應使用 If I were you 提出目前建議。", "第二項保持人物觀點，也沒有保證結果。"], cognitiveProcess: ["u25-s175-complete-speaking-fear-advice-dialogue", "select-practical-would-result-from-perspective"], representationType: "counterfactual-advice-dialogue", misconceptionTargets: ["literalize-if-i-were-you"] },
    { stem: "If Sam were taller, he would reach the shelf. Which fact is most likely true now?", options: ["The shelf is on the floor.", "Sam reached it yesterday.", "Sam is not tall enough to reach it.", "Everyone can reach the shelf."], answerIndex: 2, reasons: ["floor 會使 reach 問題失去原句基礎，且未明示。", "yesterday 沒有出現在句中。", "were taller 與 would reach 暗示目前高度不足。", "everyone 是不受支持的全稱推論。"], reviews: ["假設的改變是 taller，結果是 reach。", "第三項從這兩部分推回最直接的現實差距。"], cognitiveProcess: ["u25-s175-infer-current-height-limit-from-taller-hypothesis", "reject-unmentioned-location-time-and-universal-claims"], representationType: "counterfactual-contrast-inference", misconceptionTargets: ["ignore-implied-opposite-reality"] },
    { stem: "Which sentence shows a present condition that is not real and its result?", options: ["If I had more money, I will bought the book.", "If I would have more money, I buy the book.", "If I have more money yesterday, I would buy the book.", "If I had more money, I would buy the book."], answerIndex: 3, reasons: ["will bought 不是正確形式，也混合配對。", "基本 if 子句不寫 would have，結果也缺 would。", "have 與 yesterday 衝突，且未形成假設配對。", "had 與 would buy 正確表達現在非現實。"], reviews: ["兩個子句需成對檢查，不能只看到 would。", "第四項也讓 buy 維持原形。"], cognitiveProcess: ["u25-s175-select-had-would-buy-form-pair", "reject-mixed-and-malformed-counterfactual-forms"], representationType: "counterfactual-form-pair-selection", misconceptionTargets: ["mix-first-and-second-condition-forms"] },
    { stem: "You have too much work and cannot go out. What is good advice?", options: ["If I were you, I would finish the most important work first.", "If I am you, I will finish all the work.", "If I were you, I finished the work yesterday.", "If you were me, you would go out first."], answerIndex: 0, reasons: ["If I were you 與 would finish 提供符合情境的建議。", "am you 把假設身分寫成事實，也過度保證完成所有工作。", "finished yesterday 改成過去報告，不能建議目前做法。", "第四項顛倒立場，而且 go out first 沒有處理工作問題。"], reviews: ["建議應同時符合假設形式並回應目前工作過多。", "第一項提出可執行優先順序，也沒有聲稱已完成。"], cognitiveProcess: ["u25-s175-choose-counterfactual-advice-for-heavy-workload", "evaluate-form-and-contextual-usefulness"], representationType: "situational-advice-selection", misconceptionTargets: ["choose-formal-looking-but-contextually-wrong-advice"] },
    { stem: "If I have time tonight, I will help. If I had more time, I would help more. What is the main difference?", options: ["Both sentences describe finished past help.", "The first can happen; the second suggests limited time now.", "The second promises certain help tomorrow.", "The first says time never matters."], answerIndex: 1, reasons: ["第一句談今晚未來，第二句談現在假設，都不是已完成過去。", "have/will 保留真實可能，had/would 暗示時間不足。", "would 不表示明日確定承諾。", "第一句正把 time 當條件。"], reviews: ["同樣使用 if，動詞配對卻表達不同現實距離。", "第二項同時說明兩句，不只描述其中一個形式。"], cognitiveProcess: ["u25-s175-contrast-real-tonight-and-limited-time-counterfactual", "map-form-pairs-to-reality-status"], representationType: "first-versus-second-condition-comparison", misconceptionTargets: ["erase-reality-difference-between-condition-types"] },
    { stem: "If Nora had a map, she would find the room. Which idea cannot be known?", options: ["The sentence imagines Nora having a map.", "Finding the room is the imagined result.", "Nora lost the map on a bus yesterday.", "Nora probably does not have a map now."], answerIndex: 2, reasons: ["had a map 是明示假設。", "would find 是假設結果。", "遺失地點與時間完全未被提供。", "非現實形式通常暗示目前沒有地圖。"], reviews: ["假設語氣可支持現況差距，卻不能補寫背景故事。", "第三項加入 bus 與 yesterday，超過句子證據。"], cognitiveProcess: ["u25-s175-detect-invented-map-loss-background", "bound-counterfactual-inference-to-form"], representationType: "counterfactual-evidence-boundary", misconceptionTargets: ["invent-cause-for-unreal-condition"] },
    { stem: "Mia does not know how to fix the bike. Which sentence uses if to show this idea is not real now?", options: ["If Mia knows how, she fixed the bike yesterday.", "If Mia will know how, she would fix the bike.", "If Mia knew how, she will fix the bike.", "If Mia knew how, she would fix the bike."], answerIndex: 3, reasons: ["knows 與 fixed yesterday 改成現在事實加過去事件。", "基本非現實 if 子句不使用 will know。", "knew 與 will fix 混合兩種條件形式。", "knew 與 would fix 表示她目前不會修的現實差距。"], reviews: ["題幹已明示目前不知道，因此需使用成對的非現實形式。", "第四項保留 Mia、修理能力與腳踏車三項資訊。"], cognitiveProcess: ["u25-s175-express-mia-bike-skill-gap-counterfactually", "translate-explicit-reality-into-had-would-form"], representationType: "reality-to-counterfactual-expression", misconceptionTargets: ["mix-future-and-past-forms-in-unreal-present"] },
  ]),
];

export const ENGLISH_UNIT_SOURCE = {
  unitId: UNIT_ID,
  lectures: ENGLISH_U25_LECTURES,
  questions: ENGLISH_U25_QUESTIONS,
  vocabularyPolicy: {
    capQuestionBasis: "appendix-5-table-1",
    additionalLearningTerms: ["absent", "add", "advice", "alone", "basic", "beyond", "cause", "certain", "complete", "continue", "describe", "difference", "double", "event", "exist", "fit", "form", "general", "imagine", "impossible", "introduce", "limit", "lock", "message", "mix", "negative", "promise", "rather", "repair", "result", "return", "sense", "shelf", "state", "suggest", "support", "travel", "usual"],
    properNames: ["Amy", "Ben", "Leo", "Mia", "Nora", "Sam"],
    grammarNotation: ["A", "B", "clause", "comma", "condition", "conditions", "exception", "rung", "tense", "unless", "would"],
    malformedDistractors: [],
  },
};
