const UNIT_ID = "ENG_R4_U29";

function lecture(id, skillId, content) {
  return { id, skillId, ...content, sections: content.sections.map((section, index) => ({ id: id + "_SEC_" + String(index + 1).padStart(2, "0"), ...section })) };
}

const DIFFICULTIES = ["foundation", "foundation", "foundation", "standard", "standard", "standard", "standard", "advanced", "advanced", "advanced", "transfer", "transfer"];

function skillQuestions(skillNumber, values) {
  if (values.length !== 12) throw new Error("ENG_R4_S" + skillNumber + ": expected 12 authored questions");
  return values.map((value, index) => ({ id: "ENG_R4_Q_" + skillNumber + "_" + String(index + 1).padStart(2, "0"), skillId: "ENG_R4_S" + skillNumber, difficulty: DIFFICULTIES[index], ...value }));
}

export const ENGLISH_U29_LECTURES = [
  lecture("ENG_R4_L_S197", "ENG_R4_S197", {
    objectives: ["能辨認常見動詞與名詞形成的自然搭配。", "能以句意和慣用組合排除逐字翻譯後看似合理的動詞。"],
    sections: [
      { title: "搭配是常一起出現的組合", content: "英文中的動詞和名詞不一定能逐字自由互換。中文都可能說『做』，英文卻分成 do homework、make a mistake、take a break。選字時要把整組當成語言單位，再確認它在句中的時間和語意。" },
      { title: "先辨認名詞代表的事件", content: "decision、promise、attention 等名詞會限制前面的動詞。make a decision 表示作成決定，keep a promise 表示遵守承諾，pay attention 表示把注意力放在某處；動詞選錯時，句法可能完整，表達仍不自然。" },
      { title: "常見生活搭配分組記憶", content: "學校情境常見 do homework、ask a question、take notes；交通情境常見 catch a bus、miss a train；互動情境常見 give advice、have a talk、make friends。按情境整理比單獨背一個動詞更容易在閱讀中辨認。" },
      { title: "形式正確還要核對語境", content: "同一名詞有時可和不同動詞搭配，但意思不同，例如 give a talk 是發表談話，have a talk 是進行交談。題目若提供目的、人物關係或後續結果，這些線索會決定哪一組最精確。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S197_EX_01", prompt: "We need to ___ a decision before noon. (do / make)", steps: ["decision 表示要作成的決定。", "常見搭配是 make a decision。", "before noon 只限制時間，不改變搭配。"], answer: "make", why: "句子說必須在中午前作成決定，英文使用 make a decision。do 通常不和 decision 組成這個意思，因此即使文法位置相同也不自然。" },
      { id: "ENG_R4_L_S197_EX_02", prompt: "You look tired. Let's ___ a short break. (take / catch)", steps: ["後句提出休息建議。", "break 和 take 形成固定常見搭配。", "catch 常用於趕上交通工具或抓住事物。"], answer: "take", why: "前句指出疲累，後句應是提議休息，所以選 take a short break。catch a break 有其他語意，不能在這個初階情境中取代 take a break。" },
      { id: "ENG_R4_L_S197_EX_03", prompt: "Lena always ___ her promises. (keeps / pays)", steps: ["promises 指已向別人作出的承諾。", "遵守承諾用 keep。", "主詞是第三人稱單數，動詞加 s。"], answer: "keeps", why: "句意是 Lena 一向遵守承諾，標準搭配為 keep a promise。always 和單數主詞共同要求現在式 keeps；pay 不能表達履行承諾。" },
    ],
    misconceptions: [
      { belief: "中文都能翻成『做』，所以 do 和 make 可以任意交換。", whyWrong: "兩個動詞各有慣用名詞搭配，交換後常形成不自然英文。", correction: "把 do homework、make a plan 等完整組合一起記錄。" },
      { belief: "只要句型是動詞加名詞，任一及物動詞都可能正確。", whyWrong: "句法位置正確不代表詞彙搭配成立。", correction: "先看名詞要表達的事件，再核對常見動詞組合。" },
      { belief: "看到 bus 就選 take，忽略題目其實說趕上即將開走的車。", whyWrong: "take a bus 表示搭乘，catch a bus 強調趕上，語境不同。", correction: "利用時間、結果和人物目的判斷動作方向。" },
      { belief: "背過 give advice 後，遇到 advice 就一律選 give。", whyWrong: "ask for advice、follow advice 也成立，但表達不同角色與動作。", correction: "確認誰提供、尋求或採納建議，再選動詞。" },
    ],
    checks: [
      { prompt: "make a mistake 中，哪個字表示錯誤本身？", answer: "mistake", reason: "make 表示產生，mistake 是被產生的錯誤。" },
      { prompt: "pay attention 和 pay money 的受詞意思相同嗎？", answer: "不同", reason: "前者是慣用搭配，attention 不是金錢。" },
      { prompt: "catch a train 一定表示搭乘全程嗎？", answer: "不一定", reason: "它主要表示趕上該班車，後續行程需由上下文判斷。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S198", "ENG_R4_S198", {
    objectives: ["能辨認常見形容詞後所搭配的介系詞。", "能依人物、原因、對象與內容區分相近介系詞組合。"],
    sections: [
      { title: "形容詞後的介系詞常需整組記憶", content: "interested in、good at、afraid of、ready for 等組合不能只按中文決定介系詞。形容詞描述狀態，介系詞再引出該狀態涉及的活動、事物或對象。" },
      { title: "介系詞後接名詞或動名詞", content: "She is good at math 與 She is good at drawing 中，at 後面分別接名詞和動名詞。介系詞後若要放動作，通常使用 V-ing，而不是原形動詞或 to 加原形。" },
      { title: "同一形容詞可能因關係不同換介系詞", content: "be angry with someone 通常指出生氣的對象，be angry about something 指引起生氣的事情。並非每個形容詞都只有一個介系詞，因此要觀察後面的名詞扮演什麼角色。" },
      { title: "搭配不能取代完整語意判斷", content: "The hall is full of people 描述內容物；Taiwan is famous for night markets 指出知名原因。背到介系詞後仍要讀主詞和受詞，避免只看到熟悉單字就選答案。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S198_EX_01", prompt: "Ryan is interested ___ space. (in / at)", steps: ["interested 表示感興趣的狀態。", "引出興趣內容使用 in。", "space 是介系詞的受詞。"], answer: "in", why: "句子要說 Ryan 對太空有興趣，常見組合是 be interested in。at 可接在 good at 後，但不能因同樣描述能力或興趣就互換。" },
      { id: "ENG_R4_L_S198_EX_02", prompt: "The floor is full ___ water. (of / for)", steps: ["full 描述地板上充滿某物。", "內容物由 of 引出。", "water 完成 full of 的受詞。"], answer: "of", why: "full of water 表示有大量水占據地板。for 常用來引出用途或原因，不能在此表示容器或空間中的內容。" },
      { id: "ENG_R4_L_S198_EX_03", prompt: "Maya is good at ___. (swim / swimming)", steps: ["good at 表示擅長。", "at 是介系詞。", "介系詞後的動作用 swimming。"], answer: "swimming", why: "at 後若接動作，要把 swim 變成 swimming，整組 good at swimming 才完整。原形 swim 不能直接作介系詞 at 的受詞。" },
    ],
    misconceptions: [
      { belief: "所有表示興趣或能力的形容詞後都接 at。", whyWrong: "interested 固定常用 in，good 才常以 at 引出活動。", correction: "連同形容詞和介系詞一起學，不只記中文類別。" },
      { belief: "介系詞後看到動詞時仍保留原形。", whyWrong: "介系詞需要名詞性受詞，動作通常改為 V-ing。", correction: "先確認 to 是否為不定詞；真正介系詞後使用名詞或動名詞。" },
      { belief: "angry with 和 angry about 完全沒有差別。", whyWrong: "前者多指人，後者多指引發情緒的事情。", correction: "辨認介系詞後是對象還是事件。" },
      { belief: "只要背出 famous for，就不必確認主詞為何出名。", whyWrong: "選項內容仍可能與主詞或文章證據不合。", correction: "把搭配和上下文提供的原因一起核對。" },
    ],
    checks: [
      { prompt: "afraid of 後可直接接 go 嗎？", answer: "不可以", reason: "of 是介系詞，若表動作應使用 going。" },
      { prompt: "kind to children 中，to 引出什麼？", answer: "受到友善對待的對象", reason: "children 是 kind 所指向的人。" },
      { prompt: "different from 用來連接哪種關係？", answer: "差異比較的另一方", reason: "from 後接拿來比較的人或事物。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S199", "ENG_R4_S199", {
    objectives: ["能把常見日常語塊當成整體，依功能和情境選用。", "能分辨時間、態度、轉折與補充資訊等不同語塊功能。"],
    sections: [
      { title: "固定語塊有完整溝通功能", content: "on time、right away、by the way 等組合的意思不等於逐字相加。它們可表示準時、立刻或轉換話題；閱讀時先判斷整組在句中完成什麼功能。" },
      { title: "時間與頻率語塊提供事件線索", content: "at first 表示起初，in the end 指最後結果，once in a while 表示偶爾，as usual 表示和往常一樣。這些語塊會改變事件順序或頻率，不能只抓其中一個介系詞。" },
      { title: "說話者也用語塊組織訊息", content: "for example 引出例子，in fact 補充或修正前面的看法，by the way 轉入相關的新話題。若選錯，個別句子可能都通順，但整段邏輯會失去連接。" },
      { title: "情境決定最合適的整組", content: "in a hurry 描述匆忙狀態，have a good time 表示玩得愉快，at least 提供最低限度。題目常以人物行動或後果暗示功能，要選能解釋整個情境的語塊。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S199_EX_01", prompt: "The bell rings at eight. Please arrive ___. (on time / by the way)", steps: ["前句給出固定時間。", "後句要求不要遲到。", "on time 表示在預定時間到達。"], answer: "on time", why: "鐘聲在八點響，要求是準時到達，因此 on time 符合。by the way 用來轉換話題，不能表示抵達時間。" },
      { id: "ENG_R4_L_S199_EX_02", prompt: "The bag is getting wet. Bring it inside ___. (right away / once in a while)", steps: ["袋子正在變濕。", "情況需要立即處理。", "right away 表示立刻。"], answer: "right away", why: "getting wet 顯示問題正在發生，動作不能延後，所以使用 right away。once in a while 表示偶爾，會把緊急要求誤成頻率描述。" },
      { id: "ENG_R4_L_S199_EX_03", prompt: "___, I did not enjoy the class, but later I loved it. (At first / As usual)", steps: ["later 建立前後時間對比。", "空格要表示開始階段。", "at first 與 later 對應。"], answer: "At first", why: "後半句明說 later，前半句應描述起初的感受，At first 正好建立時間轉變。As usual 表示照常，無法和 later 形成這個改變。" },
    ],
    misconceptions: [
      { belief: "看到 time 就把 on time 和 in time 當成同一意思。", whyWrong: "on time 強調符合預定時間，in time 常強調趕在太遲之前。", correction: "用時刻表、期限或危急結果判斷語意。" },
      { belief: "by the way 可以放在任何句首，只是裝飾語。", whyWrong: "它標示話題轉換，若前後仍在同一推論鏈上就可能不合。", correction: "先判斷說話者是否真的加入新的相關事項。" },
      { belief: "at least 表示確切數量。", whyWrong: "它只設定下限，實際數量可能更多。", correction: "把 at least three 解讀為三個或以上。" },
      { belief: "in the end 只要看到句尾就能使用。", whyWrong: "它表示經過過程後的最終結果，不是一般位置標記。", correction: "確認前文是否有發展、嘗試或轉折。" },
    ],
    checks: [
      { prompt: "as usual 表示事件是否和平常不同？", answer: "通常沒有不同", reason: "它指出事情依照往常方式發生。" },
      { prompt: "for example 後面通常出現什麼？", answer: "支持前述概念的例子", reason: "它的功能是把一般說法具體化。" },
      { prompt: "in a hurry 描述什麼狀態？", answer: "匆忙、時間不足的狀態", reason: "它常解釋快速或疏忽的行動。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S200", "ENG_R4_S200", {
    objectives: ["能由上下文判斷基本片語動詞的整體意思。", "能區分動詞原義與加上副詞或介系詞後形成的新方向。"],
    sections: [
      { title: "片語動詞要讀成一個意義單位", content: "look after 表示照顧，find out 表示查明，give up 表示放棄。只翻 look、find、give 會漏掉後面的成分如何改變整體方向。" },
      { title: "同一動詞可形成不同片語", content: "look for 是尋找，look at 是看向，look after 是照顧。題目會用受詞、目的或結果限制答案，因此不能只看到 look 就判斷。" },
      { title: "語境能證明片語的實際義", content: "The milk is gone, so we have run out of it 中，gone 證明 run out of 是用完。若只有片語而沒有足夠情境，應保留可能性，不自行加入原因或後果。" },
      { title: "字典查詢也要以整組為單位", content: "遇到不熟悉的片語時，先查完整形式，再選符合句中詞性與情境的義項。查單一動詞常得到過多意思，容易把字面動作錯套進文章。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S200_EX_01", prompt: "Could you look after my dog this afternoon?", steps: ["受詞是需要人照料的 dog。", "時間涵蓋一段下午。", "look after 在此表示照顧。"], answer: "Take care of the dog.", why: "說話者請對方在下午照料狗，look after 等於 take care of。句子不是要求一直看著狗，也不是尋找走失的狗。" },
      { id: "ENG_R4_L_S200_EX_02", prompt: "I don't know the answer, but I will find it out.", steps: ["前半句指出未知資訊。", "but 引出接下來的處理。", "find out 表示查明答案。"], answer: "Learn the answer.", why: "未知的是 answer，後句承諾去查明，所以 find out 指取得原本不知道的資訊。它不是單純在某處找到一件物品。" },
      { id: "ENG_R4_L_S200_EX_03", prompt: "Do not give up after one mistake.", steps: ["after one mistake 提供受挫情境。", "命令要求繼續嘗試。", "give up 表示停止努力。"], answer: "Keep trying.", why: "只犯一次錯就 give up，意思是停止努力；否定命令要求相反行動，所以可改述為 Keep trying。不能把 give 直譯成贈送。" },
    ],
    misconceptions: [
      { belief: "片語中每個字都應保留最常見的字典意思。", whyWrong: "組合後可能形成無法逐字相加的新義。", correction: "先查完整片語，再用上下文選義。" },
      { belief: "look for、look at、look after 都只是看。", whyWrong: "三者分別表示尋找、看向與照顧。", correction: "把後接成分和受詞角色一起辨認。" },
      { belief: "find out 和 find 可在所有句子中互換。", whyWrong: "find out 偏向查明資訊，find 常指找到人或物。", correction: "確認受詞是資訊、答案，還是具體事物。" },
      { belief: "run out of 一定和跑步有關。", whyWrong: "在物品或時間語境中，它表示耗盡。", correction: "利用 gone、no more、empty 等結果線索判讀。" },
    ],
    checks: [
      { prompt: "grow up 通常描述哪種改變？", answer: "人成長、長大", reason: "up 和 grow 形成成長到成人階段的整體義。" },
      { prompt: "turn down the radio 最可能改變什麼？", answer: "音量", reason: "radio 作受詞時，turn down 常表示調低聲音。" },
      { prompt: "put off a meeting 表示把會議放在哪裡嗎？", answer: "不是", reason: "此片語表示把會議延後。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S201", "ENG_R4_S201", {
    objectives: ["能分辨常見可分與不可分片語動詞。", "能用名詞或代名詞受詞的位置判斷句型是否自然。"],
    sections: [
      { title: "可分片語可讓名詞受詞放在中間", content: "turn off the light 和 turn the light off 都成立；pick up the box 和 pick the box up 也成立。這類組合的受詞若是名詞，常有兩個位置。" },
      { title: "代名詞會顯示可分結構", content: "受詞改成 it 或 them 時，可分片語通常必須把代名詞放中間，例如 turn it off、pick them up。turn off it 在標準考試英文中不採用。" },
      { title: "不可分片語的受詞留在整組後面", content: "look after the child、look for the key、wait for the bus 中，後面的成分不能和動詞拆開。代名詞也放在整組後，如 look after her、wait for it。" },
      { title: "是否可分需要學習實際用法", content: "外形相似不代表結構相同。學生可用字典標示、可靠例句和已學搭配確認，不應自行把所有兩字動詞套成同一規則。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S201_EX_01", prompt: "Please turn ___ off before you leave. (it / for it)", steps: ["turn off 是可分片語。", "受詞為代名詞 it。", "代名詞放在 turn 與 off 中間。"], answer: "it", why: "turn off 的受詞是 it 時，標準位置為 turn it off。for it 會加入不需要的介系詞，也無法完成關掉某物的結構。" },
      { id: "ENG_R4_L_S201_EX_02", prompt: "Noah is looking ___ his missing key. (for / it for)", steps: ["missing key 是尋找的物品。", "look for 是不可分片語。", "key 放在 for 後。"], answer: "for", why: "look for the missing key 表示尋找鑰匙，for 不能移到受詞後。it for 會同時多出代名詞並破壞不可分結構。" },
      { id: "ENG_R4_L_S201_EX_03", prompt: "I wrote the address down. Which other order is possible?", steps: ["write down 是可分片語。", "受詞 address 是名詞。", "名詞也可放在整組後。"], answer: "I wrote down the address.", why: "名詞 the address 可放在 write 與 down 中間，也可放在 write down 後面。若改成 it，則應寫 I wrote it down。" },
    ],
    misconceptions: [
      { belief: "所有片語動詞都能把受詞放在兩個字中間。", whyWrong: "look after、look for 等常見片語不可分。", correction: "逐組確認結構，不由字數推測。" },
      { belief: "名詞可以放在後面，所以代名詞也一定可以。", whyWrong: "可分片語的代名詞受詞通常必須置中。", correction: "遇到 it、them 時先檢查是否要放在動詞和副詞間。" },
      { belief: "不可分表示句中不能出現任何受詞。", whyWrong: "它仍可帶受詞，只是受詞要放在完整片語後。", correction: "把 look after 視為整體，再接 the baby 或 her。" },
      { belief: "介系詞或副詞很短，可以任意移到句尾。", whyWrong: "位置會決定片語結構，有些移動會形成非標準英文。", correction: "以完整例句記憶可接受的受詞位置。" },
    ],
    checks: [
      { prompt: "pick the book up 中，book 可改成 it 而留在原位嗎？", answer: "可以", reason: "pick it up 正是可分片語的代名詞位置。" },
      { prompt: "look after him 可改成 look him after 嗎？", answer: "不可以", reason: "look after 在此不可分，him 留在 after 後。" },
      { prompt: "名詞受詞可有兩個位置就代表片語一定不可分嗎？", answer: "不是", reason: "兩個名詞位置正是可分片語常見特徵。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S202", "ENG_R4_S202", {
    objectives: ["能在可分片語動詞中正確放置名詞與代名詞受詞。", "能依受詞長度和指涉選出清楚、自然的句子。"],
    sections: [
      { title: "先找出片語真正作用的受詞", content: "Please put on your coat 中，your coat 是被穿上的物品。確定受詞後，才判斷它是名詞片語或代名詞，避免把時間、地點誤當受詞。" },
      { title: "代名詞受詞放在可分片語中間", content: "put it on、take them off、write it down、give it back 都把短代名詞置中。這是會考常見且可直接判斷的結構線索。" },
      { title: "名詞受詞通常保有兩種位置", content: "put on the coat 與 put the coat on 都可接受。較長的名詞片語放在整組後面往往較清楚，但重點仍是該片語本身確實可分。" },
      { title: "受詞位置也影響指涉清楚度", content: "若前文已明確提到 tickets，下一句可用 pick them up。代名詞必須和前文數量一致；位置正確但 it、them 指錯，句子仍不能完整傳達意思。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S202_EX_01", prompt: "The fan is still on. Please turn ___ off. (it / them)", steps: ["前文受詞是單數 fan。", "以 it 代替 fan。", "turn off 可分，it 放中間。"], answer: "it", why: "fan 是單數事物，所以用 it 指回；turn off 為可分片語，完整形式是 turn it off。them 的數量不一致。" },
      { id: "ENG_R4_L_S202_EX_02", prompt: "Your shoes are wet. Take ___ off at the door. (them / it)", steps: ["shoes 是複數。", "代名詞要用 them。", "take off 的代名詞放在中間。"], answer: "them", why: "前句提到複數 shoes，後句以 them 承接，並放在 take 和 off 之間。it 只能指單數，take off them 的位置也不合此結構。" },
      { id: "ENG_R4_L_S202_EX_03", prompt: "I wrote down the phone number. Use a pronoun for the noun.", steps: ["the phone number 是單數受詞。", "改用 it。", "可分結構把 it 放在 write 與 down 間。"], answer: "I wrote it down.", why: "電話號碼已在前文出現，可用 it 代替。write down 是可分片語，代名詞不能留在 down 後，因此寫 I wrote it down。" },
    ],
    misconceptions: [
      { belief: "只要知道片語意思，受詞放在哪裡都不影響答案。", whyWrong: "代名詞放錯位置會形成非標準結構。", correction: "先分辨名詞或代名詞，再套用可分片語位置。" },
      { belief: "it 比 them 短，所以所有物品都可用 it。", whyWrong: "代名詞必須和前文單複數一致。", correction: "先找指涉對象，再決定 it 或 them。" },
      { belief: "較長名詞只能放在動詞和副詞中間。", whyWrong: "可分片語的名詞受詞通常也可放在整組後。", correction: "選擇清楚自然的位置，但不要把代名詞規則套到名詞。" },
      { belief: "句中最後一個名詞一定是片語動詞的受詞。", whyWrong: "它可能是時間、地點或另一介系詞的受詞。", correction: "問『哪個東西受到這個動作』來確認真正受詞。" },
    ],
    checks: [
      { prompt: "turn the computer off 改用代名詞後怎麼寫？", answer: "turn it off", reason: "computer 是單數，可分片語把 it 置中。" },
      { prompt: "give back the books 改用代名詞後怎麼寫？", answer: "give them back", reason: "books 是複數，them 放在 give 與 back 間。" },
      { prompt: "put the clean dishes away 中，dishes 是什麼？", answer: "put away 的受詞", reason: "被收好的事物是 clean dishes。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S203", "ENG_R4_S203", {
    objectives: ["能辨認逐字翻譯形成的不自然英文搭配。", "能以常見英文語塊重新表達相同生活意思，而不擅自增加資訊。"],
    sections: [
      { title: "相同概念在兩種語言中切分方式不同", content: "中文說法不能逐字替換成英文，例如『吃藥』常用 take medicine，『下大雨』用 rain heavily 或 heavy rain。直譯可能每個字都認識，整組卻不是英語慣用表達。" },
      { title: "動詞選擇取決於英文搭配", content: "英文說 have breakfast、make friends、ask a question、tell a story。這些動詞不是各自唯一的中文翻譯，而是和後面的名詞一起完成自然意思。" },
      { title: "形式和情境必須同時成立", content: "play the piano 需要冠詞 the，ride a bike 使用 ride 而不是 drive。選項即使傳達大致概念，只要搭配、冠詞或受詞關係不標準，就不是最佳答案。" },
      { title: "用可靠例句修正直譯", content: "遇到不確定搭配時，可查官方字表例句、學習字典或已審核語料中的完整片語。記錄時保留前後一小段情境，才能知道同一名詞在不同意思下是否換動詞。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S203_EX_01", prompt: "The doctor told me to ___ this medicine after dinner. (eat / take)", steps: ["受詞是醫師指示使用的 medicine。", "英文慣用 take medicine。", "after dinner 只說明服用時間。"], answer: "take", why: "醫師指示的是服藥，英文使用 take medicine。eat 通常描述咀嚼食物，不能依中文『吃藥』逐字選入。" },
      { id: "ENG_R4_L_S203_EX_02", prompt: "It rained ___ all night. (heavily / largely)", steps: ["rained 是動作。", "空格要描述雨勢強。", "方式副詞 heavily 與 rain 自然搭配。"], answer: "heavily", why: "句子描述整夜雨勢很大，rained heavily 是自然說法。largely 多表示主要地或大部分，不用來直接描述下雨強度。" },
      { id: "ENG_R4_L_S203_EX_03", prompt: "I ___ breakfast at seven every day. (have / make)", steps: ["breakfast 指日常用餐。", "一般吃早餐用 have breakfast。", "every day 要求現在式。"], answer: "have", why: "句子說每天七點吃早餐，標準搭配是 have breakfast。make breakfast 會改成準備早餐，不一定表示自己吃了。" },
    ],
    misconceptions: [
      { belief: "只要每個中文字都有對應英文，照順序翻譯就會自然。", whyWrong: "兩種語言的慣用動詞和語塊切分不同。", correction: "以完整英文搭配表達概念，不逐字拼接。" },
      { belief: "make breakfast 和 have breakfast 完全相同。", whyWrong: "前者偏向準備，後者表示吃這一餐。", correction: "利用人物行動與後續結果判斷要表達哪個事件。" },
      { belief: "中文說大雨，英文就一定用 big rain。", whyWrong: "英文通常使用 heavy rain 或 rain heavily。", correction: "把天氣強度和常見形容詞、副詞一起記憶。" },
      { belief: "看到樂器名稱就能直接接在 play 後，不需要冠詞。", whyWrong: "一般表示演奏樂器時常用 play the piano 等形式。", correction: "把冠詞視為搭配的一部分，而不是可省略裝飾。" },
    ],
    checks: [
      { prompt: "make friends 表示製作朋友嗎？", answer: "不是", reason: "整組表示和別人成為朋友。" },
      { prompt: "tell a story 和 say a story 哪個是常見搭配？", answer: "tell a story", reason: "tell 常和 story 組合表示講故事。" },
      { prompt: "wear glasses 描述哪個日常狀態？", answer: "戴眼鏡", reason: "英文以 wear 表示衣物或眼鏡在身上的狀態。" },
    ], assets: [],
  }),
];

export const ENGLISH_U29_QUESTIONS = [
  ...skillQuestions("197", [
    { stem: "The answer was wrong because I ___ a mistake in the last step.", options: ["made", "did", "took", "kept"], answerIndex: 0, reasons: ["make a mistake 是犯錯的常見搭配，過去式為 made。", "do 不和 mistake 組成此意。", "take a mistake 不是標準搭配。", "keep 表示保留或遵守，不能表示犯錯。"], reviews: ["because 後說明答案錯誤的原因，動作已發生。", "第一項同時符合搭配與過去時間。"], cognitiveProcess: ["u29-s197-complete-made-a-mistake-after-wrong-answer", "coordinate-collocation-with-past-event"], representationType: "verb-noun-error-collocation", misconceptionTargets: ["translate-do-a-mistake"] },
    { stem: "The bus leaves in two minutes. We must ___ it.", options: ["miss", "catch", "hold", "follow"], answerIndex: 1, reasons: ["miss 表示沒趕上，與 must 的目的相反。", "catch the bus 表示趕上這班車。", "hold the bus 不是乘客趕車的自然說法。", "follow 只表示跟隨，不保證搭上車。"], reviews: ["in two minutes 建立必須及時趕上的情境。", "第二項表達成功搭上即將離站的車。"], cognitiveProcess: ["u29-s197-select-catch-for-imminent-bus", "distinguish-catching-from-missing-or-following"], representationType: "transport-collocation-context", misconceptionTargets: ["use-take-when-catching-is-tested"] },
    { stem: "Please ___ attention to the last safety rule.", options: ["give", "take", "pay", "make"], answerIndex: 2, reasons: ["give attention 可見於其他結構，但此命令採固定搭配。", "take attention 不是此意的標準說法。", "pay attention to 表示注意某事。", "make attention 不成立。"], reviews: ["to 已出現在句尾，應完成 pay attention to。", "第三項要求聽者把注意力放在最後一條規則。"], cognitiveProcess: ["u29-s197-complete-pay-attention-to-safety-rule", "use-following-to-as-collocation-evidence"], representationType: "attention-collocation-cloze", misconceptionTargets: ["choose-give-from-chinese-translation"] },
    { stem: "I said I would return the book, and I always ___ my promises.", options: ["pay", "do", "make", "keep"], answerIndex: 3, reasons: ["pay 不表示履行承諾。", "do promises 不是自然搭配。", "make a promise 是作出承諾，不是履行。", "keep a promise 表示遵守已作出的承諾。"], reviews: ["前半句已經作出承諾，後半句要描述是否履行。", "第四項保留 make 與 keep 在事件階段上的差別。"], cognitiveProcess: ["u29-s197-select-keep-after-promise-already-made", "separate-making-from-fulfilling-a-promise"], representationType: "promise-stage-collocation", misconceptionTargets: ["repeat-make-after-promise-exists"] },
    { stem: "After two hours of practice, the players decided to ___ a short break.", options: ["take", "bring", "catch", "spend"], answerIndex: 0, reasons: ["take a break 表示暫停休息。", "bring a break 不表示休息。", "catch a break 有其他用法，不合此直接決定。", "spend 後需接時間，不接 a break 表此意。"], reviews: ["長時間練習後的合理決定是休息。", "第一項形成最直接的日常搭配。"], cognitiveProcess: ["u29-s197-infer-take-a-break-after-practice", "reject-literal-motion-verbs-with-break"], representationType: "rest-collocation-situation", misconceptionTargets: ["treat-break-as-object-to-bring"] },
    { stem: "Our teacher asked us to ___ our homework before Friday.", options: ["make", "do", "have", "write"], answerIndex: 1, reasons: ["make homework 不是標準搭配。", "do homework 表示完成作業。", "have homework 表示有作業，不表示完成。", "write 只涵蓋書寫，未必符合所有作業。"], reviews: ["before Friday 是完成作業的期限。", "第二項表達執行 homework，而非擁有它。"], cognitiveProcess: ["u29-s197-complete-do-homework-before-deadline", "distinguish-having-from-performing-homework"], representationType: "schoolwork-collocation-deadline", misconceptionTargets: ["translate-make-homework"] },
    { stem: "Could I ___ you a question about the map?", options: ["tell", "say", "ask", "speak"], answerIndex: 2, reasons: ["tell 通常接資訊或故事，不形成 tell a question。", "say 不以此雙受詞結構使用。", "ask someone a question 是向某人提問。", "speak 常接語言或以介系詞引出對象。"], reviews: ["you 是被詢問的人，a question 是詢問內容。", "第三項能同時帶這兩個受詞。"], cognitiveProcess: ["u29-s197-select-ask-with-person-and-question", "separate-ask-from-tell-say-speak-frames"], representationType: "communication-double-object-collocation", misconceptionTargets: ["use-tell-a-question"] },
    { stem: "The guide will ___ us some advice about safe travel.", options: ["ask", "make", "pay", "give"], answerIndex: 3, reasons: ["ask advice 需用 ask for，且角色方向不同。", "make advice 不是自然搭配。", "pay advice 不成立。", "give someone advice 表示向對方提供建議。"], reviews: ["guide 是提供資訊的人，us 是接受者。", "第四項符合給予建議的角色方向。"], cognitiveProcess: ["u29-s197-map-guide-role-to-give-advice", "distinguish-giving-from-requesting-advice"], representationType: "advice-role-collocation", misconceptionTargets: ["omit-for-after-ask-advice"] },
    { stem: "Before we buy anything, we need to ___ a clear plan.", options: ["make", "do", "pay", "catch"], answerIndex: 0, reasons: ["make a plan 表示擬定計畫。", "do a plan 不是此意的標準搭配。", "pay 和 plan 沒有這種關係。", "catch 不表示形成計畫。"], reviews: ["before 指出購買前要先形成安排。", "第一項把 plan 當成需要擬定的內容。"], cognitiveProcess: ["u29-s197-select-make-plan-before-purchase", "use-event-order-to-identify-planning-collocation"], representationType: "planning-collocation-sequence", misconceptionTargets: ["overuse-do-for-create"] },
    { stem: "The students ___ notes to write down key points while the scientist explained the test.", options: ["gave", "took", "paid", "held"], answerIndex: 1, reasons: ["give notes 表示交給別人，不能表示當下記錄。", "take notes 表示把聽到的重點記下來。", "pay notes 不成立。", "hold notes 只可能表示拿著筆記，不會完成 write down key points。"], reviews: ["to write down key points 明確指出學生正在做筆記。", "第二項是課堂聽講情境的標準搭配。"], cognitiveProcess: ["u29-s197-select-took-notes-during-explanation", "separate-recording-from-storing-notes"], representationType: "note-taking-simultaneous-action", misconceptionTargets: ["choose-keep-for-current-note-taking"] },
    { stem: "I ___ the train because I reached the station too late.", options: ["caught", "rode", "missed", "left"], answerIndex: 2, reasons: ["caught 表示趕上，和 too late 矛盾。", "rode 表示乘坐，前提是已搭上。", "missed the train 表示沒有趕上。", "left 需要不同主詞角色，通常是 train left。"], reviews: ["too late 是未搭上列車的直接證據。", "第三項和結果一致，沒有倒置行動者。"], cognitiveProcess: ["u29-s197-infer-missed-train-from-late-arrival", "check-transport-collocation-against-result"], representationType: "transport-result-collocation", misconceptionTargets: ["ignore-contradiction-between-caught-and-late"] },
    { stem: "The neighbors ___ a long talk and solved the problem together.", options: ["did", "gave", "made", "had"], answerIndex: 3, reasons: ["do a talk 不是進行交談的自然說法。", "give a talk 偏向一人發表演講。", "make a talk 不合此互相討論。", "have a talk 表示一起交談。"], reviews: ["together 和 solved 顯示雙方進行討論。", "第四項不把互動誤解成單向演講。"], cognitiveProcess: ["u29-s197-select-had-a-talk-for-mutual-discussion", "contrast-conversation-with-giving-a-speech"], representationType: "interaction-collocation-outcome", misconceptionTargets: ["use-give-talk-for-dialogue"] },
  ]),
  ...skillQuestions("198", [
    { stem: "This science club is full ___ students who enjoy building things.", options: ["of", "at", "to", "for"], answerIndex: 0, reasons: ["full of 引出充滿其中的人或物。", "full at 不能表示內容物。", "full to 不合此結構。", "full for 不表示社團成員。"], reviews: ["students 是社團中充滿的成員。", "第一項完成 full of 的內容關係。"], cognitiveProcess: ["u29-s198-complete-full-of-with-club-members", "identify-container-content-adjective-frame"], representationType: "adjective-preposition-content", misconceptionTargets: ["choose-for-as-purpose"] },
    { stem: "My sister is good ___ drawing small animals.", options: ["in", "at", "of", "with"], answerIndex: 1, reasons: ["good in 不用來直接引出擅長的活動。", "good at 加動名詞表示擅長某事。", "good of 常出現在評價某人行為的其他結構。", "good with 可描述善於應對某類人事物，結構不同。"], reviews: ["drawing 是活動，at 是介系詞。", "第二項同時符合搭配與 V-ing 形式。"], cognitiveProcess: ["u29-s198-select-at-before-drawing-skill", "distinguish-activity-skill-from-other-good-frames"], representationType: "ability-adjective-gerund", misconceptionTargets: ["use-in-for-ability"] },
    { stem: "The little boy is afraid ___ the dark.", options: ["from", "with", "of", "about"], answerIndex: 2, reasons: ["afraid from 不是標準搭配。", "with 不引出害怕的事物。", "afraid of 引出令人害怕的對象。", "about 常搭 worried，不是此處基本形式。"], reviews: ["the dark 是引起害怕的事物。", "第三項完成 be afraid of。"], cognitiveProcess: ["u29-s198-complete-afraid-of-dark", "map-emotion-target-to-of"], representationType: "fear-adjective-preposition", misconceptionTargets: ["translate-afraid-from"] },
    { stem: "Are you ready ___ tomorrow's long walk?", options: ["of", "with", "at", "for"], answerIndex: 3, reasons: ["ready of 不成立。", "ready with 可出現在已備妥某物的不同結構。", "ready at 不引出即將進行的活動。", "ready for 表示為某事做好準備。"], reviews: ["tomorrow's long walk 是即將面對的活動。", "第四項符合準備對象。"], cognitiveProcess: ["u29-s198-select-ready-for-future-walk", "use-upcoming-event-as-preposition-evidence"], representationType: "readiness-adjective-event", misconceptionTargets: ["choose-at-from-activity"] },
    { stem: "The town is famous ___ its night market.", options: ["for", "to", "from", "in"], answerIndex: 0, reasons: ["famous for 引出聞名的原因或特色。", "famous to 可引出知名的對象，並非此句關係。", "from 表示來源，不合。", "in 常引出領域或地點，未直接說明特色。"], reviews: ["night market 是小鎮聞名的原因。", "第一項呈現特色與名聲的連結。"], cognitiveProcess: ["u29-s198-link-famous-town-to-night-market-cause", "separate-reason-from-audience-or-place"], representationType: "fame-adjective-reason", misconceptionTargets: ["use-of-after-famous"] },
    { stem: "This answer is different ___ the one in my book.", options: ["of", "from", "for", "at"], answerIndex: 1, reasons: ["different of 不是比較搭配。", "different from 引出比較的另一項。", "for 表用途或對象，不合。", "at 不建立差異比較。"], reviews: ["the one 指書中的答案，是比較對象。", "第二項完成兩項答案的差異關係。"], cognitiveProcess: ["u29-s198-select-from-for-answer-comparison", "resolve-one-as-comparison-counterpart"], representationType: "difference-adjective-comparison", misconceptionTargets: ["translate-different-with"] },
    { stem: "We are worried ___ the strong wind tonight.", options: ["of", "for", "about", "to"], answerIndex: 2, reasons: ["worried of 不是標準基本搭配。", "worried for 常偏向擔心某人的安危，題幹是事件。", "worried about 引出令人擔心的情況。", "to 不合此形容詞結構。"], reviews: ["strong wind 是擔心的事情，不是接受動作的人。", "第三項精確引出憂慮內容。"], cognitiveProcess: ["u29-s198-select-about-for-weather-concern", "distinguish-worried-about-event-from-for-person"], representationType: "worry-adjective-event", misconceptionTargets: ["use-of-for-all-fear-states"] },
    { stem: "The coach was angry ___ the player who broke the rule.", options: ["about", "of", "for", "with"], answerIndex: 3, reasons: ["angry about 通常引出事情，這裡直接接人。", "angry of 不成立。", "angry for 不是此處對象關係。", "angry with someone 表示對某人生氣。"], reviews: ["the player 是情緒指向的人。", "第四項區分人與造成生氣的事件。"], cognitiveProcess: ["u29-s198-select-with-for-angry-person-target", "classify-preposition-object-as-person"], representationType: "anger-adjective-person", misconceptionTargets: ["use-about-before-person"] },
    { stem: "The class was surprised ___ the sudden change in the plan.", options: ["at", "for", "from", "to"], answerIndex: 0, reasons: ["surprised at 可引出令人意外的事情。", "for 不表示驚訝原因。", "from 不合此狀態。", "to 後通常接動詞原形，不直接接此名詞片語。"], reviews: ["sudden change 是造成驚訝的事件。", "第一項能直接接名詞片語。"], cognitiveProcess: ["u29-s198-select-at-before-surprising-change", "distinguish-noun-event-from-to-infinitive-frame"], representationType: "surprise-adjective-cause", misconceptionTargets: ["choose-to-before-noun-phrase"] },
    { stem: "Our new neighbor has always been kind ___ us.", options: ["with", "to", "for", "at"], answerIndex: 1, reasons: ["kind with 不是此處基本人際搭配。", "kind to someone 表示友善對待該人。", "for 不引出接受友善的對象。", "at 不合。"], reviews: ["us 是受到鄰居友善對待的人。", "第二項呈現態度指向。"], cognitiveProcess: ["u29-s198-select-to-for-kind-treatment-recipient", "identify-recipient-of-adjective-attitude"], representationType: "kindness-adjective-recipient", misconceptionTargets: ["use-with-for-all-person-relations"] },
    { stem: "The children are excited ___ visiting the farm next week.", options: ["of", "for", "about", "from"], answerIndex: 2, reasons: ["excited of 不是常見搭配。", "excited for 可有其他對象用法，題幹直接引出自己期待的活動。", "excited about 加動名詞表示對活動感到興奮。", "from 不表示期待內容。"], reviews: ["visiting 是介系詞後的動名詞活動。", "第三項把情緒連到下週農場行程。"], cognitiveProcess: ["u29-s198-complete-excited-about-visiting", "recognize-gerund-as-emotion-topic"], representationType: "excitement-adjective-gerund", misconceptionTargets: ["use-to-before-visiting"] },
    { stem: "Which sentence says that the bag has many books in it?", options: ["The bag is good at books.", "The bag is ready for books.", "The bag is afraid of books.", "The bag is full of books."], answerIndex: 3, reasons: ["good at 描述能力，不能描述袋子內容。", "ready for 不表示已裝有書。", "afraid of 把袋子錯當成有恐懼感。", "full of 明確表示袋中有許多書。"], reviews: ["問題指定袋內有許多書，需找內容關係。", "第四項是唯一不擬人化且語意完整的描述。"], cognitiveProcess: ["u29-s198-map-contains-many-to-full-of", "reject-semantic-category-errors-in-adjective-frames"], representationType: "adjective-preposition-paraphrase", misconceptionTargets: ["match-preposition-without-subject-sense"] },
  ]),
  ...skillQuestions("199", [
    { stem: "The movie starts at 6:30, so please be there ___.", options: ["on time", "by the way", "at first", "once in a while"], answerIndex: 0, reasons: ["on time 表示符合預定時間到達。", "by the way 用於轉換話題。", "at first 表示起初。", "once in a while 描述低頻率，與準時無關。"], reviews: ["6:30 是明確的預定開始時間。", "第一項回應不得遲到的要求。"], cognitiveProcess: ["u29-s199-select-on-time-for-fixed-movie-start", "match-time-chunk-to-scheduled-event"], representationType: "fixed-chunk-schedule", misconceptionTargets: ["confuse-on-time-with-frequency"] },
    { stem: "The soup is burning. Turn off the stove ___.", options: ["as usual", "right away", "for example", "at least"], answerIndex: 1, reasons: ["as usual 表示照常，無法回應危險。", "right away 表示立刻採取行動。", "for example 用來舉例。", "at least 表示最低限度。"], reviews: ["burning 顯示需要立即處理。", "第二項是唯一符合緊急時間需求的語塊。"], cognitiveProcess: ["u29-s199-select-right-away-for-burning-soup", "rank-chunks-by-urgent-response-function"], representationType: "fixed-chunk-urgency", misconceptionTargets: ["treat-as-usual-as-neutral-time-adverb"] },
    { stem: "___, the room looked too small, but we later found enough space.", options: ["In fact", "On time", "At first", "By the way"], answerIndex: 2, reasons: ["In fact 通常補充或修正事實，未直接建立開始階段。", "On time 表準時。", "At first 與 later 形成起初和後來的對比。", "By the way 轉換話題。"], reviews: ["but later 是決定答案的時間線索。", "第三項呈現最初印象後來被改變。"], cognitiveProcess: ["u29-s199-pair-at-first-with-later-space-discovery", "build-initial-later-contrast"], representationType: "fixed-chunk-time-transition", misconceptionTargets: ["choose-in-fact-for-any-contrast"] },
    { stem: "We tried three roads. ___, we reached the lake before dark.", options: ["For example", "In a hurry", "Once in a while", "In the end"], answerIndex: 3, reasons: ["For example 不表示嘗試後的結果。", "In a hurry 描述匆忙狀態。", "Once in a while 表示偶爾。", "In the end 引出多次嘗試後的最終結果。"], reviews: ["tried three roads 建立一段過程。", "第四項把抵達湖邊標成最後結果。"], cognitiveProcess: ["u29-s199-select-in-the-end-after-three-routes", "distinguish-final-outcome-from-example-or-frequency"], representationType: "fixed-chunk-outcome", misconceptionTargets: ["use-at-last-without-process-evidence"] },
    { stem: "I was ___ and left my keys on the table.", options: ["in a hurry", "on time", "by the way", "in fact"], answerIndex: 0, reasons: ["in a hurry 可解釋匆忙造成遺漏。", "on time 表準時，不能解釋忘帶鑰匙。", "by the way 是話題標記。", "in fact 是訊息組織語。"], reviews: ["left my keys 是匆忙時可能出現的後果。", "第一項提供行動狀態而非談話功能。"], cognitiveProcess: ["u29-s199-infer-in-a-hurry-from-forgotten-keys", "connect-state-chunk-to-plausible-consequence"], representationType: "fixed-chunk-causal-context", misconceptionTargets: ["select-on-time-because-leaving-is-timed"] },
    { stem: "We visit that quiet beach ____, perhaps twice a year.", options: ["right away", "once in a while", "in the end", "at first"], answerIndex: 1, reasons: ["right away 表立即，不是頻率。", "once in a while 表示偶爾。", "in the end 表最終結果。", "at first 表起初。"], reviews: ["twice a year 顯示低頻率。", "第二項不把偶爾誤解成固定每日行程。"], cognitiveProcess: ["u29-s199-match-once-in-a-while-to-twice-yearly", "identify-low-frequency-evidence"], representationType: "fixed-chunk-frequency", misconceptionTargets: ["confuse-a-while-with-duration"] },
    { stem: "Some fruit, ___ apples and oranges, is easy to carry.", options: ["as usual", "at least", "for example", "on time"], answerIndex: 2, reasons: ["as usual 不引出具體例子。", "at least 設下限。", "for example 引出 apples and oranges 作例子。", "on time 與水果無關。"], reviews: ["apples and oranges 是前面 Some fruit 的具體成員。", "第三項清楚標示例證關係。"], cognitiveProcess: ["u29-s199-select-for-example-before-fruit-members", "map-general-category-to-specific-instances"], representationType: "fixed-chunk-example-marker", misconceptionTargets: ["use-in-fact-to-list-examples"] },
    { stem: "The sky looks clear. ___, the report says it may rain tonight.", options: ["As usual", "At least", "Right away", "In fact"], answerIndex: 3, reasons: ["As usual 沒有表達對表面看法的修正。", "At least 不是事實補充標記。", "Right away 表立即。", "In fact 引出和第一印象不同的資訊。"], reviews: ["天氣報告修正只看天空得到的判斷。", "第四項建立表象與進一步事實的差異。"], cognitiveProcess: ["u29-s199-use-in-fact-to-correct-clear-sky-impression", "contrast-observation-with-report-evidence"], representationType: "fixed-chunk-correction", misconceptionTargets: ["use-by-the-way-for-direct-correction"] },
    { stem: "You need ___ two bottles of water for the walk.", options: ["at least", "at first", "in fact", "by the way"], answerIndex: 0, reasons: ["at least two 表示兩瓶是最低數量。", "at first 表開始階段。", "in fact 不修飾數量下限。", "by the way 是談話轉折。"], reviews: ["need 和數量共同建立最低需求。", "第一項仍允許攜帶超過兩瓶。"], cognitiveProcess: ["u29-s199-interpret-at-least-two-as-minimum-water", "preserve-open-upper-bound-in-quantity-chunk"], representationType: "fixed-chunk-minimum", misconceptionTargets: ["read-at-least-as-exactly"] },
    { stem: "___, did you return the library book I lent you?", options: ["In the end", "By the way", "On time", "In a hurry"], answerIndex: 1, reasons: ["In the end 需要前述過程的最終結果。", "By the way 可加入相關但新的問題。", "On time 不能當話題轉換語。", "In a hurry 描述人物狀態。"], reviews: ["問書是談話中附帶加入的新事項。", "第二項的功能是轉換到另一個相關話題。"], cognitiveProcess: ["u29-s199-select-by-the-way-for-added-library-question", "identify-discourse-topic-shift"], representationType: "fixed-chunk-topic-shift", misconceptionTargets: ["treat-by-the-way-as-location-phrase"] },
    { stem: "The mail carrier came at nine ____, just as she does every weekday.", options: ["at first", "right away", "as usual", "for example"], answerIndex: 2, reasons: ["at first 不表示重複慣例。", "right away 表立即。", "as usual 表示和每個平日一樣。", "for example 不合此事件敘述。"], reviews: ["every weekday 和 just as she does 提供慣例證據。", "第三項不把固定行程誤成首次發生。"], cognitiveProcess: ["u29-s199-select-as-usual-from-weekday-routine", "link-repeated-schedule-to-customary-chunk"], representationType: "fixed-chunk-routine", misconceptionTargets: ["confuse-usual-with-frequency-word-only"] },
    { stem: "Everyone laughed and sang at the picnic. They ___.", options: ["arrived on time", "left in a hurry", "waited at least", "had a good time"], answerIndex: 3, reasons: ["準時抵達沒有由歡笑和唱歌證明。", "匆忙離開與題幹歡樂活動無關。", "at least 後缺少下限內容。", "had a good time 可概括玩得愉快。"], reviews: ["laughed and sang 是愉快經驗的明示線索。", "第四項總結活動品質而未增加時間資訊。"], cognitiveProcess: ["u29-s199-paraphrase-picnic-enjoyment-as-good-time", "avoid-unstated-arrival-or-departure-details"], representationType: "fixed-chunk-event-summary", misconceptionTargets: ["choose-time-chunk-from-word-time-alone"] },
  ]),
  ...skillQuestions("200", [
    { stem: "Please look after the baby while I cook. What should you do?", options: ["Take care of the baby.", "Search for the baby.", "Look only at the baby.", "Wake the baby up."], answerIndex: 0, reasons: ["look after 在此表示照顧嬰兒。", "search for 是尋找，題幹沒有走失。", "只觀看不足以表達照料責任。", "題幹沒有要求叫醒。"], reviews: ["while I cook 說明說話者暫時交付照顧工作。", "第一項保留責任內容，沒有加入未說明動作。"], cognitiveProcess: ["u29-s200-paraphrase-look-after-baby-as-care", "bound-phrasal-meaning-by-temporary-care-context"], representationType: "phrasal-verb-paraphrase-care", misconceptionTargets: ["read-look-after-literally"] },
    { stem: "We need to find out when the store closes. What information is missing?", options: ["Where the store is", "Its closing time", "What the store sells", "Who owns the store"], answerIndex: 1, reasons: ["find out 的受詞不是地點。", "when the store closes 指關門時間。", "商品內容未被詢問。", "店主身分未被詢問。"], reviews: ["find out 表示查明未知資訊。", "第二項精確改述 when 子句，沒有擴大問題。"], cognitiveProcess: ["u29-s200-resolve-find-out-when-as-closing-time", "identify-information-gap-in-phrasal-complement"], representationType: "phrasal-verb-information-target", misconceptionTargets: ["treat-find-out-as-locating-building"] },
    { stem: "After many tries, the team did not give up. What happened?", options: ["They gave the work to someone else.", "They stopped after the first try.", "They continued trying.", "They forgot the goal."], answerIndex: 2, reasons: ["give up 不表示轉交工作。", "did not give up 排除停止。", "否定放棄表示繼續嘗試。", "題幹沒有忘記目標。"], reviews: ["many tries 與 did not 共同支持持續努力。", "第三項是由否定片語可推出的最小結論。"], cognitiveProcess: ["u29-s200-infer-continued-effort-from-not-give-up", "apply-negation-to-phrasal-meaning"], representationType: "phrasal-verb-negation-inference", misconceptionTargets: ["translate-give-as-transfer"] },
    { stem: "We have run out of milk. What is true?", options: ["The milk is outside.", "We are running with milk.", "The milk was too cold.", "There is no milk left."], answerIndex: 3, reasons: ["out 不表示牛奶在屋外。", "run out of 在此與跑步無關。", "句中沒有溫度資訊。", "run out of 表示已用完。"], reviews: ["have run out 表示耗盡狀態已影響現在。", "第四項完整保留 milk 已無剩餘。"], cognitiveProcess: ["u29-s200-interpret-run-out-of-milk-as-none-left", "reject-literal-run-and-location-readings"], representationType: "phrasal-verb-resource-depletion", misconceptionTargets: ["read-out-as-outdoors"] },
    { stem: "The meeting was put off until next Monday. It was ___.", options: ["moved to a later time", "held earlier than planned", "made shorter", "moved to another room"], answerIndex: 0, reasons: ["put off 表示延後，until Monday 指新時間。", "earlier 與 off 的延後方向相反。", "題幹沒有時長改變。", "沒有提供房間變更。"], reviews: ["until next Monday 直接證明改的是日期。", "第一項沒有把時間變動誤成地點變動。"], cognitiveProcess: ["u29-s200-derive-postponement-from-put-off-until-monday", "separate-time-change-from-duration-and-place"], representationType: "phrasal-verb-postponement", misconceptionTargets: ["read-put-as-physical-placement"] },
    { stem: "Please turn down the radio; the baby is sleeping. What should change?", options: ["The station", "The sound", "The song", "The power"], answerIndex: 1, reasons: ["turn down 不要求換電台。", "睡眠情境下表示把聲音調小。", "題幹未要求換歌。", "若關閉電源應使用 turn off。"], reviews: ["baby is sleeping 是降低聲音的原因。", "第二項符合 radio 作受詞時的常見片語義。"], cognitiveProcess: ["u29-s200-map-turn-down-radio-to-volume-reduction", "use-sleeping-context-to-select-phrasal-sense"], representationType: "phrasal-verb-device-control", misconceptionTargets: ["interpret-down-as-physical-direction"] },
    { stem: "The lights went out during the storm. What happened?", options: ["They became brighter.", "They moved outside.", "They stopped shining.", "They changed color."], answerIndex: 2, reasons: ["went out 不表示變亮。", "out 不是移到戶外。", "lights went out 表示燈熄滅。", "題幹沒有顏色資訊。"], reviews: ["during the storm 支持停電或熄燈情境，但不指定原因。", "第三項只陳述可由片語確定的結果。"], cognitiveProcess: ["u29-s200-interpret-lights-went-out-as-stopped-shining", "avoid-overinferring-storm-caused-power-failure"], representationType: "phrasal-verb-state-change", misconceptionTargets: ["read-go-out-as-leave-home"] },
    { stem: "The coach told us to warm up before running. Why?", options: ["To choose a team name", "To finish the race", "To put on warmer coats", "To prepare our bodies for exercise"], answerIndex: 3, reasons: ["warm up 不涉及隊名。", "準備不等於已完成比賽。", "此運動情境不是單純穿外套。", "warm up 表示運動前讓身體做好準備。"], reviews: ["before running 限定為運動準備義。", "第四項未保證比賽結果，只說明準備目的。"], cognitiveProcess: ["u29-s200-select-exercise-sense-of-warm-up", "distinguish-body-preparation-from-clothing-warmth"], representationType: "phrasal-verb-purpose-inference", misconceptionTargets: ["interpret-warm-up-as-dressing-only"] },
    { stem: "My cousin grew up in a small town near the sea. What does 'grew up' describe?", options: ["A person's childhood in that town", "A plant becoming taller", "A town becoming larger", "A trip to the sea"], answerIndex: 0, reasons: ["主詞是 cousin，grew up 描述這個人在當地度過童年。", "cousin 是人，不是長高的植物。", "town 不是 grew up 的主詞。", "near the sea 只說明小鎮位置，不表示旅行。"], reviews: ["My cousin 是片語的主詞，in a small town 是成長地點。", "第一項不把 near the sea 誤成旅行事件。"], cognitiveProcess: ["u29-s200-interpret-person-grew-up-as-childhood-location", "track-phrasal-subject-before-selecting-sense"], representationType: "phrasal-verb-life-stage", misconceptionTargets: ["apply-plant-growth-sense-to-person"] },
    { stem: "The rain stopped, so the game went on. The game ___.", options: ["was canceled", "continued", "moved inside", "became easier"], answerIndex: 1, reasons: ["went on 表繼續，不能表示取消。", "continued 是此片語在事件語境中的意思。", "題幹沒有移到室內。", "沒有難度變化。"], reviews: ["rain stopped 解除了中斷原因。", "第二項只推得比賽恢復或繼續，不添加地點和難度。"], cognitiveProcess: ["u29-s200-paraphrase-game-went-on-as-continued", "use-cause-removal-to-confirm-continuation"], representationType: "phrasal-verb-continuation", misconceptionTargets: ["confuse-go-on-with-leave"] },
    { stem: "I cannot hear the video. Can you turn it up?", options: ["Play it again from the start.", "Make the screen brighter.", "Make the sound louder.", "Choose a different video."], answerIndex: 2, reasons: ["turn up 不必重新播放。", "hear 指向聲音，不是螢幕亮度。", "turn up 在此表示調高音量。", "題幹沒有要求換影片。"], reviews: ["cannot hear 是選擇 louder 的直接證據。", "第三項把 it 正確連回 video 的聲音設定。"], cognitiveProcess: ["u29-s200-infer-turn-up-video-as-increase-sound", "use-sensory-verb-hear-to-select-control-dimension"], representationType: "phrasal-verb-pronoun-context", misconceptionTargets: ["treat-up-as-screen-position"] },
    { stem: "The hikers came back before dark. What is known?", options: ["They reached the top.", "They found a shorter path.", "They walked very fast.", "They returned before dark."], answerIndex: 3, reasons: ["came back 不證明登頂。", "沒有路線資訊。", "返回時間不能證明速度。", "came back 表示返回，before dark 給出時間。"], reviews: ["題目只能採用片語和時間片語明示內容。", "第四項避免從準時返回猜測行程細節。"], cognitiveProcess: ["u29-s200-restate-came-back-as-returned-with-time", "limit-phrasal-inference-to-explicit-return"], representationType: "phrasal-verb-safe-inference", misconceptionTargets: ["invent-trip-success-from-return"] },
  ]),
  ...skillQuestions("201", [
    { stem: "The room is dark. Please turn the light on. Which order is also possible?", options: ["Please turn on the light.", "Please turn the on light.", "Please the light turn on.", "Please turn on it the light."], answerIndex: 0, reasons: ["turn on 可分，名詞受詞也可放在整組後。", "on 不能插在冠詞與名詞間。", "命令句動詞應在主詞省略後直接出現。", "it 與 the light 重複受詞且位置錯誤。"], reviews: ["原句已展示名詞置中，題目要求另一個可接受順序。", "第一項只移動完整名詞受詞，沒有增刪資訊。"], cognitiveProcess: ["u29-s201-transform-turn-light-on-to-postparticle-noun", "preserve-imperative-and-single-object"], representationType: "separable-phrasal-noun-alternate", misconceptionTargets: ["split-determiner-from-noun"] },
    { stem: "I am looking ___ my blue cap, but I cannot find it.", options: ["it for", "for", "my cap for", "for it my cap"], answerIndex: 1, reasons: ["look it for 把不可分片語拆開。", "look for my blue cap 表示尋找帽子。", "my cap for 顛倒受詞位置。", "it 和 my cap 重複指同一受詞。"], reviews: ["cannot find it 證明 look for 是尋找義。", "第二項讓完整名詞受詞接在 for 後。"], cognitiveProcess: ["u29-s201-keep-look-for-before-blue-cap", "reject-object-insertion-in-inseparable-phrasal"], representationType: "inseparable-phrasal-cloze", misconceptionTargets: ["separate-look-for"] },
    { stem: "Which sentence places the pronoun between the parts of 'put away'?", options: ["Put away them after dinner.", "Put away after dinner them.", "Put them away after dinner.", "Put after dinner them away."], answerIndex: 2, reasons: ["可分片語的代名詞不能留在 away 後。", "時間片語不能插入片語與受詞。", "put them away 把代名詞放在可分片語中間。", "after dinner 被錯放在動詞與受詞間。"], reviews: ["題幹明確指定 put away 的代名詞位置。", "第三項也保留 after dinner 作時間修飾語。"], cognitiveProcess: ["u29-s201-identify-pronoun-middle-in-put-away", "keep-time-adjunct-outside-phrasal-object-unit"], representationType: "separable-phrasal-pronoun-order", misconceptionTargets: ["place-pronoun-after-particle"] },
    { stem: "We waited for the bus for twenty minutes. Which words form the verb phrase?", options: ["waited the bus", "the bus for", "for twenty", "waited for"], answerIndex: 3, reasons: ["waited 不能直接帶 the bus 表等待。", "the bus for 不是動詞片語。", "for twenty 是未完整的時間片語。", "waited for 形成不可分搭配，the bus 是受詞。"], reviews: ["句中兩個 for 功能不同，第一個屬於 wait for。", "第四項不把表示時長的第二個 for 誤納入片語。"], cognitiveProcess: ["u29-s201-isolate-waited-for-before-bus", "distinguish-phrasal-preposition-from-duration-for"], representationType: "inseparable-phrasal-boundary", misconceptionTargets: ["attach-duration-for-to-verb-phrase"] },
    { stem: "The music is too loud. Turn ___ down, please.", options: ["it", "down it", "the music it", "it the music"], answerIndex: 0, reasons: ["turn it down 是代名詞受詞的標準位置。", "down it 把代名詞留在粒子後。", "the music 和 it 重複受詞。", "兩個受詞並列且順序不成立。"], reviews: ["前句已提 music，後句可用 it 承接。", "第一項也符合降低音量的情境。"], cognitiveProcess: ["u29-s201-place-it-between-turn-and-down", "resolve-music-to-singular-pronoun"], representationType: "separable-phrasal-reference", misconceptionTargets: ["repeat-noun-and-pronoun-object"] },
    { stem: "The nurse looked after the child. Use a pronoun for 'the child.'", options: ["The nurse looked her after.", "The nurse looked after her.", "The nurse her looked after.", "The nurse looked after she."], answerIndex: 1, reasons: ["look after 不可分，不能把 her 放中間。", "her 是介系詞 after 後的受格代名詞。", "受詞不能放在主詞和動詞間。", "she 是主格，不作 after 的受詞。"], reviews: ["片語結構與代名詞格位都要正確。", "第二項保留 look after 完整相連。"], cognitiveProcess: ["u29-s201-replace-child-with-her-after-look-after", "coordinate-inseparability-with-object-case"], representationType: "inseparable-phrasal-pronoun-replacement", misconceptionTargets: ["apply-separable-rule-to-look-after"] },
    { stem: "Which sentence keeps 'listen to' together before its object?", options: ["Listen the message to again.", "Listen it to again.", "Listen to the message again.", "Listen the message again to."], answerIndex: 2, reasons: ["message 不能插進 listen to。", "代名詞也不能拆開這個搭配。", "listen to 保持相連，受詞接在 to 後。", "to 不能移到句尾。"], reviews: ["again 是重複修飾語，不影響片語邊界。", "第三項把 the message 放在完整片語後。"], cognitiveProcess: ["u29-s201-preserve-listen-to-before-message", "exclude-again-from-object-placement-rule"], representationType: "inseparable-phrasal-full-sentence", misconceptionTargets: ["move-to-after-object"] },
    { stem: "I picked the package up at noon. Which part may move after 'up'?", options: ["I", "picked", "at noon", "the package"], answerIndex: 3, reasons: ["主詞 I 不能移到片語後。", "主要動詞 picked 不能移除。", "at noon 是時間片語，不是被撿起的受詞。", "名詞受詞 the package 可改放成 picked up the package。"], reviews: ["問題鎖定可分片語的名詞受詞。", "第四項是實際受到 picked up 動作的事物。"], cognitiveProcess: ["u29-s201-identify-movable-noun-object-of-picked-up", "distinguish-object-from-subject-verb-time"], representationType: "separable-phrasal-constituent-identification", misconceptionTargets: ["move-time-phrase-as-if-object"] },
    { stem: "The teacher wrote down the new word. Which sentence keeps the same meaning?", options: ["The teacher wrote the new word down.", "The teacher wrote down it the new word.", "The teacher wrote the down new word.", "The teacher down wrote the new word."], answerIndex: 0, reasons: ["名詞受詞可置於 write 與 down 之間。", "it 與名詞重複。", "down 不能插入名詞片語。", "down 不能放在主詞和動詞間。"], reviews: ["the new word 是單一完整名詞片語。", "第一項只使用可分結構的另一種排列。"], cognitiveProcess: ["u29-s201-reorder-wrote-down-new-word-with-noun-middle", "protect-internal-order-of-noun-phrase"], representationType: "separable-phrasal-equivalence", misconceptionTargets: ["split-adjective-from-noun"] },
    { stem: "We are looking forward ___ the school trip.", options: ["the trip to", "to", "it to", "forward the trip to"], answerIndex: 1, reasons: ["受詞不能放在 to 前拆開片語。", "look forward to 後接 the school trip。", "it 與 the trip 會重複，且順序錯誤。", "forward 不能和受詞交換。"], reviews: ["此處 to 是片語的一部分，整組表示期待。", "第二項使名詞受詞留在完整片語後。"], cognitiveProcess: ["u29-s201-keep-look-forward-to-before-trip", "recognize-three-word-inseparable-expression"], representationType: "three-word-inseparable-phrasal", misconceptionTargets: ["separate-look-forward-to"] },
    { stem: "Which pair shows both possible positions for the same noun object?", options: ["Look the dog after. / Look after the dog.", "Wait the bus for. / Wait for the bus.", "Turn the fan off. / Turn off the fan.", "Listen the song to. / Listen to the song."], answerIndex: 2, reasons: ["look after 不可分，第一句錯誤。", "wait for 不可分，第一句錯誤。", "turn off 可分，兩個名詞位置都成立。", "listen to 不可分，第一句錯誤。"], reviews: ["斜線兩側都必須是可接受句子。", "第三項展示同一名詞受詞的兩種位置。"], cognitiveProcess: ["u29-s201-compare-paired-orders-to-find-separable-turn-off", "require-both-members-of-option-to-be-valid"], representationType: "separability-pair-comparison", misconceptionTargets: ["assume-all-two-word-verbs-separable"] },
    { stem: "Ava looked for it under the desk. Why can 'it' stay after 'for'?", options: ["Because every pronoun goes last", "Because 'under the desk' is the object", "Because 'looked' has no object", "Because 'look for' stays together"], answerIndex: 3, reasons: ["代名詞位置取決於片語結構，不是一律句尾。", "under the desk 是地點片語。", "it 正是 look for 的受詞。", "look for 保持相連，it 接在完整片語後。"], reviews: ["題目要求解釋位置，不只選出一句。", "第四項說明不可分結構而未過度推成所有片語。"], cognitiveProcess: ["u29-s201-explain-it-after-for-by-inseparability", "classify-under-desk-as-location-not-object"], representationType: "inseparability-rule-explanation", misconceptionTargets: ["treat-all-pronouns-as-middle"] },
  ]),
  ...skillQuestions("202", [
    { stem: "The computer is still on. Please turn ___ off before you leave.", options: ["it", "them", "off it", "the computer it"], answerIndex: 0, reasons: ["computer 是單數，turn it off 的位置正確。", "them 和單數 computer 不一致。", "代名詞不能放在 off 後。", "名詞與代名詞重複受詞。"], reviews: ["前句提供可由 it 承接的單數事物。", "第一項同時通過指涉和可分片語位置檢查。"], cognitiveProcess: ["u29-s202-complete-turn-it-off-for-computer", "coordinate-singular-reference-with-middle-placement"], representationType: "separable-object-pronoun-cloze", misconceptionTargets: ["place-it-after-off"] },
    { stem: "These books belong on the shelf. Put ___ back after class.", options: ["it", "them", "back them", "these books them"], answerIndex: 1, reasons: ["it 不能指複數 books。", "put them back 把複數代名詞置中。", "them 不應放在 back 後。", "名詞和代名詞重複。"], reviews: ["These books 決定複數代名詞 them。", "第二項表達把書放回原處。"], cognitiveProcess: ["u29-s202-use-them-in-put-back-for-books", "resolve-plural-demonstrative-reference"], representationType: "separable-object-number-agreement", misconceptionTargets: ["use-it-for-plural-object"] },
    { stem: "Use a pronoun for the coin in 'She picked up the coin.'", options: ["She it picked up.", "She picked up it.", "She picked it up.", "She picked the it up."], answerIndex: 2, reasons: ["代名詞不能放在主詞和動詞間。", "可分片語不把 it 留在 up 後。", "picked it up 是正確代名詞位置。", "the 不能和 it 並用成名詞片語。"], reviews: ["coin 已被提到，所以可改成單數 it。", "第三項保留時態並只更換受詞形式。"], cognitiveProcess: ["u29-s202-transform-picked-up-coin-to-picked-it-up", "retain-past-tense-during-pronoun-substitution"], representationType: "separable-object-rewrite", misconceptionTargets: ["retain-determiner-before-pronoun"] },
    { stem: "The address is already known. What can follow 'Please write'?", options: ["down it", "the down address", "it the address down", "it down"], answerIndex: 3, reasons: ["down it 把代名詞放在粒子後。", "down 不能置於冠詞與名詞間。", "it 和 the address 重複。", "write it down 是可分片語的正確順序。"], reviews: ["already known 表示可用代名詞取代 address。", "第四項接在 Please write 後形成完整命令。"], cognitiveProcess: ["u29-s202-complete-write-it-down-from-known-address", "select-only-nonredundant-pronoun-order"], representationType: "separable-object-fragment-completion", misconceptionTargets: ["choose-down-it-order"] },
    { stem: "The coat is on the chair. Please put the coat on before you leave. Which word can stand for 'the coat'?", options: ["it", "them", "its", "itself"], answerIndex: 0, reasons: ["it 可指單數 coat，形成 put it on。", "them 是複數。", "its 是所有格，後面還要名詞。", "itself 是反身代名詞，題幹沒有反身關係。"], reviews: ["coat 是單數事物且已在前文出現。", "第一項代回後也必須移到 put 與 on 中間。"], cognitiveProcess: ["u29-s202-select-it-for-known-singular-coat", "distinguish-object-pronoun-from-possessive-and-reflexive"], representationType: "separable-object-pronoun-form", misconceptionTargets: ["choose-its-as-object"] },
    { stem: "A: Should I leave the signs here? B: No, please take ___ down.", options: ["it", "them", "down it", "the signs them"], answerIndex: 1, reasons: ["it 不符合複數 signs。", "take them down 表示把標示取下。", "down it 的代名詞位置錯誤且數量不合。", "the signs 和 them 不能同時充當同一受詞。"], reviews: ["對話中的 signs 是 B 回應的受詞。", "第二項同時符合複數指涉與 take down 結構。"], cognitiveProcess: ["u29-s202-resolve-dialogue-signs-to-take-them-down", "carry-object-number-across-speaker-turns"], representationType: "separable-object-dialogue-reference", misconceptionTargets: ["lose-plural-reference-across-dialogue"] },
    { stem: "I borrowed two maps from the desk. I must give ___ back tomorrow.", options: ["it", "the desk", "them", "back them"], answerIndex: 2, reasons: ["it 不能指 two maps。", "desk 是來源地點，不是要歸還的東西。", "give them back 正確承接複數 maps。", "代名詞不能留在 back 後。"], reviews: ["borrowed 的受詞 maps 才是之後歸還的物品。", "第三項排除較近但語意不合的 desk。"], cognitiveProcess: ["u29-s202-link-borrowed-maps-to-give-them-back", "reject-nearest-noun-desk-as-wrong-referent"], representationType: "separable-object-reference-chain", misconceptionTargets: ["choose-nearest-noun-as-pronoun-source"] },
    { stem: "Why is 'Turn off it' not used here?", options: ["The verb must be longer.", "The sentence needs two objects.", "The word 'off' must come first.", "The pronoun belongs between 'turn' and 'off'."], answerIndex: 3, reasons: ["動詞長度不是問題。", "被關掉的事物只有一個受詞。", "off 不放在 turn 前。", "可分片語的代名詞受詞應置中。"], reviews: ["錯誤來自受詞位置，不是動詞長度或受詞數量。", "第四項精確說明 turn it off 的結構。"], cognitiveProcess: ["u29-s202-diagnose-turn-off-it-pronoun-position", "exclude-tense-and-valency-as-error-causes"], representationType: "separable-object-error-diagnosis", misconceptionTargets: ["repair-with-off-turn-it"] },
    { stem: "Put the clean cups away before lunch. Which sentence uses a pronoun?", options: ["Put them away before lunch.", "Put away before lunch them.", "Put they away before lunch.", "Put their away before lunch."], answerIndex: 0, reasons: ["them 是複數受格，且放在 put 與 away 間。", "時間片語和代名詞位置都被打亂。", "they 是主格。", "their 是所有格，需接名詞。"], reviews: ["clean cups 是複數受詞，不是句子主詞。", "第一項保留 before lunch 的時間功能。"], cognitiveProcess: ["u29-s202-replace-clean-cups-with-them-in-put-away", "choose-object-case-while-preserving-adjunct"], representationType: "separable-object-case-and-order", misconceptionTargets: ["use-subject-pronoun-as-object"] },
    { stem: "The team set up a table near the door. Which shorter form points to the table?", options: ["set up them", "set it up", "set its up", "set up itself"], answerIndex: 1, reasons: ["them 不符合單數且位置不合。", "set it up 正確指回單數 table。", "its 是所有格，不能單獨作受詞。", "itself 會改成反身意思且位置仍不合。"], reviews: ["near the door 是地點，不改變 table 的單數指涉。", "第二項以最短形式保留原動作。"], cognitiveProcess: ["u29-s202-shorten-set-up-table-to-set-it-up", "ignore-location-phrase-when-resolving-object"], representationType: "separable-object-concision", misconceptionTargets: ["use-possessive-pronoun-in-object-slot"] },
    { stem: "The two jackets are too warm. Which sentence points to both jackets?", options: ["Take it off.", "Take off it.", "Take them off.", "Take off them."], answerIndex: 2, reasons: ["it 只指單數。", "it 數量不合且位置錯。", "them 指兩件外套，置於 take 與 off 間。", "them 不應放在 off 後。"], reviews: ["both jackets 強制使用複數代名詞。", "第三項是唯一在數量和位置上都正確的要求。"], cognitiveProcess: ["u29-s202-select-take-them-off-for-two-jackets", "evaluate-number-and-separation-jointly"], representationType: "separable-object-dual-constraint", misconceptionTargets: ["fix-number-but-not-position"] },
    { stem: "A long list of names is on the screen. Which sentence avoids repeating the list?", options: ["Copy down it.", "Copy its down.", "Copy down them.", "Copy it down."], answerIndex: 3, reasons: ["it 應放在 copy 與 down 間。", "its 是所有格。", "核心名詞 list 是單數，不用 them，位置也錯。", "copy it down 正確以 it 指回整份清單。"], reviews: ["of names 不會把核心 list 變成複數。", "第四項同時處理主從名詞數量和可分位置。"], cognitiveProcess: ["u29-s202-resolve-long-list-head-noun-to-copy-it-down", "ignore-plural-of-phrase-for-pronoun-number"], representationType: "separable-object-head-noun", misconceptionTargets: ["agree-pronoun-with-nearest-plural-noun"] },
  ]),
  ...skillQuestions("203", [
    { stem: "The doctor said I should ___ this medicine after dinner.", options: ["take", "eat", "drink", "use up"], answerIndex: 0, reasons: ["take medicine 是服藥的常見搭配。", "中文可說吃藥，但英文不以 eat 表一般服藥。", "藥不一定是液體，題幹也沒有說明喝。", "use up 表示用完，改變醫師指示。"], reviews: ["after dinner 是服用時間，不是藥物形態。", "第一項不從中文動詞逐字翻譯。"], cognitiveProcess: ["u29-s203-select-take-medicine-after-doctor-instruction", "reject-literal-eat-and-unstated-liquid-form"], representationType: "natural-collocation-medicine", misconceptionTargets: ["translate-eat-medicine"] },
    { stem: "The road was closed after the ___ last night.", options: ["big rain", "heavy rain", "large rain", "high rain"], answerIndex: 1, reasons: ["big rain 是依中文大小直譯的不自然組合。", "heavy rain 是大雨的自然搭配。", "large 通常描述尺寸或數量，不直接修飾 rain。", "high 不用來表示雨勢強。"], reviews: ["road was closed 提供強降雨造成影響的情境。", "第二項使用英語慣用強度形容詞。"], cognitiveProcess: ["u29-s203-replace-big-rain-with-heavy-rain", "map-weather-intensity-to-natural-adjective"], representationType: "natural-collocation-weather", misconceptionTargets: ["translate-big-rain"] },
    { stem: "We sat at the table and ___ breakfast together.", options: ["did", "built", "had", "held"], answerIndex: 2, reasons: ["do breakfast 不是用餐搭配。", "build 表建造，不合。", "have breakfast 表示吃早餐。", "hold breakfast 不是此日常用餐說法。"], reviews: ["sat at the table 和 together 建立共同用餐情境。", "第三項不把 breakfast 當成製作物或活動場地。"], cognitiveProcess: ["u29-s203-select-had-breakfast-at-table", "distinguish-meal-consumption-from-making-event"], representationType: "natural-collocation-meal", misconceptionTargets: ["translate-do-breakfast"] },
    { stem: "My brother can ___ the piano very well.", options: ["touch", "hit", "make", "play"], answerIndex: 3, reasons: ["touch 只表示碰觸樂器。", "hit 不是一般演奏鋼琴的說法。", "make 不表示演奏。", "play the piano 是演奏鋼琴的常見形式。"], reviews: ["can 與 very well 顯示在談演奏能力。", "第四項也保留樂器前的 the。"], cognitiveProcess: ["u29-s203-select-play-the-piano-for-ability", "separate-performance-from-physical-contact"], representationType: "natural-collocation-instrument", misconceptionTargets: ["omit-the-before-instrument"] },
    { stem: "If the directions are not clear, please ___ a question.", options: ["ask", "say", "speak", "tell"], answerIndex: 0, reasons: ["ask a question 表示提問。", "say 後不直接接 a question 表此意。", "speak 不使用這個受詞搭配。", "tell a question 不是自然說法。"], reviews: ["not clear 是需要提問澄清的原因。", "第一項選擇英語中和 question 搭配的動詞。"], cognitiveProcess: ["u29-s203-select-ask-question-to-clarify-directions", "reject-say-speak-tell-by-complement-frame"], representationType: "natural-collocation-question", misconceptionTargets: ["translate-say-a-question"] },
    { stem: "Before bed, the father often ___ his child a short story.", options: ["speaks", "tells", "talks", "says"], answerIndex: 1, reasons: ["speak 不使用 story 作此直接受詞。", "tell someone a story 是講故事給某人聽。", "talk 通常需介系詞，不形成 talk a story。", "say 不能直接採雙受詞 child a story。"], reviews: ["his child 是聽者，a short story 是內容。", "第二項符合 tell 的雙受詞結構。"], cognitiveProcess: ["u29-s203-select-tells-child-story-before-bed", "match-tell-to-listener-and-content-objects"], representationType: "natural-collocation-story", misconceptionTargets: ["use-say-someone-a-story"] },
    { stem: "It is safer to ___ a bike in the park than on this busy road.", options: ["drive", "sit", "ride", "run"], answerIndex: 2, reasons: ["drive 常用於汽車等車輛，不是一般自行車搭配。", "sit 只描述坐姿，未表移動。", "ride a bike 表示騎自行車。", "run a bike 不表示騎乘。"], reviews: ["park 和 busy road 建立騎車地點的安全比較。", "第三項是 bicycle 活動的自然動詞。"], cognitiveProcess: ["u29-s203-select-ride-bike-in-safety-comparison", "distinguish-bike-verb-from-car-driving"], representationType: "natural-collocation-transport", misconceptionTargets: ["translate-drive-a-bike"] },
    { stem: "I cannot read the board without my glasses, so I always ___ them in class.", options: ["dress", "put", "carry on", "wear"], answerIndex: 3, reasons: ["dress 的受詞通常是人，不能直接表示戴眼鏡狀態。", "put 需有位置或使用 put on 才完整。", "carry on 是繼續，不表示戴著。", "wear glasses 表示眼鏡在身上的持續狀態。"], reviews: ["always 和 in class 描述一段持續習慣。", "第四項符合眼鏡在使用中的狀態。"], cognitiveProcess: ["u29-s203-select-wear-glasses-for-classroom-state", "separate-wear-state-from-put-on-action"], representationType: "natural-collocation-clothing-state", misconceptionTargets: ["use-dress-glasses"] },
    { stem: "Joining the art club helped me ___ new friends.", options: ["make", "build", "create", "produce"], answerIndex: 0, reasons: ["make friends 表示和別人成為朋友。", "build friends 把人際關係逐字當建築。", "create friends 不是此日常表達。", "produce 常指製造產品或結果，不指交朋友。"], reviews: ["joining the club 提供認識同伴的機會。", "第一項是整體搭配，不是實際製造人物。"], cognitiveProcess: ["u29-s203-select-make-friends-through-club", "reject-literal-creation-verbs-for-relationships"], representationType: "natural-collocation-relationship", misconceptionTargets: ["read-make-friends-literally"] },
    { stem: "This place is beautiful. Could you ___ a picture for us?", options: ["do", "take", "catch", "hold"], answerIndex: 1, reasons: ["do a picture 不表示拍照。", "take a picture 是拍攝照片。", "catch a picture 不是一般拍照搭配。", "hold a picture 表拿著現有照片。"], reviews: ["beautiful place 是提出拍照請求的原因。", "第二項表示產生照片，而非拿著一張照片。"], cognitiveProcess: ["u29-s203-select-take-picture-of-beautiful-view", "distinguish-photographing-from-holding-existing-photo"], representationType: "natural-collocation-photography", misconceptionTargets: ["translate-do-a-picture"] },
    { stem: "We should ___ more time checking the facts before sharing the news.", options: ["pay", "cost", "spend", "make"], answerIndex: 2, reasons: ["pay 不能直接帶 time 表示花時間。", "cost 的主詞通常是事物，不能由 we 主動花費。", "spend time checking 是花時間做某事的自然結構。", "make time 後通常接 for，不直接採此結構。"], reviews: ["checking 是人如何運用時間的活動。", "第三項符合 spend + time + V-ing。"], cognitiveProcess: ["u29-s203-select-spend-time-checking-facts", "coordinate-agent-subject-with-time-gerund-frame"], representationType: "natural-collocation-time-use", misconceptionTargets: ["use-cost-with-person-subject"] },
    { stem: "Children should ___ their teeth before going to bed.", options: ["wash", "clean up", "make", "brush"], answerIndex: 3, reasons: ["wash teeth 不是一般刷牙搭配。", "clean up 通常整理空間或收拾，不直接接 teeth。", "make teeth 不合。", "brush one's teeth 表示刷牙。"], reviews: ["before going to bed 是常見口腔清潔情境。", "第四項選擇專用動詞，而不是中文『洗』的直譯。"], cognitiveProcess: ["u29-s203-select-brush-teeth-before-bed", "replace-general-cleaning-translation-with-specific-verb"], representationType: "natural-collocation-daily-care", misconceptionTargets: ["translate-wash-teeth"] },
  ]),
];

export const ENGLISH_UNIT_SOURCE = {
  unitId: UNIT_ID,
  lectures: ENGLISH_U29_LECTURES,
  questions: ENGLISH_U29_QUESTIONS,
  vocabularyPolicy: {
    capQuestionBasis: "appendix-5-table-1",
    additionalLearningTerms: ["address", "advice", "attention", "avoid", "board", "cancel", "childhood", "coach", "coin", "continue", "create", "decision", "describe", "direction", "empty", "form", "forward", "goal", "guide", "hall", "information", "message", "object", "path", "position", "produce", "promise", "return", "safety", "scientist", "search", "shelf", "solve", "step", "storm", "stove", "sudden", "travel", "usual", "weekday"],
    properNames: ["Ava", "Lena", "Maya", "Noah", "Ryan"],
    grammarNotation: ["A", "B", "adjective", "adverb", "collocation", "imperative", "ing", "inseparable", "noun", "object", "particle", "phrasal", "phrase", "pronoun", "separable", "V", "verb"],
    malformedDistractors: [],
  },
};
