import { defineChoiceQuestions as questions, defineEnglishUnit } from "../define-unit.mjs";

const skills = [
  {
    id: "ENG_R4_S267", process: "infer-author-purpose", evidence: "文體、內容安排與讀者預期行動共同指向的寫作目的",
    objectives: ["辨認告知、說明、勸說、指示、請求與娛樂等目的。", "以全文功能而非單一關鍵字判斷。", "區分文章主題與作者寫作目的。"],
    sections: [
      ["主題不是目的", "文章談 recycling 是主題；作者可能要說明分類方法、勸大家參加，或報告活動結果。目的要用『作者想讓讀者知道、相信或做什麼』回答。"],
      ["文體提供第一線索", "步驟與命令常在指示；日期、地點與報名方式常在公告；理由與行動呼籲常在勸說；人物、衝突與結局常以娛樂或分享經驗為主。"],
      ["看讀者讀完後要怎樣", "若讀完應能完成一項操作，目的多為 instruct；若應改變選擇或參加活動，常為 persuade；若只是取得事實，則為 inform。"],
      ["全文功能優先", "一篇勸說文也會含事實，一篇故事也可能教人。選能概括主要結構與結尾行動的目的，不因一句資料就改判。"],
    ],
    examples: [
      ["First wash the cup. Next place it upside down. Finally leave it to dry.", ["有順序詞。", "每句是可執行動作。", "讀者能完成清洗。"], "to explain how to clean a cup", "不是介紹杯子歷史。"],
      ["Join the park clean-up this Saturday. Your help can make the river safer.", ["有 join 呼籲。", "提供參與理由。", "希望讀者採取行動。"], "to persuade people to join", "日期服務行動呼籲。"],
      ["The report lists visitor numbers for three months.", ["內容是資料。", "無命令或評價。", "目的為告知趨勢。"], "to inform readers about visitor numbers", "不是要求讀者參觀。"],
    ],
    misconceptions: [
      ["提到日期就是告知。", "公告可用日期服務邀請。", "看全文希望讀者採取的行動。"],
      ["有一個事實就不是勸說。", "勸說常用事實作理由。", "判斷主要功能。"],
      ["主題名稱可直接當目的。", "主題只回答談什麼。", "加入作者想達成的效果。"],
      ["故事一定只有娛樂。", "也可能分享經驗或教訓。", "用結尾與結構決定主要目的。"],
    ],
    checks: [
      ["purpose 題要回答談什麼還是為何寫？", "為何寫", "主題與目的不同。"],
      ["步驟與命令最常對應哪種目的？", "指示做法", "讀者可照文操作。"],
      ["勸說文可包含事實嗎？", "可以", "事實可作說服理由。"],
    ],
    questions: questions([
      ["Bring your own cup to Green Cafe this Friday. Each reusable cup keeps one plastic cup out of the waste bin. Why was this message written?", "to encourage customers to bring reusable cups", "命令 Bring 與減廢理由共同形成行動呼籲。", [["to explain how plastic cups are made", "沒有製造步驟。"], ["to report Friday's sales", "沒有銷售數據。"], ["to entertain readers with a cafe story", "沒有故事情節。"]]],
      ["To reset the clock, hold the blue button for three seconds. When the numbers flash, press the hour button. What is the writer's purpose?", "to give instructions for resetting a clock", "順序動作讓讀者完成 reset。", [["to compare two clocks", "沒有比較。"], ["to sell a blue button", "button 是操作部件。"], ["to describe the history of time", "沒有歷史內容。"]]],
      ["The town opened two new bus stops in June. Daily riders increased from 800 to 950 by August. Why was this report written?", "to inform readers about a bus-service change and its result", "提供開站與乘客數的客觀資訊。", [["to ask readers to drive less tomorrow", "沒有請求或 tomorrow。"], ["to teach how to build a bus stop", "沒有建造步驟。"], ["to tell a funny travel story", "沒有角色衝突或幽默。"]]],
      ["Nora followed a sound through the rain and found a lost puppy under the bridge. She carried it home, where its owner was waiting. Why was this passage written?", "to tell a short story about finding a lost puppy", "人物、搜尋、發現與團聚構成敘事。", [["to list rules for owning dogs", "沒有規則清單。"], ["to advertise a bridge", "bridge 只是場景。"], ["to explain why all puppies fear rain", "沒有普遍說明。"]]],
      ["Our reading room needs brighter lights. Last month's survey found that 72% of students avoid it after four. Please support the new-light plan. What is the main purpose?", "to persuade readers to support better lighting", "資料作理由，結尾 Please support 明示訴求。", [["to define the word survey", "沒有定義。"], ["to announce that the plan is finished", "仍在尋求 support。"], ["to describe every room in the school", "只談 reading room。"]]],
      ["School Garden Day: April 20, 9 a.m.–noon. Meet at the east gate. Bring a hat and water. What is the purpose?", "to announce practical information for an event", "標題、日期、集合地與攜帶物提供參加資訊。", [["to review last year's garden", "沒有過去結果。"], ["to prove gardening is easy", "沒有論證。"], ["to teach how seeds grow", "沒有生長機制。"]]],
      ["This article explains that bees carry material from one flower to another, helping many plants form fruit. Why was it written?", "to explain how bees help plants", "內容說明過程與作用。", [["to ask readers to buy fruit", "沒有購買呼籲。"], ["to warn that every bee is dangerous", "與 help plants 主旨不合。"], ["to tell where one bee slept", "不是個別故事。"]]],
      ["Could each family send one clean coat by November 10? The center has requests from forty children. Why did the center write this?", "to request coat donations", "問句請求 send a coat，兒童需求是理由。", [["to return coats to families", "方向相反。"], ["to compare coat prices", "沒有價格。"], ["to explain winter weather", "天氣不是內容核心。"]]],
      ["The museum's new evening hours are 5–9 p.m. on Fridays. All other hours remain the same. What is the purpose?", "to notify visitors of a schedule change", "精確說明 Friday 新時段與其他不變。", [["to convince the museum to close", "沒有勸說。"], ["to describe an evening painting", "hours 不是 artwork。"], ["to teach visitors to read a clock", "沒有教學步驟。"]]],
      ["Mix the soil with old leaves, add a little water, and turn it once a week. After two months, use it in the garden. Why was this written?", "to show how to make material for garden soil", "命令與時間順序提供製作方法。", [["to sell bags of soil", "沒有價格或購買。"], ["to report a garden contest", "沒有比賽。"], ["to argue that leaves are useless", "原文利用 leaves。"]]],
      ["The writer describes three benefits of walking to school, then ends with 'Try it once this week.' What is the main purpose?", "to encourage students to try walking to school", "好處加直接行動呼籲構成勸說。", [["to measure every student's walking speed", "沒有測量。"], ["to give the history of schools", "沒有歷史。"], ["to announce that buses have stopped", "沒有此消息。"]]],
      ["A note explains that the river path will close for repairs from May 3 to May 6 and gives a safe alternate route. Why was it written?", "to warn users of a closure and guide them around it", "關閉日期與 alternate route 服務安全通行。", [["to invite users to repair the path", "沒有招募。"], ["to praise the longest route", "沒有評價或長度比較。"], ["to describe how rivers form", "不是自然科說明。"]]],
    ], { type: "author-purpose", operation: "match-genre-and-reader-action", misconception: "confuse-topic-with-purpose" }),
  },
  {
    id: "ENG_R4_S268", process: "infer-intended-audience", evidence: "稱呼、先備資訊、媒介與讀者可採取的行動",
    objectives: ["由稱呼與第二人稱辨認直接讀者。", "利用資訊深淺與可執行動作縮小讀者群。", "區分文中提到的人與文章真正寫給的人。"],
    sections: [
      ["被提到不等於被寫給", "A note to parents may discuss students，學生是內容對象，但 parents 才是收件者。先找 Dear、To、Attention 或媒介位置。"],
      ["誰能採取文中行動", "若訊息請 bring your library card，預期讀者是到館借書者；若請 sign your child's form，則是家長。行動能力是強線索。"],
      ["先備知識也能定位", "給新生的文字會解釋基本地點；給工作人員的通知可能直接使用 staff room、shift 等內部資訊。看作者假設讀者已知什麼。"],
      ["範圍不要過廣", "公告貼在 one class 且稱 Class 8A，就不能答 all people in the city。選最小且完整涵蓋的讀者群。"],
    ],
    examples: [
      ["Dear parents, please sign your child's trip form.", ["直接稱 parents。", "行動是 sign child's form。", "讀者不是 child。"], "parents of the students", "students 被提到但不是執行簽名者。"],
      ["Staff notice: Leave keys at the front desk after your shift.", ["標題 Staff notice。", "shift 是工作情境。", "員工可交 keys。"], "staff members", "不是一般 visitors。"],
      ["Welcome, new students. Your first class is in Room 2.", ["稱 new students。", "提供基礎位置。", "行動是到第一堂課。"], "new students", "不是教師或畢業生。"],
    ],
    misconceptions: [
      ["文章提到誰就寫給誰。", "內容對象與讀者可不同。", "找稱呼與預期行動。"],
      ["任何公開公告都寫給 everyone。", "地點與條件可限定讀者。", "選最小適切群體。"],
      ["只看一個人名。", "人名可能是作者或例子。", "結合媒介、稱呼與行動。"],
      ["讀者一定已知道文中所有資訊。", "作者提供的解釋反映其先備假設。", "看哪些內容被特別說明。"],
    ],
    checks: [
      ["Dear parents 最直接指誰？", "家長", "稱呼是強證據。"],
      ["能執行文中要求的人可幫助判斷什麼？", "預期讀者", "行動與角色相配。"],
      ["讀者答案應選最廣還是最小適切範圍？", "最小適切範圍", "避免過度擴張。"],
    ],
    questions: questions([
      ["Dear families, please check your child's lunch choice and return the form tomorrow. Who is the message for?", "parents or guardians of students", "稱 families 且要求處理 child's form。", [["restaurant cooks", "他們不簽 child's form。"], ["all city residents", "範圍過廣。"], ["children without adults", "要求由家庭監護者確認。"]]],
      ["Staff only: Record the room temperature at the start of your shift. Who should read this?", "employees working a shift", "Staff only 與 your shift 直接限定。", [["museum visitors", "visitors 沒有 shift。"], ["school children", "未被稱 staff。"], ["anyone checking weather", "room record 不是公開天氣。"]]],
      ["Welcome to Hill School! New students should meet their class guide by the blue gate. Who is the audience?", "new students at Hill School", "Welcome 與 New students 直接稱呼。", [["experienced teachers", "不是 new students。"], ["every student in the country", "限定 Hill School。"], ["bus drivers", "沒有駕駛行動。"]]],
      ["To bike riders: The river path is closed after 6 p.m. Please use Green Street. Who needs this notice most?", "people planning to ride bikes on the river path", "To bike riders、path 與 alternate street 精確限定。", [["people swimming in the river", "不是 path riders。"], ["all drivers in town", "範圍過廣且媒介不同。"], ["workers repairing every road", "通知是給使用者。"]]],
      ["Library email: Your reserved book is ready. Bring your card to Desk 2 by Friday. Who is the intended reader?", "the person who reserved the book", "your reserved book 與 bring your card 指向該借閱者。", [["all library workers", "worker 不是取 reserved book 的讀者。"], ["anyone who owns a book", "需有特定 reservation。"], ["the book's writer", "作者不是取書者。"]]],
      ["Class 8A: Upload your final poster before nine tonight. Who is this for?", "students in Class 8A", "直接稱 Class 8A 且要求 upload assignment。", [["all school families", "範圍過廣。"], ["poster shop owners", "不是課堂提交者。"], ["students in every grade", "只限定 8A。"]]],
      ["Coach's message: Players should bring both team shirts to Saturday's game. Who should act on it?", "members of the team", "Players 與 team shirts 指向隊員。", [["people buying tickets", "觀眾不帶 team shirts。"], ["all coaches", "coach 是發訊者。"], ["shirt makers", "沒有製作要求。"]]],
      ["Notice inside a hotel room: Dial 0 if you need another towel. Who is the audience?", "hotel guests staying in the room", "媒介在 room 且 need towel 是住宿者需求。", [["hotel owners only", "不是主要使用房內通知者。"], ["people calling from home", "不在房間情境。"], ["all travelers everywhere", "限定該 hotel room。"]]],
      ["Dear volunteers, meet at the food center at 8:30 and wear your name card. Who is addressed?", "people volunteering at the food center", "Dear volunteers 與集合要求明示。", [["families receiving food", "他們是服務對象，不是 volunteers。"], ["every person with a name", "name card 不是唯一線索，稱呼已限定。"], ["center customers", "沒有購買。"]]],
      ["Parents of Grade 7: The meeting about next year's classes begins at seven. Who is expected to attend?", "parents of Grade 7 students", "標題直接限定家長與年級。", [["Grade 7 students only", "稱呼 parents。"], ["parents of every child in town", "範圍超出 Grade 7。"], ["next year's teachers only", "內容關於 classes，不等於教師收件者。"]]],
      ["A label says: 'For adults: Take one tablet after dinner. Keep away from children.' Who is the instruction for?", "adults using the medicine", "For adults 明示服用者，children 是需遠離的群體。", [["children", "標籤明說 keep away。"], ["restaurant servers", "after dinner 只是服用時間。"], ["all medicine makers", "不是製造說明。"]]],
      ["Attention passengers on Train 306: Please move to Platform 4. Who is the announcement for?", "people taking Train 306", "Attention passengers on Train 306 精確限定。", [["all train passengers", "只有 306 需 move。"], ["platform workers only", "行動者是 passengers。"], ["people arriving by bus", "媒介是 train。"]]],
    ], { type: "intended-audience", operation: "match-address-and-reader-action", misconception: "confuse-mentioned-person-with-reader" }),
  },
  {
    id: "ENG_R4_S269", process: "infer-narrator-attitude", evidence: "評價形容詞、副詞、選取細節與比較共同顯示的態度",
    objectives: ["圈出 positive、negative 或保留態度的評價詞。", "區分敘述內容與敘述者對內容的看法。", "選擇強度與證據一致的態度描述。"],
    sections: [
      ["態度藏在選字", "fortunately、wasteful、helpful、disappointing 都直接帶評價。即使作者未說 I think，這些字仍顯示立場。"],
      ["細節選取也有方向", "同一活動可寫 friendly helpers and clear signs，或寫 long lines and confusing rules。作者反覆選哪些面向，會形成整體態度。"],
      ["態度不是主題", "文章談 a new park，態度可能 supportive、critical、mixed 或 neutral。答案需描述作者如何看它。"],
      ["控制強度", "concerned 不等於 furious，pleased 不等於 calling it perfect。選最小但充分符合評價詞的描述。"],
    ],
    examples: [
      ["Fortunately, the new signs are clear and easy to follow.", ["fortunately 正面。", "clear/easy 正面。", "態度 supportive。"], "pleased with the signs", "不需推到 excited beyond measure。"],
      ["The costly plan solved only one small problem.", ["costly 負擔。", "only one small 限縮成效。", "態度 critical。"], "doubtful or critical", "不是 neutral。"],
      ["The room is bright and useful, though it can be noisy.", ["有正面與負面。", "though 加限制。", "態度 mixed。"], "mostly positive but qualified", "不能只選 completely negative。"],
    ],
    misconceptions: [
      ["只要報告事實就一定 neutral。", "評價詞可夾在事實中。", "圈出帶價值的用字。"],
      ["出現一個缺點就 completely negative。", "全文可能同時肯定。", "衡量正負證據比例與轉折。"],
      ["作者態度等於讀者感受。", "題目問的是文本呈現的作者立場。", "回到作者選字。"],
      ["強烈選項比較像答案。", "態度強度需有同等證據。", "採最小充分描述。"],
    ],
    checks: [
      ["fortunately 帶正面還是負面態度？", "正面", "表示作者認為結果幸運。"],
      ["有優點也有缺點可能是何種態度？", "mixed 或 qualified", "不宜絕對化。"],
      ["concerned 能直接改成 furious 嗎？", "不能", "強度被誇大。"],
    ],
    questions: questions([
      ["The new path is a welcome change: it is safer, clearer, and easier for families to use. What is the writer's attitude?", "strongly positive", "welcome、safer、clearer、easier 都一致正面。", [["angry", "沒有憤怒詞。"], ["uncertain", "作者給出明確肯定。"], ["uninterested", "多項評價顯示投入。"]]],
      ["The plan is expensive and helps only a few riders. The town should examine better choices. What is the attitude?", "critical of the plan", "expensive、only a few、better choices 都質疑現方案。", [["fully supportive", "與批評詞相反。"], ["neutral", "should examine better choices 是立場。"], ["amused", "沒有幽默。"]]],
      ["The cafe is comfortable and the workers are kind, although the wait can be long. How does the narrator view it?", "mostly positively, with one concern", "兩項優點後以 although 加一缺點。", [["completely negative", "忽略 comfort/kind。"], ["perfect in every way", "long wait 否定 perfect。"], ["without any opinion", "評價詞明顯。"]]],
      ["Sadly, the old trees were removed before another plan was discussed. What attitude is shown?", "regretful", "Sadly 與未先討論呈現遺憾。", [["delighted", "與 sadly 相反。"], ["neutral", "Sadly 是明確評價。"], ["confused about what a tree is", "沒有概念困惑。"]]],
      ["At last, the town has repaired the dangerous crossing. This overdue work will protect walkers. What is the attitude?", "relieved but critical of the delay", "At last/overdue 批延誤，protect 肯定完成。", [["opposed to the repair", "作者肯定 protect walkers。"], ["fully neutral", "overdue 帶批評。"], ["certain the crossing was always safe", "dangerous 與此相反。"]]],
      ["The tiny garden may look simple, but it gives the neighborhood color, food, and a place to meet. What attitude?", "appreciative", "but 後列三項價值，肯定小花園。", [["dismissive", "作者未因 tiny/simple 否定價值。"], ["fearful", "沒有危險。"], ["unaware of the garden", "描述具體功能。"]]],
      ["Unfortunately, the update removed the easiest way to find saved work. What attitude?", "disappointed with the update", "Unfortunately 與 removed easiest way 是負面評價。", [["excited by it", "方向相反。"], ["neutral about it", "Unfortunately 不 neutral。"], ["proud of writing the update", "作者身份未提。"]]],
      ["The museum's effort is useful, but the small print still leaves many visitors out. What is the attitude?", "supportive of the effort but concerned about access", "useful 肯定，but 後指出 print 問題。", [["the museum is perfect", "small print 問題未解。"], ["the effort has no value", "與 useful 相反。"], ["the writer has no view", "評價清楚。"]]],
      ["What a clever solution! The folding seats create space without removing the tables. What is the attitude?", "impressed", "感嘆與 clever 明確讚賞。", [["bored", "語氣投入。"], ["worried", "沒有風險詞。"], ["hostile", "與稱讚相反。"]]],
      ["Calling this a complete success is too early; the test included only ten people. What is the attitude?", "cautious and doubtful", "too early 與 small sample 限制結論。", [["certain of complete success", "作者直接否定此確定性。"], ["joyful", "沒有慶祝。"], ["angry at the ten people", "批評的是結論強度。"]]],
      ["The writer calls the service 'reliable on every rainy morning' and thanks its patient drivers. What attitude?", "grateful and positive", "reliable、thanks、patient 都正面。", [["suspicious", "沒有懷疑。"], ["critical", "沒有負面評價。"], ["indifferent", "thanks 顯示態度。"]]],
      ["The old market is crowded and noisy, yet its energy and friendly sellers make every visit enjoyable. What attitude?", "positive despite some drawbacks", "yet 後 enjoyment 是主要評價，保留 crowded/noisy。", [["entirely negative", "忽略 enjoyable。"], ["the market has no drawbacks", "前半明示兩項。"], ["neutral and factual", "enjoyable/friendly 帶評價。"]]],
    ], { type: "narrator-attitude", operation: "weigh-evaluative-language", misconception: "choose-overstrong-attitude" }),
  },
  {
    id: "ENG_R4_S270", process: "infer-speaker-emotion", evidence: "語調標記、內容、標點與對方回應共同顯示的當下情緒",
    objectives: ["從感嘆、停頓、反問與回應推論情緒。", "區分說話內容與說話者感受。", "避免只靠單一驚嘆號判斷過強情緒。"],
    sections: [
      ["內容先於標點", "驚嘆號可表喜悅、驚訝、憤怒或警告。先讀說了什麼，再用標點調整強度。"],
      ["回應能確認語調", "A 說 I lost the key again，B 回 Don't worry，顯示 A 可能焦急或挫折。對方的安慰、祝賀或道歉是重要證據。"],
      ["停頓與修正", "Well...、I guess、maybe 常顯示猶豫；At last!、We did it! 常顯示如釋重負或興奮。仍要結合事件。"],
      ["採最小充分情緒", "若只支持 worried，就不要升成 terrified；若說話者既驚訝又高興，可選 pleasantly surprised，而非單一極端。"],
    ],
    examples: [
      ["A: I can't find my ticket. B: Stay calm; we'll check your bag.", ["A 遺失入場物。", "B 說 stay calm。", "推出 worried。"], "worried", "不是 bored。"],
      ["We finished before the rain—what a relief!", ["有壓力事件。", "成功避雨。", "relief 明示。"], "relieved", "可帶高興但核心是放心。"],
      ["Well... I may need more time.", ["Well 與省略號。", "may 弱化。", "顯示 hesitant。"], "hesitant", "不是 confidently refusing。"],
    ],
    misconceptions: [
      ["驚嘆號一定是生氣。", "也可表喜悅或警告。", "先讀內容。"],
      ["只看第一位說話者。", "對方回應可確認情緒。", "讀完整對話。"],
      ["worry 可以直接推成 terror。", "強度需有額外證據。", "選最小充分情緒。"],
      ["猶豫等於拒絕。", "可能尚未決定。", "保留不確定程度。"],
    ],
    checks: [
      ["Stay calm 常回應哪類情緒？", "緊張或擔心", "安撫語確認。"],
      ["Well... may 顯示什麼？", "猶豫或不確定", "語氣被弱化。"],
      ["驚嘆號能單獨決定情緒嗎？", "不能", "需配合內容。"],
    ],
    questions: questions([
      ["A: The final bus left five minutes ago! B: Don't panic. We can call a taxi. How does A likely feel?", "worried", "錯過末班車且 B 說 Don't panic。", [["relaxed", "與 panic 回應不合。"], ["proud", "沒有成就。"], ["amused", "交通困境無幽默線索。"]]],
      ["A: We found the lost dog! B: That's wonderful news. How does A sound?", "excited and relieved", "找到失犬、驚嘆號與 wonderful 共同支持。", [["disappointed", "與 found/wonderful 相反。"], ["uncertain whether a dog exists", "A 明確宣告 found。"], ["angry with B", "沒有衝突。"]]],
      ["A: Well... I'm not sure the box will fit. B: We can measure it again. How does A feel?", "uncertain", "Well...、not sure 與重新測量支持不確定。", [["completely confident", "與 not sure 相反。"], ["joyful", "沒有好消息。"], ["furious", "沒有強烈負面語言。"]]],
      ["A: You remembered my birthday! B: Of course. How does A most likely feel?", "pleasantly surprised", "反問式驚嘆顯示意外且正面。", [["offended", "沒有被冒犯線索。"], ["bored", "語氣投入。"], ["afraid", "沒有危險。"]]],
      ["A: I studied all week, but I missed passing by one point. B: I'm sorry. How does A likely feel?", "disappointed", "努力後差一分，B 表同情。", [["satisfied", "與 missed passing 不合。"], ["carefree", "投入一週且結果失落。"], ["excited", "不是成功消息。"]]],
      ["A: At last, the power is back. B: Now we can finish the work. What emotion does At last show?", "relief", "等待供電恢復後終於可工作。", [["confusion", "事件清楚。"], ["anger at finishing", "沒有抱怨工作。"], ["fear of electricity", "沒有危險語言。"]]],
      ["A: Could you maybe check this answer once more? B: Sure. How does A sound?", "polite and somewhat unsure", "Could、maybe、once more 是委婉請求與不確定。", [["commanding and angry", "語氣非命令。"], ["certain the answer is right", "要求再查顯示保留。"], ["uninterested", "主動請求檢查。"]]],
      ["A: Watch out—the floor is wet! B: Thanks for the warning. What is A's tone?", "urgent and cautioning", "Watch out、wet floor 與 warning 明示警急提醒。", [["playful", "安全風險不支持玩笑。"], ["sleepy", "沒有疲累。"], ["thankful", "B 才是道謝者。"]]],
      ["A: Another hour in line? This is getting ridiculous. B: I know; the wait is terrible. How does A feel?", "frustrated", "反問、ridiculous 與 B 同意 wait terrible。", [["delighted", "與抱怨相反。"], ["calmly neutral", "評價強烈。"], ["proud of the line", "沒有成就。"]]],
      ["A: I... I didn't expect everyone to clap. B: You gave a great talk. How does A sound?", "surprised and shy", "停頓、didn't expect 與稱讚情境支持。", [["angry at the audience", "clap 是正面。"], ["certain of the reaction", "與 didn't expect 相反。"], ["bored by the talk", "A 是講者且回應驚訝。"]]],
      ["A: If you prefer, we could try the other route. B: Either way is fine. What is A's tone?", "considerate", "提供選擇並尊重 prefer。", [["threatening", "沒有威脅。"], ["impatient", "語氣給予彈性。"], ["confused about all routes", "A 能提出明確替代。"]]],
      ["A: I can't believe the little plant has six flowers already! B: Your care worked. What emotion is strongest?", "delighted amazement", "can't believe、already、驚嘆號與成功結果表正面驚喜。", [["sadness", "花開與 care worked 是好結果。"], ["fear", "沒有威脅。"], ["doubt that the plant exists", "驚訝的是花數，不是否定存在。"]]],
    ], { type: "dialogue-emotion", operation: "combine-utterance-and-response", misconception: "judge-emotion-from-punctuation-alone" }),
  },
  {
    id: "ENG_R4_S271", process: "distinguish-fact-and-opinion", evidence: "陳述能否由可查資料驗證，或包含個人評價與偏好",
    objectives: ["辨認可由日期、數量、紀錄驗證的事實陳述。", "辨認 best、beautiful、should 等評價與建議。", "分開『有證據的意見』與『事實』。"],
    sections: [
      ["事實可查真偽", "The park opened in 2024 可查紀錄，無論目前是否知道答案，它仍是事實型陳述。"],
      ["意見含評價標準", "The park is beautiful 取決於觀點；should build more seats 是建議。best、boring、too expensive 常帶主觀標準。"],
      ["數字不自動變事實", "Only 20 people came 是可查數量；20 is a disappointing number 加入 disappointing 評價，整句含意見。"],
      ["有理由的意見仍是意見", "作者可用數據支持 should，但規範性結論仍需價值判斷。分類看句子功能，不看它是否合理。"],
    ],
    examples: [
      ["The room has 30 seats.", ["座位可數。", "可現場核對。", "無評價。"], "fact", "資料可能真或假，但型態可驗證。"],
      ["Thirty seats are far too few.", ["有數字。", "too few 依需求判斷。", "含 opinion。"], "opinion", "數字不消除評價。"],
      ["The town should add a bus.", ["should 是建議。", "需要價值與政策選擇。", "非單純資料。"], "opinion", "可有證據支持但仍是主張。"],
    ],
    misconceptions: [
      ["有數字就是事實。", "數字旁可加入評價。", "找 best、too、should 等。"],
      ["我同意的句子就是事實。", "同意不改變可驗證性。", "依句子功能分類。"],
      ["有證據支持就不再是意見。", "規範與評價仍是意見。", "證據只提升可信度。"],
      ["事實一定已被證明為真。", "題型分類看是否可客觀查驗。", "不要混淆 truth 與 statement type。"],
    ],
    checks: [
      ["opened on May 3 是可驗證嗎？", "是", "可查紀錄。"],
      ["the best park 屬於哪類？", "意見", "best 需要評價標準。"],
      ["should 通常提示什麼？", "建議或主張", "屬 opinion。"],
    ],
    questions: questions([
      ["Which sentence is a fact?", "The library opens at nine on weekdays", "開館時間可由 schedule 查驗。", [["The library is the best place in town", "best 是評價。"], ["Nine o'clock is too late", "too late 依觀點。"], ["Everyone should visit more often", "should 是建議。"]]],
      ["Which sentence is an opinion?", "The new sign is much easier to read", "easier 是比較評價，需讀者標準。", [["The sign has twelve words", "字數可查。"], ["Workers placed it on Monday", "日期行動可查。"], ["It stands beside the east gate", "位置可查。"]]],
      ["Which statement contains both a fact and an opinion?", "Only forty people came, which was a disappointing result", "forty 可查，disappointing 是評價。", [["Forty people came", "只有可查數量。"], ["The event began at two", "只有可查時間。"], ["The result was disappointing", "只有評價，未含明確事實資料。"]]],
      ["Which sentence is a recommendation rather than a fact?", "The town should add lights near the bridge", "should 表政策建議。", [["There are two lights near the bridge", "數量可查。"], ["The bridge opened in 2010", "年份可查。"], ["The report lists three dark areas", "報告內容可查。"]]],
      ["Which claim can be checked objectively?", "The path is 1.8 kilometers long", "長度可測量。", [["The path is pleasantly short", "pleasantly 是主觀感受。"], ["It is the most enjoyable route", "most enjoyable 需評價。"], ["Everyone will love walking there", "預測普遍喜愛。"]]],
      ["Which sentence expresses a preference?", "I would rather take the train than the bus", "would rather 明示偏好。", [["The train leaves at 8:20", "時刻可查。"], ["The bus has forty seats", "座位數可查。"], ["Both stop at Central Station", "路線可查。"]]],
      ["Which is a factual statement about the survey?", "Thirty of fifty students selected Option A", "樣本與結果數可由 survey 記錄查驗。", [["Option A was clearly the smartest choice", "smartest 是評價。"], ["The survey should have asked better questions", "should 是建議。"], ["Fifty students are far too few", "far too few 是樣本評價。"]]],
      ["Which sentence is an opinion even if reasons follow it?", "The school ought to keep the garden", "ought to 是價值主張。", [["The garden covers 200 square meters", "面積可測。"], ["Students grew tomatoes last year", "事件可查。"], ["Three classes use it each week", "頻率可查。"]]],
      ["Which sentence reports a fact without evaluation?", "The cafe stopped using plastic forks in June", "行動與月份可查且無評價。", [["Stopping plastic forks was a wonderful choice", "wonderful 是評價。"], ["Every cafe must do the same", "must 是規範。"], ["June was the perfect time", "perfect 是評價。"]]],
      ["Which phrase most clearly turns a fact into an opinion?", "an unacceptable wait", "unacceptable 引入評價標準。", [["a twenty-minute wait", "時長可測。"], ["a wait on Friday", "日期可查。"], ["a wait outside Room 2", "地點可查。"]]],
      ["Which statement is verifiable rather than a personal judgment?", "The model weighs 1.2 kilograms", "重量可用工具測得。", [["The model looks ugly", "ugly 是審美評價。"], ["It is too heavy for a project", "too heavy 依用途標準。"], ["It should win first prize", "should win 是主張。"]]],
      ["Which statement is an opinion?", "The final chapter is more exciting than the first", "exciting 是讀者評價。", [["The book has ten chapters", "數量可查。"], ["The first chapter is six pages", "頁數可查。"], ["The author published it in May", "出版日期可查。"]]],
    ], { type: "fact-opinion", operation: "classify-verifiable-versus-evaluative", misconception: "treat-number-as-automatic-fact" }),
  },
  {
    id: "ENG_R4_S272", process: "select-evidence-based-tone", evidence: "語氣標籤能由至少兩個具體詞句支持且強度不超過文本",
    objectives: ["為語氣判斷指出至少兩項文字證據。", "區分 formal、friendly、urgent、critical、cautious 等描述。", "排除只靠主題或單一標點的語氣標籤。"],
    sections: [
      ["語氣是文字呈現方式", "同一 closure 可用 formal notice、friendly reminder 或 urgent warning 表達。語氣取決於稱呼、動詞、評價與句型，不只主題。"],
      ["兩證據原則", "選 tone 前至少指出兩項：Please 與 thank you 支持 polite；must、immediately 與 danger 支持 urgent。單一驚嘆號太弱。"],
      ["正式度與情緒分開", "formal 描述表達方式，concerned 描述立場，兩者可同時存在。選項若只有一個面向，仍要看題目要哪個。"],
      ["強度校準", "cautious 不等於 terrified，firm 不等於 rude。答案要能被原字直接支持，不能為吸引力升級。"],
    ],
    examples: [
      ["Please return the form by Friday. Thank you for your help.", ["Please。", "Thank you。", "要求清楚但有禮。"], "polite and formal", "不是 angry。"],
      ["Leave the bridge now. Water is rising quickly.", ["命令立即離開。", "危險正在增加。", "語氣 urgent。"], "urgent", "不是 casual。"],
      ["The early results are promising, but more tests are needed.", ["promising 正面。", "but 加限制。", "more tests 顯示保留。"], "cautiously hopeful", "不能選 completely certain。"],
    ],
    misconceptions: [
      ["主題危險就一定語氣恐怖。", "作者可能冷靜正式警告。", "看實際用字。"],
      ["一個 please 就代表 joyful。", "please 主要顯示禮貌。", "用多項證據。"],
      ["firm 等於 rude。", "清楚強制可保持禮貌。", "不要擴張負面強度。"],
      ["but 前正面就表示完全樂觀。", "but 後可能限制信心。", "讀完整語氣轉折。"],
    ],
    checks: [
      ["可靠 tone 判斷至少需要幾項線索？", "兩項", "降低單字誤判。"],
      ["must 一定 rude 嗎？", "不一定", "可為正式且堅定。"],
      ["promising but more tests needed 是完全確定嗎？", "不是", "屬審慎樂觀。"],
    ],
    questions: questions([
      ["Please keep the door closed during the test. Thank you for helping everyone concentrate. Which tone is best supported?", "polite but firm", "Please/Thank you 顯禮貌，keep closed 是明確要求。", [["furious", "沒有憤怒詞。"], ["playful", "測驗規則不是玩笑。"], ["uncertain", "要求清楚。"]]],
      ["Move to higher ground immediately. Do not wait for the water to reach the road. What is the tone?", "urgent", "immediately、Do not wait 與水患風險支持緊急。", [["relaxed", "與立即命令相反。"], ["humorous", "沒有玩笑。"], ["grateful", "沒有道謝。"]]],
      ["The first results are encouraging; however, the group was small and further study is required. What tone?", "cautiously optimistic", "encouraging 正面，however、小樣本與 further study 保留。", [["completely certain", "限制否定完全確定。"], ["hopeless", "encouraging 不支持。"], ["angry", "沒有情緒攻擊。"]]],
      ["Hey, bring your favorite snack and join us by the river! We can't wait to see you. What tone?", "friendly and enthusiastic", "Hey、favorite、can't wait 與驚嘆號共同支持。", [["formal and distant", "稱呼與縮寫相反。"], ["critical", "沒有批評。"], ["fearful", "沒有危險。"]]],
      ["Applicants must submit the signed form by 17:00 on June 2. Late forms will not be reviewed. What tone?", "formal and strict", "must、精確時間、will not reviewed 顯制度性嚴格。", [["casual", "格式與硬期限不 casual。"], ["cheerful", "沒有正面情緒。"], ["confused", "規則明確。"]]],
      ["Sadly, another old tree was lost, even though earlier care could have saved it. What tone?", "regretful and critical", "Sadly 顯遺憾，could have saved 指責照顧不足。", [["celebratory", "與 Sadly 相反。"], ["neutral", "評價明確。"], ["amused", "沒有幽默。"]]],
      ["Perhaps the plan could work, but we should test it on one street before using it everywhere. What tone?", "cautious", "Perhaps、could、test one street 都降低確定性。", [["fully confident", "保留詞相反。"], ["furious", "沒有憤怒。"], ["carelessly excited", "作者要求先測試。"]]],
      ["What an elegant solution: one small change saves both time and space. What tone?", "admiring", "elegant 與 saves both 是明確讚賞。", [["doubtful", "沒有保留。"], ["hostile", "與讚賞相反。"], ["uninterested", "感嘆與評價顯投入。"]]],
      ["We understand that the delay is frustrating. Our team is working to restore service, and we appreciate your patience. What tone?", "apologetic and reassuring", "承認 frustration、restore service、appreciate patience 安撫讀者。", [["mocking", "沒有嘲諷。"], ["carefree", "正在處理問題。"], ["threatening", "沒有威脅。"]]],
      ["The claim sounds impressive, but the article gives no source, date, or data. What tone?", "skeptical", "but 後列三項缺證據，對 impressive claim 保留懷疑。", [["trusting", "缺來源導向相反。"], ["joyful", "沒有好消息。"], ["neutral about evidence", "作者明確指出缺失。"]]],
      ["Remember: a small step still matters. Try one change today, and build from there. What tone?", "encouraging", "small step still matters 與 Try one change 提供支持性動機。", [["discouraging", "方向相反。"], ["angry", "沒有責備。"], ["formal and legal", "用語親切非法律格式。"]]],
      ["For your safety, helmets are required at all times. Riders without one may not enter the course. What tone?", "serious and firm", "for safety、required、may not enter 是堅定規則。", [["joking", "安全規則不含幽默。"], ["uncertain", "required 明確。"], ["excited about fashion", "helmet 功能是 safety。"]]],
    ], { type: "evidence-based-tone", operation: "require-two-tone-signals", misconception: "infer-tone-from-topic-alone" }),
  },
];

export const ENGLISH_UNIT_SOURCE = defineEnglishUnit({
  unitId: "ENG_R4_U40",
  skills,
  vocabularyPolicy: {
    capQuestionBasis: "appendix-5-table-1",
    additionalLearningTerms: ["add", "address", "admire", "adult", "anger", "appreciate", "argue", "attention", "avoid", "beyond", "calm", "careless", "central", "certain", "clever", "coach", "command", "compare", "complete", "concern", "confident", "confuse", "considerate", "create", "crowded", "customer", "daily", "danger", "describe", "dial", "discuss", "distant", "doubt", "effort", "emotion", "energy", "event", "everywhere", "exist", "express", "fear", "final", "fit", "form", "formal", "guest", "guide", "humorous", "include", "increase", "information", "kilometer", "measure", "message", "mix", "model", "negative", "opinion", "passenger", "path", "patient", "perfect", "personal", "platform", "pleasant", "positive", "praise", "print", "project", "promise", "protect", "purpose", "rather", "receive", "record", "recycle", "refuse", "remind", "repair", "result", "return", "review", "rude", "safety", "sample", "satisfy", "select", "serve", "sleepy", "solve", "speed", "step", "success", "support", "temperature", "tiny", "travel", "trust", "truth", "value", "waste", "weekday"],
    contextualizedAboveRangeTerms: ["access", "advertise", "alternate", "amazement", "amuse", "announce", "announcement", "apologetic", "applicant", "appreciative", "article", "artwork", "assignment", "attend", "attitude", "audience", "author", "benefit", "bin", "cafe", "carefree", "casual", "caution", "cautious", "celebratory", "chapter", "cheerful", "claim", "closure", "comfort", "concentrate", "confusion", "contain", "contest", "convince", "critical", "data", "delay", "delight", "despite", "disappoint", "discourage", "dismissive", "donation", "doubtful", "drawback", "easiest", "electricity", "elegant", "email", "employee", "encourage", "enjoyable", "enjoyment", "entertain", "enthusiastic", "entirely", "evaluation", "evidence", "examine", "factual", "fashion", "fearful", "firm", "flash", "fold", "fortunate", "frustrate", "frustration", "fully", "furious", "further", "grateful", "guardian", "helmet", "hesitant", "hopeful", "hopeless", "hostile", "immediate", "impatient", "impress", "impressive", "indifferent", "inform", "instruct", "instruction", "intend", "joyful", "judgment", "label", "legal", "material", "mocking", "narrator", "neighborhood", "neutral", "notify", "objective", "offend", "oppose", "optimistic", "option", "ought", "overdue", "panic", "passage", "patience", "persuade", "phrase", "plastic", "playful", "practical", "prefer", "preference", "press", "prove", "publish", "qualify", "reaction", "reassure", "recommendation", "regretful", "relax", "reliable", "relief", "relieve", "remain", "remove", "request", "require", "reservation", "reserve", "reset", "resident", "restore", "reusable", "ridiculous", "route", "sadness", "schedule", "shift", "skeptical", "soil", "solution", "somewhat", "source", "staff", "statement", "strict", "submit", "supportive", "survey", "suspicious", "tablet", "terrify", "terror", "thankful", "threaten", "tone", "unacceptable", "unaware", "uncertain", "unfortunate", "uninterested", "unsure", "update", "upside", "urgent", "useless", "user", "verifiable", "view", "volunteer", "warn", "warning", "wasteful", "weigh"],
    properNames: ["Amy", "Ben", "Eva", "Hill", "Jay", "Leo", "Mia", "Nora"],
    grammarNotation: ["A", "A's", "B"],
    malformedDistractors: [],
  },
});
