const UNIT_ID = "ENG_R4_U19";

function lecture(id, skillId, content) {
  return { id, skillId, ...content, sections: content.sections.map((section, index) => ({ id: `${id}_SEC_${String(index + 1).padStart(2, "0")}`, ...section })) };
}

const DIFFICULTIES = ["foundation", "foundation", "foundation", "standard", "standard", "standard", "standard", "advanced", "advanced", "advanced", "transfer", "transfer"];

function skillQuestions(skillNumber, values) {
  if (values.length !== 12) throw new Error(`ENG_R4_S${skillNumber}: expected 12 authored questions`);
  return values.map((value, index) => ({ id: `ENG_R4_Q_${skillNumber}_${String(index + 1).padStart(2, "0")}`, skillId: `ENG_R4_S${skillNumber}`, difficulty: DIFFICULTIES[index], ...value }));
}

export const ENGLISH_U19_LECTURES = [
  lecture("ENG_R4_L_S127", "ENG_R4_S127", {
    objectives: ["依單字在句中的工作區分形容詞與副詞，不只看字尾。", "分辨描述名詞或主詞狀態，和說明動作方式的不同。"],
    sections: [
      { title: "形容詞描述名詞或主詞狀態", content: "形容詞可放在名詞前，如 a careful driver，也可接在 be、look、feel、sound 等連綴動詞後，如 The driver looks careful。兩個位置都把性質連到人或物，不是在說動作怎麼進行。" },
      { title: "副詞說明動作如何發生", content: "方式副詞常回答 how，例如 The driver checks the bus carefully 中，carefully 說明 checks 的方式。判斷時先找主要動作，再問空格是在描述動作者，還是在補充動作過程。" },
      { title: "同一字族會因句法工作改變形式", content: "a quiet class 用 quiet 修飾名詞；The class listened quietly 用 quietly 修飾 listened。不能因為兩句都談安靜，就忽略空格實際連接的詞。" },
      { title: "字尾只是線索，不是答案", content: "許多方式副詞有 -ly，但 fast、hard、early、late 等可用原形作副詞；friendly 雖有 -ly，通常仍是形容詞。good 與 well 也需依功能選擇，因此最後要回到句子結構和意思。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S127_EX_01", prompt: "Mia made a ___ choice. (careful / carefully)", steps: ["找空格後的名詞 choice。", "確認空格直接描述 choice。", "選形容詞 careful。"], answer: "careful", why: "空格位在 a 與 choice 之間，工作是描述這個 choice 的性質，所以用 careful。carefully 只能說明動作如何完成，不能直接放在此處修飾名詞。" },
      { id: "ENG_R4_L_S127_EX_02", prompt: "Mia chose the seat ___. (careful / carefully)", steps: ["找主要動作 chose。", "seat 已完成受詞位置。", "用 carefully 補充選擇方式。"], answer: "carefully", why: "chose 已有受詞 the seat，空格補充 Mia 怎麼選，因此需要方式副詞 carefully。careful 會描述人或物，不能直接放在句尾修飾這個動作。" },
      { id: "ENG_R4_L_S127_EX_03", prompt: "The song sounds ___. (beautiful / beautifully)", steps: ["判斷 sounds 是否連接主詞狀態。", "確認空格描述 song。", "使用形容詞 beautiful。"], answer: "beautiful", why: "sounds 在此不是歌曲主動發出某個動作，而是連接 song 和聽起來的性質。beautiful 描述歌曲；beautifully 則會把重點錯放在動作方式。" },
    ],
    misconceptions: [
      { belief: "看到動詞後的空格就一律填副詞。", whyWrong: "連綴動詞後的字會描述主詞，而不是修飾動作。", correction: "先判斷動詞是動作還是連接狀態，再選詞性。" },
      { belief: "所有以 -ly 結尾的字都是副詞。", whyWrong: "friendly 等常用字即使有 -ly，主要功能仍是形容詞。", correction: "以句中工作驗證詞性，不單靠字尾。" },
      { belief: "同一個中文意思只能對應一種英文形式。", whyWrong: "careful 與 carefully 意思相關，卻分別描述名詞和動作。", correction: "先找被修飾的詞，再從字族選合適形式。" },
      { belief: "good 可以直接修飾任何動作。", whyWrong: "一般方式用法需要副詞 well；good 多半描述人、物或狀態。", correction: "區分 looks good 和 works well 的句法功能。" },
    ],
    checks: [
      { prompt: "a slow train 中 slow 描述什麼？", answer: "train", reason: "slow 直接放在名詞前。" },
      { prompt: "The train moved slowly 中 slowly 修飾什麼？", answer: "moved", reason: "它說明列車移動的方式。" },
      { prompt: "The train looks slow 中 slow 是哪一類詞？", answer: "形容詞", reason: "looks 把 slow 連回主詞 train。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S128", "ENG_R4_S128", {
    objectives: ["形成常見的 -ly 方式副詞並處理字尾變化。", "辨識 good、fast、hard 等不直接套用 -ly 的常見情況。"],
    sections: [
      { title: "多數形容詞直接加 -ly", content: "slow 變 slowly、careful 變 carefully、quiet 變 quietly。這些副詞用來說明動作方式；加上 -ly 後仍要檢查句子是否真的需要副詞，不能只為了看到動詞就變形。" },
      { title: "子音加 y 時改成 -ily", content: "easy 變 easily、happy 變 happily。先把子音後的 y 改成 i，再加 -ly；若直接寫 easyly 或 happyly，會保留錯誤字尾。" },
      { title: "部分 -le 字尾改成 -ly", content: "terrible 變 terribly、simple 變 simply。這類字通常去掉字尾 e，再加 y；不是在完整形容詞後再接 ly，所以 terriblely 與 simplely 都不合適。" },
      { title: "常見例外要連同用法記", content: "good 的方式副詞通常是 well；fast 與 hard 可直接作方式副詞，不寫 fastly 或 hardly 來表達同一意思。hardly 的意思接近幾乎不，和努力地 hard 不同。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S128_EX_01", prompt: "Please speak ___. (quiet)", steps: ["speak 是動作。", "空格回答說話方式。", "quiet 加 -ly。"], answer: "quietly", why: "空格要說明 speak 的方式，所以將 quiet 變成 quietly。原形 quiet 會描述人或物的狀態，不能在此直接作方式副詞。" },
      { id: "ENG_R4_L_S128_EX_02", prompt: "Nora finished the work ___. (easy)", steps: ["finished 需要方式說明。", "easy 的 y 前是子音。", "y 改 i 後加 -ly。"], answer: "easily", why: "句子要表達 Nora 不費力地完成工作，需用副詞 easily。easy 字尾的 y 前是子音，因此拼字不是 easyly，而是先改 i 再接 ly。" },
      { id: "ENG_R4_L_S128_EX_03", prompt: "Leo did ___ on the test. (good)", steps: ["did 是動作表現。", "需要 good 的副詞形式。", "使用不規則形式 well。"], answer: "well", why: "空格評述 Leo 在考試中的表現方式，應使用 well。good 通常作形容詞，goodly 也不是本句需要的常用形式。" },
    ],
    misconceptions: [
      { belief: "任何形容詞後面加 ly 就會得到正確副詞。", whyWrong: "good、fast、hard 等常見字不依這個方式表達動作。", correction: "規則字依字尾變化，例外字另外核對。" },
      { belief: "easy 的副詞可以寫成 easyly。", whyWrong: "子音後的 y 在加 -ly 前要改成 i。", correction: "使用 easily，並把 happy 同樣寫成 happily。" },
      { belief: "terriblely 保留完整形容詞最安全。", whyWrong: "terrible 形成方式副詞時要去 e，再寫 terribly。", correction: "看到 -le 字尾時檢查是否改成 -ly。" },
      { belief: "hardly 就是比 hard 更用力。", whyWrong: "hard 表示努力地，hardly 通常表示幾乎不，意思方向不同。", correction: "依要表達的意思選 hard 或 hardly。" },
    ],
    checks: [
      { prompt: "slow 的方式副詞是什麼？", answer: "slowly", reason: "一般情況直接加 -ly。" },
      { prompt: "happy 的方式副詞如何拼？", answer: "happily", reason: "子音後 y 改 i 再加 -ly。" },
      { prompt: "good 的常見方式副詞是什麼？", answer: "well", reason: "它是不規則對應形式。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S129", "ENG_R4_S129", {
    objectives: ["把方式副詞放在不破壞動詞與受詞關係的位置。", "依句子是否有受詞或助動詞安排副詞。"],
    sections: [
      { title: "沒有受詞時可放在動作後", content: "The baby slept quietly 中，quietly 放在 slept 後補充睡眠方式。句首或句尾有時也能調整語氣，但國中階段先使用清楚、不切斷必要成分的位置。" },
      { title: "有受詞時常放在受詞後", content: "Mia closed the door slowly 比 Mia closed slowly the door 自然。closed 與 the door 構成緊密的動詞受詞組，方式副詞放在整組後面，讀者不會誤判動作對象。" },
      { title: "助動詞與主要動詞保持相連", content: "Nora can sing beautifully 中，can sing 構成動詞組，beautifully 放在主要內容後。不要把方式副詞插在 can 與 sing 之間來製造不自然的節奏。" },
      { title: "位置改變可能影響重點或自然度", content: "Slowly, Ben opened the box 可特別強調緩慢過程；Ben opened the box slowly 是中性說法。兩者都要保留 opened the box 的關係，並以標點清楚分隔句首副詞。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S129_EX_01", prompt: "The child smiled ___. (happily)", steps: ["smiled 沒有受詞。", "空格補充微笑方式。", "將 happily 放在動作後。"], answer: "happily", why: "smiled 在此已能獨立完成動作，句尾加入 happily 便能自然說明微笑的方式。副詞不需要移到 child 前，也不會改成形容詞 happy。" },
      { id: "ENG_R4_L_S129_EX_02", prompt: "Which order is natural: read carefully the note / read the note carefully?", steps: ["找動詞 read。", "確認受詞 the note。", "把方式副詞放在受詞後。"], answer: "read the note carefully", why: "read 和 the note 先形成動作與受詞，再由 carefully 說明整個閱讀動作。把 carefully 插在兩者之間會使短句的英文詞序不自然。" },
      { id: "ENG_R4_L_S129_EX_03", prompt: "Grace can dance ___. (beautifully)", steps: ["can 與 dance 構成動詞組。", "句中沒有另一個受詞。", "在 dance 後放 beautifully。"], answer: "beautifully", why: "beautifully 修飾主要動作 dance，放在 can dance 後最清楚。若寫 can beautifully dance，雖某些語境可能見到，初學句型不如句尾位置直接。" },
    ],
    misconceptions: [
      { belief: "方式副詞一定緊接在動詞後。", whyWrong: "及物動詞後若有受詞，硬插副詞會切開動詞與受詞。", correction: "先完成動詞加受詞，再放方式副詞。" },
      { belief: "副詞放在句中任何位置意思都完全相同。", whyWrong: "位置會改變自然度、焦點，甚至使讀者難以連接修飾對象。", correction: "選擇最靠近完整動作組且不造成歧義的位置。" },
      { belief: "助動詞後必須立刻放方式副詞。", whyWrong: "can sing、will work 等動詞組不宜被初學者任意拆開。", correction: "通常先寫完整主要動作，再補方式。" },
      { belief: "句首方式副詞不需要標點。", whyWrong: "較長或特別前置的副詞若無逗點，閱讀界線可能不清楚。", correction: "使用 Slowly, Ben opened the box 這類清楚形式。" },
    ],
    checks: [
      { prompt: "read the letter carefully 中 carefully 放在哪裡？", answer: "受詞 the letter 後", reason: "動詞與受詞先保持相連。" },
      { prompt: "The dog ran quickly 中 quickly 修飾哪個動作？", answer: "ran", reason: "句尾副詞補充奔跑方式。" },
      { prompt: "Slowly, Mia opened the bag 為何有逗點？", answer: "分隔句首方式副詞", reason: "逗點讓主要句子邊界清楚。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S130", "ENG_R4_S130", {
    objectives: ["區分 very 的高程度與 too 的過度結果。", "依 enough 修飾形容詞、副詞或名詞選擇正確位置。"],
    sections: [
      { title: "very 表示程度高但不必然造成問題", content: "The water is very cold 只說水很冷，沒有斷定不能使用。very 可修飾形容詞或副詞，如 very careful、very slowly；後續結果仍要由句子另外提供。" },
      { title: "too 表示超過情境可接受程度", content: "The water is too cold to swim in 表示冷到不適合游泳。too 常和 to + verb 說明被阻礙的行動；它不是 very 的花俏替換，因為 too 帶有超過需求或限制的意思。" },
      { title: "enough 放在形容詞或副詞後", content: "warm enough、quickly enough 都把 enough 放在被修飾詞後。The room is warm enough to use 表示程度已達需求，不是超過而造成不能使用。" },
      { title: "enough 修飾名詞時放在名詞前", content: "enough time、enough chairs 中，enough 直接限定數量。比較 There are enough chairs 與 The chairs are comfortable enough，可看出名詞和形容詞的不同位置。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S130_EX_01", prompt: "The soup is ___ hot, but I can still eat it. (very / too)", steps: ["讀 but 後仍能吃。", "判斷高溫沒有阻止行動。", "選 very。"], answer: "very", why: "but I can still eat it 明確表示熱度雖高，卻沒有高到不能吃，因此用 very。too hot 通常會和這個結果衝突。" },
      { id: "ENG_R4_L_S130_EX_02", prompt: "The box is ___ heavy for Mia to lift. (very / too)", steps: ["for Mia to lift 指目標動作。", "句意表示重量阻止動作。", "使用 too heavy。"], answer: "too", why: "句子表示箱子的重量超過 Mia 能搬起的程度，所以 too 與 for Mia to lift 形成限制。very 只表示很重，不能自行推出搬不動。" },
      { id: "ENG_R4_L_S130_EX_03", prompt: "We have ___ time to catch the bus. (enough)", steps: ["time 是名詞。", "enough 要限定時間量。", "放在 time 前。"], answer: "enough", why: "enough 在這裡直接修飾名詞 time，所以寫 enough time。若修飾 fast 等形容詞或副詞，位置才會改在該詞之後。" },
    ],
    misconceptions: [
      { belief: "very 與 too 都只是表示很，所以可以互換。", whyWrong: "too 通常表示程度過頭並造成限制，very 沒有這層必然結果。", correction: "用後續行動能否完成來判斷 very 或 too。" },
      { belief: "enough 永遠放在被修飾詞前。", whyWrong: "它在名詞前，卻放在形容詞或副詞後。", correction: "比較 enough water 與 warm enough 的位置。" },
      { belief: "too cold to go 表示雖冷仍然去。", whyWrong: "too...to 通常說明程度阻止後面的動作。", correction: "若行動仍可進行，改看 very 或 enough 的語意。" },
      { belief: "very enough 可以一起加強同一個形容詞。", whyWrong: "very tall enough 不是本單元的標準程度結構。", correction: "依高程度或達標需求擇一使用 very tall 或 tall enough。" },
    ],
    checks: [
      { prompt: "very tired 是否必然表示不能走？", answer: "否", reason: "very 只表示程度高。" },
      { prompt: "too tired to walk 表示什麼？", answer: "累到不能走", reason: "too 的程度阻止 to walk。" },
      { prompt: "足夠的椅子應寫哪個片語？", answer: "enough chairs", reason: "enough 修飾名詞時放在前面。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S131", "ENG_R4_S131", {
    objectives: ["辨識 fast、hard、early、late 等同形形容詞與副詞。", "區分 hard/hardly、late/lately 等外形接近但意思不同的字。"],
    sections: [
      { title: "同一形式可依位置做不同工作", content: "a fast train 中 fast 修飾 train；The train moves fast 中 fast 修飾 moves。early 與 late 也可分別出現在 an early bus、arrive early 或 a late bus、arrive late。" },
      { title: "hard 作副詞時不加 -ly", content: "Nora works hard 表示努力工作；hardly 不是更努力，而是幾乎不。Nora hardly works 會變成 Nora 幾乎不工作，意思方向完全不同。" },
      { title: "late 與 lately 不能直接互換", content: "arrive late 表示到達時間晚；lately 表示最近一段時間，如 I have been busy lately。兩者都可能在句尾，但時間概念不同。" },
      { title: "有 -ly 不保證是方式副詞", content: "friendly 通常是形容詞，如 a friendly teacher。若要說友善地說話，可用 speak in a friendly way。看到外形時仍需檢查它在句中修飾誰。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S131_EX_01", prompt: "The car moves ___. (fast / fastly)", steps: ["moves 需要方式說明。", "fast 可直接作副詞。", "不另加 -ly。"], answer: "fast", why: "fast 在此修飾 moves，雖然形式和形容詞相同，仍可直接作方式副詞。fastly 不是一般標準用法。" },
      { id: "ENG_R4_L_S131_EX_02", prompt: "Ben studied ___ for the test. (hard / hardly)", steps: ["句意要表達努力準備。", "hard 可表示努力地。", "排除 hardly 的幾乎不。"], answer: "hard", why: "studied hard 表示 Ben 用功準備考試。若改成 hardly studied，意思會變成幾乎沒有讀書，和努力的方向相反。" },
      { id: "ENG_R4_L_S131_EX_03", prompt: "The bus arrived ___. (late / lately)", steps: ["arrived 需要到達時間。", "late 表示時間晚。", "lately 表示最近。"], answer: "late", why: "句子關心公車抵達得晚，因此用 late 修飾 arrived。lately 是最近一段時間，不能單獨表示某班公車晚到。" },
    ],
    misconceptions: [
      { belief: "副詞沒有 -ly 就一定錯。", whyWrong: "fast、hard、early、late 都能以原形修飾動作。", correction: "把同形詞放回句中確認功能。" },
      { belief: "hardly 是 hard 的一般方式副詞。", whyWrong: "hardly 表示幾乎不，會把努力工作改成幾乎沒工作。", correction: "要表達努力地時使用 hard。" },
      { belief: "lately 可以表示某一次晚到。", whyWrong: "lately 表示最近期間，不等於 late 的時間延遲。", correction: "arrive late 與 have been busy lately 分開記。" },
      { belief: "friendly 能直接放在動詞後表示友善地。", whyWrong: "friendly 通常是形容詞，不能直接取代方式片語。", correction: "使用 in a friendly way 說明動作方式。" },
    ],
    checks: [
      { prompt: "a fast bike 中 fast 是哪一類詞？", answer: "形容詞", reason: "它直接修飾 bike。" },
      { prompt: "ride fast 中 fast 是哪一類詞？", answer: "副詞", reason: "它修飾 ride 的方式。" },
      { prompt: "hardly slept 表示什麼？", answer: "幾乎沒睡", reason: "hardly 帶有接近否定的意思。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S132", "ENG_R4_S132", {
    objectives: ["使用副詞比較級比較兩個動作進行的方式。", "依副詞形式選擇 -er、more 或不規則變化。"],
    sections: [
      { title: "短副詞或同形副詞常加 -er", content: "fast 變 faster、hard 變 harder、early 變 earlier、late 變 later。它們比較的是動作方式或時間，如 Leo arrived earlier than Ben，不是描述人本身的固定性質。" },
      { title: "-ly 方式副詞通常在前面加 more", content: "carefully 變 more carefully、slowly 變 more slowly。不要寫 carefullier，也不要同時使用 more carefullyer；比較級只標記一次。" },
      { title: "不規則副詞要使用獨立形式", content: "well 的比較級是 better，badly 的比較級是 worse。Mia sings better than before 比 more well 或 gooder 更符合標準用法。" },
      { title: "同等方式仍用 as...as", content: "Nora works as carefully as Mia 中，carefully 保持原級。not as quickly as 表示前者速度未達後者；是否使用比較級要看句型，不只看兩個對象。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S132_EX_01", prompt: "The red bus arrived ___ than the blue bus. (early)", steps: ["than 要求比較級。", "early 的 y 前是子音。", "改成 earlier。"], answer: "earlier", why: "句子比較兩班車的抵達時間，early 要變成 earlier。這裡的 earlier 修飾 arrived，表示紅色公車比藍色公車更早到。" },
      { id: "ENG_R4_L_S132_EX_02", prompt: "Please read ___ than before. (carefully)", steps: ["than 表示方式比較。", "carefully 是 -ly 副詞。", "在前面加 more。"], answer: "more carefully", why: "比較的是 read 的仔細程度，carefully 前加 more 即可。carefullier 會錯改字尾，more carefullyer 則重複比較標記。" },
      { id: "ENG_R4_L_S132_EX_03", prompt: "The team worked ___ in the second game than in the first. (well)", steps: ["worked 需要副詞。", "than 要求比較級。", "well 改為 better。"], answer: "better", why: "兩場比賽形成比較，well 在此修飾 worked，它的不規則比較級是 better。best 需要更大的群體範圍，不能取代本句的兩場比較。" },
    ],
    misconceptions: [
      { belief: "所有副詞比較級都在前面加 more。", whyWrong: "fast、hard、early、late 常直接使用 -er 形式。", correction: "先判斷副詞形式，再決定 -er 或 more。" },
      { belief: "carefully 的比較級是 carefullier。", whyWrong: "-ly 方式副詞通常不改字尾，而在前面加 more。", correction: "使用 more carefully。" },
      { belief: "well 的比較級是 more well。", whyWrong: "well 使用不規則形式 better。", correction: "把 well-better-best 作為一組記憶。" },
      { belief: "兩個人出現時一定要用比較級。", whyWrong: "as...as 比較兩者時仍保留副詞原級。", correction: "先辨認 than 或 as...as 的句型。" },
    ],
    checks: [
      { prompt: "work hard 的比較形式是什麼？", answer: "work harder", reason: "hard 可直接加 -er。" },
      { prompt: "speak slowly 的比較形式是什麼？", answer: "speak more slowly", reason: "-ly 副詞前加 more。" },
      { prompt: "do well 的比較形式是什麼？", answer: "do better", reason: "well 使用不規則比較級。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S133", "ENG_R4_S133", {
    objectives: ["在 be 與常見連綴動詞後使用形容詞描述主詞。", "依感官動詞的實際意思區分連綴功能與動作功能。"],
    sections: [
      { title: "連綴動詞把性質連回主詞", content: "The room is quiet、The child looks tired、The idea sounds good 中，quiet、tired、good 都描述主詞。即使它們位在動詞後，工作仍是形容詞補語。" },
      { title: "感官動詞可用來描述狀態", content: "The soup tastes hot、The flower smells sweet、The music sounds soft 都是在說主詞呈現的感覺。這時使用形容詞，不因 tastes、smells、sounds 長得像動作動詞就加 -ly。" },
      { title: "同一動詞也可能是真正動作", content: "Nora looked carefully at the map 中，looked 表示主動查看，carefully 修飾查看方式；Nora looked tired 則用 tired 描述 Nora。要看後面是否有 at、受詞或狀態補語。" },
      { title: "good 與 well 要依功能判斷", content: "The meal tastes good 用 good 描述 meal；Mia cooks well 用 well 修飾 cooks。well 也可在 I am well 中表示身體狀況良好，此時功能接近形容詞，不能只靠單字表面決定。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S133_EX_01", prompt: "The milk smells ___. (bad / badly)", steps: ["smells 連接 milk 與氣味。", "空格描述主詞狀態。", "選形容詞 bad。"], answer: "bad", why: "smells 在此表示牛奶聞起來的狀態，所以 bad 描述 milk。badly 會把字當成動作方式，無法表達牛奶本身的氣味。" },
      { id: "ENG_R4_L_S133_EX_02", prompt: "Mia looked ___ at the small words. (careful / carefully)", steps: ["looked 後有 at 與對象。", "這裡表示查看動作。", "使用副詞 carefully。"], answer: "carefully", why: "looked at the small words 是主動查看，空格回答 Mia 怎麼看，因此用 carefully。若沒有 at 而寫 Mia looked careful，意思會改成她看起來很謹慎。" },
      { id: "ENG_R4_L_S133_EX_03", prompt: "The plan sounds ___. (good / well)", steps: ["sounds 連接 plan 與評價。", "空格描述 plan。", "使用形容詞 good。"], answer: "good", why: "sounds 把 plan 和評價連起來，good 是描述計畫的形容詞。well 通常修飾動作表現，在此不如 good 符合句法與意思。" },
    ],
    misconceptions: [
      { belief: "動詞後面只能放副詞。", whyWrong: "連綴動詞後需要形容詞補充主詞狀態。", correction: "先辨認動詞是否連接主詞與性質。" },
      { belief: "smells sweetly 一定表示聞起來香甜。", whyWrong: "sweetly 會修飾聞的動作，不是描述主詞氣味。", correction: "描述物品氣味使用 smells sweet。" },
      { belief: "looked 後永遠接形容詞。", whyWrong: "looked at 表示查看動作，可由副詞說明方式。", correction: "比較 looked tired 與 looked carefully at。" },
      { belief: "good 與 well 只按中文意思選一個。", whyWrong: "兩者功能不同，且 well 在健康狀態中另有形容詞用法。", correction: "依被描述的是主詞狀態或動作表現判斷。" },
    ],
    checks: [
      { prompt: "The bread tastes fresh 中 fresh 描述什麼？", answer: "bread", reason: "tastes 在此是連綴動詞。" },
      { prompt: "She looked carefully at the sign 中 carefully 修飾什麼？", answer: "looked", reason: "looked at 是查看動作。" },
      { prompt: "The idea sounds good 為何不用 well？", answer: "good 描述 idea", reason: "sounds 將評價連回主詞。" },
    ], assets: [],
  }),
];

export const ENGLISH_U19_QUESTIONS = [
  ...skillQuestions("127", [
    { stem: "Mia made a ___ plan.", options: ["careful", "carefully", "care", "cared"], answerIndex: 0, reasons: ["careful 是形容詞，可直接修飾 plan。", "carefully 是副詞，不能放在此處描述名詞。", "care 通常是名詞或動詞，未形成需要的修飾語。", "cared 是動詞過去式，不適合放在 a 與 plan 之間。"], reviews: ["空格後是名詞 plan，因此先找能描述名詞的形式。", "第一項不是因字義猜中，而是句法位置要求形容詞。"], cognitiveProcess: ["locate-modifier-before-plan", "select-careful-adjective"], representationType: "adjective-before-noun-function", misconceptionTargets: ["use-adverb-before-noun"] },
    { stem: "The children waited ___.", options: ["quiet", "quietly", "quietness", "quieter"], answerIndex: 1, reasons: ["quiet 是形容詞，不能直接說明 waited 的方式。", "quietly 是方式副詞，表示孩子安靜地等。", "quietness 是名詞，不能作句尾方式修飾語。", "quieter 是比較級形容詞，題目沒有比較對象。"], reviews: ["waited 是完整動作，空格回答等待的方式。", "第二項把 quiet 字族轉成修飾動作的副詞。"], cognitiveProcess: ["ask-how-children-waited", "choose-quietly-for-action"], representationType: "manner-adverb-after-intransitive", misconceptionTargets: ["keep-quiet-after-action"] },
    { stem: "Nora answered the question ___.", options: ["clear", "a clear", "clearly", "cleared"], answerIndex: 2, reasons: ["clear 是形容詞，不能直接修飾 answered。", "a clear 後還需要名詞，不能表示回答方式。", "clearly 是副詞，說明 Nora 如何回答。", "cleared 是另一個動詞形式，會和 answered 衝突。"], reviews: ["the question 已完成受詞，句尾補充 answered 的方式。", "第三項讓修飾關係落在動作而不是 question。"], cognitiveProcess: ["separate-answer-object-from-manner", "attach-clearly-to-answered"], representationType: "transitive-action-manner-function", misconceptionTargets: ["describe-question-instead-of-answering"] },
    { stem: "The ___ rain ended at noon.", options: ["heavily", "heaviness", "more heavily", "heavy"], answerIndex: 3, reasons: ["heavily 是副詞，不能直接放在 rain 前。", "heaviness 是名詞，不能作此處修飾語。", "more heavily 是副詞比較形式，句中沒有動作或比較。", "heavy 是形容詞，直接描述 rain。"], reviews: ["空格與 rain 構成名詞片語，不是在修飾 ended。", "第四項形成 the heavy rain，詞性與意思都完整。"], cognitiveProcess: ["distinguish-rain-modifier-from-ended", "use-heavy-before-rain"], representationType: "noun-phrase-versus-verb-modifier", misconceptionTargets: ["choose-heavily-near-verb"] },
    { stem: "In 'The baby slept peacefully,' what does 'peacefully' tell us?", options: ["How the baby slept", "Which baby slept", "When the baby slept", "Where the baby slept"], answerIndex: 0, reasons: ["peacefully 回答睡眠進行的方式。", "句中沒有用 peacefully 指定哪一個 baby。", "peacefully 不提供時間。", "peacefully 不提供地點。"], reviews: ["方式副詞的核心問題是 how，而不是 who、when 或 where。", "第一項把 peacefully 的功能連回 slept。"], cognitiveProcess: ["classify-peacefully-information-role", "identify-how-not-time-place"], representationType: "adverb-function-interpretation", misconceptionTargets: ["treat-manner-as-time"] },
    { stem: "Which pair uses the same word family to describe a person first and an action second?", options: ["a quietly child / speaks quiet", "a polite child / speaks politely", "a politely child / speaks polite", "a politeness child / speaks politer"], answerIndex: 1, reasons: ["quietly 不能直接修飾 child，quiet 也不能在此修飾 speaks。", "polite 描述 child，politely 說明 speaks 的方式。", "兩個形式的位置正好相反。", "politeness 是名詞，politer 也不是此處需要的方式副詞。"], reviews: ["題目要求先形容詞、後副詞兩個不同句法工作。", "第二項在換位置時也正確換了字族形式。"], cognitiveProcess: ["compare-two-slot-word-family-functions", "match-polite-and-politely"], representationType: "paired-adjective-adverb-functions", misconceptionTargets: ["reverse-adjective-adverb-positions"] },
    { stem: "A card says, 'It is a beautifully picture.' Which change fixes the word before 'picture'?", options: ["picture → pictured", "a → an", "beautifully → beautiful", "is → does"], answerIndex: 2, reasons: ["pictured 會改掉名詞，沒有修正修飾語詞性。", "beautifully 的開頭音不需要 an，而且冠詞不是主要錯誤。", "picture 前需要形容詞 beautiful。", "does 不能連接主詞與名詞片語。"], reviews: ["先鎖定題目指定的 picture 前位置。", "第三項只把副詞改成形容詞，保留原句要描述圖片的意思。"], cognitiveProcess: ["diagnose-adverb-before-picture", "repair-beautifully-to-beautiful"], representationType: "adjective-adverb-edit", misconceptionTargets: ["change-unrelated-article-or-verb"] },
    { stem: "Nora looks tired after practice. What is the job of 'tired'?", options: ["It tells how Nora uses her eyes.", "It tells when practice ends.", "It tells how practice happens.", "It describes Nora's condition."], answerIndex: 3, reasons: ["looks 在此不表示查看動作。", "tired 沒有提供結束時間。", "tired 不修飾 practice 的進行方式。", "tired 接在 looks 後，把疲倦狀態連回 Nora。"], reviews: ["after practice 是背景；真正的句法關係是 Nora looks tired。", "第四項辨認連綴動詞後的形容詞功能。"], cognitiveProcess: ["interpret-looks-as-linking-verb", "attach-tired-condition-to-nora"], representationType: "linking-adjective-function", misconceptionTargets: ["read-looks-as-eye-action"] },
    { stem: "The bell is loud, and it rings ___.", options: ["loudly", "loud", "loudness", "more loud"], answerIndex: 0, reasons: ["loudly 修飾 rings，說明鈴聲響起的方式。", "loud 已在前句描述 bell，第二句需要副詞功能。", "loudness 是名詞，不能直接修飾 rings。", "more loud 不是此處的方式副詞。"], reviews: ["兩個分句刻意讓同一概念做不同工作。", "第一項配合 rings，把形容詞 loud 轉為方式副詞。"], cognitiveProcess: ["contrast-loud-state-with-ringing-manner", "supply-loudly-after-rings"], representationType: "cross-clause-function-shift", misconceptionTargets: ["reuse-adjective-after-action"] },
    { stem: "Which sentence uses 'friendly' to describe a person?", options: ["Mia smiled friendly at us.", "Mia is a friendly guide.", "Mia spoke friendlily to us.", "Mia guided us more friendly."], answerIndex: 1, reasons: ["friendly 通常不能直接修飾 smiled。", "friendly 是形容詞，直接描述 guide。", "friendlily 不是本單元採用的自然方式。", "more friendly 放在 guided 後仍未形成清楚的方式片語。"], reviews: ["-ly 外形不代表 friendly 是方式副詞。", "第二項把它放在名詞 guide 前，功能清楚。"], cognitiveProcess: ["test-friendly-as-adjective", "select-friendly-guide-noun-phrase"], representationType: "ly-ending-adjective-recognition", misconceptionTargets: ["assume-friendly-is-adverb"] },
    { stem: "A sign says, 'Drive slowly near the school.' Which word does 'slowly' modify?", options: ["sign", "school", "Drive", "near"], answerIndex: 2, reasons: ["slowly 不描述 sign。", "slowly 沒有描述 school 的性質。", "slowly 說明駕駛動作要如何進行。", "near 是位置關係，不是被 slowly 修飾的動作。"], reviews: ["命令句省略主詞，但主要動作 Drive 仍然存在。", "第三項從實際句法連接副詞與動詞。"], cognitiveProcess: ["find-imperative-main-verb", "link-slowly-to-drive"], representationType: "notice-adverb-target", misconceptionTargets: ["attach-adverb-to-nearest-noun"] },
    { stem: "The door closed ___.", options: ["sudden", "a sudden", "suddenness", "suddenly"], answerIndex: 3, reasons: ["sudden 是形容詞，不能直接修飾 closed。", "a sudden 後還需要名詞。", "suddenness 是名詞，不回答門如何關上。", "suddenly 是副詞，表示門突然關上。"], reviews: ["closed 在此沒有受詞，句尾空格補充動作發生方式。", "第四項同時符合詞性與事件意思。"], cognitiveProcess: ["classify-closed-as-event-action", "choose-suddenly-for-manner"], representationType: "event-manner-cloze", misconceptionTargets: ["use-sudden-after-action"] },
  ]),
  ...skillQuestions("128", [
    { stem: "Please close the door ___. (quiet)", options: ["quietly", "quiet", "quietness", "quieter"], answerIndex: 0, reasons: ["quietly 是 quiet 加 -ly 的方式副詞。", "quiet 是形容詞，不能直接修飾 close。", "quietness 是名詞，不表示關門方式。", "quieter 是比較級形容詞，句中沒有比較。"], reviews: ["close 已有受詞 the door，句尾需要方式副詞。", "第一項使用一般加 -ly 的形成方式。"], cognitiveProcess: ["identify-close-door-manner-slot", "form-quietly-with-ly"], representationType: "regular-ly-adverb-formation", misconceptionTargets: ["leave-quiet-uninflected"] },
    { stem: "The children played ___. (happy)", options: ["happyly", "happily", "happy", "happiness"], answerIndex: 1, reasons: ["happyly 沒有把子音後的 y 改成 i。", "happily 是 happy 的正確方式副詞。", "happy 是形容詞，不能直接修飾 played。", "happiness 是名詞。"], reviews: ["played 要求方式，happy 的 y 前是子音。", "第二項先改 y 為 i，再加 -ly。"], cognitiveProcess: ["inspect-happy-y-ending", "spell-happily-for-played"], representationType: "y-to-ily-adverb", misconceptionTargets: ["write-happyly"] },
    { stem: "Ben explained the rule ___. (simple)", options: ["simplely", "simpily", "simply", "simple"], answerIndex: 2, reasons: ["simplely 錯誤保留完整 -le 再加 ly。", "simpily 拼錯字尾。", "simply 去掉 e 並把 -le 改成 -ly。", "simple 是形容詞，不能直接修飾 explained。"], reviews: ["空格說明 explained 的方式。", "第三項套用 simple → simply 的 -le 變化。"], cognitiveProcess: ["recognize-simple-le-ending", "form-simply-after-explained"], representationType: "le-to-ly-adverb", misconceptionTargets: ["append-ly-to-full-simple"] },
    { stem: "Grace sings ___. (good)", options: ["good", "goodly", "more good", "well"], answerIndex: 3, reasons: ["good 是形容詞，不能直接說明 sings 的方式。", "goodly 不是此句需要的常見形式。", "more good 不是 good 的方式副詞。", "well 是 good 對應的常見方式副詞。"], reviews: ["sings 是動作，空格評述唱歌表現。", "第四項使用不規則對應，不套一般 -ly。"], cognitiveProcess: ["identify-singing-performance-adverb", "map-good-to-well"], representationType: "good-well-irregular-adverb", misconceptionTargets: ["form-goodly"] },
    { stem: "Nora checked the number ___. (careful)", options: ["carefully", "careful", "carefuly", "care"], answerIndex: 0, reasons: ["carefully 在 careful 後加 -ly，拼字與功能都正確。", "careful 是形容詞，不能直接修飾 checked。", "carefuly 少了一個 l。", "care 不是本句需要的方式副詞。"], reviews: ["the number 是受詞，空格補充檢查方式。", "第一項保留 careful 的雙 l，再加 y。"], cognitiveProcess: ["complete-check-number-with-manner", "spell-carefully-with-double-l"], representationType: "ful-to-fully-adverb", misconceptionTargets: ["drop-l-in-carefuly"] },
    { stem: "Mia found the answer ___. (easy)", options: ["easyly", "easily", "easly", "easiest"], answerIndex: 1, reasons: ["easyly 沒有處理 y 字尾。", "easily 把 y 改成 i，再加 -ly。", "easly 遺漏必要的 i。", "easiest 是形容詞最高級，不表示 found 的方式。"], reviews: ["found 需要方式副詞，easy 的 y 前是子音。", "第二項的字形與句法功能都符合。"], cognitiveProcess: ["apply-y-rule-to-easy", "choose-easily-after-found"], representationType: "easy-to-easily-spelling", misconceptionTargets: ["omit-i-in-easily"] },
    { stem: "The team played ___. (terrible)", options: ["terrible", "terriblely", "terribly", "more terrible"], answerIndex: 2, reasons: ["terrible 是形容詞，不能直接修飾 played。", "terriblely 錯誤保留 e 再加 ly。", "terribly 把 -le 改成 -ly，功能正確。", "more terrible 是形容詞比較形式，不是此處的方式副詞。"], reviews: ["played 的表現需要副詞。", "第三項用 terrible → terribly 的字尾變化。"], cognitiveProcess: ["inspect-terrible-le-ending", "select-terribly-for-team-play"], representationType: "terrible-to-terribly", misconceptionTargets: ["write-terriblely"] },
    { stem: "Leo works ___. (hard)", options: ["hardly", "harder", "hardest", "hard"], answerIndex: 3, reasons: ["hardly 表示幾乎不，會改變句意。", "harder 是比較級，但句中沒有比較。", "hardest 是最高級，需要群體範圍。", "hard 可直接作副詞，表示努力工作。"], reviews: ["題目沒有 than 或群體，也不是接近否定。", "第四項提醒 hard 作方式副詞時形式不變。"], cognitiveProcess: ["separate-hard-from-hardly", "keep-hard-as-manner-adverb"], representationType: "unchanged-hard-adverb", misconceptionTargets: ["add-ly-to-hard"] },
    { stem: "Rain fell ___ during the night. (heavy)", options: ["heavily", "heavyly", "heavy", "heavier"], answerIndex: 0, reasons: ["heavily 把子音後 y 改 i，再加 -ly。", "heavyly 沒有處理 y 字尾。", "heavy 是形容詞，不能直接修飾 fell。", "heavier 是比較級形容詞，沒有比較對象。"], reviews: ["fell 是動作，空格說明降雨方式。", "第一項使用 heavy → heavily 的規則。"], cognitiveProcess: ["apply-y-to-ily-for-heavy", "attach-heavily-to-fell"], representationType: "heavy-to-heavily-transfer", misconceptionTargets: ["write-heavyly"] },
    { stem: "The child smiled ___. (gentle)", options: ["gentlely", "gently", "gentily", "gentle"], answerIndex: 1, reasons: ["gentlely 錯誤保留完整 -le。", "gently 去 e 並形成自然方式副詞。", "gentily 拼錯中間母音。", "gentle 是形容詞，不能直接修飾 smiled。"], reviews: ["smiled 沒有受詞，句尾空格補充方式。", "第二項和 simple → simply 使用相同字尾原理，但字詞與語境不同。"], cognitiveProcess: ["transform-gentle-le-ending", "use-gently-after-smiled"], representationType: "gentle-to-gently", misconceptionTargets: ["write-gentlely"] },
    { stem: "A note says, 'Please walk slowful.' Which choice fixes 'slowful'?", options: ["slow", "slowness", "slowly", "slower"], answerIndex: 2, reasons: ["slow 是形容詞，不能在此直接修飾 walk。", "slowness 是名詞。", "slowly 是 slow 的正常方式副詞。", "slower 是比較級，題目沒有比較。"], reviews: ["slowful 不是標準形式，但意思要保留為走得慢。", "第三項用最基本的加 -ly 修復方式。"], cognitiveProcess: ["diagnose-invented-slowful", "replace-with-slowly-manner"], representationType: "nonword-adverb-repair", misconceptionTargets: ["invent-ful-adverb-ending"] },
    { stem: "The horse can run ___. (fast)", options: ["fastly", "fastest", "more fast", "fast"], answerIndex: 3, reasons: ["fastly 不是一般標準形式。", "fastest 是最高級，句中沒有群體。", "more fast 不是本題的方式副詞形式。", "fast 可直接修飾 run，形式不變。"], reviews: ["can run 是動詞組，空格說明奔跑方式。", "第四項和 hard 一樣屬於不加 -ly 的常見副詞。"], cognitiveProcess: ["identify-fast-as-unchanged-adverb", "complete-can-run-fast"], representationType: "unchanged-fast-adverb", misconceptionTargets: ["form-fastly"] },
  ]),
  ...skillQuestions("129", [
    { stem: "The baby slept ___.", options: ["quietly", "the bed quietly", "quietly the bed", "the quietly bed"], answerIndex: 0, reasons: ["slept 沒有受詞，quietly 可直接放在句尾。", "the bed 不能在此直接接於 slept 後表示方式。", "quietly the bed 形成不完整片語。", "quietly 是副詞，不能直接修飾 bed。"], reviews: ["沒有受詞需要保護時，句尾是最清楚的方式副詞位置。", "第一項只補充 slept 的方式，不增加無關成分。"], cognitiveProcess: ["recognize-intransitive-slept", "place-quietly-at-sentence-end"], representationType: "intransitive-adverb-placement", misconceptionTargets: ["invent-object-after-slept"] },
    { stem: "Which order keeps 'closed' next to its object?", options: ["Mia slowly the door closed.", "Mia closed the door slowly.", "Mia closed slowly the door.", "Mia the door slowly closed."], answerIndex: 1, reasons: ["主詞後的詞序沒有形成正常動詞組。", "closed the door 保持動詞與受詞相連，slowly 放在後面。", "slowly 插入 closed 與 the door 之間，短句不自然。", "the door 被移到主要動詞前，並非本題的一般敘述詞序。"], reviews: ["題目指定檢查動詞 closed 和受詞 the door。", "第二項先完成動作對象，再補充速度。"], cognitiveProcess: ["compare-closed-door-word-orders", "keep-object-before-slowly"], representationType: "verb-object-adverb-order", misconceptionTargets: ["insert-adverb-before-object"] },
    { stem: "Grace can sing ___.", options: ["beautiful", "can beautifully", "beautifully", "a beautiful"], answerIndex: 2, reasons: ["beautiful 是形容詞，不能直接修飾 sing。", "can 已在題幹中，選項會重複助動詞且位置不完整。", "beautifully 放在主要動作 sing 後，說明歌唱方式。", "a beautiful 後需要名詞。"], reviews: ["can sing 是完整動詞組，空格位於組合之後。", "第三項不拆開助動詞與主要動詞。"], cognitiveProcess: ["preserve-can-sing-group", "append-beautifully-after-main-verb"], representationType: "modal-main-verb-adverb-placement", misconceptionTargets: ["split-can-and-sing"] },
    { stem: "Which line uses a comma to separate a manner word placed first?", options: ["Slowly Ben, opened the box.", "Slowly Ben opened, the box.", "Ben, opened the box slowly.", "Slowly, Ben opened the box."], answerIndex: 3, reasons: ["逗點錯放在 Ben 後，沒有分隔句首 slowly。", "逗點切開 opened 與 the box。", "主詞 Ben 與動詞 opened 不應被逗點分開。", "Slowly 放句首，逗點後再接完整主句。"], reviews: ["先找前置的方式副詞 Slowly，再找主句 Ben opened the box。", "第四項只在兩個部分的邊界使用逗點。"], cognitiveProcess: ["locate-fronted-manner-boundary", "punctuate-slowly-before-main-clause"], representationType: "fronted-adverb-punctuation", misconceptionTargets: ["comma-between-subject-and-verb"] },
    { stem: "Nora read the message ___.", options: ["carefully", "carefully the message", "the carefully message", "careful"], answerIndex: 0, reasons: ["carefully 放在受詞 the message 後，修飾 read。", "題幹已有 the message，選項會重複受詞。", "carefully 不能直接修飾 message。", "careful 是形容詞，不表示閱讀方式。"], reviews: ["read the message 已完成動詞與受詞。", "第一項在完整動作組後補上方式，不改變受詞。"], cognitiveProcess: ["complete-read-message-object-group", "place-carefully-after-object"], representationType: "post-object-manner-cloze", misconceptionTargets: ["repeat-object-inside-option"] },
    { stem: "The worker placed the cups ___.", options: ["on carefully the table", "carefully on the table", "the table carefully on", "careful on the table"], answerIndex: 1, reasons: ["carefully 不應插入介系詞 on 與其受詞之間。", "carefully 說明 placed 的方式，on the table 保持完整地點片語。", "詞序沒有形成完整的地點片語。", "careful 是形容詞，不能直接修飾 placed。"], reviews: ["空格同時要容納方式與地點，兩個片語各自保持完整。", "第二項將 carefully 放在 on the table 前，不切斷任何必要成分。"], cognitiveProcess: ["preserve-on-the-table-phrase", "position-carefully-before-location"], representationType: "manner-location-order", misconceptionTargets: ["split-preposition-and-object"] },
    { stem: "A student writes, 'Mia opened slowly the box.' Which change gives the clearest order?", options: ["slowly → slow", "the box → box the", "opened slowly the box → opened the box slowly", "Mia → Mia's"], answerIndex: 2, reasons: ["slow 會變成形容詞，仍未修正位置。", "box the 不是正常名詞片語。", "opened the box 先連接動詞受詞，再放 slowly。", "Mia 已是正確主詞，不需所有格。"], reviews: ["原句要表達的字都足夠，問題在方式副詞切開動詞與受詞。", "第三項只調整順序，沒有改變事件內容。"], cognitiveProcess: ["diagnose-slowly-between-verb-object", "move-adverb-after-the-box"], representationType: "adverb-order-edit", misconceptionTargets: ["change-adverb-form-instead-of-position"] },
    { stem: "The dog barked ___ at night.", options: ["at loudly night", "night loudly at", "loud", "loudly"], answerIndex: 3, reasons: ["at night 是完整時間片語，不能被 loudly 切開。", "詞序沒有形成可理解的時間片語。", "loud 是形容詞，不能直接修飾 barked。", "loudly 放在 barked 後，at night 再提供時間。"], reviews: ["句中同時有方式與時間，但兩者都不需進入另一個片語。", "第四項形成 barked loudly at night 的清楚順序。"], cognitiveProcess: ["separate-manner-from-at-night", "select-loudly-before-time-phrase"], representationType: "manner-before-time-phrase", misconceptionTargets: ["split-at-night"] },
    { stem: "Put the parts in a natural order: carefully / the glass / carried / Ben.", options: ["Ben carried the glass carefully.", "Ben carried carefully the glass.", "Carefully the glass Ben carried.", "The glass carefully carried Ben."], answerIndex: 0, reasons: ["主詞、動詞、受詞、方式副詞依序完整。", "carefully 切開 carried 與 the glass。", "句首 carefully 後缺少逗點，後續詞序也不自然。", "此項把 glass 寫成執行 carried 的主詞。"], reviews: ["先組成 Ben carried the glass，再加入方式。", "第一項保留人物、動作與物品的角色。"], cognitiveProcess: ["assemble-subject-verb-object-first", "append-carefully-to-carried-glass"], representationType: "word-order-construction", misconceptionTargets: ["make-object-the-agent"] },
    { stem: "Which line gives special focus to the careful way Mia carried the bowl?", options: ["Mia careful carried the bowl.", "Carefully, Mia carried the bowl.", "Mia carried carefully the bowl.", "Mia carried the carefully bowl."], answerIndex: 1, reasons: ["careful 是形容詞，且位置不自然。", "Carefully 前置並以逗點分隔，特別強調方式。", "carefully 切開 carried 與 the bowl。", "carefully 不能直接修飾 bowl。"], reviews: ["題目要求的不只是正確，還要把方式放到句首形成焦點。", "第二項前置方式副詞，同時保留完整主句。"], cognitiveProcess: ["identify-fronted-focus-request", "choose-carefully-comma-main-clause"], representationType: "fronted-manner-focus", misconceptionTargets: ["front-adjective-without-comma"] },
    { stem: "The guide explained the map clearly. Which part receives the explanation?", options: ["clearly", "the guide", "the map", "explained clearly"], answerIndex: 2, reasons: ["clearly 是方式，不是接受說明的內容。", "the guide 是執行 explained 的人。", "the map 是 explained 的受詞，也就是被說明的內容。", "explained clearly 是動作加方式，不是名詞受詞。"], reviews: ["副詞放句尾不會改變 explained 與 the map 的動詞受詞關係。", "第三項確認位置安排仍能清楚找出動作對象。"], cognitiveProcess: ["parse-explained-map-object", "separate-object-from-clearly"], representationType: "placement-preserves-object-role", misconceptionTargets: ["mistake-adverb-for-object"] },
    { stem: "A drink card says, 'Mix the water and juice ___.'", options: ["the cup slowly", "slow the cup", "the slowly cup", "slowly"], answerIndex: 3, reasons: ["題幹已給受詞，the cup 會增加未交代的對象。", "slow 是形容詞，且 the cup 不是必要成分。", "slowly 不能直接修飾 cup。", "slowly 放在完整受詞後，清楚說明 mix 的方式。"], reviews: ["the water and juice 已經是 mix 的完整受詞。", "第四項只加入操作速度，適合作為簡短指示。"], cognitiveProcess: ["read-instruction-with-complete-object", "append-slowly-to-mixing-action"], representationType: "instruction-manner-placement", misconceptionTargets: ["add-extra-object-to-instruction"] },
  ]),
  ...skillQuestions("130", [
    { stem: "The tea is ___ hot, but I can still drink it.", options: ["very", "too", "enough", "many"], answerIndex: 0, reasons: ["very 表示溫度高，但可與 still drink it 並存。", "too hot 通常表示熱到不能喝，和後半句衝突。", "enough 應放在 hot 後，且表示達到需求。", "many 不能修飾 hot。"], reviews: ["but I can still drink it 是選詞的決定性結果。", "第一項只提高程度，沒有自動阻止喝茶。"], cognitiveProcess: ["use-still-drink-result", "choose-very-not-too"], representationType: "very-versus-too-context", misconceptionTargets: ["treat-too-as-very"] },
    { stem: "The bag is ___ heavy for the child to carry.", options: ["very", "too", "enough", "many"], answerIndex: 1, reasons: ["very heavy 不必然表示孩子搬不動。", "too heavy 與 for the child to carry 表示重量超過能力。", "enough 要放在 heavy 後。", "many 不修飾形容詞 heavy。"], reviews: ["for the child to carry 指出受限制的行動。", "第二項用 too 將過重和不能搬連接起來。"], cognitiveProcess: ["identify-carrying-limit", "complete-too-heavy-for-child"], representationType: "too-for-person-limit", misconceptionTargets: ["use-very-for-impossible-action"] },
    { stem: "The water is ___ for the fish. (warm / enough)", options: ["enough warm", "very enough warm", "warm enough", "too enough warm"], answerIndex: 2, reasons: ["enough 修飾形容詞時不放在前面。", "very 與 enough 不能用這種順序疊加。", "warm enough 表示溫度達到魚需要的程度。", "too enough 不是標準程度結構。"], reviews: ["空格要組合形容詞 warm 和 enough。", "第三項把 enough 放在形容詞之後。"], cognitiveProcess: ["identify-adjective-enough-order", "form-warm-enough"], representationType: "post-adjective-enough", misconceptionTargets: ["place-enough-before-adjective"] },
    { stem: "There are ___ chairs for every student.", options: ["chairs enough", "very chairs", "too chairs", "enough"], answerIndex: 3, reasons: ["chairs enough 顛倒了名詞與 enough 的位置。", "very 不能直接修飾複數名詞 chairs。", "too chairs 缺少 many。", "enough 放在 chairs 前，表示數量足夠。"], reviews: ["題幹空格在名詞 chairs 前，因此 enough 直接限定數量。", "第四項和 warm enough 的位置規則不同。"], cognitiveProcess: ["locate-quantity-word-before-chairs", "use-enough-before-noun"], representationType: "pre-noun-enough", misconceptionTargets: ["put-enough-after-noun"] },
    { stem: "Leo is too tired to walk home. What does the sentence mean?", options: ["His tiredness stops him from walking home.", "He walks home although he is tired.", "He is tired enough after walking home.", "He walks home very quickly."], answerIndex: 0, reasons: ["too tired to walk 表示疲勞程度阻止步行。", "此項把不能走改成仍然走。", "原句不是說走完後達到疲勞程度。", "句子沒有提供速度。"], reviews: ["too...to 的結果方向是程度過高而無法完成後項。", "第一項保持 tired 與 walk home 的因果限制。"], cognitiveProcess: ["interpret-too-tired-to-walk", "state-prevented-action"], representationType: "too-to-meaning", misconceptionTargets: ["read-too-to-as-although"] },
    { stem: "The room is ___ dark to read in, so we need another light.", options: ["very", "too", "enough", "much"], answerIndex: 1, reasons: ["very dark 只表示很暗，不能自行連到無法閱讀。", "too dark to read 表示暗度已阻礙閱讀。", "enough 應放在 dark 後，而且語意方向不合。", "much 不能直接修飾 dark。"], reviews: ["need another light 提供目前亮度不足的證據。", "第二項把超過可閱讀限度的意思說完整。"], cognitiveProcess: ["connect-extra-light-need-to-darkness", "select-too-dark-to-read"], representationType: "too-to-evidence-context", misconceptionTargets: ["ignore-result-clause"] },
    { stem: "A student writes, 'Nora is enough tall to reach it.' Which change fixes the degree phrase?", options: ["tall → height", "enough → very", "enough tall → tall enough", "reach → reaches"], answerIndex: 2, reasons: ["height 是名詞，不能直接取代 tall。", "very tall 不一定表示已達 reach it 的需求。", "形容詞 tall 要放在 enough 前。", "to 後需保留原形 reach。"], reviews: ["句子要表達身高達標，不是單純很高。", "第三項同時保留 enough 的意思與正確位置。"], cognitiveProcess: ["diagnose-enough-before-tall", "move-enough-after-adjective"], representationType: "enough-order-edit", misconceptionTargets: ["replace-enough-with-very"] },
    { stem: "We do not have ___ time to catch the last bus.", options: ["time enough", "very", "too", "enough"], answerIndex: 3, reasons: ["time enough 不是本題採用的標準名詞順序。", "very 不能直接修飾 time。", "too 單獨不能限定 time，需有 much。", "enough time 表示可用時間是否足夠。"], reviews: ["空格在名詞 time 前，not 將整個足夠狀態否定。", "第四項形成 do not have enough time。"], cognitiveProcess: ["parse-not-have-quantity-gap", "place-enough-before-time"], representationType: "negative-enough-noun-cloze", misconceptionTargets: ["reverse-time-enough-order"] },
    { stem: "The pool rule allows water up to 30°C. Today it is 38°C, so the water is ___.", options: ["too hot", "very enough", "hot enough", "enough hot"], answerIndex: 0, reasons: ["38°C 超過規定上限，too hot 表示過熱。", "very enough 不是標準組合。", "hot enough 表示達到某需求，沒有呈現超過上限。", "enough 應放在形容詞後，且語意方向仍不合。"], reviews: ["先比較實際 38°C 與允許上限 30°C。", "第一項把數值超標轉成 too 的限制意思。"], cognitiveProcess: ["compare-temperature-with-rule-limit", "label-over-limit-as-too-hot"], representationType: "numeric-limit-too-transfer", misconceptionTargets: ["use-enough-for-over-limit"] },
    { stem: "Mia ran ___ to catch the bus.", options: ["enough quickly", "quickly enough", "very enough quickly", "too quickly enough"], answerIndex: 1, reasons: ["enough 修飾副詞 quickly 時放在後面。", "quickly enough 表示速度達到趕上車的需求。", "very enough 不是標準程度組合。", "too 與 enough 同時標示相反方向，結構不合。"], reviews: ["to catch the bus 表示速度需要達成的目標。", "第二項把 enough 放在方式副詞之後。"], cognitiveProcess: ["identify-adverb-enough-target", "form-quickly-enough-to-catch"], representationType: "post-adverb-enough", misconceptionTargets: ["place-enough-before-adverb"] },
    { stem: "The machine moves very slowly. What can we know from this alone?", options: ["It cannot finish the work.", "It is too old to use.", "Its movement has a low speed.", "It will stop in one minute."], answerIndex: 2, reasons: ["very slowly 沒有斷定工作一定無法完成。", "句子沒有提供機器年齡或可用性。", "very slowly 只直接說明移動速度很低。", "句子沒有提供停止時間。"], reviews: ["very 提高 slowly 的程度，但不自動產生不能完成的結果。", "第三項只重述已知速度，不加入故障推論。"], cognitiveProcess: ["limit-inference-from-very-slowly", "retain-low-speed-fact-only"], representationType: "very-inference-boundary", misconceptionTargets: ["infer-impossibility-from-very"] },
    { stem: "A room has 25 chairs for 25 students. Which sentence matches?", options: ["There are very chairs.", "The chairs are enough comfortable.", "There are too chairs.", "There are enough chairs."], answerIndex: 3, reasons: ["very 不能直接限定 chairs。", "enough 修飾 comfortable 時應在後面，而且資料只談數量。", "too 後需要 many，資料也未顯示過多造成問題。", "椅子與學生各 25，數量足夠。"], reviews: ["本題比較供應數和需求數，兩者相等。", "第四項使用 enough + plural noun 表達數量達標。"], cognitiveProcess: ["compare-chair-supply-with-students", "express-sufficient-count-with-enough"], representationType: "capacity-enough-transfer", misconceptionTargets: ["use-enough-as-adjective-prefix"] },
  ]),
  ...skillQuestions("131", [
    { stem: "The train moves ___. (fast)", options: ["fast", "fastly", "a fast", "fastness"], answerIndex: 0, reasons: ["fast 可直接作副詞修飾 moves。", "fast 不加 -ly，fastly 不能完成這個句子。", "a fast 後需要名詞，不能修飾 moves。", "fastness 不是本句需要的方式副詞。"], reviews: ["moves 需要方式說明，但 fast 的副詞形式不變。", "第一項雖沒有 -ly，句法工作仍是副詞。"], cognitiveProcess: ["recognize-fast-after-moves", "keep-fast-form-as-adverb"], representationType: "same-form-fast-adverb", misconceptionTargets: ["require-fastly"] },
    { stem: "Nora studied ___ for the test.", options: ["hardly", "hard", "harder", "a hard"], answerIndex: 1, reasons: ["hardly 表示幾乎沒有讀書，和努力準備不同。", "hard 可直接作副詞，表示用功讀書。", "harder 是比較級，句中沒有比較基準。", "a hard 後需要名詞。"], reviews: ["for the test 提供準備情境，但決定性差異是 hard 與 hardly 的意思。", "第二項表示努力，不會產生接近否定的方向。"], cognitiveProcess: ["contrast-hard-and-hardly-in-study", "choose-hard-for-effort"], representationType: "hard-versus-hardly", misconceptionTargets: ["treat-hardly-as-manner-hard"] },
    { stem: "The bus arrived ___. (late)", options: ["lately", "latest", "late", "more lately"], answerIndex: 2, reasons: ["lately 表示最近一段時間，不是某次晚到。", "latest 是最高級，題目沒有群體。", "late 可直接修飾 arrived，表示到得晚。", "more lately 不是本句需要的形式。"], reviews: ["arrived 指一次到達事件，空格說明時間延遲。", "第三項使用同形副詞 late。"], cognitiveProcess: ["identify-single-arrival-delay", "select-late-not-lately"], representationType: "late-event-adverb", misconceptionTargets: ["use-lately-for-one-late-arrival"] },
    { stem: "I have read many science stories ___.", options: ["late", "latest", "later", "lately"], answerIndex: 3, reasons: ["late 表示晚，不表示最近期間。", "latest 是最高級形容詞或名詞用法。", "later 表示較晚或之後。", "lately 表示最近一段時間，能配合 have read。"], reviews: ["have read many stories 指一段延伸到現在的近期經驗。", "第四項不是某次晚讀，而是最近常讀。"], cognitiveProcess: ["connect-present-perfect-to-recent-period", "choose-lately-time-adverb"], representationType: "lately-recent-period", misconceptionTargets: ["confuse-late-and-lately"] },
    { stem: "Which pair uses 'early' once before a noun and once after an action?", options: ["an early bus / arrived early", "an earlier bus / arrived earliest", "an early bus / arrived earlyly", "an earlyly bus / arrived early"], answerIndex: 0, reasons: ["第一個 early 描述 bus，第二個 early 修飾 arrived。", "earlier 與 earliest 是不同級別，不是同形功能對照。", "earlyly 不是標準形式。", "earlyly 不能放在 bus 前。"], reviews: ["題目要找同一拼字在兩個位置做不同工作。", "第一項清楚展示形容詞與副詞同形。"], cognitiveProcess: ["compare-two-early-syntactic-slots", "select-identical-early-forms"], representationType: "same-form-early-pair", misconceptionTargets: ["invent-earlyly"] },
    { stem: "Ben ___ eats breakfast before school; he does so only once a week.", options: ["hard", "hardly", "harder", "hardest"], answerIndex: 1, reasons: ["hard 會表示用力吃，不符合頻率線索。", "hardly 表示幾乎不，和 once a week 相符。", "harder 是比較級，沒有另一個對象。", "hardest 是最高級，沒有群體範圍。"], reviews: ["only once a week 提供接近沒有的頻率證據。", "第二項在此不是方式，而是接近否定的程度。"], cognitiveProcess: ["use-once-a-week-as-scarcity-evidence", "select-hardly-for-almost-not"], representationType: "hardly-frequency-context", misconceptionTargets: ["read-hardly-as-effort"] },
    { stem: "A note says, 'The guide spoke friendly to us.' Which choice fixes 'friendly'?", options: ["more friendly", "friendliest", "in a friendly way", "a friendly"], answerIndex: 2, reasons: ["more friendly 通常比較人的特質，不能直接修飾 spoke。", "friendliest 是最高級形容詞。", "in a friendly way 能自然說明說話方式。", "a friendly 後需要名詞。"], reviews: ["friendly 主要是形容詞，不能因 -ly 外形直接當方式副詞。", "第三項保留友善意思並建立完整方式片語。"], cognitiveProcess: ["diagnose-friendly-after-spoke", "repair-with-friendly-way-phrase"], representationType: "friendly-manner-repair", misconceptionTargets: ["treat-friendly-as-direct-adverb"] },
    { stem: "Walk ___ until you reach the door.", options: ["straightly", "a straight", "straightest", "straight"], answerIndex: 3, reasons: ["straightly 不是此處常用形式。", "a straight 後需要名詞。", "straightest 是最高級，沒有比較範圍。", "straight 可直接作副詞，表示一直向前。"], reviews: ["Walk 是動作，空格提供方向方式。", "第四項和 fast、hard 一樣，不必加 -ly。"], cognitiveProcess: ["interpret-walking-direction", "use-straight-as-unchanged-adverb"], representationType: "same-form-straight-adverb", misconceptionTargets: ["form-straightly"] },
    { stem: "Class begins at 8:00. Mia arrives at 8:10. Mia arrives ___.", options: ["late", "lately", "latest", "hardly"], answerIndex: 0, reasons: ["8:10 晚於 8:00，所以 late 符合單次遲到。", "lately 表示最近期間，不表示這次晚十分鐘。", "latest 是最高級，沒有比較多人的到達時間。", "hardly 表示幾乎不，不能描述時間差。"], reviews: ["先比較開始與抵達時間，得到晚到十分鐘。", "第一項將數值結果轉成同形副詞 late。"], cognitiveProcess: ["compare-class-and-arrival-times", "label-ten-minute-delay-late"], representationType: "time-data-late-transfer", misconceptionTargets: ["choose-lately-for-clock-delay"] },
    { stem: "Which sentence uses 'lately' to mean 'during the days before now'?", options: ["The train came lately at nine.", "Mia has felt tired lately.", "The late bus is here.", "Please come lately than noon."], answerIndex: 1, reasons: ["某次九點到達應用 late，不用 lately。", "lately 表示最近一段時間，配合 has felt。", "late 在此是形容詞，修飾 bus。", "比較時間應使用 later，且 than 結構不完整。"], reviews: ["days before now 指跨一段近期時間，而不是某一次時刻。", "第二項的現在完成式和 lately 彼此配合。"], cognitiveProcess: ["test-lately-across-four-time-uses", "select-recent-period-sentence"], representationType: "late-lately-sentence-selection", misconceptionTargets: ["use-lately-for-specific-time"] },
    { stem: "Nora was sick yesterday, but she feels ___ today.", options: ["goodly", "betterly", "well", "hard"], answerIndex: 2, reasons: ["goodly 不是本句描述健康的常用形式。", "betterly 不是標準形式。", "well 在 feels 後可表示身體狀況良好。", "hard 不表示健康恢復。"], reviews: ["feels 在此連接 Nora 與健康狀態，不是在說感覺動作的方式。", "第三項顯示 well 除了方式副詞外，也有健康狀態用法。"], cognitiveProcess: ["interpret-feels-as-health-link", "use-well-for-healthy-condition"], representationType: "well-health-adjective-use", misconceptionTargets: ["assume-well-only-adverb"] },
    { stem: "A coach says, 'Practice hard, not hardly.' Why?", options: ["Hard is always an adjective.", "Hardly means more strongly.", "Hard and hardly have the same meaning.", "Hardly would mean almost no practice."], answerIndex: 3, reasons: ["hard 可直接作副詞修飾 practice。", "hardly 不表示更強。", "兩字意思方向不同。", "hardly practice 會接近幾乎不練習。"], reviews: ["教練要的是努力練習，因此必須避開接近否定的 hardly。", "第四項說明換成 -ly 會改變整句意思，而不只是形式。"], cognitiveProcess: ["explain-coach-hard-not-hardly", "identify-almost-no-practice-consequence"], representationType: "metalinguistic-hard-hardly-transfer", misconceptionTargets: ["equate-ly-with-manner"] },
  ]),
  ...skillQuestions("132", [
    { stem: "The red car moved ___ than the blue car. (fast)", options: ["faster", "more fast", "fastest", "fastly"], answerIndex: 0, reasons: ["faster 是 fast 的比較級副詞，可修飾 moved。", "more fast 不是此處標準形式。", "fastest 是最高級，不能只比較兩車。", "fastly 不是一般標準副詞。"], reviews: ["than 與兩車要求方式比較級。", "第一項的 faster 比較的是移動速度，不是車輛大小。"], cognitiveProcess: ["identify-two-car-speed-comparison", "form-adverb-faster"], representationType: "same-form-adverb-comparative", misconceptionTargets: ["use-more-fast"] },
    { stem: "Nora checked the list ___ than before. (carefully)", options: ["carefullier", "more carefully", "most carefully", "carefullyer"], answerIndex: 1, reasons: ["carefullier 錯改 -ly 副詞字尾。", "more carefully 正確比較檢查方式。", "most carefully 是最高級，題目只比較前後。", "carefullyer 直接加 -er 並不合適。"], reviews: ["than before 建立同一人的兩次動作比較。", "第二項在完整副詞前加 more，不再改字尾。"], cognitiveProcess: ["compare-checking-before-and-now", "prefix-more-to-carefully"], representationType: "more-ly-adverb-comparative", misconceptionTargets: ["attach-er-to-carefully"] },
    { stem: "Amy arrived ___ than Ben. (early)", options: ["more early", "earliest", "earlier", "earlyer"], answerIndex: 2, reasons: ["more early 不是本題採用的標準形式。", "earliest 是最高級，不適合兩人。", "earlier 把 y 改成 i 再加 -er。", "earlyer 沒有處理 y 字尾。"], reviews: ["arrived 表示動作，than 指向兩人的抵達時間比較。", "第三項雖和形容詞比較級同形，在此修飾 arrived。"], cognitiveProcess: ["compare-two-arrival-times-with-early", "spell-earlier-as-adverb"], representationType: "early-adverb-comparative", misconceptionTargets: ["write-earlyer"] },
    { stem: "Leo played ___ than last week. (well)", options: ["more well", "best", "gooder", "better"], answerIndex: 3, reasons: ["more well 不是 well 的標準比較級。", "best 是最高級，題目只比較兩個時間。", "gooder 不是標準形式，也把詞性方向混亂。", "better 是 well 的不規則比較級。"], reviews: ["played 需要副詞，than last week 要求比較級。", "第四項使用 well-better-best 的中間形式。"], cognitiveProcess: ["identify-well-as-played-modifier", "choose-irregular-better"], representationType: "well-better-adverb-comparison", misconceptionTargets: ["form-more-well"] },
    { stem: "Mia can type as ___ as Nora. (quickly)", options: ["quickly", "more quickly", "quicklier", "quickest"], answerIndex: 0, reasons: ["as...as 中保留副詞原級 quickly。", "more quickly 是比較級，會破壞同等結構。", "quicklier 不是標準形式。", "quickest 是最高級，不能放在 as...as 中。"], reviews: ["兩個人出現不代表一定要用比較級；句型由兩個 as 決定。", "第一項表示打字速度同等。"], cognitiveProcess: ["recognize-adverb-equality-frame", "keep-quickly-between-as"], representationType: "adverb-as-as-equality", misconceptionTargets: ["insert-comparative-into-as-as"] },
    { stem: "The old computer starts ___ than the new one. (slowly)", options: ["slowlier", "more slowly", "most slowly", "slowlyer"], answerIndex: 1, reasons: ["slowlier 錯改副詞字尾。", "more slowly 正確比較兩台電腦啟動方式。", "most slowly 是最高級，需要三台以上。", "slowlyer 不是標準形式。"], reviews: ["than the new one 明確比較兩個啟動速度。", "第二項保留 slowly 完整形式並在前面加 more。"], cognitiveProcess: ["compare-two-computer-start-speeds", "form-more-slowly"], representationType: "slowly-comparative-cloze", misconceptionTargets: ["form-slowlier"] },
    { stem: "A note says, 'The bike moved more faster today.' Which change is needed?", options: ["moved → moves", "today → tomorrow", "more faster → faster", "bike → bikes"], answerIndex: 2, reasons: ["若事件在 today 已發生，moved 可保留。", "時間詞不是比較級錯誤來源。", "faster 已含 -er，刪除重複的 more。", "主詞單數和 moved 不衝突。"], reviews: ["原句的問題是同一比較級標記兩次。", "第三項保留 fast 的正確副詞比較形式。"], cognitiveProcess: ["diagnose-more-faster", "remove-duplicate-more"], representationType: "double-adverb-comparative-edit", misconceptionTargets: ["change-tense-instead-of-degree"] },
    { stem: "The second group did ___ than the first group. (badly)", options: ["more bad", "baddest", "badlier", "worse"], answerIndex: 3, reasons: ["more bad 沒有形成修飾 did 的標準方式副詞比較。", "baddest 不是 badly 的標準比較級。", "badlier 不是標準形式。", "worse 是 badly 的常見不規則比較級。"], reviews: ["did 需要副詞，than 比較兩組表現。", "第四項不是形容詞 bad 的規則變化，而是不規則形式。"], cognitiveProcess: ["compare-two-group-performance-quality", "map-badly-to-worse"], representationType: "badly-worse-adverb-comparison", misconceptionTargets: ["form-badlier"] },
    { stem: "Mia and Nora ran the same 1 km road. Mia took 5 minutes, and Nora took 6. Mia ran ___.", options: ["faster", "more carefully", "the fastest", "as fast"], answerIndex: 0, reasons: ["相同距離下用時較少，表示 Mia 跑得較快。", "資料沒有比較仔細程度。", "只有兩人，不能用最高級總結群體。", "5 與 6 不相等，不能用 as fast。"], reviews: ["固定距離下，時間 5 小於 6。", "第一項把數值關係轉成方式副詞比較級。"], cognitiveProcess: ["compare-times-on-equal-distance", "infer-mia-ran-faster"], representationType: "rate-data-adverb-comparison", misconceptionTargets: ["treat-longer-time-as-faster"] },
    { stem: "Ben found three errors. Leo found one error in the same report. Leo checked the report ___.", options: ["carefuler than Ben", "more carefully than Ben", "most carefully than Ben", "as carefully Ben"], answerIndex: 1, reasons: ["carefuler 不是方式副詞比較形式。", "錯誤較少支持 Leo 檢查得比 Ben 更仔細。", "most carefully 不能接 than 比較兩人。", "as...as 結構缺少第二個 as，資料也不表示同等。"], reviews: ["同一份 report 與錯誤數提供可比較的結果。", "第二項用 more carefully than 連接檢查方式與兩人。"], cognitiveProcess: ["use-error-count-as-checking-evidence", "select-more-carefully-than-ben"], representationType: "outcome-evidence-adverb-comparative", misconceptionTargets: ["use-adjective-comparative-for-action"] },
    { stem: "Leo works harder than Sam. What can we know from this alone?", options: ["Leo always gets better results.", "Sam never works.", "Leo puts more effort into the work.", "Leo finishes every job first."], answerIndex: 2, reasons: ["較努力不保證每次結果都較好。", "Sam 可能工作，只是努力程度較低。", "harder 直接比較投入工作的努力方式。", "句子沒有提供完成順序。"], reviews: ["方式比較只能支持被比較的方式屬性。", "第三項保留 effort，不擴大到結果、頻率或速度。"], cognitiveProcess: ["limit-inference-from-works-harder", "retain-greater-effort-only"], representationType: "adverb-comparison-inference-boundary", misconceptionTargets: ["infer-results-from-effort"] },
    { stem: "Both speakers read the five lines with no mistakes. Which sentence expresses equal manner?", options: ["Amy read more clearly as Ben.", "Amy read the clearest than Ben.", "Amy read clearly than Ben.", "Amy read as clearly as Ben."], answerIndex: 3, reasons: ["more clearly 應接 than，不接單一 as。", "clearest 是最高級，不能接 than 比較兩人。", "clearly 是原級，不能直接接 than。", "as clearly as 正確表達兩人朗讀清楚程度相同。"], reviews: ["題目明示 both 且結果相同，應使用同等方式比較。", "第四項把副詞原級 clearly 放在兩個 as 之間。"], cognitiveProcess: ["recognize-equal-reading-performance", "form-as-clearly-as"], representationType: "equal-manner-from-shared-outcome", misconceptionTargets: ["use-than-for-equality"] },
  ]),
  ...skillQuestions("133", [
    { stem: "The milk tastes ___.", options: ["sour", "sourly", "a sour", "more sourly"], answerIndex: 0, reasons: ["sour 是形容詞，接在 tastes 後描述牛奶的味道。", "sourly 是副詞，不能在此作主詞補語。", "a sour 缺少被冠詞限定的名詞。", "more sourly 是副詞比較形式，句中沒有比較。"], reviews: ["tastes 在此把 milk 和味道狀態連起來。", "第一項描述主詞，不是在說品嘗動作如何進行。"], cognitiveProcess: ["interpret-tastes-as-linking-verb", "supply-sour-subject-complement"], representationType: "taste-linking-adjective-cloze", misconceptionTargets: ["place-manner-adverb-after-linking-taste"] },
    { stem: "Ben smelled the milk ___ before drinking it.", options: ["careful", "carefully", "a careful", "more careful"], answerIndex: 1, reasons: ["careful 是形容詞，不能直接修飾 smelled 這個動作。", "carefully 說明 Ben 聞牛奶時採取的方式。", "a careful 後需要名詞，不能獨立補入。", "more careful 是形容詞比較形式，句中也沒有比較。"], reviews: ["smelled 後已有受詞 the milk，因此這裡表示實際聞東西的動作。", "第二項修飾動作，而不是把狀態連回 Ben。"], cognitiveProcess: ["read-smelled-with-object-as-action", "choose-carefully-for-smelling-manner"], representationType: "sensory-action-adverb-cloze", misconceptionTargets: ["always-treat-smell-as-linking"] },
    { stem: "The quiet song sounds ___.", options: ["softly", "a soft", "soft", "soft music"], answerIndex: 2, reasons: ["softly 通常修飾動作，不能在此描述 song 的性質。", "a soft 後缺少名詞。", "soft 是形容詞，接在 sounds 後描述歌曲聽起來的狀態。", "soft music 是名詞片語，不能作此處的主詞補語。"], reviews: ["sounds 並非發出某個動作，而是連接 song 與聽覺印象。", "第三項保留形容詞形式來描述主詞。"], cognitiveProcess: ["classify-sounds-as-linking-verb", "attach-soft-quality-to-song"], representationType: "sound-linking-adjective-cloze", misconceptionTargets: ["add-ly-after-sensory-linking-verb"] },
    { stem: "These flowers smell ___.", options: ["sweetly", "sweets", "a sweet", "sweet"], answerIndex: 3, reasons: ["sweetly 是副詞，不能描述 flowers 本身的氣味狀態。", "sweets 是複數名詞，不適合作補語。", "a sweet 是名詞片語，意思與花的氣味不合。", "sweet 是形容詞，表示這些花聞起來很香甜。"], reviews: ["句中沒有聞花的人，smell 是連綴動詞。", "第四項把感官得到的性質連回主詞 flowers。"], cognitiveProcess: ["detect-no-agent-in-flowers-smell", "select-sweet-for-flower-state"], representationType: "smell-linking-adjective-cloze", misconceptionTargets: ["use-sweetly-after-linking-smell"] },
    { stem: "Mia looks tired after the long game. Which sentence uses 'looks' in the same way?", options: ["The room looks clean.", "Mia looks at the clock.", "Ben looks for his bag.", "Nora looks through the window."], answerIndex: 0, reasons: ["looks clean 和 looks tired 都把主詞連到一個狀態。", "looks at 表示觀看時鐘的動作。", "looks for 表示尋找物品。", "looks through 表示從窗戶向外看。"], reviews: ["判斷 looks 的功能要連同後接成分閱讀。", "第一項同樣以形容詞作主詞補語。"], cognitiveProcess: ["compare-four-looks-complements", "match-linking-looks-with-adjective"], representationType: "linking-look-use-match", misconceptionTargets: ["treat-every-look-as-linking"] },
    { stem: "The dog ___ before eating it.", options: ["smelled carefully the food", "smelled the food carefully", "smelled the food careful", "smelled good the food"], answerIndex: 1, reasons: ["carefully 插在動詞與短受詞之間，詞序不自然。", "smelled the food carefully 先保留動詞與受詞，再說明聞的方式。", "careful 是形容詞，不能修飾 smelled。", "good 不能放在 smelled 與受詞之間形成這個意思。"], reviews: ["it 指 food，smelled 是狗實際聞食物的動作。", "第二項同時保留受詞位置與方式副詞。"], cognitiveProcess: ["use-it-reference-to-identify-food", "order-smell-object-before-manner"], representationType: "smell-action-word-order", misconceptionTargets: ["force-linking-good-before-object"] },
    { stem: "A student writes, 'The soup tastes coldly.' Which change fixes the sentence?", options: ["soup → soups", "tastes → tasting", "coldly → cold", "The → A"], answerIndex: 2, reasons: ["單複數不是描述溫度的問題。", "改成 tasting 會破壞完整述語。", "cold 是形容詞，可在 tastes 後描述 soup。", "改冠詞不能修正錯誤的補語形式。"], reviews: ["tastes 是連綴動詞，後面需要狀態形容詞。", "第三項只把副詞改成形容詞，原意不變。"], cognitiveProcess: ["diagnose-coldly-after-linking-tastes", "repair-to-cold-adjective"], representationType: "linking-complement-edit", misconceptionTargets: ["repair-unrelated-subject-or-article"] },
    { stem: "Ben became ___ when he heard the news.", options: ["angrily", "anger", "an angry", "angry"], answerIndex: 3, reasons: ["angrily 是副詞，不能作 became 後的主詞補語。", "anger 是名詞，不能直接描述 Ben 的狀態。", "an angry 後缺少名詞。", "angry 是形容詞，表示 Ben 變得生氣。"], reviews: ["became 表示狀態改變，空格要說明改變後的 Ben。", "第四項直接連接主詞與新狀態。"], cognitiveProcess: ["identify-became-state-change", "choose-angry-resulting-condition"], representationType: "become-linking-adjective-cloze", misconceptionTargets: ["choose-angrily-after-became"] },
    { stem: "Nora looks calm. Nora looks carefully at the map. What changes between the two uses of 'looks'?", options: ["The first links Nora to a state; the second describes an action.", "Both describe the way Nora uses her eyes.", "Both link Nora to the same state.", "The first describes an action; the second links Nora to a state."], answerIndex: 0, reasons: ["looks calm 連接 Nora 與狀態；looks carefully at 則是查看地圖的動作。", "第一句沒有表示使用眼睛的方式。", "第二句的 carefully 修飾查看動作，不是主詞狀態。", "此項把兩句功能顛倒。"], reviews: ["同一個 looks 要依後接成分和整句意思判斷。", "第一項正確區分連綴用法與實義動作。"], cognitiveProcess: ["contrast-two-looks-syntactic-functions", "map-complement-and-at-phrase-to-uses"], representationType: "same-verb-linking-action-contrast", misconceptionTargets: ["assign-one-function-to-every-look"] },
    { stem: "Nora cooks ___.", options: ["good", "well", "a good", "goodness"], answerIndex: 1, reasons: ["good 是形容詞，不能直接修飾 cooks。", "well 是副詞，說明 Nora 烹調的表現。", "a good 後缺少名詞。", "goodness 是名詞，不回答烹調方式。"], reviews: ["cooks 在這裡是動作，不是連綴動詞。", "第二項使用 good 對應的方式副詞 well。"], cognitiveProcess: ["classify-cooks-as-action-verb", "choose-well-for-cooking-performance"], representationType: "action-good-well-cloze", misconceptionTargets: ["use-good-after-action-verb"] },
    { stem: "The cake tastes good. What can we know from this alone?", options: ["The cake is healthy.", "The cake is cheap.", "Its taste is pleasant.", "Everyone will eat it."], answerIndex: 2, reasons: ["good 在此只描述味道，不能證明食物健康。", "句中沒有提供價格。", "tastes good 直接表示味道令人愉快。", "好吃不保證每個人都會吃。"], reviews: ["連綴動詞後的 good 限定在主詞呈現的味道狀態。", "第三項沒有把感官描述擴大成營養、價格或所有人的選擇。"], cognitiveProcess: ["limit-inference-from-tastes-good", "retain-pleasant-taste-only"], representationType: "linking-adjective-inference-boundary", misconceptionTargets: ["infer-health-or-popularity-from-good"] },
    { stem: "A phone card says, 'This model feels ___ in your hand.'", options: ["lightly", "a light", "lightness", "light"], answerIndex: 3, reasons: ["lightly 是方式副詞，不能描述 model 的重量感受。", "a light 表示一盞燈等名詞意思，和手機重量不合。", "lightness 是名詞，不能直接作此處補語。", "light 是形容詞，表示這款手機拿起來很輕。"], reviews: ["feels 在產品描述中連接 model 與使用者感受到的性質。", "第四項描述主詞本身，不是在說觸摸動作很輕。"], cognitiveProcess: ["interpret-feels-as-product-linking-verb", "select-light-weight-condition"], representationType: "product-feel-linking-adjective", misconceptionTargets: ["choose-lightly-for-sensory-state"] },
  ]),
];

export const ENGLISH_U19_VOCABULARY_POLICY = Object.freeze({
  capQuestionBasis: "appendix-5-table-1",
  additionalLearningTerms: ["alone", "anger", "bark", "calm", "coach", "degree", "describe", "effort", "equal", "express", "focus", "gentle", "goodness", "guide", "latest", "lift", "link", "manner", "match", "message", "mix", "model", "movement", "natural", "object", "peaceful", "pleasant", "receive", "result", "soft", "sour", "speed", "state", "sudden"],
  properNames: ["Amy", "Ben", "Grace", "Leo", "Mia", "Nora", "Sam"],
  grammarNotation: ["adjective", "adverb", "angrily", "as", "comma", "comparative", "condition", "description", "earlier", "earliest", "easiest", "easily", "enough", "er", "explanation", "fastness", "friendliest", "friendlily", "gently", "happily", "happiness", "heavier", "heavily", "heaviness", "ily", "km", "L", "le", "lightness", "loudness", "ly", "modify", "noun", "phrase", "politeness", "politer", "quietness", "separate", "simply", "slowness", "suddenness", "terribly", "than", "tiredness", "too", "verb", "very", "worse", "y"],
  malformedDistractors: ["baddest", "badlier", "carefullier", "carefuly", "easly", "gentily", "gentlely", "quicklier", "simpily", "simplely", "slowful", "slowlier", "slowlyer", "terriblely"],
});

export const ENGLISH_U19_SOURCE = Object.freeze({ unitId: UNIT_ID, lectures: ENGLISH_U19_LECTURES, questions: ENGLISH_U19_QUESTIONS, vocabularyPolicy: ENGLISH_U19_VOCABULARY_POLICY });
export const ENGLISH_UNIT_SOURCE = ENGLISH_U19_SOURCE;
