const UNIT_ID = "ENG_R4_U28";

function lecture(id, skillId, content) {
  return { id, skillId, ...content, sections: content.sections.map((section, index) => ({ id: id + "_SEC_" + String(index + 1).padStart(2, "0"), ...section })) };
}

const DIFFICULTIES = ["foundation", "foundation", "foundation", "standard", "standard", "standard", "standard", "advanced", "advanced", "advanced", "transfer", "transfer"];

function skillQuestions(skillNumber, values) {
  if (values.length !== 12) throw new Error("ENG_R4_S" + skillNumber + ": expected 12 authored questions");
  return values.map((value, index) => ({ id: "ENG_R4_Q_" + skillNumber + "_" + String(index + 1).padStart(2, "0"), skillId: "ENG_R4_S" + skillNumber, difficulty: DIFFICULTIES[index], ...value }));
}

export const ENGLISH_U28_LECTURES = [
  lecture("ENG_R4_L_S190", "ENG_R4_S190", {
    objectives: ["能先由冠詞、修飾語、動詞與連綴動詞判斷空格需要的詞性。", "能把句法位置與整句意思交叉檢查，不只靠字尾猜答案。"],
    sections: [
      { title: "名詞位置看前後關係", content: "a、an、the、this、my 等限定語後面常形成名詞片語；若中間已有形容詞，空格通常要放名詞，例如 a clear plan。名詞也常作主詞或受詞，但動名詞也可能占名詞位置，因此判斷的是句中工作，不是只看單字外形。" },
      { title: "形容詞描述名詞或主詞狀態", content: "形容詞可直接放在名詞前，如 a useful map；也可接在 be、look、feel、sound、smell、taste、become 等連綴動詞後，描述主詞的狀態。連綴動詞後若改放方式副詞，往往會錯把狀態當成動作方式。" },
      { title: "副詞補充動作、程度或頻率", content: "副詞可說明動作如何、何時或多常發生，也能修飾形容詞，例如 spoke clearly、very narrow。不是每個動詞後都要副詞：若動詞後需要受詞，就應先補名詞；若是連綴動詞，後面可能需要形容詞。" },
      { title: "位置先縮小範圍，語意再定案", content: "詞性線索只能排除不合位置的形式，最後仍要讀完整句子。The team needs a clear plan 中，空格要名詞且 plan 符合意思；只看到 clear 就選 clearly，或只因某字有 -tion 就選它，都沒有完成語意檢查。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S190_EX_01", prompt: "The club needs a clear ___ before Friday. (plan / clearly)", steps: ["a clear 後面還缺名詞中心。", "plan 可作可數名詞。", "代回後表示社團需要明確計畫。"], answer: "plan", why: "a 與 clear 已經組成限定語和形容詞，後面需要名詞完成 a clear plan。clearly 是副詞，不能在這個位置取代被描述的事物。" },
      { id: "ENG_R4_L_S190_EX_02", prompt: "The baby looks ___. (sleepy / sleepily)", steps: ["looks 在此連接主詞與狀態。", "空格要描述 baby。", "選形容詞 sleepy。"], answer: "sleepy", why: "looks 不是指寶寶用眼睛觀看，而是表示看起來的狀態，所以後面接形容詞 sleepy。sleepily 會說明動作方式，無法完成這個連綴結構。" },
      { id: "ENG_R4_L_S190_EX_03", prompt: "Leo spoke ___ so everyone heard him. (clear / clearly)", steps: ["spoke 表示說話動作。", "空格回答說話方式。", "選方式副詞 clearly。"], answer: "clearly", why: "空格補充 Leo 如何說話，因此 clearly 修飾 spoke。clear 是形容詞，適合描述聲音或訊息本身，不能直接放在這裡說明動作方式。" },
    ],
    misconceptions: [
      { belief: "看到動詞後有空格，就認為一定要填副詞。", whyWrong: "動詞後可能缺受詞，連綴動詞後也可能需要形容詞。", correction: "先判斷空格是受詞、主詞狀態，還是動作修飾語。" },
      { belief: "單字以 -ly 結尾就一定能放進任何副詞位置。", whyWrong: "friendly 等字多作形容詞，而且詞義也可能不合句意。", correction: "用句法位置縮小詞性後，仍須核對實際用法與意思。" },
      { belief: "冠詞後面看到形容詞，就把形容詞當成完整名詞片語。", whyWrong: "a clear 後仍缺少被描述的人或事物。", correction: "確認冠詞、形容詞與名詞中心是否都已出現。" },
      { belief: "只要某個選項有熟悉的字尾，就不必讀完整句子。", whyWrong: "同詞性的多個字仍可能因語意或搭配而只有一個適合。", correction: "先看位置，再把候選形式逐一代回整句。" },
    ],
    checks: [
      { prompt: "The soup smells fresh 中，fresh 描述什麼？", answer: "soup 的狀態", reason: "smells 在此是連綴動詞，fresh 是形容詞補語。" },
      { prompt: "The nurse spoke softly 中，softly 的工作是什麼？", answer: "說明 spoke 的方式", reason: "softly 是方式副詞，不是人物或物品名稱。" },
      { prompt: "a useful tool 中，哪一個字是名詞中心？", answer: "tool", reason: "a 限定整個名詞片語，useful 描述 tool。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S191", "ENG_R4_S191", {
    objectives: ["能辨識 -er、-or、-tion、-ment、-ness 等常見名詞字尾。", "能以冠詞、複數、主詞與受詞位置確認字尾線索，而不把字尾當成絕對規則。"],
    sections: [
      { title: "人物或工具常見 -er 與 -or", content: "teach 變 teacher、visit 變 visitor 時，字尾可把動作轉成做該動作的人；有些 -er 名詞也指工具，如 opener。拼字不是每次直接相加，且 winter、water 等字雖以相同字母結尾，不能據此拆成動詞加人物字尾。" },
      { title: "動作或結果常見 -tion 與 -ment", content: "communicate 與 communication、move 與 movement 展示動詞轉為名詞的關係。這些名詞可作主詞、受詞，或接在 the、a、good 等字後；實際拼字可能改變詞根，不能自行把 -tion 接到每個動詞。" },
      { title: "性質或狀態常見 -ness 與 -ity", content: "kindness、happiness、ability 等名詞用來命名性質、感受或能力。-ness 通常接在形容詞後，但 happy 形成 happiness 時會改 y；-ity 也不是能任意加在所有形容詞後的通用字尾。" },
      { title: "字尾與句法證據要互相支持", content: "看到 -tion 只能先提出名詞假設，還要確認句子是否真的缺名詞。例如 Good communication helps a team 中，communication 是主詞；若空格放在 be 後描述主詞，則可能需要形容詞而不是名詞。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S191_EX_01", prompt: "The ___ showed us the new classroom. (teach)", steps: ["the 後需要人物名詞。", "做 teach 動作的人是 teacher。", "確認單數形式符合 showed。"], answer: "teacher", why: "空格是 showed 的主詞，且指帶大家看教室的人。teach 加人物字尾 -er 形成 teacher；teaching 雖可作名詞，卻不表示這位人物。" },
      { id: "ENG_R4_L_S191_EX_02", prompt: "Their kind___ made the new student feel welcome.", steps: ["their 後需要名詞。", "句意要命名 kind 的性質。", "加 -ness 形成 kindness。"], answer: "kindness", why: "made 前的完整主詞是 Their kindness，表示他們展現的善意。kind 是形容詞，加入 -ness 後才成為可被 their 限定的性質名詞。" },
      { id: "ENG_R4_L_S191_EX_03", prompt: "Good communica___ helps every team share ideas.", steps: ["Good 後缺名詞中心。", "communicate 是動詞詞根。", "使用 communication 作主詞。"], answer: "communication", why: "helps 前需要單數主詞，Good communication 表示良好的溝通。communicate 不能直接接在 Good 後當名詞，-tion 形式才符合句法位置。" },
    ],
    misconceptions: [
      { belief: "任何以 er 結尾的字都表示從事某動作的人。", whyWrong: "water、winter 等字的 er 並不是可拆出的職業字尾。", correction: "先確認是否存在相關詞根與合理的人物或工具意思。" },
      { belief: "動詞後直接加 tion，一定能得到正確名詞。", whyWrong: "拼字常有改變，而且許多動詞使用不同名詞形式。", correction: "把字尾當辨識線索，實際形式要以學過的字族或字典確認。" },
      { belief: "看到名詞字尾就忽略冠詞、單複數與動詞一致。", whyWrong: "詞性正確仍可能因數量或句法不合而不能使用。", correction: "選定名詞後，再檢查整個名詞片語和主要動詞。" },
      { belief: "happiness 可寫成 happyness，因為只要在 happy 後加 ness。", whyWrong: "happy 的子音加 y 字尾在此改成 i。", correction: "使用標準拼法 happiness，不自行保留 y。" },
    ],
    checks: [
      { prompt: "visitor 的 -or 提供哪一種線索？", answer: "人物名詞", reason: "visitor 通常表示前來參訪的人。" },
      { prompt: "movement 在 The movement stopped 中作什麼？", answer: "主詞名詞", reason: "它位於 stopped 前，命名停止的動作或移動。" },
      { prompt: "darkness 和 dark 的詞性有何不同？", answer: "darkness 是名詞；dark 常作形容詞", reason: "-ness 把性質轉成狀態名稱。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S192", "ENG_R4_S192", {
    objectives: ["能辨識 -ful、-less、-ous、-able、-al、-y 等常見形容詞字尾。", "能用名詞前位置與連綴動詞後位置確認形容詞功能。"],
    sections: [
      { title: "-ful 與 -less 提供有無方向", content: "helpful 表示能提供幫助，careless 表示缺少應有的注意。-ful 與 -less 常形成形容詞，但不能機械地加到任何名詞後；同一詞根的兩個形式可能方向相反，仍要靠上下文判斷哪一個符合。" },
      { title: "-ous 與 -al 常標示描述性形式", content: "dangerous、famous、natural 等字常用來描述人、物或情況。字尾能協助辨識形容詞，但 famous 不能拆成一個日常使用的 fame 加簡單規則來臨時拼寫；學習時要把實際字形與句中功能一起記住。" },
      { title: "-able 常帶有可以的方向", content: "usable、washable 等形式常表示某物可以被使用或清洗。這是理解方向的線索，不代表每個動詞都能直接加 -able，也不保證加字尾後不需改拼字。" },
      { title: "-y 可把事物特徵變成描述", content: "rainy、cloudy、noisy 等形容詞可描述具有某種情況的天氣或場所。由 noise 形成 noisy 時會去 e，再加 y；而 day、family 等以 y 結尾的名詞並不因此自動成為形容詞。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S192_EX_01", prompt: "This map is very use___.", steps: ["is very 後需要形容詞。", "句意是地圖能提供幫助。", "use 加 -ful 形成 useful。"], answer: "useful", why: "very 後要接可分程度的形容詞，useful 可描述 map 的功能。use 是名詞或動詞，不能直接在 is very 後完成這個描述。" },
      { id: "ENG_R4_L_S192_EX_02", prompt: "It was a rain___ morning, so we stayed inside.", steps: ["morning 前需要形容詞。", "rain 提供天氣特徵。", "加 y 得到 rainy。"], answer: "rainy", why: "a 與 morning 之間的空格要描述早晨，rainy 表示有雨的。rain 是名詞或動詞，不能直接取代這個形容詞位置。" },
      { id: "ENG_R4_L_S192_EX_03", prompt: "The broken step is danger___ for young children.", steps: ["is 後描述 step。", "danger 是名詞詞根。", "選 dangerous 表示有危險的。"], answer: "dangerous", why: "句子要說破損階梯的性質，dangerous 是形容詞，可接在 is 後。danger 命名危險，dangerously 則說明動作方式，都不合此位置。" },
    ],
    misconceptions: [
      { belief: "看到 ful 就只翻成很多，不必讀前後文。", whyWrong: "不同字的實際意思與搭配仍需由整句確認。", correction: "先用 -ful 判斷形容詞與正向方向，再核對名詞和情境。" },
      { belief: "less 只用於比較級，所以 careless 一定表示比較。", whyWrong: "careless 中的 -less 是缺少的構詞字尾，不是 little 的比較級。", correction: "區分獨立比較字 less 與附在詞根後的 -less。" },
      { belief: "所有表示可以的形容詞都能由動詞直接加 able。", whyWrong: "有些字會改拼法，有些概念使用完全不同的形容詞。", correction: "用 -able 幫助理解已存在的字，不自行創造未確認的形式。" },
      { belief: "只要名詞以 y 結尾，它就是形容詞。", whyWrong: "family、day 等名詞本身也以 y 結尾。", correction: "檢查字根、句中位置及實際詞義，不單看最後一個字母。" },
    ],
    checks: [
      { prompt: "careless 的 -less 表示哪個方向？", answer: "缺少應有的 care", reason: "整個字是形容詞，並非比較級。" },
      { prompt: "natural 在 natural light 中作什麼？", answer: "描述 light", reason: "它位於名詞前，是形容詞修飾語。" },
      { prompt: "noisy 的原始名詞常是哪個字？", answer: "noise", reason: "形成 noisy 時去掉字尾 e 再加 y。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S193", "ENG_R4_S193", {
    objectives: ["能辨識 -ly 方式副詞及 early、fast、hard、daily 等常見同形或例外用法。", "能分辨 friendly 等 -ly 形容詞，以及 hard 與 hardly 的不同方向。"],
    sections: [
      { title: "方式副詞常回答動作如何發生", content: "politely、slowly、carefully 等 -ly 副詞常修飾動詞，回答如何做。判斷時要找它所連接的動作；若字放在名詞前描述人或事物，就可能是形容詞而不是方式副詞。" },
      { title: "頻率與程度也可由副詞表達", content: "usually、often、almost、very 等字不一定描述動作方式，卻仍可修飾動詞、形容詞或整句。只把副詞理解成中文的地並不完整，應觀察它補充的是頻率、程度、時間還是方式。" },
      { title: "沒有 -ly 也可能是副詞", content: "fast、hard、early、late 可直接修飾動作，例如 run fast、work hard、arrive early、come late。不能因為缺少 -ly 就判定它們一定是形容詞；句法位置和要表達的關係更可靠。" },
      { title: "有 -ly 也不保證是方式副詞", content: "friendly 通常是形容詞，daily 可作形容詞或副詞；hardly 表示幾乎不，和 work hard 的努力地不同。遇到熟悉字尾仍要核對字典標記與上下文，避免只按外形分類。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S193_EX_01", prompt: "Nora answered the child polite___.", steps: ["answered 是動作。", "空格說明回答方式。", "polite 變 politely。"], answer: "politely", why: "句子不是描述 Nora 或 child 的個性，而是說明回答的方式，所以使用副詞 politely。polite 放在此處會把形容詞直接接到動作後。" },
      { id: "ENG_R4_L_S193_EX_02", prompt: "The friendly clerk spoke to us. Is friendly an adverb here?", steps: ["friendly 緊接在 clerk 前。", "它描述這位店員。", "判定為形容詞。"], answer: "No. It is an adjective.", why: "friendly 雖然以 -ly 結尾，卻直接修飾名詞 clerk，因此在本句是形容詞。不能只靠最後兩個字母把它分類成副詞。" },
      { id: "ENG_R4_L_S193_EX_03", prompt: "I could hardly hear the radio. Did I hear it easily?", steps: ["hardly 修飾 hear。", "hardly 表示幾乎不。", "因此不是容易聽見。"], answer: "No. I could almost not hear it.", why: "hardly 在這裡不是 hard 的一般加字尾形式，而是表示幾乎不。句子說收音機很難聽見，不能解讀成努力地聽或容易聽到。" },
    ],
    misconceptions: [
      { belief: "所有副詞都必須以 ly 結尾。", whyWrong: "fast、hard、early、late 都能直接修飾動作。", correction: "以句中功能判斷，再確認是否需要特殊字形。" },
      { belief: "所有以 ly 結尾的字都修飾動詞。", whyWrong: "friendly、lovely 等常作形容詞，daily 也可能修飾名詞。", correction: "查看它實際連接的是名詞、動詞還是形容詞。" },
      { belief: "hardly 就是 hard 的方式副詞，可以互換。", whyWrong: "hard 表示努力地，hardly 通常表示幾乎不。", correction: "把兩個字視為不同意思，依句意選擇。" },
      { belief: "副詞只回答如何，不能表達頻率或程度。", whyWrong: "usually、never、very、almost 都有其他修飾功能。", correction: "辨認副詞補充的是方式、頻率、時間或程度。" },
    ],
    checks: [
      { prompt: "We meet daily 中，daily 說明什麼？", answer: "見面的頻率", reason: "它修飾 meet，表示每天。" },
      { prompt: "a daily meeting 中，daily 是哪一詞性？", answer: "形容詞", reason: "它直接描述名詞 meeting。" },
      { prompt: "work hard 與 hardly work 的意思相同嗎？", answer: "不同", reason: "前者是努力工作，後者是幾乎不工作。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S194", "ENG_R4_S194", {
    objectives: ["能用 un-、in-、im-、dis- 等常見否定字首推測詞義方向。", "能辨認字首只是線索，並以詞根與上下文排除 uncle 等假拆解。"],
    sections: [
      { title: "un- 常把原有性質轉向否定", content: "unsafe、unhappy、unfair 等字常可先理解為不安全、不快樂、不公平。這個方向有助於閱讀，但仍要辨認後面的完整詞根；uncle 的 un 並不是附加在 cle 前的否定字首。" },
      { title: "in- 與 im- 會依字形出現", content: "incorrect、incomplete、inactive 使用 in-，impossible、impatient 使用 im-。兩者常帶有不或非的方向，但拼法不能任意互換，也不是每個以 in 或 im 開頭的字都能拆成否定字首。" },
      { title: "dis- 常表示相反、分離或停止", content: "disagree 表示不同意，dishonest 表示不誠實，disappear 表示不再看得見。dis- 提供大方向，但不同詞的精確意思不完全相同，因此不能只用一個中文詞硬套所有例子。" },
      { title: "先拆可確認的詞根，再回到上下文", content: "遇到不熟的字，可先找熟悉詞根，再看字首是否改變方向，最後用前後句驗證。例如 The box is unsafe, so do not touch it 中，警告內容支持 unsafe 的負向解讀；若上下文不支持，就不能只靠字母猜。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S194_EX_01", prompt: "The bridge is unsafe, so the road is closed. What direction does un- add?", steps: ["找出詞根 safe。", "un- 反轉安全方向。", "closed 提供負向情境證據。"], answer: "It makes safe negative.", why: "safe 表示安全，un- 加在前面形成 unsafe，方向變為不安全。後面的 road is closed 也支持這座橋目前不適合通行。" },
      { id: "ENG_R4_L_S194_EX_02", prompt: "Mia disagreed with the plan. Did she share the same idea?", steps: ["找出 agree。", "dis- 改變同意方向。", "判定兩方看法不同。"], answer: "No, she did not share the same idea.", why: "agree 表示同意，disagree 則表示不同意。句子只告訴我們 Mia 不贊成這項計畫，不能再推論她提出了哪個替代方案。" },
      { id: "ENG_R4_L_S194_EX_03", prompt: "The word uncle begins with un. Does un- mean not here?", steps: ["嘗試找可獨立辨識的詞根。", "cle 不是此字中的常見詞根。", "不把 uncle 當成否定構詞。"], answer: "No.", why: "uncle 是完整的親屬名稱，開頭字母剛好是 un，並非在 cle 前加否定字首。這說明外形相同不等於構詞方式相同。" },
    ],
    misconceptions: [
      { belief: "任何以 un 開頭的字都表示原字的相反。", whyWrong: "uncle、under 等字不能用這種方式拆解。", correction: "確認字首後面是否有可辨識且意思相關的完整詞根。" },
      { belief: "in- 和 im- 可以任意交換而不影響拼字。", whyWrong: "實際單字有固定形式，例如 impossible，不寫 inpossible。", correction: "理解共同否定方向，同時記住已確認的標準字形。" },
      { belief: "只要看到否定字首，就能知道整個句子的所有細節。", whyWrong: "字首只提供方向，不說明事件原因、時間或結果。", correction: "用上下文補足範圍，避免加入文章未提供的資訊。" },
      { belief: "dis- 在每個字中都只能逐字翻成不。", whyWrong: "disappear、disconnect 等詞的自然意思可能是消失或分開。", correction: "先抓相反或分離方向，再依完整單字與句子調整。" },
    ],
    checks: [
      { prompt: "impatient 與 patient 的方向相同嗎？", answer: "不同", reason: "im- 在此帶否定方向。" },
      { prompt: "incomplete 表示 complete 已全部達成嗎？", answer: "沒有", reason: "in- 顯示尚不完整。" },
      { prompt: "under 的 un 可以解讀成 not 嗎？", answer: "不可以", reason: "under 不是 un- 加 der 的否定構詞。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S195", "ENG_R4_S195", {
    objectives: ["能在同一字族的名詞、動詞、形容詞與副詞中選出符合空格的形式。", "能同時檢查詞性、拼字、搭配與整句意思。"],
    sections: [
      { title: "先找空格的句法工作", content: "同一字族可能有 care、careful、carefully 等形式。冠詞或所有格後常需要名詞，名詞前或連綴動詞後常需要形容詞，修飾動作時常需要副詞；若空格是主要動作，還要選動詞並處理時態。" },
      { title: "字族形式不一定只加一個固定字尾", content: "choose 變 choice、succeed 變 success、health 變 healthy 時，拼字或詞根會改變。不能看出需要名詞就自行加 -tion，也不能把每個形容詞都變成 -ly；應使用學過的標準形式。" },
      { title: "分詞形容詞還要看感受者與起因", content: "confused 描述感到困惑的人，confusing 描述使人困惑的事物。兩者都可能放在形容詞位置，這時單靠詞性仍無法定案，必須判斷主詞是感受者還是造成感受的來源。" },
      { title: "完成後逐層驗證", content: "把選定形式放回句子，檢查它是否完成必要成分、拼字是否正確、語意是否自然，最後再看時態或單複數。詞性判斷不是獨立小技巧，而是閱讀完整句構的第一層。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S195_EX_01", prompt: "Ben crossed the busy road ___. (safe)", steps: ["crossed 已是主要動詞。", "空格說明過馬路的方式。", "safe 變 safely。"], answer: "safely", why: "句子需要修飾 crossed 的方式副詞，因此使用 safely。safe 可描述 road 或 Ben 的狀態，但不能在這個句尾位置直接說明動作。" },
      { id: "ENG_R4_L_S195_EX_02", prompt: "The directions were ___, so we asked again. (confuse)", steps: ["were 後需要形容詞。", "directions 是造成困惑的來源。", "選 confusing。"], answer: "confusing", why: "指示使人困惑，所以描述指示本身要用 confusing。confused 會描述人的感受；後面的 we asked again 也支持指示造成問題。" },
      { id: "ENG_R4_L_S195_EX_03", prompt: "The team improved its ___ during the project. (communicate)", steps: ["its 後需要名詞。", "空格是 improved 的受詞。", "使用 communication。"], answer: "communication", why: "its 後要接團隊所改善的事物，communication 是符合位置的名詞。communicate 是動詞，communicative 是形容詞，都不能作 improved 的直接受詞。" },
    ],
    misconceptions: [
      { belief: "知道字根中文意思，就可以任選同字族形式。", whyWrong: "不同形式在句中承擔不同工作，位置錯誤仍不成句。", correction: "先標出空格需要的詞性，再比較同字族候選。" },
      { belief: "每個名詞都能由動詞加 tion 形成。", whyWrong: "choice、success 等名詞使用不同字形。", correction: "使用已確認的字族形式，不臨時創造單字。" },
      { belief: "confused 和 confusing 都是形容詞，所以可互換。", whyWrong: "前者通常描述感受者，後者描述造成感受的人事物。", correction: "判斷主詞在情境中是接收感受，還是引發感受。" },
      { belief: "選對詞性後就不必檢查單複數或時態。", whyWrong: "名詞與動詞仍可能因數量、人稱或時間而改變形式。", correction: "完成詞性選擇後，再讀一次整句做文法與語意核對。" },
    ],
    checks: [
      { prompt: "The healthy child 中，healthy 來自哪個名詞？", answer: "health", reason: "health 命名健康，healthy 描述 child。" },
      { prompt: "The news was surprising 中，誰造成驚訝？", answer: "the news", reason: "surprising 描述引發感受的來源。" },
      { prompt: "They spoke politely 中，polite 可以直接取代 politely 嗎？", answer: "不可以", reason: "spoke 需要方式副詞，而不是形容詞。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S196", "ENG_R4_S196", {
    objectives: ["能讀懂 n.、v.、adj.、adv. 等常見字典詞性標記。", "能在一字多詞性時，以句法位置和字典例句確認實際用法。"],
    sections: [
      { title: "先讀詞性標記，再看定義", content: "常見標記 n. 是 noun、v. 是 verb、adj. 是 adjective、adv. 是 adverb。查字時先確認句子需要哪一類，再閱讀該詞性下的定義與例句，能避免看到第一個中文意思就直接套入。" },
      { title: "同一拼法可以有不同詞性", content: "plan 可作名詞或動詞，light 可作名詞、形容詞或動詞，daily 可作形容詞或副詞。字典分列多個標記，是因為同一字形在不同位置會有不同工作；不能把整個單字永久貼上一種詞性。" },
      { title: "字典中的字族條目要分開核對", content: "success n.、successful adj.、successfully adv. 雖共享詞根，仍是不同條目或形式。句子若是 The plan was ___，應查形容詞；若是 finished ___，應查副詞，不能只選自己最熟的拼法。" },
      { title: "標記提供語法，例句確認自然用法", content: "詞性正確不代表意思一定合適。close 可作不同詞性，stand close 中是副詞，a close friend 中是形容詞；若還不確定，就比較字典例句中的位置、搭配與要表達的關係。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S196_EX_01", prompt: "A dictionary shows plan n., v. In 'We plan to leave,' which label should you use?", steps: ["找出主詞 We。", "plan 是句中主要動作。", "選 v. 標記。"], answer: "v.", why: "We 後的 plan 承擔主要動詞，並接 to leave 說明計畫內容，所以應查 v. 的用法。若是 a plan，冠詞才會把它標成名詞。" },
      { id: "ENG_R4_L_S196_EX_02", prompt: "A dictionary shows daily adj., adv. What is daily in 'a daily meeting'?", steps: ["daily 緊接在 meeting 前。", "它描述會議的頻率特徵。", "選 adj. 標記。"], answer: "adj.", why: "daily 直接修飾名詞 meeting，因此這裡使用形容詞條目。若句子是 We meet daily，它會改為修飾 meet 的副詞用法。" },
      { id: "ENG_R4_L_S196_EX_03", prompt: "Entries: health n.; healthy adj. Complete 'Exercise keeps us ___.'", steps: ["keeps us 後描述 us 的狀態。", "需要形容詞。", "從 adj. 條目選 healthy。"], answer: "healthy", why: "keep + object 後的空格描述 us 維持的狀態，所以要用 adj. healthy。health 是名詞，只能命名健康概念，不能直接完成此補語。" },
    ],
    misconceptions: [
      { belief: "字典列在最前面的詞性一定適合目前句子。", whyWrong: "排序不會取代句法判斷，一字多詞性時要選符合位置的條目。", correction: "先分析句中工作，再查對應標記下的定義與例句。" },
      { belief: "一個英文單字只能有一種詞性。", whyWrong: "plan、light、close、daily 都能依位置承擔不同工作。", correction: "把詞性視為單字在特定句子中的功能。" },
      { belief: "查到中文意思相近，就不必看 adj. 或 adv.。", whyWrong: "形容詞和副詞即使中文相近，也不能任意交換位置。", correction: "同時核對意思、詞性與字典例句的搭配。" },
      { belief: "字典縮寫只是附加資訊，考試時不需理解。", whyWrong: "縮寫能直接排除不符合空格句法角色的形式。", correction: "熟悉 n.、v.、adj.、adv.，並用它們定位正確條目。" },
    ],
    checks: [
      { prompt: "n. 代表哪一詞性？", answer: "noun", reason: "它標示名詞條目。" },
      { prompt: "The light bag 中，light 應查哪個標記？", answer: "adj.", reason: "light 直接描述 bag。" },
      { prompt: "They record the talk 中，record 應查哪個標記？", answer: "v.", reason: "record 是主詞 they 執行的動作。" },
    ], assets: [],
  }),
];

export const ENGLISH_U28_QUESTIONS = [
  ...skillQuestions("190", [
    { stem: "The club needs a clear ___ before Friday.", options: ["plan", "planned", "clearly", "planning to"], answerIndex: 0, reasons: ["plan 是名詞，完成 a clear plan。", "planned 是過去式或分詞，不能作此名詞中心。", "clearly 是副詞，不能被 a 限定。", "planning to 後還缺動詞，也不能接在 a clear 後。"], reviews: ["a 與 clear 後面仍缺被描述的事物。", "第一項同時符合名詞位置與社團需要計畫的句意。"], cognitiveProcess: ["u28-s190-identify-noun-center-after-a-clear", "complete-club-plan-noun-phrase"], representationType: "article-adjective-noun-slot", misconceptionTargets: ["choose-adverb-after-adjective"] },
    { stem: "The water became ___ after the rain stopped.", options: ["clearly", "clear", "clearness", "clearing"], answerIndex: 1, reasons: ["clearly 是副詞，不能在此描述 water 的狀態。", "clear 是形容詞，可接在 became 後。", "clearness 是名詞。", "clearing 是動作形式或名詞，句意不合。"], reviews: ["became 是連綴動詞，空格補充 water 後來的狀態。", "第二項能表達雨停後水變清澈。"], cognitiveProcess: ["u28-s190-read-became-as-linking-verb", "select-clear-for-water-state"], representationType: "linking-verb-adjective-cloze", misconceptionTargets: ["use-clearly-after-became"] },
    { stem: "Leo spoke ___ so everyone could hear each word.", options: ["clear", "clearness", "clearly", "cleared"], answerIndex: 2, reasons: ["clear 是形容詞，不能直接修飾 spoke。", "clearness 是名詞，不能說明 Leo 如何說話。", "clearly 是副詞，說明說話方式。", "cleared 是動詞過去式或分詞，意思也不合。"], reviews: ["so 子句說明每個字都能聽清楚，空格要補充 spoke 的方式。", "第三項在詞性與因果語意上都完整。"], cognitiveProcess: ["u28-s190-locate-manner-slot-after-spoke", "choose-clearly-from-hearing-result"], representationType: "action-manner-cloze", misconceptionTargets: ["place-adjective-after-action-verb"] },
    { stem: "Which word is the subject of 'Health matters to every family'?", options: ["every", "matters", "family", "Health"], answerIndex: 3, reasons: ["every 限定 family。", "matters 是主要動詞。", "family 位於介系詞 to 後。", "Health 位於動詞前，是句子談論的主體。"], reviews: ["先找主要動詞 matters，再向前找執行或承擔陳述的成分。", "第四項是名詞主詞，不因位於句首就只靠位置猜測。"], cognitiveProcess: ["u28-s190-find-subject-before-matters", "distinguish-health-from-prepositional-object"], representationType: "sentence-role-identification", misconceptionTargets: ["mistake-nearest-noun-for-subject"] },
    { stem: "The word after 'very' in 'The road is very narrow' works as a ___.", options: ["adjective", "noun", "verb", "article"], answerIndex: 0, reasons: ["narrow 描述 road 的狀態，是形容詞。", "它沒有命名人事物。", "句中主要動詞是 is。", "article 指 a、an、the 等限定詞。"], reviews: ["very 修飾程度，is 將 road 與 narrow 連接。", "第一項能解釋 narrow 為何可以被 very 修飾。"], cognitiveProcess: ["u28-s190-classify-narrow-after-very", "connect-linking-complement-to-adjective-label"], representationType: "part-of-speech-label", misconceptionTargets: ["call-every-word-after-is-a-noun"] },
    { stem: "In 'The bus moved slowly,' slowly tells ___.", options: ["which bus was used", "how the bus moved", "who owned the bus", "what the bus carried"], answerIndex: 1, reasons: ["slowly 不辨認公車種類。", "slowly 說明 moved 的方式。", "句中沒有所有權資訊。", "slowly 不提供載運內容。"], reviews: ["問題要求說明副詞在句中的實際工作。", "第二項只使用 slowly 可支持的方式資訊。"], cognitiveProcess: ["u28-s190-explain-slowly-function", "limit-adverb-information-to-manner"], representationType: "modifier-function-paraphrase", misconceptionTargets: ["treat-adverb-as-noun-detail"] },
    { stem: "The team's ___ surprised the coach.", options: ["successful", "succeed", "success", "successfully"], answerIndex: 2, reasons: ["successful 是形容詞，不能直接被 team's 所有格限定為中心。", "succeed 是動詞。", "success 是名詞，可作 surprised 的主詞。", "successfully 是副詞。"], reviews: ["team's 後需要被擁有或歸屬於隊伍的名詞。", "第三項形成 The team's success，並與單數動詞 surprised 相合。"], cognitiveProcess: ["u28-s190-detect-noun-after-team-possessive", "select-success-as-subject-center"], representationType: "possessive-noun-family-cloze", misconceptionTargets: ["choose-familiar-adjective-after-possessive"] },
    { stem: "The sign gives drivers a ___ message.", options: ["clearly", "clearness", "clearer than", "clear"], answerIndex: 3, reasons: ["clearly 是副詞，不能直接描述 message。", "clearness 是名詞，不能放在另一名詞前表達此性質。", "clearer than 後缺少比較對象。", "clear 是形容詞，描述 message 易於理解。"], reviews: ["a 與 message 已建立名詞片語，空格用形容詞補充訊息性質。", "第四項是唯一能直接形成 a clear message 的完整形式。"], cognitiveProcess: ["u28-s190-fill-clear-adjective-before-message", "reject-adverb-noun-and-incomplete-comparative"], representationType: "prenominal-adjective-selection", misconceptionTargets: ["choose-related-family-form-without-checking-slot"] },
    { stem: "After a linking verb, which form completes 'The milk smells ___'?", options: ["fresh", "freshly", "freshness", "freshen"], answerIndex: 0, reasons: ["fresh 是形容詞，描述 milk 的氣味狀態。", "freshly 是副詞，通常修飾動作。", "freshness 是名詞。", "freshen 是動詞。"], reviews: ["smells 在此不是牛奶主動聞，而是連接主詞與感官狀態。", "第一項正確完成主詞補語。"], cognitiveProcess: ["u28-s190-interpret-smells-as-linking", "choose-fresh-state-complement"], representationType: "sensory-linking-form-selection", misconceptionTargets: ["use-manner-adverb-after-sensory-link"] },
    { stem: "Which blank needs an adverb?", options: ["a ___ answer", "The nurse spoke ___.", "The ___ opened.", "They became ___."], answerIndex: 1, reasons: ["名詞 answer 前通常需要形容詞。", "spoke 後的空格可說明說話方式，需要副詞。", "冠詞與動詞間需要主詞名詞。", "became 後描述主詞狀態，通常需要形容詞。"], reviews: ["四個位置分別測名詞修飾、動作修飾、主詞和主詞補語。", "第二項是唯一明確要求方式副詞的位置。"], cognitiveProcess: ["u28-s190-compare-four-blank-functions", "locate-adverb-slot-after-spoke"], representationType: "slot-type-comparison", misconceptionTargets: ["assume-all-postverb-slots-are-adverbs"] },
    { stem: "In 'The careful student checked the answer twice,' careful describes ___.", options: ["checked", "twice", "student", "answer"], answerIndex: 2, reasons: ["checked 是動作，若修飾它通常需副詞 carefully。", "twice 是次數副詞。", "careful 緊接在 student 前，描述學生。", "answer 與 careful 之間隔著主要動詞。"], reviews: ["看修飾語與名詞的相鄰關係，不因 checked 是動詞就把所有修飾語連給它。", "第三項正確指出形容詞的中心名詞。"], cognitiveProcess: ["u28-s190-link-careful-to-student", "reject-remote-answer-and-verb-attachments"], representationType: "modifier-head-tracing", misconceptionTargets: ["attach-adjective-to-nearest-event"] },
    { stem: "The lights went out ___. Which type of word belongs in the blank?", options: ["noun", "adjective", "verb", "adverb"], answerIndex: 3, reasons: ["went out 已形成完整事件，不缺名詞受詞。", "形容詞不能直接說明 went out 的方式或時間。", "句中已有主要動詞 went。", "副詞可補充燈何時或如何熄滅。"], reviews: ["went out 是不及物片語，句尾空格應加事件修飾語。", "第四項可容納 suddenly、yesterday 等不同副詞資訊。"], cognitiveProcess: ["u28-s190-analyze-complete-phrasal-event", "classify-final-light-event-slot-as-adverbial"], representationType: "open-slot-category-reasoning", misconceptionTargets: ["seek-object-after-intransitive-phrasal-verb"] },
  ]),
  ...skillQuestions("191", [
    { stem: "The ___ gave us clear directions. (teach)", options: ["teacher", "teaching", "teach", "teachly"], answerIndex: 0, reasons: ["teacher 是做教學工作的人，可作 gave 的主詞。", "teaching 命名教學活動，不是此處指路的人。", "teach 是動詞原形。", "teachly 不是標準形式。"], reviews: ["The 後的空格要指能給 directions 的人物。", "第一項使用 -er 形成自然人物名詞。"], cognitiveProcess: ["u28-s191-form-teacher-as-person-noun", "match-agent-noun-to-gave-directions"], representationType: "agent-noun-cloze", misconceptionTargets: ["use-gerund-for-person"] },
    { stem: "The word 'movement' ends with a suffix that often forms a ___.", options: ["preposition", "noun", "question word", "article"], answerIndex: 1, reasons: ["-ment 不形成介系詞。", "-ment 常把動作或狀態轉成名詞。", "疑問詞不是由此字尾形成。", "冠詞只有 a、an、the。"], reviews: ["move 與 movement 顯示動詞到名詞的字族關係。", "第二項說明 movement 為何能作主詞或受詞。"], cognitiveProcess: ["u28-s191-read-ment-as-noun-suffix", "map-move-to-movement-category"], representationType: "suffix-category-identification", misconceptionTargets: ["classify-suffix-by-word-position-alone"] },
    { stem: "Her ___ made the new student feel welcome. (kind)", options: ["kindly", "kinder", "kindness", "kind"], answerIndex: 2, reasons: ["kindly 是副詞。", "kinder 是比較級形容詞。", "kindness 是性質名詞，可被 Her 限定。", "kind 是形容詞或種類名詞，但此處要命名善意。"], reviews: ["Her 後的完整成分是 made 的主詞。", "第三項用 -ness 將 kind 轉成符合位置的抽象名詞。"], cognitiveProcess: ["u28-s191-build-kindness-after-possessive", "use-quality-noun-as-cause-subject"], representationType: "quality-noun-word-family", misconceptionTargets: ["choose-kindly-because-action-follows"] },
    { stem: "The class had a long ___ about the new rule. (discuss)", options: ["discuss", "discussing", "discussed", "discussion"], answerIndex: 3, reasons: ["discuss 是動詞，不能接在 a long 後作中心。", "discussing 在此不如標準事件名詞自然。", "discussed 是過去式或分詞，不能作此名詞中心。", "discussion 是名詞，可接 about。"], reviews: ["a long 與 about the new rule 共同要求一個討論事件名詞。", "第四項使用實際字形 discussion，而非直接在 discuss 後亂加字尾。"], cognitiveProcess: ["u28-s191-select-discussion-for-a-long-frame", "recognize-spelling-change-before-ion"], representationType: "event-noun-cloze", misconceptionTargets: ["insert-base-verb-after-article"] },
    { stem: "Which ending most often helps name a person who does an action?", options: ["-er", "-ly", "-ful", "-ness"], answerIndex: 0, reasons: ["-er 可見於 teacher、worker 等人物名詞。", "-ly 常見於副詞。", "-ful 常形成形容詞。", "-ness 常命名性質或狀態。"], reviews: ["題目問的是常見線索，不宣稱所有 -er 字都能如此拆解。", "第一項符合動作執行者的構詞方向。"], cognitiveProcess: ["u28-s191-choose-agentive-er-ending", "contrast-person-suffix-with-other-categories"], representationType: "suffix-function-contrast", misconceptionTargets: ["treat-ly-as-person-ending"] },
    { stem: "In 'Darkness covered the road,' darkness names ___.", options: ["an action done by the road", "the state of being dark", "a person who makes light", "the way something moves"], answerIndex: 1, reasons: ["road 沒有執行 darkness。", "-ness 將 dark 的性質命名為狀態。", "darkness 不指人物。", "它不是方式副詞。"], reviews: ["darkness 位於 covered 前，是造成視線受影響的主詞名詞。", "第二項保留 dark 與 -ness 的字族關係。"], cognitiveProcess: ["u28-s191-interpret-darkness-as-state-noun", "exclude-agent-and-manner-readings"], representationType: "derived-noun-meaning-direction", misconceptionTargets: ["read-ness-word-as-adverb"] },
    { stem: "Which form can be the subject of '___ is important during a fire'? (inform)", options: ["Inform", "Informative", "Information", "Informing us to"], answerIndex: 2, reasons: ["Inform 是命令或動詞原形。", "Informative 是形容詞。", "Information 是不可數名詞，可作主詞。", "Informing us to 結構未完成。"], reviews: ["is 前需要一個完整單數或不可數主詞。", "第三項是標準名詞形式，且符合火災時資訊重要的句意。"], cognitiveProcess: ["u28-s191-select-information-as-is-subject", "distinguish-noun-from-informative-adjective"], representationType: "subject-form-selection", misconceptionTargets: ["use-adjective-as-bare-subject"] },
    { stem: "The word 'visitor' is built from visit plus ___.", options: ["-ly", "-ful", "-ness", "-or"], answerIndex: 3, reasons: ["visitly 不是人物名詞。", "visitful 不是標準形式。", "visitness 不是標準人物名稱。", "visitor 使用 -or 形成來訪者。"], reviews: ["題目要求辨認實際字形，不是自行發明規則。", "第四項能保留 visit 詞根並得到 visitor。"], cognitiveProcess: ["u28-s191-segment-visitor-into-visit-or", "identify-or-person-ending"], representationType: "word-segmentation", misconceptionTargets: ["assume-all-agent-nouns-use-er"] },
    { stem: "Their ___ helped both teams finish the project. (agree)", options: ["agreement", "agreeable", "agree", "agreeing to"], answerIndex: 0, reasons: ["agreement 是名詞，可被 Their 限定並作主詞。", "agreeable 是形容詞。", "agree 是動詞。", "agreeing to 後缺少內容，也不合 Their 後的中心。"], reviews: ["helped 前的主詞要命名雙方達成的共識。", "第一項使用 -ment 形成 agreement，句法與事件關係都完整。"], cognitiveProcess: ["u28-s191-form-agreement-as-causal-subject", "fit-ment-noun-after-possessive"], representationType: "agreement-context-cloze", misconceptionTargets: ["use-base-verb-after-their"] },
    { stem: "Which sentence uses 'happiness' as the subject?", options: ["The child happiness smiled.", "Her happiness filled the room.", "She spoke happinessly.", "The news was happiness."], answerIndex: 1, reasons: ["child 才位於 smiled 前的主詞位置，happiness 插入後破壞結構。", "Her happiness 是名詞片語，作 filled 的主詞。", "happinessly 不是標準副詞，也不是主詞。", "The news 是主詞，happiness 位於 was 後。"], reviews: ["題目指定 subject，不只要求看見名詞形式。", "第二項同時呈現所有格限定與完整主詞功能。"], cognitiveProcess: ["u28-s191-find-happiness-as-subject", "distinguish-subject-position-from-predicate-noun"], representationType: "noun-subject-sentence-comparison", misconceptionTargets: ["count-any-noun-position-as-subject"] },
    { stem: "The suffix in 'ability' helps show that the word is a ___.", options: ["verb", "adverb", "noun", "conjunction"], answerIndex: 2, reasons: ["ability 不表示動作。", "它不修飾動詞。", "-ity 常形成性質或狀態名詞。", "它不連接子句。"], reviews: ["ability 可接在 an ability 或 her ability 中，也能作主詞。", "第三項符合字尾與句法證據。"], cognitiveProcess: ["u28-s191-classify-ability-via-ity", "confirm-abstract-noun-function"], representationType: "ity-noun-label", misconceptionTargets: ["confuse-ity-with-adverb-ending"] },
    { stem: "Which ending changes 'kind' into the name of a quality?", options: ["-ly", "-ful", "-er", "-ness"], answerIndex: 3, reasons: ["kindly 常作副詞。", "kindful 不是本題的標準字。", "kinder 是比較級形容詞，不會命名這項性質。", "kindness 命名善意這項性質。"], reviews: ["name of a quality 指名詞，而不是描述方式或比較程度。", "第四項產生實際名詞 kindness。"], cognitiveProcess: ["u28-s191-transform-kind-to-quality-name", "choose-ness-over-adverb-and-comparative-endings"], representationType: "root-to-quality-noun", misconceptionTargets: ["select-er-as-general-noun-marker"] },
  ]),
  ...skillQuestions("192", [
    { stem: "This map is ___ when we visit a new town. (use)", options: ["useful", "usefully", "use", "usefulness"], answerIndex: 0, reasons: ["useful 是形容詞，可接在 is 後描述 map。", "usefully 是副詞。", "use 是名詞或動詞，不能在此描述狀態。", "usefulness 是名詞。"], reviews: ["is 後需要主詞補語，情境說地圖能提供幫助。", "第一項的 -ful 形式同時符合位置與意思。"], cognitiveProcess: ["u28-s192-form-useful-after-is", "describe-map-function-with-ful-adjective"], representationType: "ful-adjective-cloze", misconceptionTargets: ["choose-usefulness-after-linking-verb"] },
    { stem: "The broken bridge is ___ at night. (danger)", options: ["danger", "dangerous", "dangerously", "endanger"], answerIndex: 1, reasons: ["danger 是名詞。", "dangerous 是形容詞，描述 bridge。", "dangerously 是副詞，需修飾動作。", "endanger 是動詞，表示使陷入危險。"], reviews: ["is 後的空格說明破橋的性質，不是另一個動作。", "第二項用 -ous 形成適當形容詞。"], cognitiveProcess: ["u28-s192-select-dangerous-for-bridge-state", "separate-danger-family-functions"], representationType: "ous-adjective-word-family", misconceptionTargets: ["put-danger-noun-after-is"] },
    { stem: "The cup can be washed many times, so it is ___.", options: ["wash", "washing", "washable", "washedly"], answerIndex: 2, reasons: ["wash 是動詞原形。", "washing 表示進行或活動。", "washable 表示可以清洗的。", "washedly 不是標準形式。"], reviews: ["can be washed 提供 -able 所需的可以被清洗方向。", "第三項將前半句濃縮成杯子的形容詞性質。"], cognitiveProcess: ["u28-s192-infer-washable-from-can-be-washed", "map-passive-possibility-to-able-adjective"], representationType: "able-paraphrase-selection", misconceptionTargets: ["confuse-washing-activity-with-property"] },
    { stem: "It was a ___ morning, so every road was wet. (rain)", options: ["rain", "rained", "raining", "rainy"], answerIndex: 3, reasons: ["rain 是名詞或動詞，不能直接修飾 morning。", "rained 是過去式，不能放在此名詞前位置。", "raining 不能放在 a 與 morning 間作一般描述。", "rainy 是形容詞，表示有雨的。"], reviews: ["a 與 morning 之間需要形容詞，後文 wet 支持有雨情境。", "第四項使用 rain + y 的標準形式。"], cognitiveProcess: ["u28-s192-form-rainy-before-morning", "use-wet-roads-as-weather-evidence"], representationType: "y-weather-adjective", misconceptionTargets: ["place-raining-before-noun"] },
    { stem: "Which suffix in 'helpful' shows an adjective?", options: ["-ful", "-er", "-tion", "-ly"], answerIndex: 0, reasons: ["-ful 常形成表示具有某種特質的形容詞。", "-er 常見於人物名詞或比較級。", "-tion 常形成名詞。", "-ly 多半指向副詞，並不是 helpful 的字尾。"], reviews: ["help 是詞根，題目要求辨認後接的構詞部分。", "第一項能解釋 helpful 為何可描述 person、idea 或 tool。"], cognitiveProcess: ["u28-s192-isolate-ful-in-helpful", "contrast-adjective-ending-with-noun-and-adverb-endings"], representationType: "adjective-suffix-identification", misconceptionTargets: ["read-final-letter-only"] },
    { stem: "In 'a careless mistake,' which part adds the direction 'without enough care'?", options: ["care", "-less", "mis-", "-ful"], answerIndex: 1, reasons: ["care 提供注意的核心概念，沒有否定方向。", "-less 表示缺少應有的 care。", "mistake 的開頭不是本題要分析的字首。", "-ful 會形成相反的有注意方向。"], reviews: ["題目問的是 careless 內部的構詞，不是 mistake 的拼法。", "第二項提供缺少的語意並保留形容詞功能。"], cognitiveProcess: ["u28-s192-segment-careless-negative-suffix", "distinguish-root-from-less-direction"], representationType: "less-suffix-direction", misconceptionTargets: ["treat-less-as-comparative-word"] },
    { stem: "The music from the next room was very ___. (noise)", options: ["noise", "noisily", "noisy", "noised"], answerIndex: 2, reasons: ["noise 是名詞。", "noisily 是副詞，不能接在 was very 後描述 music。", "noisy 是形容詞，且 noise 形成時去 e 加 y。", "noised 不是此處的自然形式。"], reviews: ["very 後需形容詞，主詞 music 是產生噪音的來源。", "第三項兼顧詞性、拼字和情境。"], cognitiveProcess: ["u28-s192-transform-noise-to-noisy", "fit-y-adjective-after-very"], representationType: "e-drop-y-adjective", misconceptionTargets: ["retain-noise-as-adjective"] },
    { stem: "Which word can naturally stand before 'decision'?", options: ["danger", "dangerously", "endanger", "dangerous"], answerIndex: 3, reasons: ["danger 是名詞，放在此處會形成不同且不自然的關係。", "dangerously 是副詞，不能直接放在 decision 前。", "endanger 是動詞，無法作這個前置修飾語。", "dangerous 是形容詞，可描述 decision。"], reviews: ["空格位於名詞 decision 前，題目還要求自然描述決定的性質。", "第四項是唯一可直接作前置形容詞的形式。"], cognitiveProcess: ["u28-s192-select-dangerous-before-decision", "compare-four-danger-family-roles"], representationType: "prenominal-family-selection", misconceptionTargets: ["choose-adverb-before-noun"] },
    { stem: "The new student found the class notes very ___. (help)", options: ["helpful", "helpfully", "helper", "helpfulness"], answerIndex: 0, reasons: ["helpful 是形容詞，作 notes 的受詞補語。", "helpfully 是副詞。", "helper 是人物名詞。", "helpfulness 是抽象名詞。"], reviews: ["found + object + very ___ 描述 notes 具有的性質。", "第一項能表達筆記對新生有幫助。"], cognitiveProcess: ["u28-s192-complete-found-notes-helpful", "identify-object-complement-adjective"], representationType: "object-complement-word-family", misconceptionTargets: ["treat-very-slot-as-adverb-only"] },
    { stem: "The weather became ___ before noon. (cloud)", options: ["cloud", "cloudy", "clouds", "clouding"], answerIndex: 1, reasons: ["cloud 是名詞或動詞。", "cloudy 是形容詞，可描述 weather。", "clouds 是複數名詞或第三人稱動詞。", "clouding 是進行形式，句法與意思不合。"], reviews: ["became 指天氣狀態改變，空格應接形容詞。", "第二項使用 cloud + y，表示多雲的。"], cognitiveProcess: ["u28-s192-form-cloudy-after-became", "read-weather-change-as-adjective-complement"], representationType: "weather-state-word-formation", misconceptionTargets: ["use-cloud-noun-as-state"] },
    { stem: "Which word carries the adjective ending '-al'?", options: ["nature", "naturally", "natural", "naturalness"], answerIndex: 2, reasons: ["nature 是名詞。", "naturally 是副詞，完整字尾為 -ally。", "natural 是形容詞，使用 -al。", "naturalness 是名詞。"], reviews: ["題目要求辨認以 -al 結束的形容詞本身。", "第三項可出現在 natural light 或 looks natural 中。"], cognitiveProcess: ["u28-s192-identify-al-ending-in-natural", "separate-natural-from-derived-adverb-and-noun"], representationType: "al-adjective-recognition", misconceptionTargets: ["choose-longest-related-form"] },
    { stem: "This glass may break if it falls, so it is ___.", options: ["break", "breaking", "brokenly", "breakable"], answerIndex: 3, reasons: ["break 是動詞。", "breaking 表示動作進行，不是物品性質。", "brokenly 不是標準描述。", "breakable 表示可能被打破或容易破的。"], reviews: ["may break 提供 glass 具有可破性，而不是說它現在已破。", "第四項用 -able 將可能性轉成形容詞。"], cognitiveProcess: ["u28-s192-infer-breakable-property-from-may-break", "distinguish-potential-from-current-breaking"], representationType: "property-from-event-possibility", misconceptionTargets: ["use-participle-for-general-property"] },
  ]),
  ...skillQuestions("193", [
    { stem: "In 'Nora spoke politely to the visitor,' politely is a ___.", options: ["adverb", "noun", "adjective", "preposition"], answerIndex: 0, reasons: ["politely 修飾 spoke，說明說話方式，是副詞。", "它不命名人事物。", "它沒有直接描述 Nora 或 visitor。", "它不建立名詞間關係。"], reviews: ["找出 politely 實際連接的動作 spoke。", "第一項符合 -ly 線索與句中功能。"], cognitiveProcess: ["u28-s193-classify-politely-modifying-spoke", "confirm-ly-manner-adverb"], representationType: "adverb-label-in-context", misconceptionTargets: ["call-ly-word-adjective"] },
    { stem: "Which word tells how often the event happens in 'We usually meet after lunch'?", options: ["after", "usually", "lunch", "meet"], answerIndex: 1, reasons: ["after 建立時間關係。", "usually 表示事件發生的頻率。", "lunch 是名詞。", "meet 是主要動詞。"], reviews: ["問題問 how often，而不是何時或做什麼。", "第二項是頻率副詞，沒有 -ly 方式的意思。"], cognitiveProcess: ["u28-s193-locate-usually-as-frequency-marker", "distinguish-frequency-from-time-phrase"], representationType: "frequency-adverb-identification", misconceptionTargets: ["limit-adverbs-to-manner"] },
    { stem: "In 'The train arrived early,' early works as an ___.", options: ["article", "adjective", "adverb", "object"], answerIndex: 2, reasons: ["early 不是 a、an、the。", "它沒有修飾名詞。", "early 修飾 arrived，說明抵達時間。", "arrived 在此不帶受詞。"], reviews: ["early 雖無 -ly 方式字尾，仍可修飾動作。", "第三項以句法功能而非外形分類。"], cognitiveProcess: ["u28-s193-classify-early-after-arrived", "recognize-unmarked-time-adverb"], representationType: "non-ly-adverb-classification", misconceptionTargets: ["require-ly-for-every-adverb"] },
    { stem: "Which word is usually an adjective even though it ends in '-ly'?", options: ["slowly", "carefully", "quietly", "friendly"], answerIndex: 3, reasons: ["slowly 通常是方式副詞。", "carefully 通常修飾動作。", "quietly 通常修飾動作。", "friendly 通常描述人、行為或氣氛，是形容詞。"], reviews: ["題目要求辨認常見例外，不是否定所有 -ly 線索。", "第四項可放在 a friendly clerk 或 seems friendly。"], cognitiveProcess: ["u28-s193-identify-friendly-ly-adjective", "contrast-lexical-exception-with-manner-adverbs"], representationType: "ly-exception-selection", misconceptionTargets: ["classify-by-ending-only"] },
    { stem: "The child waited ___ outside the office. (patient)", options: ["patiently", "patient", "patience", "more patient"], answerIndex: 0, reasons: ["patiently 是副詞，說明 waited 的方式。", "patient 是形容詞。", "patience 是名詞。", "more patient 是比較級形容詞，句中沒有比較。"], reviews: ["outside the office 提供地點，空格另補等待方式。", "第一項使用 patient 的方式副詞形式。"], cognitiveProcess: ["u28-s193-fill-waited-with-patiently", "separate-manner-from-location"], representationType: "manner-and-place-cloze", misconceptionTargets: ["put-adjective-after-waited"] },
    { stem: "In 'I could hardly hear the radio,' hardly means ___.", options: ["with much effort", "almost not", "in a hard voice", "every day"], answerIndex: 1, reasons: ["with much effort 對應 hard，不是 hardly。", "hardly 表示幾乎不，句意是很難聽見。", "句中沒有聲音質地的描述。", "它不表示頻率。"], reviews: ["hardly 是需要整體記憶的常見副詞，不能按 hard + ly 直譯。", "第二項符合 could hardly hear 的低程度。"], cognitiveProcess: ["u28-s193-interpret-hardly-as-almost-not", "contrast-hard-effort-with-hardly-degree"], representationType: "false-friend-adverb-meaning", misconceptionTargets: ["derive-hardly-from-hard-mechanically"] },
    { stem: "Which sentence uses 'fast' as an adverb?", options: ["The fast train is full.", "We ordered fast food.", "The train moves fast.", "The fast is over."], answerIndex: 2, reasons: ["fast 修飾名詞 train，是形容詞。", "fast 修飾 food，也是形容詞。", "fast 修飾 moves，說明移動方式，是副詞。", "fast 在此被當成名詞，與本題用法不同。"], reviews: ["相同字形要依它修飾的中心判斷詞性。", "第三項把 fast 連到動詞 moves。"], cognitiveProcess: ["u28-s193-find-fast-modifying-moves", "compare-adjective-and-adverb-homographs"], representationType: "same-form-function-comparison", misconceptionTargets: ["assign-one-fixed-part-of-speech-to-fast"] },
    { stem: "Which form tells how Ben completed the work? (careful)", options: ["care", "careful", "carefulness", "carefully"], answerIndex: 3, reasons: ["care 是名詞或動詞。", "careful 是形容詞。", "carefulness 是名詞。", "carefully 是副詞，能說明 completed 的方式。"], reviews: ["how Ben completed 指向動作修飾，不是在描述 work 的性質。", "第四項是該字族的方式副詞。"], cognitiveProcess: ["u28-s193-select-carefully-for-completed", "map-how-question-to-adverb-form"], representationType: "word-family-manner-selection", misconceptionTargets: ["choose-careful-from-shared-meaning"] },
    { stem: "In 'We have a daily meeting,' daily works as an ___.", options: ["adjective", "adverb", "verb", "pronoun"], answerIndex: 0, reasons: ["daily 直接描述 meeting，是形容詞。", "它在本句沒有修飾 have。", "have 才是主要動詞。", "daily 不代替名詞。"], reviews: ["同一字可有多詞性；這裡以名詞前位置決定。", "第一項說明 daily meeting 是每天舉行的會議。"], cognitiveProcess: ["u28-s193-classify-daily-before-meeting", "distinguish-daily-adjective-from-frequency-adverb"], representationType: "daily-dual-function-adjective", misconceptionTargets: ["assume-daily-always-adverb"] },
    { stem: "In 'The shop closes daily,' daily tells ___.", options: ["which shop it is", "how often it closes", "who closes it", "what it sells"], answerIndex: 1, reasons: ["daily 不辨認商店。", "daily 修飾 closes，表示每天。", "句中沒有行動者姓名。", "它不提供商品內容。"], reviews: ["daily 位於完整動詞後，這次不是修飾名詞。", "第二項正確解讀頻率副詞功能。"], cognitiveProcess: ["u28-s193-interpret-daily-after-closes", "extract-frequency-without-extra-shop-details"], representationType: "daily-dual-function-adverb", misconceptionTargets: ["carry-prenominal-reading-into-postverb-slot"] },
    { stem: "Which word is the adverb in 'The very tired runner walked slowly'?", options: ["tired", "runner", "slowly", "walked"], answerIndex: 2, reasons: ["tired 是形容詞，描述 runner。", "runner 是名詞。", "slowly 是副詞，修飾 walked。", "walked 是動詞。"], reviews: ["very 也是程度副詞，但選項中要找的是 slowly；題目有唯一可選答案。", "第三項直接說明走路方式。"], cognitiveProcess: ["u28-s193-identify-slowly-among-content-words", "separate-adverb-from-adjective-noun-verb"], representationType: "part-of-speech-sentence-scan", misconceptionTargets: ["choose-tired-because-very-precedes-it"] },
    { stem: "The bus came late. Which description fits 'late' here?", options: ["a noun naming the bus", "an adjective before a noun", "a verb showing travel", "an adverb about the time the bus came"], answerIndex: 3, reasons: ["late 不命名 bus。", "它沒有放在名詞前。", "came 才是動詞。", "late 修飾 came，說明抵達時間。"], reviews: ["late 和 early 一樣，不加 -ly 也能作時間副詞。", "第四項精確指出它與 came 的時間關係。"], cognitiveProcess: ["u28-s193-explain-late-after-came", "recognize-time-adverb-without-suffix"], representationType: "late-function-description", misconceptionTargets: ["classify-late-only-as-adjective"] },
  ]),
  ...skillQuestions("194", [
    { stem: "The note says the path is unsafe. What does 'un-' do to 'safe'?", options: ["It makes the direction negative.", "It changes the word into a person.", "It shows a past action.", "It marks more than one path."], answerIndex: 0, reasons: ["unsafe 表示不安全，un- 改變原詞方向。", "字首沒有形成人物名詞。", "過去時間不由 un- 表示。", "複數要看名詞形式，不看 un-。"], reviews: ["題目只要求字首功能，不加入路徑為何危險的原因。", "第一項準確保留 negative direction 的範圍。"], cognitiveProcess: ["u28-s194-explain-un-in-unsafe", "separate-negation-from-person-tense-number"], representationType: "negative-prefix-function", misconceptionTargets: ["treat-prefix-as-tense-marker"] },
    { stem: "If a job is impossible, it ___.", options: ["has already been finished", "cannot be done", "must be done twice", "belongs to one person"], answerIndex: 1, reasons: ["impossible 不表示已完成。", "im- 在 possible 前形成不可能，表示無法完成。", "字首不提供次數。", "它不表示所有權。"], reviews: ["先辨認 possible 的可能方向，再由 im- 反轉。", "第二項沒有加入時間、次數或人物資訊。"], cognitiveProcess: ["u28-s194-derive-impossible-from-possible", "limit-prefix-inference-to-feasibility"], representationType: "prefix-direction-paraphrase", misconceptionTargets: ["infer-completion-from-impossible"] },
    { stem: "Mia disagreed with Ben. What is stated?", options: ["Mia did not hear Ben.", "Ben changed the subject.", "They did not share the same idea.", "They agreed after the talk."], answerIndex: 2, reasons: ["disagree 不表示沒聽見。", "句中沒有轉換主題。", "dis- 加在 agree 前，表示看法不一致。", "題幹沒有後來同意的資訊。"], reviews: ["字首和詞根共同支持 different ideas。", "第三項不把不同意擴大成爭吵或後續和解。"], cognitiveProcess: ["u28-s194-interpret-disagreed-between-two-people", "avoid-inventing-cause-or-later-agreement"], representationType: "negative-prefix-event-inference", misconceptionTargets: ["add-unstated-result-to-disagreement"] },
    { stem: "The answer is incorrect. Which description matches it?", options: ["It is written in ink.", "It is not complete.", "It is hard to read.", "It is not correct."], answerIndex: 3, reasons: ["incorrect 不說明書寫材料。", "not complete 對應 incomplete。", "可讀性不是此字提供的資訊。", "in- 反轉 correct，得到不正確。"], reviews: ["correct 是可直接辨識的詞根，in- 在此表否定。", "第四項是唯一與完整字形精確對應的解釋。"], cognitiveProcess: ["u28-s194-match-incorrect-to-not-correct", "distinguish-incomplete-and-illegible-directions"], representationType: "prefix-root-meaning-match", misconceptionTargets: ["confuse-negative-prefix-words"] },
    { stem: "Which word uses a negative prefix attached to 'happy'?", options: ["unhappy", "happily", "happiness", "happier"], answerIndex: 0, reasons: ["unhappy 在 happy 前加 un-，方向變為不快樂。", "happily 使用副詞字尾。", "happiness 使用名詞字尾。", "happier 是比較級。"], reviews: ["四個選項共享詞根，但只有一個在前面加否定成分。", "第一項測的是 prefix，不是詞尾變化。"], cognitiveProcess: ["u28-s194-identify-unhappy-prefix-change", "separate-prefix-from-suffix-family-members"], representationType: "word-family-prefix-recognition", misconceptionTargets: ["confuse-negative-prefix-with-comparative"] },
    { stem: "Which pair keeps the same root but changes its direction with a prefix?", options: ["care / careful", "honest / dishonest", "teach / teacher", "slow / slowly"], answerIndex: 1, reasons: ["-ful 形成形容詞，未必反轉 care。", "dishonest 在 honest 前加 dis-，形成否定方向。", "-er 形成人物名詞。", "-ly 形成副詞，沒有否定 slow。"], reviews: ["題目同時要求 same root 與 changed direction。", "第二項是唯一由前置字首完成方向轉變的配對。"], cognitiveProcess: ["u28-s194-find-honest-dishonest-reversal", "contrast-prefix-negation-with-suffix-category-change"], representationType: "root-direction-pair-comparison", misconceptionTargets: ["treat-any-word-family-change-as-negation"] },
    { stem: "The machine is inactive. What does the prefix suggest?", options: ["It is moving very fast.", "It was active yesterday.", "It is not active now.", "It is used by two people."], answerIndex: 2, reasons: ["inactive 不表示高速移動。", "字本身不提供昨天狀態。", "in- 在 active 前表示目前非活動狀態。", "它不說明使用人數。"], reviews: ["句子的 is 提供現在狀態，prefix 只改變 active 方向。", "第三項結合兩項證據而未增加原因。"], cognitiveProcess: ["u28-s194-read-inactive-current-state", "combine-present-linking-verb-with-negative-prefix"], representationType: "prefix-and-tense-evidence", misconceptionTargets: ["infer-past-contrast-without-evidence"] },
    { stem: "Which word should not be read as a negative prefix plus a root?", options: ["unsafe", "impatient", "disagree", "uncle"], answerIndex: 3, reasons: ["unsafe 可分析為 un- + safe。", "impatient 可由 im- 與 patient 理解。", "disagree 可由 dis- 與 agree 理解。", "uncle 是完整親屬名稱，cle 不是此處詞根。"], reviews: ["字母開頭相同不保證存在構詞關係。", "第四項防止把所有 un 開頭的字機械拆解。"], cognitiveProcess: ["u28-s194-reject-false-prefix-analysis-of-uncle", "verify-independent-root-after-prefix"], representationType: "false-segmentation-detection", misconceptionTargets: ["split-every-un-initial-word"] },
    { stem: "The box is unlocked, so you can open it without a key. What does 'un-' show here?", options: ["The box is not locked.", "The box has two locks.", "The box was made yesterday.", "The key is inside."], answerIndex: 0, reasons: ["unlocked 在本情境表示沒有鎖住。", "un- 不表示數量。", "它不提供製造時間。", "不用鑰匙不能證明鑰匙在裡面。"], reviews: ["後半句 without a key 支持 not locked 的狀態解讀。", "第一項保留題幹明示範圍，沒有猜測鑰匙位置。"], cognitiveProcess: ["u28-s194-use-keyless-opening-to-read-unlocked", "reject-unstated-lock-count-and-key-location"], representationType: "prefix-context-confirmation", misconceptionTargets: ["overinfer-object-details-from-prefix"] },
    { stem: "Which word describes a person who is not patient?", options: ["unpatient", "impatient", "dispatient", "patientless"], answerIndex: 1, reasons: ["unpatient 不是本題採用的標準形式。", "impatient 是 patient 的常見否定形式。", "dispatient 不是標準字。", "patientless 不是自然形式。"], reviews: ["理解否定方向後，仍需選實際存在的固定拼法。", "第二項顯示 im- 不是可任意替換的字首。"], cognitiveProcess: ["u28-s194-select-standard-impatient-form", "distinguish-valid-negative-prefix-allomorph"], representationType: "negative-form-spelling-selection", misconceptionTargets: ["attach-any-negative-prefix-to-root"] },
    { stem: "Nora's report is incomplete. Which statement follows?", options: ["Nora did not start it.", "Every part is wrong.", "Some needed part is still missing.", "The report will never be finished."], answerIndex: 2, reasons: ["incomplete 不表示完全未開始。", "缺少部分不等於每部分錯誤。", "in- + complete 表示尚未具備全部內容。", "句中沒有永遠無法完成的預測。"], reviews: ["否定字首作用在 complete，範圍是完整程度。", "第三項是可由該字支持的最小結論。"], cognitiveProcess: ["u28-s194-infer-missing-part-from-incomplete", "avoid-all-or-never-overstatement"], representationType: "scope-limited-prefix-inference", misconceptionTargets: ["interpret-incomplete-as-entirely-wrong"] },
    { stem: "A bird disappeared behind the building. Which reading is safest?", options: ["The bird became unhappy.", "The bird stopped moving after that.", "The building was not real.", "The bird could no longer be seen from there."], answerIndex: 3, reasons: ["disappear 與 happy 無關。", "看不見不等於停止移動。", "句中沒有建築物真假資訊。", "disappear 加上 behind the building 支持從該處看不見。"], reviews: ["dis- 提供離開可見狀態的大方向，地點片語限制觀察範圍。", "第四項不把暫時遮蔽誇大成不存在。"], cognitiveProcess: ["u28-s194-interpret-disappeared-with-viewpoint-limit", "avoid-existence-inference-from-visibility-loss"], representationType: "prefix-context-boundary-transfer", misconceptionTargets: ["equate-disappear-with-cease-to-exist"] },
  ]),
  ...skillQuestions("195", [
    { stem: "The children crossed the street ___. (safe)", options: ["safely", "safe", "safety", "safer"], answerIndex: 0, reasons: ["safely 是副詞，修飾 crossed。", "safe 是形容詞。", "safety 是名詞。", "safer 是比較級形容詞，句中沒有比較。"], reviews: ["crossed 已完成主要動作，空格回答如何過街。", "第一項的詞性與字形都符合。"], cognitiveProcess: ["u28-s195-form-safely-after-crossed", "exclude-state-and-comparison-forms"], representationType: "word-family-action-manner", misconceptionTargets: ["use-safe-after-action"] },
    { stem: "The book gives ___ information about local buses. (help)", options: ["helpfully", "helpful", "helper", "helpfulness"], answerIndex: 1, reasons: ["helpfully 是副詞，不能直接修飾 information。", "helpful 是形容詞，描述資訊有幫助。", "helper 是人物名詞，不能描述 information。", "helpfulness 是抽象名詞，無法放在另一名詞前作此性質修飾。"], reviews: ["空格位於名詞 information 前，需要描述其性質。", "第二項形成 helpful information。"], cognitiveProcess: ["u28-s195-select-helpful-before-information", "distinguish-property-from-manner-and-agent"], representationType: "word-family-prenominal-form", misconceptionTargets: ["choose-helpfully-before-noun"] },
    { stem: "Good ___ helps a team solve problems. (communicate)", options: ["communicative", "communicate", "communication", "communicatively"], answerIndex: 2, reasons: ["communicative 是形容詞。", "communicate 是動詞。", "communication 是名詞，作 helps 的主詞。", "communicatively 是副詞且不合此處。"], reviews: ["Good 後缺名詞中心，整個片語位於主要動詞前。", "第三項使用標準名詞形式而非直接加一個任意字尾。"], cognitiveProcess: ["u28-s195-form-communication-as-subject", "use-good-and-helps-to-identify-noun"], representationType: "word-family-subject-formation", misconceptionTargets: ["use-base-verb-as-noun-center"] },
    { stem: "The driver answered the visitor ___. (polite)", options: ["polite", "politeness", "politer", "politely"], answerIndex: 3, reasons: ["polite 是形容詞。", "politeness 是名詞。", "politer 是比較級形容詞，沒有比較。", "politely 是方式副詞，修飾 answered。"], reviews: ["visitor 是 answered 的受詞，句尾空格另說明回答方式。", "第四項不會誤把 visitor 當成被描述的名詞。"], cognitiveProcess: ["u28-s195-attach-politely-to-answered", "separate-object-from-final-manner-modifier"], representationType: "transitive-verb-plus-adverb", misconceptionTargets: ["treat-final-slot-as-object-description"] },
    { stem: "The room became ___ when everyone left. (quiet)", options: ["quiet", "quietly", "quietness", "quieter than"], answerIndex: 0, reasons: ["quiet 是形容詞，接在 became 後描述 room。", "quietly 是副詞。", "quietness 是名詞。", "quieter than 後缺比較對象。"], reviews: ["when 子句提供狀態改變的原因，became 需要形容詞補語。", "第一項雖未改字形，仍是該字族中正確形式。"], cognitiveProcess: ["u28-s195-keep-quiet-form-after-became", "recognize-zero-derivation-option-without-forced-suffix"], representationType: "unchanged-root-adjective-selection", misconceptionTargets: ["force-visible-suffix-change"] },
    { stem: "A sudden ___ surprised everyone in the house. (noise)", options: ["noisy", "noise", "noisily", "noised"], answerIndex: 1, reasons: ["noisy 是形容詞，後面還需名詞。", "noise 是名詞，可被 a sudden 限定。", "noisily 是副詞。", "noised 不是本句自然形式。"], reviews: ["surprised 前需要主詞名詞，a sudden 已提供限定與描述。", "第二項不因同字族有 noisy 就強迫改形。"], cognitiveProcess: ["u28-s195-select-noise-as-surprised-subject", "use-article-adjective-frame-to-choose-root-noun"], representationType: "root-noun-retention", misconceptionTargets: ["choose-noisy-after-sudden"] },
    { stem: "Regular exercise helps children stay ___. (health)", options: ["health", "healthily", "healthy", "healthier than"], answerIndex: 2, reasons: ["health 是名詞。", "healthily 是副詞。", "healthy 是形容詞，描述 children 的狀態。", "healthier than 後缺比較對象。"], reviews: ["stay 在此是連綴動詞，空格說明 children 維持的狀態。", "第三項由 health 形成標準形容詞 healthy。"], cognitiveProcess: ["u28-s195-transform-health-to-healthy-after-stay", "reject-noun-adverb-and-incomplete-comparative"], representationType: "stay-state-word-family", misconceptionTargets: ["place-health-noun-after-stay"] },
    { stem: "The storm put the small boats in great ___. (danger)", options: ["dangerous", "dangerously", "endanger", "danger"], answerIndex: 3, reasons: ["dangerous 是形容詞，不能作 in great 後的名詞中心。", "dangerously 是副詞，無法被 great 直接描述。", "endanger 是動詞，不能接在此介系詞片語中。", "danger 是名詞，完成 in great danger。"], reviews: ["介系詞 in 與形容詞 great 後需要名詞中心。", "第四項形成固定且語意完整的名詞片語。"], cognitiveProcess: ["u28-s195-complete-in-great-danger", "select-noun-after-preposition-and-adjective"], representationType: "prepositional-noun-family-cloze", misconceptionTargets: ["use-dangerous-after-great"] },
    { stem: "Mia made a careful ___ after reading both plans. (choose)", options: ["choice", "choose", "chosen", "choosing to"], answerIndex: 0, reasons: ["choice 是名詞，可接在 a careful 後。", "choose 是動詞。", "chosen 是過去分詞。", "choosing to 後缺動詞，也不能作此名詞中心。"], reviews: ["made a careful ___ 是單數可數名詞位置。", "第一項提醒字族可能改變詞根拼法，不一定靠常見字尾。"], cognitiveProcess: ["u28-s195-select-choice-from-choose-family", "identify-irregular-noun-form-after-a-careful"], representationType: "irregular-family-noun-selection", misconceptionTargets: ["put-base-verb-after-article"] },
    { stem: "The directions were ___, so we asked for help. (confuse)", options: ["confused", "confusing", "confusion", "confusingly"], answerIndex: 1, reasons: ["confused 通常描述感到困惑的人。", "confusing 描述 directions 是造成困惑的來源。", "confusion 是名詞。", "confusingly 是副詞。"], reviews: ["主詞 directions 不會感受困惑，而會使讀者困惑。", "第二項也與後面的 asked for help 因果一致。"], cognitiveProcess: ["u28-s195-select-confusing-for-directions-source", "use-resulting-help-request-as-causal-check"], representationType: "ing-ed-source-selection", misconceptionTargets: ["describe-thing-with-confused"] },
    { stem: "The students felt ___ after reading the directions. (confuse)", options: ["confusion", "confusing", "confused", "confusingly"], answerIndex: 2, reasons: ["confusion 是名詞，不能接在 felt 後描述 students。", "confusing 描述造成感受的來源。", "confused 描述 students 的感受。", "confusingly 是副詞，不能作主詞狀態補語。"], reviews: ["felt 是連綴動詞，students 是感受者。", "第三項與上一種起因形容詞形成角色對照。"], cognitiveProcess: ["u28-s195-select-confused-for-student-experiencers", "contrast-experiencer-ed-with-source-ing"], representationType: "ed-experiencer-selection", misconceptionTargets: ["describe-person-as-confusing-without-cause-role"] },
    { stem: "The two answers are very ___. (difference)", options: ["difference", "differently", "differ", "different"], answerIndex: 3, reasons: ["difference 是名詞。", "differently 是副詞。", "differ 是動詞。", "different 是形容詞，可被 very 修飾並描述 answers。"], reviews: ["are very 後面需要形容詞，主詞是複數也不改形容詞形式。", "第四項完成兩個答案差異很大的敘述。"], cognitiveProcess: ["u28-s195-transform-difference-to-different", "fit-adjective-after-are-very"], representationType: "noun-to-adjective-family-cloze", misconceptionTargets: ["place-difference-after-very"] },
  ]),
  ...skillQuestions("196", [
    { stem: "A dictionary shows 'plan n., v.' Which label should you use in 'We plan to leave early'?", options: ["v.", "n.", "adj.", "adv."], answerIndex: 0, reasons: ["plan 是 We 執行的主要動作，使用動詞標記。", "此處前面沒有冠詞，也不是事物名稱。", "plan 沒有描述名詞。", "plan 沒有修飾動作。"], reviews: ["to leave 是 plan 的內容，支持 plan 作動詞。", "第一項使用句法位置選條目，不因 n. 排在字典前面而誤選。"], cognitiveProcess: ["u28-s196-choose-verb-label-for-plan", "use-subject-and-infinitive-to-disambiguate-entry"], representationType: "dictionary-multiple-entry-label", misconceptionTargets: ["always-use-first-dictionary-label"] },
    { stem: "A dictionary lists 'light n., adj., v.' What is 'light' in 'the light bag'?", options: ["noun", "adjective", "verb", "adverb"], answerIndex: 1, reasons: ["light 沒有在此命名燈或光。", "light 直接描述 bag 的重量，是形容詞。", "句中沒有點燃動作。", "它沒有修飾動詞。"], reviews: ["相同拼法要由名詞前位置選擇 adj. 條目。", "第二項不把其他字典義項帶進目前句子。"], cognitiveProcess: ["u28-s196-classify-light-before-bag", "select-adjective-sense-from-multi-entry-word"], representationType: "dictionary-polysemy-position", misconceptionTargets: ["assign-noun-label-to-every-light"] },
    { stem: "Entries: success n.; successful adj.; successfully adv. Complete 'The school event was ___.'", options: ["successfully", "success", "successful", "succeed"], answerIndex: 2, reasons: ["successfully 是副詞，不能接在 was 後描述 event 的狀態。", "success 是名詞，不能在此直接描述 event。", "successful 是形容詞，接在 was 後描述活動結果。", "succeed 是動詞，不能作 was 的形容詞補語。"], reviews: ["was 後的空格需要主詞補語，字典標記應選 adj.。", "第三項符合形式，也表達活動辦得成功。"], cognitiveProcess: ["u28-s196-use-adj-entry-for-successful-event", "select-family-form-from-dictionary-labels"], representationType: "dictionary-family-form-cloze", misconceptionTargets: ["choose-noun-because-meaning-is-close"] },
    {
      stem: "Entries: careful adj.; carefully adv. Complete 'Nora checked every name ___.'",
      options: ["care", "careful", "carefulness", "carefully"], answerIndex: 3,
      reasons: ["care 是名詞或動詞，不能說明 checked 的方式。", "careful 是形容詞，不能直接放在完整受詞後修飾動作。", "carefulness 是名詞，無法作此方式修飾語。", "carefully 是副詞，修飾 checked。"],
      reviews: ["every name 已是 checked 的受詞，句尾空格補充檢查方式。", "第四項對應字典的 adv. 條目。"],
      cognitiveProcess: ["u28-s196-select-carefully-adv-entry", "use-complete-object-to-locate-manner-slot"], representationType: "dictionary-adverb-form-selection", misconceptionTargets: ["use-adjective-for-action-manner"],
    },
    { stem: "Which dictionary label should you check for a word after 'a' in 'a ___ arrived'?", options: ["n.", "v.", "adj.", "adv."], answerIndex: 0, reasons: ["a 後的空格是 arrived 的人物或事物主詞，需要名詞。", "主要動詞已是 arrived。", "若只有形容詞，後面仍缺名詞中心。", "副詞不能被 a 限定。"], reviews: ["a ___ 整體位於 arrived 前，必須形成名詞片語。", "第一項是查找候選字時的起點，仍需再核對語意。"], cognitiveProcess: ["u28-s196-choose-n-label-after-indefinite-article", "derive-dictionary-category-from-empty-subject-slot"], representationType: "dictionary-label-from-sentence-slot", misconceptionTargets: ["look-up-adjective-only-after-article"] },
    { stem: "A dictionary shows 'record n., v.' Which label should you use in 'They record the talk'?", options: ["n.", "v.", "adj.", "prep."], answerIndex: 1, reasons: ["record 前沒有冠詞，且不是此句的事物名稱。", "record 位於主詞 They 後並帶受詞 the talk，是動詞。", "它沒有描述名詞。", "它不建立介系關係。"], reviews: ["主詞、動作、受詞三個位置清楚區分 record 的詞性。", "第二項說明為何同字的 n. 條目不適用。"], cognitiveProcess: ["u28-s196-choose-verb-record-before-object", "use-transitive-frame-to-select-entry"], representationType: "noun-verb-entry-disambiguation", misconceptionTargets: ["treat-record-as-noun-in-every-use"] },
    { stem: "A dictionary gives 'daily adj., adv.' Which label should you use in 'a daily report'?", options: ["n.", "v.", "adj.", "adv."], answerIndex: 2, reasons: ["daily 不命名 report。", "它不是動作。", "daily 直接修飾名詞 report，是形容詞。", "若放在 send reports daily 中才會作副詞。"], reviews: ["一字多詞性時，名詞前位置指向 adj.。", "第三項與 a daily meeting 的結構相同，但換成字典標記判讀。"], cognitiveProcess: ["u28-s196-select-adj-label-for-daily-report", "contrast-prenominal-and-postverb-daily-entries"], representationType: "dual-label-dictionary-choice", misconceptionTargets: ["classify-daily-by-spelling-only"] },
    { stem: "Entries: hard adj., adv.; hardly adv. Complete 'The team worked ___ to finish on time.'", options: ["hardly", "hardness", "harder than", "hard"], answerIndex: 3, reasons: ["hardly 表示幾乎不，會與完成目標的語意衝突。", "hardness 是名詞。", "harder than 後缺比較對象。", "hard 是副詞，表示努力地工作。"], reviews: ["to finish on time 支持投入努力，而非幾乎沒工作。", "第四項提醒字典的 adv. 條目不一定以 -ly 結尾。"], cognitiveProcess: ["u28-s196-distinguish-hard-and-hardly-entries", "use-purpose-clause-to-select-effort-adverb"], representationType: "dictionary-near-form-disambiguation", misconceptionTargets: ["assume-hardly-is-manner-form-of-hard"] },
    { stem: "A dictionary lists 'present n., adj., v.' What is 'present' in 'All students are present'?", options: ["adjective", "noun", "verb", "adverb"], answerIndex: 0, reasons: ["present 接在 are 後描述 students 都在場，是形容詞。", "它不是禮物或現在這個名詞意思。", "句中主要動詞已是 are。", "它沒有修飾動作。"], reviews: ["All students 是主詞，are present 表示出席狀態。", "第一項由句法功能選定 adj. 條目。"], cognitiveProcess: ["u28-s196-select-present-adjective-sense", "exclude-gift-and-show-entries-from-linking-frame"], representationType: "dictionary-three-way-polysemy", misconceptionTargets: ["choose-familiar-present-noun-sense"] },
    { stem: "A dictionary shows 'close v., adj., adv.' What is 'close' in 'Please stand close'?", options: ["a verb meaning shut", "an adverb about distance", "an adjective before a noun", "a noun naming a place"], answerIndex: 1, reasons: ["stand 已是主要動詞，close 不表示關上。", "close 修飾 stand，表示距離近。", "close 在這個句子沒有放在名詞前。", "close 不命名地點。"], reviews: ["命令句的動作是 stand，後面的 close 補充站的位置距離。", "第二項對應 adv. 條目而非熟悉的 shut 意思。"], cognitiveProcess: ["u28-s196-interpret-close-as-distance-adverb", "resolve-entry-by-stand-frame-and-meaning"], representationType: "dictionary-contextual-sense-selection", misconceptionTargets: ["default-close-to-shut-verb"] },
    {
      stem: "Entries: health n.; healthy adj. Complete 'Fresh food helps keep us ___.'",
      options: ["health", "healthily", "healthy", "healthier than"], answerIndex: 2,
      reasons: ["health 是名詞，不能作 keep us 後的狀態補語。", "healthily 是副詞，不能描述 us 維持的狀態。", "healthy 是形容詞，描述 us 的狀態。", "healthier than 在此缺少明確比較對象。"],
      reviews: ["keep + us 後要用形容詞受詞補語。", "第三項直接對應 healthy 的 adj. 標記。"],
      cognitiveProcess: ["u28-s196-use-healthy-adj-entry-after-keep-object", "reject-noun-adverb-and-open-comparative"], representationType: "dictionary-object-complement-selection", misconceptionTargets: ["use-health-noun-after-keep-us"],
    },
    { stem: "Entries: use n., v.; useful adj.; usefully adv. Which label explains 'useful' in 'a useful tool'?", options: ["n.", "v.", "adv.", "adj."], answerIndex: 3, reasons: ["useful 不命名物品。", "它不是主要動作。", "useful 沒有修飾動詞，因此不是此處的 adv.。", "useful 直接描述 tool，是形容詞。"], reviews: ["a 限定 tool，useful 位於名詞前提供性質。", "第四項選字族中的正確條目，而不是只查詞根 use。"], cognitiveProcess: ["u28-s196-locate-useful-adjective-entry", "distinguish-root-entry-from-derived-form-label"], representationType: "dictionary-derived-entry-label", misconceptionTargets: ["look-up-root-instead-of-visible-form"] },
  ]),
];

export const ENGLISH_UNIT_SOURCE = {
  unitId: UNIT_ID,
  lectures: ENGLISH_U28_LECTURES,
  questions: ENGLISH_U28_QUESTIONS,
  vocabularyPolicy: {
    capQuestionBasis: "appendix-5-table-1",
    additionalLearningTerms: ["add", "careless", "coach", "complete", "confuse", "daily", "danger", "decision", "describe", "difference", "direction", "disappear", "discuss", "discussion", "dishonest", "distance", "effort", "fit", "form", "impossible", "improve", "information", "ink", "local", "lock", "match", "message", "movement", "narrow", "natural", "path", "patient", "plus", "project", "record", "regular", "safety", "shut", "sleepy", "soft", "solve", "state", "step", "storm", "succeed", "success", "sudden", "suggest", "travel"],
    properNames: ["Amy", "Ben", "Leo", "Mia", "Nora", "Sam"],
    grammarNotation: ["ability", "action", "active", "adj", "adjective", "adverb", "adv", "agreeable", "agreement", "al", "ally", "article", "attached", "breakable", "carefulness", "category", "clause", "cle", "clearness", "cloze", "communica", "communicate", "communication", "communicative", "communicatively", "comparison", "complement", "confusion", "conjunction", "context", "darkness", "der", "derived", "description", "differ", "dis", "disagree", "disagreed", "disconnect", "easily", "ending", "endanger", "entries", "entry", "er", "event", "evidence", "fame", "frequency", "freshen", "freshness", "ful", "function", "gerund", "grammar", "happier", "happily", "happiness", "hardness", "healthier", "healthily", "helpfulness", "im", "impatient", "inactive", "incomplete", "incorrect", "inform", "informative", "informing", "ity", "kindness", "label", "linking", "ly", "marker", "meaning", "ment", "mis", "modifier", "n", "naturalness", "negative", "ness", "noisily", "noun", "object", "ous", "part", "patience", "phrase", "politeness", "politer", "polysemy", "prefix", "prep", "preposition", "pronoun", "quality", "quietness", "representation", "root", "runner", "safer", "safest", "sentence", "sleepily", "slot", "speech", "statement", "subject", "suffix", "tion", "transfer", "un", "unfair", "unlocked", "unsafe", "usable", "usefulness", "V", "verb", "washable", "word", "y"],
    malformedDistractors: ["dispatient", "happinessly", "happyness", "inpossible", "kindful", "patientless", "teachly", "unpatient", "visitful", "visitness", "washedly"],
  },
};
