import { defineChoiceQuestions as questions, defineEnglishUnit } from "../define-unit.mjs";

const skills = [
  {
    id: "ENG_R4_S261", process: "infer-word-from-definition", evidence: "同句的 is、means、or、that is 等定義訊號",
    objectives: ["辨認同句中直接解釋陌生字的訊號。", "把定義替換回原字位置，檢查詞性與句意。", "排除只與主題相關但不符合定義的選項。"],
    sections: [
      ["定義常在旁邊", "作者若預期讀者不熟某字，常立刻用 is、means、or、that is 或兩個逗點補充。先讀完整同句，不急著查字典。"],
      ["找解釋的邊界", "A habitat, the natural home of an animal, ... 中兩個逗點夾住 habitat 的定義。把夾住部分換回 habitat，確認句法位置相同。"],
      ["定義不等於同主題字", "文章談 food 時，edible 定義為 safe to eat；fresh、sweet、cheap 都與食物相關，卻不是定義。答案必須精確對上解釋。"],
      ["詞性也要一致", "若目標字在 be 後描述名詞，答案通常是形容性解釋；若位於冠詞後，則需名詞概念。定義與位置兩者都要通過。"],
    ],
    examples: [
      ["The glass is transparent, which means light can pass through it.", ["means 引出定義。", "定義是光可穿過。", "替回 transparent 位置。"], "allowing light through", "不是指 glass 很亮，而是能透光。"],
      ["A habitat, the natural home of a plant or animal, can change.", ["逗點夾住補充。", "home 是上位概念。", "選名詞義。"], "a natural home", "完整對應定義。"],
      ["This fruit is edible, or safe to eat.", ["or 在此改述。", "safe to eat 是明示。", "排除味道與價格。"], "safe to eat", "or 不是列另一種水果，而是解釋 edible。"],
    ],
    misconceptions: [
      ["陌生字一定要先查字典。", "同句可能已給完整定義。", "先找定義訊號。"],
      ["同主題選項都可。", "主題相關不代表語義相同。", "要求與解釋精確互換。"],
      ["or 永遠表示選擇。", "or 也可引出換句話說。", "檢查兩側是否指同一事物。"],
      ["忽略詞性只看中文。", "定義還要能放回原位置。", "核對名詞、動詞或形容詞功能。"],
    ],
    checks: [
      ["that is 後常出現什麼？", "前文的改述或定義", "它提示換句話說。"],
      ["定義選項只需同主題嗎？", "不夠", "必須精確等義。"],
      ["替換測試要檢查什麼？", "句意與詞性", "兩者都合才成立。"],
    ],
    questions: questions([
      ["A portable light is one that can be carried easily. What does portable mean?", "easy to carry", "one that can be carried easily 是直接定義。", [["very bright", "與 light 主題相關但未對應 carried。"], ["hard to repair", "原文未談 repair。"], ["fixed to a wall", "與 can be carried 相反。"]]],
      ["The path is narrow, meaning there is little space from one side to the other. What does narrow mean?", "not wide", "little space from side to side 等義於 not wide。", [["very long", "長度方向不同。"], ["covered with stones", "路面材料未提。"], ["easy to find", "原文只定義寬度。"]]],
      ["Nocturnal animals are active at night and usually rest by day. What does nocturnal mean?", "active at night", "are active at night 直接解釋 nocturnal。", [["living in water", "棲地未在定義中。"], ["sleeping all the time", "原文說 night active。"], ["moving only in winter", "季節未提。"]]],
      ["A bilingual sign uses two languages. What does bilingual mean?", "using two languages", "uses two languages 是完整定義。", [["made from two boards", "把 bi 誤讀成物件數量。"], ["written in large letters", "字體大小未提。"], ["difficult to read", "原文沒有難度評價。"]]],
      ["The cup is fragile; that is, it can break easily. What does fragile mean?", "easy to break", "that is 後明示 break easily。", [["safe to drop", "與易破相反。"], ["too heavy to lift", "重量未提。"], ["made for hot drinks", "用途未提。"]]],
      ["A volunteer is a person who chooses to help without being paid. Who is a volunteer?", "someone who helps by choice without pay", "完整保留 chooses、help、without paid。", [["a worker who must be paid", "與 without being paid 相反。"], ["any person waiting for help", "角色由 helper 變成受助者。"], ["a customer choosing a product", "選擇購物不等於志願協助。"]]],
      ["The water is shallow, or not deep enough to cover an adult's knees. What does shallow mean?", "not deep", "or 後直接改述 not deep。", [["moving quickly", "流速未提。"], ["unsafe to drink", "水質未提。"], ["far from shore", "位置未提。"]]],
      ["A refund is money returned to a customer after a purchase is canceled. What is a refund?", "returned purchase money", "定義包含 money returned 與 canceled purchase。", [["an extra charge", "returned 與 charge 相反。"], ["a shopping list", "不是金錢退回。"], ["a promise to buy later", "未包含 returned money。"]]],
      ["The room is vacant, which means nobody is using it now. What does vacant mean?", "not being used", "nobody is using it 是直接定義。", [["full of visitors", "與 nobody 相反。"], ["closed forever", "now 不等於 forever。"], ["available only at night", "時間限制未提。"]]],
      ["A detour is another route used when the usual way is closed. What is a detour?", "a different route around a closed way", "完整對應 another route 與 usual way closed。", [["the shortest part of the usual route", "原文說 another route。"], ["a place to stop and rest", "不是休息地點。"], ["a rule that closes every road", "detour 是路線，不是規則。"]]],
      ["The medicine may cause drowsiness, a state of feeling sleepy. What is drowsiness?", "sleepiness", "逗點後 a state of feeling sleepy 是定義。", [["hunger", "沒有 food 或 hunger 線索。"], ["strong pain", "原文沒有 pain。"], ["better hearing", "感官未提。"]]],
      ["The two reports are identical—they are exactly the same. What does identical mean?", "exactly the same", "破折號後直接定義。", [["written by two people", "作者數量未定義字義。"], ["different in one detail", "與 exactly the same 相反。"], ["both difficult to finish", "難度未提。"]]],
    ], { type: "same-sentence-definition", operation: "replace-word-with-definition", misconception: "choose-topic-related-meaning" }),
  },
  {
    id: "ENG_R4_S262", process: "infer-word-from-example-or-contrast", evidence: "for example、such as 或 but/unlike 建立的例證與對比",
    objectives: ["由列舉實例歸納陌生字共同特徵。", "由 but、unlike、while 等對比推出相反或不同面向。", "避免把單一例子誤當完整字義。"],
    sections: [
      ["例子要找共同點", "for example 或 such as 後可能列出多項。不要只翻第一例，問這些事物共同具有什麼特徵。"],
      ["對比提供界線", "Unlike the rigid board, this sheet is flexible 中 rigid 與 flexible 在可彎曲程度形成對比。先找比較面向，再推出目標字。"],
      ["but 後不一定是反義字", "The room is plain but comfortable 中 plain 與 comfortable 是不同評價面向，不是直接反義。只能推出本文支持的部分。"],
      ["用全部線索限制", "例子、對比與句法應指向同一意思。若候選只合一個例子但不合另一個，就不是共同字義。"],
    ],
    examples: [
      ["The shop sells produce, such as apples, beans, and carrots.", ["列出三種食物。", "共同點是農作物。", "不是只指 apples。"], "farm-grown food", "produce 在此是農產品。"],
      ["Unlike the rigid box, the bag is flexible.", ["比較同一可彎程度。", "rigid 不易彎。", "flexible 為可彎。"], "easy to bend", "對比限定了物理特徵。"],
      ["Most seats were empty, but the front row was packed.", ["empty 與 packed 對比。", "比較占用程度。", "packed 表很多人。"], "very full", "不是說座位被包裝。"],
    ],
    misconceptions: [
      ["第一個例子就是完整定義。", "例子只是一個成員。", "歸納所有例子的共同上位概念。"],
      ["but 兩邊每個字都互為反義。", "轉折可能發生在整句或不同面向。", "先確定比較維度。"],
      ["unlike 後只需看最近字。", "需比較前後兩個對象的同一特徵。", "寫出 A 與 B 的差異。"],
      ["一個候選合一例就足夠。", "多例必須全部涵蓋。", "逐例測試。"],
    ],
    checks: [
      ["such as 後的項目用來做什麼？", "提供例子", "應歸納共同概念。"],
      ["unlike 提示哪種關係？", "對比", "比較兩者差異。"],
      ["三例中候選只合兩例可選嗎？", "不可", "完整字義需涵蓋全部例子。"],
    ],
    questions: questions([
      ["The box contains stationery, such as pens, paper, and rulers. What is stationery?", "materials used for writing or schoolwork", "pens、paper、rulers 的共同用途是書寫或學習。", [["only pens", "只取第一例。"], ["food kept in a box", "三例都不是食物。"], ["large classroom furniture", "三例是小型用品。"]]],
      ["Unlike the timid cat that hid under the chair, the other cat walked up to every visitor. What does timid mean?", "shy or easily frightened", "hid 與主動靠近訪客形成膽怯對比。", [["friendly to everyone", "這描述 other cat。"], ["very hungry", "沒有食物線索。"], ["unable to walk", "cat 能 hid，未表示不能走。"]]],
      ["Fresh water was abundant near the river, but it was scarce on the dry hill. What does scarce mean?", "hard to find or not enough", "與 abundant 形成數量充足與不足的對比。", [["easy to find in large amounts", "這是 abundant 的意思。"], ["too cold to drink", "溫度未比較。"], ["moving down the hill", "動向未提。"]]],
      ["The museum protects ancient objects—for example, bowls made two thousand years ago and tools from an early town. What does ancient mean?", "very old", "兩千年前與 early town 共同指很久以前。", [["made yesterday", "時間方向相反。"], ["very expensive", "價格未提。"], ["used only for cooking", "tools 不一定烹飪，且非共同點。"]]],
      ["Some materials are absorbent. A towel, for instance, takes in water quickly. What does absorbent mean?", "able to take in liquid", "towel takes in water 是直接例證。", [["keeping all water outside", "與 takes in 相反。"], ["drying only in sunlight", "乾燥條件未提。"], ["made from hard metal", "towel 不是 metal。"]]],
      ["The old chair was rigid, while the new one could bend slightly without breaking. What does rigid mean?", "not easy to bend", "while 對比 new one could bend。", [["soft enough to sleep on", "舒適度未提。"], ["easy to fold", "與對比相反。"], ["newly made", "old/new 是時間，不是 rigid 字義。"]]],
      ["The guide asked for durable shoes, such as strong boots that can be used on many long walks. What does durable mean?", "able to last through much use", "strong、many long walks 共同指耐用。", [["worn only once", "與 many walks 相反。"], ["brightly colored", "顏色未提。"], ["cheap to replace", "價格與替換未定義耐用。"]]],
      ["The front room was packed, but the back room had only two people. What does packed mean?", "very crowded", "與 only two people 對比，人數很多。", [["closed and locked", "開關狀態未提。"], ["carefully cleaned", "清潔未提。"], ["almost empty", "與對比方向相反。"]]],
      ["The menu offers beverages, including tea, milk, and fruit juice. What are beverages?", "drinks", "三個例子全是飲品。", [["sweet desserts", "milk/tea 不必是 dessert。"], ["breakfast plates", "例子是液體。"], ["only fruit juice", "只取最後一例。"]]],
      ["Unlike the permanent wall, the light screen can be removed after the show. What does permanent mean?", "intended to stay in place", "與 can be removed 形成是否固定保留的對比。", [["easy to carry away", "這描述 light screen。"], ["used during one show", "短期用法與 permanent 相反。"], ["painted a dark color", "顏色未提。"]]],
      ["The story has several fictional characters, including a talking tree and a boy who can fly. What does fictional mean?", "created in imagination rather than real", "會說話的樹與會飛的男孩是想像角色例子。", [["famous in history", "例子非史實。"], ["ordinary and real", "與超現實例子不合。"], ["all adults", "例子含 tree 與 boy。"]]],
      ["The first answer was vague, but the second gave an exact time, place, and name. What does vague mean?", "not clear or specific", "與 exact details 形成清楚程度對比。", [["full of exact detail", "這是 second answer。"], ["spoken very loudly", "音量未提。"], ["certain to be correct", "正確性未比較。"]]],
    ], { type: "example-contrast-vocabulary", operation: "generalize-examples-or-invert-contrast", misconception: "copy-one-example" }),
  },
  {
    id: "ENG_R4_S263", process: "infer-word-from-cause-effect", evidence: "陌生字所在原因與後句結果形成可驗證的事件鏈",
    objectives: ["辨認陌生字所在句是原因還是結果。", "利用可觀察後果限制可能字義。", "排除無法產生該結果的同詞性選項。"],
    sections: [
      ["先畫原因箭頭", "把句子簡化成 A → B。若 floor was slippery → Mia walked slowly，後果 slow walking 可限制 slippery 為容易滑。"],
      ["結果要有解釋力", "正確字義應能自然造成後句結果。若候選與結果無關，即使詞性正確也排除。"],
      ["也可由結果回推原因", "he was exhausted, so he sat down 由 sat down 回推 exhausted 是很累，而不是開心或迷路。"],
      ["避免過度因果", "一個結果可能有多種一般原因，但題目會用其他線索縮到唯一。只推出足以解釋文本的範圍，不加入疾病或意圖。"],
    ],
    examples: [
      ["The road was slippery, so drivers slowed down.", ["結果是慢行。", "慢行回應打滑風險。", "推出 slippery。"], "easy to slide on", "不需推成 road damaged。"],
      ["Nora was exhausted and fell asleep at once.", ["結果立即睡著。", "最直接原因是極累。", "選 tired meaning。"], "extremely tired", "不是 bored，因文本用睡著支持疲累。"],
      ["The box was sealed, so water could not enter.", ["結果是水進不去。", "原因是開口被封住。", "推出 tightly closed。"], "closed tightly", "sealed 不是 empty。"],
    ],
    misconceptions: [
      ["只看陌生字同句，不讀結果。", "後句常是主要線索。", "建立完整因果鏈。"],
      ["任何可造成結果的原因都可選。", "還需合詞性與其他文字。", "用全部線索縮到唯一。"],
      ["so 前一定是結果。", "通常 so 後引出結果。", "辨認箭頭方向。"],
      ["可以推論具體疾病或動機。", "文本通常只支持一般狀態。", "採最小充分推論。"],
    ],
    checks: [
      ["A so B 中通常誰是結果？", "B", "so 引出後果。"],
      ["結果線索只能檢查詞性嗎？", "不是", "它主要限制語義。"],
      ["推論應選具體病名還是足以解釋的狀態？", "足以解釋的狀態", "避免超出證據。"],
    ],
    questions: questions([
      ["The steps were slick after the rain, so everyone held the rail. What does slick mean here?", "easy to slip on", "扶 rail 是避免在濕滑階梯滑倒。", [["painted a bright color", "顏色不能解釋扶 rail。"], ["very wide", "寬度與 rain、扶手結果無關。"], ["covered by a roof", "若有屋頂也不能由此推出 slick。"]]],
      ["Ben felt famished after missing lunch, so he ate two bowls of rice. What does famished mean?", "very hungry", "missed lunch 與吃兩碗共同支持極餓。", [["too tired to move", "後文能吃飯，主線是 hunger。"], ["angry about the bowl", "容器不是原因。"], ["ready to sleep", "結果是 eating。"]]],
      ["The print was faint, so Mia moved the paper closer to the light. What does faint mean?", "hard to see", "移近 light 是為了看清淡弱文字。", [["written in another language", "光線不能解決語言。"], ["too large for the paper", "大小不需移近 light。"], ["full of mistakes", "正確性與亮度無關。"]]],
      ["The path was blocked by a fallen tree; therefore, the hikers turned back. What does blocked mean?", "not possible to pass", "turned back 是無法通過的結果。", [["easy to follow", "若 easy 不需回頭。"], ["shorter than expected", "長度不能解釋 fallen tree 阻路。"], ["open only to hikers", "hikers 本人也 turned back。"]]],
      ["The room became stuffy after every window was closed, so Jay opened the door for air. What does stuffy mean?", "lacking fresh air", "開門 for air 直接回應空氣不流通。", [["too cold to enter", "開門不一定增加溫暖。"], ["full of loud music", "air 行動不能解決音樂。"], ["bright from sunlight", "與 closed windows/air 結果不合。"]]],
      ["The plate was unstable on the small box, so Nora moved it before it fell. What does unstable mean?", "likely to move or fall", "before it fell 明示不穩造成掉落風險。", [["too hot to touch", "移動原因不是 heat。"], ["made from metal", "材質不能直接解釋 fell risk。"], ["perfectly balanced", "與 fall risk 相反。"]]],
      ["Leo spoke discreetly because the news was not public yet; nobody nearby heard him. What does discreetly mean?", "carefully and privately", "not public 與 nobody heard 支持謹慎低調。", [["as loudly as possible", "與 nobody heard 相反。"], ["without knowing the news", "Leo 正在說 news。"], ["in a language nobody knew", "原文未提語言。"]]],
      ["The river rose rapidly, so workers closed the low bridge before noon. What does rapidly mean?", "very quickly", "需在 noon 前緊急關橋顯示水位上升快。", [["once each year", "頻率未提且不能解釋急關。"], ["without any danger", "關橋顯示風險。"], ["toward the sea", "方向未定義速度。"]]],
      ["The instructions were misleading, so several users pressed the wrong button. What does misleading mean?", "causing people to understand wrongly", "多人按錯鍵是指示導向錯誤理解的結果。", [["printed in a large size", "字體大小不能必然造成按錯。"], ["correct and complete", "與 wrong button 結果相反。"], ["available online", "媒介未解釋錯誤。"]]],
      ["Amy was reluctant to enter, and her friends had to ask three times before she moved. What does reluctant mean?", "not willing or eager", "三次勸說才動表現不願意。", [["unable to hear", "原文沒有聽力問題。"], ["excited to go first", "與遲遲不動相反。"], ["certain of the route", "路線資訊未提。"]]],
      ["The old pipe was leaking, so the floor below it became wet. What does leaking mean?", "letting liquid escape", "floor wet 是液體從 pipe 漏出的結果。", [["making a loud sound", "聲音不能造成 wet floor。"], ["carrying no water", "若無水不能解釋濕。"], ["painted under the floor", "位置與 paint 未提。"]]],
      ["The schedule was flexible, so the group moved the meeting without a fee. What does flexible mean?", "able to be changed", "可免費 move meeting 說明安排可調整。", [["fixed forever", "與 moved 相反。"], ["written in small letters", "字體不能解釋改期。"], ["missing all dates", "仍有 meeting schedule，只是可變。"]]],
    ], { type: "cause-effect-vocabulary", operation: "infer-minimal-cause-from-result", misconception: "ignore-result-clue" }),
  },
  {
    id: "ENG_R4_S264", process: "use-part-of-speech-and-collocation", evidence: "陌生字的句法位置及與相鄰字形成的自然搭配",
    objectives: ["由冠詞、助動詞、be 與修飾位置判定詞性。", "利用動詞—受詞與形容詞—介系詞搭配縮小意思。", "在詞性相同時再以全文語意決定。"],
    sections: [
      ["位置先排詞性", "a ___ 後多需名詞，can ___ 需動詞原形，very ___ 常需形容詞或副詞。先排除不能放入的位置，降低字義負擔。"],
      ["搭配提供語義角色", "raise a concern 中 concern 是被提出的問題；address a concern 中 address 是處理。不要把熟悉的 address 只解成地址。"],
      ["同字可能跨詞性", "record 可作名詞紀錄，也可作動詞錄製。由前面的 a 或 to、句中主詞動詞骨架決定本文功能。"],
      ["最後用情境核對", "詞性只能排掉一部分，剩下仍需看情境。例如 light 作形容詞可表示輕或淡，要由 object、color 等搭配決定。"],
    ],
    examples: [
      ["They will address the problem tomorrow.", ["will 後需動詞。", "受詞是 problem。", "address 此處為處理。"], "deal with", "不是郵寄地址名詞。"],
      ["Please keep a record of each visit.", ["a 後需單數名詞。", "of each visit 說明內容。", "record 為紀錄。"], "written account", "不是錄音動作。"],
      ["The bag is light enough to carry.", ["is 後形容 bag。", "to carry 提供重量情境。", "light 表不重。"], "not heavy", "不是亮度。"],
    ],
    misconceptions: [
      ["熟字只會有一個詞性。", "許多字可作名詞與動詞。", "依位置判定本文功能。"],
      ["詞性相同就都可。", "搭配與情境仍會排除。", "檢查相鄰字與受詞。"],
      ["看到 address 一定是地址。", "作動詞可表示處理或發言。", "看是否位於助動詞後並帶受詞。"],
      ["light 永遠表示光。", "可描述重量、顏色或亮度。", "用後續搭配選義。"],
    ],
    checks: [
      ["can record 中 record 是哪類詞？", "動詞", "can 後接原形。"],
      ["a record 中 record 是哪類詞？", "名詞", "a 標示單數名詞。"],
      ["詞性判斷後還需做什麼？", "用搭配與情境核對字義", "同詞性仍可能多義。"],
    ],
    questions: questions([
      ["The group will tackle the waste problem next month. From its position and object, what does tackle mean?", "work on solving", "will 後為動詞，受詞 problem 支持著手解決。", [["a piece of sports equipment", "那是名詞義，不能直接接 will。"], ["avoid discussing", "與主動面對 problem 的搭配不合。"], ["measure the weight", "problem 不是被秤重物。"]]],
      ["Please file the report under June. What does file mean here?", "place and organize a document", "祈使句動詞 file 帶 report，under June 指分類位置。", [["a folder made of paper", "這是名詞概念，句中需要動詞。"], ["read the report aloud", "分類線索 under June 不支持朗讀。"], ["delete every report", "file 表保存整理，不是刪除。"]]],
      ["The school raised a concern about the dark crossing. What is a concern here?", "a worry or problem", "a 標名詞，raise a concern 是提出擔憂。", [["a higher place", "把 raised 只當物理抬高，搭配不合。"], ["a celebration", "dark crossing 導向安全擔憂。"], ["a road sign", "sign 可能處理 concern，但不是 concern 本身。"]]],
      ["Nora gave a brief reply and returned to work. What does brief mean?", "short", "brief 置於 reply 前作形容詞，returned to work 支持回答不長。", [["a bag for papers", "名詞義不能直接描述 reply。"], ["angry", "情緒未由位置或情境支持。"], ["written tomorrow", "時間未提。"]]],
      ["The guide asked us to observe the birds without touching them. What does observe mean?", "watch carefully", "to 後動詞，birds 為受詞，without touching 限定為觀看。", [["feed", "without touching 不支持餵食。"], ["draw from memory", "原文未要求畫。"], ["become a bird", "主受角色不合。"]]],
      ["The team reached a sound decision after checking the facts. What does sound mean?", "reasonable and reliable", "sound 置於 decision 前，checking facts 支持判斷可靠。", [["easy to hear", "此處不是聲音名詞。"], ["very loud", "decision 沒有音量。"], ["made without evidence", "與 checking facts 相反。"]]],
      ["The shop will charge $20 for delivery. What does charge mean?", "ask someone to pay", "will 後動詞，$20 與 for delivery 是收費搭配。", [["fill a battery", "雖是 charge 另一義，但金額與 delivery 不合。"], ["run toward someone", "原文沒有移動。"], ["write an address", "付款數字不支持地址義。"]]],
      ["Mia found the lecture engaging and asked several questions. What does engaging mean?", "interesting enough to hold attention", "found ... engaging 為受詞補語，後續提問支持投入。", [["locked with a key", "不是機械接合義。"], ["too boring to follow", "與 asked questions 的投入相反。"], ["ending very early", "時長未提。"]]],
      ["The town plans to launch a new bus service in June. What does launch mean?", "start", "to 後動詞，受詞 new service 支持啟動。", [["throw into the air", "雖是另一義，但 service 不能被投擲。"], ["cancel", "與 new service 計畫方向相反。"], ["paint the buses", "原文未談外觀。"]]],
      ["The river current became stronger after the rain. What is current here?", "moving water", "the river current 為名詞片語，stronger after rain 支持水流。", [["happening now", "形容詞義不能作此名詞中心。"], ["electric power", "river/rain 情境不支持電流。"], ["a newspaper report", "媒體義與 stronger 不合。"]]],
      ["The report highlights three benefits of the plan. What does highlights mean?", "draws attention to", "主詞 report、受詞 benefits，表示特別指出。", [["adds yellow color to", "可能是實體標記，但本文是報告內容功能。"], ["hides", "與指出 benefits 相反。"], ["proves every benefit is true", "highlight 不等於證明。"]]],
      ["Ben gave the rope a sharp pull. What does sharp mean?", "sudden and strong", "sharp 描述 pull，動作搭配表示突然有力。", [["able to cut", "這是刀刃義，pull 不是物件刃口。"], ["high in sound", "句中沒有聲音。"], ["careful and slow", "與 sharp pull 的動作特徵不合。"]]],
    ], { type: "syntax-collocation-vocabulary", operation: "filter-by-part-of-speech-and-object", misconception: "use-most-familiar-sense" }),
  },
  {
    id: "ENG_R4_S265", process: "select-contextual-dictionary-sense", evidence: "字典多個義項中只有一項符合本文詞性、搭配與事件",
    objectives: ["讀懂簡化字典條目中的詞性與多個義項。", "依上下文選擇一項，而非把所有義項混合。", "以替換測試確認選中義項使句子自然。"],
    sections: [
      ["字典列的是可能，不是答案", "同一字會列多義。上下文負責決定哪一義在本句被啟動；不能看到第一義就停止。"],
      ["先對詞性再對意思", "bank 作名詞可為銀行或河岸，作動詞可為傾斜。先看句法標記，再用 river、money 等搭配決定。"],
      ["用替換測試", "把字典釋義短語換進原句，讀是否通順且符合事件。若需改動其他字或產生怪異因果，該義項不合。"],
      ["保留本文範圍", "選到正確義項後，只解釋本文用法，不宣稱這就是該字永遠唯一的意思。"],
    ],
    examples: [
      ["bank: 1 money business; 2 land beside water. We sat on the river bank.", ["bank 是名詞。", "river 提供水域搭配。", "選 land beside water。"], "sense 2", "不是去銀行坐。"],
      ["match: 1 contest; 2 be the same or suitable. The blue shirt matches the hat.", ["matches 為動詞。", "shirt/hat 比較搭配。", "選 suitable/together。"], "sense 2", "不是運動比賽。"],
      ["point: 1 sharp end; 2 main idea. What is the writer's point?", ["writer 與文章情境。", "不是實體尖端。", "選 main idea。"], "sense 2", "由搭配決定抽象義。"],
    ],
    misconceptions: [
      ["字典第一義一定最正確。", "義項排序不替代上下文。", "逐項代回。"],
      ["熟悉義可套所有句子。", "多義字會隨搭配改變。", "檢查名詞與動詞角色。"],
      ["可以把兩個義項混成一個答案。", "本文通常啟動單一主要義。", "選最符合整句的一項。"],
      ["選義後不用重讀原句。", "替換測試是最後證據。", "將釋義放回確認自然。"],
    ],
    checks: [
      ["字典義項排序能直接決定本文意思嗎？", "不能", "上下文才決定。"],
      ["選義第一步先核對什麼？", "詞性", "排除句法功能不合者。"],
      ["替換測試的目的？", "確認釋義在原句自然且一致", "防止只靠熟悉度。"],
    ],
    questions: questions([
      ["bank: (1) a place for money; (2) land beside a river. 'Wild flowers grew along the bank.' Which sense fits?", "sense 2", "along 與 grew、river-area 情境支持河岸。", [["sense 1", "銀行建築不自然地與 wild flowers along 搭配。"], ["both senses equally", "本文自然地只啟動河岸義。"], ["neither sense", "sense 2 可完整替換。"]]],
      ["light: (1) brightness; (2) not heavy. 'This light chair is easy to carry.' Which sense fits light?", "sense 2", "chair easy to carry 指重量輕。", [["sense 1", "brightness 不能解釋 easy to carry。"], ["both", "本文只使用重量義。"], ["neither", "not heavy 可自然替換。"]]],
      ["match: (1) a sports game; (2) to go well together. 'The green tie matches his shirt.' Which sense fits?", "sense 2", "tie 與 shirt 在搭配上相稱。", [["sense 1", "matches 在此為動詞且不是比賽。"], ["both", "服裝句不啟動 sports game。"], ["neither", "go well together 完整符合。"]]],
      ["field: (1) open land; (2) an area of study or work. 'She hopes to enter the field of medicine.' Which sense fits?", "sense 2", "of medicine 明示專業領域。", [["sense 1", "medicine 不是戶外土地。"], ["both", "句中 enter 是進入專業，不是走進田野。"], ["neither", "area of work 可自然替換。"]]],
      ["current: (1) happening now; (2) moving water. 'The boat moved slowly against the current.' Which sense fits?", "sense 2", "boat against 的是水流。", [["sense 1", "against happening now 不構成此航行關係。"], ["both", "本文只有水流義。"], ["neither", "moving water 解釋船速。"]]],
      ["issue: (1) an important problem; (2) one edition of a magazine. 'This month's issue has an article on bees.' Which sense fits?", "sense 2", "this month's 與 article 指一期雜誌。", [["sense 1", "problem 不會 contain an article。"], ["both", "本文媒體搭配排除 problem。"], ["neither", "magazine edition 完整符合。"]]],
      ["run: (1) move quickly on foot; (2) manage or operate. 'Nora runs the community cafe.' Which sense fits?", "sense 2", "run 帶 cafe 受詞表示經營。", [["sense 1", "不能在 cafe 這個受詞上跑步。"], ["both", "本文只啟動 manage 義。"], ["neither", "manage the cafe 可替換。"]]],
      ["break: (1) damage into pieces; (2) a short rest. 'Let's take a ten-minute break.' Which sense fits?", "sense 2", "take a ... break 與 ten-minute 表休息。", [["sense 1", "damage 不能作 take a ten-minute 的名詞事件。"], ["both", "本文沒有損壞。"], ["neither", "short rest 精確符合。"]]],
      ["table: (1) furniture with a flat top; (2) facts arranged in rows and columns. 'Check the table for train times.' Which sense fits?", "sense 2", "train times 可在資料表查找。", [["sense 1", "家具本身不提供時刻資料。"], ["both", "本文資訊功能明確。"], ["neither", "rows/columns facts 可包含 times。"]]],
      ["charge: (1) ask a price; (2) fill a battery with power. 'The hotel will charge $200 for the room.' Which sense fits?", "sense 1", "$200 for room 明示收費。", [["sense 2", "沒有 battery 或 power。"], ["both", "價格搭配只啟動 ask a price。"], ["neither", "sense 1 可直接替換。"]]],
      ["draft: (1) an early version of writing; (2) a flow of cool air. 'Please review my first draft.' Which sense fits?", "sense 1", "review、my first 與寫作版本搭配。", [["sense 2", "cool air 不能被 review 為 my first version。"], ["both", "本文只有 writing context。"], ["neither", "early version 精確符合。"]]],
      ["face: (1) the front of a head; (2) deal with a difficult situation. 'The town must face the water problem.' Which sense fits?", "sense 2", "must 後動詞帶 problem，表示面對處理。", [["sense 1", "名詞 head front 不能接 must。"], ["both", "句法先排除名詞義。"], ["neither", "deal with 可自然替換。"]]],
    ], { type: "dictionary-sense-selection", operation: "choose-one-sense-by-context", misconception: "always-use-first-dictionary-sense" }),
  },
  {
    id: "ENG_R4_S266", process: "distinguish-literal-and-extended-sense", evidence: "熟字與抽象受詞、比喻關係或篇章功能形成的延伸用法",
    objectives: ["辨認熟字由具體義延伸到抽象義。", "利用受詞與語境判斷是否仍為字面動作。", "用不誇張的改述說明本文延伸義。"],
    sections: [
      ["熟字也可能陌生", "認得 branch 是樹枝，不代表理解 a branch of science。先看它搭配的是具體物件還是抽象概念。"],
      ["延伸義保留核心關係", "tree branch 從主幹分出；company branch 也從總部系統分出。延伸不是隨意新義，而是保留形狀、功能或關係。"],
      ["受詞是關鍵", "bridge a river 是跨越實體河川，bridge two ideas 是連結概念差距。ideas 這類抽象受詞提示延伸義。"],
      ["改述要最小", "不要把 warm welcome 推成天氣炎熱；只改述為 friendly welcome。保留原句真正啟動的抽象特徵。"],
    ],
    examples: [
      ["Education can open doors to new work.", ["doors 不是實體工作門。", "open doors 與 new work 搭配。", "延伸為創造機會。"], "create opportunities", "保留門讓人通過的核心關係。"],
      ["The article gives a clear picture of town life.", ["article 不提供照片。", "picture of life 是理解。", "延伸為 description。"], "a clear understanding", "不是實體圖像。"],
      ["Her warm reply made the visitor relax.", ["reply 沒有溫度。", "relax 是友善效果。", "warm 延伸為 friendly。"], "friendly and welcoming", "不能解成 hot。"],
    ],
    misconceptions: [
      ["熟字永遠使用最常見具體義。", "抽象搭配會啟動延伸義。", "先檢查受詞。"],
      ["延伸義可以任意想像。", "仍保留原義核心關係。", "指出形狀、功能或效果連結。"],
      ["看到 picture 一定有圖。", "可延伸為整體理解。", "看文章是否真有視覺物件。"],
      ["warm reply 表回信溫度高。", "語境描述態度。", "以 friendly 改述。"],
    ],
    checks: [
      ["open doors to work 通常是實體開門嗎？", "不是", "表示創造機會。"],
      ["判斷延伸義最有用的線索？", "抽象受詞與情境", "它們顯示字面動作不成立。"],
      ["延伸義仍保留什麼？", "原義的核心關係或效果", "不是完全無關的新意思。"],
    ],
    questions: questions([
      ["The new bridge program connects older volunteers with young readers. What does bridge mean here?", "bring two groups together", "受詞是 two groups，延伸保留跨越距離、建立連結。", [["build a road over water", "本文沒有 river 或實體工程。"], ["separate the age groups", "與 connects 相反。"], ["test the strength of a bridge", "program 功能是人際連結。"]]],
      ["Good sleep is the key to staying focused. What does key mean?", "the most important means or factor", "to staying focused 表解決或達成焦點的關鍵。", [["a metal tool for a lock", "sleep 不是實體金屬。"], ["a list of map signs", "沒有 map。"], ["a musical note", "沒有 music context。"]]],
      ["The school hopes the garden will grow into a center for community life. What does grow into mean?", "gradually become", "garden 由目前狀態發展成 community center role。", [["become physically taller only", "center for life 是功能轉變，不只高度。"], ["be cut into pieces", "與 grow 相反。"], ["move to another town", "地點移動未提。"]]],
      ["The article shines a light on problems faced by night workers. What does shines a light on mean?", "draws attention to and explains", "article 對 problems 的功能是揭示，不是實體照明。", [["uses a lamp at night", "article 不能使用實體 lamp。"], ["hides the problems", "與 light/attention 方向相反。"], ["solves every problem", "說明不等於全部解決。"]]],
      ["Mia gave the new student a warm welcome. What does warm mean?", "friendly", "welcome 是態度，warm 延伸為親切。", [["high in temperature", "welcome 沒有物理溫度。"], ["spoken outdoors", "地點未提。"], ["very short", "長度未提。"]]],
      ["The project took root after local shops began to support it. What does took root mean?", "became established", "shops support 使 project 穩定建立，借用植物扎根關係。", [["grew actual roots", "project 是抽象活動。"], ["was removed", "與 support 後發展相反。"], ["moved underground", "沒有實體位置。"]]],
      ["A wave of new visitors arrived after the video was shared. What is a wave here?", "a large group arriving in a short period", "visitors 是人群，wave 延伸表一批接一批到來。", [["moving sea water", "地點未必在 sea，受詞是 visitors。"], ["one visitor", "a wave 表大量。"], ["a hand movement", "沒有 greeting context。"]]],
      ["The report paints a clear picture of how families use the park. What does paints a clear picture mean?", "describes clearly", "report 以內容呈現理解，不是用 paint。", [["adds color to a paper picture", "how families use 是抽象資訊。"], ["changes the park signs", "report 不執行改造。"], ["hides family activity", "clear picture 與 hides 相反。"]]],
      ["The coach's words lifted the team's spirits. What does lifted their spirits mean?", "made them feel more hopeful", "words 對團隊情緒產生提升效果。", [["raised their bodies", "spirits 在此非身體。"], ["made them leave the field", "lifted 不表示離場。"], ["gave them a heavier task", "情緒結果不是 workload。"]]],
      ["The plan faces strong headwinds from rising costs. What are headwinds here?", "difficult forces working against the plan", "costs 對 plan 形成阻力，借用逆風概念。", [["winds blowing at a person's head", "plan 與 costs 是抽象情境。"], ["helpful support", "working against 與 support 相反。"], ["a weather report", "沒有實際天氣。"]]],
      ["This small success planted a seed of confidence in Ben. What does planted a seed mean?", "started the beginning of a feeling", "success 使 confidence 開始萌生，保留種子成長關係。", [["put a plant inside Ben", "confidence 是抽象感受。"], ["ended his confidence", "seed 表開始而非結束。"], ["taught him farming", "原文沒有農作技能。"]]],
      ["The club broke the ice with a simple game before discussion. What does broke the ice mean?", "made people feel less uncomfortable", "discussion 前遊戲用來打破陌生尷尬。", [["cracked frozen water", "club discussion 情境非實體冰。"], ["ended the meeting", "game 發生 before discussion，目的是開始互動。"], ["made the room colder", "情緒而非溫度。"]]],
    ], { type: "extended-familiar-word", operation: "map-literal-core-to-abstract-context", misconception: "force-literal-sense" }),
  },
];

export const ENGLISH_UNIT_SOURCE = defineEnglishUnit({
  unitId: "ENG_R4_U39",
  skills,
  vocabularyPolicy: {
    capQuestionBasis: "appendix-5-table-1",
    additionalLearningTerms: ["active", "activity", "add", "address", "adult", "against", "aloud", "amount", "ancient", "arrange", "asleep", "attention", "available", "avoid", "board", "branch", "cancel", "carrot", "cause", "certain", "character", "charge", "coach", "company", "complete", "concern", "create", "crowded", "current", "customer", "damage", "danger", "decision", "describe", "dessert", "discuss", "discussion", "electric", "empty", "equal", "extra", "fee", "fit", "flat", "focus", "frighten", "furniture", "greet", "guide", "hunger", "include", "lack", "lift", "liquid", "local", "lock", "magazine", "match", "measure", "memory", "metal", "movement", "narrow", "natural", "neither", "object", "ordinary", "pain", "path", "perfect", "period", "plain", "position", "print", "private", "produce", "project", "promise", "protect", "rather", "record", "repair", "return", "review", "role", "roof", "sense", "sheet", "shore", "sleepy", "soft", "solve", "spirit", "state", "stationery", "step", "stone", "success", "such", "sudden", "support", "temperature", "therefore", "toward", "usual", "waste", "weight", "wild"],
    contextualizedAboveRangeTerms: ["absorbent", "abundant", "account", "actual", "article", "balance", "battery", "bend", "benefit", "beverage", "bi", "bilingual", "boot", "brief", "brightness", "cafe", "celebration", "column", "community", "confidence", "connect", "contain", "contest", "context", "crack", "delete", "delivery", "description", "detail", "detour", "discreetly", "document", "draft", "drowsiness", "durable", "eager", "edible", "edition", "engaging", "equipment", "escape", "establish", "evidence", "exact", "exhaust", "extreme", "factor", "faint", "famished", "fictional", "field", "flexible", "flow", "fold", "folder", "force", "forever", "fragile", "freeze", "gradual", "habitat", "headwind", "highlight", "hopeful", "identical", "imagination", "instance", "instruction", "intend", "issue", "launch", "leak", "lecture", "manage", "material", "misleading", "musical", "nearby", "nocturnal", "observe", "online", "operate", "opportunity", "organize", "outdoors", "permanent", "portable", "press", "product", "prove", "purchase", "rail", "rapid", "reasonable", "refund", "relax", "reliable", "reluctant", "remove", "replace", "reply", "rigid", "risk", "route", "scarce", "schedule", "schoolwork", "seal", "separate", "shallow", "situation", "sleepiness", "slick", "slight", "slip", "slippery", "specific", "strength", "stuffy", "suitable", "sunlight", "tackle", "task", "tight", "timid", "transparent", "unable", "uncomfortable", "underground", "unlike", "unsafe", "unstable", "user", "vacant", "vague", "version", "volunteer", "workload"],
    properNames: ["Amy", "Ben", "Jay", "Leo", "Mia", "Nora"],
    grammarNotation: ["A", "B"],
    malformedDistractors: [],
  },
});
