const UNIT_ID = "ENG_R4_U10";

function lecture(id, skillId, content) {
  return {
    id,
    skillId,
    ...content,
    sections: content.sections.map((section, index) => ({
      id: `${id}_SEC_${String(index + 1).padStart(2, "0")}`,
      ...section,
    })),
  };
}

function question({
  id,
  skillId,
  difficulty,
  stem,
  options,
  answerIndex,
  reasons,
  reviews,
  cognitiveProcess,
  representationType = "sentence-cloze",
  misconceptionTargets = [],
}) {
  return {
    id,
    skillId,
    stem,
    options,
    answerIndex,
    reasons,
    difficulty,
    cognitiveProcess,
    representationType,
    misconceptionTargets,
    reviews,
  };
}

export const ENGLISH_U10_LECTURES = [
  lecture("ENG_R4_L_S064", "ENG_R4_S064", {
    objectives: [
      "辨認已在過去時間完成的事件，並以動詞過去式表達。",
      "從句意、事件順序與時間線索判斷是否應使用過去簡單式。",
    ],
    sections: [
      {
        title: "過去簡單式說明已完成的事",
        content: "說話時若事件已經結束，主要動詞要用過去式，例如 I finished my homework last night。這個形式著重事件發生並完成，不表示它現在仍在進行。即使句中沒有明寫 yesterday，只要上下文清楚把事件放在過去，也可使用過去式。",
      },
      {
        title: "一段話中的多個過去事件",
        content: "敘述過去經歷時，連續完成的動作通常都用過去式，例如 The bus arrived, and the doors opened。不要只把第一個動詞改成過去式；每個有自己主詞與動作的子句，都要依它的時間判斷形式。",
      },
      {
        title: "過去事件與習慣、現在動作的差別",
        content: "every day 常配現在簡單式，now 常配現在進行式，而 last night 常把事件放在過去。比較 Ben walks home every day、Ben is walking home now 與 Ben walked home yesterday，可看出動詞形式隨時間意義改變。",
      },
      {
        title: "先理解意思，再選形式",
        content: "不要只看句尾的一個時間字。先找事件是否已完成，再確認主句和連接詞前後的動作是否在同一段過去時間。若前後時間不同，兩個動詞不一定使用相同時態；判斷依據是各自表達的時間。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S064_EX_01",
        prompt: "Mia ___ her homework before dinner yesterday. (finishes / finished / is finishing)",
        steps: ["找出 yesterday，確認事件在過去。", "判斷作業在晚餐前已完成。", "把 finish 改成過去式 finished。"],
        answer: "finished",
        why: "yesterday 與 before dinner 都把完成作業放在已結束的時間，因此用 finished。finishes 表習慣，is finishing 表現在正在做，都不符合句意。",
      },
      {
        id: "ENG_R4_L_S064_EX_02",
        prompt: "The rain stopped, and then the game began. Which event happened first?",
        steps: ["找出兩個過去式動詞 stopped 與 began。", "用 then 確認第二件事開始。", "判定雨停在比賽開始之前。"],
        answer: "The rain stopped first.",
        why: "stopped 與 began 都表示完成事件，then 明確把比賽開始放在雨停之後。因此雨先停，比賽才開始；began 仍是過去式。",
      },
      {
        id: "ENG_R4_L_S064_EX_03",
        prompt: "Yesterday, Tom ___ his key, so he walked back home. (loses / lost / is losing)",
        steps: ["以 Yesterday 建立過去時間。", "由 walked 確認結果也在過去。", "選 lost 表示先前遺失鑰匙。"],
        answer: "lost",
        why: "walked 說明走回家是過去結果，前面的原因也應是已發生的遺失，所以選 lost。loses 是現在習慣，is losing 則像事件仍在發生。",
      },
    ],
    misconceptions: [
      {
        belief: "句中出現 yesterday，就只把最靠近它的動詞改成過去式。",
        whyWrong: "同一段過去敘事可能含有數個動作，每個動詞都要依自己的時間意義判斷。",
        correction: "逐一圈出各子句的主要動詞，確認每件事是否都在過去完成。",
      },
      {
        belief: "過去式表示事情很久以前發生，剛才的事不能使用。",
        whyWrong: "過去式的重點是事件在說話前已完成，不受距離現在多久限制。",
        correction: "last year 與 a minute ago 都可搭配過去式，只要事件已結束。",
      },
      {
        belief: "句中沒有明寫過去時間，就一定不能用過去式。",
        whyWrong: "前文、因果關係或敘事背景也能清楚建立過去時間。",
        correction: "除了時間詞，也要讀前後句是否已把故事放在過去。",
      },
      {
        belief: "兩個動詞以 and 連接時，只需要第一個動詞標示過去。",
        whyWrong: "and 不會替第二個動詞提供過去式形式，兩個完成動作都需正確變化。",
        correction: "確認 and 兩側的主要動詞都符合各自的主詞與時間。",
      },
    ],
    checks: [
      { prompt: "We visited the museum last Saturday. 哪個字表示主要動作？", answer: "visited", reason: "visited 是 visit 的過去式，表示參觀已完成。" },
      { prompt: "The bus arrived, and we got on. 共有幾個完成事件？", answer: "two", reason: "arrived 與 got on 分別表示兩個已完成的動作。" },
      { prompt: "Ben walks home every day. 這句是否描述單一過去事件？", answer: "no", reason: "every day 表習慣，walks 是現在簡單式。" },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S065", "ENG_R4_S065", {
    objectives: [
      "依動詞字尾形成規則動詞的過去式。",
      "區分直接加 -ed、加 -d、改 y 為 ied 與重複字尾再加 -ed。",
    ],
    sections: [
      {
        title: "多數規則動詞加 -ed",
        content: "多數規則動詞在字尾加 -ed，例如 wash → washed、visit → visited。若原形已以 e 結尾，只加 -d，例如 live → lived。形成過去式後仍要確認拼字，不能把 live 寫成 liveed。",
      },
      {
        title: "子音加 y 與母音加 y",
        content: "動詞以子音字母加 y 結尾時，把 y 改為 i 再加 -ed，例如 study → studied、carry → carried。若 y 前是母音，則保留 y 直接加 -ed，例如 play → played、enjoy → enjoyed。",
      },
      {
        title: "短母音後的字尾重複",
        content: "某些短而重讀的動詞以單一母音加單一子音結尾時，要重複最後一個子音再加 -ed，例如 stop → stopped、plan → planned。字尾是 w、x 或 y 時通常不重複，例如 snowed、fixed、played。",
      },
      {
        title: "拼字規則不能取代句意判斷",
        content: "先確認句子需要過去式，再套用拼字規則。若句子有 did 或 did not，後面的動詞要回到原形，不寫 did studied。規則動詞的拼字與助動詞結構是兩個不同層次，必須分開處理。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S065_EX_01",
        prompt: "We ___ near the station last year. (live / lived / liveed)",
        steps: ["last year 要求過去式。", "live 已以 e 結尾。", "只加 -d，得到 lived。"],
        answer: "lived",
        why: "live 的字尾已有 e，所以過去式只補 d，形成 lived。live 沒有標示過去，liveed 則重複加入不需要的 e。",
      },
      {
        id: "ENG_R4_L_S065_EX_02",
        prompt: "Nora ___ the box into the room yesterday. (carryed / carried / carrid)",
        steps: ["確認 carry 以子音加 y 結尾。", "把 y 改成 i。", "再加 -ed，形成 carried。"],
        answer: "carried",
        why: "carry 的 y 前是子音 r，因此要把 y 改為 i 再加 -ed，寫成 carried。carryed 沒有改 y，carrid 則少了 e。",
      },
      {
        id: "ENG_R4_L_S065_EX_03",
        prompt: "The bus ___ at the corner. (stoped / stopped / stopied)",
        steps: ["stop 是短母音加單一子音結尾。", "重複最後的 p。", "加 -ed，得到 stopped。"],
        answer: "stopped",
        why: "stop 的字尾符合重複子音的條件，所以要寫 stopped。stoped 少了一個 p，stopied 則誤用了子音加 y 的規則。",
      },
    ],
    misconceptions: [
      {
        belief: "所有規則動詞只要在原形後面直接接 ed。",
        whyWrong: "字尾 e、子音加 y，以及部分短母音字尾都有不同拼法。",
        correction: "先辨認原形最後幾個字母，再選擇對應的規則。",
      },
      {
        belief: "只要動詞以 y 結尾，就把 y 改成 ied。",
        whyWrong: "play、enjoy 的 y 前是母音，必須保留 y。",
        correction: "檢查 y 前一個字母；子音才改 ied，母音則直接加 ed。",
      },
      {
        belief: "任何短動詞都要重複最後一個字母再加 ed。",
        whyWrong: "需要同時符合適當的母音與子音字尾，w、x、y 也通常不重複。",
        correction: "不要只看字長，要檢查實際字尾結構。",
      },
      {
        belief: "did 後面仍要保留規則動詞的 -ed。",
        whyWrong: "did 已承擔過去時間，後面的主要動詞必須使用原形。",
        correction: "問句與否定句看到 did，就把主要動詞還原。",
      },
    ],
    checks: [
      { prompt: "study 的過去式是什麼？", answer: "studied", reason: "y 前是子音 d，因此改 y 為 ied。" },
      { prompt: "play 的過去式是否為 plaied？", answer: "no", reason: "y 前是母音 a，應保留 y 寫 played。" },
      { prompt: "plan 的過去式為什麼有兩個 n？", answer: "planned", reason: "plan 的字尾符合重複最後子音再加 ed 的條件。" },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S066", "ENG_R4_S066", {
    objectives: [
      "辨認常見不規則動詞的過去式，並放入正確語境。",
      "避免把不規則動詞誤加 -ed，或在 did 後保留過去式。",
    ],
    sections: [
      {
        title: "不規則動詞沒有單一拼字公式",
        content: "go → went、see → saw、take → took 等過去式不能只靠加 -ed 形成。學習時要把原形、過去式和例句一起記，才能在句中辨認。goed、seed、taked 都不是這些動詞的標準過去式。",
      },
      {
        title: "依句意選擇正確動詞",
        content: "只記形狀不夠，還要確認動詞意思。例如 bought 來自 buy，表示買；brought 來自 bring，表示帶來。兩者拼字相近，但事件不同，應由受詞、地點與前後文判斷。",
      },
      {
        title: "有些形式看起來沒有改變",
        content: "read 的原形與過去式拼字相同，但讀音不同；句中的 yesterday 或其他過去背景會告訴你它是過去式。不要因拼字未變，就認定句子一定是現在時間。",
      },
      {
        title: "did 會讓主要動詞回到原形",
        content: "肯定句寫 She went home，但問句是 Did she go home?，否定句是 She did not go home。went 的不規則形式只在沒有 did 的肯定過去句中使用；did 已經標出過去。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S066_EX_01",
        prompt: "Ken ___ home after practice yesterday. (go / went / goed)",
        steps: ["yesterday 建立過去時間。", "go 是不規則動詞。", "選它的過去式 went。"],
        answer: "went",
        why: "回家已在昨天完成，go 的標準過去式是 went，不是直接加 ed 的 goed。原形 go 也不能單獨放在這個肯定過去句中。",
      },
      {
        id: "ENG_R4_L_S066_EX_02",
        prompt: "My father ___ fruit at the market and paid for it. (bought / brought / buyed)",
        steps: ["paid for it 表示父親付錢取得水果。", "選 buy 的不規則過去式。", "排除表示帶來的 brought。"],
        answer: "bought",
        why: "paid for it 說明動作是購買，因此要用 buy 的過去式 bought。brought 表示帶來，buyed 則不是標準的過去式。",
      },
      {
        id: "ENG_R4_L_S066_EX_03",
        prompt: "Did Lily ___ the letter yesterday? (write / wrote / written)",
        steps: ["Did 已標示過去時間。", "問句中的主要動詞使用原形。", "選 write，不保留 wrote。"],
        answer: "write",
        why: "Did 已經承擔過去式，因此主要動詞必須回到原形 write。wrote 適用於肯定過去句，written 不能在此單獨作主要動詞。",
      },
    ],
    misconceptions: [
      {
        belief: "不熟悉的過去式都可以在原形後加 ed。",
        whyWrong: "常見動詞中有許多不規則變化，直接加 ed 會產生不存在的形式。",
        correction: "把常見不規則動詞成組學習，並在完整句子中練習。",
      },
      {
        belief: "bought 和 brought 拼字相近，所以兩者可以互換。",
        whyWrong: "bought 表示買，brought 表示帶來，動作意義不同。",
        correction: "先讀情境需要哪個原形，再回想它的過去式。",
      },
      {
        belief: "read 拼字沒變，因此任何 read 都是現在式。",
        whyWrong: "read 的過去式與原形同形，需由時間與讀音辨認。",
        correction: "看到同形動詞時，利用時間詞和上下文判定時態。",
      },
      {
        belief: "Did she went home 同時用了兩個過去形式，所以更完整。",
        whyWrong: "did 已標出過去，went 再標一次會造成錯誤的雙重變化。",
        correction: "Did 後使用原形 go，肯定句沒有 did 時才用 went。",
      },
    ],
    checks: [
      { prompt: "take 的過去式是什麼？", answer: "took", reason: "take 是不規則動詞，過去式為 took。" },
      { prompt: "bought 的原形是什麼？", answer: "buy", reason: "bought 表示已買，是 buy 的過去式。" },
      { prompt: "Did you saw it? 應改哪個字？", answer: "saw → see", reason: "did 後主要動詞要用原形 see。" },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S067", "ENG_R4_S067", {
    objectives: [
      "使用 did 形成過去式的一般問句、特殊問句與否定句。",
      "在 did 或 did not 後使用動詞原形，並組成自然回答。",
    ],
    sections: [
      {
        title: "一般問句：Did 加主詞與原形動詞",
        content: "把過去肯定句 You called Amy 改成問句時，使用 Did you call Amy?。Did 放在主詞前，主要動詞回到原形。簡答可用 Yes, I did 或 No, I did not，不需要重複整個句子。",
      },
      {
        title: "否定句：did not 加原形動詞",
        content: "過去否定句使用 subject + did not + 原形動詞，例如 We did not miss the bus。did not 可縮寫為 didn't。不能寫 did not missed，因為過去時間已由 did 表示。",
      },
      {
        title: "特殊問句保留疑問詞",
        content: "詢問時間、地點、原因或事物時，結構是疑問詞 + did + 主詞 + 原形動詞，例如 Where did Ben put the key?。疑問詞負責指定所問資訊，did 負責過去時間。",
      },
      {
        title: "be 動詞不使用 did",
        content: "若過去句的主要動詞是 was 或 were，問句直接把 was/were 移到主詞前，例如 Was Mia tired?，否定句是 Mia was not tired。不要寫 Did Mia be tired?，這是一般動詞與 be 動詞結構混用。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S067_EX_01",
        prompt: "___ you call your aunt last night? (Did / Do / Were)",
        steps: ["last night 表過去。", "call 是一般動詞。", "把 Did 放在主詞 you 前。"],
        answer: "Did",
        why: "call 是一般動詞，且事件在 last night，因此問句以 Did 開頭。Do 是現在式問句，Were 不能直接搭配原形 call。",
      },
      {
        id: "ENG_R4_L_S067_EX_02",
        prompt: "Sara did not ___ her lunch. (bring / brought / brings)",
        steps: ["找出 did not。", "主要動詞必須使用原形。", "選 bring。"],
        answer: "bring",
        why: "did not 已經表示過去否定，所以後面接原形 bring。brought 又標一次過去，brings 則是現在簡單式第三人稱形式。",
      },
      {
        id: "ENG_R4_L_S067_EX_03",
        prompt: "What did Mina ___ at the store? (buy / bought / buying)",
        steps: ["What 詢問所買的事物。", "did 建立過去問句。", "主要動詞使用原形 buy。"],
        answer: "buy",
        why: "疑問詞 What 之後已有 did，Mina 後面應接原形 buy。bought 造成雙重過去，buying 則缺少形成進行式所需的 be。",
      },
    ],
    misconceptions: [
      {
        belief: "過去問句中的 did 和主要動詞都要變成過去式。",
        whyWrong: "did 已承擔時態，主要動詞再變化會形成雙重過去。",
        correction: "看到 did，立即檢查後面的主要動詞是否為原形。",
      },
      {
        belief: "所有過去問句都可使用 Did，包括以 was 或 were 為主要動詞的句子。",
        whyWrong: "be 動詞自己可以移到主詞前，不需要 did。",
        correction: "先判斷主要動詞是一般動詞還是 was/were，再選問句結構。",
      },
      {
        belief: "特殊問句只要把疑問詞放在肯定句前面即可。",
        whyWrong: "一般動詞的過去特殊問句仍需要 did，並調整主詞與動詞順序。",
        correction: "使用疑問詞 + did + 主詞 + 原形動詞。",
      },
      {
        belief: "Did you...? 的肯定簡答可以說 Yes, I do。",
        whyWrong: "簡答的助動詞要和問句時態一致，do 是現在式。",
        correction: "過去問句以 did 提問時，用 Yes, I did 或 No, I didn't。",
      },
    ],
    checks: [
      { prompt: "Did Ben went home? 哪個字要改？", answer: "went → go", reason: "did 後使用原形 go。" },
      { prompt: "We did not missed the bus. 哪個字要改？", answer: "missed → miss", reason: "did not 後使用原形 miss。" },
      { prompt: "Was Amy at school? 是否需要 did？", answer: "no", reason: "was 是 be 動詞，可直接移到主詞前。" },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S068", "ENG_R4_S068", {
    objectives: [
      "依過去句的主詞選用 was 或 were。",
      "使用 was/were 形成陳述句、否定句、問句與 there was/were 結構。",
    ],
    sections: [
      {
        title: "was 與 were 的主詞搭配",
        content: "I、he、she、it 與單數名詞在過去搭配 was；you、we、they 與複數名詞搭配 were。例如 I was tired、The keys were on the desk。判斷時看真正主詞，不要被主詞後方的複數名詞干擾。",
      },
      {
        title: "否定句與問句",
        content: "否定句在 was/were 後加 not，例如 They were not late。問句把 was/were 移到主詞前，例如 Were they late?。was/were 本身就是過去式，不需再加入 did。",
      },
      {
        title: "there was 與 there were",
        content: "表示過去某處有某物時，後方名詞為單數用 there was，複數用 there were，例如 There was one seat、There were two seats。真正決定形式的是後面的名詞數量。",
      },
      {
        title: "找核心主詞，不看最近名詞",
        content: "The box of photos was under the bed 中，主詞核心是單數 box，of photos 只是補充內容，因此使用 was。若主詞是 Amy and I，and 連接兩人，整體為複數，要用 were。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S068_EX_01",
        prompt: "I ___ tired after the race. (was / were / did)",
        steps: ["主詞是 I。", "時間在比賽之後的過去。", "I 的過去 be 動詞用 was。"],
        answer: "was",
        why: "I 在過去式固定搭配 was，所以答案是 was。were 配複數主詞或 you，did 則不能直接接形容詞 tired。",
      },
      {
        id: "ENG_R4_L_S068_EX_02",
        prompt: "There ___ three messages on my phone. (was / were / did)",
        steps: ["找 there 後面的名詞 messages。", "three messages 是複數。", "複數存在句使用 were。"],
        answer: "were",
        why: "there 後面是 three messages，數量為複數，因此用 were。was 只適合 one message，did 不能建立這種存在句。",
      },
      {
        id: "ENG_R4_L_S068_EX_03",
        prompt: "When we looked, the box of old photos ___ under the bed. (was / were / did)",
        steps: ["找主詞核心 box。", "of old photos 只是修飾 box。", "單數 box 搭配 was。"],
        answer: "was",
        why: "核心主詞是單數 box，不是離空格較近的複數 photos，所以使用 was。若只看最近名詞，才會誤選 were。",
      },
    ],
    misconceptions: [
      {
        belief: "I 是說話者一個人，卻要和複數一樣使用 were。",
        whyWrong: "一般過去陳述中 I 固定搭配 was，不按字面人數推測。",
        correction: "記住 I was 與 you were 這兩個常用搭配。",
      },
      {
        belief: "空格前最近出現複數名詞，就一定選 were。",
        whyWrong: "介系詞片語中的名詞可能不是主詞核心。",
        correction: "先找完整主詞的中心名詞，再判斷單複數。",
      },
      {
        belief: "there was/were 的形式由句首 there 決定。",
        whyWrong: "there 不代表數量，真正依據是後方存在的人或物。",
        correction: "one item 用 was，two or more items 用 were。",
      },
      {
        belief: "過去 be 動詞問句仍要在句首加 Did。",
        whyWrong: "was/were 可以自行移到主詞前，加入 did 反而破壞結構。",
        correction: "直接形成 Was she...? 或 Were they...?。",
      },
    ],
    checks: [
      { prompt: "You ___ right about the time.", answer: "were", reason: "you 在過去式搭配 were。" },
      { prompt: "There ___ one empty chair.", answer: "was", reason: "one chair 是單數，使用 was。" },
      { prompt: "___ the windows open?", answer: "Were", reason: "windows 是複數，問句把 Were 放在主詞前。" },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S069", "ENG_R4_S069", {
    objectives: [
      "辨認 yesterday、ago、last 與明確過去年份等時間線索。",
      "結合說話時間和上下文，避免把每個含 today 的句子都判成現在式。",
    ],
    sections: [
      {
        title: "常見的過去時間線索",
        content: "yesterday、last night、two days ago 與 in 2020 都把事件放在已結束的時間。ago 從現在往前計算，last 加一段時間表示上一個已結束的期間。這些線索通常與過去簡單式搭配。",
      },
      {
        title: "this morning 要看說話時刻",
        content: "若現在已是 evening，this morning 已經結束，可說 I met Ben this morning。若上午仍在進行，句意可能不同。時間片語本身不總是足夠，還要看說話時刻與事件是否完成。",
      },
      {
        title: "過去開始不代表現在一定結束",
        content: "The library opened in 2020 中，opened 是過去事件；圖書館現在仍可營運。過去式只說明開幕發生在過去，不自動表示開幕造成的狀態已消失。",
      },
      {
        title: "日記與相對時間",
        content: "日記中的 yesterday 要以日記日期為基準。若一篇日記標示 Monday，文中 yesterday 指 Sunday，不是讀者閱讀日記的前一天。先找敘述立足點，再換算相對時間。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S069_EX_01",
        prompt: "My aunt ___ here five years ago. (lives / lived / is living)",
        steps: ["辨認 five years ago。", "ago 表示從現在往前的已結束時間。", "使用過去式 lived。"],
        answer: "lived",
        why: "five years ago 明確指向過去，所以 live 要改成 lived。lives 表現在習慣，is living 表目前一段時間，兩者都不配 ago。",
      },
      {
        id: "ENG_R4_L_S069_EX_02",
        prompt: "It is evening now. I ___ Nora this morning. (meet / met / am meeting)",
        steps: ["現在是 evening。", "this morning 已結束。", "用 met 表示上午已完成的見面。"],
        answer: "met",
        why: "說話時已到 evening，今天上午屬於已結束的時間，因此選 met。不能只看到 this 就誤以為一定使用現在式。",
      },
      {
        id: "ENG_R4_L_S069_EX_03",
        prompt: "A Monday diary says, “Yesterday we climbed the hill.” When did they climb it?",
        steps: ["找出日記日期 Monday。", "把 yesterday 往前推一天。", "得到 Sunday。"],
        answer: "Sunday",
        why: "yesterday 的基準是日記中的 Monday，所以所指日期是 Sunday。不能以今天閱讀日記的日期另行計算。",
      },
    ],
    misconceptions: [
      {
        belief: "句中只要有 this，就一定要使用現在式。",
        whyWrong: "this morning 在晚上回顧時已是完成的過去時段。",
        correction: "判斷整段時間是否已結束，而不是只看單一指示詞。",
      },
      {
        belief: "ago 前面的數字越大，才越需要過去式。",
        whyWrong: "one minute ago 和 ten years ago 都表示已過去的時間。",
        correction: "看到 ago 就從說話時刻往前定位，不以距離長短決定。",
      },
      {
        belief: "opened in 2020 表示該地點現在一定已關閉。",
        whyWrong: "opened 只描述開幕事件，不能推出目前營運狀態。",
        correction: "把過去發生的事件與現在是否持續分開判讀。",
      },
      {
        belief: "日記中的 yesterday 永遠是讀者今天的前一天。",
        whyWrong: "相對時間要以文本建立的日期或說話時刻為基準。",
        correction: "先找到日記日期，再計算 yesterday、today 與 tomorrow。",
      },
    ],
    checks: [
      { prompt: "Which time words show a finished past time: now or last Friday?", answer: "last Friday", reason: "last Friday 是已結束的上一個星期五。" },
      { prompt: "two hours ago 應從哪個時刻往前算？", answer: "now", reason: "ago 以說話當下為基準往前計算。" },
      { prompt: "A store opened in 2018. 能否只憑這句判定商店已關閉？", answer: "no", reason: "句子只提供開幕時間，沒有目前是否營業的資訊。" },
    ],
    assets: [],
  }),
  lecture("ENG_R4_L_S070", "ENG_R4_S070", {
    objectives: [
      "利用 before、after、then、later 與 finally 排列過去事件。",
      "整合句子順序、連接詞與因果資訊，重建敘事時間線。",
    ],
    sections: [
      {
        title: "連接詞直接標示事件關係",
        content: "A happened before B 表示 A 在前；A happened after B 表示 B 在前。不要只依英文句中出現的先後位置判斷，因為 after 子句可以放在句首或句尾，位置不會改變它和主句的時間關係。先列出動作，再依連接詞排序。",
      },
      {
        title: "then、later 與 finally 推進故事",
        content: "then 和 later 把敘事往後推，finally 通常引出最後結果。例如 We found the stop, then we got on the bus, and finally we reached home。這些詞協助讀者追蹤順序，但每個動詞仍需符合過去時間。",
      },
      {
        title: "敘述順序不一定等於發生順序",
        content: "After Mia locked the door, she checked her bag 先寫 After 子句，但事件仍是鎖門在前、檢查袋子在後。讀故事時要依 before/after 的意義，而不是機械地把第一個看到的動詞當成第一件事。",
      },
      {
        title: "因果與先後要分開確認",
        content: "because 說明原因，so 引出結果，常可協助判斷事件關係，但它們主要標示因果。若題目問精確先後，仍要查看時間詞、上下文或是否有明確完成動作，不能把所有原因都當成最早事件。",
      },
    ],
    workedExamples: [
      {
        id: "ENG_R4_L_S070_EX_01",
        prompt: "Mia packed her bag before she left home. What happened first?",
        steps: ["找出 packed 與 left。", "before 表示前一動作較早。", "確定 packed her bag 在先。"],
        answer: "Mia packed her bag first.",
        why: "before 清楚說明打包發生在離家之前，因此第一件事是 packed her bag。兩個動詞雖都用過去式，仍可由連接詞排出先後。",
      },
      {
        id: "ENG_R4_L_S070_EX_02",
        prompt: "After Ben locked the door, he checked his bag. What happened second?",
        steps: ["After 子句中的 locked 先發生。", "主句 checked 接著發生。", "把 checked his bag 列為第二件事。"],
        answer: "He checked his bag second.",
        why: "After Ben locked the door 建立第一件事，主句 he checked his bag 才是後續動作。不能只因 checked 位在主句就忽略 after 的順序功能。",
      },
      {
        id: "ENG_R4_L_S070_EX_03",
        prompt: "We missed the bus. Later, we found another way home. Which word moves the story forward?",
        steps: ["第一句建立錯過公車的事件。", "第二句開頭有 Later。", "Later 表示較後的時間。"],
        answer: "Later",
        why: "Later 把找到回家方法放在錯過公車之後，讓故事往下一個時間點推進。它不是原因詞，也不表示兩件事同時發生。",
      },
    ],
    misconceptions: [
      {
        belief: "英文句中先出現的動詞一定代表最早發生的事件。",
        whyWrong: "after 或 before 子句會改變表面語序與實際時間順序的關係。",
        correction: "先解讀連接詞，再把事件放到時間線上。",
      },
      {
        belief: "after A, B 表示 B 在 A 之前。",
        whyWrong: "after A 建立 A 已先完成，B 才在其後發生。",
        correction: "把 after 理解為完成 A 之後，再進行 B。",
      },
      {
        belief: "finally 可以放在故事中任何位置，不影響順序。",
        whyWrong: "finally 通常引出最後階段或結果，位置錯誤會改變敘事。",
        correction: "確認 finally 後的事件確實是整段過程的最後一步。",
      },
      {
        belief: "有 because 的句子中，because 後面的事永遠是整篇故事第一件事。",
        whyWrong: "because 標示直接原因，不一定提供故事中所有事件的完整時間排序。",
        correction: "因果可協助理解，但精確先後仍以全文時間線索為準。",
      },
    ],
    checks: [
      { prompt: "A happened before B. 哪件事先發生？", answer: "A", reason: "before 直接表示 A 在 B 之前。" },
      { prompt: "After the bell rang, students left. 哪件事後發生？", answer: "students left", reason: "離開發生在鐘響之後。" },
      { prompt: "then 與 finally 哪個較常引出最後結果？", answer: "finally", reason: "finally 通常標示過程的最後階段。" },
    ],
    assets: [],
  }),
];

export const ENGLISH_U10_QUESTIONS = [
  question({
    id: "ENG_R4_Q_064_01",
    skillId: "ENG_R4_S064",
    difficulty: "foundation",
    stem: "Mia ___ her homework before dinner yesterday.",
    options: ["finished", "finishes", "is finishing", "will finish"],
    answerIndex: 0,
    reasons: ["finished 表示作業已在昨天完成。", "finishes 表示現在的習慣。", "is finishing 表示目前正在完成。", "will finish 表示未來才會完成。"],
    reviews: ["yesterday 與 before dinner 都把事件放在已結束的過去時間。", "只有 finished 同時符合過去時間與完成事件；其餘三項分屬現在習慣、現在進行與未來。"],
    cognitiveProcess: ["locate-finished-homework-in-past", "select-past-finish-form"],
    misconceptionTargets: ["ignore-explicit-yesterday"],
  }),
  question({
    id: "ENG_R4_Q_064_02",
    skillId: "ENG_R4_S064",
    difficulty: "foundation",
    stem: "Last night, the lights ___ out at ten.",
    options: ["go", "went", "goes", "are going"],
    answerIndex: 1,
    reasons: ["go 是原形，不能單獨表示昨晚的完成事件。", "went 是 go 的過去式，符合 last night。", "goes 是現在簡單式第三人稱形式。", "are going 表示目前正在進行。"],
    reviews: ["last night 和 at ten 指向昨晚十點，熄燈事件已完成。", "went out 是自然的過去表達；其他選項都沒有正確標示該過去時間。"],
    cognitiveProcess: ["interpret-last-night-power-event", "retrieve-went-for-go-out"],
    representationType: "past-event-cloze",
    misconceptionTargets: ["regularize-go-as-present"],
  }),
  question({
    id: "ENG_R4_Q_064_03",
    skillId: "ENG_R4_S064",
    difficulty: "foundation",
    stem: "Ben visited his aunt on Sunday. When did the visit happen?",
    options: ["Every Sunday", "Right now", "On Sunday", "Next Sunday"],
    answerIndex: 2,
    reasons: ["Every Sunday 會把事件解讀成固定習慣。", "Right now 與過去式 visited 不符。", "On Sunday 直接重述文中的完成時間。", "Next Sunday 指未來，文中沒有此意。"],
    reviews: ["visited 是過去式，on Sunday 明確提供該次探訪的時間。", "題目問這一次探訪何時發生，第三項有直接文本證據且不擴大成習慣。"],
    cognitiveProcess: ["extract-visit-time-from-completed-sentence", "separate-single-event-from-habit"],
    representationType: "time-detail-question",
    misconceptionTargets: ["turn-one-sunday-into-weekly-habit"],
  }),
  question({
    id: "ENG_R4_Q_064_04",
    skillId: "ENG_R4_S064",
    difficulty: "standard",
    stem: "We ___ the museum last Saturday.",
    options: ["visit", "visits", "are visiting", "visited"],
    answerIndex: 3,
    reasons: ["visit 是原形，未標示過去。", "visits 不配主詞 We，且是現在式。", "are visiting 表示正在參觀。", "visited 表示上星期六已完成參觀。"],
    reviews: ["last Saturday 是已結束的時間，主詞 We 的肯定過去句使用 visited。", "第四項在時態與主詞上都成立；其他形式分別缺少過去、主詞不合或表示現在進行。"],
    cognitiveProcess: ["map-last-saturday-to-completed-visit", "reject-present-visit-forms"],
    misconceptionTargets: ["choose-progressive-for-group-activity"],
  }),
  question({
    id: "ENG_R4_Q_064_05",
    skillId: "ENG_R4_S064",
    difficulty: "standard",
    stem: "The bus arrived, and the doors opened. What does the sentence report?",
    options: ["Two completed events in the past", "One daily habit", "Two actions happening now", "One plan for tomorrow"],
    answerIndex: 0,
    reasons: ["arrived 和 opened 都是過去式，表示兩件完成事件。", "句中沒有 every day 等習慣線索。", "目前動作通常需要 are arriving、are opening 等形式。", "句中沒有 will 或 tomorrow。"],
    reviews: ["兩個子句各有過去式動詞，先報告公車抵達，再報告車門打開。", "只有第一項能同時解釋 arrived 與 opened；其餘項目改變了時間或事件數量。"],
    cognitiveProcess: ["count-past-events-across-coordination", "classify-arrived-opened-report"],
    representationType: "event-structure-classification",
    misconceptionTargets: ["read-and-as-single-action"],
  }),
  question({
    id: "ENG_R4_Q_064_06",
    skillId: "ENG_R4_S064",
    difficulty: "standard",
    stem: "Sara cooked dinner and then washed the dishes. Which event happened second?",
    options: ["Sara cooked dinner.", "Sara washed the dishes.", "Sara bought the dishes.", "Sara left before dinner."],
    answerIndex: 1,
    reasons: ["cooked dinner 出現在 then 之前，是第一件事。", "then 把 washed the dishes 放在第二個時間點。", "文中沒有買餐具。", "文中沒有離開或 before 的資訊。"],
    reviews: ["then 明確推進事件，煮完晚餐後才洗餐具。", "第二項直接對應 then 後的過去事件；第三、四項都加入原句沒有的內容。"],
    cognitiveProcess: ["order-cooked-and-washed-events", "use-then-to-identify-second-action"],
    representationType: "two-event-order-question",
    misconceptionTargets: ["select-first-mentioned-event-as-answer"],
  }),
  question({
    id: "ENG_R4_Q_064_07",
    skillId: "ENG_R4_S064",
    difficulty: "standard",
    stem: "Yesterday, Tom ___ his key, so he walked back home.",
    options: ["loses", "is losing", "lost", "will lose"],
    answerIndex: 2,
    reasons: ["loses 表現在習慣，不能說明昨天走回家的原因。", "is losing 表目前進行，時間與 walked 不合。", "lost 是過去式，可作 walked back home 的先前原因。", "will lose 是未來式，不能造成已發生的結果。"],
    reviews: ["Yesterday 和 walked 共同建立過去情境，遺失鑰匙也須是過去事件。", "lost 能形成合理因果：先遺失鑰匙，再走回家；其餘時態無法和結果對齊。"],
    cognitiveProcess: ["infer-past-cause-of-walked-home", "align-lost-with-past-result"],
    misconceptionTargets: ["leave-cause-in-present-tense"],
  }),
  question({
    id: "ENG_R4_Q_064_08",
    skillId: "ENG_R4_S064",
    difficulty: "advanced",
    stem: "The rain stopped before the game began. Which answer gives the right order?",
    options: ["The game began before the rain stopped.", "Both events will happen tomorrow.", "Both events happen every day.", "The rain stopped first, and the game began later."],
    answerIndex: 3,
    reasons: ["這一項顛倒 before 所表示的順序。", "stopped 與 began 都不是未來式。", "句中沒有日常習慣線索。", "before 表明雨先停，比賽後開始。"],
    reviews: ["stopped 和 began 都是完成事件，before 再提供先後關係。", "第四項保留時態和事件順序；前三項分別顛倒順序或改成未來、習慣。"],
    cognitiveProcess: ["combine-past-aspect-with-before-order", "validate-rain-game-timeline"],
    representationType: "timeline-inference",
    misconceptionTargets: ["reverse-before-relation"],
  }),
  question({
    id: "ENG_R4_Q_064_09",
    skillId: "ENG_R4_S064",
    difficulty: "advanced",
    stem: "A note says, “I left the book on your desk this morning.” Which words name the completed action?",
    options: ["left the book", "on your desk", "this morning", "A note says"],
    answerIndex: 0,
    reasons: ["left the book 是主詞完成的動作。", "on your desk 說明地點，不是動作。", "this morning 說明時間，不是動作。", "A note says 是題目外層的引介。"],
    reviews: ["left 是 leave 的過去式，連同受詞 the book 構成完成動作。", "地點與時間只補充事件，不能取代主要動詞片語，所以第一項唯一符合。"],
    cognitiveProcess: ["isolate-action-from-time-and-place", "identify-left-book-as-past-predicate"],
    representationType: "sentence-part-function",
    misconceptionTargets: ["mistake-time-phrase-for-action"],
  }),
  question({
    id: "ENG_R4_Q_064_10",
    skillId: "ENG_R4_S064",
    difficulty: "advanced",
    stem: "The shop ___ at nine but ___ early because of the rain.",
    options: ["opens / closed", "opened / closed", "is opening / closes", "opened / is closing"],
    answerIndex: 1,
    reasons: ["opens 把第一件事變成現在習慣，與單次 closed 不一致。", "opened 與 closed 都把同一天的兩件事放在過去。", "is opening 與 closes 都是現在時間。", "is closing 把第二件事改成目前進行。"],
    reviews: ["but 連接同一天的開門與提早關門，兩件事都已完成。", "第二組讓兩個主要動詞共享過去背景；其他組至少有一個動詞落在現在時間。"],
    cognitiveProcess: ["coordinate-two-shop-actions-in-past", "select-consistent-open-close-pair"],
    representationType: "paired-verb-cloze",
    misconceptionTargets: ["mix-present-and-past-in-one-report"],
  }),
  question({
    id: "ENG_R4_Q_064_11",
    skillId: "ENG_R4_S064",
    difficulty: "transfer",
    stem: "The train was late, so we took a bus. What did the group do because the train was late?",
    options: ["They waited for tomorrow.", "They made the train late.", "They took a bus.", "They are taking a train now."],
    answerIndex: 2,
    reasons: ["文中沒有等待到明天。", "句子沒有說這群人造成火車誤點。", "so 後的 took a bus 是因誤點採取的行動。", "這一項改成現在搭火車，和原句不同。"],
    reviews: ["was late 是原因，so 引出已完成的結果 took a bus。", "第三項直接回答 did...do 的過去問題，沒有增加或更改交通資訊。"],
    cognitiveProcess: ["trace-delay-to-past-response", "answer-what-group-did-from-so-clause"],
    representationType: "past-cause-result-comprehension",
    misconceptionTargets: ["confuse-cause-with-agent-action"],
  }),
  question({
    id: "ENG_R4_Q_064_12",
    skillId: "ENG_R4_S064",
    difficulty: "transfer",
    stem: "A student writes about yesterday: “I walk to the park and played ball.” Which change puts both events in the past?",
    options: ["I walk to the park and play ball.", "I am walking to the park and played ball.", "I walks to the park and played ball.", "I walked to the park and played ball."],
    answerIndex: 3,
    reasons: ["兩個動詞都變成現在式，沒有表達 yesterday。", "第一個動詞是現在進行，第二個才是過去。", "walks 不配主詞 I，且仍不是過去式。", "walked 與 played 都是過去式，時間一致。"],
    reviews: ["原句的問題是 walk 沒有配合 yesterday，played 已正確。", "第四項只做必要修正，把 walk 改成 walked，並保留 played 與原意。"],
    cognitiveProcess: ["repair-mixed-tense-yesterday-report", "preserve-played-while-changing-walk"],
    representationType: "specific-tense-repair",
    misconceptionTargets: ["change-already-correct-past-verb"],
  }),
  question({
    id: "ENG_R4_Q_065_01",
    skillId: "ENG_R4_S065",
    difficulty: "foundation",
    stem: "The children ___ outside after lunch yesterday.",
    options: ["played", "plaied", "playd", "playing"],
    answerIndex: 0,
    reasons: ["played 保留 y 並加 -ed，拼字正確。", "plaied 誤把母音後的 y 改成 i。", "playd 少了 e。", "playing 是 V-ing，不是過去式。"],
    reviews: ["play 的 y 前是母音 a，所以直接加 -ed 成為 played。", "只有第一項同時符合 yesterday 的過去時間與 play 的拼字規則。"],
    cognitiveProcess: ["apply-vowel-y-played-spelling", "reject-plaied-and-playd"],
    misconceptionTargets: ["change-every-final-y-to-i"],
  }),
  question({
    id: "ENG_R4_Q_065_02",
    skillId: "ENG_R4_S065",
    difficulty: "foundation",
    stem: "Last year, we ___ near the station.",
    options: ["live", "lived", "liveed", "living"],
    answerIndex: 1,
    reasons: ["live 是原形，未標示 last year。", "lived 在字尾 e 後加 d，正確。", "liveed 多加了一個 e。", "living 需搭配 be 才能形成進行式。"],
    reviews: ["live 已以 e 結尾，過去式只需加 d。", "第二項拼字與 last year 相符；第三項正是常見的重複 e 錯誤。"],
    cognitiveProcess: ["form-lived-from-final-e", "exclude-liveed-overaddition"],
    misconceptionTargets: ["append-full-ed-after-final-e"],
  }),
  question({
    id: "ENG_R4_Q_065_03",
    skillId: "ENG_R4_S065",
    difficulty: "foundation",
    stem: "Grace ___ English at home last night.",
    options: ["studyed", "studyd", "studied", "studying"],
    answerIndex: 2,
    reasons: ["studyed 沒有把子音後的 y 改成 i。", "studyd 少了形成過去式所需的 ie。", "studied 是 study 的正確過去式。", "studying 是現在分詞，不能單獨表過去。"],
    reviews: ["study 的 y 前是子音 d，因此改 y 為 i 再加 -ed。", "第三項完整形成 studied；其餘三項都缺少正確的過去式拼字。"],
    cognitiveProcess: ["convert-consonant-y-study-to-studied", "distinguish-ied-from-yed"],
    misconceptionTargets: ["keep-y-after-consonant"],
  }),
  question({
    id: "ENG_R4_Q_065_04",
    skillId: "ENG_R4_S065",
    difficulty: "standard",
    stem: "The bus ___ at the corner and let us off.",
    options: ["stoped", "stopied", "stopt", "stopped"],
    answerIndex: 3,
    reasons: ["stoped 只寫一個 p，不是 stop 的正確過去式。", "stopied 誤套用 y 的規則。", "stopt 不是本課使用的標準拼法。", "stopped 重複 p 再加 -ed，正確。"],
    reviews: ["stop 的短母音字尾需要重複最後的 p，再接 -ed。", "第四項得到 stopped，且能與 let us off 組成同一段過去敘事。"],
    cognitiveProcess: ["double-final-p-in-stopped", "match-stopped-with-let-off-event"],
    misconceptionTargets: ["omit-doubled-consonant"],
  }),
  question({
    id: "ENG_R4_Q_065_05",
    skillId: "ENG_R4_S065",
    difficulty: "standard",
    stem: "Which past form keeps the y at the end?",
    options: ["played", "carried", "studied", "tried"],
    answerIndex: 0,
    reasons: ["played 的 y 前是母音 a，所以保留 y。", "carried 的 y 前是子音 r，已改成 i。", "studied 的 y 前是子音 d，已改成 i。", "tried 的 y 前是子音 r，已改成 i。"],
    reviews: ["題目要求找保留 y 的過去式，played 清楚保留 play 的 y。", "另外三項都屬子音加 y，形成過去式時已把 y 改為 i。"],
    cognitiveProcess: ["compare-y-spelling-across-four-verbs", "identify-vowel-before-y-case"],
    representationType: "spelling-property-comparison",
    misconceptionTargets: ["classify-all-y-verbs-together"],
  }),
  question({
    id: "ENG_R4_Q_065_06",
    skillId: "ENG_R4_S065",
    difficulty: "standard",
    stem: "Nora ___ the box into the room yesterday.",
    options: ["carryed", "carried", "carrid", "carries"],
    answerIndex: 1,
    reasons: ["carryed 沒有改掉子音後的 y。", "carried 正確把 y 改為 ied。", "carrid 少了 e。", "carries 是現在簡單式第三人稱形式。"],
    reviews: ["carry 以子音 r 加 y 結尾，過去式是 carried。", "第二項也符合 yesterday；其他選項不是正確過去拼字或時態。"],
    cognitiveProcess: ["spell-carried-in-moving-box-context", "separate-carried-from-carries"],
    misconceptionTargets: ["confuse-past-ied-with-present-ies"],
  }),
  question({
    id: "ENG_R4_Q_065_07",
    skillId: "ENG_R4_S065",
    difficulty: "standard",
    stem: "The club ___ a clean-up day last month.",
    options: ["planed", "plans", "planned", "planning"],
    answerIndex: 2,
    reasons: ["planed 少了一個 n，且可能被讀成另一個字。", "plans 是現在簡單式。", "planned 重複 n 再加 -ed，拼字正確。", "planning 是 V-ing，不能單獨作過去謂語。"],
    reviews: ["plan 的字尾符合重複最後子音的條件，所以形成 planned。", "last month 要求過去式，只有第三項在時態與拼字上都成立。"],
    cognitiveProcess: ["double-final-n-in-planned", "apply-spelling-to-club-plan-event"],
    misconceptionTargets: ["write-planed-for-planned"],
  }),
  question({
    id: "ENG_R4_Q_065_08",
    skillId: "ENG_R4_S065",
    difficulty: "advanced",
    stem: "Our class ___ the science room twice last week.",
    options: ["visitted", "visits", "visiting", "visited"],
    answerIndex: 3,
    reasons: ["visitted 不必要地重複 t。", "visits 是現在習慣。", "visiting 需搭配 be，且不是過去式。", "visited 直接加 -ed，拼字正確。"],
    reviews: ["visit 不屬於 stop、plan 那類需要重複最後子音的短動詞。", "last week 要求過去式 visited；第一項正是過度套用重複規則的錯誤。"],
    cognitiveProcess: ["avoid-overdoubling-t-in-visited", "select-visited-for-last-week"],
    misconceptionTargets: ["double-final-consonant-in-every-verb"],
  }),
  question({
    id: "ENG_R4_Q_065_09",
    skillId: "ENG_R4_S065",
    difficulty: "advanced",
    stem: "Why is played spelled with y, but carried is spelled with i?",
    options: ["The letter before y is a in play, but r in carry.", "Play is always present, while carry is always past.", "Longer words must change y to i.", "A word about games cannot change its last letter."],
    answerIndex: 0,
    reasons: ["這一項正確比較 a+y 與 r+y 的字尾。", "兩個動詞都能表現在或過去，意思不決定拼字。", "字長不是 y 是否改成 i 的條件。", "是否談遊戲和字尾規則無關。"],
    reviews: ["played 的 y 前是母音 a，carried 的 y 前是子音 r，差異來自字尾結構。", "第一項提供可檢查的拼字條件；其餘項目把時態、字長或意思誤當規則。"],
    cognitiveProcess: ["explain-played-carried-spelling-contrast", "reject-meaning-based-y-rule"],
    representationType: "specific-spelling-explanation",
    misconceptionTargets: ["infer-spelling-from-word-meaning"],
  }),
  question({
    id: "ENG_R4_Q_065_10",
    skillId: "ENG_R4_S065",
    difficulty: "advanced",
    stem: "The rain ___, so the workers opened the windows again.",
    options: ["stoped", "stopped", "stoppied", "stopping"],
    answerIndex: 1,
    reasons: ["stoped 少重複一個 p。", "stopped 是 stop 的正確過去式。", "stoppied 誤用了 -ied。", "stopping 需搭配 was 才能作進行式。"],
    reviews: ["opened 是過去結果，前面的雨停也需是已完成事件 stopped。", "第二項不只拼字正確，也能建立雨停後重新開窗的合理因果。"],
    cognitiveProcess: ["integrate-stopped-spelling-with-past-result", "reject-stoppied-in-weather-context"],
    misconceptionTargets: ["mix-doubling-and-ied-rules"],
  }),
  question({
    id: "ENG_R4_Q_065_11",
    skillId: "ENG_R4_S065",
    difficulty: "transfer",
    stem: "Maya ___ the books downstairs and ___ for the bus.",
    options: ["carryed / waitted", "carried / waitted", "carried / waited", "carryed / waited"],
    answerIndex: 2,
    reasons: ["carryed 未改 y，waitted 又多重複 t。", "carried 正確，但 waitted 不正確。", "carried 與 waited 分別套用正確規則。", "carryed 不正確，只有 waited 正確。"],
    reviews: ["carry 要改 y 為 ied；wait 直接加 -ed，不重複 t。", "第三組同時通過兩個不同拼字條件，其他組至少含一個可定位的錯誤。"],
    cognitiveProcess: ["coordinate-carried-and-waited-spellings", "validate-two-regular-past-forms"],
    representationType: "dual-spelling-selection",
    misconceptionTargets: ["apply-one-ending-rule-to-both-verbs"],
  }),
  question({
    id: "ENG_R4_Q_065_12",
    skillId: "ENG_R4_S065",
    difficulty: "transfer",
    stem: "The club ___ a trip and ___ a map for every student.",
    options: ["planed / printted", "planned / printted", "planed / printed", "planned / printed"],
    answerIndex: 3,
    reasons: ["planed 少一個 n，printted 又多一個 t。", "planned 正確，但 printted 不需重複 t。", "printed 正確，但 planed 少一個 n。", "planned 與 printed 都是正確過去式。"],
    reviews: ["plan 需要重複 n，print 則直接加 -ed，兩個動詞不能套同一細節。", "第四組分別得到 planned 與 printed，並完整表達兩件已完成的準備工作。"],
    cognitiveProcess: ["contrast-planned-with-printed-endings", "complete-two-action-club-report"],
    representationType: "contrasting-regular-endings",
    misconceptionTargets: ["double-final-letter-in-print"],
  }),
  question({
    id: "ENG_R4_Q_066_01",
    skillId: "ENG_R4_S066",
    difficulty: "foundation",
    stem: "Ken ___ home after practice yesterday.",
    options: ["went", "goed", "goes", "going"],
    answerIndex: 0,
    reasons: ["went 是 go 的不規則過去式。", "goed 不是標準英文形式。", "goes 是現在簡單式第三人稱。", "going 不能單獨作過去謂語。"],
    reviews: ["yesterday 把回家事件放在過去，go 必須變成 went。", "第一項是唯一正確的不規則形式；其餘項目或不存在，或不是過去式。"],
    cognitiveProcess: ["retrieve-went-for-yesterday-homecoming", "reject-regularized-goed"],
    misconceptionTargets: ["add-ed-to-go"],
  }),
  question({
    id: "ENG_R4_Q_066_02",
    skillId: "ENG_R4_S066",
    difficulty: "foundation",
    stem: "We ___ a bright light in the sky last night.",
    options: ["see", "saw", "seed", "seeing"],
    answerIndex: 1,
    reasons: ["see 是原形，未標示昨晚。", "saw 是 see 的過去式。", "seed 是另一個字，不是 see 的過去式。", "seeing 需搭配 be 才能作進行式。"],
    reviews: ["last night 表示觀看發生在已結束的時間，因此使用 saw。", "第二項保留 see 的意思並正確改成過去；其他選項不符合形式或詞義。"],
    cognitiveProcess: ["map-see-to-saw-in-night-observation", "separate-saw-from-seed"],
    misconceptionTargets: ["invent-seed-as-past-see"],
  }),
  question({
    id: "ENG_R4_Q_066_03",
    skillId: "ENG_R4_S066",
    difficulty: "foundation",
    stem: "Lily ___ the wrong bus, so she got off at the next stop.",
    options: ["take", "taked", "took", "takes"],
    answerIndex: 2,
    reasons: ["take 是原形，不能和 got off 組成完整過去敘事。", "taked 不是 take 的標準過去式。", "took 是 take 的不規則過去式。", "takes 是現在簡單式第三人稱。"],
    reviews: ["got off 是過去結果，搭錯公車也必須是先前已完成的 took。", "第三項形成 took the wrong bus；其他形式無法正確標示這段過去事件。"],
    cognitiveProcess: ["infer-took-from-got-off-result", "reject-taked-in-transport-context"],
    misconceptionTargets: ["regularize-take"],
  }),
  question({
    id: "ENG_R4_Q_066_04",
    skillId: "ENG_R4_S066",
    difficulty: "standard",
    stem: "My father ___ fresh fruit at the market yesterday morning.",
    options: ["buyed", "brings", "buying", "bought"],
    answerIndex: 3,
    reasons: ["buyed 不是 buy 的過去式。", "brings 表示帶來且是現在式，意思不同。", "buying 不能單獨構成過去句。", "bought 是 buy 的過去式，符合市場情境。"],
    reviews: ["在市場取得水果需要 buy 的意思，完成事件用 bought。", "第四項同時符合詞義與時態；第一項是假規則形式，第二、三項改變意思或結構。"],
    cognitiveProcess: ["choose-bought-for-market-purchase", "separate-buy-from-bring-meaning"],
    misconceptionTargets: ["confuse-bought-and-brought"],
  }),
  question({
    id: "ENG_R4_Q_066_05",
    skillId: "ENG_R4_S066",
    difficulty: "standard",
    stem: "The guests ___ early and sat near the window.",
    options: ["came", "comed", "come", "coming"],
    answerIndex: 0,
    reasons: ["came 是 come 的過去式，能和 sat 並列。", "comed 不是標準過去式。", "come 是原形，與 sat 時態不一致。", "coming 缺少 be，不能作完整謂語。"],
    reviews: ["sat 已建立過去敘事，客人先到達也應使用 came。", "第一項讓 came and sat 成為兩個完成事件，其他項目都不是合適的過去形式。"],
    cognitiveProcess: ["align-came-with-sat-in-guest-story", "exclude-comed-formation"],
    misconceptionTargets: ["add-ed-to-come"],
  }),
  question({
    id: "ENG_R4_Q_066_06",
    skillId: "ENG_R4_S066",
    difficulty: "standard",
    stem: "I ___ rice and soup for lunch yesterday.",
    options: ["eated", "ate", "eat", "eats"],
    answerIndex: 1,
    reasons: ["eated 不是 eat 的標準過去式。", "ate 是 eat 的不規則過去式。", "eat 是原形，未表達 yesterday。", "eats 不配主詞 I，且為現在式。"],
    reviews: ["yesterday 的午餐已吃完，eat 應變為 ate。", "第二項在主詞、時間與拼字上都正確；其他項目不是合法過去式。"],
    cognitiveProcess: ["retrieve-ate-for-yesterday-lunch", "distinguish-ate-from-eated"],
    misconceptionTargets: ["regularize-eat"],
  }),
  question({
    id: "ENG_R4_Q_066_07",
    skillId: "ENG_R4_S066",
    difficulty: "standard",
    stem: "The teacher ___ us two minutes to finish.",
    options: ["give", "gived", "gave", "given"],
    answerIndex: 2,
    reasons: ["give 是原形，未標示過去。", "gived 不是標準形式。", "gave 是 give 的過去式。", "given 需要搭配 have 或 be，不能在此單獨作謂語。"],
    reviews: ["老師給時間是已完成的動作，give 的過去式為 gave。", "第三項可直接形成 gave us two minutes；其餘項目不是正確的單純過去形式。"],
    cognitiveProcess: ["select-gave-in-time-allocation", "separate-gave-from-given"],
    misconceptionTargets: ["use-past-participle-alone"],
  }),
  question({
    id: "ENG_R4_Q_066_08",
    skillId: "ENG_R4_S066",
    difficulty: "advanced",
    stem: "Nora ___ a short note and put it in her bag.",
    options: ["writed", "written", "writes", "wrote"],
    answerIndex: 3,
    reasons: ["writed 不是 write 的過去式。", "written 不能在此單獨作主要動詞。", "writes 是現在簡單式。", "wrote 是 write 的過去式，與 put 並列。"],
    reviews: ["put 在此是過去式，前面的寫字動作也應用 wrote。", "第四項形成 wrote a note and put it...；其他形式不是合適的肯定過去謂語。"],
    cognitiveProcess: ["coordinate-wrote-with-past-put", "distinguish-wrote-from-written"],
    misconceptionTargets: ["replace-past-with-participle"],
  }),
  question({
    id: "ENG_R4_Q_066_09",
    skillId: "ENG_R4_S066",
    difficulty: "advanced",
    stem: "A strong wind ___ the door close, but it did not break the glass.",
    options: ["made", "maked", "makes", "making"],
    answerIndex: 0,
    reasons: ["made 是 make 的過去式，表示風吹得門關上。", "maked 不是標準形式。", "makes 是現在式，與 did not 不合。", "making 缺少 be，不能作主要動詞。"],
    reviews: ["did not break 將情境放在過去，風吹門關也應使用 made。", "第一項保持因果與過去時間；其他項目為錯誤變化或不同時態。"],
    cognitiveProcess: ["infer-made-from-past-wind-result", "align-made-with-did-not-break"],
    misconceptionTargets: ["form-maked-by-ed"],
  }),
  question({
    id: "ENG_R4_Q_066_10",
    skillId: "ENG_R4_S066",
    difficulty: "advanced",
    stem: "We ___ enough water for the long walk, so nobody was thirsty.",
    options: ["have", "had", "haved", "having"],
    answerIndex: 1,
    reasons: ["have 是現在原形，與 was 不在同一過去背景。", "had 是 have 的過去式。", "haved 不是標準形式。", "having 不能單獨作過去謂語。"],
    reviews: ["was thirsty 建立過去情境，當時擁有足夠水要用 had。", "第二項也能合理說明沒有人口渴的原因；其他項目不是正確過去形式。"],
    cognitiveProcess: ["connect-had-water-to-past-outcome", "reject-haved-in-possession-context"],
    misconceptionTargets: ["regularize-have"],
  }),
  question({
    id: "ENG_R4_Q_066_11",
    skillId: "ENG_R4_S066",
    difficulty: "transfer",
    stem: "Ben looked under every chair and finally ___ his wallet.",
    options: ["find", "finded", "found", "finding"],
    answerIndex: 2,
    reasons: ["find 是原形，與 looked 時態不一致。", "finded 不是標準形式。", "found 是 find 的過去式，符合尋找結果。", "finding 不能單獨接在主詞後作過去謂語。"],
    reviews: ["looked 和 finally 都建立已完成的尋找過程，結果應使用 found。", "第三項在語意上是尋找的結果，在形式上也是正確不規則過去式。"],
    cognitiveProcess: ["resolve-search-story-with-found", "match-finally-to-irregular-result"],
    misconceptionTargets: ["write-finded-after-looked"],
  }),
  question({
    id: "ENG_R4_Q_066_12",
    skillId: "ENG_R4_S066",
    difficulty: "transfer",
    stem: "A message says, “I read your note and came right away.” Which base forms match the two past words?",
    options: ["read / came", "readed / come", "write / go", "read / come"],
    answerIndex: 3,
    reasons: ["came 本身是過去式，不是所問的原形。", "readed 不存在，雖然 come 是原形。", "write 和 go 改變了原句兩個動作的意思。", "read 的原形同形，came 的原形是 come。"],
    reviews: ["第一個 read 的原形仍拼作 read，第二個 came 對應 come。", "第四組完整還原兩個動詞且不改意思；其他組保留過去式、使用假形式或換詞。"],
    cognitiveProcess: ["reverse-map-read-and-came-to-base", "handle-unchanged-read-spelling"],
    representationType: "irregular-base-form-pair",
    misconceptionTargets: ["assume-every-past-form-changes-spelling"],
  }),
  question({
    id: "ENG_R4_Q_067_01",
    skillId: "ENG_R4_S067",
    difficulty: "foundation",
    stem: "___ you call your aunt last night?",
    options: ["Did", "Do", "Were", "Are"],
    answerIndex: 0,
    reasons: ["Did 可形成一般動詞的過去問句。", "Do 是現在問句。", "Were 不能直接接原形 call。", "Are 也不能和 call 組成此問句。"],
    reviews: ["last night 與一般動詞 call 要求 Did + subject + base verb。", "第一項能形成 Did you call...?；其餘助動詞或 be 動詞不符合結構與時間。"],
    cognitiveProcess: ["form-did-question-about-phone-call", "separate-did-from-present-do"],
    misconceptionTargets: ["use-do-with-last-night"],
  }),
  question({
    id: "ENG_R4_Q_067_02",
    skillId: "ENG_R4_S067",
    difficulty: "foundation",
    stem: "Sara did not ___ her lunch.",
    options: ["brought", "bring", "brings", "bringing"],
    answerIndex: 1,
    reasons: ["brought 與 did 形成雙重過去。", "bring 是 did not 後需要的原形。", "brings 是現在第三人稱形式。", "bringing 不能直接接在 did not 後。"],
    reviews: ["did not 已標出過去否定，主要動詞需回到 bring。", "第二項是唯一原形；其餘形式分別是過去式、現在變化或 V-ing。"],
    cognitiveProcess: ["restore-bring-after-did-not", "avoid-double-past-brought"],
    misconceptionTargets: ["keep-irregular-past-after-did"],
  }),
  question({
    id: "ENG_R4_Q_067_03",
    skillId: "ENG_R4_S067",
    difficulty: "foundation",
    stem: "Where did Ben ___ the key?",
    options: ["puts", "putting", "put", "putted"],
    answerIndex: 2,
    reasons: ["puts 是現在第三人稱形式。", "putting 不能直接接在 did 後。", "put 是 did 後的原形。", "putted 不是 put 的標準過去式。"],
    reviews: ["Where 保留所問地點，did 後使用原形 put。", "第三項可形成完整特殊問句；其他選項都不是 did 後的原形。"],
    cognitiveProcess: ["complete-where-did-put-question", "recognize-put-base-after-did"],
    misconceptionTargets: ["invent-putted"],
  }),
  question({
    id: "ENG_R4_Q_067_04",
    skillId: "ENG_R4_S067",
    difficulty: "standard",
    stem: "___ the team win the game yesterday?",
    options: ["Does", "Was", "Is", "Did"],
    answerIndex: 3,
    reasons: ["Does 是現在式，與 yesterday 不符。", "Was 後不能直接接 win。", "Is 也是現在 be 動詞。", "Did 配合 yesterday，後接原形 win。"],
    reviews: ["win 是一般動詞，且比賽在昨天，因此問句以 Did 開頭。", "第四項形成 Did the team win...?；其他選項不是正確的過去一般問句。"],
    cognitiveProcess: ["select-did-for-team-win-question", "reject-be-before-base-win"],
    misconceptionTargets: ["use-was-as-universal-past-helper"],
  }),
  question({
    id: "ENG_R4_Q_067_05",
    skillId: "ENG_R4_S067",
    difficulty: "standard",
    stem: "We did not ___ the meeting time.",
    options: ["forget", "forgot", "forgets", "forgotten"],
    answerIndex: 0,
    reasons: ["forget 是 did not 後的原形。", "forgot 會和 did 形成雙重過去。", "forgets 是現在第三人稱形式。", "forgotten 不能直接接在 did not 後。"],
    reviews: ["did not 已承擔否定與過去，後面只需原形 forget。", "第一項保留原意與正確結構；其他項目都不是助動詞後的原形。"],
    cognitiveProcess: ["use-forget-after-negative-did", "differentiate-forget-forgot-forgotten"],
    misconceptionTargets: ["choose-forgot-because-time-is-past"],
  }),
  question({
    id: "ENG_R4_Q_067_06",
    skillId: "ENG_R4_S067",
    difficulty: "standard",
    stem: "Why did Amy ___ early?",
    options: ["left", "leave", "leaves", "leaving"],
    answerIndex: 1,
    reasons: ["left 是過去式，不能留在 did 後。", "leave 是原形，結構正確。", "leaves 是現在第三人稱形式。", "leaving 不能直接接 did。"],
    reviews: ["Why 指定詢問原因，did 建立過去，主要動詞使用 leave。", "第二項完成 Why did Amy leave...?；其他三項都不是 did 後的原形。"],
    cognitiveProcess: ["build-why-did-leave-question", "remove-left-after-did"],
    misconceptionTargets: ["retain-left-in-past-question"],
  }),
  question({
    id: "ENG_R4_Q_067_07",
    skillId: "ENG_R4_S067",
    difficulty: "standard",
    stem: "Choose the question with the words in the right order.",
    options: ["When the movie did start?", "Did when the movie start?", "When did the movie start?", "When did start the movie?"],
    answerIndex: 2,
    reasons: ["did 應放在主詞 the movie 前。", "疑問詞 When 應位在句首。", "When + did + subject + start 的順序正確。", "did 後應先出現主詞，再接原形動詞。"],
    reviews: ["特殊問句的順序是 When did the movie start?。", "第三項保留疑問詞、助動詞、主詞與原形動詞的正確位置，其他項目各有明確錯位。"],
    cognitiveProcess: ["order-when-did-movie-start", "locate-subject-between-did-and-verb"],
    representationType: "specific-word-order-task",
    misconceptionTargets: ["place-question-word-after-did"],
  }),
  question({
    id: "ENG_R4_Q_067_08",
    skillId: "ENG_R4_S067",
    difficulty: "advanced",
    stem: "Change “Leo visited the museum” to a negative sentence without changing the time.",
    options: ["Leo not visited the museum.", "Leo does not visit the museum.", "Leo did not visited the museum.", "Leo did not visit the museum."],
    answerIndex: 3,
    reasons: ["英文否定句不能只在過去式前加 not。", "does not 把句子改成現在時間。", "did not 後不應保留 visited。", "did not + visit 正確表達過去否定。"],
    reviews: ["原句是過去式 visited，改否定時使用 did not 並還原 visit。", "第四項保持相同人物、地點與過去時間，只改變肯定為否定。"],
    cognitiveProcess: ["negate-visited-without-changing-time", "convert-visited-to-did-not-visit"],
    representationType: "specific-negative-transformation",
    misconceptionTargets: ["put-not-before-past-verb"],
  }),
  question({
    id: "ENG_R4_Q_067_09",
    skillId: "ENG_R4_S067",
    difficulty: "advanced",
    stem: "“Did your sister enjoy the trip?” Which short answer says yes?",
    options: ["Yes, she did.", "Yes, she does.", "Yes, she enjoyed.", "Yes, she was."],
    answerIndex: 0,
    reasons: ["did 與問句時態一致，短答完整。", "does 是現在式。", "短答不以 enjoyed 單獨代替助動詞。", "was 不是原問句使用的動詞。"],
    reviews: ["問句以 Did 開頭，肯定簡答重複 did 而不重複主要動詞。", "第一項符合主詞 she 與過去時態；其他助動詞或結構都不對應原問句。"],
    cognitiveProcess: ["answer-did-question-affirmatively", "maintain-past-auxiliary-in-short-answer"],
    representationType: "past-short-answer-selection",
    misconceptionTargets: ["answer-past-question-with-does"],
  }),
  question({
    id: "ENG_R4_Q_067_10",
    skillId: "ENG_R4_S067",
    difficulty: "advanced",
    stem: "Mina bought a book. Which question asks about the thing she bought?",
    options: ["Where did Mina buy?", "What did Mina buy?", "What Mina bought?", "Did Mina bought what?"],
    answerIndex: 1,
    reasons: ["Where 詢問地點，不是所買的物品。", "What 詢問事物，且字序與動詞形式正確。", "缺少 did，字序也不是完整問句。", "did 後保留 bought，且疑問詞位置錯誤。"],
    reviews: ["題目要問受詞 a book，因此用 What did Mina buy?。", "第二項精確指定事物並把 bought 還原成 buy；其他項目問錯資訊或結構錯誤。"],
    cognitiveProcess: ["form-object-question-from-bought-book", "choose-what-over-where"],
    representationType: "information-gap-question",
    misconceptionTargets: ["omit-did-in-object-question"],
  }),
  question({
    id: "ENG_R4_Q_067_11",
    skillId: "ENG_R4_S067",
    difficulty: "transfer",
    stem: "“Did Nora went home?” has one word error. Which sentence keeps the meaning?",
    options: ["Does Nora went home?", "Did Nora goes home?", "Did Nora go home?", "Was Nora go home?"],
    answerIndex: 2,
    reasons: ["Does 改成現在式，且後面仍錯用 went。", "did 後不能用 goes。", "did 後使用原形 go，意義與時間不變。", "was 不能直接接原形 go。"],
    reviews: ["錯誤只在 did 後使用 went，必要修正是把它還原成 go。", "第三項保留 Nora、home 與過去問句，其餘項目另引入時態或結構錯誤。"],
    cognitiveProcess: ["repair-did-nora-went-error", "preserve-question-meaning-with-go"],
    representationType: "single-error-correction",
    misconceptionTargets: ["double-mark-past-in-question"],
  }),
  question({
    id: "ENG_R4_Q_067_12",
    skillId: "ENG_R4_S067",
    difficulty: "transfer",
    stem: "A: Why didn't Sam come to the meeting? B: He did not ___ the new time.",
    options: ["knew", "knows", "knowing", "know"],
    answerIndex: 3,
    reasons: ["knew 與 did not 形成雙重過去。", "knows 是現在第三人稱形式。", "knowing 不能直接接 did not。", "know 是 did not 後的原形。"],
    reviews: ["B 說明 Sam 沒來的原因，did not 後應接 know。", "第四項使回答成為完整過去否定句，也和問句中的 didn't come 保持同一時間。"],
    cognitiveProcess: ["complete-reason-dialogue-with-know", "coordinate-two-did-negatives"],
    representationType: "past-negative-dialogue",
    misconceptionTargets: ["use-knew-after-did-not"],
  }),
  question({
    id: "ENG_R4_Q_068_01",
    skillId: "ENG_R4_S068",
    difficulty: "foundation",
    stem: "I ___ tired after the race.",
    options: ["was", "were", "did", "am"],
    answerIndex: 0,
    reasons: ["I 在過去式搭配 was。", "were 不用於一般 I 的過去陳述。", "did 不能直接接形容詞 tired。", "am 是現在式。"],
    reviews: ["after the race 建立過去狀態，I 的過去 be 動詞是 was。", "第一項形成 I was tired；其餘項目或主詞不合、結構不合或時間不同。"],
    cognitiveProcess: ["match-i-with-was-after-race", "reject-did-before-adjective"],
    misconceptionTargets: ["use-were-with-i-by-number"],
  }),
  question({
    id: "ENG_R4_Q_068_02",
    skillId: "ENG_R4_S068",
    difficulty: "foundation",
    stem: "The keys ___ on the desk yesterday morning.",
    options: ["was", "were", "is", "did"],
    answerIndex: 1,
    reasons: ["was 不配複數 keys。", "were 配合複數主詞與過去時間。", "is 把位置改成現在，且不配複數 keys。", "did 後缺少一般動詞，不能直接連 on the desk。"],
    reviews: ["The keys 是複數，且 this morning 在此回顧已發生狀態，所以用 were。", "第二項同時符合主詞數量與時間；其他形式至少違反其中一項。"],
    cognitiveProcess: ["match-plural-keys-with-were", "identify-past-location-state"],
    misconceptionTargets: ["choose-was-for-nearby-singular-desk"],
  }),
  question({
    id: "ENG_R4_Q_068_03",
    skillId: "ENG_R4_S068",
    difficulty: "foundation",
    stem: "My brother ___ at home last night.",
    options: ["were", "is", "was", "did"],
    answerIndex: 2,
    reasons: ["were 不配單數 brother。", "is 是現在式，與 last night 不符。", "was 配合單數主詞與過去時間。", "did 不能直接接 at home。"],
    reviews: ["My brother 是單數，last night 要求過去 be 動詞 was。", "第三項形成完整地點狀態句；其他選項在主詞、時間或結構上不成立。"],
    cognitiveProcess: ["select-was-for-single-brother", "combine-last-night-with-be-state"],
    misconceptionTargets: ["use-did-for-every-past-sentence"],
  }),
  question({
    id: "ENG_R4_Q_068_04",
    skillId: "ENG_R4_S068",
    difficulty: "standard",
    stem: "You ___ right about the meeting time.",
    options: ["was", "did", "are", "were"],
    answerIndex: 3,
    reasons: ["was 不與 you 搭配。", "did 不能直接接形容詞 right。", "are 是現在式。", "were 是 you 的過去 be 動詞。"],
    reviews: ["you 無論指一人或多人，過去陳述都搭配 were。", "第四項形成 You were right；其餘項目為錯誤搭配、錯誤結構或現在時間。"],
    cognitiveProcess: ["apply-you-were-fixed-pair", "reject-was-for-singular-you"],
    misconceptionTargets: ["use-was-when-you-means-one-person"],
  }),
  question({
    id: "ENG_R4_Q_068_05",
    skillId: "ENG_R4_S068",
    difficulty: "standard",
    stem: "There ___ one message on my phone.",
    options: ["was", "were", "did", "are"],
    answerIndex: 0,
    reasons: ["one message 是單數，there was 正確。", "were 要配複數存在項目。", "did 不能形成存在句。", "are 是現在複數形式。"],
    reviews: ["there 後真正決定形式的是 one message，因此使用 was。", "第一項形成過去單數存在句；其他選項不合數量、時間或句型。"],
    cognitiveProcess: ["derive-there-was-from-one-message", "ignore-neutral-there-for-number"],
    representationType: "past-existence-cloze",
    misconceptionTargets: ["treat-there-as-plural-subject"],
  }),
  question({
    id: "ENG_R4_Q_068_06",
    skillId: "ENG_R4_S068",
    difficulty: "standard",
    stem: "There ___ many people outside the station last night.",
    options: ["was", "were", "is", "did"],
    answerIndex: 1,
    reasons: ["was 不配 many people。", "were 配合複數 people。", "is 不配 many people，也不是 last night 的過去式。", "did 不能直接接名詞片語。"],
    reviews: ["many people 是複數存在項目，因此過去式使用 there were。", "第二項唯一符合複數與 be 句型；其他選項或數量不合或結構錯誤。"],
    cognitiveProcess: ["derive-there-were-from-many-people", "contrast-one-and-many-existence"],
    representationType: "plural-existence-cloze",
    misconceptionTargets: ["use-there-was-for-all-existence"],
  }),
  question({
    id: "ENG_R4_Q_068_07",
    skillId: "ENG_R4_S068",
    difficulty: "standard",
    stem: "___ the windows open when you left?",
    options: ["Was", "Did", "Were", "Are"],
    answerIndex: 2,
    reasons: ["was 不配複數 windows。", "did 不能直接接 open 這個形容狀態。", "Were 配合複數主詞並形成過去問句。", "Are 是現在問句。"],
    reviews: ["windows 是複數，且 when you left 建立過去時間，問句用 Were。", "第三項可直接把 were 移到主詞前；不需要再加入 did。"],
    cognitiveProcess: ["invert-were-before-plural-windows", "form-past-state-question-without-did"],
    representationType: "past-be-question-cloze",
    misconceptionTargets: ["insert-did-before-open-adjective"],
  }),
  question({
    id: "ENG_R4_Q_068_08",
    skillId: "ENG_R4_S068",
    difficulty: "advanced",
    stem: "When we checked, the book and the map ___ not in the bag.",
    options: ["was", "did", "is", "were"],
    answerIndex: 3,
    reasons: ["was 不配 and 連接的複數主詞。", "did not 後需要一般動詞，不能直接接地點片語。", "is 既不配 book and map，也與 checked 的過去背景不合。", "were not 正確表達複數過去否定。"],
    reviews: ["The book and the map 合計兩件物品，整體為複數。", "第四項形成 were not in the bag；其他形式在數量、時間或否定結構上錯誤。"],
    cognitiveProcess: ["combine-two-nouns-into-were-subject", "form-past-location-negative"],
    misconceptionTargets: ["agree-with-nearest-singular-map"],
  }),
  question({
    id: "ENG_R4_Q_068_09",
    skillId: "ENG_R4_S068",
    difficulty: "advanced",
    stem: "The meeting was in Room 3. Which question asks for its place?",
    options: ["Where was the meeting?", "Where did the meeting?", "Was where the meeting?", "Where the meeting was?"],
    answerIndex: 0,
    reasons: ["Where + was + subject 的問句結構正確。", "did 後缺少一般動詞。", "疑問詞 Where 應放句首。", "這是陳述式字序，不是直接問句。"],
    reviews: ["原句的主要動詞是 was，問地點時形成 Where was the meeting?。", "第一項不加入 did，並把 was 放在主詞 meeting 前，完整詢問 Room 3。"],
    cognitiveProcess: ["form-where-was-meeting-question", "retain-be-in-location-question"],
    representationType: "past-be-information-question",
    misconceptionTargets: ["use-did-with-was-sentence"],
  }),
  question({
    id: "ENG_R4_Q_068_10",
    skillId: "ENG_R4_S068",
    difficulty: "advanced",
    stem: "Amy and I ___ ready before the doors opened.",
    options: ["was", "were", "am", "did"],
    answerIndex: 1,
    reasons: ["was 不配 Amy and I 的複數主詞。", "were 配合兩人與過去狀態。", "am 只配現在式的 I。", "did 不能直接接形容詞 ready。"],
    reviews: ["and 連接 Amy 與 I，主詞包含兩人，因此使用 were。", "before the doors opened 也建立過去背景，第二項同時符合數量和時間。"],
    cognitiveProcess: ["treat-amy-and-i-as-plural", "align-were-ready-with-opened"],
    misconceptionTargets: ["choose-was-because-i-alone-uses-was"],
  }),
  question({
    id: "ENG_R4_Q_068_11",
    skillId: "ENG_R4_S068",
    difficulty: "transfer",
    stem: "When we looked, the box of old photos ___ under the bed.",
    options: ["were", "are", "was", "did"],
    answerIndex: 2,
    reasons: ["were 誤把 photos 當成主詞核心。", "are 是現在式，也不配單數核心 box。", "was 配合單數核心 box。", "did 不能用來連接 box 與 under the bed。"],
    reviews: ["of old photos 只是修飾 box，真正主詞仍是單數。", "第三項依核心主詞選 was；若只看最近的 photos 才會誤選 were。"],
    cognitiveProcess: ["identify-box-as-head-of-subject", "resist-nearest-noun-agreement"],
    representationType: "complex-subject-agreement",
    misconceptionTargets: ["agree-with-noun-inside-of-phrase"],
  }),
  question({
    id: "ENG_R4_Q_068_12",
    skillId: "ENG_R4_S068",
    difficulty: "transfer",
    stem: "There ___ no buses after ten, so we walked home.",
    options: ["was", "is", "did", "were"],
    answerIndex: 3,
    reasons: ["was 不配複數 buses。", "is 不配 buses，也與 walked 的過去時間衝突。", "did 不能形成 there 存在句。", "were 配合複數 buses 與 walked 的過去背景。"],
    reviews: ["no buses 的中心名詞 buses 是複數，且 walked 表示整段在過去。", "第四項形成 There were no buses，合理說明大家走路回家的原因。"],
    cognitiveProcess: ["use-were-with-zero-plural-buses", "connect-past-absence-to-walked-result"],
    representationType: "negative-existence-cause",
    misconceptionTargets: ["treat-no-as-singular"],
  }),
  question({
    id: "ENG_R4_Q_069_01",
    skillId: "ENG_R4_S069",
    difficulty: "foundation",
    stem: "Yesterday, our class ___ a short movie.",
    options: ["watched", "watches", "is watching", "will watch"],
    answerIndex: 0,
    reasons: ["watched 配合 yesterday，表示已看完。", "watches 表現在習慣。", "is watching 表目前進行。", "will watch 表未來。"],
    reviews: ["Yesterday 是直接的過去時間線索，watch 應使用 watched。", "第一項符合完成事件；其餘三項分別落在現在習慣、現在進行和未來。"],
    cognitiveProcess: ["map-yesterday-to-watched-movie", "separate-three-nonpast-forms"],
    misconceptionTargets: ["ignore-yesterday-time-anchor"],
  }),
  question({
    id: "ENG_R4_Q_069_02",
    skillId: "ENG_R4_S069",
    difficulty: "foundation",
    stem: "I ___ this card two days ago.",
    options: ["find", "found", "finds", "am finding"],
    answerIndex: 1,
    reasons: ["find 是原形，沒有標示 ago 的過去。", "found 是 find 的過去式。", "finds 是現在第三人稱形式且不配 I。", "am finding 表目前正在發現。"],
    reviews: ["two days ago 從現在往前定位兩天，事件已完成。", "第二項 found 同時符合不規則變化與過去時間；其他選項不符合。"],
    cognitiveProcess: ["interpret-two-days-ago-anchor", "select-found-for-card-discovery"],
    misconceptionTargets: ["treat-ago-as-duration-in-progress"],
  }),
  question({
    id: "ENG_R4_Q_069_03",
    skillId: "ENG_R4_S069",
    difficulty: "foundation",
    stem: "My family ___ to Tainan last month.",
    options: ["moves", "is moving", "moved", "will move"],
    answerIndex: 2,
    reasons: ["moves 表現在習慣。", "is moving 表目前進行。", "moved 表上個月已完成搬遷。", "will move 表未來計畫。"],
    reviews: ["last month 是已結束的上一個月，因此使用 moved。", "第三項能表達單一完成事件；其他選項把搬遷放在現在或未來。"],
    cognitiveProcess: ["locate-family-move-in-last-month", "choose-completed-moved-form"],
    misconceptionTargets: ["read-last-month-as-current-plan"],
  }),
  question({
    id: "ENG_R4_Q_069_04",
    skillId: "ENG_R4_S069",
    difficulty: "standard",
    stem: "The school ___ its evening program in 2018.",
    options: ["begins", "is beginning", "will begin", "began"],
    answerIndex: 3,
    reasons: ["begins 是現在簡單式。", "is beginning 表目前正在開始。", "will begin 表未來。", "began 配合明確過去年份 2018。"],
    reviews: ["in 2018 把夜間課程開始的事件固定在過去，begin 要改為 began。", "第四項是唯一過去形式；句子沒有提供現在進行或未來的依據。"],
    cognitiveProcess: ["anchor-library-start-to-2018", "retrieve-began-for-dated-event"],
    misconceptionTargets: ["leave-begin-in-present-for-existing-library"],
  }),
  question({
    id: "ENG_R4_Q_069_05",
    skillId: "ENG_R4_S069",
    difficulty: "standard",
    stem: "Which time words point to a finished past time?",
    options: ["last Friday", "right now", "every weekend", "next year"],
    answerIndex: 0,
    reasons: ["last Friday 是已結束的上一個星期五。", "right now 指目前。", "every weekend 表重複習慣。", "next year 指未來。"],
    reviews: ["題目只問時間性質，last Friday 唯一明確指向完成的過去時段。", "其他選項分別屬現在、習慣與未來，不能支持單一過去事件。"],
    cognitiveProcess: ["classify-four-time-phrases", "identify-last-friday-as-past"],
    representationType: "time-phrase-classification",
    misconceptionTargets: ["equate-every-weekend-with-one-past-time"],
  }),
  question({
    id: "ENG_R4_Q_069_06",
    skillId: "ENG_R4_S069",
    difficulty: "standard",
    stem: "My aunt lived here ___.",
    options: ["right now", "five years ago", "every morning", "next week"],
    answerIndex: 1,
    reasons: ["right now 通常不配 lived。", "five years ago 與過去式 lived 相符。", "every morning 表習慣，通常使用 lives。", "next week 是未來時間。"],
    reviews: ["lived 已標示過去，five years ago 提供相符的完成時間。", "第二項是唯一不需更改動詞形式即可成立的時間片語。"],
    cognitiveProcess: ["match-lived-with-compatible-time-phrase", "reject-now-habit-future-markers"],
    representationType: "time-phrase-completion",
    misconceptionTargets: ["pair-past-verb-with-future-time"],
  }),
  question({
    id: "ENG_R4_Q_069_07",
    skillId: "ENG_R4_S069",
    difficulty: "standard",
    stem: "It is evening now. I met Grace ___.",
    options: ["tomorrow morning", "every morning", "this morning", "right now"],
    answerIndex: 2,
    reasons: ["tomorrow morning 是未來。", "every morning 表重複習慣，與 met 不合。", "this morning 在 evening 回顧時已結束。", "right now 指目前，與過去式 met 不合。"],
    reviews: ["現在已是 evening，所以同一天的 morning 已成為過去時段。", "第三項能和 met 搭配；其他片語分別指未來、習慣或現在。"],
    cognitiveProcess: ["resolve-this-morning-from-evening-viewpoint", "match-met-to-ended-day-part"],
    misconceptionTargets: ["assume-this-always-means-present"],
  }),
  question({
    id: "ENG_R4_Q_069_08",
    skillId: "ENG_R4_S069",
    difficulty: "advanced",
    stem: "When I was seven, I ___ to ride a bike.",
    options: ["learn", "am learning", "learns", "learned"],
    answerIndex: 3,
    reasons: ["learn 是原形，沒有配合 was seven。", "am learning 是現在進行式。", "learns 是現在第三人稱且不配 I。", "learned 表示七歲時完成學習。"],
    reviews: ["When I was seven 建立明確過去人生階段，主要動作使用 learned。", "第四項同時配合主詞 I 與過去背景；其他形式均為非過去。"],
    cognitiveProcess: ["use-age-clause-as-past-anchor", "select-learned-for-childhood-event"],
    misconceptionTargets: ["focus-on-present-ability-instead-of-learning-time"],
  }),
  question({
    id: "ENG_R4_Q_069_09",
    skillId: "ENG_R4_S069",
    difficulty: "advanced",
    stem: "The report says, “The road opened last June.” Which words place the opening in the past?",
    options: ["last June", "The road", "says", "The report"],
    answerIndex: 0,
    reasons: ["last June 是明確過去時間。", "The road 是事件主詞。", "says 是外層報告動詞。", "The report 是外層主詞。"],
    reviews: ["opened 已是過去式，而 last June 進一步指出事件發生時間。", "只有第一項具有時間定位功能；另外三項提供人物或句子結構資訊。"],
    cognitiveProcess: ["isolate-last-june-time-anchor", "distinguish-report-frame-from-event-time"],
    representationType: "time-anchor-identification",
    misconceptionTargets: ["select-past-verb-frame-instead-of-time-phrase"],
  }),
  question({
    id: "ENG_R4_Q_069_10",
    skillId: "ENG_R4_S069",
    difficulty: "advanced",
    stem: "A diary dated Monday says, “Yesterday we climbed the hill.” On which day did they climb it?",
    options: ["Monday", "Sunday", "Tuesday", "Friday"],
    answerIndex: 1,
    reasons: ["Monday 是寫日記的日期，不是 yesterday。", "Sunday 是 Monday 的前一天。", "Tuesday 是 Monday 的後一天。", "Friday 沒有文本依據。"],
    reviews: ["日記中的 yesterday 以 Monday 為立足點，往前一天就是 Sunday。", "第二項由日期關係直接推出；其他日期不是 Monday 的前一天。"],
    cognitiveProcess: ["convert-diary-yesterday-to-sunday", "anchor-relative-time-to-text-date"],
    representationType: "relative-date-inference",
    misconceptionTargets: ["anchor-yesterday-to-reader-date"],
  }),
  question({
    id: "ENG_R4_Q_069_11",
    skillId: "ENG_R4_S069",
    difficulty: "transfer",
    stem: "Which sentence matches “three weeks ago”?",
    options: ["The team practices now.", "The team will practice next week.", "The team practiced three weeks before today.", "The team practices every three weeks."],
    answerIndex: 2,
    reasons: ["now 指目前，不是三週前。", "next week 指未來。", "three weeks before today 正確解釋 ago。", "every three weeks 表固定間隔的習慣。"],
    reviews: ["ago 從 today 往前計算，因此 three weeks ago 是今天前三週。", "第三項保留單一過去時間；其他選項分別改成現在、未來或重複習慣。"],
    cognitiveProcess: ["paraphrase-three-weeks-ago", "separate-single-past-point-from-frequency"],
    representationType: "time-expression-paraphrase",
    misconceptionTargets: ["confuse-ago-with-every"],
  }),
  question({
    id: "ENG_R4_Q_069_12",
    skillId: "ENG_R4_S069",
    difficulty: "transfer",
    stem: "It is 2026. The library opened in 2020 and still serves the town. What is true now?",
    options: ["The library will first open after 2026.", "The library closed in 2020.", "The library serves only in the past.", "The opening happened in the past, but the service continues now."],
    answerIndex: 3,
    reasons: ["opened in 2020 明確早於 2026。", "文中沒有關閉資訊。", "still serves 表現在持續服務。", "這一項正確分開過去開幕與現在服務。"],
    reviews: ["opened 定位一次過去事件，still serves 則說明現況延續。", "第四項同時保留兩種時間意義；前三項都和年份或 still 的證據衝突。"],
    cognitiveProcess: ["separate-past-opening-from-current-service", "integrate-in-2020-with-still"],
    representationType: "cross-time-state-inference",
    misconceptionTargets: ["infer-current-closure-from-past-opened"],
  }),
  question({
    id: "ENG_R4_Q_070_01",
    skillId: "ENG_R4_S070",
    difficulty: "foundation",
    stem: "Mia packed her bag before she left home. What happened first?",
    options: ["Mia packed her bag.", "Mia left home.", "Mia came home.", "Mia opened her bag."],
    answerIndex: 0,
    reasons: ["before 表示打包發生在離家之前。", "left home 是第二件事。", "文中沒有回家。", "文中沒有打開袋子。"],
    reviews: ["packed her bag 位於 before 前，明確是較早事件。", "第一項直接重述已知順序，第三、四項則加入原句沒有的動作。"],
    cognitiveProcess: ["identify-packed-as-first-before-left", "exclude-unstated-home-actions"],
    representationType: "before-order-detail",
    misconceptionTargets: ["choose-left-because-it-is-nearer-question"],
  }),
  question({
    id: "ENG_R4_Q_070_02",
    skillId: "ENG_R4_S070",
    difficulty: "foundation",
    stem: "Ben ate breakfast, then brushed his teeth. What happened second?",
    options: ["Ben made breakfast.", "Ben brushed his teeth.", "Ben went to bed.", "Ben ate dinner."],
    answerIndex: 1,
    reasons: ["文中只說吃早餐，沒有說製作。", "then 後的 brushed his teeth 是第二件事。", "文中沒有上床睡覺。", "事件是 breakfast，不是 dinner。"],
    reviews: ["then 將刷牙放在吃早餐之後。", "第二項完全對應第二個過去動作；其他項目更換了動作或餐別。"],
    cognitiveProcess: ["use-then-to-locate-brushing-second", "retain-breakfast-story-details"],
    representationType: "then-order-detail",
    misconceptionTargets: ["replace-ate-with-made"],
  }),
  question({
    id: "ENG_R4_Q_070_03",
    skillId: "ENG_R4_S070",
    difficulty: "foundation",
    stem: "The bell rang after the students sat down. What happened first?",
    options: ["The students left.", "The bell rang.", "The students sat down.", "The teacher opened the door."],
    answerIndex: 2,
    reasons: ["文中沒有學生離開。", "rang 發生在 after 所指事件之後。", "after the students sat down 表示坐下在先。", "文中沒有老師開門。"],
    reviews: ["A after B 的實際順序是 B 在前、A 在後，因此 students sat down 先發生。", "第三項由 after 直接推出；其他選項不是第一件事或沒有文本根據。"],
    cognitiveProcess: ["reverse-surface-order-in-after-sentence", "identify-sat-before-rang"],
    representationType: "after-order-detail",
    misconceptionTargets: ["assume-first-mentioned-event-happened-first"],
  }),
  question({
    id: "ENG_R4_Q_070_04",
    skillId: "ENG_R4_S070",
    difficulty: "standard",
    stem: "Before the rain began, the workers covered the boxes. Which event happened later?",
    options: ["The workers found new boxes.", "The workers moved the boxes.", "The workers covered the boxes.", "The rain began."],
    answerIndex: 3,
    reasons: ["文中沒有找到新箱子。", "文中沒有搬動箱子。", "covered 發生在 before 所建立的較早時間。", "rain began 發生在工人蓋好箱子之後。"],
    reviews: ["before the rain began 說明覆蓋箱子先完成，雨之後才開始。", "第四項是唯一較晚事件；第一、二項無依據，第三項是較早事件。"],
    cognitiveProcess: ["identify-rain-as-later-event", "apply-before-with-fronted-clause"],
    representationType: "later-event-selection",
    misconceptionTargets: ["mistake-fronted-before-event-as-later"],
  }),
  question({
    id: "ENG_R4_Q_070_05",
    skillId: "ENG_R4_S070",
    difficulty: "standard",
    stem: "First, we found the bus stop. Then, we got on the bus. Which order matches the story?",
    options: ["find the stop → get on the bus", "get on the bus → find the stop", "leave the bus → find the stop", "get home → look for the stop"],
    answerIndex: 0,
    reasons: ["這個順序符合 First 與 Then。", "這一項把兩件事顛倒。", "文中沒有離開公車。", "文中沒有先回家。"],
    reviews: ["First 標示找到站牌，Then 才標示上車。", "第一項保留兩個原事件與正確箭頭方向，其餘選項顛倒或加入新事件。"],
    cognitiveProcess: ["translate-first-then-story-to-arrow-order", "preserve-bus-stop-and-boarding-events"],
    representationType: "event-sequence-diagram-text",
    misconceptionTargets: ["reverse-first-then-arrow"],
  }),
  question({
    id: "ENG_R4_Q_070_06",
    skillId: "ENG_R4_S070",
    difficulty: "standard",
    stem: "After Grace locked the door, she checked her bag. Which action followed the locking?",
    options: ["She opened the door.", "She checked her bag.", "She put the key in her bag.", "She packed before locking."],
    answerIndex: 1,
    reasons: ["文中沒有再開門。", "主句 checked her bag 發生在鎖門之後。", "文中沒有說她把鑰匙放進袋子。", "文中沒有提到打包。"],
    reviews: ["After Grace locked the door 建立先行事件，後續是 she checked her bag。", "第二項回答 followed the locking；其他選項都不是原句提供的後續動作。"],
    cognitiveProcess: ["resolve-following-action-after-locking", "distinguish-main-clause-from-after-clause"],
    representationType: "following-action-question",
    misconceptionTargets: ["treat-after-clause-as-second-event"],
  }),
  question({
    id: "ENG_R4_Q_070_07",
    skillId: "ENG_R4_S070",
    difficulty: "standard",
    stem: "The lights went out. We waited a minute. Then Sam found a flashlight. Which event was third?",
    options: ["The lights went out.", "We waited a minute.", "Sam found a flashlight.", "Sam turned off the lights."],
    answerIndex: 2,
    reasons: ["燈熄滅是第一件事。", "等待一分鐘是第二件事。", "Then 後找到手電筒是第三件事。", "文中沒有說 Sam 關燈。"],
    reviews: ["三句依序建立熄燈、等待、找到手電筒。", "第三項對應最後一句；第四項把自然現象錯寫成 Sam 的行動。"],
    cognitiveProcess: ["track-three-event-flashlight-sequence", "select-third-after-two-prior-events"],
    representationType: "three-event-position-question",
    misconceptionTargets: ["confuse-cause-of-lights-out-with-third-event"],
  }),
  question({
    id: "ENG_R4_Q_070_08",
    skillId: "ENG_R4_S070",
    difficulty: "advanced",
    stem: "At first, the road was dry. Later, heavy rain covered it with water. What changed?",
    options: ["The road changed from wet to dry.", "The road was wet before the rain.", "The road stayed dry the whole time.", "The road changed from dry to wet."],
    answerIndex: 3,
    reasons: ["這一項把乾濕變化顛倒。", "At first 已明說道路是乾的。", "Later 的雨水表示路面不再保持乾燥。", "At first 與 Later 對比出乾到濕的變化。"],
    reviews: ["At first 建立乾燥狀態，Later 的大雨使路面覆水。", "第四項精確概括前後變化；前三項與地點或狀態證據衝突。"],
    cognitiveProcess: ["compare-at-first-and-later-road-states", "infer-dry-to-wet-change"],
    representationType: "state-change-over-time",
    misconceptionTargets: ["ignore-later-state-update"],
  }),
  question({
    id: "ENG_R4_Q_070_09",
    skillId: "ENG_R4_S070",
    difficulty: "advanced",
    stem: "We ___ the map before we ___ the station.",
    options: ["checked / left", "left / checked", "check / leave", "are checking / left"],
    answerIndex: 0,
    reasons: ["checked 與 left 都是過去式，且順序符合 before。", "此組變成先離站後查地圖，與句型位置不同。", "兩個原形沒有標示過去敘事。", "第一個動詞改成現在進行，時間不一致。"],
    reviews: ["before 連接兩個已完成事件：先查地圖，再離開車站。", "第一組在時態與語意順序上都一致；其他組顛倒動作或混用時間。"],
    cognitiveProcess: ["complete-before-clause-with-two-past-verbs", "preserve-check-then-leave-order"],
    representationType: "ordered-dual-cloze",
    misconceptionTargets: ["reverse-verbs-around-before"],
  }),
  question({
    id: "ENG_R4_Q_070_10",
    skillId: "ENG_R4_S070",
    difficulty: "advanced",
    stem: "Nora put the cake in the oven. Twenty minutes later, she took it out. What does “later” tell us?",
    options: ["The two actions happened every day.", "Taking the cake out happened after putting it in.", "The cake was never in the oven.", "Taking it out happened first."],
    answerIndex: 1,
    reasons: ["句子描述一次過去過程，不是每日習慣。", "later 明確把 took it out 放在 put it in 之後。", "第一句已說蛋糕放進烤箱。", "這一項顛倒 later 的順序。"],
    reviews: ["Twenty minutes later 表示第二個動作比第一個晚二十分鐘。", "第二項保留放入、取出的合理順序；其餘項目改成習慣、否定事實或顛倒時間。"],
    cognitiveProcess: ["interpret-later-in-oven-process", "order-put-in-and-took-out"],
    representationType: "connector-meaning-in-context",
    misconceptionTargets: ["read-later-as-earlier"],
  }),
  question({
    id: "ENG_R4_Q_070_11",
    skillId: "ENG_R4_S070",
    difficulty: "transfer",
    stem: "The team arrived at school at 8:00, left for the game at 8:30, and reached the park at 9:00. Which event was between the other two?",
    options: ["The team reached the park.", "The team played at school.", "The team left for the game.", "The team arrived at school."],
    answerIndex: 2,
    reasons: ["reached the park 是 9:00 的最後事件。", "文中沒有在學校比賽。", "8:30 的離校位於 8:00 與 9:00 之間。", "arrived at school 是 8:00 的第一事件。"],
    reviews: ["依 8:00、8:30、9:00 排序，中間事件是 left for the game。", "第三項同時符合時間數值與敘述內容；其他項目為首尾事件或未提資訊。"],
    cognitiveProcess: ["place-three-schedule-events-on-timeline", "identify-middle-eight-thirty-event"],
    representationType: "clock-time-sequence",
    misconceptionTargets: ["select-last-event-as-middle"],
  }),
  question({
    id: "ENG_R4_Q_070_12",
    skillId: "ENG_R4_S070",
    difficulty: "transfer",
    stem: "We missed the first bus, waited for the next one, and finally reached home. Which event ended the story?",
    options: ["We missed the first bus.", "We waited at home.", "We found the first bus.", "We reached home."],
    answerIndex: 3,
    reasons: ["錯過公車是故事開端。", "文中是在等下一班車，不是在家等。", "文中沒有找到第一班車。", "finally 表示到家是最後事件。"],
    reviews: ["finally 明確引出整段交通過程的結尾 reached home。", "第四項保留原文最後結果；其他選項屬開端或加入不存在的事件。"],
    cognitiveProcess: ["identify-finally-marked-story-ending", "separate-opening-delay-from-final-result"],
    representationType: "narrative-ending-identification",
    misconceptionTargets: ["choose-first-problem-as-story-ending"],
  }),
];

export const ENGLISH_U10_VOCABULARY_POLICY = Object.freeze({
  capQuestionBasis: "appendix-5-table-1",
  additionalLearningTerms: ["ball", "base", "complete", "continue", "daily", "diary", "downstairs", "empty", "event", "flashlight", "form", "forward", "guest", "lock", "match", "message", "negative", "oven", "print", "serve", "whole"],
  properNames: ["Amy", "Ben", "Grace", "Jack", "Ken", "Leo", "Lily", "Maya", "Mia", "Mina", "Nora", "Sam", "Sara", "Tainan", "Tom"],
  grammarNotation: ["-d", "-ed", "-ie", "-ied", "-ing", "-n", "-V", "-w", "-x", "-y", "A", "B", "V-ing"],
  malformedDistractors: ["buyed", "carrid", "carryed", "comed", "eated", "finded", "gived", "goed", "haved", "liveed", "maked", "plaied", "playd", "planed", "printted", "putted", "seed", "stoped", "stopied", "stoppied", "stopt", "studyd", "studyed", "taked", "visitted", "waitted", "writed"],
});

export const ENGLISH_U10_SOURCE = Object.freeze({
  unitId: UNIT_ID,
  lectures: ENGLISH_U10_LECTURES,
  questions: ENGLISH_U10_QUESTIONS,
  vocabularyPolicy: ENGLISH_U10_VOCABULARY_POLICY,
});

export const ENGLISH_UNIT_SOURCE = ENGLISH_U10_SOURCE;

export { question };
