const UNIT_ID = "ENG_R4_U18";

function lecture(id, skillId, content) {
  return { id, skillId, ...content, sections: content.sections.map((section, index) => ({ id: `${id}_SEC_${String(index + 1).padStart(2, "0")}`, ...section })) };
}

const DIFFICULTIES = ["foundation", "foundation", "foundation", "standard", "standard", "standard", "standard", "advanced", "advanced", "advanced", "transfer", "transfer"];

function skillQuestions(skillNumber, values) {
  if (values.length !== 12) throw new Error(`ENG_R4_S${skillNumber}: expected 12 authored questions`);
  return values.map((value, index) => ({ id: `ENG_R4_Q_${skillNumber}_${String(index + 1).padStart(2, "0")}`, skillId: `ENG_R4_S${skillNumber}`, difficulty: DIFFICULTIES[index], ...value }));
}

export const ENGLISH_U18_LECTURES = [
  lecture("ENG_R4_L_S120", "ENG_R4_S120", {
    objectives: ["依句中位置把形容詞放在名詞前或連綴動詞後。", "區分形容詞描述人事物與副詞修飾動作的功能。"],
    sections: [
      { title: "名詞前的形容詞直接描述名詞", content: "a quiet room、an old bridge 中 quiet 與 old 都放在名詞前，回答『什麼樣的房間或橋』。形容詞不因名詞變複數而加 s，因此 three quiet rooms 仍使用 quiet。冠詞或數量詞通常放在形容詞前。" },
      { title: "連綴動詞後仍使用形容詞", content: "The room is quiet. 與 The soup smells good. 中形容詞放在 be、look、feel、sound、smell、taste 等連綴動詞後，說明主詞的狀態。此時不是描述動作做得如何，所以不能看到動詞就一律改成副詞。" },
      { title: "動作方式才通常由副詞修飾", content: "Nora is careful. 描述 Nora 的特質；Nora checks the door carefully. 則說明她如何檢查。若主要動詞表示實際動作，修飾動作方式時才使用 carefully。先問被描述的是名詞，還是動作。" },
      { title: "同一形容詞可出現在兩種位置", content: "a bright light 與 The light is bright. 都使用 bright，只是前者直接放在名詞前，後者經由 is 描述主詞。不能把第二句誤寫成 brightly，也不能把名詞前形容詞放到冠詞前面寫成 bright a light。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S120_EX_01", prompt: "It is a ___ room. (quiet / quietly)", steps: ["找空格後的名詞 room。", "判斷空格直接描述 room。", "選擇形容詞 quiet。"], answer: "quiet", why: "空格位於 room 前，功能是說明房間很安靜，因此用形容詞 quiet。quietly 修飾動作，不能直接放在 room 前表達這個意思。" },
      { id: "ENG_R4_L_S120_EX_02", prompt: "The soup smells ___. (good / well)", steps: ["辨認 smells 在此連接 soup 與狀態。", "確認要描述湯的氣味。", "使用形容詞 good。"], answer: "good", why: "smells 在此不是『用鼻子聞得好』的動作，而是連綴動詞，後方 good 描述 soup 的氣味。well 若當副詞，會錯把重點放在聞的方式。" },
      { id: "ENG_R4_L_S120_EX_03", prompt: "Mia is a ___ student. She studies ___. (careful / carefully)", steps: ["student 前需要形容詞。", "studies 後要說明讀書方式。", "依序填 careful 與 carefully。"], answer: "careful; carefully", why: "careful 直接修飾名詞 student，carefully 則修飾動作 studies。兩個空格談的是不同對象，不能因字根相同就填成同一形式。" },
    ],
    misconceptions: [
      { belief: "形容詞只要出現在動詞後就要加 -ly。", whyWrong: "be、look、feel、sound、smell、taste 後常用形容詞描述主詞。", correction: "先判斷動詞是連接狀態，還是表示實際動作。" },
      { belief: "複數名詞前的形容詞也要加 s。", whyWrong: "英文形容詞不隨名詞單複數改變形式。", correction: "寫 one clean cup 與 two clean cups，形容詞都用 clean。" },
      { belief: "看到 good 與 well 時，放在動詞後的一定是 well。", whyWrong: "smells good、looks good 的形容詞描述主詞狀態。", correction: "檢查句意是在評價主詞，還是在說明動作方式。" },
      { belief: "形容詞放在名詞前或 be 後會改變基本意思。", whyWrong: "a dark room 與 The room is dark 都描述同一種狀態。", correction: "把兩種位置視為名詞內部描述與完整句敘述。" },
    ],
    checks: [
      { prompt: "a careful driver 中 careful 描述什麼？", answer: "driver", reason: "形容詞直接放在名詞前。" },
      { prompt: "The music sounds loud 中 loud 要改成 loudly 嗎？", answer: "不用", reason: "sounds 是連綴動詞，loud 描述 music。" },
      { prompt: "They work quietly 中 quietly 修飾什麼？", answer: "work", reason: "它說明工作的方式。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S121", "ENG_R4_S121", {
    objectives: ["依短形容詞拼字規則形成比較級與最高級。", "分辨加 -er、-est、去 e、雙寫字尾與 y 變 i 的情況。"],
    sections: [
      { title: "多數短形容詞直接加 -er 或 -est", content: "tall 變 taller、tallest，fast 變 faster、fastest。比較兩個對象時常用比較級；從三個以上的範圍選出最突出者時使用最高級。不能只看到 than 就忽略字形變化。" },
      { title: "字尾已有 e 時只加 r 或 st", content: "large 變 larger、largest，nice 變 nicer、nicest。原字已有不發音 e，不再重複寫 e。若寫成 largeer 或 largeest，雖看得出原字，拼字仍然錯誤。" },
      { title: "短母音加單一字尾子音時要雙寫", content: "big 變 bigger、biggest，hot 變 hotter、hottest。雙寫保留原本的短母音讀法；並非所有短字都雙寫，例如 fast 的字尾不符合這個結構，所以是 faster。" },
      { title: "子音加 y 時先把 y 改成 i", content: "happy 變 happier、happiest，easy 變 easier、easiest：子音後的 y 要先改成 i。若 y 前是母音，如 gray，通常直接加 -er、-est；因此不能看到 y 就一律更換。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S121_EX_01", prompt: "This box is ___ than that one. (big)", steps: ["than 要求比較級。", "big 為短母音加單一字尾子音。", "雙寫 g 再加 -er。"], answer: "bigger", why: "兩個箱子由 than 連接，所以使用比較級。big 的結尾符合短母音加單一子音，必須雙寫 g，正確拼成 bigger，而不是 biger。" },
      { id: "ENG_R4_L_S121_EX_02", prompt: "Nora is the ___ player on the team. (fast)", steps: ["on the team 提供群體範圍。", "the 後需要最高級。", "fast 直接加 -est。"], answer: "fastest", why: "題目從整個 team 找速度最突出的 player，因此用最高級 fastest。fast 不需雙寫 t，因為字尾不是一個短母音後只接一個子音的形式。" },
      { id: "ENG_R4_L_S121_EX_03", prompt: "Today is ___ than yesterday. (happy)", steps: ["than 指向比較級。", "happy 以子音加 y 結尾。", "把 y 改 i 再加 -er。"], answer: "happier", why: "比較今天與昨天要用比較級。happy 的 y 前是子音 p，所以先改成 i，再加 -er，形成 happier；happyer 沒有套用正確字尾規則。" },
    ],
    misconceptions: [
      { belief: "所有短形容詞加 -er 前都要雙寫最後字母。", whyWrong: "tall、fast 等字不符合短母音加單一字尾子音的條件。", correction: "只在 big、hot 這類結尾結構下雙寫。" },
      { belief: "large 的比較級是 largeer。", whyWrong: "原字已有 e，只需加 r。", correction: "把 large、nice 這類字分成已有 e 的拼字群。" },
      { belief: "任何 y 結尾的形容詞都把 y 改成 i。", whyWrong: "gray 的 y 前是母音，通常直接加字尾。", correction: "先看 y 前一個字母是子音還是母音。" },
      { belief: "最高級只是比較級再多加一個 t。", whyWrong: "比較級與最高級有各自的 -er、-est 字尾。", correction: "由比較範圍先選級別，再從原級套用對應規則。" },
    ],
    checks: [
      { prompt: "large 的比較級怎麼拼？", answer: "larger", reason: "原字已有 e，只加 r。" },
      { prompt: "hot 的最高級為何雙寫 t？", answer: "hottest", reason: "字尾符合短母音加單一子音。" },
      { prompt: "easy 的比較級是什麼？", answer: "easier", reason: "子音加 y 要改 y 為 i。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S122", "ENG_R4_S122", {
    objectives: ["使用 more 與 most 形成長形容詞的比較級與最高級。", "避免同時使用 more 或 most 與 -er、-est 的雙重標記。"],
    sections: [
      { title: "長形容詞比較級通常使用 more", content: "difficult 變 more difficult，important 變 more important。more 放在形容詞前，原形拼字不變。與 than 搭配時寫 more useful than，不寫 usefuller 或 more usefuller。" },
      { title: "長形容詞最高級通常使用 most", content: "beautiful 變 most beautiful，interesting 變 most interesting。若句子在一個群體中選出最突出者，常見結構是 the most + adjective。most 後仍放原級，不再加 -est。" },
      { title: "more 與 most 不能和字尾重複標記", content: "more difficult 已經表示比較級，difficulter 與 more difficulter 都不合標準形式；most important 已表示最高級，不寫 most importantest。先決定採前置詞或字尾其中一套。" },
      { title: "先看比較範圍再選 more 或 most", content: "A is more useful than B 比較兩者；A is the most useful tool in the box 則從整盒工具中選出一個。長短只決定字形方式，兩者或群體才決定使用比較級或最高級。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S122_EX_01", prompt: "This plan is ___ than the old plan. (useful)", steps: ["than 表示兩個計畫相比。", "useful 使用前置 more。", "保留 useful 原形。"], answer: "more useful", why: "句子只比較新舊兩個 plan，因此需要比較級。useful 不直接加 -er，而是在原形前放 more，形成 more useful than the old plan。" },
      { id: "ENG_R4_L_S122_EX_02", prompt: "It is the ___ story in this book. (interesting)", steps: ["in this book 建立多篇故事的範圍。", "需要最高級。", "在 interesting 前放 most。"], answer: "most interesting", why: "題目從書中所有故事選出最有趣的一篇，所以使用 the most interesting。interesting 保持原形，不能再接 -est 形成雙重最高級。" },
      { id: "ENG_R4_L_S122_EX_03", prompt: "The bus is ___ than the train today. (comfortable)", steps: ["than 鎖定比較級。", "comfortable 是較長形容詞。", "使用 more comfortable。"], answer: "more comfortable", why: "今天只比較 bus 和 train 的舒適程度，故用比較級。comfortable 前加 more 即可，不能把 more 與 -er 同時放進答案。" },
    ],
    misconceptions: [
      { belief: "字母多的形容詞一律直接加 -er。", whyWrong: "多數長形容詞以 more 形成比較級。", correction: "把 difficult、important、beautiful 等常見長字整理為 more/most 類。" },
      { belief: "more difficult 與 difficulter 可以任選。", whyWrong: "標準用法採 more difficult，後者不是本單元規範形式。", correction: "長形容詞保留原形，前加 more。" },
      { belief: "最高級可寫 most interestingest 來加強語氣。", whyWrong: "most 與 -est 都是最高級標記，不能重複。", correction: "使用 the most interesting，保留原級拼字。" },
      { belief: "只要形容詞很長，任何句子都用 most。", whyWrong: "比較兩者仍用 more，群體中最突出才用 most。", correction: "先判斷比較對象數量，再套用長形容詞形式。" },
    ],
    checks: [
      { prompt: "difficult 的比較級是什麼？", answer: "more difficult", reason: "長形容詞前加 more。" },
      { prompt: "the most beautiful 後還要加 -est 嗎？", answer: "不用", reason: "most 已經標示最高級。" },
      { prompt: "兩個主意相比要用 more 還是 most important？", answer: "more important", reason: "兩者比較使用比較級。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S123", "ENG_R4_S123", {
    objectives: ["辨識常見不規則形容詞的比較級與最高級。", "依 good、bad、many、much、little 與 far 的實際意思選擇形式。"],
    sections: [
      { title: "good 與 bad 需記住完整變化", content: "good 的比較級與最高級是 better、best；bad 則是 worse、worst。這些形式不能由原字直接加 -er 或 -est 推出，所以 gooder、badder 都不是標準答案。" },
      { title: "many 與 much 共用 more、most", content: "many 修飾可數複數，much 修飾不可數，但兩者的比較級都是 more，最高級都是 most。more books 與 more water 的名詞類型不同，不能因此改變 more 的形式。" },
      { title: "little 表示少量時變成 less、least", content: "little water 的 little 表示數量少，變化為 less water、the least water。若 little 表示尺寸小，通常改用 smaller、smallest。必須先判斷句中談的是數量還是大小。" },
      { title: "far 的距離比較有兩組常見形式", content: "farther、farthest 常直接表示實際距離；further、furthest 也可表示距離，further 還常見於『更多、進一步』。國中距離題可優先掌握 far、farther、farthest，並知道另一組也是標準英文。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S123_EX_01", prompt: "This road is ___ than the old road. (good)", steps: ["than 要求比較級。", "good 是不規則形容詞。", "選擇 better。"], answer: "better", why: "兩條道路相比需要比較級，但 good 不加 -er，而是不規則變成 better。gooder 與 more good 都不是這個意思的標準形式。" },
      { id: "ENG_R4_L_S123_EX_02", prompt: "That was the ___ day of the trip. (bad)", steps: ["the 與整趟旅程形成最高級範圍。", "bad 的最高級不規則。", "使用 worst。"], answer: "worst", why: "題目從整趟 trip 的多天中選出最糟的一天，所以要用 bad 的最高級 worst。worse 只適合兩者比較，baddest 則不是標準變化。" },
      { id: "ENG_R4_L_S123_EX_03", prompt: "This bottle has ___ water than that one. (little)", steps: ["water 是不可數名詞。", "little 表示水量少。", "than 前使用 less。"], answer: "less", why: "句子比較兩瓶水的數量，little 在此不是說瓶子尺寸小，因此比較級是 less。smaller 會比較物體大小，無法直接修飾 water 的量。" },
    ],
    misconceptions: [
      { belief: "good 的比較級可寫 gooder。", whyWrong: "good 使用不規則形式 better。", correction: "將 good-better-best 作為一組記憶。" },
      { belief: "bad 的最高級是 baddest。", whyWrong: "標準形式是 worst。", correction: "把 bad-worse-worst 與 good 的變化對照整理。" },
      { belief: "less 一定表示物體比較小。", whyWrong: "less 主要比較不可數量的多寡。", correction: "尺寸用 smaller，數量少用 less。" },
      { belief: "many 與 much 的比較級不同。", whyWrong: "兩者雖修飾不同名詞，皆使用 more、most。", correction: "先選名詞類型，再保留共同的不規則比較形式。" },
    ],
    checks: [
      { prompt: "good 的最高級是什麼？", answer: "best", reason: "good-better-best 為不規則變化。" },
      { prompt: "bad 的比較級怎麼寫？", answer: "worse", reason: "不是 badder，也不是 more bad。" },
      { prompt: "less time 中 less 比較的是大小還是數量？", answer: "數量", reason: "time 在此為不可數概念。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S124", "ENG_R4_S124", {
    objectives: ["使用比較級加 than 清楚比較兩個對象。", "檢查 than 前後是否比較相同的人、物或屬性。"],
    sections: [
      { title: "基本結構是 comparative + than", content: "Mia is taller than Nora. 中 taller 表示身高較高，than 引出另一個比較對象。不能寫 more taller than，因為 taller 已經帶有比較級標記。" },
      { title: "than 前後要比較相同類型", content: "Mia's bag is heavier than Nora's bag. 比較的是兩個 bag。若寫 Mia's bag is heavier than Nora，就變成拿袋子重量和人的重量相比。省略重複名詞時可保留 Nora's，表示 Nora's bag。" },
      { title: "比較內容必須由上下文支持", content: "The blue box is larger than the red box. 只表示大小關係，不能推出藍箱比較重、比較新或比較貴。閱讀比較句時要抓住形容詞代表的單一屬性，不自行增加其他差異。" },
      { title: "差額可放在比較級前", content: "Leo is three years older than Sam. 中 three years 說明年齡相差多少。a little、much 也可修飾比較級，但 very 不直接放在比較級前寫 very taller。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S124_EX_01", prompt: "The red line is ___ than the blue line. (long)", steps: ["兩條線形成兩者比較。", "long 是短形容詞。", "使用 longer than。"], answer: "longer", why: "than 已經引出 blue line，所以空格要填 long 的比較級 longer。longest 會表示群體中的最長，more longer 則重複標記。" },
      { id: "ENG_R4_L_S124_EX_02", prompt: "Mia's room is cleaner than Nora's. What does 'Nora's' mean?", steps: ["找比較的第一個對象 Mia's room。", "確認 than 後省略相同名詞。", "還原為 Nora's room。"], answer: "Nora's room", why: "比較的是兩個 room 的整潔程度，than 後的 Nora's 保留所有格並省略重複的 room。它不是拿房間和 Nora 本人相比。" },
      { id: "ENG_R4_L_S124_EX_03", prompt: "Ben is two years ___ than Leo. (young)", steps: ["two years 表示年齡差。", "than 需要比較級。", "young 直接加 -er。"], answer: "younger", why: "句子比較 Ben 與 Leo 的年齡，two years 說明差距，young 要變成 younger。youngest 需有更大的群體範圍，不能接在此處。" },
    ],
    misconceptions: [
      { belief: "than 前只要有形容詞原級就可以。", whyWrong: "標準比較結構需要比較級。", correction: "確認是 taller than、more useful than 等形式。" },
      { belief: "more taller 能表示差距更大。", whyWrong: "more 與 -er 重複標記同一比較級。", correction: "短形容詞只保留 taller，強調差距可用 much taller。" },
      { belief: "Mia's bag is heavier than Nora 比較的是兩個人的袋子。", whyWrong: "字面上第二個比較對象是 Nora 本人。", correction: "寫 Nora's bag 或可清楚還原的 Nora's。" },
      { belief: "看到 larger 就能推論物品也比較重。", whyWrong: "larger 只陳述尺寸，不保證重量。", correction: "每個比較句只採用形容詞明說的屬性。" },
    ],
    checks: [
      { prompt: "taller than 中 than 後放什麼？", answer: "另一個比較對象", reason: "than 用來連接兩者。" },
      { prompt: "more easier 正確嗎？", answer: "不正確", reason: "easier 已經是比較級，不能再加 more。" },
      { prompt: "Amy's bike is newer than Ben's 中 Ben's 省略什麼？", answer: "bike", reason: "前後比較同一類物品。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S125", "ENG_R4_S125", {
    objectives: ["使用 as + 原級 + as 表示兩者同等。", "以 not as...as、as many 與 as much 表達不同類型的比較。"],
    sections: [
      { title: "同等比較中間使用原級", content: "This box is as heavy as that one. 表示兩個箱子一樣重。兩個 as 之間放形容詞原級 heavy，不放 heavier、heaviest 或 more heavy。" },
      { title: "not as...as 表示前者程度較低", content: "This road is not as wide as that road. 表示這條路沒有那條路寬，也就是那條路較寬。閱讀時要保留否定方向，不能誤解成兩條一樣寬。" },
      { title: "比較數量時分辨 many 與 much", content: "as many books as 使用 many，因為 books 可數；as much water as 使用 much，因為 water 不可數。many 或 much 後必須保留被比較的名詞，不能只看 as...as 就省略數量對象。" },
      { title: "同等只限句中明說的屬性", content: "The two bags are as heavy as each other. 只能推出重量相同，不能推出顏色、大小或價格也相同。比較結構提供的證據範圍由中間的形容詞決定。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S125_EX_01", prompt: "The green cup is as ___ as the blue cup. (large)", steps: ["辨認兩個 as。", "中間需要形容詞原級。", "保留 large。"], answer: "large", why: "as...as 表示兩個杯子的大小相同，中間固定使用原級 large。larger 會改成一方較大，largest 則需要群體最高級。" },
      { id: "ENG_R4_L_S125_EX_02", prompt: "This tree is not as tall as that tree. Which tree is taller?", steps: ["找 not as tall as。", "判讀前者未達後者高度。", "選擇 that tree。"], answer: "that tree", why: "not as tall as 表示 this tree 的高度低於 that tree，因此較高的是 that tree。否定詞 not 不能忽略，也不能解成兩棵一樣高。" },
      { id: "ENG_R4_L_S125_EX_03", prompt: "Mia has as ___ books as Nora. (many / much)", steps: ["books 是可數複數。", "可數數量使用 many。", "完成 as many books as。"], answer: "many", why: "books 能以本數計算，所以在 as...as 結構中使用 many。much 用於 water、time 等不可數名詞，不能直接修飾 books。" },
    ],
    misconceptions: [
      { belief: "as...as 中間要使用比較級。", whyWrong: "同等結構固定使用形容詞原級。", correction: "寫 as tall as，不寫 as taller as。" },
      { belief: "not as heavy as 表示兩者一樣重。", whyWrong: "not 否定同等，表示前者較輕。", correction: "先圈出 not，再判斷比較方向。" },
      { belief: "as many 與 as much 可以任意交換。", whyWrong: "many 接可數複數，much 接不可數名詞。", correction: "先判斷被比較名詞能否逐一計數。" },
      { belief: "兩物 as old as 就代表各方面都相同。", whyWrong: "句子只說明年齡相同。", correction: "推論範圍限制在 as...as 中間的屬性。" },
    ],
    checks: [
      { prompt: "as fast as 中 fast 是哪一級？", answer: "原級", reason: "同等比較不使用 faster。" },
      { prompt: "not as old as 表示前者較老嗎？", answer: "不是", reason: "前者沒有後者那麼老。" },
      { prompt: "as much rice as 還是 as many rice as？", answer: "as much rice as", reason: "rice 是不可數名詞。" },
    ], assets: [],
  }),
  lecture("ENG_R4_L_S126", "ENG_R4_S126", {
    objectives: ["由比較對象數量與範圍判斷是否使用最高級。", "正確使用 the、in、of 與 one of the + superlative + plural noun。"],
    sections: [
      { title: "兩者比較不用最高級", content: "在 Mia 和 Nora 兩人之間，應說 Mia is taller than Nora。最高級表示一個對象在三個以上或明確群體中最突出；若範圍只有兩個，使用比較級較合適。" },
      { title: "最高級前通常使用 the", content: "Leo is the tallest student in the class. 中 the tallest 指班上唯一最高程度的位置。若前面已有 my、Nora's 等所有格，則可寫 my best friend，不再加 the。" },
      { title: "in 與 of 說明比較範圍", content: "the tallest student in the class 以班級作範圍；the tallest of the three students 則從明列的三人中比較。in 常接地點或群體，of 常接明確列出的成員集合。" },
      { title: "one of the 後接最高級與複數名詞", content: "one of the best players 表示最佳球員群中的一位，因此 players 必須是複數。這個結構不表示唯一第一名，而是屬於最高表現的一群人。" },
    ],
    workedExamples: [
      { id: "ENG_R4_L_S126_EX_01", prompt: "Of the three bags, the red one is the ___. (light)", steps: ["of the three bags 建立三個比較對象。", "需要最高級。", "light 直接加 -est。"], answer: "lightest", why: "比較範圍明列三個 bags，因此 red one 要用最高級 lightest。lighter 只表示比另一個輕，沒有表達三者之中最輕。" },
      { id: "ENG_R4_L_S126_EX_02", prompt: "This is the ___ tool in the box. (useful)", steps: ["in the box 指出整組工具。", "useful 使用 most 形成最高級。", "保留 the most useful。"], answer: "most useful", why: "題目從箱內整組工具選出最有用的一件，所以用 the most useful。more useful 仍需要另一個 than 比較對象，無法表達群體第一。" },
      { id: "ENG_R4_L_S126_EX_03", prompt: "Nora is one of the ___ players on the team. (good)", steps: ["one of the 表示群體中的一員。", "good 使用不規則最高級 best。", "players 保持複數。"], answer: "best", why: "one of the 後要接最高級與複數名詞，表示 Nora 屬於隊上表現最好的一群球員。good 的最高級是不規則 best，不是 goodest。" },
    ],
    misconceptions: [
      { belief: "兩個人之中一定要用 the tallest。", whyWrong: "只有兩個對象時通常使用 taller。", correction: "先數比較對象，再選比較級或最高級。" },
      { belief: "最高級前無論如何都要加 the。", whyWrong: "my best friend 等所有格已限定名詞。", correction: "若已有 my、his、Nora's 等限定詞，不再重複 the。" },
      { belief: "one of the best player 使用單數 player。", whyWrong: "one 是從一群最佳成員中取一位，群體名詞要複數。", correction: "固定檢查 one of the + 最高級 + 複數名詞。" },
      { belief: "the largest 代表物品也一定最重。", whyWrong: "最高級只針對 largest 所說的尺寸。", correction: "不要把一種屬性的最高程度延伸到其他屬性。" },
    ],
    checks: [
      { prompt: "兩位學生比較身高用 taller 還是 tallest？", answer: "taller", reason: "兩者比較使用比較級。" },
      { prompt: "the oldest of the four 中 of the four 做什麼？", answer: "指出比較範圍", reason: "它明列四個比較對象。" },
      { prompt: "one of the tallest student 哪裡需要修正？", answer: "student 改為 students", reason: "最高級群體必須用複數名詞。" },
    ], assets: [],
  }),
];

export const ENGLISH_U18_QUESTIONS = [
  ...skillQuestions("120", [
    { stem: "It is a ___ room.", options: ["quiet", "quietly", "quite", "more quietly"], answerIndex: 0, reasons: ["quiet 是形容詞，可直接修飾 room。", "quietly 是副詞，不能在此描述名詞。", "quite 是程度副詞，後面還需接形容詞，不能單獨修飾 room。", "more quietly 是副詞比較形式，句中沒有動作可修飾。"], reviews: ["空格後緊接名詞 room，需選形容詞。", "第一項形成 a quiet room，字義與句法都完整。"], cognitiveProcess: ["inspect-word-before-room", "select-quiet-as-attributive-adjective"], representationType: "adjective-before-noun-cloze", misconceptionTargets: ["add-ly-before-noun"] },
    { stem: "The soup smells ___.", options: ["well", "good", "goodness", "more well"], answerIndex: 1, reasons: ["well 當副詞時修飾聞的動作，不是此句要描述的湯。", "good 是形容詞，接在 smells 後說明 soup 的氣味。", "goodness 是名詞，不能作此處主詞狀態。", "more well 不是描述湯味道的標準結構。"], reviews: ["smells 在此連接 soup 與氣味狀態。", "第二項不是因為位置在動詞後，而是因為要描述主詞。"], cognitiveProcess: ["read-smells-as-linking-verb", "describe-soup-with-good"], representationType: "linking-verb-adjective-cloze", misconceptionTargets: ["use-well-after-every-verb"] },
    { stem: "Mia is a ___ student.", options: ["carefully", "care", "careful", "cared"], answerIndex: 2, reasons: ["carefully 是副詞，不直接修飾 student。", "care 通常是名詞或動詞，不能在此表達特質。", "careful 是形容詞，可描述 student。", "cared 是動詞過去式，不能放在 a 與 student 之間。"], reviews: ["冠詞 a 後、名詞 student 前是典型形容詞位置。", "第三項表達 Mia 是一位做事謹慎的學生。"], cognitiveProcess: ["locate-modifier-between-a-and-student", "choose-careful-not-carefully"], representationType: "person-quality-adjective", misconceptionTargets: ["confuse-adjective-and-adverb-family"] },
    { stem: "Nora checks every door ___.", options: ["careful", "care", "cared", "carefully"], answerIndex: 3, reasons: ["careful 描述人或物，但此空格要說明 checks 的方式。", "care 無法直接作方式副詞。", "cared 是過去式動詞，和 checks 衝突。", "carefully 是副詞，說明 Nora 如何檢查。"], reviews: ["主要動作 checks 已完整，句尾空格補充動作方式。", "第四項把 carefully 與實際動作連接，而不是只看人物特質。"], cognitiveProcess: ["identify-checks-as-action-needing-manner", "place-carefully-after-door"], representationType: "adverb-versus-adjective-cloze", misconceptionTargets: ["use-careful-for-action-manner"] },
    { stem: "Which line puts an adjective directly before the noun it describes?", options: ["We sat in a quiet room.", "The room became quiet.", "The baby slept quietly.", "Please speak more quietly."], answerIndex: 0, reasons: ["quiet 直接放在 room 前。", "quiet 位於 became 後描述主詞，不在名詞前。", "quietly 修飾 slept。", "more quietly 修飾 speak 的方式。"], reviews: ["題目指定的是名詞前位置，不只是找任何形容詞。", "第一項的 quiet 與 room 位於同一名詞片語。"], cognitiveProcess: ["compare-quiet-family-positions", "find-quiet-immediately-before-room"], representationType: "adjective-position-selection", misconceptionTargets: ["choose-linking-verb-adjective-instead"] },
    { stem: "The music sounds ___.", options: ["loudly", "loud", "noise", "louder than"], answerIndex: 1, reasons: ["loudly 通常修飾發出聲音的動作方式。", "loud 是形容詞，描述 music 聽起來的狀態。", "noise 是名詞，不能直接接在 sounds 後描述音樂狀態。", "louder than 缺少 than 後的比較對象。"], reviews: ["sounds 是連綴動詞，並未表示音樂主動聆聽。", "第二項把音量特質連回主詞 music。"], cognitiveProcess: ["interpret-sounds-as-state-link", "attach-loud-to-music"], representationType: "sound-linking-adjective", misconceptionTargets: ["select-loudly-because-sounds-is-verb"] },
    { stem: "Please wash the two ___ cups.", options: ["cleans", "cleanly", "clean", "cleaned"], answerIndex: 2, reasons: ["形容詞不因 cups 為複數而加 s。", "cleanly 是副詞，不能描述 cups 的狀態。", "clean 是形容詞，修飾複數 cups 時形式不變。", "cleaned 表示已被清洗，與指示要洗乾淨杯子的意思不同。"], reviews: ["two 與 cups 顯示名詞複數，但不會改變形容詞。", "第三項形成 two clean cups，保留正確詞序。"], cognitiveProcess: ["separate-cup-plural-from-adjective-form", "keep-clean-unchanged-before-cups"], representationType: "plural-noun-adjective-invariance", misconceptionTargets: ["pluralize-adjective-with-s"] },
    { stem: "A student writes, 'Sam is a carefully driver.' Which change fixes the sentence about Sam?", options: ["Sam → Sams", "is → does", "driver → drive", "carefully → careful"], answerIndex: 3, reasons: ["Sam 是單一人名，不需變複數。", "is 正確連接 Sam 與身分。", "drive 會把職業名詞改成動詞。", "driver 前需要形容詞 careful，不使用副詞 carefully。"], reviews: ["錯誤出現在名詞 driver 前的詞性。", "第四項只修正修飾語，不改人物、動詞或身分。"], cognitiveProcess: ["diagnose-adverb-before-driver", "repair-carefully-to-careful"], representationType: "adjective-form-edit", misconceptionTargets: ["change-noun-instead-of-modifier"] },
    { stem: "Which pair puts 'bright' before a noun and after 'is'?", options: ["a bright light / The light is bright.", "a brightly light / The light is brightly.", "bright a light / The bright is light.", "a light bright / Brightly the light is."], answerIndex: 0, reasons: ["bright 可放在 light 前，也可放在 is 後描述同一主詞。", "brightly 不能直接修飾 light，也不作連綴動詞補語。", "第一個片語詞序錯誤，第二句也把詞性關係顛倒。", "兩部分都不符合一般形容詞位置。"], reviews: ["同一形容詞可在名詞片語內或連綴動詞後出現。", "第一項展示位置改變但描述內容不變。"], cognitiveProcess: ["match-two-valid-bright-positions", "preserve-light-description-across-forms"], representationType: "paired-adjective-position", misconceptionTargets: ["believe-one-adjective-has-one-position"] },
    { stem: "The children looked ___ after the long walk.", options: ["tiredly", "tired", "tiring", "more tiredly"], answerIndex: 1, reasons: ["tiredly 不是此處描述孩子狀態的形式。", "tired 是形容詞，接在 looked 後說明 children 的樣子。", "tiring 表示令人疲倦，會把孩子說成造成疲勞的人。", "more tiredly 仍是副詞方向，且沒有比較對象。"], reviews: ["after the long walk 提供孩子感到疲倦的原因。", "第二項讓 looked 成為連綴動詞，語意與形式一致。"], cognitiveProcess: ["use-walk-result-to-choose-tired", "place-state-adjective-after-looked"], representationType: "ed-ing-linking-adjective", misconceptionTargets: ["choose-tiring-for-person-feeling"] },
    { stem: "A sign says, 'The floor is wet. Walk ___.'", options: ["careful", "care", "carefully", "more careful"], answerIndex: 2, reasons: ["careful 是形容詞，不能直接說明 walk 的方式。", "care 不是此處需要的方式副詞。", "carefully 修飾 walk，符合濕地板警示。", "more careful 需要 be 等結構或比較語境。"], reviews: ["警示先交代 wet floor，再要求改變走路方式。", "第三項把安全要求放在動作 walk 上。"], cognitiveProcess: ["connect-wet-floor-warning-to-walking-manner", "select-carefully-for-imperative"], representationType: "notice-adverb-transfer", misconceptionTargets: ["use-adjective-after-action-verb"] },
    { stem: "Which line says that the flower has a pleasant smell?", options: ["The flower smells the sweet air.", "The flower smells sweetly.", "The flower is sweetly.", "The flower smells sweet."], answerIndex: 3, reasons: ["此句把 flower 寫成聞空氣的動作者。", "sweetly 把重點改成聞的方式，沒有描述花的氣味。", "be 動詞後不能用副詞 sweetly 作主詞狀態。", "smells 作連綴動詞，sweet 描述花的氣味。"], reviews: ["題目要表達花本身聞起來香甜，不是花去聞別物。", "第四項用最短完整結構連接 flower 與 sweet。"], cognitiveProcess: ["distinguish-flower-scent-from-smelling-action", "select-smells-sweet-clause"], representationType: "meaning-specific-linking-verb", misconceptionTargets: ["add-ly-to-scent-adjective"] },
  ]),
  ...skillQuestions("121", [
    { stem: "This tree is ___ than that tree. (tall)", options: ["taller", "tallest", "more tall", "tall"], answerIndex: 0, reasons: ["taller 是 tall 的比較級，能與 than 搭配。", "tallest 是最高級，需要群體範圍。", "more tall 不是本單元採用的短形容詞形式。", "原級 tall 沒有標出兩樹的高低比較。"], reviews: ["than 先確定使用比較級，tall 再直接加 -er。", "第一項只標記一次比較，形式完整。"], cognitiveProcess: ["use-than-to-select-tall-comparative", "form-taller-with-er"], representationType: "short-adjective-comparative", misconceptionTargets: ["use-more-with-tall"] },
    { stem: "This is the ___ car in the race. (fast)", options: ["faster", "fastest", "most fast", "fastly"], answerIndex: 1, reasons: ["faster 只表示比另一輛快，未涵蓋整場 race。", "fastest 是短形容詞最高級，符合 in the race。", "most fast 不是此處標準短字形式。", "fastly 不是 fast 的一般副詞形式。"], reviews: ["the 與 in the race 建立群體最高級。", "第二項從參賽車輛中指出速度最高的一輛。"], cognitiveProcess: ["read-race-as-superlative-range", "choose-fastest-car"], representationType: "short-adjective-superlative", misconceptionTargets: ["stop-at-comparative-with-group"] },
    { stem: "The new room is ___ than the old room. (large)", options: ["largeer", "largest", "larger", "more larger"], answerIndex: 2, reasons: ["large 已有 e，不能再完整加 er。", "largest 是最高級，不用於兩個房間。", "larger 只在原字後加 r，拼字正確。", "more 與 -er 重複標記比較級。"], reviews: ["than 確定比較級，字尾 e 決定只加 r。", "第三項同時通過級別與拼字檢查。"], cognitiveProcess: ["apply-existing-e-rule-to-large", "select-larger-between-two-rooms"], representationType: "silent-e-comparative", misconceptionTargets: ["write-largeer"] },
    { stem: "It was the ___ day this week. (hot)", options: ["hotest", "hotter", "most hot", "hottest"], answerIndex: 3, reasons: ["hot 需雙寫 t，hotest 少一個 t。", "hotter 是比較級，未表達一週最熱。", "most hot 不是此處採用的短形容詞最高級。", "hottest 雙寫 t 再加 -est，且符合 this week 的範圍。"], reviews: ["this week 提供多天比較，需最高級。", "第四項保留 hot 的短母音讀法並正確標示最高程度。"], cognitiveProcess: ["combine-week-range-with-hot-spelling", "double-t-for-hottest"], representationType: "cvc-superlative", misconceptionTargets: ["omit-doubled-final-consonant"] },
    { stem: "Mia looks ___ today than yesterday. (happy)", options: ["happier", "happyer", "happiest", "more happier"], answerIndex: 0, reasons: ["happier 把子音後的 y 改為 i，再加 -er。", "happyer 沒有套用 y 變 i。", "happiest 是最高級，不符合兩天比較。", "more 與 happier 重複標記。"], reviews: ["today 與 yesterday 是兩個時間狀態，than 要求比較級。", "第一項正確處理 happy 的字尾。"], cognitiveProcess: ["compare-happiness-across-two-days", "change-y-to-i-in-happier"], representationType: "y-ending-comparative", misconceptionTargets: ["keep-y-before-er"] },
    { stem: "This is the ___ question on the page. (easy)", options: ["easyest", "easiest", "easier", "most easiest"], answerIndex: 1, reasons: ["easyest 沒把子音後的 y 改成 i。", "easiest 是 easy 的正確最高級。", "easier 只表示兩者比較。", "most 與 -est 形成雙重最高級。"], reviews: ["on the page 表示從頁面多題中選一題。", "第二項用 iest 完成最高級拼字。"], cognitiveProcess: ["identify-page-question-group", "form-easiest-from-easy"], representationType: "y-ending-superlative", misconceptionTargets: ["spell-easyest"] },
    { stem: "A student writes, 'This box is biger than mine.' Which change is needed?", options: ["This → These", "is → are", "biger → bigger", "than → then"], answerIndex: 2, reasons: ["box 是單數，This 正確。", "單數主詞需保留 is。", "big 要雙寫 g 再加 -er。", "than 才是比較連接詞，then 表示時間順序。"], reviews: ["句型與單複數都正確，問題只在比較級拼字。", "第三項修復短母音加單一子音的雙寫規則。"], cognitiveProcess: ["isolate-biger-spelling-error", "repair-big-to-bigger"], representationType: "comparative-spelling-edit", misconceptionTargets: ["change-than-to-then"] },
    { stem: "Which form completes 'the ___ smile in the photo'? (nice)", options: ["niceest", "nicer", "more nice", "nicest"], answerIndex: 3, reasons: ["nice 已有 e，不能再寫完整 eest。", "nicer 是比較級，不足以表示照片中最突出。", "more nice 不是此處短形容詞最高級。", "nicest 只加 st，拼字與級別都正確。"], reviews: ["the 與 in the photo 要求最高級。", "第四項處理原字尾 e 時不重複 e。"], cognitiveProcess: ["combine-photo-range-with-nice", "append-st-to-nice"], representationType: "silent-e-superlative", misconceptionTargets: ["write-niceest"] },
    { stem: "The red box is bigger than the blue box. The blue box is bigger than the green box. The red box is the ___.", options: ["biggest", "bigger", "big", "more big"], answerIndex: 0, reasons: ["biggest 表示 red box 在三箱中尺寸最大。", "bigger 只表示比另一個大，未總結整組排序。", "big 沒有最高級標記。", "more big 不是短形容詞標準形式。"], reviews: ["兩個比較句可排出 red、blue、green 的大小順序。", "第一項用 big 的雙寫最高級形式總結 red box 的位置。"], cognitiveProcess: ["combine-two-box-size-relations", "identify-red-box-as-biggest"], representationType: "ordered-superlative-context", misconceptionTargets: ["use-comparative-after-full-ranking"] },
    { stem: "The class note says, 'Today was the happyest day.' Which spelling is correct?", options: ["happyer", "happiest", "happier", "most happyest"], answerIndex: 1, reasons: ["happyer 仍保留錯誤 y，且只是比較級。", "happiest 把 y 改 i，再加 -est。", "happier 是比較級，不能接 the 表最高程度。", "most 與 -est 重複，happyest 拼字也錯。"], reviews: ["the 與 day 的最高程度要求 -est 形式。", "第二項同時修正 y 變 i 與最高級字尾。"], cognitiveProcess: ["diagnose-happyest-in-note", "replace-with-happiest"], representationType: "superlative-proofreading", misconceptionTargets: ["fix-only-er-est-level"] },
    { stem: "The bike is ___ than the bus on this short road. (fast)", options: ["fastest", "most fast", "faster", "fastter"], answerIndex: 2, reasons: ["fastest 是最高級，不適合 bike 與 bus 兩者。", "most fast 不是短形容詞比較級。", "faster 直接加 -er，且不雙寫 t。", "fastter 不必要地雙寫 t。"], reviews: ["題目只有 bike 與 bus，than 鎖定比較級。", "第三項提醒不是每個短字都套用 CVC 雙寫。"], cognitiveProcess: ["compare-bike-and-bus-speed", "avoid-doubling-t-in-faster"], representationType: "non-cvc-comparative", misconceptionTargets: ["double-final-letter-in-fast"] },
    { stem: "At noon the air was 30°C, at three it was 35°C, and at six it was 28°C. It was ___ at three.", options: ["hot", "hotter", "most hot", "hottest"], answerIndex: 3, reasons: ["hot 只描述狀態，沒有比較三個時間。", "hotter 未指出三者中的最高溫。", "most hot 不是短形容詞標準最高級。", "35°C 是三個數值最高者，使用 hottest。"], reviews: ["三個時間與溫度可直接排序，最高值在 three。", "第四項兼具正確範圍判讀與雙寫拼字。"], cognitiveProcess: ["compare-three-time-temperatures", "label-35-degrees-as-hottest"], representationType: "temperature-superlative-transfer", misconceptionTargets: ["use-comparative-for-maximum"] },
  ]),
  ...skillQuestions("122", [
    { stem: "This map is ___ than the old one. (useful)", options: ["more useful", "most useful", "usefuller", "useful"], answerIndex: 0, reasons: ["more useful 是長形容詞 useful 的比較級，能與 than 搭配。", "most useful 是最高級，需要一個包含三者以上的範圍。", "usefuller 不是 useful 的標準比較形式。", "useful 是原級，沒有標出兩張地圖的比較。"], reviews: ["題目只比較 this map 與 the old one，因此使用比較級。", "useful 前加 more，不再加 -er。"], cognitiveProcess: ["identify-two-map-comparison", "form-more-useful-without-er"], representationType: "long-adjective-comparative-cloze", misconceptionTargets: ["attach-er-to-useful"] },
    { stem: "Of the four stories, this one is the ___. (interesting)", options: ["more interesting", "most interesting", "interest", "interestingest"], answerIndex: 1, reasons: ["more interesting 是比較級，通常需要另一個比較對象。", "most interesting 是長形容詞最高級，符合 four stories 的範圍。", "interest 是名詞或動詞，不能在此描述 story 的程度。", "interestingest 錯把長形容詞直接加 -est。"], reviews: ["of the four stories 表示從四篇中選出最高程度。", "第二項以 the most interesting 完成最高級結構。"], cognitiveProcess: ["read-four-story-range", "choose-most-interesting-for-group"], representationType: "long-adjective-superlative-cloze", misconceptionTargets: ["use-comparative-for-four-items"] },
    { stem: "The blue chair is ___ than the red chair. (comfortable)", options: ["comfortabler", "most comfortable", "more comfortable", "comfortable"], answerIndex: 2, reasons: ["comfortabler 不是 comfortable 的標準比較形式。", "most comfortable 表示群體最高級，不符合兩張椅子。", "more comfortable 是長形容詞比較級，並可接 than。", "comfortable 是原級，缺少比較標記。"], reviews: ["blue chair 與 red chair 是兩個對象。", "第三項只用 more 標記一次比較。"], cognitiveProcess: ["count-two-chair-referents", "apply-more-to-comfortable"], representationType: "comfort-comparison-cloze", misconceptionTargets: ["use-most-for-two-chairs"] },
    { stem: "This is the ___ picture in the room. (beautiful)", options: ["beautifuler", "more beautiful", "beautifulest", "most beautiful"], answerIndex: 3, reasons: ["beautifuler 錯把長形容詞直接加 -er。", "more beautiful 是比較級，不能單獨表示房內第一。", "beautifulest 不是標準最高級形式。", "most beautiful 與 in the room 共同表達群體中的最高程度。"], reviews: ["the 與 in the room 建立明確的最高級範圍。", "第四項在 beautiful 前使用 most。"], cognitiveProcess: ["connect-room-range-to-superlative", "select-most-beautiful-form"], representationType: "room-range-superlative", misconceptionTargets: ["append-est-to-beautiful"] },
    { stem: "Which sentence compares two plans without marking the comparison twice?", options: ["Plan A is more popular than Plan B.", "Plan A is popularer than Plan B.", "Plan A is more popularer than Plan B.", "Plan A is the most popular than Plan B."], answerIndex: 0, reasons: ["more popular than 只標記一次比較，且比較兩個 plans。", "popularer 不是 popular 的標準比較級。", "more 與 -er 重複標記同一個比較級。", "the most popular 是最高級，不能再接 than 比較兩者。"], reviews: ["題目同時要求長形容詞形式與兩者比較。", "第一項沒有重複的級別標記。"], cognitiveProcess: ["compare-four-popular-forms", "reject-double-and-superlative-marking"], representationType: "double-marking-sentence-check", misconceptionTargets: ["combine-more-with-er"] },
    { stem: "A note says, 'The second test was more difficulter than the first.' Which form is needed?", options: ["most difficult", "more difficult", "difficultest", "difficult"], answerIndex: 1, reasons: ["most difficult 是最高級，不符合兩次 tests 的比較。", "more difficult 保留 more 並移除多餘的 -er。", "difficultest 不是 difficult 的標準形式。", "difficult 是原級，無法與 than 完成比較。"], reviews: ["錯誤不是 than，而是同時出現 more 與 -er。", "第二項留下長形容詞需要的比較標記。"], cognitiveProcess: ["locate-double-comparative-in-note", "repair-to-more-difficult"], representationType: "long-comparative-edit", misconceptionTargets: ["preserve-doubled-comparison"] },
    { stem: "All three rules are important, but the first rule is the ___.", options: ["important", "more important", "most important", "importantest"], answerIndex: 2, reasons: ["important 只描述性質，沒有表示排序最高。", "more important 只比較兩者，沒有總結 three rules。", "most important 表示第一條在三條之中最重要。", "importantest 不是 important 的標準最高級。"], reviews: ["all three rules 明示三個比較對象。", "第三項與 the 組成長形容詞最高級。"], cognitiveProcess: ["use-three-rule-scope", "rank-first-rule-with-most-important"], representationType: "rule-priority-superlative", misconceptionTargets: ["choose-more-for-three-rules"] },
    { stem: "Of these students, Amy is the ___. (careful)", options: ["carefuler", "more careful", "carefulest", "most careful"], answerIndex: 3, reasons: ["carefuler 不是 careful 的標準比較形式。", "more careful 是比較級，未表示整組學生中的最高程度。", "carefulest 錯把 careful 直接加 -est。", "most careful 能配合 of these students 表達群體最高級。"], reviews: ["of these students 不是兩人之間的 than 比較。", "第四項在 careful 前加 most，沒有其他級別字尾。"], cognitiveProcess: ["interpret-student-set-as-group", "form-most-careful"], representationType: "care-superlative-cloze", misconceptionTargets: ["append-est-to-careful"] },
    { stem: "A bus ticket is $20, and a train ticket is $50. The train ticket is ___ than the bus ticket.", options: ["more expensive", "the most expensive", "expensiver", "more expensiver"], answerIndex: 0, reasons: ["more expensive 與題幹的 than 正確表達兩種票價的高低。", "the most expensive 是最高級，不能接 than 比較兩者。", "expensiver 不是 expensive 的標準比較級。", "more 與 -er 重複標記比較。"], reviews: ["50 大於 20，且資料只有 bus ticket 與 train ticket。", "第一項同時符合數值關係與長形容詞形式。"], cognitiveProcess: ["compare-two-ticket-prices", "express-higher-price-with-more-expensive"], representationType: "price-data-comparative", misconceptionTargets: ["use-superlative-for-two-prices"] },
    { stem: "Three paths lead home. Paths A and C have lights and few cars. Path B has no lights and many cars, so it is the ___.", options: ["more dangerous", "most dangerous", "dangerouser", "more danger"], answerIndex: 1, reasons: ["more dangerous 是比較級，未標明三條路中的最高程度。", "most dangerous 符合 three paths 與完整的安全線索。", "dangerouser 不是標準形式。", "danger 是名詞，more danger 不能直接補在 the 後描述 path。"], reviews: ["三條 paths 都有資料，B 的無燈與車多和另外兩條形成對照。", "第二項以最高級總結 Path B 在整組中的危險程度。"], cognitiveProcess: ["compare-safety-clues-for-three-paths", "choose-most-dangerous-for-path-b"], representationType: "context-evidence-superlative", misconceptionTargets: ["ignore-three-item-range"] },
    { stem: "The team won eight games this year and three last year. It was ___ this year. (successful)", options: ["successfuller", "most successful", "more successful", "successfulest"], answerIndex: 2, reasons: ["successfuller 不是 successful 的標準比較級。", "most successful 需要多個對象或時期，不是今年與去年兩者。", "more successful 能根據勝場由三場增加到八場比較前後。", "successfulest 不是標準最高級形式。"], reviews: ["this year 與 last year 是同一 team 的兩個時期。", "第三項把具體勝場差轉成長形容詞比較級。"], cognitiveProcess: ["compare-team-wins-across-years", "map-eight-versus-three-to-more-successful"], representationType: "before-after-comparative-transfer", misconceptionTargets: ["use-most-for-two-time-states"] },
    { stem: "Story A is more interesting than Story B. Story B is more interesting than Story C. Which sentence must be true?", options: ["Story C is more interesting than Story A.", "Story B is the most interesting story.", "Story A and Story C are equally interesting.", "Story A is the most interesting of the three."], answerIndex: 3, reasons: ["兩個比較句都把 Story C 排在較後，不能高於 A。", "Story B 高於 C，卻低於 A，因此不是最高。", "已知 A 高於 B、B 高於 C，A 與 C 不相等。", "A 高於 B，而 B 又高於 C，所以 A 在三篇中最高。"], reviews: ["先把兩個 than 關係合成 A > B > C。", "第四項用 most interesting 正確總結完整排序。"], cognitiveProcess: ["chain-two-story-interest-relations", "infer-a-as-group-maximum"], representationType: "long-adjective-ranking-inference", misconceptionTargets: ["read-comparisons-independently"] },
  ]),
  ...skillQuestions("123", [
    { stem: "This meal tastes ___ than the one we had yesterday. (good)", options: ["better", "best", "more good", "weller"], answerIndex: 0, reasons: ["better 是 good 的不規則比較級，能與 than 搭配。", "best 是最高級，不用於兩餐的直接比較。", "more good 不是 good 的標準比較形式。", "weller 不是此句中 good 的比較級。"], reviews: ["than 與兩餐先確定需要比較級。", "good 不加 -er，也不加 more，而要改成 better。"], cognitiveProcess: ["identify-two-meal-quality-comparison", "recall-good-to-better"], representationType: "irregular-good-comparative", misconceptionTargets: ["form-more-good"] },
    { stem: "Of the three days, Friday had the ___ weather. (bad)", options: ["worse", "worst", "baddest", "more bad"], answerIndex: 1, reasons: ["worse 是比較級，不能單獨總結 three days。", "worst 是 bad 的不規則最高級，符合三天範圍。", "baddest 不是課內標準形式。", "more bad 不是 bad 的標準比較形式。"], reviews: ["of the three days 與 the 要求最高級。", "第二項使用 bad-worse-worst 的最後一級。"], cognitiveProcess: ["read-three-day-weather-range", "select-bad-to-worst"], representationType: "irregular-bad-superlative", misconceptionTargets: ["append-est-to-bad"] },
    { stem: "The new shelf holds ___ books than the old shelf. (many)", options: ["many", "most", "more", "manyer"], answerIndex: 2, reasons: ["many 是原級，沒有和 old shelf 比較。", "most 是最高級，需要群體範圍。", "more 是 many 的不規則比較級，可修飾複數 books。", "manyer 不是標準英文形式。"], reviews: ["books 是可數複數，但 than 才是決定比較級的線索。", "第三項可同時承接 many 的變化與兩個 shelf 的比較。"], cognitiveProcess: ["link-many-books-to-than", "change-many-to-more"], representationType: "many-irregular-comparative", misconceptionTargets: ["write-manyer"] },
    { stem: "After lunch, Mia has ___ water than Ben. (little)", options: ["littler", "least", "smallest", "less"], answerIndex: 3, reasons: ["littler 通常不是用來比較不可數水量的形式。", "least 是最高級，題目只有 Mia 與 Ben。", "smallest 比較尺寸，不表示 water 的量。", "less 是 little 表示少量時的比較級。"], reviews: ["water 在此是不可數的量，且只比較兩人。", "第四項把 little 的量改成不規則比較級 less。"], cognitiveProcess: ["separate-water-amount-from-size", "choose-less-for-two-amounts"], representationType: "little-amount-comparative", misconceptionTargets: ["use-smaller-for-water-amount"] },
    { stem: "Of all the plans, Amy's plan is the ___. (good)", options: ["best", "better", "goodest", "most good"], answerIndex: 0, reasons: ["best 是 good 的不規則最高級，符合 all the plans。", "better 只表示兩者比較。", "goodest 不是標準形式。", "most good 不是此處採用的 good 最高級。"], reviews: ["of all the plans 指出 Amy 的方案要和整組比較。", "第一項不是加字尾，而是使用獨立形式 best。"], cognitiveProcess: ["use-all-plans-as-superlative-scope", "map-good-to-best"], representationType: "good-group-superlative", misconceptionTargets: ["regularize-good-as-goodest"] },
    { stem: "The road is ___ than it was yesterday. (bad)", options: ["badder", "worse", "worst", "more worse"], answerIndex: 1, reasons: ["badder 不是 bad 的標準比較級。", "worse 表示今天道路狀況比昨天差。", "worst 是最高級，題目只比較兩天。", "more worse 重複標記比較級。"], reviews: ["than 與 today/yesterday 的對照要求比較級。", "第二項使用 bad 的不規則比較形式，不另外增加 more。"], cognitiveProcess: ["read-road-condition-across-two-days", "select-worse-for-two-days"], representationType: "irregular-condition-comparative", misconceptionTargets: ["regularize-bad-as-badder"] },
    { stem: "This tank has ___ water than that tank. (much)", options: ["much", "most", "more", "many"], answerIndex: 2, reasons: ["much 是原級，沒有表達 than 所需的比較。", "most 是最高級，不符合兩個 tanks。", "more 是 much 的比較級，可修飾不可數 water。", "many 用於可數複數，不能直接修飾 water。"], reviews: ["water 決定原級用 much，不用 many；than 再把 much 改為 more。", "第三項同時符合名詞類型與比較級。"], cognitiveProcess: ["classify-water-as-uncountable", "transform-much-to-more"], representationType: "much-irregular-comparative", misconceptionTargets: ["choose-many-before-water"] },
    { stem: "The cup has 100 mL of water, and the bowl has 300 mL. The cup has ___ water.", options: ["smaller", "smallest", "least", "less"], answerIndex: 3, reasons: ["smaller 描述杯子或物體尺寸，不直接比較水量。", "smallest 是尺寸最高級，資料也只有兩個容器。", "least 是量的最高級，不能用於兩個量。", "less 正確表示 100 mL 少於 300 mL。"], reviews: ["數字比較的是容器內的 water，不是 cup 與 bowl 的大小。", "第四項把量的差異準確寫成 less water。"], cognitiveProcess: ["compare-two-water-measurements", "distinguish-less-from-smaller"], representationType: "measured-amount-comparative", misconceptionTargets: ["transfer-container-size-to-amount"] },
    { stem: "The station is ___ from here than the park. (far)", options: ["farther", "farthest", "more far", "far"], answerIndex: 0, reasons: ["farther 可用於實際距離，並與 than 搭配。", "farthest 是最高級，題目只比較兩個地點。", "more far 不是此處採用的標準比較形式。", "far 是原級，未標示 station 與 park 的距離差。"], reviews: ["station 與 park 是兩個實際地點，句子比較離 here 的距離。", "第一項使用 far 的不規則比較形式之一；本題沒有要求排除其他語境可用的 further。"], cognitiveProcess: ["identify-physical-distance-comparison", "select-farther-with-than"], representationType: "far-distance-comparative", misconceptionTargets: ["form-more-far"] },
    { stem: "A report says, 'Today's traffic was badder than yesterday's.' Which word is needed?", options: ["bad", "worse", "worst", "more bad"], answerIndex: 1, reasons: ["bad 是原級，不能完成 than 的比較。", "worse 是 bad 的正確比較級。", "worst 是最高級，需要三者以上的範圍。", "more bad 不是標準比較形式。"], reviews: ["today 與 yesterday 是兩個交通狀況。", "第二項只修正不規則變化，不改動原句的比較關係。"], cognitiveProcess: ["diagnose-badder-in-traffic-report", "replace-with-worse"], representationType: "irregular-form-proofreading", misconceptionTargets: ["keep-regular-badder"] },
    { stem: "A store sells 12 notebooks on Monday, 20 on Tuesday, and 18 on Wednesday. Which sentence matches the numbers?", options: ["Monday sells the most notebooks.", "Wednesday sells more notebooks than Tuesday.", "Tuesday sells more notebooks than Monday.", "Tuesday sells fewer notebooks than Wednesday."], answerIndex: 2, reasons: ["12 是三天中最少，不是最多。", "18 不大於 20。", "20 大於 12，因此 Tuesday 的數量比 Monday 多。", "20 不少於 18。"], reviews: ["先比較 12、20、18，再檢查每個句子的方向。", "第三項以 more notebooks 正確描述 20 與 12 的關係。"], cognitiveProcess: ["read-three-day-sales-record", "verify-more-notebooks-statement"], representationType: "count-data-irregular-comparison", misconceptionTargets: ["reverse-more-relation"] },
    { stem: "Three bottles have 600 mL, 350 mL, and 200 mL of water. The third bottle has the ___.", options: ["smaller water", "less water", "smallest water", "least water"], answerIndex: 3, reasons: ["smaller 描述尺寸，不是三瓶水量的最高級。", "less 是比較級，不能總結三個水量。", "smallest water 不是表示不可數水量最少的標準搭配。", "least water 表示 200 mL 是三個量中的最少。"], reviews: ["600、350、200 中的最低值是第三瓶。", "第四項使用 little-less-least 的最高級形式描述水量。"], cognitiveProcess: ["rank-three-water-volumes", "express-minimum-with-least-water"], representationType: "volume-minimum-superlative", misconceptionTargets: ["use-smallest-for-amount"] },
  ]),
  ...skillQuestions("124", [
    { stem: "Mia is taller than Nora. Which sentence says the same thing about their height?", options: ["Nora is shorter than Mia.", "Nora is taller than Mia.", "Mia and Nora are equally tall.", "Mia is the tallest student in school."], answerIndex: 0, reasons: ["若 Mia 較高，從 Nora 的方向看就是 Nora 較矮。", "此項把原本的高低順序顛倒。", "taller than 已表示兩人不等高。", "原句只比較兩人，不能推論全校最高。"], reviews: ["把 A taller than B 反向表達時，要同時交換人物與形容詞方向。", "第一項保留相同的身高關係，也沒有擴大比較範圍。"], cognitiveProcess: ["reverse-taller-than-with-opposite-adjective", "preserve-mia-nora-height-order"], representationType: "than-relation-equivalence", misconceptionTargets: ["reverse-names-without-reversing-adjective"] },
    { stem: "This chair is more comfortable ___ the old one.", options: ["as", "than", "of", "from"], answerIndex: 1, reasons: ["as 需要 as...as 的同等結構，不能接在比較級後。", "than 正確連接 more comfortable 與 the old one。", "of 常標示最高級範圍，不接比較級的另一對象。", "from 表示來源或分離，不建立程度比較。"], reviews: ["more comfortable 已完成比較級，空格要連接第二張 chair。", "第二項形成完整的 comparative + than 結構。"], cognitiveProcess: ["locate-connector-after-long-comparative", "choose-than-before-old-one"], representationType: "than-connector-cloze", misconceptionTargets: ["place-as-after-comparative"] },
    { stem: "Mia's bag is heavier than ___.", options: ["Nora", "Nora bag", "Nora's", "Noras"], answerIndex: 2, reasons: ["Nora 會使句子表面上把 bag 與人比較。", "Nora bag 缺少所有格形式。", "Nora's 代替 Nora's bag，使兩邊都比較袋子。", "Noras 不是 Nora 的所有格。"], reviews: ["than 前是 Mia's bag，後面也應代表另一個 bag。", "第三項省略重複名詞但保留相同類型。"], cognitiveProcess: ["match-bag-with-bag-after-than", "use-possessive-substitution-noras"], representationType: "possessive-comparison-completion", misconceptionTargets: ["compare-object-with-person"] },
    { stem: "Grace is three months ___ than Amy. (young)", options: ["young", "youngest", "more young", "younger"], answerIndex: 3, reasons: ["young 是原級，不能接在差額與 than 之間。", "youngest 是最高級，不描述兩人的年齡差。", "more young 不是 young 的標準比較級。", "younger 與 three months、than 共同表示 Grace 小三個月。"], reviews: ["three months 是比較差額，不會取代比較級。", "第四項把差額放在 younger 前，語意完整。"], cognitiveProcess: ["interpret-three-months-as-age-gap", "place-younger-before-than"], representationType: "age-difference-comparative", misconceptionTargets: ["omit-comparative-after-difference"] },
    { stem: "Which sentence compares how long two pencils are?", options: ["The blue pencil is longer than the red pencil.", "The blue pencil is longer than Mia.", "The blue pencil is the longest than the red pencil.", "The blue pencil is long than the red pencil."], answerIndex: 0, reasons: ["兩邊都是 pencils，且 longer than 正確比較長度。", "此句把 pencil 與人 Mia 比較，類型不一致。", "longest 是最高級，不能和 than 搭配比較兩枝。", "long 是原級，不能直接接 than。"], reviews: ["題目指定比較兩枝 pencil 有多長，因此兩側對象必須相同類型。", "第一項沒有省略造成的歧義，也只標記一次比較級。"], cognitiveProcess: ["check-comparison-object-types", "select-pencil-to-pencil-length-sentence"], representationType: "same-type-comparison-selection", misconceptionTargets: ["compare-pencil-with-person"] },
    { stem: "A student writes, 'The white wall is more taller than the gray wall.' Which form is needed?", options: ["most tall", "taller", "more tallest", "tall"], answerIndex: 1, reasons: ["most tall 不是 tall 的標準最高級。", "taller 已包含比較級，不需再加 more。", "more 與 tallest 混合比較級和最高級。", "tall 是原級，不能完成 than 結構。"], reviews: ["原句的兩面牆與 than 都正確，錯在雙重比較標記。", "第二項刪除 more 後保留必要的 -er。"], cognitiveProcess: ["isolate-more-taller-error", "retain-single-comparative-marker"], representationType: "double-comparative-repair", misconceptionTargets: ["keep-more-before-taller"] },
    { stem: "The blue box is larger than the red box. What do we know?", options: ["The blue box is heavier.", "The red box costs less.", "The blue box has a greater size.", "The red box is older."], answerIndex: 2, reasons: ["larger 沒有提供重量資料。", "句子沒有提到價格。", "larger 只足以確定 blue box 的尺寸較大。", "句子沒有提供兩個箱子的年代。"], reviews: ["比較級只保證它明確指出的屬性。", "第三項把 larger 改述為 greater size，沒有加入重量、價格或年代。"], cognitiveProcess: ["limit-inference-to-size-property", "paraphrase-larger-as-greater-size"], representationType: "comparison-inference-boundary", misconceptionTargets: ["infer-weight-from-size"] },
    { stem: "The north road is 8 km long, and the south road is 5 km long. The north road is ___.", options: ["longest", "more long", "long", "longer"], answerIndex: 3, reasons: ["longest 是最高級，資料只有兩條道路。", "more long 不是 long 的標準比較級。", "long 只描述長，沒有表達 8 與 5 的差異。", "longer 正確表示 8 km 大於 5 km。"], reviews: ["兩個數值與兩條 roads 只需要比較級。", "第四項的方向和 8 > 5 一致。"], cognitiveProcess: ["compare-two-route-lengths", "express-eight-km-as-longer"], representationType: "distance-data-comparative", misconceptionTargets: ["use-longest-for-two-routes"] },
    { stem: "Mia's room is cleaner than Nora. Which change compares two rooms?", options: ["Mia's room is cleaner than Nora's.", "Mia is cleaner than Nora's room.", "Mia's room is the cleanest than Nora.", "Mia's room is clean than Nora's."], answerIndex: 0, reasons: ["Nora's 代替 Nora's room，使兩側都是 rooms。", "此句反而把 Mia 這個人與 room 比較。", "cleanest 不能接 than 比較兩個房間。", "clean 是原級，不能直接搭配 than。"], reviews: ["原句的問題不是 cleaner，而是 than 後只留下人名。", "第一項用所有格省略重複的 room，仍維持清楚對應。"], cognitiveProcess: ["diagnose-unlike-room-person-comparison", "revise-with-noras-room-substitution"], representationType: "comparison-reference-repair", misconceptionTargets: ["repair-by-changing-comparative"] },
    { stem: "Leo is 15 years old, and Sam is 13. Leo is ___ years older than Sam.", options: ["one", "two", "three", "four"], answerIndex: 1, reasons: ["15 - 13 不是 1。", "15 - 13 = 2，所以年齡差是 two years。", "three 會把 Sam 的年齡誤讀為 12。", "four 不符合題目給的兩個年齡。"], reviews: ["older than 前的數量要寫兩人實際差額。", "第二項由 15 與 13 相減得到，不只是依人物順序猜測。"], cognitiveProcess: ["subtract-two-person-ages", "insert-two-before-years-older"], representationType: "age-gap-calculation", misconceptionTargets: ["guess-age-gap-without-subtraction"] },
    { stem: "Bag A has a weight of 8 kg, and Bag B has a weight of 3 kg. Bag A is ___ Bag B.", options: ["very heavier than", "much heaviest than", "much heavier than", "more heavy than"], answerIndex: 2, reasons: ["very 不能直接修飾比較級 heavier。", "heaviest 是最高級，也不能接 than 比較兩袋。", "much 可加強 heavier，並正確連接 Bag B。", "heavy 在本單元使用規則比較級 heavier，不用 more heavy。"], reviews: ["8 kg 與 3 kg 表示明顯的兩者重量差。", "第三項用 much 表示差距大，但比較級核心仍是 heavier than。"], cognitiveProcess: ["interpret-weight-gap-between-bags", "use-much-to-modify-heavier"], representationType: "comparative-degree-modifier", misconceptionTargets: ["use-very-before-comparative"] },
    { stem: "Road A takes 20 minutes. Road B takes 35 minutes. Which sentence is true?", options: ["Road A takes 15 minutes longer than Road B.", "Road B is the longest of the two roads.", "Road A and Road B take the same time.", "Road B takes 15 minutes longer than Road A."], answerIndex: 3, reasons: ["20 比 35 少 15，方向相反。", "兩個時間應用比較級；longest 也不直接描述此處所花時間。", "20 與 35 不相等。", "35 - 20 = 15，且 Road B 花的時間較長。"], reviews: ["先算時間差 15，再確認 longer than 的方向。", "第四項同時保留正確差額與比較對象順序。"], cognitiveProcess: ["subtract-route-times", "align-longer-than-direction-with-35-minutes"], representationType: "time-difference-transfer", misconceptionTargets: ["reverse-difference-direction"] },
  ]),
  ...skillQuestions("125", [
    { stem: "The two boxes are 6 kg each. The red box is ___ the blue box.", options: ["as heavy as", "as heavier as", "heavier as", "as heaviest as"], answerIndex: 0, reasons: ["as heavy as 使用原級 heavy，正確表達重量相同。", "as...as 中不能放比較級 heavier。", "heavier 需要 than，不與單一 as 搭配。", "最高級 heaviest 不能放在 as...as 中。"], reviews: ["兩個 6 kg 表示同等，不是高低差。", "第一項保留 heavy 原級並完整使用兩個 as。"], cognitiveProcess: ["recognize-equal-six-kilogram-weights", "form-as-heavy-as"], representationType: "equal-weight-as-as-cloze", misconceptionTargets: ["insert-comparative-between-as"] },
    { stem: "The bus is not as fast as the train. What does the sentence mean?", options: ["The bus and the train have the same speed.", "The train is faster than the bus.", "The bus is faster than the train.", "The train is the fastest way to travel."], answerIndex: 1, reasons: ["not as fast as 表示速度不相等。", "公車沒有火車那麼快，因此火車較快。", "此項把比較方向顛倒。", "原句只比較 bus 與 train，不能推論所有交通方式。"], reviews: ["先去除 not 會是同等；加入 not 後，前者未達後者程度。", "第二項只轉換同一個兩者關係，沒有擴大範圍。"], cognitiveProcess: ["interpret-negative-equality-pattern", "reverse-to-train-faster-than-bus"], representationType: "not-as-as-meaning", misconceptionTargets: ["read-not-as-as-as-equal"] },
    { stem: "Amy has four notebooks, and Ben also has four. Amy has ___ Ben.", options: ["as much notebooks as", "more notebooks as", "as many notebooks as", "as many notebook than"], answerIndex: 2, reasons: ["notebooks 是可數複數，不能用 much。", "more 應與 than 搭配，也不表示數量相同。", "as many notebooks as 正確表達兩人各有四本。", "notebook 應為複數，as...as 也不能改成 than。"], reviews: ["四本與四本是可數名詞的同量關係。", "第三項使用 many 並保留複數 notebooks。"], cognitiveProcess: ["classify-notebooks-as-countable", "build-as-many-notebooks-as"], representationType: "equal-count-as-many-as", misconceptionTargets: ["use-much-with-count-noun"] },
    { stem: "Each bottle has 500 mL of water. Bottle A has ___ Bottle B.", options: ["as many water as", "as more water as", "as much waters as", "as much water as"], answerIndex: 3, reasons: ["water 是不可數名詞，不用 many。", "more 表示比較差異，不能放在同等結構中。", "water 在此不加複數 s。", "as much water as 正確表示兩瓶水量相同。"], reviews: ["500 mL 與 500 mL 建立相等的不可數量。", "第四項選 much，且 water 保持不可數形式。"], cognitiveProcess: ["read-equal-bottle-volumes", "apply-as-much-water-as"], representationType: "equal-mass-as-much-as", misconceptionTargets: ["pluralize-water-in-quantity-phrase"] },
    { stem: "Mia and Nora are both 13 years old. Which sentence matches?", options: ["Mia is as old as Nora.", "Mia is as older as Nora.", "Mia is older as Nora.", "Mia is the oldest as Nora."], answerIndex: 0, reasons: ["as old as 使用原級，符合兩人同為 13 歲。", "older 是比較級，不能放在兩個 as 之間。", "older 應接 than，而且會表示年齡不同。", "oldest 是最高級，不能與 as Nora 連接。"], reviews: ["相同年齡需要同等比較，不是比較級或最高級。", "第一項把 old 保持原級，語意與數值一致。"], cognitiveProcess: ["match-equal-ages-to-equality", "choose-base-old-between-as"], representationType: "age-equality-sentence-selection", misconceptionTargets: ["use-older-for-equal-age"] },
    { stem: "A student writes, 'This tree is as taller as that tree.' Which form is needed?", options: ["taller than", "as tall as", "the tallest of", "as tallest as"], answerIndex: 1, reasons: ["taller than 表示一棵較高，改變原句要表達的同等關係。", "as tall as 保留兩個 as，並把形容詞改回原級。", "the tallest of 是最高級片語，不能直接接 that tree。", "最高級 tallest 不能放在 as...as 中。"], reviews: ["原句已有完整的同等框架，錯在中間用了 taller。", "第二項只修正級別，不把同等改成高低比較。"], cognitiveProcess: ["diagnose-comparative-inside-as-as", "repair-with-base-tall"], representationType: "as-as-form-edit", misconceptionTargets: ["replace-equality-with-than"] },
    { stem: "The blue bag is as heavy as the red bag. What do we know?", options: ["The blue bag is larger.", "The red bag costs more.", "The two bags have the same weight.", "The two bags hold the same number of books."], answerIndex: 2, reasons: ["heavy 的同等關係不提供尺寸資料。", "as heavy as 沒有比較兩個 bags 的售價。", "as heavy as 明確表示兩袋重量相同。", "相同重量不代表裝有相同數量的書。"], reviews: ["as...as 只保證中間形容詞所指的屬性相同。", "第三項保留 weight 這個已知屬性，沒有加入其他推測。"], cognitiveProcess: ["restrict-as-heavy-as-inference", "identify-equal-weight-only"], representationType: "equality-inference-boundary", misconceptionTargets: ["infer-size-or-content-from-weight"] },
    { stem: "The north road is 4 m wide, and the south road is 6 m wide. The north road is ___ the south road.", options: ["as wide as", "wider than", "the widest of", "not as wide as"], answerIndex: 3, reasons: ["4 m 與 6 m 不相等，不能用 as wide as。", "4 小於 6，north 不是較寬者。", "資料只有兩條路，且 north 並非最高。", "4 m 未達 6 m，因此 not as wide as 符合數據。"], reviews: ["先比較 4 與 6，再決定前者是否達到後者的寬度。", "第四項把較小數值寫成負向同等結構。"], cognitiveProcess: ["compare-four-and-six-meter-widths", "construct-not-as-wide-as-from-data"], representationType: "negative-equality-from-measurement", misconceptionTargets: ["reverse-width-data-direction"] },
    { stem: "Trains A and B travel the same 20 km road, and both take 40 minutes. Which sentence is true?", options: ["Train A is as fast as Train B on this trip.", "Train A is faster than Train B.", "Train B is the fastest train.", "Train A is not as fast as Train B."], answerIndex: 0, reasons: ["相同距離與時間支持兩車在此趟的速度表現相同。", "兩車距離與時間都相同，沒有較快的依據。", "資料只含兩列車，不能判定所有列車中的最高級。", "not as fast as 與相同距離、時間的資料衝突。"], reviews: ["相同 20 km 且同為 40 minutes，才足以比較出同速。", "第一項用 on this trip 限定結論，不擴大成列車的一般性能。"], cognitiveProcess: ["compare-equal-trip-times", "state-trip-specific-speed-equality"], representationType: "equal-time-transfer", misconceptionTargets: ["infer-permanent-speed-ranking"] },
    { stem: "The green trip takes ___ time as the yellow trip.", options: ["as many", "as much", "so many", "more much"], answerIndex: 1, reasons: ["time 在此表示不可數的時間量，不用 many。", "as much 與後面的 as 組成不可數同量結構。", "so many 不適合修飾不可數 time，也不完成同等結構。", "more much 不是正確的數量片語。"], reviews: ["空格後已有 time as，因此要補前半部 as much。", "第二項用新的不可數情境檢查 much，不重複 water 題面。"], cognitiveProcess: ["classify-trip-time-as-uncountable", "supply-as-much-before-time"], representationType: "as-much-partial-cloze", misconceptionTargets: ["choose-many-before-time"] },
    { stem: "Room A seats 30 students, and Room B also seats 30. Which sentence matches the notice?", options: ["Room A can seat more students than Room B.", "Room B can seat the most students.", "Room A can seat as many students as Room B.", "Room A cannot seat as much students as Room B."], answerIndex: 2, reasons: ["30 不大於 30。", "資料只有兩個 rooms，也沒有顯示 B 較多。", "兩室各 30 位，as many students as 正確表示同量。", "students 是可數複數，不能用 much；cannot 也與資料不符。"], reviews: ["seat 數相等，而且 students 是可數名詞。", "第三項把 notice 的兩個數字轉成正確同量句。"], cognitiveProcess: ["compare-room-seat-capacities", "express-equal-count-with-as-many"], representationType: "capacity-notice-equality", misconceptionTargets: ["use-much-with-students"] },
    { stem: "Nora runs 2 km in 12 minutes. Mia runs 2 km in 10 minutes. Which sentence matches the times?", options: ["Nora is as fast as Mia.", "Mia is not as fast as Nora.", "Nora is faster than Mia.", "Nora is not as fast as Mia."], answerIndex: 3, reasons: ["相同距離下用時不同，速度不相同。", "Mia 用時較少，因此不是較慢者。", "Nora 用時較多，不能判為較快。", "相同 2 km 下，Nora 花 12 分鐘而 Mia 花 10 分鐘，所以 Nora 較慢。"], reviews: ["比較相同距離所需時間：時間較少者較快。", "第四項以 not as fast as 表達 Nora 未達 Mia 的速度。"], cognitiveProcess: ["compare-times-for-equal-distance", "translate-slower-runner-to-not-as-fast"], representationType: "rate-data-negative-equality", misconceptionTargets: ["treat-longer-time-as-faster"] },
  ]),
  ...skillQuestions("126", [
    { stem: "Leo is 180 cm tall, and Ben is 170 cm tall. Which sentence matches?", options: ["Leo is taller than Ben.", "Leo is the tallest of the two boys.", "Ben is taller than Leo.", "Leo and Ben are equally tall."], answerIndex: 0, reasons: ["180 cm 大於 170 cm，兩人用 taller than 表達。", "兩個對象通常使用比較級，不以 of the two 硬套最高級。", "此項把數值大小方向顛倒。", "180 與 170 不相等。"], reviews: ["本題同時限定兩個人並提供實際身高。", "第一項從數值推出比較級，不只是辨認 than 字樣。"], cognitiveProcess: ["compare-two-height-measurements", "choose-comparative-for-two-boys"], representationType: "two-versus-group-comparative", misconceptionTargets: ["use-superlative-for-two-people"] },
    { stem: "Nora is the ___ student in her class. (tall)", options: ["taller", "tallest", "more tall", "most taller"], answerIndex: 1, reasons: ["taller 是比較級，通常需要 than 後的另一人。", "tallest 表示 Nora 在全班身高中最高。", "more tall 不是標準短形容詞形式。", "most 與 taller 混合兩種級別標記。"], reviews: ["in her class 提供包含多人的最高級範圍。", "第二項與 the 組成 the tallest student。"], cognitiveProcess: ["identify-class-as-comparison-group", "select-tallest-with-in-range"], representationType: "group-height-superlative", misconceptionTargets: ["use-comparative-with-class-range"] },
    { stem: "Five tools were tested. This tool worked better than each of the other four. It was the ___. (useful)", options: ["usefuller", "more useful", "most useful", "usefulest"], answerIndex: 2, reasons: ["usefuller 不是 useful 的標準比較級。", "more useful 只保留單次兩者比較，未總結五件工具。", "most useful 把高於其餘四件的關係總結成群體最高級。", "usefulest 不是標準形式。"], reviews: ["each of the other four 表示此 tool 已逐一高於其餘成員。", "第三項把多個比較關係合成五件中的最高程度。"], cognitiveProcess: ["combine-tool-over-four-relations", "summarize-as-most-useful"], representationType: "comparative-evidence-to-long-superlative", misconceptionTargets: ["stop-at-more-useful"] },
    { stem: "This is one of the ___ ideas in the book. (good)", options: ["better", "goodest", "most good", "best"], answerIndex: 3, reasons: ["better 是比較級，不能接在 one of the 後表示群體成員。", "goodest 不是 good 的標準最高級。", "most good 不是此處的標準形式。", "best 是 good 的最高級，形成 one of the best ideas。"], reviews: ["one of the 表示這個 idea 是高程度群體中的一個。", "第四項後面的 ideas 保持複數，結構才完整。"], cognitiveProcess: ["interpret-idea-as-one-member-of-group", "insert-irregular-best-before-ideas"], representationType: "one-of-superlative-cloze", misconceptionTargets: ["use-comparative-after-one-of-the"] },
    { stem: "Leo is my ___ friend.", options: ["best", "the best", "better", "most good"], answerIndex: 0, reasons: ["best 可直接接在所有格 my 後。", "my 已限定 friend，不能再疊加 the。", "better 是比較級，未說明與誰比較。", "most good 不是 good 的標準最高級。"], reviews: ["最高級常見 the，但所有格 my 已占限定詞位置。", "第一項形成 my best friend，而不是 my the best friend。"], cognitiveProcess: ["recognize-possessive-before-superlative", "omit-the-after-my"], representationType: "possessive-superlative-determiner", misconceptionTargets: ["always-add-the-before-best"] },
    { stem: "Leo is the tallest ___ the three boys.", options: ["in", "of", "than", "from"], answerIndex: 1, reasons: ["in 通常接場所或群體名詞，如 in the class，不直接接 the three boys。", "of 可接明列的三個對象，形成 of the three boys。", "than 與比較級搭配，不接 tallest。", "from 不用來標示最高級比較範圍。"], reviews: ["the three boys 是列舉出的比較集合。", "第二項用 of 把 Leo 放回這個三人範圍。"], cognitiveProcess: ["classify-explicit-three-person-range", "choose-of-before-the-three-boys"], representationType: "superlative-range-preposition", misconceptionTargets: ["use-than-after-superlative"] },
    { stem: "Bag A is 8 kg, Bag B is 12 kg, and Bag C is 10 kg. Which sentence matches?", options: ["Bag A is the heaviest.", "Bag C is heavier than Bag B.", "Bag B is the heaviest.", "Bag A and Bag C are equally heavy."], answerIndex: 2, reasons: ["8 kg 是三袋中最輕，不是最重。", "10 kg 不大於 12 kg。", "12 kg 是最高重量，所以 Bag B 最重。", "8 kg 與 10 kg 不相等。"], reviews: ["將 8、12、10 排序後，最大值對應 Bag B。", "第三項使用 heaviest 總結三個重量。"], cognitiveProcess: ["rank-three-bag-weights", "map-maximum-weight-to-bag-b"], representationType: "three-item-weight-superlative", misconceptionTargets: ["choose-last-mentioned-bag"] },
    { stem: "This is one of the most popular ___ at school.", options: ["club", "club's", "clubbing", "clubs"], answerIndex: 3, reasons: ["one of the 後要從一群事物中選一個，名詞需複數。", "club's 是所有格，後面還需要被修飾的名詞。", "clubbing 不是此處表示社團群體的名詞形式。", "clubs 是複數，完成 one of the most popular clubs。"], reviews: ["one 表示其中一個，但 of 後的集合必須包含多個成員。", "第四項的複數不是說 this 有多個，而是說它屬於 clubs 這個群體。"], cognitiveProcess: ["separate-one-member-from-plural-group", "select-clubs-after-one-of"], representationType: "one-of-plural-noun", misconceptionTargets: ["use-singular-after-one-of"] },
    { stem: "Sam, Leo, and Ben ran the same 2 km road. Sam finished in 12 minutes, Leo in 10, and Ben in 14. Who was the fastest?", options: ["Leo", "Sam", "Ben", "They were equally fast."], answerIndex: 0, reasons: ["相同 2 km 中，Leo 的 10 minutes 最少，因此最快。", "Sam 的 12 minutes 比 Leo 多。", "Ben 的 14 minutes 是三人中最多。", "三個完成時間不同，速度表現不相同。"], reviews: ["距離相同時，完成時間越短代表速度越快。", "第一項把最低時間正確對應到最高級 fastest。"], cognitiveProcess: ["rank-three-times-for-equal-distance", "identify-leo-as-fastest"], representationType: "minimum-time-maximum-speed", misconceptionTargets: ["treat-largest-time-as-fastest"] },
    { stem: "The yellow box is the largest of the three boxes. What do we still need to know?", options: ["Which box has the greatest size", "Which box is the heaviest", "How many boxes are compared", "Whether the yellow box is larger than the other two"], answerIndex: 1, reasons: ["largest 已指出 yellow box 的尺寸最大。", "尺寸最大不一定重量最大，句中沒有重量資料。", "of the three boxes 已指出共比較三箱。", "最高級 largest 已表示它大於另外兩箱。"], reviews: ["最高級也只能保證它所描述的屬性。", "第二項要求 weight，超出 largest 提供的 size 資訊。"], cognitiveProcess: ["separate-largest-size-from-weight", "identify-unanswered-heaviest-question"], representationType: "superlative-inference-boundary", misconceptionTargets: ["infer-weight-from-largest-size"] },
    { stem: "Nora ran faster than Mia and Amy. Nora was ___.", options: ["faster of the three", "the faster than the three", "the fastest of the three", "the most fast of the three"], answerIndex: 2, reasons: ["faster 是比較級，不能用 of the three 總結三人。", "the faster than the three 混合了不相容的結構。", "the fastest of the three 正確總結 Nora 高於另外兩人。", "most fast 不是 fast 的標準最高級。"], reviews: ["兩個 faster than 關係共同涵蓋 Mia 與 Amy。", "第三項把三人範圍改寫為明確最高級。"], cognitiveProcess: ["combine-nora-over-two-runners", "rewrite-as-fastest-of-three"], representationType: "comparative-to-superlative-rewrite", misconceptionTargets: ["retain-comparative-with-of-three"] },
    { stem: "Road A is 4 km, Road B is 7 km, and Road C is 5 km. Which sentence is true?", options: ["Road A is longer than Road C.", "Road C is the longest road.", "Road B is longer than both roads, but not the longest.", "Road B is the longest of the three roads."], answerIndex: 3, reasons: ["4 km 不大於 5 km。", "5 km 不是三個距離的最大值。", "若 B 長於另外兩條，它就是三者中最長，後半句矛盾。", "7 km 大於 4 km 與 5 km，所以 B 最長。"], reviews: ["比較三個距離 4、7、5，最大值是 7。", "第四項同時使用正確對象、最高級與 of the three 範圍。"], cognitiveProcess: ["rank-three-route-distances", "validate-longest-of-three-statement"], representationType: "route-table-superlative-transfer", misconceptionTargets: ["deny-superlative-after-two-comparisons"] },
  ]),
];

export const ENGLISH_U18_VOCABULARY_POLICY = Object.freeze({
  capQuestionBasis: "appendix-5-table-1",
  additionalLearningTerms: ["compare", "complete", "danger", "describe", "direct", "equal", "form", "goodness", "match", "path", "pleasant", "shelf", "speed", "tank", "tire", "travel", "weight"],
  properNames: ["Amy", "Ben", "Grace", "Jack", "Leo", "Mia", "Nora", "Sam", "Wendy"],
  grammarNotation: ["A", "B", "adjective", "as", "bigger", "biggest", "cm", "comparative", "comparison", "easier", "easiest", "eest", "er", "est", "farther", "farthest", "further", "furthest", "g", "happier", "happiest", "heavier", "heaviest", "hotter", "hottest", "kg", "km", "larger", "largest", "ly", "mL", "nicer", "nicest", "noun", "plural", "st", "superlative", "than", "wider", "widest", "worse", "worst", "y"],
  malformedDistractors: ["badder", "baddest", "comfortabler", "expensiver", "fastter", "littler", "noras", "popularer", "sams", "successfuller", "usefuller"],
});

export const ENGLISH_U18_SOURCE = Object.freeze({ unitId: UNIT_ID, lectures: ENGLISH_U18_LECTURES, questions: ENGLISH_U18_QUESTIONS, vocabularyPolicy: ENGLISH_U18_VOCABULARY_POLICY });
export const ENGLISH_UNIT_SOURCE = ENGLISH_U18_SOURCE;
