import { defineEnglishUnit } from "../define-unit.mjs";

const skills = [
  {
    id: "ENG_R4_S237", process: "resolve-pronoun-antecedent", evidence: "代名詞的數量、類型與後續動作",
    objectives: ["找出 he、she、it、they 等形式可回指的前文對象。", "以後句動作確認先行詞，不採最近名詞捷徑。", "說明被排除對象在哪一項特徵上衝突。"],
    sections: [
      ["先讀代名詞本身", "he、she 通常指單一人物，it 指單一事物，they 指複數。先用人或物、單數或複數縮小候選，再看後面的動作由誰做才合理。"],
      ["事件也能被指涉", "it 或 this 有時不只代替一個名詞，而是代替前句整件事。若後文說 this surprised everyone，應問造成驚訝的是哪個事件，而非硬找最近的單數名詞。"],
      ["建立候選清單", "把代名詞前可見的人物、物件與事件列出；逐一檢查數量、句法角色與常識。只有三項證據都通過者才保留。"],
      ["遇到真正歧義", "如果兩個候選在形式與意思上都合理，負責任的結論是原句不清楚。考題若要求唯一答案，必須另有後文線索解除歧義。"],
    ],
    examples: [
      ["A dog followed two boys. They stopped at the gate.", ["They 是複數。", "候選有 two boys。", "停在門口是兩位男孩的動作。"], "They = the two boys.", "數量與事件角色一致。"],
      ["Mia lost her key. It made her late.", ["It 可指單數物件或事件。", "鑰匙本身不直接使人遲到。", "遺失鑰匙這件事造成遲到。"], "It = losing the key.", "因果關係要求把整個事件當先行內容。"],
      ["Leo put the cup by the plate because it was wet.", ["cup 與 plate 都是單數物件。", "兩者都可能是 wet。", "沒有後文排除任一個。"], "The reference is unclear.", "形式與語意都留下兩個候選，不能自行假定最近者。"],
    ],
    misconceptions: [
      ["永遠選離代名詞最近的名詞。", "最近者可能數量不合或做不了後續動作。", "逐項檢查形式與事件角色。"],
      ["it 只能指物品。", "it 也能概括前句事件。", "看後文是在描述物件，還是評論整件事。"],
      ["they 只能指人。", "複數事物也能用 they。", "以數量為主要形式線索。"],
      ["題目一定清楚，所以可以硬猜。", "有些句子本來就歧義。", "只有出現足以排除其他候選的證據才下結論。"],
    ],
    checks: [
      ["two boxes 應以哪個主格代名詞承接？", "they", "先行詞為複數事物。"],
      ["This made us happy 中 This 可能指什麼？", "前文事件", "This 可概括剛敘述的整件事。"],
      ["兩個單數候選都合理時應怎麼辦？", "判定指涉不清", "不能用距離製造原文沒有的確定性。"],
    ],
    questions: [
      ["Nora opened a box and found three letters. They were from her old friends. What does They refer to?", ["the box", "three letters", "Nora", "old friends"], 1, "They 為複數主詞，且能合理帶有寄件來源，指 three letters。", ["box 是單數，應以 it 承接。", "Nora 是單一人物，應以 she 承接。", "friends 是寄件者，不是 from her old friends 的主詞。"], "short-paragraph-reference", "match-plural-object-and-source", "choose-nearest-plural"],
      ["Ben missed the last bus. This forced him to walk home. What does This mean?", ["Ben", "the last bus", "missing the last bus", "Ben's home"], 2, "被迫走路的原因是錯過末班車整件事。", ["Ben 是被迫走路的人，不是原因事件。", "公車本身不是被錯過這個結果的完整表達。", "home 是目的地，不能造成步行。"], "event-reference", "resolve-this-as-event", "force-this-to-nearest-noun"],
      ["A truck passed two bikes. It turned left at the next light. What can It refer to by grammar alone?", ["only the truck", "only the bikes", "the truck, but meaning must still be checked", "the next light"], 2, "It 是單數，形式上可指 truck；仍須用語意確認。", ["只說 only the truck 忽略還需語意核對。", "bikes 是複數，應用 they。", "light 尚在代名詞之後，不能成為前文先行詞。"], "grammar-first-reference", "use-number-before-semantics", "claim-form-alone-proves-meaning"],
      ["Eva bought a plant for her room. It needed little light, which was perfect for the room. What needed little light?", ["Eva", "the plant", "the room", "the act of buying"], 1, "plant 是單數物件，且植物有光照需求。", ["Eva 是人物，不以 little light 描述需求。", "room 是後面評價適合的地點，不是需要光的主體。", "購買事件不會需要光。"], "descriptive-reference", "combine-number-and-world-knowledge", "bind-it-to-location"],
      ["The red cups were beside a white bowl. They were still warm. What does They refer to?", ["the cups", "the bowl", "the color white", "the table"], 0, "They 是複數，唯一已出現的複數候選為 cups。", ["bowl 是單數，應用 it。", "white 是顏色描述，不是複數物件。", "table 未在原文出現。"], "number-reference", "select-only-plural-antecedent", "prefer-nearest-singular"],
      ["Jay told Leo that the door was open. He then went back to close it. Which statement is safest?", ["He must be Jay", "He must be Leo", "He could be Jay or Leo without more context", "He means the door"], 2, "Jay 與 Leo 都是單數男性且都可能回去關門，資訊不足。", ["原文沒有證據排除 Leo。", "原文沒有證據排除 Jay。", "door 是事物，應以 it 而非 He 指稱。"], "ambiguity-judgment", "recognize-two-valid-human-candidates", "always-select-subject"],
      ["Amy placed the cookies on two plates and carried them outside. What did she carry?", ["Amy", "the cookies", "the plates only", "either the cookies or the plates; the sentence is unclear"], 3, "them 可回指複數 cookies 或 plates，兩者都能被搬到外面。", ["Amy 是動作者，不是 them。", "cookies 合理但 plates 也合理，不能稱為唯一。", "plates 合理但 cookies 也合理，不能稱為唯一。"], "ambiguous-object-reference", "retain-both-plural-candidates", "pick-nearest-plural"],
      ["The class won the city contest. It surprised even their teacher. What caused the surprise?", ["the city", "the teacher", "the class's winning", "the contest building"], 2, "surprised 評論的是全班獲勝這件事。", ["city 只是比賽範圍。", "teacher 是感到驚訝的人。", "原文沒有比賽建築物。"], "event-cause-reference", "map-it-to-proposition", "search-only-for-noun"],
      ["Sam put the fish into a clean tank. It swam behind a rock at once. What does It refer to?", ["Sam", "the fish", "the tank", "the rock"], 1, "能 swim 的單數動物是 fish。", ["Sam 是人物，應以 he 指稱。", "tank 不能游泳。", "rock 在代名詞後才出現且不能游泳。"], "action-compatibility-reference", "use-verb-to-identify-antecedent", "use-nearest-object"],
      ["A note was under the books. They covered most of it. What do They and it refer to?", ["They=books; it=note", "They=note; it=books", "They=books; it=table", "They=notes; it=book"], 0, "They 承接複數 books，it 承接單數 note，且書能蓋住紙條。", ["note 是單數不能配 They，books 是複數不能配 it。", "table 未出現，it 有明確單數 note。", "原文只有一張 note 且有複數 books，形式全反。"], "dual-pronoun-reference", "resolve-two-linked-pronouns", "resolve-pronouns-independently-without-action"],
      ["Mia said, 'I will call you,' to Nora. Later, she did. Who made the call?", ["Mia", "Nora", "both of them", "the sentence gives no clue"], 0, "did 代替 call，且承接引號中由 Mia 作出的 I will call you 承諾。", ["Nora 是被告知與接聽的對象。", "承諾中的主詞 I 只有 Mia。", "引號中的 I 與後文 did 提供足夠線索。"], "dialogue-reference", "track-speaker-and-substitution", "bind-she-to-nearest-name"],
      ["The school moved sports day indoors because rain was likely. This kept the games on schedule. What kept the schedule?", ["the rain", "moving the event indoors", "the school building alone", "the weather report alone"], 1, "移到室內這項決定避免雨勢打亂賽程。", ["雨是風險，不能保證照表進行。", "建築物只有在移入活動後才發揮作用。", "報告提供資訊，但真正維持賽程的是搬到室內。"], "policy-event-reference", "identify-action-that-produces-result", "choose-causal-background"],
    ],
  },
  {
    id: "ENG_R4_S238", process: "resolve-demonstrative-proposition", evidence: "this 或 that 後的評論對哪一整句成立",
    objectives: ["辨認 this、that 概括前句事件的用法。", "區分單一名詞指涉與整句命題指涉。", "利用評價、結果與距離觀點確認唯一內容。"],
    sections: [
      ["指物還是指事情", "this book 中 this 直接限定名詞；This was unexpected 中 this 可獨立概括前句。先看後面是否有名詞，沒有時再測試整句事件。"],
      ["把前句變成一個名詞片語", "若前句是 The train arrived early，可暫時改成 the train's early arrival，再讀 This helped us。能順接 help 的是提早到達事件。"],
      ["that 可帶距離或回顧", "對話中的 that 常回指對方剛說的話；敘事中的 this 常承接作者正聚焦的事件。距離色彩是輔助，核心仍是後句語意。"],
      ["避免只抓最後一字", "前句尾端名詞常是誘餌。後文若評論是否公平、令人驚訝或造成結果，通常需要一整個行動或事實，而不是尾端物件。"],
    ],
    examples: [
      ["The team shared its food with visitors. This made the coach proud.", ["This 後無名詞。", "made proud 需要一個行為原因。", "概括分享食物事件。"], "This = the team's sharing food.", "分享行動而非 food 這個名詞造成教練驕傲。"],
      ["'I finished the work early.' 'That is good news.'", ["That 位於回應中。", "它回指對方整句話。", "good news 評論完成工作。"], "That = finishing the work early.", "對話者把剛聽到的事視為好消息。"],
      ["Nora chose this chair.", ["this 後直接有 chair。", "它是限定詞。", "不是獨立概括前句。"], "this chair", "this 與名詞組成同一名詞片語。"],
    ],
    misconceptions: [
      ["this 一定只指最近名詞。", "獨立 this 常概括整個事件。", "檢查後文是否在評論行動或事實。"],
      ["that 一定表示很遠的物品。", "對話中也常回指剛說的內容。", "依語境判定空間距離或篇章回指。"],
      ["this 後有名詞也要找前句事件。", "this book 類形式直接限定名詞。", "先辨認 this 的句法位置。"],
      ["只要重複前句最後一字就能解釋。", "後句評價可能要求完整命題。", "把候選放入後句，檢查能否造成該結果。"],
    ],
    checks: [
      ["This was unfair 中 this 後有被限定名詞嗎？", "沒有", "this 在此獨立作主詞。"],
      ["前句事件如何方便地測試為先行內容？", "改寫成事件名詞片語", "再看它能否承接後句評價。"],
      ["That sounds great 常回指什麼？", "對方剛說的內容", "sounds great 是對整個消息的評價。"],
    ],
    questions: [
      ["The store gave every child a free book. This brought many families back the next week. What does This mean?", ["the store building", "giving free books", "one child", "the next week"], 1, "送書活動能造成家庭再次來訪。", ["建築物本身不是後續回訪的新原因。", "單一孩子不能概括 every child 的活動。", "next week 是結果發生時間，不是原因。"], "cause-proposition-reference", "map-this-to-causal-event", "select-final-noun"],
      ["'Our train leaves at six.' 'That means we must wake up early.' What does That refer to?", ["the train's leaving time", "the alarm clock", "the speaker's bed", "six people"], 0, "六點發車的事實推出必須早起。", ["alarm 未在對話出現。", "bed 未在對話出現。", "six 是時間不是人數。"], "dialogue-proposition-reference", "use-inference-to-resolve-that", "treat-number-as-count"],
      ["Mia returned the lost wallet without taking the money. This was honest. What was honest?", ["the wallet", "the money", "Mia's action", "the owner"], 2, "誠實評價針對歸還且未取錢的行為。", ["wallet 是物件，不能有誠實品格。", "money 是被留下的物品，不是行為者。", "owner 未執行題中行為。"], "evaluation-reference", "match-moral-evaluation-to-action", "bind-this-to-nearest-noun"],
      ["Jay broke the cup and then hid it. That made the problem worse. What made the problem worse?", ["the cup alone", "hiding the broken cup", "the table", "buying a new cup"], 1, "隱瞞破杯使問題惡化，that 概括前述處理方式。", ["杯子是問題對象，但後句評論的是 Jay 的後續行動。", "table 未出現。", "原文沒有購買新杯，且那會改善而非惡化。"], "result-reference", "select-action-causing-worse-result", "select-object-not-action"],
      ["The road will be closed tonight. Please tell the drivers about that. What is that?", ["the road closure", "tonight alone", "the drivers", "the act of telling"], 0, "需要告知駕駛的是今晚道路封閉這項消息。", ["只說 tonight 缺少事件內容。", "drivers 是消息接收者。", "telling 是後句要求，不能回指尚未做的行動。"], "message-reference", "resolve-that-as-prior-fact", "choose-nearest-plural"],
      ["Leo chose this map because it shows every bus line. What is the role of this?", ["It limits map to a particular one", "It refers to the whole earlier sentence", "It replaces the verb chose", "It shows that map is plural"], 0, "this 直接放在單數名詞 map 前，指定某一張地圖。", ["this 後有名詞，不是獨立回指整句。", "chose 是動詞，this 不取代它。", "map 是單數，this 也標示單數。"], "demonstrative-determiner", "distinguish-noun-limiter-from-proform", "treat-all-this-as-event"],
      ["The class planted trees beside the road. This will give walkers more shade in summer. What will give shade?", ["the planting of trees", "the road alone", "summer", "the class schedule"], 0, "種樹會在未來提供遮蔭。", ["道路本身不新產生 shade。", "summer 是需要遮蔭的季節。", "schedule 未出現且不能製造遮蔭。"], "future-effect-reference", "link-action-to-future-benefit", "choose-location"],
      ["'I cannot come today, but I can help tomorrow.' 'That works for me.' What does That mean?", ["the offer to help tomorrow", "not helping at all", "today's work", "the word tomorrow only"], 0, "回應者接受的是改到明天幫忙的安排。", ["原話明說明天能幫，不是完全不幫。", "today's work 不是被接受的替代安排。", "單一時間字不足以包含幫忙承諾。"], "dialogue-offer-reference", "resolve-accepted-plan", "select-last-word-only"],
      ["The museum moved the old boat indoors before the storm. This protected it from the rain. What does This refer to?", ["moving the boat indoors", "the storm", "the rain", "the museum name"], 0, "搬到室內的行動使船免受雨淋。", ["storm 是威脅，不是保護行動。", "rain 是要避免的事物。", "museum name 與保護無關。"], "protective-action-reference", "identify-cause-of-protection", "bind-this-to-weather"],
      ["Sam said the test was moved to Friday. Nora had not heard that. What had Nora not heard?", ["the change of test date", "Sam's voice", "Friday as a word", "the test questions"], 0, "that 回指測驗改到星期五的完整消息。", ["重點是內容而非聲音。", "單一 Friday 不包含測驗改期。", "原文未提題目內容。"], "reported-fact-reference", "recover-content-of-that", "reduce-proposition-to-final-word"],
      ["The team practiced in the rain and still finished every task. This impressed the coach. Which part is included in This?", ["both practicing in rain and finishing tasks", "only the rain", "only the coach", "a future practice"], 0, "教練佩服的是克服雨勢仍完成任務的整體表現。", ["雨本身不是團隊表現。", "coach 是感受者，不是被評價事件。", "原文敘述已完成事件，不是未來練習。"], "compound-proposition-reference", "include-linked-actions-in-reference", "retain-only-final-noun"],
      ["A rule required lights on every bike, but the store sold a bike without one. That was the problem. What was the problem?", ["the store sold a bike that lacked a required light", "the rule had words", "every bike had a light", "the buyer entered the store"], 0, "問題是售出不符合規則的車，需整合 rule 與 without one。", ["規則有文字不是違規問題。", "這與 without one 相反。", "原文未說進店本身有問題。"], "cross-sentence-proposition", "combine-rule-and-violation", "treat-that-as-single-object"],
    ],
  },
  {
    id: "ENG_R4_S239", process: "resolve-substitution-form", evidence: "替代形式保留的名詞或動作內容",
    objectives: ["辨認 one、ones、do so、did 等避免重複的形式。", "還原替代內容並保持單複數與時態。", "排除只匹配最近字卻不符合句法角色的答案。"],
    sections: [
      ["one 與 ones 替代名詞", "one 替代可數單數名詞，ones 替代複數名詞。I need a pen. Do you have one? 中 one 保留 pen 的概念，但不是同一支已知的筆。"],
      ["do so 替代動作", "do so 可替代剛提到的動作片語。The sign asks us to wait, so we should do so 中 do so 等於 wait，而不是替代 sign。"],
      ["助動詞也能代替", "Mia can swim, and Nora can, too 中第二個 can 省略重複的 swim。還原時要保留主詞與助動詞所標示的時間、可能性或否定。"],
      ["先還原再作答", "把 one、do so 或助動詞暫時換回完整內容，重讀整句。若還原後數量、時態或意思不合，就不是正確先行內容。"],
    ],
    examples: [
      ["This cup is dirty. Please bring me a clean one.", ["one 是可數單數。", "前文單數名詞為 cup。", "clean 與 dirty 形成對比。"], "one = cup", "需要另一個乾淨杯子，而非重複 cup 一字作代名詞。"],
      ["The teacher asked us to sit down, and we did so.", ["did so 替代動作。", "往前找 asked 後的行動。", "時態由 did 標成過去。"], "did so = sat down", "全班執行了坐下的要求。"],
      ["Leo did not finish, but Amy did.", ["第二個 did 是替代用法。", "前文動作是 finish。", "Amy 的 did 為肯定。"], "Amy finished.", "第二句省略 finish，但保留完成的肯定意思。"],
    ],
    misconceptions: [
      ["one 永遠表示數字一。", "它也能替代可數單數名詞。", "看 one 是否位在需要名詞的位置。"],
      ["do so 指前面最近的名詞。", "它替代動作片語。", "往前找可被執行的動作。"],
      ["助動詞省略後沒有時態。", "did、can、will 等仍保留時間或語氣。", "還原動作時保留助動詞資訊。"],
      ["ones 可替代不可數名詞。", "ones 通常替代複數可數名詞。", "先檢查先行名詞是否可數且為複數。"],
    ],
    checks: [
      ["a blue one 中 one 最常替代哪一類名詞？", "可數單數名詞", "a 與 one 都標出單數。"],
      ["do so 應往前找名詞還是動作？", "動作", "do so 是動作替代形式。"],
      ["Nora can, too 中 can 後省略什麼？", "前文相同動作", "助動詞保留，主要動詞可省略。"],
    ],
    questions: [
      ["My pencil broke. May I use your extra one? What is one?", ["pencil", "break", "hand", "one minute"], 0, "one 替代可數單數 pencil，extra 描述另一支備用鉛筆。", ["break 是動作，one 在此需名詞。", "hand 未出現且不是被借用的文具。", "句中沒有時間單位。"], "one-substitution", "restore-singular-noun", "read-one-only-as-number"],
      ["The black shoes are wet, so I will wear the brown ones. What are ones?", ["shoes", "colors", "feet", "days"], 0, "ones 為複數，替代前文 shoes。", ["colors 是描述差異，不是被穿的物件。", "feet 未作先行名詞。", "days 與穿鞋情境無關。"], "ones-substitution", "restore-plural-noun", "bind-ones-to-adjective"],
      ["The coach told the players to rest, and they did so. What did they do?", ["They rested", "They spoke", "They coached", "They left the team"], 0, "did so 替代 told 後的動作 rest，時態為過去。", ["spoke 不是教練要求的動作。", "players 不是成為教練。", "原文只要求休息，未要求離隊。"], "do-so-substitution", "restore-requested-action", "bind-so-to-speaker"],
      ["Mia has visited the island, but Ben has not. What has Ben not done?", ["visited the island", "met Mia", "owned an island", "left home"], 0, "has not 省略重複的 visited the island。", ["兩人是否見面未提。", "visited 不表示 owned。", "離家不是被省略的明確動作。"], "auxiliary-substitution", "restore-present-perfect-action", "replace-only-main-verb"],
      ["I ordered a small bowl, but the server brought a large one. What was large?", ["a bowl", "the server", "the order time", "the table"], 0, "one 替代 bowl，large 與 small 對比。", ["server 是人物，不由 one 替代。", "order time 未出現且不可用 large one 指稱。", "table 未作先行名詞。"], "contrastive-one", "use-adjective-contrast-to-restore-noun", "select-nearest-person"],
      ["The sign asks visitors not to feed the birds. Please do not do so. What is forbidden?", ["feeding the birds", "reading the sign", "visiting the park", "watching birds"], 0, "do so 替代 feed the birds，雙重 not 保持禁止。", ["reading sign 是取得規則，不是規則禁止事項。", "visiting 並未被禁止。", "watching birds 與 feed 不同。"], "negative-do-so", "preserve-negated-action", "drop-negation-when-restoring"],
      ["Jay can play the guitar, and his sister can, too. What can his sister do?", ["play the guitar", "buy a guitar", "teach Jay", "sing only"], 0, "第二個 can 省略 play the guitar。", ["can play 不等於 can buy。", "原文沒有教學角色。", "sing 未在前文動作中。"], "modal-ellipsis", "restore-modal-complement", "invent-related-action"],
      ["There are two buses. The first one goes downtown; the second one goes to the lake. What does each one replace?", ["bus", "place", "driver", "road"], 0, "first one 與 second one 都從 two buses 中選一輛。", ["place 是目的地類別，不是被排序物。", "driver 未出現。", "road 未出現。"], "ordered-one-substitution", "restore-counted-noun", "treat-one-as-route-number"],
      ["Nora promised to return the key and did so before noon. Which sentence has the same meaning?", ["Nora returned the key before noon", "Nora made another promise", "Nora kept the key", "Nora returned at noon without the key"], 0, "did so 還原為 return the key，before noon 保留。", ["did so 表執行承諾，不是再承諾一次。", "kept the key 與 return 相反。", "被歸還的是 key，且時間為 noon 之前。"], "paraphrase-substitution", "restore-action-and-time", "restore-only-verb-without-object"],
      ["The red paper is too dark. Do we have a lighter one? What is requested?", ["a lighter piece of paper", "a lamp", "a smaller room", "less time"], 0, "one 替代 paper，lighter 與 red paper 的深色形成對比。", ["light 可聯想到燈，但 one 的先行名詞是 paper。", "room 未出現。", "time 不可由 a ... one 在此替代。"], "adjective-one-substitution", "use-context-not-wordplay", "interpret-lighter-as-object-weight-only"],
      ["Leo did not agree to join, but Sam did. What does the final did show?", ["Sam agreed to join", "Sam did not agree", "Leo joined Sam", "both refused"], 0, "but 標出對比，Sam did 為肯定地 agreed to join。", ["final did 沒有 not，不能保留否定。", "join 的對象是活動而非 Leo joining Sam。", "Sam 的肯定與 both refused 相反。"], "contrastive-ellipsis", "restore-positive-action-after-negative", "copy-negation-across-but"],
      ["The guide asked us to stay on the path. Most visitors did so, but two did not. What did the two visitors fail to do?", ["stay on the path", "ask the guide", "visit the place", "count the paths"], 0, "did so 與 did not 都共用 stay on the path；兩人未遵守。", ["guide 才是提出要求者。", "他們已是 visitors，並非沒參觀。", "原文沒有數路徑的要求。"], "linked-substitution-chain", "carry-same-action-through-positive-and-negative", "change-action-at-second-ellipsis"],
    ],
  },
  {
    id: "ENG_R4_S240", process: "use-discourse-marker", evidence: "標記詞宣告的轉折、因果或例證功能",
    objectives: ["辨認 however、therefore、for example 等標記功能。", "用標記詞預測下一句角色。", "跨句核對關係方向並排除錯誤標記。"],
    sections: [
      ["標記詞是路標", "however 通常預告轉折，therefore 或 as a result 引出結果，for example 引出前述概念的具體例子。先看到路標，就先預測後句要完成哪種工作。"],
      ["看清方向", "because 引原因，therefore 引結果；for example 後面較具體，前面較一般。若方向顛倒，即使兩句內容相關也不能選。"],
      ["標點提供邊界", "句首副詞標記常以逗點隔開，例如 However, ...。連接兩個完整句時要注意標點，但考題核心仍是邏輯，不應只靠逗點猜。"],
      ["標記詞不能創造不存在的關係", "兩句若只在同一主題下增加資訊，also 可能比 therefore 合理。必須先證明前句確實造成、對比或舉例後句。"],
    ],
    examples: [
      ["The walk is easy. For example, even young children can finish it.", ["前句提出一般評價 easy。", "後句是具體證據。", "for example 功能吻合。"], "example", "兒童也能走完是『容易』的具體例子。"],
      ["The shop was closed. Therefore, we came back later.", ["closed 是情況。", "come back later 是應對結果。", "therefore 引出結果。"], "result", "後句由前句直接導出。"],
      ["The room is small. However, it feels comfortable.", ["small 常帶負面限制。", "comfortable 是正面感受。", "however 標示落差。"], "contrast", "兩項評價方向不同。"],
    ],
    misconceptions: [
      ["有先後順序就能用 therefore。", "先後不一定是因果。", "確認前句是否真的造成後句。"],
      ["for example 前後一樣具體也可以。", "例證通常由一般概念走向具體案例。", "找出上位說法與實例。"],
      ["however 等於 because。", "however 表轉折，不表原因。", "先比較兩句方向是否相反。"],
      ["看到逗點就選句首標記。", "多個標記都能帶逗點。", "用句意關係決定。"],
    ],
    checks: [
      ["therefore 後通常是原因還是結果？", "結果", "它表示由前文推出的後果。"],
      ["for instance 的功能是什麼？", "舉例", "它把一般說法具體化。"],
      ["however 預告兩句關係如何？", "轉折", "後句與前句形成預期落差。"],
    ],
    questions: [
      ["The path was covered with ice. Therefore, the school closed it for the day. What relation does Therefore show?", ["result", "example", "contrast", "time"], 0, "關閉是結冰造成的結果。", ["後句不是結冰的一個例子。", "兩句不相反。", "for the day 是時間，但標記連接的是因果。"], "marker-function", "identify-result-marker", "label-any-sequence-as-time"],
      ["Many small actions save water. For example, turn off the water while brushing your teeth. What follows For example?", ["a specific action", "an opposite idea", "a final result", "an unrelated story"], 0, "關水是節水行動的具體案例。", ["後句支持而非反對前句。", "它示範作法，不是所有作法的最終結果。", "內容直接服務節水主題。"], "example-marker", "map-general-claim-to-instance", "confuse-example-and-result"],
      ["The ticket was cheap. However, the trip took three hours. Why is However suitable?", ["It marks a positive-negative contrast", "It gives the price cause", "It lists another cheap item", "It tells when the trip began"], 0, "便宜是優點，耗時三小時是缺點，形成評價轉折。", ["耗時不是票價便宜的原因。", "後句不是另一件商品。", "three hours 是時長，未提供開始時間。"], "contrast-marker", "identify-evaluation-shift", "read-duration-as-time-marker-only"],
      ["The library added more seats. As a result, fewer students had to stand. What is the result?", ["fewer students stood", "the library existed", "students asked for books", "the seats were removed"], 0, "增加座位直接使站立人數減少。", ["圖書館存在是背景，不是新增座位的後果。", "借書需求未提。", "removed 與 added 相反。"], "result-identification", "extract-clause-after-result-marker", "reverse-cause-and-result"],
      ["Some birds travel very far. For instance, one kind flies across the sea each year. Which sentence is more general?", ["the first sentence", "the second sentence", "both are one exact bird", "neither discusses birds"], 0, "第一句涵蓋 some birds，第二句以 one kind 舉例。", ["第二句較具體。", "第一句不是單一鳥。", "兩句都談 birds。"], "general-example-order", "identify-general-statement", "treat-example-as-generalization"],
      ["The team lost its first game. Nevertheless, it kept practicing. What does Nevertheless signal?", ["continuation despite difficulty", "practice caused the loss", "an example of losing", "the exact score"], 0, "失利通常使人灰心，但團隊仍持續練習。", ["練習發生在失利後，且未說造成失利。", "持續練習不是輸球例子。", "沒有比分資訊。"], "concession-marker", "interpret-nevertheless", "translate-marker-as-cause"],
      ["The weather report warned of heavy rain. ___, the outdoor show was moved inside.", ["As a result", "For example", "In contrast", "At first"], 0, "警告造成移入室內的決定。", ["後句不是 heavy rain 的例子。", "兩句沒有相反觀點。", "At first 只標示起初，不能表示因果。"], "marker-cloze", "select-result-connector", "select-marker-by-position-only"],
      ["The town has several ways to travel without a car. ___, people can rent bikes near the station.", ["For example", "However", "Therefore", "Instead"], 0, "租腳踏車是無車旅行方式的具體例子。", ["後句沒有反駁 several ways。", "有多種方式不必然造成租車站存在，重點是例證。", "Instead 需要被取代的前方案。"], "example-cloze", "select-example-connector", "use-therefore-for-topic-match"],
      ["The old phone was slow. ___, it still worked well for simple calls.", ["However", "Therefore", "For instance", "Similarly"], 0, "慢是缺點，但仍能好好通話，形成轉折。", ["slow 不會自然導致 worked well。", "通話不是 slow 的例子。", "Similarly 需要前文另一個相似對象。"], "contrast-cloze", "select-however", "treat-two-properties-as-addition"],
      ["The road is narrow. In addition, it has no lights at night. What does In addition do?", ["adds a second problem", "corrects the first claim", "gives the result of lights", "shows an earlier time"], 0, "沒有路燈是在道路狹窄之外增加的第二項問題。", ["後句沒有否定 narrow。", "無燈不是 narrow 的必然結果。", "at night 是細節，標記本身不表先後。"], "addition-marker", "identify-added-support", "mistake-detail-time-for-relation"],
      ["The first plan cost too much. Instead, the club used a free room. What does Instead show?", ["replacement of the first plan", "proof that both plans were used", "a reason the room was costly", "an example of the first plan"], 0, "免費房間取代昂貴的第一方案。", ["Instead 表改用，不是兩案並行。", "free 與 costly 相反，且昂貴原因未提。", "後句是替代方案，不是原案例子。"], "replacement-marker", "identify-alternative-plan", "read-instead-as-addition"],
      ["A paragraph says the lake is cleaner now. It then gives lower waste numbers and more fish. Which marker best introduces those details?", ["For example", "On the other hand", "As a result", "Before"], 0, "數據與魚量是湖變乾淨的具體支持例。", ["細節支持而非提出另一面。", "細節是證據，不一定都是變乾淨後才發生的結果。", "Before 需要時間比較，題幹未設此結構。"], "paragraph-marker-selection", "choose-example-for-supporting-details", "overstate-evidence-as-causation"],
    ],
  },
  {
    id: "ENG_R4_S241", process: "track-topic-by-lexical-chain", evidence: "重複詞、同義改寫與上位概念形成的詞鏈",
    objectives: ["以重複關鍵詞辨認段落持續主題。", "把同義詞與較概括說法連回同一概念。", "排除只出現一次但不承接後文的醒目細節。"],
    sections: [
      ["找詞鏈而非單字", "作者會避免每句重複同一字，而用 bike、this vehicle、the two-wheeled ride 等方式承接。將指向同一概念的字圈成一條鏈，比只數單字可靠。"],
      ["主題通常跨多句", "一個地名或數字可能只出現一次。真正主題會在多句中被重述、解釋、比較或以代名詞承接。看哪個概念控制最多句子。"],
      ["同義不必完全相等", "help 與 support、buy 與 purchase 在特定上下文可承接；但近義字仍有用法差異。要以該段事件確認它們是否真的談同一事。"],
      ["用主題句驗證", "試著用一個短名詞片語概括整段。若某句完全無法放入，就檢查它是例子、結果，還是主題其實選錯。"],
    ],
    examples: [
      ["The town opened a bike path. The new route keeps riders away from cars. This safer way is popular.", ["bike path 首次介紹。", "new route 改寫同一設施。", "safer way 再次承接。"], "the bike path", "三個不同表達形成同一詞鏈。"],
      ["Mia joined a food drive. The project collected rice. This activity helped families.", ["food drive 是活動。", "project 與 activity 都可重述。", "收集食物與幫助家庭延伸同一主題。"], "the food drive", "同義上位詞讓主題跨句延續。"],
      ["A paragraph mentions 8:00 once but repeats buses, drivers, and routes.", ["8:00 是單一細節。", "交通詞群跨多句。", "主題應涵蓋整段。"], "the bus service", "醒目數字不是主題；多句詞鏈才是。"],
    ],
    misconceptions: [
      ["重複次數最多的完全相同單字一定是主題。", "同義詞與代名詞也會承接。", "把相同概念的不同表達合併計算。"],
      ["第一句的每個名詞都同樣重要。", "後文只會持續發展其中核心概念。", "追蹤哪個名詞有後續詞鏈。"],
      ["數字很具體，所以是主題。", "數字常只是支持細節。", "用能涵蓋所有句子的概念作主題。"],
      ["近義字在任何文章都完全相同。", "詞義取決於語境。", "確認兩字是否承接同一人物、物件或行動。"],
    ],
    checks: [
      ["route 可在交通段落中承接 path 嗎？", "可以，若兩者指同一路線", "要由上下文確認同一對象。"],
      ["只出現一次的日期通常是主題還是細節？", "細節", "除非整段都在發展該日期。"],
      ["主題短語應能涵蓋多少句？", "整個段落", "包括例子與結果都要能連回它。"],
    ],
    questions: [
      ["A passage uses 'a free meal program,' 'the service,' and 'this project.' What likely links the three phrases?", ["They name the same program", "They describe three meals", "They are unrelated dates", "They name three schools"], 0, "service 與 project 在同段承接首次介紹的 meal program。", ["三詞是不同稱呼，不是三餐數量。", "沒有日期詞。", "沒有三所學校的證據。"], "lexical-chain", "link-program-service-project", "treat-rewording-as-new-topic"],
      ["The river was once dirty. Volunteers cleaned the water, and the stream now has fish again. Which words form a topic chain?", ["river-water-stream", "dirty-volunteers-fish", "once-now-again", "cleaned-has"], 0, "river、water、stream 在此共同承接同一水域。", ["三字分屬狀態、人物與動物，不能命名同一對象。", "這是時間對比詞，不是水域主題鏈。", "兩個動詞不能共同指稱主題名詞。"], "topic-chain-identification", "connect-contextual-synonyms", "group-by-word-class-only"],
      ["A paragraph mentions a concert once, then discusses tickets, seats, and the stage. What is the broad topic?", ["the concert event", "one seat", "paper tickets only", "the time of day"], 0, "tickets、seats、stage 都是 concert event 的部分。", ["單一 seat 無法涵蓋票與舞台。", "paper tickets 無法涵蓋座位與舞台。", "沒有跨句時間詞鏈。"], "topic-inference", "select-superordinate-event", "choose-most-repeated-detail"],
      ["The text says 'older people,' later 'these adults,' and finally 'the group.' Who remains the topic?", ["the older people", "children", "three different groups", "the writer"], 0, "these adults 與 the group 都承接 older people。", ["沒有 children 線索。", "指示詞 these 顯示承接而非新群體。", "writer 未成為 group 的成員。"], "participant-chain", "trace-group-rewording", "assume-new-noun-means-new-group"],
      ["A story repeats storm, strong wind, and heavy rain across four sentences. Which phrase best names the topic chain?", ["dangerous weather", "a quiet morning", "school subjects", "food prices"], 0, "storm、wind、rain 都屬危險天氣。", ["quiet 與 strong/heavy 相反。", "沒有課科資訊。", "沒有價格資訊。"], "semantic-field", "infer-hypernym-from-weather-terms", "select-single-weather-item"],
      ["The first sentence introduces a night market. Later sentences call it 'the busy place' and 'this shopping area.' What does it refer to?", ["the night market", "the first sentence", "a private home", "one product"], 0, "busy place 與 shopping area 都符合 night market 的地點特徵。", ["代名詞指內容中的地點，不是句子本身。", "private home 與 shopping area 不合。", "area 是整體，不是單一產品。"], "place-chain", "connect-descriptive-renaming", "bind-it-to-nearest-abstract-noun"],
      ["Which detail is least likely to be the paragraph topic if it appears once while 'garden,' 'plants,' and 'flowers' appear throughout?", ["the price of one pot", "the garden", "plant care", "growing flowers"], 0, "單一花盆價格是局部細節，其餘都可涵蓋跨句園藝詞鏈。", ["garden 本身是反覆核心。", "plant care 可統攝植物相關行動。", "growing flowers 可連結 garden、plants、flowers。"], "detail-versus-topic", "downrank-single-detail", "select-specific-number-as-topic"],
      ["The writer changes 'buying less plastic' to 'this choice' in the next sentence. What does choice carry forward?", ["buying less plastic", "buying more goods", "choosing a store", "the next sentence"], 0, "this choice 概括前句減少購買塑膠的決定。", ["more 與 less 相反。", "store 未出現。", "指涉文章內容而非句子形式。"], "nominalization-chain", "resolve-action-as-choice", "choose-nearest-noun-plastic"],
      ["A paragraph moves from buses to public transport and then to ways to travel together. What happens to the topic?", ["It becomes broader", "It changes to food", "It becomes one exact bus", "It disappears"], 0, "public transport 與 shared travel 是 buses 的較廣概念。", ["沒有食物詞鏈。", "發展方向由具體 bus 走向更廣，而非更窄。", "概念仍被上位詞承接。"], "topic-development", "recognize-broadening-chain", "treat-rewording-as-topic-loss"],
      ["The passage discusses a school garden. One sentence gives the number 24. Which question best tests whether 24 is the topic?", ["Do later sentences keep developing that number?", "Is 24 larger than 20?", "Is the number near the first sentence?", "Does 24 look important?"], 0, "主題需被後文持續發展，不能只靠數字外觀。", ["大小比較不證明篇章角色。", "位置近不表示跨句承接。", "視覺醒目不是語意證據。"], "topic-test-strategy", "check-cross-sentence-development", "equate-salience-with-topic"],
      ["A text calls a repair group 'the team,' 'these helpers,' and 'the volunteers.' Which repeated idea should a summary keep?", ["people helping with repairs", "three separate clubs", "the names of all tools", "only the word volunteers"], 0, "三個稱呼共同指向協助修繕的人群。", ["these 表明同一群人，不是三社團。", "工具不是這條人物詞鏈的核心。", "摘要應保留概念，不必只保留原字。"], "summary-from-chain", "compress-synonyms-to-core-idea", "copy-last-label-only"],
      ["Across a paragraph, 'the lake,' 'its water,' 'the shore,' and 'the area' appear. Which claim is safest?", ["They can support one lake topic while naming different parts", "Every phrase names exactly the water", "The paragraph must have four topics", "shore means the same thing as water"], 0, "不同部分可共同支持 lake 主題，但不必字義完全相同。", ["shore 與 area 不等於 water。", "部分名稱不必各自成為主題。", "shore 是岸邊，不能當 water 同義詞。"], "part-whole-topic-chain", "distinguish-topic-link-from-synonymy", "demand-exact-synonyms"],
    ],
  },
  {
    id: "ENG_R4_S242", process: "reject-near-but-incompatible-antecedent", evidence: "候選與後句動作、數量及因果的相容性",
    objectives: ["辨認距離誘餌並列出所有候選。", "用後句動作與因果排除最近但不合理的名詞。", "在證據不足時保留歧義，不過度推論。"],
    sections: [
      ["最近名詞只是候選", "英語常把其他細節插在先行詞與代名詞之間。最近名詞若數量、人物類型或動作不合，必須退回更前面的候選。"],
      ["動詞是強力篩選器", "在 The key was beside the books. It opened the door 中，opened the door 使 key 成為唯一合理先行詞；books 雖較近卻為複數且不能用 it。"],
      ["因果能跨越距離", "若後句有 so、because 或結果描述，找能造成該結果的前文事件。位置近但無因果作用的名詞要排除。"],
      ["證據排序", "先用硬性句法，如單複數與主受格；再用明確事件角色；最後才用距離與常識。這個順序可避免以直覺蓋過可驗證線索。"],
    ],
    examples: [
      ["A key lay under two papers. It opened the back door.", ["It 是單數。", "papers 是複數，排除。", "key 能開門。"], "It = a key.", "較遠的 key 同時通過數量與動作檢查。"],
      ["The rain hit the windows of the old house. They shook loudly.", ["They 是複數。", "house 是最近單數，排除。", "windows 可被風吹雨打而震動。"], "They = the windows.", "數量證據勝過距離。"],
      ["Mia put a note in Nora's bag. She read it later.", ["Mia 與 Nora 都可配 she。", "兩人都可能閱讀。", "沒有額外證據。"], "She is unclear.", "不能因 Nora 較近就宣稱唯一答案。"],
    ],
    misconceptions: [
      ["距離是第一優先規則。", "硬性數量與動作證據更可靠。", "依句法、角色、距離的順序檢查。"],
      ["常識覺得可能就足以唯一決定。", "多個人可能做同一動作。", "需要文字證據排除其他候選。"],
      ["介系詞片語中的名詞總是先行詞。", "它可能只是插入細節。", "看後句是否真正承接該名詞。"],
      ["較遠候選一定已離開主題。", "主題可跨越修飾語延續。", "追蹤事件鏈而非字距。"],
    ],
    checks: [
      ["最近名詞為複數但代名詞為 it，應保留嗎？", "不應", "數量硬性衝突。"],
      ["兩位女性都可能做 she 後的動作時可選最近者嗎？", "不可", "沒有唯一文字證據。"],
      ["判斷順序中距離應在句法之前還是之後？", "之後", "距離只是弱提示。"],
    ],
    questions: [
      ["The lamp stood beside two chairs. It gave enough light to read. What does It refer to?", ["the lamp", "the chairs", "reading", "two people"], 0, "It 是單數且能 give light，指 lamp。", ["chairs 是複數，應用 they，且不是主要光源。", "reading 是動作，不能給光。", "people 未出現。"], "distance-trap-reference", "override-nearest-plural-with-action", "choose-nearest-noun"],
      ["A bird sat on the roofs of two houses. They were covered with snow. What were covered?", ["the roofs", "the bird", "snow", "one house"], 0, "They 為複數，covered with snow 合理描述 roofs。", ["bird 是單數。", "snow 是覆蓋物，不是被雪覆蓋者。", "one house 是單數，與 They 不合。"], "plural-distance-reference", "match-number-and-passive-state", "bind-they-to-nearest-singular"],
      ["Leo put his ticket inside a book. He needed it to enter the show. What is it?", ["the ticket", "the book", "Leo", "the show"], 0, "進場需要 ticket；book 雖較近但不能作入場憑證。", ["book 只是存放票的位置。", "Leo 是需要者，不是被需要的物件。", "show 是目的活動，不能用來進入自身。"], "purpose-reference", "use-purpose-to-reject-nearest-object", "choose-container-not-contained-item"],
      ["The bus passed a shop with bright windows. It stopped at the school gate. What stopped?", ["the bus", "the shop", "the windows", "the gate"], 0, "bus 是移動後能在校門停下的交通工具。", ["shop 是固定建築物，不會到校門停下。", "windows 是複數且不移動。", "gate 是停靠地點。"], "movement-chain-reference", "track-moving-topic-across-detail", "bind-it-to-nearest-singular-shop"],
      ["Nora found a photo in an old box. It showed her father as a child. What showed the father?", ["the photo", "the box", "Nora", "the finding"], 0, "photo 能 show 圖像內容；box 只是容器。", ["box 不呈現照片中的人物。", "Nora 是觀看者。", "finding 是事件，不會直接顯示影像。"], "container-content-reference", "select-content-over-near-container", "choose-nearest-container"],
      ["The teacher spoke to Mia after calling Nora. She sounded worried. Which answer is justified?", ["She must be the teacher", "She must be Mia", "She must be Nora", "More context is needed"], 3, "三位女性都可能 sounded worried，原文未提供唯一角色。", ["teacher 合理但不是唯一。", "Mia 合理但不是唯一。", "Nora 合理但不是唯一。"], "three-candidate-ambiguity", "refuse-distance-only-resolution", "force-unique-answer-from-distance"],
      ["A strong wind moved the branches of the tree. They hit the window. What hit the window?", ["the branches", "the tree", "the wind only", "the house"], 0, "They 是複數且 branches 被風吹動後能撞窗。", ["tree 是單數。", "wind 是單數，且後句明確用 They。", "house 未作移動物。"], "cause-chain-reference", "trace-moved-plural-object", "bind-they-to-nearest-tree"],
      ["Jay left a wet coat on the wooden chair. It made the chair wet, too. What made the chair wet?", ["the coat", "the wood", "Jay", "the word too"], 0, "前文 wet coat 與後文結果建立直接因果。", ["wood 是 chair 的材質，不是新增濕氣來源。", "Jay 放置外套但 it 為事物，直接指 coat。", "too 是副詞，不是原因。"], "causal-object-reference", "select-cause-not-nearest-noun", "choose-nearest-chair"],
      ["The guide gave maps to the visitors near the gate. They folded them and put them in their bags. Who folded the maps?", ["the visitors", "the maps", "the gate", "the guide alone"], 0, "They 指複數 visitors；them 指 maps，訪客執行折疊。", ["maps 是被折的受詞。", "gate 是單數地點。", "guide 是給 maps 的人，後句複數 They 不指他一人。"], "multiple-reference-chain", "resolve-agent-and-object", "bind-they-to-nearest-plural-maps"],
      ["The river reached the steps of the houses. It was higher than yesterday. What was higher?", ["the river level", "the steps", "the houses", "yesterday"], 0, "reached the steps 與 higher 都描述河水水位。", ["steps 是複數且只是比較位置。", "houses 是複數，應用 they。", "yesterday 是比較時間，不是高度物。"], "measurement-reference", "carry-measured-topic-across-location-detail", "bind-it-to-steps"],
      ["Amy put the cake beside the ice because it needed to stay cool. What is the clearest referent of it?", ["the cake", "the ice", "Amy", "the act of putting"], 0, "需要保持涼的是 cake；ice 已是冷卻來源。", ["ice 本身提供低溫，stay cool 目的指被保存食物。", "Amy 是人且 she 才是相應形式。", "行動不會需要保持涼。"], "purpose-and-role-reference", "distinguish-target-from-means", "select-nearest-noun-ice"],
      ["A report compared a van with three bikes. It carried more boxes but used more fuel. Which vehicle is It?", ["the van", "the three bikes", "the report", "the boxes"], 0, "It 是單數 vehicle，且 van 能和三輛 bikes 比載貨量與燃料。", ["bikes 是複數，應用 they。", "report 不搬運箱子或用燃料。", "boxes 是被載物且為複數。"], "comparison-reference", "use-number-and-vehicle-properties", "bind-it-to-nearest-plural"],
    ],
  },
];

export const ENGLISH_UNIT_SOURCE = defineEnglishUnit({
  unitId: "ENG_R4_U35",
  skills,
  vocabularyPolicy: {
    capQuestionBasis: "appendix-5-table-1",
    additionalLearningTerms: ["activity", "add", "adult", "alarm", "alone", "branch", "broad", "cause", "coach", "compare", "describe", "develop", "difficulty", "disappear", "discuss", "downtown", "event", "exist", "extra", "final", "form", "forward", "general", "guide", "include", "introduce", "lack", "lay", "limit", "link", "narrow", "negative", "neither", "path", "perfect", "positive", "private", "project", "promise", "protect", "refuse", "rent", "repair", "result", "return", "role", "roof", "score", "serve", "shore", "similar", "step", "storm", "stream", "support", "tank", "therefore", "travel", "waste", "wheel", "whole", "wood"],
    contextualizedAboveRangeTerms: ["addition", "arrival", "chain", "claim", "closure", "clue", "concert", "contest", "context", "continuation", "contrast", "despite", "detail", "exact", "fold", "forbid", "force", "fuel", "grammar", "impress", "indoors", "instance", "instead", "justify", "loss", "mention", "nevertheless", "opposite", "outdoor", "paragraph", "particular", "passage", "phrase", "plastic", "plural", "product", "proof", "purchase", "refer", "reference", "referent", "relation", "remain", "remove", "replace", "replacement", "request", "require", "route", "safest", "schedule", "separate", "shade", "signal", "specific", "stage", "statement", "suitable", "summary", "task", "text", "throughout", "transport", "unclear", "unexpected", "unfair", "unrelated", "van", "vehicle", "verb", "volunteer", "warn", "wooden"],
    properNames: ["Amy", "Ben", "Eva", "Jay", "Leo", "Mia", "Nora", "Sam"],
    grammarNotation: [],
    malformedDistractors: [],
  },
});
