export const INTEGRATED_SOCIAL_VERSION = "4.0.0";

export const OFFICIAL_CALIBRATION = {
  latestPaper: "CAP-115-MAIN",
  minutes: 70,
  minimumQuestions: 50,
  maximumQuestions: 60,
  defaultQuestions: 54,
  defaultSubjectCounts: {
    geography: 17,
    history: 19,
    civics: 18,
  },
  sharedSetCount: 4,
};

const INTEGRATED_AUTHORITY_REFS = [
  "AUTH-SOCIAL-LP-SOC-2B-4-3",
  "AUTH-SOCIAL-LP-SOC-3D-4-2",
];

const INTEGRATED_PROVENANCE = {
  status: "original",
  authorRole: "Codex R4 integrated social content author",
  copyrightStatus: "Original wording and simulated data; official sources and completed R4 subject banks were used only for scope, concepts, and assessment calibration.",
  sourceRefs: INTEGRATED_AUTHORITY_REFS,
};

// ponytail: keep reviewed prose static here; runtime only selects and orders IDs.
function integratedQuestion({ id, stimulusId, skillIds, stem, options, answerIndex, reasons, difficulty, cognitiveProcess, misconceptionTargets, reviews }) {
  return {
    id,
    subject: "civics",
    skillIds,
    authorityRefs: INTEGRATED_AUTHORITY_REFS,
    stimulusId,
    stem,
    options,
    answerIndex,
    optionRationales: reasons.map((reason, optionIndex) => ({ optionIndex, isCorrect: optionIndex === answerIndex, reason })),
    difficulty,
    cognitiveProcess,
    representationType: "integrated-data-table",
    misconceptionTargets,
    provenance: INTEGRATED_PROVENANCE,
    independentReviews: reviews.map((evidence, index) => ({
      reviewerRole: index === 0 ? "integrated-social-solution-review" : "integrated-social-alternative-answer-review",
      derivedAnswerIndex: answerIndex,
      evidence,
      status: "pass",
    })),
    assets: [],
  };
}

const C01_SKILLS = ["CIV_R4_S121", "GEO_R4_S151"];
const C02_SKILLS = ["CIV_R4_S210", "GEO_R4_S212", "HIS_R4_S224"];
const C03_SKILLS = ["CIV_R4_S047", "GEO_R4_S070", "GEO_R4_S131"];
const C04_SKILLS = ["CIV_R4_S239", "GEO_R4_S105", "HIS_R4_S191"];

const INTEGRATED_CIVICS_CONTENT = {
  ISOC_SET_C01: {
    stimulus: {
      id: "ISOC_ST_C01",
      subject: "civics",
      type: "table",
      skillIds: C01_SKILLS,
      authorityRefs: INTEGRATED_AUTHORITY_REFS,
      content: {
        title: "離岸風電選址比較",
        prompt: "原創情境。政策門檻為年發電指數至少 70、漁場作業減少不超過 10%，且須避開候鳥高使用區；通過門檻後仍須完成實質公共參與。",
        table: {
          caption: "三個離岸風電方案的能源、生計、生態與參與資料",
          columns: ["方案", "年發電指數", "漁場作業減少", "生態條件", "漁民有效回覆率"],
          rows: [
            ["甲", "82", "24%", "穿越候鳥高使用區", "18%"],
            ["乙", "74", "9%", "避開候鳥高使用區", "61%"],
            ["丙", "78", "16%", "避開候鳥高使用區", "22%"],
          ],
        },
      },
      accessibility: {
        summary: "表格比較甲乙丙三案的發電、漁場影響、生態條件與漁民回覆率。",
        longDescription: "只有乙案同時達到發電至少七十、漁場作業減少不超過百分之十並避開候鳥高使用區；乙案漁民有效回覆率為百分之六十一。",
      },
      assets: [],
      questionIds: ["ISOC_C01_Q01", "ISOC_C01_Q02", "ISOC_C01_Q03"],
      provenance: INTEGRATED_PROVENANCE,
    },
    questions: [
      integratedQuestion({
        id: "ISOC_C01_Q01",
        stimulusId: "ISOC_ST_C01",
        skillIds: C01_SKILLS,
        stem: "只依題示的能源、生計與生態門檻，哪一方案可進入下一階段審查？",
        options: ["甲案", "乙案", "丙案", "三案都符合"],
        answerIndex: 1,
        reasons: [
          "甲案的漁場作業減少為 24%，且穿越候鳥高使用區。",
          "乙案發電指數 74、漁場作業減少 9%，並避開候鳥高使用區，三項門檻皆符合。",
          "丙案的漁場作業減少為 16%，超過 10% 上限。",
          "甲、丙各有未達門檻之處，不能判定三案都符合。",
        ],
        difficulty: "standard",
        cognitiveProcess: ["table-analysis", "criteria-application"],
        misconceptionTargets: ["只看發電量忽略空間與生計限制"],
        reviews: [
          "逐欄套用三項明確門檻，只有乙案同時符合，答案為 B。",
          "甲案違反漁場與候鳥條件，丙案違反漁場條件，A、C、D 均可排除。",
        ],
      }),
      integratedQuestion({
        id: "ISOC_C01_Q02",
        stimulusId: "ISOC_ST_C01",
        skillIds: C01_SKILLS,
        stem: "為何不能因甲案發電指數最高就直接核准？",
        options: [
          "發電指數越高，其他資料就失去效力",
          "所有能源建設都不得設在海上",
          "公共決策仍須比較漁業生計、生態承載與受影響者參與",
          "漁民有效回覆率可直接換算成發電量",
        ],
        answerIndex: 2,
        reasons: [
          "發電效益不能消除表中其他政策條件。",
          "材料要求比較方案，未提出全面禁止海上能源建設。",
          "甲案同時牽涉空間利用、生態風險與公共參與，須綜合衡量。",
          "回覆率是參與資訊，與發電指數不是可互換單位。",
        ],
        difficulty: "advanced",
        cognitiveProcess: ["multi-criteria-evaluation", "public-reasoning"],
        misconceptionTargets: ["單一效益足以正當化全部成本"],
        reviews: [
          "題幹問核准理由，C 是唯一同時回應地理承載、生計影響與公民參與的選項。",
          "A 否定資料、B 過度概括、D 混淆指標，均不能支持直接核准。",
        ],
      }),
      integratedQuestion({
        id: "ISOC_C01_Q03",
        stimulusId: "ISOC_ST_C01",
        skillIds: C01_SKILLS,
        stem: "乙案通過三項門檻後，哪一作法最符合『實質公共參與』？",
        options: [
          "只公布核准結果，不公開影響資料",
          "以回覆率超過五成為由，停止接受反對意見",
          "只邀請開發公司修正漁業資料",
          "公開假設與影響資料、協助受影響漁民參與，並逐項回應意見後再決定",
        ],
        answerIndex: 3,
        reasons: [
          "不公開資料使受影響者無法知情判斷。",
          "回覆率不會取消少數意見或後續檢驗的必要。",
          "只讓開發者修正資料欠缺受影響者與獨立檢核。",
          "知情、可近用、可回應且能影響決策，才構成實質參與。",
        ],
        difficulty: "transfer",
        cognitiveProcess: ["participation-design", "policy-transfer"],
        misconceptionTargets: ["形式收件等同實質參與"],
        reviews: [
          "D 包含資訊公開、參與可近用、意見回應與決策連結，符合實質參與。",
          "A、B、C 分別欠缺公開、少數保障或利害關係人參與，沒有替代正解。",
        ],
      }),
    ],
  },
  ISOC_SET_C02: {
    stimulus: {
      id: "ISOC_ST_C02",
      subject: "civics",
      type: "table",
      skillIds: C02_SKILLS,
      authorityRefs: INTEGRATED_AUTHORITY_REFS,
      content: {
        title: "港口城市供應鏈變化",
        prompt: "原創歷時情境，不代表實際統計。『最大單一境外來源占比』越高，表示供應來源越集中。",
        table: {
          caption: "1975、2000 與 2025 年港口城市的生產與供應鏈指標",
          columns: ["年份", "本地零組件占比", "最大單一境外來源占比", "出口市場數", "港運中斷日數"],
          rows: [
            ["1975", "72%", "12%", "3", "2"],
            ["2000", "48%", "28%", "8", "4"],
            ["2025", "35%", "52%", "14", "21"],
          ],
        },
      },
      accessibility: {
        summary: "表格呈現三個年份的本地零組件、最大境外來源、出口市場與港運中斷日數。",
        longDescription: "出口市場由三個增至十四個，但本地零組件由百分之七十二降至三十五；最大單一境外來源由百分之十二升至五十二，港運中斷由兩日增至二十一日。",
      },
      assets: [],
      questionIds: ["ISOC_C02_Q01", "ISOC_C02_Q02", "ISOC_C02_Q03"],
      provenance: INTEGRATED_PROVENANCE,
    },
    questions: [
      integratedQuestion({
        id: "ISOC_C02_Q01",
        stimulusId: "ISOC_ST_C02",
        skillIds: C02_SKILLS,
        stem: "哪一組變化最直接顯示供應鏈集中風險上升？",
        options: [
          "出口市場由 3 個增至 14 個",
          "本地零組件占比由 72% 降至 35%",
          "最大單一境外來源占比由 12% 升至 52%，中斷日數由 2 日增至 21 日",
          "年份由 1975 進入 2025",
        ],
        answerIndex: 2,
        reasons: [
          "市場增加呈現出口多元，不能直接證明供應來源集中。",
          "本地占比下降顯示依賴增加，但未單獨指出集中於單一來源。",
          "單一來源占比與中斷日數同步大增，最直接對應集中風險。",
          "時間經過本身不是供應鏈風險指標。",
        ],
        difficulty: "standard",
        cognitiveProcess: ["trend-reading", "risk-identification"],
        misconceptionTargets: ["出口市場多就代表供應來源也多"],
        reviews: [
          "依題示集中定義，C 同時使用單一來源占比與中斷結果，答案唯一。",
          "A 是需求端市場、B 只顯示境外依賴、D 無因果指標，均不如 C 直接。",
        ],
      }),
      integratedQuestion({
        id: "ISOC_C02_Q02",
        stimulusId: "ISOC_ST_C02",
        skillIds: C02_SKILLS,
        stem: "綜合三個年份，哪項歷史解釋最符合資料？",
        options: [
          "全球連結擴大出口市場，同時可能形成新的空間依賴與中斷風險",
          "出口市場增加必然使本地零組件占比上升",
          "1975 年的生產完全沒有對外連結",
          "港運中斷日數增加證明出口市場數必須減少",
        ],
        answerIndex: 0,
        reasons: [
          "出口市場增加與來源集中、中斷日數上升並存，呈現連結與風險的雙重變化。",
          "表中本地零組件占比反而下降。",
          "1975 年已有境外來源與三個出口市場。",
          "2025 年中斷日數較多，但出口市場仍增加至十四個。",
        ],
        difficulty: "advanced",
        cognitiveProcess: ["historical-change", "relational-analysis"],
        misconceptionTargets: ["全球化只有利益或只有風險"],
        reviews: [
          "A 能同時解釋出口市場擴張與供應集中風險，是對全表最完整的有限結論。",
          "B、C、D 都與至少一欄資料直接矛盾，不能成為替代答案。",
        ],
      }),
      integratedQuestion({
        id: "ISOC_C02_Q03",
        stimulusId: "ISOC_ST_C02",
        skillIds: C02_SKILLS,
        stem: "若政策目標是在維持對外交易下減少集中風險，哪一方案最完整？",
        options: [
          "禁止全部進出口並關閉港口",
          "只增加宣傳預算，不調整供應來源",
          "把採購全部移到目前占比最高的單一來源",
          "分散關鍵來源、建立必要備援，並公開成本及協助受衝擊勞工轉型",
        ],
        answerIndex: 3,
        reasons: [
          "全面停止交易違反題示的維持對外交易目標。",
          "宣傳無法處理來源集中與中斷備援。",
          "進一步集中會提高而非降低風險。",
          "來源分散與備援處理空間風險，成本公開與勞工轉型回應分配影響。",
        ],
        difficulty: "transfer",
        cognitiveProcess: ["policy-design", "distributional-evaluation"],
        misconceptionTargets: ["效率政策不必處理受衝擊群體"],
        reviews: [
          "D 同時符合維持交易、降低集中與處理轉型成本三項要求。",
          "A 違反目標，B 無風險機制，C 使集中惡化，皆可排除。",
        ],
      }),
    ],
  },
  ISOC_SET_C03: {
    stimulus: {
      id: "ISOC_ST_C03",
      subject: "civics",
      type: "table",
      skillIds: C03_SKILLS,
      authorityRefs: INTEGRATED_AUTHORITY_REFS,
      content: {
        title: "同一流域三地避難條件",
        prompt: "原創豪雨情境。河水由上游甲流向中游乙、下游丙；三地分屬不同自治區。",
        table: {
          caption: "甲乙丙三地的淹水、人口、交通與避難所資料",
          columns: ["地區", "預估淹水深度", "65 歲以上人口", "無車家戶", "每小時接駁車", "避難所空缺"],
          rows: [
            ["上游甲", "0.4 公尺", "18%", "12%", "4 班", "180 人"],
            ["中游乙", "1.2 公尺", "29%", "31%", "2 班", "90 人"],
            ["下游丙", "2.0 公尺", "35%", "44%", "1 班", "40 人"],
          ],
        },
      },
      accessibility: {
        summary: "表格比較同一流域上中下游三地的淹水深度、高齡人口、無車家戶、接駁車與避難容量。",
        longDescription: "丙地預估淹水最深、高齡與無車家戶比例最高，同時接駁車最少、避難所空缺最少。",
      },
      assets: [],
      questionIds: ["ISOC_C03_Q01", "ISOC_C03_Q02", "ISOC_C03_Q03"],
      provenance: INTEGRATED_PROVENANCE,
    },
    questions: [
      integratedQuestion({
        id: "ISOC_C03_Q01",
        stimulusId: "ISOC_ST_C03",
        skillIds: C03_SKILLS,
        stem: "若先補強最急迫的交通避難缺口，哪一地應優先？",
        options: ["上游甲", "中游乙", "下游丙", "三地風險完全相同"],
        answerIndex: 2,
        reasons: [
          "甲的淹水較淺、無車與高齡比例較低，接駁及空缺也較多。",
          "乙有明顯風險，但各項弱勢與容量指標都未高於丙。",
          "丙同時有最深淹水、最高高齡與無車比例、最少接駁及最少空缺。",
          "表中各項風險與資源明顯不同。",
        ],
        difficulty: "standard",
        cognitiveProcess: ["table-analysis", "priority-identification"],
        misconceptionTargets: ["平均分配等同公平"],
        reviews: [
          "五項指標一致指向丙的風險最高且避難資源最低，答案為 C。",
          "甲、乙沒有同時達到丙的風險與資源缺口，D 也與表格不符。",
        ],
      }),
      integratedQuestion({
        id: "ISOC_C03_Q02",
        stimulusId: "ISOC_ST_C03",
        skillIds: C03_SKILLS,
        stem: "只有一筆新增接駁預算時，哪一分配理由最符合需求公平？",
        options: [
          "三地不論風險都分到完全相同班次",
          "優先補助丙，因其暴露、脆弱度與交通缺口都最高，並公開後續檢核標準",
          "只補助人口中高齡比例最低的甲",
          "由三地首長抽籤且不公布資料",
        ],
        answerIndex: 1,
        reasons: [
          "資源有限時完全等量未回應不等的風險與需求。",
          "丙的多項需求最高，且公開檢核可讓優先順序接受監督。",
          "甲的相對需求最低，與需求公平相反。",
          "不依資料且不公開，無法說明分配正當性。",
        ],
        difficulty: "advanced",
        cognitiveProcess: ["needs-based-allocation", "public-accountability"],
        misconceptionTargets: ["形式相等必然是公平"],
        reviews: [
          "B 以可核對的差異需求分配有限資源，並保留公開問責，符合需求公平。",
          "A 忽略差異、C 逆向優先、D 無理由與透明度，均不能成立。",
        ],
      }),
      integratedQuestion({
        id: "ISOC_C03_Q03",
        stimulusId: "ISOC_ST_C03",
        skillIds: C03_SKILLS,
        stem: "三地分屬不同自治區，為何仍需要流域共同預警與避難協調？",
        options: [
          "行政界線會使河水停止流動",
          "上游資訊只影響上游居民",
          "跨區協調會使所有地方權責消失",
          "洪水沿同一流域傳遞，上游決策與資訊會改變中下游風險",
        ],
        answerIndex: 3,
        reasons: [
          "行政界線不會阻斷自然水流。",
          "上游雨量、放流與預警會影響下游準備時間。",
          "合作可協調權責，不等於取消地方政府。",
          "共同流域形成跨行政區的風險連結，因此需要資訊與行動協調。",
        ],
        difficulty: "transfer",
        cognitiveProcess: ["spatial-transfer", "intergovernmental-coordination"],
        misconceptionTargets: ["行政界線等同自然系統界線"],
        reviews: [
          "D 正確連結上中下游空間關係與跨政府協調必要性。",
          "A、B 否認流域連動，C 誤把協調理解為權責消失，皆可排除。",
        ],
      }),
    ],
  },
  ISOC_SET_C04: {
    stimulus: {
      id: "ISOC_ST_C04",
      subject: "civics",
      type: "table",
      skillIds: C04_SKILLS,
      authorityRefs: INTEGRATED_AUTHORITY_REFS,
      content: {
        title: "老工業城市減碳方案",
        prompt: "原創情境。該市的重工業聚落形成於 1970 年代。政策門檻為 2030 年排放至少減少 30%、懸浮微粒至少減少 20%，且直接失業不超過 1,000 人。",
        table: {
          caption: "甲乙丙三個減碳方案的環境、價格、就業與轉型基金比較",
          columns: ["方案", "排放減少", "懸浮微粒減少", "電價增加", "直接失業", "轉型基金"],
          rows: [
            ["甲：設備汰換", "18%", "8%", "2%", "120 人", "2 億元"],
            ["乙：立即停產", "45%", "32%", "8%", "2,200 人", "0 元"],
            ["丙：分期退場與再訓練", "35%", "25%", "5%", "500 人", "9 億元"],
          ],
        },
      },
      accessibility: {
        summary: "表格比較三種減碳方案的排放、空污、電價、失業與轉型基金。",
        longDescription: "甲未達兩項環境門檻；乙達環境門檻但失業二千二百人；丙排放減少百分之三十五、懸浮微粒減少百分之二十五、失業五百人，三項門檻皆符合。",
      },
      assets: [],
      questionIds: ["ISOC_C04_Q01", "ISOC_C04_Q02", "ISOC_C04_Q03"],
      provenance: INTEGRATED_PROVENANCE,
    },
    questions: [
      integratedQuestion({
        id: "ISOC_C04_Q01",
        stimulusId: "ISOC_ST_C04",
        skillIds: C04_SKILLS,
        stem: "哪一方案同時通過三項政策門檻？",
        options: ["甲", "乙", "丙", "甲與乙"],
        answerIndex: 2,
        reasons: [
          "甲的排放與懸浮微粒減幅都低於門檻。",
          "乙雖達環境門檻，但直接失業 2,200 人，超過上限。",
          "丙的兩項環境減幅達標，直接失業 500 人也在上限內。",
          "甲未達環境門檻，乙未達就業門檻。",
        ],
        difficulty: "standard",
        cognitiveProcess: ["multi-column-filter", "criteria-application"],
        misconceptionTargets: ["只看單一最高減幅"],
        reviews: [
          "依三項門檻逐列檢查，只有丙全部符合，答案為 C。",
          "甲環境不合、乙就業不合，因此 A、B、D 都不是替代答案。",
        ],
      }),
      integratedQuestion({
        id: "ISOC_C04_Q02",
        stimulusId: "ISOC_ST_C04",
        skillIds: C04_SKILLS,
        stem: "為何不能只因乙案減排最多就判定它最適當？",
        options: [
          "還須評估長期工業聚落的就業依賴、能源價格與轉型成本如何分配",
          "減少污染在公共政策中完全沒有價值",
          "1970 年代形成的產業永遠不得調整",
          "只要設轉型基金，任何方案都必然成功",
        ],
        answerIndex: 0,
        reasons: [
          "老工業城市的空間與歷史依賴，使環境效益必須和就業、價格及轉型負擔一併評估。",
          "材料把排放與懸浮微粒列為必要政策門檻。",
          "歷史形成能解釋轉型條件，不能推出禁止調整。",
          "基金仍須檢查金額、對象、執行與成效。",
        ],
        difficulty: "advanced",
        cognitiveProcess: ["historical-context", "distributional-analysis"],
        misconceptionTargets: ["環境效益最高即政策整體最優"],
        reviews: [
          "A 是唯一把歷史產業依賴、地理環境效益與公民分配正義共同納入的判斷。",
          "B 否定門檻、C 把歷史變成禁令、D 過度保證基金效果，均不成立。",
        ],
      }),
      integratedQuestion({
        id: "ISOC_C04_Q03",
        stimulusId: "ISOC_ST_C04",
        skillIds: C04_SKILLS,
        stem: "市府選擇丙案後，哪一項追蹤方式最能檢驗『轉型公平』？",
        options: [
          "只公布全市平均減排，不區分受影響群體",
          "只計算基金編列金額，不查實際用途",
          "分區公開污染改善，並追蹤失業者再就業、家庭電費負擔與基金受益者",
          "以方案名稱含有『再訓練』直接判定公平",
        ],
        answerIndex: 2,
        reasons: [
          "平均值會遮蔽地區與群體差異。",
          "預算投入不等於實際效果。",
          "分區環境結果與群體就業、負擔、受益資料可直接檢驗成本與利益分配。",
          "政策名稱不是執行成效證據。",
        ],
        difficulty: "transfer",
        cognitiveProcess: ["evaluation-design", "equity-monitoring"],
        misconceptionTargets: ["政策投入或名稱等同公平結果"],
        reviews: [
          "C 同時追蹤環境、就業、家戶成本與基金受益分布，能檢驗轉型公平。",
          "A 隱藏差異、B 只看投入、D 只看名稱，皆無法驗證分配結果。",
        ],
      }),
    ],
  },
};

export const SINGLE_QUESTION_IDS = {
  geography: [
    "GEO_R4_Q_S002_04",
    "GEO_R4_Q_S012_08",
    "GEO_R4_Q_S016_11",
    "GEO_R4_Q_S025_05",
    "GEO_R4_Q_S031_09",
    "GEO_R4_Q_S037_11",
    "GEO_R4_Q_S045_06",
    "GEO_R4_Q_S053_10",
    "GEO_R4_Q_S060_11",
    "GEO_R4_Q_S067_07",
    "GEO_R4_Q_S073_08",
    "GEO_R4_Q_S080_11",
    "GEO_R4_Q_S087_04",
    "GEO_R4_Q_S095_08",
    "GEO_R4_Q_S102_11",
    "GEO_R4_Q_S107_05",
    "GEO_R4_Q_S115_10",
    "GEO_R4_Q_S121_12",
    "GEO_R4_Q_S128_06",
    "GEO_R4_Q_S136_10",
    "GEO_R4_Q_S143_11",
    "GEO_R4_Q_S150_07",
    "GEO_R4_Q_S156_08",
    "GEO_R4_Q_S165_12",
    "GEO_R4_Q_S170_04",
    "GEO_R4_Q_S177_08",
    "GEO_R4_Q_S184_11",
    "GEO_R4_Q_S190_05",
    "GEO_R4_Q_S194_09",
    "GEO_R4_Q_S203_12",
    "GEO_R4_Q_S208_06",
    "GEO_R4_Q_S212_10",
    "GEO_R4_Q_S219_11",
    "GEO_R4_Q_S224_07",
    "GEO_R4_Q_S230_08",
    "GEO_R4_Q_S237_12",
  ],
  history: [
    "HIS_R4_Q007_04",
    "HIS_R4_Q014_08",
    "HIS_R4_Q021_11",
    "HIS_R4_Q028_05",
    "HIS_R4_Q035_09",
    "HIS_R4_Q042_12",
    "HIS_R4_Q049_06",
    "HIS_R4_Q056_10",
    "HIS_R4_Q063_11",
    "HIS_R4_Q070_07",
    "HIS_R4_Q077_08",
    "HIS_R4_Q084_12",
    "HIS_R4_Q091_04",
    "HIS_R4_Q098_08",
    "HIS_R4_Q105_11",
    "HIS_R4_Q112_05",
    "HIS_R4_Q119_09",
    "HIS_R4_Q126_12",
    "HIS_R4_Q133_06",
    "HIS_R4_Q140_10",
    "HIS_R4_Q147_11",
    "HIS_R4_Q154_07",
    "HIS_R4_Q161_08",
    "HIS_R4_Q168_12",
    "HIS_R4_Q174_04",
    "HIS_R4_Q180_08",
    "HIS_R4_Q186_11",
    "HIS_R4_Q192_05",
    "HIS_R4_Q198_09",
    "HIS_R4_Q204_12",
    "HIS_R4_Q210_06",
    "HIS_R4_Q216_10",
    "HIS_R4_Q222_11",
    "HIS_R4_Q228_07",
    "HIS_R4_Q234_08",
    "HIS_R4_Q240_12",
  ],
  civics: [
    "CIV_R4_Q_S007_04",
    "CIV_R4_Q_S014_08",
    "CIV_R4_Q_S021_11",
    "CIV_R4_Q_S028_04",
    "CIV_R4_Q_S035_09",
    "CIV_R4_Q_S042_12",
    "CIV_R4_Q_S049_06",
    "CIV_R4_Q_S056_10",
    "CIV_R4_Q_S063_11",
    "CIV_R4_Q_S070_07",
    "CIV_R4_Q_S077_08",
    "CIV_R4_Q_S084_12",
    "CIV_R4_Q_S091_04",
    "CIV_R4_Q_S098_08",
    "CIV_R4_Q_S105_11",
    "CIV_R4_Q_S112_05",
    "CIV_R4_Q_S119_09",
    "CIV_R4_Q_S126_12",
    "CIV_R4_Q_S133_06",
    "CIV_R4_Q_S140_10",
    "CIV_R4_Q_S147_11",
    "CIV_R4_Q_S154_07",
    "CIV_R4_Q_S161_08",
    "CIV_R4_Q_S168_12",
    "CIV_R4_Q_S174_04",
    "CIV_R4_Q_S180_08",
    "CIV_R4_Q_S186_11",
    "CIV_R4_Q_S192_05",
    "CIV_R4_Q_S198_08",
    "CIV_R4_Q_S204_12",
    "CIV_R4_Q_S210_06",
    "CIV_R4_Q_S216_10",
    "CIV_R4_Q_S222_11",
    "CIV_R4_Q_S228_07",
    "CIV_R4_Q_S234_08",
    "CIV_R4_Q_S240_12",
  ],
};

export const CROSS_DOMAIN_SETS = [
  {
    id: "ISOC_SET_G01",
    subject: "geography",
    title: "土地利用與公共參與",
    domains: ["geography", "civics"],
    skillIds: ["GEO_R4_S148", "CIV_R4_S121"],
    stimulusId: "GEO_R4_ST148",
    questionIds: ["GEO_R4_Q_S148_ST01", "GEO_R4_Q_S148_ST02", "GEO_R4_Q_S148_ST03"],
  },
  {
    id: "ISOC_SET_G02",
    subject: "geography",
    title: "資源流動與環境治理",
    domains: ["geography", "civics"],
    skillIds: ["GEO_R4_S150", "CIV_R4_S239"],
    stimulusId: "GEO_R4_ST150",
    questionIds: ["GEO_R4_Q_S150_ST01", "GEO_R4_Q_S150_ST02", "GEO_R4_Q_S150_ST03"],
  },
  {
    id: "ISOC_SET_G03",
    subject: "geography",
    title: "文化交流與歷史證據",
    domains: ["geography", "history"],
    skillIds: ["GEO_R4_S161", "HIS_R4_S105"],
    stimulusId: "GEO_R4_ST161",
    questionIds: ["GEO_R4_Q_S161_ST01", "GEO_R4_Q_S161_ST02", "GEO_R4_Q_S161_ST03"],
  },
  {
    id: "ISOC_SET_G04",
    subject: "geography",
    title: "工業化、觀光與都市發展",
    domains: ["geography", "history", "civics"],
    skillIds: ["GEO_R4_S166", "HIS_R4_S189", "CIV_R4_S191"],
    stimulusId: "GEO_R4_ST166",
    questionIds: ["GEO_R4_Q_S166_ST01", "GEO_R4_Q_S166_ST02", "GEO_R4_Q_S166_ST03"],
  },
  {
    id: "ISOC_SET_H01",
    subject: "history",
    title: "工業成長、遷移與環境影響",
    domains: ["history", "geography", "civics"],
    skillIds: ["HIS_R4_S073", "GEO_R4_S075", "CIV_R4_S173"],
    stimulusId: "HIS_R4_ST073",
    questionIds: ["HIS_R4_SQ073_01", "HIS_R4_SQ073_02", "HIS_R4_SQ073_03"],
  },
  {
    id: "ISOC_SET_H02",
    subject: "history",
    title: "民主化進程與制度變遷",
    domains: ["history", "civics"],
    skillIds: ["HIS_R4_S078", "CIV_R4_S221"],
    stimulusId: "HIS_R4_ST078",
    questionIds: ["HIS_R4_SQ078_01", "HIS_R4_SQ078_02", "HIS_R4_SQ078_03"],
  },
  {
    id: "ISOC_SET_H03",
    subject: "history",
    title: "民主運作與媒體查核",
    domains: ["history", "civics"],
    skillIds: ["HIS_R4_S084", "CIV_R4_S112"],
    stimulusId: "HIS_R4_ST084",
    questionIds: ["HIS_R4_SQ084_01", "HIS_R4_SQ084_02", "HIS_R4_SQ084_03"],
  },
  {
    id: "ISOC_SET_H04",
    subject: "history",
    title: "全球交換與人口變動",
    domains: ["history", "geography", "civics"],
    skillIds: ["HIS_R4_S177", "GEO_R4_S211", "CIV_R4_S227"],
    stimulusId: "HIS_R4_ST177",
    questionIds: ["HIS_R4_SQ177_01", "HIS_R4_SQ177_02", "HIS_R4_SQ177_03"],
  },
  {
    id: "ISOC_SET_C01",
    subject: "civics",
    title: "離岸風電選址與漁業參與",
    domains: ["civics", "geography"],
    skillIds: C01_SKILLS,
    ...INTEGRATED_CIVICS_CONTENT.ISOC_SET_C01,
  },
  {
    id: "ISOC_SET_C02",
    subject: "civics",
    title: "港口供應鏈與產業韌性",
    domains: ["civics", "geography", "history"],
    skillIds: C02_SKILLS,
    ...INTEGRATED_CIVICS_CONTENT.ISOC_SET_C02,
  },
  {
    id: "ISOC_SET_C03",
    subject: "civics",
    title: "流域豪雨避難與資源分配",
    domains: ["civics", "geography"],
    skillIds: C03_SKILLS,
    ...INTEGRATED_CIVICS_CONTENT.ISOC_SET_C03,
  },
  {
    id: "ISOC_SET_C04",
    subject: "civics",
    title: "工業區減碳與轉型公平",
    domains: ["civics", "geography", "history"],
    skillIds: C04_SKILLS,
    ...INTEGRATED_CIVICS_CONTENT.ISOC_SET_C04,
  },
];
